/*
* Licensee agrees that the example code provided to Licensee has been developed and released by Bosch solely as an example to be used as a potential reference for application development by Licensee. 
* Fitness and suitability of the example code for any use within application developed by Licensee need to be verified by Licensee on its own authority by taking appropriate state of the art actions and measures (e.g. by means of quality assurance measures).
* Licensee shall be responsible for conducting the development of its applications as well as integration of parts of the example code into such applications, taking into account the state of the art of technology and any statutory regulations and provisions applicable for such applications. Compliance with the functional system requirements and testing there of (including validation of information/data security aspects and functional safety) and release shall be solely incumbent upon Licensee. 
* For the avoidance of doubt, Licensee shall be responsible and fully liable for the applications and any distribution of such applications into the market.
* 
* 
* Redistribution and use in source and binary forms, with or without 
* modification, are permitted provided that the following conditions are 
* met:
* 
*     (1) Redistributions of source code must retain the above copyright
*     notice, this list of conditions and the following disclaimer. 
* 
*     (2) Redistributions in binary form must reproduce the above copyright
*     notice, this list of conditions and the following disclaimer in
*     the documentation and/or other materials provided with the
*     distribution.  
*     
*     (3)The name of the author may not be used to
*     endorse or promote products derived from this software without
*     specific prior written permission.
* 
*  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR 
*  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
*  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
*  DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
*  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
*  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
*  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
*  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
*  STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
*  IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
*  POSSIBILITY OF SUCH DAMAGE.
*/
/*----------------------------------------------------------------------------*/

/**
 * @file
 *
 * @brief CA Certificate in PEM (string) format , generated by using openssl commands to the particular URL (test.mosquitto.org)
 *
 */

#define SERVER_CA \
"-----BEGIN CERTIFICATE-----\n" \
"MIIDyzCCArOgAwIBAgIJAKa0PrcArlYlMA0GCSqGSIb3DQEBBQUAMHwxCzAJBgNV\n" \
"BAYTAmluMQswCQYDVQQIDAJ0bjEMMAoGA1UEBwwDY2JlMQ4wDAYDVQQKDAVib3Nj\n" \
"aDENMAsGA1UECwwEcmJlaTEWMBQGA1UEAwwNMTkyLjE2OC4xLjE0MDEbMBkGCSqG\n" \
"SIb3DQEJARYMcHJpeWdvdmluZDE3MB4XDTE5MDEyOTExNDAwN1oXDTI0MDEyOTEx\n" \
"NDAwN1owfDELMAkGA1UEBhMCaW4xCzAJBgNVBAgMAnRuMQwwCgYDVQQHDANjYmUx\n" \
"DjAMBgNVBAoMBWJvc2NoMQ0wCwYDVQQLDARyYmVpMRYwFAYDVQQDDA0xOTIuMTY4\n" \
"LjEuMTQwMRswGQYJKoZIhvcNAQkBFgxwcml5Z292aW5kMTcwggEiMA0GCSqGSIb3\n" \
"DQEBAQUAA4IBDwAwggEKAoIBAQC7jSfzNhSztpOMNN9U+Vxaxefg/XyJm0f+byk4\n" \
"ZdOnXUiqc8ZPYKGjm9bwF+5/3oLi/yZ8rD3nlzR4kp8RQA836a8t3Bw7HOoev385\n" \
"mbw8vkK+mYCs+C+zSHg1lPC46+/ALpb4nMpeKkQMuhTDidb5hEzBM0WiP1Fx/ini\n" \
"tcyExDLrIrABlUv2Yxu1ayET4dM2E16YZAfxD+V0ldKaJA8Nq2KopdYd/Y9q6VTW\n" \
"9YB+vzTZNAp9MvAuEaqrlDQ72YW8RBO0CCEJhj281Y0m32urELL9aGaNa+XWZ9On\n" \
"nOU94mA1YDSOFbQi2BljOytliVMxsOlKmcu1fx0VUnX0OPDHAgMBAAGjUDBOMB0G\n" \
"A1UdDgQWBBTvtDZQcTkA8BgbWtoZW43NThI+TzAfBgNVHSMEGDAWgBTvtDZQcTkA\n" \
"8BgbWtoZW43NThI+TzAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4IBAQBm\n" \
"yQFU0Mbe6lgrSsaxhHs/UlBlpnB79qmi3mMTvqGe94dN+9pvPiP23xeWdJqoEPRC\n" \
"7alGPbewzMKQYdGyKTIauzAAn7bZlm+SPQd+7jkuOxvwvqgxfWHBvhk454QgVWsE\n" \
"5z1KKCL3IkW53UXr6Rp2b3qlACPMvh2/k20k0KRCvb/pqNEsDvhpOpQg35LxXv2B\n" \
"Q5Lc3+ajKulir83VauEkn3gkpLtrewCVpd1MdBKhmefcRw/42l0TGBKZ+0eG8tKw\n" \
"HtwEXat+ODhVTg3kNNkQNgDrTwkNpqqj0pzrkhTOKD9uvaFdbOKPeFv2I42YVNVo\n" \
"fsMaaPma8syqTd/wszAV\n" \
"-----END CERTIFICATE-----\n"
