################### Common Feature Makefile for EFM32 ##################################

# At the time the below variables are defined (read-in phase),
# source files are not yet necessarly declared. Those could get
# defined later (by the target platform make file for instance). 
# We therefore have to enable the .SECONDEXPANSION: feature of
# make. This will tell make to expand variables escaped with an
# additional "$" during the target-run phase.
.SECONDEXPANSION:

#This macro is used to select the features needed by application
#ALL    ----> All the features will be enabled
#NONE   ----> All the features will be disabled
#SELECT ----> Application has to select the required features
XDK_FEATURE_SET ?='ALL'

ifeq ('ALL',$(XDK_FEATURE_SET))
XDK_CONNECTIVITY_BLE =1
XDK_CONNECTIVITY_HTTPRESTCLIENT =1
XDK_CONNECTIVITY_LED =1
XDK_CONNECTIVITY_LORA =1
XDK_CONNECTIVITY_LWM2M =1
XDK_CONNECTIVITY_MQTT =1
XDK_CONNECTIVITY_UDP =1
XDK_CONNECTIVITY_WLAN =1

XDK_SENSOR_SENSOR =1
XDK_SENSOR_BUTTON =1
XDK_SENSOR_VIRTUALSENSOR =1
XDK_SENSOR_EXTERNALSENSOR =1

XDK_UTILITY_SERVALPAL =1
XDK_UTILITY_STORAGE =1
XDK_UTILITY_SNTP =1
else ifeq ('NONE',$(XDK_FEATURE_SET))
XDK_CONNECTIVITY_BLE =0
XDK_CONNECTIVITY_HTTPRESTCLIENT =0
XDK_CONNECTIVITY_LED =0
XDK_CONNECTIVITY_LORA =0
XDK_CONNECTIVITY_LWM2M =0
XDK_CONNECTIVITY_MQTT =0
XDK_CONNECTIVITY_UDP =0
XDK_CONNECTIVITY_WLAN =0

XDK_SENSOR_SENSOR =0
XDK_SENSOR_BUTTON =0
XDK_SENSOR_VIRTUALSENSOR =0
XDK_SENSOR_EXTERNALSENSOR =0

XDK_UTILITY_SERVALPAL =0
XDK_UTILITY_STORAGE =0
XDK_UTILITY_SNTP =0
else ifeq ('SELECT',$(XDK_FEATURE_SET)) #Selection of features has to be done from application
XDK_CONNECTIVITY_BLE ?=0
XDK_CONNECTIVITY_HTTPRESTCLIENT?=0
XDK_CONNECTIVITY_LED?=0
XDK_CONNECTIVITY_LORA?=0
XDK_CONNECTIVITY_LWM2M?=0
XDK_CONNECTIVITY_MQTT?=0
XDK_CONNECTIVITY_UDP?=0
XDK_CONNECTIVITY_WLAN?=0

XDK_SENSOR_SENSOR?=0
XDK_SENSOR_BUTTON?=0
XDK_SENSOR_VIRTUALSENSOR?=0
XDK_SENSOR_EXTERNALSENSOR?=0

XDK_UTILITY_SERVALPAL?=0
XDK_UTILITY_STORAGE ?=0
XDK_UTILITY_SNTP?=0
else
$(info Enabling all the features as XDK_FEATURE_SET doesn't match any case)
XDK_CONNECTIVITY_BLE =1
XDK_CONNECTIVITY_HTTPRESTCLIENT =1
XDK_CONNECTIVITY_LED =1
XDK_CONNECTIVITY_LORA =1
XDK_CONNECTIVITY_LWM2M =1
XDK_CONNECTIVITY_MQTT =1
XDK_CONNECTIVITY_UDP =1
XDK_CONNECTIVITY_WLAN =1

XDK_SENSOR_SENSOR =1
XDK_SENSOR_BUTTON =1
XDK_SENSOR_VIRTUALSENSOR =1
XDK_SENSOR_EXTERNALSENSOR =1

XDK_UTILITY_SERVALPAL =1
XDK_UTILITY_STORAGE =1
XDK_UTILITY_SNTP =1
endif

XDK_CFLAGS_COMMON += \
	-D XDK_CONNECTIVITY_BLE=$(XDK_CONNECTIVITY_BLE) \
	-D XDK_CONNECTIVITY_HTTPRESTCLIENT=$(XDK_CONNECTIVITY_HTTPRESTCLIENT) \
	-D XDK_CONNECTIVITY_LED=$(XDK_CONNECTIVITY_LED) \
	-D XDK_CONNECTIVITY_LORA=$(XDK_CONNECTIVITY_LORA) \
	-D XDK_CONNECTIVITY_LWM2M=$(XDK_CONNECTIVITY_LWM2M) \
	-D XDK_CONNECTIVITY_MQTT=$(XDK_CONNECTIVITY_MQTT) \
	-D XDK_CONNECTIVITY_UDP=$(XDK_CONNECTIVITY_UDP) \
	-D XDK_CONNECTIVITY_WLAN=$(XDK_CONNECTIVITY_WLAN) \
	-D XDK_SENSOR_SENSOR=$(XDK_SENSOR_SENSOR) \
	-D XDK_SENSOR_BUTTON=$(XDK_SENSOR_BUTTON) \
	-D XDK_SENSOR_EXTERNALSENSOR=$(XDK_SENSOR_EXTERNALSENSOR) \
	-D XDK_SENSOR_VIRTUALSENSOR=$(XDK_SENSOR_VIRTUALSENSOR) \
	-D XDK_UTILITY_SERVALPAL=$(XDK_UTILITY_SERVALPAL) \
	-D XDK_UTILITY_STORAGE=$(XDK_UTILITY_STORAGE) \
	-D XDK_UTILITY_SNTP=$(XDK_UTILITY_SNTP) \
	
	