Accelerometer.c
BCDS_MODULE_ID
BMA_INTERRUPT_CHANNEL_1
Referenced by bmaIsrCallback.
BMA_INTERRUPT_CHANNEL_2
Referenced by bmaIsrCallback.
Accelerometer_HandlePtr_T Bma280Handle
uint8_t bmaRangeValue
Referenced by Accelerometer_setRange, Accelerometer_readXyzGValue.
uint8_t bmiRangeValue
Referenced by Accelerometer_setRange, Accelerometer_readXyzGValue.
const uint8_t bwLookUpTable[ACCELEROMETER_BANDWIDTH_OUT_OF_RANGE][ACCELEROMETER_BANDWIDTH_OUT_OF_RANGE]
Referenced by Accelerometer_setBandwidth, Accelerometer_getBandwidth.
const uint8_t getmodeLookUpTable[ACCELEROMETER_POWERMODE_OUT_OF_RANGE][ACCELEROMETER_POWERMODE_OUT_OF_RANGE]
Referenced by Accelerometer_getMode.
const uint8_t modeLookUpTable[ACCELEROMETER_POWERMODE_OUT_OF_RANGE][ACCELEROMETER_POWERMODE_OUT_OF_RANGE]
Referenced by Accelerometer_setMode, Accelerometer_getMode.
const uint8_t rangeLookUpTable[ACCELEROMETER_RANGE_OUT_OF_BOUND][ACCELEROMETER_RANGE_OUT_OF_BOUND]
Referenced by Accelerometer_setRange, Accelerometer_getRange.
const uint8_t rangeValueLookUpTable[ACCELEROMETER_RANGE_OUT_OF_BOUND][ACCELEROMETER_RANGE_OUT_OF_BOUND]
Referenced by Accelerometer_setRange.
const uint8_t sleepDurationLookUpTable[ACCELEROMETER_SLEEP_DURATION_OUT_OF_RANGE][ACCELEROMETER_SLEEP_DURATION_OUT_OF_RANGE]
Referenced by Accelerometer_setSleepDuration, Accelerometer_getSleepDuration.
Retcode_T Accelerometer_configInterrupt(Accelerometer_HandlePtr_T handle, Accelerometer_InterruptChannel_T channel, Accelerometer_InterruptType_T interruptType, void *InterruptTypeParameters)
Configures the accelerometer Interrupt referenced by the passed handle.
handle Handle to the accelerometer object channel Channel on which the interrupt line connected to interruptType Type of interrupt requested for the specified interrupt channel InterruptTypeParameters Parameter related to interrupted type. Note it is void pointer and hence the user has to give corresponding parameters for the selected interrupt y RETCODE_SUCCESS Interrupt Configuration success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle or invalid interrupt type Accelerometer_InterruptType_E. RETCODE_NOT_SUPPORTED In case of not supported. In case of other failures refer Bma280Utils_configInterrupt API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, NULL, ACCELEROMETER_INVALID_INTERRUPT_CHANNEL, ACCELEROMETER_INVALID_INTERRUPT, Accelerometer_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Accelerometer_Handle_S::SensorInformation, Acceleromter_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Bma280Utils_ConfigInterrupt_S::interruptType, Bma280Utils_ConfigInterrupt_S::interruptChannel, Bma280Utils_ConfigInterrupt_S::configInterrupt, Acceleromter_SensorInfo_S::sensorID, ACCELEROMETER_BMI160, RETCODE_NOT_SUPPORTED, ACCELEROMETER_BMA280, ACCELEROMETER_BMA280_SLOPE_INTERRUPT, Accelerometer_ConfigSlopeIntr_S::slopeEnableX, Accelerometer_ConfigSlopeIntr_S::slopeEnableY, Accelerometer_ConfigSlopeIntr_S::slopeEnableZ, Accelerometer_ConfigSlopeIntr_S::slopeDuration, ACCELEROMETER_INVALID_SLOPE_DURATION, Bma280Utils_configInterrupt, ACCELEROMETER_BMA280_NEW_DATA_INTERRUPT, RETCODE_OK, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T Accelerometer_deInit(Accelerometer_HandlePtr_T handle)
DeInitializes the accelerometer referenced by the passed handle.
handle Handle to the accelerometer object RETCODE_SUCCESS Accelerometer De-initialization success. RETCODE_INVALID_PARAM In case of invalid sensor handle. In case of any other error refer Bma280Utils_uninitialize or Bmi160Utils_uninitialize error codes. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Accelerometer_Handle_S::SensorInformation, Acceleromter_SensorInfo_S::initializationStatus, RETCODE_OK, Acceleromter_SensorInfo_S::sensorID, ACCELEROMETER_BMA280, Bma280Utils_uninitialize, Accelerometer_Handle_S::SensorPtr, ACCELEROMETER_BMI160, Bmi160Utils_uninitialize, Retcode_GetPackage, PACKAGE_ID_DEFAULT, RETCODE_SEVERITY_ERROR.
Referenced by LWM2MSensorDeviceAccelerometer_Activate.
Retcode_T Accelerometer_disableInterrupt(Accelerometer_HandlePtr_T handle, Accelerometer_InterruptChannel_T channel, Accelerometer_InterruptType_T interruptType)
Disable Interrupt type on the specified channel.
handle Handle to the accelerometer object channel Channel on which the specified interrupt type to be disabled interruptType Type of interrupt to be disabled RETCODE_SUCCESS Disabling Interrupt success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle or invalid interrupt type Accelerometer_InterruptType_E. RETCODE_NOT_SUPPORTED In case of not supported. In case of other failures refer Bma280Utils_disableInterrupt. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, NULL, ACCELEROMETER_INVALID_INTERRUPT_CHANNEL, ACCELEROMETER_INVALID_INTERRUPT, Accelerometer_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Accelerometer_Handle_S::SensorInformation, Acceleromter_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Acceleromter_SensorInfo_S::sensorID, ACCELEROMETER_BMA280, Bma280Utils_disableInterrupt, ACCELEROMETER_BMI160, RETCODE_NOT_SUPPORTED, RETCODE_OK, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T Accelerometer_getBandwidth(Accelerometer_HandlePtr_T handle, Accelerometer_BandwidthPtr_T bandwidth)
Reads the bandwidth for the accelerometer referenced by the passed handle.
handle Handle to the accelerometer object bandwidth Last configured bandwidth of accelerometer sensor RETCODE_SUCCESS Getting Bandwidth success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of getting bandwidth values other than Accelerometer_Bandwidth_E. In case of other failures refer bma2x2LibErrorMapping or bmi160LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References GET_MAPPING_ERROR, RETCODE_FAILURE, BMA2x2_RETURN_FUNCTION_TYPE, E_OUT_OF_RANGE, BMI160_RETURN_FUNCTION_TYPE, E_BMI160_OUT_OF_RANGE, ACCELEROMETER_BANDWIDTH_OUT_OF_RANGE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, Accelerometer_Handle_S::SensorInformation, Acceleromter_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Acceleromter_SensorInfo_S::sensorID, ACCELEROMETER_BMA280, bma2x2_get_bw, bma2x2LibErrorMapping, RETCODE_OK, mappingEnumForGetFunctions, ACCELEROMETER_BMA280_BANDWIDTH_7_81HZ, ACCELEROMETER_BMA280_BANDWIDTH_500HZ, bwLookUpTable, RETCODE_NOT_SUPPORTED, ACCELEROMETER_BMI160, bmi160_get_accel_output_data_rate, bmi160LibErrorMapping, ACCELEROMETER_BMI160_BANDWIDTH_0_78HZ, ACCELEROMETER_BMI160_BANDWIDTH_200HZ, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T Accelerometer_getMode(Accelerometer_HandlePtr_T handle, Accelerometer_PowermodePtr_T powermode)
get the powermode for the accelerometer referenced by the passed handle.
handle Handle to the accelerometer object powermode Last configured power mode of accelerometer sensor RETCODE_SUCCESS Get mode success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of getting mode values other than Accelerometer_Powermode_E. In case of other failures refer bma2x2LibErrorMapping or bmi160LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References GET_MAPPING_ERROR, RETCODE_FAILURE, BMA2x2_RETURN_FUNCTION_TYPE, E_OUT_OF_RANGE, BMI160_RETURN_FUNCTION_TYPE, E_BMI160_OUT_OF_RANGE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Accelerometer_Handle_S::SensorInformation, Acceleromter_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Acceleromter_SensorInfo_S::sensorID, ACCELEROMETER_BMA280, bma2x2_get_power_mode, bma2x2LibErrorMapping, RETCODE_OK, mappingEnumForGetFunctions, ACCELEROMETER_BMA280_POWERMODE_NORMAL, ACCELEROMETER_BMA280_POWERMODE_STANDBY, modeLookUpTable, RETCODE_NOT_SUPPORTED, ACCELEROMETER_BMI160, bmi160_get_accel_power_mode_stat, bmi160LibErrorMapping, ACCELEROMETER_BMI160_POWERMODE_NORMAL, ACCELEROMETER_BMI160_POWERMODE_SUSPEND, getmodeLookUpTable, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T Accelerometer_getRange(Accelerometer_HandlePtr_T handle, Accelerometer_RangePtr_T range)
Reads the Range for the accelerometer referenced by the passed handle.
handle Handle to the accelerometer object range Last configured range of accelerometer sensor RETCODE_SUCCESS get Range success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of getting range values other than Accelerometer_Range_E. In case of other failures refer bma2x2LibErrorMapping or bmi160LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References GET_MAPPING_ERROR, BMA2x2_RETURN_FUNCTION_TYPE, E_OUT_OF_RANGE, BMI160_RETURN_FUNCTION_TYPE, E_BMI160_OUT_OF_RANGE, RETCODE_FAILURE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, Accelerometer_Handle_S::SensorInformation, Acceleromter_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Acceleromter_SensorInfo_S::sensorID, ACCELEROMETER_BMA280, bma2x2_get_range, bma2x2LibErrorMapping, RETCODE_OK, mappingEnumForGetFunctions, ACCELEROMETER_BMA280_RANGE_2G, ACCELEROMETER_BMA280_RANGE_16G, rangeLookUpTable, RETCODE_NOT_SUPPORTED, ACCELEROMETER_BMI160, bmi160_get_accel_range, bmi160LibErrorMapping, ACCELEROMETER_BMI160_RANGE_2G, ACCELEROMETER_BMI160_RANGE_16G, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Referenced by LWM2MSensorDeviceAccelerometer_Activate.
Retcode_T Accelerometer_getSleepDuration(Accelerometer_HandlePtr_T handle, Accelerometer_SleepDurationPtr_T lowPowerModeSleepDuration)
Reads the last set sleep duration of accelerometer referenced by the passed handle.
handle Handle to the accelerometer object range Last configured sleep duration of accelerometer sensor RETCODE_SUCCESS Get Sleep Duration success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of getting sleep duration values other than Accelerometer_SleepDuration_E. In case of other failures refer bma2x2LibErrorMapping or bmi160LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References GET_MAPPING_ERROR, RETCODE_FAILURE, BMA2x2_RETURN_FUNCTION_TYPE, E_OUT_OF_RANGE, ACCELEROMETER_SLEEP_DURATION_OUT_OF_RANGE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, Accelerometer_Handle_S::SensorInformation, Acceleromter_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Acceleromter_SensorInfo_S::sensorID, ACCELEROMETER_BMA280, bma2x2_get_sleep_durn, bma2x2LibErrorMapping, RETCODE_OK, mappingEnumForGetFunctions, ACCELEROMETER_BMA280_SLEEP_DURATION_0_5MS, ACCELEROMETER_BMA280_SLEEP_DURATION_1S, sleepDurationLookUpTable, RETCODE_NOT_SUPPORTED, ACCELEROMETER_BMI160, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T Accelerometer_init(Accelerometer_HandlePtr_T handle)
Initializes the accelerometer referenced by the passed handle.
handle Handle to the accelerometer object RETCODE_SUCCESS Accelerometer initialization success. RETCODE_INVALID_PARAM In case of invalid sensor handle. In case of any other error refer Bma280Utils_initialize or Bmi160Utils_initialize error codes. This function needs to be called before calling any other accelerometer API. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, NULL, Accelerometer_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, Accelerometer_Handle_S::SensorInformation, Acceleromter_SensorInfo_S::initializationStatus, RETCODE_OK, Acceleromter_SensorInfo_S::sensorID, ACCELEROMETER_BMA280, Bma280Utils_Info_S::ISRCallback, bmaIsrCallback, Bma280Utils_initialize, INIT_DONE, INIT_NOT_DONE, ACCELEROMETER_BMI160, Bmi160Utils_Info_S::ISRCallback, Bmi160Utils_initialize, Retcode_GetCode, RETCODE_DOPPLE_INITIALIZATION, Retcode_GetPackage, PACKAGE_ID_DEFAULT, RETCODE_SEVERITY_ERROR.
Referenced by LWM2MSensorDeviceAccelerometer_Activate.
Retcode_T Accelerometer_readXyzGValue(Accelerometer_HandlePtr_T handle, Accelerometer_XyzDataPtr_T accelData)
Reads an milli Gravity values from the accelerometer referenced by the passed handle for the UG correction.
handle Handle to the accelerometer object value Parameter in which the accelerometer milli G value of XYZ gets collected RETCODE_SUCCESS Reading accelerometer xyzGvalue success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. In case of other failures refer bma2x2LibErrorMapping or bmi160LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, BMA2x2_RETURN_FUNCTION_TYPE, E_OUT_OF_RANGE, BMI160_RETURN_FUNCTION_TYPE, E_BMI160_OUT_OF_RANGE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Accelerometer_Handle_S::SensorInformation, Acceleromter_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Acceleromter_SensorInfo_S::sensorID, ACCELEROMETER_BMA280, bma2x2_read_accel_xyz, bma2x2LibErrorMapping, RETCODE_OK, bma2x2_accel_data::x, ACCEL_CONV_G_MG, bmaRangeValue, AxisRemap_Data_S::x, BMA2X2_ONEBITRESOLUTION, bma2x2_accel_data::y, AxisRemap_Data_S::y, bma2x2_accel_data::z, AxisRemap_Data_S::z, Bma280Utils_remapAxis, Accelerometer_Handle_S::SensorPtr, Accelerometer_XyzData_S::xAxisData, Accelerometer_XyzData_S::yAxisData, Accelerometer_XyzData_S::zAxisData, ACCELEROMETER_BMI160, bmi160_read_accel_xyz, bmi160LibErrorMapping, bmiRangeValue, bmi160_accel_t::x, BMI160_ONEBITRESOLUTION, bmi160_accel_t::y, bmi160_accel_t::z, Bmi160Utils_remapAxis, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Referenced by LWM2MSensorDeviceAccelerometer_Update.
Retcode_T Accelerometer_readXyzLsbValue(Accelerometer_HandlePtr_T handle, Accelerometer_XyzDataPtr_T accelData)
Reads an LSB xyz value from the accelerometer referenced by the passed handle.
handle Handle to the accelerometer object value Parameter in which the accelerometer LSB value of XYZ gets collected RETCODE_SUCCESS Reading accelerometer xyzLsb value success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. In case of other failures refer bma2x2LibErrorMapping or bmi160LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, BMA2x2_RETURN_FUNCTION_TYPE, E_OUT_OF_RANGE, BMI160_RETURN_FUNCTION_TYPE, E_BMI160_OUT_OF_RANGE, NULL, Accelerometer_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Accelerometer_Handle_S::SensorInformation, Acceleromter_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Acceleromter_SensorInfo_S::sensorID, ACCELEROMETER_BMA280, bma2x2_read_accel_xyz, bma2x2LibErrorMapping, RETCODE_OK, AxisRemap_Data_S::x, bma2x2_accel_data::x, AxisRemap_Data_S::y, bma2x2_accel_data::y, AxisRemap_Data_S::z, bma2x2_accel_data::z, Bma280Utils_remapAxis, Accelerometer_XyzData_S::xAxisData, Accelerometer_XyzData_S::yAxisData, Accelerometer_XyzData_S::zAxisData, ACCELEROMETER_BMI160, bmi160_read_accel_xyz, bmi160LibErrorMapping, bmi160_accel_t::x, bmi160_accel_t::y, bmi160_accel_t::z, Bmi160Utils_remapAxis, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T Accelerometer_regDeferredCallback(Accelerometer_HandlePtr_T handle, Accelerometer_InterruptChannel_T intChannel, accelDeferredTimeCallback deferredCallback)
Register deferred user callback function on the specified channel to indicate user that interrupt has occurred not immediately but at deferred context of RTOS.
handle Handle to the accelerometer object intChannel Channel on which the deferred callback to be mapped accelDeferredTimeCallback user function pointer to be registered for deferred callback RETCODE_SUCCESS Registering deferred callback is success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle or invalid channel Accelerometer_InterruptChannel_E or NULL callback. RETCODE_NOT_SUPPORTED In case of not supported. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_OK, NULL, ACCELEROMETER_INVALID_INTERRUPT_CHANNEL, Accelerometer_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Accelerometer_Handle_S::SensorInformation, Acceleromter_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Acceleromter_SensorInfo_S::sensorID, ACCELEROMETER_BMA280, ACCELEROMETER_BMA280_INTERRUPT_CHANNEL1, Accelerometer_Handle_S::IntChannel1, Accelerometer_InterruptCallback_S::deferredCallback, Accelerometer_InterruptCallback_S::rtCallback, ACCELEROMETER_BMA280_INTERRUPT_CHANNEL2, Accelerometer_Handle_S::IntChannel2, ACCELEROMETER_BMI160, RETCODE_NOT_SUPPORTED, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T Accelerometer_regRealTimeCallback(Accelerometer_HandlePtr_T handle, Accelerometer_InterruptChannel_T intChannel, accelRealTimeCallback realTimeCallback)
Register real time user callback function on the specified channel to indicate user that interrupt has occurred.
handle Handle to the accelerometer object intChannel Channel on which the real time callback to be mapped accelRealTimeCallback user function pointer to be registered for real time callback RETCODE_SUCCESS Registering real time callback is success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle or invalid channel Accelerometer_InterruptChannel_E or NULL callback. RETCODE_NOT_SUPPORTED In case of not supported. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_OK, NULL, Accelerometer_Handle_S::SensorPtr, ACCELEROMETER_INVALID_INTERRUPT_CHANNEL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Accelerometer_Handle_S::SensorInformation, Acceleromter_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Acceleromter_SensorInfo_S::sensorID, ACCELEROMETER_BMA280, ACCELEROMETER_BMA280_INTERRUPT_CHANNEL1, Accelerometer_Handle_S::IntChannel1, Accelerometer_InterruptCallback_S::rtCallback, Accelerometer_InterruptCallback_S::deferredCallback, ACCELEROMETER_BMA280_INTERRUPT_CHANNEL2, Accelerometer_Handle_S::IntChannel2, ACCELEROMETER_BMI160, RETCODE_NOT_SUPPORTED, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T Accelerometer_setBandwidth(Accelerometer_HandlePtr_T handle, Accelerometer_Bandwidth_T bandwidth)
Sets the bandwidth for the accelerometer referenced by the passed handle.
handle Handle to the accelerometer object bandwidth The desired bandwidth that needs to be set, BMA280 supports upto 500Hz, Normally the sampling rate of the filtered data depends on the selected filter bandwidth and is always twice the selected bandwidth ( BW = ODR/2). RETCODE_SUCCESS Bandwidth setting success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of setting bandwidth values other than Accelerometer_Bandwidth_E. In case of other failures refer bma2x2LibErrorMapping or bmi160LibErrorMapping API's. Bandwidth will be depends on the ODR as per the following Table: Bandwidth Update Time 7.81 HZ 64 ms 15.63 HZ 32 ms 31.25 HZ 16 ms 62.5 HZ 8 ms 125 HZ 4 ms 250 HZ 2 ms 500 HZ 1 ms The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, BMA2x2_RETURN_FUNCTION_TYPE, E_OUT_OF_RANGE, BMI160_RETURN_FUNCTION_TYPE, E_BMI160_OUT_OF_RANGE, NULL, Accelerometer_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, ACCELEROMETER_BANDWIDTH_OUT_OF_RANGE, RETCODE_SEVERITY_ERROR, Accelerometer_Handle_S::SensorInformation, Acceleromter_SensorInfo_S::initializationStatus, RETCODE_UNINITIALIZED, Acceleromter_SensorInfo_S::sensorID, ACCELEROMETER_BMA280, ACCELEROMETER_BMA280_BANDWIDTH_500HZ, RETCODE_NOT_SUPPORTED, bma2x2_set_high_bw, BMA2X2_FILTERED_LOW_BANDWIDTH, bma2x2_set_bw, bwLookUpTable, bma2x2LibErrorMapping, ACCELEROMETER_BMI160, ACCELEROMETER_BMI160_BANDWIDTH_0_78HZ, ACCELEROMETER_BMI160_BANDWIDTH_12_5HZ, bmi160_set_accel_under_sampling_parameter, ENABLE_UNDERSAMPLING, SUCCESS, bmi160_set_accel_output_data_rate, BMI160_ACCEL_RES_AVG4, bmi160_set_accel_bw, BMI160_ACCEL_NORMAL_AVG4, bmi160LibErrorMapping, ACCELEROMETER_BMI160_BANDWIDTH_200HZ, DISABLE_UNDERSAMPLING, RETCODE_OK, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T Accelerometer_setMode(Accelerometer_HandlePtr_T handle, Accelerometer_Powermode_T powermode)
Sets the powermode for the accelerometer referenced by the passed handle.
handle Handle to the accelerometer object powermode The desired power mode that needs to be set RETCODE_SUCCESS Set mode success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of setting mode values other than Accelerometer_Powermode_E. In case of other failures refer bma2x2LibErrorMapping or bmi160LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, BMA2x2_RETURN_FUNCTION_TYPE, E_OUT_OF_RANGE, BMI160_RETURN_FUNCTION_TYPE, E_BMI160_OUT_OF_RANGE, NULL, Accelerometer_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, ACCELEROMETER_POWERMODE_OUT_OF_RANGE, RETCODE_SEVERITY_ERROR, Accelerometer_Handle_S::SensorInformation, Acceleromter_SensorInfo_S::initializationStatus, RETCODE_UNINITIALIZED, Acceleromter_SensorInfo_S::sensorID, ACCELEROMETER_BMA280, ACCELEROMETER_BMA280_POWERMODE_STANDBY, RETCODE_NOT_SUPPORTED, bma2x2_set_power_mode, modeLookUpTable, bma2x2LibErrorMapping, ACCELEROMETER_BMI160, ACCELEROMETER_BMI160_POWERMODE_NORMAL, ACCELEROMETER_BMI160_POWERMODE_SUSPEND, bmi160_set_command_register, bmi160LibErrorMapping, RETCODE_OK, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T Accelerometer_setRange(Accelerometer_HandlePtr_T handle, Accelerometer_Range_T range)
Sets the Range for the accelerometer referenced by the passed handle.
handle Handle to the accelerometer object range The desired range that needs to be set RETCODE_SUCCESS Set Range success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of setting range values other than Accelerometer_Range_E. In case of other failures refer bma2x2LibErrorMapping or bmi160LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, BMA2x2_RETURN_FUNCTION_TYPE, E_OUT_OF_RANGE, BMI160_RETURN_FUNCTION_TYPE, E_BMI160_OUT_OF_RANGE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, ACCELEROMETER_RANGE_OUT_OF_BOUND, RETCODE_SEVERITY_ERROR, Accelerometer_Handle_S::SensorInformation, Acceleromter_SensorInfo_S::initializationStatus, RETCODE_UNINITIALIZED, Acceleromter_SensorInfo_S::sensorID, ACCELEROMETER_BMA280, ACCELEROMETER_BMA280_RANGE_16G, RETCODE_NOT_SUPPORTED, bma2x2_set_range, rangeLookUpTable, bmaRangeValue, rangeValueLookUpTable, bma2x2LibErrorMapping, ACCELEROMETER_BMI160, ACCELEROMETER_BMI160_RANGE_2G, bmi160_set_accel_range, SUCCESS, bmiRangeValue, bmi160LibErrorMapping, RETCODE_OK, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T Accelerometer_setSleepDuration(Accelerometer_HandlePtr_T handle, Accelerometer_SleepDuration_T lowPowerModeSleepDuration)
Sets the SleepDuration for the accelerometer referenced by the passed handle.
handle Handle to the accelerometer object lowPowerModeSleepDuration set value for sleep duration RETCODE_SUCCESS Set Sleep Duration success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of setting sleep duration values other than Accelerometer_SleepDuration_E. In case of other failures refer bma2x2LibErrorMapping or bmi160LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, BMA2x2_RETURN_FUNCTION_TYPE, E_OUT_OF_RANGE, NULL, Accelerometer_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, ACCELEROMETER_SLEEP_DURATION_OUT_OF_RANGE, RETCODE_SEVERITY_ERROR, Accelerometer_Handle_S::SensorInformation, Acceleromter_SensorInfo_S::initializationStatus, RETCODE_UNINITIALIZED, Acceleromter_SensorInfo_S::sensorID, ACCELEROMETER_BMA280, bma2x2_set_sleep_durn, sleepDurationLookUpTable, bma2x2LibErrorMapping, ACCELEROMETER_BMI160, RETCODE_NOT_SUPPORTED, RETCODE_OK, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
static Retcode_T bma2x2LibErrorMapping(BMA2x2_RETURN_FUNCTION_TYPE BMA2X2_libReturn)
References RETCODE_FAILURE, BMA2x2_RETURN_FUNCTION_TYPE, RETCODE_OK, E_BMA2x2_NULL_PTR, RETCODE_INVALID_PARAM.
Referenced by Accelerometer_setBandwidth, Accelerometer_getBandwidth, Accelerometer_setRange, Accelerometer_getRange, Accelerometer_setSleepDuration, Accelerometer_getSleepDuration, Accelerometer_setMode, Accelerometer_getMode, Accelerometer_readXyzLsbValue, Accelerometer_readXyzGValue.
static void bmaIsrCallback(uint32_t channel, uint32_t edge)
BMA280 driver callback function for channel2 that will be called during ISR, when deferred application callback is registered. This is responsible to defer the context.
channel channel at which interrupt has occurred edge edge at which interrupt has occurred falling(0) or raising edge(1)
References RETCODE_OK, portBASE_TYPE, xHigherPriorityTaskWoken, NULL, BMA_INTERRUPT_CHANNEL_1, Accelerometer_Handle_S::IntChannel1, Accelerometer_InterruptCallback_S::rtCallback, Accelerometer_InterruptCallback_S::deferredCallback, BMA_INTERRUPT_CHANNEL_2, Accelerometer_Handle_S::IntChannel2, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM, xTimerPendFunctionCallFromISR, portYIELD_FROM_ISR, RETCODE_OUT_OF_RESOURCES, Retcode_RaiseError.
Referenced by Accelerometer_init.
static Retcode_T bmi160LibErrorMapping(BMI160_RETURN_FUNCTION_TYPE BMI160_libReturn)
References RETCODE_FAILURE, SUCCESS, RETCODE_OK, E_BMI160_NULL_PTR, RETCODE_INVALID_PARAM.
Referenced by Accelerometer_setBandwidth, Accelerometer_getBandwidth, Accelerometer_setRange, Accelerometer_getRange, Accelerometer_setMode, Accelerometer_getMode, Accelerometer_readXyzLsbValue, Accelerometer_readXyzGValue.
static int8_t mappingEnumForGetFunctions(uint8_t start, uint8_t end, uint8_t getValueToBeTransalated, const uint8_t *lookUpTablePtr)
References GET_MAPPING_ERROR.
Referenced by Accelerometer_getBandwidth, Accelerometer_getRange, Accelerometer_getSleepDuration, Accelerometer_getMode.