AdcCentral.c
ADC_DMA_BUFFER_SIZE
BCDS_MODULE_ID
MAX_NO_OF_SCAN_CHANNELS
Referenced by IsChannelAlreadyActivated, findScanChannelsInfo, findindexOfScanChannel, receiveProcess, AdcCentral_StartScan, AdcCentral_StopScan.
AdcCentral_SingleState_E
AdcCentral_State_E
typedef struct AdcCentral_Info_S AdcCentral_Info_T
typedef struct AdcCentral_ScanChannelInfo_S AdcCentral_ScanChannelInfo_T
typedef struct AdcCentral_SingleChannelInfo_S AdcCentral_SingleChannelInfo_T
typedef enum AdcCentral_SingleState_E AdcCentral_SingleState_T
Enumeration of ADC central single conversion state machine states.
typedef enum AdcCentral_State_E AdcCentral_State_T
Enumeration of ADC central Initialize state machine states.
AdcCentral_Info_T AdcCentalInfo
volatile uint16_t* bufferPointer
Referenced by AdcIRQCallback, receiveProcess.
uint16_t scanDataBufffer[ADC_DMA_BUFFER_SIZE][ADC_DMA_BUFFER_SIZE]
Referenced by AdcCentral_StartScan, AdcCentral_StopScan.
Retcode_T AdcCentral_DeInit(void)
De-Initialize the ADC Module.
RETCODE_OK upon successful execution, error otherwise
References RETCODE_OK, ADC_CENTRAL_INIT, AdcCentral_Info_S::State, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_ADC_CENTRAL_ALREADY_DEINIT, Mcu_Adc_StopScan, AdcCentral_Info_S::ScanChannelConfigLock, NULL, vSemaphoreDelete, AdcCentral_Info_S::ScanChannelInfoLock, GuardedTask_Deinitialize, AdcCentral_Info_S::AdcScanGuardedTaskHandle, Mcu_Adc_DeInitialize, AdcCentral_Info_S::SingleChannel, AdcCentral_SingleChannelInfo_S::State, ADC_SINGLE_STATE_INIT.
Retcode_T AdcCentral_Init(void)
Initialize the ADC Central Module.
RETCODE_OK upon successful execution, error otherwise
References RETCODE_OK, ADC_CENTRAL_READY, AdcCentral_Info_S::State, Mcu_Adc_Initialize, AdcIRQCallback, GuardedTask_Initialize, AdcCentral_Info_S::AdcScanGuardedTaskHandle, receiveProcess, ADCCENTRAL_TASK_PRIORITY, ADCCENTRAL_TASK_STACK_SIZE, AdcCentral_Info_S::ScanChannelInfoLock, AdcCentral_Info_S::ScanChannelConfigLock, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_SEMAPHORE_ERROR, AdcCentral_Info_S::SingleChannel, AdcCentral_SingleChannelInfo_S::State, ADC_SINGLE_STATE_READY, AdcCentral_Info_S::ScanSamplingFreq, AdcCentral_Info_S::ScanChannelMask, AdcCentral_Info_S::ScanChannelInfoIndex.
Referenced by BatteryMonitor_Init, Lem_Enable, NoiseSensor_Setup.
Retcode_T AdcCentral_StartScan(ADC_T adc, AdcCentral_ConfigScanPtr_T configScan)
Start Scan Mode on ADC Interface & Start the PRS Timer as producer.
adc : ADC handle. configScan : Structure which holds the configurations related to scan mode. Three channels(CH4, CH5 & CH6) are supported for the ADC scan & maximum 3 independent users can be possible. Number of samples is fixed to 256 samples per channel. So if multiple channels are enabled by single user then provide buffer accordingly. ADC sampling is done with the user which has the highest sampling frequency. Lower sampling frequency users are notified with ADC callback on multiples of higher sampling frequency user. Independent sampling frequency works better when lower sampling frequency is multiples of higher sampling frequency. So when ADC Scan complete callback is triggered for the users actual frequency at which the adc samples provided is notified with the sampleFrequency parameter in the AdcCentral_SingleCallback_T callback. RETCODE_OK upon successful execution, error otherwise
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, MAX_NO_OF_SCAN_CHANNELS, AdcCentral_Info_S::ScanChannelInfoIndex, RETCODE_ADC_REACHED_MAX_SCAN_CHANNELS, xSemaphoreTake, AdcCentral_Info_S::ScanChannelInfoLock, portMAX_DELAY, IsChannelAlreadyActivated, AdcCentral_ConfigScan_S::ChannelScanMask, RETCODE_ADC_SCAN_CHANNEL_ALREADY_ENABLED, findScanChannelsInfo, AdcCentral_Info_S::ScanChannelMask, AdcCentral_Info_S::IsScanChannelConfigChanged, AdcCentral_Info_S::ScanChannelConfigLock, Mcu_Adc_StopScan, RETCODE_SEMAPHORE_ERROR, AdcCentral_Info_S::ScanChannel, AdcCentral_ScanChannelInfo_S::SamplingFreq, AdcCentral_ConfigScan_S::SamplingRateInHz, AdcCentral_Info_S::ScanSamplingFreq, Mcu_Adc_ConfigScan_S::AcqTime, ADC_ACQ_TIME_128, Mcu_Adc_ConfigScan_S::ChannelScanMask, Mcu_Adc_ConfigScan_S::SamplingRateInHz, Mcu_Adc_ConfigScan_S::Reference, ADCCENTRAL_REF_VOLTAGE, Mcu_Adc_ConfigScan_S::Resolution, ADC_RESOLUTION_12BIT, Mcu_Adc_ConfigScan_S::BufferPtr, scanDataBufffer, Mcu_Adc_ConfigScan_S::NoOfSamples, ADC_CENTRAL_NO_OF_SAMPLES, AdcCentral_ScanChannelInfo_S::Appcallback, AdcCentral_ConfigScan_S::Appcallback, AdcCentral_ScanChannelInfo_S::Buffer, AdcCentral_ConfigScan_S::BufferPtr, AdcCentral_ScanChannelInfo_S::Channelmask, Mcu_Adc_StartScan, xSemaphoreGive.
Referenced by Lem_Enable, NoiseSensor_Enable.
Retcode_T AdcCentral_StartSingle(ADC_T adc, AdcCentral_ConfigSinglePtr_T configStart)
Start Single Mode on ADC Interface.
adc : ADC handle. configStart : Structure which holds the configurations(Resolution, ADC reference,callback) related to single mode. RETCODE_OK upon successful execution, error otherwise
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM, ADC_SINGLE_STATE_READY, AdcCentral_Info_S::SingleChannel, AdcCentral_SingleChannelInfo_S::State, RETCODE_ADC_SINGLE_CHANNEL_NOT_READY, IsScanChannelActive, AdcCentral_ConfigSingle_S::Channel, RETCODE_ADC_CENTRAL_USED_IN_SCAN, Mcu_Adc_ConfigSingle_S::AcqTime, AdcCentral_ConfigSingle_S::AcqTime, Mcu_Adc_ConfigSingle_S::Channel, Mcu_Adc_ConfigSingle_S::Reference, AdcCentral_ConfigSingle_S::Reference, Mcu_Adc_ConfigSingle_S::Resolution, AdcCentral_ConfigSingle_S::Resolution, Mcu_Adc_ConfigSingle_S::BufferPtr, AdcCentral_ConfigSingle_S::BufferPtr, AdcCentral_SingleChannelInfo_S::Appcallback, AdcCentral_ConfigSingle_S::Appcallback, ADC_SINGLE_CONVERSION_STATE, Mcu_Adc_StartSingle.
Referenced by BatteryMonitor_MeasureSignal.
Retcode_T AdcCentral_StopScan(ADC_T adc, uint32_t ChannelScanMask)
Stop the Scan mode on ADC Interface and stops the PRS timer used for sampling adc channels.
adc : ADC handle. ChannelScanMask : Channel in which scan has to be stopped RETCODE_OK upon successful execution, error otherwise
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_FAILURE, IsChannelAlreadyActivated, RETCODE_ADC_SCAN_CHANNEL_NOT_ENABLED, Mcu_Adc_StopScan, findindexOfScanChannel, MAX_NO_OF_SCAN_CHANNELS, AdcCentral_Info_S::ScanChannel, AdcCentral_ScanChannelInfo_S::Appcallback, AdcCentral_ScanChannelInfo_S::Buffer, AdcCentral_ScanChannelInfo_S::Channelmask, AdcCentral_Info_S::ScanChannelInfoIndex, AdcCentral_Info_S::ScanChannelMask, Mcu_Adc_ConfigScan_S::AcqTime, ADC_ACQ_TIME_16, Mcu_Adc_ConfigScan_S::ChannelScanMask, Mcu_Adc_ConfigScan_S::SamplingRateInHz, AdcCentral_Info_S::ScanSamplingFreq, Mcu_Adc_ConfigScan_S::Reference, ADCCENTRAL_REF_VOLTAGE, Mcu_Adc_ConfigScan_S::Resolution, ADC_RESOLUTION_12BIT, Mcu_Adc_ConfigScan_S::BufferPtr, scanDataBufffer, Mcu_Adc_ConfigScan_S::NoOfSamples, ADC_CENTRAL_NO_OF_SAMPLES, Mcu_Adc_StartScan.
Referenced by Lem_Disable, NoiseSensor_Disable.
void AdcIRQCallback(ADC_T adc, Mcu_Adc_Event_T event, uint16_t *buff)
References RETCODE_OK, Mcu_Adc_Handle_S::Link1RegPtr, Mcu_Adc_Handle_S::_DriverCtx, Mcu_Adc_Driver_S::NumOfSamples, Mcu_Adc_Driver_S::NumOfScanChannels, Mcu_Adc_Event_S::ScanComplete, AdcCentral_Info_S::IsScanChannelConfigChanged, xSemaphoreGiveFromISR, AdcCentral_Info_S::ScanChannelConfigLock, portYIELD_FROM_ISR, MCU_DMA_Channel_S::ChannelId, Mcu_Adc_Driver_S::PointerValue, NULL, bufferPointer, GuardedTask_SignalFromIsr, AdcCentral_Info_S::AdcScanGuardedTaskHandle, Mcu_Adc_Event_S::SingleComplete, AdcCentral_Info_S::SingleChannel, AdcCentral_SingleChannelInfo_S::Appcallback, AdcCentral_SingleChannelInfo_S::State, ADC_SINGLE_STATE_READY, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_FAILURE, Retcode_RaiseErrorFromIsr.
Referenced by AdcCentral_Init.
static uint8_t findindexOfScanChannel(uint32_t channelMask)
References MAX_NO_OF_SCAN_CHANNELS, AdcCentral_Info_S::ScanChannel, AdcCentral_ScanChannelInfo_S::Channelmask.
Referenced by AdcCentral_StopScan.
static Retcode_T findScanChannelsInfo(uint8_t *ChannelCnt, uint8_t *ChannelNo, uint32_t ChannelMask)
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, MAX_NO_OF_SCAN_CHANNELS.
Referenced by receiveProcess, AdcCentral_StartScan.
static bool IsChannelAlreadyActivated(uint32_t channelMask)
References AdcCentral_Info_S::ScanChannelMask, MAX_NO_OF_SCAN_CHANNELS.
Referenced by AdcCentral_StartScan, AdcCentral_StopScan.
static bool IsScanChannelActive(Adc_Channel_T channel)
References AdcCentral_Info_S::ScanChannelMask.
Referenced by AdcCentral_StartSingle.
static void receiveProcess(void)
References RETCODE_OK, xSemaphoreTake, AdcCentral_Info_S::ScanChannelInfoLock, portMAX_DELAY, findScanChannelsInfo, AdcCentral_Info_S::ScanChannelMask, AdcCentral_Info_S::ScanChannel, AdcCentral_ScanChannelInfo_S::Channelmask, AdcCentral_ScanChannelInfo_S::Buffer, bufferPointer, ADC_CENTRAL_NO_OF_SAMPLES, AdcCentral_ScanChannelInfo_S::Appcallback, AdcCentral_Info_S::ScanSamplingFreq, MAX_NO_OF_SCAN_CHANNELS, AdcCentral_ScanChannelInfo_S::SamplingCounter, AdcCentral_ScanChannelInfo_S::SamplingFreq, xSemaphoreGive, Retcode_RaiseError, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_SEMAPHORE_ERROR.
Referenced by AdcCentral_Init.