AppTxtParser.c
APP_TXT_PARSER_EMPTY
Referenced by AppTxtParserReset, AppTxtParserInitialize.
APP_TXT_PARSER_LINE_SIZE_MAX
Referenced by AppTxtParserReset, AppTxtParserInitialize.
APP_TXT_PARSER_NO
Referenced by AppTxtParser_WLANStaticIpValue, AppTxtParser_LWM2MTestModeValue.
APP_TXT_PARSER_SPACE
Referenced by ATPGetToken.
APP_TXT_PARSER_WHITESPACE
Referenced by ATPGetToken.
APP_TXT_PARSER_YES
Referenced by AppTxtParser_WLANStaticIpValue, AppTxtParser_LWM2MTestModeValue, AppTxtParser_LWM2MConNotifiesValue.
ATP_EXPANDED_LENGTH
length of expanded lwm2m endpoint name and dtls identity
ATP_MAC_LENGTH
length of MAC as string
ATP_MAGIC_EP_EXPAND
Magic token expanded to LWM2M endpoint name
Referenced by AppTxtParserInitialize.
ATP_MAGIC_MAC_EXPAND
Magic token expanded to MAC
Referenced by AppTxtParserInitialize.
BCDS_MODULE_ID
LWM2M_CON_NOTIFIES_TXT_DEFAULT
LWM2M binding by Default
LWM2M_TESTMODE_MIX
Referenced by AppTxtParser_LWM2MTestModeValue.
LWM2M_TESTMODE_OFF
Referenced by AppTxtParser_LWM2MTestModeValue.
LWM2M_TESTMODE_ON
Referenced by AppTxtParser_LWM2MTestModeValue.
WLAN_STATIC_IP_TXT_DEFAULT
Network static IP Address Default
AppTxtParser_ConfigArrayIndex_E
AppTxtParser_States_E
AppTxtParser_TokensType_E
typedef struct AppTxtParser_ConfigLine_S AppTxtParser_ConfigLine_T
typedef enum AppTxtParser_States_E AppTxtParser_States_T
typedef enum AppTxtParser_TokensType_E AppTxtParser_TokensType_T
const char A10Name[][]
const char A11Name[][]
const char A12Name[][]
const char A13Name[][]
const char A14Name[][]
const char A15Name[][]
const char A16Name[][]
const char A17Name[][]
const char A18Name[][]
const char A1Name[][]
Variable containers for configuration values Attribute names on the configuration file
const char A2Name[][]
const char A3Name[][]
const char A4Name[][]
const char A5Name[][]
const char A6Name[][]
const char A7Name[][]
const char A8Name[][]
const char A9Name[][]
AppTxtParser_ConfigLine_T ATPConfigStructure[ATP_IDX_SIZE][ATP_IDX_SIZE]
char ATPExpandedEndpointName[ATP_EXPANDED_LENGTH][ATP_EXPANDED_LENGTH]
Referenced by AppTxtParserInitialize, AppTxtParser_LWM2MEndPointValue.
char ATPExpandedPskIdentity[ATP_EXPANDED_LENGTH][ATP_EXPANDED_LENGTH]
Referenced by AppTxtParserInitialize.
const char* ATPHexToBin
Referenced by digitHexToBin.
char ATPKeyBuffer[ATP_EXPANDED_LENGTH][ATP_EXPANDED_LENGTH]
Referenced by AppTxtParserInitialize.
char ATPMacAddress[ATP_MAC_LENGTH][ATP_MAC_LENGTH]
Referenced by AppTxtParserInitialize, AppTxtParser_LWM2MMACAddrValue.
const char* ATPPskIdentityPtr
Referenced by AppTxtParserInitialize, AppTxtParser_DTLSPSKIdentityValue.
uint32_t ATPPskSecretKeyLength
Referenced by AppTxtParserInitialize, AppTxtParser_DTLSPSKSecretKeyLengthValue.
const char* ATPPskSecretKeyPtr
Referenced by AppTxtParserInitialize, AppTxtParser_DTLSPSKSecretKeyValue.
uint32_t ATPServerPort
Referenced by AppTxtParserInitialize, AppTxtParser_LWM2MServerPortValue.
char ATPServerURL[ATP_EXPANDED_LENGTH][ATP_EXPANDED_LENGTH]
Referenced by AppTxtParserInitialize, AppTxtParser_LWM2MIsSecureValue.
char* ATPServerURLPtr
Referenced by AppTxtParserInitialize, AppTxtParser_LWM2MServerURLValue.
char ATPValues[ATP_IDX_SIZE][APP_TXT_PARSER_LINE_SIZE_MAX][ATP_IDX_SIZE][APP_TXT_PARSER_LINE_SIZE_MAX]
const char* AppTxtParser_DTLSPSKIdentityValue(void)
returns the DTLS/PSK identity of the configuration file
Refer interface header for description
References ATPPskIdentityPtr.
Referenced by AppControllerSetup.
uint32_t AppTxtParser_DTLSPSKSecretKeyLengthValue(void)
returns the DTLS/PSK secret key length of the configuration file
Refer interface header for description
References ATPPskSecretKeyLength.
Referenced by AppControllerSetup.
const char* AppTxtParser_DTLSPSKSecretKeyValue(void)
returns the DTLS/PSK secret key of the configuration file
Refer interface header for description
References ATPPskSecretKeyPtr.
Referenced by AppControllerSetup.
Retcode_T AppTxtParser_Initialize(AppTxtParser_Init_T *initCredentials)
Parse the config file read inside the buffer.
Refer interface header for description
References AppTxtParserInitialize, AppTxtParser_PrintConfigurations, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_FAILURE, RETCODE_OK.
Referenced by AppControllerSetup.
const char* AppTxtParser_LWM2MBindingValue(void)
returns lwm2m binding value
Refer interface header for description
References ATPGetAttValue, ATP_IDX_LWM2M_BINDING.
Referenced by AppControllerSetup.
bool AppTxtParser_LWM2MConNotifiesValue(void)
returns the Lwm2m connection notify value
Refer interface header for description
References ATPGetAttValue, ATP_IDX_LWM2M_CON_NOTIFIES, APP_TXT_PARSER_YES.
Referenced by AppControllerSetup.
const char* AppTxtParser_LWM2MEndPointValue(void)
returns attribute value for the token LWM2MENDPOINT as defined at the configuration file
Refer interface header for description
References ATPExpandedEndpointName.
Referenced by AppControllerSetup.
bool AppTxtParser_LWM2MIsSecureValue(void)
This function checks whether the lwm2m is secure or not based on the url.
Refer interface header for description
References ATPServerURL.
Referenced by AppControllerSetup, AppTxtParserInitialize.
uint32_t AppTxtParser_LWM2MLifetimeValue(void)
returns lwm2m lifetime in seconds.
Refer interface header for description
References ATPGetAttValue, ATP_IDX_LWM2M_LIFETIME.
Referenced by AppControllerSetup.
const char* AppTxtParser_LWM2MMACAddrValue(void)
returns MAC address value for Lwm2m
Refer interface header for description
References ATPMacAddress.
uint32_t AppTxtParser_LWM2MServerPortValue(void)
returns the port value extracted from the server url
Refer interface header for description
References ATPServerPort.
Referenced by AppControllerSetup.
const char* AppTxtParser_LWM2MServerURLValue(void)
returns attribute value for the token LWM2MDERSRV as defined at the configuration file
Refer interface header for description
References ATPServerURLPtr.
Referenced by AppControllerSetup.
uint8_t AppTxtParser_LWM2MTestModeValue(void)
Returns the current configuration for the field TESTMODE set in the *.txt file.
Refer interface header for description
References LWM2M_TESTMODE_MIX, ATPGetAttValue, ATP_IDX_TEST_MODE, LWM2M_TEST_MODE_DEFAULT, APP_TXT_PARSER_YES, LWM2M_TESTMODE_ON, APP_TXT_PARSER_NO, LWM2M_TESTMODE_OFF.
Referenced by AppControllerFireTask, AppControllerSetup.
void AppTxtParser_PrintConfigurations(const char *title, bool defaultsOnly)
Print list of configured values.
Refer interface header for description
References ATP_IDX_SIZE, ATP_IDX_WLAN_PASSWORD, AppTxtParser_ConfigLine_S::Ignore, AppTxtParser_ConfigLine_S::Defined, AppTxtParser_ConfigLine_S::ATPName, AppTxtParser_ConfigLine_S::ATPValue, AppTxtParser_ConfigLine_S::DefaultValue.
Referenced by AppControllerFire, AppTxtParser_Initialize.
uint32_t AppTxtParser_WLANDnsAddrValue(void)
returns attribute value for the token DNSSERVER as defined at the configuration file
Refer interface header for description
References RETCODE_OK, value, ATPGetAttValue, ATP_IDX_WLAN_DNS_ADDR, ATPEmptyCfg, Utils_ConvertIpStringToNumber, Retcode_RaiseError.
Referenced by AppControllerSetup.
uint32_t AppTxtParser_WLANGwAddrValue(void)
returns attribute value for the token GATEWAY as defined at the configuration file
Refer interface header for description
References RETCODE_OK, value, ATPGetAttValue, ATP_IDX_WLAN_GW_ADDR, ATPEmptyCfg, Utils_ConvertIpStringToNumber, Retcode_RaiseError.
Referenced by AppControllerSetup.
uint32_t AppTxtParser_WLANIpAddrValue(void)
returns attribute value for the token DNSSERVER as defined at the configuration file
Refer interface header for description
References RETCODE_OK, value, ATPGetAttValue, ATP_IDX_WLAN_IP_ADDR, ATPEmptyCfg, Utils_ConvertIpStringToNumber, Retcode_RaiseError.
Referenced by AppControllerSetup.
uint32_t AppTxtParser_WLANMaskValue(void)
returns attribute value for the token MASK as defined at the configuration file
Refer interface header for description
References RETCODE_OK, value, ATPGetAttValue, ATP_IDX_WLAN_MASK, ATPEmptyCfg, Utils_ConvertIpStringToNumber, Retcode_RaiseError.
Referenced by AppControllerSetup.
const char* AppTxtParser_WLANPasswordValue(void)
returns attribute value for the token PASSWORD as defined at the configuration file
Refer interface header for description
References ATPGetAttValue, ATP_IDX_WLAN_PASSWORD, ATPEmptyCfg.
Referenced by AppControllerSetup.
const char* AppTxtParser_WLANSsidValue(void)
returns the attribute value for the token SSID as defined at the configuration file
Refer interface header for description
References ATPGetAttValue, ATP_IDX_WLAN_SSID, ATPEmptyCfg.
Referenced by AppControllerSetup.
bool AppTxtParser_WLANStaticIpValue(void)
returns attribute value for the token STATICIP as defined at the configuration file
Refer interface header for description
References value, ATPGetAttValue, ATP_IDX_WLAN_STATIC_IP, ATPEmptyCfg, APP_TXT_PARSER_YES, APP_TXT_PARSER_NO.
Referenced by AppControllerSetup.
static const char* AppTxtParserDTLSPSKIdentityValue(void)
References ATPGetAttValue, ATP_IDX_DTLS_PSK_IDENTITY.
Referenced by AppTxtParserInitialize.
static const char* AppTxtParserDTLSPSKSecretKeyHexValue(void)
References ATP_IDX_DTLS_PSK_SECRET_KEY_HEX, AppTxtParser_ConfigLine_S::Defined, ATP_IDX_DTLS_PSK_SECRET_KEY, ATPGetAttValue.
Referenced by AppTxtParserInitialize.
static const char* AppTxtParserDTLSPSKSecretKeyValue(void)
References ATPGetAttValue, ATP_IDX_DTLS_PSK_SECRET_KEY.
Referenced by AppTxtParserInitialize.
static bool AppTxtParserInitialize(AppTxtParser_Init_T *initCredentials)
Parse the config file read inside the buffer.
initCredentials credentials for parsing true if configuration file is correct and contains necessary attribute/values
References ATP_STATE_EXP_NAME, APP_TXT_PARSER_LINE_SIZE_MAX, ATP_TOKEN_TYPE_UNKNOWN, NULL, AppTxtParserReset, ATPGetToken, AppTxtParser_Init_S::DataPointer, AppTxtParser_Init_S::DataLength, ATP_TOKEN_EOF, ATP_TOKEN_ATT_NAME, ATP_IDX_SIZE, AppTxtParser_ConfigLine_S::ATPName, ATP_STATE_EXP_EQUAL, ATP_TOKEN_EQUAL, ATP_STATE_EXP_VALUE, ATP_TOKEN_VALUE, AppTxtParser_ConfigLine_S::ATPValue, AppTxtParser_ConfigLine_S::Defined, ATP_IDX_DTLS_PSK_SECRET_KEY, ATP_IDX_DTLS_PSK_SECRET_KEY_HEX, AppTxtParser_ConfigLine_S::DefaultValue, APP_TXT_PARSER_EMPTY, ATP_IDX_LWM2M_ENDPOINT, ATP_IDX_DTLS_PSK_IDENTITY, ATPMacAddress, AppTxtParser_Init_S::DeviceMAC, ATPKeyBuffer, ATPExpandToken, AppTxtParserLWM2MEndPointValue, ATP_MAGIC_MAC_EXPAND, ATPExpandedEndpointName, ATPEmptyCfg, AppTxtParserDTLSPSKIdentityValue, ATPPskIdentityPtr, ATPExpandedPskIdentity, ATP_MAGIC_EP_EXPAND, AppTxtParserDTLSPSKSecretKeyHexValue, AppTxtParserDTLSPSKSecretKeyValue, ATPPskSecretKeyPtr, ATPPskSecretKeyLength, ATPDecodeHexToBin, AppTxtParserLWM2MDefaultServerValue, ATPServerURL, AppTxtParser_LWM2MIsSecureValue, ATPServerPort, ATPServerURLPtr.
Referenced by AppTxtParser_Initialize.
static const char* AppTxtParserLWM2MDefaultServerValue(void)
References value, ATPGetAttValue, ATP_IDX_LWM2M_DEFAULT_SERVER, ATPEmptyCfg.
Referenced by AppTxtParserInitialize.
static const char* AppTxtParserLWM2MEndPointValue(void)
References value, ATPGetAttValue, ATP_IDX_LWM2M_ENDPOINT, ATPEmptyCfg.
Referenced by AppTxtParserInitialize.
static void AppTxtParserReset(void)
References ATP_IDX_SIZE, AppTxtParser_ConfigLine_S::Defined, AppTxtParser_ConfigLine_S::ATPValue, APP_TXT_PARSER_LINE_SIZE_MAX, NULL, AppTxtParser_ConfigLine_S::DefaultValue, APP_TXT_PARSER_EMPTY.
Referenced by AppTxtParserInitialize.
static unsigned int ATPDecodeHexToBin(const char *source, char *dest, bool terminatedString)
Decode hexadecimal string to binary buffer.
source Hexadecimal string dest Binary destination buffer. terminatedString Dest should be handled as string (0 terminated) number of converted bytes dest (excluding 0 termination, if applied):
References assert, digitHexToBin.
Referenced by AppTxtParserInitialize.
static bool ATPEmptyCfg(const char *value)
References NULL, value.
Referenced by AppTxtParserLWM2MEndPointValue, AppTxtParserLWM2MDefaultServerValue, AppTxtParserInitialize, AppTxtParser_WLANSsidValue, AppTxtParser_WLANPasswordValue, AppTxtParser_WLANStaticIpValue, AppTxtParser_WLANIpAddrValue, AppTxtParser_WLANDnsAddrValue, AppTxtParser_WLANGwAddrValue, AppTxtParser_WLANMaskValue.
static void ATPExpandToken(const char *value, const char *magicToken, const char *expand, char *expandedValue, size_t expandedSize)
References NULL, value.
Referenced by AppTxtParserInitialize.
static const char * ATPGetAttValue(int index)
References ATP_IDX_SIZE, AppTxtParser_ConfigLine_S::Defined, AppTxtParser_ConfigLine_S::ATPValue, AppTxtParser_ConfigLine_S::DefaultValue.
Referenced by AppTxtParserLWM2MEndPointValue, AppTxtParserDTLSPSKIdentityValue, AppTxtParserDTLSPSKSecretKeyValue, AppTxtParserDTLSPSKSecretKeyHexValue, AppTxtParserLWM2MDefaultServerValue, AppTxtParser_WLANSsidValue, AppTxtParser_WLANPasswordValue, AppTxtParser_WLANStaticIpValue, AppTxtParser_WLANIpAddrValue, AppTxtParser_WLANDnsAddrValue, AppTxtParser_WLANGwAddrValue, AppTxtParser_WLANMaskValue, AppTxtParser_LWM2MTestModeValue, AppTxtParser_LWM2MLifetimeValue, AppTxtParser_LWM2MBindingValue, AppTxtParser_LWM2MConNotifiesValue.
static AppTxtParser_TokensType_T ATPGetToken(const char *buffer, uint16_t *idxAtBuffer, uint16_t bufSize, char *token, uint16_t *tokenSize, AppTxtParser_States_T expTokenType)
extracts tokens from the input buffer , copy into the token buffer and returns its size at tokensize
buffer The input buffer idxAtBuffer The index from which we have to look after tokens bufSize The size of the input buffer (param one) token The buffer that will contain the token (must be different to NULL ) expTokenType expected token type awaited from attribute parser tokenSize The pointer to the variable that receive the size of the buffer the TOKEN types found (ATP_TOKEN_TYPE_UNKNOWN is EOF)
References ATP_TOKEN_TYPE_UNKNOWN, ATP_STATE_EXP_VALUE, APP_TXT_PARSER_SPACE, APP_TXT_PARSER_WHITESPACE, NULL, ATP_STATE_EXP_NAME, ATP_TOKEN_EQUAL, ATP_IDX_SIZE, AppTxtParser_ConfigLine_S::ATPName, ATP_TOKEN_ATT_NAME, ATP_TOKEN_VALUE, ATP_TOKEN_EOF.
Referenced by AppTxtParserInitialize.
static int digitHexToBin(char c)
Convert hexadecimal character/digit to number.
'0' ... '9' to 0 ... 9 'a' ... 'f' to 10 ... 15 'A' ... 'F' to 10 ... 15 c character to be converted number, or -1, if provided character wasN::t a valid hexadecimal character.
References ATPHexToBin, NULL, assert.
Referenced by ATPDecodeHexToBin.