AppTxtParser.h
typedef struct AppTxtParser_Init_S AppTxtParser_Init_T
Typedef for init credentials for AppTxtParser.
const char* AppTxtParser_DTLSPSKIdentityValue(void)
returns the DTLS/PSK identity of the configuration file
Refer interface header for description
References ATPPskIdentityPtr.
Referenced by AppControllerSetup.
uint32_t AppTxtParser_DTLSPSKSecretKeyLengthValue(void)
returns the DTLS/PSK secret key length of the configuration file
Refer interface header for description
References ATPPskSecretKeyLength.
Referenced by AppControllerSetup.
const char* AppTxtParser_DTLSPSKSecretKeyValue(void)
returns the DTLS/PSK secret key of the configuration file
Refer interface header for description
References ATPPskSecretKeyPtr.
Referenced by AppControllerSetup.
Retcode_T AppTxtParser_Initialize(AppTxtParser_Init_T *initCredentials)
Parse the config file read inside the buffer.
initCredentials credentials for parsing true if configuration file is correct and contains necessary attribute/values Refer interface header for description
References AppTxtParserInitialize, AppTxtParser_PrintConfigurations, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_FAILURE, RETCODE_OK.
Referenced by AppControllerSetup.
const char* AppTxtParser_LWM2MBindingValue(void)
returns lwm2m binding value
Refer interface header for description
References ATPGetAttValue, ATP_IDX_LWM2M_BINDING.
Referenced by AppControllerSetup.
bool AppTxtParser_LWM2MConNotifiesValue(void)
returns the Lwm2m connection notify value
Refer interface header for description
References ATPGetAttValue, ATP_IDX_LWM2M_CON_NOTIFIES, APP_TXT_PARSER_YES.
Referenced by AppControllerSetup.
const char* AppTxtParser_LWM2MEndPointValue(void)
returns attribute value for the token LWM2MENDPOINT as defined at the configuration file
If attribute is not defined in configuration file it returns empty string Refer interface header for description
References ATPExpandedEndpointName.
Referenced by AppControllerSetup.
bool AppTxtParser_LWM2MIsSecureValue(void)
This function checks whether the lwm2m is secure or not based on the url.
true if it is secure, false if not secure Refer interface header for description
References ATPServerURL.
Referenced by AppControllerSetup, AppTxtParserInitialize.
uint32_t AppTxtParser_LWM2MLifetimeValue(void)
returns lwm2m lifetime in seconds.
Refer interface header for description
References ATPGetAttValue, ATP_IDX_LWM2M_LIFETIME.
Referenced by AppControllerSetup.
const char* AppTxtParser_LWM2MMACAddrValue(void)
returns MAC address value for Lwm2m
Refer interface header for description
References ATPMacAddress.
uint32_t AppTxtParser_LWM2MServerPortValue(void)
returns the port value extracted from the server url
Refer interface header for description
References ATPServerPort.
Referenced by AppControllerSetup.
const char* AppTxtParser_LWM2MServerURLValue(void)
returns attribute value for the token LWM2MDERSRV as defined at the configuration file
Refer interface header for description
References ATPServerURLPtr.
Referenced by AppControllerSetup.
uint8_t AppTxtParser_LWM2MTestModeValue(void)
Returns the current configuration for the field TESTMODE set in the *.txt file.
TESTMODE_OFF - If attribute token 'TESTMODE = NO',is defined in config file TESTMODE_ON - If attribute token 'TESTMODE = YES', is defined in config file TESTMODE_MIX - If attribute token 'TESTMODE = MIX', is defined in config file If no entry for TESTMODE configuration in SD card, then the default return value is TESTMODE_MIX Refer interface header for description
References LWM2M_TESTMODE_MIX, ATPGetAttValue, ATP_IDX_TEST_MODE, LWM2M_TEST_MODE_DEFAULT, APP_TXT_PARSER_YES, LWM2M_TESTMODE_ON, APP_TXT_PARSER_NO, LWM2M_TESTMODE_OFF.
Referenced by AppControllerFireTask, AppControllerSetup.
void AppTxtParser_PrintConfigurations(const char *title, bool defaultsOnly)
Print list of configured values.
title title for list defaultsOnly list only default values Refer interface header for description
References ATP_IDX_SIZE, ATP_IDX_WLAN_PASSWORD, AppTxtParser_ConfigLine_S::Ignore, AppTxtParser_ConfigLine_S::Defined, AppTxtParser_ConfigLine_S::ATPName, AppTxtParser_ConfigLine_S::ATPValue, AppTxtParser_ConfigLine_S::DefaultValue.
Referenced by AppControllerFire, AppTxtParser_Initialize.
uint32_t AppTxtParser_WLANDnsAddrValue(void)
returns attribute value for the token DNSSERVER as defined at the configuration file
If attribute is not defined in configuration file it returns empty string Refer interface header for description
References RETCODE_OK, value, ATPGetAttValue, ATP_IDX_WLAN_DNS_ADDR, ATPEmptyCfg, Utils_ConvertIpStringToNumber, Retcode_RaiseError.
Referenced by AppControllerSetup.
uint32_t AppTxtParser_WLANGwAddrValue(void)
returns attribute value for the token GATEWAY as defined at the configuration file
If attribute is not defined in configuration file it returns empty string Refer interface header for description
References RETCODE_OK, value, ATPGetAttValue, ATP_IDX_WLAN_GW_ADDR, ATPEmptyCfg, Utils_ConvertIpStringToNumber, Retcode_RaiseError.
Referenced by AppControllerSetup.
uint32_t AppTxtParser_WLANIpAddrValue(void)
returns attribute value for the token DNSSERVER as defined at the configuration file
If attribute is not defined in configuration file it returns empty string Refer interface header for description
References RETCODE_OK, value, ATPGetAttValue, ATP_IDX_WLAN_IP_ADDR, ATPEmptyCfg, Utils_ConvertIpStringToNumber, Retcode_RaiseError.
Referenced by AppControllerSetup.
uint32_t AppTxtParser_WLANMaskValue(void)
returns attribute value for the token MASK as defined at the configuration file
If attribute is not defined in configuration file it returns empty string Refer interface header for description
References RETCODE_OK, value, ATPGetAttValue, ATP_IDX_WLAN_MASK, ATPEmptyCfg, Utils_ConvertIpStringToNumber, Retcode_RaiseError.
Referenced by AppControllerSetup.
const char* AppTxtParser_WLANPasswordValue(void)
returns attribute value for the token PASSWORD as defined at the configuration file
If attribute is not defined in configuration file it returns empty string Refer interface header for description
References ATPGetAttValue, ATP_IDX_WLAN_PASSWORD, ATPEmptyCfg.
Referenced by AppControllerSetup.
const char* AppTxtParser_WLANSsidValue(void)
returns the attribute value for the token SSID as defined at the configuration file
If attribute is not defined in configuration file it returns empty string Refer interface header for description
References ATPGetAttValue, ATP_IDX_WLAN_SSID, ATPEmptyCfg.
Referenced by AppControllerSetup.
bool AppTxtParser_WLANStaticIpValue(void)
returns attribute value for the token STATICIP as defined at the configuration file
If attribute is not defined in configuration file it returns empty string Refer interface header for description
References value, ATPGetAttValue, ATP_IDX_WLAN_STATIC_IP, ATPEmptyCfg, APP_TXT_PARSER_YES, APP_TXT_PARSER_NO.
Referenced by AppControllerSetup.