AxisRemap.c
BCDS_MODULE_ID
MAP_X_TO_Y
Referenced by AxisRemap_remapSensorData.
MAP_X_TO_Z
Referenced by AxisRemap_remapSensorData.
MAP_Y_TO_X
Referenced by AxisRemap_remapSensorData.
MAP_Y_TO_Z
Referenced by AxisRemap_remapSensorData.
MAP_Z_TO_X
Referenced by AxisRemap_remapSensorData.
MAP_Z_TO_Y
Referenced by AxisRemap_remapSensorData.
MASK_TWO_LEAST_SIGNIFICANT_BITS
Referenced by AxisRemap_remapSensorData.
X_AXIS_SIGN_MASK_VAL
Referenced by AxisRemap_remapSensorData.
Y_AXIS_CONFIG_SHIFT_VAL
Referenced by AxisRemap_remapSensorData.
Y_AXIS_SIGN_MASK_VAL
Referenced by AxisRemap_remapSensorData.
Z_AXIS_CONFIG_SHIFT_VAL
Referenced by AxisRemap_remapSensorData.
Z_AXIS_SIGN_MASK_VAL
Referenced by AxisRemap_remapSensorData.
Retcode_T AxisRemap_remapSensorData(AxisRemap_Data_T actualSensorDataXyz, AxisRemap_Config_T remapConfigData, AxisRemap_Data_T *remapSensorDataXyz_p)
References RETCODE_FAILURE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, AxisRemap_Config_S::axisConfig, AxisRemap_Config_S::axisSign, MASK_TWO_LEAST_SIGNIFICANT_BITS, X_AXIS_SIGN_MASK_VAL, Y_AXIS_CONFIG_SHIFT_VAL, Y_AXIS_SIGN_MASK_VAL, Z_AXIS_CONFIG_SHIFT_VAL, Z_AXIS_SIGN_MASK_VAL, MAP_Y_TO_X, AxisRemap_Data_S::x, AxisRemap_Data_S::y, MAP_Z_TO_X, AxisRemap_Data_S::z, MAP_X_TO_Y, MAP_Z_TO_Y, MAP_X_TO_Z, MAP_Y_TO_Z, RETCODE_OK, RETCODE_INVALID_PARAM, RETCODE_SEVERITY_ERROR.
Referenced by Bma280Utils_remapAxis, Bmg160Utils_remapAxis, Bmi160Utils_remapAxis, Bmm150Utils_remapAxis.