BCDS_GuardedTask.h
typedef void(* GuardedTask_Function_T)(void))(void)
typedef void* GuardedTask_SemaphoreHandle_T
typedef struct GuardedTask_S GuardedTask_T
typedef void* GuardedTask_TaskHandle_T
BCDS_DEPRECATED(Retcode_T GuardedTask_initialize(GuardedTask_T *handle, GuardedTask_Function_T taskRunFunction, const char *taskName, uint32_t taskPriority, uint32_t taskStackSize))
This function initializes a given GuardedTask handle.
Deprecatedsince version vxx.xx.xx, replaced by GuardedTask_Initialize handle - A pointer to an empty GuardedTask structure taskRunFunction - A function pointer to the user-code run function that should be called by the task taskName - A cstring representing the name of the task taskPriority - The task priority taskStackSize - The task stack size RETCODE_OK - Guarded Task has been initialized successfully RETCODE_INVALID_PARAM - One of the parameters was invalid RETCODE_OUT_OF_RESOURCES - Unable to allocate resources for task or semaphore
BCDS_DEPRECATED(Retcode_T GuardedTask_deinitialize(GuardedTask_T *handle))
This function deinitializes a given GuardTask handle and sets all attributes to NULL.
This function signals the GuardTask-task to execute its user run function.Deprecatedsince version vxx.xx.xx, replaced by GuardedTask_Deinitialize handle - A pointer to an initialized GuardTask structure. RETCODE_OK - Guarded Task has been deinitialized successfully RETCODE_INVALID_PARAM - handle pointer is NULL Deprecatedsince version vxx.xx.xx, replaced by GuardedTask_Signal handle - A pointer to an initialized GuardTask structure This function may ONLY be called from NON-ISR context! RETCODE_OK - Task has been signaled properly RETCODE_GUARDEDTASK_SEMAPHORE_ALREADY_GIVEN - Indicates that the semaphore was already in a given state. This implicitly means that the encapsulated task is still in execution RETCODE_INVALID_PARAM - Given parameter was invalid Deprecatedsince version vxx.xx.xx, replaced by GuardedTask_SignalFromIsr handle - A pointer to an initialized GuardTask structure This function may ONLY be called from ISR context! RETCODE_OK - Task has been signaled properly RETCODE_GUARDEDTASK_SEMAPHORE_ALREADY_GIVEN - Indicates that the semaphore was already in a given state. This implicitly means that the encapsulated task is still in execution RETCODE_INVALID_PARAM - Given parameter was invalid
Retcode_T GuardedTask_Deinitialize(GuardedTask_T *handle)
This function deinitializes a given GuardTask handle and sets all attributes to NULL.
handle - A pointer to an initialized GuardTask structure. RETCODE_OK - Guarded Task has been deinitialized successfully RETCODE_INVALID_PARAM - handle pointer is NULL
Referenced by AdcCentral_DeInit.
Retcode_T GuardedTask_Initialize(GuardedTask_T *handle, GuardedTask_Function_T taskRunFunction, const char *taskName, uint32_t taskPriority, uint32_t taskStackSize)
This function initializes a given GuardedTask handle.
handle - A pointer to an empty GuardedTask structure taskRunFunction - A function pointer to the user-code run function that should be called by the task taskName - A cstring representing the name of the task taskPriority - The task priority taskStackSize - The task stack size RETCODE_OK - Guarded Task has been initialized successfully RETCODE_INVALID_PARAM - One of the parameters was invalid RETCODE_OUT_OF_RESOURCES - Unable to allocate resources for task or semaphore
Referenced by AdcCentral_Init.
Retcode_T GuardedTask_Signal(GuardedTask_T *handle)
This function signals the GuardTask-task to execute its user run function.
handle - A pointer to an initialized GuardTask structure This function may ONLY be called from NON-ISR context! RETCODE_OK - Task has been signaled properly RETCODE_GUARDEDTASK_SEMAPHORE_ALREADY_GIVEN - Indicates that the semaphore was already in a given state. This implicitly means that the encapsulated task is still in execution RETCODE_INVALID_PARAM - Given parameter was invalid
Retcode_T GuardedTask_SignalFromIsr(GuardedTask_T *handle)
This function signals the GuardTask-task to execute its user run function.
handle - A pointer to an initialized GuardTask structure This function may ONLY be called from ISR context! RETCODE_OK - Task has been signaled properly RETCODE_GUARDEDTASK_SEMAPHORE_ALREADY_GIVEN - Indicates that the semaphore was already in a given state. This implicitly means that the encapsulated task is still in execution RETCODE_INVALID_PARAM - Given parameter was invalid
Referenced by AdcIRQCallback.