BCDS_UARTTransceiver.h
UART_TRANSCEIVER_DECLARE_LOOP_CALLBACK
Generates a UART loop callback.
The middle-layer driver, which uses UART/LEUART and UARTTransceiver, may use this macro in oder to generate a callback function to initialize UART/LEUART with it. The generated function loops the callback to the transceiver by calling the function UARTTransceiver_LoopCallback(). transceiver The variable name of the transceiver. It must be a pointer to the context structure but the context structure itself.
UARTTransceiver_Mode_E
UARTTransceiver_State_E
UARTTransceiver_UartType_E
typedef void(* UARTransceiver_Callback_T)(struct MCU_UART_Event_S event))(struct MCU_UART_Event_S event)
typedef bool(* UARTTransceiver_EndofFrameCheckFunc_T)(uint8_t lastByte))(uint8_t lastByte)
typedef struct _UARTTransceiver_S UARTTransceiver_T
Retcode_T UARTTransceiver_Deinitialize(UARTTransceiver_T *transceiver)
De-initializes the transceiver.
The transceiver must not be used after calling this function. transceiver a pointer to the transceiver context structure to be de-initialized RETCODE_OK if successfully deinitialize RETCODE_INVALID_PARAM if the transceiver pointer parameter is NULL
Referenced by ExtensionUartExample_DeInitialize.
Retcode_T UARTTransceiver_Initialize(UARTTransceiver_T *transceiver, HWHandle_T handle, uint8_t *rawRxBuffer, uint32_t rawRxBufferSize, enum UARTTransceiver_UartType_E type)
Initializes the transceiver for the use with the passed UART or LEUART handle.
transceiver a pointer to the transceiver context structure to be initialized handle the handle of the UART or LEUART to be used by the transceiver. The handle must be initialized before passing it here. mode The mode in which the transceiver will operate, i.e. synchronous or asynchronous. @ rawRxBuffer The buffer which will be used by the transceiver internally to save the received bytes. It must not be NULL. rawRxBufferSize The size of the rawRxBuffer. It must be larger than zero. RETCODE_OK if successfully initialized RETCODE_INVALID_PARAM if any of the parameter is NULL RETCODE_SEMAPHORE_ERROR if the semaphores are not created (see UARTTransceiver_T.TxSemaphore and UARTTransceiver_T.RxSemaphore) RETCODE_DOPPLE_INITIALIZATION if you are trying to initialized the transceiver again
Referenced by ExtensionUartExample_Initialize.
void UARTTransceiver_LoopCallback(UARTTransceiver_T *transceiver, struct MCU_UART_Event_S event)
Function to loop the UART/LEUART callback.
It is necessary for the UARTTransceiver to loop the UART/LEUART callback. This means, the middle-layer driver which uses UART/LEUART and UARTTransceiver must initialize UART/LEUART with a callback function which invokes this function in order to loop the callbacks from UART/LEUART to the transceiver.The middle-layer driver may use the macro UART_TRANSCEIVER_DECLARE_LOOP_CALLBACK can be used to generate such a callback. transceiver The transceiver event The event which is notified by the callback
Referenced by UartCallBack.
Retcode_T UARTTransceiver_ReadData(UARTTransceiver_T *transceiver, uint8_t *buffer, uint32_t size, uint32_t *length, uint32_t timeout_ms)
It reads the data received by the transceiver.
The transceiver must be started and not suspended when calling this function.In the synchronous mode, this call will return only after the End-of-Frame check function which is used by the transceiver returns true. This holds even if the number of the received bytes exceeds the given buffer size. In the asynchronous mode, the function copies the bytes which have been already received an returns immediately. In both cases, the number bytes saved to the given buffer never exceeds the given buffer size. If more bytes are available in the transceiver internal buffer, they will reside there. transceiver a pointer to the transceiver buffer The buffer which the bytes are copied to. size The buffer size. Independent of the number of the bytes which the transceiver has received, no more bytes are saved to the given buffer than the given size. length The number of received bytes which were saved to the given buffer. timeout_ms in synchronous modeThe function will return with an error if this time elapsed before receiving the end of frame character RETCODE_OK if successfully started RETCODE_INVALID_PARAM if any parameter is NULL RETCODE_INCONSITENT_STATE if the transceiver is not in an active state (see UARTTransceiver_State_E) RETCODE_SEMAPHORE_ERROR if semaphore could not be taken with given timeout (see UARTTransceiver_T.RxSemaphore)
Referenced by ExtensionUartExample_Read.
Retcode_T UARTTransceiver_Resume(UARTTransceiver_T *transceiver)
It resumes the transceiver after it has been suspended.
The transceiver must be suspended when calling this function. transceiver a pointer to the transceiver to be resumed. RETCODE_OK if successfully started RETCODE_INVALID_PARAM if transceiver pointer parameter is NULL RETCODE_INCONSITENT_STATE if the transceiver is not in an suspended state (see UARTTransceiver_State_E)
Retcode_T UARTTransceiver_Start(UARTTransceiver_T *transceiver, UARTTransceiver_EndofFrameCheckFunc_T frameEndCheckFunc)
It activates the transceiver to start receiving and sending in the synchronous operation mode.
transceiver a pointer to the transceiver to be started. frameEndCheckFunc A function pointer which is used by the transceiver to detect the end of the frame in order to invoke the callback. RETCODE_OK if successfully started RETCODE_INVALID_PARAM if transceiver pointer parameter is NULL RETCODE_INCONSITENT_STATE if the transceiver is not in an initialized state (see UARTTransceiver_State_E)
Retcode_T UARTTransceiver_StartInAsyncMode(UARTTransceiver_T *transceiver, UARTTransceiver_EndofFrameCheckFunc_T frameEndCheckFunc, UARTransceiver_Callback_T callback)
It activates the transceiver to start receiving and sending in the asynchronous operation mode.
Beside the operation mode, this function does the same as the function UARTTransceiver_Start(). transceiver a pointer to the transceiver to be started. frameEndCheckFunc A function pointer which is used by the transceiver to detect the end of the frame in order to invoke the callback. callback A callback function which will be invoked on RX and TX events, e.g. errors or operation completeness in the asynchronous mode. RETCODE_OK if successfully started RETCODE_INVALID_PARAM if transceiver pointer parameter is NULL RETCODE_INCONSITENT_STATE if the transceiver is not in an initialized state (see UARTTransceiver_State_E)
Referenced by ExtensionUartExample_Initialize.
Retcode_T UARTTransceiver_Stop(UARTTransceiver_T *transceiver)
It stops the transceiver.
The transceiver must be started when calling this function. When the transceiver is stopped, read or write operations are not permitted. Resuming the transceiver after stopping it is not possible. It must be started using the UARTTransceiver_Start() function. transceiver a pointer to the transceiver to be suspended. RETCODE_OK if successfully started RETCODE_INVALID_PARAM if transceiver pointer parameter is NULL RETCODE_INCONSITENT_STATE if the transceiver is not in an active or already suspended state (see UARTTransceiver_State_E)
Retcode_T UARTTransceiver_Suspend(UARTTransceiver_T *transceiver)
It suspends the transceiver.
The transceiver must be started when calling this function. When the transceiver is suspended read or write operations are not permitted. transceiver a pointer to the transceiver to be suspended. RETCODE_OK if successfully started RETCODE_INVALID_PARAM if transceiver pointer parameter is NULL RETCODE_INCONSITENT_STATE if the transceiver is not in an active state (see UARTTransceiver_State_E)
Retcode_T UARTTransceiver_WriteData(UARTTransceiver_T *transceiver, uint8_t *data, uint32_t length, uint32_t timeout_ms)
It writes the data for sending.
The transceiver must be started and not suspended when calling this function.In the synchronous mode, this call will return only after the passed bytes have been send over UART/LEUART. In the asynchronous mode, the function triggers the sending and returns immediately. A callback follows to inform about the success or failure of the send operation. transceiver a pointer to the transceiver buffer The buffer which the bytes are copied to. length The buffer length and the number of bytes to be copied. timeout_ms The time afterwhich if the function does not succeed for any reason it will return an semaphore error. RETCODE_OK if successfully started RETCODE_INVALID_PARAM if any parameter is NULL RETCODE_INCONSITENT_STATE if the transceiver is not in an active state (see UARTTransceiver_State_E) RETCODE_SEMAPHORE_ERROR if semaphore could not be taken with given timeout (see UARTTransceiver_T.TxSemaphore)
Referenced by ExtensionUartExample_Write.