BCDS_CmdProcessor.h
CMDPROCESSOR_MAX_NAME_LEN
Maximum length of command processor task name including 0 termination char
CmdProcessor_Retcode_E
typedef void(* CmdProcessor_Func_T)(void *param1, uint32_t param2))(void *param1, uint32_t param2)
This data type represents a function pointer for the functions which can be handled by the command processor.
The return value of the command processor function is void. Exceptions must be handled within the function itself. *param1 - a generic pointer to any context data structure which will be passed to the function when it is invoked by the command processor. param2 - a generic 32 bit value which will be passed to the function when it is invoked by the command processor..
typedef struct _CmdProcessor_S CmdProcessor_T
The Command Processor handle data type. The structure itself is hidden in the source file.
typedef void* cmdProcessorQueueHandle_t
typedef void* cmdProcessorTaskHandle_t
BCDS_DEPRECATED(Retcode_T CmdProcessor_initialize(CmdProcessor_T *cmdProcessor, char *name, uint32_t taskPriority, uint32_t taskStackDepth, uint32_t queueSize))
This function initializes the command processor instance. It creates a queue which will carry the command functions and a task which will process the queue.
Deprecatedsince version vxx.xx.xx, replaced by CmdProcessor_Initialize CmdProcessor_T*cmdProcessor=CmdProcessor_getSingleton(); CmdProcessor_Initialize(&cmdProcessor,"AppCmdProcessor",...); Please take care while assigning the priority to command processor task, it should be less than scheduler timer task priority. Command processor does not support the delegation from ISR because it falls under the application tasks and application task should be operated at least priority compare to ISR and RTOS(timer service). cmdProcessor - contains the queue and task handles name - represents the task name taskPriority - represents the task priority taskStackDepth - Represents the stack Size for the task queueSize - Represents the queue Size RETCODE_OK when the queue is created successfully RETCODE_NULL_POINTER when the task or queue is not created
BCDS_DEPRECATED(Retcode_T CmdProcessor_enqueue(CmdProcessor_T *cmdProcessor, CmdProcessor_Func_T func, void *param1, uint32_t param2))
This routine is used to hand-over a function to the command processor for execution. The function is added to the queue which is processed in a FIFO manner.
This routine is used to hand-over a function to the command processor from ISR context. The function is added to the queue which is processed in a FIFO manner.Deprecatedsince version vxx.xx.xx, replaced by CmdProcessor_Enqueue This routine should be called after CmdProcessor_Initialize function. Hand-over Function prototype should be same as cmdprocess_fun_t cmdProcessor - contains the queue handle func - represents the function param1 - a generic pointer to an arbitrary context data structure which will be passed to the function when it is invoked by the command processor. param2 - second argument of the function RETCODE_OK when the function is pushed successfully into the queue RETCODE_INVALID_PARAM when cmdProcessor or function pointers is NULL RETCODE_FAILURE when the queue is full Deprecatedsince version vxx.xx.xx, replaced by CmdProcessor_EnqueueFromIsr This routine should be called after cmdprocessor_intitialize function. Hand-over Function prototype should be same as cmdprocess_fun_t cmdProcessor - contains the queue handle func - represents the function param1 - a generic pointer to an arbitrary context data structure which will be passed to the function when it is invoked by the command processor. param2 - second argument of the function RETCODE_OK when the function is pushed successfully into the queue RETCODE_INVALID_PARAM when cmdProcessor or function pointers is NULL RETCODE_FAILURE when the queue is full
BCDS_DEPRECATED(void CmdProcessor_suspend(CmdProcessor_T *cmdProcessor))
The API suspends the command processor service. It is used to stop the execution of the command processor task functionality.
The API resumes the command processor service. It is used to execute the suspended command processor task functionality.Deprecatedsince version vxx.xx.xx, replaced by CmdProcessor_Suspend cmdProcessor - Holds the command processor task handle Deprecatedsince version vxx.xx.xx, replaced by CmdProcessor_Resume cmdProcessor - Holds the command processor task handle
Retcode_T CmdProcessor_Enqueue(CmdProcessor_T *cmdProcessor, CmdProcessor_Func_T func, void *param1, uint32_t param2)
This routine is used to hand-over a function to the command processor for execution. The function is added to the queue which is processed in a FIFO manner.
This routine should be called after cmdprocessor_intitialize function. Hand-over Function prototype should be same as cmdprocess_fun_t cmdProcessor - contains the queue handle func - represents the function param1 - a generic pointer to an arbitrary context data structure which will be passed to the function when it is invoked by the command processor. param2 - second argument of the function RETCODE_OK when the function is pushed successfully into the queue RETCODE_INVALID_PARAM when cmdProcessor or function pointers is NULL RETCODE_FAILURE when the queue is full
Referenced by AppControllerFire, AppControllerEnable, AppControllerSetup, AppController_Init, AppControllerBleDataRxCB, main, ProcessUartTxData.
Retcode_T CmdProcessor_EnqueueFromIsr(CmdProcessor_T *cmdProcessor, CmdProcessor_Func_T func, void *param1, uint32_t param2)
This routine is used to hand-over a function to the command processor from ISR context. The function is added to the queue which is processed in a FIFO manner.
This routine should be called after cmdprocessor_intitialize function. Hand-over Function prototype should be same as cmdprocess_fun_t cmdProcessor - contains the queue handle func - represents the function param1 - a generic pointer to an arbitrary context data structure which will be passed to the function when it is invoked by the command processor. param2 - second argument of the function RETCODE_OK when the function is pushed successfully into the queue RETCODE_INVALID_PARAM when cmdProcessor or function pointers is NULL RETCODE_FAILURE when the queue is full
Referenced by GpioInterruptCallback, UartAppCallback.
Retcode_T CmdProcessor_Initialize(CmdProcessor_T *cmdProcessor, char *name, uint32_t taskPriority, uint32_t taskStackDepth, uint32_t queueSize)
This function initializes the command processor instance. It creates a queue which will carry the command functions and a task which will process the queue.
CmdProcessor_T*cmdProcessor=CmdProcessor_getSingleton(); CmdProcessor_Initialize(&cmdProcessor,"AppCmdProcessor",...); Please take care while assigning the priority to command processor task, it should be less than scheduler timer task priority. Command processor does not support the delegation from ISR because it falls under the application tasks and application task should be operated at least priority compare to ISR and RTOS(timer service). cmdProcessor - contains the queue and task handles name - represents the task name taskPriority - represents the task priority taskStackDepth - Represents the stack Size for the task queueSize - Represents the queue Size RETCODE_OK when the queue is created successfully RETCODE_NULL_POINTER when the task or queue is not created
Referenced by main, ServalPalSetup.
void CmdProcessor_Resume(CmdProcessor_T *cmdProcessor)
The API resumes the command processor service. It is used to execute the suspended command processor task functionality.
cmdProcessor - Holds the command processor task handle
void CmdProcessor_Suspend(CmdProcessor_T *cmdProcessor)
The API suspends the command processor service. It is used to stop the execution of the command processor task functionality.
cmdProcessor - Holds the command processor task handle