BCDS_Max44009.h
MAX09_ConfigMode_E
Manual mode disable
MAX44009_ConfigBrightness_E
normal brightness
MAX44009_ConfigStatus_E
indicates the disabled state
MAX44009_IntegrationTime_E
800 ms integration time(time taken for capturing lux intensity)
MAX44009_IntrpStatus_E
no interrupt event triggered
MAX44009_Registers_E
interrupt status register
typedef enum MAX44009_IntrpStatus_E MAX09_IntrpStatus_T
typedef enum MAX44009_ConfigBrightness_E MAX44009_ConfigBrightness_T
typedef enum MAX44009_ConfigBrightness_E * MAX44009_ConfigBrightnessPtr_T
typedef enum MAX09_ConfigMode_E MAX44009_ConfigMode_T
typedef enum MAX09_ConfigMode_E * MAX44009_ConfigModePtr_T
typedef enum MAX44009_ConfigStatus_E MAX44009_ConfigStatus_T
typedef void(* MAX44009_delayFunc)(uint32_t timeInMs))(uint32_t timeInMs)
Delay function prototype.
timeInMs time in milliseconds
typedef struct MAX44009_Init_S MAX44009_Init_T
typedef struct MAX44009_Init_S * MAX44009_InitPtr_T
typedef enum MAX44009_IntegrationTime_E MAX44009_IntegrationTime_T
typedef enum MAX44009_IntegrationTime_E * MAX44009_IntegrationTimePtr_T
typedef struct MAX44009_ManualModeConfig_S MAX44009_ManualModeConfig_T
typedef int8_t(* MAX44009_readReg)(uint8_t dev_addr, uint8_t reg_addr, uint8_t *data_p, uint8_t r_len))(uint8_t dev_addr, uint8_t reg_addr, uint8_t *data_p, uint8_t r_len)
Sensor register Read function prototype.
dev_addr device address reg_addr register address data_p data wr_len length of the data int8_t 0 Success -1 Fail
typedef enum MAX44009_Registers_E MAX44009_Registers_T
typedef int8_t(* MAX44009_writeReg)(uint8_t dev_addr, uint8_t reg_addr, uint8_t *data_p, uint8_t wr_len))(uint8_t dev_addr, uint8_t reg_addr, uint8_t *data_p, uint8_t wr_len)
Sensor register write function prototype.
dev_addr device address reg_addr register address data_p data wr_len length of the data int8_t 0 Success -1 Fail
BCDS_DEPRECATED(Retcode_T MAX44009_init(MAX44009_InitPtr_T configParams))
The function to initialize the ambient light sensor. It initializes and preserves the i2c address and i2c bus read , write functions for further communication between the sensor and the controller.
Deprecatedsince version vxx.xx.xx, replaced by MAX44009_Init configParams configuration parameters RETCODE_OK MAX44009 Light sensor initialization success. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
BCDS_DEPRECATED(Retcode_T MAX44009_setCdr(MAX44009_ConfigBrightness_T cdr))
The function to set the CDR value of the Configuration register Api to configure the desired photodiode current that goes to ADC.
Deprecatedsince version vxx.xx.xx, replaced by MAX44009_SetCdr cdr CDR value(from the provided enum value) RETCODE_OK Setting cdr for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid CDR value. In case of any other error refer MAX44009_GetConfigurationReg error codes. reflects the configured value only if Manual mode is enabled The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
BCDS_DEPRECATED(Retcode_T MAX44009_getCdr(uint8_t *cdr))
The function to get the configured CDR value.
Deprecatedsince version vxx.xx.xx, replaced by MAX44009_GetCdr cdr configured cdr value RETCODE_OK Getting cdr for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid CDR value. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
BCDS_DEPRECATED(Retcode_T MAX44009_getConfigurationReg(uint8_t *configuredVal))
The function to get the configuration register value.
Deprecatedsince version vxx.xx.xx, replaced by MAX44009_GetConfigurationReg configuredVal the read configuration register value. RETCODE_OK Getting the configuration register value for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
BCDS_DEPRECATED(Retcode_T MAX44009_setIntegrationTime(MAX44009_IntegrationTime_T time))
The function to set the integration time of the sensor.
Deprecatedsince version vxx.xx.xx, replaced by MAX44009_SetIntegrationTime time integration time RETCODE_OK Configuration of integration time for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. In case of any other error refer MAX44009_GetConfigurationReg error codes. reflects the configured value only if Manual mode is enabled The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
BCDS_DEPRECATED(Retcode_T MAX44009_getIntegrationTime(uint8_t *time))
The function to get the configured integration time value.
Deprecatedsince version vxx.xx.xx, replaced by MAX44009_GetIntegrationTime time configured time RETCODE_OK Getting of integration time for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. In case of any other error refer MAX44009_GetConfigurationReg error codes. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
BCDS_DEPRECATED(Retcode_T MAX44009_getSensorData(uint16_t *sensorData))
The function to get the light sensor values in LUX.
Deprecatedsince version vxx.xx.xx, replaced by MAX44009_GetSensorData sensorData raw sensor data represented in the 16 bit output format [0 0 0 0 E3 E2 E1 E0 M7 M6 M5 M4 M3 M2 M1 M0] from [bit 15 to bit 0]. M7-M0:Mantissa and E3-E0:Exponent RETCODE_OK Getting the MAX44009 Light sensor value successful. RETCODE_INVALID_PARAM Invalid sensor data. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
BCDS_DEPRECATED(uint32_t MAX44009_getDataInMilliLux(uint16_t sensorData))
The function to convert the Raw sensor value to Milli Lux.
Deprecatedsince version vxx.xx.xx, replaced by MAX44009_GetDataInMilliLux sensorData raw sensor value sensorData sensor value in milli lux RETCODE_OK Converting the raw MAX44009 Light sensor value to Milli Lux successful.
BCDS_DEPRECATED(Retcode_T MAX44009_setUpperThreshold(uint8_t thresholdVal))
Function used to set the upper threshold level of the sensor.
Function to set the lower threshold level of the sensor.Deprecatedsince version vxx.xx.xx, replaced by MAX44009_SetUpperThreshold thresholdVal Threshold value that to be configured RETCODE_OK Setting the Upper threshold level for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Deprecatedsince version vxx.xx.xx, replaced by MAX44009_SetLowerThreshold thresholdVal threshold value that to be configured RETCODE_OK Setting the lower threshold level for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
BCDS_DEPRECATED(Retcode_T MAX44009_getUpperThreshold(uint8_t *thresholdVal))
Function to get the upper threshold value.
Function to get the Lower threshold value.Deprecatedsince version vxx.xx.xx, replaced by MAX44009_GetUpperThreshold thresholdVal the upper threshold value RETCODE_OK Getting the upper threshold level for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Deprecatedsince version vxx.xx.xx, replaced by MAX44009_GetLowerThreshold thresholdVal the Lower threshold value RETCODE_OK Getting the lower threshold level for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
BCDS_DEPRECATED(Retcode_T MAX44009_setThresholdTimer(uint8_t thresholdTimerVal))
Function used to set the threshold timer.
Deprecatedsince version vxx.xx.xx, replaced by MAX44009_SetThresholdTimer thresholdTimerVal threshold timer value(100ms) that to be configured. RETCODE_OK Setting the threshold timer for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
BCDS_DEPRECATED(Retcode_T MAX44009_getThresholdTimer(uint8_t *thresholdTimerVal))
Function to get the threshold timer register value.
Deprecatedsince version vxx.xx.xx, replaced by MAX44009_GetThresholdTimer thresholdTimerVal threshold timer value in 100ms. RETCODE_OK Getting the threshold timer for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
BCDS_DEPRECATED(Retcode_T MAX44009_setContinousModeReg(MAX44009_ConfigMode_T configParam))
The function to set Continuous mode MAX44009_DISABLE_CONTINOUS_MOD(default mode): the IC measures lux intensity only once every 800ms regardless of integration time MAX44009_ENABLE_CONTINOUS_MODE : The IC continuously measures lux intensity. That is, as soon as one reading is finished, a new one begins. If integration time is 6.25ms, readings are taken every 6.25ms If integration time is 800ms,readings are taken every 800ms.
The function to configure interrupt.The function to set Manual mode MAX44009_ENABLE_MANUAL_MODE : CDR, and TIM[2:0] bits can be programmed, MAX44009_DISABLE_MANUAL_MODE((default mode)) : CDR, TIM[2:0] bits are automatically determined by the internal autoranging circuitry of the IC.Deprecatedsince version vxx.xx.xx, replaced by MAX44009_SetContinousModeReg configParam value of the continuous mode. RETCODE_OK Setting the Continuous mode for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. In case of any other error refer MAX44009_GetConfigurationReg error codes. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Deprecatedsince version vxx.xx.xx, replaced by MAX44009_SetManualModeReg configParam value of the manual mode. RETCODE_OK Setting the manual mode for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. In case of any other error refer MAX44009_GetConfigurationReg error codes. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Deprecatedsince version vxx.xx.xx, replaced by MAX44009_SetIntrptReg configParam interrupt configured value. RETCODE_OK Configuring the interrupt status for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
BCDS_DEPRECATED(Retcode_T MAX44009_getContinousModeReg(uint8_t *configParams))
The function to get the Continuous mode.
The function to get Manual mode.Deprecatedsince version vxx.xx.xx, replaced by MAX44009_GetContinousModeReg configParams gets the continuous mode value. RETCODE_OK Getting the Continuous mode for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. In case of any other error refer MAX44009_GetConfigurationReg error codes. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Deprecatedsince version vxx.xx.xx, replaced by MAX44009_GetManualModeReg configParams value of the manual mode. RETCODE_OK Getting the manual mode for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. In case of any other error refer MAX44009_GetConfigurationReg error codes. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
BCDS_DEPRECATED(Retcode_T MAX44009_getInterptStatus(uint8_t *status))
The function to get the interrupt status.
Deprecatedsince version vxx.xx.xx, replaced by MAX44009_GetInterptStatus status the interrupt triggered event status. RETCODE_OK Getting the interrupt status for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
BCDS_DEPRECATED(Retcode_T MAX44009_getIntrptReg(MAX44009_ConfigModePtr_T configParam))
The function to get interrupt register value.
Deprecatedsince version vxx.xx.xx, replaced by MAX44009_GetIntrptReg configParam configured value. RETCODE_OK Getting the interrupt status for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
BCDS_DEPRECATED(Retcode_T MAX44009_getRegister(MAX44009_Registers_T regAddress, uint8_t *value))
The function to get a register value.
Deprecatedsince version vxx.xx.xx, replaced by MAX44009_GetRegister regAddress register address that to be read value configured value. RETCODE_OK Getting the register value for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
BCDS_DEPRECATED(Retcode_T MAX44009_setRegister(MAX44009_Registers_T regAddress, uint8_t value))
The function to set a register value.
Deprecatedsince version vxx.xx.xx, replaced by MAX44009_SetRegister regAddress register address that to be write value the value that to be configured RETCODE_OK Setting the register value for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
BCDS_DEPRECATED(void MAX44009_deInit(void))
The function to deinitialize the sensor.
Deprecatedsince version vxx.xx.xx, replaced by MAX44009_DeInit
void MAX44009_DeInit(void)
The function to deinitialize the sensor.
Referenced by Max44009Utils_uninitialize.
Retcode_T MAX44009_GetCdr(uint8_t *cdr)
The function to get the configured CDR value.
cdr configured cdr value RETCODE_OK Getting cdr for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid CDR value. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
Retcode_T MAX44009_GetConfigurationReg(uint8_t *configuredVal)
The function to get the configuration register value.
configuredVal the read configuration register value. RETCODE_OK Getting the configuration register value for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
Retcode_T MAX44009_GetContinousModeReg(uint8_t *configParams)
The function to get the Continuous mode.
configParams gets the continuous mode value. RETCODE_OK Getting the Continuous mode for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. In case of any other error refer MAX44009_GetConfigurationReg error codes. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
uint32_t MAX44009_GetDataInMilliLux(uint16_t sensorData)
The function to convert the Raw sensor value to Milli Lux.
sensorData raw sensor value sensorData sensor value in milli lux RETCODE_OK Converting the raw MAX44009 Light sensor value to Milli Lux successful.
Referenced by LightSensor_readLuxData.
Retcode_T MAX44009_GetIntegrationTime(uint8_t *time)
The function to get the configured integration time value.
time configured time RETCODE_OK Getting of integration time for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. In case of any other error refer MAX44009_GetConfigurationReg error codes. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
Retcode_T MAX44009_GetInterptStatus(uint8_t *status)
The function to get the interrupt status.
status the interrupt triggered event status. RETCODE_OK Getting the interrupt status for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
Referenced by LightSensor_getInterruptStatus.
Retcode_T MAX44009_GetIntrptReg(MAX44009_ConfigModePtr_T configParam)
The function to get interrupt register value.
configParam configured value. RETCODE_OK Getting the interrupt status for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
Retcode_T MAX44009_GetLowerThreshold(uint8_t *thresholdVal)
Function to get the Lower threshold value.
thresholdVal the Lower threshold value RETCODE_OK Getting the lower threshold level for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
Retcode_T MAX44009_GetManualModeReg(uint8_t *configParams)
The function to get Manual mode.
configParams value of the manual mode. RETCODE_OK Getting the manual mode for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. In case of any other error refer MAX44009_GetConfigurationReg error codes. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
Retcode_T MAX44009_GetRegister(MAX44009_Registers_T regAddress, uint8_t *value)
The function to get a register value.
regAddress register address that to be read value configured value. RETCODE_OK Getting the register value for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
Retcode_T MAX44009_GetSensorData(uint16_t *sensorData)
The function to get the light sensor values in LUX.
sensorData raw sensor data represented in the 16 bit output format [0 0 0 0 E3 E2 E1 E0 M7 M6 M5 M4 M3 M2 M1 M0] from [bit 15 to bit 0]. M7-M0:Mantissa and E3-E0:Exponent RETCODE_OK Getting the MAX44009 Light sensor value successful. RETCODE_INVALID_PARAM Invalid sensor data. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
Referenced by LightSensor_readRawData, LightSensor_readLuxData.
Retcode_T MAX44009_GetThresholdTimer(uint8_t *thresholdTimerVal)
Function to get the threshold timer register value.
thresholdTimerVal threshold timer value in 100ms. RETCODE_OK Getting the threshold timer for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
Retcode_T MAX44009_GetUpperThreshold(uint8_t *thresholdVal)
Function to get the upper threshold value.
thresholdVal the upper threshold value RETCODE_OK Getting the upper threshold level for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
Retcode_T MAX44009_Init(MAX44009_InitPtr_T configParams)
The function to initialize the ambient light sensor. It initializes and preserves the i2c address and i2c bus read , write functions for further communication between the sensor and the controller.
configParams configuration parameters RETCODE_OK MAX44009 Light sensor initialization success. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
Referenced by Max44009Utils_initialize.
Retcode_T MAX44009_SetCdr(MAX44009_ConfigBrightness_T cdr)
The function to set the CDR value of the Configuration register Api to configure the desired photodiode current that goes to ADC.
cdr CDR value(from the provided enum value) RETCODE_OK Setting cdr for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid CDR value. In case of any other error refer MAX44009_GetConfigurationReg error codes. reflects the configured value only if Manual mode is enabled The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
Referenced by LightSensor_setBrightness, Max44009Utils_initialize.
Retcode_T MAX44009_SetContinousModeReg(MAX44009_ConfigMode_T configParam)
The function to set Continuous mode MAX44009_DISABLE_CONTINOUS_MOD(default mode): the IC measures lux intensity only once every 800ms regardless of integration time MAX44009_ENABLE_CONTINOUS_MODE : The IC continuously measures lux intensity. That is, as soon as one reading is finished, a new one begins. If integration time is 6.25ms, readings are taken every 6.25ms If integration time is 800ms,readings are taken every 800ms.
configParam value of the continuous mode. RETCODE_OK Setting the Continuous mode for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. In case of any other error refer MAX44009_GetConfigurationReg error codes. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
Referenced by LightSensor_setContinuousMode, Max44009Utils_initialize.
Retcode_T MAX44009_SetIntegrationTime(MAX44009_IntegrationTime_T time)
The function to set the integration time of the sensor.
time integration time RETCODE_OK Configuration of integration time for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. In case of any other error refer MAX44009_GetConfigurationReg error codes. reflects the configured value only if Manual mode is enabled The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
Referenced by LightSensor_setIntegrationTime, Max44009Utils_initialize.
Retcode_T MAX44009_SetIntrptReg(MAX44009_ConfigMode_T configParam)
The function to configure interrupt.
configParam interrupt configured value. RETCODE_OK Configuring the interrupt status for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
Referenced by configureThresholdInterrupt, Max44009Utils_disableInterrupt.
Retcode_T MAX44009_SetLowerThreshold(uint8_t thresholdVal)
Function to set the lower threshold level of the sensor.
thresholdVal threshold value that to be configured RETCODE_OK Setting the lower threshold level for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
Referenced by configureThresholdInterrupt.
Retcode_T MAX44009_SetManualModeReg(MAX44009_ConfigMode_T configParam)
The function to set Manual mode MAX44009_ENABLE_MANUAL_MODE : CDR, and TIM[2:0] bits can be programmed, MAX44009_DISABLE_MANUAL_MODE((default mode)) : CDR, TIM[2:0] bits are automatically determined by the internal autoranging circuitry of the IC.
configParam value of the manual mode. RETCODE_OK Setting the manual mode for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. In case of any other error refer MAX44009_GetConfigurationReg error codes. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
Referenced by LightSensor_setManualMode.
Retcode_T MAX44009_SetRegister(MAX44009_Registers_T regAddress, uint8_t value)
The function to set a register value.
regAddress register address that to be write value the value that to be configured RETCODE_OK Setting the register value for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
Retcode_T MAX44009_SetThresholdTimer(uint8_t thresholdTimerVal)
Function used to set the threshold timer.
thresholdTimerVal threshold timer value(100ms) that to be configured. RETCODE_OK Setting the threshold timer for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
Referenced by configureThresholdInterrupt.
Retcode_T MAX44009_SetUpperThreshold(uint8_t thresholdVal)
Function used to set the upper threshold level of the sensor.
thresholdVal Threshold value that to be configured RETCODE_OK Setting the Upper threshold level for MAX44009 Light sensor successful. RETCODE_INVALID_PARAM Invalid configuration parameter. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
Referenced by configureThresholdInterrupt.