BCDS_WlanNetworkConnect.h
WLANNWCT_DUMMY_SSID
macro to represent the ssid of the device in WPS_PBC and WPS_PIN Security mode
WLANNWCT_ENROLLEE_PIN
This is the Enrollee PIN that must be entered in the router for WPS PIN Connection. The pin code is stored in the SFlash. The default pin code is 35072317.
WLANNWCT_INITIALZED
Macro to represent Initialized state of Wlan
WLANNWCT_MAX_MAC_ADDR_LEN
The max buffer for storing the MAC address length
WLANNWCT_MAX_SCAN_INFO_BUF
The max buffer for storing the scan data
Referenced by ScanNetwork.
WLANNWCT_MAX_SSID_LENGTH
The max buffer for storing the SSID length
WLANNWCT_NOT_INITIALZED
Macro to represent un-Initialized state of Wlan Macro to represent the blocking connection request timeout
WLANNWCT_TIMEOUT_SEC
WlanNetworkConnect_IpStatus_E
Connected and IPV4 address acquired
WlanNetworkConnect_PwrCtrl_E
Lowest power mode. Memories are not retained and only RTC will run.
WlanNetworkConnect_Retcode_E
No available networks
WlanNetworkConnect_Status_E
Wlan status Connected
typedef unsigned long(WlanNetworkConnect_ScanInterval_T)(WlanNetworkConnect_ScanInterval_T)
Type defining scan interval. This type is used for WlanNetworkConnect_scanNetworks function
typedef void(* WlanNetworkConnect_Callback_T)(WlanNetworkConnect_Status_T connectStatus))(WlanNetworkConnect_Status_T connectStatus)
Type defining the prototype which connection call back must conform to. This call back is called to notify the user when connection is established or Disconnection occurs. Returns the connection status as a parameter
typedef enum WlanNetworkConnect_IpStatus_E WlanNetworkConnect_IpStatus_T
typedef signed char* WlanNetworkConnect_PassPhrase_T
Type defining a pointer to char This type is used in order to pass the network Pass Phrase
typedef enum WlanNetworkConnect_PwrCtrl_E WlanNetworkConnect_PwrCtrl_T
typedef enum WlanNetworkConnect_Retcode_E WlanNetworkConnect_Retcode_T
typedef struct WlanNetworkConnect_ScanInfo_S WlanNetworkConnect_ScanInfo_T
typedef struct WlanNetworkConnect_ScanList_S WlanNetworkConnect_ScanList_T
typedef signed char* WlanNetworkConnect_SSID_T
Type defining a pointer to char. This type is used in order to pass the network SSID
typedef enum WlanNetworkConnect_Status_E WlanNetworkConnect_Status_T
typedef signed char* WlanNetworkConnect_Username_T
Type defining a pointer to char. This type is used in order to pass the network Username
Retcode_T WlanNetworkConnect_DeInit(void)
WLAN driver de-initialization function. Performs memory deallocation, closes WLAN driver context and shuts down the hardware interfaces.
none Retcode_T The return value consist of (First 1 MSByte represents Package ID, Next Byte represents Severity and Last 2 LSBytes represents error code) Below shows the error code(last 2 Bytes) meaning RETCODE_OK - Successfully WLAN driver de-initialized. RETCODE_SIMPLELINK_ERROR - De-initializing WLAN driver failed RETCODE_UNEXPECTED_BEHAVIOR - FreeRTOS timer delete failure Example1 usage: Deinitialize the WLAN Stack //DeinitializeWLANstack WlanNetworkConnect_DeInit(); Example2 usage: Restart Device //Callbackfunction voidmyConnectCallbackFunc(WlanNetworkConnect_Status_TreturnStatus) { if(WLANNWCT_STATUS_DISCONNECTED==returnStatus) { //Networkdis-connectionsuccessfully printf("CallbackFunction:DisConnectOK!\n\r"); //Usermayaddlogiconcetheconnectionisdone //E.glaunchanotherOSTimer } else { //usermayretrytoconnect } } Retcode_TretStatus; //InitializeWLANdriverandWLANstack retStatus=WlanNetworkConnect_Init(myConnectCallbackFunc); if(RETCODE_OK!=retStatus) { printf("WLANdriverinitializationfailure"); } //LocalAPIreturnstatus Retcode_TretStatus[2]; retStatus[0]=WlanNetworkConnect_DeInit(); retStatus[1]=WlanNetworkConnect_Init(myConnectCallbackFunc); //Checkifdevicerestarthasfinishedwitherror if((RETCODE_OK!=retStatus[0])||(RETCODE_OK!=retStatus[1])) { printf("Restartdevicefailed"); }
Referenced by WlanConnect_DeInit.
Retcode_T WlanNetworkConnect_DeleteAllProfiles(void)
WLAN Delete All Profiles interface. This function erases from memory all the stored profiles from WIFI Protected Setup functions.
none RETCODE_OK - successfully erased all profiles. RETCODE_SIMPLELINK_ERROR - error during erase Retcode_T The return value consist of (First 1 MSByte represents Package ID, Next Byte represents Severity and Last 2 LSBytes represents error code) Below shows the error code(last 2 Bytes) meaning Example usage: Delete all stored WLAN profiles Retcode_TretStatus; retStatus=WlanNetworkConnect_DeleteAllProfiles(); if(RETCODE_OK!=retStatus) { printf("Profileswerenotdeletedcorrectly"); }
Retcode_T WlanNetworkConnect_Disconnect(void)
WLAN disconnect interface. This function disconnects from the WLAN network. Function is configurable in two ways: callback parameter is set to the address of the user function.
RETCODE_OK successfully disconnected from Access point. RETCODE_DISCONNECT_ERROR Error in disconnecting Retcode_T The return value consist of (First 1 MSByte represents Package ID, Next Byte represents Severity and Last 2 LSBytes represents error code) Below shows the error code(last 2 Bytes) meaning Example usage: Disconnect with callback (non-blocking) voidmyDisconnectCallbackFunc(WlanNetworkConnect_Status_TreturnStatus) { if(WLANNWCT_STATUS_CONNECTED==returnStatus) { //NetworkdisconnectionsuccessfullyfromWlanNetworkConnect_Disconnectfunction printf("CallbackFunction:DisconnectOK!\n\r"); } else { //usercanretry } } //localvariables Retcode_TretStatus; retStatus=WlanNetworkConnect_Init(myConnectCallbackFunc); if(RETCODE_OK==retStatus) { //disconnectfromnetworkinnon-blockingmode retStatus=WlanNetworkConnect_Disconnect(); if(RETCODE_OK==retStatus) { //Disconnecthascompletedsuccessfully printf("Disconnectedsuccessfully!\n\r"); } }
Referenced by SetAndGetIp.
Retcode_T WlanNetworkConnect_EnterpriseWPA(WlanNetworkConnect_SSID_T connectSSID, WlanNetworkConnect_Username_T connectUsername, WlanNetworkConnect_PassPhrase_T connectPassPhrase)
WLAN Connect to Enterprise WPA Network interface. This function connects to an WPA2-PSK or WPA-PSK network. Function is configurable in two ways:
blocking : callback parameter is set to NULL(maximum blocking in error case will be 15seconds)non-blocking : callback parameter is set to the address of the user function connectionSSID Pointer to char containing the network SSID to connect to. connectUsername Pointer to char containing the network Username to connect to. connectionPass Pointer to char containing the network Pass Phrase. RETCODE_OK - API return code for success. RETCODE_SIMPLELINK_ERROR - Failure returned by simplelink API. RETCODE_ERROR_SSID_NOT_FOUND - Failure because of incorrect SSID. RETCODE_ERROR_WRONG_PASSWORD - Failure because of incorrect Pass phrase. RETCODE_ERROR_IP_NOT_ACQ - Connected but ip not acquired Retcode_T The return value consist of (First 1 MSByte represents Package ID, Next Byte represents Severity and Last 2 LSBytes represents error code) Below shows the error code(last 2 Bytes) meaning It uses index 0 for certificate. The Host must have been programmed with the certificate in this Index prior. It uses PEAP0-MSCHAPv2 as EAP method. It uses the connectUsername for default and anonymous user names Example usage: Connect to Enterprise WPA/WPA2 network with callback (non-blocking) //Callbackfunction voidmyConnectCallbackFunc(WlanNetworkConnect_Status_TreturnStatus) { if(WLANNWCT_STATUS_CONNECTED==returnStatus) { //Networkconnectionsuccessfully printf("CallbackFunction:ConnectOK!\n\r"); //Usermayaddlogiconcetheconnectionisdone //E.glaunchanotherOSTimer } else { //usermayretrytoconnect } } //localvariables WlanNetworkConnect_SSID_TconnectSSID; Retcode_TretStatus; WlanNetworkConnect_PassPhrase_TconnectPassPhrase; //WPA/WPA2encryptedwirelessnetworksettings connectSSID=(WlanNetworkConnect_SSID_T)"WPA-NETWORK-NAME"; connectUsername=(WlanNetworkConnect_Username_T)"WPA-USERNAME-NAME"; connectPassPhrase=(WlanNetworkConnect_PassPhrase_T)"WPA-PASSWORD"; //Setcallbackfunctions connectCallback=myConnectCallbackFunc; //Connecttonetwork-->nonblockingfunctionwithcallback retStatus=WlanNetworkConnect_EnterpriseWPA(connectSSID,connectUsername,connectPassPhrase);
uint8_t WlanNetworkConnect_GetInitStatus(void)
Function to get the connection status. This function return the connection status.
none WLANNWCT_INITIALZED - Wlan module is initialized. WLANNWCT_NOT_INITIALZED - Wlan module is not initialized.
Referenced by WlanConnect_GetInitStatus.
WlanNetworkConnect_IpStatus_T WlanNetworkConnect_GetIpStatus(void)
Function to get the current network status This function sets a disconnect callback which is used to notify the user that there has been a disconnection that was not triggered by the user.ed on connection status.
This API must be called only after initialization allDisconnectCallback Pointer to user function callback. Returns the WLAN connection status as a parameter. WLANNWCT_IPSTATUS_CT_AQRD - currently WLAN connected and IP acquired. WLANNWCT_IPSTATUS_CT_NAQRD - currently WLAN connected and IP not acquired. WLANNWCT_IPSTATUS_DISCT_AQRD - currently WLAN disconnected and IP acquired WLANNWCT_IPSTATUS_DISCT_NAQRD - currently WLAN disconnected and IP not acquired. Example usage: Get current status of a network and set a callback for any disconnect events voidmyAllDisconnectCallbackFunc(WlanNetworkConnect_Status_TreturnStatus) { if(WLANNWCT_STATUS_DISCONNECTED==returnStatus) { //NetworkdisconnectionsuccessfullyfromWlanNetworkConnect_Disconnectfunction printf("CallbackFunction:Adisconnecteventhashappened!\n\r"); } } //localvariables Retcode_TretStatus; if(WLANNWCT_IPSTATUS_DISCT_NAQRD !=WlanNetworkConnect_GetIpStatus() &&(WLANNWCT_IPSTATUS_DISCT_AQRD !=WlanNetworkConnect_GetIpStatus())) { retStatus=WlanNetworkConnect_Disconnect(); printf("Finisheddisconnectionsuccessfully\n\r"); }
Referenced by AppControllerValidateWLANConnectivity, SetAndGetIp.
WlanNetworkConnect_Status_T WlanNetworkConnect_GetStatus(void)
Function to get the connection status. This function return the connection status.
none WLANNWCT_STATUS_CONNECTED - WLAN connected obtained after calling connect function. WLANNWCT_STATUS_DISCONNECTED - WLAN disconnected obtained after calling disconnect function. Example usage: Block until IP status is acquired and Wlan is connected while((WLANNWCT_STATUS_DISCONNECTED==WlanNetworkConnect_GetStatus()) ||(WLANNWCNF_IPSTATUS_IP_NOTAQRD==WlanNetworkConfig_GetIpStatus())) { //Stayhereuntilconnectedandipacquired. //Timeoutlogiccanbeaddedhere. } This API must be called only after initialization
Referenced by AppControllerWLANMonitor, SetAndGetIp, WlanConnect_GetStatus.
Retcode_T WlanNetworkConnect_Init(WlanNetworkConnect_Callback_T callBack)
WLAN driver initialization function. This function initializes WLAN driver context and Hardware interfaces; Also initializes the WLAN Stack. This API should be called first before calling any other API.
By default device is configured to STA mode if user want to change the mode, they need to use the Simple link API directly callBack call poiner to notify the connection status Retcode_T The return value consist of (First 1 MSByte represents Package ID, Next Byte represents Severity and Last 2 LSBytes represents error code) Below shows the error code(last 2 Bytes) meaning RETCODE_OK - Successfully WLAN driver initialized. RETCODE_SIMPLELINK_ERROR - Not initialized WLAN driver. RETCODE_NULL_POINTER - Invalid callBack passed RETCODE_TIMERCREATE_FAILURE - Failure in s/w timer creation Example1 usage: Initialize the WLAN Stack and the WLAN Driver //Callbackfunction voidmyConnectCallbackFunc(WlanNetworkConnect_Status_TreturnStatus) { if(WLANNWCT_STATUS_CONNECTED==returnStatus) { //Networkconnectionsuccessfully printf("CallbackFunction:ConnectOK!\n\r"); //Usermayaddlogiconcetheconnectionisdone //E.glaunchanotherOSTimer } else { //usermayretrytoconnect } } Retcode_TretStatus; //InitializeWLANdriverandWLANstack retStatus=WlanNetworkConnect_Init(myConnectCallbackFunc); if(RETCODE_OK!=retStatus) { printf("WLANdriverinitializationfailure"); } Example2 usage: Restart Device //LocalAPIreturnstatus Retcode_TretStatus[2]; retStatus[0]=WlanNetworkConnect_DeInit(); retStatus[1]=WlanNetworkConnect_Init(myConnectCallbackFunc); //Checkifdevicerestarthasfinishedwitherror if((RETCODE_OK!=retStatus[0])||(RETCODE_OK!=retStatus[1])) { printf("Restartdevicefailed"); }
Referenced by AppControllerEnable, WlanConnect_Init.
Retcode_T WlanNetworkConnect_Open(WlanNetworkConnect_SSID_T connectSSID)
WLAN Connect to Open Network interface. This function connects to an open network. Function is configurable in two ways:
blocking : callback parameter is set to NULL(maximum blocking in error case will be 15seconds)non-blocking : callback parameter is set to the address of the user function connectSSID Pointer to char containing the network SSID to connect to. RETCODE_OK - Successfully connected to the AP. RETCODE_SIMPLELINK_ERROR - Failure returned by simplelink API. WLANNWCT_STATUS_CONNECTERR - Failure because of incorrect SSID. RETCODE_ERROR_IP_NOT_ACQ - Connected but ip not acquired. Retcode_T The return value consist of (First 1 MSByte represents Package ID, Next Byte represents Severity and Last 2 LSBytes represents error code) Below shows the error code(last 2 Bytes) meaning Example usage: Connect to an open WLAN network with callback (non-blocking) //Callbackfunction voidmyConnectCallbackFunc(WlanNetworkConnect_Status_TreturnStatus) { if(WLANNWCT_STATUS_CONNECTED==returnStatus) { //Networkconnectionsuccessfully printf("CallbackFunction:ConnectOK!\n\r"); //Usermayaddlogiconcetheconnectionisdone //E.glaunchanotherOSTimer } else { //usermayretrytoconnect } } //localvariables WlanNetworkConnect_SSID_TconnectSSID; Retcode_TretStatus; retStatus=WlanNetworkConnect_Init(myConnectCallbackFunc); //Openwirelessnetworksettings connectSSID=(WlanNetworkConnect_SSID_T)"Name-Of-Open-Network"; //Connecttonetwork-->nonblockingfunctionwithcallback retStatus=WlanNetworkConnect_Open(connectSSID,false);
Retcode_T WlanNetworkConnect_PersonalWPA(WlanNetworkConnect_SSID_T connectSSID, WlanNetworkConnect_PassPhrase_T connectPass)
WLAN Connect to Personal WPA Network interface. This function connects to an WPA2-PSK or WPA-PSK network. Function is configurable in two ways:
blocking : callback parameter is set to NULL(maximum blocking in error case will be 15seconds)non-blocking : callback parameter is set to the address of the user function connectionSSID Pointer to char containing the network SSID to connect to. connectionPass Pointer to char containing the network Pass Phrase. RETCODE_OK - API return code for success. RETCODE_SIMPLELINK_ERROR - Failure returned by simplelink API. RETCODE_ERROR_SSID_NOT_FOUND - Failure because of incorrect SSID. RETCODE_ERROR_WRONG_PASSWORD - Failure because of incorrect Pass phrase. RETCODE_ERROR_IP_NOT_ACQ - Connected but ip not acquired Retcode_T The return value consist of (First 1 MSByte represents Package ID, Next Byte represents Severity and Last 2 LSBytes represents error code) Below shows the error code(last 2 Bytes) meaning Example usage: Connect to Personal WPA/WPA2 network with callback (non-blocking) //Callbackfunction voidmyConnectCallbackFunc(WlanNetworkConnect_Status_TreturnStatus) { if(WLANNWCT_STATUS_CONNECTED==returnStatus) { //Networkconnectionsuccessfully printf("CallbackFunction:ConnectOK!\n\r"); //Usermayaddlogiconcetheconnectionisdone //E.glaunchanotherOSTimer } else { //usermayretrytoconnect } } //localvariables WlanNetworkConnect_SSID_TconnectSSID; Retcode_TretStatus; WlanNetworkConnect_PassPhrase_TconnectPassPhrase; //WPA/WPA2encryptedwirelessnetworksettings connectSSID=(WlanNetworkConnect_SSID_T)"WPA-NETWORK-NAME"; connectPassPhrase=(WlanNetworkConnect_PassPhrase_T)"WPA-PASSWORD"; //Setcallbackfunctions connectCallback=myConnectCallbackFunc; //Connecttonetwork-->nonblockingfunctionwithcallback retStatus=WlanNetworkConnect_PersonalWPA(connectSSID,connectPassPhrase);
Referenced by SetAndGetIp.
Retcode_T WlanNetworkConnect_PowerControl(WlanNetworkConnect_PwrCtrl_T mode, void *data)
Wlan power control function.
mode - Wlan power modes data - data based on the power mode that is being notified | mode | data | | WLANNWCT_PWRCTRL_HIBERNATE | not used | | WLANNWCT_PWRCTRL_WAKEUP | not used | | WLANNWCT_PWRCTRL_FAST_CONNECT | bool | | WLANNWCT_PWRCTRL_MDNS_PACKET | bool | Example1 usage: Hibernate mode //Thisisthelowestpowermode.Ifthedeviceenterintohibernatemode,deviceispoweredoffexceptRTCclockkeepsrunning. //Inthismode,memoryisnotretained,andwakeuprequiresacoldbootinitialization. WlanNetworkConnect_PowerControl(WLANNWCT_PWRCTRL_HIBERNATE,NULL); If the network is in connected mode, then disconnect from network and enter into hibernate mode. If the device is in hibernate mode, then system won't connected to the specified network. Example2 usage: Wakeup mode //Inthismode,devicewillwakeupfromsleepmodeorhibernatemode.Ensurethat,ifthedeviceisinhibernatemode,thenwakeup //requiresbootinitialization WlanNetworkConnect_PowerControl(WLANNWCT_PWRCTRL_WAKEUP,NULL); If the device is in hibernate mode, then wakeup the device and connect to the specified network. Example3 usage: Fast connect mode //Infastconnectpolicy,intheeventofdisconnectoruponinitialization,thenetworksubsystemimmediatelytriestoconnectthe //lastaccesspointthatitwasconnected.itremembersthelastssid,securitycredentialsandchannelinfooflastaccesspoint. //Themainadvantageoffastconnectoverautoconnectisthatthesystemskipsthescan.Ifthelastaccesspointconnectionfails, //thenitrunsthescanprocessandlookforthehighestpriorityprofileandconnecttoit. //Toenablefastconnectpolicy boolstatusFlag=true; WlanNetworkConnect_PowerControl(WLANNWCT_PWRCTRL_FAST_CONNECT,(void*)&statusFlag); //Todisablefastconnectpolicy boolstatusFlag=false; WlanNetworkConnect_PowerControl(WLANNWCT_PWRCTRL_FAST_CONNECT,(void*)&statusFlag); Example4 usage: mDNS mode //Afterconnectingtoaccesspoint,networkprocessorwillsendthemDNSpacketsforservicediscovery.StopsendingthismDNSpackets //whenitnotrequiredbythesystemapplicationforpoweroptimization. //ToenablemDNSprotocolenable boolstatusFlag=true; WlanNetworkConnect_PowerControl(WLANNWCT_PWRCTRL_MDNS_PACKET,(void*)&statusFlag); //ToenablemDNSprotocoldisable boolstatusFlag=false; WlanNetworkConnect_PowerControl(WLANNWCT_PWRCTRL_MDNS_PACKET,(void*)&statusFlag); RETCODE_OK in the case of success or an error code otherwise.
Retcode_T WlanNetworkConnect_ScanNetworks(WlanNetworkConnect_ScanInterval_T scanInterval, WlanNetworkConnect_ScanList_T *scanList)
Function used to scan the available networks. Get the available scan information. List of scan results will be available via the call back function.
scanInterval Time interval between network scan. scanList Structure pointer hold the WLAN scan information data. RETCODE_OK - scan done successful. RETCODE_SIMPLELINK_ERROR - scan was not successful. RETCODE_NO_NW_AVAILABLE - No network available to scan. Retcode_T The return value consist of (First 1 MSByte represents Package ID, Next Byte represents Severity and Last 2 LSBytes represents error code) Below shows the error code(last 2 Bytes) meaning Example usage: Scan networks and print SSIDs //localvariables Retcode_TretScanStatus; WlanNetworkConnect_ScanInterval_TscanInterval; WlanNetworkConnect_ScanList_TscanList; //Setscaninterval scanInterval=5; //Filloutthescanlistbycallingthescannetworkfunction retScanStatus=WlanNetworkConnect_ScanNetworks(scanInterval,&scanList); //Setthenumberofentries intnbEntries=scanList.numOfScanEntries; //Printallthenon-emptySSIDs for(inti=0;i<nbEntries;i++) { if(0!=scanList.scanData[i].ssidLength) { printf("-foundSSIDnumber%dis:%s\n\r",i,scanList.scanData[i].ssid); //Delayeachprintfwith0,5seconds vTaskDelay(DELAY_500_MSEC); } }
Referenced by ScanNetwork.
Retcode_T WlanNetworkConnect_WEP_Open(WlanNetworkConnect_SSID_T connectSSID, WlanNetworkConnect_PassPhrase_T connectPass, uint8_t passPhraseLength)
WLAN Connect to WEP Open Network interface. This function connects to an WEP Open network. Function is configurable in two ways:
blocking : callback parameter is set to NULL(maximum blocking in error case will be 15seconds)non-blocking : callback parameter is set to the address of the user function connectionSSID Pointer to char containing the network SSID to connect to. connectionPass Pointer to char containing the network Pass Phrase. passPhraseLength Length of the Pass Phrase RETCODE_OK - API return code for success. RETCODE_SIMPLELINK_ERROR - Failure returned by simplelink API. RETCODE_ERROR_SSID_NOT_FOUND - Failure because of incorrect SSID. RETCODE_ERROR_WRONG_PASSWORD - Failure because of incorrect Pass phrase. RETCODE_ERROR_IP_NOT_ACQ - Connected but ip not acquired RETCODE_INVALID_PARAM - passPhraseLength is zero Retcode_T The return value consist of (First 1 MSByte represents Package ID, Next Byte represents Severity and Last 2 LSBytes represents error code) Below shows the error code(last 2 Bytes) meaning Example usage: Connect to an WEP Open network with callback (non-blocking) //Callbackfunction voidmyConnectCallbackFunc(WlanNetworkConnect_Status_TreturnStatus) { if(WLANNWCT_STATUS_CONNECTED==returnStatus) { //Networkconnectionsuccessfully printf("CallbackFunction:ConnectOK!\n\r"); //Usermayaddlogiconcetheconnectionisdone //E.glaunchanotherOSTimer } else { //usermayretrytoconnect } } //localvariables //ForexampleifAPisconfiguredtoWEPwith40bitHexpasswordof:"FFFFFFFFFF" charpassPhrase[5]={0xFF,0xFF,0xFF,0xFF,0xFF}; WlanNetworkConnect_SSID_TconnectSSID; Retcode_TretStatus; WlanNetworkConnect_PassPhrase_TconnectPassPhrase; uint8_tpassPhraseLength;[Don'tusestrlen()inordernottobumponzero/NULLinthepassPhrase] //WEPencryptedwirelessnetworksettings connectSSID=(WlanNetworkConnect_SSID_T)"WEP-OPEN-NETWORK-NAME"; connectPassPhrase=(WlanNetworkConnect_PassPhrase_T)passPhrase; passPhraseLength=UINT8_C(5); //Connecttonetwork-->nonblockingfunctionwithcallback retStatus=WlanNetworkConnect_WEP_Open(connectSSID,connectPassPhrase,passPhraseLength,false);
Retcode_T WlanNetworkConnect_WPS_PBC(void)
WLAN Connect using WPS PBC interface. This function connects to a network by using the Wi-Fi Protected Setup. After calling the function the user must push the connect button of the Router for around 5 seconds. Function is configurable in two ways:
blocking : callback parameter is set to NULL(maximum blocking in error case will be 15seconds)non-blocking : callback parameter is set to the address of the user function Retcode_T The return value consist of (First 1 MSByte represents Package ID, Next Byte represents Severity and Last 2 LSBytes represents error code) Below shows the error code(last 2 Bytes) meaning RETCODE_OK - API return code for success. RETCODE_SIMPLELINK_ERROR - Failure returned by simplelink API. RETCODE_CONNECTION_ERROR - connection Failure . RETCODE_ERROR_IP_NOT_ACQ - Connected but ip not acquired Example usage: Connect to a wireless network using WPS (WiFi Protected Setup) PBC (Push Button Connect) with callback (non-blocking) //Callbackfunction voidmyConnectCallbackFunc(WlanNetworkConnect_Status_TreturnStatus) { if(WLANNWCT_STATUS_CONNECTED==returnStatus) { //Networkconnectionsuccessfully printf("CallbackFunction:ConnectOK!\n\r"); //Usermayaddlogiconcetheconnectionisdone //E.glaunchanotherOSTimer } else { //usermayretrytoconnect } } //localvariables Retcode_TretStatus[3]; //Setcallbackfunctions //Becausetheboardconnectstonetworkveryfast,theuser //mustdisconnectanddeleteallstoredprofilesbefore //retryingtoconnectwithWPSPBC retStatus[0]=WlanNetworkConnect_Disconnect(); //DeleteallstoredprofilesinordertoconnectWPSbypushing //thebuttonallthetime.Removethislineifyouwantto //keepprofileafterrunningoncethefunction. retStatus[1]=WlanNetworkConnect_DeleteAllProfiles(); //Connecttonetwork-->nonblockingfunctionwithcallback retStatus[2]=WlanNetworkConnect_WPS_PBC();
Retcode_T WlanNetworkConnect_WPS_PIN(void)
WLAN Connect using WPS PIN interface. This function connects to a network by using the Wi-Fi Protected Setup. The function is configured with the following enrollee PIN code: 35072317. This PIN must be entered in the router interface after calling the function. Function is configurable in two ways:
blocking : callback parameter is set to NULL(maximum blocking in error case will be 15seconds)non-blocking : callback parameter is set to the address of the user function RETCODE_OK - API return code for success. RETCODE_SIMPLELINK_ERROR - Failure returned by simplelink API. RETCODE_CONNECTION_ERROR - Connection Failure because of incorrect Pin. RETCODE_ERROR_IP_NOT_ACQ - Connected but IP not acquired Retcode_T The return value consist of (First 1 MSByte represents Package ID, Next Byte represents Severity and Last 2 LSBytes represents error code) Below shows the error code(last 2 Bytes) meaning Example usage: Connect to a wireless network using WPS (WiFi Protected Setup) PIN (Personal Identify. Number) with callback (non-blocking) //Callbackfunction voidmyConnectCallbackFunc(WlanNetworkConnect_Status_TreturnStatus) { if(WLANNWCT_STATUS_CONNECTED==returnStatus) { //Networkconnectionsuccessfully printf("CallbackFunction:ConnectOK!\n\r"); //Usermayaddlogiconcetheconnectionisdone //E.glaunchanotherOSTimer } else { //usermayretrytoconnect } } //localvariables Retcode_TretStatus[3]; //Becausetheboardconnectstonetworkveryfast,theuser //mustdisconnectanddeleteallstoredprofilesbefore //retryingtoconnectwithWPSPIN retStatus[0]=WlanNetworkConnect_Disconnect(); //DeleteallstoredprofilesinordertoconnectWPSusing //enrolleePINallthetime.Removethislineifyouwantto //keepprofileafterrunningoncethefunction. retStatus[1]=WlanNetworkConnect_DeleteAllProfiles(); //Connecttonetwork-->nonblockingfunctionwithcallback retStatus[2]=WlanNetworkConnect_WPS_PIN();