BCDS_NVM.h
NVM_Endianness_E
NVM_Mode_E
NVM_Retcode_E
Retcode_T NVM_Deinitialize(const struct NVM_S *Nvm_obj)
De-initializes the NVM interface and makes sure all items are written back to flash.
nvm_obj object instance\ RETCODE_OK NVM de-initialization successful. RETCODE_NULL_POINTER nvm_obj is a null pointer any further usage of nvm_obj after that function call leads to undefined behavior of the NVM
Retcode_T NVM_Flush(const struct NVM_S *Nvm_obj)
Flush all items from an NVM internal buffer to the flash memory.
nvm_obj nvm object holding the used page and section specification RETCODE_OK Flushing all items from an NVM internal buffer to the flash memory successful RETCODE_FAILURE Flushing all items from an NVM internal buffer to the flash memory failed In case of any other error refer #MCU_Flash_ErasePage or #MCU_Flash_Write error codes.
Referenced by systemStartup, FOTA_UpdateSdcardFw.
Retcode_T NVM_Initialize(struct NVM_S *Nvm_obj)
Initializes the NVM for a certain section specified by the user and the given function parameter nvm_obj. NVM_Init() reads the section content of the flash memory and stores it in the NVM internal buffer for later read and write operations.
nvm_obj object instance RETCODE_OK NVM Initialization successful. RETCODE_FAILURE NVM Initialization successful. In case of any other error refer #MCU_Flash_Read error codes.
Referenced by systemStartup.
Retcode_T NVM_Read(const struct NVM_S *Nvm_obj, struct NVM_Item_S Item, void *Value, uint32_t Length)
Reads an item from NVM. This function only operates on the NVM internal buffer. In order to store the buffers content to the flash memory use NVM_Flush().
nvm_obj object instance item identifies an item value must point to a properly sized buffer length length of provided value buffer RETCODE_OK Reading an item from NVM successful NVM_RETCODE_INVALID_SIZE Provided buffer length does not match item length NVM_RETCODE_INTEGRITY_FAILED The item's content is corrupt
Referenced by Utils_GetMacInfoFromNVM.
Retcode_T NVM_ReadInt16(const struct NVM_S *Nvm_obj, struct NVM_Item_S Item, int16_t *Value)
Reads an signed int8 item. This function only operates on an NVM internal buffer. In order to store the buffers content to the flash memory use NVM_Flush().
nvm_obj nvm object holding the used page and section specification item item to be read value read value RETCODE_OK If the item has been read successfully NVM_RETCODE_INVALID_SIZE If the item size is invalid In case of any other error refer NVM_Read error codes.
Retcode_T NVM_ReadInt32(const struct NVM_S *Nvm_obj, struct NVM_Item_S Item, int32_t *Value)
Reads an signed int8 item. This function only operates on an NVM internal buffer. In order to store the buffers content to the flash memory use NVM_Flush().
nvm_obj nvm object holding the used page and section specification item item to be read value read value RETCODE_OK If the item has been read successfully NVM_RETCODE_INVALID_SIZE If the item size is invalid In case of any other error refer NVM_Read error codes.
Retcode_T NVM_ReadInt64(const struct NVM_S *Nvm_obj, struct NVM_Item_S Item, int64_t *Value)
Reads an signed int8 item. This function only operates on an NVM internal buffer. In order to store the buffers content to the flash memory use NVM_Flush().
nvm_obj nvm object holding the used page and section specification item item to be read value read value RETCODE_OK If the item has been read successfully NVM_RETCODE_INVALID_SIZE If the item size is invalid In case of any other error refer NVM_Read error codes.
Retcode_T NVM_ReadInt8(const struct NVM_S *Nvm_obj, struct NVM_Item_S Item, int8_t *Value)
Reads an signed int8 item. This function only operates on the NVM internal buffer. In order to store the buffers content to the flash memory use NVM_Flush().
nvm_obj nvm object holding the used page and section specification item item to be read value read value RETCODE_OK If the item has been read successfully NVM_RETCODE_INVALID_SIZE If the item size is invalid In case of any other error refer NVM_Read error codes.
Retcode_T NVM_ReadUInt16(const struct NVM_S *Nvm_obj, struct NVM_Item_S Item, uint16_t *Value)
Reads an signed int8 item. This function only operates on an NVM internal buffer. In order to store the buffers content to the flash memory use NVM_Flush().
nvm_obj nvm object holding the used page and section specification item item to be read value read value RETCODE_OK If the item has been read successfully NVM_RETCODE_INVALID_SIZE If the item size is invalid In case of any other error refer NVM_Read error codes.
Retcode_T NVM_ReadUInt32(const struct NVM_S *Nvm_obj, struct NVM_Item_S Item, uint32_t *Value)
Reads an signed int8 item. This function only operates on an NVM internal buffer. In order to store the buffers content to the flash memory use NVM_Flush().
nvm_obj nvm object holding the used page and section specification item item to be read value read value RETCODE_OK If the item has been read successfully NVM_RETCODE_INVALID_SIZE If the item size is invalid In case of any other error refer NVM_Read error codes.
Retcode_T NVM_ReadUInt64(const struct NVM_S *Nvm_obj, struct NVM_Item_S Item, uint64_t *Value)
Reads an signed int8 item. This function only operates on an NVM internal buffer. In order to store the buffers content to the flash memory use NVM_Flush().
nvm_obj nvm object holding the used page and section specification item item to be read value read value RETCODE_OK if the item has been read successfully NVM_RETCODE_INVALID_SIZE If the item size is invalid In case of any other error refer NVM_Read error codes.
Retcode_T NVM_ReadUInt8(const struct NVM_S *nvm_obj, struct NVM_Item_S item, uint8_t *value)
Reads an signed int8 item. This function only operates on an NVM internal buffer. In order to store the buffers content to the flash memory use NVM_Flush().
nvm_obj nvm object holding the used page and section specification item item to be read value read value RETCODE_OK If the item has been read successfully NVM_RETCODE_INVALID_SIZE If the item size is invalid In case of any other error refer NVM_Read error codes.
Referenced by systemStartup, Utils_GetMacInfoFromNVM.
Retcode_T NVM_Write(const struct NVM_S *Nvm_obj, struct NVM_Item_S Item, const void *Value, uint32_t Length)
Writes an item to NVM. This function only operates on the NVM internal buffer. In order to store the buffers content to the flash memory use NVM_Flush().
nvm_obj object instance item identifies an item value must point to a properly sized buffer which includes data to be written length of provided value buffer, amount of bytes to be written RETCODE_OK Writing an item from NVM successful NVM_RETCODE_INVALID_SIZE Provided buffer length does not match item length NVM_RETCODE_WRITE_FORBIDDEN Item is read-only
Retcode_T NVM_WriteInt16(const struct NVM_S *Nvm_obj, struct NVM_Item_S Item, const int16_t *Value)
Writes an unsigned uint8 item to NVM. This function only operates on an NVM internal buffer. In order to store the buffers content to the flash memory use NVM_Flush().
nvm_obj nvm object holding the used page and section specification item item specification value desired value to write RETCODE_OK if the item has been successfully written NVM_RETCODE_INVALID_SIZE If the item size is invalid In case of any other error refer NVM_Write error codes.
Retcode_T NVM_WriteInt32(const struct NVM_S *Nvm_obj, struct NVM_Item_S Item, const int32_t *Value)
Writes an unsigned uint8 item to NVM. This function only operates on an NVM internal buffer. In order to store the buffers content to the flash memory use NVM_Flush().
nvm_obj nvm object holding the used page and section specification item item specification value desired value to write RETCODE_OK if the item has been successfully written NVM_RETCODE_INVALID_SIZE If the item size is invalid In case of any other error refer NVM_Write error codes.
Retcode_T NVM_WriteInt64(const struct NVM_S *Nvm_obj, struct NVM_Item_S Item, const int64_t *Value)
Writes an unsigned uint8 item to NVM. This function only operates on an NVM internal buffer. In order to store the buffers content to the flash memory use NVM_Flush().
nvm_obj nvm object holding the used page and section specification item item specification value desired value to write RETCODE_OK if the item has been successfully written NVM_RETCODE_INVALID_SIZE If the item size is invalid In case of any other error refer NVM_Write error codes.
Retcode_T NVM_WriteInt8(const struct NVM_S *Nvm_obj, struct NVM_Item_S Item, const int8_t *Value)
Writes an unsigned uint8 item to NVM. This function only operates on an NVM internal buffer. In order to store the buffers content to the flash memory use NVM_Flush().
nvm_obj nvm object holding the used page and section specification item item specification value desired value to write RETCODE_OK if the item has been successfully written NVM_RETCODE_INVALID_SIZE If the item size is invalid In case of any other error refer NVM_Write error codes.
Retcode_T NVM_WriteUInt16(const struct NVM_S *Nvm_obj, struct NVM_Item_S Item, const uint16_t *Value)
Writes an unsigned uint8 item to NVM. This function only operates on an NVM internal buffer. In order to store the buffers content to the flash memory use NVM_Flush().
nvm_obj nvm object holding the used page and section specification item item specification value desired value to write RETCODE_OK if the item has been successfully written NVM_RETCODE_INVALID_SIZE If the item size is invalid In case of any other error refer NVM_Write error codes.
Retcode_T NVM_WriteUInt32(const struct NVM_S *Nvm_obj, struct NVM_Item_S Item, const uint32_t *Value)
Writes an unsigned uint8 item to NVM. This function only operates on an NVM internal buffer. In order to store the buffers content to the flash memory use NVM_Flush().
nvm_obj nvm object holding the used page and section specification item item specification value desired value to write RETCODE_OK if the item has been successfully written NVM_RETCODE_INVALID_SIZE If the item size is invalid In case of any other error refer NVM_Write error codes.
Referenced by FOTA_UpdateSdcardFw.
Retcode_T NVM_WriteUInt64(const struct NVM_S *Nvm_obj, struct NVM_Item_S Item, const uint64_t *Value)
Writes an unsigned uint8 item to NVM. This function only operates on an NVM internal buffer. In order to store the buffers content to the flash memory use NVM_Flush().
nvm_obj nvm object holding the used page and section specification item item specification value desired value to write RETCODE_OK if the item has been successfully written NVM_RETCODE_INVALID_SIZE If the item size is invalid In case of any other error refer NVM_Write error codes.
Retcode_T NVM_WriteUInt8(const struct NVM_S *Nvm_obj, struct NVM_Item_S Item, const uint8_t *Value)
Writes an unsigned uint8 item to NVM. This function only operates on an NVM internal buffer. In order to store the buffers content to the flash memory use NVM_Flush().
nvm_obj nvm object holding the used page and section specification item item specification value desired value to write RETCODE_OK if the item has been successfully written NVM_RETCODE_INVALID_SIZE If the item size is invalid In case of any other error refer NVM_Write error codes.
Referenced by systemStartup, FOTA_UpdateSdcardFw.