BSP_UMTS_QuectelUC20.c
BCDS_MODULE_ID
static Retcode_T BSP_UMTS_QuectelUC20_Connect(void)
References RETCODE_OK, UMTS_POWER_ON_PIN, UMTS_RESET_PIN.
Referenced by BSP_UMTS_QuectelUC20_Enable.
Retcode_T BSP_UMTS_QuectelUC20_Disable(void)
References RETCODE_OK, UMTS_POWER_ON_PIN, UMTS_RESET_PIN, Board_SnoozePowerSupply2V5, EXTENSION_BOARD, Board_DisablePowerSupply3V3.
Retcode_T BSP_UMTS_QuectelUC20_Enable(void)
References RETCODE_OK, Board_WakeupPowerSupply2V5, EXTENSION_BOARD, Board_EnablePowerSupply3V3, BSP_UMTS_QuectelUC20_Connect, BSP_UMTS_QuectelUC20_EnableGpio, OStoBSPdelayFunc, UMTS_GPIO_CONNECT_DELAY_MS, BSP_UMTS_QuectelUC20_EnableUart.
static Retcode_T BSP_UMTS_QuectelUC20_EnableGpio(void)
References RETCODE_OK, UMTS_POWER_ON_PIN, NULL, UMTS_RESET_PIN.
Referenced by BSP_UMTS_QuectelUC20_Enable.
static Retcode_T BSP_UMTS_QuectelUC20_EnableUart(void)
References RETCODE_OK, UART1_BAUDRATE, NULL.
Referenced by BSP_UMTS_QuectelUC20_Enable.
HWHandle_T BSP_UMTS_QuectelUC20_GetUARTHandle(void)
Retcode_T BSP_UMTS_QuectelUC20_PowerOff(void)
References RETCODE_OK, UMTS_POWER_ON_PIN, OStoBSPdelayFunc, UMTS_POWER_OFF_PROCESSING_DELAY_MS.
Retcode_T BSP_UMTS_QuectelUC20_PowerOn(void)
References RETCODE_OK, UMTS_POWER_ON_PIN, OStoBSPdelayFunc, UMTS_POWER_ON_PROCESSING_DELAY_MS.
Retcode_T BSP_UMTS_QuectelUC20_Reset(void)
References RETCODE_OK, UMTS_RESET_PIN, OStoBSPdelayFunc, UMTS_RESET_PROCESSING_DELAY_MS.