BSP_Board.c
BCDS_FEATURE_TRACEPORT
BCDS_MODULE_ID
BSPLock_T ADCLock
Referenced by BSP_Charger_BQ2405X_MeasureSignal.
PowerSupply2V5Register_T BSP_PowerSupply2V5
power supply 2v5 register
PowerSupply3V3Register_T BSP_PowerSupply3V3
power supply 3v3 register
volatile uint32_t BSP_Tick
Referenced by Board_IncTick, Board_GetTick.
USART_InitAsync_TypeDef BSP_UART0InitStruct
Referenced by Board_UART0_UART_Init, Board_UART1_UART_Init.
USB_lineCoding_t BSP_USBHandle
Referenced by Board_USB_Init.
GPIOINT_IrqCallbackPtr_t gpioCallbacks[16][16]
Referenced by Board_GPIOInterruptGetCallback, Board_GPIOInterruptRegisterCallback, Board_GPIOInterruptDispatch.
OStoBSPDelayFunc_T OStoBSPdelayFunc
Referenced by BSP_Board_SetOStoBSPDelayFunc, BSP_UMTS_LisaU2_Disable, BSP_UMTS_LisaU2_Reset, BSP_UMTS_QuectelUC20_Enable, BSP_UMTS_QuectelUC20_PowerOn, BSP_UMTS_QuectelUC20_PowerOff, BSP_UMTS_QuectelUC20_Reset, BSP_WiFi_CC3100MOD_Enable.
Retcode_T Board_ADC_Init(void)
Initialize the ADC interface for the analog measurements.
References RETCODE_OK.
Referenced by BSP_Board_Initialize.
Retcode_T Board_BURTC_Init(void)
Initializes the Board part of the BURTC peripheral.
References RETCODE_OK, NULL.
Referenced by BSP_Board_Initialize.
void Board_Delay(uint32_t delay)
Provide a delay in millisecond.
delay delay time in ms;
References Board_GetTick.
Referenced by BSP_Board_Initialize, BSP_BT_EM9301_Enable, BSP_BT_EM9301_SetWUHigh, BSP_LoRa_RN2xx3_Enable, BSP_SensorNode_Enable, BSP_UMTS_LisaU2_Reset, BSP_WiFi_CC3100MOD_Enable, BSP_WiFi_CC3100MOD_Disable, BSP_WiFi_CC3100MOD_Wakeup, BSP_WiFi_CC3100MOD_Hibernate, BSP_WiFi_CC3100MOD_Reset.
void Board_DisablePowerSupply3V3(Peripherals_T peripheral)
Disables the 3V3 power rail.
This function holds a register of the connected peripherals to the power supply and if a peripheral requests disabling it, the corresponding bit field is Reset and the register and if this register equals zero then the power rail is safe to be disabled. Peripheral : enumerated value representing the peripheral requesting the Disabling of the power supply RETCODE_OK in case of success error code otherwise.
References PowerSupply3V3UpdateRegister, PowerSupply3V3Register_U::Register, PWR_3V3_EN_PORT, PWR_3V3_EN_PIN.
Referenced by BSP_IRSensorNode_Disable, BSP_Max31865_Disconnect, BSP_UMTS_QuectelUC20_Disable.
void Board_EnablePowerSupply3V3(Peripherals_T peripheral)
Enables the 3V3 power rail.
This function holds a register of the connected peripherals to the power supply and if a peripheral requests enabling it, the MCU output enabling the Power rail is Set its and the corresponding peripheral bit field is Set Peripheral : enumerated value representing the peripheral requesting the Enabling of the power supply RETCODE_OK in case of success error code otherwise.
References PowerSupply3V3Register_U::Register, PowerSupply3V3UpdateRegister, PWR_3V3_EN_PORT, PWR_3V3_EN_PIN.
Referenced by BSP_IRSensorNode_Enable, BSP_Max31865_Connect, BSP_UMTS_QuectelUC20_Enable.
uint32_t Board_GetTick(void)
Provide a tick value in millisecond.
tick value
References BSP_Tick.
Referenced by BSP_Board_Delay, Board_Delay.
void Board_GPIO_Init(void)
Initialization of critical GPIO pins.
References WIFI_NRESET_PORT, WIFI_NRESET_PIN, WIFI_NRESET_MODE, PWR_2V5_SNOOZE_PORT, PWR_2V5_SNOOZE_PIN, PWR_2V5_SNOOZE_MODE, PWR_3V3_EN_PORT, PWR_3V3_EN_PIN, PWR_3V3_EN_MODE.
Referenced by BSP_Board_Initialize.
void Board_GPIOInterruptDispatch(uint32_t iflags)
Function calls users callback for registered pin interrupts.
This function is called when GPIO interrupts are handled by the dispatcher. Function gets even or odd interrupt flags and calls user callback registered for that pin. Function iterates on flags starting from MSB. iflags Interrupt flags which shall be handled by the dispatcher.
References gpioCallbacks.
Referenced by GPIO_EVEN_IRQHandler, GPIO_ODD_IRQHandler.
GPIOINT_IrqCallbackPtr_t Board_GPIOInterruptGetCallback(uint8_t pin)
Returns the callback pointer.
This function is used to query the callback function registered for the requested pin. pin The pin number. The callback pointer.
References gpioCallbacks.
Referenced by BSP_SensorNode_Enable.
void Board_GPIOInterruptInit(void)
Initialization of GPIO Interrupts.
Referenced by BSP_Board_Initialize.
void Board_GPIOInterruptRegisterCallback(uint8_t pin, GPIOINT_IrqCallbackPtr_t callbackPtr)
Registers user callback for given pin number.
Use this function to register a callback which shall be called upon interrupt generated from given pin number (port is irrelevant). Interrupt itself must be configured externally. Function overwrites previously registered callback. pin Pin number for the callback. callbackPtr A pointer to callback function.
References gpioCallbacks.
Referenced by Board_GPIOInterruptUnregisterCallback, BSP_SensorNode_Enable, BSP_WiFi_CC3100MOD_Enable.
Retcode_T Board_I2C0_Init(void)
Initialize the I2C interface for the sensor node.
RETCODE_OK in case of success error code otherwise.
References RETCODE_OK.
Referenced by BSP_Board_Initialize.
Retcode_T Board_I2C1_Init(void)
Initialize the I2C interface to the default values for the extension board.
RETCODE_OK in case of success error code otherwise.
References RETCODE_OK.
Referenced by BSP_Board_Initialize.
void Board_IncTick(void)
This function is called to increment a global variable "BSP_Tick" used as application time base.
In the default implementation, this variable is incremented each 1ms in SysTick ISR. None
References BSP_Tick.
Retcode_T Board_RTC_Init(void)
Initializes the Board part of the RTC peripheral.
References RETCODE_OK, NULL.
Referenced by BSP_Board_Initialize.
void Board_SnoozePowerSupply2V5(Peripherals_T peripheral)
Puts the 2V5 power rail on low power mode(snooze).
This function holds a register of the connected peripherals to the power supply and if a peripheral requests disabling it, the corresponding bit field is Reset and the register and if this register equals zero then the power rail is safe to be scaled down. Peripheral : enumerated value representing the peripheral requesting the Snoozing of the power supply RETCODE_OK in case of success error code otherwise.
References PowerSupply2V5UpdateRegister, PowerSupply2V5Register_U::Register, PWR_2V5_SNOOZE_PORT, PWR_2V5_SNOOZE_PIN.
Referenced by BSP_IRSensorNode_Disable, BSP_LoRa_RN2xx3_Disconnect, BSP_Max31865_Disconnect, BSP_Mic_AKU340_Disable, BSP_UMTS_LisaU2_Disconnect, BSP_UMTS_QuectelUC20_Disable, BSP_WiFi_CC3100MOD_Disable.
Retcode_T Board_UART0_UART_Init(void)
Initialize the UART interface for the bluetooth module.
RETCODE_OK in case of success error code otherwise.
References BSP_UART0InitStruct, RETCODE_OK.
Referenced by BSP_Board_Initialize.
Retcode_T Board_UART1_UART_Init(void)
Initialize the UART interface to the default values for the extension board.
The default values for the UART1 interface mapped to the extension board depending on which extension board is used this UART gets its configuration values from BoardExtSettings.h file. 115200baud RETCODE_OK in case of success error code otherwise.
References BSP_UART0InitStruct, UART1_STATE, UART1_REF_FREQ, UART1_BAUDRATE, UART1_OVERSAMPLING, UART1_DATABITS, UART1_PARITY, UART1_STOPBITS, UART1_MAJORITY_VOTING, UART1_PRS_RX_ENABLE, UART1_PRS_RX_CHANNEL, RETCODE_OK.
Referenced by BSP_Board_Initialize.
Retcode_T Board_USART0_SPI_Init(void)
Initialize the USART interface at default SPI mode for the wifi module.
RETCODE_OK in case of success error code otherwise.
References WIFI_SERIAL_PORT, WIFI_SPI_PERCLK_FREQUENCY, WIFI_SPI_BAUDRATE, RETCODE_OK.
Referenced by BSP_Board_Initialize.
Retcode_T Board_USART1_SPI_Init(void)
Initialize the USART interface at the default values for the for the SD_Card.
RETCODE_OK in case of success error code otherwise.
References SD_CARD_SERIAL_PORT, SD_CARD_SPI_PERCLK_FREQUENCY, SD_CARD_SPI_BAUDRATE, RETCODE_OK.
Referenced by BSP_Board_Initialize.
Retcode_T Board_USB_Init(void)
Initialize the USB interface.
References BSP_USBHandle, USB_SET_BAUDRATE, USB_SET_STOPBITS_MODE, USB_SET_PARITY, USB_SET_DATA_BITS, USB_init, NULL, RETCODE_OK.
Referenced by BSP_Board_Initialize.
void Board_WakeupPowerSupply2V5(Peripherals_T peripheral)
Performs operations prior to SysTick count increment.
This function is initialized during BSP_Board_OSTickInitialize() and makes it possible for the application to perform some operations before the SysTick counter is incremented (e.g. context switching in OS based applications) This function is called in SysTick_Handler() function in IrqHandler.c file Wakes up the 2V5 power rail This function holds a register of the connected peripherals to the power supply and if a peripheral requests enabling it, the MCU output enabling the Power rail is Set its and the corresponding peripheral bit field is Set Peripheral : enumerated value representing the peripheral requesting the Enabling of the power supply
References PowerSupply2V5Register_U::Register, PowerSupply2V5UpdateRegister, PWR_2V5_SNOOZE_PORT, PWR_2V5_SNOOZE_PIN.
Referenced by BSP_Board_Initialize, BSP_BT_EM9301_Enable, BSP_IRSensorNode_Enable, BSP_LoRa_RN2xx3_Enable, BSP_Max31865_Connect, BSP_Mic_AKU340_Enable, BSP_UMTS_LisaU2_EnableGpio, BSP_UMTS_QuectelUC20_Enable, BSP_WiFi_CC3100MOD_Enable.
Retcode_T BSP_Board_ControlPowerRail(uint32_t control)
Controls the on-board power rails.
: provided that there are controllable power rails on the board, the BSP will provide the necessary commands that are possible to have in order to control them safely. control the desired power rail command implemented by the BSP. RETCODE_OK in the case of success or an error code otherwise.
References RETCODE_OK, BSP_XDK_RAIL_3V3_DISABLE, PWR_3V3_EN_PORT, PWR_3V3_EN_PIN, PowerSupply3V3Register_U::Register, BSP_XDK_RAIL_2V5_SNOOZE, PWR_2V5_SNOOZE_PORT, PWR_2V5_SNOOZE_PIN, PowerSupply2V5Register_U::Register, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM.
void BSP_Board_Delay(uint32_t delayMs)
Provide accurate delay based on variable incremented.
delay specifies the delay time Refer to your implementation for time granularity details.
References Board_GetTick.
Referenced by ExtensionPortSpiCtrl_AckAwaitHigh, ExtensionPortSpiCtrl_AckAwaitLow, Sigfox_Enable, Sigfox_SendWakeUp, BSP_BT_EM9301_Reset, BSP_Max31865_Connect, BSP_UMTS_LisaU2_Enable, BSP_UMTS_LisaU2_Disable, BSP_UMTS_LisaU2_Reset, configureSlopeInterrupt, Bma280Utils_DelayMS, Bme280Utils_DelayMS, Bme280Utils_initialize, Bmg160_DelayMS, Bmm150_DelayMS, Max44009Utils_initialize.
uint32_t BSP_Board_DetectPowerSupply(void)
Returns the power-supply mode.
This function detects whether the MCU is being supplied using a battery or using an external power supply.the current power supply type.
References POWER_SUPPLY_UNKNOWN.
void BSP_Board_DisableSysTick(void)
Disable the Core SysTick.
Retcode_T BSP_Board_EnableSysTick(void)
Enable the Core SysTick.
RETCODE_OK if success RETCODE_FAILURE if failure
References RETCODE_OK, HSE_VALUE, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_FAILURE.
Referenced by BSP_Board_Initialize.
uint32_t BSP_Board_GetBoardRevision(void)
Returns the BSP Revision.
BSP Revision.
uint32_t BSP_Board_GetWakeupSource(void)
Returns the last wake-up source.
This function will return the last event that resulted in the wake-up of the MCU from a sleep/deep-sleep state.The latest wake-up event source.
References BSP_XDK_WAKE_EVENT_NONE.
Retcode_T BSP_Board_Initialize(uint32_t param1, void *param2)
Initializes the entire board.
This function is responsible of setting the initial configuration at the MCU and board level in order to establish a running state and perform basic operations.The MCU resources are at this time configured according to their use cases and shut-down in order to maintain a low power consumption. As an example for a UART interface the BSP_Board_Initialize(param1, param2) will set the baudrate, the parity, the number of data bits, the number of stop bits, etc. and then disables the UART and turns off its clock. param1 : Initialization parameter depending on the implementation, can be used to indicate type of param2. param2 : Initialization parameter depending on the implementation. RETCODE_OK in the case of success or an error code otherwise.
References BCDS_UNUSED, RETCODE_OK, IrqHandler_SysTickDummyHandler, BSP_Board_EnableSysTick, Board_WakeupPowerSupply2V5, MCU, Board_BURTC_Init, Board_RTC_Init, Board_GPIO_Init, Board_GPIOInterruptInit, Board_UART0_UART_Init, Board_UART1_UART_Init, Board_USART0_SPI_Init, Board_USART1_SPI_Init, Board_I2C0_Init, Board_I2C1_Init, Board_ADC_Init, Board_USB_Init, BSP_Board_SetOStoBSPDelayFunc, Board_Delay.
Referenced by systemStartup.
void BSP_Board_OSTickInitialize(BSP_Systick_Callback_T PreCallback, BSP_Systick_Callback_T PostCallback)
Initializes pre/post tick increment processing in OS based applications.
If an operating system needs to perform some operations before and/or after the system tick count is incremented the application needs to call this function and provide the callbacks which are called before and after the tick increment. preCallback A pointer to the function which the system needs to execute before incrementing the tick count of the system tick. If no pre-processing is needed provide NULL. postCallback A pointer that points to the function which the system needs to execute after incrementing the tick count of the system tick. If no post-processing is needed provide NULL.
References SysTickOsPreProcessing, SysTickOsPostProcessing.
Referenced by systemStartup.
void BSP_Board_SetOStoBSPDelayFunc(OStoBSPDelayFunc_T delayFunc)
Passes delay function from OS to BSP.
If the application needs to replace the blocking delays greater than 50ms with non blocking delays it has to assign the delay function to this function pointer.In general the delays implemented have 1 ms granularity. delayFunc delay function.
References OStoBSPdelayFunc.
Referenced by BSP_Board_Initialize.
void BSP_Board_SoftReset(void)
Invoke Board Soft Reset. This puts the MCU registers to appropriate state applicable for soft reset. Please note this is not equivalent to hard reset.
Referenced by AppControllerValidateWLANConnectivity, AppControllerFire, AppControllerBleDataRxCB, extractFaultInfo, FOTA_UpdateSdcardFw.
Retcode_T BSP_Board_SwitchPowerMode(uint32_t powerMode)
Switches between different power modes.
This function is responsible of preparing switching between the available MCU power modes if the transition from the current mode to the next mode is allowed. Depending on the selected mode this function implements the recovery routines in order to bring the system to the state before it switched to that power mode. powerMode 32 bit value designating the desired power mode according to what is specified in the implementation under BSP_BoardType.h RETCODE_OK in the case of success or an error code otherwise.
References BCDS_UNUSED, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NOT_SUPPORTED.
void PowerSupply2V5UpdateRegister(Peripherals_T peripheral, uint32_t updateValue)
References MCU, PowerSupply2V5Register_U::Peripheral, PowerSupply2V5Register_S::MCU, MIC_AKU340, PowerSupply2V5Register_S::Mic_AKU340, BT_EM9301, PowerSupply2V5Register_S::BT_EM9301, WIFI_CC3100MOD, PowerSupply2V5Register_S::WiFi_CC3100MOD, SENSOR_BMA280, PowerSupply2V5Register_S::Sensor_BMA280, SENSOR_BMG160, PowerSupply2V5Register_S::Sensor_BMG160, SENSOR_BME280, PowerSupply2V5Register_S::Sensor_BME280, SENSOR_BMI150, PowerSupply2V5Register_S::Sensor_BMI150, SENSOR_MAX44009, PowerSupply2V5Register_S::Sensor_MAX44009, SENSOR_BMI160, PowerSupply2V5Register_S::Sensor_BMI160, EXTENSION_BOARD, PowerSupply2V5Register_S::ExtensionBoard, SD_CARD, PowerSupply2V5Register_S::SDCard, LED_ORANGE, PowerSupply2V5Register_S::LED_O, LED_YELLOW, PowerSupply2V5Register_S::LED_Y, LED_RED, PowerSupply2V5Register_S::LED_R, LED_ALL.
Referenced by Board_WakeupPowerSupply2V5, Board_SnoozePowerSupply2V5.
void PowerSupply3V3UpdateRegister(Peripherals_T peripheral, uint32_t updateValue)
References MCU, PowerSupply3V3Register_U::Peripheral, PowerSupply3V3Register_S::MCU, SD_CARD, PowerSupply3V3Register_S::SDCard, EXTENSION_BOARD, PowerSupply3V3Register_S::ExtensionBoard.
Referenced by Board_DisablePowerSupply3V3, Board_EnablePowerSupply3V3.