BSP_WiFi_cc3100mod.c
BCDS_MODULE_ID
BSP_BT_EM9301_Retcode_E
struct MCU_SPI_Handle_S BSP_WiFi_CC3100MOD_SPI_Handle
Referenced by BSP_WiFi_CC3100MOD_Connect, BSP_WiFi_CC3100MOD_Enable, BSP_WiFi_CC3100MOD_GetSPIHandle, WiFi_CC3100MOD_SPIRxISR, WiFi_CC3100MOD_SPITxISR.
BSP_WiFi_CC3100MOD_InterruptCallback_T WiFi_CC3100MOD_ISRCallback
Referenced by BSP_WiFi_CC3100MOD_Enable, BSP_WiFi_CC3100MOD_Disable, WiFi_INT_InterruptCallback.
SPI_IRQ_Callback_T WiFi_CC3100MOD_SPI_RxISRCallback
Referenced by BSP_WiFi_CC3100MOD_Enable, BSP_WiFi_CC3100MOD_Disable, WiFi_CC3100MOD_SPIRxISR.
SPI_IRQ_Callback_T WiFi_CC3100MOD_SPI_TxISRCallback
Referenced by BSP_WiFi_CC3100MOD_Enable, BSP_WiFi_CC3100MOD_Disable, WiFi_CC3100MOD_SPITxISR.
Retcode_T BSP_WiFi_CC3100MOD_Connect(void)
Maps the GPIO pins to their desired function.
This function once called will map the GPIO pins to their desired functions to drive the TI(R) CC3100MOD WIFI peripheral. It is needed to call this function prior to the BSP_WIFI_CC3100MOD_Enable(). RETCODE_OK in the case of success or an error code otherwise.
References VDD_WIFI_EN_PORT, VDD_WIFI_EN_PIN, VDD_WIFI_EN_MODE, WIFI_NRESET_PORT, WIFI_NRESET_PIN, WIFI_NRESET_MODE, WIFI_CSN_PORT, WIFI_CSN_PIN, WIFI_CSN_MODE, WIFI_INT_PORT, WIFI_INT_PIN, WIFI_INT_MODE, WIFI_NHIB_PORT, WIFI_NHIB_PIN, WIFI_NHIB_MODE, WIFI_SPI0_MISO_PORT, WIFI_SPI0_MISO_PIN, WIFI_SPI0_MISO_MODE, WIFI_SPI0_MOSI_PORT, WIFI_SPI0_MOSI_PIN, WIFI_SPI0_MOSI_MODE, WIFI_SPI0_SCK_PORT, WIFI_SPI0_SCK_PIN, WIFI_SPI0_SCK_MODE, WIFI_SPI0_CLOCK, WIFI_SERIAL_PORT, WIFI_SPI_TX_DMA_CHANNEL, WiFi_CC3100MOD_SPI_TxDMAComplete, BSP_WiFi_CC3100MOD_SPI_Handle, WIFI_SPI_RX_DMA_CHANNEL, WiFi_CC3100MOD_SPI_RxDMAComplete, BCDS_HAL_TRANSFER_MODE_DMA, BCDS_HAL_TRANSFER_MODE_INTERRUPT, RETCODE_OK.
Retcode_T BSP_WiFi_CC3100MOD_Disable(void)
Disables the control over the peripheral.
This function once called will disable control over the TI(R) CC3100MOD WIFI peripheral by executing the disabling procedure as prescribed in the vendor datasheet. RETCODE_OK in the case of success or an error code otherwise.
References RETCODE_OK, WIFI_SPI0_CLOCK, WIFI_RX_IRQN, WIFI_TX_IRQN, WIFI_INT_PIN, Board_GPIOInterruptUnregisterCallback, WiFi_CC3100MOD_SPI_RxISRCallback, NULL, WiFi_CC3100MOD_SPI_TxISRCallback, WiFi_CC3100MOD_ISRCallback, WIFI_NRESET_PORT, WIFI_NRESET_PIN, WIFI_NHIB_PORT, WIFI_NHIB_PIN, VDD_WIFI_EN_PORT, VDD_WIFI_EN_PIN, Board_SnoozePowerSupply2V5, WIFI_CC3100MOD, Board_Delay, WIFI_POWER_OFF_DELAY_MS.
Retcode_T BSP_WiFi_CC3100MOD_Disconnect(void)
Disconnects the WIFI peripheral.
This function disconnects the GPIO pins dedicated to the TI(R) CC3100MOD WIFI peripheral and put them into low power consumption status. RETCODE_OK in the case of success or an error code otherwise.
References VDD_WIFI_EN_PORT, VDD_WIFI_EN_PIN, WIFI_CSN_PORT, WIFI_CSN_PIN, WIFI_INT_PORT, WIFI_INT_PIN, WIFI_NHIB_PORT, WIFI_NHIB_PIN, WIFI_NRESET_PORT, WIFI_NRESET_PIN, WIFI_SPI0_MISO_PORT, WIFI_SPI0_MISO_PIN, WIFI_SPI0_MOSI_PORT, WIFI_SPI0_MOSI_PIN, WIFI_SPI0_SCK_PORT, WIFI_SPI0_SCK_PIN, WIFI_SPI0_CLOCK, RETCODE_OK.
Retcode_T BSP_WiFi_CC3100MOD_Enable(BSP_WiFi_CC3100MOD_InterruptCallback_T callback)
Enables the control over the peripheral.
A prior call to MCU_<RESOURCE>_Initialize() is necessary for this function in order to operate.This function once called will allow the TI(R) CC3100MOD WIFI peripheral to receive, execute commands and transmit process data. callback : function to be called whenever an interrupt occurs on the line RETCODE_OK in the case of success or an error code otherwise.
References RETCODE_OK, NULL, BSP_WiFi_CC3100MOD_SPI_Handle, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_BSP_WIFI_SERIAL_NOT_INITIALIZED, Board_WakeupPowerSupply2V5, WIFI_CC3100MOD, WiFi_CC3100MOD_ISRCallback, Board_GPIOInterruptRegisterCallback, WIFI_INT_PIN, WiFi_INT_InterruptCallback, WIFI_INT_PORT, WIFI_INT_EDGE_RISING, WIFI_INT_EDGE_FALLING, BSP_ENABLE, VDD_WIFI_EN_PORT, VDD_WIFI_EN_PIN, WIFI_NHIB_PORT, WIFI_NHIB_PIN, Board_Delay, WIFI_SUPPLY_SETTING_DELAY_MS, WIFI_NRESET_PORT, WIFI_NRESET_PIN, WIFI_MIN_RESET_DELAY_MS, WIFI_PWRON_HW_WAKEUP_DELAY_MS, OStoBSPdelayFunc, WIFI_INIT_DELAY_MS, WIFI_SPI0_CLOCK, WIFI_SERIAL_PORT, WIFI_RX_IRQN, WIFI_RX_INTERRUPT_PRIORITY, WIFI_TX_IRQN, WIFI_TX_INTERRUPT_PRIORITY, WiFi_CC3100MOD_SPI_RxISRCallback, WiFi_CC3100MOD_SPI_TxISRCallback.
HWHandle_T BSP_WiFi_CC3100MOD_GetSPIHandle(void)
Returns the SPI handle of the communication interfaces used by the peripheral.
After successful execution of BSP_Board_Initialize(param1, param2), the application is free to call this function in order to get the handle needed by the resources drivers. This handle will be used by the MCU drivers for the intended resource. HWHandle_T: Handle for the used MCU resource.
References BSP_WiFi_CC3100MOD_SPI_Handle.
HWHandle_T BSP_WiFi_CC3100MOD_GetUartHandle(void)
Returns the UART handle of the communication interfaces used by the peripheral.
After successful execution of BSP_Board_Initialize(param1, param2), the application is free to call this function in order to get the handle needed by the resources drivers. This handle will be used by the MCU drivers for the intended resource. HWHandle_T: Handle for the used MCU resource.
Retcode_T BSP_WiFi_CC3100MOD_Hibernate(void)
Hibernates the WIFI module.
this function will execute the instruction sequence in order to put the WIFI module into hibernated state. RETCODE_OK in the case of success or an error code otherwise.
References WIFI_NHIB_PORT, WIFI_NHIB_PIN, Board_Delay, WIFI_MIN_HIB_DELAY_MS, RETCODE_OK.
Retcode_T BSP_WiFi_CC3100MOD_Reset(void)
Resets the WIFI module.
This function will execute the sequence to reset the CC3100MOD device RETCODE_OK in the case of success or an error code otherwise.
References WIFI_NRESET_PORT, WIFI_NRESET_PIN, Board_Delay, WIFI_MIN_RESET_DELAY_MS, RETCODE_OK.
Retcode_T BSP_WiFi_CC3100MOD_SetCSHigh()
Sets the CS pin to high i.e. device deselected.
RETCODE_OK in the case of success or an error code otherwise.
References WIFI_CSN_PORT, WIFI_CSN_PIN, RETCODE_OK.
Retcode_T BSP_WiFi_CC3100MOD_SetCSLow()
Sets the CS pin to Low i.e. device selected.
RETCODE_OK in the case of success or an error code otherwise.
References WIFI_CSN_PORT, WIFI_CSN_PIN, RETCODE_OK.
Retcode_T BSP_WiFi_CC3100MOD_Wakeup(void)
Wakes the module from hibernate mode.
If the WIFI peripheral is hibernated this function will execute the wake-up sequence with respect to the timing specified in the component data-sheet. RETCODE_OK in the case of success or an error code otherwise.
References WIFI_NHIB_PORT, WIFI_NHIB_PIN, Board_Delay, WIFI_HIB_WAKEUP_DELAY_MS, RETCODE_OK.
void WiFi_CC3100MOD_SPIRxISR(void)
SPI receive interrupt service routine used to capture interrupts at the SPI resource and to forward them to the MCU driver for processing.
References NULL, WiFi_CC3100MOD_SPI_RxISRCallback, BSP_WiFi_CC3100MOD_SPI_Handle.
Referenced by USART0_RX_IRQHandler.
void WiFi_CC3100MOD_SPITxISR(void)
SPI transmit interrupt service routine used to capture interrupts at the SPI resource and to forward them to the MCU driver for processing.
References NULL, WiFi_CC3100MOD_SPI_TxISRCallback, BSP_WiFi_CC3100MOD_SPI_Handle.
Referenced by USART0_TX_IRQHandler.
static void WiFi_INT_InterruptCallback(void)
References WiFi_CC3100MOD_ISRCallback.
Referenced by BSP_WiFi_CC3100MOD_Enable.