BSP_BT_EM9301.c
BCDS_MODULE_ID
BSP_BT_EM9301_Retcode_E
struct MCU_UART_Handle_S BSP_BT_EM9301_UART_Handle
Referenced by BSP_BT_EM9301_Enable, BSP_BT_EM9301_GetUARTHandle, BT_EM9301_UART_TxISR, BT_EM9301_UART_RxISR.
UART_IRQ_Callback_T BT_EM9301_UART_RxISRCallback
Referenced by BSP_BT_EM9301_Enable, BSP_BT_EM9301_Disable, BT_EM9301_UART_RxISR.
UART_IRQ_Callback_T BT_EM9301_UART_TxISRCallback
Referenced by BSP_BT_EM9301_Enable, BSP_BT_EM9301_Disable, BT_EM9301_UART_TxISR.
BSPLock_T BT_GPIOLock
Referenced by BSP_BT_EM9301_Enable, BSP_BT_EM9301_Disable, BSP_BT_EM9301_SetWUHigh, BSP_BT_EM9301_SetWULow.
Retcode_T BSP_BT_EM9301_Connect(void)
References BT_IRQ_PORT, BT_IRQ_PIN, BT_IRQ_MODE, BT_RST_PORT, BT_RST_PIN, BT_RST_MODE, BT_UART0_RX_PORT, BT_UART0_RX_PIN, BT_UART0_RX_MODE, BT_UART0_TX_PORT, BT_UART0_TX_PIN, BT_UART0_TX_MODE, BT_WAKEUP_PORT, BT_WAKEUP_PIN, BT_WAKEUP_MODE, BT_UART0_CLOCK, BT_SERIAL_PORT, RETCODE_OK.
Retcode_T BSP_BT_EM9301_Disable(void)
References RETCODE_OK, BT_SERIAL_PORT, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_FAILURE, BT_GPIOLock, BSP_LOCKED, BT_UART_RX_IRQn, BT_UART_TX_IRQn, BT_EM9301_UART_RxISRCallback, NULL, BT_EM9301_UART_TxISRCallback, BSP_BT_EM9301_Reset.
Retcode_T BSP_BT_EM9301_Disconnect(void)
References BT_IRQ_PORT, BT_IRQ_PIN, BT_RST_PORT, BT_RST_PIN, BT_UART0_RX_PORT, BT_UART0_RX_PIN, BT_UART0_TX_PORT, BT_UART0_TX_PIN, BT_WAKEUP_PORT, BT_WAKEUP_PIN, RETCODE_OK.
Retcode_T BSP_BT_EM9301_Enable(void)
References RETCODE_OK, NULL, BSP_BT_EM9301_UART_Handle, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_BSP_BT_SERIAL_NOT_INITIALIZED, Board_WakeupPowerSupply2V5, BT_EM9301, Board_Delay, BT_STARTUP_DELAY_MS, BT_UART0_CLOCK, BT_SERIAL_PORT, BT_EM9301_UART_RxISRCallback, BT_EM9301_UART_TxISRCallback, BT_UART_RX_IRQn, BT_UART_RX_PRIORITY, BT_UART_TX_IRQn, BT_UART_TX_PRIORITY, BT_GPIOLock, BSP_UNLOCKED, RETCODE_FAILURE.
HWHandle_T BSP_BT_EM9301_GetUARTHandle(void)
References BSP_BT_EM9301_UART_Handle, BCDS_HAL_TRANSFER_MODE_INTERRUPT.
Retcode_T BSP_BT_EM9301_Reset(void)
References BT_RST_PORT, BT_RST_PIN, BSP_Board_Delay, BT_RESET_PULLUP_DELAY_MS, BT_RESET_PROCESSING_DELAY_MS, RETCODE_OK.
Referenced by BSP_BT_EM9301_Disable.
Retcode_T BSP_BT_EM9301_SetWUHigh(void)
References RETCODE_OK, BSP_UNLOCKED, BT_GPIOLock, BT_WAKEUP_PORT, BT_WAKEUP_PIN, Board_Delay, BT_WAKEUP_DELAY_MS, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_BSP_BT_DISABLED.
Retcode_T BSP_BT_EM9301_SetWULow(void)
References RETCODE_OK, BSP_UNLOCKED, BT_GPIOLock, BT_WAKEUP_PORT, BT_WAKEUP_PIN, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_BSP_BT_DISABLED.
void BT_EM9301_UART_RxISR(void)
UART receive interrupt service routine used to capture interrupts at the UART resource and to forward them to the MCU driver for processing.
References NULL, BT_EM9301_UART_RxISRCallback, BSP_BT_EM9301_UART_Handle.
Referenced by UART0_RX_IRQHandler.
void BT_EM9301_UART_TxISR(void)
UART transmit interrupt service routine used to capture interrupts at the UART resource and to forward them to the MCU driver for processing.
References NULL, BT_EM9301_UART_TxISRCallback, BSP_BT_EM9301_UART_Handle.
Referenced by UART0_TX_IRQHandler.