BSP_BoardShared.h
BSPLock_E
Peripherals_E
typedef enum BSPLock_E BSPLock_T
typedef union EXTILineEven_U EXTILineEven_T
typedef union EXTILineOdd_U EXTILineOdd_T
typedef void(* GPIOINT_IrqCallbackPtr_t)(void))(void)
GPIO interrupt callback function pointer.
Parameters: pin - The pin index the callback function is invoked for.
typedef union GPIOPorts_U GPIOPorts_T
typedef union I2C0Register_U I2C0Register_T
typedef enum Peripherals_E Peripherals_T
typedef union PowerSupply2V5Register_U PowerSupply2V5Register_T
typedef union PowerSupply3V3Register_U PowerSupply3V3Register_T
BSPLock_T ADCLock
Referenced by BSP_Charger_BQ2405X_MeasureSignal.
I2C0Register_T BSP_I2C0
OStoBSPDelayFunc_T OStoBSPdelayFunc
Referenced by BSP_Board_SetOStoBSPDelayFunc, BSP_UMTS_LisaU2_Disable, BSP_UMTS_LisaU2_Reset, BSP_UMTS_QuectelUC20_Enable, BSP_UMTS_QuectelUC20_PowerOn, BSP_UMTS_QuectelUC20_PowerOff, BSP_UMTS_QuectelUC20_Reset, BSP_WiFi_CC3100MOD_Enable.
BSP_Systick_Callback_T SysTickOsPostProcessing
Performs operations Post to SysTick count increment.
This function is initialized during BSP_Board_OSTickInitialize() and makes it possible for the application to perform some operations after the SysTick counter has is incremented (e.g. context switching in OS based applications) This function is called in SysTick_Handler() function in IrqHandler.c file
Referenced by BSP_Board_OSTickInitialize.
BSP_Systick_Callback_T SysTickOsPreProcessing
Performs operations prior to SysTick count increment.
This function is initialized during BSP_Board_OSTickInitialize() and makes it possible for the application to perform some operations before the SysTick counter is incremented (e.g. context switching in OS based applications) This function is called in SysTick_Handler() function in IrqHandler.c file
Referenced by BSP_Board_OSTickInitialize.
USB_lineCoding_t __attribute__((aligned(4))) USB_lineCoding_mds
void Board_Delay(uint32_t delay)
Provide a delay in millisecond.
delay delay time in ms;
References Board_GetTick.
Referenced by BSP_Board_Initialize, BSP_BT_EM9301_Enable, BSP_BT_EM9301_SetWUHigh, BSP_LoRa_RN2xx3_Enable, BSP_SensorNode_Enable, BSP_UMTS_LisaU2_Reset, BSP_WiFi_CC3100MOD_Enable, BSP_WiFi_CC3100MOD_Disable, BSP_WiFi_CC3100MOD_Wakeup, BSP_WiFi_CC3100MOD_Hibernate, BSP_WiFi_CC3100MOD_Reset.
void Board_DisablePowerSupply3V3(Peripherals_T Peripheral)
Disables the 3V3 power rail.
This function holds a register of the connected peripherals to the power supply and if a peripheral requests disabling it, the corresponding bit field is Reset and the register and if this register equals zero then the power rail is safe to be disabled. Peripheral : enumerated value representing the peripheral requesting the Disabling of the power supply RETCODE_OK in case of success error code otherwise.
References PowerSupply3V3UpdateRegister, PowerSupply3V3Register_U::Register, PWR_3V3_EN_PORT, PWR_3V3_EN_PIN.
Referenced by BSP_IRSensorNode_Disable, BSP_Max31865_Disconnect, BSP_UMTS_QuectelUC20_Disable.
void Board_EnablePowerSupply3V3(Peripherals_T Peripheral)
Enables the 3V3 power rail.
This function holds a register of the connected peripherals to the power supply and if a peripheral requests enabling it, the MCU output enabling the Power rail is Set its and the corresponding peripheral bit field is Set Peripheral : enumerated value representing the peripheral requesting the Enabling of the power supply RETCODE_OK in case of success error code otherwise.
References PowerSupply3V3Register_U::Register, PowerSupply3V3UpdateRegister, PWR_3V3_EN_PORT, PWR_3V3_EN_PIN.
Referenced by BSP_IRSensorNode_Enable, BSP_Max31865_Connect, BSP_UMTS_QuectelUC20_Enable.
uint32_t Board_GetTick(void)
Provide a tick value in millisecond.
tick value
References BSP_Tick.
Referenced by BSP_Board_Delay, Board_Delay.
void Board_GPIOInterruptDispatch(uint32_t iflags)
Function calls users callback for registered pin interrupts.
This function is called when GPIO interrupts are handled by the dispatcher. Function gets even or odd interrupt flags and calls user callback registered for that pin. Function iterates on flags starting from MSB. iflags Interrupt flags which shall be handled by the dispatcher.
References gpioCallbacks.
Referenced by GPIO_EVEN_IRQHandler, GPIO_ODD_IRQHandler.
GPIOINT_IrqCallbackPtr_t Board_GPIOInterruptGetCallback(uint8_t pin)
Returns the callback pointer.
This function is used to query the callback function registered for the requested pin. pin The pin number. The callback pointer.
References gpioCallbacks.
Referenced by BSP_SensorNode_Enable.
void Board_GPIOInterruptRegisterCallback(uint8_t pin, GPIOINT_IrqCallbackPtr_t callbackPtr)
Registers user callback for given pin number.
Use this function to register a callback which shall be called upon interrupt generated from given pin number (port is irrelevant). Interrupt itself must be configured externally. Function overwrites previously registered callback. pin Pin number for the callback. callbackPtr A pointer to callback function.
References gpioCallbacks.
Referenced by Board_GPIOInterruptUnregisterCallback, BSP_SensorNode_Enable, BSP_WiFi_CC3100MOD_Enable.
static void Board_GPIOInterruptUnregisterCallback(uint8_t pin)
Unregisters user callback for given pin number.
Use this function to unregister a callback. pin Pin number for the callback.
References Board_GPIOInterruptRegisterCallback.
Referenced by BSP_SensorNode_Disable, BSP_WiFi_CC3100MOD_Disable.
void Board_IncTick(void)
This function is called to increment a global variable "BSP_Tick" used as application time base.
In the default implementation, this variable is incremented each 1ms in SysTick ISR. None
References BSP_Tick.
void Board_SnoozePowerSupply2V5(Peripherals_T Peripheral)
Puts the 2V5 power rail on low power mode(snooze).
This function holds a register of the connected peripherals to the power supply and if a peripheral requests disabling it, the corresponding bit field is Reset and the register and if this register equals zero then the power rail is safe to be scaled down. Peripheral : enumerated value representing the peripheral requesting the Snoozing of the power supply RETCODE_OK in case of success error code otherwise.
References PowerSupply2V5UpdateRegister, PowerSupply2V5Register_U::Register, PWR_2V5_SNOOZE_PORT, PWR_2V5_SNOOZE_PIN.
Referenced by BSP_IRSensorNode_Disable, BSP_LoRa_RN2xx3_Disconnect, BSP_Max31865_Disconnect, BSP_Mic_AKU340_Disable, BSP_UMTS_LisaU2_Disconnect, BSP_UMTS_QuectelUC20_Disable, BSP_WiFi_CC3100MOD_Disable.
void Board_WakeupPowerSupply2V5(Peripherals_T Peripheral)
Performs operations prior to SysTick count increment.
This function is initialized during BSP_Board_OSTickInitialize() and makes it possible for the application to perform some operations before the SysTick counter is incremented (e.g. context switching in OS based applications) This function is called in SysTick_Handler() function in IrqHandler.c file Wakes up the 2V5 power rail This function holds a register of the connected peripherals to the power supply and if a peripheral requests enabling it, the MCU output enabling the Power rail is Set its and the corresponding peripheral bit field is Set Peripheral : enumerated value representing the peripheral requesting the Enabling of the power supply
References PowerSupply2V5Register_U::Register, PowerSupply2V5UpdateRegister, PWR_2V5_SNOOZE_PORT, PWR_2V5_SNOOZE_PIN.
Referenced by BSP_Board_Initialize, BSP_BT_EM9301_Enable, BSP_IRSensorNode_Enable, BSP_LoRa_RN2xx3_Enable, BSP_Max31865_Connect, BSP_Mic_AKU340_Enable, BSP_UMTS_LisaU2_EnableGpio, BSP_UMTS_QuectelUC20_Enable, BSP_WiFi_CC3100MOD_Enable.