BSP_WiFi_cc3100mod.h
void WiFi_CC3100MOD_SPI_RxDMAComplete(uint32_t channel, bool primary, void *user)
SPI rx dma interrupt service routine used to capture interrupts at the SPI resource and to forward them to the MCU driver for processing.
Referenced by BSP_WiFi_CC3100MOD_Connect.
void WiFi_CC3100MOD_SPI_TxDMAComplete(uint32_t channel, bool primary, void *user)
SPI tx dma interrupt service routine used to capture interrupts at the SPI resource and to forward them to the MCU driver for processing.
Referenced by BSP_WiFi_CC3100MOD_Connect.
void WiFi_CC3100MOD_SPIRxISR(void)
SPI receive interrupt service routine used to capture interrupts at the SPI resource and to forward them to the MCU driver for processing.
References NULL, WiFi_CC3100MOD_SPI_RxISRCallback, BSP_WiFi_CC3100MOD_SPI_Handle.
Referenced by USART0_RX_IRQHandler.
void WiFi_CC3100MOD_SPITxISR(void)
SPI transmit interrupt service routine used to capture interrupts at the SPI resource and to forward them to the MCU driver for processing.
References NULL, WiFi_CC3100MOD_SPI_TxISRCallback, BSP_WiFi_CC3100MOD_SPI_Handle.
Referenced by USART0_TX_IRQHandler.