BSP_SensorNode.c
BCDS_MODULE_ID
BMA280_STARTUP_DELAY
macro used to represent the delay required for BMA280 after the power-up
Referenced by BSP_SensorNode_Enable.
BME280_STARTUP_DELAY
macro used to represent the delay required for BME280 after the power-up
Referenced by BSP_SensorNode_Enable.
BMG160_STARTUP_DELAY
macro used to represent the delay required for BMG160 after the power-up
Referenced by BSP_SensorNode_Enable.
BMI160_STARTUP_DELAY
macro used to represent the delay required for BMI160 after the power-up
Referenced by BSP_SensorNode_Enable.
BMM150_STARTUP_DELAY
macro used to represent the delay required for BMM150 after the power-up
Referenced by BSP_SensorNode_Enable.
MAX44009_STARTUP_DELAY
macro used to represent the delay required for MAX4409 after the power-up
Referenced by BSP_SensorNode_Enable.
@29
@30
@31
@32
@33
Retcode_SensorNode_E
bool BMA280UsesINT1
bool BMA280UsesINT2
bool BMG160UsesINT1
bool BMG160UsesINT2
bool BMI160UsesINT1
bool BMI160UsesINT2
bool BMM150UsesDRDY
bool BMM150UsesINT
I2C0Register_T BSP_I2C0
struct MCU_I2C_Handle_S BSP_SensorNode_I2C_Handle
Referenced by BSP_SensorNode_GetI2CHandle, SensorNode_EnableBus, SensorNode_I2CISR.
bool MAX44009UsesINTN
BSP_Sensor_InterruptCallback_T SensorNode_BMA280ISRCallback
Referenced by BSP_SensorNode_Enable, BSP_SensorNode_Disable, BMA280_INT_InterruptCallback, BMA280_INT2_InterruptCallback.
BSP_Sensor_InterruptCallback_T SensorNode_BMG160ISRCallback
Referenced by BSP_SensorNode_Enable, BSP_SensorNode_Disable, BMG160_INT2_InterruptCallback, BMG160_INT1_InterruptCallback.
BSP_Sensor_InterruptCallback_T SensorNode_BMI160ISRCallback
Referenced by BSP_SensorNode_Enable, BSP_SensorNode_Disable, BMI160_INT2_InterruptCallback, BMI160_INT1_InterruptCallback.
BSP_Sensor_InterruptCallback_T SensorNode_BMM150ISRCallback
Referenced by BSP_SensorNode_Enable, BSP_SensorNode_Disable, BMM150_INT_InterruptCallback, BMM150_DRDY_InterruptCallback.
I2C_IRQ_Callback_T SensorNode_I2CISRCallback
Referenced by SensorNode_EnableBus, SensorNode_DisableBus, SensorNode_I2CISR.
BSP_Sensor_InterruptCallback_T SensorNode_MAX44009ISRCallback
Referenced by BSP_SensorNode_Enable, BSP_SensorNode_Disable, MAX44009_INTN_InterruptCallback.
struct @34 SensorsFlags
Referenced by BSP_SensorNode_Enable, BSP_SensorNode_Disable.
static void BMA280_INT2_InterruptCallback(void)
References BMA280_INTERRUPT_2, BSP_IO_PIN_LOW, BMA280_INT2_PORT, BMA280_INT2_PIN, BSP_FALLING_EDGE, BSP_RISING_EDGE, SensorNode_BMA280ISRCallback.
Referenced by BSP_SensorNode_Enable.
static void BMA280_INT_InterruptCallback(void)
References BMA280_INTERRUPT_1, BSP_IO_PIN_LOW, BMA280_INT1_PORT, BMA280_INT1_PIN, BSP_FALLING_EDGE, BSP_RISING_EDGE, SensorNode_BMA280ISRCallback.
Referenced by BSP_SensorNode_Enable.
static void BMG160_INT1_InterruptCallback(void)
References BMG160_INTERRUPT_1, BSP_IO_PIN_LOW, BMG160_INT1_PORT, BMG160_INT1_PIN, BSP_FALLING_EDGE, BSP_RISING_EDGE, SensorNode_BMG160ISRCallback.
Referenced by BSP_SensorNode_Enable.
static void BMG160_INT2_InterruptCallback(void)
References BMG160_INTERRUPT_2, BSP_IO_PIN_LOW, BMG160_INT2_PORT, BMG160_INT2_PIN, BSP_FALLING_EDGE, BSP_RISING_EDGE, SensorNode_BMG160ISRCallback.
Referenced by BSP_SensorNode_Enable.
static void BMI160_INT1_InterruptCallback(void)
References BMI160_INTERRUPT_1, BSP_IO_PIN_LOW, BMI160_INT1_PORT, BMI160_INT1_PIN, BSP_FALLING_EDGE, BSP_RISING_EDGE, SensorNode_BMI160ISRCallback.
Referenced by BSP_SensorNode_Enable.
static void BMI160_INT2_InterruptCallback(void)
References BMI160_INTERRUPT_2, BSP_IO_PIN_LOW, BMI160_INT2_PORT, BMI160_INT2_PIN, BSP_FALLING_EDGE, BSP_RISING_EDGE, SensorNode_BMI160ISRCallback.
Referenced by BSP_SensorNode_Enable.
static void BMM150_DRDY_InterruptCallback(void)
References BMM150_DRDY, BSP_IO_PIN_LOW, BMM150_DRDY_PORT, BMM150_DRDY_PIN, BSP_FALLING_EDGE, BSP_RISING_EDGE, SensorNode_BMM150ISRCallback.
Referenced by BSP_SensorNode_Enable.
static void BMM150_INT_InterruptCallback(void)
References BMM150_INTERRUPT_1, BSP_IO_PIN_LOW, BMM150_INT_PORT, BMM150_INT_PIN, BSP_FALLING_EDGE, BSP_RISING_EDGE, SensorNode_BMM150ISRCallback.
Referenced by BSP_SensorNode_Enable.
Retcode_T BSP_SensorNode_Connect(void)
Maps the GPIO pins to their desired function.
This function once called will map the GPIO pins related to the sensor node to their desired functions. RETCODE_OK in the case of success or an error code otherwise.
References VDD_BMA280_PORT, VDD_BMA280_PIN, VDD_BMA280_MODE, VDD_BME280_PORT, VDD_BME280_PIN, VDD_BME280_MODE, VDD_BMG160_PORT, VDD_BMG160_PIN, VDD_BMG160_MODE, VDD_BMI160_PORT, VDD_BMI160_PIN, VDD_BMI160_MODE, VDD_BMM150_PORT, VDD_BMM150_PIN, VDD_BMM150_MODE, VDD_MAX44009_PORT, VDD_MAX44009_PIN, VDD_MAX44009_MODE, BMA280_INT1_PORT, BMA280_INT1_PIN, BMA280_INT1_MODE, BMA280_INT2_PORT, BMA280_INT2_PIN, BMA280_INT2_MODE, BMG160_INT1_PORT, BMG160_INT1_PIN, BMG160_INT1_MODE, BMG160_INT2_PORT, BMG160_INT2_PIN, BMG160_INT2_MODE, BMI160_INT1_PORT, BMI160_INT1_PIN, BMI160_INT1_MODE, BMI160_INT2_PORT, BMI160_INT2_PIN, BMI160_INT2_MODE, BMM150_DRDY_PORT, BMM150_DRDY_PIN, BMM150_DRDY_MODE, BMM150_INT_PORT, BMM150_INT_PIN, BMM150_INT_MODE, MAX44009_INTN_PORT, MAX44009_INTN_PIN, MAX44009_INTN_MODE, I2C0_SCL_PORT, I2C0_SCL_PIN, I2C0_SCL_MODE, I2C0_SDA_PORT, I2C0_SDA_PIN, I2C0_SDA_MODE, SENSOR_NODE_I2C_CLOCK, SENSOR_NODE_I2C_BUS, RETCODE_OK.
Referenced by SensorNodeMapping_Init.
Retcode_T BSP_SensorNode_Disable(uint32_t id)
Disables the control over the peripheral.
This function once called will disable control over the requested sensor peripheral by executing the disabling procedure as prescribed in the vendor datasheet. id identifier of the sensor targeted by the disable request. This is defined in the Board Interface under the BSP_Sensor_E enumeration. RETCODE_OK in the case of success or an error code otherwise.
References RETCODE_OK, BSP_XDK_SENSOR_BMA280, I2C0Register_U::Peripheral, I2C0Register_S::Sensor_BMA280, SensorNode_DisableBus, SensorsFlags, BMA280_INT1_PORT, BMA280_INT1_PIN, BMA280_INT1_EDGE_RISING, BMA280_INT1_EDGE_FALLING, BSP_DISABLE, SensorNode_BMA280ISRCallback, NULL, Board_GPIOInterruptUnregisterCallback, BMA280_INT2_PIN, BMA280_INT2_EDGE_RISING, BMA280_INT2_EDGE_FALLING, BMA280_INT2_PORT, VDD_BMA280_PORT, VDD_BMA280_PIN, BSP_XDK_SENSOR_BMG160, I2C0Register_S::Sensor_BMG160, BMG160_INT1_PORT, BMG160_INT1_PIN, BMG160_INT1_EDGE_RISING, BMG160_INT1_EDGE_FALLING, SensorNode_BMG160ISRCallback, BMG160_INT2_PORT, BMG160_INT2_PIN, BMG160_INT2_EDGE_RISING, BMG160_INT2_EDGE_FALLING, VDD_BMG160_PORT, VDD_BMG160_PIN, BSP_XDK_SENSOR_BME280, I2C0Register_S::Sensor_BME280, VDD_BME280_PORT, VDD_BME280_PIN, BSP_XDK_SENSOR_BMM150, I2C0Register_S::Sensor_BMM150, BMM150_INT_PORT, BMM150_INT_PIN, BMM150_INT_EDGE_RISING, BMM150_INT_EDGE_FALLING, SensorNode_BMM150ISRCallback, BMM150_DRDY_PORT, BMM150_DRDY_PIN, BMM150_DRDY_EDGE_RISING, BMM150_DRDY_EDGE_FALLING, VDD_BMM150_PORT, VDD_BMM150_PIN, BSP_XDK_SENSOR_MAX44009, I2C0Register_S::Sensor_MAX44009, MAX44009_INTN_PORT, MAX44009_INTN_PIN, MAX44009_INTN_EDGE_RISING, MAX44009_INTN_EDGE_FALLING, SensorNode_MAX44009ISRCallback, VDD_MAX44009_PORT, VDD_MAX44009_PIN, BSP_XDK_SENSOR_BMI160, I2C0Register_S::Sensor_BMI160, BMI160_INT1_PORT, BMI160_INT1_PIN, BMI160_INT1_EDGE_RISING, BMI160_INT1_EDGE_FALLING, SensorNode_BMI160ISRCallback, BMI160_INT2_PIN, BMI160_INT2_PORT, VDD_BMI160_PORT, VDD_BMI160_PIN, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM.
Referenced by Bma280Utils_uninitialize, Bme280Utils_uninitialize, Bmg160Utils_uninitialize, Bmm150Utils_uninitialize, Max44009Utils_uninitialize.
Retcode_T BSP_SensorNode_Disconnect(void)
Disconnects the sensor node.
This function disconnects the GPIO pins dedicated to the sensor node and put them into low power consumption status. RETCODE_OK in the case of success or an error code otherwise.
References VDD_BMA280_PORT, VDD_BMA280_PIN, VDD_BME280_PORT, VDD_BME280_PIN, VDD_BMG160_PORT, VDD_BMG160_PIN, VDD_BMI160_PORT, VDD_BMI160_PIN, VDD_BMM150_PORT, VDD_BMM150_PIN, VDD_MAX44009_PORT, VDD_MAX44009_PIN, BMA280_INT1_PORT, BMA280_INT1_PIN, BMA280_INT2_PORT, BMA280_INT2_PIN, BMG160_INT1_PORT, BMG160_INT1_PIN, BMG160_INT2_PORT, BMG160_INT2_PIN, BMI160_INT1_PORT, BMI160_INT1_PIN, BMI160_INT2_PORT, BMI160_INT2_PIN, BMM150_DRDY_PORT, BMM150_DRDY_PIN, BMM150_INT_PORT, BMM150_INT_PIN, MAX44009_INTN_PORT, MAX44009_INTN_PIN, I2C0_SCL_PORT, I2C0_SCL_PIN, I2C0_SDA_PORT, I2C0_SDA_PIN, SENSOR_NODE_I2C_CLOCK, SENSOR_NODE_I2C_BUS, RETCODE_OK.
Referenced by SensorNodeMapping_DeInit.
Retcode_T BSP_SensorNode_Enable(uint32_t id, BSP_Sensor_InterruptCallback_T callback)
Enables the control over the peripheral.
A prior call to MCU_<RESOURCE>_Initialize() is necessary for this function in order to operate.This function once called will allow the required sensor peripheral to receive, execute commands and transmit process data. id identifier of the sensor targeted by the enable request. callback If the sensor has dedicated interrupt lines a callback is required to process the generated events. RETCODE_OK in the case of success or an error code otherwise.
References RETCODE_OK, BSP_XDK_SENSOR_BMA280, I2C0Register_U::Peripheral, I2C0Register_S::Sensor_BMA280, VDD_BMA280_PORT, VDD_BMA280_PIN, VDD_BMA280_MODE, Board_Delay, BMA280_STARTUP_DELAY, SensorNode_EnableBus, BSP_XDK_SENSOR_BMA280_ENABLE_INTERRUPT, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM, BSP_XDK_SENSOR_BMA280_FORCE_INTERRUPT, Board_GPIOInterruptGetCallback, BMA280_INT2_PIN, BMA280_INT1_PORT, BMA280_INT1_PIN, SensorNode_BMA280ISRCallback, Board_GPIOInterruptRegisterCallback, BMA280_INT_InterruptCallback, BMA280_INT1_EDGE_RISING, BMA280_INT1_EDGE_FALLING, BSP_ENABLE, SensorsFlags, RETCODE_SEVERITY_INFO, RETCODE_BSP_SENSOR_NODE_BMA280_INT2_BUSY, BMA280_INT2_PORT, BMA280_INT2_InterruptCallback, BMA280_INT2_EDGE_RISING, BMA280_INT2_EDGE_FALLING, RETCODE_SENSOR_NODE_BMA280_ENABLED, BSP_XDK_SENSOR_BMG160, I2C0Register_S::Sensor_BMG160, VDD_BMG160_PORT, VDD_BMG160_PIN, VDD_BMG160_MODE, BMG160_STARTUP_DELAY, BSP_XDK_SENSOR_BMG160_ENABLE_INTERRUPT, BMG160_INT1_PORT, BMG160_INT1_PIN, BMG160_INT2_PORT, BMG160_INT2_PIN, SensorNode_BMG160ISRCallback, BMG160_INT1_InterruptCallback, BMG160_INT2_InterruptCallback, BMG160_INT1_EDGE_RISING, BMG160_INT1_EDGE_FALLING, BMG160_INT2_EDGE_RISING, BMG160_INT2_EDGE_FALLING, RETCODE_SENSOR_NODE_BMG160_ENABLED, BSP_XDK_SENSOR_BME280, I2C0Register_S::Sensor_BME280, VDD_BME280_PORT, VDD_BME280_PIN, VDD_BME280_MODE, BME280_STARTUP_DELAY, RETCODE_SENSOR_NODE_BME280_ENABLED, BSP_XDK_SENSOR_BMM150, I2C0Register_S::Sensor_BMM150, VDD_BMM150_PORT, VDD_BMM150_PIN, VDD_BMM150_MODE, BMM150_STARTUP_DELAY, BSP_XDK_SENSOR_BMM150_ENABLE_INTERRUPT, BSP_XDK_SENSOR_BMM150_FORCE_INTERRUPT, BMM150_INT_PIN, BMM150_DRDY_PORT, BMM150_DRDY_PIN, SensorNode_BMM150ISRCallback, BMM150_DRDY_InterruptCallback, BMM150_DRDY_EDGE_RISING, BMM150_DRDY_EDGE_FALLING, RETCODE_BSP_SENSOR_NODE_BMM150_INT_BUSY, BMM150_INT_PORT, BMM150_INT_InterruptCallback, BMM150_INT_EDGE_RISING, BMM150_INT_EDGE_FALLING, RETCODE_SENSOR_NODE_BMM150_ENABLED, BSP_XDK_SENSOR_MAX44009, I2C0Register_S::Sensor_MAX44009, VDD_MAX44009_PORT, VDD_MAX44009_PIN, VDD_MAX44009_MODE, MAX44009_STARTUP_DELAY, BSP_XDK_SENSOR_MAX44009_ENABLE_INTERRUPT, MAX44009_INTN_PORT, MAX44009_INTN_PIN, SensorNode_MAX44009ISRCallback, MAX44009_INTN_InterruptCallback, MAX44009_INTN_EDGE_RISING, MAX44009_INTN_EDGE_FALLING, RETCODE_SENSOR_NODE_MAX44009_ENABLED, BSP_XDK_SENSOR_BMI160, I2C0Register_S::Sensor_BMI160, VDD_BMI160_PORT, VDD_BMI160_PIN, VDD_BMI160_MODE, BMI160_STARTUP_DELAY, BSP_XDK_SENSOR_BMI160_ENABLE_INTERRUPT, BSP_XDK_SENSOR_BMI160_FORCE_INTERRUPT, BMI160_INT2_PIN, BMI160_INT1_PORT, BMI160_INT1_PIN, SensorNode_BMI160ISRCallback, BMI160_INT1_InterruptCallback, BMI160_INT1_EDGE_RISING, BMI160_INT1_EDGE_FALLING, RETCODE_BSP_SENSOR_NODE_BMI160_INT2_BUSY, BMI160_INT2_PORT, BMI160_INT2_InterruptCallback, BMI160_INT2_EDGE_RISING, BMI160_INT2_EDGE_FALLING, RETCODE_SENSOR_NODE_BMI160_ENABLED.
Referenced by Bma280Utils_initialize, Bme280Utils_initialize, Bmg160Utils_initialize, Bmm150Utils_initialize, Max44009Utils_initialize.
HWHandle_T BSP_SensorNode_GetI2CHandle(void)
Returns the handle of the communication interface used by the peripheral in case I2C is used for the sensor node.
After successful execution of BSP_Board_Initialize(param1, param2), the application is free to call this function in order to get the handle needed by the resources drivers. This handle will be used by the MCU drivers for the intended resources I2C, SPI, UART, etc. HWHandle_T: Handle for the used MCU resource.
References BSP_SensorNode_I2C_Handle, SENSOR_NODE_I2C_BUS, BCDS_HAL_TRANSFER_MODE_INTERRUPT.
Referenced by SensorNodeMapping_Init, SensorNodeMapping_DeInit.
bool BSP_SensorNode_IsAllNodesDisabled(void)
Returns the boolean (TRUE/FALSE) based on the sensor node Enable/Disable status used by the peripheral in case I2C is used for the sensor node.
only after successful Disable of all the sensor nodes this API will return TRUE. Even if one sensor node is enabled then we get FALSE from this API Bool: Boolean (TRUE/FALSE).
References I2C0Register_U::Register.
Referenced by SensorNodeMapping_DeInit.
static void MAX44009_INTN_InterruptCallback(void)
References MAX44009_INTN, BSP_IO_PIN_LOW, MAX44009_INTN_PORT, MAX44009_INTN_PIN, BSP_FALLING_EDGE, BSP_RISING_EDGE, SensorNode_MAX44009ISRCallback.
Referenced by BSP_SensorNode_Enable.
static void SensorNode_DisableBus(void)
Disables the I2C bus.
This function disables the bus if it is not in use by any sensor Sensor the sensor requesting to be enabled
References I2C0Register_U::Register, SENSOR_NODE_I2C_IRQn, SensorNode_I2CISRCallback, NULL, SENSOR_NODE_I2C_BUS, SENSOR_NODE_I2C_CLOCK.
Referenced by BSP_SensorNode_Disable.
static void SensorNode_EnableBus(void)
Enable the I2C bus.
This function enables the bus and registers the sensor in the bus shared register Sensor the sensor requesting to be enabled
References I2C0Register_U::Register, SENSOR_NODE_I2C_CLOCK, NULL, BSP_SensorNode_I2C_Handle, SensorNode_I2CISRCallback, SENSOR_NODE_I2C_IRQn, SENSOR_NODE_I2C_PRIORITY, SENSOR_NODE_I2C_BUS.
Referenced by BSP_SensorNode_Enable.
void SensorNode_I2CISR(void)
I2C interrupt service routine used to capture events at the I2C resource and to forward them to the MCU driver for processing.
References NULL, SensorNode_I2CISRCallback, BSP_SensorNode_I2C_Handle.
Referenced by I2C0_IRQHandler.