BSP_LoRa_RN2xx3.c
BCDS_MODULE_ID
static void BreakAndSync(uint32_t baudrate)
References BSP_ENABLE, LORA_SERIAL_PORT, LORA_BREAK_BAUDRATE, LORA_BREAK_SYNC_CHAR, BSP_DISABLE.
Referenced by BSP_LoRa_RN2xx3_ChangeBaudrate, BSP_LoRa_RN2xx3_WakeUp.
Retcode_T BSP_LoRa_RN2xx3_ChangeBaudrate(uint32_t baudrate)
Changes the baudrate of the communication interface.
baudrate desired baudrate -if 0 will keep the current baudrate and send a break command with synchronization frame could be used to wakeup the module from sleep according to datasheet. RETCODE_OK in the case of success or an error code otherwise.
References BreakAndSync, NULL, RETCODE_OK.
Retcode_T BSP_LoRa_RN2xx3_Connect(void)
Maps the GPIO pins to their desired function.
This function once called will map the GPIO pins to their desired functions to drive the Microchip(R) RN2483/RN2903 LPWAN (LoRa) peripheral. It is needed to call this function prior to the BSP_LoRa_RN2xx3_Enable(). RETCODE_OK in the case of success or an error code otherwise.
References RETCODE_OK, LORA_RTS_PIN, LORA_CTS_PIN, LORA_RESET_PIN.
Retcode_T BSP_LoRa_RN2xx3_Disable(void)
Disables the control over the peripheral.
This function once called will disable control over the Microchip(R) RN2483/RN2903 LPWAN (LoRa) peripheral by executing the disabling procedure as prescribed in the vendor datasheet. RETCODE_OK in the case of success or an error code otherwise.
References RETCODE_OK, LORA_RTS_PIN, LORA_CTS_PIN, LORA_RESET_PIN.
Retcode_T BSP_LoRa_RN2xx3_Disconnect(void)
Disconnects the LPWAN (LoRa) peripheral.
This function disconnects the GPIO pins dedicatded to the Microchip(R) RN2483/RN2903 LPWAN (LoRa) peripheral and put them into low power consumption status. RETCODE_OK in the case of success or an error code otherwise.
References RETCODE_OK, LORA_RTS_PIN, LORA_CTS_PIN, LORA_RESET_PIN, Board_SnoozePowerSupply2V5, EXTENSION_BOARD.
Retcode_T BSP_LoRa_RN2xx3_Enable(void)
Enables the control over the peripheral.
A prior call to MCU_<RESOURCE>_Initialize() is necessary for this function in order to operate.This function once called will allow the Microchip(R) RN2483/RN2903 LPWAN (LoRa) peripheral to receive, execute commands and transmit process data. RETCODE_OK in the case of success or an error code otherwise.
References RETCODE_OK, Board_WakeupPowerSupply2V5, EXTENSION_BOARD, Board_Delay, LORA_STARTUP_DELAY_MS, LORA_BAUDRATE, NULL, LORA_RTS_PIN, LORA_CTS_PIN, LORA_RESET_PIN, BSP_LoRa_RN2xx3_SetResetPin.
HWHandle_T BSP_LoRa_RN2xx3_GetUartHandle(void)
Returns the UART handle of the communication interface used by the peripheral.
After successful execution of BSP_Board_Initialize(param1, param2), the application is free to call this function in order to get the handle needed by the resources drivers. This handle will be used by the MCU drivers for the intended resource. HWHandle_T: Handle for the used MCU resource.
Retcode_T BSP_LoRa_RN2xx3_SetResetPin(uint32_t state)
Sets the reset pin of the module to the desired state Low or High.
0 for Low 1 for High RETCODE_OK in the case of success or an error code otherwise.
References RETCODE_OK, LORA_RESET_PIN.
Referenced by BSP_LoRa_RN2xx3_Enable.
Retcode_T BSP_LoRa_RN2xx3_WakeUp(void)
Sends wake-up signal to the LoRa module.
RETCODE_OK in the case of success or an error code otherwise.
References BreakAndSync, LORA_BAUDRATE, RETCODE_OK.