BatteryMonitor.c
BATTERYMONITOR_ADC_REFERENCE
ADC reference voltage is configured to 2.5 Volts
Referenced by BatteryMonitor_MeasureSignal.
BATTERYMONITOR_ADC_RESOLUTION
ADC resolution is configured to 12 bit hence 2^12=4096
Referenced by BatteryMonitor_MeasureSignal.
BCDS_MODULE_ID
SemaphoreHandle_t AdcSampleSemaphore
Referenced by AdcSampleIRQCallback, BatteryMonitor_Init, BatteryMonitor_MeasureSignal.
bool IsInitialized
Referenced by BatteryMonitor_Init, BatteryMonitor_MeasureSignal.
void AdcSampleIRQCallback(ADC_T adc, uint16_t *buffer)
References BCDS_UNUSED, xSemaphoreGiveFromISR, AdcSampleSemaphore, portYIELD_FROM_ISR.
Referenced by BatteryMonitor_MeasureSignal.
Retcode_T BatteryMonitor_Init(void)
Initialize the Battery monitor module.
: Enables the Battery Charger & Initialize the Battery monitor to measure the battery voltage RETCODE_OK in case of successfully Initializing the Battery monitor. RETCODE_SEMAPHORE_ERROR in case not able to create Semaphore.
References RETCODE_OK, IsInitialized, AdcSampleSemaphore, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_SEMAPHORE_ERROR, BSP_XDK_CHARGING_SPEED_1, AdcCentral_Init.
Referenced by LWM2MObjectDevice_Init.
Retcode_T BatteryMonitor_MeasureSignal(uint32_t *outputVoltage)
Measures the specified voltage signal.
: the analog signals from the charger routed to the MCU could be fetched using this functionThis function once called will return the value of the specified signal in millivolts. outputVoltage measured battery voltage in millivolts RETCODE_OK in case of successfully getting the battery voltage. RETCODE_NULL_POINTER in case of NULL pointer passed. RETCODE_BSP_CHARGER_NOT_ENABLED in case of accessing before enabling the charger.
References RETCODE_OK, AdcCentral_ConfigSingle_S::AcqTime, ADC_ACQ_TIME_16, AdcCentral_ConfigSingle_S::Appcallback, AdcSampleIRQCallback, AdcCentral_ConfigSingle_S::BufferPtr, AdcCentral_ConfigSingle_S::Channel, ADC_ENABLE_CH7, AdcCentral_ConfigSingle_S::Reference, ADC_REF_2V5, AdcCentral_ConfigSingle_S::Resolution, ADC_RESOLUTION_12BIT, IsInitialized, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_BATTERY_MONITOR_NOT_INIT, AdcCentral_StartSingle, xSemaphoreTake, AdcSampleSemaphore, RETCODE_TIMEOUT, BATTERYMONITOR_ADC_REFERENCE, BATTERYMONITOR_ADC_RESOLUTION.
Referenced by powerSourceVoltageFunc, batteryLevelFunc, batteryStatusFunc.