Bma280Utils.c
BCDS_MODULE_ID
BMA280_MAX_ALLOWED_SLOPE_DURATION
macro to set maximum allowed slope duration
Referenced by configureSlopeInterrupt.
CONFIGURATION_DELAY
macro used to represent the delay needed between changing the configuration and enabling the interrupt variable to check initialization status
Referenced by configureSlopeInterrupt.
DISABLE_INTERRUPT
macro used to disable the interrupt
Referenced by configureSlopeInterrupt, Bma280Utils_disableInterrupt.
ENABLE_INTERRUPT
macro used to enable the interrupt
Referenced by configureNewDataInterrupt, configureSlopeInterrupt.
struct bma2x2_t bma280Initialization
Referenced by Bma280Utils_initialize.
bool initializationStatus
BMA280 initialization structure
Referenced by Bma280Utils_initialize, Bma280Utils_remapAxis, Bma280Utils_configInterrupt, Bma280Utils_disableInterrupt, Bma280Utils_uninitialize.
Retcode_T Bma280Utils_configInterrupt(Bma280Utils_InfoPtr_T bma280Info, Bma280Utils_ConfigInterruptPtr_T interruptConfig)
Function to Configure interrupts of Bma280. Before calling this API Update the below information in the appropriate structure 1) Update callback function in Bma280Utils_InfoPtr_T. 2) Update the type of callback(deferred or real time) in Bma280Utils_InfoPtr_T. 3) Update interrupt type and channel to Which interrupt needs be associated in Bma280Utils_ConfigInterrupt_T. 4) Update Bma280Utils_IntrConfigPtr_T with appropriate interrupt configuration After calling this API the given interrupt will be enabled on the given channel and the callback will be associated with the interrupt.
bma280Info :Structure holding the bma280 specific configurations.Callback for the interrupt and its type should be given in this handle interruptConfig :Structure holding the information about interrupt type,channel and its related configuration should be given here RETCODE_OK Configuration of interrupt for BMA280 is success. RETCODE_NULL_POINTER when any of the input parameter(interruptConfig & interruptConfig->configInterrupt) is NULL. RETCODE_LIB_NULL_POINTER when any of the input parameter for BST library API is NULL. RETCODE_BST_BMA280_ERROR when error is returned from BST library API. RETCODE_INVALID_PARAM when the interrupt configuration parameter is invalid. RETCODE_UNINITIALIZED when this api is called before initializing Bma280 sensor The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
References BCDS_UNUSED, RETCODE_FAILURE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Bma280Utils_ConfigInterrupt_S::interruptChannel, BMA280UTILS_INTERRUPT_CHANNEL2, RETCODE_INVALID_PARAM, Bma280Utils_ConfigInterrupt_S::interruptType, BMA280UTILS_SLOPE_INTERRUPT, configureSlopeInterrupt, Bma280Utils_ConfigInterrupt_S::configInterrupt, BMA280UTILS_NEW_DATA_INTERRUPT, configureNewDataInterrupt.
Referenced by Accelerometer_configInterrupt.
static void Bma280Utils_DelayMS(BMA2x2_MDELAY_DATA_TYPE delayMS)
Function to provide a delay.
delayMS Delay in milliseconds
References BSP_Board_Delay.
Referenced by Bma280Utils_initialize.
Retcode_T Bma280Utils_disableInterrupt(Bma280Utils_InfoPtr_T bma280Info, Bma280Utils_IntrType_T interruptType, Bma280Utils_IntrChannel_T interruptChannel)
Function to Disable the Interrupt.
bma280Info :structure holding the Bma280 specific configurations interruptType :type of interrupt that needs to be disabled interruptChannel :interrupt channel in which interrupt needs to be disabled RETCODE_OK BMA280 disable interrupt success RETCODE_LIB_NULL_POINTER when any of the input parameter for BST library API is NULL. RETCODE_BST_BMA280_ERROR when error is returned from BST library API. RETCODE_INVALID_PARAM when the interrupt configuration parameter is invalid. RETCODE_UNINITIALIZED when this api is called before initializing Bma280 sensor. The return value consist of (First MSB Byte represents Package ID,Next Byte represents Severity and Last 2LSB Bytes represents error code).
References BCDS_UNUSED, BMA2x2_RETURN_FUNCTION_TYPE, E_OUT_OF_RANGE, RETCODE_FAILURE, BMA280UTILS_INTERRUPT_CHANNEL_INVALID, BMA280UTILS_INVALID_INTERRUPT, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, BMA280UTILS_SLOPE_INTERRUPT, bma2x2_set_intr_slope, DISABLE_INTERRUPT, libErrorMapping.
Referenced by Accelerometer_disableInterrupt.
Retcode_T Bma280Utils_initialize(Bma280Utils_InfoPtr_T bma280Info)
Function to initialize Bma280. This needs to be called before calling any other API.
bma280Info :structure holding the bma280 specific configurations RETCODE_OK BMA280 is initialized successfully. RETCODE_NULL_POINTER when any of the input parameter(bma280Info->ISRCallback or bma280Info) is NULL. RETCODE_LIB_NULL_POINTER when any of the input parameter for BST library API is NULL. RETCODE_BST_BMA280_ERROR when error is returned from BST library API. RETCODE_DOPPLE_INITIALIZATION When initialization is already done. In case of other failures refer BSP_SensorNode_Enable or #I2CSensorTransceiver_Init API's. 1) The return value consist of (First MSB Byte represents Package ID,Next Byte represents Severity and Last 2LSB Bytes represents error code). 2) The support of multiple instances is not possible due to the limitation in the BST library. 3) Calling Bma280 initialization API present in sensorUtils (Bma280Utils_initialize) and BST library (bma2x2_init) concurrently will lead to unexpected behaviour.
References BMA2x2_RETURN_FUNCTION_TYPE, E_OUT_OF_RANGE, RETCODE_FAILURE, NULL, Bma280Utils_Info_S::ISRCallback, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, initializationStatus, RETCODE_SEVERITY_WARNING, RETCODE_DOPPLE_INITIALIZATION, SensorNodeMapping_Init, RETCODE_OK, BSP_SensorNode_Enable, Bma280Utils_Info_S::BspSensorId, RETCODE_SEVERITY_INFO, Retcode_GetSeverity, bma280Initialization, SensorNodeMapping_Read, SensorNodeMapping_Write, bma2x2_t::delay_msec, Bma280Utils_DelayMS, bma2x2_t::dev_addr, Bma280Utils_Info_S::dev_addr, bma2x2_init, SUCCESS, bma2x2_set_bw, BMA2x2_BW_500HZ, libErrorMapping.
Referenced by Accelerometer_init.
Retcode_T Bma280Utils_remapAxis(Bma280Utils_InfoPtr_T bma280Info, AxisRemap_Data_T *accelData)
Function to read remapped Bma280 data.
bma280Info :structure holding the Bma280 specific configurations. The information about remap configuration should be given in this struct accelData : while calling this API structure will hold the Bma280 data that needs to be the remapped. After calling this API the structure will hold remapped data RETCODE_OK BMA280 axis remap success RETCODE_NULL_POINTER when any of the input parameter is NULL. RETCODE_UNINITIALIZED when this api is called before initializing Bma280 sensor. In case of other failures refer AxisRemap_remapSensorData API. The return value consist of (First MSB Byte represents Package ID,Next Byte represents Severity and Last 2LSB Bytes represents error code).
References RETCODE_FAILURE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, AxisRemap_Data_S::x, AxisRemap_Data_S::y, AxisRemap_Data_S::z, AxisRemap_remapSensorData, Bma280Utils_Info_S::remap.
Referenced by Accelerometer_readXyzLsbValue, Accelerometer_readXyzGValue.
Retcode_T Bma280Utils_uninitialize(Bma280Utils_InfoPtr_T bma280Info)
Function to uninitialize Accel.After calling this API sensor is no more usable without initializing it again by calling Bma280Utils_initialize() API.
bma280Info :structure holding the bma280 specific configurations RETCODE_OK BMA280 un-initialization success RETCODE_NULL_POINTER when bma280Info is NULL. RETCODE_UNINITIALIZED when this api is called before initializing Bma280 sensor. In case of other failures refer BSP_SensorNode_Disable or BSP_SensorNode_IsAllNodesDisabled or #I2CSensorTransceiver_Deinit API. The return value consist of (First MSB Byte represents Package ID,Next Byte represents Severity and Last 2LSB Bytes represents error code).
References RETCODE_FAILURE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, BSP_SensorNode_Disable, Bma280Utils_Info_S::BspSensorId, RETCODE_OK, SensorNodeMapping_DeInit.
Referenced by Accelerometer_deInit.
static Retcode_T configureNewDataInterrupt(Bma280Utils_IntrChannel_T interruptChannel)
Function responsible to configure interrupt for new sensor data.
interruptChannel - Channel to which interrupt needs to be configured RETCODE_OK BMA280 sensor configure slope interrupt success. RETCODE_FAILURE BMA280 sensor configure slope interrupt failed. RETCODE_INVALID_PARAM BMA280 sensor configure slope interrupt failed because of invalid input parameter.
References RETCODE_FAILURE, BMA2x2_RETURN_FUNCTION_TYPE, E_OUT_OF_RANGE, bma2x2_set_new_data, ENABLE_INTERRUPT, SUCCESS, bma2x2_set_intr_enable, BMA2x2_DATA_ENABLE, INTR_ENABLE, libErrorMapping.
Referenced by Bma280Utils_configInterrupt.
static Retcode_T configureSlopeInterrupt(Bma280Utils_SlopeIntrConfigPtr_T slopeIntrConfig, Bma280Utils_IntrChannel_T interruptChannel)
Function responsible to configure interrupt conditions in the support layer.
slopeIntrConfig structure representing to slope interrupt configuration interruptChannel Channel to which interrupt needs to be configured RETCODE_OK BMA280 sensor configure slope interrupt success. RETCODE_FAILURE BMA280 sensor configure slope interrupt failed. RETCODE_INVALID_PARAM BMA280 sensor configure slope interrupt failed because of invalid input parameter.
References RETCODE_FAILURE, BMA2x2_RETURN_FUNCTION_TYPE, E_OUT_OF_RANGE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, Bma280Utils_SlopeIntrConfig_S::slopeEnableX, ENABLE_INTERRUPT, Bma280Utils_SlopeIntrConfig_S::slopeEnableY, Bma280Utils_SlopeIntrConfig_S::slopeEnableZ, Bma280Utils_SlopeIntrConfig_S::slopeDuration, BMA280_MAX_ALLOWED_SLOPE_DURATION, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM, bma2x2_set_intr_slope, DISABLE_INTERRUPT, SUCCESS, bma2x2_set_intr_enable, BMA2x2_SLOPE_X_INTR, BMA2x2_SLOPE_Y_INTR, BMA2x2_SLOPE_Z_INTR, bma2x2_set_durn, BMA2x2_SLOPE_DURN, bma2x2_set_thres, BMA2x2_SLOPE_THRES, Bma280Utils_SlopeIntrConfig_S::slopeThreshold, BSP_Board_Delay, CONFIGURATION_DELAY, libErrorMapping.
Referenced by Bma280Utils_configInterrupt.
static Retcode_T libErrorMapping(BMA2x2_RETURN_FUNCTION_TYPE bmaLibReturn)
This function maps error codes returned from BMA280 library to retcode values.
bmaLibReturn - Return value from BMA2X2 library RETCODE_OK BMA2X2 sensor API call success RETCODE_BST_BMA280_ERROR BMA2X2 sensor API call failed RETCODE_LIB_NULL_POINTER BMA2X2 sensor API call failed because of NULL input parameter
References RETCODE_FAILURE, SUCCESS, RETCODE_OK, E_BMA2x2_NULL_PTR, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_LIB_NULL_POINTER, RETCODE_BST_BMA280_ERROR.
Referenced by configureNewDataInterrupt, configureSlopeInterrupt, Bma280Utils_initialize, Bma280Utils_disableInterrupt.