Bme280Utils.c
BCDS_MODULE_ID
DELAY_100MS
macro used to represent 100ms delay variable to check initialization status
Referenced by Bme280Utils_initialize.
struct bme280_t bme280Initialization
Referenced by Bme280Utils_initialize.
bool initializationStatus
BME280 initialization structure
Referenced by Bme280Utils_initialize, Bme280Utils_uninitialize.
static void Bme280Utils_DelayMS(BME280_MDELAY_DATA_TYPE delayMS)
Function to provide a delay.
delayMS Delay in milliseconds
References BSP_Board_Delay.
Referenced by Bme280Utils_initialize.
Retcode_T Bme280Utils_initialize(Bme280Utils_InfoPtr_T bme280Info)
Function to initialize Environmental.This needs to be called before calling any other API.
bme280Info :structure holding the bme280 specific configurations RETCODE_OK BME280 initialized successfully RETCODE_NULL_POINTER when bma280Info is NULL. RETCODE_LIB_NULL_POINTER when any of the input parameter for BST library API is NULL. RETCODE_BST_BME280_ERROR when error is returned from BST library API. RETCODE_DOPPLE_INITIALIZATION When initialization is already done. In case of other failures refer BSP_SensorNode_Enable or #I2CSensorTransceiver_Init API's. 1) The return value consist of (First MSB Byte represents Package ID,Next Byte represents Severity and Last 2LSB Bytes represents error code). 2) The support of multiple instances is not possible due to the limitation in the BST library. 3) Calling Bme280 initialization API present in sensorUtils (Bme280Utils_initialize) and BST library (bme280_init) concurrently will lead to unexpected behaviour.
References RETCODE_FAILURE, BME280_RETURN_FUNCTION_TYPE, E_BME280_OUT_OF_RANGE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, initializationStatus, RETCODE_SEVERITY_WARNING, RETCODE_DOPPLE_INITIALIZATION, SensorNodeMapping_Init, RETCODE_OK, BSP_SensorNode_Enable, Bme280Utils_Info_S::BspSensorId, bme280Initialization, SensorNodeMapping_Read, SensorNodeMapping_Write, bme280_t::delay_msec, Bme280Utils_DelayMS, bme280_t::dev_addr, Bme280Utils_Info_S::dev_addr, bme280_init, SUCCESS, bme280_set_oversamp_temperature, BME280_OVERSAMP_1X, bme280_set_oversamp_pressure, BME280_OVERSAMP_4X, bme280_set_oversamp_humidity, BME280_OVERSAMP_2X, bme280_set_standby_durn, BME280_STANDBY_TIME_125_MS, bme280_set_power_mode, BME280_NORMAL_MODE, libErrorMapping, BSP_Board_Delay, DELAY_100MS.
Referenced by Environmental_init.
Retcode_T Bme280Utils_uninitialize(Bme280Utils_InfoPtr_T bme280Info)
Function to uninitialize Environmental.After calling this API sensor is no more usable without initializing it again by calling Bme280Utils_initialize() API.
bme280Info :structure holding the bme280 specific configurations RETCODE_OK BME280 un-initialization success RETCODE_NULL_POINTER when bme280Info is NULL. RETCODE_UNINITIALIZED when this api is called before initializing Bme280 sensor. In case of other failures refer BSP_SensorNode_Disable or BSP_SensorNode_IsAllNodesDisabled or #I2CSensorTransceiver_Deinit API. The return value consist of (First MSB Byte represents Package ID,Next Byte represents Severity and Last 2LSB Bytes represents error code).
References RETCODE_FAILURE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, BSP_SensorNode_Disable, Bme280Utils_Info_S::BspSensorId, RETCODE_OK, SensorNodeMapping_DeInit.
Referenced by Environmental_deInit.
static Retcode_T libErrorMapping(BME280_RETURN_FUNCTION_TYPE BME280_libReturn)
This function maps error codes returned from BME280 library to retcode values.
BME280_RETURN_FUNCTION_TYPE Return value from BME280 library RETCODE_OK BME280 sensor API call success RETCODE_FAILURE BME280 sensor API call failed RETCODE_INVALID_PARAM BME280 sensor API call failed because of invalid input parameter
References RETCODE_FAILURE, SUCCESS, RETCODE_OK, E_BME280_NULL_PTR, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_LIB_NULL_POINTER, RETCODE_BST_BME280_ERROR.
Referenced by Bme280Utils_initialize.