Bmg160Utils.c
BCDS_MODULE_ID
struct bmg160_t bmg160Initialization
Referenced by Bmg160Utils_initialize.
bool initializationStatus
< variable to check initialization status BMG160 initialization structure
Referenced by Bmg160Utils_initialize, Bmg160Utils_uninitialize, Bmg160Utils_remapAxis.
static void Bmg160_DelayMS(BMG160_MDELAY_DATA_TYPE delayMS)
Function to provide a delay.
delayMS Delay in milliseconds
References BSP_Board_Delay.
Referenced by Bmg160Utils_initialize.
Retcode_T Bmg160Utils_initialize(Bmg160Utils_InfoPtr_T bmg160Info)
Function to initialize bmg160.This needs to be called before calling any other API.
bmg160Info :structure holding the bmg160 specific configurations callback :callback that will be called in deferred context when an registered interrupt occurs RETCODE_OK BMG160 initialized successfully RETCODE_NULL_POINTER when any of the input paramete(bmg160Info or bmg160Info->ISRCallback) is NULL. RETCODE_LIB_NULL_POINTER when any of the input parameter for BST library API is NULL. RETCODE_BST_BMG160_ERROR when error is returned from BST library API. RETCODE_DOPPLE_INITIALIZATION When initialization is already done. In case of other failures refer BSP_SensorNode_Enable or #I2CSensorTransceiver_Init API's. 1) The return value consist of (First MSB Byte represents Package ID,Next Byte represents Severity and Last 2LSB Bytes represents error code). 2) The support of multiple instances is not possible due to the limitation in the BST library. 3) Calling Bmi160 initialization API present in sensorUtils (Bmg160Utils_initialize) and BST library (bmg160_init) concurrently will lead to unexpected behaviour.
References BMG160_RETURN_FUNCTION_TYPE, E_BMG160_NULL_PTR, RETCODE_FAILURE, NULL, Bmg160Utils_Info_S::ISRCallback, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, initializationStatus, RETCODE_SEVERITY_WARNING, RETCODE_DOPPLE_INITIALIZATION, SensorNodeMapping_Init, RETCODE_OK, BSP_SensorNode_Enable, Bmg160Utils_Info_S::BspSensorId, bmg160Initialization, SensorNodeMapping_Read, SensorNodeMapping_Write, bmg160_t::delay_msec, Bmg160_DelayMS, bmg160_t::dev_addr, Bmg160Utils_Info_S::dev_addr, bmg160_init, libErrorMapping.
Referenced by Gyroscope_init.
Retcode_T Bmg160Utils_remapAxis(Bmg160Utils_InfoPtr_T bmg160Info, AxisRemap_Data_T *bmgData)
Function to read remapped bmg160 data.
bmg160Info :structure holding the bmg160 specific configurations bmgData :structure to hold the remapped bmg160 data RETCODE_OK BMG160 initialized successfully RETCODE_NULL_POINTER when any of the input parameter is NULL. RETCODE_UNINITIALIZED when this api is called before initializing Bma280 sensor. In case of other failures refer AxisRemap_remapSensorData API. The return value consist of (First MSB Byte represents Package ID,Next Byte represents Severity and Last 2LSB Bytes represents error code).
References RETCODE_FAILURE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, AxisRemap_Data_S::x, AxisRemap_Data_S::y, AxisRemap_Data_S::z, AxisRemap_remapSensorData, Bmg160Utils_Info_S::remap, RETCODE_OK.
Referenced by Gyroscope_readXyzValue, Gyroscope_readXyzDegreeValue.
Retcode_T Bmg160Utils_uninitialize(Bmg160Utils_InfoPtr_T bmg160Info)
Function to uninitialize bmg160.After calling this API sensor is no more usable without initializing it again by calling initialize API.
bmg160Info :structure holding the bmg160 specific configurations RETCODE_OK BMG160 initialized successfully RETCODE_NULL_POINTER when bmg160Info is NULL. RETCODE_UNINITIALIZED when this api is called before initializing Bma280 sensor. In case of other failures refer BSP_SensorNode_Disable or BSP_SensorNode_IsAllNodesDisabled or #I2CSensorTransceiver_Deinit API. The return value consist of (First MSB Byte represents Package ID,Next Byte represents Severity and Last 2LSB Bytes represents error code).
References RETCODE_FAILURE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, BSP_SensorNode_Disable, Bmg160Utils_Info_S::BspSensorId, RETCODE_OK, SensorNodeMapping_DeInit.
Referenced by Gyroscope_deInit.
static Retcode_T libErrorMapping(BMG160_RETURN_FUNCTION_TYPE bmgLibReturn)
This function maps error codes returned from BMG160 library to retcode values.
BMG160_RETURN_FUNCTION_TYPE Return value from BMA2X2 library RETCODE_OK BMG160 sensor API call success RETCODE_FAILURE BMG160 sensor API call failed RETCODE_INVALID_PARAM BMG160 sensor API call failed because of invalid input parameter
References RETCODE_FAILURE, C_BMG160_SUCCESS, RETCODE_OK, E_BMG160_NULL_PTR, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_LIB_NULL_POINTER, RETCODE_BST_BMG160_ERROR.
Referenced by Bmg160Utils_initialize.