Bmi160Utils.c
ACCEL_DELAY
This macro indicates the delay required for BMI160_ACCEL while switching from Suspend/low power mode to normal mode
BCDS_MODULE_ID
ENABLE_INTERRUPT
macro used to enable the interrupt variable to check initialization status
GYRO_DELAY
This macro indicates the delay required for BMI160_GYRO while switching from Suspend mode to normal mode
struct bmi160_t bmi160Initialization
bool initializationStatus
BMI160 initialization structure
Referenced by Bmi160Utils_remapAxis.
static void Bmi160_DelayMS(BMI160_MDELAY_DATA_TYPE delayMS)
Function to provide a delay.
delayMS Delay in milliseconds
Retcode_T Bmi160Utils_initialize(Bmi160Utils_InfoPtr_T bmi160Info)
Function to initialize bmi160.This needs to be called before calling any other API.
bmi160Info :structure holding the bmi160 specific configurations callback :callback that will be called in deferred context when an registered interrupt occurs RETCODE_OK BMI160 initialized successfully RETCODE_NULL_POINTER when any of the input parameter(bmi160Info or bmi160Info->ISRCallback) is NULL. RETCODE_LIB_NULL_POINTER when any of the input parameter for BST library API is NULL. RETCODE_BST_BMI160_ERROR when error is returned from BST library API. RETCODE_DOPPLE_INITIALIZATION When initialization is already done. In case of other failures refer BSP_SensorNode_Enable or #I2CSensorTransceiver_Init API's. 1) The return value consist of (First MSB Byte represents Package ID,Next Byte represents Severity and Last 2LSB Bytes represents error code). 2) The support of multiple instances is not possible due to the limitation in the BST library. 3) Calling Bmi160 initialization API present in sensorUtils (Bmi160Utils_initialize) and BST library (bmi160_init) concurrently will lead to unexpected behaviour.
References RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER.
Referenced by Accelerometer_init, Gyroscope_init.
Retcode_T Bmi160Utils_remapAxis(Bmi160Utils_InfoPtr_T bmi160Info, AxisRemap_Data_T *bmiData)
Function to read remapped bmi160 data .
bmi160Info :structure holding the bmi160 specific configurations bmiData :structure to hold the remapped bmi160 data RETCODE_OK BMI160 initialized successfully RETCODE_NULL_POINTER when any of the input parameter is NULL. RETCODE_UNINITIALIZED when this api is called before initializing Bma280 sensor. In case of other failures refer AxisRemap_remapSensorData API. The return value consist of (First MSB Byte represents Package ID,Next Byte represents Severity and Last 2LSB Bytes represents error code).
References RETCODE_FAILURE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, AxisRemap_Data_S::x, AxisRemap_Data_S::y, AxisRemap_Data_S::z, AxisRemap_remapSensorData, Bmi160Utils_Info_S::remap.
Referenced by Accelerometer_readXyzLsbValue, Accelerometer_readXyzGValue, Gyroscope_readXyzValue, Gyroscope_readXyzDegreeValue.
Retcode_T Bmi160Utils_uninitialize(Bmi160Utils_InfoPtr_T bmi160Info)
Function to uninitialize bmi160.After calling this API sensor is no more usable without initializing it again by calling initialize API.
bmi160Info :structure holding the bmi160 specific configurations RETCODE_OK BMI160 initialized successfully RETCODE_NULL_POINTER when bmi160Info is NULL. RETCODE_UNINITIALIZED when this api is called before initializing Bma280 sensor. In case of other failures refer BSP_SensorNode_Disable or BSP_SensorNode_IsAllNodesDisabled or #I2CSensorTransceiver_Deinit API. The return value consist of (First MSB Byte represents Package ID,Next Byte represents Severity and Last 2LSB Bytes represents error code).
References RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER.
Referenced by Accelerometer_deInit, Gyroscope_deInit.
static Retcode_T libErrorMapping(BMI160_RETURN_FUNCTION_TYPE bmiLibReturn)
This function maps error codes returned from BMI160 library to retcode values.
BMI160_RETURN_FUNCTION_TYPE Return value from BMA2X2 library RETCODE_OK BMI160 sensor API call success RETCODE_FAILURE BMI160 sensor API call failed RETCODE_INVALID_PARAM BMI160 sensor API call failed because of invalid input parameter
References RETCODE_OK.