Bmm150Utils.c
BCDS_MODULE_ID
BMM050_SUCCESS
macro used to represent success of library variable to check initialization status
Referenced by libErrorMapping, Bmm150Utils_initialize.
struct bmm050_t bmm150Initialization
Referenced by Bmm150Utils_initialize.
bool initializationStatus
BMM150 initialization structure
Referenced by Bmm150Utils_initialize, Bmm150Utils_remapAxis, Bmm150Utils_uninitialize.
static void Bmm150_DelayMS(BMM050_MDELAY_DATA_TYPE delayMS)
Function to provide a delay.
delayMS Delay in milliseconds
References BSP_Board_Delay.
Referenced by Bmm150Utils_initialize.
Retcode_T Bmm150Utils_initialize(Bmm150Utils_InfoPtr_T bmm150Info)
Function to initialize bmm150.This needs to be called before calling any other API.
bmm150Info :structure holding the bmm150 specific configurations RETCODE_OK BMM150 initialized successfully RETCODE_NULL_POINTER when any of the input parameter(bmm150Info or bmm150Info->ISRCallback) is NULL. RETCODE_LIB_NULL_POINTER when any of the input parameter for BST library API is NULL. RETCODE_BST_BMM150_ERROR when error is returned from BST library API. RETCODE_DOPPLE_INITIALIZATION When initialization is already done. In case of other failures refer BSP_SensorNode_Enable or #I2CSensorTransceiver_Init API's. 1) The return value consist of (First MSB Byte represents Package ID,Next Byte represents Severity and Last 2LSB Bytes represents error code). 2) The support of multiple instances is not possible due to the limitation in the BST library. 3) Calling Bmm150 initialization API present in sensorUtils (Bmm150Utils_initialize) and BST library (bmm050_init) concurrently will lead to unexpected behaviour.
References BMM050_RETURN_FUNCTION_TYPE, BMM050_SUCCESS, RETCODE_FAILURE, NULL, Bmm150Utils_Info_S::ISRCallback, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, initializationStatus, RETCODE_SEVERITY_WARNING, RETCODE_DOPPLE_INITIALIZATION, SensorNodeMapping_Init, RETCODE_OK, BSP_SensorNode_Enable, Bmm150Utils_Info_S::BspSensorId, RETCODE_SEVERITY_INFO, Retcode_GetSeverity, bmm150Initialization, SensorNodeMapping_Read, SensorNodeMapping_Write, bmm050_t::delay_msec, Bmm150_DelayMS, bmm050_t::dev_addr, Bmm150Utils_Info_S::dev_addr, bmm050_init, bmm050_set_functional_state, BMM050_NORMAL_MODE, libErrorMapping.
Referenced by Magnetometer_init.
Retcode_T Bmm150Utils_remapAxis(Bmm150Utils_InfoPtr_T bmm150Info, AxisRemap_Data_T *bmiData)
Function to read remapped bmm150 data .
bmm150Info :structure holding the bmm150 specific configurations bmiData :structure to hold the remapped magnetometer data RETCODE_OK BMM150 axis remap success RETCODE_NULL_POINTER when any of the input parameter is NULL. RETCODE_UNINITIALIZED when this api is called before initializing Bma280 sensor. In case of other failures refer AxisRemap_remapSensorData API. The return value consist of (First MSB Byte represents Package ID,Next Byte represents Severity and Last 2LSB Bytes represents error code).
References RETCODE_FAILURE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, AxisRemap_Data_S::x, AxisRemap_Data_S::y, AxisRemap_Data_S::z, AxisRemap_remapSensorData, Bmm150Utils_Info_S::remap.
Referenced by Magnetometer_readXyzLsbData, Magnetometer_readXyzTeslaData.
Retcode_T Bmm150Utils_uninitialize(Bmm150Utils_InfoPtr_T bmm150Info)
Function to uninitialize bmm150.After calling this API sensor is no more usable without initializing it again by calling initialize API.
bmm150Info :structure holding the bmm150 specific configurations RETCODE_OK BMM150 un-initialization success RETCODE_NULL_POINTER when bmm150Info is NULL. RETCODE_UNINITIALIZED when this api is called before initializing Bma280 sensor. In case of other failures refer BSP_SensorNode_Disable or BSP_SensorNode_IsAllNodesDisabled or #I2CSensorTransceiver_Deinit API. The return value consist of (First MSB Byte represents Package ID,Next Byte represents Severity and Last 2LSB Bytes represents error code).
References RETCODE_FAILURE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, BSP_SensorNode_Disable, Bmm150Utils_Info_S::BspSensorId, RETCODE_OK, SensorNodeMapping_DeInit.
Referenced by Magnetometer_deInit.
static Retcode_T libErrorMapping(BMM050_RETURN_FUNCTION_TYPE bmmLibReturn)
This function maps error codes returned from BMM150 library to retcode values.
BMM050_RETURN_FUNCTION_TYPE Return value from BMA2X2 library RETCODE_OK BMM150 sensor API call success RETCODE_FAILURE BMM150 sensor API call failed RETCODE_INVALID_PARAM BMM150 sensor API call failed because of invalid input parameter
References RETCODE_FAILURE, BMM050_SUCCESS, RETCODE_OK, E_BMM050_NULL_PTR, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_LIB_NULL_POINTER, RETCODE_BST_BMM150_ERROR.
Referenced by Bmm150Utils_initialize.