EnvironmentalUtils.c
BCDS_MODULE_ID
TETENS_ALPHA_NEGATIVE
Referenced by ComputeCompensationFactorTetens.
TETENS_ALPHA_POSITIVE
Referenced by ComputeCompensationFactorTetens.
TETENS_BETA_NEGATIVE
Referenced by ComputeCompensationFactorTetens.
TETENS_BETA_POSITIVE
Referenced by ComputeCompensationFactorTetens.
XDK_DEFAULT_TEMPERATURE_OFFSET
Default Temperature offset macroUse this macro to set a default or static temperature offset.
float tOffset
Referenced by SetAmbientTemperatureOffset, GetAmbientTemperatureOffset, ComputeAmbientTemperature.
float ComputeAmbientHumidity(float rH_sensor, float T_sensor, float T_ambient)
Compute Ambient Humidity.
Computes the ambient relative humidity using the Tetens formula for estimation of ambient vapor pressureCompensation formula:Rh_ambient = Ew(T_sensor) / Ew(T_ambient) * Rh_sensorThe vapor pressure of water approximation used is the Tetens formula with a validity range between -10 degree C and 75 degree C Sensor values are measured inside the device housing This function has a division by zero in the case where T_sensor or T_ambient is equal to -TETENS_BETA_NEGATIVE (-265.5 degree C) rH_sensor Relative humidity measured by the sensor T_sensor Temperature in degree C measured by the sensor T_ambient Temperature in degree C measured or estimated outside rH_ambient Computed ambient relative humidity
References ComputeCompensationFactorTetens.
Referenced by Environmental_compensateData.
float ComputeAmbientTemperature(float T_sensor)
Compute Ambient Temperature.
Ambient Temperature is calculated by adding an offset to the measured sensor temperatureCompensation formula:T_offset = T_ambient - T_sensorT_ambient = T_sensor + T_offsetThis API provides a default value for the temperature offset value. T_sensor Temperature in \°C measured inside T_ambient Calculated ambient temperature
References tOffset.
Referenced by Environmental_compensateData.
static float ComputeCompensationFactorTetens(float T_sensor, float T_ambient)
Calculates the compensation factor using the Tetens formula.
Compensation factor: CompensationFactor = Ew(T_sensor) / Ew(T_ambient)Using Magnus Tetens formula:Ew(T_sensor) = 0.61078 * exp( A_sensor * T_sensor / (T_sensor + B_sensor)) Ew(T_ambient) = 0.61078 * exp( A_ambient * T_ambient / (T_ambient + B_ambient)) )A_sensor, B_sensor, A_ambient and B_ambient are dependent on the sign of the corresponding temperatureCompensationFactor = exp((A_sensor*T_sensor )/(B_sensor+T_sensor) (A_ambient*T_ambient)/(B_ambient+T_ambient)) This formula has a division by zero in the case where T_sensor or T_ambient is equal to -TETENS_BETA_NEGATIVE (-265.5 degree C) T_sensor Temperature in degree C measured at the sensor T_ambient Temperature in degree C measured or estimated outside the housing Compensation Factor
References TETENS_ALPHA_POSITIVE, TETENS_BETA_POSITIVE, TETENS_ALPHA_NEGATIVE, TETENS_BETA_NEGATIVE.
Referenced by ComputeAmbientHumidity.
float GetAmbientTemperatureOffset(void)
Returns the ambient temperature offset.
Ambient Temperature Offset
References tOffset.
Retcode_T SetAmbientTemperatureOffset(float T_offset)
Register the ambient temperature offset in degree C.
returnCode Return code indicating state and success of the operation RETCODE_OK operation was successful RETCODE_INVALID_PARAM Invalid Temperature offset
References RETCODE_OK, tOffset.
Referenced by Environmental_setTemperatureOffset.