Environmental.c
BCDS_MODULE_ID
const uint8_t filterCoeffLookUpTable[ENVIRONMENTAL_FILTER_COEFF_OUT_OF_RANGE][ENVIRONMENTAL_FILTER_COEFF_OUT_OF_RANGE]
Referenced by Environmental_setFilterCoefficient.
const uint8_t modeLookUpTable[ENVIRONMENTAL_POWERMODE_OUT_OF_RANGE][ENVIRONMENTAL_POWERMODE_OUT_OF_RANGE]
Referenced by Environmental_setPowerMode, Environmental_getPowerMode.
const uint8_t overSamplingLookUpTable[ENVIRONMENTAL_OVERSAMP_OUT_OF_RANGE][ENVIRONMENTAL_OVERSAMP_OUT_OF_RANGE]
Referenced by setOverSampling.
const uint8_t standbytimeLookUpTable[ENVIRONMENTAL_STANDBY_TIME_OUT_OF_RANGE][ENVIRONMENTAL_STANDBY_TIME_OUT_OF_RANGE]
Referenced by Environmental_setStandbyDuration, Environmental_getStandbyDuration.
static Retcode_T bme280LibErrorMapping(BME280_RETURN_FUNCTION_TYPE BME280_libReturn)
References RETCODE_FAILURE, SUCCESS, RETCODE_OK, E_BME280_NULL_PTR, RETCODE_INVALID_PARAM.
Referenced by setOverSampling, Environmental_setPowerMode, Environmental_getPowerMode, Environmental_readData, Environmental_readDataLSB, Environmental_readTemperatureLSB, Environmental_readPressureLSB, Environmental_readHumidityLSB, Environmental_setStandbyDuration, Environmental_getStandbyDuration, Environmental_setFilterCoefficient.
Retcode_T Environmental_compensateData(Environmental_HandlePtr_T handle, Environmental_DataPtr_T sensorData)
Compensates temperature and relative humidity values.
Compensates temperature and humidity values read using Environmental_readData() The result can be seen as the ambient values outside the sensorPlease set an appropriate temperature offset value using the Environmental_setTemperatureOffset() function before using this API handle Handle to the environmental object sensorData Parameter in which Temperature(mDegC),pressure(Pascal) and relative humidity (%rH) data from environmental sensor RETCODE_SUCCESS Set compensateData success. RETCODE_NULL_POINTER In case of NULL pointers arguments passed. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of trying to set invalid compensate data. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_OK, NULL, Environmental_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, INIT_NOT_DONE, Environmental_Handle_S::SensorInformation, Environmental_SensorInfo_S::initializationStatus, RETCODE_UNINITIALIZED, Environmental_SensorInfo_S::sensorID, ENVIRONMENTAL_BME280, Environmental_Data_S::temperature, RETCODE_INVALID_PARAM, Environmental_Data_S::humidity, ComputeAmbientTemperature, ComputeAmbientHumidity.
Referenced by LWM2MSensorDeviceEnvironment_Update, Environmental_readCompensatedData.
Retcode_T Environmental_deInit(Environmental_HandlePtr_T handle)
DeInitializes the environmental sensor referenced by the passed handle.
handle Handle to the environmental object RETCODE_SUCCESS Environmental De-initialization success. RETCODE_INVALID_PARAM In case of invalid sensor handle. In case of any other error refer Bme280Utils_uninitialize error codes. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, NULL, Environmental_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Environmental_Handle_S::SensorInformation, Environmental_SensorInfo_S::initializationStatus, RETCODE_OK, Environmental_SensorInfo_S::sensorID, ENVIRONMENTAL_BME280, Bme280Utils_uninitialize, Retcode_GetPackage, PACKAGE_ID_DEFAULT, RETCODE_SEVERITY_ERROR.
Referenced by LWM2MSensorDeviceEnvironment_Activate.
Retcode_T Environmental_getPowerMode(Environmental_HandlePtr_T handle, Environmental_PowerModesPtr_T mode)
Gets the power mode for the environmental sensor referenced by the passed handle.
handle Handle to the environmental object mode Last configured power mode of environmental sensor RETCODE_SUCCESS Get power mode success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of getting power mode values other than Environmental_PowerModes_E. In case of other failures refer bme280LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, BME280_RETURN_FUNCTION_TYPE, ENVIRONMENTAL_POWERMODE_OUT_OF_RANGE, GET_MAPPING_ERROR, NULL, Environmental_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Environmental_Handle_S::SensorInformation, Environmental_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Environmental_SensorInfo_S::sensorID, ENVIRONMENTAL_BME280, bme280_get_power_mode, bme280LibErrorMapping, RETCODE_OK, mappingEnumForGetFunctions, ENVIRONMENTAL_BME280_POWERMODE_SLEEP, ENVIRONMENTAL_BME280_POWERMODE_NORMAL, modeLookUpTable, RETCODE_NOT_SUPPORTED.
Referenced by setOverSampling.
Retcode_T Environmental_getStandbyDuration(Environmental_HandlePtr_T handle, Environmental_StandbyTimePtr_T duration)
reads the StandbyDuration for the environmental sensor
handle Handle to the environmental object duration Last configured Standby duration of environmental RETCODE_SUCCESS Environmental get standby duration success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of NULL pointer arguments. RETCODE_NOT_SUPPORTED in case of getting standby duration values other than Environmental_StandbyTime_E In case of other failures refer bme280LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E
References RETCODE_FAILURE, BME280_RETURN_FUNCTION_TYPE, ENVIRONMENTAL_STANDBY_TIME_OUT_OF_RANGE, GET_MAPPING_ERROR, NULL, Environmental_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Environmental_Handle_S::SensorInformation, Environmental_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Environmental_SensorInfo_S::sensorID, ENVIRONMENTAL_BME280, bme280_get_standby_durn, bme280LibErrorMapping, RETCODE_OK, mappingEnumForGetFunctions, ENVIRONMENTAL_BME280_STANDBY_TIME_1_MS, ENVIRONMENTAL_BME280_STANDBY_TIME_20_MS, standbytimeLookUpTable, RETCODE_NOT_SUPPORTED.
Retcode_T Environmental_init(Environmental_HandlePtr_T handle)
Initializes the environmental sensor referenced by the passed handle.
handle Handle to the environmental sensor object RETCODE_SUCCESS Environmental initialization success. RETCODE_INVALID_PARAM In case of invalid sensor handle. In case of any other error refer Bme280Utils_initialize error codes. This function needs to be called before calling any other accelerometer API. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, NULL, Environmental_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, Environmental_Handle_S::SensorInformation, Environmental_SensorInfo_S::initializationStatus, INIT_DONE, RETCODE_OK, Environmental_SensorInfo_S::sensorID, ENVIRONMENTAL_BME280, Bme280Utils_initialize, INIT_NOT_DONE, Retcode_GetPackage, PACKAGE_ID_DEFAULT, RETCODE_SEVERITY_ERROR.
Referenced by LWM2MSensorDeviceEnvironment_Activate.
Retcode_T Environmental_readCompensatedData(Environmental_HandlePtr_T handle, Environmental_DataPtr_T sensorData)
Reads and compensates temperature and relative humidity values.
Reads and compensates temperature and humidity values The result can be seen as the ambient values outside the sensorPlease set an appropriate temperature offset value using the Environmental_setTemperatureOffset() function before using this API handle Handle to the environmental object sensorData Parameter in which Temperature(mDegC),pressure(Pascal) and relative humidity (%rH) data from environmental sensor RETCODE_SUCCESS Read compensateData success. RETCODE_NULL_POINTER In case of NULL pointers arguments passed. In case of other error code refer Environmental_readData or Environmental_compensateData API. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, Environmental_readData, Environmental_compensateData.
Retcode_T Environmental_readData(Environmental_HandlePtr_T handle, Environmental_DataPtr_T sensorData)
Reads Temperature in milli degree Celsius,pressure in Pascal and humidity in(%rh) values from the environmental sensor.
handle Handle to the environmental object sensorData Parameter in which Temperature(mDegC),pressure(Pascal) and Humidity(%rh) data from environmental sensor RETCODE_SUCCESS Environmental ReadData success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. In case of other failures refer bme280LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, BME280_RETURN_FUNCTION_TYPE, NULL, Environmental_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Environmental_Handle_S::SensorInformation, Environmental_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Environmental_SensorInfo_S::sensorID, ENVIRONMENTAL_BME280, bme280_read_pressure_temperature_humidity, Environmental_Data_S::pressure, Environmental_Data_S::temperature, Environmental_Data_S::humidity, bme280LibErrorMapping, RETCODE_OK, ENVI_BME280_HUM_RH_CONV, ENVI_BME280_TEMP_MIILIDEG_CONV.
Referenced by LWM2MSensorDeviceEnvironment_Update, Environmental_readCompensatedData.
Retcode_T Environmental_readDataLSB(Environmental_HandlePtr_T handle, Environmental_LsbDataPtr_T sensorData)
Reads Temperature,pressure and humidity Raw values from the environmental sensor.
handle Handle to the environmental object sensorData Parameter in which Temperature,pressure and humidity LSB raw data from environmental sensor gets collected. RETCODE_SUCCESS Environmental ReadDataLSB success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. In case of other failures refer bme280LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, BME280_RETURN_FUNCTION_TYPE, NULL, Environmental_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Environmental_Handle_S::SensorInformation, Environmental_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Environmental_SensorInfo_S::sensorID, ENVIRONMENTAL_BME280, bme280_read_uncomp_pressure_temperature_humidity, Environmental_LsbData_S::pressure, Environmental_LsbData_S::temperature, Environmental_LsbData_S::humidity, bme280LibErrorMapping, RETCODE_OK.
Retcode_T Environmental_readHumidity(Environmental_HandlePtr_T handle, uint32_t *humidity)
Reads Humidity values in(%rh) from the environmental sensor.
handle Handle to the environmental object humidity Parameter in which Humidity(%rh) data from environmental sensor gets collected. RETCODE_SUCCESS Environmental read Humidity success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of NULL pointer arguments. In case of other failures refer bme280LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, Environmental_readHumidityLSB, RETCODE_OK, bme280_compensate_humidity_int32, ENVI_BME280_HUM_RH_CONV.
Retcode_T Environmental_readHumidityLSB(Environmental_HandlePtr_T handle, int32_t *humiditylsb)
Reads Humidity LSB(raw) values from the environmental sensor.
handle Handle to the environmental object humiditylsb Parameter in which Humidity LSB raw data from environmental sensor gets collected. RETCODE_SUCCESS Environmental read Humidity LSB success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. In case of other failures refer bme280LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, BME280_RETURN_FUNCTION_TYPE, NULL, Environmental_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Environmental_Handle_S::SensorInformation, Environmental_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Environmental_SensorInfo_S::sensorID, ENVIRONMENTAL_BME280, bme280_read_uncomp_humidity, bme280LibErrorMapping, RETCODE_OK.
Referenced by Environmental_readHumidity.
Retcode_T Environmental_readPressure(Environmental_HandlePtr_T handle, uint32_t *pressure)
Reads Pressure in Pascal values from the environmental sensor.
handle Handle to the environmental object pressure Parameter in which Pressure(Pascal) data from environmental sensor gets collected. RETCODE_SUCCESS Environmental read Pressure success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of NULL pointer arguments. In case of other failures refer bme280LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, Environmental_readPressureLSB, RETCODE_OK, bme280_compensate_pressure_int32.
Retcode_T Environmental_readPressureLSB(Environmental_HandlePtr_T handle, int32_t *pressurelsb)
Reads Pressure LSB(raw) values from the environmental sensor.
handle Handle to the environmental object pressurelsb Parameter in which pressure LSB raw data from environmental sensor gets collected. RETCODE_SUCCESS Environmental read Pressure LSB success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. In case of other failures refer bme280LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, BME280_RETURN_FUNCTION_TYPE, NULL, Environmental_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Environmental_Handle_S::SensorInformation, Environmental_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Environmental_SensorInfo_S::sensorID, ENVIRONMENTAL_BME280, bme280_read_uncomp_pressure, bme280LibErrorMapping, RETCODE_OK.
Referenced by Environmental_readPressure.
Retcode_T Environmental_readTemperature(Environmental_HandlePtr_T handle, int32_t *temperature)
Reads Temperature in milli degree Celsius values from the environmental sensor.
handle Handle to the environmental object temperature Parameter in which Temperature(mDegC) data from environmental sensor gets collected. RETCODE_SUCCESS Environmental read Temperature success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of NULL pointer arguments. In case of other failures refer bme280LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, Environmental_readTemperatureLSB, RETCODE_OK, bme280_compensate_temperature_int32, ENVI_BME280_TEMP_MIILIDEG_CONV.
Retcode_T Environmental_readTemperatureLSB(Environmental_HandlePtr_T handle, int32_t *temperaturelsb)
Reads Temperature LSB(raw) values from the environmental sensor.
handle Handle to the environmental object temperaturelsb Parameter in which Temperature LSB raw data from environmental sensor gets collected. RETCODE_SUCCESS Environmental read Temperature LSB success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. In case of other failures refer bme280LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, BME280_RETURN_FUNCTION_TYPE, NULL, Environmental_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Environmental_Handle_S::SensorInformation, Environmental_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Environmental_SensorInfo_S::sensorID, ENVIRONMENTAL_BME280, bme280_read_uncomp_temperature, bme280LibErrorMapping, RETCODE_OK.
Referenced by Environmental_readTemperature.
Retcode_T Environmental_setFilterCoefficient(Environmental_HandlePtr_T handle, Environmental_FilterCoefficient_T filter)
sets the Filter Coefficient for the environmental sensor
handle Handle to the environmental object filter set value for the Filter Coefficient RETCODE_SUCCESS Environmental set filter coefficient success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of NULL pointer arguments. RETCODE_NOT_SUPPORTED in case of setting filter values other than Environmental_FilterCoefficient_E In case of other failures refer bme280LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E
References RETCODE_FAILURE, BME280_RETURN_FUNCTION_TYPE, NULL, Environmental_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, ENVIRONMENTAL_FILTER_COEFF_OUT_OF_RANGE, RETCODE_SEVERITY_ERROR, INIT_NOT_DONE, Environmental_Handle_S::SensorInformation, Environmental_SensorInfo_S::initializationStatus, RETCODE_UNINITIALIZED, Environmental_SensorInfo_S::sensorID, ENVIRONMENTAL_BME280, ENVIRONMENTAL_BME280_FILTER_COEFF_16, RETCODE_NOT_SUPPORTED, bme280_set_filter, filterCoeffLookUpTable, bme280LibErrorMapping, RETCODE_OK.
Retcode_T Environmental_setOverSamplingHumidity(Environmental_HandlePtr_T handle, Environmental_OverSampling_T samplingRate)
sets the OverSampling rate of Humidity data for the environmental sensor referenced by the passed handle.
If this function is called with option ENVIRONMENTAL_BME280_OVERSAMP_SKIPPED then humidity measurement will be disabled and default value 0x8000 returned for all the subsequent read operation. handle Handle to the environmental object samplingRate set value for the Humidity OverSampling rate. RETCODE_SUCCESS Environmental set over sampling humidity success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of NULL pointer arguments. RETCODE_NOT_SUPPORTED in case of setting over sampling values other than Environmental_OverSampling_E Failure can also be because of Environmental_getPowerMode or Environmental_setPowerMode API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E In order to have this setting effective for subsequent measurements, User needs to provide minimum 100 milliseconds delay after calling this API and then the sensor values can be read Example Usage: #include"BCDS_Environmental.h" voiddelayAPI(uint32_tmilliSecondsDelay) { //Implementthedelaylogichere } if(RETCODE_OK==Environmental_setOverSamplingHumidity(xdkEnvironmental_BME280_Handle,ENVIRONMENTAL_BME280_OVERSAMP_8X)) { printf("Environmental_setOverSamplingHumiditySuccess\n\r"); delayAPI(100); }
References setOverSampling, HUMIDITY.
Retcode_T Environmental_setOverSamplingPressure(Environmental_HandlePtr_T handle, Environmental_OverSampling_T samplingRate)
sets the OverSampling rate of pressure data for the environmental sensor referenced by the passed handle.
If this function is called with option ENVIRONMENTAL_BME280_OVERSAMP_SKIPPED then pressure measurement will be disabled and default value 0x80000 returned for all the subsequent read operation. handle Handle to the environmental object samplingRate set value for the Pressure OverSampling rate. RETCODE_SUCCESS Environmental set over sampling pressure success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of NULL pointer arguments. RETCODE_NOT_SUPPORTED in case of setting over sampling values other than Environmental_OverSampling_E Failure can also be because of Environmental_getPowerMode or Environmental_setPowerMode API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E In order to have this setting effective for subsequent measurements, User needs to provide minimum 100 milliseconds delay after calling this API and then the sensor values can be read Example Usage: #include"BCDS_Environmental.h" voiddelayAPI(uint32_tmilliSecondsDelay) { //Implementthedelaylogichere } if(RETCODE_OK==Environmental_setOverSamplingPressure(xdkEnvironmental_BME280_Handle,ENVIRONMENTAL_BME280_OVERSAMP_8X)) { printf("Environmental_setOverSamplingPressureSuccess\n\r"); delayAPI(100); }
References setOverSampling, PRESSURE.
Retcode_T Environmental_setOverSamplingTemperature(Environmental_HandlePtr_T handle, Environmental_OverSampling_T samplingRate)
sets the OverSampling rate of temperature data for the environmental sensor referenced by the passed handle.
If this function is called with option ENVIRONMENTAL_BME280_OVERSAMP_SKIPPED then temperature measurement will be disabled and default value 0x80000 returned for all the subsequent read operation. handle Handle to the environmental object samplingRate set value for the Temperature OverSampling rate. RETCODE_SUCCESS Environmental set over sampling temperature success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of NULL pointer arguments. RETCODE_NOT_SUPPORTED in case of setting over sampling values other than Environmental_OverSampling_E Failure can also be because of Environmental_getPowerMode or Environmental_setPowerMode API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E In order to have this setting effective for subsequent measurements, User needs to provide minimum 100 milliseconds delay after calling this API and then the sensor values can be read Example Usage: #include"BCDS_Environmental.h" voiddelayAPI(uint32_tmilliSecondsDelay) { //Implementthedelaylogichere } if(RETCODE_OK==Environmental_setOverSamplingTemperature(xdkEnvironmental_BME280_Handle,ENVIRONMENTAL_BME280_OVERSAMP_8X)) { printf("Environmental_setOverSamplingTemperatureSuccess\n\r"); delayAPI(100); }
References setOverSampling, TEMPERATURE.
Retcode_T Environmental_setPowerMode(Environmental_HandlePtr_T handle, Environmental_PowerModes_T mode)
Sets the power mode for the environmental sensor referenced by the passed handle.
handle Handle to the environmental object mode The desired power mode that needs to be set RETCODE_SUCCESS Set power mode success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of setting power mode values other than Environmental_PowerModes_E. In case of other failures refer bme280LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, BME280_RETURN_FUNCTION_TYPE, NULL, Environmental_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, ENVIRONMENTAL_POWERMODE_OUT_OF_RANGE, RETCODE_SEVERITY_ERROR, INIT_NOT_DONE, Environmental_Handle_S::SensorInformation, Environmental_SensorInfo_S::initializationStatus, RETCODE_UNINITIALIZED, Environmental_SensorInfo_S::sensorID, ENVIRONMENTAL_BME280, ENVIRONMENTAL_BME280_POWERMODE_NORMAL, RETCODE_NOT_SUPPORTED, bme280_set_power_mode, modeLookUpTable, bme280LibErrorMapping, RETCODE_OK.
Referenced by setOverSampling.
Retcode_T Environmental_setStandbyDuration(Environmental_HandlePtr_T handle, Environmental_StandbyTime_T duration)
Sets the StandbyDuration for the environmental sensor.
handle Handle to the environmental object duration set value for the desired Standby duration RETCODE_SUCCESS Environmental set standby duration success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of NULL pointer arguments. RETCODE_NOT_SUPPORTED in case of setting standby duration values other than Environmental_StandbyTime_E In case of other failures refer bme280LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, BME280_RETURN_FUNCTION_TYPE, NULL, Environmental_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, ENVIRONMENTAL_STANDBY_TIME_OUT_OF_RANGE, RETCODE_SEVERITY_ERROR, INIT_NOT_DONE, Environmental_Handle_S::SensorInformation, Environmental_SensorInfo_S::initializationStatus, RETCODE_UNINITIALIZED, Environmental_SensorInfo_S::sensorID, ENVIRONMENTAL_BME280, ENVIRONMENTAL_BME280_STANDBY_TIME_20_MS, RETCODE_NOT_SUPPORTED, bme280_set_standby_durn, standbytimeLookUpTable, bme280LibErrorMapping, RETCODE_OK.
Retcode_T Environmental_setTemperatureOffset(Environmental_HandlePtr_T handle, int32_t offset)
Register the ambient temperature offset in millidegree Kelvin.
Registers a temperature offset to be used by the temperature compensation API.T_ambient = T_sensor + T_offset handle Handle to the environmental object offset Parameter in which Temperature offset (mDegC) is given to be registered in the temperature compensation API RETCODE_SUCCESS Set temperature offset success. RETCODE_NULL_POINTER In case of NULL pointers arguments passed. RETCODE_UNINITIALIZED if called without initializing the sensor. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_OK, NULL, Environmental_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, INIT_NOT_DONE, Environmental_Handle_S::SensorInformation, Environmental_SensorInfo_S::initializationStatus, RETCODE_UNINITIALIZED, Environmental_SensorInfo_S::sensorID, ENVIRONMENTAL_BME280, SetAmbientTemperatureOffset, RETCODE_INVALID_PARAM.
Referenced by LWM2MSensorDeviceEnvironment_Activate.
static int8_t mappingEnumForGetFunctions(uint8_t start, uint8_t end, uint8_t getValueToBeTransalated, const uint8_t *lookUpTablePtr)
References GET_MAPPING_ERROR.
Referenced by Environmental_getPowerMode, Environmental_getStandbyDuration.
static Retcode_T setOverSampling(int8_t ParamType, Environmental_HandlePtr_T handle, Environmental_OverSampling_T samplingRate)
References RETCODE_FAILURE, ENVIRONMENTAL_BME280_POWERMODE_SLEEP, BME280_RETURN_FUNCTION_TYPE, NULL, Environmental_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, ENVIRONMENTAL_OVERSAMP_OUT_OF_RANGE, RETCODE_SEVERITY_ERROR, INIT_NOT_DONE, Environmental_Handle_S::SensorInformation, Environmental_SensorInfo_S::initializationStatus, RETCODE_UNINITIALIZED, Environmental_SensorInfo_S::sensorID, ENVIRONMENTAL_BME280, ENVIRONMENTAL_BME280_OVERSAMP_16X, RETCODE_NOT_SUPPORTED, TEMPERATURE, Environmental_getPowerMode, RETCODE_OK, Environmental_setPowerMode, bme280_set_oversamp_temperature, overSamplingLookUpTable, bme280LibErrorMapping, PRESSURE, bme280_set_oversamp_pressure, HUMIDITY, bme280_set_oversamp_humidity, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Referenced by Environmental_setOverSamplingTemperature, Environmental_setOverSamplingPressure, Environmental_setOverSamplingHumidity.