EnvironmentalUtils.h
Retcode_T SetAmbientTemperatureOffset(float T_offset)
Register the ambient temperature offset in degree C.
returnCode Return code indicating state and success of the operation RETCODE_OK operation was successful RETCODE_INVALID_PARAM Invalid Temperature offset
References RETCODE_OK, tOffset.
Referenced by Environmental_setTemperatureOffset.
float GetAmbientTemperatureOffset(void)
Returns the ambient temperature offset.
Ambient Temperature Offset
References tOffset.
float ComputeAmbientTemperature(float T_sensor)
Compute Ambient Temperature.
Ambient Temperature is calculated by adding an offset to the measured sensor temperatureCompensation formula:T_offset = T_ambient - T_sensorT_ambient = T_sensor + T_offsetThis API provides a default value for the temperature offset value. T_sensor Temperature in \°C measured inside T_ambient Calculated ambient temperature
References tOffset.
Referenced by Environmental_compensateData.
float ComputeAmbientHumidity(float rH_sensor, float T_sensor, float T_ambient)
Compute Ambient Humidity.
Computes the ambient relative humidity using the Tetens formula for estimation of ambient vapor pressureCompensation formula:Rh_ambient = Ew(T_sensor) / Ew(T_ambient) * Rh_sensorThe vapor pressure of water approximation used is the Tetens formula with a validity range between -10 degree C and 75 degree C Sensor values are measured inside the device housing This function has a division by zero in the case where T_sensor or T_ambient is equal to -TETENS_BETA_NEGATIVE (-265.5 degree C) rH_sensor Relative humidity measured by the sensor T_sensor Temperature in degree C measured by the sensor T_ambient Temperature in degree C measured or estimated outside rH_ambient Computed ambient relative humidity
References ComputeCompensationFactorTetens.
Referenced by Environmental_compensateData.