ExtensionUartExample.h
Retcode_T ExtensionUartExample_DeInitialize(void)
This API is used to deinit the UART interface. Once this called, from there-on user needs to call ExtensionUartExample_Initialize for using the UART communication again.
RETCODE_OK in success case error otherwise Refer interface header for description
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, UARTTransceiver_Deinitialize.
Retcode_T ExtensionUartExample_Initialize(CmdProcessor_T *handle)
This API is used to prepare the UART with the user configuration data. Once after this call the user can write over UART interface at any time. Read callback will happen for each byte and user can able to read received data using UartRead()
handle Command processor handle RETCODE_OK in success case error otherwise Please refer to the implementation XdkExtensionPortUart.c on how data receptions are handled asynchronously. Refer interface header for description
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, UART_BAURDRATE, UartCallBack, UART_TRANSCEIVER_UART_TYPE_UART, MAX_UART_RX_BUFFERSIZE, UARTTransceiver_Initialize, UartRxBuffInstance, UARTTransceiver_StartInAsyncMode, FrameEndCheckFunc, UartAppCallback.
Referenced by AppControllerSetup.
Retcode_T ExtensionUartExample_Read(uint8_t *readBuffer, uint8_t readlength, uint32_t *actualLength)
This API is used to read the data received over the UART interface.
readBuffer To collect the received data readlength Bytes requested for reading actualLength Actual Bytes read RETCODE_OK in success case error otherwise Please refer to the implementation XdkExtensionPortUart.c on how data receptions are handled asynchronously. Refer interface header for description
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, UARTTransceiver_ReadData, UART_SPI_DATA_TRANSFER_TIMEOUT_MILLISEC.
Referenced by ProcessUartRxData.
Retcode_T ExtensionUartExample_Write(uint8_t *writeBuffer, uint8_t writeLength)
This API is used to write data over the UART interface. Once the UartInit() was success, user can transmit data over UART interface.
writeBuffer User transmit data buffer writeLength No of Bytes to transmit RETCODE_OK in success case error otherwise Refer interface header for description
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, UARTTransceiver_WriteData, UART_SPI_DATA_TRANSFER_TIMEOUT_MILLISEC.
Referenced by SendUartResponseData.