ExtensionI2cExample.h
Retcode_T ExtensionI2cExample_DeInitialize(void)
This API is used to deinitialize the I2C interface. Once this called, from there-on user needs to call ExtensionI2cExample_Initialize for using the I2C communication again.
RETCODE_OK on success, or an error code otherwise. Refer interface header for description
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, I2CTranceiverInstance.
Retcode_T ExtensionI2cExample_Initialize(CmdProcessor_T *handle)
This API is used to prepare the I2C with the user configuration data.
handle Command processor handle This must be the first API to be called if any of the features in this module is to be used. RETCODE_OK on success, or an error code otherwise. Refer interface header for description
References BCDS_UNUSED, RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, I2cMcuCallback, I2CTranceiverInstance.
Referenced by AppControllerSetup.
Retcode_T ExtensionI2cExample_Read(uint8_t slaveAddr, uint8_t regAddr, uint8_t *readVal, uint8_t readLength)
This API is used to read the data received over the I2C extension port interface.
slaveAddr slave address of the I2C regAddr Address of the register to read readVal Buffer to hold the data received over I2C readLength No of bytes to be read over the I2C bus RETCODE_OK on success, or an error code otherwise. Refer interface header for description
References I2CTranceiverInstance.
Referenced by ExtensionI2cExample_ValidateChip.
Retcode_T ExtensionI2cExample_ValidateChip(void)
This API is used to demonstrate read and write on the extension port I2C interface.
RETCODE_OK on success, or an error code otherwise. Refer interface header for description
References RETCODE_OK, EXT_PORT_I2C_REG1_VAL, ExtensionI2cExample_Read, EXT_PORT_I2C_SLAVE_ADDR, EXT_PORT_I2C_REG2_ADDR, EXT_PORT_I2C_REG2_VAL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_UNEXPECTED_BEHAVIOR, ExtensionI2cExample_Write, EXT_PORT_I2C_REG1_ADDR.
Referenced by AppControllerFire.
Retcode_T ExtensionI2cExample_Write(uint8_t slaveAddr, uint8_t regAddr, uint8_t *writeVal, uint8_t writeLength)
This API is used to write the data received over the I2C extension port interface.
slaveAddr slave address of the I2C regAddr Address of the register to write writeVal Buffer to hold the data to be transmitted over I2C writeLength No of bytes to be transmitted over the I2C bus RETCODE_OK on success, or an error code otherwise. Refer interface header for description
References I2CTranceiverInstance.
Referenced by ExtensionI2cExample_ValidateChip.