ExtensionPortSpiCtrl.c
BCDS_MODULE_ID
This Module contains support feature like the Chip select and Acknowledgment pin handling controls for SPI.
BSP_IO_PIN_HIGH
Referenced by ExtensionPortSpiCtrl_AckAwaitHigh.
BSP_IO_PIN_LOW
Referenced by ExtensionPortSpiCtrl_AckAwaitLow.
Retcode_T ExtensionPortSpiCtrl_AckAwaitHigh(void)
function to await on Extension board SPI ACK pin until it is High Will exit only when the Extension board SPI ACK pin gets Low
Refer interface header for description
References RETCODE_OK, EXT_PORT_SPI_ACK_PIN_ID, BSP_IO_PIN_HIGH, BSP_Board_Delay.
Referenced by HandleSPIDataTransfer.
Retcode_T ExtensionPortSpiCtrl_AckAwaitLow(void)
function to await on Extension board SPI ACK pin until it is Low Will exit only when the Extension board SPI ACK pin gets High
Refer interface header for description
References RETCODE_OK, EXT_PORT_SPI_ACK_PIN_ID, BSP_IO_PIN_LOW, BSP_Board_Delay.
Referenced by HandleSPIDataTransfer.
Retcode_T ExtensionPortSpiCtrl_CSHigh(void)
function to Put the Extension board SPI CS pin High
Refer interface header for description
References RETCODE_OK, EXT_PORT_SPI_CS_PIN_ID.
Referenced by HandleSPIDataTransfer.
Retcode_T ExtensionPortSpiCtrl_CSLow(void)
function to Put the Extension board SPI CS pin Low
Refer interface header for description
References RETCODE_OK, EXT_PORT_SPI_CS_PIN_ID.
Referenced by HandleSPIDataTransfer.
Retcode_T ExtensionPortSpiCtrl_DeInitialize(void)
function to deinitialize the Extension board SPI CS and Ack pins
Refer interface header for description
References RETCODE_OK, EXT_PORT_SPI_CS_PIN_ID, EXT_PORT_SPI_ACK_PIN_ID.
Referenced by Sigfox_SendToSleep.
Retcode_T ExtensionPortSpiCtrl_Initialize(void)
function to initialize the Extension board SPI CS and Ack pins
Refer interface header for description
References RETCODE_OK, EXT_PORT_SPI_CS_PIN_ID, NULL, EXT_PORT_SPI_ACK_PIN_ID.
Referenced by Sigfox_Setup.