ExtensionPortSpi.c
BCDS_MODULE_ID
This Module contains necessary implementation in order to enable user to develop his application using the Extension port SPI communication interface. This module can be used a reference design for interfacing user device via SPI of extension port.
SemaphoreHandle_t SpiCompleteSync
Referenced by AppCallback, ExtensionPortSpi_Initialize, ExtensionPortSpi_Read, ExtensionPortSpi_Write, ExtensionPortSpi_DeInitialize.
HWHandle_T SpiHandle
SPI handle for hardware SPI instance created for External SPI hardware
Referenced by ExtensionPortSpi_Initialize, ExtensionPortSpi_Read, ExtensionPortSpi_Write, ExtensionPortSpi_DeInitialize.
static void AppCallback(SPI_T spi, struct MCU_SPI_Event_S event)
Callback function to be triggered upon Tx & Rx interrupts through the SPI.
References SpiCompleteSync, NULL, portBASE_TYPE, xHigherPriorityTaskWoken, xSemaphoreGiveFromISR, portYIELD_FROM_ISR, Retcode_RaiseErrorFromIsr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, RETCODE_SEVERITY_ERROR, RETCODE_EXTENSIONPORTSPI_RX_ERROR, RETCODE_EXTENSIONPORTSPI_TX_ERROR, RETCODE_EXTENSIONPORTSPI_DATALOSS.
Referenced by ExtensionPortSpi_Initialize.
Retcode_T ExtensionPortSpi_DeInitialize(void)
This API Deinitialize the SPI interface driver.
Refer interface header for description
References RETCODE_OK, NULL, SpiHandle, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, SpiCompleteSync, vSemaphoreDelete.
Referenced by Sigfox_SendToSleep, ExtensionSpiExample_DeInitialize.
Retcode_T ExtensionPortSpi_Initialize(ExtensionPortSpi_Config_T *config)
This API initialize the SPI Interface Driver.
Refer interface header for description
References RETCODE_OK, ExtensionPortSpi_Config_S::BaudRate, NULL, ExtensionPortSpi_Config_S::ClockMode, ExtensionPortSpi_Config_S::BitOrder, SpiCompleteSync, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_OUT_OF_RESOURCES, SpiHandle, AppCallback, RETCODE_NULL_POINTER.
Referenced by Sigfox_Setup, ExtensionSpiExample_Initialize.
Retcode_T ExtensionPortSpi_Read(uint8_t *readVal, uint32_t readLength, uint32_t timeout)
This API will Read the value from the SPI interface driver.
Refer interface header for description
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_WARNING, RETCODE_INVALID_PARAM, SpiCompleteSync, RETCODE_UNINITIALIZED, SpiHandle, xSemaphoreTake, RETCODE_TIMEOUT.
Referenced by HandleSPIDataTransfer, ExtensionSpiExample_ReadRegister.
Retcode_T ExtensionPortSpi_Write(uint8_t *writeVal, uint32_t writeLength, uint32_t timeout)
This API will Write the Value to the SPI interface driver.
Refer interface header for description
References RETCODE_OK, RETCODE, RETCODE_SEVERITY_WARNING, RETCODE_INVALID_PARAM, SpiCompleteSync, NULL, RETCODE_UNINITIALIZED, SpiHandle, xSemaphoreTake, RETCODE_TIMEOUT.
Referenced by HandleSPIDataTransfer, ExtensionSpiExample_ReadRegister, ExtensionSpiExample_WriteRegister.