ExtensionPortSpiCtrl.h
EXT_PORT_SPI_ACK_PIN_ID
Referenced by ExtensionPortSpiCtrl_Initialize, ExtensionPortSpiCtrl_AckAwaitHigh, ExtensionPortSpiCtrl_AckAwaitLow, ExtensionPortSpiCtrl_DeInitialize.
EXT_PORT_SPI_CS_PIN_ID
Referenced by ExtensionPortSpiCtrl_Initialize, ExtensionPortSpiCtrl_CSLow, ExtensionPortSpiCtrl_CSHigh, ExtensionPortSpiCtrl_DeInitialize.
Retcode_T ExtensionPortSpiCtrl_AckAwaitHigh(void)
function to await on Extension board SPI ACK pin until it is High Will exit only when the Extension board SPI ACK pin gets Low
ExtensionPortSpiCtrl_Initialize must have been successful prior RETCODE_OK on success, or an error code otherwise. Refer interface header for description
References RETCODE_OK, EXT_PORT_SPI_ACK_PIN_ID, BSP_IO_PIN_HIGH, BSP_Board_Delay.
Referenced by HandleSPIDataTransfer.
Retcode_T ExtensionPortSpiCtrl_AckAwaitLow(void)
function to await on Extension board SPI ACK pin until it is Low Will exit only when the Extension board SPI ACK pin gets High
ExtensionPortSpiCtrl_Initialize must have been successful prior RETCODE_OK on success, or an error code otherwise. Refer interface header for description
References RETCODE_OK, EXT_PORT_SPI_ACK_PIN_ID, BSP_IO_PIN_LOW, BSP_Board_Delay.
Referenced by HandleSPIDataTransfer.
Retcode_T ExtensionPortSpiCtrl_CSHigh(void)
function to Put the Extension board SPI CS pin High
ExtensionPortSpiCtrl_Initialize must have been successful prior RETCODE_OK on success, or an error code otherwise. Refer interface header for description
References RETCODE_OK, EXT_PORT_SPI_CS_PIN_ID.
Referenced by HandleSPIDataTransfer.
Retcode_T ExtensionPortSpiCtrl_CSLow(void)
function to Put the Extension board SPI CS pin Low
ExtensionPortSpiCtrl_Initialize must have been successful prior RETCODE_OK on success, or an error code otherwise. Refer interface header for description
References RETCODE_OK, EXT_PORT_SPI_CS_PIN_ID.
Referenced by HandleSPIDataTransfer.
Retcode_T ExtensionPortSpiCtrl_DeInitialize(void)
function to deinitialize the Extension board SPI CS and Ack pins
ExtensionPortSpi_Initialize must have been successful prior RETCODE_OK on success, or an error code otherwise. Refer interface header for description
References RETCODE_OK, EXT_PORT_SPI_CS_PIN_ID, EXT_PORT_SPI_ACK_PIN_ID.
Referenced by Sigfox_SendToSleep.
Retcode_T ExtensionPortSpiCtrl_Initialize(void)
function to initialize the Extension board SPI CS and Ack pins
This must be the first API to use this module. RETCODE_OK on success, or an error code otherwise. Refer interface header for description
References RETCODE_OK, EXT_PORT_SPI_CS_PIN_ID, NULL, EXT_PORT_SPI_ACK_PIN_ID.
Referenced by Sigfox_Setup.