ExtensionSpiExample.h
Retcode_T ExtensionSpiExample_DeInitialize(void)
This API Deinitialize the SPI interface driver Once this called, from there-on user needs to call ExtensionSpiExample_Initialize for using the SPI communication again.
RETCODE_OK on success, or an error code otherwise. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Refer interface header for description
References RETCODE_OK, ExtensionPortSpi_DeInitialize, SpiCSPinDeInit.
Retcode_T ExtensionSpiExample_Initialize(CmdProcessor_T *handle)
This API initialize the SPI Interface Driver.
handle Command processor handle RETCODE_OK on success, or an error code otherwise. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Refer interface header for description
References BCDS_UNUSED, RETCODE_OK, ExtensionPortSpi_Config_S::BaudRate, SPI_DATA_TRANSFER_BAUDRATE, EXTENSION_PORT_SPI_BIT_ORDER_MSB_FIRST, EXTENSION_PORT_SPI_CLOCK_MODE_0, SpiCSPinInit, ExtensionPortSpi_Initialize.
Referenced by AppControllerSetup.
Retcode_T ExtensionSpiExample_ReadRegister(uint8_t regAddr, uint8_t *readVal, uint8_t readLength)
This API Read the value from the SPI interface driver.
regAddr Address of the register to Read readVal Buffer to hold the data received over SPI readLength No of bytes to be read over the SPI bus RETCODE_OK on success, or an error code otherwise. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Refer interface header for description
References RETCODE_OK, SpiSetCSLow, ExtensionPortSpi_Write, SPI_DATA_TRANSFER_TIMEOUT_MILLISEC, ExtensionPortSpi_Read, SpiSetCSHigh.
Referenced by ExtensionSpiExample_ValidateChip.
Retcode_T ExtensionSpiExample_ValidateChip(void)
This API is used to demonstrate read and write on the extension port SPI interface.
RETCODE_OK on success, or an error code otherwise. Refer interface header for description
References RETCODE_OK, ExtensionSpiExample_ReadRegister, EXT_PORT_SPI_REG2_ADDR, EXT_PORT_SPI_READ_BIT, EXT_PORT_SPI_REG2_ADDR_VAL, EXT_PORT_SPI_REG1_ADDR_VAL, ExtensionSpiExample_WriteRegister, EXT_PORT_SPI_REG1_ADDR, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_FAILURE.
Referenced by AppControllerFire.
Retcode_T ExtensionSpiExample_WriteRegister(uint8_t regAddr, uint8_t *writeVal, uint8_t writeLength)
This API Write the Value to the SPI interface driver.
regAddr Address of the register to write writeVal Buffer to hold the data to be transmitted over SPI writeLength No of bytes to be transmitted over the SPI bus RETCODE_OK on success, or an error code otherwise. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Refer interface header for description
References RETCODE_OK, SpiSetCSLow, ExtensionPortSpi_Write, SPI_DATA_TRANSFER_TIMEOUT_MILLISEC, SpiSetCSHigh.
Referenced by ExtensionSpiExample_ValidateChip.