ExtensionGpioExample.h
Retcode_T ExtensionGpioExample_DeleteGpio(BSP_ExtensionPort_PinId_T pinId)
This API is used to de-initialize a particular GPIO pin and put it into default state.
pinId Pin Id for extension port GPIO pin Refer BSP_ExtensionPort.h to get the value macro definitions for pinId value RETCODE_OK on success, or an error code otherwise. Refer interface header for description
References RETCODE_OK.
Retcode_T ExtensionGpioExample_InitGpioIntBothEdge(BSP_ExtensionPort_PinId_T pinId)
This API is used to configure GPIO as Input and capable of triggering interrupt for both Raising and Falling. After calling this API successfully the signal on the GPIO will trigger an Interrupt.
pinId Pin Id for extension port GPIO pin Refer BSP_ExtensionPort.h to get the value macro definitions for pinId value RETCODE_OK on success, or an error code otherwise. Refer interface header for description
References RETCODE_OK, NULL, GpioInterruptCallback, GpioPinIdForEdgeInterrupt.
Referenced by AppControllerEnable.
Retcode_T ExtensionGpioExample_InitGpioOutputMode(BSP_ExtensionPort_PinId_T pinId)
This API is used to configure GPIO pin as output pin.
pinId Pin Id for extension port GPIO pin Refer BSP_ExtensionPort.h to get the value macro definitions for pinId value RETCODE_OK on success, or an error code otherwise. This API demonstrates how to configure GPIO as output with push-pull mode. This API puts the pin to default value as 'logic 0'. This API is written for demonstration purpose only and hence kept as simple as possible. For different output mode configuration user can modify this API or write new API based on his application requirement. Refer interface header for description
References RETCODE_OK, NULL.
Referenced by AppControllerFire.
Retcode_T ExtensionGpioExample_Initialize(CmdProcessor_T *handle)
This API is used to initialize the GPIO example resources.
handle Command processor handle This must be the first API to be called if any of the features in this module is to be used. RETCODE_OK on success, or an error code otherwise. Refer interface header for description
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER.
Referenced by AppControllerSetup.