FOTA.c
BCDS_MODULE_ID
FIRMWARE_NAME
Filename to open/write/read from SD-card
Referenced by FOTA_ValidateSdcardFw, FOTA_UpdateSdcardFw.
Retcode_T FOTA_ReadFirmwareCRC(Fota_PartitionInfo_T partitionInfo, uint32_t *firmwareCRC)
This function reads the Fota container firmware CRC on the fota header from the specified partition.
partitionInfo mention the partition information from which firmware CRC info needs to be read. In-case of FOTA_PARTITION_DOWNLOAD specify the file name Incase of FOTA_PARTITION_PRIMARY file name is not used, can be NULL. firmwareCRC pointer to hold the Fota container firmware CRC information. Storage_Setup & Storage_Enable must be called prior to using this API. RETCODE_OK if fota container firmware CRC is read properly, or an error code otherwise.
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, FOTA_ReadHeader.
Referenced by FOTA_UpdateSdcardFw.
Retcode_T FOTA_ReadFirmwareVersion(Fota_PartitionInfo_T partitionInfo, uint32_t *FirmwareVer)
This function reads the Fota container firmware version on the fota header from the specified partition.
partitionInfo mention the partition information from which Firmware version needs to be read. In-case of FOTA_PARTITION_DOWNLOAD specify the file name Incase of FOTA_PARTITION_PRIMARY file name is not used can be NULL. firmwareVer pointer to hold the Fota container firmware version information. Storage_Setup & Storage_Enable must be called prior to using this API. RETCODE_OK if fota container firmware version is read properly, or an error code otherwise.
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, FOTA_ReadHeader.
Referenced by Utils_GetXdkVersionString.
Retcode_T FOTA_ReadHeader(Fota_PartitionInfo_T partitionInfo, FWContainer_Header_T *Header)
This function reads the Fota container header from the specified partition.
partitionInfo mention the partition information from which header info needs to be read. In-case of FOTA_PARTITION_DOWNLOAD specify the file name Incase of FOTA_PARTITION_PRIMARY file name is not used can be NULL. header Buffer pointer to hold the read Fota container header information. Storage_Setup & Storage_Enable must be called prior to using this API. RETCODE_OK if fota container header is read properly, or an error code otherwise.
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, FOTA_PARTITION_DOWNLOADED, Fota_PartitionInfo_S::Partition, Fota_PartitionInfo_S::PartitionFileName, Storage_Read_S::FileName, Storage_Read_S::ReadBuffer, Storage_Read_S::BytesToRead, Storage_Read_S::ActualBytesRead, Storage_Read_S::Offset, Storage_Read, STORAGE_MEDIUM_SD_CARD, FOTA_PARTITION_PRIMARY, FOTA_PRIMARY_PARTTITION_START_ADDRESS, RETCODE_SEVERITY_ERROR, RETCODE_FOTA_PARTITION_UNKNOWN.
Referenced by FOTA_ReadFirmwareVersion, FOTA_ReadFirmwareCRC, FOTA_ValidateSdcardFw.
Retcode_T FOTA_UpdateSdcardFw(void)
This function Triggers an firmware update from Sdcard.
Firmware has to be validated by calling FOTA_ValidateSdcardFw() before updating.latest validated firmware will be updated. If firmware is valid.Device will be rebooted so no return value, or an error code otherwise.
References RETCODE_OK, FR_OK, FILINFO::lfname, NULL, f_stat, FIRMWARE_NAME, RETCODE, RETCODE_SEVERITY_WARNING, RETCODE_STORAGE_SDCARD_STAT_FAILED, Fota_PartitionInfo_S::Partition, FOTA_PARTITION_DOWNLOADED, Fota_PartitionInfo_S::PartitionFileName, FOTA_ReadFirmwareCRC, NVM_WriteUInt32, NVMUser, NVM_ITEM_ID_NEW_FW_CRC, NVM_WriteUInt8, NVM_ITEM_ID_IS_NEW_FW, NVM_Flush, BSP_Board_SoftReset.
Retcode_T FOTA_ValidateSdcardFw(const char *firmwareName)
This function Validates the firmware in the Sdcard.
firmwareName Name of the firmware which needs to be validated. Storage_Setup & Storage_Enable must be called prior to using this API.If Firmware is valid,this API will rename the firmware to "firmware.bin"In-case if "firmware.bin" is already available then it will be overwritten with the new firmware "firmwareName" . RETCODE_OK if firmware is valid, or an error code otherwise.
References RETCODE_OK, FR_OK, Fota_PartitionInfo_S::Partition, FOTA_PARTITION_DOWNLOADED, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, FOTA_ReadHeader, VerifyHeader, VerifyImage, f_rename, FIRMWARE_NAME, FR_EXIST, f_unlink, RETCODE_SEVERITY_WARNING, RETCODE_FOTA_FILESYSTEM_ERROR.
static Retcode_T VerifyHeader(FWContainer_Header_T *header)
Verifies the Header CRC & firmware size of the given fota container.
header pointer to a buffer holding the fota container header data. status RETCODE_OK if header CRC is passed & firmware size is within the maximum range or an error code otherwise.
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, CRC32_EATH_STD_INIT, CRC_32_Reverse, CRC32_ETHERNET_REVERSE_POLYNOMIAL, RETCODE_SEVERITY_ERROR, FOTA_FW_CRCRUN_FAIL, CRC32_INVERSE, FOTA_FW_CRC_FAIL, FOTA_FIRMWARE_MAX_SIZE, FOTA_RETCODE_FIRMWARE_SIZE_FAIL.
Referenced by FOTA_ValidateSdcardFw.
static Retcode_T VerifyImage(Fota_PartitionInfo_T *partitionInfo, uint8_t *optBuffer)
Verifies the firmware CRC of the given fota container partition.
partitionInfo mention the partition information for which header firmware CRC needs to be verified. In-case of FOTA_PARTITION_DOWNLOADED specify the file name Incase of FOTA_PARTITION_PRIMARY file name is not used, can be NULL. optBuffer Operation buffer from the application where blocks of the firmware is kept for the CRC calculation. Make sure minimum buffer size of optBuffer is sizeof(Fota_PartitionInfo_T).Storage_Setup & Storage_Enable must be called prior to using this API.
References RETCODE_OK, Storage_Read_S::FileName, NULL, FOTA_PARTITION_PRIMARY, Fota_PartitionInfo_S::Partition, FOTA_PRIMARY_PARTTITION_START_ADDRESS, FOTA_PARTITION_DOWNLOADED, Fota_PartitionInfo_S::PartitionFileName, Storage_Read, STORAGE_MEDIUM_SD_CARD, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_FOTA_PARTITION_UNKNOWN, FWContainer_Header_S::FirmwareCRC, FWContainer_Header_S::FirmwareSize, CRC32_EATH_STD_INIT, Storage_Read_S::BytesToRead, FWCONTAINER_BLOCK_SIZE, Storage_Read_S::Offset, CRC_32_Reverse, CRC32_ETHERNET_REVERSE_POLYNOMIAL, FOTA_FW_CRCRUN_FAIL, CRC32_INVERSE, FOTA_FW_CRC_FAIL.
Referenced by FOTA_ValidateSdcardFw.