FaultHandler.c
NVIC_AFSR
Referenced by extractFaultInfo.
NVIC_BFAR
Referenced by extractFaultInfo.
NVIC_BFSR
Referenced by extractFaultInfo.
NVIC_DFSR
Referenced by extractFaultInfo.
NVIC_HFSR
Referenced by extractFaultInfo.
NVIC_MFSR
Referenced by extractFaultInfo.
NVIC_UFSR
Referenced by extractFaultInfo.
SYSHND_CTRL
Referenced by extractFaultInfo.
volatile unsigned int afsr
unsigned int APSR
volatile unsigned int bfar
unsigned int BFARVALID
union @12::@16 bfsr
struct @12::@19::@27 bits
unsigned int BKPT
unsigned int BUSFAULTACT
unsigned int BUSFAULTENA
unsigned int BUSFAULTPENDED
volatile unsigned int byte
unsigned char DACCVIOL
unsigned int DEBUGEVT
union @12::@19 dfsr
unsigned short DIVBYZERO
unsigned int DWTTRAP
unsigned int EPSR
unsigned int EXTERNAL
unsigned int FORCED
unsigned int HALTED
struct @12 HardFaultRegs
Referenced by extractFaultInfo.
union @12::@18 hfsr
unsigned char IACCVIOL
unsigned int IBUSERR
unsigned int IMPREISERR
unsigned short INVPC
unsigned short INVSTATE
unsigned int IPSR
volatile unsigned int lr
unsigned int MEMFAULTACT
unsigned int MEMFAULTENA
unsigned int MEMFAULTPENDED
union @12::@15 mfsr
unsigned char MMARVALID
unsigned int MONITORACT
unsigned char MSTKERR
unsigned char MUNSTKERR
unsigned short NOCP
volatile unsigned int pc
unsigned int PENDSVACT
unsigned int PRECISERR
union @12::@13::@20 psr
volatile unsigned int r0
volatile unsigned int r1
volatile unsigned int r12
volatile unsigned int r2
volatile unsigned int r3
struct @12::@13 SavedRegs
unsigned int STKERR
unsigned int SVCALLACT
unsigned int SVCALLPENDED
union @12::@14 syshndctrl
unsigned int SYSTICKACT
union @12::@17 ufsr
unsigned short UNALIGNED
unsigned short UNDEFINSTR
unsigned int UNSTKERR
unsigned int UnusedBits
unsigned int UnusedBits1
unsigned int UnusedBits2
unsigned int UnusedBits3
unsigned int USGFAULTACT
unsigned int USGFAULTENA
unsigned int USGFAULTPENDED
unsigned int VCATCH
unsigned int VECTBL
__attribute__((naked))
Debug function which is entered whenever an unrecoverable system fault occurs. pulFaultStackAddress Pointer to the saved fault stack.Hard Fault exception handler Usage Fault exception handlerBUS Fault exception handlerMemory Manager Fault exception handler
void Bus_Fault_Handler(unsigned int *pulBusFaultStackAddress)
References extractFaultInfo.
static void extractFaultInfo(unsigned int *pStack)
References HardFaultRegs, SYSHND_CTRL, NVIC_MFSR, NVIC_BFSR, NVIC_BFAR, NVIC_UFSR, NVIC_HFSR, NVIC_DFSR, NVIC_AFSR, BSP_Board_SoftReset.
Referenced by Hard_Fault_Handler, Usage_Fault_Handler, Bus_Fault_Handler, Mem_Fault_Handler.
void Hard_Fault_Handler(unsigned int *pulHardFaultStackAddress)
References extractFaultInfo.
void Mem_Fault_Handler(unsigned int *pulMemFaultStackAddress)
References extractFaultInfo.
void Usage_Fault_Handler(unsigned int *pulUsageFaultStackAddress)
References extractFaultInfo.