Gyroscope.c
BCDS_MODULE_ID
const uint8_t autoSleepDurationValueLookUpTable[GYROSCOPE_BMG160_AUTOSLEEP_DURATION_OUT_OF_RANGE][GYROSCOPE_BMG160_AUTOSLEEP_DURATION_OUT_OF_RANGE]
Referenced by Gyroscope_setAutoSleepDuration.
uint16_t bmgRangeValue
Referenced by Gyroscope_setRange, Gyroscope_readXyzDegreeValue.
uint16_t bmiRangeValue
Referenced by Gyroscope_setRange, Gyroscope_readXyzDegreeValue.
const uint8_t bwLookUpTable[GYROSCOPE_BANDWIDTH_OUT_OF_RANGE][GYROSCOPE_BANDWIDTH_OUT_OF_RANGE]
Referenced by Gyroscope_setBandwidth, Gyroscope_getBandwidth.
const uint8_t getModeLookUpTable[GYROSCOPE_POWERMODE_OUT_OF_RANGE][GYROSCOPE_POWERMODE_OUT_OF_RANGE]
Referenced by Gyroscope_getMode.
const uint8_t modeLookUpTable[GYROSCOPE_POWERMODE_OUT_OF_RANGE][GYROSCOPE_POWERMODE_OUT_OF_RANGE]
Referenced by Gyroscope_setMode, Gyroscope_getMode.
const uint8_t rangeLookUpTable[GYROSCOPE_OUT_OF_RANGE][GYROSCOPE_OUT_OF_RANGE]
Referenced by Gyroscope_setRange, Gyroscope_getRange.
const uint16_t rangeValueLookUpTable[GYROSCOPE_OUT_OF_RANGE][GYROSCOPE_OUT_OF_RANGE]
Referenced by Gyroscope_setRange.
const uint8_t sleepDurationValueLookUpTable[GYROSCOPE_BMG160_SLEEP_DURATION_OUT_OF_RANGE][GYROSCOPE_BMG160_SLEEP_DURATION_OUT_OF_RANGE]
Referenced by Gyroscope_setSleepDuration.
static Retcode_T bmg160LibErrorMapping(BMG160_RETURN_FUNCTION_TYPE BMG160_libReturn)
This function maps error codes returned from BMG160 library to retcode values.
BMG160_RETURN_FUNCTION_TYPE Return value from BMG160 library RETCODE_OK BMG160 sensor API call success RETCODE_FAILURE BMG160 sensor API call failed RETCODE_INVALID_PARAM BMG160 sensor API call failed because of invalid input parameter
References RETCODE_FAILURE, BMG160_RETURN_FUNCTION_TYPE, RETCODE_OK, E_BMG160_NULL_PTR, RETCODE_INVALID_PARAM.
Referenced by Gyroscope_setBandwidth, Gyroscope_setRange, Gyroscope_getRange, Gyroscope_getBandwidth, Gyroscope_setMode, Gyroscope_getMode, Gyroscope_readXyzValue, Gyroscope_readXyzDegreeValue, Gyroscope_setSleepDuration, Gyroscope_setAutoSleepDuration.
static void bmgIsrCallback(uint32_t channel, uint32_t edge)
BMG160 driver callback function that will be called during ISR.
channel channel at which interrupt has occurred edge edge at which interrupt has occurred falling(0) or raising edge(1) Currently interrupt is not supported for BMG160
References BCDS_UNUSED.
Referenced by Gyroscope_init.
static Retcode_T BMI160_libErrorMapping(BMI160_RETURN_FUNCTION_TYPE BMI160_libReturn)
This function maps error codes returned from BMI160 library to retcode values.
BMI160_RETURN_FUNCTION_TYPE Return value from BMI160 library RETCODE_OK BMI160 sensor API call success RETCODE_FAILURE BMI160 sensor API call failed
References RETCODE_FAILURE, SUCCESS, RETCODE_OK, E_BMI160_NULL_PTR, RETCODE_INVALID_PARAM.
Referenced by Gyroscope_setBandwidth, Gyroscope_setRange, Gyroscope_getRange, Gyroscope_getBandwidth, Gyroscope_setMode, Gyroscope_getMode, Gyroscope_readXyzValue, Gyroscope_readXyzDegreeValue.
Retcode_T Gyroscope_deInit(Gyroscope_HandlePtr_T handle)
Function to DeInitializes the Gyroscope referenced by the passed handle.
handle Handle to the Gyroscope object RETCODE_SUCCESS Gyroscope De-initialization success. RETCODE_INVALID_PARAM In case of invalid sensor handle. In case of any other error refer Bmg160Utils_uninitialize or Bmi160Utils_uninitialize error codes. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Gyroscope_Handle_S::sensorInfo, Gyroscope_SensorInfo_S::initializationStatus, RETCODE_OK, Gyroscope_SensorInfo_S::sensorID, BMG160_GYRO_SENSOR, Bmg160Utils_uninitialize, Gyroscope_Handle_S::sensorPtr, BMI160_GYRO_SENSOR, Bmi160Utils_uninitialize, Retcode_GetPackage, PACKAGE_ID_DEFAULT, RETCODE_SEVERITY_ERROR.
Referenced by LWM2MSensorDeviceGyroscope_InitRand, LWM2MSensorDeviceGyroscope_Activate.
Retcode_T Gyroscope_getBandwidth(Gyroscope_HandlePtr_T handle, Gyroscope_BandwidthPtr_T bandwidth)
Reads the bandwidth for the Gyroscope referenced by the passed handle.
handle Handle to the Gyroscope object [in/out] bandwidth Collects the last set Bandwidth value from the gyro sensor RETCODE_SUCCESS Getting Bandwidth success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of getting bandwidth values other than Gyroscope_Bandwidth_E. In case of other failures refer bmg160LibErrorMapping or BMI160_libErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References GET_MAPPING_ERROR, RETCODE_FAILURE, GYROSCOPE_BANDWIDTH_OUT_OF_RANGE, BMG160_RETURN_FUNCTION_TYPE, C_BMG160_FAILURE, BMI160_RETURN_FUNCTION_TYPE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, Gyroscope_Handle_S::sensorInfo, Gyroscope_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Gyroscope_SensorInfo_S::sensorID, BMG160_GYRO_SENSOR, bmg160_get_bw, bmg160LibErrorMapping, RETCODE_OK, mappingEnumForGetFunctions, GYROSCOPE_BMG160_BANDWIDTH_12HZ, GYROSCOPE_BMG160_BANDWIDTH_523HZ, bwLookUpTable, RETCODE_NOT_SUPPORTED, BMI160_GYRO_SENSOR, bmi160_get_gyro_output_data_rate, BMI160_libErrorMapping, GYROSCOPE_BMI160_BANDWIDTH_10_7HZ, GYROSCOPE_BMI160_BANDWIDTH_890HZ, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T Gyroscope_getMode(Gyroscope_HandlePtr_T handle, Gyroscope_PowermodePtr_T powermode)
Reads the power mode for the Gyroscope by the passed handle.
handle Handle to the Gyroscope object [in/out] powermode Collects the last set power mode value from gyro sensor RETCODE_SUCCESS Getting power mode success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of getting power mode other than Gyroscope_Powermode_E. In case of other failures refer bmg160LibErrorMapping or BMI160_libErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References GET_MAPPING_ERROR, RETCODE_FAILURE, BMG160_RETURN_FUNCTION_TYPE, C_BMG160_FAILURE, BMI160_RETURN_FUNCTION_TYPE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Gyroscope_Handle_S::sensorInfo, Gyroscope_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Gyroscope_SensorInfo_S::sensorID, BMG160_GYRO_SENSOR, bmg160_get_power_mode, bmg160LibErrorMapping, RETCODE_OK, mappingEnumForGetFunctions, GYROSCOPE_BMG160_POWERMODE_NORMAL, GYROSCOPE_BMG160_POWERMODE_ADVANCE_POWERUP, modeLookUpTable, RETCODE_NOT_SUPPORTED, BMI160_GYRO_SENSOR, bmi160_get_gyro_power_mode_stat, BMI160_libErrorMapping, GYROSCOPE_BMI160_POWERMODE_SUSPEND, GYROSCOPE_BMI160_POWERMODE_FAST_STARTUP, getModeLookUpTable, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T Gyroscope_getRange(Gyroscope_HandlePtr_T handle, Gyroscope_RangePtr_T range)
Reads the Range for the Gyroscope referenced by the passed handle.
handle Handle to the Gyroscope object [in/out] range Collects the last set measurement range value from the sensor RETCODE_SUCCESS Getting range success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of getting range values other than Gyroscope_Range_E. In case of other failures refer bmg160LibErrorMapping or BMI160_libErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References GET_MAPPING_ERROR, RETCODE_FAILURE, BMG160_RETURN_FUNCTION_TYPE, C_BMG160_FAILURE, BMI160_RETURN_FUNCTION_TYPE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, Gyroscope_Handle_S::sensorInfo, Gyroscope_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Gyroscope_SensorInfo_S::sensorID, BMG160_GYRO_SENSOR, bmg160_get_range_reg, bmg160LibErrorMapping, RETCODE_OK, mappingEnumForGetFunctions, GYROSCOPE_BMG160_RANGE_125s, GYROSCOPE_BMG160_RANGE_2000s, rangeLookUpTable, RETCODE_NOT_SUPPORTED, BMI160_GYRO_SENSOR, bmi160_get_gyro_range, BMI160_libErrorMapping, GYROSCOPE_BMI160_125S_RANGE, GYROSCOPE_BMI160_2000S_RANGE, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Referenced by LWM2MSensorDeviceGyroscope_Activate.
Retcode_T Gyroscope_init(Gyroscope_HandlePtr_T handle)
Function to initialize Gyroscope.This needs to be called before calling any other API.
handle Handle to the Gyroscope object RETCODE_SUCCESS Gyroscope initialization success. RETCODE_INVALID_PARAM In case of invalid sensor handle. In case of any other error refer Bmg160Utils_initialize or Bmi160Utils_initialize error codes. This function needs to be called before calling any other Gyroscope API. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, NULL, Gyroscope_Handle_S::sensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, Gyroscope_Handle_S::sensorInfo, Gyroscope_SensorInfo_S::initializationStatus, RETCODE_OK, Gyroscope_SensorInfo_S::sensorID, BMG160_GYRO_SENSOR, Bmg160Utils_Info_S::ISRCallback, bmgIsrCallback, Bmg160Utils_initialize, BMI160_GYRO_SENSOR, Bmi160Utils_Info_S::ISRCallback, Bmi160Utils_initialize, Retcode_GetCode, RETCODE_DOPPLE_INITIALIZATION, Retcode_GetPackage, PACKAGE_ID_DEFAULT, RETCODE_SEVERITY_ERROR.
Referenced by LWM2MSensorDeviceGyroscope_InitRand, LWM2MSensorDeviceGyroscope_Activate.
Retcode_T Gyroscope_readXyzDegreeValue(Gyroscope_HandlePtr_T handle, Gyroscope_XyzDataPtr_T gyrodata)
Reads an Xyz degree value from the Gyroscope referenced by the passed handle.
handle Handle to the Gyroscope object [in/out] value Collects the XYZ value of gyro sensor in milli Degree RETCODE_SUCCESS Reading xyzDegree value success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. In case of other failures refer Bmg160Utils_remapAxis, Bmi160Utils_remapAxis, bma2x2LibErrorMapping or bmi160LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, BMG160_RETURN_FUNCTION_TYPE, C_BMG160_FAILURE, BMI160_RETURN_FUNCTION_TYPE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Gyroscope_Handle_S::sensorInfo, Gyroscope_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Gyroscope_SensorInfo_S::sensorID, BMG160_GYRO_SENSOR, bmg160_get_data_XYZ, bmg160LibErrorMapping, bmgRangeValue, BMG160S_GYRO_MILLIDEGREE, BMG160S_GYRO_RESOLUTION, RETCODE_OK, AxisRemap_Data_S::x, bmg160_data_t::datax, AxisRemap_Data_S::y, bmg160_data_t::datay, AxisRemap_Data_S::z, bmg160_data_t::dataz, Bmg160Utils_remapAxis, Gyroscope_Handle_S::sensorPtr, Gyroscope_XyzData_S::xAxisData, Gyroscope_XyzData_S::yAxisData, Gyroscope_XyzData_S::zAxisData, BMI160_GYRO_SENSOR, bmi160_read_gyro_xyz, BMI160_libErrorMapping, bmiRangeValue, BMI160S_GYRO_MILLIDEGREE, BMI160S_GYRO_RESOLUTION, bmi160_gyro_t::x, bmi160_gyro_t::y, bmi160_gyro_t::z, Bmi160Utils_remapAxis, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Referenced by LWM2MSensorDeviceGyroscope_InitRand, LWM2MSensorDeviceGyroscope_Update.
Retcode_T Gyroscope_readXyzValue(Gyroscope_HandlePtr_T handle, Gyroscope_XyzDataPtr_T gyrodata)
Reads an xyz values from the Gyroscope referenced by the passed handle.
handle Handle to the Gyroscope object [in/out] value Collects the XYZ value of gyro sensor in LSB RETCODE_SUCCESS Reading xyz value success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. In case of other failures refer Bmg160Utils_remapAxis, Bmi160Utils_remapAxis, bma2x2LibErrorMapping or bmi160LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, BMG160_RETURN_FUNCTION_TYPE, C_BMG160_FAILURE, BMI160_RETURN_FUNCTION_TYPE, NULL, Gyroscope_Handle_S::sensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Gyroscope_Handle_S::sensorInfo, Gyroscope_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Gyroscope_SensorInfo_S::sensorID, BMG160_GYRO_SENSOR, bmg160_get_data_XYZ, bmg160LibErrorMapping, RETCODE_OK, AxisRemap_Data_S::x, bmg160_data_t::datax, AxisRemap_Data_S::y, bmg160_data_t::datay, AxisRemap_Data_S::z, bmg160_data_t::dataz, Bmg160Utils_remapAxis, Gyroscope_XyzData_S::xAxisData, Gyroscope_XyzData_S::yAxisData, Gyroscope_XyzData_S::zAxisData, BMI160_GYRO_SENSOR, bmi160_read_gyro_xyz, BMI160_libErrorMapping, bmi160_gyro_t::x, bmi160_gyro_t::y, bmi160_gyro_t::z, Bmi160Utils_remapAxis, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T Gyroscope_setAutoSleepDuration(Gyroscope_HandlePtr_T handle, Gyroscope_AutoSleepDuration_T lowPowerModeSleepDuration, Gyroscope_Bandwidth_T bandwidthForAutoSleep)
Sets the Auto-SleepDuration for Gyroscope referenced by the passed handle.
handle Handle to the Gyroscope object lowPowerModeSleepDuration Represents the AutoSleepDuration that needs to be configured for gyro sensor bandwidthForAutoSleep It needs to be the value read from gyroscopeGetBandwidth(), this is required for proper operation of gyro sensor in advanced power saving mode only RETCODE_SUCCESS Set auto sleep Duration success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle or setting auto sleep values other than Gyroscope_AutoSleepDuration_E. RETCODE_NOT_SUPPORTED In case of Invalid sensor selection. In case of other failures refer bmg160LibErrorMapping API. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, BMG160_RETURN_FUNCTION_TYPE, C_BMG160_FAILURE, NULL, Gyroscope_Handle_S::sensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, GYROSCOPE_BMG160_BANDWIDTH_523HZ, RETCODE_SEVERITY_ERROR, GYROSCOPE_BMG160_AUTOSLEEP_DURATION_OUT_OF_RANGE, INIT_NOT_DONE, Gyroscope_Handle_S::sensorInfo, Gyroscope_SensorInfo_S::initializationStatus, RETCODE_UNINITIALIZED, Gyroscope_SensorInfo_S::sensorID, BMG160_GYRO_SENSOR, bmg160_set_auto_sleep_durn, autoSleepDurationValueLookUpTable, bmg160LibErrorMapping, BMI160_GYRO_SENSOR, RETCODE_NOT_SUPPORTED, RETCODE_OK, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T Gyroscope_setBandwidth(Gyroscope_HandlePtr_T handle, Gyroscope_Bandwidth_T bandwidth)
Sets the bandwidth for the Gyroscope referenced by the passed handle.
handle Handle to the Gyroscope object bandwidth Represents the bandwidth that needs to be configured for gyro sensor RETCODE_SUCCESS Bandwidth setting success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of setting bandwidth values other than Gyroscope_Bandwidth_E. In case of other failures refer bmg160LibErrorMapping or BMI160_libErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, BMG160_RETURN_FUNCTION_TYPE, C_BMG160_FAILURE, BMI160_RETURN_FUNCTION_TYPE, NULL, Gyroscope_Handle_S::sensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, GYROSCOPE_BANDWIDTH_OUT_OF_RANGE, RETCODE_SEVERITY_ERROR, Gyroscope_Handle_S::sensorInfo, Gyroscope_SensorInfo_S::initializationStatus, RETCODE_UNINITIALIZED, Gyroscope_SensorInfo_S::sensorID, BMG160_GYRO_SENSOR, GYROSCOPE_BMG160_BANDWIDTH_523HZ, RETCODE_NOT_SUPPORTED, bmg160_set_high_bw, FILTERED_LOW_BANDWIDTH, C_BMG160_SUCCESS, bmg160_set_bw, bwLookUpTable, bmg160LibErrorMapping, BMI160_GYRO_SENSOR, GYROSCOPE_BMI160_BANDWIDTH_10_7HZ, bmi160_set_gyro_bw, SUCCESS, bmi160_set_gyro_output_data_rate, BMI160_libErrorMapping, RETCODE_OK, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T Gyroscope_setMode(Gyroscope_HandlePtr_T handle, Gyroscope_Powermode_T powermode)
Sets the powermode for the Gyroscope by the passed handle.
handle Handle to the Gyroscope object powermode Represents the power mode that needs to be configured for gyro sensor RETCODE_SUCCESS Setting power mode success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of setting power mode other than Gyroscope_Powermode_E. In case of other failures refer bmg160LibErrorMapping or BMI160_libErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, BMG160_RETURN_FUNCTION_TYPE, C_BMG160_FAILURE, BMI160_RETURN_FUNCTION_TYPE, NULL, Gyroscope_Handle_S::sensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, GYROSCOPE_POWERMODE_OUT_OF_RANGE, RETCODE_SEVERITY_ERROR, Gyroscope_Handle_S::sensorInfo, Gyroscope_SensorInfo_S::initializationStatus, RETCODE_UNINITIALIZED, Gyroscope_SensorInfo_S::sensorID, BMG160_GYRO_SENSOR, GYROSCOPE_BMG160_POWERMODE_ADVANCE_POWERUP, RETCODE_NOT_SUPPORTED, bmg160_set_power_mode, modeLookUpTable, bmg160LibErrorMapping, BMI160_GYRO_SENSOR, GYROSCOPE_BMI160_POWERMODE_SUSPEND, bmi160_set_command_register, BMI160_libErrorMapping, RETCODE_OK, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T Gyroscope_setRange(Gyroscope_HandlePtr_T handle, Gyroscope_Range_T range)
Sets the Range for the Gyroscope by the passed handle.
handle Handle to the Gyroscope object range Represents the measurement range that needs to be configured for gyro sensor RETCODE_SUCCESS Setting range success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of setting range values other than Gyroscope_Range_E. In case of other failures refer bmg160LibErrorMapping or BMI160_libErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, BMG160_RETURN_FUNCTION_TYPE, C_BMG160_FAILURE, BMI160_RETURN_FUNCTION_TYPE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, GYROSCOPE_OUT_OF_RANGE, RETCODE_SEVERITY_ERROR, Gyroscope_Handle_S::sensorInfo, Gyroscope_SensorInfo_S::initializationStatus, RETCODE_UNINITIALIZED, Gyroscope_SensorInfo_S::sensorID, BMG160_GYRO_SENSOR, GYROSCOPE_BMG160_RANGE_2000s, RETCODE_NOT_SUPPORTED, bmg160_set_range_reg, rangeLookUpTable, C_BMG160_SUCCESS, bmgRangeValue, rangeValueLookUpTable, bmg160LibErrorMapping, BMI160_GYRO_SENSOR, GYROSCOPE_BMI160_125S_RANGE, bmi160_set_gyro_range, SUCCESS, bmiRangeValue, BMI160_libErrorMapping, RETCODE_OK, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T Gyroscope_setSleepDuration(Gyroscope_HandlePtr_T handle, Gyroscope_SleepDuration_T lowPowerModeSleepDuration)
Sets the SleepDuration for Gyroscope referenced by the passed handle.
handle Handle to the Gyroscope object lowPowerModeSleepDuration Represents the Sleep Duration that needs to be configured for gyroscope sensor RETCODE_SUCCESS Set Sleep Duration success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle or setting sleep duration values other than Gyroscope_SleepDuration_E. RETCODE_NOT_SUPPORTED In case of Invalid sensor selection. In case of other failures refer bmg160LibErrorMapping API. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, BMG160_RETURN_FUNCTION_TYPE, C_BMG160_FAILURE, NULL, Gyroscope_Handle_S::sensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, GYROSCOPE_BMG160_SLEEP_DURATION_OUT_OF_RANGE, RETCODE_SEVERITY_ERROR, Gyroscope_Handle_S::sensorInfo, Gyroscope_SensorInfo_S::initializationStatus, RETCODE_UNINITIALIZED, Gyroscope_SensorInfo_S::sensorID, BMG160_GYRO_SENSOR, bmg160_set_sleep_durn, sleepDurationValueLookUpTable, bmg160LibErrorMapping, BMI160_GYRO_SENSOR, RETCODE_NOT_SUPPORTED, RETCODE_OK, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
static int8_t mappingEnumForGetFunctions(uint8_t start, uint8_t end, uint8_t getValueToBeTransalated, const uint8_t *lookUpTablePtr)
References GET_MAPPING_ERROR.
Referenced by Gyroscope_getRange, Gyroscope_getBandwidth, Gyroscope_getMode.