LWM2MObjectSensorDevice.c
BCDS_MODULE_ID
DEFAULT_SENSORS_MODE
DEFAULT_SENSORS_TRANSPORT_INTERVAL
MAC_LENGTH
MAX_MODE_LENGTH
SENSORDEVICE_RESOURCES_INDEX
Referenced by Interval, PreprocessingMode.
SENSORS_READ_INTERVAL
Referenced by LWM2MObjectSensorDevice_Init.
ProcessingMode_T LastMode
last time for sending sensor values in ms
Referenced by SensorTimerHandler.
int32_t LastTransportInterval
time of last sending information
Referenced by SensorTimerHandler.
uint64_t LastTransportTime
Referenced by SensorTimerHandler.
LWM2MObjectSensorDevice_Resource_T LWM2MObjectSensorDeviceResources
LWM2M resource data for instance 0.
ProcessingMode_T Mode
time for sending sensor values in ms
Referenced by SensorTimerHandler, PreprocessingMode.
volatile bool Started
Referenced by Interval, PreprocessingMode, LWM2MObjectSensorDevice_Init, LWM2MObjectSensorDevice_Enable, LWM2MObjectSensorDevice_Disable.
xTimerHandle TimerHandle
Timer handle for periodically reading sensor values
Referenced by LWM2MObjectSensorDevice_Init, LWM2MObjectSensorDevice_Enable, LWM2MObjectSensorDevice_Disable.
int32_t TransportInterval
Referenced by SensorTimerHandler, Interval.
static retcode_t Interval(Lwm2mSerializer_T *serializer_ptr, Lwm2mParser_T *parser_ptr)
References NULL, value, Lwm2mParser_getInt, RC_OK, TransportInterval, LWM2M_MUTEX_LOCK, LWM2M_MUTEX_UNLOCK, Started, LWM2MOBJECTS_IX_SENSORDEVICE_0, SENSORDEVICE_RESOURCES_INDEX, Lwm2mReporting_resourceChanged, Lwm2mSerializer_serializeInt, RC_LWM2M_METHOD_NOT_ALLOWED.
static LWM2M_MUTEX_INSTANCE(Mutex)
Retcode_T LWM2MObjectSensorDevice_Disable(void)
Disable LWM2M object instance to stop providing sensor device controls. Stops the sensors timer to frequently read and process values.
Refer interface header for description
References Started, RETCODE_OK, xTimerStop, TimerHandle, portTICK_RATE_MS, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_RTOS_QUEUE_ERROR.
Referenced by deviceRebootFunc.
void LWM2MObjectSensorDevice_Enable(void)
Enable LWM2M object instance to start providing sensor device controls. Starts sensors timer to frequently read and process values.
Refer interface header for description
References Started, xTimerStart, TimerHandle, portTICK_RATE_MS, assert.
void LWM2MObjectSensorDevice_Init(const char *mac)
Initialize LWM2M object instance. Must be called before any other function call.
Refer interface header for description
References configASSERT, portTICK_RATE_MS, Started, LWM2M_MUTEX_CREATE, SENSORS_READ_INTERVAL, TimerHandle, NULL, SensorTimer, assert, LWM2MObjectSensorDevice_Resource_S::macAddress, Lwm2mResource_S::data, Lwm2mResource_S::s.
static retcode_t PreprocessingMode(Lwm2mSerializer_T *serializer_ptr, Lwm2mParser_T *parser_ptr)
References NULL, Lwm2mParser_getString, RC_OK, CURRENT, StringDescr_compare, MAX, MIN, AVG, RC_LWM2M_BAD_REQUEST, Mode, LWM2M_MUTEX_LOCK, LWM2M_MUTEX_UNLOCK, Started, LWM2MOBJECTS_IX_SENSORDEVICE_0, SENSORDEVICE_RESOURCES_INDEX, Lwm2mReporting_resourceChanged, StringDescr_set, Lwm2mSerializer_serializeString, RC_LWM2M_METHOD_NOT_ALLOWED.
static void SensorTimer(xTimerHandle xTimer)
References BCDS_UNUSED, SensorTimerHandler, NULL.
Referenced by LWM2MObjectSensorDevice_Init.
void SensorTimerHandler(void *param1, uint32_t data)
Handler to update the timer objects.
References BCDS_UNUSED, RC_OK, LastTransportInterval, LastMode, Clock_getTimeMillis, LWM2M_MUTEX_LOCK_TIMEOUT, TransportInterval, Mode, LWM2M_MUTEX_UNLOCK, LastTransportTime, LWM2MSensorDeviceAccelerometer_Activate, LWM2MObjectSensorDevice_Resource_S::accelerometerEnabled, Lwm2mResource_S::data, Lwm2mResource_S::b, LWM2MSensorDeviceAccelerometer_Update, LWM2MSensorDeviceGyroscope_Activate, LWM2MObjectSensorDevice_Resource_S::gyroscopeEnabled, LWM2MSensorDeviceGyroscope_Update, LWM2MSensorDeviceMagnetometer_Activate, LWM2MObjectSensorDevice_Resource_S::magnetometerEnabled, LWM2MSensorDeviceMagnetometer_Update, LWM2MSensorDeviceIlluminance_Activate, LWM2MObjectSensorDevice_Resource_S::illuminanceSensorEnabled, LWM2MSensorDeviceIlluminance_Update, LWM2MSensorDeviceEnvironment_Activate, LWM2MObjectSensorDevice_Resource_S::temperatureSensorEnabled, LWM2MObjectSensorDevice_Resource_S::humiditySensorEnabled, LWM2MObjectSensorDevice_Resource_S::barometerEnabled, LWM2MSensorDeviceEnvironment_Update.
Referenced by SensorTimer.