LWM2MObjectIlluminance.h
LWM2M_OBJECTID_IPSO_ILLUMINANCE
LWM2M object id for illuminance.
typedef struct LWM2MObjectIlluminance_Resource_S LWM2MObjectIlluminance_Resource_T
LWM2MObjectIlluminance_Resource_T LWM2MObjectIlluminanceResources
LWM2M resource data for instance 0.
void LWM2MObjectIlluminance_Disable(void)
Disable LWM2M object instance to stop providing sensor data. Sets unit to "" and all other values to 0. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
Refer interface header for description
References LWM2MUtil_Schedule.
Referenced by LWM2MSensorDeviceIlluminance_Activate.
void LWM2MObjectIlluminance_Enable(float minRange, float maxRange)
Enables the LWM2M object instance to start providing sensor data. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
minRange minimum range of possible values in [mlx] maxRange maximum range of possible values in [mlx] Refer interface header for description
References LWM2MUtil_UpdatePairResources.
Referenced by LWM2MSensorDeviceIlluminance_Activate.
void LWM2MObjectIlluminance_Init(void)
Initialize LWM2M object instance. Must be called before any other function call.
Refer interface header for description
References Started, LWM2M_MUTEX_CREATE.
void LWM2MObjectIlluminance_SetValue(float currentValue)
the function set the current measured sensorValue in [mlx]
Will triggers the sending of a notification, if the value was changed. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred. currentValue current sensor value in [mlx] Refer interface header for description
References LWM2MUtil_UpdateSingleResource.
Referenced by LWM2MSensorDeviceIlluminance_Update.