LWM2MDnsUtil.h
DNS_TIMEOUT_IN_S
timeout for repeat DNS lookup. Note, the DNS lookup may take longer but it's not repeated then!
RC_DNS_BUSY
DNS lookup busy by already pending lookup
Referenced by LWM2MDnsUtil_StartResolveHostname.
RC_DNS_OK
DNS lookup OK
Referenced by LWM2MDnsTask, LWM2MDnsUtil_Init, LWM2MDnsUtil_ExtendedResolveHostname.
RC_DNS_PENDING
DNS lookup pending. Result will be reported by callback
Referenced by LWM2MDnsUtil_StartResolveHostname.
RC_MODULE_DNS
MODULE code for DNS
typedef void(* LWM2MDnsUtil_Callback_T)(retcode_t rc, const char *resolvedURL, void *context))(retcode_t rc, const char *resolvedURL, void *context)
Callback for asynchronous DNS lookup.
rc RC_OK, if DNS lookup was successful, false, otherwise. resolvedURL resolved URL, if rc is RC_OK context context provided when call Dns_StartResolveHostname or Dns_ExtendedResolveHostname
retcode_t LWM2MDnsUtil_ExtendedResolveHostname(const char *const URL, char *const resolvedURL, const size_t sizeResolvedURL, uint32_t timeout, const LWM2MDnsUtil_Callback_T callback, void *context)
Extended resolve URL. If URL uses literal host (e.g. "192.168.1.10"), the URL is just copied to provided resolvedURL buffer. Otherwise, either synchronous, if no callback is provided (NULL), or asynchronous, if callback is provided.
URL url to resolve. Format "[proto://]host[:port][/path]". resolvedURL buffer for resolved url, if URL contains literal host or callback is NULL sizeResolvedURL size of buffer for resolved url, if URL contains literal host or callback is NULL timeout retry timeout in seconds callback callback for result, if asynchronous lookup should be executed. context context for callback. RC_DNS_OK, if url was resolved successfully, RC_DNS_PENDING, when starting was successful, RC_DNS_BUSY, when asynchronous DNS lookup is already pending, and RC_PLATFORM_ERROR in case of an error.* Refer interface header for description
References RETCODE_OK, RC_DNS_OK, NULL, RC_PLATFORM_ERROR, Ip_convertStringToAddr, RC_OK, SERVAL_IP_ADDR_LEN, Clock_getTime, WlanNetworkConfig_GetIpAddress, vTaskDelay, DNS_RETRY_INTERVAL_IN_MS, portTICK_RATE_MS, Retcode_RaiseError, Ip_convertAddrToString, LWM2MDnsUtil_StartResolveHostname.
Referenced by LWM2MDnsTask, LWM2MDnsUtil_ResolveHostname.
retcode_t LWM2MDnsUtil_Init(void)
Initialize DNS module.
Must be called before any other function of this module. RC_OK, if successful, false, otherwise. Refer interface header for description
References LWM2MDnsUtilUrl, LWM2MDnsUtilResolvedURL, LWM2MDnsUtilResolvedCallback, NULL, LWM2MDnsUtilCallbackContext, LWM2MDnsUtilSemaHandle, assert, LWM2MDnsUtilMutexHandle, LWM2MDnsTask, DNS_TASK_STACK_SIZE, DNS_TASK_PRIORITY, LWM2MDnsUtilTaskHandle, RC_DNS_OK.
retcode_t LWM2MDnsUtil_ResolveHostname(const char *const URL, char *const resolvedURL, const size_t sizeResolvedURL, uint32_t timeout)
Resolve URL.
URL url to resolve resolvedURL buffer for resolved url sizeResolvedURL size of buffer for resolved url. timeout retry timeout in seconds RC_DNS_OK, if url was resolved successfully RC_PLATFORM_ERROR, if an error occurred. Refer interface header for description
References LWM2MDnsUtil_ExtendedResolveHostname, NULL.
retcode_t LWM2MDnsUtil_StartResolveHostname(const char *const URL, uint32_t timeout, const LWM2MDnsUtil_Callback_T callback, void *context)
Start asynchronous DNS lookup. Report result using the callback.
URL url to resolve timeout timeout for retries. callback callback for result context context to be passed to callback. RC_DNS_PENDING, when starting was successful, RC_DNS_BUSY, when asynchronous DNS lookup is already pending, and RC_PLATFORM_ERROR in case of an error. Refer interface header for description
References RC_DNS_BUSY, assert, NULL, RC_PLATFORM_ERROR, xSemaphoreTake, LWM2MDnsUtilMutexHandle, MUTEX_TIMEOUT, LWM2MDnsUtilResolvedCallback, LWM2MDnsUtilUrl, LWM2MDnsUtilResolvedURL, LWM2MDnsUtilCallbackContext, LWM2MDnsUtilTimeout, xSemaphoreGive, LWM2MDnsUtilSemaHandle, RC_DNS_PENDING.
Referenced by LWM2MDnsUtil_ExtendedResolveHostname.