LWM2MObjectBarometer.h
LWM2M_OBJECTID_IPSO_BAROMETER
LWM2M object id for barometer.
typedef struct LWM2MObjectBarometer_Resource_S LWM2MObjectBarometer_Resource_T
LWM2MObjectBarometer_Resource_T LWM2MObjectBarometerResources
LWM2M resource data for instance 0.
void LWM2MObjectBarometer_Disable(void)
Disable LWM2M object instance to stop providing sensor data. Sets unit to "" and all other values to 0. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
Refer interface header for description
References LWM2MUtil_Schedule.
Referenced by LWM2MSensorDeviceEnvironment_Activate.
void LWM2MObjectBarometer_Enable(float minRangeValue_hPa, float maxRangeValue_hPa)
Enable the LWM2M object instance to start providing sensor data. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
minRangeValue_hPa minimum range of possible values in [hPa] maxRangeValue_hPa maximum range of possible values in [hPa] Refer interface header for description
References LWM2MUtil_UpdatePairResources.
Referenced by LWM2MSensorDeviceEnvironment_Activate.
void LWM2MObjectBarometer_Init(void)
Initialize LWM2M object instance. Must be called before any other function call.
Refer interface header for description
References Started, MinMaxInit, LWM2M_MUTEX_CREATE.
void LWM2MObjectBarometer_SetValue(float sensorValue_hPa)
the function set the current measured sensorValue in [hPa]
Will triggers the sending of a notification, if the value was changed. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred. sensorValue_hPa current sensor value in [hPa] Refer interface header for description
References LWM2MUtil_UpdateSingleResource.
Referenced by LWM2MSensorDeviceEnvironment_Update.