LWM2MObjectHumidity.c
BCDS_MODULE_ID
FLUSH_RESOURCES
Referenced by LWM2MObjectHumidityInternalEnable, LWM2MObjectHumidityInternalDisable.
HUMIDITY_RESOURCE_INDEX
Lwm2m_Call_T AsyncCall_Disabler
Lwm2m_Pair_Resource_Update_T AsyncCall_Enabler
Lwm2m_Single_Resource_Update_T AsyncCall_Updater
Lwm2m_URI_Path_T HumidityUriPath
LWM2MObjectHumidityResource_T LWM2MObjectHumidityResources
LWM2M resource data for instance 0.
bool MinMaxInit
Referenced by LWM2MObjectHumidityInternalEnable, LWM2MObjectHumidityInternalDisable, LWM2MObjectHumidityInternalSetValue.
volatile bool started
Referenced by ResetMinMaxValues, LWM2MObjectHumidityInternalEnable, LWM2MObjectHumidityInternalDisable, LWM2MObjectHumidityInternalSetValue, LWM2MObjectHumidity_Init.
void LWM2MObjectHumidity_Disable(void)
Disable LWM2M object instance to stop providing sensor data. Sets unit to "" and all other values to 0. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
Refer interface header for description
References LWM2MUtil_Schedule.
Referenced by LWM2MSensorDeviceEnvironment_Activate.
void LWM2MObjectHumidity_Enable(float minRangeValue, float maxRangeValue)
Enables the LWM2M object instance to start providing sensor data. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
Refer interface header for description
References LWM2MUtil_UpdatePairResources.
Referenced by LWM2MSensorDeviceEnvironment_Activate.
void LWM2MObjectHumidity_Init(void)
Initialize LWM2M object instance. Must be called before any other function call.
Refer interface header for description
References started, LWM2M_MUTEX_CREATE.
void LWM2MObjectHumidity_SetValue(float sensorValue_prh)
the function set the current measured sensorValue in [%]
Refer interface header for description
References LWM2MUtil_UpdateSingleResource.
Referenced by LWM2MSensorDeviceEnvironment_Update.
static void LWM2MObjectHumidityInternalDisable(void)
References started, LWM2MObjectHumidityResource_S::units, Lwm2mResource_S::data, Lwm2mResource_S::s, LWM2MObjectHumidityResource_S::minRangeValue, Lwm2mResource_S::f, LWM2MObjectHumidityResource_S::maxRangeValue, LWM2MObjectHumidityResource_S::minMeasuredValue, LWM2MObjectHumidityResource_S::maxMeasuredValue, LWM2MObjectHumidityResource_S::sensorValue, MinMaxInit, FLUSH_RESOURCES.
static void LWM2MObjectHumidityInternalEnable(float minRangeValue, float maxRangeValue)
References started, LWM2MObjectHumidityResource_S::units, Lwm2mResource_S::data, Lwm2mResource_S::s, LWM2MObjectHumidityResource_S::minRangeValue, Lwm2mResource_S::f, LWM2MLWM2MObjectGyroscope_Resource_S::minRangeValue, LWM2MObjectHumidityResource_S::maxRangeValue, LWM2MLWM2MObjectGyroscope_Resource_S::maxRangeValue, LWM2MObjectHumidityResource_S::minMeasuredValue, LWM2MObjectHumidityResource_S::maxMeasuredValue, LWM2MObjectHumidityResource_S::sensorValue, MinMaxInit, FLUSH_RESOURCES.
static void LWM2MObjectHumidityInternalSetValue(float sensorValue_prh)
References INIT_LWM2M_DYNAMIC_CHANGES, changes, MinMaxInit, LWM2M_DYNAMIC_CHANGES_SET_FLOAT_VALUE, LWM2M_DYNAMIC_CHANGES_SET_FLOAT_MIN_VALUE, LWM2M_DYNAMIC_CHANGES_SET_FLOAT_MAX_VALUE, started, LWM2M_DYNAMIC_CHANGES_REPORT.
static retcode_t ResetMinMaxValues(Lwm2mSerializer_T *serializer_ptr, Lwm2mParser_T *parser_ptr)
References INIT_LWM2M_DYNAMIC_CHANGES, changes, LWM2M_DYNAMIC_CHANGES_SET_FLOAT_VALUE, LWM2MObjectHumidityResource_S::sensorValue, Lwm2mResource_S::data, Lwm2mResource_S::f, started, LWM2M_DYNAMIC_CHANGES_REPORT, RC_OK.