LWM2M.h
typedef void(* LWM2M_LedStateChangeHandler_T)(bool state))(bool state)
Callback handler for LED state changes. state new state of LED. true for LED on, false, for off
void LWM2M_OrangeLedSetState(bool on)
Set state of the orange LED.
Set state of the orange LED and reports that to the associated handler. LWM2M_SetOrangeLedStateChangeHandler on state of LED
Referenced by RW_Orange.
void LWM2M_Reboot(void)
Reboot the device.
When the function is called first, it reboots with a delay of 5s to have time to send a response. Though reboot is sometimes used for undetermined working devices, the delay of 5 s may not work. Therefore, a second call of this function reboots the device immediately (and without sending a response).
Referenced by deviceRebootFunc.
void LWM2M_RebootNow(const char *msg)
Reboots the device. Prints last message and wait before reboot the device, if SERVAL_LOG_LEVEL is at least SERVAL_LOG_LEVEL_ERROR.
msg message to be printed
void LWM2M_RedLedSetState(bool on)
Set state of the red LED.
Set state of the red LED and reports that to the associated handler. LWM2M_SetRedLedStateChangeHandler on state of LED
Referenced by RW_Red.
void LWM2M_SetOrangeLedStateChangeHandler(LWM2M_LedStateChangeHandler_T handler)
Set change handler for orange LED.
handler callback for LED state changes
Referenced by LWM2MObjectLightControl_Init.
void LWM2M_SetRedLedStateChangeHandler(LWM2M_LedStateChangeHandler_T handler)
Set change handler for red LED.
handler callback for LED state changes
Referenced by LWM2MObjectLightControl_Init.
void LWM2M_SetYellowLedStateChangeHandler(LWM2M_LedStateChangeHandler_T handler)
Set change handler for yellow LED.
handler callback for LED state changes
Referenced by LWM2MObjectLightControl_Init.
void LWM2M_YellowLedSetState(bool on)
Set state of the yellow LED.
Set state of the yellow LED and reports that to the associated handler. LWM2M_SetOrangeLedStateChangeHandler on state of LED
Referenced by RW_Yellow.
LWM2M_Setup_T* LWM2MGetCredentials(void)