LWM2MObjectGyroscope.c
BCDS_MODULE_ID
FLUSH_RESOURCES
Referenced by LWM2MObjectGyroscopeInternalEnable, LWM2MObjectGyroscopeInternalDisable.
GYROSCOPE_RESOURCES_INDEX
Lwm2m_Call_T AsyncCall_Disabler
Lwm2m_Pair_Resource_Update_T AsyncCall_Enabler
Lwm2m_Tripple_Resource_Update_T AsyncCall_Updater
Lwm2m_URI_Path_T GyroscopeUriPath
LWM2MLWM2MObjectGyroscope_Resource_T LWM2MObjectGyroscopeResources
LWM2M resource data for instance 0.
volatile bool Started
Referenced by LWM2MObjectGyroscopeInternalEnable, LWM2MObjectGyroscopeInternalDisable, LWM2MObjectGyroscopeInternalSetValues, LWM2MObjectGyroscope_Init.
void LWM2MObjectGyroscope_Disable()
Disable LWM2M object instance to stop providing sensor data. Sets unit to "" and all other values to 0. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
Refer interface header for description
References LWM2MUtil_Schedule.
Referenced by LWM2MSensorDeviceGyroscope_Activate.
void LWM2MObjectGyroscope_Enable(float minRangeValue, float maxRangeValue)
Enable LWM2M object instance to start providing sensor data. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
Refer interface header for description
References LWM2MUtil_UpdatePairResources.
Referenced by LWM2MSensorDeviceGyroscope_Activate.
void LWM2MObjectGyroscope_Init(void)
Initialize LWM2M object instance. Must be called before any other function call.
Refer interface header for description
References Started, LWM2M_MUTEX_CREATE.
void LWM2MObjectGyroscope_SetValues(float xValue, float yValue, float zValue)
Set values for x-, y-, and z-axis.
Refer interface header for description
References LWM2MUtil_UpdateTrippleResources.
Referenced by LWM2MSensorDeviceGyroscope_Update.
static void LWM2MObjectGyroscopeInternalDisable(void)
References Started, LWM2MLWM2MObjectGyroscope_Resource_S::minRangeValue, Lwm2mResource_S::data, Lwm2mResource_S::f, LWM2MLWM2MObjectGyroscope_Resource_S::maxRangeValue, LWM2MLWM2MObjectGyroscope_Resource_S::units, Lwm2mResource_S::s, LWM2MLWM2MObjectGyroscope_Resource_S::xValue, LWM2MLWM2MObjectGyroscope_Resource_S::yValue, LWM2MLWM2MObjectGyroscope_Resource_S::zValue, FLUSH_RESOURCES.
static void LWM2MObjectGyroscopeInternalEnable(float minRangeValue, float maxRangeValue)
References Started, LWM2MLWM2MObjectGyroscope_Resource_S::minRangeValue, Lwm2mResource_S::data, Lwm2mResource_S::f, LWM2MLWM2MObjectGyroscope_Resource_S::maxRangeValue, LWM2MLWM2MObjectGyroscope_Resource_S::units, Lwm2mResource_S::s, LWM2MLWM2MObjectGyroscope_Resource_S::xValue, LWM2MLWM2MObjectGyroscope_Resource_S::yValue, LWM2MLWM2MObjectGyroscope_Resource_S::zValue, FLUSH_RESOURCES.
static void LWM2MObjectGyroscopeInternalSetValues(float xValue, float yValue, float zValue)
References INIT_LWM2M_DYNAMIC_CHANGES, changes, LWM2M_DYNAMIC_CHANGES_SET_FLOAT_VALUE, Started, LWM2M_DYNAMIC_CHANGES_REPORT.