LWM2MObjectTemperature.c
BCDS_MODULE_ID
FLUSH_RESOURCES
Referenced by LWM2MObjectTemperatureInternalEnable, LWM2MObjectTemperatureInternalDisable.
TEMPERATURE_RESOURCE_INDEX
Lwm2m_Call_T AsyncCall_Disabler
Lwm2m_Pair_Resource_Update_T AsyncCall_Enabler
Lwm2m_Single_Resource_Update_T AsyncCall_Updater
LWM2MObjectTemperatureResource_T LWM2MObjectTemperatureResources
LWM2M resource data for instance 0.
bool MinMaxInit
Referenced by LWM2MObjectTemperatureInternalEnable, LWM2MObjectTemperatureInternalDisable, LWM2MObjectTemperatureInternalSetValue.
volatile bool Started
Referenced by ResetMinMaxValues, LWM2MObjectTemperatureInternalEnable, LWM2MObjectTemperatureInternalDisable, LWM2MObjectTemperatureInternalSetValue, LWM2MObjectTemperature_Init.
Lwm2m_URI_Path_T TemperatureUriPath
void LWM2MObjectTemperature_Disable(void)
Disable the LWM2M object instance to stop providing sensor data. Sets unit to "" and all other values to 0. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
Refer interface header for description
References LWM2MUtil_Schedule.
Referenced by LWM2MSensorDeviceEnvironment_Activate.
void LWM2MObjectTemperature_Enable(float minRangeValue_C, float maxRangeValue_C)
Enable the LWM2M object instance to start providing sensor data. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
Refer interface header for description
References LWM2MUtil_UpdatePairResources.
Referenced by LWM2MSensorDeviceEnvironment_Activate.
void LWM2MObjectTemperature_Init(void)
Initialize LWM2M object instance. Must be called before any other function call.
Refer interface header for description
References Started, LWM2M_MUTEX_CREATE.
void LWM2MObjectTemperature_SetValue(float sensorValue_C)
the function set the current measured sensorValue in [Cel]
Refer interface header for description
References LWM2MUtil_UpdateSingleResource.
Referenced by LWM2MSensorDeviceEnvironment_Update.
static void LWM2MObjectTemperatureInternalDisable(void)
References Started, LWM2MObjectTemperatureResource_S::units, Lwm2mResource_S::data, Lwm2mResource_S::s, LWM2MObjectTemperatureResource_S::minRangeValue, Lwm2mResource_S::f, LWM2MObjectTemperatureResource_S::maxRangeValue, LWM2MObjectTemperatureResource_S::minMeasuredValue, LWM2MObjectTemperatureResource_S::maxMeasuredValue, LWM2MObjectTemperatureResource_S::sensorValue, MinMaxInit, FLUSH_RESOURCES.
static void LWM2MObjectTemperatureInternalEnable(float minRangeValue_C, float maxRangeValue_C)
References Started, LWM2MObjectTemperatureResource_S::units, Lwm2mResource_S::data, Lwm2mResource_S::s, LWM2MObjectTemperatureResource_S::minRangeValue, Lwm2mResource_S::f, LWM2MObjectTemperatureResource_S::maxRangeValue, LWM2MObjectTemperatureResource_S::minMeasuredValue, LWM2MObjectTemperatureResource_S::maxMeasuredValue, LWM2MObjectTemperatureResource_S::sensorValue, MinMaxInit, FLUSH_RESOURCES.
static void LWM2MObjectTemperatureInternalSetValue(float sensorValue_C)
References INIT_LWM2M_DYNAMIC_CHANGES, changes, MinMaxInit, LWM2M_DYNAMIC_CHANGES_SET_FLOAT_VALUE, LWM2M_DYNAMIC_CHANGES_SET_FLOAT_MIN_VALUE, LWM2M_DYNAMIC_CHANGES_SET_FLOAT_MAX_VALUE, Started, LWM2M_DYNAMIC_CHANGES_REPORT.
static retcode_t ResetMinMaxValues(Lwm2mSerializer_T *serializer_ptr, Lwm2mParser_T *parser_ptr)
References INIT_LWM2M_DYNAMIC_CHANGES, changes, LWM2M_DYNAMIC_CHANGES_SET_FLOAT_VALUE, LWM2MObjectTemperatureResource_S::sensorValue, Lwm2mResource_S::data, Lwm2mResource_S::f, Started, LWM2M_DYNAMIC_CHANGES_REPORT, RC_OK.