LWM2MObjectHumidity.h
LWM2M_OBJECTID_IPSO_HUMIDITY
LWM2M object id for humidity.
typedef struct LWM2MObjectHumidityResource_S LWM2MObjectHumidityResource_T
LWM2MObjectHumidityResource_T LWM2MObjectHumidityResources
LWM2M resource data for instance 0.
void LWM2MObjectHumidity_Disable(void)
Disable LWM2M object instance to stop providing sensor data. Sets unit to "" and all other values to 0. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
Refer interface header for description
References LWM2MUtil_Schedule.
Referenced by LWM2MSensorDeviceEnvironment_Activate.
void LWM2MObjectHumidity_Enable(float minRangeValue, float maxRangeValue)
Enables the LWM2M object instance to start providing sensor data. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
minRangeValue minimum range of possible values in [%] maxRangeValue maximum range of possible values in [%] Refer interface header for description
References LWM2MUtil_UpdatePairResources.
Referenced by LWM2MSensorDeviceEnvironment_Activate.
void LWM2MObjectHumidity_Init(void)
Initialize LWM2M object instance. Must be called before any other function call.
Refer interface header for description
References started, LWM2M_MUTEX_CREATE.
void LWM2MObjectHumidity_SetValue(float sensorValue_prH)
the function set the current measured sensorValue in [%]
Will triggers the sending of a notification, if the value was changed. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred. sensorValue_prH current sensor value in [%] Refer interface header for description
References LWM2MUtil_UpdateSingleResource.
Referenced by LWM2MSensorDeviceEnvironment_Update.