LWM2MObjectIlluminance.c
BCDS_MODULE_ID
FLUSH_RESOURCES
Referenced by LWM2MObjectIlluminanceInternalEnable, LWM2MObjectIlluminanceInternalDisable.
ILLUMINANCE_RESOURCES_INDEX
Lwm2m_Call_T AsyncCall_Disabler
Lwm2m_Pair_Resource_Update_T AsyncCall_Enabler
Lwm2m_Single_Resource_Update_T AsyncCall_Updater
Lwm2m_URI_Path_T IlluminanceUriPath
LWM2MObjectIlluminance_Resource_T LWM2MObjectIlluminanceResources
LWM2M resource data for instance 0.
bool MinMaxInit
Referenced by LWM2MObjectIlluminanceInternalEnable, LWM2MObjectIlluminanceInternalDisable, LWM2MObjectIlluminanceInternalSetValue.
volatile bool Started
Referenced by ResetMinMax, LWM2MObjectIlluminanceInternalEnable, LWM2MObjectIlluminanceInternalDisable, LWM2MObjectIlluminanceInternalSetValue, LWM2MObjectIlluminance_Init.
void LWM2MObjectIlluminance_Disable(void)
Disable LWM2M object instance to stop providing sensor data. Sets unit to "" and all other values to 0. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
Refer interface header for description
References LWM2MUtil_Schedule.
Referenced by LWM2MSensorDeviceIlluminance_Activate.
void LWM2MObjectIlluminance_Enable(float minRange, float maxRange)
Enables the LWM2M object instance to start providing sensor data. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
Refer interface header for description
References LWM2MUtil_UpdatePairResources.
Referenced by LWM2MSensorDeviceIlluminance_Activate.
void LWM2MObjectIlluminance_Init(void)
Initialize LWM2M object instance. Must be called before any other function call.
Refer interface header for description
References Started, LWM2M_MUTEX_CREATE.
void LWM2MObjectIlluminance_SetValue(float currentValue)
the function set the current measured sensorValue in [mlx]
Refer interface header for description
References LWM2MUtil_UpdateSingleResource.
Referenced by LWM2MSensorDeviceIlluminance_Update.
static void LWM2MObjectIlluminanceInternalDisable(void)
References Started, LWM2MObjectIlluminance_Resource_S::minValue, Lwm2mResource_S::data, Lwm2mResource_S::f, LWM2MObjectIlluminance_Resource_S::maxValue, LWM2MObjectIlluminance_Resource_S::minRangeValue, LWM2MObjectIlluminance_Resource_S::maxRangeValue, LWM2MObjectIlluminance_Resource_S::value, LWM2MObjectIlluminance_Resource_S::units, Lwm2mResource_S::s, MinMaxInit, FLUSH_RESOURCES.
static void LWM2MObjectIlluminanceInternalEnable(float minRange, float maxRange)
References Started, LWM2MObjectIlluminance_Resource_S::minValue, Lwm2mResource_S::data, Lwm2mResource_S::f, LWM2MObjectIlluminance_Resource_S::maxValue, LWM2MObjectIlluminance_Resource_S::minRangeValue, LWM2MObjectIlluminance_Resource_S::maxRangeValue, LWM2MObjectIlluminance_Resource_S::value, LWM2MObjectIlluminance_Resource_S::units, Lwm2mResource_S::s, MinMaxInit, FLUSH_RESOURCES.
static void LWM2MObjectIlluminanceInternalSetValue(float currentValue)
References INIT_LWM2M_DYNAMIC_CHANGES, changes, MinMaxInit, LWM2M_DYNAMIC_CHANGES_SET_FLOAT_VALUE, value, LWM2M_DYNAMIC_CHANGES_SET_FLOAT_MIN_VALUE, LWM2M_DYNAMIC_CHANGES_SET_FLOAT_MAX_VALUE, Started, LWM2M_DYNAMIC_CHANGES_REPORT.
static retcode_t ResetMinMax(Lwm2mSerializer_T *serializer_ptr, Lwm2mParser_T *parser_ptr)
References INIT_LWM2M_DYNAMIC_CHANGES, changes, LWM2M_DYNAMIC_CHANGES_SET_FLOAT_VALUE, LWM2MObjectIlluminance_Resource_S::value, Lwm2mResource_S::data, Lwm2mResource_S::f, Started, LWM2M_DYNAMIC_CHANGES_REPORT, RC_OK.