LWM2MSensorDeviceUtil.h
SENSORDEVICE_MAX_VALUES
Definition of maxiumum values processed per sensor.
ProcessingMode
use current value
typedef enum ProcessingMode ProcessingMode_T
typedef struct SensorDeviceProcessDataFloat SensorDeviceProcessDataFloat_T
Processed sensor values.
typedef struct SensorDeviceSampleDataFloat SensorDeviceSampleDataFloat_T
Sensor values for processing.
Used to pass values from sensors to processing functions.
bool LWM2MSensorDeviceUtil_GetDataFloat(SensorDeviceProcessDataFloat_T *data, SensorDeviceSampleDataFloat_T *sample)
get processed sensor values.
Get the processed sensor values and reset the processing. data processed sensor values sample read values true-if values are valid false, otherwise Refer interface header for description
References SensorDeviceProcessDataFloat::enabled, SensorDeviceProcessDataFloat::sample_counter, SensorDeviceProcessDataFloat::mode, MAX, MIN, CURRENT, SensorDeviceProcessDataFloat::value_counter, SensorDeviceSampleDataFloat::values, SensorDeviceProcessDataFloat::data, AVG, LWM2MSensorDeviceUtil_ResetProcessDataFloat.
Referenced by LWM2MSensorDeviceAccelerometer_Update, LWM2MSensorDeviceEnvironment_Update, LWM2MSensorDeviceGyroscope_Update, LWM2MSensorDeviceIlluminance_Update, LWM2MSensorDeviceMagnetometer_Update.
void LWM2MSensorDeviceUtil_ProcessDataFloat(ProcessingMode_T mode, SensorDeviceProcessDataFloat_T *data, SensorDeviceSampleDataFloat_T *sample)
process current sensor values.
Process current sensor values according process mode and store the result in the processed sensor values. Adjust processed value for minimum, maximum or current mode, add values for avarage mode. mode process mode data processed sensor values sample current sensor values Refer interface header for description
References SensorDeviceProcessDataFloat::enabled, SensorDeviceProcessDataFloat::mode, LWM2MSensorDeviceUtil_ResetProcessDataFloat, SensorDeviceProcessDataFloat::sample_counter, MAX, MIN, CURRENT, SensorDeviceProcessDataFloat::value_counter, SensorDeviceProcessDataFloat::data, SensorDeviceSampleDataFloat::values, AVG.
Referenced by LWM2MSensorDeviceAccelerometer_Update, LWM2MSensorDeviceEnvironment_Update, LWM2MSensorDeviceGyroscope_Update, LWM2MSensorDeviceIlluminance_Update, LWM2MSensorDeviceMagnetometer_Update.
void LWM2MSensorDeviceUtil_ResetProcessDataFloat(SensorDeviceProcessDataFloat_T *data)
reset processed sensor values.
Reset minimum, maximum and avarage value by reseting the sample_counter to 0. data processed sensor values Refer interface header for description
References SensorDeviceProcessDataFloat::value_counter, SensorDeviceProcessDataFloat::data, SensorDeviceSampleDataFloat::values, SensorDeviceProcessDataFloat::sample_counter.
Referenced by LWM2MSensorDeviceAccelerometer_Activate, LWM2MSensorDeviceEnvironment_Activate, LWM2MSensorDeviceGyroscope_Activate, LWM2MSensorDeviceIlluminance_Activate, LWM2MSensorDeviceMagnetometer_Activate, LWM2MSensorDeviceUtil_ProcessDataFloat, LWM2MSensorDeviceUtil_GetDataFloat.