LWM2MObjectMagnetometer.c
BCDS_MODULE_ID
FLUSH_RESOURCES
Referenced by LWM2MObjectMagnetometerInternalEnable, LWM2MObjectMagnetometerInternalDisable.
M_PI
Referenced by CalculateDirection.
MAGNETOMETER_RESOURCES_INDEX
Lwm2m_Call_T AsyncCall_Disabler
Lwm2m_Pair_Resource_Update_T AsyncCall_Enabler
Lwm2m_Tripple_Resource_Update_T AsyncCall_Updater
LWM2MObjectMagnetometer_Resource_T LWM2MObjectMagnetometerResources
LWM2M resource data for instance 0.
Lwm2m_URI_Path_T MagnetometerUriPath
volatile bool Started
Referenced by LWM2MObjectMagnetometerInternalEnable, LWM2MObjectMagnetometerInternalDisable, LWM2MObjectMagnetometerInternalSetValues, LWM2MObjectMagnetometer_Init.
static float CalculateDirection(float xValue, float yValue)
References MAGNETOMETER_DECLANATIONANGLE, M_PI.
Referenced by LWM2MObjectMagnetometerInternalEnable, LWM2MObjectMagnetometerInternalSetValues.
void LWM2MObjectMagnetometer_Disable(void)
Disable LWM2M object instance to stop providing sensor data. Sets unit to "" and all other values to 0. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
Refer interface header for description
References LWM2MUtil_Schedule.
Referenced by LWM2MSensorDeviceMagnetometer_Activate.
void LWM2MObjectMagnetometer_Enable(float minRangeValue, float maxRangeValue)
Enable LWM2M object instance to start providing sensor data. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
Refer interface header for description
References LWM2MUtil_UpdatePairResources.
Referenced by LWM2MSensorDeviceMagnetometer_Activate.
void LWM2MObjectMagnetometer_Init(void)
Initialize LWM2M object instance. Must be called before any other function call.
Refer interface header for description
References Started, LWM2M_MUTEX_CREATE.
void LWM2MObjectMagnetometer_SetValues(float xValue, float yValue, float zValue)
Set values for x-, y-, and z-axis.
Refer interface header for description
References LWM2MUtil_UpdateTrippleResources.
Referenced by LWM2MSensorDeviceMagnetometer_Update.
static void LWM2MObjectMagnetometerInternalDisable(void)
References Started, LWM2MObjectMagnetometer_Resource_S::minRangeValue, Lwm2mResource_S::data, Lwm2mResource_S::f, LWM2MObjectMagnetometer_Resource_S::maxRangeValue, LWM2MObjectMagnetometer_Resource_S::units, Lwm2mResource_S::s, LWM2MObjectMagnetometer_Resource_S::xValue, LWM2MObjectMagnetometer_Resource_S::yValue, LWM2MObjectMagnetometer_Resource_S::zValue, LWM2MObjectMagnetometer_Resource_S::direction, FLUSH_RESOURCES.
static void LWM2MObjectMagnetometerInternalEnable(float minRangeValue, float maxRangeValue)
References Started, LWM2MObjectMagnetometer_Resource_S::minRangeValue, Lwm2mResource_S::data, Lwm2mResource_S::f, LWM2MObjectMagnetometer_Resource_S::maxRangeValue, LWM2MObjectMagnetometer_Resource_S::units, Lwm2mResource_S::s, LWM2MObjectMagnetometer_Resource_S::xValue, LWM2MObjectMagnetometer_Resource_S::yValue, LWM2MObjectMagnetometer_Resource_S::zValue, LWM2MObjectMagnetometer_Resource_S::direction, CalculateDirection, FLUSH_RESOURCES.
static void LWM2MObjectMagnetometerInternalSetValues(float xValue, float yValue, float zValue)
References INIT_LWM2M_DYNAMIC_CHANGES, changes, LWM2M_DYNAMIC_CHANGES_SET_FLOAT_VALUE, CalculateDirection, Started, LWM2M_DYNAMIC_CHANGES_REPORT.