LWM2MObjectLightControl.c
BCDS_MODULE_ID
LIGHTCONTROL_RESOURCES_INDEX
Referenced by NotifyRed, NotifyOrange, NotifyYellow.
volatile bool LedTestMode
Referenced by LightControl, LWM2MObjectLightControl_Enable.
LWM2MObjectLightControl_Resource_T LightOrangeResources
LWM2M resource data for instance 1.
LWM2MObjectLightControl_Resource_T LightRedResources
LWM2M resource data for instance 0.
LWM2MObjectLightControl_Resource_T LightYellowResources
LWM2M resource data for instance 2.
volatile bool Orange
Referenced by NotifyOrange, LightControl, RW_Orange.
volatile bool Red
Referenced by NotifyRed, LightControl, RW_Red.
volatile bool Started
Referenced by NotifyRed, NotifyOrange, NotifyYellow, LWM2MObjectLightControl_Init, LWM2MObjectLightControl_Enable.
volatile bool Yellow
Referenced by NotifyYellow, LightControl, RW_Yellow.
static bool AdjustState(volatile bool *current, bool state)
References LWM2M_MUTEX_LOCK, LWM2M_MUTEX_UNLOCK.
Referenced by NotifyRed, NotifyOrange, NotifyYellow.
static retcode_t LightControl(Lwm2mSerializer_T *serializer_ptr, Lwm2mParser_T *parser_ptr, volatile bool *state, void(*handler)(bool state))
References RC_LWM2M_METHOD_NOT_ALLOWED, NULL, value, Lwm2mParser_getBool, RC_OK, Red, Orange, Yellow, LedTestMode, Lwm2mSerializer_serializeBool.
Referenced by RW_Red, RW_Orange, RW_Yellow.
static LWM2M_MUTEX_INSTANCE(mutex)
void LWM2MObjectLightControl_Enable(bool testMode)
Enable LWM2M object instances to start providing light controls.
Refer interface header for description
References LedTestMode, Started.
void LWM2MObjectLightControl_Init(void)
Initialize LWM2M object instances. Must be called before any other function call.
Refer interface header for description
References Started, LWM2M_MUTEX_CREATE, LWM2M_SetRedLedStateChangeHandler, NotifyRed, LWM2M_SetOrangeLedStateChangeHandler, NotifyOrange, LWM2M_SetYellowLedStateChangeHandler, NotifyYellow.
static void NotifyOrange(bool state)
References AdjustState, Orange, Started, LWM2MOBJECTS_IX_LIGHTCONTROL_0, LWM2MOBJECTS_IX_LIGHTCONTROL_1, LIGHTCONTROL_RESOURCES_INDEX, Lwm2mReporting_resourceChanged.
Referenced by LWM2MObjectLightControl_Init.
static void NotifyRed(bool state)
References AdjustState, Red, Started, LWM2MOBJECTS_IX_LIGHTCONTROL_0, LIGHTCONTROL_RESOURCES_INDEX, Lwm2mReporting_resourceChanged.
Referenced by LWM2MObjectLightControl_Init.
static void NotifyYellow(bool state)
References AdjustState, Yellow, Started, LWM2MOBJECTS_IX_LIGHTCONTROL_0, LWM2MOBJECTS_IX_LIGHTCONTROL_2, LIGHTCONTROL_RESOURCES_INDEX, Lwm2mReporting_resourceChanged.
Referenced by LWM2MObjectLightControl_Init.
static retcode_t RW_Orange(Lwm2mSerializer_T *serializer_ptr, Lwm2mParser_T *parser_ptr)
References LightControl, Orange, LWM2M_OrangeLedSetState.
static retcode_t RW_Red(Lwm2mSerializer_T *serializer_ptr, Lwm2mParser_T *parser_ptr)
References LightControl, Red, LWM2M_RedLedSetState.
static retcode_t RW_Yellow(Lwm2mSerializer_T *serializer_ptr, Lwm2mParser_T *parser_ptr)
References LightControl, Yellow, LWM2M_YellowLedSetState.