LWM2MObjectMagnetometer.h
LWM2M_OBJECTID_IPSO_MAGNETOMETER
LWM2M object id for magnetometer.
MAGNETOMETER_DECLANATIONANGLE
magnetic declanation angle for Waiblingen
Referenced by CalculateDirection.
typedef struct LWM2MObjectMagnetometer_Resource_S LWM2MObjectMagnetometer_Resource_T
LWM2MObjectMagnetometer_Resource_T LWM2MObjectMagnetometerResources
LWM2M resource data for instance 0.
void LWM2MObjectMagnetometer_Disable(void)
Disable LWM2M object instance to stop providing sensor data. Sets unit to "" and all other values to 0. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
Refer interface header for description
References LWM2MUtil_Schedule.
Referenced by LWM2MSensorDeviceMagnetometer_Activate.
void LWM2MObjectMagnetometer_Enable(float minRangeValue, float maxRangeValue)
Enable LWM2M object instance to start providing sensor data. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
minRangeValue minimum range of value in [uT]. maxRangeValue maximum range of value in [uT]. Refer interface header for description
References LWM2MUtil_UpdatePairResources.
Referenced by LWM2MSensorDeviceMagnetometer_Activate.
void LWM2MObjectMagnetometer_Init(void)
Initialize LWM2M object instance. Must be called before any other function call.
Refer interface header for description
References Started, LWM2M_MUTEX_CREATE.
void LWM2MObjectMagnetometer_SetValues(float x, float y, float z)
Set values for x-, y-, and z-axis.
Set values for axis, units in [uT]. Will triggers the sending of a notification, if a values was changed. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred. x value of x-axis in [uT] y value of y-axis in [uT] z value of z-axis in [uT] Refer interface header for description
References LWM2MUtil_UpdateTrippleResources.
Referenced by LWM2MSensorDeviceMagnetometer_Update.