LWM2MSensorDeviceUtil.c
BCDS_MODULE_ID
bool LWM2MSensorDeviceUtil_GetDataFloat(SensorDeviceProcessDataFloat_T *data, SensorDeviceSampleDataFloat_T *sample)
get processed sensor values.
Refer interface header for description
References SensorDeviceProcessDataFloat::enabled, SensorDeviceProcessDataFloat::sample_counter, SensorDeviceProcessDataFloat::mode, MAX, MIN, CURRENT, SensorDeviceProcessDataFloat::value_counter, SensorDeviceSampleDataFloat::values, SensorDeviceProcessDataFloat::data, AVG, LWM2MSensorDeviceUtil_ResetProcessDataFloat.
Referenced by LWM2MSensorDeviceAccelerometer_Update, LWM2MSensorDeviceEnvironment_Update, LWM2MSensorDeviceGyroscope_Update, LWM2MSensorDeviceIlluminance_Update, LWM2MSensorDeviceMagnetometer_Update.
void LWM2MSensorDeviceUtil_ProcessDataFloat(ProcessingMode_T mode, SensorDeviceProcessDataFloat_T *data, SensorDeviceSampleDataFloat_T *sample)
process current sensor values.
Refer interface header for description
References SensorDeviceProcessDataFloat::enabled, SensorDeviceProcessDataFloat::mode, LWM2MSensorDeviceUtil_ResetProcessDataFloat, SensorDeviceProcessDataFloat::sample_counter, MAX, MIN, CURRENT, SensorDeviceProcessDataFloat::value_counter, SensorDeviceProcessDataFloat::data, SensorDeviceSampleDataFloat::values, AVG.
Referenced by LWM2MSensorDeviceAccelerometer_Update, LWM2MSensorDeviceEnvironment_Update, LWM2MSensorDeviceGyroscope_Update, LWM2MSensorDeviceIlluminance_Update, LWM2MSensorDeviceMagnetometer_Update.
void LWM2MSensorDeviceUtil_ResetProcessDataFloat(SensorDeviceProcessDataFloat_T *data)
reset processed sensor values.
Refer interface header for description
References SensorDeviceProcessDataFloat::value_counter, SensorDeviceProcessDataFloat::data, SensorDeviceSampleDataFloat::values, SensorDeviceProcessDataFloat::sample_counter.
Referenced by LWM2MSensorDeviceAccelerometer_Activate, LWM2MSensorDeviceEnvironment_Activate, LWM2MSensorDeviceGyroscope_Activate, LWM2MSensorDeviceIlluminance_Activate, LWM2MSensorDeviceMagnetometer_Activate, LWM2MSensorDeviceUtil_ProcessDataFloat, LWM2MSensorDeviceUtil_GetDataFloat.