LWM2MObjectTemperature.h
LWM2M_OBJECTID_IPSO_TEMPERATURE
LWM2M object id for temperature.
typedef struct LWM2MObjectTemperatureResource_S LWM2MObjectTemperatureResource_T
LWM2MObjectTemperatureResource_T LWM2MObjectTemperatureResources
LWM2M resource data for instance 0.
void LWM2MObjectTemperature_Disable(void)
Disable the LWM2M object instance to stop providing sensor data. Sets unit to "" and all other values to 0. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
Refer interface header for description
References LWM2MUtil_Schedule.
Referenced by LWM2MSensorDeviceEnvironment_Activate.
void LWM2MObjectTemperature_Enable(float minRangeValue_C, float maxRangeValue_C)
Enable the LWM2M object instance to start providing sensor data. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
minRangeValue_C minimum range of possible values in [Cel] maxRangeValue_C maximum range of possible values in [Cel] Refer interface header for description
References LWM2MUtil_UpdatePairResources.
Referenced by LWM2MSensorDeviceEnvironment_Activate.
void LWM2MObjectTemperature_Init(void)
Initialize LWM2M object instance. Must be called before any other function call.
Refer interface header for description
References Started, LWM2M_MUTEX_CREATE.
void LWM2MObjectTemperature_SetValue(float sensorValue_C)
the function set the current measured sensorValue in [Cel]
Will triggers the sending of a notification, if the value was changed. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred. sensorValue_C current sensor value in [Cel] Refer interface header for description
References LWM2MUtil_UpdateSingleResource.
Referenced by LWM2MSensorDeviceEnvironment_Update.