LWM2MObjectBarometer.c
BAROMETER_RESOURCE_INDEX
BCDS_MODULE_ID
FLUSH_RESOURCES
Referenced by LWM2MObjectBarometerInternalEnable, LWM2MObjectBarometerInternalDisable.
Lwm2m_Call_T AsyncCall_Disabler
Lwm2m_Pair_Resource_Update_T AsyncCall_Enabler
Lwm2m_Single_Resource_Update_T AsyncCall_Updater
Lwm2m_URI_Path_T BarometerUriPath
LWM2MObjectBarometer_Resource_T LWM2MObjectBarometerResources
LWM2M resource data for instance 0.
bool MinMaxInit
Referenced by LWM2MObjectBarometerInternalEnable, LWM2MObjectBarometerInternalDisable, LWM2MObjectBarometerInternalSetValue, LWM2MObjectBarometer_Init.
volatile bool Started
Referenced by LWM2MObjectBarometerInternalEnable, LWM2MObjectBarometerInternalDisable, LWM2MObjectBarometerInternalSetValue, LWM2MObjectBarometer_Init.
void LWM2MObjectBarometer_Disable(void)
Disable LWM2M object instance to stop providing sensor data. Sets unit to "" and all other values to 0. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
Refer interface header for description
References LWM2MUtil_Schedule.
Referenced by LWM2MSensorDeviceEnvironment_Activate.
void LWM2MObjectBarometer_Enable(float minRangeValue, float maxRangeValue)
Enable the LWM2M object instance to start providing sensor data. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
Refer interface header for description
References LWM2MUtil_UpdatePairResources.
Referenced by LWM2MSensorDeviceEnvironment_Activate.
void LWM2MObjectBarometer_Init(void)
Initialize LWM2M object instance. Must be called before any other function call.
Refer interface header for description
References Started, MinMaxInit, LWM2M_MUTEX_CREATE.
void LWM2MObjectBarometer_SetValue(float sensorValue_hPa)
the function set the current measured sensorValue in [hPa]
Refer interface header for description
References LWM2MUtil_UpdateSingleResource.
Referenced by LWM2MSensorDeviceEnvironment_Update.
static void LWM2MObjectBarometerInternalDisable(void)
References Started, LWM2MObjectBarometer_Resource_S::units, Lwm2mResource_S::data, Lwm2mResource_S::s, LWM2MObjectBarometer_Resource_S::minRangeValue, Lwm2mResource_S::f, LWM2MObjectBarometer_Resource_S::maxRangeValue, LWM2MObjectBarometer_Resource_S::minMeasuredValue, LWM2MObjectBarometer_Resource_S::maxMeasuredValue, LWM2MObjectBarometer_Resource_S::sensorValue, MinMaxInit, FLUSH_RESOURCES.
static void LWM2MObjectBarometerInternalEnable(float minRangeValue, float maxRangeValue)
References Started, LWM2MObjectBarometer_Resource_S::units, Lwm2mResource_S::data, Lwm2mResource_S::s, LWM2MObjectBarometer_Resource_S::minRangeValue, Lwm2mResource_S::f, LWM2MObjectBarometer_Resource_S::maxRangeValue, LWM2MObjectBarometer_Resource_S::minMeasuredValue, LWM2MObjectBarometer_Resource_S::maxMeasuredValue, LWM2MObjectBarometer_Resource_S::sensorValue, MinMaxInit, FLUSH_RESOURCES.
static void LWM2MObjectBarometerInternalSetValue(float sensorValue_hPa)
References INIT_LWM2M_DYNAMIC_CHANGES, changes, MinMaxInit, LWM2M_DYNAMIC_CHANGES_SET_FLOAT_VALUE, LWM2M_DYNAMIC_CHANGES_SET_FLOAT_MIN_VALUE, LWM2M_DYNAMIC_CHANGES_SET_FLOAT_MAX_VALUE, Started, LWM2M_DYNAMIC_CHANGES_REPORT.
static retcode_t LWM2MObjectBarometerResetMinMaxValues(Lwm2mSerializer_T *serializer_ptr, Lwm2mParser_T *parser_ptr)
References INIT_LWM2M_DYNAMIC_CHANGES, changes, LWM2M_DYNAMIC_CHANGES_SET_FLOAT_VALUE, LWM2MObjectBarometer_Resource_S::sensorValue, Lwm2mResource_S::data, Lwm2mResource_S::f, LWM2M_DYNAMIC_CHANGES_REPORT, RC_OK.