LWM2MObjectAccelerometer.c
ACCELEROMETER_RESOURCES_INDEX
BCDS_MODULE_ID
FLUSH_RESOURCES
Referenced by LWM2MObjectAccelerometerInternalEnable, LWM2MObjectAccelerometerInternalDisable.
Lwm2m_URI_Path_T AccelerometerUriPath
Lwm2m_Call_T AsyncCall_Disabler
Lwm2m_Pair_Resource_Update_T AsyncCall_Enabler
Lwm2m_Tripple_Resource_Update_T AsyncCall_Updater
LWM2MObjectAccelerometer_Resource_T LWM2MObjectAccelerometerResources
LWM2M resource data for instance 0.
volatile bool Started
Referenced by LWM2MObjectAccelerometerInternalEnable, LWM2MObjectAccelerometerInternalDisable, LWM2MObjectAccelerometerInternalSetValues, LWM2MObjectAccelerometer_Init.
void LWM2MObjectAccelerometer_Disable(void)
Disable LWM2M object instance to stop providing sensor data. Sets unit to "" and all other values to 0. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
Refer interface header for description
References LWM2MUtil_Schedule.
Referenced by LWM2MSensorDeviceAccelerometer_Activate.
void LWM2MObjectAccelerometer_Enable(float minRange, float maxRange)
Enable LWM2M object instance to start providing sensor data. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
Refer interface header for description
References LWM2MUtil_UpdatePairResources.
Referenced by LWM2MSensorDeviceAccelerometer_Activate.
void LWM2MObjectAccelerometer_Init(void)
Initialize LWM2M object instance. Must be called before any other function call.
Refer interface header for description
References Started, LWM2M_MUTEX_CREATE.
void LWM2MObjectAccelerometer_SetValues(float xAxis, float yAxis, float zAxis)
Set values for x-, y-, and z-axis.
Refer interface header for description
References LWM2MUtil_UpdateTrippleResources.
Referenced by LWM2MSensorDeviceAccelerometer_Update.
static void LWM2MObjectAccelerometerInternalDisable(void)
References Started, LWM2MObjectAccelerometer_Resource_S::units, Lwm2mResource_S::data, Lwm2mResource_S::s, LWM2MObjectAccelerometer_Resource_S::minRange, Lwm2mResource_S::f, LWM2MObjectAccelerometer_Resource_S::maxRange, LWM2MObjectAccelerometer_Resource_S::xAxis, LWM2MObjectAccelerometer_Resource_S::yAxis, LWM2MObjectAccelerometer_Resource_S::zAxis, FLUSH_RESOURCES.
static void LWM2MObjectAccelerometerInternalEnable(float minRange, float maxRange)
References Started, LWM2MObjectAccelerometer_Resource_S::units, Lwm2mResource_S::data, Lwm2mResource_S::s, LWM2MObjectAccelerometer_Resource_S::minRange, Lwm2mResource_S::f, LWM2MObjectAccelerometer_Resource_S::maxRange, LWM2MObjectAccelerometer_Resource_S::xAxis, LWM2MObjectAccelerometer_Resource_S::yAxis, LWM2MObjectAccelerometer_Resource_S::zAxis, FLUSH_RESOURCES.
static void LWM2MObjectAccelerometerInternalSetValues(float xAxis, float yAxis, float zAxis)
References INIT_LWM2M_DYNAMIC_CHANGES, changes, LWM2M_DYNAMIC_CHANGES_SET_FLOAT_VALUE, Started, LWM2M_DYNAMIC_CHANGES_REPORT.