LWM2MUtil.h
INIT_LWM2M_DYNAMIC_CHANGES
Initialize dynamic changes data.
C local name of changes
Referenced by LWM2MObjectAccelerometerInternalSetValues, LWM2MObjectBarometerResetMinMaxValues, LWM2MObjectBarometerInternalSetValue, LWM2MObjectGyroscopeInternalSetValues, ResetMinMaxValues, LWM2MObjectHumidityInternalSetValue, ResetMinMax, LWM2MObjectIlluminanceInternalSetValue, LWM2MObjectMagnetometerInternalSetValues, LWM2MObjectTemperatureInternalSetValue.
LWM2M_DYNAMIC_CHANGES_REPORT
Report changes from dynamic changes data.
C dynamic changes data U uri path to changed instance LWM2MUtil_ReportChanges
Referenced by LWM2MObjectAccelerometerInternalSetValues, LWM2MObjectBarometerResetMinMaxValues, LWM2MObjectBarometerInternalSetValue, LWM2MObjectGyroscopeInternalSetValues, ResetMinMaxValues, LWM2MObjectHumidityInternalSetValue, ResetMinMax, LWM2MObjectIlluminanceInternalSetValue, LWM2MObjectMagnetometerInternalSetValues, LWM2MObjectTemperatureInternalSetValue.
LWM2M_DYNAMIC_CHANGES_SET_FLOAT_MAX_VALUE
set new float resource value, if its larger then the current value.
Check, if the new value is larger then the current resource value. If so, change the resource value and store the resource index in the dynamic changes data. C dynamic changes data T resource table the resource belongs to R resource of the resource table V new value true, if resource value was changed, false, otherwise LWM2MUtil_SetFloatMaxValue
Referenced by LWM2MObjectBarometerInternalSetValue, LWM2MObjectHumidityInternalSetValue, LWM2MObjectIlluminanceInternalSetValue, LWM2MObjectTemperatureInternalSetValue.
LWM2M_DYNAMIC_CHANGES_SET_FLOAT_MIN_VALUE
set new float resource value, if its less then the current value.
Check, if the new value is less then the current resource value. If so, change the resource value and store the resource index in the dynamic changes data. C dynamic changes data T resource table the resource belongs to R resource of the resource table V new value true, if resource value was changed, false, otherwise LWM2MUtil_SetFloatMinValue
Referenced by LWM2MObjectBarometerInternalSetValue, LWM2MObjectHumidityInternalSetValue, LWM2MObjectIlluminanceInternalSetValue, LWM2MObjectTemperatureInternalSetValue.
LWM2M_DYNAMIC_CHANGES_SET_FLOAT_VALUE
set new float resource value.
Check, if the new value changes the resource value. If changed, store the resource index in the dynamic changes data. C dynamic changes data T resource table the resource belongs to R resource of the resource table V new value true, if resource value was changed, false, otherwise LWM2MUtil_SetFloatValue
Referenced by LWM2MObjectAccelerometerInternalSetValues, LWM2MObjectBarometerResetMinMaxValues, LWM2MObjectBarometerInternalSetValue, LWM2MObjectGyroscopeInternalSetValues, ResetMinMaxValues, LWM2MObjectHumidityInternalSetValue, ResetMinMax, LWM2MObjectIlluminanceInternalSetValue, LWM2MObjectMagnetometerInternalSetValues, LWM2MObjectTemperatureInternalSetValue.
LWM2M_MAX_DYNAMIC_CHANGES
Maximum number of supported resources changes using Lwm2mDynamicChanges_S .
Referenced by LWM2MUtil_SetFloatValue.
LWM2M_MUTEX_CREATE
Creates mutex.
M mutex name
Referenced by LWM2MObjectAccelerometer_Init, LWM2MObjectAlertNotification_Init, LWM2MObjectBarometer_Init, LWM2MObjectConnectivityMonitoring_Init, LWM2MObjectGyroscope_Init, LWM2MObjectHumidity_Init, LWM2MObjectIlluminance_Init, LWM2MObjectLightControl_Init, LWM2MObjectMagnetometer_Init, LWM2MObjectSensorDevice_Init, LWM2MObjectTemperature_Init.
LWM2M_MUTEX_INIT_VALUE
Initial value of a mutex.
LWM2M_MUTEX_INSTANCE
Declare/define an instance of a mutex.
M mutex name
LWM2M_MUTEX_IS_CREATED
Check, if mutex is already created.
M mutex name
LWM2M_MUTEX_LOCK
Lock mutex.
M mutex name true, it the mutex could be locked within 2000ms, false otherwise.
Referenced by LWM2MResetAlertFunc, LWM2MReadAlert, LWM2MObjectAlertNotification_SetValue, LWM2MGetIpAddresses, LWM2MObjectConnectivityMonitoring_SetIpAddress, AdjustState, Interval, PreprocessingMode, ScheduleUpdateSingleResource, LWM2MUtil_UpdateSingleResource, ScheduleUpdatePairResources, LWM2MUtil_UpdatePairResources, ScheduleUpdateTrippleResources, LWM2MUtil_UpdateTrippleResources.
LWM2M_MUTEX_LOCK_TIMEOUT
Lock mutex with timeout.
M mutex name T timeout in milliseconds true, it the mutex could be locked within the timeout, false otherwise.
Referenced by SensorTimerHandler.
LWM2M_MUTEX_UNLOCK
Unlock mutex.
M mutex name
Referenced by LWM2MResetAlertFunc, LWM2MReadAlert, LWM2MObjectAlertNotification_SetValue, LWM2MGetIpAddresses, LWM2MObjectConnectivityMonitoring_SetIpAddress, AdjustState, SensorTimerHandler, Interval, PreprocessingMode, ScheduleUpdateSingleResource, LWM2MUtil_UpdateSingleResource, ScheduleUpdatePairResources, LWM2MUtil_UpdatePairResources, ScheduleUpdateTrippleResources, LWM2MUtil_UpdateTrippleResources.
typedef void(* lwm2m_set_pair_float)(float value1, float value2))(float value1, float value2)
Function to set a two float values.
value1 first value to be set. value2 second value to be set.
typedef void(* lwm2m_set_single_float)(float value))(float value)
Function to set a single float value.
value value to be set.
typedef void(* lwm2m_set_tripple_float)(float value1, float value2, float value3))(float value1, float value2, float value3)
Function to set a three float values.
value1 first value to be set. value2 second value to be set. value3 third value to be set.
typedef struct Lwm2mDynamicChanges_S Lwm2mDynamicChanges_T
Data for dynamic reporting changes.
void LWM2MUtil_ReportChanges(Lwm2mDynamicChanges_T *changes, const Lwm2m_URI_Path_T *instanceUriPath)
Report changes from dynamic changes data.
Intended to be used by LWM2M_DYNAMIC_CHANGES_REPORT . changes dynamic changes data instanceUriPath uri path to changed instance Refer interface header for description
References Lwm2mDynamicChanges_S::changes, Lwm2mReporting_multipleResourcesChanged, Lwm2mDynamicChanges_S::changeResourceIndexes, RC_COAP_SERVER_SESSION_ALREADY_ACTIVE, Lwm2m_URI_Path_S::objectInstanceIndex, LWM2MDeviceResourceInfo, Lwm2mDevice_S::numberOfObjectInstances, Lwm2mDevice_S::objectInstances, Lwm2mObjectInstance_S::objectId, Lwm2mObjectInstance_S::objectInstanceId, LOG_ERROR, RC_OK, RC_RESOLVE_FORMAT_STR, RC_RESOLVE.
void LWM2MUtil_Schedule(Lwm2m_Call_T *call)
Schedule a call to lwm2m scheduler.
call callback executed in context of scheduler Refer interface header for description
References Callable_isAssigned, Lwm2m_Call_T::callback, Callable_assign, ScheduleCall, RC_OK, Scheduler_enqueue, assert.
Referenced by LWM2MObjectAccelerometer_Disable, LWM2MObjectBarometer_Disable, LWM2MObjectGyroscope_Disable, LWM2MObjectHumidity_Disable, LWM2MObjectIlluminance_Disable, LWM2MObjectMagnetometer_Disable, LWM2MObjectTemperature_Disable.
bool LWM2MUtil_SetFloatMaxValue(Lwm2mDynamicChanges_T *changes, const Lwm2mResource_T *resourceTable, Lwm2mResource_T *resource, float value)
set new float resource value, if its larger then the current value.
Check, if the new value is larger then the current resource value. If so, change the resource value and store the resource index in the dynamic changes data. Intended to be used by LWM2M_DYNAMIC_CHANGES_SET_FLOAT_MAX_VALUE . changes dynamic changes data resourceTable resource table the resource belongs to resource resource of the resource table value new value true, if resource value was changed, false, otherwise Refer interface header for description
References Lwm2mResource_S::data, Lwm2mResource_S::f, LWM2MUtil_SetFloatValue.
bool LWM2MUtil_SetFloatMinValue(Lwm2mDynamicChanges_T *changes, const Lwm2mResource_T *resourceTable, Lwm2mResource_T *resource, float value)
set new float resource value, if its less then the current value.
Check, if the new value is less then the current resource value. If so, change the resource value and store the resource index in the dynamic changes data. Intended to be used by LWM2M_DYNAMIC_CHANGES_SET_FLOAT_MIN_VALUE . changes dynamic changes data resourceTable resource table the resource belongs to resource resource of the resource table value new value true, if resource value was changed, false, otherwise Refer interface header for description
References Lwm2mResource_S::data, Lwm2mResource_S::f, LWM2MUtil_SetFloatValue.
bool LWM2MUtil_SetFloatValue(Lwm2mDynamicChanges_T *changes, const Lwm2mResource_T *resourceTable, Lwm2mResource_T *resource, float value)
set new float resource value.
Check, if the new value changes the resource value. If changed, store the resource index in the dynamic changes data. Intended to be used by LWM2M_DYNAMIC_CHANGES_SET_FLOAT_VALUE . changes dynamic changes data resourceTable resource table the resource belongs to resource resource of the resource table value new value true, if resource value was changed, false, otherwise Refer interface header for description
References Lwm2mResource_S::data, Lwm2mResource_S::f, value, LWM2M_MAX_DYNAMIC_CHANGES, Lwm2mDynamicChanges_S::changes, Lwm2mDynamicChanges_S::changeResourceIndexes.
Referenced by LWM2MUtil_SetFloatMinValue, LWM2MUtil_SetFloatMaxValue.
void LWM2MUtil_UpdatePairResources(float value1, float value2, Lwm2m_Pair_Resource_Update_T *updater)
Update two resource values. Delegate the transfer to the scheduler.
value1 new value value2 new value updater data for synchronized resource transfer Refer interface header for description
References LWM2M_MUTEX_LOCK, Lwm2m_Pair_Resource_Update_T::value1, Lwm2m_Pair_Resource_Update_T::value2, Callable_isAssigned, Lwm2m_Pair_Resource_Update_T::callback, Callable_assign, ScheduleUpdatePairResources, LWM2M_MUTEX_UNLOCK, RC_OK, Scheduler_enqueue, Callable_clear.
Referenced by LWM2MObjectAccelerometer_Enable, LWM2MObjectBarometer_Enable, LWM2MObjectGyroscope_Enable, LWM2MObjectHumidity_Enable, LWM2MObjectIlluminance_Enable, LWM2MObjectMagnetometer_Enable, LWM2MObjectTemperature_Enable.
void LWM2MUtil_UpdateSingleResource(float value, Lwm2m_Single_Resource_Update_T *updater)
Update single float resource value. Delegate the transfer to the scheduler.
value new value updater data for synchronized resource transfer Refer interface header for description
References LWM2M_MUTEX_LOCK, Lwm2m_Single_Resource_Update_T::value, value, Callable_isAssigned, Lwm2m_Single_Resource_Update_T::callback, Callable_assign, ScheduleUpdateSingleResource, LWM2M_MUTEX_UNLOCK, RC_OK, Scheduler_enqueue, Callable_clear.
Referenced by LWM2MObjectBarometer_SetValue, LWM2MObjectHumidity_SetValue, LWM2MObjectIlluminance_SetValue, LWM2MObjectTemperature_SetValue.
void LWM2MUtil_UpdateTrippleResources(float value1, float value2, float value3, Lwm2m_Tripple_Resource_Update_T *updater)
Update three resource values. Delegate the transfer to the scheduler.
value1 new value value2 new value value3 new value updater data for synchronized resource transfer Refer interface header for description
References LWM2M_MUTEX_LOCK, Lwm2m_Tripple_Resource_Update_T::value1, Lwm2m_Tripple_Resource_Update_T::value2, Lwm2m_Tripple_Resource_Update_T::value3, Callable_isAssigned, Lwm2m_Tripple_Resource_Update_T::callback, Callable_assign, ScheduleUpdateTrippleResources, LWM2M_MUTEX_UNLOCK, RC_OK, Scheduler_enqueue, Callable_clear.
Referenced by LWM2MObjectAccelerometer_SetValues, LWM2MObjectGyroscope_SetValues, LWM2MObjectMagnetometer_SetValues.