LWM2MDnsUtil.c
BCDS_MODULE_ID
DNS_RETRY_INTERVAL_IN_MS
interval in milliseconds for lookup retries
Referenced by LWM2MDnsUtil_ExtendedResolveHostname.
DNS_TASK_PRIORITY
Task Priority for DNS Task
Referenced by LWM2MDnsUtil_Init.
DNS_TASK_STACK_SIZE
TASK stack size for DNS Task
Referenced by LWM2MDnsUtil_Init.
MUTEX_TIMEOUT
timeout for mutex functions
Referenced by LWM2MDnsUtil_StartResolveHostname.
void* LWM2MDnsUtilCallbackContext
DNS context data, callback context
Referenced by LWM2MDnsTask, LWM2MDnsUtil_Init, LWM2MDnsUtil_StartResolveHostname.
xSemaphoreHandle LWM2MDnsUtilMutexHandle
mutex to protect DNS context data for asynchronous lookup
Referenced by LWM2MDnsTask, LWM2MDnsUtil_Init, LWM2MDnsUtil_StartResolveHostname.
LWM2MDnsUtil_Callback_T LWM2MDnsUtilResolvedCallback
DNS context data, resolved callback
Referenced by LWM2MDnsTask, LWM2MDnsUtil_Init, LWM2MDnsUtil_StartResolveHostname.
char LWM2MDnsUtilResolvedURL[128][128]
DNS context data, resolved URL
Referenced by LWM2MDnsTask, LWM2MDnsUtil_Init, LWM2MDnsUtil_StartResolveHostname.
xSemaphoreHandle LWM2MDnsUtilSemaHandle
semaphore to trigger asynchronous lookup
Referenced by LWM2MDnsTask, LWM2MDnsUtil_Init, LWM2MDnsUtil_StartResolveHostname.
xTaskHandle LWM2MDnsUtilTaskHandle
task to execute asynchronous lookup
Referenced by LWM2MDnsUtil_Init.
uint32_t LWM2MDnsUtilTimeout
DNS context data, retry timeout in seconds
Referenced by LWM2MDnsTask, LWM2MDnsUtil_StartResolveHostname.
char LWM2MDnsUtilUrl[128][128]
DNS context data, URL to be resolved
Referenced by LWM2MDnsTask, LWM2MDnsUtil_Init, LWM2MDnsUtil_StartResolveHostname.
static void LWM2MDnsTask(void *pvParameters)
Task for asynchronous DNS lookup. If parameter is provided, it must point to a "int32_t" which contains the number of loops. If not provided (NULL) unlimited loops are executed.
pvParameters optional pointer to number of loops.
References RC_DNS_OK, NULL, xSemaphoreTake, LWM2MDnsUtilSemaHandle, portMAX_DELAY, LWM2MDnsUtilMutexHandle, LWM2MDnsUtilUrl, Clock_getTimeMillis, LWM2MDnsUtil_ExtendedResolveHostname, LWM2MDnsUtilResolvedURL, LWM2MDnsUtilTimeout, RC_OK, RC_RESOLVE_FORMAT_STR, RC_RESOLVE, assert, LWM2MDnsUtilResolvedCallback, LWM2MDnsUtilCallbackContext, xSemaphoreGive.
Referenced by LWM2MDnsUtil_Init.
retcode_t LWM2MDnsUtil_ExtendedResolveHostname(const char *const URL, char *const resolvedURL, const size_t sizeResolvedURL, uint32_t timeout, const LWM2MDnsUtil_Callback_T callback, void *context)
Extended resolve URL. If URL uses literal host (e.g. "192.168.1.10"), the URL is just copied to provided resolvedURL buffer. Otherwise, either synchronous, if no callback is provided (NULL), or asynchronous, if callback is provided.
Refer interface header for description
References RETCODE_OK, RC_DNS_OK, NULL, RC_PLATFORM_ERROR, Ip_convertStringToAddr, RC_OK, SERVAL_IP_ADDR_LEN, Clock_getTime, WlanNetworkConfig_GetIpAddress, vTaskDelay, DNS_RETRY_INTERVAL_IN_MS, portTICK_RATE_MS, Retcode_RaiseError, Ip_convertAddrToString, LWM2MDnsUtil_StartResolveHostname.
Referenced by LWM2MDnsTask, LWM2MDnsUtil_ResolveHostname.
retcode_t LWM2MDnsUtil_Init(void)
Initialize DNS module.
Refer interface header for description
References LWM2MDnsUtilUrl, LWM2MDnsUtilResolvedURL, LWM2MDnsUtilResolvedCallback, NULL, LWM2MDnsUtilCallbackContext, LWM2MDnsUtilSemaHandle, assert, LWM2MDnsUtilMutexHandle, LWM2MDnsTask, DNS_TASK_STACK_SIZE, DNS_TASK_PRIORITY, LWM2MDnsUtilTaskHandle, RC_DNS_OK.
retcode_t LWM2MDnsUtil_ResolveHostname(const char *const URL, char *const resolvedURL, const size_t sizeResolvedURL, uint32_t timeout)
Resolve URL.
Refer interface header for description
References LWM2MDnsUtil_ExtendedResolveHostname, NULL.
retcode_t LWM2MDnsUtil_StartResolveHostname(const char *const URL, uint32_t timeout, const LWM2MDnsUtil_Callback_T callback, void *context)
Start asynchronous DNS lookup. Report result using the callback.
Refer interface header for description
References RC_DNS_BUSY, assert, NULL, RC_PLATFORM_ERROR, xSemaphoreTake, LWM2MDnsUtilMutexHandle, MUTEX_TIMEOUT, LWM2MDnsUtilResolvedCallback, LWM2MDnsUtilUrl, LWM2MDnsUtilResolvedURL, LWM2MDnsUtilCallbackContext, LWM2MDnsUtilTimeout, xSemaphoreGive, LWM2MDnsUtilSemaHandle, RC_DNS_PENDING.
Referenced by LWM2MDnsUtil_ExtendedResolveHostname.