LWM2MObjectGyroscope.h
LWM2M_OBJECTID_GYROSCOPE
LWM2M object id for Gyroscope.
https://github.com/IPSO-Alliance/pub/blob/master/reg/xml/3334.xml
typedef struct LWM2MLWM2MObjectGyroscope_Resource_S LWM2MLWM2MObjectGyroscope_Resource_T
LWM2MLWM2MObjectGyroscope_Resource_T LWM2MObjectGyroscopeResources
LWM2M resource data for instance 0.
void LWM2MObjectGyroscope_Disable(void)
Disable LWM2M object instance to stop providing sensor data. Sets unit to "" and all other values to 0. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
Refer interface header for description
References LWM2MUtil_Schedule.
Referenced by LWM2MSensorDeviceGyroscope_Activate.
void LWM2MObjectGyroscope_Enable(float minRange, float maxRange)
Enable LWM2M object instance to start providing sensor data. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
minRange minimum range of value in [Deg/s]. maxRange maximum range of value in [Deg/s]. Refer interface header for description
References LWM2MUtil_UpdatePairResources.
Referenced by LWM2MSensorDeviceGyroscope_Activate.
void LWM2MObjectGyroscope_Init(void)
Initialize LWM2M object instance. Must be called before any other function call.
Refer interface header for description
References Started, LWM2M_MUTEX_CREATE.
void LWM2MObjectGyroscope_SetValues(float xValue, float yValue, float zValue)
Set values for x-, y-, and z-axis.
Set values for axis, units in "Deg/s". Will triggers the sending of a notification, if a values was changed. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred. xValue value of x-axis in [Deg/s] yValue value of y-axis in [Deg/s] zValue value of z-axis in [Deg/s] Refer interface header for description
References LWM2MUtil_UpdateTrippleResources.
Referenced by LWM2MSensorDeviceGyroscope_Update.