LWM2MUtil.c
BCDS_MODULE_ID
LOG_MODULE
serval logging prefix
void LWM2MUtil_ReportChanges(Lwm2mDynamicChanges_T *changes, const Lwm2m_URI_Path_T *instanceUriPath)
Report changes from dynamic changes data.
Refer interface header for description
References Lwm2mDynamicChanges_S::changes, Lwm2mReporting_multipleResourcesChanged, Lwm2mDynamicChanges_S::changeResourceIndexes, RC_COAP_SERVER_SESSION_ALREADY_ACTIVE, Lwm2m_URI_Path_S::objectInstanceIndex, LWM2MDeviceResourceInfo, Lwm2mDevice_S::numberOfObjectInstances, Lwm2mDevice_S::objectInstances, Lwm2mObjectInstance_S::objectId, Lwm2mObjectInstance_S::objectInstanceId, LOG_ERROR, RC_OK, RC_RESOLVE_FORMAT_STR, RC_RESOLVE.
void LWM2MUtil_Schedule(Lwm2m_Call_T *call)
Schedule a call to lwm2m scheduler.
Refer interface header for description
References Callable_isAssigned, Lwm2m_Call_T::callback, Callable_assign, ScheduleCall, RC_OK, Scheduler_enqueue, assert.
Referenced by LWM2MObjectAccelerometer_Disable, LWM2MObjectBarometer_Disable, LWM2MObjectGyroscope_Disable, LWM2MObjectHumidity_Disable, LWM2MObjectIlluminance_Disable, LWM2MObjectMagnetometer_Disable, LWM2MObjectTemperature_Disable.
bool LWM2MUtil_SetFloatMaxValue(Lwm2mDynamicChanges_T *changes, const Lwm2mResource_T *resourceTable, Lwm2mResource_T *resource, float value)
set new float resource value, if its larger then the current value.
Refer interface header for description
References Lwm2mResource_S::data, Lwm2mResource_S::f, LWM2MUtil_SetFloatValue.
bool LWM2MUtil_SetFloatMinValue(Lwm2mDynamicChanges_T *changes, const Lwm2mResource_T *resourceTable, Lwm2mResource_T *resource, float value)
set new float resource value, if its less then the current value.
Refer interface header for description
References Lwm2mResource_S::data, Lwm2mResource_S::f, LWM2MUtil_SetFloatValue.
bool LWM2MUtil_SetFloatValue(Lwm2mDynamicChanges_T *changes, const Lwm2mResource_T *resourceTable, Lwm2mResource_T *resource, float value)
set new float resource value.
Refer interface header for description
References Lwm2mResource_S::data, Lwm2mResource_S::f, value, LWM2M_MAX_DYNAMIC_CHANGES, Lwm2mDynamicChanges_S::changes, Lwm2mDynamicChanges_S::changeResourceIndexes.
Referenced by LWM2MUtil_SetFloatMinValue, LWM2MUtil_SetFloatMaxValue.
void LWM2MUtil_UpdatePairResources(float value1, float value2, Lwm2m_Pair_Resource_Update_T *updater)
Update two resource values. Delegate the transfer to the scheduler.
Refer interface header for description
References LWM2M_MUTEX_LOCK, Lwm2m_Pair_Resource_Update_T::value1, Lwm2m_Pair_Resource_Update_T::value2, Callable_isAssigned, Lwm2m_Pair_Resource_Update_T::callback, Callable_assign, ScheduleUpdatePairResources, LWM2M_MUTEX_UNLOCK, RC_OK, Scheduler_enqueue, Callable_clear.
Referenced by LWM2MObjectAccelerometer_Enable, LWM2MObjectBarometer_Enable, LWM2MObjectGyroscope_Enable, LWM2MObjectHumidity_Enable, LWM2MObjectIlluminance_Enable, LWM2MObjectMagnetometer_Enable, LWM2MObjectTemperature_Enable.
void LWM2MUtil_UpdateSingleResource(float value, Lwm2m_Single_Resource_Update_T *updater)
Update single float resource value. Delegate the transfer to the scheduler.
Refer interface header for description
References LWM2M_MUTEX_LOCK, Lwm2m_Single_Resource_Update_T::value, value, Callable_isAssigned, Lwm2m_Single_Resource_Update_T::callback, Callable_assign, ScheduleUpdateSingleResource, LWM2M_MUTEX_UNLOCK, RC_OK, Scheduler_enqueue, Callable_clear.
Referenced by LWM2MObjectBarometer_SetValue, LWM2MObjectHumidity_SetValue, LWM2MObjectIlluminance_SetValue, LWM2MObjectTemperature_SetValue.
void LWM2MUtil_UpdateTrippleResources(float value1, float value2, float value3, Lwm2m_Tripple_Resource_Update_T *updater)
Update three resource values. Delegate the transfer to the scheduler.
Refer interface header for description
References LWM2M_MUTEX_LOCK, Lwm2m_Tripple_Resource_Update_T::value1, Lwm2m_Tripple_Resource_Update_T::value2, Lwm2m_Tripple_Resource_Update_T::value3, Callable_isAssigned, Lwm2m_Tripple_Resource_Update_T::callback, Callable_assign, ScheduleUpdateTrippleResources, LWM2M_MUTEX_UNLOCK, RC_OK, Scheduler_enqueue, Callable_clear.
Referenced by LWM2MObjectAccelerometer_SetValues, LWM2MObjectGyroscope_SetValues, LWM2MObjectMagnetometer_SetValues.
static retcode_t ScheduleCall(Callable_T *callable_ptr, retcode_t status)
References CALLABLE_GET_CONTEXT, Lwm2m_Call_T::call, RC_OK.
Referenced by LWM2MUtil_Schedule.
static retcode_t ScheduleUpdatePairResources(Callable_T *callable_ptr, retcode_t status)
References CALLABLE_GET_CONTEXT, LWM2M_MUTEX_LOCK, Lwm2m_Pair_Resource_Update_T::value1, Lwm2m_Pair_Resource_Update_T::value2, Callable_clear, Lwm2m_Pair_Resource_Update_T::callback, LWM2M_MUTEX_UNLOCK, Lwm2m_Pair_Resource_Update_T::set_pair, RC_OK.
Referenced by LWM2MUtil_UpdatePairResources.
static retcode_t ScheduleUpdateSingleResource(Callable_T *callable_ptr, retcode_t status)
References CALLABLE_GET_CONTEXT, LWM2M_MUTEX_LOCK, value, Lwm2m_Single_Resource_Update_T::value, Callable_clear, Lwm2m_Single_Resource_Update_T::callback, LWM2M_MUTEX_UNLOCK, Lwm2m_Single_Resource_Update_T::set_single, RC_OK.
Referenced by LWM2MUtil_UpdateSingleResource.
static retcode_t ScheduleUpdateTrippleResources(Callable_T *callable_ptr, retcode_t status)
References CALLABLE_GET_CONTEXT, LWM2M_MUTEX_LOCK, Lwm2m_Tripple_Resource_Update_T::value1, Lwm2m_Tripple_Resource_Update_T::value2, Lwm2m_Tripple_Resource_Update_T::value3, Callable_clear, Lwm2m_Tripple_Resource_Update_T::callback, LWM2M_MUTEX_UNLOCK, Lwm2m_Tripple_Resource_Update_T::set_tripple, RC_OK.
Referenced by LWM2MUtil_UpdateTrippleResources.