LWM2MObjectAccelerometer.h
LWM2M_OBJECTID_IPSO_ACCELEROMETER
LWM2M object id for accelerometer.
typedef struct LWM2MObjectAccelerometer_Resource_S LWM2MObjectAccelerometer_Resource_T
LWM2MObjectAccelerometer_Resource_T LWM2MObjectAccelerometerResources
LWM2M resource data for instance 0.
void LWM2MObjectAccelerometer_Disable(void)
Disable LWM2M object instance to stop providing sensor data. Sets unit to "" and all other values to 0. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
Refer interface header for description
References LWM2MUtil_Schedule.
Referenced by LWM2MSensorDeviceAccelerometer_Activate.
void LWM2MObjectAccelerometer_Enable(float minRangeValue, float maxRangeValue)
Enable LWM2M object instance to start providing sensor data. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred.
minRangeValue minimum range of value in [g]. maxRangeValue maximum range of value in [g]. Refer interface header for description
References LWM2MUtil_UpdatePairResources.
Referenced by LWM2MSensorDeviceAccelerometer_Activate.
void LWM2MObjectAccelerometer_Init(void)
Initialize LWM2M object instance. Must be called before any other function call.
Refer interface header for description
References Started, LWM2M_MUTEX_CREATE.
void LWM2MObjectAccelerometer_SetValues(float xAxis, float yAxis, float zAxis)
Set values for x-, y-, and z-axis.
Set values for axis, units in [g]. Will triggers the sending of a notification, if a value was changed. Function is thread safe, it schedules a job for serval. Execution may therefore be deferred. xAxis acceleration of x-axis in [g] yAxis acceleration of y-axis in [g] zAxis acceleration of z-axis in [g] Refer interface header for description
References LWM2MUtil_UpdateTrippleResources.
Referenced by LWM2MSensorDeviceAccelerometer_Update.