Lem.c
ADC_BUFFER_SIZE
Referenced by CalculateRunningRMS.
BCDS_MODULE_ID
NO_OF_CHANNELS_USED
Referenced by CalculateRunningRMS.
TIMER_SAMPLING_FREQ
ADC Signal sampling frequency in Hz
Referenced by Lem_Enable.
float CurrentRatedTransformationRatio
Current rated transformation ratio for lem sensor
Referenced by Lem_Setup, Lem_GetRmsCurrent.
volatile float RMSVoltageSumOfSquares
RMS Voltage on Ch5
Referenced by CalculateRunningRMS, Lem_GetRmsVoltage, Lem_GetRmsCurrent.
uint16_t ScanData[ADC_BUFFER_SIZE][ADC_BUFFER_SIZE]
LEM sensor ADC user buffer for CH5
Referenced by Lem_Enable.
static void CalculateRunningRMS(ADC_T adc, uint32_t SamplingFreq, uint16_t *bufferPtr)
ADC Central callback function which calculates the RMS voltage for the Differential signal from the AD5 & AD6 channels.
adc handle not used. SamplingFreq which tells the adc samples collected frequency. bufferPtr which is pointer to the application provided adc buffer which holds adc samples for CH5 & Ch6. ADC central always provides 256 fixed number of adc samples per channel so the expecting the users to provide the buffer accordingly.
References BCDS_UNUSED, ADC_BUFFER_SIZE, NO_OF_CHANNELS_USED, ADC_CONVERSION_FACTOR, RMSVoltageSumOfSquares.
Referenced by Lem_Enable.
Retcode_T Lem_Disable(void)
function to Deinitialize lemsensor module.
Status of the LemSensor Deinitialization RETCODE_OK if the Deinitialization is successfulError for failure
References RETCODE_OK, AdcCentral_StopScan, ADC_ENABLE_CH5_SCAN, ADC_ENABLE_CH6_SCAN.
Referenced by HandleExternalHwHotPlug.
Retcode_T Lem_Enable(void)
function to initialize the ADC, DMA , Board detect pin, Timer required for the LEM sensor sampling & Starts the sampling timer.
Status of the LemSensor Initialization RETCODE_OK if the initialization is successfulError for failure
References RETCODE_OK, AdcCentral_Init, AdcCentral_ConfigScan_S::BufferPtr, ScanData, AdcCentral_ConfigScan_S::Appcallback, CalculateRunningRMS, AdcCentral_ConfigScan_S::ChannelScanMask, ADC_ENABLE_CH5_SCAN, ADC_ENABLE_CH6_SCAN, AdcCentral_ConfigScan_S::SamplingRateInHz, TIMER_SAMPLING_FREQ, AdcCentral_StartScan.
Referenced by HandleExternalHwHotPlug, AppControllerEnable.
Retcode_T Lem_GetRmsCurrent(float *rmsCurrent)
function to get the RMS current.
rmsCurrent To get the LEM Sensor RMS current in ampere. Status of the Getting the LemSensor Rms currnt RETCODE_OK if the RMS current got successfullyError for failure.
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, RMSVoltageSumOfSquares, ADC_CENTRAL_NO_OF_SAMPLES, CurrentRatedTransformationRatio.
Retcode_T Lem_GetRmsVoltage(float *rmsvoltage)
function to get the RMS voltage.
rmsvoltage To get the LEM Sensor RMS voltage in volts. Status of the Getting the LemSensor Rms Voltage RETCODE_OK if the RMS voltage got successfullyError for failure. On every #SAMPLING_WINDOW_CYCLES the RMS voltage is updated.
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, RMSVoltageSumOfSquares, ADC_CENTRAL_NO_OF_SAMPLES.
Retcode_T Lem_Setup(float currentRatedTransformationRatio)
Initialize the required components and variables of lem sensor module.
currentRatedTransformationRatio Current transformation ratio for the core used in lemsensor : example- Rated transformation ratio is 44.44 for 75Ampere split core current transformer RETCODE_OK upon successful initialization or error code otherwise
References RETCODE_OK, CurrentRatedTransformationRatio, RETCODE, RETCODE_SEVERITY_WARNING, RETCODE_INVALID_PARAM.