LightSensor.c
BCDS_MODULE_ID
GET_MAPPING_ERROR
Referenced by mappingEnumForGetFunctions, LightSensor_getInterruptStatus.
INIT_DONE
Referenced by LightSensor_init.
INIT_NOT_DONE
Referenced by LightSensor_init, LightSensor_setManualMode, LightSensor_setContinuousMode, LightSensor_setIntegrationTime, LightSensor_setBrightness, LightSensor_getInterruptStatus, LightSensor_readRawData, LightSensor_readLuxData, LightSensor_configureThresholdInterrupt, LightSensor_registerRealTimeCallback, LightSensor_registerDeferredCallback, LightSensor_disableInterrupt, LightSensor_deInit.
MAX_INTERRUPT_CHANNEL_1
Referenced by maxIsrCallback.
PACKAGE_ID_DEFAULT
default package ID
Referenced by LightSensor_init, LightSensor_setManualMode, LightSensor_setContinuousMode, LightSensor_setIntegrationTime, LightSensor_setBrightness, LightSensor_getInterruptStatus, LightSensor_readRawData, LightSensor_readLuxData, LightSensor_configureThresholdInterrupt, LightSensor_registerRealTimeCallback, LightSensor_registerDeferredCallback, LightSensor_disableInterrupt, LightSensor_deInit.
const MAX44009_ConfigBrightness_T brightnessLookupTable[LIGHTSENSOR_BRIGHTNESS_OUT_OF_RANGE][LIGHTSENSOR_BRIGHTNESS_OUT_OF_RANGE]
Referenced by LightSensor_setBrightness.
const MAX44009_ConfigMode_T continousModeLookUpTable[LIGHTSENSOR_MODE_OUT_OF_RANGE][LIGHTSENSOR_MODE_OUT_OF_RANGE]
Referenced by LightSensor_setContinuousMode.
const MAX44009_IntegrationTime_T integrationtimeLookupTable[LIGHTSENSOR_TIME_OUT_OF_RANGE][LIGHTSENSOR_TIME_OUT_OF_RANGE]
Referenced by LightSensor_setIntegrationTime.
const MAX44009_ConfigMode_T interruptStatusLookupTable[LIGHTSENSOR_CONFIG_INTERRUPT_OUT_OF_RANGE][LIGHTSENSOR_CONFIG_INTERRUPT_OUT_OF_RANGE]
Referenced by LightSensor_getInterruptStatus.
const MAX44009_ConfigMode_T manualModeLookUpTable[LIGHTSENSOR_MODE_OUT_OF_RANGE][LIGHTSENSOR_MODE_OUT_OF_RANGE]
Referenced by LightSensor_setManualMode.
LightSensor_HandlePtr_T Max44009Handle
Retcode_T LightSensor_configureThresholdInterrupt(LightSensor_HandlePtr_T handle, uint32_t upperThreshold, uint32_t lowerThreshold, uint32_t thresholdTimer)
function responsible to set interrupt conditions, that means, threshold boundaries and threshold timer for lightsensor interrupt. Interrupt will be fired if the light intensity is crossed threshold boundaries for a window period defined in threshold timer.User must register the callback before calling configuring interrupt
handle global handle of sensor upperThreshold upper threshold value to be programmed in upper threshold register for light sensor interrupt. lowerThreshold lower threshold value to be programmed in lower threshold register for light sensor interrupt. thresholdTimer threshold timer value to be programmed in threshold timer register for light sensor interrupt. RETCODE_SUCCESS Interrupt Configuration success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. In case of other failures refer Max44009Utils_configInterrupt API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, NULL, LightSensor_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, LightSensor_Handle_S::SensorInformation, LightSensor_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Max44009Utils_ThresholdIntrConfig_S::upperThreshold, Max44009Utils_ThresholdIntrConfig_S::lowerThreshold, Max44009Utils_ThresholdIntrConfig_S::thresholdTimer, LightSensor_SensorInfo_S::sensorID, LIGHTSENSOR_MAX44009, Max44009Utils_configInterrupt, RETCODE_OK, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T LightSensor_deInit(LightSensor_HandlePtr_T handle)
DeInitializes the light sensor referenced by the passed handle.
handle Handle to the light sensor object RETCODE_SUCCESS Sensor De-initialization success. RETCODE_INVALID_PARAM In case of invalid sensor handle. In case of any other error refer Max44009Utils_uninitialize error codes. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, NULL, LightSensor_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, LightSensor_Handle_S::SensorInformation, LightSensor_SensorInfo_S::initializationStatus, RETCODE_OK, LightSensor_SensorInfo_S::sensorID, LIGHTSENSOR_MAX44009, Max44009Utils_uninitialize, Retcode_GetPackage, PACKAGE_ID_DEFAULT, RETCODE_SEVERITY_ERROR.
Referenced by LWM2MSensorDeviceIlluminance_Activate.
Retcode_T LightSensor_disableInterrupt(LightSensor_HandlePtr_T handle)
Disable Interrupt type on the handle.
handle Handle to the lightSensor object RETCODE_SUCCESS Disable interrupt status is success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. In case of other failures refer Max44009Utils_disableInterrupt API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, NULL, LightSensor_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, LightSensor_Handle_S::SensorInformation, LightSensor_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, LightSensor_SensorInfo_S::sensorID, LIGHTSENSOR_MAX44009, Max44009Utils_disableInterrupt, RETCODE_OK, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T LightSensor_getInterruptStatus(LightSensor_HandlePtr_T handle, LightSensor_ConfigInterruptPtr_T interruptStatus)
function to read light sensor interrupt status register
handle global handle of sensor interruptStatus holds the interrupt configuration that is configured RETCODE_SUCCESS get interrupt status is success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of getting interrupt status value other than LightSensor_ConfigInterrupt_E. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, GET_MAPPING_ERROR, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, LightSensor_Handle_S::SensorInformation, LightSensor_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, LightSensor_SensorInfo_S::sensorID, LIGHTSENSOR_MAX44009, MAX44009_GetInterptStatus, RETCODE_OK, mappingEnumForGetFunctions, LIGHTSENSOR_DISABLE_INTERRUPT, LIGHTSENSOR_ENABLE_INTERRUPT, interruptStatusLookupTable, RETCODE_NOT_SUPPORTED, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T LightSensor_init(LightSensor_HandlePtr_T handle)
Initializes the LightSensor referenced by the passed handle.
handle Handle to the light sensor object RETCODE_SUCCESS Light sensor initialization success. RETCODE_INVALID_PARAM In case of invalid sensor handle. In case of any other error refer Max44009Utils_initialize error codes. This function needs to be called before calling any other light sensor API. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, NULL, LightSensor_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_DONE, LightSensor_Handle_S::SensorInformation, LightSensor_SensorInfo_S::initializationStatus, RETCODE_OK, LightSensor_SensorInfo_S::sensorID, LIGHTSENSOR_MAX44009, Max44009Utils_Info_S::ISRCallback, maxIsrCallback, Max44009Utils_initialize, INIT_NOT_DONE, Retcode_GetPackage, PACKAGE_ID_DEFAULT, RETCODE_SEVERITY_ERROR.
Referenced by LWM2MSensorDeviceIlluminance_Activate.
Retcode_T LightSensor_readLuxData(LightSensor_HandlePtr_T handle, uint32_t *luxData)
function to read sensor data in milli lux.
handle global handle of sensor luxData holds sensor data in milli lux RETCODE_SUCCESS Reading lux data success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle or NULL pointer arguments. In case of other failures refer #MAX44009_getSensorData API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, NULL, LightSensor_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, LightSensor_Handle_S::SensorInformation, LightSensor_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, LightSensor_SensorInfo_S::sensorID, LIGHTSENSOR_MAX44009, MAX44009_GetSensorData, RETCODE_OK, MAX44009_GetDataInMilliLux, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Referenced by LWM2MSensorDeviceIlluminance_Update.
Retcode_T LightSensor_readRawData(LightSensor_HandlePtr_T handle, uint16_t *luxData)
Reads raw sensor data from light sensor referenced by the passed handle.
handle global handle of sensor luxData holds sensor data RETCODE_SUCCESS Reading raw data success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle or NULL pointer arguments. In case of other failures refer #MAX44009_getSensorData API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, NULL, LightSensor_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, LightSensor_Handle_S::SensorInformation, LightSensor_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, LightSensor_SensorInfo_S::sensorID, LIGHTSENSOR_MAX44009, MAX44009_GetSensorData, RETCODE_OK, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T LightSensor_registerDeferredCallback(LightSensor_HandlePtr_T handle, deferredInterruptCallback deferredCallback)
function responsible to register deferred interrupt handler for light sensor. When user registers deferred callback their callback will be executed in timer daemon context, where there is no restriction of using delay functions and/or APIs related to bus access.
handle global handle of sensor deferredInterruptCallback function handle to register RETCODE_SUCCESS Registering deferred time callback is success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle or NULL callback. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, NULL, LightSensor_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, LightSensor_Handle_S::SensorInformation, LightSensor_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, LightSensor_SensorInfo_S::sensorID, LIGHTSENSOR_MAX44009, LightSensor_Handle_S::MaxInterrupt, LightSensor_InterruptCallback_S::deferredCallback, LightSensor_InterruptCallback_S::rtCallback, RETCODE_OK, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T LightSensor_registerRealTimeCallback(LightSensor_HandlePtr_T handle, interruptCallback realTimeCallback)
function responsible to register real time interrupt handler for light sensor. When user registers real time callback their callback will be executed in ISR context. User must not use any delay functions or bus access in ISR context.
handle global handle of sensor realTimeCallback function handle to register RETCODE_SUCCESS Registering real time callback is success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle or NULL callback. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, NULL, LightSensor_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, LightSensor_Handle_S::SensorInformation, LightSensor_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, LightSensor_SensorInfo_S::sensorID, LIGHTSENSOR_MAX44009, LightSensor_Handle_S::MaxInterrupt, LightSensor_InterruptCallback_S::rtCallback, LightSensor_InterruptCallback_S::deferredCallback, RETCODE_OK, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T LightSensor_setBrightness(LightSensor_HandlePtr_T handle, LightSensor_ConfigBrightness_T brightness)
function to set brightness to low or high for light sensor
handle global handle of sensor brightness LightSensor_ConfigBrightness_T holds brightness configuration RETCODE_SUCCESS Setting brightness success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of setting brightness other than LightSensor_ConfigBrightness_E. In case of other failures refer #MAX44009_setCdr API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, NULL, LIGHTSENSOR_BRIGHTNESS_OUT_OF_RANGE, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, LightSensor_Handle_S::SensorInformation, LightSensor_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, LightSensor_SensorInfo_S::sensorID, LIGHTSENSOR_MAX44009, LIGHTSENSOR_HIGH_BRIGHTNESS, RETCODE_NOT_SUPPORTED, MAX44009_SetCdr, brightnessLookupTable, RETCODE_OK, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T LightSensor_setContinuousMode(LightSensor_HandlePtr_T handle, LightSensor_ConfigMode_T manualMode)
Function to enable/disable the Continuous mode for the light sensor referenced by the passed handle.
handle Handle to the lightSensor object continuousMode This variable holds the Continuous mode configuration RETCODE_SUCCESS Setting continuous mode success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of setting mode other than LightSensor_ConfigMode_E. In case of other failures refer #MAX44009_setContinousModeReg API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, NULL, LIGHTSENSOR_MODE_OUT_OF_RANGE, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, LightSensor_Handle_S::SensorInformation, LightSensor_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, LightSensor_SensorInfo_S::sensorID, LIGHTSENSOR_MAX44009, LIGHTSENSOR_MAX44009_DISABLE_MODE, RETCODE_NOT_SUPPORTED, MAX44009_SetContinousModeReg, continousModeLookUpTable, RETCODE_OK, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T LightSensor_setIntegrationTime(LightSensor_HandlePtr_T handle, LightSensor_IntegrationTime_T integrationTime)
function to configure integration time of light sensor.
handle global handle of sensor integrationTime LightSensor_IntegrationTime_T holds the integration time configuration RETCODE_SUCCESS Setting Integration time success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of setting integration time other than LightSensor_IntegrationTime_E. In case of other failures refer #MAX44009_setIntegrationTime API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, NULL, LIGHTSENSOR_TIME_OUT_OF_RANGE, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, LightSensor_Handle_S::SensorInformation, LightSensor_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, LightSensor_SensorInfo_S::sensorID, LIGHTSENSOR_MAX44009, LIGHTSENSOR_6P5MS, RETCODE_NOT_SUPPORTED, MAX44009_SetIntegrationTime, integrationtimeLookupTable, RETCODE_OK, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T LightSensor_setManualMode(LightSensor_HandlePtr_T handle, LightSensor_ConfigMode_T manualMode)
Function to enable/disable the Manual mode for the light sensor referenced by the passed handle.
handle Handle to the lightSensor object manualMode This variable holds the manual mode configuration RETCODE_SUCCESS Setting manual mode success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of setting mode other than LightSensor_ConfigMode_E. In case of other failures refer #MAX44009_setManualModeReg API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, NULL, LIGHTSENSOR_MODE_OUT_OF_RANGE, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, LightSensor_Handle_S::SensorInformation, LightSensor_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, LightSensor_SensorInfo_S::sensorID, LIGHTSENSOR_MAX44009, LIGHTSENSOR_MAX44009_DISABLE_MODE, RETCODE_NOT_SUPPORTED, MAX44009_SetManualModeReg, manualModeLookUpTable, RETCODE_OK, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
static int8_t mappingEnumForGetFunctions(uint8_t start, uint8_t end, uint8_t getValueToBeTransalated, const uint8_t *lookUpTablePtr)
References GET_MAPPING_ERROR.
Referenced by LightSensor_getInterruptStatus.
static void maxIsrCallback(uint32_t channel, uint32_t edge)
MAX44009 driver callback function that will be called during ISR.
channel channel at which interrupt has occurred edge edge at which interrupt has occurred falling(0) or raising edge(1)
References RETCODE_OK, portBASE_TYPE, xHigherPriorityTaskWoken, NULL, MAX_INTERRUPT_CHANNEL_1, LightSensor_Handle_S::MaxInterrupt, LightSensor_InterruptCallback_S::rtCallback, LightSensor_InterruptCallback_S::deferredCallback, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM, xTimerPendFunctionCallFromISR, portYIELD_FROM_ISR, RETCODE_OUT_OF_RESOURCES, Retcode_RaiseError.
Referenced by LightSensor_init.