Magnetometer.c
BCDS_MODULE_ID
const uint8_t dataRateLookUpTable[MAGNETOMETER_DATARATE_OUT_OF_RANGE][MAGNETOMETER_DATARATE_OUT_OF_RANGE]
Referenced by Magnetometer_setDataRate, Magnetometer_getDataRate.
const uint8_t modeLookUpTable[MAGNETOMETER_POWERMODE_OUT_OF_RANGE][MAGNETOMETER_POWERMODE_OUT_OF_RANGE]
Referenced by Magnetometer_setPowerMode, Magnetometer_getPowerMode.
const uint8_t presetModeLookUpTable[MAGNETOMETER_PRESETMODE_OUT_OF_RANGE][MAGNETOMETER_PRESETMODE_OUT_OF_RANGE]
Referenced by Magnetometer_setPresetMode, Magnetometer_getPresetMode.
static Retcode_T bmm150LibErrorMapping(BMM050_RETURN_FUNCTION_TYPE BMM150_libReturn)
This function maps error codes returned from BMM150 library to retcode values.
BMM150_RETURN_FUNCTION_TYPE Return value from BMM150 library RETCODE_OK BMM150 sensor API call success RETCODE_FAILURE BMM150 sensor API call failed RETCODE_INVALID_PARAM BMM150 sensor API call failed because of invalid input parameter
References RETCODE_FAILURE, BMM150_SUCCESS, RETCODE_OK, E_BMM050_NULL_PTR, RETCODE_INVALID_PARAM.
Referenced by readMagData, Magnetometer_setPowerMode, Magnetometer_setPresetMode, Magnetometer_setDataRate, Magnetometer_getPowerMode, Magnetometer_getPresetMode, Magnetometer_getDataRate.
static void bmmIsrCallback(uint32_t channel, uint32_t edge)
BMM150 driver callback function that will be called during ISR.
channel channel at which interrupt has occurred edge edge at which interrupt has occurred falling(0) or raising edge(1) Currently interrupt is not supported for BMM150
References BCDS_UNUSED.
Referenced by Magnetometer_init.
Retcode_T Magnetometer_deInit(Magnetometer_HandlePtr_T handle)
Function to DeInitialize the magnetometer sensor referenced by the passed handle.
handle handle of the Magnetometer object RETCODE_SUCCESS Magnetometer De-initialization success. RETCODE_INVALID_PARAM In case of invalid sensor handle. In case of any other error refer Bmm150Utils_uninitialize error codes. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, NULL, Magnetometer_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Magnetometer_Handle_S::SensorInformation, Magnetometer_SensorInfo_S::initializationStatus, RETCODE_OK, Magnetometer_SensorInfo_S::sensorID, MAGNETOMETER_BMM150, Bmm150Utils_uninitialize, Retcode_GetPackage, PACKAGE_ID_DEFAULT, RETCODE_SEVERITY_ERROR.
Referenced by LWM2MSensorDeviceMagnetometer_Activate.
Retcode_T Magnetometer_getDataRate(Magnetometer_HandlePtr_T handle, Magnetometer_DataRatePtr_T datarate)
Function to read the Datarate of the Magnetometer sensor.
handle handle of the Magnetometer object datarate variable to store datarate of the sensor RETCODE_SUCCESS Getting data rate success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of getting data rate other than Magnetometer_DataRate_E. In case of other failures refer bmm150LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References GET_MAPPING_ERROR, RETCODE_FAILURE, MAGNETOMETER_DATARATE_OUT_OF_RANGE, BMM050_RETURN_FUNCTION_TYPE, E_BMM050_NULL_PTR, NULL, Magnetometer_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Magnetometer_Handle_S::SensorInformation, Magnetometer_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Magnetometer_SensorInfo_S::sensorID, MAGNETOMETER_BMM150, bmm050_get_data_rate, bmm150LibErrorMapping, RETCODE_OK, mappingEnumForGetFunctions, MAGNETOMETER_BMM150_DATARATE_10HZ, MAGNETOMETER_BMM150_DATARATE_30HZ, dataRateLookUpTable, RETCODE_NOT_SUPPORTED, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T Magnetometer_getPowerMode(Magnetometer_HandlePtr_T handle, Magnetometer_PowerModePtr_T powerMode)
Function to read the powermode of the Magnetometer sensor.
handle handle of the Magnetometer object powerMode variable to be update the powermode RETCODE_SUCCESS Getting power mode success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of getting power mode other than Magnetometer_PowerMode_E. In case of other failures refer bmm150LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References GET_MAPPING_ERROR, RETCODE_FAILURE, MAGNETOMETER_POWERMODE_OUT_OF_RANGE, BMM050_RETURN_FUNCTION_TYPE, E_BMM050_NULL_PTR, NULL, Magnetometer_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Magnetometer_Handle_S::SensorInformation, Magnetometer_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Magnetometer_SensorInfo_S::sensorID, MAGNETOMETER_BMM150, bmm050_get_functional_state, bmm150LibErrorMapping, RETCODE_OK, mappingEnumForGetFunctions, MAGNETOMETER_BMM150_POWERMODE_NORMAL, MAGNETOMETER_BMM150_POWERMODE_SLEEP, modeLookUpTable, RETCODE_NOT_SUPPORTED, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T Magnetometer_getPresetMode(Magnetometer_HandlePtr_T handle, Magnetometer_PresetModePtr_T presetMode)
Function to read the preset mode of the Magnetometer sensor.
handle handle of the Magnetometer object presetMode variable to store the presetMode of the sensor RETCODE_SUCCESS Getting preset mode success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of getting preset mode other than Magnetometer_PresetMode_E. In case of other failures refer bmm150LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References GET_MAPPING_ERROR, RETCODE_FAILURE, MAGNETOMETER_PRESETMODE_OUT_OF_RANGE, BMM050_RETURN_FUNCTION_TYPE, E_BMM050_NULL_PTR, NULL, Magnetometer_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Magnetometer_Handle_S::SensorInformation, Magnetometer_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Magnetometer_SensorInfo_S::sensorID, MAGNETOMETER_BMM150, bmm050_get_presetmode, bmm150LibErrorMapping, RETCODE_OK, mappingEnumForGetFunctions, MAGNETOMETER_BMM150_PRESETMODE_LOWPOWER, MAGNETOMETER_BMM150_PRESETMODE_ENHANCED, presetModeLookUpTable, RETCODE_NOT_SUPPORTED, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T Magnetometer_init(Magnetometer_HandlePtr_T handle)
Initializes the Magnetometer sensor referenced by the passed handle.
handle handle of the Magnetometer object RETCODE_SUCCESS Magnetometer initialization success. RETCODE_INVALID_PARAM In case of invalid sensor handle. In case of any other error refer Bmm150Utils_initialize error codes. This function needs to be called before calling any other Magnetometer API. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, NULL, Magnetometer_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_DONE, Magnetometer_Handle_S::SensorInformation, Magnetometer_SensorInfo_S::initializationStatus, RETCODE_OK, Magnetometer_SensorInfo_S::sensorID, MAGNETOMETER_BMM150, Bmm150Utils_Info_S::ISRCallback, bmmIsrCallback, Bmm150Utils_initialize, INIT_NOT_DONE, Retcode_GetPackage, PACKAGE_ID_DEFAULT, RETCODE_SEVERITY_ERROR.
Referenced by LWM2MSensorDeviceMagnetometer_Activate.
Retcode_T Magnetometer_readXyzLsbData(Magnetometer_HandlePtr_T handle, Magnetometer_XyzDataPtr_T data)
Function to Read the magnetometer sensor data referenced by the passed handle.
handle handle of the Magnetometer object data Parameter in which the magnetometer XYZ data gets collected RETCODE_SUCCESS Reading Magnetometer xyzLsbdata success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle or NULL pointer. In case of other failures refer readMagData or Bmm150Utils_remapAxis API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E. Whenever there is an overflow in any axis this API will return the maximum value the sensor could read for that axis below are the maximum value the sensor could read x-axis - 1500, y-axis - 1500, z-axis - 2500
References RETCODE_FAILURE, NULL, Magnetometer_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Magnetometer_Handle_S::SensorInformation, Magnetometer_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Magnetometer_SensorInfo_S::sensorID, MAGNETOMETER_BMM150, readMagData, RETCODE_OK, AxisRemap_Data_S::x, bmm050_mag_s32_data_t::datax, AxisRemap_Data_S::y, bmm050_mag_s32_data_t::datay, AxisRemap_Data_S::z, bmm050_mag_s32_data_t::dataz, Bmm150Utils_remapAxis, Magnetometer_XyzData_S::xAxisData, Magnetometer_XyzData_S::yAxisData, Magnetometer_XyzData_S::zAxisData, Magnetometer_XyzData_S::resistance, bmm050_mag_s32_data_t::resistance, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T Magnetometer_readXyzTeslaData(Magnetometer_HandlePtr_T handle, Magnetometer_XyzDataPtr_T data)
Function to read micro tesla xyz value from the magnetometer referenced by the passed handle.
handle handle of the Magnetometer object data Parameter in which the magnetometer XYZ data gets collected in micro tesla RETCODE_SUCCESS Reading Magnetometer xyzTesladata success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle or NULL pointer. In case of other failures refer readMagData or Bmm150Utils_remapAxis API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E. Whenever there is an overflow in any axis this API will return the maximum value the sensor could read for that axis below are the maximum value the sensor could read x-axis - 20800, y-axis - 20800, z-axis - 40000
References RETCODE_FAILURE, NULL, Magnetometer_Handle_S::SensorPtr, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Magnetometer_Handle_S::SensorInformation, Magnetometer_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Magnetometer_SensorInfo_S::sensorID, MAGNETOMETER_BMM150, readMagData, RETCODE_OK, AxisRemap_Data_S::x, bmm050_mag_s32_data_t::datax, BMM150_CONVERSION_FACTOR, AxisRemap_Data_S::y, bmm050_mag_s32_data_t::datay, AxisRemap_Data_S::z, bmm050_mag_s32_data_t::dataz, Bmm150Utils_remapAxis, Magnetometer_XyzData_S::xAxisData, Magnetometer_XyzData_S::yAxisData, Magnetometer_XyzData_S::zAxisData, Magnetometer_XyzData_S::resistance, bmm050_mag_s32_data_t::resistance, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Referenced by LWM2MSensorDeviceMagnetometer_Update.
Retcode_T Magnetometer_setDataRate(Magnetometer_HandlePtr_T handle, Magnetometer_DataRate_T datarate)
Function to set the Datarate of the Magnetometer sensor.
handle handle of the Magnetometer object datarate Datarate to be set to the sensor RETCODE_SUCCESS Setting data rate success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of setting data rate other than Magnetometer_DataRate_E. In case of other failures refer bmm150LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, BMM050_RETURN_FUNCTION_TYPE, E_BMM050_NULL_PTR, NULL, Magnetometer_Handle_S::SensorPtr, MAGNETOMETER_DATARATE_OUT_OF_RANGE, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Magnetometer_Handle_S::SensorInformation, Magnetometer_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Magnetometer_SensorInfo_S::sensorID, MAGNETOMETER_BMM150, MAGNETOMETER_BMM150_DATARATE_30HZ, RETCODE_NOT_SUPPORTED, bmm050_set_data_rate, dataRateLookUpTable, bmm150LibErrorMapping, RETCODE_OK, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T Magnetometer_setPowerMode(Magnetometer_HandlePtr_T handle, Magnetometer_PowerMode_T powerMode)
Function to set the powermode of the Magnetometer sensor.
handle handle of the Magnetometer object powerMode powermode to be set to the sensor RETCODE_SUCCESS Setting power mode success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of setting power mode other than Magnetometer_PowerMode_E. In case of other failures refer bmm150LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, BMM050_RETURN_FUNCTION_TYPE, E_BMM050_NULL_PTR, NULL, Magnetometer_Handle_S::SensorPtr, MAGNETOMETER_POWERMODE_OUT_OF_RANGE, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Magnetometer_Handle_S::SensorInformation, Magnetometer_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Magnetometer_SensorInfo_S::sensorID, MAGNETOMETER_BMM150, MAGNETOMETER_BMM150_POWERMODE_SLEEP, RETCODE_NOT_SUPPORTED, bmm050_set_functional_state, modeLookUpTable, bmm150LibErrorMapping, RETCODE_OK, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
Retcode_T Magnetometer_setPresetMode(Magnetometer_HandlePtr_T handle, Magnetometer_PresetMode_T presetMode)
Function to set the preset mode of the Magnetometer sensor.
handle handle of the Magnetometer object presetMode presetMode to be set to the sensor RETCODE_SUCCESS Setting preset mode success. RETCODE_UNINITIALIZED if called without initializing the sensor. RETCODE_INVALID_PARAM In case of invalid sensor handle. RETCODE_NOT_SUPPORTED In case of setting preset mode other than Magnetometer_PresetMode_E. In case of other failures refer bmm150LibErrorMapping API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Pass the return value of this function to BCDS_getSensorErrorCode API to know the sensor return code present in BCDS_SensorErrorType_E.
References RETCODE_FAILURE, BMM050_RETURN_FUNCTION_TYPE, E_BMM050_NULL_PTR, NULL, Magnetometer_Handle_S::SensorPtr, MAGNETOMETER_PRESETMODE_OUT_OF_RANGE, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, INIT_NOT_DONE, Magnetometer_Handle_S::SensorInformation, Magnetometer_SensorInfo_S::initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Magnetometer_SensorInfo_S::sensorID, MAGNETOMETER_BMM150, MAGNETOMETER_BMM150_PRESETMODE_ENHANCED, RETCODE_NOT_SUPPORTED, bmm050_set_presetmode, presetModeLookUpTable, bmm150LibErrorMapping, RETCODE_OK, Retcode_GetPackage, PACKAGE_ID_DEFAULT.
static int8_t mappingEnumForGetFunctions(uint8_t start, uint8_t end, uint8_t getValueToBeTransalated, const uint8_t *lookUpTablePtr)
References GET_MAPPING_ERROR.
Referenced by Magnetometer_getPowerMode, Magnetometer_getPresetMode, Magnetometer_getDataRate.
static Retcode_T readMagData(struct bmm050_mag_s32_data_t *magData)
This function used read the sensor data.
bmm050_mag_s32_data_t structure to hold the data RETCODE_OK BMM150 sensor API call success RETCODE_FAILURE BMM150 sensor API call failed RETCODE_INVALID_PARAM BMM150 sensor API call failed because of invalid input parameter
References RETCODE_FAILURE, BMM050_RETURN_FUNCTION_TYPE, E_BMM050_NULL_PTR, NULL, RETCODE_INVALID_PARAM, bmm050_read_mag_data_XYZ_s32, bmm150LibErrorMapping, RETCODE_OK, BMM050_OVERFLOW_OUTPUT_S32, bmm050_mag_s32_data_t::datax, BMM150_MAX_LIMIT_XAXIS, bmm050_mag_s32_data_t::datay, BMM150_MAX_LIMIT_YAXIS, bmm050_mag_s32_data_t::dataz, BMM150_MAX_LIMIT_ZAXIS.
Referenced by Magnetometer_readXyzLsbData, Magnetometer_readXyzTeslaData.