Max44009Utils.c
BCDS_MODULE_ID
bool initializationStatus
< variable to check initialization status MAX44009 initialization structure
Referenced by Max44009Utils_initialize, Max44009Utils_configInterrupt, Max44009Utils_disableInterrupt, Max44009Utils_uninitialize.
MAX44009_Init_T max44009Initialization
static Retcode_T configureThresholdInterrupt(Max44009Utils_ThresholdIntrConfigPtr_T interruptConfig)
Function responsible to configure Threshold interrupt conditions in the support layer.
interruptConfig structure representing to Threshold interrupt configuration RETCODE_OK MAX44009 sensor configure Threshold interrupt success. RETCODE_FAILURE MAX44009 sensor configure Threshold interrupt failed. RETCODE_INVALID_PARAM MAX44009 sensor configure Threshold interrupt failed because of invalid input parameter.
References RETCODE_FAILURE, MAX44009_SetUpperThreshold, Max44009Utils_ThresholdIntrConfig_S::upperThreshold, RETCODE_OK, MAX44009_SetLowerThreshold, Max44009Utils_ThresholdIntrConfig_S::lowerThreshold, MAX44009_SetThresholdTimer, Max44009Utils_ThresholdIntrConfig_S::thresholdTimer, MAX44009_SetIntrptReg, MAX44009_ENABLE_INTERRUPT.
Referenced by Max44009Utils_configInterrupt.
Retcode_T Max44009Utils_configInterrupt(Max44009Utils_ThresholdIntrConfigPtr_T interruptConfig)
Function to Configure interrupts of Max44009. Before calling this API Update the below information in the appropriate structure 1) Update callback function in Max44009Utils_InfoPtr_T. 2) Update the type of callback(deferred or real time) in Max44009Utils_InfoPtr_T. After calling this API the given interrupt will be enabled and the callback will be associated with the interrupt.
interruptConfig :Structure holding the information about interrupt related configuration should be given here RETCODE_OK Max44009 interrupt configuration success RETCODE_NULL_POINTER when interruptConfig is NULL. RETCODE_UNINITIALIZED when this api is called before initializing Bma280 sensor. In case of other failures refer #MAX44009_setUpperThreshold or #MAX44009_setLowerThreshold or #MAX44009_setThresholdTimer or #MAX44009_setIntrptReg API's. The return value consist of (First MSB Byte represents Package ID,Next Byte represents Severity and Last 2LSB Bytes represents error code).
References RETCODE_FAILURE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, configureThresholdInterrupt.
Referenced by LightSensor_configureThresholdInterrupt.
Retcode_T Max44009Utils_disableInterrupt()
Function to Disable the Interrupt.Max44009 sensor supports only Threshold Interrupt. So, calling this API will disable Max44009 Threshold interrupt explicitly.
RETCODE_OK Max44009 disable interrupt success RETCODE_UNINITIALIZED when this api is called before initializing Bma280 sensor. In case of other failures refer #MAX44009_setIntrptReg API. The return value consist of (First MSB Byte represents Package ID,Next Byte represents Severity and Last 2LSB Bytes represents error code).
References RETCODE_FAILURE, initializationStatus, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, MAX44009_SetIntrptReg, MAX44009_DISABLE_INTERRUPT.
Referenced by LightSensor_disableInterrupt.
Retcode_T Max44009Utils_initialize(Max44009Utils_InfoPtr_T max44009Info)
Function to initialize Max44009. This needs to be called before calling any other API.
max44009Info :structure holding the Max44009 specific configurations RETCODE_OK Max44009 initialized successfully RETCODE_NULL_POINTER when any of the input parameter(max44009Info or max44009Info->ISRCallback) is NULL. RETCODE_DOPPLE_INITIALIZATION When initialization is already done. In case of other failures refer BSP_SensorNode_Enable or #I2CSensorTransceiver_Init or #MAX44009_init or #MAX44009_setCdr or #MAX44009_setIntegrationTime or #MAX44009_setContinousModeReg API's. 1) The return value consist of (First MSB Byte represents Package ID,Next Byte represents Severity and Last 2LSB Bytes represents error code). 2) The support of multiple instances is not possible due to the limitation in the library. 3) Calling Max44009 initialization API present in sensorUtils (Max44009Utils_initialize) and sensorDriver (MAX09_init) concurrently will lead to unexpected behaviour.
References RETCODE_FAILURE, NULL, Max44009Utils_Info_S::ISRCallback, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, initializationStatus, RETCODE_SEVERITY_WARNING, RETCODE_DOPPLE_INITIALIZATION, SensorNodeMapping_Init, RETCODE_OK, BSP_SensorNode_Enable, Max44009Utils_Info_S::BspSensorId, MAX44009_Init_S::readFunc, SensorNodeMapping_Read, MAX44009_Init_S::writeFunc, SensorNodeMapping_Write, MAX44009_Init_S::delayFunc, BSP_Board_Delay, MAX44009_Init_S::dev_add, Max44009Utils_Info_S::dev_addr, MAX44009_Init, MAX44009_SetIntegrationTime, MAX44009_100MS, MAX44009_SetCdr, MAX44009_HIGH_BRIGHTNESS, MAX44009_SetContinousModeReg, MAX44009_ENABLE_CONTINOUS_MODE.
Referenced by LightSensor_init.
Retcode_T Max44009Utils_uninitialize(Max44009Utils_InfoPtr_T max44009Info)
Function to uninitialize Max44009.After calling this API sensor is no more usable without initializing it again by calling Max44009Utils_initialize() API.
max44009Info :structure holding the Max44009 specific configurations RETCODE_OK Max44009 un-initialization success RETCODE_NULL_POINTER when max44009Info is NULL. RETCODE_UNINITIALIZED when this api is called before initializing Bma280 sensor. In case of other failures refer BSP_SensorNode_Disable or BSP_SensorNode_IsAllNodesDisabled or #I2CSensorTransceiver_Deinit API. The return value consist of (First MSB Byte represents Package ID,Next Byte represents Severity and Last 2LSB Bytes represents error code).
References RETCODE_FAILURE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, MAX44009_DeInit, BSP_SensorNode_Disable, Max44009Utils_Info_S::BspSensorId, RETCODE_OK, SensorNodeMapping_DeInit.
Referenced by LightSensor_deInit.