Mcu_Adc.c
ADC_MAX_SAMPLING_FREQUENCY
ADC_MIN_SAMPLING_FREQUENCY
Referenced by Mcu_Adc_StartScan.
MASK_IEN_ADC_SCAN
MASK_IEN_ADC_SINGLE
PRS_CHANNEL_NO_ADC_FROM_TIMER0
Referenced by Mcu_Adc_StartScan.
PRS_CHANNEL_NO_TIMER0_TO_ADC
Referenced by Adc_PrsChannelSetup.
uint16_t* globalBufferSwitchPtr
Referenced by Adc_McuIrqCallback, Mcu_Adc_StartScan.
uint16_t ReqNoOfSamplesInScan
Referenced by Adc_McuIrqCallback, Mcu_Adc_StartScan.
const ADC_SingleInput_TypeDef singleChannelArray[ADC_ENABLE_CH_MAX][ADC_ENABLE_CH_MAX]
Referenced by Mcu_Adc_StartSingle.
void Adc_McuIrqCallback(ADC_T adc)
References RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_FAILURE, NULL, Mcu_Adc_Handle_S::_DriverCtx, Mcu_Adc_Driver_S::AppCallback, Retcode_RaiseErrorFromIsr, RETCODE_NULL_POINTER, Mcu_Adc_Handle_S::Instance, globalBufferSwitchPtr, ReqNoOfSamplesInScan, Mcu_Adc_Driver_S::NumOfSamples, Mcu_Adc_Driver_S::ScanBuffer2, Mcu_Adc_Driver_S::ScanBuffer1, Mcu_Adc_Event_U::Bitfield, Mcu_Adc_Driver_S::SingleBuffer.
Referenced by Mcu_Adc_Initialize.
static void Adc_PrsChannelSetup(void)
References PRS_CHANNEL_NO_TIMER0_TO_ADC.
Referenced by Mcu_Adc_StartScan.
static Retcode_T Adc_SamplingTimerSetup(uint32_t samplingFreqInHz)
References RETCODE_OK, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM.
Referenced by Mcu_Adc_StartScan.
static uint8_t findNoOfScanChannel(uint32_t channelMask)
Referenced by Mcu_Adc_StartScan.
Retcode_T Mcu_Adc_DeInitialize(ADC_T adc)
See interface function description in Mcu_Adc.h.
De-initialize and powers down the ADC interface.
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, Mcu_Adc_Handle_S::_DriverCtx, Mcu_Adc_Driver_S::Initialized, BCDS_HAL_TRANSFER_MODE_DMA, Mcu_Adc_Handle_S::TransferMode, Mcu_Adc_Handle_S::DmaScanCallback, Mcu_Adc_Handle_S::DmaSingleCallback, BCDS_HAL_TRANSFER_MODE_INTERRUPT, Mcu_Adc_Handle_S::IRQCallback, Mcu_Adc_Driver_S::AppCallback, RETCODE_UNINITIALIZED.
Referenced by AdcCentral_DeInit.
Retcode_T Mcu_Adc_Initialize(ADC_T adc, Mcu_Adc_Callback_T callback)
See interface function description in Mcu_Adc.h.
Initialize the ADC Interface.
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, Mcu_Adc_Handle_S::_DriverCtx, Mcu_Adc_Driver_S::Initialized, RETCODE_DOPPLE_INITIALIZATION, BCDS_HAL_TRANSFER_MODE_DMA, Mcu_Adc_Handle_S::TransferMode, Mcu_Adc_Handle_S::Link1RegPtr, Mcu_Adc_Handle_S::Link2RegPtr, Mcu_Adc_Handle_S::DmaScanCallback, McuAdcDmaScanChannelCb, MCU_DMA_Channel_S::Config, MCU_DMA_Channel_S::CallBack, MCU_DMA_Channel_S::ChannelId, Mcu_Adc_Handle_S::DmaSingleCallback, McuAdcDmaSingleChannelCb, RETCODE_ADC_NULL_DMA_CALLBACK, BCDS_HAL_TRANSFER_MODE_INTERRUPT, Mcu_Adc_Handle_S::IRQCallback, Adc_McuIrqCallback, Mcu_Adc_Driver_S::AppCallback.
Referenced by AdcCentral_Init.
Retcode_T Mcu_Adc_StartScan(ADC_T adc, Mcu_Adc_ConfigScanPtr_T configScan)
See interface function description in Mcu_Adc.h.
Start Scan Mode on ADC Interface & Start the PRS Timer as producer.
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, ADC_MIN_SAMPLING_FREQUENCY, Mcu_Adc_ConfigScan_S::SamplingRateInHz, RETCODE_INVALID_PARAM, Mcu_Adc_Handle_S::Instance, Mcu_Adc_Handle_S::_DriverCtx, Mcu_Adc_Driver_S::NumOfSamples, Mcu_Adc_ConfigScan_S::NoOfSamples, Mcu_Adc_Driver_S::NumOfScanChannels, findNoOfScanChannel, Mcu_Adc_ConfigScan_S::ChannelScanMask, Mcu_Adc_Driver_S::ScanBuffer1, Mcu_Adc_ConfigScan_S::BufferPtr, Mcu_Adc_Driver_S::ScanBuffer2, Mcu_Adc_ConfigScan_S::Reference, PRS_CHANNEL_NO_ADC_FROM_TIMER0, Mcu_Adc_ConfigScan_S::AcqTime, Mcu_Adc_ConfigScan_S::Resolution, Adc_PrsChannelSetup, BCDS_HAL_TRANSFER_MODE_INTERRUPT, Mcu_Adc_Handle_S::TransferMode, ReqNoOfSamplesInScan, globalBufferSwitchPtr, BCDS_HAL_TRANSFER_MODE_DMA, Mcu_Adc_Handle_S::Link1RegPtr, MCU_DMA_Channel_S::ChannelId, Adc_SamplingTimerSetup.
Referenced by AdcCentral_StartScan, AdcCentral_StopScan.
Retcode_T Mcu_Adc_StartSingle(ADC_T adc, Mcu_Adc_ConfigSinglePtr_T configStart)
See interface function description in Mcu_Adc.h.
Start Single Mode on ADC Interface.
References RETCODE_OK, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM, NULL, RETCODE_NULL_POINTER, Mcu_Adc_Handle_S::_DriverCtx, Mcu_Adc_Driver_S::SingleBuffer, Mcu_Adc_ConfigSingle_S::BufferPtr, singleChannelArray, Mcu_Adc_ConfigSingle_S::Channel, Mcu_Adc_ConfigSingle_S::Reference, Mcu_Adc_ConfigSingle_S::AcqTime, Mcu_Adc_ConfigSingle_S::Resolution, Mcu_Adc_Handle_S::Instance, BCDS_HAL_TRANSFER_MODE_INTERRUPT, Mcu_Adc_Handle_S::TransferMode, BCDS_HAL_TRANSFER_MODE_DMA, Mcu_Adc_Handle_S::Link2RegPtr, MCU_DMA_Channel_S::ChannelId.
Referenced by AdcCentral_StartSingle.
Retcode_T Mcu_Adc_StopScan(ADC_T adc)
See interface function description in Mcu_Adc.h.
Stop the Scan mode on ADC Interface and stops the PRS timer used for sampling adc channels.
References RETCODE_OK, Mcu_Adc_Handle_S::Link1RegPtr, Mcu_Adc_Handle_S::Instance, BCDS_HAL_TRANSFER_MODE_INTERRUPT, Mcu_Adc_Handle_S::TransferMode, BCDS_HAL_TRANSFER_MODE_DMA, MCU_DMA_Channel_S::ChannelId.
Referenced by AdcCentral_DeInit, AdcCentral_StartScan, AdcCentral_StopScan.
static void McuAdcDmaScanChannelCb(ADC_T adc)
References Mcu_Adc_Handle_S::_DriverCtx, Mcu_Adc_Driver_S::PointerValue, Mcu_Adc_Event_U::RegisterValue, Mcu_Adc_Driver_S::ScanBuffer1, Mcu_Adc_Driver_S::ScanBuffer2, Mcu_Adc_Driver_S::AppCallback, Mcu_Adc_Event_U::Bitfield.
Referenced by Mcu_Adc_Initialize.
static void McuAdcDmaSingleChannelCb(ADC_T adc)
References Mcu_Adc_Event_U::RegisterValue, Mcu_Adc_Handle_S::_DriverCtx, Mcu_Adc_Driver_S::AppCallback, Mcu_Adc_Event_U::Bitfield, Mcu_Adc_Driver_S::SingleBuffer.
Referenced by Mcu_Adc_Initialize.