Mcu_Adc.h
Adc_AcqTime_E
1 clock cycle.
Adc_Channel_E
Adc_Reference_E
Internal 1.25V reference.
Adc_Resolution_E
12 bit sampling.
Adc_ScanChannelMask_E
typedef enum Adc_AcqTime_E Adc_AcqTime_T
typedef enum Adc_Channel_E Adc_Channel_T
typedef enum Adc_Reference_E Adc_Reference_T
typedef enum Adc_Resolution_E Adc_Resolution_T
typedef HWHandle_T ADC_T
ADC_T is a generic hardware handle,which is void pointer guaranteed to store pointer to integer.
typedef void(* Mcu_Adc_Callback_T)(ADC_T adc, Mcu_Adc_Event_T event, uint16_t *bufferPtr))(ADC_T adc, Mcu_Adc_Event_T event, uint16_t *bufferPtr)
Application callback template.
adc MCU handle for ADC event Represents the various application events bufferPtr Represents the pointer value of the result buffer for processing
typedef struct Mcu_Adc_ConfigScan_S Mcu_Adc_ConfigScan_T
typedef struct Mcu_Adc_ConfigScan_S * Mcu_Adc_ConfigScanPtr_T
typedef struct Mcu_Adc_ConfigSingle_S Mcu_Adc_ConfigSingle_T
typedef struct Mcu_Adc_ConfigSingle_S * Mcu_Adc_ConfigSinglePtr_T
typedef struct Mcu_Adc_Event_S Mcu_Adc_Event_T
Retcode_T Mcu_Adc_DeInitialize(ADC_T adc)
De-initialize and powers down the ADC interface.
adc : ADC handle. RETCODE_OK upon successful execution, error otherwise De-initialize and powers down the ADC interface.
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, Mcu_Adc_Handle_S::_DriverCtx, Mcu_Adc_Driver_S::Initialized, BCDS_HAL_TRANSFER_MODE_DMA, Mcu_Adc_Handle_S::TransferMode, Mcu_Adc_Handle_S::DmaScanCallback, Mcu_Adc_Handle_S::DmaSingleCallback, BCDS_HAL_TRANSFER_MODE_INTERRUPT, Mcu_Adc_Handle_S::IRQCallback, Mcu_Adc_Driver_S::AppCallback, RETCODE_UNINITIALIZED.
Referenced by AdcCentral_DeInit.
Retcode_T Mcu_Adc_Initialize(ADC_T adc, Mcu_Adc_Callback_T callback)
Initialize the ADC Interface.
adc : ADC handle. callback : Function pointer to a callback function which handles the ADC events. RETCODE_OK upon successful execution, error otherwise Initialize the ADC Interface.
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, Mcu_Adc_Handle_S::_DriverCtx, Mcu_Adc_Driver_S::Initialized, RETCODE_DOPPLE_INITIALIZATION, BCDS_HAL_TRANSFER_MODE_DMA, Mcu_Adc_Handle_S::TransferMode, Mcu_Adc_Handle_S::Link1RegPtr, Mcu_Adc_Handle_S::Link2RegPtr, Mcu_Adc_Handle_S::DmaScanCallback, McuAdcDmaScanChannelCb, MCU_DMA_Channel_S::Config, MCU_DMA_Channel_S::CallBack, MCU_DMA_Channel_S::ChannelId, Mcu_Adc_Handle_S::DmaSingleCallback, McuAdcDmaSingleChannelCb, RETCODE_ADC_NULL_DMA_CALLBACK, BCDS_HAL_TRANSFER_MODE_INTERRUPT, Mcu_Adc_Handle_S::IRQCallback, Adc_McuIrqCallback, Mcu_Adc_Driver_S::AppCallback.
Referenced by AdcCentral_Init.
Retcode_T Mcu_Adc_StartScan(ADC_T adc, Mcu_Adc_ConfigScanPtr_T configScan)
Start Scan Mode on ADC Interface & Start the PRS Timer as producer.
adc : ADC handle. configScan : Structure which holds the configurations related to scan mode. The sampling rate must be limited to minimum and maximum range mentioned by macro ADC_MIN_SAMPLING_FREQUENCY and ADC_MAX_SAMPLING_FREQUENCY respectively RETCODE_OK upon successful execution, error otherwise Start Scan Mode on ADC Interface & Start the PRS Timer as producer.
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, ADC_MIN_SAMPLING_FREQUENCY, Mcu_Adc_ConfigScan_S::SamplingRateInHz, RETCODE_INVALID_PARAM, Mcu_Adc_Handle_S::Instance, Mcu_Adc_Handle_S::_DriverCtx, Mcu_Adc_Driver_S::NumOfSamples, Mcu_Adc_ConfigScan_S::NoOfSamples, Mcu_Adc_Driver_S::NumOfScanChannels, findNoOfScanChannel, Mcu_Adc_ConfigScan_S::ChannelScanMask, Mcu_Adc_Driver_S::ScanBuffer1, Mcu_Adc_ConfigScan_S::BufferPtr, Mcu_Adc_Driver_S::ScanBuffer2, Mcu_Adc_ConfigScan_S::Reference, PRS_CHANNEL_NO_ADC_FROM_TIMER0, Mcu_Adc_ConfigScan_S::AcqTime, Mcu_Adc_ConfigScan_S::Resolution, Adc_PrsChannelSetup, BCDS_HAL_TRANSFER_MODE_INTERRUPT, Mcu_Adc_Handle_S::TransferMode, ReqNoOfSamplesInScan, globalBufferSwitchPtr, BCDS_HAL_TRANSFER_MODE_DMA, Mcu_Adc_Handle_S::Link1RegPtr, MCU_DMA_Channel_S::ChannelId, Adc_SamplingTimerSetup.
Referenced by AdcCentral_StartScan, AdcCentral_StopScan.
Retcode_T Mcu_Adc_StartSingle(ADC_T adc, Mcu_Adc_ConfigSinglePtr_T configStart)
Start Single Mode on ADC Interface.
adc : ADC handle. configStart : Structure which holds the configurations related to single mode. RETCODE_OK upon successful execution, error otherwise Start Single Mode on ADC Interface.
References RETCODE_OK, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM, NULL, RETCODE_NULL_POINTER, Mcu_Adc_Handle_S::_DriverCtx, Mcu_Adc_Driver_S::SingleBuffer, Mcu_Adc_ConfigSingle_S::BufferPtr, singleChannelArray, Mcu_Adc_ConfigSingle_S::Channel, Mcu_Adc_ConfigSingle_S::Reference, Mcu_Adc_ConfigSingle_S::AcqTime, Mcu_Adc_ConfigSingle_S::Resolution, Mcu_Adc_Handle_S::Instance, BCDS_HAL_TRANSFER_MODE_INTERRUPT, Mcu_Adc_Handle_S::TransferMode, BCDS_HAL_TRANSFER_MODE_DMA, Mcu_Adc_Handle_S::Link2RegPtr, MCU_DMA_Channel_S::ChannelId.
Referenced by AdcCentral_StartSingle.
Retcode_T Mcu_Adc_StopScan(ADC_T adc)
Stop the Scan mode on ADC Interface and stops the PRS timer used for sampling adc channels.
adc : ADC handle. RETCODE_OK upon successful execution, error otherwise Stop the Scan mode on ADC Interface and stops the PRS timer used for sampling adc channels.
References RETCODE_OK, Mcu_Adc_Handle_S::Link1RegPtr, Mcu_Adc_Handle_S::Instance, BCDS_HAL_TRANSFER_MODE_INTERRUPT, Mcu_Adc_Handle_S::TransferMode, BCDS_HAL_TRANSFER_MODE_DMA, MCU_DMA_Channel_S::ChannelId.
Referenced by AdcCentral_DeInit, AdcCentral_StartScan, AdcCentral_StopScan.