NetworkConfig.c
BCDS_MODULE_ID
NETWORKCONFIG_FAILURE
Macro for defining -1
NETWORKCONFIG_ONE
Macro for defining 1
NETWORKCONFIG_SUCCESS
Macro for defining 0
NETWORKCONFIG_TIMEOUT
Macro for defining timeout
NETWORKCONFIG_ZERO
Macro for defining 0
volatile NetworkConfig_IpCallback_T IpConfigCallback
Variable for storing the DHCP IP callback
volatile NetworkConfig_IpStatus_T NetworkIpStatus
Flag variable for IP obtained status
Referenced by NetworkConfig_SetIpStatus.
Retcode_T NetworkConfig_GetIpAddress(uint8_t *url, uint32_t *destAddr)
References WlanNetworkConfig_GetIpAddress.
Retcode_T NetworkConfig_GetIpSettings(NetworkConfig_IpSettings_T *myIpSettings)
References WlanNetworkConfig_GetIpSettings.
NetworkConfig_IpStatus_T NetworkConfig_GetIpStatus(void)
References WlanNetworkConfig_GetIpStatus.
Referenced by connectNonBlockingCall, connectBlockingCall, WlanConnect_GetCurrentNwStatus.
uint8_t NetworkConfig_Ipv4Byte(uint32_t ipValue, uint8_t index)
References SL_IPV4_BYTE.
uint32_t NetworkConfig_Ipv4Value(uint8_t add3, uint8_t add2, uint8_t add1, uint8_t add0)
References SL_IPV4_VAL.
Retcode_T NetworkConfig_SetIpDhcp(NetworkConfig_IpCallback_T myIpCallback)
References WlanNetworkConfig_SetIpDhcp.
Retcode_T NetworkConfig_SetIpStatic(NetworkConfig_IpSettings_T myIpSettings)
References WlanNetworkConfig_SetIpStatic.
void NetworkConfig_SetIpStatus(NetworkConfig_IpStatus_T ipStatus)
References NetworkIpStatus.