NoiseSensor.c
BCDS_MODULE_ID
HWHandle_T AdcHandle
Referenced by NoiseSensor_Enable, NoiseSensor_ReadRmsValue, NoiseSensor_Disable.
uint16_t CH4UserBuffer[ADC_CENTRAL_NO_OF_SAMPLES][ADC_CENTRAL_NO_OF_SAMPLES]
Referenced by ProcessCH4Data, NoiseSensor_Enable.
AdcCentral_ConfigScan_T ConfigScan
QueueHandle_t RmsQueue
Referenced by ProcessCH4Data, NoiseSensor_Setup, NoiseSensor_ReadRmsValue.
Retcode_T NoiseSensor_Close(void)
To close noise sensor module.
RETCODE_OK upon successful execution
References RETCODE_OK.
Retcode_T NoiseSensor_Disable(void)
Disable the noise sensor module and stop adc scan.
RETCODE_OK upon successful execution In case of any other error code refer AdcCentral_StopScan
References RETCODE_OK, AdcCentral_StopScan, AdcHandle, AdcCentral_ConfigScan_S::ChannelScanMask, BSP_Mic_AKU340_Disable, BSP_Mic_AKU340_Disconnect, NULL.
Retcode_T NoiseSensor_Enable(void)
Enable the noise sensor, Configure the ADC parameters and start ADC scan.
RETCODE_OK on success RETCODE_NULL_POINTER if the Adc resource handle is NULL In case of any other error code refer AdcCentral_StartScan Channel-4 is used for ADC to read the noise sensor data. ADC Resolution as 12 bit
References RETCODE_OK, BSP_Mic_AKU340_Connect, BSP_Mic_AKU340_Enable, AdcHandle, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, AdcCentral_ConfigScan_S::BufferPtr, CH4UserBuffer, AdcCentral_ConfigScan_S::Appcallback, ProcessCH4Data, AdcCentral_ConfigScan_S::ChannelScanMask, ADC_ENABLE_CH4_SCAN, AdcCentral_StartScan.
Referenced by AppControllerEnable.
Retcode_T NoiseSensor_ReadRmsValue(float *rmsValue, uint32_t timeout)
To read the last calculated RMS voltage.
rmsValue Calculated RMS voltage for the range of 256 samples timeout in milli seconds Timeout to read the RmsVoltage RETCODE_OK upon successful execution RETCODE_RTOS_QUEUE_ERROR if queue create fails RETCODE_NULL_POINTER if the pointer is NULL RETCODE_NOISE_SENSOR_ENABLE_FAILED if noise sensor enable fails RETCODE_NO_DATA_ON_QUEUE if no data available on queue If the calculated value isn't available in queue then it will wait until the data availability
References RETCODE_OK, NULL, AdcHandle, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NOISE_SENSOR_ENABLE_FAILED, RmsQueue, xQueueReceive, RETCODE_NO_DATA_ON_QUEUE, RETCODE_RTOS_QUEUE_ERROR, RETCODE_NULL_POINTER.
Referenced by NoiseSensorTask.
Retcode_T NoiseSensor_Setup(uint32_t samplingFreqency)
Initialize the required components and variables of noise sensor module.
samplingFreqency Adc Sampling frequency in hertz (Hz) RETCODE_OK upon successful initialization RETCODE_RTOS_QUEUE_ERROR if freertos queue create fails
References RETCODE_OK, RmsQueue, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_RTOS_QUEUE_ERROR, AdcCentral_Init, AdcCentral_ConfigScan_S::SamplingRateInHz.
Referenced by AppControllerSetup.
static void ProcessCH4Data(ADC_T adc, uint32_t samplingFreq, uint16_t *bufferPtr)
References BCDS_UNUSED, ADC_CENTRAL_NO_OF_SAMPLES, CH4UserBuffer, ADC_CONVERSION_FACTOR, NULL, RmsQueue, xQueueOverwrite, Retcode_RaiseError, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_QUEUE_WRITE_FAILED.
Referenced by NoiseSensor_Enable.