AppController.c
APP_HTTP_COMM_ISSUE_COUNT_FOR_RESET
APP_HTTP_COMM_ISSUE_COUNT_FOR_RESET is an application logic count where-in upon encountering those many consecutive server communication failures the node will reset.
Referenced by AppControllerFire.
APP_POST_REQUEST_CUSTOM_HEADER_0
APP_POST_REQUEST_CUSTOM_HEADER_0 is a custom header which is sent along with the POST request.
APP_POST_REQUEST_CUSTOM_HEADER_1
APP_POST_REQUEST_CUSTOM_HEADER_1 is a custom header which is sent along with the POST request.
APP_REQUEST_MAX_DOWNLOAD_SIZE
The maximum amount of data we download in a single request (in bytes). This number is limited by the platform abstraction layer implementation that ships with the XDK. The maximum value that will work here is 512 bytes.
APP_RESPONSE_FROM_HTTP_SERVER_POST_TIMEOUT
Timeout for completion of HTTP rest client POST
Referenced by AppControllerFire.
APP_RESPONSE_FROM_SNTP_SERVER_TIMEOUT
Timeout for SNTP server time sync
Referenced by AppControllerFire.
APP_SENSORS_PAYLOAD_TO_BE_SERIALIZED
APP_SENSORS_PAYLOAD_TO_BE_SERIALIZED is an application logic count which will define the number of sensor payloads to be serialized.
Referenced by AppControllerFire.
APP_SENSORS_TO_BE_SERIALIZED_PER_PAYLOAD
APP_SENSORS_TO_BE_SERIALIZED_PER_PAYLOAD is an application logic count which will define the number of sensors to be serialized per send.
Referenced by AppControllerFire.
BCDS_MODULE_ID
CmdProcessor_T* AppCmdProcessor
Handle to store the main Command processor handle to be reused by ServalPAL thread
Referenced by AppControllerSetup.
xTaskHandle AppControllerHandle
OS thread handle for Application controller
Referenced by AppControllerEnable.
HTTPRestClient_Config_T HTTPRestClientConfigInfo
HTTP rest client configuration parameters
HTTPRestClient_Post_T HTTPRestClientPostMeasurementInfo
HTTP rest client POST parameters
HTTPRestClient_Setup_T HTTPRestClientSetupInfo
HTTP rest client setup parameters
PPMPSerializer_Setup_T PPMPSerializerSetup
PPMP serializer setup parameters
Sensor_Setup_T SensorSetup
Sensor setup parameters
SNTP_Setup_T SNTPSetupInfo
SNTP setup parameters
WLAN_Setup_T WLANSetupInfo
WLAN setup parameters
void AppController_Init(void *cmdProcessorHandle, uint32_t param2)
Gives control to the Application controller.
This is a template function where the user can write his custom application.Refer interface header for description
References BCDS_UNUSED, RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, CmdProcessor_Enqueue, AppControllerSetup, Retcode_RaiseError, assert.
static void AppControllerEnable(void *param1, uint32_t param2)
To enable the necessary modules for the application.
WLANServalPALSNTPHTTP rest clientPPMP SerializerSensor param1 Unused param2 Unused
References BCDS_UNUSED, WLAN_Enable, RETCODE_OK, ServalPAL_Enable, SNTP_Enable, HTTPRestClient_Enable, PPMPSerializer_Enable, Sensor_Enable, AppControllerFire, TASK_STACK_SIZE_APP_CONTROLLER, NULL, TASK_PRIO_APP_CONTROLLER, AppControllerHandle, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_OUT_OF_RESOURCES, Retcode_RaiseError, assert, Utils_PrintResetCause.
Referenced by AppControllerSetup.
static void AppControllerFire(void *pvParameters)
Responsible for controlling the PPMP Example application control flow.
Check whether the network connection is availableSynchronize the SNTP server for timestampSample the node dataConstruct the PPMP payloadPOST it to the serverWait for APP_POST_INTERVAL_MS before proceeding to redoing the above steps pvParameters Unused
References BCDS_UNUSED, RETCODE_OK, Sensor_Setup_S::Enable, APP_SENSORS_PAYLOAD_TO_BE_SERIALIZED, NULL, APP_POST_INTERVAL_MS, Sensor_Enable_S::Accel, Sensor_Enable_S::Mag, Sensor_Enable_S::Gyro, Sensor_Enable_S::Humidity, Sensor_Enable_S::Temp, Sensor_Enable_S::Pressure, Sensor_Enable_S::Light, Sensor_Enable_S::Noise, APP_SENSORS_TO_BE_SERIALIZED_PER_PAYLOAD, Retcode_RaiseError, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INCONSITENT_STATE, assert, xTaskGetTickCount, AppControllerValidateWLANConnectivity, SNTP_GetTimeFromServer, APP_RESPONSE_FROM_SNTP_SERVER_TIMEOUT, SNTP_GetTimeFromSystem, Sensor_GetData, Sensor_Value_S::Temp, TimeStamp_SecsToTm, TimeStamp_TmToIso8601, PPMPSerializer_PayloadSensorSelective, HTTPRestClient_Post_S::Payload, HTTPRestClient_Post_S::PayloadLength, HTTPRestClient_Post, APP_RESPONSE_FROM_HTTP_SERVER_POST_TIMEOUT, vTaskDelay, vTaskDelayUntil, APP_SYNC_TIME_FOR_EVERY_POST, APP_SYNC_TIME_INTERVAL_MAX_MS, APP_HTTP_COMM_ISSUE_COUNT_FOR_RESET, BSP_Board_SoftReset.
Referenced by AppControllerEnable.
static void AppControllerSetup(void *param1, uint32_t param2)
To setup the necessary modules for the application.
WLANServalPALSNTPHTTP rest clientPPMP SerializerSensor param1 Unused param2 Unused
References BCDS_UNUSED, WLAN_Setup, RETCODE_OK, ServalPAL_Setup, SNTP_Setup, HTTPRestClient_Setup, PPMPSerializer_Setup, Sensor_Setup_S::CmdProcessorHandle, AppCmdProcessor, Sensor_Setup, CmdProcessor_Enqueue, AppControllerEnable, NULL, Retcode_RaiseError, assert.
Referenced by AppController_Init.
static void AppControllerValidateWLANConnectivity(void)
This will validate the WLAN network connectivity.
Currently, upon abrupt disconnection the event from the WiFi chip is not propagated / notified to the application. Until then, we manually validate prior to ever HTTP Rest Client POST/GET cycle to make sure that the possibility of software break is reduced. We check if the IP is valid to validate the same.If there is no connectivity we will restart the node after 10 seconds.
References RETCODE_OK, WLANNWCNF_IPSTATUS_IP_NOTAQRD, WlanNetworkConfig_GetIpStatus, WLANNWCNF_IPSTATUS_IPV4_AQRD, WlanNetworkConfig_GetIpSettings, WlanNetworkConfig_IpSettings_S::ipV4, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NODE_IPV4_IS_CORRUPTED, RETCODE_NODE_WLAN_CONNECTION_IS_LOST, Retcode_RaiseError, vTaskDelay, BSP_Board_SoftReset, assert.
Referenced by AppControllerFire.