AppController.c
BCDS_MODULE_ID
BUFFER_SIZE
Referenced by AppControllerFatFileSystemWriteRead.
DRIVE_ZERO
SD Card Drive 0 location
SECTOR_VALUE
SDC Disk sector value
Referenced by AppControllerFire.
SINGLE_BLOCK
SD- Card Single block write or read
SINGLE_SECTOR_LEN
Single sector size in SDcard
CmdProcessor_T* AppCmdProcessor
Handle to store the main Command processor handle to be used by run-time event driven threads
xTaskHandle AppControllerHandle
OS thread handle for Application controller to be used by run-time blocking threads
Referenced by AppControllerEnable.
Storage_Setup_T StorageSetupInfo
Storage setup parameters
void AppController_Init(void *cmdProcessorHandle, uint32_t param2)
Gives control to the Application controller.
This is a template function where the user can write his custom application.Refer interface header for description
References BCDS_UNUSED, RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, CmdProcessor_Enqueue, AppControllerSetup, Retcode_RaiseError, assert.
static void AppControllerEnable(void *param1, uint32_t param2)
To enable the necessary modules for the application.
SD CardLED param1 Unused param2 Unused
References BCDS_UNUSED, RETCODE_OK, Storage_Enable, RETCODE_STORAGE_SDCARD_NOT_AVAILABLE, Retcode_GetCode, Retcode_RaiseError, Storage_Delete, STORAGE_MEDIUM_SD_CARD, TEST_FILENAME, LED_Enable, AppControllerFire, TASK_STACK_SIZE_APP_CONTROLLER, NULL, TASK_PRIO_APP_CONTROLLER, AppControllerHandle, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_OUT_OF_RESOURCES, assert, Utils_PrintResetCause.
Referenced by AppControllerSetup.
static Retcode_T AppControllerFatFileSystemWriteRead(void)
ThIS API uses the FAT file system library calls. This API will write and read files and it will compare the contents which has been written and read.
RETCODE_OK - All the file operations are success SDCARD_APP_ERROR - when there is a mismatch in read and write buffer FILE_WRITE_ERROR - when file system write is failed FILE_READ_ERROR - when file system read is failed
References BUFFER_SIZE, DATA_TO_WRITE_IN_SDCARD, RETCODE_OK, Storage_Read_S::FileName, TEST_FILENAME, Storage_Write_S::FileName, Storage_Write_S::Offset, Storage_Write, STORAGE_MEDIUM_SD_CARD, Storage_Write_S::BytesToWrite, Storage_Write_S::ActualBytesWritten, Storage_Read_S::Offset, Storage_Read, RETCODE, RETCODE_SEVERITY_ERROR, FILE_WRITE_ERROR, Storage_Read_S::BytesToRead, Storage_Read_S::ActualBytesRead, FILE_READ_ERROR, SDCARD_APP_ERROR.
Referenced by AppControllerFire.
static void AppControllerFire(void *pvParameters)
Responsible for controlling the SD card example flow.
Check whether the storage medium (SD Card)is available or notif FAT_FILE_SYSTEM==1 then will write and read files and it will compare the contents which has been written and read.if FAT_FILE_SYSTEM==0 then it will write some string and read the string. then validate the written and read string. pvParameters Unused
References BCDS_UNUSED, RETCODE_OK, Storage_IsAvailable, STORAGE_MEDIUM_SD_CARD, LED_On, LED_INBUILT_RED, Storage_Disable, Storage_Enable, AppControllerFatFileSystemWriteRead, SECTOR_VALUE, Retcode_GetCode, RETCODE_STORAGE_SDCARD_UNINITIALIZED, LED_Off, Retcode_RaiseError, vTaskDelay, WRITEREAD_DELAY.
Referenced by AppControllerEnable.
static void AppControllerSetup(void *param1, uint32_t param2)
To setup the necessary modules for the application.
SD CardLED param1 Unused param2 Unused
References BCDS_UNUSED, RETCODE_OK, Storage_Setup, LED_Setup, CmdProcessor_Enqueue, AppControllerEnable, NULL, Retcode_RaiseError, assert.
Referenced by AppController_Init.