SensorServices.c
BCDS_MODULE_ID
BLE_OS_DELAY_UPON_CONNECT
Referenced by SensorServices_SendData.
SENSOR_SERVICES_HIGH_DATA_RATE_ATT_LEN_MAX
Referenced by SensorServicesRegisterHighDataRateService, WriteAndNotifyPriorityData.
SENSOR_SERVICES_UUID_MAX
typedef struct SensorServices_Characteristic_S SensorServices_Characteristic_T
Typedef to represent the Characteristic property of Sensor Services.
uint8_t AcceleratorSensorCharacteristicValues[SENSOR_AXIS_MAX][2][SENSOR_AXIS_MAX][2]
Container for the accelerometer sensor values send via BLE
Referenced by SensorServicesRegisterAccelerometer, WriteAndNotifyAccelerometerAxisValue.
SensorServices_Characteristic_T AccelerometerCharacteristicProperties[SENSOR_AXIS_MAX][SENSOR_AXIS_MAX]
Characteristic properties for the accelerometer sensor
const uint8_t AccelerometerSensorServiceUUID[SENSOR_SERVICES_UUID_MAX][SENSOR_SERVICES_UUID_MAX]
Accelerometer Sensor Service UUID: 5a 21 1d 40 71 66 11 e4 82 f8 08 00 20 0c 9a 66
Referenced by SensorServicesRegisterAccelerometer.
AttServiceAttribute AccelerometorSensorService
Referenced by SensorServicesRegisterAccelerometer.
TickType_t BleLastWakeTimeUponConnect
Referenced by SensorServices_SendData, SensorServices_UpdateConnectionStatus.
uint16_t ConnectionHandle
Connection handle to client
Referenced by WriteAndNotifyAccelerometerAxisValue, WriteAndNotifyGyroAxisValue, WriteAndNotifyLightSensorValue, WriteAndNotifyNoiseSensorValue, WriteAndNotifyMagnetometerValue, WriteAndNotifyPressureSensorValue, WriteAndNotifyTemperatureSensorValue, WriteAndNotifyHumiditySensorValue, WriteAndNotifyPriorityData, SensorServices_SendData.
AttServiceAttribute ControlNodeService
Attribute handle for the high data rate service
Referenced by SensorServicesRegisterControlSensor.
const uint8_t ControlNodeServiceUUID[SENSOR_SERVICES_UUID_MAX][SENSOR_SERVICES_UUID_MAX]
Control Node Service UUID: 55b741d0-7ada-11e4-82f8-0800200c9a66
Referenced by SensorServicesRegisterControlSensor.
SensorServices_DataReceivedCallBack DataReadCallBack
Callback function of type Ble_DataReceivedCallBack to read the data received
Referenced by AcceleratorSensorServiceCallback, GyroSensorServiceCallback, LightSensorServiceCallback, HighDataRateServiceCallback, ControlXdkServiceCallback, SensorServices_Init.
SensorServices_Characteristic_T EnvironmentSensorHumidityCharacteristicProperties
Characteristic properties for the environment sensor humidity value UUID: 92dab063-7634-11e4-82f8-0800200c9a66
uint8_t EnvironmentSensorHumidityCharacteristicValue[4][4]
Container for the humidity sensor values send via BLE
Referenced by SensorServicesRegisterEnvironmentSensor, WriteAndNotifyHumiditySensorValue.
SensorServices_Characteristic_T EnvironmentSensorPressureCharacteristicProperties
Characteristic properties for the environment sensor pressure value UUID: 92dab061-7634-11e4-82f8-0800200c9a66
uint8_t EnvironmentSensorPressureCharacteristicValue[4][4]
Container for the pressure sensor values send via BLE
Referenced by SensorServicesRegisterEnvironmentSensor, WriteAndNotifyPressureSensorValue.
AttServiceAttribute EnvironmentSensorService
Attribute handle for the magnetometer sensor service
Referenced by SensorServicesRegisterEnvironmentSensor.
const uint8_t EnvironmentSensorServiceUUID[SENSOR_SERVICES_UUID_MAX][SENSOR_SERVICES_UUID_MAX]
Environment Sensor Service UUID: 92dab060-7634-11e4-82f8-0800200c9a66
Referenced by SensorServicesRegisterEnvironmentSensor.
SensorServices_Characteristic_T EnvironmentSensorTemperatureCharacteristicProperties
Characteristic properties for the environment sensor temperature value UUID: 92dab062-7634-11e4-82f8-0800200c9a66
uint8_t EnvironmentSensorTemperatureCharacteristicValue[4][4]
Container for the temperature sensor values send via BLE
Referenced by SensorServicesRegisterEnvironmentSensor, WriteAndNotifyTemperatureSensorValue.
const uint8_t FirmwareVersionCharacteristicValue[4U][4U]
Firmware version information Format: {year, month, day, build-number}
Referenced by SensorServicesRegisterControlSensor.
SensorServices_Characteristic_T GetNodeFirmwareVersionCharacteristicProperties
Characteristic property for getting the firmware version sampling Characteristic UUID: 55b741d4-7ada-11e4-82f8-0800200c9a66
SensorServices_Characteristic_T GyroCharacteristicProperties[SENSOR_AXIS_MAX][SENSOR_AXIS_MAX]
Characteristic properties for the gyro sensor
uint8_t GyroSensorCharacteristicValues[SENSOR_AXIS_MAX][2][SENSOR_AXIS_MAX][2]
Container for the gyro sensor values send via BLE
Referenced by SensorServicesRegisterGyro, WriteAndNotifyGyroAxisValue.
AttServiceAttribute GyroSensorService
Attribute handle for the accelerometer sensor service
Referenced by SensorServicesRegisterGyro.
const uint8_t GyroSensorServiceUUID[SENSOR_SERVICES_UUID_MAX][SENSOR_SERVICES_UUID_MAX]
Gyro Sensor Service Sensor UUID: ac a9 6a 40 74 a4 11 e4 82 f8 08 00 20 0c 9a 66
Referenced by SensorServicesRegisterGyro.
SensorServices_Characteristic_T HighDataRateCharacteristicProperties[][]
Characteristic properties for the high rate data service
uint8_t HighDataRateCharacteristicValue[HIGH_DATA_RATE_MAX][SENSOR_SERVICES_HIGH_DATA_RATE_ATT_LEN_MAX][HIGH_DATA_RATE_MAX][SENSOR_SERVICES_HIGH_DATA_RATE_ATT_LEN_MAX]
Container for the high data rate values send via BLE
Referenced by SensorServicesRegisterHighDataRateService, WriteAndNotifyPriorityData.
AttServiceAttribute HighDataRateService
Attribute handle for the environment sensor service
Referenced by SensorServicesRegisterHighDataRateService.
const uint8_t HighDataRateServiceUUID[SENSOR_SERVICES_UUID_MAX][SENSOR_SERVICES_UUID_MAX]
High Data Rate Service UUID: c2967210-7ba4-11e4-82f8-0800200c9a66
Referenced by SensorServicesRegisterHighDataRateService.
bool IsFirstSendPending
Referenced by SensorServices_SendData, SensorServices_UpdateConnectionStatus.
SensorServices_Characteristic_T LightSensorCharacteristicProperties
Characteristic properties for the light sensor UUID: 38eb02c1-7540-11e4-82f8-0800200c9a66
uint8_t LightSensorCharacteristicValue[4][4]
Container for the light sensor values send via BLE
Referenced by SensorServicesRegisterLightSensor, WriteAndNotifyLightSensorValue.
AttServiceAttribute LightSensorService
Attribute handle for the gyro sensor service
Referenced by SensorServicesRegisterLightSensor.
const uint8_t LightSensorServiceUUID[SENSOR_SERVICES_UUID_MAX][SENSOR_SERVICES_UUID_MAX]
Light Sensor Service UUID: 38eb02c0-7540-11e4-82f8-0800200c9a66
Referenced by SensorServicesRegisterLightSensor.
SensorServices_Characteristic_T MagnetometerSensorCharacteristicProperties[4][4]
Characteristic properties for the magnetometer sensor
uint8_t MagnetometerSensorCharacteristicValues[SENSOR_MAGNETOMETER_MAX][2][SENSOR_MAGNETOMETER_MAX][2]
Container for the magnetometer sensor values send via BLE
Referenced by SensorServicesRegisterMagnetometerSensor, WriteAndNotifyMagnetometerValue.
AttServiceAttribute MagnetometerSensorService
Attribute handle for the noise sensor service
Referenced by SensorServicesRegisterMagnetometerSensor.
const uint8_t MagnetometerSensorServiceUUID[SENSOR_SERVICES_UUID_MAX][SENSOR_SERVICES_UUID_MAX]
Magnetometer Sensor Service UUID: 651f4c00-7579-11e4-82f8-0800200c9a66
Referenced by SensorServicesRegisterMagnetometerSensor.
SensorServices_Characteristic_T NoiseSensorCharacteristicProperties
Characteristic properties for the noise sensor UUID: 01033831-754c-11e4-82f8-0800200c9a66
uint8_t NoiseSensorCharacteristicValue[4][4]
Container for the noise sensor values send via BLE
Referenced by SensorServicesRegisterNoiseSensor, WriteAndNotifyNoiseSensorValue.
AttServiceAttribute NoiseSensorService
Attribute handle for the light sensor service
Referenced by SensorServicesRegisterNoiseSensor.
const uint8_t NoiseSensorServiceUUID[SENSOR_SERVICES_UUID_MAX][SENSOR_SERVICES_UUID_MAX]
Noise Sensor Service UUID: 01033830-754c-11e4-82f8-0800200c9a66
Referenced by SensorServicesRegisterNoiseSensor.
SensorServices_Characteristic_T RebootNodeCharacteristicProperties
Characteristic property for reset the Node Characteristic UUID: 55b741d3-7ada-11e4-82f8-0800200c9a66
uint8_t RebootNodeCharacteristicValue[1][1]
Container for the reset Node message received via BLE
Referenced by SensorServicesRegisterControlSensor.
SensorServices_SendEventCallback SendCallBack
Referenced by AcceleratorSensorServiceCallback, GyroSensorServiceCallback, LightSensorServiceCallback, SensorServicesCallback, HighDataRateServiceCallback, ControlXdkServiceCallback, SensorServices_Init.
SensorServices_Characteristic_T SetSamplingRateCharacteristicProperties
Characteristic property for the setting the sensor sampling rate Characteristic UUID: 55b741d2-7ada-11e4-82f8-0800200c9a66
uint8_t SetSensorSamplingTimerCharacteristicValue[4][4]
Container for the sampling time message received via BLE
Referenced by SensorServicesRegisterControlSensor.
SensorServices_Characteristic_T StartSensorSamplingAndNotificationsCharacteristicProperties
Characteristic property for the starting sensor sampling Characteristic UUID: 55b741d1-7ada-11e4-82f8-0800200c9a66
uint8_t StartSensorSamplingCharacteristicValue[1][1]
Container for the start sensor sampling message received via BLE
Referenced by SensorServicesRegisterControlSensor.
uint8_t SwitchNodeCharacteristicValue[1][1]
Container for the reset Node message received via BLE
Referenced by SensorServicesRegisterControlSensor.
SensorServices_Characteristic_T UseBuiltInSensorFusionCharacteristicProperties
Characteristic property to switch between orientationData or accelData + gpsData UUID: 55b741d5-7ada-11e4-82f8-0800200c9a66
static void AcceleratorSensorServiceCallback(AttServerCallbackParms *serverCallbackParms)
This function handles accelerometer sensor service events.
Attribute handle for the Node control service serverCallbackParms : Parameters holding service event status
References SensorServices_Info_S::sensorServicesType, BLE_SENSOR_ACCELEROMETER, SENSOR_AXIS_X, SensorServices_Characteristic_S::CharacteristicAttribute, SensorServices_Info_S::sensorServicesContent, SENSOR_AXIS_Y, SENSOR_AXIS_Z, SENSOR_AXIS_MAX, NULL, DataReadCallBack, RETCODE_OK, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_SENSORSERVICES_DATA_SEND_FAIL, SendCallBack.
Referenced by SensorServicesRegisterAccelerometer.
static void ControlXdkServiceCallback(AttServerCallbackParms *serverCallbackParms)
This function handles the Node control service events.
i] serverCallbackParms Parameters holding service event status
References SensorServices_Info_S::sensorServicesType, BLE_CONTROL_NODE, SensorServices_Characteristic_S::CharacteristicAttribute, SensorServices_Info_S::sensorServicesContent, CONTROL_NODE_START_SAMPLING, CONTROL_NODE_CHANGE_SAMPLING_RATE, CONTROL_NODE_REBOOT, CONTROL_NODE_GET_FW_VERSION, CONTROL_NODE_USE_SENSOR_FUSION, CONTROL_NODE_MAX, NULL, DataReadCallBack, RETCODE_OK, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_SENSORSERVICES_DATA_SEND_FAIL, SendCallBack.
Referenced by SensorServicesRegisterControlSensor.
static void GyroSensorServiceCallback(AttServerCallbackParms *serverCallbackParms)
This function handles gyro sensor service events.
i] serverCallbackParms Parameters holding service event status
References SensorServices_Info_S::sensorServicesType, BLE_SENSOR_GYRO, SENSOR_AXIS_X, SensorServices_Characteristic_S::CharacteristicAttribute, SensorServices_Info_S::sensorServicesContent, SENSOR_AXIS_Y, SENSOR_AXIS_Z, SENSOR_AXIS_MAX, NULL, DataReadCallBack, RETCODE_OK, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_SENSORSERVICES_DATA_SEND_FAIL, SendCallBack.
Referenced by SensorServicesRegisterGyro.
static void HighDataRateServiceCallback(AttServerCallbackParms *serverCallbackParms)
This function handles high data rate service events.
i] serverCallbackParms Parameters holding service event status
References SensorServices_Info_S::sensorServicesType, BLE_HIGH_DATA_RATE, HIGH_DATA_RATE_HIGH_PRIO, SensorServices_Characteristic_S::CharacteristicAttribute, SensorServices_Info_S::sensorServicesContent, HIGH_DATA_RATE_LOW_PRIO, HIGH_DATA_RATE_MAX, NULL, DataReadCallBack, RETCODE_OK, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_SENSORSERVICES_DATA_SEND_FAIL, SendCallBack.
Referenced by SensorServicesRegisterHighDataRateService.
static void LightSensorServiceCallback(AttServerCallbackParms *serverCallbackParms)
This function handles light sensor service events.
i] serverCallbackParms Parameters holding service event status
References SensorServices_Characteristic_S::CharacteristicAttribute, SensorServices_Info_S::sensorServicesType, BLE_SENSOR_LIGHT, SensorServices_Info_S::sensorServicesContent, NULL, DataReadCallBack, RETCODE_OK, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_SENSORSERVICES_DATA_SEND_FAIL, SendCallBack.
Referenced by SensorServicesRegisterLightSensor.
Retcode_T SensorServices_Init(SensorServices_DataReceivedCallBack readCallback, SensorServices_SendEventCallback sendCallback)
Initialize application callback to intimate for events from sensor services.
Initialize application callback to intimate for events from sensor services readCallback Application Callback that will be called on data reception for any sensor services characteristics sendCallback Application Callback that will be notified about the data send status. RETCODE_OK on success, or an error code otherwise. Refer Retcode_General_E and Ble_Retcode_E for other values. SensorServices_SendData
References NULL, DataReadCallBack, SendCallBack, RETCODE_OK, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER.
Retcode_T SensorServices_Register(void)
This function registers the Sensor Services at the ATT server. This must be done during the boot phase of the stack.
This function registers the Sensor Services at the ATT server. This must be done during the boot phase of the stack.BlePeripheral_ServiceRegistryCallback RETCODE_OK on success, or an error code otherwise. Refer Retcode_General_E and Ble_Retcode_E for other values. Sensor Services must have been successfully initialized prior.
References BLESTATUS_SUCCESS, SensorServicesRegisterAccelerometer, BLESTATUS_FAILED, SensorServicesRegisterGyro, SensorServicesRegisterLightSensor, SensorServicesRegisterNoiseSensor, SensorServicesRegisterMagnetometerSensor, SensorServicesRegisterEnvironmentSensor, SensorServicesRegisterHighDataRateService, SensorServicesRegisterControlSensor, RETCODE_OK, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_SENSORSERVICES_REGISTRATION_FAIL.
Retcode_T SensorServices_SendData(uint8_t *payload, uint8_t payloadLen, SensorServices_Info_T *sensorServiceInfo)
This function sends data to the client.
This function sends data to the client dataToSend The payload to be sent dataToSendLen The length of the payload to be sent param Provides the service characteristics information RETCODE_OK on success, or an error code otherwise. Refer Retcode_General_E and Ble_Retcode_E for other values. Sensor Services must have been successfully initialized and registered prior. SensorServices_SendEventCallback will be triggered to provide the status of every individual send's. SensorServices_SendEventCallback
References RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM, ConnectionHandle, BlePeripheral_GetConnectionHandle, RETCODE_SENSORSERVICES_NO_DEVICE_PAIRED, NULL, IsFirstSendPending, vTaskDelayUntil, BleLastWakeTimeUponConnect, BLE_OS_DELAY_UPON_CONNECT, SensorServices_Info_S::sensorServicesType, BLE_SENSOR_ACCELEROMETER, WriteAndNotifyAccelerometerAxisValue, SensorServices_Info_S::sensorServicesContent, BLE_SENSOR_GYRO, WriteAndNotifyGyroAxisValue, BLE_SENSOR_LIGHT, WriteAndNotifyLightSensorValue, BLE_SENSOR_NOISE, WriteAndNotifyNoiseSensorValue, BLE_SENSOR_MAGNETOMETER, WriteAndNotifyMagnetometerValue, BLE_SENSOR_ENVIRONMENTAL, SENSOR_ENVIRONMENTAL_PRESSURE, WriteAndNotifyPressureSensorValue, SENSOR_ENVIRONMENTAL_TEMPERATURE, WriteAndNotifyTemperatureSensorValue, SENSOR_ENVIRONMENTAL_HUMIDITY, WriteAndNotifyHumiditySensorValue, BLE_HIGH_DATA_RATE, WriteAndNotifyPriorityData, BLE_CONTROL_NODE.
void SensorServices_UpdateConnectionStatus(bool connectionStatus)
This function notifies the BLE connection status.
This function notifies the BLE connection status connectionStatus BLE connection status
References IsFirstSendPending, BleLastWakeTimeUponConnect, xTaskGetTickCount.
static void SensorServicesCallback(AttServerCallbackParms *serverCallbackParms)
This function handles several sensor service events.
i] serverCallbackParms Parameters holding service event status
References RETCODE_OK, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_SENSORSERVICES_DATA_SEND_FAIL, NULL, SendCallBack.
Referenced by SensorServicesRegisterNoiseSensor, SensorServicesRegisterMagnetometerSensor, SensorServicesRegisterEnvironmentSensor.
static BleStatus SensorServicesRegisterAccelerometer(void)
This function registers the accelerometer sensor in the attribute database with a dedicated service and the associated characteristics.
The status of registration.
References AccelerometerSensorServiceUUID, AcceleratorSensorServiceCallback, AccelerometorSensorService, BLESTATUS_FAILED, SENSOR_AXIS_MAX, SensorServices_Characteristic_S::UUIDType, SensorServices_Characteristic_S::CharacteristicUUID, SensorServices_Characteristic_S::Characteristic, AcceleratorSensorCharacteristicValues, SensorServices_Characteristic_S::CharacteristicAttribute, BLESTATUS_SUCCESS.
Referenced by SensorServices_Register.
static BleStatus SensorServicesRegisterControlSensor(void)
The function register Node control service into the attribute database.
This function register the Node control service in the attribute database with a dedicated service and the associated characteristics.
References ControlNodeServiceUUID, ControlXdkServiceCallback, ControlNodeService, BLESTATUS_FAILED, SensorServices_Characteristic_S::UUIDType, SensorServices_Characteristic_S::CharacteristicUUID, SensorServices_Characteristic_S::Characteristic, StartSensorSamplingCharacteristicValue, SensorServices_Characteristic_S::CharacteristicAttribute, SetSensorSamplingTimerCharacteristicValue, RebootNodeCharacteristicValue, FirmwareVersionCharacteristicValue, SwitchNodeCharacteristicValue, BLESTATUS_SUCCESS.
Referenced by SensorServices_Register.
static BleStatus SensorServicesRegisterEnvironmentSensor(void)
The function register environment sensor into the attribute database.
This function register the environment sensor in the attribute database with a dedicated service and the associated characteristics.
References EnvironmentSensorServiceUUID, SensorServicesCallback, EnvironmentSensorService, BLESTATUS_FAILED, SensorServices_Characteristic_S::UUIDType, SensorServices_Characteristic_S::CharacteristicUUID, SensorServices_Characteristic_S::Characteristic, EnvironmentSensorPressureCharacteristicValue, SensorServices_Characteristic_S::CharacteristicAttribute, EnvironmentSensorTemperatureCharacteristicValue, EnvironmentSensorHumidityCharacteristicValue, BLESTATUS_SUCCESS.
Referenced by SensorServices_Register.
static BleStatus SensorServicesRegisterGyro(void)
The function register gyro sensor into the attribute database.
This function register the gyro sensor in the attribute database with a dedicated service and the associated characteristics.
References GyroSensorServiceUUID, GyroSensorServiceCallback, GyroSensorService, BLESTATUS_FAILED, SENSOR_AXIS_MAX, SensorServices_Characteristic_S::UUIDType, SensorServices_Characteristic_S::CharacteristicUUID, SensorServices_Characteristic_S::Characteristic, GyroSensorCharacteristicValues, SensorServices_Characteristic_S::CharacteristicAttribute, BLESTATUS_SUCCESS.
Referenced by SensorServices_Register.
static BleStatus SensorServicesRegisterHighDataRateService(void)
The function register the high data rate service in the attribute database.
This function register the high data rate service in the attribute database with a dedicated service and the associated characteristics.
References HighDataRateServiceUUID, HighDataRateServiceCallback, HighDataRateService, BLESTATUS_FAILED, SensorServices_Characteristic_S::UUIDType, SensorServices_Characteristic_S::CharacteristicUUID, SensorServices_Characteristic_S::Characteristic, SENSOR_SERVICES_HIGH_DATA_RATE_ATT_LEN_MAX, HighDataRateCharacteristicValue, SensorServices_Characteristic_S::CharacteristicAttribute, BLESTATUS_SUCCESS.
Referenced by SensorServices_Register.
static BleStatus SensorServicesRegisterLightSensor(void)
The function register light sensor into the attribute database.
This function register the light sensor in the attribute database with a dedicated service and the associated characteristics.
References LightSensorServiceUUID, LightSensorServiceCallback, LightSensorService, BLESTATUS_FAILED, SensorServices_Characteristic_S::UUIDType, SensorServices_Characteristic_S::CharacteristicUUID, SensorServices_Characteristic_S::Characteristic, LightSensorCharacteristicValue, SensorServices_Characteristic_S::CharacteristicAttribute, BLESTATUS_SUCCESS.
Referenced by SensorServices_Register.
static BleStatus SensorServicesRegisterMagnetometerSensor(void)
The function register magnetometer sensor into the attribute database.
This function register the magnetometer sensor in the attribute database with a dedicated service and the associated characteristics.
References MagnetometerSensorServiceUUID, SensorServicesCallback, MagnetometerSensorService, BLESTATUS_FAILED, SENSOR_MAGNETOMETER_MAX, SensorServices_Characteristic_S::UUIDType, SensorServices_Characteristic_S::CharacteristicUUID, SensorServices_Characteristic_S::Characteristic, MagnetometerSensorCharacteristicValues, SensorServices_Characteristic_S::CharacteristicAttribute, BLESTATUS_SUCCESS.
Referenced by SensorServices_Register.
static BleStatus SensorServicesRegisterNoiseSensor(void)
The function register noise sensor into the attribute database.
This function register the noise sensor in the attribute database with a dedicated service and the associated characteristics.
References NoiseSensorServiceUUID, SensorServicesCallback, NoiseSensorService, BLESTATUS_FAILED, SensorServices_Characteristic_S::UUIDType, SensorServices_Characteristic_S::CharacteristicUUID, SensorServices_Characteristic_S::Characteristic, NoiseSensorCharacteristicValue, SensorServices_Characteristic_S::CharacteristicAttribute, BLESTATUS_SUCCESS.
Referenced by SensorServices_Register.
static Retcode_T WriteAndNotifyAccelerometerAxisValue(int16_t value, SensorServices_SensorAxisType_T axis)
References RETCODE_OK, SENSOR_AXIS_MAX, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM, AcceleratorSensorCharacteristicValues, SensorServices_Characteristic_S::CharacteristicAttribute, BLESTATUS_SUCCESS, RETCODE_SENSORSERVICES_WRITE_ATT_VALUE_FAILED, ConnectionHandle, BLESTATUS_FAILED, BLESTATUS_INVALID_PARMS, RETCODE_SENSORSERVICES_SEND_NOTIFICATION_FAILED.
Referenced by SensorServices_SendData.
static Retcode_T WriteAndNotifyGyroAxisValue(int16_t value, SensorServices_SensorAxisType_T axis)
References RETCODE_OK, SENSOR_AXIS_MAX, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM, GyroSensorCharacteristicValues, SensorServices_Characteristic_S::CharacteristicAttribute, BLESTATUS_SUCCESS, RETCODE_SENSORSERVICES_WRITE_ATT_VALUE_FAILED, ConnectionHandle, BLESTATUS_FAILED, BLESTATUS_INVALID_PARMS, RETCODE_SENSORSERVICES_SEND_NOTIFICATION_FAILED.
Referenced by SensorServices_SendData.
static Retcode_T WriteAndNotifyHumiditySensorValue(uint32_t value)
References RETCODE_OK, EnvironmentSensorHumidityCharacteristicValue, SensorServices_Characteristic_S::CharacteristicAttribute, BLESTATUS_SUCCESS, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_SENSORSERVICES_WRITE_ATT_VALUE_FAILED, ConnectionHandle, BLESTATUS_FAILED, BLESTATUS_INVALID_PARMS, RETCODE_SENSORSERVICES_SEND_NOTIFICATION_FAILED.
Referenced by SensorServices_SendData.
static Retcode_T WriteAndNotifyLightSensorValue(uint32_t value)
References RETCODE_OK, BLESTATUS_FAILED, LightSensorCharacteristicValue, SensorServices_Characteristic_S::CharacteristicAttribute, BLESTATUS_SUCCESS, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_SENSORSERVICES_WRITE_ATT_VALUE_FAILED, ConnectionHandle, BLESTATUS_INVALID_PARMS, RETCODE_SENSORSERVICES_SEND_NOTIFICATION_FAILED.
Referenced by SensorServices_SendData.
static Retcode_T WriteAndNotifyMagnetometerValue(int16_t value, SensorServices_MagnetometerType_T axis)
References RETCODE_OK, SENSOR_MAGNETOMETER_MAX, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM, MagnetometerSensorCharacteristicValues, SensorServices_Characteristic_S::CharacteristicAttribute, BLESTATUS_SUCCESS, RETCODE_SENSORSERVICES_WRITE_ATT_VALUE_FAILED, ConnectionHandle, BLESTATUS_FAILED, BLESTATUS_INVALID_PARMS, RETCODE_SENSORSERVICES_SEND_NOTIFICATION_FAILED.
Referenced by SensorServices_SendData.
static Retcode_T WriteAndNotifyNoiseSensorValue(uint32_t value)
References RETCODE_OK, NoiseSensorCharacteristicValue, SensorServices_Characteristic_S::CharacteristicAttribute, BLESTATUS_SUCCESS, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_SENSORSERVICES_WRITE_ATT_VALUE_FAILED, ConnectionHandle, BLESTATUS_FAILED, BLESTATUS_INVALID_PARMS, RETCODE_SENSORSERVICES_SEND_NOTIFICATION_FAILED.
Referenced by SensorServices_SendData.
static Retcode_T WriteAndNotifyPressureSensorValue(uint32_t value)
References RETCODE_OK, EnvironmentSensorPressureCharacteristicValue, SensorServices_Characteristic_S::CharacteristicAttribute, BLESTATUS_SUCCESS, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_SENSORSERVICES_WRITE_ATT_VALUE_FAILED, ConnectionHandle, BLESTATUS_FAILED, BLESTATUS_INVALID_PARMS, RETCODE_SENSORSERVICES_SEND_NOTIFICATION_FAILED.
Referenced by SensorServices_SendData.
static Retcode_T WriteAndNotifyPriorityData(uint8_t *buffer, U8 payloadLen, SensorServices_HighDataRateType_T priority)
References RETCODE_OK, HIGH_DATA_RATE_MAX, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM, HighDataRateCharacteristicValue, SENSOR_SERVICES_HIGH_DATA_RATE_ATT_LEN_MAX, SensorServices_Characteristic_S::CharacteristicAttribute, BLESTATUS_SUCCESS, RETCODE_SENSORSERVICES_WRITE_ATT_VALUE_FAILED, ConnectionHandle, BLESTATUS_FAILED, BLESTATUS_INVALID_PARMS, RETCODE_SENSORSERVICES_SEND_NOTIFICATION_FAILED.
Referenced by SensorServices_SendData.
static Retcode_T WriteAndNotifyTemperatureSensorValue(int32_t value)
References RETCODE_OK, EnvironmentSensorTemperatureCharacteristicValue, SensorServices_Characteristic_S::CharacteristicAttribute, BLESTATUS_SUCCESS, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_SENSORSERVICES_WRITE_ATT_VALUE_FAILED, ConnectionHandle, BLESTATUS_FAILED, BLESTATUS_INVALID_PARMS, RETCODE_SENSORSERVICES_SEND_NOTIFICATION_FAILED.
Referenced by SensorServices_SendData.