SensorNodeMapping.c
BCDS_MODULE_ID
I2cTranceiverHandle_T SensorNodeI2CTransceiver
Referenced by I2cInterruptCallback, SensorNodeMapping_Init, SensorNodeMapping_Write, SensorNodeMapping_Read, SensorNodeMapping_BurstRead, SensorNodeMapping_DeInit.
static void I2cInterruptCallback(I2C_T i2c, struct MCU_I2C_Event_S event)
References BCDS_UNUSED, SensorNodeI2CTransceiver.
Referenced by SensorNodeMapping_Init.
int8_t SensorNodeMapping_BurstRead(unsigned char I2Caddr, unsigned char Reg, unsigned char *RegData, unsigned int NbrBytesToRead)
Function to read a register of a device connected to I2C.
I2Caddr I2C address of the connected device from which to read the register. Reg Register address of the device to read. RegData Pointer on a buffer into which the read values will be stored. NbrBytesToRead Number of data elements expected to be received. I2C_SUCCESS on success. I2C_FAILURE if an error occurred.
References I2C_SUCCESS, NULL, RETCODE_OK, SensorNodeI2CTransceiver, I2C_FAILURE.
Retcode_T SensorNodeMapping_DeInit(void)
de-Initializes I2C and disables the power to sensors.
RETCODE_OK on success or an error code otherwise.
References RETCODE_OK, BSP_SensorNode_IsAllNodesDisabled, BSP_SensorNode_GetI2CHandle, SensorNodeI2CTransceiver, BSP_SensorNode_Disconnect.
Referenced by Bma280Utils_uninitialize, Bme280Utils_uninitialize, Bmg160Utils_uninitialize, Bmm150Utils_uninitialize, Max44009Utils_uninitialize.
Retcode_T SensorNodeMapping_Init(void)
Initializes I2C and enables the power to sensors.
RETCODE_OK on success or an error code otherwise.
References NULL, SensorNodeI2CTransceiver, RETCODE_OK, BSP_SensorNode_Connect, BSP_SensorNode_GetI2CHandle, I2cInterruptCallback, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER.
Referenced by Bma280Utils_initialize, Bme280Utils_initialize, Bmg160Utils_initialize, Bmm150Utils_initialize, Max44009Utils_initialize.
int8_t SensorNodeMapping_Read(unsigned char I2Caddr, unsigned char Reg, unsigned char *RegData, unsigned char NbrBytesToRead)
Function to read a register of a device connected to I2C.
I2Caddr I2C address of the connected device from which to read the register. Reg Register address of the device to read. RegData Pointer on a buffer into which the read values will be stored. NbrBytesToRead Number of data elements expected to be received. I2C_SUCCESS on success. I2C_FAILURE if an error occurred.
References I2C_SUCCESS, NULL, RETCODE_OK, SensorNodeI2CTransceiver, I2C_FAILURE.
Referenced by Bma280Utils_initialize, Bme280Utils_initialize, Bmg160Utils_initialize, Bmm150Utils_initialize, Max44009Utils_initialize.
int8_t SensorNodeMapping_Write(unsigned char I2Caddr, unsigned char Reg, unsigned char *RegData, unsigned char NbrBytesToWrite)
Function to write a register of a device connected to I2C.
I2Caddr I2C address of the connected device from which to read the register. Reg Register address of the device to read. RegData Pointer on a buffer into which the read values will be stored. NbrBytesToRead Number of data elements expected to be received. I2C_SUCCESS on success. I2C_FAILURE if an error occurred.
References I2C_SUCCESS, NULL, RETCODE_OK, SensorNodeI2CTransceiver, I2C_FAILURE.
Referenced by Bma280Utils_initialize, Bme280Utils_initialize, Bmg160Utils_initialize, Bmm150Utils_initialize, Max44009Utils_initialize.