Serval_Clock.h
retcode_t Clock_getTime(uint32_t *time_ptr)
This function is called to fetch the time in seconds since the last reset. time_ptr This is reference to a variable which must hold the time in seconds,since last reset, when the function returns. It has to be a valid pointer. RC_OK if the time has been successfully retrieved, RC_CLOCK_ERROR_FATAL otherwise.
Referenced by LWM2MDnsUtil_ExtendedResolveHostname.
retcode_t Clock_getTimeMillis(uint64_t *time_ptr)
This function is called to fetch the time in milliseconds since the last reset. time_ptr This is reference to a variable which must hold the time in milliseconds, since last reset, when the function returns. It has to be a valid pointer. RC_OK if the time has been successfully retrieved, RC_CLOCK_ERROR_FATAL otherwise.
Referenced by LWM2MDnsTask, SensorTimerHandler.