Serval_Lwm2m.h
LWM2M_ACCESS_CONTROL_OWNER
macro used to determine the owner of the access control object
LWM2M_BOOL
Helper macro to initialize a bool resource
LWM2M_BOOTSTRAP_TIMEOUT
BOOTSTRAP_TIMEOUT in seconds (default value 2)
LWM2M_CONFIRM_NOTIFY
Mark the resource to be delivered via confirmable messages
Referenced by LWM2MObjectsEnableConNotifies.
LWM2M_CREATE_ALLOWED
LWM2M_DELETE_ALLOWED
LWM2M_DYNAMIC
Helper macro to initialize a dynamic resource
LWM2M_DYNAMIC_ARRAY
Helper macro to initialize a dynamic resource as an array
LWM2M_DYNAMIC_BULK
Helper macro to initialize a bulk resource
LWM2M_EXECUTE_ALLOWED
LWM2M_FLOAT
Helper macro to initialize a floating point resource
LWM2M_FULL_ACCESS
LWM2M_FUNCTION
Helper macro to initialize a function resource
LWM2M_INACTIVE_INSTANCE
Used to define an object instance as inactive / not allocated
LWM2M_INACTIVE_RESOURCE_INSTANCE
Used to define a non instanced multiple resource
LWM2M_INTEGER
Helper macro to initialize an integer resource
LWM2M_INVISIBLE_INSTANCE
Used to define an object instance as invisible (it won't be considered for discovery) This is mainly useful for testing
LWM2M_IP_ADDRESS_MAX_LENGTH
Maximum length of the name that the device registers with Maximum length of the address of a (bootstrap) server (coap(s)://xxx.xxx.xxx.xxx:xxxxx)
LWM2M_MAX_NUMBER_SERVERS
Maximum number of servers supported by LwM2M
LWM2M_NOT_READABLE
Mark the resource type as not readable
Referenced by LWM2MObjectsEnableConNotifies.
LWM2M_NOT_WRITABLE
Mark the resource type as not writable
LWM2M_OBJECT_INSTANCE_COUNT
Helper macro to set the count of objects in the Lwm2m device
LWM2M_QUEUE_MODE_TIMEOUT
QUEUE_MODE_TIMEOUT in seconds (default value 2)
LWM2M_READ_ALLOWED
Macros used to set the access right for servers. Read access means right for Read, Observe, Write Attributes and Discover
LWM2M_READ_ONLY
Convenience value, same as not writable
LWM2M_REJECT_ANONYMOUS_DTLS_SERVERS
Enable to reject any server that does not provide a DTLS Server hint. Only applicable with DTLS enabled and when using LWm2mSecurity_callback as the security callback
LWM2M_RESOURCE_AFFIX_MASK
Mask for the bits that contain affixes
LWM2M_RESOURCE_TYPE_MASK
Mask for the bits that contain the raw type
LWM2M_RESOURCES
Helper macro to set the count of resources in an Lwm2m object
LWM2M_SINGLE_INSTANCE
Macro to point out the semantic difference between a non-multiple object and the instance 0
LWM2M_SINGLE_RESOURCE_INSTANCE
Used to define a resource as single
LWM2M_STRING_RO
Helper macro to initialize a string resource
LWM2M_TIME
Helper macro to initialize a time resource
LWM2M_WRITE_ALLOWED
LWM2M_WRITE_ONLY
Convenience value, same as not readable
SERVAL_LWM2M_SECURITY_INFO_MAX_LENGTH
Macro used to set a maximum for the security informations such as identity length or PSK length
Lwm2m_Binding_E
Lwm2m_Event_Type_E
Bootstrapping
Lwm2m_Notification_Resumption_e
Lwm2m_Resource_Type_E
Resource is a (read-only) String. Use 'dynamic' for strings writable by the server
typedef void(* Lwm2m_ApplicationCallback_T)(Lwm2m_Event_Type_T eventType, Lwm2m_URI_Path_T *path, retcode_t status))(Lwm2m_Event_Type_T eventType, Lwm2m_URI_Path_T *path, retcode_t status)
Callback function triggered after an event occurred in the stack that need to be notified to the application. This callback function is used for registration for example or resources changes.
event type to specify which event we are notifying the application about (registration success or resources changed) structure containing the uri path of the target status will tell the application about the kind of error that occurred
typedef enum Lwm2m_Binding_E Lwm2m_Binding_T
Type definition for the lightweight M2M communication binding. Lwm2m_Binding_E
typedef retcode_t(* Lwm2m_Dynamic_Resource_T)(Lwm2mSerializer_T *serializer_ptr, Lwm2mParser_T *parser_ptr))(Lwm2mSerializer_T *serializer_ptr, Lwm2mParser_T *parser_ptr)
typedef enum Lwm2m_Event_Type_E Lwm2m_Event_Type_T
Type definition for the event type. Lwm2m_Event_Type_E
typedef enum Lwm2m_Notification_Resumption_e Lwm2m_Notification_Resumption_t
typedef retcode_t(* Lwm2m_Resource_Function_T)(Lwm2mSerializer_T *serializer_ptr, Lwm2mParser_T *parser_ptr))(Lwm2mSerializer_T *serializer_ptr, Lwm2mParser_T *parser_ptr)
typedef enum Lwm2m_Resource_Type_E Lwm2m_Resource_Type_T
Type definition for the resource type. Lwm2m_Resource_Type_E
typedef struct Lwm2m_URI_Path_S Lwm2m_URI_Path_T
Type definition for the uri path. Lwm2m_URI_Path_S
typedef struct Lwm2mBootstrapServer_S Lwm2mBootstrapServer_T
typedef struct Lwm2mDevice_S Lwm2mDevice_T
Type definition for the lightweight M2M device. Lwm2mDevice_S
typedef struct Lwm2mObjectInstance_S Lwm2mObjectInstance_T
Type definition for the lightweight M2M object. Lwm2mObject_S
typedef struct Lwm2mParser_S Lwm2mParser_T
Opaque type to use for message parsing. Used only to pass into the parsing API
typedef struct Lwm2mResource_S Lwm2mResource_T
typedef struct Lwm2mSecurityInfo_S Lwm2mSecurityInfo_T
typedef struct Lwm2mSerializer_S Lwm2mSerializer_T
Opaque type to use for message serialization. Used only to pass into the serialization API
typedef struct Lwm2mServer_S Lwm2mServer_T
Lwm2mServer_T* Lwm2m_getServer(uint8_t serverIndex)
Get a reference to a particular server. The application can then set and access to the server informations.
serverIndex the index of the server in the array of servers Lwm2mServer: pointer to the LwM2M server of serverIndex-
retcode_t Lwm2m_initialize(Lwm2mDevice_T *device)
Initialize the Lightweight M2M module for a device described by device.
device structure containing the information about the device bootstrapServer structure containing information about the bootstrap server (in case of factory bootstrap the bootstrapServer argument must be NULL) servers structure containing information about the servers (in case of client initiate bootstrap the servers should be NULL) Initializes the LwM2M module. Device is a pointer to an initialized structure which contains the relevant information about the device.
void Lwm2m_setNumberOfServers(uint8_t numberOfServers)
Sets the number of instanciated servers. This function should be called after the application set servers informations to tell the stack about the number of instanciated servers.
numberOfServers number of active servers (this MUST be less than maximum number of servers)
retcode_t Lwm2m_start(Ip_Port_T port, Lwm2m_ApplicationCallback_T applicationCallback)
Start the Lightweight M2M module.
DeprecatedStarts the LwM2M service. Depending on the value of the secure flag in the Lwm2mDevice, this is equivalent to Lwm2m_startService(SERVAL_SCHEME_COAP, ...) or Lwm2m_startService(SERVAL_SCHEME_COAPS, ...) for the secure flag being false and true, respectively. port The coap server port, i.e. the local port used by this device applicationCallback a callback used to tell the application about events (like write, registration, bootstrapping) Starts a CoAP server on the given port.
Lwm2mBootstrapServer_T* Lwm2mBootstrap_getBootstrapServer(void)
Gets a reference to the bootstrap server. The application can then set the bootstrap informations.
Lwm2mBootstrapServer: pointer to the LwM2M bootstrap server.
retcode_t Lwm2mBootstrap_request(void)
Request Bootstrap to a bootstrap server for the LwM2M device.
Note: This is preliminary APIRC_OK on success
retcode_t Lwm2mParser_convertStringToInt(const char *string, const uint32_t length, int32_t *value)
Converts a parsed string to an integer. Use this function when obtaining string data from the parser that you want to convert to at integer value.
It rejects white space or any other non-digit characters.The key difference to existing standard functions is that the string provided by the parser is not terminated by '\0'! In memory, the string data is followed by the remaining payload in order to prevent copying the string data. Thus, the following TLV header may resemble an ASCII digit (e.g. object instance with 16-bit ID and 16-bit length will encode to 0x30 == '0') string the string data obtained from Lwm2mParser_getString() length the length of the string data obtained from Lwm2mParser_getString() value the converted string value RC_OK on success RC_LWM2M_PARSING_ERROR if the string could not be converted
retcode_t Lwm2mParser_getBool(Lwm2mParser_T *parser_ptr, bool *value)
Parses a bool from an incoming lwm2m message. The function takes care to handle TLV decoding if necessary.
parser_ptr Pointer to the parser structure (typically obtained in the callback) value of the bool that was parsed RC_OK on success RC_LWM2M_PARSING_ERROR if the data could not be parsed properly
Referenced by LightControl.
retcode_t Lwm2mParser_getFloat(Lwm2mParser_T *parser_ptr, float *value)
Parses a float from an incoming lwm2m message. The function takes care to handle TLV decoding if necessary.
parser_ptr Pointer to the parser structure (typically obtained in the callback) value of the float that was parsed RC_OK on success RC_LWM2M_PARSING_ERROR if the data could not be parsed properly
retcode_t Lwm2mParser_getInt(Lwm2mParser_T *parser_ptr, int32_t *value)
Parses an integer from an incoming lwm2m message. The function takes care to handle TLV decoding if necessary.
parser_ptr Pointer to the parser structure (typically obtained in the callback) value of the integer that was parsed RC_OK on success RC_LWM2M_PARSING_ERROR if the data could not be parsed properly
Referenced by Interval.
retcode_t Lwm2mParser_getOpaque(Lwm2mParser_T *parser_ptr, const uint8_t **value, uint32_t *length)
Parses opaque data from an incoming lwm2m message. The function takes care to handle TLV decoding if necessary.
parser_ptr Pointer to the parser structure (typically obtained in the callback) value the data that was parsed length the length of the data that was parsed RC_OK on success RC_LWM2M_PARSING_ERROR if the data could not be parsed properly
retcode_t Lwm2mParser_getResourceInstanceId(Lwm2mParser_T *parser_ptr, uint16_t *id)
This is used to get the resource instance Id from the Tlv header before parsing the corresponding resource instance.
parser_ptr Pointer to the parser structure (typically obtained in the callback) RC_OK on success RC_LWM2M_SERIALIZATION_ERROR if the next element is not a resource instance
retcode_t Lwm2mParser_getString(Lwm2mParser_T *parser_ptr, StringDescr_T *strDescr)
Parses a string from an incoming lwm2m message. The function takes care to handle TLV decoding if necessary.
Note that the string is not guaranteed to be terminated by '\0'. In case of TLV encoded payload, it is followed by the remaining payload of the message. parser_ptr Pointer to the parser structure (typically obtained in the callback) strDescriptor contains the the string that was parsed RC_OK on success RC_LWM2M_PARSING_ERROR if the data could not be parsed properly
Referenced by lwm2mDeviceUtcOffset, getTimeZone, PreprocessingMode.
retcode_t Lwm2mParser_getTime(Lwm2mParser_T *parser_ptr, int32_t *value)
Parses a timestamp from an incoming lwm2m message. The function takes care to handle TLV decoding if necessary.
parser_ptr Pointer to the parser structure (typically obtained in the callback) value of the timestamp that was parsed RC_OK on success RC_LWM2M_PARSING_ERROR if the data could not be parsed properly
Referenced by getCurrentTime.
retcode_t Lwm2mParser_parseNextResourceInstance(Lwm2mParser_T *parser_ptr)
This is used to parse the next resource instance. This function get the next resource instance in the tlv encoded payload to be able to parsing using Lwm2mParser_get functions.
Function to get the next resource instance in the tlv encoded payload parser_ptr Pointer to the parser structure (typically obtained in the callback) RC_OK on success RC_LWM2M_PARSER_END if we reached the end of the resource array
retcode_t Lwm2mParser_startParsingResourceArray(Lwm2mParser_T *parser_ptr)
This is used to start the parsing of a resource array. This function prepares the parser_ptr to parse resource arrays.
parser_ptr Pointer to the parser structure (typically obtained in the callback) RC_OK on success RC_LWM2M_PARSING_ERROR if the data is not a resource array
retcode_t Lwm2mRegistration_closeSecureConn(uint8_t serverIndex)
close and disconnect an existing secure COAP connection.
Note: This is preliminary API serverIndex the index of the server(in the array of server) to close the secure connection RC_OK on success (or if connection is not secure), RC_COAP_SECURE_CONNECTION_ERROR on failure.
retcode_t Lwm2mRegistration_deRegister(uint8_t serverIndex)
Perform a deregistration of an LwM2M device with an LwM2M server.
A successful registration with Lwm2m_register MUST have been performed.Note: This is preliminary API serverIndex the index of the server(in the array of server) to deregister from RC_OK on success
retcode_t Lwm2mRegistration_deRegisterFromAllServers(void)
Perform a deregistration of an LwM2M device with all the LwM2M servers.
A successful registration with Lwm2m_register MUST have been performed.Note: This is preliminary APIRC_OK on success
retcode_t Lwm2mRegistration_register(uint8_t serverIndex)
Register a LwM2M device with an LwM2M server.
Note: This is preliminary API serverIndex the index of the server(in the array of server) to register to RC_OK on success
retcode_t Lwm2mRegistration_registerToAllServers(void)
Register a LwM2M device with all the LwM2M servers.
Note: This is preliminary APIRC_OK on success
retcode_t Lwm2mRegistration_update(uint8_t serverIndex)
Perform a registration update of an LwM2M device with an LwM2M server.
A successful registration with Lwm2m_register MUST have been performed.Note: This is preliminary API serverIndex the index of the server(in the array of server) to update to RC_OK on success
retcode_t Lwm2mRegistration_updateToAllServers(void)
Perform a registration update of an LwM2M device with all the LwM2M servers.
A successful registration with Lwm2m_register MUST have been performed.Note: This is preliminary APIRC_OK on success
retcode_t Lwm2mReporting_multipleResourcesChanged(Lwm2m_URI_Path_T *objectInstanceUripath, uint8_t count,...)
Notify the stack that a resource has changed. This will cause the stack to notify any pending observers about the changed resource.
uripath The uripath of the object instance that has changed count The number of resources of the object instance that have changed resourceIndex The indexes of the resources that have changed RC_OK on success
Referenced by LWM2MUtil_ReportChanges.
retcode_t Lwm2mReporting_resourceChanged(Lwm2m_URI_Path_T *uripath)
Notify the stack that a resource has changed. This will cause the stack to notify any pending observers about the changed resource.
uripath The uripath of the resource that has changed RC_OK on success
Referenced by LWM2MResetAlertFunc, LWM2MObjectAlertNotification_SetValue, LWM2MObjectConnectivityMonitoring_SetRadioSignalStrength, LWM2MObjectConnectivityMonitoring_SetIpAddress, resetErrorCodeFunc, getCurrentTime, getTimeZone, LWM2MObjectDevice_NotifyTimeChanged, NotifyRed, NotifyOrange, NotifyYellow, Interval, PreprocessingMode.
void Lwm2mReporting_resumeNotifications(uint8_t serverIndex, Lwm2m_Notification_Resumption_t mode)
Resume sending notifications to a server.
Resume transmitting notifications resulting from Lwm2mReporting_resourceChanged or Lwm2mReporting_multipleResourcesChanged. This function is only required, if the server has been suspended before by a call to Lwm2mReporting_suspendNotifications. serverIndex the index of the server in the array of servers mode the way that changed observations are handled LWM2M_DROP_NOTIFICATIONS will cause changed observations to be silently ignored. Only future calls to Lwm2m_resourceChanged will trigger notifications. LWM2M_SEND_NOTIFICATIONS will cause a single notification to be triggered for changed resources. Thus, the observer will be notified about the new state of the resource, but not necessarily of all state changes. RC_OK on success
void Lwm2mReporting_suspendNotifications(uint8_t serverIndex)
Suspend sending of notifications to the given server.
Any notification resulting Lwm2mReporting_resourceChanged or Lwm2mReporting_multipleResourcesChanged will not be sent to the given server. The notification will silently be dropped. serverIndex the index of the server in the array of servers RC_OK on success
retcode_t Lwm2mSecurity_defaultCallback(SecurityToken_T token, SecurityData_T *tokenData)
Callback that can be provided to Security_setCallback to take over security token handling.
Lwm2m provides a notion of servers and the associated keying information for these servers. If the application has no special needs, this function can be provided to Security_setCallback in order to let the Lwm2m module perform security token management. token the security token to be provided in/out] tokenData additional data about the token to be provided and memory to provide it return RC_OK on success, see SecurityCallback_T for a description of return codes.
static void Lwm2mSerializer_checkIfDone(Lwm2mSerializer_T *serializer_ptr, uint32_t availableSize)
Check if resource is serialized completely and set the more flag if required.
NOTE: This is experimental API and subject to change!Resources marked as LWM2M_RESOURCE_DYNAMIC_BULK support blockwise transfer. In such a resource, this function can be used to check if the resource is transferred completely and, if required, mark the transfer with the flag indicating that more data can be transmitted. serializer_ptr Pointer to the serializer that is used to extract the server details availableSize The total size of the resource available for serialization 1.8
References Lwm2mSerializer_getBlockOffset, Lwm2mSerializer_getBlockSize, Lwm2mSerializer_haveMoreData.
retcode_t Lwm2mSerializer_endSerializingResourceArray(Lwm2mSerializer_T *serializer_ptr)
This is used to end the parsing of a resource array. The function takes care of ending the array by writing the length of the array.
serializer_ptr Pointer to the serializer structure (typically obtained in the callback) RC_OK on success RC_LWM2M_SERIALIZATION_ERROR if this is called without calling first
Referenced by LWM2MGetAvailableNetworkBearer, LWM2MGetIpAddresses, util_serialize_array, availablePowerSourcesfunc, powerSourceVoltageFunc.
uint32_t Lwm2mSerializer_getBlockOffset(Lwm2mSerializer_T *serializer_ptr)
Get the offset of the current block to be serialized.
NOTE: This is experimental API and subject to change!Resources marked as LWM2M_RESOURCE_DYNAMIC_BULK support blockwise transfer. In such a resource, this function can be used to obtain the offset of data to be written. For other resources, the returned value will always be 0. serializer_ptr Pointer to the serializer that is used to extract the server details offset in bytes of the block that was requested. 1.8
Referenced by Lwm2mSerializer_getSerializableSize, Lwm2mSerializer_checkIfDone, Lwm2mSerializer_serializeOpaqueBulk.
uint16_t Lwm2mSerializer_getBlockSize(Lwm2mSerializer_T *serializer_ptr)
Get the size of the current block to be serialized.
NOTE: This is experimental API and subject to change!Resources marked as LWM2M_RESOURCE_DYNAMIC_BULK support blockwise transfer. In such a resource, this function can be used to obtain the size of the data block to be written. For other resources, the returned value is undefined. serializer_ptr Pointer to the serializer that is used to extract the server details size in bytes of the block that was requested. 1.8
Referenced by Lwm2mSerializer_getSerializableSize, Lwm2mSerializer_checkIfDone, Lwm2mSerializer_serializeOpaqueBulk.
static uint16_t Lwm2mSerializer_getSerializableSize(Lwm2mSerializer_T *serializer_ptr, uint32_t availableSize)
Get the chunk size of the resource that is to be serialized.
NOTE: This is experimental API and subject to change!Resources marked as LWM2M_RESOURCE_DYNAMIC_BULK support blockwise transfer. In such a resource, this function can be used to obtain the size of the data block to be written, including the correct value for the last block. Thus, if the available length of the resource is larger than the block size, the block size is returned. Otherwise, the residual size is returned. For resources that are not of type LWM2M_RESOURCE_DYNAMIC_BULK, the returned value is undefined. serializer_ptr Pointer to the serializer that is used to extract the server details availableSize The total size of the resource available for serialization size to be serialized in bytes, 0 if no bytes need to be serialized. 1.8
References Lwm2mSerializer_getBlockOffset, Lwm2mSerializer_getBlockSize.
uint8_t Lwm2mSerializer_getServerIndex(Lwm2mSerializer_T *serializer_ptr)
Get the server index from which the LWM2M request came from.
serializer_ptr Pointer to the serializer that is used to extract the server details server index The index of the server(0 to LWM2M_MAX_NUMBER_SERVERS -1, as it is stored in an array) SERVER_INDEX_NOT_FOUND - if the server index could not be found
void Lwm2mSerializer_haveMoreData(Lwm2mSerializer_T *serializer_ptr)
Indicate that more data needs to be transmitted for the resource to be fully serialized.
NOTE: This is experimental API and subject to change!Resources marked as LWM2M_RESOURCE_DYNAMIC_BULK support blockwise transfer. In such a resource, this function can be used to indicate that the resource is larger than what has been serialized, i.e. further blocks are required to be transmitted. serializer_ptr - Pointer to the serializer that is used to extract the server details 1.8
Referenced by Lwm2mSerializer_checkIfDone, Lwm2mSerializer_serializeOpaqueBulk.
retcode_t Lwm2mSerializer_serializeBool(Lwm2mSerializer_T *serializer_ptr, bool value)
Serializes a boolean to an outgoing lwm2m message. The function takes care to handle TLV encoding if necessary.
serializer_ptr Pointer to the serializer structure (typically obtained in the callback) value the bool to be serialized RC_OK on success RC_LWM2M_ENTITY_TOO_LARGE if the length is to large to be serialized RC_LWM2M_SERIALIZATION_ERROR if the data could not be serialized
Referenced by LightControl.
retcode_t Lwm2mSerializer_serializeFloat(Lwm2mSerializer_T *serializer_ptr, float value)
Serializes an integer to an outgoing lwm2m message. The function takes care to handle TLV encoding if necessary.
serializer_ptr Pointer to the serializer structure (typically obtained in the callback) value the float to be serialized RC_OK on success RC_LWM2M_ENTITY_TOO_LARGE if the length is to large to be serialized RC_LWM2M_SERIALIZATION_ERROR if the data could not be serialized
retcode_t Lwm2mSerializer_serializeInt(Lwm2mSerializer_T *serializer_ptr, int32_t value)
Serializes an integer to an outgoing lwm2m message. The function takes care to handle TLV encoding if necessary.
serializer_ptr Pointer to the serializer structure (typically obtained in the callback) value of the integer to be serialized RC_OK on success RC_LWM2M_ENTITY_TOO_LARGE if the length is to large to be serialized RC_LWM2M_SERIALIZATION_ERROR if the data could not be serialized
Referenced by LWM2MGetAvailableNetworkBearer, util_serialize_array, availablePowerSourcesfunc, powerSourceVoltageFunc, batteryLevelFunc, batteryStatusFunc, Interval.
retcode_t Lwm2mSerializer_serializeOpaque(Lwm2mSerializer_T *serializer_ptr, uint8_t *value, uint32_t length)
Serializes an opaque data pointer to an outgoing lwm2m message. The function takes care to handle TLV encoding if necessary.
serializer_ptr Pointer to the serializer structure (typically obtained in the callback) value the data to be serialized length the length of the value RC_OK on success RC_LWM2M_ENTITY_TOO_LARGE if the length is to large to be serialized RC_LWM2M_SERIALIZATION_ERROR if the data could not be serialized
Referenced by Lwm2mSerializer_serializeOpaqueBulk.
static retcode_t Lwm2mSerializer_serializeOpaqueBulk(Lwm2mSerializer_T *serializer_ptr, uint8_t *data, uint32_t availableSize)
Serialize a chunk of an opaque resource.
NOTE: This is experimental API and subject to change!Resources marked as LWM2M_RESOURCE_DYNAMIC_BULK support blockwise transfer. In such a resource, this function can be used as a convenience function in order to serialize the corret chunk of a larger memory location. No other function should be called after this one. serializer_ptr Pointer to the serializer that is used to extract the server details data Pointer to the memory of the opaque chunk availableSize The total size of the resource available for serialization RC_OK if serialization suceeded, an error otherwise 1.8
References Lwm2mSerializer_getBlockOffset, Lwm2mSerializer_getBlockSize, RC_LWM2M_BAD_REQUEST, Lwm2mSerializer_haveMoreData, Lwm2mSerializer_serializeOpaque.
retcode_t Lwm2mSerializer_serializeString(Lwm2mSerializer_T *serializer_ptr, StringDescr_T *strDescr)
Serializes a string to an outgoing lwm2m message. The function takes care to handle TLV encoding if necessary.
serializer_ptr Pointer to the serializer structure (typically obtained in the callback) strDescr a descriptor for the string to be serialized RC_OK on success RC_LWM2M_ENTITY_TOO_LARGE if the length is to large to be serialized RC_LWM2M_SERIALIZATION_ERROR if the data could not be serialized
Referenced by LWM2MReadAlert, LWM2MGetIpAddresses, serialNumber_RO, firmwareVersionNumber_RO, lwm2mDeviceUtcOffset, getTimeZone, lwm2mDeviceGetBinding, PreprocessingMode.
retcode_t Lwm2mSerializer_serializeTime(Lwm2mSerializer_T *serializer_ptr, uint32_t value)
Serializes a timestamp (integer) to an outgoing lwm2m message. The function takes care to handle TLV encoding if necessary.
serializer_ptr Pointer to the serializer structure (typically obtained in the callback) value the time value to be serialized RC_OK on success RC_LWM2M_ENTITY_TOO_LARGE if the length is to large to be serialized RC_LWM2M_SERIALIZATION_ERROR if the data could not be serialized
Referenced by getCurrentTime.
retcode_t Lwm2mSerializer_setResourceInstanceId(Lwm2mSerializer_T *serializer_ptr, uint16_t instanceId)
This is used to set the resource instance Id before serializing the corresponding resource instance.
serializer_ptr Pointer to the serializer structure (typically obtained in the callback) RC_OK on success RC_LWM2M_SERIALIZATION_ERROR if this is called without calling first
Referenced by LWM2MGetAvailableNetworkBearer, LWM2MGetIpAddresses, util_serialize_array, availablePowerSourcesfunc, powerSourceVoltageFunc.
retcode_t Lwm2mSerializer_startSerializingResourceArray(Lwm2mSerializer_T *serializer_ptr)
This is used to start the serialization of a resource array. This function prepares the serializer_ptr to serialize resource arrays.
serializer_ptr Pointer to the serializer structure (typically obtained in the callback) RC_OK on success RC_LWM2M_SERIALIZATION_ERROR if this is used without tlv enabled
Referenced by LWM2MGetAvailableNetworkBearer, LWM2MGetIpAddresses, util_serialize_array, availablePowerSourcesfunc, powerSourceVoltageFunc.