Serval_StringDescr.h
typedef struct StringDescr_S StringDescr_T
This structure describes a string by a pointer to the start location and its length.struct StringDescr_S
static char StringDescr_charAt(const StringDescr_T *str_ptr, int pos)
This function returns the character at a specified position in the string associated with the given instance of string descriptor. str_ptr Reference to a StringDescr_T object which identifies the instance of string descriptor been used. It has to be a valid pointer. pos This will contain starting point of the string when the function returns. Character in the given string at the desired position.
References assert, NULL, StringDescr_S::start.
static void StringDescr_clone(StringDescr_T *dest_ptr, const StringDescr_T *src_ptr)
This function is called to clone a String Descriptor which means that the description information of src will be cloned to dest. The content characters will not be copied. dest_ptr Reference to a StringDescr_T object which identifies the instance of destination string descriptor. src_ptr Reference to a StringDescr_T object which identifies the instance of source string descriptor. StringDescr_cloneSegment()
References StringDescr_cloneSegment, StringDescr_S::length.
Referenced by XmlParser_getTagName, XmlParser_getTagValue.
static void StringDescr_cloneFrom(StringDescr_T *dest_ptr, const StringDescr_T *src_ptr, int pos)
This function is called to clone a String Descriptor which means that the description information of src will be cloned to dest. The clone operation considers only the segment of the source String Descriptor starting at the specified position. The content characters will not be copied. dest_ptr Reference to a StringDescr_T object which identifies the instance of destination string descriptor. src_ptr Reference to a StringDescr_T object which identifies the instance of source string descriptor. pos The start position of the segment of src which the clone operation should consider.
References StringDescr_cloneSegment, StringDescr_S::length.
static void StringDescr_cloneSegment(StringDescr_T *dest_ptr, const StringDescr_T *src_ptr, int pos, int n)
This function is called to clone a String Descriptor which means that the description information of src will be cloned to dest. The clone operation considers only a particular segment of the source String Descriptor. The content characters will not be copied. dest_ptr Reference to a StringDescr_T object which identifies the instance of destination string descriptor. src_ptr Reference to a StringDescr_T object which identifies the instance of source string descriptor. pos The start position of the segment of src which the clone operation should consider. n The length of the segment of src which the clone operation should consider.
References assert, NULL, StringDescr_S::length, StringDescr_S::start.
Referenced by StringDescr_clone, StringDescr_cloneFrom.
static bool StringDescr_compare(const StringDescr_T *str_ptr, const char *cstr)
This function compares a string description with a char string, and returns the result. str_ptr Reference to a StringDescr_T object which identifies the instance of string descriptor to be compared. cstr C string to be compared. true if found equal, otherwise false.
References StringDescr_compareFrom.
Referenced by PreprocessingMode.
static bool StringDescr_compareFrom(const StringDescr_T *str_ptr, int pos, const char *cstr)
This function compares a string description with a char string at a certain position, and returns the result. str_ptr Reference to a StringDescr_T object which identifies the instance of string descriptor to be compared. pos Starting position inside the string description cstr C string to be compared. true if found equal, otherwise false.
References assert, NULL, StringDescr_S::length, FALSE, StringDescr_compareSegment.
Referenced by StringDescr_compare.
static bool StringDescr_compareFromNoCase(StringDescr_T const *str_ptr, int pos, char const *cstr)
This function compares a segment of string description with a char string starting at a certain position, ignoring case, and returns the result. str_ptr Reference to a StringDescr_T object which identifies the instance of string descriptor to be compared. pos Starting position inside the string description cstr C string to be compared. true if found equal, otherwise false. StringDescr_compareSegmentNoCase()
References assert, NULL, StringDescr_S::start, StringDescr_S::length, FALSE, StringDescr_compareSegmentNoCase.
Referenced by StringDescr_compareNoCase.
static bool StringDescr_compareNoCase(const StringDescr_T *str_ptr, const char *cstr)
This function compares a segment of string description with a char string starting at a certain position, ignoring case, and returns the result. str_ptr Reference to a StringDescr_T object which identifies the instance of string descriptor to be compared. cstr C string to be compared. true if found equal, otherwise false.
References StringDescr_compareFromNoCase.
bool StringDescr_compareSegment(const StringDescr_T *str_ptr, int pos, const char *cstr, int n)
This function compares a segment of string description with a string starting at a certain position, and returns the result. str_ptr Reference to a StringDescr_T object which identifies the instance of string descriptor to be compared. pos Starting position inside the string description cstr C string to be compared. n The number of characters which should be considered in the comparison true if found equal, otherwise false.
Referenced by StringDescr_compareFrom.
bool StringDescr_compareSegmentNoCase(StringDescr_T const *str_ptr, int pos, char const *cstr, int n)
This function compares a segment of string description with n characters of a string starting at a certain position, ignoring case, and returns the result. str_ptr Reference to a StringDescr_T object which identifies the instance of string descriptor to be compared. pos Starting position inside the string description cstr C string to be compared. n the number of character of cstr to be used for the compare true if found equal, otherwise false. StringDescr_compareSegmentNoCase()
Referenced by StringDescr_compareFromNoCase.
static void StringDescr_copy(const StringDescr_T *src_ptr, char *buf_ptr)
This function is called to copy the string which is described by a string descriptor into a char buffer. src_ptr Reference to a StringDescr_T object which identifies the instance of source string descriptor. buf_ptr Destination character buffer, This must be valid.
References StringDescr_copySegment, StringDescr_S::length.
static void StringDescr_copyFrom(const StringDescr_T *src_ptr, char *buf_ptr, int pos)
This function is called to copy the string which is described by a string descriptor into a char buffer from a given offset. src_ptr Reference to a StringDescr_T object which identifies the instance of source string descriptor. buf_ptr Destination character buffer. This must be valid. pos The position at which the copy operation shout start StringDescr_copySegment()
References StringDescr_copySegment, StringDescr_S::length.
static void StringDescr_copySegment(const StringDescr_T *src_ptr, char *buf_ptr, int pos, int n)
This function is called to copy a segment of the string described by a string descriptor into a char buffer. src_ptr Reference to a StringDescr_T object which identifies the instance of source string descriptor. buf_ptr Destination character buffer, This must be valid. pos The position at which the copy operation shout start n The number of characters which should be maximally copied.
References assert, NULL, StringDescr_S::length, StringDescr_S::start.
Referenced by StringDescr_copy, StringDescr_copyFrom.
int StringDescr_findFirstChar(const StringDescr_T *str_ptr, int offset, char c)
This function finds and returns first occurrence of a character inside a String Descriptor. str_ptr Reference to a StringDescr_T object which identifies the instance of string descriptor to be searched. offset The position at which the search is starting. c Character to look for. Position of the character or -1 if character is not found.
int StringDescr_findLastChar(const StringDescr_T *str_ptr, char c)
This function finds and returns last occurrence of a character inside a String Descriptor. str_ptr Reference to a StringDescr_T object which identifies the instance of string descriptor to be searched. c Character to look for. Position of the character or -1 if character is not found.
static void StringDescr_get(const StringDescr_T *str_ptr, const char **start_pptr, int *len_ptr)
This function is called to fetch start and length associated with the given instance of string descriptor. The function StringDescr_set() should have been called before calling this function. str_ptr Reference to a StringDescr_T object which identifies the instance of string descriptor been used. It has to be a valid pointer. start_pptr This will contain starting point of the string when the function returns. len_ptr This will contain length of the string when the function returns.
References assert, NULL, StringDescr_S::start, StringDescr_S::length.
static int StringDescr_getLength(const StringDescr_T *str_ptr)
This function returns the total length of the entire string described by the given String Descriptor. str_ptr Reference to a StringDescr_T object which identifies the instance of string descriptor been used. It has to be a valid pointer. Total length of the string.
References assert, NULL, StringDescr_S::start, StringDescr_S::length.
static bool StringDescr_isValid(const StringDescr_T *str_ptr)
This function checks the state of the string descriptor, and sees if the string descriptor is valid or not. str_ptr Reference to a StringDescr_T object which identifies the instance of string descriptor to be checked. It has to be a valid pointer. true if string descriptor is valid false if it is not.
References NULL, StringDescr_S::start.
static bool StringDescr_parseUInt(const StringDescr_T *str_ptr, uint32_t *value)
This function parses the given string descriptor for an unsigned integer. It does not handle leading or trailing characters and will produce an error if those are found. str_ptr Reference to a StringDescr_T object which identifies the instance of string descriptor to be compared. value the parsed value true if parsing went ok, false otherwise 1.4
References StringDescr_S::length, StringDescr_S::start.
static void StringDescr_set(StringDescr_T *str_ptr, char const *start_ptr, int len)
This function is called to initialize and prepare a instance of string descriptor. This function must be called before a string descriptor is used. str_ptr Reference to a StringDescr_T object which identifies the instance of string descriptor to be used. It has to be a valid pointer. start_ptr This gives starting point of the string. len This gives length of the string.
References StringDescr_S::start, StringDescr_S::length.
Referenced by LWM2MReadAlert, LWM2MGetIpAddresses, serialNumber_RO, firmwareVersionNumber_RO, PreprocessingMode.
static void StringDescr_wrap(StringDescr_T *dest_ptr, const char *cstr)
This function is called to record the description information (i.e. start address and length) of the given string in the given String Descriptor. The content characters will not be copied. dest_ptr Reference to a StringDescr_T object which identifies the instance of destination string descriptor. cstr The string which should be described by the String Descriptor.
References assert, NULL, StringDescr_S::start, StringDescr_S::length.