Serval_Serializer.h
retcode_t Serializer_deserializeBool(StringDescr_T const *str_ptr, bool *value_ptr)
This function converts a string into the bool data type. str_ptr The String Descriptor object that has the value desired value_ptr Pointer to variable where the resulting value will be stored RC_OK, if successful RC_DESERIALIZE_ERROR given string does not match "1", "0", "true", "false"
retcode_t Serializer_deserializeDouble(StringDescr_T const *str_ptr, double *value_ptr)
This function converts a string into the double data type. str_ptr The String Descriptor object that has the value desired value_ptr Pointer to variable where the resulting value will be stored RC_OK, if successful RC_DESERIALIZE_ERROR given string too long
retcode_t Serializer_deserializeFloat(StringDescr_T const *str_ptr, float *value_ptr)
This function converts a string into the float data type. str_ptr The String Descriptor object that has the value desired value_ptr Pointer to variable where the resulting value will be stored RC_OK, if successful RC_DESERIALIZE_ERROR given string too long
retcode_t Serializer_deserializeInt16(StringDescr_T const *str_ptr, int16_t *value_ptr)
retcode_t Serializer_deserializeInt32(StringDescr_T const *str_ptr, int32_t *value_ptr)
retcode_t Serializer_deserializeInt64(StringDescr_T const *str_ptr, int64_t *value_ptr)
This function converts a string into integer data type. str_ptr The String Descriptor object that has the value desired value_ptr Pointer to variable where the resulting value will be stored RC_OK, if successful RC_DESERIALIZE_ERROR given string too long
retcode_t Serializer_deserializeInt8(StringDescr_T const *str_ptr, int8_t *value_ptr)
retcode_t Serializer_deserializeString(StringDescr_T const *str_ptr, char buf[], uint32_t bufSize)
This function copies a string into the given buffer. str_ptr The String Descriptor object that has the value desired buf Pointer to buffer where the resulting value will be stored bufSize Size of the buffer. RC_OK, if successful RC_DESERIALIZE_ERROR given string too long
retcode_t Serializer_deserializeUint16(StringDescr_T const *str_ptr, uint16_t *value_ptr)
retcode_t Serializer_deserializeUint32(StringDescr_T const *str_ptr, uint32_t *value_ptr)
retcode_t Serializer_deserializeUint64(StringDescr_T const *str_ptr, uint64_t *value_ptr)
retcode_t Serializer_deserializeUint8(StringDescr_T const *str_ptr, uint8_t *value_ptr)
retcode_t Serializer_serialize(char *buf_ptr, int bufSize, int *len_ptr, const char *format,...)
This function writes data to a buffer in a printf-like fashion. buf_ptr The buffer to which given value should be written bufSize The size of the buffer len_ptr The number of bytes written format The format of the data (specified like for printf()) and followed by the data RC_OK on success RC_MSG_FACTORY_INCOMPLETE given buffer is too small
Referenced by Serializer_serializeBool, Serializer_serializeInt, Serializer_serializeLong, Serializer_serializeFloat, Serializer_serializeString.
static retcode_t Serializer_serializeBool(bool value, char *buf_ptr, int bufSize, int *len_ptr)
This function writes a bool, a primitive data type, into a given buffer. value The value to write to buffer buf_ptr The buffer to which given value should be written bufSize The size of the buffer len_ptr The number of bytes written RC_OK on success RC_MSG_FACTORY_INCOMPLETE given buffer is too small
References Serializer_serialize.
static retcode_t Serializer_serializeFloat(float value, char *buf_ptr, int bufSize, int *len_ptr)
This function writes a float, a primitive data type, into a given buffer. value The value to write to buffer buf_ptr The buffer to which given value should be written bufSize The size of the buffer len_ptr The number of bytes written RC_OK, if successful RC_MSG_FACTORY_INCOMPLETE given buffer is too small
References Serializer_serialize.
static retcode_t Serializer_serializeInt(int value, char *buf_ptr, int bufSize, int *len_ptr)
This function writes a integer, a primitive data type, into a given buffer. value The value to write to buffer buf_ptr The buffer to which given value should be written bufSize The size of the buffer len_ptr The number of bytes written RC_OK, if successful RC_MSG_FACTORY_INCOMPLETE given buffer is too small
References Serializer_serialize.
static retcode_t Serializer_serializeLong(int64_t value, char *buf_ptr, int bufSize, int *len_ptr)
This function writes a long integer, a primitive data type, into a given buffer. value The value to write to buffer buf_ptr The buffer to which given value should be written bufSize The size of the buffer len_ptr The number of bytes written RC_OK, if successful RC_MSG_FACTORY_INCOMPLETE buffer was too small
References Serializer_serialize.
static retcode_t Serializer_serializeString(char const *value, char *buf_ptr, int bufSize, int *len_ptr)
This function writes a string into a given buffer. value The value to write to buffer buf_ptr The buffer to which given value should be written bufSize The size of the buffer len_ptr The number of bytes written RC_OK, if successful RC_MSG_FACTORY_INCOMPLETE given buffer is too small
References Serializer_serialize.
retcode_t Serializer_vserialize(char *buf_ptr, int bufSize, int *len_ptr, const char *format, va_list args)
This function writes data to a buffer in a printf-like fashion. buf_ptr The buffer to which given value should be written bufSize The size of the buffer len_ptr The number of bytes written format The format of the data (specified like for printf()) and followed by the data args The list of data parameters for the given format. RC_OK on success RC_MSG_FACTORY_INCOMPLETE given buffer is too small