Serval_Callable.h
CALLABLE_GET_CONTEXT
This macro provides a pointer to the context structure of the given callable object. It is assumed here that the callable object is member of a struct. A pointer to the struct will be returned. ContextTypeName the name of the expected data type of the containing structure ContextMemberNameOfCallable the member name of the callable object inside the enclosing structure callable_ptr a pointer to the callable object a pointer to the enclosing structure which contains the given callable object as a member.
Referenced by ScheduleUpdateSingleResource, ScheduleUpdatePairResources, ScheduleUpdateTrippleResources, ScheduleCall.
typedef struct Callable_S Callable_T
The data type for callable elements.struct Callable_S
typedef retcode_t(* CallableFunc_T)(Callable_T *callable_ptr, retcode_t status))(Callable_T *callable_ptr, retcode_t status)
This data type represents a function pointer for the function carried by the Callable_T element.The parameter callable_ptr generally refers to the Callable_T element carrying this functions. This pointer is passed into the function in order to allow the retrieval of the context structure using the macro CALLABLE_GET_CONTEXT(). The other parameter status is used to pass the status which should be signaled to the invoked function.CALLABLE_GET_CONTEXT()
static Callable_T* Callable_assign(Callable_T *callable_ptr, CallableFunc_T function)
This function assigns a function to the given Callable. callable_ptr Reference to a Callable_T object to which the function needs to be assigned. It has to be a valid pointer. function Reference to a CallableFunc_T object, this holds the function to be assigned. pointer to Callable_T object.
References Callable_S::func.
Referenced by LWM2MUtil_UpdateSingleResource, LWM2MUtil_UpdatePairResources, LWM2MUtil_UpdateTrippleResources, LWM2MUtil_Schedule.
retcode_t Callable_call(Callable_T *callable_ptr, retcode_t status)
This function is called to invoke the callable element. It propagates the error code returned by the encapsulated function. also this function does not handle any exception returned by the invoked callback, instead it return the return code from callbeck as it is to the calling function. callable_ptr Reference to a Callable_T element to be invoked. It has to be a valid pointer. status Status to be passed to callable element. the return value of the encapsulated function.
void Callable_callback(Callable_T *callable_ptr, retcode_t status)
This function is called to invoke the callable element when it is used as a callback function. It works as Callable_call() with the difference that any potential error codes are handled inside the function without propagating them to the caller. This is done this way since the caller of a callback function is not resposible and usually not able to handle errors in this context. callable_ptr Reference to a Callable_T object which holds the callback function. It has to be a valid pointer. status Status to be passed to callback.
static void Callable_clear(Callable_T *callable_ptr)
This function clears or resets the callable element by setting its function pointer to NULL. callable_ptr Reference to a Callable_T object to be cleared. It has to be a valid pointer.
References Callable_S::func, NULL.
Referenced by ScheduleUpdateSingleResource, LWM2MUtil_UpdateSingleResource, ScheduleUpdatePairResources, LWM2MUtil_UpdatePairResources, ScheduleUpdateTrippleResources, LWM2MUtil_UpdateTrippleResources.
static bool Callable_isAssigned(Callable_T *callable_ptr)
This function checks the given callable pointer on being valid (not NULL) and a valid function is assigned to it. callable_ptr The reference of object Callable_T to check for the state. TRUE if the callable pointer is valid (not NULL) and it holds a valid callable function pointer. Otherwise, FALSE is returned.
References null, Callable_S::func.
Referenced by LWM2MUtil_UpdateSingleResource, LWM2MUtil_UpdatePairResources, LWM2MUtil_UpdateTrippleResources, LWM2MUtil_Schedule.