Serval_Ip.h
typedef struct Peer_S Peer_T
A data structure to contain information about a communication peerstruct Peer_S
static bool comparePeer(const Peer_T *a, const Peer_T *b)
Compare a peer with another peer true if both address and port of the peers match
References Peer_S::port, Ip_compareAddr, Peer_S::address.
bool Ip_compareAddr(Ip_Address_T const *ip1_ptr, Ip_Address_T const *ip2_ptr)
This function is called compares two IP addresses on being equal and return the result. ip1_ptr A pointer to the first IP address. It has to be valid. ip2_ptr A pointer to the second IP address. It has to be valid. TRUE if the both IP address are equal, or FALSE otherwise.
Referenced by samePeer, comparePeer.
int Ip_convertAddrToString(Ip_Address_T const *ipAddr_ptr, char *buffer_ptr)
This function converts a given IP address to a null-terminated string, and stores the result in the given buffer. ipAddr_ptr A valid pointer reference to the IP address to be converted. buffer_ptr A valid pointer to the buffer which the IP string should be written to. The given buffer must be larger than the maximal length of the IP string presentation by at least 1 (for the null-character). The written string will be NULL terminated. On success, the total number of characters written is returned. This count does not include the additional null-character. On failure, a negative number is returned.
Referenced by LWM2MDnsUtil_ExtendedResolveHostname.
Ip_Port_T Ip_convertIntToPort(uint16_t port)
This function converts a given Integer to a port and returns the result. port The port number as an Integer in the platform byte order The port in the network byte order.
void Ip_convertOctetsToAddr(uint8_t first, uint8_t second, uint8_t third, uint8_t fourth, Ip_Address_T *ipAddr_ptr)
This function converts given octets to an IP address. first First block of the IP address. It has to be in the range of 0-255. second Second block of the IP address. It has to be in the range of 0-255. third Third block of the IP address. It has to be in the range of 0-255. fourth Forth block of the IP address. It has to be in the range of 0-255. ipAddr_ptr Reference to an IPv4 address for the result of the conversion. It has to be a valid pointer. TODO: Rename to Ip_convertBlocksToAddr()
uint16_t Ip_convertPortToInt(Ip_Port_T port)
This function converts a given port from the network byte order to an Integer in the platform byte order and returns the result. port Port to be converted. Converted port as an Integer in the platform byte order.
void Ip_copyAddr(Ip_Address_T const *src_ptr, Ip_Address_T *dest_ptr)
This function is called to copy a given IP address to a destination whose reference is given. src_ptr Reference to the source IP address to be copied dest_ptr Reference to the destination which the given IP will copied to.
Ip_Address_T* Ip_getMyIpAddr(void)
This function returns a reference to the IP address assigned to the own network interface. If no IP address has been assigned to the network interface, this function returns the unspecified IP address, i.e. an address which is equal to the result of Ip_getUnspecifiedAddr().On success, a reference to the own IP address is returned. On failure Null is returned. Ip_getUnspecifiedAddr()
Ip_Address_T const* Ip_getUnspecifiedAddr(void)
This function should be used to un-initialize an IP address. It returns a reference to the unspecified address which is 0.0.0.0 in the case of IPv4 or 0:0:0:0:0:0:0:0:0 (i.e. ::) in the case of IPv6.A reference to the unspecified IP address.
static bool samePeer(const Peer_T *peer, const Ip_Address_T *address, const Ip_Port_T port)
Compare a peer with an address and a port. true if both address and port match the ones stored in the peer
References Peer_S::port, Ip_compareAddr, Peer_S::address.