Serval_Scheduler.h
retcode_t Scheduler_enqueue(Callable_T *callable_ptr, retcode_t status)
This function is called to schedule a given task. On success, stack expects that the enqueued callable will be invoked with the given status. callable_ptr Reference to a Callable_T object be scheduled. It has to be a valid pointer. status The status which will be passed to the callable when it is invoked. On success, RC_OK is returned. RC_SCHED_FULL if the scheduling queue is full.
Referenced by LWM2MUtil_UpdateSingleResource, LWM2MUtil_UpdatePairResources, LWM2MUtil_UpdateTrippleResources, LWM2MUtil_Schedule.