Sigfox.c
BCDS_MODULE_ID
Licensee agrees that the example code provided to Licensee has been developed and released by Bosch solely as an example to be used as a potential reference for Licensee’s application development. Fitness and suitability of the example code for any use within Licensee’s applications need to be verified by Licensee on its own authority by taking appropriate state of the art actions and measures (e.g. by means of quality assurance measures). Licensee shall be responsible for conducting the development of its applications as well as integration of parts of the example code into such applications, taking into account the state of the art of technology and any statutory regulations and provisions applicable for such applications. Compliance with the functional system requirements and testing there of (including validation of information/data security aspects and functional safety) and release shall be solely incumbent upon Licensee. For the avoidance of doubt, Licensee shall be responsible and fully liable for the applications and any distribution of such applications into the market.Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: (1) Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer. (2) Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution. (3)The name of the author may not be used to endorse or promote products derived from this software without specific prior written permission. THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
EXTENSION_BUS_SPI_BAUDRATE
Macro used to define the SPI Baudrate
Referenced by Sigfox_Setup.
EXTENSION_BUS_SPI_TX_RX_TIMEOUT_IN_MS
Macro used to define the data transfer timeout
Referenced by HandleSPIDataTransfer.
uint8_t DownlinkPayload[8][8]
Referenced by Sigfox_SendPayload, Sigfox_PrintRXPayload.
const uint8_t ETSIPATable[200][200]
Referenced by Sigfox_UpdatePACurve.
const uint8_t FCCPATable[200][200]
Referenced by Sigfox_UpdatePACurve.
uint8_t ReadBuffer[SIGFIX_READ_WRITE_BUFFER_SIZE][SIGFIX_READ_WRITE_BUFFER_SIZE]
Referenced by Sigfox_Setup.
uint8_t ReadBufferLength
Referenced by HandleSPIDataTransfer, Sigfox_SendPayload, Sigfox_SetRCZ1, Sigfox_SetRCZ2, Sigfox_SetRCZ3, Sigfox_SetRCZ4, Sigfox_ResetMacroChannel, Sigfox_SetPrivateKey, Sigfox_SendBit, Sigfox_SetFCCMacroChannel, Sigfox_UpdatePACurve, Sigfox_ReadPACurve.
uint8_t* ReadBufferPointer
Referenced by HandleSPIDataTransfer, PrintInfo, PrintSOCVersion, Sigfox_Setup, Sigfox_SendPayload, Sigfox_SetRCZ1, Sigfox_SetRCZ2, Sigfox_SetRCZ3, Sigfox_SetRCZ4, Sigfox_ResetMacroChannel, Sigfox_SetPrivateKey, Sigfox_SendBit, Sigfox_SetFCCMacroChannel, Sigfox_UpdatePACurve, Sigfox_ReadPACurve.
uint8_t WriteBuffer[SIGFIX_READ_WRITE_BUFFER_SIZE][SIGFIX_READ_WRITE_BUFFER_SIZE]
Referenced by Sigfox_Setup.
uint8_t WriteBufferLength
Referenced by HandleSPIDataTransfer, Sigfox_SendWakeUp, Sigfox_SendToSleep, Sigfox_GetInfo, Sigfox_SendPayload, Sigfox_SetRCZ1, Sigfox_SetRCZ2, Sigfox_SetRCZ3, Sigfox_SetRCZ4, Sigfox_ResetMacroChannel, Sigfox_SetPrivateKey, Sigfox_SetPublicKey, Sigfox_SendBit, Sigfox_GetSOCVersion, Sigfox_SetFCCMacroChannel, Sigfox_UpdatePACurve, Sigfox_ReadPACurve.
uint8_t* WriteBufferPointer
Referenced by HandleSPIDataTransfer, Sigfox_Setup, Sigfox_SendWakeUp, Sigfox_SendToSleep, Sigfox_GetInfo, Sigfox_SendPayload, Sigfox_SetRCZ1, Sigfox_SetRCZ2, Sigfox_SetRCZ3, Sigfox_SetRCZ4, Sigfox_ResetMacroChannel, Sigfox_SetPrivateKey, Sigfox_SetPublicKey, Sigfox_SendBit, Sigfox_GetSOCVersion, Sigfox_SetFCCMacroChannel, Sigfox_UpdatePACurve, Sigfox_ReadPACurve.
static Retcode_T HandleSPIDataTransfer(void)
Generic function to send and receive data over SPI.
RETCODE_OK on success, or an error code otherwise. Refer function prototype for description
References RETCODE_OK, ExtensionPortSpiCtrl_CSLow, ExtensionPortSpiCtrl_AckAwaitHigh, ExtensionPortSpi_Write, WriteBufferPointer, WriteBufferLength, EXTENSION_BUS_SPI_TX_RX_TIMEOUT_IN_MS, ExtensionPortSpiCtrl_AckAwaitLow, ExtensionPortSpiCtrl_CSHigh, ReadBufferPointer, ExtensionPortSpi_Read, ReadBufferLength.
Referenced by Sigfox_SendWakeUp, Sigfox_SendToSleep, Sigfox_GetInfo, Sigfox_SendPayload, Sigfox_SetRCZ1, Sigfox_SetRCZ2, Sigfox_SetRCZ3, Sigfox_SetRCZ4, Sigfox_ResetMacroChannel, Sigfox_SetPrivateKey, Sigfox_SetPublicKey, Sigfox_SendBit, Sigfox_GetSOCVersion, Sigfox_SetFCCMacroChannel, Sigfox_UpdatePACurve, Sigfox_ReadPACurve.
static void PrintInfo(void)
Function to print Device ID, PAC and Lib info.
Refer function prototype for description
References ReadBufferPointer.
Referenced by Sigfox_GetInfo.
static void PrintSOCVersion(void)
Function to print chip SOC Version.
Refer function prototype for description
References ReadBufferPointer.
Referenced by Sigfox_GetSOCVersion.
Retcode_T Sigfox_Enable(void)
This will enable the Sigfox communication. It wakes up the chip and prepares it for further communication exchange.
Refer interface header for description
References BSP_Board_Delay, Sigfox_SendWakeUp.
Retcode_T Sigfox_GetInfo(void)
Send getInfo command to SOC OL2385 to get ID and PAC and lib version.
Refer interface header for description
References RETCODE_OK, WriteBufferPointer, SIGFOX_GETINFO_LEN, SIGFOX_GETINFO_ID, WriteBufferLength, HandleSPIDataTransfer, PrintInfo.
Retcode_T Sigfox_GetSOCVersion(void)
Retrieve device & software version of OL2385 chip.
Refer interface header for description
References RETCODE_OK, WriteBufferPointer, SIGFOX_GETSOCV_LEN, SIGFOX_GETSOCV_ID, WriteBufferLength, HandleSPIDataTransfer, PrintSOCVersion.
void Sigfox_PrintRXPayload(void)
Print Downlink Payload.
Refer interface header for description
References DownlinkPayload.
Retcode_T Sigfox_ReadPACurve(uint8_t subcommand)
Read PA Curve. Only subcommands 0-ReadETSIPATable and 3-ReadFCCPATable are supported.
Refer interface header for description
References RETCODE_OK, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, WriteBufferPointer, SIGFOX_READPACURVE_LEN, SIGFOX_READPACURVE_ID, WriteBufferLength, HandleSPIDataTransfer, ReadBufferLength, ReadBufferPointer.
Retcode_T Sigfox_ResetMacroChannel(void)
Reset Macrochannel (for RCZ2 and RCZ4 only)
Refer interface header for description
References RETCODE_OK, WriteBufferPointer, SIGFOX_RESETMACROCHANNEL_LEN, SIGFOX_RESETMACROCHANNEL_ID, WriteBufferLength, HandleSPIDataTransfer, ReadBufferLength, ReadBufferPointer.
Retcode_T Sigfox_SendBit(void)
Send sigfox empty frame.
Refer interface header for description
References RETCODE_OK, WriteBufferPointer, SIGFOX_SENDBIT_LEN, SIGFOX_SENDBIT_ID, WriteBufferLength, HandleSPIDataTransfer, ReadBufferLength, ReadBufferPointer.
Retcode_T Sigfox_SendPayload(uint8_t *payload, uint8_t payloadSize, bool downlinkFlag)
Send sigfox payload.
Refer interface header for description
References RETCODE_OK, SIGFOX_SEND_PAYLOAD_LEN_MAX, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM, NULL, RETCODE_NULL_POINTER, WriteBufferPointer, SIGFOX_SENDPAYLOADACK_ID, SIGFOX_SENDPAYLOAD_ID, WriteBufferLength, HandleSPIDataTransfer, ReadBufferLength, DownlinkPayload, ReadBufferPointer.
Retcode_T Sigfox_SendToSleep(void)
Send Innocomm chipset to sleep mode.
Refer interface header for description
References RETCODE_OK, WriteBufferPointer, SIGFOX_SENDTOSLEEP_LEN, SIGFOX_SENDTOSLEEP_ID, WriteBufferLength, HandleSPIDataTransfer, ExtensionPortSpi_DeInitialize, ExtensionPortSpiCtrl_DeInitialize.
Retcode_T Sigfox_SendWakeUp(void)
Send wakeup command to SOC OL2385. Should be used before sending a payload as SOC goes in sleep mode automatically.
Refer interface header for description
References RETCODE_OK, WriteBufferPointer, SIGFOX_SENDWAKEUP_LEN, SIGFOX_SENDWAKEUP_ID, WriteBufferLength, HandleSPIDataTransfer, BSP_Board_Delay.
Referenced by Sigfox_Enable.
Retcode_T Sigfox_SetFCCMacroChannel(uint32_t *configWords, uint8_t defaultChannelConfig)
Set FCC Macrochannel. config_words[0] are for Channels 1 to 32 (902.2MHz to 911.5MHz) config_words[1] are for Channels 33 to 64 (911.8MHz to 921.1MHz) config_words[2] are for Channels 65 to 86 (921.4MHz to 927.7MHz)
Refer interface header for description
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, WriteBufferPointer, SIGFOX_SETFCCMACROCHANNEL_LEN, SIGFOX_SETFCCMACROCHANNEL_ID, WriteBufferLength, HandleSPIDataTransfer, ReadBufferLength, ReadBufferPointer.
Retcode_T Sigfox_SetPrivateKey(void)
Set AES Private Key (default mode)
Refer interface header for description
References RETCODE_OK, WriteBufferPointer, SIGFOX_PRIVATEKEY_LEN, SIGFOX_PRIVATEKEY_ID, WriteBufferLength, HandleSPIDataTransfer, ReadBufferLength, ReadBufferPointer.
Retcode_T Sigfox_SetPublicKey(void)
Set AES Public Key (to use with SNEK)
Refer interface header for description
References WriteBufferPointer, SIGFOX_PUBLICKEY_LEN, SIGFOX_PUBLICKEY_ID, WriteBufferLength, HandleSPIDataTransfer.
Retcode_T Sigfox_SetRCZ1(void)
Set Radio Zone 1 (ETSI)
Refer interface header for description
References RETCODE_OK, WriteBufferPointer, SIGFOX_SETRCZ1_LEN, SIGFOX_SETRCZ1_ID, WriteBufferLength, HandleSPIDataTransfer, ReadBufferLength, ReadBufferPointer.
Retcode_T Sigfox_SetRCZ2(void)
Set Radio Zone 2.
Refer interface header for description
References RETCODE_OK, WriteBufferPointer, SIGFOX_SETRCZ2_LEN, SIGFOX_SETRCZ2_ID, WriteBufferLength, HandleSPIDataTransfer, ReadBufferLength, ReadBufferPointer.
Retcode_T Sigfox_SetRCZ3(void)
Set Radio Zone 3.
Refer interface header for description
References RETCODE_OK, WriteBufferPointer, SIGFOX_SETRCZ3_LEN, SIGFOX_SETRCZ3_ID, WriteBufferLength, HandleSPIDataTransfer, ReadBufferLength, ReadBufferPointer.
Retcode_T Sigfox_SetRCZ4(void)
Set Radio Zone 4.
Refer interface header for description
References RETCODE_OK, WriteBufferPointer, SIGFOX_SETRCZ4_LEN, SIGFOX_SETRCZ4_ID, WriteBufferLength, HandleSPIDataTransfer, ReadBufferLength, ReadBufferPointer.
Retcode_T Sigfox_Setup(void)
This will setup the Sigfox communication by initializing the SPI interface with the chip and allocating the necessary buffers for memory.
Refer interface header for description
References RETCODE_OK, ExtensionPortSpi_Config_S::BaudRate, EXTENSION_BUS_SPI_BAUDRATE, EXTENSION_PORT_SPI_BIT_ORDER_MSB_FIRST, EXTENSION_PORT_SPI_CLOCK_MODE_1, ReadBufferPointer, ReadBuffer, WriteBufferPointer, WriteBuffer, ExtensionPortSpiCtrl_Initialize, ExtensionPortSpi_Initialize.
Retcode_T Sigfox_UpdatePACurve(uint8_t subcommand)
Update PA Curve. Only subcommands 1-UpdateETSIPATable and 4-UpdateFCCPATable are supported PA Curves tables are hardcoded in Sigfox.c file.
Refer interface header for description
References RETCODE_OK, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, WriteBufferPointer, SIGFOX_UPDATEPACURVE_LEN, SIGFOX_UPDATEPACURVE_ID, WriteBufferLength, ETSIPATable, FCCPATable, HandleSPIDataTransfer, ReadBufferLength, ReadBufferPointer.