SystemStartup.c
BCDS_MODULE_ID
This module contains "Main" routine and the APIs , in which user can easily integrate application specific routines.
BLE_MAC_USERPAGE_FLAG_BIT
Referenced by systemStartup.
WIFI_MAC_USERPAGE_FLAG_BIT
Referenced by systemStartup.
struct NVM_S NVMUser
Global instance that is used by NVM to maintain internal (secured) data.
Global instance for NMV section that is placed in user data flash. Usually the application has to create an instance of this structure. It may then be used by other modules to access the user data section
Referenced by FOTA_UpdateSdcardFw, Utils_GetMacInfoFromNVM.
uint8_t NVMUserData[NVM_SECTION_UserPage_BUFFER_SIZE][NVM_SECTION_UserPage_BUFFER_SIZE]
Data buffer of the user data NVM section.
This buffer is used by the NVM module to access and write the non volatile memory (NVM) section in the user data page of the internal flash.
BSP_Systick_Callback_T SystickPreCallback
Referenced by SysTickPreCallback, systemStartup.
void assertIndicationMapping(const unsigned long line, const unsigned char *const file)
This API is called when function enters an assert.
line : line number where asserted file : file name which is asserted
References RETCODE_OK, BSP_LED_COMMAND_ON, vTaskSuspendAll.
Referenced by systemStartup.
void DefaultErrorHandlingFunc(Retcode_T error, bool isfromIsr)
System Error Handling routine.
Error Error Information from Basic isfromIsr :currently unused, can be used for future implementation.
References Retcode_GetPackage, Retcode_GetCode, Retcode_GetModuleId, Retcode_GetSeverity, RETCODE_SEVERITY_FATAL, RETCODE_SEVERITY_ERROR, RETCODE_SEVERITY_WARNING, RETCODE_SEVERITY_INFO.
Referenced by main.
Retcode_T systemStartup(void)
The main function initializes the hardware and starts the RTOS scheduler.
returns RETCODE_OK for successful intialisation.
References RETCODE_OK, NULL, BSP_Board_OSTickInitialize, SystickPreCallback, Assert_Initialize, assertIndicationMapping, BSP_Board_Initialize, UsbResetUtility_Init, NVM_Initialize, NVM_ReadUInt8, NVM_ITEM_CONTENT_INDEX, BLE_MAC_USERPAGE_FLAG_BIT, WIFI_MAC_USERPAGE_FLAG_BIT, NVM_WriteUInt8, NVM_Flush, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NVM_WIFI_AND_BLE_BIT_SET_FAILED.
Referenced by main.
static void SysTickPreCallback(void)
This function is SysTick Handler. This is called when ever the IRQ is hit. This is a temporary implementation where the SysTick_Handler() is not directly mapped to xPortSysTickHandler(). Instead it is only called if the scheduler has started.
Refer function prototype for description
References xTaskGetSchedulerState, taskSCHEDULER_NOT_STARTED, xPortSysTickHandler, SystickPreCallback.
void vApplicationGetIdleTaskMemory(StaticTask_t **ppxIdleTaskTCBBuffer, StackType_t **ppxIdleTaskStackBuffer, uint32_t *pulIdleTaskStackSize)
References configMINIMAL_STACK_SIZE.
Referenced by vTaskStartScheduler.
void vApplicationGetTimerTaskMemory(StaticTask_t **ppxTimerTaskTCBBuffer, StackType_t **ppxTimerTaskStackBuffer, uint32_t *pulTimerTaskStackSize)
References configTIMER_TASK_STACK_DEPTH.
void vApplicationIdleHook(void)
References MCU_Sleep_EnterSleep.
Referenced by portTASK_FUNCTION.
void vApplicationMallocFailedHook(void)
Referenced by pvPortMalloc.
void vApplicationStackOverflowHook(xTaskHandle *pxTask, signed char *pcTaskName)
This function is called when is stack overflows and the program gets into infinite loop.
Task handle Task name
References RETCODE_OK, BSP_XDK_LED_Y, BSP_LED_COMMAND_ON, BSP_XDK_LED_O, BSP_XDK_LED_R, BSP_LED_COMMAND_OFF.
void xPortSysTickHandler(void)
Referenced by SysTickPreCallback.