TimeStamp.c
BCDS_MODULE_ID
NO_OF_DAYS_PER_100_Y
Referenced by TimeStamp_SecsToTm.
NO_OF_DAYS_PER_400_Y
Referenced by TimeStamp_SecsToTm.
NO_OF_DAYS_PER_4_Y
Referenced by TimeStamp_SecsToTm.
SECS_TO_DAYS_FACTOR
Referenced by TimeStamp_SecsToTm.
TIME_OFFSET
Referenced by TimeStamp_SecsToTm.
TIME_OVERFLOW_INT_MAX_MULTIPLIER
Referenced by TimeStamp_SecsToTm.
TIME_OVERFLOW_INT_MIN_MULTIPLIER
Retcode_T TimeStamp_SecsToTm(int64_t timeInSeconds, struct tm *tm)
This converts time from seconds to struct tm format.
Refer interface header for description
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, TIME_OVERFLOW_INT_MAX_MULTIPLIER, RETCODE_INVALID_PARAM, TIME_OFFSET, SECS_TO_DAYS_FACTOR, NO_OF_DAYS_PER_400_Y, NO_OF_DAYS_PER_100_Y, NO_OF_DAYS_PER_4_Y.
Referenced by AppControllerFireTask, AppControllerFire.
Retcode_T TimeStamp_TmToIso8601(struct tm *tmPtr, char *iso8601Format, uint8_t bufferSize)
This converts time from struct tm format to ISO 8601 format.
Refer interface header for description
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, tm_to_realtime, RETCODE_INVALID_PARAM.
Referenced by AppControllerFire.
static void tm_to_realtime(struct tm *tmPtr)
Convert time to real time.
struct tm * tmPtr tm structure pointer
Referenced by TimeStamp_TmToIso8601.