Utils.c
BCDS_MODULE_ID
static uint8_t* convDecToStr(uint8_t data, uint8_t *str)
Convert Decimal/Hex value to String Format to display Version Information.
data Number which needs to be convert into string to display in Decimal instead of HEX values. in/out] *str pointer to Store/write the Version number in String Format.
Referenced by convert32IntegerToVersionString.
static uint8_t* convert32IntegerToVersionString(uint32_t appVersion, uint32_t xdkVersion, uint8_t *str)
This function is to convert the integer data into a string data.
appVersion - 32 bit value containing the FOTA version information xdkVersion - 32 bit value containing the XDK SW version information in/out] str - pointer to the parsed version string Returns index where the application version starts 1. FOTA capable device only has the Valid application firmware version in that case output format will be example:v3.0.1-0.0.1( XDK Version + Application version) For Non- FOTA capable device version number will be v3.0.1-xx.xx.xx( XDK Version-xx.xx.xx) Also note that the XDK version number is represented in Decimal format (i.e if XDK version is 3.0.1). the following macros maintain to represent the XDK SW release version #define XDKVERSION_MAJOR 3 #define XDKVERSION_MINOR 0 #define XDKVERSION_PATCH 1Also note that the Application version number is represented in Decimal format. example: if user modifies the application version value macros under application.mk as follows MAJOR_SW_NO ?= 0xFF MINOR_SW_NO ?= 0xFF PATCH_SW_NO ?= 0xFF so, the appVersion will be represented as 255.255.255
References NULL, convDecToStr.
Referenced by Utils_GetXdkVersionString.
static uint32_t InterChangeEndianIfNecessaryU32(uint32_t dataU32)
Converts the IP address from little endian format to big endian format if necessary.
uint32_t IP Address Returns Ip address in big endian format
Referenced by Utils_ConvertIpStringToNumber.
Retcode_T Utils_ConvertIpStringToNumber(const char *ipDottedQuad, uint32_t *ipAddress)
Convert human readable IPv4 address to UINT32 which is in big endian format.
Refer interface header for description
References RETCODE_OK, value, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, RETCODE_INVALID_PARAM, InterChangeEndianIfNecessaryU32.
Referenced by AppParseConfigFile, AppTxtParser_WLANIpAddrValue, AppTxtParser_WLANDnsAddrValue, AppTxtParser_WLANGwAddrValue, AppTxtParser_WLANMaskValue.
Retcode_T Utils_GetMacInfoFromNVM(Utils_NVMMacInfo_T nvmMacInfo, uint8_t *data)
This function reads the BLE/wifi MAC address from NVM module.
Refer interface header for description
References RETCODE_OK, NVM_ReadUInt8, NVMUser, NVM_ITEM_CONTENT_INDEX, UTILS_BLE_MAC_DATA, NVM_Read, NVM_BTLE_MAC_INDEX, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NVM_GET_DATA_FAILED, UTILS_WIFI_MAC_DATA, NVM_WIFI_MAC_INDEX, RETCODE_INVALID_PARAM.
Retcode_T Utils_GetXdkVersionString(uint8_t *verstring)
This function to Get the Firmware Version by combining the XDK SW Release (i.e., Workbench Release) version (i.e., 3.0.1) & Fota Container Firmware Version (i.e., 0.0.1) So , the GetFwVersionInfo returns the Version Information as like (i.e., 3.0.1-0.0.1 )
This function to Get the Version string by combining the XDK SW Release (XdkVersion_GetVersion) i.e., Workbench Release version & Fota Container Application Firmware Version So, the combined Version Information will be like (i.e., vAA.BB.CC-aa.bb.cc ) versionNo - Firmware Version (i.e., 3.0.1-0.0.1 if new bootloader or 3.0.1-xx.xx.xx for old bootloader).
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, Fota_PartitionInfo_S::Partition, FOTA_PARTITION_PRIMARY, FOTA_ReadFirmwareVersion, XdkVersion_GetVersion, convert32IntegerToVersionString.
Referenced by AppControllerEnable, firmwareVersionNumber_RO.
void Utils_PrintResetCause(void)
This function prints if last reset was caused due to watchdog timer.
Refer interface header for description
Referenced by AppControllerEnable.