WlanConnect.c
BCDS_MODULE_ID
TIMER_AUTORELOAD_ON
Auto reload of timer is disabled
Referenced by NonBlockingTimer, WlanConnect_Disconnect.
TIMERBLOCKTIME
Macro used to define blocktime of a timer
Referenced by disConnectNonBlockingCall, connectNonBlockingCall, NonBlockingTimer, WlanConnect_Disconnect.
WLANCONNECT_ALL_PROFILES
Macro for deleting all profiles
Referenced by WlanConnect_DeleteAllProfiles.
WLANCONNECT_FAILURE
Macro for defining Failure
Referenced by WlanConnect_DeleteAllProfiles, WlanConnect_ScanNetworks.
WLANCONNECT_MAX_BUFFER
Macro for Simple Link status buffer
WLANCONNECT_MAX_TRIES
Macro for Simple Link status buffer
Referenced by disConnectNonBlockingCall, connectNonBlockingCall, connectBlockingCall, WlanConnect_Disconnect.
WLANCONNECT_NO_OF_ENTRIES
Macro for scan function number of entries
Referenced by WlanConnect_ScanNetworks.
WLANCONNECT_ONE
Macro for defining 1
Referenced by WlanConnect_ScanNetworks.
WLANCONNECT_ONE_SEC_DELAY
Macro for 1 second delay
Referenced by connectBlockingCall, WlanConnect_Disconnect, WlanConnect_ScanNetworks.
WLANCONNECT_SCAN_DISABLE
Referenced by WlanConnect_ScanNetworks.
WLANCONNECT_SCAN_ENABLE
Referenced by WlanConnect_ScanNetworks.
WLANCONNECT_SCAN_TABLE_SIZE
Referenced by WlanConnect_ScanNetworks.
WLANCONNECT_SUCCESS
Macro for defining SUCCESS
Referenced by WlanConnect_Open, WlanConnect_WEP_Open, WlanConnect_WPA, WlanConnect_WPS_PBC, WlanConnect_WPS_PIN, WlanConnect_EnterpriseWPA, WlanConnect_DeleteAllProfiles, WlanConnect_Disconnect, WlanConnect_ScanNetworks.
WLANCONNECT_TIMEOUT_VAL
Macro for timeout value
WLANCONNECT_TIMER_TICKS
Macro for Simple Link status buffer
Referenced by NonBlockingTimer, WlanConnect_Disconnect.
WLANCONNECT_ZERO
Macro for defining 0
Referenced by SystemClock_getTime, WlanConnect_Open, WlanConnect_WPS_PBC, WlanConnect_ScanNetworks.
xTimerHandle ConnectTimerHandle
Referenced by connectNonBlockingCall, NonBlockingTimer.
xTimerHandle DisConnectTimerHandle
Referenced by disConnectNonBlockingCall, WlanConnect_Disconnect.
Sl_WlanNetworkEntry_t NetEntries[WLANCONNECT_SCAN_TABLE_SIZE][WLANCONNECT_SCAN_TABLE_SIZE]
Variable for storing the scanned network entries
volatile uint8_t WlanConnect_InitStatus
Flag variable for Wlan init status
Referenced by WlanConnect_Open, WlanConnect_WEP_Open, WlanConnect_WPA, WlanConnect_WPS_PBC, WlanConnect_WPS_PIN, WlanConnect_EnterpriseWPA, WlanConnect_DeleteAllProfiles, WlanConnect_Disconnect, WlanConnect_ScanNetworks.
volatile WlanConnect_Status_T WlanConnect_Status
Flag variable for WLI connect status
Referenced by WlanConnectcallBack, disConnectNonBlockingCall, connectNonBlockingCall, connectBlockingCall, WlanConnect_Disconnect, WlanConnect_GetCurrentNwStatus.
volatile WlanConnect_Callback_T WlanConnectCallback
Variable for storing the connection callback
Referenced by connectNonBlockingCall, WlanConnect_Open, WlanConnect_WEP_Open, WlanConnect_WPA, WlanConnect_WPS_PBC, WlanConnect_WPS_PIN, WlanConnect_EnterpriseWPA.
volatile WlanConnect_DisconnectCallback_T WlanDisconnectCallback
Variable for storing the disconnection callback from disconnect function
Referenced by disConnectNonBlockingCall, WlanConnect_Disconnect.
static Retcode_T connectBlockingCall(void)
This function is called by connect API's when connection needs to be blocking
References RETCODE_OK, WLAN_DISCONNECTED, WlanConnect_Status, NETWORKCONFIG_IP_NOT_ACQUIRED, NetworkConfig_GetIpStatus, vTaskDelay, WLANCONNECT_ONE_SEC_DELAY, portTICK_RATE_MS, WlanConnect_GetStatus, WLANCONNECT_MAX_TRIES, WLAN_CONNECTED, NETWORKCONFIG_IPV4_ACQUIRED, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_CONNECTION_ERROR, WLAN_CONNECTION_PWD_ERROR, RETCODE_ERROR_WRONG_PASSWORD, RETCODE_ERROR_IP_NOT_ACQ.
Referenced by WlanConnect_Open, WlanConnect_WEP_Open, WlanConnect_WPA, WlanConnect_WPS_PBC, WlanConnect_WPS_PIN, WlanConnect_EnterpriseWPA.
static void connectNonBlockingCall(xTimerHandle xTimer)
This is a timer callback called from connect API's when connection needs to be non-blocking
References BCDS_UNUSED, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_RTOS_QUEUE_ERROR, WlanConnect_Status, WlanConnect_GetStatus, WLAN_CONNECTED, NETWORKCONFIG_IPV4_ACQUIRED, NetworkConfig_GetIpStatus, WlanConnectCallback, xTimerDelete, ConnectTimerHandle, TIMERBLOCKTIME, Retcode_RaiseError, WLAN_DISCONNECTED, WLANCONNECT_MAX_TRIES, WLAN_CONNECTION_ERROR, WLAN_CONNECTION_PWD_ERROR, NETWORKCONFIG_IP_NOT_ACQUIRED.
Referenced by NonBlockingTimer.
static void disConnectNonBlockingCall(xTimerHandle xTimer)
References BCDS_UNUSED, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_RTOS_QUEUE_ERROR, WlanConnect_Status, WlanConnect_GetStatus, WLAN_DISCONNECTED, WlanDisconnectCallback, xTimerDelete, DisConnectTimerHandle, TIMERBLOCKTIME, Retcode_RaiseError, WLANCONNECT_MAX_TRIES, WLAN_DISCONNECT_ERROR.
Referenced by WlanConnect_Disconnect.
static Retcode_T NonBlockingTimer(void)
References RETCODE_OK, ConnectTimerHandle, WLANCONNECT_TIMER_TICKS, TIMER_AUTORELOAD_ON, NULL, connectNonBlockingCall, xTimerStart, TIMERBLOCKTIME, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_TIMERSTART_FAILURE, RETCODE_TIMERCREATE_FAILURE.
Referenced by WlanConnect_Open, WlanConnect_WEP_Open, WlanConnect_WPA, WlanConnect_WPS_PBC, WlanConnect_WPS_PIN, WlanConnect_EnterpriseWPA.
static Retcode_T SystemClock_getTime(uint32_t *time_ptr)
Function that retrieves time stamp. Currently retrieving.
time_ptr Pointer containing time in seconds. returnClockStatus Return status for the SystemClock_getTime function
References RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_TIME_NULL, xTaskGetTickCount, portTICK_RATE_MS, WLANCONNECT_ZERO, RETCODE_OK.
Referenced by WlanConnect_ScanNetworks.
Retcode_T WlanConnect_DeInit(void)
References WlanNetworkConnect_DeInit.
Retcode_T WlanConnect_DeleteAllProfiles(void)
References WlanConnect_InitStatus, WlanConnect_GetInitStatus, WLANCONNECT_NOT_INITIALZED, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, RETCODE_UNEXPECTED_BEHAVIOR, WLANCONNECT_SUCCESS, WLANCONNECT_ALL_PROFILES, RETCODE_OK, WLANCONNECT_FAILURE, RETCODE_SIMPLELINK_ERROR.
Retcode_T WlanConnect_Disconnect(WlanConnect_DisconnectCallback_T disconnectCallback)
References WlanConnect_InitStatus, WlanConnect_GetInitStatus, WLANCONNECT_NOT_INITIALZED, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, RETCODE_UNEXPECTED_BEHAVIOR, WLANCONNECT_SUCCESS, WlanDisconnectCallback, NULL, WLAN_CONNECTED, WlanConnect_Status, WLAN_CONNECTION_PWD_ERROR, vTaskDelay, WLANCONNECT_ONE_SEC_DELAY, portTICK_RATE_MS, WLANCONNECT_MAX_TRIES, WLAN_DISCONNECTED, RETCODE_OK, RETCODE_DISCONNECT_ERROR, DisConnectTimerHandle, WLANCONNECT_TIMER_TICKS, TIMER_AUTORELOAD_ON, disConnectNonBlockingCall, xTimerStart, TIMERBLOCKTIME, RETCODE_TIMERSTART_FAILURE, RETCODE_TIMERCREATE_FAILURE.
Retcode_T WlanConnect_EnterpriseWPA(WlanConnect_SSID_T connectSSID, WlanConnect_Username_T connectUsername, WlanConnect_PassPhrase_T connectPass, WlanConnect_Callback_T connectCallback)
References WlanConnect_InitStatus, WlanConnect_GetInitStatus, WLANCONNECT_NOT_INITIALZED, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, NULL, RETCODE_NULL_POINTER, RETCODE_OK, WLANCONNECT_SUCCESS, SlSecParams_t::Key, SlSecParams_t::KeyLen, SlSecParams_t::Type, SL_SEC_TYPE_WPA_ENT, SlSecParamsExt_t::User, SlSecParamsExt_t::UserLen, SlSecParamsExt_t::AnonUser, SlSecParamsExt_t::AnonUserLen, SlSecParamsExt_t::CertIndex, SlSecParamsExt_t::EapMethod, SL_ENT_EAP_METHOD_PEAP0_MSCHAPv2, WlanConnectCallback, connectBlockingCall, NonBlockingTimer, RETCODE_SIMPLELINK_ERROR.
WlanConnect_CurrentNwStatus_T WlanConnect_GetCurrentNwStatus(void)
References DISCONNECTED_IP_NOT_ACQUIRED, NETWORKCONFIG_IPV4_ACQUIRED, NetworkConfig_GetIpStatus, WLAN_CONNECTED, WlanConnect_Status, CONNECTED_AND_IPV4_ACQUIRED, NETWORKCONFIG_IP_NOT_ACQUIRED, CONNECTED_AND_IP_NOT_ACQUIRED, WLAN_DISCONNECTED, DISCONNECTED_AND_IPV4_ACQUIRED.
uint8_t WlanConnect_GetInitStatus(void)
References WlanNetworkConnect_GetInitStatus.
Referenced by WlanConnect_Open, WlanConnect_WEP_Open, WlanConnect_WPA, WlanConnect_WPS_PBC, WlanConnect_WPS_PIN, WlanConnect_EnterpriseWPA, WlanConnect_DeleteAllProfiles, WlanConnect_Disconnect, WlanConnect_ScanNetworks.
WlanConnect_Status_T WlanConnect_GetStatus(void)
References WlanNetworkConnect_GetStatus.
Referenced by disConnectNonBlockingCall, connectNonBlockingCall, connectBlockingCall.
Retcode_T WlanConnect_Init(void)
References WlanNetworkConnect_Init, WlanConnectcallBack.
Retcode_T WlanConnect_Open(WlanConnect_SSID_T connectSSID, WlanConnect_Callback_T connectCallback)
References WlanConnect_InitStatus, WlanConnect_GetInitStatus, WLANCONNECT_NOT_INITIALZED, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, NULL, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, RETCODE_OK, WLANCONNECT_SUCCESS, SlSecParams_t::KeyLen, WLANCONNECT_ZERO, SlSecParams_t::Type, SL_SEC_TYPE_OPEN, WlanConnectCallback, connectBlockingCall, NonBlockingTimer, RETCODE_SIMPLELINK_ERROR.
Retcode_T WlanConnect_ScanNetworks(WlanConnect_ScanInterval_T scanInterval, WlanConnect_ScanList_T *scanList)
References WlanConnect_InitStatus, WlanConnect_GetInitStatus, WLANCONNECT_NOT_INITIALZED, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, NULL, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, WLANCONNECT_SUCCESS, RETCODE_UNEXPECTED_BEHAVIOR, WLANCONNECT_ZERO, WLANCONNECT_NO_OF_ENTRIES, WlanConnect_ScanList_S::NumOfScanEntries, WlanConnect_ScanList_S::TimeStamp, WlanConnect_ScanList_S::ScanData, SL_POLICY_CONNECTION, SL_CONNECTION_POLICY, SL_POLICY_SCAN, WLANCONNECT_SCAN_ENABLE, _u8, vTaskDelay, WLANCONNECT_ONE_SEC_DELAY, portTICK_RATE_MS, WLANCONNECT_FAILURE, RETCODE_SIMPLELINK_ERROR, WLANCONNECT_SCAN_TABLE_SIZE, WLANCONNECT_SCAN_DISABLE, WLANCONNECT_ONE, WLANCONNECT_MAX_SSID_LENGTH, WlanConnect_ScanInfo_S::Ssid, Sl_WlanNetworkEntry_t::ssid, WLANCONNECT_MAX_MAC_ADDR_LEN, WlanConnect_ScanInfo_S::Bssid, Sl_WlanNetworkEntry_t::bssid, WlanConnect_ScanInfo_S::SsidLength, Sl_WlanNetworkEntry_t::ssid_len, WlanConnect_ScanInfo_S::SecurityType, Sl_WlanNetworkEntry_t::sec_type, WlanConnect_ScanInfo_S::Rssi, Sl_WlanNetworkEntry_t::rssi, SystemClock_getTime, RETCODE_NO_NW_AVAILABLE, RETCODE_OK.
Retcode_T WlanConnect_WEP_Open(WlanConnect_SSID_T connectSSID, WlanConnect_PassPhrase_T connectPass, uint8_t passPhraseLength, WlanConnect_Callback_T connectCallback)
References WlanConnect_InitStatus, WlanConnect_GetInitStatus, WLANCONNECT_NOT_INITIALZED, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, NULL, RETCODE_NULL_POINTER, RETCODE_OK, WLANCONNECT_SUCCESS, SlSecParams_t::Key, SlSecParams_t::KeyLen, SlSecParams_t::Type, SL_SEC_TYPE_WEP, WlanConnectCallback, connectBlockingCall, NonBlockingTimer, RETCODE_SIMPLELINK_ERROR.
Retcode_T WlanConnect_WPA(WlanConnect_SSID_T connectSSID, WlanConnect_PassPhrase_T connectPass, WlanConnect_Callback_T connectCallback)
References WlanConnect_InitStatus, WlanConnect_GetInitStatus, WLANCONNECT_NOT_INITIALZED, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, NULL, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, RETCODE_OK, WLANCONNECT_SUCCESS, SlSecParams_t::Key, SlSecParams_t::KeyLen, SlSecParams_t::Type, SL_SEC_TYPE_WPA, WlanConnectCallback, connectBlockingCall, NonBlockingTimer, RETCODE_SIMPLELINK_ERROR.
Retcode_T WlanConnect_WPS_PBC(WlanConnect_Callback_T connectCallback)
References WlanConnect_InitStatus, WlanConnect_GetInitStatus, WLANCONNECT_NOT_INITIALZED, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, RETCODE_OK, WLANCONNECT_SUCCESS, SlSecParams_t::Key, NULL, SlSecParams_t::KeyLen, WLANCONNECT_ZERO, SlSecParams_t::Type, SL_SEC_TYPE_WPS_PBC, WlanConnectCallback, WLANCONNECT_DUMMY_SSID, connectBlockingCall, NonBlockingTimer, RETCODE_SIMPLELINK_ERROR.
Retcode_T WlanConnect_WPS_PIN(WlanConnect_Callback_T connectCallback)
References WlanConnect_InitStatus, WlanConnect_GetInitStatus, WLANCONNECT_NOT_INITIALZED, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, RETCODE_OK, WLANCONNECT_SUCCESS, SlSecParams_t::Key, WLANCONNECT_ENROLLEE_PIN, SlSecParams_t::KeyLen, SlSecParams_t::Type, SL_SEC_TYPE_WPS_PIN, WlanConnectCallback, WLANCONNECT_DUMMY_SSID, NULL, connectBlockingCall, NonBlockingTimer, RETCODE_SIMPLELINK_ERROR.
static void WlanConnectcallBack(WlanConnect_Status_T connectStatus)
References WlanConnect_Status.
Referenced by WlanConnect_Init.