XDK_Utils.h
XDK_NETWORK_IPV4
Utils_NVMMacInfo_E
typedef enum Utils_NVMMacInfo_E Utils_NVMMacInfo_T
Typedef to represent theNvm Data Info.
Retcode_T Utils_ConvertIpStringToNumber(const char *ipDottedQuad, uint32_t *ipAddress)
Convert human readable IPv4 address to UINT32 which is in big endian format.
ipDottedQuad Input C string e.g. "192.168.0.1" ipAddress ipAddress pointer to variable to hold the ip data RETCODE_OK in case of success RETCODE_NULL_POINTER when the ipDottedQuad or ipAddress is NULL RETCODE_INVALID_PARAM when the parameter is invalid Refer interface header for description
References RETCODE_OK, value, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, RETCODE_INVALID_PARAM, InterChangeEndianIfNecessaryU32.
Referenced by AppParseConfigFile, AppTxtParser_WLANIpAddrValue, AppTxtParser_WLANDnsAddrValue, AppTxtParser_WLANGwAddrValue, AppTxtParser_WLANMaskValue.
Retcode_T Utils_GetMacInfoFromNVM(Utils_NVMMacInfo_T nvmMacInfo, uint8_t *data)
This function reads the BLE/wifi MAC address from NVM module.
nvmMacInfo medium(BLE/WIFI) whose data should be read from NVM. data Pointer to the buffer to store data. RETCODE_OK in success scenario, error case otherwise The buffer length for MAC address for BLE and WIFI is 6 bytes Refer interface header for description
References RETCODE_OK, NVM_ReadUInt8, NVMUser, NVM_ITEM_CONTENT_INDEX, UTILS_BLE_MAC_DATA, NVM_Read, NVM_BTLE_MAC_INDEX, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NVM_GET_DATA_FAILED, UTILS_WIFI_MAC_DATA, NVM_WIFI_MAC_INDEX, RETCODE_INVALID_PARAM.
Retcode_T Utils_GetXdkVersionString(uint8_t *verstring)
This function to Get the Version string by combining the XDK SW Release (XdkVersion_GetVersion) i.e., Workbench Release version & Fota Container Application Firmware Version So, the combined Version Information will be like (i.e., vAA.BB.CC-aa.bb.cc )
verstring - XDK Version string.For Fota support XDK SW, verstring = vAA.BB.CC-aa.bb.cc, XDK Version string.For Fota support XDK SW, verstring = vAA.BB.CC-aa.bb.cc, . XDK SW Release version, AA - Major; BB - Minor; CC - PatchApplication Firmware Version aa - Major; bb - Minor; cc - PatchIf Fota supported XDK SW, then verstring = vAA.BB.CC-aa.bb.cc. for without Fota supported XDK SW verstring = vAA.BB.CC-xx.xx.xxxx.xx.xx means not applicable. RETCODE_OK if success, or an error code otherwise. This function to Get the Version string by combining the XDK SW Release (XdkVersion_GetVersion) i.e., Workbench Release version & Fota Container Application Firmware Version So, the combined Version Information will be like (i.e., vAA.BB.CC-aa.bb.cc ) versionNo - Firmware Version (i.e., 3.0.1-0.0.1 if new bootloader or 3.0.1-xx.xx.xx for old bootloader).
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, Fota_PartitionInfo_S::Partition, FOTA_PARTITION_PRIMARY, FOTA_ReadFirmwareVersion, XdkVersion_GetVersion, convert32IntegerToVersionString.
Referenced by AppControllerEnable, firmwareVersionNumber_RO.
void Utils_PrintResetCause(void)
This function prints if last reset was caused due to watchdog timer.
Refer interface header for description
Referenced by AppControllerEnable.