XDK_HTTPRestClient.h
typedef struct HTTPRestClient_Config_S HTTPRestClient_Config_T
Typedef to represent the HTTP Rest Client POST/GET common configuration.
typedef struct HTTPRestClient_Get_S HTTPRestClient_Get_T
Typedef to represent the HTTP Rest Client GET configuration.
typedef void(* HTTPRestClient_GetCB_T)(const char *responseContent, uint32_t responseContentLen, bool isLastMessage))(const char *responseContent, uint32_t responseContentLen, bool isLastMessage)
Typedef of the HTTP GET payload callback.
responseContent Pointer to the GET request response responseContentLen Length of the GET request response isLastMessage Boolean to represent if it is the last part of the ongoing message
typedef struct HTTPRestClient_Post_S HTTPRestClient_Post_T
Typedef to represent the HTTP Rest Client POST configuration.
typedef struct HTTPRestClient_Setup_S HTTPRestClient_Setup_T
Typedef to represent the HTTP Rest Client setup feature.
Retcode_T HTTPRestClient_Enable(void)
This will enable the HTTP rest client.
RETCODE_OK on success, or an error code otherwise. If setup->IsSecure was enabled at the time of HTTPRestClient_Setup, then we will enable the HTTPs server certificates as well.HTTPRestClient_Setup must have been successful prior.WLAN_Enable must have been successful prior.Do not call this API more than once.
Referenced by AppControllerEnable.
Retcode_T HTTPRestClient_Get(HTTPRestClient_Config_T *config, HTTPRestClient_Get_T *get, uint32_t timeout)
This will do a HTTP rest client GET request.
config Pointer to the HTTP Rest Client general configuration get Pointer to the HTTP Rest Client GET specific configuration timeout Timeout in milli-second to complete a GET cycle RETCODE_OK on success, or an error code otherwise. HTTPRestClient_Setup and HTTPRestClient_Enable must have been successful prior.This is a blocking callIf get->GetCB can be NULL, but then the application will not be notified of the response received from the server. HTTPRestClient_Post note. GET is similar to POST w.r.t TCP Socket layer. Therefore 100 milli-second delay is expected to be provided by the user as a wait time if he is to GET continuously.
Referenced by AppControllerFire.
Retcode_T HTTPRestClient_GetFirmware(HTTPRestClient_Config_T *config, HTTPRestClient_Get_T *get, uint32_t timeout)
This will do Firmware download through http and stored it in sd card if the get->GetCB is NULL. If get->GetCB is defined, then firmware data will be passed to application.
config Pointer to the HTTP Rest Client general configuration get Pointer to the HTTP Rest Client GET specific configuration timeout GET cycle response timeout in milli second RETCODE_OK on success, or an error code otherwise. File system and sd card must be initialized before calling this apiAfter successful completion of fota download, firmware verification also done in this functionIf get->GetCB can be NULL, but then the application will not be notified of the response received from the server.This is a blocking callIf get->GetCB is NULL then, Provide the Url path from where can get the bin data. While downloading, this api will append the get size and offset to the given url Example: if the given get->Url = "/range", then while downloading it will append get size and offset like "/range/512/0/" Here 512 is get size and 0 is bin file offset position Final url "/range/512/0/" only used to request the bin data from serverFirmware file is stored as firmware.bin after the verification. it will overwrite if it is already present. If get->GetCB is defined then, Provide the Url path from where can get the bin data along with size and offset
Retcode_T HTTPRestClient_Post(HTTPRestClient_Config_T *config, HTTPRestClient_Post_T *post, uint32_t timeout)
This will do a HTTP rest client POST.
config Pointer to the HTTP Rest Client general configuration post Pointer to the HTTP Rest Client POST specific configuration timeout Timeout in milli-second to complete a POST cycle RETCODE_OK on success, or an error code otherwise. HTTPRestClient_Setup and HTTPRestClient_Enable must have been successful prior.This is a blocking callHTTP is on top of TCP for XDK, there is something called “KeepAlive” feature for the HTTP session which the serval stack currently doesn’t allow it to be configured. This is currently “false”. This means that every single time, when there is a HTTP POST, a new TCP socket is opened, HTTP session is established and data is POST’ed followed by socket closure. Now, from an application perspective, the moment a payload is POST’ed, we would receive a notification that this was successful. And then the ServalStack will proceed to close the session and the socket. This takes some time based on the system load. During this time, if we trigger another HTTP POST, since the socket is busy with “close procedure”, the trigger would fail. Worst case, 100 milli-second delay is expected to be provided by the user as a wait time if he is to POST continuously.
Referenced by AppControllerFire.
Retcode_T HTTPRestClient_Setup(HTTPRestClient_Setup_T *setup)
This will setup the HTTP rest client.
setup Pointer to the HTTP Rest Client setup feature RETCODE_OK on success, or an error code otherwise. If setup->IsSecure is enabled, then we will setup the HTTPs server certificates as well.This must be the first API to be called if HTTP Rest Client feature is to be used.Do not call this API more than once.
Referenced by AppControllerSetup.