XDK_MQTT.h
MQTT_Type_E
typedef struct MQTT_Connect_S MQTT_Connect_T
Typedef to represent the MQTT connect feature.
typedef struct MQTT_Publish_S MQTT_Publish_T
Typedef to represent the MQTT publish feature.
typedef struct MQTT_Setup_S MQTT_Setup_T
Typedef to represent the MQTT setup feature.
typedef struct MQTT_Subscribe_S MQTT_Subscribe_T
Structure to represent the MQTT subscribe feature.
typedef void(* MQTT_SubscribeCB_T)(MQTT_SubscribeCBParam_T param))(MQTT_SubscribeCBParam_T param)
Typedef to the function to be called upon receiving incoming MQTT messages.
typedef struct MQTT_SubscribeCBParam_S MQTT_SubscribeCBParam_T
Typedef to represent the incoming MQTT message information.
typedef enum MQTT_Type_E MQTT_Type_T
Typedef to represent the supported MQTT type.
Retcode_T MQTT_ConnectToBroker(MQTT_Connect_T *mqttConnect, uint32_t timeout)
This will connect to a MQTT broker.
mqttConnect Pointer to the MQTT connect feature timeout Timeout in milli-second to await successful connection RETCODE_OK on success, or an error code otherwise.
Referenced by AppControllerFireTask, AppControllerValidateWLANConnectivity, AppControllerFire.
Retcode_T MQTT_Enable(void)
This will enable the MQTT by connecting to the broker.
RETCODE_OK on success, or an error code otherwise. If setup->IsSecure was enabled at the time of MQTT_Setup, then we will enable the HTTPs server certificates as well.MQTT_Setup must have been successful prior.WLAN_Enable must have been successful prior.Do not call this API more than once.
Referenced by AppControllerEnable.
Retcode_T MQTT_PublishToTopic(MQTT_Publish_T *publish, uint32_t timeout)
This will publish to a MQTT topic.
subscribe Pointer to the MQTT publish feature timeout Timeout in milli-second to await successful publication RETCODE_OK on success, or an error code otherwise.
Referenced by AppControllerFireTask, AppControllerFire.
Retcode_T MQTT_Setup(MQTT_Setup_T *setup)
This will setup the MQTT.
setup Pointer to the MQTT setup feature RETCODE_OK on success, or an error code otherwise. This must be the first API to be called if MQTT feature is to be used.Do not call this API more than once.
Referenced by AppControllerSetup.
Retcode_T MQTT_SubsribeToTopic(MQTT_Subscribe_T *subscribe, uint32_t timeout)
This will subscribe to a MQTT topic.
subscribe Pointer to the MQTT subscribe feature timeout Timeout in milli-second to await successful subscription RETCODE_OK on success, or an error code otherwise.
Referenced by AppControllerFireTask, AppControllerValidateWLANConnectivity, AppControllerFire.