XDK_ExternalSensor.h
ExternalSensor_Max31865TempType_E
PT100 based temperature sensor
ExternalSensor_Target_E
typedef struct ExternalSensor_Enable_S ExternalSensor_Enable_T
Typedef to represent the Sensor to be enabled.
typedef struct ExternalSensor_LemConfig_S ExternalSensor_LemConfig_T
typedef struct ExternalSensor_Max31865Config_S ExternalSensor_Max31865Config_T
typedef enum ExternalSensor_Max31865TempType_E ExternalSensor_Max31865TempType_T
Typedef representing the the external temperature sensor..
typedef struct ExternalSensor_Setup_S ExternalSensor_Setup_T
Typedef to represent the Sensor setup features.
typedef enum ExternalSensor_Target_E ExternalSensor_Target_T
Typedef representing the supported External sensor.
typedef struct ExternalSensor_Value_S ExternalSensor_Value_T
Typedef to represent the Data Collector sampled node information.
Retcode_T ExternalSensor_Enable(void)
This will enable the External Sensor module.
RETCODE_OK on success, or an error code otherwise. Based on setup->Enable value, it will enable the necessary sensors.ExternalSensor_Setup must have been successful prior.Do not call this API more than once.
Referenced by AppControllerEnable.
Retcode_T ExternalSensor_GetData(ExternalSensor_Value_T *value)
This will sample the necessary sensor nodes and update the data.
in/out] value The sampled sensor node values. User must provide a valid buffer. RETCODE_OK on success, or an error code otherwise. ExternalSensor_Setup and ExternalSensor_Enable must have been successful prior.This is a blocking callExternalSensor_GetData are not thread safe, yet.
Referenced by AppControllerFire.
Retcode_T ExternalSensor_GetLemData(float *xLemI, float *xLemV)
Referenced by SampleAndNotifyHighPriorityData.
Retcode_T ExternalSensor_GetMax31865Data(float *xMaxT, float *xMaxR)
Referenced by SampleAndNotifyHighPriorityData.
Retcode_T ExternalSensor_HwStatusPinDeInit(void)
Referenced by HandleExternalHwHotPlug, AppControllerSetup.
Retcode_T ExternalSensor_HwStatusPinInit(void)
Referenced by HandleExternalHwHotPlug, AppControllerSetup.
Retcode_T ExternalSensor_IsAvailable(ExternalSensor_Target_T sensor, bool *status)
This will validate if the Sensor is available or not.
sensor External sensor to be validated for availability status Pointer to the availability of the requested sensor availability status More than one sensor availability can be validated in single request RETCODE_OK on success, or an error code otherwise.
Referenced by CurrentExternalHWConnected, AppControllerSetup.
Retcode_T ExternalSensor_Setup(ExternalSensor_Setup_T *setup)
This will setup the External Sensor module.
setup Pointer to the Sensor setup feature RETCODE_OK on success, or an error code otherwise. This must be the first API to be called if this Sensor feature is to be used.Enable required sensor which is connected on external board.Do not call this API more than once.
Referenced by AppControllerSetup.