XDK_LWM2M.h
LWM2M_ConnectivityMonitoring_E
LWM2M_LedMixMode_E
LWM2M_SecurityMode_E
Pre-Shared Key
LWM2M_StatusNotification_E
LWM2M device registration succeeded
LWM2M_TestMode_E
typedef enum LWM2M_ConnectivityMonitoring_E LWM2M_ConnectivityMonitoring_T
Typedef to represent the LWM2M Connectivity Monitoring parameter configurable by the user.
typedef enum LWM2M_LedMixMode_E LWM2M_LedMixMode_T
Typedef to represent the possible safe LED configuration for the application when the Light control is not confined only with the LWM2M module, but also shared for the application.
typedef enum LWM2M_SecurityMode_E LWM2M_SecurityMode_T
Typedef to represent the supported LWM2M security mode.
typedef struct LWM2M_SecurityPreSharedKeyInfo_S LWM2M_SecurityPreSharedKeyInfo_T
Typedef to configure the LWM2M security mode -Pre-Shared Key value.
typedef struct LWM2M_Setup_S LWM2M_Setup_T
Typedef to represent the LWM2M setup feature.
typedef enum LWM2M_StatusNotification_E LWM2M_StatusNotification_T
Typedef to represent the LWM2M status notification.
typedef void(* LWM2M_StatusNotificationCB_T)(LWM2M_StatusNotification_T status))(LWM2M_StatusNotification_T status)
Typedef of the LWM2M status notification callback.
status run-time status of the LWM2M stack
typedef enum LWM2M_TestMode_E LWM2M_TestMode_T
Enum to represent the LWM2M test mode.
Retcode_T LWM2M_AlertNotification(char *value)
The function initiates an alert notification.
value Pointer to the string to be notified to the server via Alert Notification object resource. RETCODE_OK on success, or an error code otherwise. LWM2M_Register must have been successful prior.The value is considers as a string and hence must be NULL terminated.The maximum size of value string must not exceed 128 bytes including the NULL terminator.
Referenced by Button1Callback.
Retcode_T LWM2M_ConnectivityMonitoring(LWM2M_ConnectivityMonitoring_T notify, void *value)
The function sets LWM2M Connectivity Monitoring parameters.
notify Parameter configurable by the user. value If notify is LWM2M_SET_IP_ADDRESS, this is a const char * string value. If notify is LWM2M_SET_RADIO_SIGNAL_STRENGTH, this is a int value. RETCODE_OK on success, or an error code otherwise. LWM2M_Register must have been successful prior.
Referenced by AppControllerWLANMonitor.
Retcode_T LWM2M_Enable(void)
This will enable the LWM2M.
RETCODE_OK on success, or an error code otherwise. LWM2M_Setup must have been successful prior.Do not call this API more than once.
Referenced by AppControllerEnable.
Retcode_T LWM2M_LedMixModeControl(LWM2M_LedMixMode_T state)
The function initiates provides a safe LED configuration for the application when the Light control is not confined only with the LWM2M module, but also shared for the application.
state User expected LED state. RETCODE_OK on success, or an error code otherwise. LWM2M_Register must have been successful prior.Do not use this when .
Referenced by Button1Callback, Button2Callback.
Retcode_T LWM2M_Register(void)
The function initiates the LWM2M registration of the node to the LWM2M Server.
RETCODE_OK on success, or an error code otherwise. LWM2M_Enable must have been successful prior.WLAN_Enable must have been successful prior.Do not call this API more than once.
Referenced by AppControllerFireTask, AppControllerFire.
Retcode_T LWM2M_Setup(LWM2M_Setup_T *setup)
This will setup the LWM2M.
setup Pointer to the LWM2M setup feature RETCODE_OK on success, or an error code otherwise. This must be the first API to be called if LWM2M feature is to be used.Do not call this API more than once.
Referenced by AppControllerSetup.
Retcode_T LWM2M_TriggerForceRegister(void)
The function forcefully triggers the LWM2M registration of the node to the LWM2M Server irrespective of the current node status.
RETCODE_OK on success, or an error code otherwise. LWM2M_Enable must have been successful prior.
Referenced by Button1Callback, Button2Callback.