XDK_FOTA.h
Fota_Partition_E
Active running Fota container firmware in the controller FLASH memory
typedef enum Fota_Partition_E Fota_Partition_T
typedef struct Fota_PartitionInfo_S Fota_PartitionInfo_T
struct FWContainer_Footer_S __attribute__
Usage Fault exception handlerBUS Fault exception handlerMemory Manager Fault exception handler
Retcode_T FOTA_ReadFirmwareCRC(Fota_PartitionInfo_T partitionInfo, uint32_t *firmwareCRC)
This function reads the Fota container firmware CRC on the fota header from the specified partition.
partitionInfo mention the partition information from which firmware CRC info needs to be read. In-case of FOTA_PARTITION_DOWNLOAD specify the file name Incase of FOTA_PARTITION_PRIMARY file name is not used, can be NULL. firmwareCRC pointer to hold the Fota container firmware CRC information. Storage_Setup & Storage_Enable must be called prior to using this API. RETCODE_OK if fota container firmware CRC is read properly, or an error code otherwise.
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, FOTA_ReadHeader.
Referenced by FOTA_UpdateSdcardFw.
Retcode_T FOTA_ReadFirmwareVersion(Fota_PartitionInfo_T partitionInfo, uint32_t *firmwareVer)
This function reads the Fota container firmware version on the fota header from the specified partition.
partitionInfo mention the partition information from which Firmware version needs to be read. In-case of FOTA_PARTITION_DOWNLOAD specify the file name Incase of FOTA_PARTITION_PRIMARY file name is not used can be NULL. firmwareVer pointer to hold the Fota container firmware version information. Storage_Setup & Storage_Enable must be called prior to using this API. RETCODE_OK if fota container firmware version is read properly, or an error code otherwise.
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, FOTA_ReadHeader.
Referenced by Utils_GetXdkVersionString.
Retcode_T FOTA_ReadHeader(Fota_PartitionInfo_T partitionInfo, FWContainer_Header_T *header)
This function reads the Fota container header from the specified partition.
partitionInfo mention the partition information from which header info needs to be read. In-case of FOTA_PARTITION_DOWNLOAD specify the file name Incase of FOTA_PARTITION_PRIMARY file name is not used can be NULL. header Buffer pointer to hold the read Fota container header information. Storage_Setup & Storage_Enable must be called prior to using this API. RETCODE_OK if fota container header is read properly, or an error code otherwise.
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, FOTA_PARTITION_DOWNLOADED, Fota_PartitionInfo_S::Partition, Fota_PartitionInfo_S::PartitionFileName, Storage_Read_S::FileName, Storage_Read_S::ReadBuffer, Storage_Read_S::BytesToRead, Storage_Read_S::ActualBytesRead, Storage_Read_S::Offset, Storage_Read, STORAGE_MEDIUM_SD_CARD, FOTA_PARTITION_PRIMARY, FOTA_PRIMARY_PARTTITION_START_ADDRESS, RETCODE_SEVERITY_ERROR, RETCODE_FOTA_PARTITION_UNKNOWN.
Referenced by FOTA_ReadFirmwareVersion, FOTA_ReadFirmwareCRC, FOTA_ValidateSdcardFw.
Retcode_T FOTA_UpdateSdcardFw(void)
This function Triggers an firmware update from Sdcard.
Firmware has to be validated by calling FOTA_ValidateSdcardFw() before updating.latest validated firmware will be updated. If firmware is valid.Device will be rebooted so no return value, or an error code otherwise.
References RETCODE_OK, FR_OK, FILINFO::lfname, NULL, f_stat, FIRMWARE_NAME, RETCODE, RETCODE_SEVERITY_WARNING, RETCODE_STORAGE_SDCARD_STAT_FAILED, Fota_PartitionInfo_S::Partition, FOTA_PARTITION_DOWNLOADED, Fota_PartitionInfo_S::PartitionFileName, FOTA_ReadFirmwareCRC, NVM_WriteUInt32, NVMUser, NVM_ITEM_ID_NEW_FW_CRC, NVM_WriteUInt8, NVM_ITEM_ID_IS_NEW_FW, NVM_Flush, BSP_Board_SoftReset.
Retcode_T FOTA_ValidateSdcardFw(const char *firmwareName)
This function Validates the firmware in the Sdcard.
firmwareName Name of the firmware which needs to be validated. Storage_Setup & Storage_Enable must be called prior to using this API.If Firmware is valid,this API will rename the firmware to "firmware.bin"In-case if "firmware.bin" is already available then it will be overwritten with the new firmware "firmwareName" . RETCODE_OK if firmware is valid, or an error code otherwise.
References RETCODE_OK, FR_OK, Fota_PartitionInfo_S::Partition, FOTA_PARTITION_DOWNLOADED, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, FOTA_ReadHeader, VerifyHeader, VerifyImage, f_rename, FIRMWARE_NAME, FR_EXIST, f_unlink, RETCODE_SEVERITY_WARNING, RETCODE_FOTA_FILESYSTEM_ERROR.