XDK_Storage.h
Storage_Medium_S
typedef enum Storage_Medium_S Storage_Medium_T
Typedef to represent the Storage medium.
typedef struct Storage_Read_S Storage_Read_T
Typedef to represent the Storage read feature.
typedef struct Storage_Rename_S Storage_Rename_T
Typedef to represent the Storage rename feature.
typedef struct Storage_Setup_S Storage_Setup_T
Typedef to represent the Storage setup feature.
typedef struct Storage_Setup_S Storage_Status_T
Typedef to represent the Storage status feature.
typedef struct Storage_Transfer_S Storage_Transfer_T
Typedef to represent the Storage transfer feature.
typedef struct Storage_Write_S Storage_Write_T
Typedef to represent the Storage write feature.
Retcode_T Storage_Close(void)
This will close the Storage.
RETCODE_OK on success, or an error code otherwise. Storage_Setup must have been successful prior.If Storage_Enable is done prior then it should be disabled by calling Storage_Disable before calling Storage_Close.After calling this API storage module can't be used.
Retcode_T Storage_Delete(Storage_Medium_T medium, const char *fileName)
This will delete the given file in the storage.
medium Storage medium in which the file is to be deleted. fileName Name of the file which has to be deleted. RETCODE_OK on success, or an error code otherwise. Storage_Enable must have been successful prior.
Referenced by AppControllerEnable.
Retcode_T Storage_Disable(Storage_Medium_T medium)
This will disable the Storage medium.
medium Storage medium that has to be disabled. RETCODE_OK on success, or an error code otherwise. Storage_Enable must have been successful prior.
Referenced by AppControllerFire.
Retcode_T Storage_Enable(void)
This will enable the Storage.
RETCODE_OK on success, or an error code otherwise. Storage_Setup must have been successful prior.
Referenced by AppControllerEnable, AppControllerFire.
Retcode_T Storage_IsAvailable(Storage_Medium_T medium, bool *status)
This will validate if the Storage is available or not.
medium Storage medium to be validated for availability status Pointer to the availability of the requested storage medium status In case of failure the status will be falseStorage_Enable must have been successful prior. RETCODE_OK on success, or an error code otherwise.
Referenced by AppControllerFire.
Retcode_T Storage_Read(Storage_Medium_T medium, Storage_Read_T *readCredentials)
This will read the data from the storage.
medium Storage medium in while the file is to be renamed. readCredentials Pointer to the Storage read structure. RETCODE_OK on success, or an error code otherwise. Storage_Enable must have been successful prior.
Referenced by AppControllerFire, AppControllerFatFileSystemWriteRead, VerifyImage, FOTA_ReadHeader.
Retcode_T Storage_Rename(Storage_Medium_T medium, Storage_Rename_T *renameCredentials)
This will rename the file in the storage.
medium Storage medium in while the file is to be renamed. renameCredentials Pointer to the storage rename credentials. RETCODE_OK on success, or an error code otherwise. Storage_Enable must have been successful prior.
Referenced by AppControllerFire.
Retcode_T Storage_Setup(Storage_Setup_T *setup)
This will setup the Storage.
setup Pointer to the Storage setup feature RETCODE_OK on success, or an error code otherwise. This must be the first API to be called if this storage feature is to be used.Do not call this API more than once.
Referenced by AppControllerSetup.
Retcode_T Storage_Transfer(Storage_Medium_T sourceMedium, Storage_Medium_T destinationMedium, Storage_Transfer_T *transferCredentials)
This will transfer the file from source to destination storage medium.
sourceMedium Source Storage medium from which the file is to be transfered. destinationMedium Destination Storage medium to which the file is to be transfered. transferCredentials Pointer to the transfer credentials. RETCODE_OK on success, or an error code otherwise. Storage_Enable must have been successful prior.
Referenced by AppControllerFire.
Retcode_T Storage_Write(Storage_Medium_T medium, Storage_Write_T *writeCredentials)
This will write the data in the storage.
medium Storage medium in while the file is to be renamed. writeCredentials Pointer to the storage write credentials. RETCODE_OK on success, or an error code otherwise. Storage_Enable must have been successful prior.
Referenced by AppControllerFire, AppControllerFatFileSystemWriteRead.