XDK_VirtualSensor.h
VirtualSensor_AccelMode_E
Accel Data in lsb
VirtualSensor_FingerPrintNumber_E
Specifies FingerPrint 1 to be recorded
VirtualSensor_FingerPrintStorageState_E
FingerPrint empty
VirtualSensor_GravityMode_E
Gravity Data in lsb
VirtualSensor_GyroMode_E
Gyro data in lsb
VirtualSensor_MagMode_E
Mag data in lsb
VirtualSensor_RotationMode_E
Rotation Euler Value in Degrees
typedef enum VirtualSensor_AccelMode_E VirtualSensor_AccelMode_T
Typedef to represent the Accelerometer Sensor Mode.
typedef struct VirtualSensor_AxisFloatData_S VirtualSensor_AxisFloatData_T
Typedef to represent the Float value of Various Axis.
typedef struct VirtualSensor_AxisIntData_S VirtualSensor_AxisIntData_T
Typedef to represent the Integer value of Various Axis.
typedef union VirtualSensor_DataType_U VirtualSensor_DataType_T
Typedef to represent the various virtual sensor data.
typedef struct VirtualSensor_Enable_S VirtualSensor_Enable_T
Typedef to represent the Virtual Sensor to be enabled.
typedef struct VirtualSensor_FingerPrintMonitorData_S VirtualSensor_FingerPrintMonitorData_T
typedef enum VirtualSensor_FingerPrintNumber_E VirtualSensor_FingerPrintNumber_T
Typedef to represent the different FingerPrint reference values.
typedef enum VirtualSensor_FingerPrintStorageState_E VirtualSensor_FingerPrintStorageState_T
typedef enum VirtualSensor_GravityMode_E VirtualSensor_GravityMode_T
Typedef to represent the Gravity Sensor Mode.
typedef enum VirtualSensor_GyroMode_E VirtualSensor_GyroMode_T
Typedef to represent the Gyro Sensor Mode.
typedef enum VirtualSensor_MagMode_E VirtualSensor_MagMode_T
Typedef to represent the Magnetometer Sensor Mode.
typedef struct VirtualSensor_RotationEuler_S VirtualSensor_RotationEuler_T
Typedef to represent the Rotation Euler data.
typedef enum VirtualSensor_RotationMode_E VirtualSensor_RotationMode_T
Typedef to represent the Rotation Sensor Mode.
typedef struct VirtualSensor_RotationQuaternion_S VirtualSensor_RotationQuaternion_T
Typedef to represent the Rotation Quaternion data.
typedef struct VirtualSensor_Setup_S VirtualSensor_Setup_T
Typedef to represent the Virtual Sensor setup params.
Retcode_T VirtualSensor_CheckFingerPrintStoredValue(VirtualSensor_FingerPrintNumber_T num, VirtualSensor_FingerPrintStorageState_T *status)
Get current FingerPrint reference values from FingerPrint sensor.
@ param[in] num num for which finger print stored value has to be checked@ param[out] status finger print value for given valueRETCODE_OK on success, or an error code otherwise.
Referenced by ProcessFingerPrint.
Retcode_T VirtualSensor_Close(void)
This will close the Virtual Sensor module.
RETCODE_OK on success, or an error code otherwise.
Retcode_T VirtualSensor_Disable(void)
This will disable the Sensor Virtual module.
RETCODE_OK on success, or an error code otherwise.
Retcode_T VirtualSensor_Enable(void)
This will enable the Sensor Virtual module.
RETCODE_OK on success, or an error code otherwise.
Referenced by AppControllerEnable.
Retcode_T VirtualSensor_GetAbsoluteHumidityData(float *humidity)
Get the absolute humidity value from the humidity sensor.
@ param[out] humidity absolute humidity valueRETCODE_OK on success, or an error code otherwise.
Referenced by PrintHumidity.
Retcode_T VirtualSensor_GetCalibratedAccel(VirtualSensor_DataType_T *data, VirtualSensor_AccelMode_T mode)
Get the xyz values from calibrated acceleration for given accel mode.
@ param[out] data calibrated acceleration value@ param[in] mode calibrated acceleration mode to read dataRETCODE_OK on success, or an error code otherwise.
Referenced by PrintCalibratedAccel.
Retcode_T VirtualSensor_GetCalibratedGyro(VirtualSensor_DataType_T *data, VirtualSensor_GyroMode_T mode)
Get the xyz values from calibrated gyro for given accel mode.
@ param[out] data calibrated gyro value@ param[in] mode calibrated gyro mode to read dataRETCODE_OK on success, or an error code otherwise.
Referenced by PrintCalibratedGyro.
Retcode_T VirtualSensor_GetCalibratedMag(VirtualSensor_DataType_T *data, VirtualSensor_MagMode_T mode)
Get the xyz values from calibrated Magnetometer for given accel mode.
@ param[out] data magnetometer gyro value@ param[in] mode calibrated magnetometer mode to read dataRETCODE_OK on success, or an error code otherwise.
Referenced by PrintCalibratedMag.
Retcode_T VirtualSensor_GetCompassData(float *compass)
Get the Heading angle from the compass sensor.
@ param[out] compass Heading angle dataRETCODE_OK on success, or an error code otherwise.
Referenced by PrintCompass.
Retcode_T VirtualSensor_GetGestureCount(uint32_t *gestureCount)
Get the gestures value (Provides the gestures detected)
@ param[out] gestureCount value of GesturesRETCODE_OK on success, or an error code otherwise.
Referenced by PrintGesture.
Retcode_T VirtualSensor_GetGravity(VirtualSensor_DataType_T *data, VirtualSensor_GravityMode_T mode)
Get the xyz values from Gravity sensor for given mode.
@ param[out] data gravity value@ param[in] mode gravity mode to read dataRETCODE_OK on success, or an error code otherwise.
Referenced by PrintGravity.
Retcode_T VirtualSensor_GetLinearAccel(VirtualSensor_DataType_T *data, VirtualSensor_AccelMode_T mode)
Get the xyz values from linear acceleration for given accel mode.
@ param[out] data linear acceleration value@ param[in] mode linear acceleration mode to read dataRETCODE_OK on success, or an error code otherwise.
Referenced by PrintLinearAccel.
Retcode_T VirtualSensor_GetRotationData(VirtualSensor_DataType_T *data, VirtualSensor_RotationMode_T mode)
Get the rotation value from the rotation sensor.
@ param[out] data rotation sensor data based on given mode@ param[in] mode mode of the rotation sensorRETCODE_OK on success, or an error code otherwise.
Referenced by PrintRotation, SampleAndNotifyHighPriorityData.
Retcode_T VirtualSensor_GetStepCounter(int16_t *stepCounter)
Get the step count value (Provides the number of user steps)
@ param[out] stepCounter value of Step countRETCODE_OK on success, or an error code otherwise.
Referenced by PrintStepCounter.
Retcode_T VirtualSensor_MonitorFingerPrint(VirtualSensor_DataType_T *result)
Monitors whether the measured data matches with stored FingerPrint values from FingerPrint sensor.
@ param[out] result Finger PrintMonitor DataRETCODE_OK on success, or an error code otherwise.
Referenced by ProcessFingerPrint.
Retcode_T VirtualSensor_ResetFingerPrintValue(VirtualSensor_FingerPrintNumber_T num)
Clears the reference value for the selected FingerPrint.
@ param[in] num reference value that is used to clear finger printRETCODE_OK on success, or an error code otherwise.
Referenced by ProcessFingerPrint.
Retcode_T VirtualSensor_SetFingerPrintValue(VirtualSensor_FingerPrintNumber_T num)
Sets the reference value for the selected FingerPrint.
@ param[in] num reference value that is set for the finger print sensorRETCODE_OK on success, or an error code otherwise.
Referenced by ProcessFingerPrint.
Retcode_T VirtualSensor_Setup(VirtualSensor_Setup_T *setup)
This will setup the Virtual Sensor module.
setup Pointer to the Virtual Sensor setup feature RETCODE_OK on success, or an error code otherwise. This must be the first API to be called if this Virtual Sensor feature is to be used.Only one sensor should be enabled. Do not call this API more than once.
Referenced by AppControllerSetup.