bma2x2.c
struct bma2x2_t* p_bma2x2
Copyright (C) 2015 - 2016 Bosch Sensortec GmbHbma2x2.c Date: 2016/03/11 Revision: 2.0.4 $Usage: Sensor Driver for BMA2x2 sensorLicense:Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.Neither the name of the copyright holder nor the names of the contributors may be used to endorse or promote products derived from this software without specific prior written permission.THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGEThe information provided is believed to be accurate and reliable. The copyright holder assumes no responsibility for the consequences of use of such information nor for any infringement of patents or other rights of third parties which may result from its use. No license is granted by implication or otherwise under any patent or patent rights of the copyright holder.file <BMA2x2> brief <Sensor driver="" for="" bma2x2>="">user defined code to be added here ...
u8 V_BMA2x2RESOLUTION_U8
Based on Bit resolution value_u8 should be modified
Referenced by bma2x2_read_accel_x, bma2x2_read_accel_y, bma2x2_read_accel_z, bma2x2_read_accel_xyz, bma2x2_read_accel_xyzt.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_burst_read(u8 addr_u8, u8 *data_u8, u32 len_u32)
This API reads the data from the given register continuously.
addr_u8 -> Address of the register data_u8 -> The data from the register len_u32 -> no of bytes to read results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_bw(u8 *bw_u8)
This API is used to get the bandwidth of the sensor in the register 0x10 bit from 0 to 4.
bw_u8 : The value of bandwidth bw_u8 result 0x08 BMA2x2_BW_7_81HZ 0x09 BMA2x2_BW_15_63HZ 0x0A BMA2x2_BW_31_25HZ 0x0B BMA2x2_BW_62_50HZ 0x0C BMA2x2_BW_125HZ 0x0D BMA2x2_BW_250HZ 0x0E BMA2x2_BW_500HZ 0x0F BMA2x2_BW_1000HZ results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_BW_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
Referenced by Accelerometer_getBandwidth.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_cal_rdy(u8 *cal_rdy_u8)
This API is used to get the status of fast offset compensation(cal_rdy) in the register 0x36 bit 4(Read Only Possible)
cal_rdy_u8 The value of cal_ready results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_FAST_CAL_RDY_STAT_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_durn(u8 channel_u8, u8 *durn_u8)
This API is used to get the duration of Low, High, Slope and slow no motion interrupts in the registers.
LOW_DURN -> register 0x22 bit form 0 to 7 HIGH_DURN -> register 0x25 bit form 0 to 7 SLOPE_DURN -> register 0x27 bit form 0 to 1 SLO_NO_MOT_DURN -> register 0x27 bit form 2 to 7 channel_u8 The value of duration select channel_u8 result 0 BMA2x2_ACCEL_LOW_DURN 1 BMA2x2_ACCEL_HIGH_DURN 2 BMA2x2_ACCEL_SLOPE_DURN 3 BMA2x2_ACCEL_SLOW_NO_MOTION_DURN durn_u8 The value of duration : Duration result BMA2x2_ACCEL_LOW_DURN Low-g interrupt trigger - delay according to([durn_u8 +1]*2)ms - range from 2ms to 512ms. default is 20ms BMA2x2_ACCEL_HIGH_DURN high-g interrupt trigger - delay according to([durn_u8 +1]*2)ms - range from 2ms to 512ms. default is 32ms BMA2x2_ACCEL_SLOPE_DURNslope interrupt trigger - if[durn_u8<1:0>+1] consecutive data points - are above the slope interrupt threshold SLO_NO_MOT_DURN Refer data sheet for clear information results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_LOW_DURN, bma2x2_t::dev_addr, BMA2x2_LOW_DURN_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_HIGH_DURN, BMA2x2_HIGH_DURN_ADDR, BMA2x2_SLOPE_DURN, BMA2x2_SLOPE_DURN_REG, BMA2x2_GET_BITSLICE, BMA2x2_SLOW_NO_MOTION_DURN, BMA2x2_SLOW_NO_MOTION_DURN_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_fifo_data_output_reg(u8 *output_reg_u8)
This API is used to get the fifo data in the register 0x3F bit 0 to 7.
output_reg_u8 : The value of fifo data results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_FIFO_DATA_OUTPUT_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_fifo_data_select(u8 *fifo_data_select_u8)
This API is used to get the axis enable of fifo data select in the register 0x3E bit 0 and 1.
fifo_data_select_u8 : The value of FIFO axis data select fifo_data_select_u8 result 0x00 XYZ 0x01 Y 0x02 X 0x03 Z results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_FIFO_DATA_SELECT_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_fifo_frame_count(u8 *frame_count_u8)
This API read fifo frame count from location 0Eh bit position 0 to 6.
frame_count_u8 : The status of fifo frame count results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_FIFO_FRAME_COUNT_STAT_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_fifo_mode(u8 *fifo_mode_u8)
This API is used to get the status of fifo (fifo_mode) in the register 0x3E bit 6 and 7.
fifo_mode_u8 : The value of fifo mode fifo_mode_u8 result 0x00 BYPASS 0x01 FIFO 0x02 STREAM 0x03 RESERVED results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_FIFO_MODE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_fifo_overrun(u8 *fifo_overrun_u8)
This API read fifo overrun from location 0Eh bit position 7.
fifo_overrun_u8 : The status of fifo overrun results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_FIFO_OVERRUN_STAT_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_fifo_stat(u8 *stat_fifo_u8)
This API reads fifo overrun and fifo frame counter status register byte from location 0Eh.
stat_fifo_u8 : The status of fifo overrun and frame counter results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_STAT_FIFO_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_fifo_wml_trig(u8 *fifo_wml_trig)
This API is used to get the fifo water mark level trigger in the register 0x30 bit from 0 to 5.
fifo_wml_trig The value of fifo watermark trigger level results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_FIFO_WML_TRIG_RETAIN_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_flat_hold_time(u8 *flat_hold_time_u8)
This API is used to get the interrupt enable of flat hold time(flat_hold_time) in the register 0x2F bit 4 and 5.
flat_hold_time_u8 : The value of flat hold time flat_hold_time_u8 result 0x00 0ms 0x01 512ms 0x02 1024ms 0x03 2048ms results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_FLAT_HOLD_TIME_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_flat_hyst(u8 *flat_hyst_u8)
This API is used to get the interrupt enable of flat hysteresis("flat_hy) in the register 0x2F bit 0 to 2.
flat_hyst_u8 : The value of flat hysteresis results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_FLAT_HYST_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_high_bw(u8 *high_bw_u8)
This API is used to get high bandwidth in the register 0x13 bit 7.
high_bw_u8 : The value of high bandwidth high_bw_u8 result 0 Unfiltered High Bandwidth 1 Filtered Low Bandwidth results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ENABLE_DATA_HIGH_BW_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_i2c_wdt(u8 channel_u8, u8 *i2c_wdt_u8)
This API is used to get the i2c watch dog timer period and I2C interface mode is selected in the register 0x34 bit 1 and 2.
channel_u8 The i2c option selection channel_u8 result 0 BMA2x2_ACCEL_I2C_SELECT 1 BMA2x2_ACCEL_I2C_ENABLE i2c_wdt_u8 watch dog timer period and I2C interface mode is selected BMA2x2_ACCEL_I2C_SELECTresult 0x00 Disable the watchdog at SDI pin 0x01 Enable watchdog BMA2x2_I2C_ENABLE result 0x00 1ms 0x01 50ms results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_I2C_SELECT, bma2x2_t::dev_addr, BMA2x2_I2C_WDT_PERIOD_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_I2C_ENABLE, BMA2x2_ENABLE_I2C_WDT_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr1_fifo_full(u8 *intr1_fifo_full_u8)
This API is used to get the fifo full interrupt1 in the register 0x1A bit 2.
intr1_fifo_full_u8 : The value of fifo full interrupt enable intr1_fifo_full_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_FIFO_FULL_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr1_fifo_wm(u8 *intr1_fifo_wm_u8)
This API is used to get the fifo watermark interrupt1 data in the register 0x1A bit 1.
intr1_fifo_wm_u8 : The value of interrupt1 FIFO watermark enable intr1_fifo_wm_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_FIFO_WM_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr2_fifo_full(u8 *intr2_fifo_full_u8)
This API is used to get the fifo full interrupt2 in the register 0x1A bit 5.
intr2_fifo_full_u8 : Thee vale of fifo full enable intr2_fifo_full_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR2_PAD_FIFO_FULL_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr2_fifo_wm(u8 *intr2_fifo_wm_u8)
This API is used to get the fifo watermark interrupt2 data in the register 0x1A bit 6.
intr2_fifo_wm_u8 : The value of interrupt1 FIFO watermark enable intr2_fifo_wm_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR2_PAD_FIFO_WM_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_double_tap(u8 channel_u8, u8 *intr_double_tap_u8)
This API is used to get the interrupt enable of double tap interrupt in the register 0x19 and 0x1B.
INTR1_double -> register 0x19 bit 4 INTR2_double -> register 0x1B bit 4 channel_u8 The value of double tap selection channel_u8 result 0 BMA2x2_ACCEL_INTR1_DOUBLE_TAP 1 BMA2x2_ACCEL_INTR2_DOUBLE_TAP intr_double_tap_u8 The double tap interrupt enable value intr_double_tap_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_DOUBLE_TAP, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_DOUBLE_TAP_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_INTR2_DOUBLE_TAP, BMA2x2_ENABLE_INTR2_PAD_DOUBLE_TAP_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_enable(u8 intr_type_u8, u8 *value_u8)
This API is used to get interrupt enable bits of the sensor in the registers 0x16 and 0x17.
It reads the flat enable, orient enable, single tap enable, double tap enable slope-x enable, slope-y enable, slope-z enable, fifo watermark enable, fifo full enable, data enable, low-g enable, high-z enable, high-y enable high-z enable intr_type_u8 The value of interrupts intr_type_u8 result 0 BMA2x2_LOW_G_INTR 1 BMA2x2_HIGH_G_X_INTR 2 BMA2x2_HIGH_G_Y_INTR 3 BMA2x2_HIGH_G_Z_INTR 4 BMA2x2_DATA_ENABLE 5 SLOPE_X_INTR 6 SLOPE_Y_INTR 7 SLOPE_Z_INTR 8 SINGLE_TAP_INTR 9 SINGLE_TAP_INTR 10 ORIENT_INT 11 FLAT_INT value_u8 : The value of interrupts enable value_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_LOW_G_INTR, bma2x2_t::dev_addr, BMA2x2_ENABLE_LOW_G_INTR_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_HIGH_G_X_INTR, BMA2x2_ENABLE_HIGH_G_X_INTR_REG, BMA2x2_HIGH_G_Y_INTR, BMA2x2_ENABLE_HIGH_G_Y_INTR_REG, BMA2x2_HIGH_G_Z_INTR, BMA2x2_ENABLE_HIGH_G_Z_INTR_REG, BMA2x2_DATA_ENABLE, BMA2x2_ENABLE_NEW_DATA_INTR_REG, BMA2x2_SLOPE_X_INTR, BMA2x2_ENABLE_SLOPE_X_INTR_REG, BMA2x2_SLOPE_Y_INTR, BMA2x2_ENABLE_SLOPE_Y_INTR_REG, BMA2x2_SLOPE_Z_INTR, BMA2x2_ENABLE_SLOPE_Z_INTR_REG, BMA2x2_SINGLE_TAP_INTR, BMA2x2_ENABLE_SINGLE_TAP_INTR_REG, BMA2x2_DOUBLE_TAP_INTR, BMA2x2_ENABLE_DOUBLE_TAP_INTR_REG, BMA2x2_ORIENT_INTR, BMA2x2_ENABLE_ORIENT_INTR_REG, BMA2x2_FLAT_INTR, BMA2x2_ENABLE_FLAT_INTR_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_fifo_full(u8 *fifo_full_u8)
This API is used to get the interrupt fifo full enable interrupt status in the register 0x17 bit 5.
fifo_full_u8 The value of fifo full interrupt enable fifo_full_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_INTR_FIFO_FULL_ENABLE_INTR_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_fifo_wm(u8 *fifo_wm_u8)
This API is used to get the interrupt fifo watermark enable interrupt status in the register 0x17 bit 6.
fifo_wm_u8 : the value FIFO Water Mark fifo_wm_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_INTR_FIFO_WM_ENABLE_INTR_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_flat(u8 channel_u8, u8 *intr_flat_u8)
This API is used to get the interrupt enable of flat interrupt in the register 0x19 and 0x1B.
INTR1_flat -> register 0x19 bit 7 INTR2_flat -> register 0x1B bit 7 channel_u8 The value of flat interrupt select channel_u8 result 0 BMA2x2_ACCEL_INTR1_FLAT 1 BMA2x2_ACCEL_INTR2_FLAT intr_flat_u8 The flat interrupt enable value intr_flat_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_FLAT, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_FLAT_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_INTR2_FLAT, BMA2x2_ENABLE_INTR2_PAD_FLAT_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_high_g(u8 channel_u8, u8 *intr_high_g_u8)
This API is used to get the interrupt enable of high_g interrupt in the register 0x19 and 0x1B.
INTR1_high_g -> register 0x19 bit 1 INTR2_high_g -> register 0x1B bit 1 channel_u8 The value of high_g interrupt selection channel_u8 result 0 BMA2x2_ACCEL_INTR1_HIGH_G 1 BMA2x2_ACCEL_INTR2_HIGH_G intr_high_g_u8 : the value of high_g interrupt intr_high_g_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_HIGH_G, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_HIGH_G_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_INTR2_HIGH_G, BMA2x2_ENABLE_INTR2_PAD_HIGH_G_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_level(u8 channel_u8, u8 *intr_level_u8)
This API is used to get Active Level status in the register 0x20.
INTR1 -> bit 0 INTR2 -> bit 2 channel_u8 The value of Active Level select channel_u8 result 0 BMA2x2_ACCEL_INTR1_LEVEL 1 BMA2x2_ACCEL_INTR2_LEVEL intr_level_u8 The Active Level status enable value intr_level_u8 result 0x01 ACTIVE_HIGH 0x00 ACTIVE_LOW results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_LEVEL, bma2x2_t::dev_addr, BMA2x2_INTR1_PAD_ACTIVE_LEVEL_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_INTR2_LEVEL, BMA2x2_INTR2_PAD_ACTIVE_LEVEL_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_low_g(u8 channel_u8, u8 *intr_low_g_u8)
This API is used to get the interrupt enable of low_g interrupt in the register 0x19 and 0x1B.
INTR1_Low_g -> register 0x19 bit 0 INTR2_Low_g -> register 0x1B bit 0 channel_u8 : The value of low interrupt selection channel channel_u8 result 0 BMA2x2_ACCEL_INTR1_LOW_G 1 BMA2x2_ACCEL_INTR2_LOW_G intr_low_g_u8 : the value of low_g interrupt intr_low_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_LOW_G, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_LOW_G_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_INTR2_LOW_G, BMA2x2_ENABLE_INTR2_PAD_LOW_G_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_orient(u8 channel_u8, u8 *intr_orient_u8)
This API is used to get the interrupt status of orient interrupt in the register 0x19 and 0x1B.
INTR1_orient -> register 0x19 bit 6 INTR2_orient -> register 0x1B bit 6 channel_u8 The value of orient interrupt select channel_u8 result 0 BMA2x2_ACCEL_INTR1_ORIENT 1 BMA2x2_ACCEL_INTR2_ORIENT intr_orient_u8 The value of orient interrupt enable intr_orient_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_ORIENT, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_ORIENT_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_INTR2_ORIENT, BMA2x2_ENABLE_INTR2_PAD_ORIENT_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_orient_stat(u8 *stat_orient_u8)
This API read orient, high-sign and high-first-xyz status register byte from location 0Ch.
stat_orient_u8 : The status of orient and high results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_STAT_ORIENT_HIGH_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_output_type(u8 channel_u8, u8 *intr_output_type_u8)
This API is used to get the interrupt output type in the register 0x20.
INTR1 -> bit 1 INTR2 -> bit 3 channel_u8 The value of output type select channel_u8 result 0 BMA2x2_ACCEL_INTR1_OUTPUT 1 BMA2x2_ACCEL_INTR2_OUTPUT intr_output_type_u8 The value of output type select intr_source_u8 result 0x01 OPEN_DRAIN 0x00 PUSS_PULL results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_OUTPUT, bma2x2_t::dev_addr, BMA2x2_INTR1_PAD_OUTPUT_TYPE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_INTR2_OUTPUT, BMA2x2_INTR2_PAD_OUTPUT_TYPE_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_single_tap(u8 channel_u8, u8 *intr_single_tap_u8)
This API is used to get the interrupt enable of single tap interrupt in the register 0x19 and 0x1B.
INTR1_single_tap -> register 0x19 bit 5 INTR2_single_tap -> register 0x1B bit 5 channel_u8 The value of single tap interrupt select channel_u8 result 0 BMA2x2_ACCEL_INTR1_SINGLE_TAP 1 BMA2x2_ACCEL_INTR2_SINGLE_TAP intr_single_tap_u8 The single tap interrupt enable value intr_single_tap_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_SINGLE_TAP, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_SINGLE_TAP_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_INTR2_SINGLE_TAP, BMA2x2_ENABLE_INTR2_PAD_SINGLE_TAP_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_slope(u8 channel_u8, u8 *intr_slope_u8)
This API is used to get the interrupt enable of slope interrupt in the register 0x19 and 0x1B.
INTR1_slope -> register 0x19 bit 2 INTR2_slope -> register 0x1B bit 2 channel_u8 the value of slope channel select channel_u8 result 0 BMA2x2_ACCEL_INTR1_SLOPE 1 BMA2x2_ACCEL_INTR2_SLOPE intr_slope_u8 : The slope value enable value intr_slope_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_SLOPE, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_SLOPE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_INTR2_SLOPE, BMA2x2_ENABLE_INTR2_PAD_SLOPE_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_slow_no_motion(u8 channel_u8, u8 *intr_slow_no_motion_u8)
This API is used to get the interrupt enable of slow/no motion interrupt in the register 0x19 and 0x1B.
INTR1_slow_no_motion -> register 0x19 bit 3 INTR2_slow_no_motion -> register 0x1B bit 3 channel_u8 : The value of slow/no motion selection channel_u8 result 0 BMA2x2_INTR1_SLOW_NO_MOTION 1 BMA2x2_INTR2_SLOW_NO_MOTION intr_slow_no_motion_u8 the slow_no_motion enable value intr_slow_no_motion_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_SLOW_NO_MOTION, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_SLOW_NO_MOTION_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_INTR2_SLOW_NO_MOTION, BMA2x2_ENABLE_INTR2_PAD_SLOW_NO_MOTION_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_stat(u8 *intr_stat_u8)
This API read interrupt status of flat, orient, single tap, double tap, slow no motion, slope, highg and lowg from location 09h.
intr_stat_u8 : The value of interrupt status results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_STAT1_ADDR, BMA2x2_SHIFT_FOUR_BITS.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_tap_stat(u8 *stat_tap_u8)
This API read tap-sign, tap-first-xyz slope-sign, slope-first-xyz status register byte from location 0Bh.
stat_tap_u8 : The status of tap and slope results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_STAT_TAP_SLOPE_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_latch_intr(u8 *latch_intr_u8)
This API is used to get the latch duration in the register 0x21 bit from 0 to 3.
latch_intr_u8 The value of latch duration latch_intr_u8 result 0x00 BMA2x2_LATCH_DURN_NON_LATCH 0x01 BMA2x2_LATCH_DURN_250MS 0x02 BMA2x2_LATCH_DURN_500MS 0x03 BMA2x2_LATCH_DURN_1S 0x04 BMA2x2_LATCH_DURN_2S 0x05 BMA2x2_LATCH_DURN_4S 0x06 BMA2x2_LATCH_DURN_8S 0x07 BMA2x2_LATCH_DURN_LATCH 0x08 BMA2x2_LATCH_DURN_NON_LATCH1 0x09 BMA2x2_LATCH_DURN_250US 0x0A BMA2x2_LATCH_DURN_500US 0x0B BMA2x2_LATCH_DURN_1MS 0x0C BMA2x2_LATCH_DURN_12_5MS 0x0D BMA2x2_LATCH_DURN_25MS 0x0E BMA2x2_LATCH_DURN_50MS 0x0F BMA2x2_LATCH_DURN_LATCH1 results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_LATCH_INTR_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_low_g_mode(u8 *low_g_mode_u8)
This API is used to get low_g mode in the registers 0x24 bit 2.
low_g_mode_u8 The value of Low_G mode low_g_mode_u8 g-result 0x00 LOW_G_SINGLE_AXIS_MODE 0x01 LOW_G_SUMMING_MODE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_LOW_G_INTR_MODE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_low_high_g_hyst(u8 channel_u8, u8 *hyst_u8)
This API is used to get the low high hysteresis in the registers 0x24.
LOW_G_HYST -> bit form 0 to 1 HIGH_G_HYST -> bit from 6 to 7 channel_u8 The value of hysteresis selection channel_u8 result 0 BMA2x2_ACCEL_LOW_G_HYST 1 BMA2x2_ACCEL_HIGH_G_HYST hyst_u8 The hysteresis data LOW HYSTERESIS Hysteresis of low-g interrupt according to (hyst_u8 * 125)mg HIGH HYSTERESIS High hysteresis depends on the accel range selection g-range High Hysteresis 2g (thres_u8 * 125) mg 4g (thres_u8 * 250) mg 8g (thres_u8 * 500) mg 16g (thres_u8 * 1000) mg results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_LOW_G_HYST, bma2x2_t::dev_addr, BMA2x2_LOW_G_HYST_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_HIGH_G_HYST, BMA2x2_HIGH_G_HYST_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_new_data(u8 channel_u8, u8 *intr_newdata_u8)
This API is used to get the interrupt status of new data in the register 0x19.
INTR1_data -> register 0x19 bit 0 INTR2_data -> register 0x19 bit 7 channel_u8 The value of new data interrupt select channel_u8 result 0 BMA2x2_ACCEL_INTR1_NEWDATA 1 BMA2x2_ACCEL_INTR2_NEWDATA intr_newdata_u8 The new data interrupt enable value intr_newdata_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_NEWDATA, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_NEWDATA_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_INTR2_NEWDATA, BMA2x2_ENABLE_INTR2_PAD_NEWDATA_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_nvmprog_mode(u8 *nvmprog_mode_u8)
This API is used to get the nvm program mode(nvm_prog_mode)in the register 0x33 bit 0.
nvmprog_mode_u8 : The value of nvm program mode nvmprog_mode_u8 result 0x00 Disable program mode 0x01 Enable program mode results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_UNLOCK_EE_PROG_MODE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_nvmprog_ready(u8 *nvprog_ready_u8)
This API is used to get the nvm program ready in the register bit 2.
nvprog_ready_u8 The value of nvm program ready nvprog_ready_u8 result 0x00 nvm write/update operation is in progress 0x01 nvm is ready to accept a new write results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_EE_PROG_READY_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_nvmprog_remain(u8 *nvprog_remain_u8)
This API is used to set the nvm program ready in the register bit 2.
nvprog_remain_u8 The value of nvm program ready nvprog_remain_u8 result 0x00 nvm write/update operation is in progress 0x01 nvm is ready to accept a new write results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_EE_REMAIN_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_offset(u8 channel_u8, s8 *offset_u8)
This API is used to get the status of offset (offset_x, offset_y and offset_z) in the registers 0x38,0x39 and 0x3A.
offset_x -> register 0x38 bit 0 to 7 offset_y -> register 0x39 bit 0 to 7 offset_z -> register 0x3A bit 0 to 7 channel_u8 The value of offset selection channel_u8 result 0 BMA2x2_ACCEL_X_AXIS 1 BMA2x2_ACCEL_Y_AXIS 2 BMA2x2_ACCEL_Z_AXIS offset_u8 The value of offset results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_X_AXIS, bma2x2_t::dev_addr, BMA2x2_OFFSET_X_AXIS_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_Y_AXIS, BMA2x2_OFFSET_Y_AXIS_ADDR, BMA2x2_Z_AXIS, BMA2x2_OFFSET_Z_AXIS_ADDR, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_offset_target(u8 channel_u8, u8 *offset_u8)
This API is used to get the status of offset target axis(offset_target_x, offset_target_y and offset_target_z) and cut_off in the register 0x37.
CUT_OFF -> bit 0 OFFSET_TRIGGER_X -> bit 1 and 2 OFFSET_TRIGGER_Y -> bit 3 and 4 OFFSET_TRIGGER_Z -> bit 5 and 6 channel_u8 The value of offset axis selection channel_u8 result 0 BMA2x2_ACCEL_CUT_OFF 1 BMA2x2_ACCEL_OFFSET_TRIGGER_X 2 BMA2x2_ACCEL_OFFSET_TRIGGER_Y 2 BMA2x2_ACCEL_OFFSET_TRIGGER_Z offset_u8 The offset target value CUT_OFF result 0 1Hz 1 10Hz OFFSET_TRIGGER result 0x00 0g 0x01 +1g 0x02 -1g 0x03 0g results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_CUT_OFF, bma2x2_t::dev_addr, BMA2x2_COMP_CUTOFF_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_OFFSET_TRIGGER_X, BMA2x2_COMP_TARGET_OFFSET_X_REG, BMA2x2_OFFSET_TRIGGER_Y, BMA2x2_COMP_TARGET_OFFSET_Y_REG, BMA2x2_OFFSET_TRIGGER_Z, BMA2x2_COMP_TARGET_OFFSET_Z_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_orient_block(u8 *orient_block_u8)
This API is used to get the orient block in the register 0x2C bit 2 and 3.
orient_block_u8 : The value of orient block orient_mode_u8 result 0x00 no blocking 0x01 theta blocking or | acceleration slope in any axis > 1.5g 0x02 | theta blocking or | acceleration slope in any axis > 0.2g | acceleration in any axis > 1.5g 0x03 | theta blocking or | acceleration slope in any axis > 0.4g | acceleration in any axis > 1.5g | value of orient is not stable for at lease 100ms results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ORIENT_BLOCK_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_orient_enable(u8 *orient_enable_u8)
This API is used to get the interrupt enable of orient ud_enable in the register 0x2D bit 6.
orient_enable_u8 : The value of orient ud_enable orient_enable_u8 result 0x00 Generates Interrupt 0x01 Do not generate interrupt results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ORIENT_UD_ENABLE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_orient_hyst(u8 *orient_hyst_u8)
This API is used to get the orient hysteresis in the register 0x2C bit 4 to 6.
orient_hyst_u8 : The value of orient hysteresis results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ORIENT_HYST_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_orient_mode(u8 *orient_mode_u8)
This API is used to get the orient mode in the register 0x2C bit 0 and 1.
orient_mode_u8 : The value of orient mode orient_mode_u8 result 0x00 symmetrical 0x01 high asymmetrical 0x02 low asymmetrical 0x03 symmetrical results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ORIENT_MODE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_power_mode(u8 *power_mode_u8)
This API is used to get the operating modes of the sensor in the register 0x11 and 0x12.
Register 0x11 - bit from 5 to 7 Register 0x12 - bit from 5 and 6 power_mode_u8 : The value of power mode power_mode_u8 value 0x11 0x12 BMA2x2_MODE_NORMAL 0 0x00 0x00 BMA2x2_MODE_LOWPOWER1 1 0x02 0x00 BMA2x2_MODE_SUSPEND 2 0x06 0x00 BMA2x2_MODE_DEEP_SUSPEND 3 0x01 0x00 BMA2x2_MODE_LOWPOWER2 4 0x02 0x01 BMA2x2_MODE_STANDBY 5 0x04 0x00 results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_MODE_CTRL_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_LOW_NOISE_CTRL_ADDR, BMA2x2_POWER_MODE_HEX_E_ZERO_MASK, BMA2x2_SHIFT_FIVE_BITS, BMA2x2_POWER_MODE_HEX_4_ZERO_MASK, BMA2x2_SHIFT_SIX_BITS, BMA2x2_POWER_MODE_HEX_ZERO_ZERO_MASK, BMA2x2_MODE_NORMAL, BMA2x2_POWER_MODE_HEX_ZERO_TWO_MASK, BMA2x2_MODE_LOWPOWER1, BMA2x2_POWER_MODE_HEX_ZERO_FOUR_MASK, BMA2x2_POWER_MODE_HEX_ZERO_SIX_MASK, BMA2x2_MODE_SUSPEND, BMA2x2_POWER_MODE_HEX_ZERO_ONE_MASK, BMA2x2_MODE_DEEP_SUSPEND, BMA2x2_MODE_LOWPOWER2, BMA2x2_MODE_STANDBY, bma2x2_t::power_mode_u8.
Referenced by Accelerometer_getMode.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_range(u8 *range_u8)
This API is used to get the ranges(g values) of the sensor in the register 0x0F bit from 0 to 3.
range_u8 : The value of range range_u8 result 0x03 BMA2x2_RANGE_2G 0x05 BMA2x2_RANGE_4G 0x08 BMA2x2_RANGE_8G 0x0C BMA2x2_RANGE_16G results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_RANGE_SELECT_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
Referenced by Accelerometer_getRange.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_selftest_axis(u8 *selftest_axis_u8)
This API is for to get the self test axis(self_test_axis) in the register ox32 bit 0 to 2.
selftest_axis_u8 : The value of selftest axis selftest_axis_u8 result 0x00 self test disable 0x01 x-axis 0x02 y-axis 0x03 z-axis results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ENABLE_SELFTEST_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_selftest_sign(u8 *selftest_sign_u8)
This API is for to get the Self Test sign(selftest_sign) in the register 0x32 bit 2.
selftest_sign_u8 : The value of self test sign selftest_sign_u8 result 0x00 negative sign 0x01 positive sign results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_NEG_SELFTEST_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_shadow_dis(u8 *shadow_dis_u8)
This API is used to get shadow dis in the register 0x13 bit 6.
shadow_dis_u8 : The value of shadow dis shadow_dis_u8 result 0 MSB is Locked 1 No MSB Locking results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_DIS_SHADOW_PROC_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_sleep_durn(u8 *sleep_durn_u8)
This API is used to get the sleep duration of the sensor in the register 0x11 Register 0x11 - bit from 0 to 3.
sleep_durn_u8 : The value of sleep duration time sleep_durn_u8 result 0x05 BMA2x2_SLEEP_DURN_0_5MS 0x06 BMA2x2_SLEEP_DURN_1MS 0x07 BMA2x2_SLEEP_DURN_2MS 0x08 BMA2x2_SLEEP_DURN_4MS 0x09 BMA2x2_SLEEP_DURN_6MS 0x0A BMA2x2_SLEEP_DURN_10MS 0x0B BMA2x2_SLEEP_DURN_25MS 0x0C BMA2x2_SLEEP_DURN_50MS 0x0D BMA2x2_SLEEP_DURN_100MS 0x0E BMA2x2_SLEEP_DURN_500MS 0x0F BMA2x2_SLEEP_DURN_1S results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_SLEEP_DURN_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
Referenced by Accelerometer_getSleepDuration.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_sleep_timer_mode(u8 *sleep_timer_u8)
This API is used to get the sleep timer mode in the register 0x12 bit 5.
sleep_timer_u8 : The value of sleep timer mode sleep_timer_u8 result 0 enable EventDrivenSampling(EDT) 1 enable Equidistant sampling mode(EST) results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_SLEEP_TIMER_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_slow_comp(u8 channel_u8, u8 *slow_comp_u8)
This API is used to get slow compensation(hp_x_enable, hp_y_enable and hp_z_enable) enable in the register 0x36 bit 0 to 2.
SLOW_COMP_X -> bit 0 SLOW_COMP_Y -> bit 1 SLOW_COMP_Z -> bit 2 channel_u8 The value of slow compensation selection channel_u8 result 0 BMA2x2_ACCEL_SLOW_COMP_X 1 BMA2x2_ACCEL_SLOW_COMP_Y 2 BMA2x2_ACCEL_SLOW_COMP_Z slow_comp_u8 The value of slow compensation enable slow_comp_u8 result 0x00 Disable 0x01 Enable results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_SLOW_COMP_X, bma2x2_t::dev_addr, BMA2x2_ENABLE_SLOW_COMP_X_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_SLOW_COMP_Y, BMA2x2_ENABLE_SLOW_COMP_Y_REG, BMA2x2_SLOW_COMP_Z, BMA2x2_ENABLE_SLOW_COMP_Z_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_slow_no_motion(u8 channel_u8, u8 *slow_no_motion_u8)
This API is used to get the interrupt status of slow/no motion select and slow no motion enable xyz interrupt in the register 0x18 bit from 0 to 3.
channel_u8 : The value of slow/no motion select channel_u8 result 0 BMA2x2_ACCEL_SLOW_NO_MOTION_ENABLE_X 1 BMA2x2_ACCEL_SLOW_NO_MOTION_ENABLE_Y 2 BMA2x2_ACCEL_SLOW_NO_MOTION_ENABLE_Z 3 BMA2x2_ACCEL_SLOW_NO_MOTION_ENABLE_SEL slow_no_motion_u8 : The value of slow no motion interrupt enable slow_no_motion_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_SLOW_NO_MOTION_ENABLE_X, bma2x2_t::dev_addr, BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_X_INTR_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_SLOW_NO_MOTION_ENABLE_Y, BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_Y_INTR_REG, BMA2x2_SLOW_NO_MOTION_ENABLE_Z, BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_Z_INTR_REG, BMA2x2_SLOW_NO_MOTION_ENABLE_SELECT, BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_SELECT_INTR_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_source(u8 channel_u8, u8 *intr_source_u8)
This API is used to get the source data status of source data, source slow no motion, source slope, source high and source low in the register 0x1E bit from 0 to 5.
channel_u8 : The value of source select channel_u8 result 0 BMA2x2_ACCEL_SOURCE_LOW_G 1 BMA2x2_ACCEL_SOURCE_HIGH_G 2 BMA2x2_ACCEL_SOURCE_SLOPE 3 BMA2x2_ACCEL_SOURCE_SLOW_NO_MOTION 4 BMA2x2_ACCEL_SOURCE_TAP 5 BMA2x2_ACCEL_SOURCE_DATA intr_source_u8 The source status enable value intr_source_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_SOURCE_LOW_G, bma2x2_t::dev_addr, BMA2x2_UNFILT_INTR_SOURCE_LOW_G_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_SOURCE_HIGH_G, BMA2x2_UNFILT_INTR_SOURCE_HIGH_G_REG, BMA2x2_SOURCE_SLOPE, BMA2x2_UNFILT_INTR_SOURCE_SLOPE_REG, BMA2x2_SOURCE_SLOW_NO_MOTION, BMA2x2_UNFILT_INTR_SOURCE_SLOW_NO_MOTION_REG, BMA2x2_SOURCE_TAP, BMA2x2_UNFILT_INTR_SOURCE_TAP_REG, BMA2x2_SOURCE_DATA, BMA2x2_UNFILT_INTR_SOURCE_DATA_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_spi3(u8 *spi3_u8)
This API is used to get the enable status of spi3 in the register 0x34 bit 0.
spi3_u8 : The value of SPI 3 or 4 wire enable spi3_u8 result 0x00 spi4 0x01 spi3 results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ENABLE_SPI_MODE_3_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_tap_durn(u8 *tap_durn_u8)
This API is used to get the tap duration in the register 0x2A bit form 0 to 2.
tap_durn_u8 The value of tap duration tap_durn_u8 result 0x00 TAP_DURN_50_MS 0x01 TAP_DURN_100_MS 0x02 TAP_DURN_150_MS 0x03 TAP_DURN_200_MS 0x04 TAP_DURN_250_MS 0x05 TAP_DURN_375_MS 0x06 TAP_DURN_500_MS 0x07 TAP_DURN_700_MS results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_TAP_DURN_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_tap_quiet(u8 *tap_quiet_u8)
This API is used to get the tap quiet in the register 0x2A bit 7.
tap_quiet_u8 : The value of tap quiet tap_quiet_u8 result 0x00 TAP_QUIET_30_MS 0x01 TAP_QUIET_20_MS results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_TAP_QUIET_DURN_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_tap_sample(u8 *tap_sample_u8)
This API is used to get the tap sample in the register 0x2B bit 6 and 7.
*tap_sample_u8 : The value of tap sample tap_sample_u8 result 0x00 2 samples 0x01 4 samples 0x02 8 samples 0x03 16 samples results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_TAP_SAMPLES_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_tap_shock(u8 *tap_shock_u8)
This API is used to get the tap shock form the register 0x2A bit 6.
tap_shock_u8 The value of tap shock tap_shock_u8 result 0x00 TAP_SHOCK_50_MS 0x01 TAP_SHOCK_75_MS results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_TAP_SHOCK_DURN_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_tap_thres(u8 *tap_thres_u8)
This API is used to get the tap threshold in the register 0x2B bit from 0 to 4.
tap_thres_u8 : The value of tap threshold Tap threshold of single and double tap corresponding to accel range range Tap threshold 2g (tap_thres_u8 * 62.5)mg 4g (tap_thres_u8 * 125)mg 8g (tap_thres_u8 * 250)mg 16g (tap_thres_u8 * 500)mg results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_TAP_THRES_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_theta(u8 channel_u8, u8 *theta_u8)
This API is used to get the theta value of orient and flat interrupts.
ORIENT_THETA -> register 0x2D bit 0 to 5 FLAT_THETA -> register 0x2E bit 0 to 5 channel_u8 The value of theta selection channel_u8 result 0x00 BMA2x2_ACCEL_ORIENT_THETA 0x01 BMA2x2_ACCEL_FLAT_THETA FLAT_THETA : Defines a blocking angle between 0 deg to 44.8 deg ORIENT_THETA : Defines threshold for detection of flat position in range from 0 deg to 44.8 deg theta_u8 The value of theta results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_ORIENT_THETA, bma2x2_t::dev_addr, BMA2x2_THETA_BLOCK_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_FLAT_THETA, BMA2x2_THETA_FLAT_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_thres(u8 channel_u8, u8 *thres_u8)
This API is used to get the threshold of Low, High, Slope and slow no motion interrupts in the registers.
LOW_THRES -> register 0x23 bit form 0 to 7 HIGH_THRES -> register 0x26 bit form 0 to 7 SLOPE_THRES -> register 0x28 bit form 0 to 7 SLO_NO_MOT_THRES -> register 0x29 bit form 0 to 7 channel_u8 The value of threshold selection channel_u8 result 0 BMA2x2_ACCEL_LOW_THRES 1 BMA2x2_ACCEL_HIGH_THRES 2 BMA2x2_ACCEL_SLOPE_THRES 3 BMA2x2_ACCEL_SLOW_NO_MOTION_THRES thres_u8 The threshold value of selected interrupts : LOW-G THRESHOLD Threshold result BMA2x2_ACCEL_LOW_THRES Low-threshold interrupt trigger | according to(thres_u8 * 7.81) mg | range from 0g to 1.992g | default is 375mg : HIGH-G THRESHOLD Threshold of high-g interrupt according to accel g range g-range High-g threshold 2g (thres_u8 * 7.81) mg 4g (thres_u8 * 15.63) mg 8g (thres_u8 * 31.25) mg 16g (thres_u8 * 62.5) mg : SLOPE THRESHOLD Threshold of slope interrupt according to accel g range g-range Slope threshold 2g (thres_u8 * 3.19) mg 4g (thres_u8 * 7.81) mg 8g (thres_u8 * 15.63) mg 16g (thres_u8 * 31.25) mg : SLOW NO MOTION THRESHOLD Threshold of slow no motion interrupt according to accel g range g-range slow no motion threshold 2g (thres_u8 * 3.19) mg 4g (thres_u8 * 7.81) mg 8g (thres_u8 * 15.63) mg 16g (thres_u8 * 31.25) mg results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_LOW_THRES, bma2x2_t::dev_addr, BMA2x2_LOW_THRES_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_HIGH_THRES, BMA2x2_HIGH_THRES_ADDR, BMA2x2_SLOPE_THRES, BMA2x2_SLOPE_THRES_ADDR, BMA2x2_SLOW_NO_MOTION_THRES, BMA2x2_SLOW_NO_MOTION_THRES_ADDR, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_init(struct bma2x2_t *bma2x2)
This function is used for initialize bus read and bus write functions assign the chip id and device address chip id is read in the register 0x00 bit from 0 to 7.
bma2x2 : structure pointer results of bus communication function 0 -> Success -1 -> Error While changing the parameter of the bma2x2_t consider the following point: Changing the reference value of the parameter will changes the local copy or local reference make sure your changes will not affect the reference value of the parameter (Better case don't change the reference value of the parameter)
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, bma2x2_t::dev_addr, BMA2x2_CHIP_ID_REG, BMA2x2_GEN_READ_WRITE_LENGTH, bma2x2_t::chip_id, bma2x2_read_reg, BMA2x2_FIFO_MODE_REG, bma2x2_t::fifo_config.
Referenced by Bma280Utils_initialize.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_read_accel_eight_resolution_x(s8 *accel_x_s8)
This API reads acceleration data X values from location 02h and 03h bit resolution support 8bit.
accel_x_s8 : pointer holding the data of accel X results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_X_AXIS_MSB_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_read_accel_eight_resolution_xyz(struct bma2x2_accel_eight_resolution *accel)
This API reads acceleration of 8 bit resolution data of X,Y,Z values from location 03h , 05h and 07h.
accel : pointer holding the data of accel results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_X_AXIS_MSB_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH, bma2x2_accel_eight_resolution::x, BMA2x2_GET_BITSLICE, BMA2x2_Y_AXIS_MSB_ADDR, bma2x2_accel_eight_resolution::y, BMA2x2_Z_AXIS_MSB_ADDR, bma2x2_accel_eight_resolution::z.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_read_accel_eight_resolution_xyzt(struct bma2x2_accel_eight_resolution_temp *accel)
This API reads accelerometer data X,Y,Z values and temperature data from location 0x02 to 0x08.
accel : The value of accel xyz and temperature data results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_X_AXIS_MSB_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH, bma2x2_accel_eight_resolution_temp::x, BMA2x2_GET_BITSLICE, BMA2x2_Y_AXIS_MSB_ADDR, bma2x2_accel_eight_resolution_temp::y, BMA2x2_Z_AXIS_MSB_ADDR, bma2x2_accel_eight_resolution_temp::z, BMA2x2_TEMP_ADDR, bma2x2_accel_eight_resolution_temp::temp.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_read_accel_eight_resolution_y(s8 *accel_y_s8)
This API reads acceleration data Y values of 8bit resolution from location 05h.
accel_y_s8 The data of y results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_Y_AXIS_MSB_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_read_accel_eight_resolution_z(s8 *accel_z_s8)
This API reads acceleration data Z values of 8bit resolution from location 07h.
@aram accel_z_s8 : the data of zresults of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_Z_AXIS_MSB_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_read_accel_x(s16 *accel_x_s16)
This API reads acceleration data X values from location 02h and 03h.
accel_x_s16 : pointer holding the data of accel X value resolution 0 BMA2x2_12_RESOLUTION 1 BMA2x2_10_RESOLUTION 2 BMA2x2_14_RESOLUTION results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_ACCEL_DATA_SIZE, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, V_BMA2x2RESOLUTION_U8, BMA2x2_12_RESOLUTION, bma2x2_t::dev_addr, BMA2x2_ACCEL_X12_LSB_REG, BMA2x2_LSB_MSB_READ_LENGTH, BMA2x2_SENSOR_DATA_ACCEL_MSB, BMA2x2_SHIFT_EIGHT_BITS, BMA2x2_SENSOR_DATA_ACCEL_LSB, BMA2x2_RESOLUTION_12_MASK, BMA2x2_SHIFT_FOUR_BITS, BMA2x2_10_RESOLUTION, BMA2x2_ACCEL_X10_LSB_REG, BMA2x2_RESOLUTION_10_MASK, BMA2x2_SHIFT_SIX_BITS, BMA2x2_14_RESOLUTION, BMA2x2_ACCEL_X14_LSB_REG, BMA2x2_RESOLUTION_14_MASK, BMA2x2_SHIFT_TWO_BITS.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_read_accel_xyz(struct bma2x2_accel_data *accel)
This API reads acceleration data X,Y,Z values from location 02h to 07h.
accel : pointer holding the data of accel value resolution 0 BMA2x2_12_RESOLUTION 1 BMA2x2_10_RESOLUTION 2 BMA2x2_14_RESOLUTION results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_ACCEL_XYZ_DATA_SIZE, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, V_BMA2x2RESOLUTION_U8, BMA2x2_12_RESOLUTION, bma2x2_t::dev_addr, BMA2x2_ACCEL_X12_LSB_REG, BMA2x2_SHIFT_SIX_BITS, bma2x2_accel_data::x, BMA2x2_SENSOR_DATA_XYZ_X_MSB, BMA2x2_SHIFT_EIGHT_BITS, BMA2x2_SENSOR_DATA_XYZ_X_LSB, BMA2x2_12_BIT_SHIFT, BMA2x2_SHIFT_FOUR_BITS, bma2x2_accel_data::y, BMA2x2_SENSOR_DATA_XYZ_Y_MSB, BMA2x2_SENSOR_DATA_XYZ_Y_LSB, bma2x2_accel_data::z, BMA2x2_SENSOR_DATA_XYZ_Z_MSB, BMA2x2_SENSOR_DATA_XYZ_Z_LSB, BMA2x2_10_RESOLUTION, BMA2x2_ACCEL_X10_LSB_REG, BMA2x2_10_BIT_SHIFT, BMA2x2_14_RESOLUTION, BMA2x2_ACCEL_X14_LSB_REG, BMA2x2_14_BIT_SHIFT, BMA2x2_SHIFT_TWO_BITS.
Referenced by Accelerometer_readXyzLsbValue, Accelerometer_readXyzGValue.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_read_accel_xyzt(struct bma2x2_accel_data_temp *accel)
This API reads accelerometer data X,Y,Z values and temperature data from location 02h to 08h.
accel : The value of accel xyz and temperature data results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_ACCEL_XYZ_TEMP_DATA_SIZE, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, V_BMA2x2RESOLUTION_U8, BMA2x2_12_RESOLUTION, bma2x2_t::dev_addr, BMA2x2_ACCEL_X12_LSB_REG, BMA2x2_ACCEL_BW_MIN_RANGE, bma2x2_accel_data_temp::x, BMA2x2_SENSOR_DATA_XYZ_X_MSB, BMA2x2_SHIFT_EIGHT_BITS, BMA2x2_SENSOR_DATA_XYZ_X_LSB, BMA2x2_12_BIT_SHIFT, BMA2x2_SHIFT_FOUR_BITS, bma2x2_accel_data_temp::y, BMA2x2_SENSOR_DATA_XYZ_Y_MSB, BMA2x2_SENSOR_DATA_XYZ_Y_LSB, bma2x2_accel_data_temp::z, BMA2x2_SENSOR_DATA_XYZ_Z_MSB, BMA2x2_SENSOR_DATA_XYZ_Z_LSB, bma2x2_accel_data_temp::temp, BMA2x2_SENSOR_DATA_TEMP, BMA2x2_10_RESOLUTION, BMA2x2_ACCEL_X10_LSB_REG, BMA2x2_10_BIT_SHIFT, BMA2x2_SHIFT_SIX_BITS, BMA2x2_14_RESOLUTION, BMA2x2_ACCEL_X14_LSB_REG, BMA2x2_14_BIT_SHIFT, BMA2x2_SHIFT_TWO_BITS.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_read_accel_y(s16 *accel_y_s16)
This API reads acceleration data Y values from location 04h and 05h.
accel_y_s16 : pointer holding the data of accel Y value resolution 0 BMA2x2_12_RESOLUTION 1 BMA2x2_10_RESOLUTION 2 BMA2x2_14_RESOLUTION results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_ACCEL_DATA_SIZE, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, V_BMA2x2RESOLUTION_U8, BMA2x2_12_RESOLUTION, bma2x2_t::dev_addr, BMA2x2_ACCEL_Y12_LSB_REG, BMA2x2_LSB_MSB_READ_LENGTH, BMA2x2_SENSOR_DATA_ACCEL_MSB, BMA2x2_SHIFT_EIGHT_BITS, BMA2x2_SENSOR_DATA_ACCEL_LSB, BMA2x2_12_BIT_SHIFT, BMA2x2_SHIFT_FOUR_BITS, BMA2x2_10_RESOLUTION, BMA2x2_ACCEL_Y10_LSB_REG, BMA2x2_10_BIT_SHIFT, BMA2x2_SHIFT_SIX_BITS, BMA2x2_14_RESOLUTION, BMA2x2_ACCEL_Y14_LSB_REG, BMA2x2_14_BIT_SHIFT, BMA2x2_SHIFT_TWO_BITS.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_read_accel_z(s16 *accel_z_s16)
This API reads acceleration data Z values from location 06h and 07h.
accel_z_s16 : pointer holding the data of accel Z value resolution 0 BMA2x2_12_RESOLUTION 1 BMA2x2_10_RESOLUTION 2 BMA2x2_14_RESOLUTION results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_ACCEL_DATA_SIZE, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, V_BMA2x2RESOLUTION_U8, BMA2x2_12_RESOLUTION, bma2x2_t::dev_addr, BMA2x2_ACCEL_Z12_LSB_REG, BMA2x2_LSB_MSB_READ_LENGTH, BMA2x2_SENSOR_DATA_ACCEL_MSB, BMA2x2_SHIFT_EIGHT_BITS, BMA2x2_SENSOR_DATA_ACCEL_LSB, BMA2x2_12_BIT_SHIFT, BMA2x2_SHIFT_FOUR_BITS, BMA2x2_10_RESOLUTION, BMA2x2_ACCEL_Z10_LSB_REG, BMA2x2_10_BIT_SHIFT, BMA2x2_SHIFT_SIX_BITS, BMA2x2_14_RESOLUTION, BMA2x2_ACCEL_Z14_LSB_REG, BMA2x2_14_BIT_SHIFT, BMA2x2_SHIFT_TWO_BITS.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_read_reg(u8 adr_u8, u8 *data_u8, u8 len_u8)
This API reads the data from the given register address.
adr_u8 -> Address of the register data_u8 -> The data from the register len_u8 -> no of bytes to read results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr.
Referenced by bma2x2_init, bma2x2_set_fifo_mode, bma2x2_set_fifo_data_select.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_read_temp(s8 *temp_s8)
This API is used to read the temp from register 0x08.
temp_s8 The value of temperature results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_TEMP_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_rst_intr(u8 rst_intr_u8)
This API is used to set the reset interrupt in the register 0x21 bit 7.
rst_intr_u8 The value of reset interrupt rst_intr_u8 result 0x01 clear any latch interrupt 0x00 keep latch interrupt active results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_RESET_INTR_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_bw(u8 bw_u8)
This API is used to set the bandwidth of the sensor in the register 0x10 bit from 0 to 4.
bw_u8 : The value of bandwidth bw_u8 result 0x08 BMA2x2_BW_7_81HZ 0x09 BMA2x2_BW_15_63HZ 0x0A BMA2x2_BW_31_25HZ 0x0B BMA2x2_BW_62_50HZ 0x0C BMA2x2_BW_125HZ 0x0D BMA2x2_BW_250HZ 0x0E BMA2x2_BW_500HZ 0x0F BMA2x2_BW_1000HZ results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::chip_id, BANDWIDTH_DEFINE, BMA2x2_ACCEL_BW_MIN_RANGE, BMA2x2_ACCEL_BW_1000HZ_RANGE, BMA2x2_BW_7_81HZ, BMA2x2_BW_15_63HZ, BMA2x2_BW_31_25HZ, BMA2x2_BW_62_50HZ, BMA2x2_BW_125HZ, BMA2x2_BW_250HZ, BMA2x2_BW_500HZ, bma2x2_t::dev_addr, BMA2x2_BW_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE, BMA2x2_ACCEL_BW_MAX_RANGE, BMA2x2_BW_1000HZ.
Referenced by Accelerometer_setBandwidth, Bma280Utils_initialize.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_cal_trigger(u8 cal_trigger_u8)
This API is used to set the status of fast offset compensation(cal_rdy) in the register 0x36 bit 4(Read Only Possible)
cal_trigger_u8 The value of cal_ready results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_CAL_TRIGGER_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_durn(u8 channel_u8, u8 durn_u8)
This API is used to set the duration of Low, High, Slope and slow no motion interrupts in the registers.
LOW_DURN -> register 0x22 bit form 0 to 7 HIGH_DURN -> register 0x25 bit form 0 to 7 SLOPE_DURN -> register 0x27 bit form 0 to 1 SLO_NO_MOT_DURN -> register 0x27 bit form 2 to 7 channel_u8 The value of duration select channel_u8 result 0 BMA2x2_ACCEL_LOW_DURN 1 BMA2x2_ACCEL_HIGH_DURN 2 BMA2x2_ACCEL_SLOPE_DURN 3 BMA2x2_ACCEL_SLOW_NO_MOTION_DURN durn_u8 The value of duration : Duration result BMA2x2_ACCEL_LOW_DURN Low-g interrupt trigger - delay according to([durn_u8 +1]*2)ms - range from 2ms to 512ms. default is 20ms BMA2x2_ACCEL_HIGH_DURN high-g interrupt trigger - delay according to([durn_u8 +1]*2)ms - range from 2ms to 512ms. default is 32ms BMA2x2_ACCEL_SLOPE_DURNslope interrupt trigger - if[durn_u8<1:0>+1] consecutive data points - are above the slope interrupt threshold SLO_NO_MOT_DURN Refer data sheet for clear information results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_LOW_DURN, bma2x2_t::dev_addr, BMA2x2_LOW_DURN_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_HIGH_DURN, BMA2x2_HIGH_DURN_ADDR, BMA2x2_SLOPE_DURN, BMA2x2_SLOPE_DURN_REG, BMA2x2_SET_BITSLICE, BMA2x2_SLOW_NO_MOTION_DURN, BMA2x2_SLOW_NO_MOTION_DURN_REG, E_OUT_OF_RANGE.
Referenced by configureSlopeInterrupt.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_fifo_data_select(u8 fifo_data_select_u8)
This API is used to set the axis enable of fifo data select in the register 0x3E bit 0 and 1.
fifo_data_select_u8 : The value of FIFO axis data select fifo_data_select_u8 result 0x00 XYZ 0x01 Y 0x02 X 0x03 Z results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_FIFO_DATA_SELECT_RANGE, bma2x2_t::dev_addr, BMA2x2_FIFO_DATA_SELECT_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, SUCCESS, bma2x2_read_reg, BMA2x2_FIFO_MODE_REG, bma2x2_t::fifo_config, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_fifo_mode(u8 fifo_mode_u8)
This API is used to set the status of fifo (fifo_mode) in the register 0x3E bit 6 and 7.
fifo_mode_u8 : The value of fifo mode fifo_mode_u8 result 0x00 BYPASS 0x01 FIFO 0x02 STREAM 0x03 RESERVED results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_FIFO_MODE_RANGE, bma2x2_t::dev_addr, BMA2x2_FIFO_MODE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, SUCCESS, bma2x2_read_reg, bma2x2_t::fifo_config, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_fifo_wml_trig(u8 fifo_wml_trig)
This API is used to set the fifo water mark level trigger in the register 0x30 bit from 0 to 5.
fifo_wml_trig The value of fifo watermark trigger level results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_FIFO_WML_RANGE, bma2x2_t::dev_addr, BMA2x2_FIFO_WML_TRIG_RETAIN_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_flat_hold_time(u8 flat_hold_time_u8)
This API is used to set the interrupt enable of flat hold time(flat_hold_time) in the register 0x2F bit 4 and 5.
flat_hold_time_u8 : The value of flat hold time flat_hold_time_u8 result 0x00 0ms 0x01 512ms 0x02 1024ms 0x03 2048ms results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_FLAT_HOLD_TIME_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_flat_hyst(u8 flat_hyst_u8)
This API is used to set the interrupt enable of flat hysteresis("flat_hy) in the register 0x2F bit 0 to 2.
flat_hyst_u8 : The value of flat hysteresis results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_FLAT_HYST_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_high_bw(u8 high_bw_u8)
This API is used to write high bandwidth in the register 0x13 bit 7.
high_bw_u8 : The value of high bandwidth high_bw_u8 result 0 Unfiltered High Bandwidth 1 Filtered Low Bandwidth results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ENABLE_DATA_HIGH_BW_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
Referenced by Accelerometer_setBandwidth.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_i2c_wdt(u8 channel_u8, u8 i2c_wdt_u8)
This API is used to set the i2c watch dog timer period and I2C interface mode is selected in the register 0x34 bit 1 and 2.
channel_u8 The i2c option selection channel_u8 result 0 BMA2x2_ACCEL_I2C_SELECT 1 BMA2x2_ACCEL_I2C_ENABLE i2c_wdt_u8 watch dog timer period and I2C interface mode is selected BMA2x2_ACCEL_I2C_SELECTresult 0x00 Disable the watchdog at SDI pin 0x01 Enable watchdog BMA2x2_I2C_ENABLE result 0x00 1ms 0x01 50ms results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_I2C_SELECT, bma2x2_t::dev_addr, BMA2x2_I2C_WDT_PERIOD_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_I2C_ENABLE, BMA2x2_ENABLE_I2C_WDT_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr1_fifo_full(u8 intr1_fifo_full_u8)
This API is used to set the fifo full interrupt1 in the register 0x1A bit 2.
intr1_fifo_full_u8 : The value of fifo full interrupt enable intr1_fifo_full_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_FIFO_MODE_STATUS_RANGE, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_FIFO_FULL_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr1_fifo_wm(u8 intr1_fifo_wm_u8)
This API is used to set the fifo watermark interrupt1 data in the register 0x1A bit 1.
intr1_fifo_wm_u8 : The value of interrupt1 FIFO watermark enable intr1_fifo_wm_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_FIFO_MODE_STATUS_RANGE, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_FIFO_WM_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr2_fifo_full(u8 intr2_fifo_full_u8)
This API is used to set the fifo full interrupt2 in the register 0x1A bit 5.
intr2_fifo_full_u8 : Thee vale of fifo full enable intr2_fifo_full_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_FIFO_MODE_STATUS_RANGE, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR2_PAD_FIFO_FULL_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr2_fifo_wm(u8 intr2_fifo_wm_u8)
This API is used to set the fifo watermark interrupt2 data in the register 0x1A bit 6.
intr2_fifo_wm_u8 : The value of interrupt1 FIFO watermark enable intr2_fifo_wm_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_FIFO_MODE_STATUS_RANGE, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR2_PAD_FIFO_WM_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_double_tap(u8 channel_u8, u8 intr_double_tap_u8)
This API is used to set the interrupt enable of double tap interrupt in the register 0x19 and 0x1B.
INTR1_double -> register 0x19 bit 4 INTR2_double -> register 0x1B bit 4 channel_u8 The value of double tap selection channel_u8 result 0 BMA2x2_ACCEL_INTR1_DOUBLE_TAP 1 BMA2x2_ACCEL_INTR2_DOUBLE_TAP intr_double_tap_u8 The double tap interrupt enable value intr_double_tap_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_DOUBLE_TAP, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_DOUBLE_TAP_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_INTR2_DOUBLE_TAP, BMA2x2_ENABLE_INTR2_PAD_DOUBLE_TAP_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_enable(u8 intr_type_u8, u8 value_u8)
This API is used to set interrupt enable bits of the sensor in the registers 0x16 and 0x17.
It reads the flat enable, orient enable, single tap enable, double tap enable slope-x enable, slope-y enable, slope-z enable, fifo watermark enable, fifo full enable, data enable, low-g enable, high-z enable, high-y enable high-z enable intr_type_u8 The value of interrupts intr_type_u8 result 0 BMA2x2_LOW_G_INTR 1 BMA2x2_HIGH_G_X_INTR 2 BMA2x2_HIGH_G_Y_INTR 3 BMA2x2_HIGH_G_Z_INTR 4 BMA2x2_DATA_ENABLE 5 SLOPE_X_INTR 6 SLOPE_Y_INTR 7 SLOPE_Z_INTR 8 SINGLE_TAP_INTR 9 SINGLE_TAP_INTR 10 ORIENT_INT 11 FLAT_INT value_u8 : The value of interrupts enable value_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_INTR_ENABLE1_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_INTR_ENABLE2_ADDR, BMA2x2_LOW_G_INTR, BMA2x2_SET_BITSLICE, BMA2x2_HIGH_G_X_INTR, BMA2x2_HIGH_G_Y_INTR, BMA2x2_HIGH_G_Z_INTR, BMA2x2_DATA_ENABLE, BMA2x2_SLOPE_X_INTR, BMA2x2_SLOPE_Y_INTR, BMA2x2_SLOPE_Z_INTR, BMA2x2_SINGLE_TAP_INTR, BMA2x2_DOUBLE_TAP_INTR, BMA2x2_ORIENT_INTR, BMA2x2_FLAT_INTR, E_OUT_OF_RANGE.
Referenced by configureNewDataInterrupt, configureSlopeInterrupt.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_fifo_full(u8 fifo_full_u8)
This API is used to set the interrupt fifo full enable interrupt status in the register 0x17 bit 5.
fifo_full_u8 The value of fifo full interrupt enable fifo_full_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_FIFO_MODE_STATUS_RANGE, bma2x2_t::dev_addr, BMA2x2_INTR_FIFO_FULL_ENABLE_INTR_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_fifo_wm(u8 fifo_wm_u8)
This API is used to set the interrupt fifo watermark enable interrupt status in the register 0x17 bit 6.
fifo_wm_u8 : the value FIFO Water Mark fifo_wm_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_FIFO_MODE_STATUS_RANGE, bma2x2_t::dev_addr, BMA2x2_INTR_FIFO_WM_ENABLE_INTR_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_flat(u8 channel_u8, u8 intr_flat_u8)
This API is used to set the interrupt enable of flat interrupt in the register 0x19 and 0x1B.
INTR1_flat -> register 0x19 bit 7 INTR2_flat -> register 0x1B bit 7 channel_u8 The value of flat interrupt select channel_u8 result 0 BMA2x2_ACCEL_INTR1_FLAT 1 BMA2x2_ACCEL_INTR2_FLAT intr_flat_u8 The flat interrupt enable value intr_flat_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_FLAT, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_FLAT_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_INTR2_FLAT, BMA2x2_ENABLE_INTR2_PAD_FLAT_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_high_g(u8 channel_u8, u8 intr_high_g_u8)
This API is used to set the interrupt enable of high_g interrupt in the register 0x19 and 0x1B.
INTR1_high_g -> register 0x19 bit 1 INTR2_high_g -> register 0x1B bit 1 channel_u8 The value of high_g interrupt selection channel_u8 result 0 BMA2x2_ACCEL_INTR1_HIGH_G 1 BMA2x2_ACCEL_INTR2_HIGH_G intr_high_g_u8 : the value of high_g interrupt intr_high_g_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_HIGH_G, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_HIGH_G_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_INTR2_HIGH_G, BMA2x2_ENABLE_INTR2_PAD_HIGH_G_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_level(u8 channel_u8, u8 intr_level_u8)
This API is used to set Active Level status in the register 0x20.
INTR1 -> bit 0 INTR2 -> bit 2 channel_u8 The value of Active Level select channel_u8 result 0 BMA2x2_ACCEL_INTR1_LEVEL 1 BMA2x2_ACCEL_INTR2_LEVEL intr_level_u8 The Active Level status enable value intr_level_u8 result 0x01 ACTIVE_HIGH 0x00 ACTIVE_LOW results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_LEVEL, bma2x2_t::dev_addr, BMA2x2_INTR1_PAD_ACTIVE_LEVEL_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_INTR2_LEVEL, BMA2x2_INTR2_PAD_ACTIVE_LEVEL_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_low_g(u8 channel_u8, u8 intr_low_u8)
This API is used to set the interrupt enable of low_g interrupt in the register 0x19 and 0x1B.
INTR1_Low_g -> register 0x19 bit 0 INTR2_Low_g -> register 0x1B bit 0 channel_u8 : The value of low interrupt selection channel channel_u8 result 0 BMA2x2_ACCEL_INTR1_LOW_G 1 BMA2x2_ACCEL_INTR2_LOW_G intr_low_u8 : the value of low_g interrupt intr_low_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_LOW_G, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_LOW_G_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_INTR2_LOW_G, BMA2x2_ENABLE_INTR2_PAD_LOW_G_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_orient(u8 channel_u8, u8 intr_orient_u8)
This API is used to set the interrupt status of orient interrupt in the register 0x19 and 0x1B.
INTR1_orient -> register 0x19 bit 6 INTR2_orient -> register 0x1B bit 6 channel_u8 The value of orient interrupt select channel_u8 result 0 BMA2x2_ACCEL_INTR1_ORIENT 1 BMA2x2_ACCEL_INTR2_ORIENT intr_orient_u8 The value of orient interrupt enable intr_orient_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_ORIENT, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_ORIENT_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_INTR2_ORIENT, BMA2x2_ENABLE_INTR2_PAD_ORIENT_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_output_type(u8 channel_u8, u8 intr_output_type_u8)
This API is used to set the interrupt output type in the register 0x20.
INTR1 -> bit 1 INTR2 -> bit 3 channel_u8 The value of output type select channel_u8 result 0 BMA2x2_ACCEL_INTR1_OUTPUT 1 BMA2x2_ACCEL_INTR2_OUTPUT intr_output_type_u8 The value of output type select intr_source_u8 result 0x01 OPEN_DRAIN 0x00 PUSS_PULL results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_OUTPUT, bma2x2_t::dev_addr, BMA2x2_INTR1_PAD_OUTPUT_TYPE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_INTR2_OUTPUT, BMA2x2_INTR2_PAD_OUTPUT_TYPE_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_single_tap(u8 channel_u8, u8 intr_single_tap_u8)
This API is used to set the interrupt enable of single tap interrupt in the register 0x19 and 0x1B.
INTR1_single_tap -> register 0x19 bit 5 INTR2_single_tap -> register 0x1B bit 5 channel_u8 The value of single tap interrupt select channel_u8 result 0 BMA2x2_ACCEL_INTR1_SINGLE_TAP 1 BMA2x2_ACCEL_INTR2_SINGLE_TAP intr_single_tap_u8 The single tap interrupt enable value intr_single_tap_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_SINGLE_TAP, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_SINGLE_TAP_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_INTR2_SINGLE_TAP, BMA2x2_ENABLE_INTR2_PAD_SINGLE_TAP_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_slope(u8 channel_u8, u8 intr_slope_u8)
This API is used to set the interrupt enable of slope interrupt in the register 0x19 and 0x1B.
INTR1_slope -> register 0x19 bit 2 INTR2_slope -> register 0x1B bit 2 channel_u8 the value of slope channel select channel_u8 result 0 BMA2x2_ACCEL_INTR1_SLOPE 1 BMA2x2_ACCEL_INTR2_SLOPE intr_slope_u8 : The slope value enable value intr_slope_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_SLOPE, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_SLOPE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_INTR2_SLOPE, BMA2x2_ENABLE_INTR2_PAD_SLOPE_REG, E_OUT_OF_RANGE.
Referenced by configureSlopeInterrupt, Bma280Utils_disableInterrupt.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_slow_no_motion(u8 channel_u8, u8 intr_slow_no_motion_u8)
This API is used to set the interrupt enable of slow/no motion interrupt in the register 0x19 and 0x1B.
INTR1_slow_no_motion -> register 0x19 bit 3 INTR2_slow_no_motion -> register 0x1B bit 3 channel_u8 : The value of slow/no motion selection channel_u8 result 0 BMA2x2_INTR1_SLOW_NO_MOTION 1 BMA2x2_INTR2_SLOW_NO_MOTION intr_slow_no_motion_u8 the slow_no_motion enable value intr_slow_no_motion_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_SLOW_NO_MOTION, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_SLOW_NO_MOTION_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_INTR2_SLOW_NO_MOTION, BMA2x2_ENABLE_INTR2_PAD_SLOW_NO_MOTION_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_latch_intr(u8 latch_intr_u8)
This API is used to set the latch duration in the register 0x21 bit from 0 to 3.
latch_intr_u8 The value of latch duration latch_intr_u8 result 0x00 BMA2x2_LATCH_DURN_NON_LATCH 0x01 BMA2x2_LATCH_DURN_250MS 0x02 BMA2x2_LATCH_DURN_500MS 0x03 BMA2x2_LATCH_DURN_1S 0x04 BMA2x2_LATCH_DURN_2S 0x05 BMA2x2_LATCH_DURN_4S 0x06 BMA2x2_LATCH_DURN_8S 0x07 BMA2x2_LATCH_DURN_LATCH 0x08 BMA2x2_LATCH_DURN_NON_LATCH1 0x09 BMA2x2_LATCH_DURN_250US 0x0A BMA2x2_LATCH_DURN_500US 0x0B BMA2x2_LATCH_DURN_1MS 0x0C BMA2x2_LATCH_DURN_12_5MS 0x0D BMA2x2_LATCH_DURN_25MS 0x0E BMA2x2_LATCH_DURN_50MS 0x0F BMA2x2_LATCH_DURN_LATCH1 results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_ACCEL_BW_MAX_RANGE, BMA2x2_LATCH_DURN_NON_LATCH, BMA2x2_LATCH_DURN_250MS, BMA2x2_LATCH_DURN_500MS, BMA2x2_LATCH_DURN_1S, BMA2x2_LATCH_DURN_2S, BMA2x2_LATCH_DURN_4S, BMA2x2_LATCH_DURN_8S, BMA2x2_LATCH_DURN_LATCH, BMA2x2_LATCH_DURN_NON_LATCH1, BMA2x2_LATCH_DURN_250US, BMA2x2_LATCH_DURN_500US, BMA2x2_LATCH_DURN_1MS, BMA2x2_LATCH_DURN_12_5MS, BMA2x2_LATCH_DURN_25MS, BMA2x2_LATCH_DURN_50MS, BMA2x2_LATCH_DURN_LATCH1, bma2x2_t::dev_addr, BMA2x2_LATCH_INTR_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_low_g_mode(u8 low_g_mode_u8)
This API is used to set low_g mode in the registers 0x24 bit 2.
low_g_mode_u8 The value of Low_G mode low_g_mode_u8 result 0x00 LOW_G_SINGLE_AXIS_MODE 0x01 LOW_G_SUMMING_MODE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_LOW_G_INTR_MODE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_low_high_g_hyst(u8 channel_u8, u8 hyst_u8)
This API is used to set the low high hysteresis in the registers 0x24.
LOW_G_HYST -> bit form 0 to 1 HIGH_G_HYST -> bit from 6 to 7 channel_u8 The value of hysteresis selection channel_u8 result 0 BMA2x2_ACCEL_LOW_G_HYST 1 BMA2x2_ACCEL_HIGH_G_HYST hyst_u8 The hysteresis data LOW HYSTERESIS Hysteresis of low-g interrupt according to (hyst_u8 * 125)mg HIGH HYSTERESIS High hysteresis depends on the accel range selection g-range High Hysteresis 2g (thres_u8 * 125) mg 4g (thres_u8 * 250) mg 8g (thres_u8 * 500) mg 16g (thres_u8 * 1000) mg results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_LOW_G_HYST, bma2x2_t::dev_addr, BMA2x2_LOW_G_HYST_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_HIGH_G_HYST, BMA2x2_HIGH_G_HYST_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_mode_value(u8 power_mode_u8)
This API is used to assign the power mode values modes of the sensor in the register 0x11 and 0x12.
Register 0x11 - bit from 5 to 7 Register 0x12 - bit from 5 and 6 power_mode_u8 : The value of power mode power_mode_u8 value 0x11 0x12 BMA2x2_MODE_NORMAL 0 0x00 0x00 BMA2x2_MODE_LOWPOWER1 1 0x02 0x00 BMA2x2_MODE_SUSPEND 2 0x06 0x00 BMA2x2_MODE_DEEP_SUSPEND 3 0x01 0x00 BMA2x2_MODE_LOWPOWER2 4 0x02 0x01 BMA2x2_MODE_STANDBY 5 0x04 0x00 results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, SUCCESS, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_POWER_MODE_RANGE, BMA2x2_MODE_NORMAL, bma2x2_t::ctrl_mode_reg, BMA2x2_POWER_MODE_HEX_ZERO_ZERO_MASK, bma2x2_t::low_mode_reg, BMA2x2_MODE_LOWPOWER1, BMA2x2_POWER_MODE_HEX_ZERO_TWO_MASK, BMA2x2_MODE_LOWPOWER2, BMA2x2_POWER_MODE_HEX_ZERO_ONE_MASK, BMA2x2_MODE_SUSPEND, BMA2x2_POWER_MODE_HEX_ZERO_FOUR_MASK, BMA2x2_MODE_STANDBY, BMA2x2_MODE_DEEP_SUSPEND, E_OUT_OF_RANGE.
Referenced by bma2x2_set_power_mode.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_new_data(u8 channel_u8, u8 intr_newdata_u8)
This API is used to set the interrupt status of new data in the register 0x19.
INTR1_data -> register 0x19 bit 0 INTR2_data -> register 0x19 bit 7 channel_u8 The value of new data interrupt select channel_u8 result 0 BMA2x2_ACCEL_INTR1_NEWDATA 1 BMA2x2_ACCEL_INTR2_NEWDATA intr_newdata_u8 The new data interrupt enable value intr_newdata_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_NEWDATA, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_NEWDATA_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_INTR2_NEWDATA, BMA2x2_ENABLE_INTR2_PAD_NEWDATA_REG, E_OUT_OF_RANGE.
Referenced by configureNewDataInterrupt.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_nvmprog_mode(u8 nvmprog_mode_u8)
This API is used to set the nvm program mode(nvm_prog_mode)in the register 0x33 bit 0.
nvmprog_mode_u8 : The value of nvm program mode nvmprog_mode_u8 result 0x00 Disable program mode 0x01 Enable program mode results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_UNLOCK_EE_PROG_MODE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_nvprog_trig(u8 nvprog_trig_u8)
This API is used to set the value of nvm program trig in the register 0x33 bit 1.
nvprog_trig_u8 The value of nvm program trig nvprog_trig_u8 result 0x00 Do not trigger nvm program 0x01 Trigger nvm program results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_START_EE_PROG_TRIG_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_offset(u8 channel_u8, s8 offset_u8)
This API is used to set the status of offset (offset_x, offset_y and offset_z) in the registers 0x38,0x39 and 0x3A.
offset_x -> register 0x38 bit 0 to 7 offset_y -> register 0x39 bit 0 to 7 offset_z -> register 0x3A bit 0 to 7 channel_u8 The value of offset selection channel_u8 result 0 BMA2x2_ACCEL_X_AXIS 1 BMA2x2_ACCEL_Y_AXIS 2 BMA2x2_ACCEL_Z_AXIS offset_u8 The value of offset results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_X_AXIS, bma2x2_t::dev_addr, BMA2x2_OFFSET_X_AXIS_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_Y_AXIS, BMA2x2_OFFSET_Y_AXIS_ADDR, BMA2x2_Z_AXIS, BMA2x2_OFFSET_Z_AXIS_ADDR, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_offset_rst(u8 offset_rst_u8)
This API is used to set the offset reset(offset_reset) in the register 0x36 bit 7(Write only possible)
offset_rst_u8 The offset reset value results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_RST_OFFSET_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_offset_target(u8 channel_u8, u8 offset_u8)
This API is used to set the status of offset target axis(offset_target_x, offset_target_y and offset_target_z) and cut_off in the register 0x37.
CUT_OFF -> bit 0 OFFSET_TRIGGER_X -> bit 1 and 2 OFFSET_TRIGGER_Y -> bit 3 and 4 OFFSET_TRIGGER_Z -> bit 5 and 6 channel_u8 The value of offset axis selection channel_u8 result 0 BMA2x2_ACCEL_CUT_OFF 1 BMA2x2_ACCEL_OFFSET_TRIGGER_X 2 BMA2x2_ACCEL_OFFSET_TRIGGER_Y 2 BMA2x2_ACCEL_OFFSET_TRIGGER_Z offset_u8 The offset target value CUT_OFF result 0 1Hz 1 10Hz OFFSET_TRIGGER result 0x00 0g 0x01 +1g 0x02 -1g 0x03 0g results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_CUT_OFF, bma2x2_t::dev_addr, BMA2x2_COMP_CUTOFF_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_OFFSET_TRIGGER_X, BMA2x2_COMP_TARGET_OFFSET_X_REG, BMA2x2_OFFSET_TRIGGER_Y, BMA2x2_COMP_TARGET_OFFSET_Y_REG, BMA2x2_OFFSET_TRIGGER_Z, BMA2x2_COMP_TARGET_OFFSET_Z_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_orient_block(u8 orient_block_u8)
This API is used to set the orient block in the register 0x2C bit 2 and 3.
orient_block_u8 : The value of orient block orient_mode_u8 result 0x00 no blocking 0x01 theta blocking or | acceleration slope in any axis > 1.5g 0x02 | theta blocking or | acceleration slope in any axis > 0.2g | acceleration in any axis > 1.5g 0x03 | theta blocking or | acceleration slope in any axis > 0.4g | acceleration in any axis > 1.5g | value of orient is not stable for at lease 100ms results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ORIENT_BLOCK_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_orient_enable(u8 orient_enable_u8)
This API is used to set the interrupt enable of orient ud_enable in the register 0x2D bit 6.
orient_enable_u8 : The value of orient ud_enable orient_enable_u8 result 0x00 Generates Interrupt 0x01 Do not generate interrupt results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ORIENT_UD_ENABLE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_orient_hyst(u8 orient_hyst_u8)
This API is used to set the orient hysteresis in the register 0x2C bit 4 to 6.
orient_hyst_u8 : The value of orient hysteresis results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ORIENT_HYST_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_orient_mode(u8 orient_mode_u8)
This API is used to set the orient mode in the register 0x2C bit 0 and 1.
orient_mode_u8 : The value of orient mode orient_mode_u8 result 0x00 symmetrical 0x01 high asymmetrical 0x02 low asymmetrical 0x03 symmetrical results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ORIENT_MODE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_power_mode(u8 power_mode_u8)
This API is used to set the operating modes of the sensor in the register 0x11 and 0x12.
Register 0x11 - bit from 5 to 7 Register 0x12 - bit from 5 and 6 power_mode_u8 : The value of power mode power_mode_u8 value 0x11 0x12 BMA2x2_MODE_NORMAL 0 0x00 0x00 BMA2x2_MODE_LOWPOWER1 1 0x02 0x00 BMA2x2_MODE_SUSPEND 2 0x06 0x00 BMA2x2_MODE_DEEP_SUSPEND 3 0x01 0x00 BMA2x2_MODE_LOWPOWER2 4 0x02 0x01 BMA2x2_MODE_STANDBY 5 0x04 0x00 results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_MODE_CTRL_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_LOW_POWER_MODE_REG, bma2x2_set_mode_value, bma2x2_t::ctrl_mode_reg, bma2x2_t::low_mode_reg, BMA2x2_SET_BITSLICE, bma2x2_t::delay_msec, BMA2x2_SHIFT_FOUR_BITS, bma2x2_t::fifo_config, bma2x2_write_reg, BMA2x2_FIFO_MODE_REG.
Referenced by Accelerometer_setMode.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_range(u8 range_u8)
This API is used to set the ranges(g values) of the sensor in the register 0x0F bit from 0 to 3.
range_u8 : The value of range range_u8 result 0x03 BMA2x2_RANGE_2G 0x05 BMA2x2_RANGE_4G 0x08 BMA2x2_RANGE_8G 0x0C BMA2x2_RANGE_16G results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_RANGE_2G, BMA2x2_RANGE_4G, BMA2x2_RANGE_8G, BMA2x2_RANGE_16G, bma2x2_t::dev_addr, BMA2x2_RANGE_SELECT_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
Referenced by Accelerometer_setRange.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_selftest_axis(u8 selftest_axis_u8)
This API is for to set the self test axis(self_test_axis) in the register ox32 bit 0 to 2.
selftest_axis_u8 : The value of selftest axis selftest_axis_u8 result 0x00 self test disable 0x01 x-axis 0x02 y-axis 0x03 z-axis results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_SELF_TEST_AXIS_RANGE, bma2x2_t::dev_addr, BMA2x2_ENABLE_SELFTEST_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_selftest_sign(u8 selftest_sign_u8)
This API is for to set the Self Test sign(selftest_sign) in the register 0x32 bit 2.
selftest_sign_u8 : The value of self test sign selftest_sign_u8 result 0x00 negative sign 0x01 positive sign results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_SELF_TEST_SIGN_RANGE, bma2x2_t::dev_addr, BMA2x2_NEG_SELFTEST_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_shadow_dis(u8 shadow_dis_u8)
This API is used to set shadow dis in the register 0x13 bit 6.
shadow_dis_u8 : The value of shadow dis shadow_dis_u8 result 0 MSB is Locked 1 No MSB Locking results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_DIS_SHADOW_PROC_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_sleep_durn(u8 sleep_durn_u8)
This API is used to set the sleep duration of the sensor in the register 0x11 Register 0x11 - bit from 0 to 3.
sleep_durn_u8 : The value of sleep duration time sleep_durn_u8 result 0x05 BMA2x2_SLEEP_DURN_0_5MS 0x06 BMA2x2_SLEEP_DURN_1MS 0x07 BMA2x2_SLEEP_DURN_2MS 0x08 BMA2x2_SLEEP_DURN_4MS 0x09 BMA2x2_SLEEP_DURN_6MS 0x0A BMA2x2_SLEEP_DURN_10MS 0x0B BMA2x2_SLEEP_DURN_25MS 0x0C BMA2x2_SLEEP_DURN_50MS 0x0D BMA2x2_SLEEP_DURN_100MS 0x0E BMA2x2_SLEEP_DURN_500MS 0x0F BMA2x2_SLEEP_DURN_1S results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_SLEEP_DURN_MIN_RANGE, BMA2x2_SLEEP_DURN_MAX_RANGE, BMA2x2_SLEEP_DURN_0_5MS, BMA2x2_SLEEP_DURN_1MS, BMA2x2_SLEEP_DURN_2MS, BMA2x2_SLEEP_DURN_4MS, BMA2x2_SLEEP_DURN_6MS, BMA2x2_SLEEP_DURN_10MS, BMA2x2_SLEEP_DURN_25MS, BMA2x2_SLEEP_DURN_50MS, BMA2x2_SLEEP_DURN_100MS, BMA2x2_SLEEP_DURN_500MS, BMA2x2_SLEEP_DURN_1S, bma2x2_t::dev_addr, BMA2x2_SLEEP_DURN_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
Referenced by Accelerometer_setSleepDuration.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_sleep_timer_mode(u8 sleep_timer_u8)
This API is used to set the sleep timer mode in the register 0x12 bit 5.
sleep_timer_u8 : The value of sleep timer mode sleep_timer_u8 result 0 enable EventDrivenSampling(EDT) 1 enable Equidistant sampling mode(EST) results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_SLEEP_TIMER_MODE_RANGE, bma2x2_t::dev_addr, BMA2x2_SLEEP_TIMER_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_slow_comp(u8 channel_u8, u8 slow_comp_u8)
This API is used to set slow compensation(hp_x_enable, hp_y_enable and hp_z_enable) enable in the register 0x36 bit 0 to 2.
SLOW_COMP_X -> bit 0 SLOW_COMP_Y -> bit 1 SLOW_COMP_Z -> bit 2 channel_u8 The value of slow compensation selection channel_u8 result 0 BMA2x2_ACCEL_SLOW_COMP_X 1 BMA2x2_ACCEL_SLOW_COMP_Y 2 BMA2x2_ACCEL_SLOW_COMP_Z slow_comp_u8 The value of slow compensation enable slow_comp_u8 result 0x00 Disable 0x01 Enable results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_SLOW_COMP_X, bma2x2_t::dev_addr, BMA2x2_ENABLE_SLOW_COMP_X_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_SLOW_COMP_Y, BMA2x2_ENABLE_SLOW_COMP_Y_REG, BMA2x2_SLOW_COMP_Z, BMA2x2_ENABLE_SLOW_COMP_Z_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_slow_no_motion(u8 channel_u8, u8 slow_no_motion_u8)
This API is used to set the interrupt status of slow/no motion select and slow no motion enable xyz interrupt in the register 0x18 bit from 0 to 3.
channel_u8 : The value of slow/no motion select channel_u8 result 0 BMA2x2_ACCEL_SLOW_NO_MOTION_ENABLE_X 1 BMA2x2_ACCEL_SLOW_NO_MOTION_ENABLE_Y 2 BMA2x2_ACCEL_SLOW_NO_MOTION_ENABLE_Z 3 BMA2x2_ACCEL_SLOW_NO_MOTION_ENABLE_SEL slow_no_motion_u8 : The value of slow no motion interrupt enable slow_no_motion_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_SLOW_NO_MOTION_ENABLE_X, bma2x2_t::dev_addr, BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_X_INTR_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_SLOW_NO_MOTION_ENABLE_Y, BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_Y_INTR_REG, BMA2x2_SLOW_NO_MOTION_ENABLE_Z, BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_Z_INTR_REG, BMA2x2_SLOW_NO_MOTION_ENABLE_SELECT, BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_SELECT_INTR_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_source(u8 channel_u8, u8 intr_source_u8)
This API is used to set the source data status of source data, source slow no motion, source slope, source high and source low in the register 0x1E bit from 0 to 5.
channel_u8 : The value of source select channel_u8 result 0 BMA2x2_ACCEL_SOURCE_LOW_G 1 BMA2x2_ACCEL_SOURCE_HIGH_G 2 BMA2x2_ACCEL_SOURCE_SLOPE 3 BMA2x2_ACCEL_SOURCE_SLOW_NO_MOTION 4 BMA2x2_ACCEL_SOURCE_TAP 5 BMA2x2_ACCEL_SOURCE_DATA intr_source_u8 The source status enable value intr_source_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_SOURCE_LOW_G, bma2x2_t::dev_addr, BMA2x2_UNFILT_INTR_SOURCE_LOW_G_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_SOURCE_HIGH_G, BMA2x2_UNFILT_INTR_SOURCE_HIGH_G_REG, BMA2x2_SOURCE_SLOPE, BMA2x2_UNFILT_INTR_SOURCE_SLOPE_REG, BMA2x2_SOURCE_SLOW_NO_MOTION, BMA2x2_UNFILT_INTR_SOURCE_SLOW_NO_MOTION_REG, BMA2x2_SOURCE_TAP, BMA2x2_UNFILT_INTR_SOURCE_TAP_REG, BMA2x2_SOURCE_DATA, BMA2x2_UNFILT_INTR_SOURCE_DATA_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_spi3(u8 spi3_u8)
This API is used to set the enable status of spi3 in the register 0x34 bit 0.
spi3_u8 : The value of SPI 3 or 4 wire enable spi3_u8 result 0x00 spi4 0x01 spi3 results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ENABLE_SPI_MODE_3_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_tap_durn(u8 tap_durn_u8)
This API is used to set the tap duration in the register 0x2A bit form 0 to 2.
tap_durn_u8 The value of tap duration tap_durn_u8 result 0x00 TAP_DURN_50_MS 0x01 TAP_DURN_100_MS 0x02 TAP_DURN_150_MS 0x03 TAP_DURN_200_MS 0x04 TAP_DURN_250_MS 0x05 TAP_DURN_375_MS 0x06 TAP_DURN_500_MS 0x07 TAP_DURN_700_MS results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_TAP_DURN_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_tap_quiet(u8 tap_quiet_u8)
This API is used to set the tap quiet in the register 0x2A bit 7.
tap_quiet_u8 : The value of tap quiet tap_quiet_u8 result 0x00 TAP_QUIET_30_MS 0x01 TAP_QUIET_20_MS results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_TAP_QUIET_DURN_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_tap_sample(u8 tap_sample_u8)
This API is used to set the tap sample in the register 0x2B bit 6 and 7.
*tap_sample_u8 : The value of tap sample tap_sample_u8 result 0x00 2 samples 0x01 4 samples 0x02 8 samples 0x03 16 samples results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_TAP_SAMPLES_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_tap_shock(u8 tap_shock_u8)
This API is used to set the tap shock form the register 0x2A bit 6.
tap_shock_u8 The value of tap shock tap_shock_u8 result 0x00 TAP_SHOCK_50_MS 0x01 TAP_SHOCK_75_MS results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_TAP_SHOCK_DURN_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_tap_thres(u8 tap_thres_u8)
This API is used to set the tap threshold in the register 0x2B bit from 0 to 4.
tap_thres_u8 : The value of tap threshold Tap threshold of single and double tap corresponding to accel range range Tap threshold 2g (tap_thres_u8 * 62.5)mg 4g (tap_thres_u8 * 125)mg 8g (tap_thres_u8 * 250)mg 16g (tap_thres_u8 * 500)mg results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_TAP_THRES_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_theta(u8 channel_u8, u8 theta_u8)
This API is used to set the theta value of orient and flat interrupts.
ORIENT_THETA -> register 0x2D bit 0 to 5 FLAT_THETA -> register 0x2E bit 0 to 5 channel_u8 The value of theta selection channel_u8 result 0x00 BMA2x2_ACCEL_ORIENT_THETA 0x01 BMA2x2_ACCEL_FLAT_THETA FLAT_THETA : Defines a blocking angle between 0 deg to 44.8 deg ORIENT_THETA : Defines threshold for detection of flat position in range from 0 deg to 44.8 deg theta_u8 The value of theta results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_ORIENT_THETA, bma2x2_t::dev_addr, BMA2x2_THETA_BLOCK_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_FLAT_THETA, BMA2x2_THETA_FLAT_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_thres(u8 channel_u8, u8 thres_u8)
This API is used to set the threshold of Low, High, Slope and slow no motion interrupts in the registers.
LOW_THRES -> register 0x23 bit form 0 to 7 HIGH_THRES -> register 0x26 bit form 0 to 7 SLOPE_THRES -> register 0x28 bit form 0 to 7 SLO_NO_MOT_THRES -> register 0x29 bit form 0 to 7 channel_u8 The value of threshold selection channel_u8 result 0 BMA2x2_ACCEL_LOW_THRES 1 BMA2x2_ACCEL_HIGH_THRES 2 BMA2x2_ACCEL_SLOPE_THRES 3 BMA2x2_ACCEL_SLOW_NO_MOTION_THRES thres_u8 The threshold value of selected interrupts : LOW-G THRESHOLD Threshold result BMA2x2_ACCEL_LOW_THRES Low-threshold interrupt trigger | according to(thres_u8 * 7.81) mg | range from 0g to 1.992g | default is 375mg : HIGH-G THRESHOLD Threshold of high-g interrupt according to accel g range g-range High-g threshold 2g (thres_u8 * 7.81) mg 4g (thres_u8 * 15.63) mg 8g (thres_u8 * 31.25) mg 16g (thres_u8 * 62.5) mg : SLOPE THRESHOLD Threshold of slope interrupt according to accel g range g-range Slope threshold 2g (thres_u8 * 3.19) mg 4g (thres_u8 * 7.81) mg 8g (thres_u8 * 15.63) mg 16g (thres_u8 * 31.25) mg : SLOW NO MOTION THRESHOLD Threshold of slow no motion interrupt according to accel g range g-range slow no motion threshold 2g (thres_u8 * 3.19) mg 4g (thres_u8 * 7.81) mg 8g (thres_u8 * 15.63) mg 16g (thres_u8 * 31.25) mg results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_LOW_THRES, bma2x2_t::dev_addr, BMA2x2_LOW_THRES_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_HIGH_THRES, BMA2x2_HIGH_THRES_ADDR, BMA2x2_SLOPE_THRES, BMA2x2_SLOPE_THRES_ADDR, BMA2x2_SLOW_NO_MOTION_THRES, BMA2x2_SLOW_NO_MOTION_THRES_ADDR, E_OUT_OF_RANGE.
Referenced by configureSlopeInterrupt.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_soft_rst(void)
This function is used for the soft reset The soft reset register will be written with 0xB6 in the register 0x14.
None results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_ENABLE_SOFT_RESET_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_RST_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_update_image(void)
This API is used to update the register values.
None results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_UPDATE_IMAGE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_write_reg(u8 adr_u8, u8 *data_u8, u8 len_u8)
This API gives data to the given register and the data is written in the corresponding register address.
adr_u8 -> Address of the register data_u8 -> The data to the register len_u8 -> no of bytes to read results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr.
Referenced by bma2x2_set_power_mode.