bma2x2.h
MACHINE_32_BIT
The following definition uses for define the data types.
While porting the API please consider the following Please check the version of C standard Are you using Linux platform For the Linux platform support Please use the types.h for your data types definitionsBy default it is defined as 32 bit machine configuration define your data types based on your machine/compiler/controller configuration
typedef signed char s8
If your machine support 16 bit define the MACHINE_16_BIT.
used for signed 8bit
typedef signed short int s16
used for signed 16bit
typedef signed int s32
used for signed 32bit
typedef signed long long int s64
used for signed 64bit
typedef unsigned char u8
used for unsigned 8bit
typedef unsigned short int u16
used for unsigned 16bit
typedef unsigned int u32
used for unsigned 32bit
typedef unsigned long long int u64
used for unsigned 64bit
BMA2x2_WR_FUNC_PTR
Define the calling convention of YOUR bus communication routine.
This includes types of parameters. This example shows the configuration for an SPI bus link. If your communication function looks like this:write_my_bus_xy(u8 device_addr, u8 register_addr, u8 * data, u8 length);The BMA2x2_WR_FUNC_PTR would equal:BMA2x2_WR_FUNC_PTR char (* bus_write)(u8, u8, u8 *, u8)Parameters can be mixed as needed refer to the BMA2x2_BUS_WRITE_FUNC macro.
BMA2x2_BUS_WRITE_FUNC
link macro between API function calls and bus write function
The bus write function can change since this is a system dependant issue. If the bus_write parameter calling order is like: reg_addr, reg_data, wr_len it would be as it is here.If the parameters are differently ordered or your communication function like I2C need to know the device address, you can change this macro accordingly.define BMA2x2_BUS_WRITE_FUNC(dev_addr, reg_addr, reg_data, wr_len)\ bus_write(dev_addr, reg_addr, reg_data, wr_len)This macro lets all API functions call YOUR communication routine in a way that equals your definition in the ref BMA2x2_WR_FUNC_PTR definition.
BMA2x2_SPI_RD_MASK
Define the calling convention of YOUR bus communication routine.
This includes types of parameters. This example shows the configuration for an SPI bus link. If your communication function looks like this:read_my_bus_xy(u8 device_addr, u8 register_addr, u8* data, u8 length);The BMA2x2_RD_FUNC_PTR would equal:BMA2x2_RD_FUNC_PTR s8 (* bus_read)(u8, u8, u8*, u8)Parameters can be mixed as needed refer to the ref BMA2x2_BUS_READ_FUNC macro.
BMA2x2_RD_FUNC_PTR
BMA2x2_BRD_FUNC_PTR
BMA2x2_BUS_READ_FUNC
link macro between API function calls and bus read function
The bus write function can change since this is a system dependant issue. If the bus_read parameter calling order is like: reg_addr, reg_data, wr_len it would be as it is here.If the parameters are differently ordered or your communication function like I2C need to know the device address, you can change this macro accordingly.define BMA2x2_BUS_READ_FUNC(dev_addr, reg_addr, reg_data, wr_len)\ bus_read(dev_addr, reg_addr, reg_data, wr_len)This macro lets all API functions call YOUR communication routine in a way that equals your definition in the ref BMA2x2_WR_FUNC_PTR definition.: this macro also includes the "MSB='1'" for reading BMA2x2 addresses.
BMA2x2_BURST_READ_FUNC
BMA2x2_I2C_ADDR1
< The following definition of I2C address is used for the following sensors BMA255 BMA355 BMA280 BMA282 BMA223 BMA254 BMA284 BMA250E BMA222E
BMA2x2_I2C_ADDR2
The following definition of I2C address is used for the following sensors BMC150 BMC056 BMC156
BMA2x2_I2C_ADDR3
BMA2x2_I2C_ADDR4
BMA2x2_INIT_VALUE
Referenced by bma2x2_init, bma2x2_read_accel_x, bma2x2_read_accel_eight_resolution_x, bma2x2_read_accel_y, bma2x2_read_accel_eight_resolution_y, bma2x2_read_accel_z, bma2x2_read_accel_eight_resolution_z, bma2x2_read_accel_xyz, bma2x2_read_accel_eight_resolution_xyz, bma2x2_get_fifo_frame_count, bma2x2_get_fifo_overrun, bma2x2_get_range, bma2x2_set_range, bma2x2_get_bw, bma2x2_set_bw, bma2x2_get_power_mode, bma2x2_set_power_mode, bma2x2_get_sleep_durn, bma2x2_set_sleep_durn, bma2x2_get_sleep_timer_mode, bma2x2_set_sleep_timer_mode, bma2x2_get_high_bw, bma2x2_set_high_bw, bma2x2_get_shadow_dis, bma2x2_set_shadow_dis, bma2x2_update_image, bma2x2_get_intr_enable, bma2x2_set_intr_enable, bma2x2_get_intr_fifo_full, bma2x2_set_intr_fifo_full, bma2x2_get_intr_fifo_wm, bma2x2_set_intr_fifo_wm, bma2x2_get_slow_no_motion, bma2x2_set_slow_no_motion, bma2x2_get_intr_low_g, bma2x2_set_intr_low_g, bma2x2_get_intr_high_g, bma2x2_set_intr_high_g, bma2x2_get_intr_slope, bma2x2_set_intr_slope, bma2x2_get_intr_slow_no_motion, bma2x2_set_intr_slow_no_motion, bma2x2_get_intr_double_tap, bma2x2_set_intr_double_tap, bma2x2_get_intr_single_tap, bma2x2_set_intr_single_tap, bma2x2_get_intr_orient, bma2x2_set_intr_orient, bma2x2_get_intr_flat, bma2x2_set_intr_flat, bma2x2_get_new_data, bma2x2_set_new_data, bma2x2_get_intr1_fifo_wm, bma2x2_set_intr1_fifo_wm, bma2x2_get_intr2_fifo_wm, bma2x2_set_intr2_fifo_wm, bma2x2_get_intr1_fifo_full, bma2x2_set_intr1_fifo_full, bma2x2_get_intr2_fifo_full, bma2x2_set_intr2_fifo_full, bma2x2_get_source, bma2x2_set_source, bma2x2_get_intr_output_type, bma2x2_set_intr_output_type, bma2x2_get_intr_level, bma2x2_set_intr_level, bma2x2_rst_intr, bma2x2_get_latch_intr, bma2x2_set_latch_intr, bma2x2_get_durn, bma2x2_set_durn, bma2x2_get_thres, bma2x2_set_thres, bma2x2_get_low_high_g_hyst, bma2x2_set_low_high_g_hyst, bma2x2_get_low_g_mode, bma2x2_set_low_g_mode, bma2x2_get_tap_durn, bma2x2_set_tap_durn, bma2x2_get_tap_shock, bma2x2_set_tap_shock, bma2x2_get_tap_quiet, bma2x2_set_tap_quiet, bma2x2_get_tap_thres, bma2x2_set_tap_thres, bma2x2_get_tap_sample, bma2x2_set_tap_sample, bma2x2_get_orient_mode, bma2x2_set_orient_mode, bma2x2_get_orient_block, bma2x2_set_orient_block, bma2x2_get_orient_hyst, bma2x2_set_orient_hyst, bma2x2_get_theta, bma2x2_set_theta, bma2x2_get_orient_enable, bma2x2_set_orient_enable, bma2x2_get_flat_hyst, bma2x2_set_flat_hyst, bma2x2_get_flat_hold_time, bma2x2_set_flat_hold_time, bma2x2_get_fifo_wml_trig, bma2x2_set_fifo_wml_trig, bma2x2_get_selftest_axis, bma2x2_set_selftest_axis, bma2x2_get_selftest_sign, bma2x2_set_selftest_sign, bma2x2_get_nvmprog_mode, bma2x2_set_nvmprog_mode, bma2x2_set_nvprog_trig, bma2x2_get_nvmprog_ready, bma2x2_get_nvmprog_remain, bma2x2_get_spi3, bma2x2_set_spi3, bma2x2_get_i2c_wdt, bma2x2_set_i2c_wdt, bma2x2_get_slow_comp, bma2x2_set_slow_comp, bma2x2_get_cal_rdy, bma2x2_set_cal_trigger, bma2x2_set_offset_rst, bma2x2_get_offset_target, bma2x2_set_offset_target, bma2x2_get_offset, bma2x2_set_offset, bma2x2_get_fifo_mode, bma2x2_set_fifo_mode, bma2x2_get_fifo_data_select, bma2x2_set_fifo_data_select, bma2x2_get_fifo_data_output_reg, bma2x2_read_temp, bma2x2_read_accel_xyzt, bma2x2_read_accel_eight_resolution_xyzt.
BMA2x2_GEN_READ_WRITE_LENGTH
Referenced by bma2x2_init, bma2x2_read_accel_eight_resolution_x, bma2x2_read_accel_eight_resolution_y, bma2x2_read_accel_eight_resolution_z, bma2x2_read_accel_eight_resolution_xyz, bma2x2_get_intr_tap_stat, bma2x2_get_intr_orient_stat, bma2x2_get_fifo_stat, bma2x2_get_fifo_frame_count, bma2x2_get_fifo_overrun, bma2x2_get_range, bma2x2_set_range, bma2x2_get_bw, bma2x2_set_bw, bma2x2_get_power_mode, bma2x2_set_power_mode, bma2x2_get_sleep_durn, bma2x2_set_sleep_durn, bma2x2_get_sleep_timer_mode, bma2x2_set_sleep_timer_mode, bma2x2_get_high_bw, bma2x2_set_high_bw, bma2x2_get_shadow_dis, bma2x2_set_shadow_dis, bma2x2_soft_rst, bma2x2_update_image, bma2x2_get_intr_enable, bma2x2_set_intr_enable, bma2x2_get_intr_fifo_full, bma2x2_set_intr_fifo_full, bma2x2_get_intr_fifo_wm, bma2x2_set_intr_fifo_wm, bma2x2_get_slow_no_motion, bma2x2_set_slow_no_motion, bma2x2_get_intr_low_g, bma2x2_set_intr_low_g, bma2x2_get_intr_high_g, bma2x2_set_intr_high_g, bma2x2_get_intr_slope, bma2x2_set_intr_slope, bma2x2_get_intr_slow_no_motion, bma2x2_set_intr_slow_no_motion, bma2x2_get_intr_double_tap, bma2x2_set_intr_double_tap, bma2x2_get_intr_single_tap, bma2x2_set_intr_single_tap, bma2x2_get_intr_orient, bma2x2_set_intr_orient, bma2x2_get_intr_flat, bma2x2_set_intr_flat, bma2x2_get_new_data, bma2x2_set_new_data, bma2x2_get_intr1_fifo_wm, bma2x2_set_intr1_fifo_wm, bma2x2_get_intr2_fifo_wm, bma2x2_set_intr2_fifo_wm, bma2x2_get_intr1_fifo_full, bma2x2_set_intr1_fifo_full, bma2x2_get_intr2_fifo_full, bma2x2_set_intr2_fifo_full, bma2x2_get_source, bma2x2_set_source, bma2x2_get_intr_output_type, bma2x2_set_intr_output_type, bma2x2_get_intr_level, bma2x2_set_intr_level, bma2x2_rst_intr, bma2x2_get_latch_intr, bma2x2_set_latch_intr, bma2x2_get_durn, bma2x2_set_durn, bma2x2_get_thres, bma2x2_set_thres, bma2x2_get_low_high_g_hyst, bma2x2_set_low_high_g_hyst, bma2x2_get_low_g_mode, bma2x2_set_low_g_mode, bma2x2_get_tap_durn, bma2x2_set_tap_durn, bma2x2_get_tap_shock, bma2x2_set_tap_shock, bma2x2_get_tap_quiet, bma2x2_set_tap_quiet, bma2x2_get_tap_thres, bma2x2_set_tap_thres, bma2x2_get_tap_sample, bma2x2_set_tap_sample, bma2x2_get_orient_mode, bma2x2_set_orient_mode, bma2x2_get_orient_block, bma2x2_set_orient_block, bma2x2_get_orient_hyst, bma2x2_set_orient_hyst, bma2x2_get_theta, bma2x2_set_theta, bma2x2_get_orient_enable, bma2x2_set_orient_enable, bma2x2_get_flat_hyst, bma2x2_set_flat_hyst, bma2x2_get_flat_hold_time, bma2x2_set_flat_hold_time, bma2x2_get_fifo_wml_trig, bma2x2_set_fifo_wml_trig, bma2x2_get_selftest_axis, bma2x2_set_selftest_axis, bma2x2_get_selftest_sign, bma2x2_set_selftest_sign, bma2x2_get_nvmprog_mode, bma2x2_set_nvmprog_mode, bma2x2_set_nvprog_trig, bma2x2_get_nvmprog_ready, bma2x2_get_nvmprog_remain, bma2x2_get_spi3, bma2x2_set_spi3, bma2x2_get_i2c_wdt, bma2x2_set_i2c_wdt, bma2x2_get_slow_comp, bma2x2_set_slow_comp, bma2x2_get_cal_rdy, bma2x2_set_cal_trigger, bma2x2_set_offset_rst, bma2x2_get_offset_target, bma2x2_set_offset_target, bma2x2_get_offset, bma2x2_set_offset, bma2x2_get_fifo_mode, bma2x2_set_fifo_mode, bma2x2_get_fifo_data_select, bma2x2_set_fifo_data_select, bma2x2_get_fifo_data_output_reg, bma2x2_read_temp, bma2x2_read_accel_eight_resolution_xyzt.
BMA2x2_LSB_MSB_READ_LENGTH
Referenced by bma2x2_read_accel_x, bma2x2_read_accel_y, bma2x2_read_accel_z.
BMA2x2_SHIFT_TWO_BITS
BIT SHIFT DEFINITIONS
Referenced by bma2x2_read_accel_x, bma2x2_read_accel_y, bma2x2_read_accel_z, bma2x2_read_accel_xyz, bma2x2_read_accel_xyzt.
BMA2x2_SHIFT_FOUR_BITS
Referenced by bma2x2_read_accel_x, bma2x2_read_accel_y, bma2x2_read_accel_z, bma2x2_read_accel_xyz, bma2x2_get_intr_stat, bma2x2_set_power_mode, bma2x2_read_accel_xyzt.
BMA2x2_SHIFT_FIVE_BITS
Referenced by bma2x2_get_power_mode.
BMA2x2_SHIFT_SIX_BITS
Referenced by bma2x2_read_accel_x, bma2x2_read_accel_y, bma2x2_read_accel_z, bma2x2_read_accel_xyz, bma2x2_get_power_mode, bma2x2_read_accel_xyzt.
BMA2x2_SHIFT_EIGHT_BITS
Referenced by bma2x2_read_accel_x, bma2x2_read_accel_y, bma2x2_read_accel_z, bma2x2_read_accel_xyz, bma2x2_read_accel_xyzt.
BMA2x2_FIFO_MODE_STATUS_RANGE
FIFO DEFINITIONS
Referenced by bma2x2_set_intr_fifo_full, bma2x2_set_intr_fifo_wm, bma2x2_set_intr1_fifo_wm, bma2x2_set_intr2_fifo_wm, bma2x2_set_intr1_fifo_full, bma2x2_set_intr2_fifo_full.
BMA2x2_FIFO_DATA_SELECT_RANGE
Referenced by bma2x2_set_fifo_data_select.
BMA2x2_FIFO_MODE_RANGE
Referenced by bma2x2_set_fifo_mode.
BMA2x2_FIFO_WML_RANGE
Referenced by bma2x2_set_fifo_wml_trig.
BMA2x2_ACCEL_BW_MIN_RANGE
MODE RANGES
Referenced by bma2x2_set_bw, bma2x2_read_accel_xyzt.
BMA2x2_ACCEL_BW_1000HZ_RANGE
Referenced by bma2x2_set_bw.
BMA2x2_ACCEL_BW_MAX_RANGE
Referenced by bma2x2_set_bw, bma2x2_set_latch_intr.
BMA2x2_SLEEP_DURN_MIN_RANGE
Referenced by bma2x2_set_sleep_durn.
BMA2x2_SLEEP_TIMER_MODE_RANGE
Referenced by bma2x2_set_sleep_timer_mode.
BMA2x2_SLEEP_DURN_MAX_RANGE
Referenced by bma2x2_set_sleep_durn.
BMA2x2_POWER_MODE_RANGE
Referenced by bma2x2_set_mode_value.
BMA2x2_SELF_TEST_AXIS_RANGE
Referenced by bma2x2_set_selftest_axis.
BMA2x2_SELF_TEST_SIGN_RANGE
Referenced by bma2x2_set_selftest_sign.
E_OUT_OF_RANGE
Referenced by bma2x2_set_range, bma2x2_set_bw, bma2x2_set_mode_value, bma2x2_set_sleep_durn, bma2x2_set_sleep_timer_mode, bma2x2_get_intr_enable, bma2x2_set_intr_enable, bma2x2_set_intr_fifo_full, bma2x2_set_intr_fifo_wm, bma2x2_get_slow_no_motion, bma2x2_set_slow_no_motion, bma2x2_get_intr_low_g, bma2x2_set_intr_low_g, bma2x2_get_intr_high_g, bma2x2_set_intr_high_g, bma2x2_get_intr_slope, bma2x2_set_intr_slope, bma2x2_get_intr_slow_no_motion, bma2x2_set_intr_slow_no_motion, bma2x2_get_intr_double_tap, bma2x2_set_intr_double_tap, bma2x2_get_intr_single_tap, bma2x2_set_intr_single_tap, bma2x2_get_intr_orient, bma2x2_set_intr_orient, bma2x2_get_intr_flat, bma2x2_set_intr_flat, bma2x2_get_new_data, bma2x2_set_new_data, bma2x2_set_intr1_fifo_wm, bma2x2_set_intr2_fifo_wm, bma2x2_set_intr1_fifo_full, bma2x2_set_intr2_fifo_full, bma2x2_get_source, bma2x2_set_source, bma2x2_get_intr_output_type, bma2x2_set_intr_output_type, bma2x2_get_intr_level, bma2x2_set_intr_level, bma2x2_set_latch_intr, bma2x2_get_durn, bma2x2_set_durn, bma2x2_get_thres, bma2x2_set_thres, bma2x2_get_low_high_g_hyst, bma2x2_set_low_high_g_hyst, bma2x2_get_theta, bma2x2_set_theta, bma2x2_set_fifo_wml_trig, bma2x2_set_selftest_axis, bma2x2_set_selftest_sign, bma2x2_get_i2c_wdt, bma2x2_set_i2c_wdt, bma2x2_get_slow_comp, bma2x2_set_slow_comp, bma2x2_get_offset_target, bma2x2_set_offset_target, bma2x2_get_offset, bma2x2_set_offset, bma2x2_set_fifo_mode, bma2x2_set_fifo_data_select, Accelerometer_setBandwidth, Accelerometer_getBandwidth, Accelerometer_setRange, Accelerometer_getRange, Accelerometer_setSleepDuration, Accelerometer_getSleepDuration, Accelerometer_setMode, Accelerometer_getMode, Accelerometer_readXyzLsbValue, Accelerometer_readXyzGValue, configureNewDataInterrupt, configureSlopeInterrupt, Bma280Utils_initialize, Bma280Utils_disableInterrupt.
E_BMA2x2_NULL_PTR
Referenced by bma2x2_burst_read, bma2x2_write_reg, bma2x2_read_reg, bma2x2_read_accel_x, bma2x2_read_accel_eight_resolution_x, bma2x2_read_accel_y, bma2x2_read_accel_eight_resolution_y, bma2x2_read_accel_z, bma2x2_read_accel_eight_resolution_z, bma2x2_read_accel_xyz, bma2x2_read_accel_eight_resolution_xyz, bma2x2_get_intr_tap_stat, bma2x2_get_intr_orient_stat, bma2x2_get_fifo_stat, bma2x2_get_fifo_frame_count, bma2x2_get_fifo_overrun, bma2x2_get_intr_stat, bma2x2_get_range, bma2x2_set_range, bma2x2_get_bw, bma2x2_set_bw, bma2x2_get_power_mode, bma2x2_set_power_mode, bma2x2_set_mode_value, bma2x2_get_sleep_durn, bma2x2_set_sleep_durn, bma2x2_get_sleep_timer_mode, bma2x2_set_sleep_timer_mode, bma2x2_get_high_bw, bma2x2_set_high_bw, bma2x2_get_shadow_dis, bma2x2_set_shadow_dis, bma2x2_soft_rst, bma2x2_update_image, bma2x2_get_intr_enable, bma2x2_set_intr_enable, bma2x2_get_intr_fifo_full, bma2x2_set_intr_fifo_full, bma2x2_get_intr_fifo_wm, bma2x2_set_intr_fifo_wm, bma2x2_get_slow_no_motion, bma2x2_set_slow_no_motion, bma2x2_get_intr_low_g, bma2x2_set_intr_low_g, bma2x2_get_intr_high_g, bma2x2_set_intr_high_g, bma2x2_get_intr_slope, bma2x2_set_intr_slope, bma2x2_get_intr_slow_no_motion, bma2x2_set_intr_slow_no_motion, bma2x2_get_intr_double_tap, bma2x2_set_intr_double_tap, bma2x2_get_intr_single_tap, bma2x2_set_intr_single_tap, bma2x2_get_intr_orient, bma2x2_set_intr_orient, bma2x2_get_intr_flat, bma2x2_set_intr_flat, bma2x2_get_new_data, bma2x2_set_new_data, bma2x2_get_intr1_fifo_wm, bma2x2_set_intr1_fifo_wm, bma2x2_get_intr2_fifo_wm, bma2x2_set_intr2_fifo_wm, bma2x2_get_intr1_fifo_full, bma2x2_set_intr1_fifo_full, bma2x2_get_intr2_fifo_full, bma2x2_set_intr2_fifo_full, bma2x2_get_source, bma2x2_set_source, bma2x2_get_intr_output_type, bma2x2_set_intr_output_type, bma2x2_get_intr_level, bma2x2_set_intr_level, bma2x2_rst_intr, bma2x2_get_latch_intr, bma2x2_set_latch_intr, bma2x2_get_durn, bma2x2_set_durn, bma2x2_get_thres, bma2x2_set_thres, bma2x2_get_low_high_g_hyst, bma2x2_set_low_high_g_hyst, bma2x2_get_low_g_mode, bma2x2_set_low_g_mode, bma2x2_get_tap_durn, bma2x2_set_tap_durn, bma2x2_get_tap_shock, bma2x2_set_tap_shock, bma2x2_get_tap_quiet, bma2x2_set_tap_quiet, bma2x2_get_tap_thres, bma2x2_set_tap_thres, bma2x2_get_tap_sample, bma2x2_set_tap_sample, bma2x2_get_orient_mode, bma2x2_set_orient_mode, bma2x2_get_orient_block, bma2x2_set_orient_block, bma2x2_get_orient_hyst, bma2x2_set_orient_hyst, bma2x2_get_theta, bma2x2_set_theta, bma2x2_get_orient_enable, bma2x2_set_orient_enable, bma2x2_get_flat_hyst, bma2x2_set_flat_hyst, bma2x2_get_flat_hold_time, bma2x2_set_flat_hold_time, bma2x2_get_fifo_wml_trig, bma2x2_set_fifo_wml_trig, bma2x2_get_selftest_axis, bma2x2_set_selftest_axis, bma2x2_get_selftest_sign, bma2x2_set_selftest_sign, bma2x2_get_nvmprog_mode, bma2x2_set_nvmprog_mode, bma2x2_set_nvprog_trig, bma2x2_get_nvmprog_ready, bma2x2_get_nvmprog_remain, bma2x2_get_spi3, bma2x2_set_spi3, bma2x2_get_i2c_wdt, bma2x2_set_i2c_wdt, bma2x2_get_slow_comp, bma2x2_set_slow_comp, bma2x2_get_cal_rdy, bma2x2_set_cal_trigger, bma2x2_set_offset_rst, bma2x2_get_offset_target, bma2x2_set_offset_target, bma2x2_get_offset, bma2x2_set_offset, bma2x2_get_fifo_mode, bma2x2_set_fifo_mode, bma2x2_get_fifo_data_select, bma2x2_set_fifo_data_select, bma2x2_get_fifo_data_output_reg, bma2x2_read_temp, bma2x2_read_accel_xyzt, bma2x2_read_accel_eight_resolution_xyzt, bma2x2LibErrorMapping, libErrorMapping.
BMA2x2_NULL
Referenced by bma2x2_burst_read, bma2x2_write_reg, bma2x2_read_reg, bma2x2_read_accel_x, bma2x2_read_accel_eight_resolution_x, bma2x2_read_accel_y, bma2x2_read_accel_eight_resolution_y, bma2x2_read_accel_z, bma2x2_read_accel_eight_resolution_z, bma2x2_read_accel_xyz, bma2x2_read_accel_eight_resolution_xyz, bma2x2_get_intr_tap_stat, bma2x2_get_intr_orient_stat, bma2x2_get_fifo_stat, bma2x2_get_fifo_frame_count, bma2x2_get_fifo_overrun, bma2x2_get_intr_stat, bma2x2_get_range, bma2x2_set_range, bma2x2_get_bw, bma2x2_set_bw, bma2x2_get_power_mode, bma2x2_set_power_mode, bma2x2_set_mode_value, bma2x2_get_sleep_durn, bma2x2_set_sleep_durn, bma2x2_get_sleep_timer_mode, bma2x2_set_sleep_timer_mode, bma2x2_get_high_bw, bma2x2_set_high_bw, bma2x2_get_shadow_dis, bma2x2_set_shadow_dis, bma2x2_soft_rst, bma2x2_update_image, bma2x2_get_intr_enable, bma2x2_set_intr_enable, bma2x2_get_intr_fifo_full, bma2x2_set_intr_fifo_full, bma2x2_get_intr_fifo_wm, bma2x2_set_intr_fifo_wm, bma2x2_get_slow_no_motion, bma2x2_set_slow_no_motion, bma2x2_get_intr_low_g, bma2x2_set_intr_low_g, bma2x2_get_intr_high_g, bma2x2_set_intr_high_g, bma2x2_get_intr_slope, bma2x2_set_intr_slope, bma2x2_get_intr_slow_no_motion, bma2x2_set_intr_slow_no_motion, bma2x2_get_intr_double_tap, bma2x2_set_intr_double_tap, bma2x2_get_intr_single_tap, bma2x2_set_intr_single_tap, bma2x2_get_intr_orient, bma2x2_set_intr_orient, bma2x2_get_intr_flat, bma2x2_set_intr_flat, bma2x2_get_new_data, bma2x2_set_new_data, bma2x2_get_intr1_fifo_wm, bma2x2_set_intr1_fifo_wm, bma2x2_get_intr2_fifo_wm, bma2x2_set_intr2_fifo_wm, bma2x2_get_intr1_fifo_full, bma2x2_set_intr1_fifo_full, bma2x2_get_intr2_fifo_full, bma2x2_set_intr2_fifo_full, bma2x2_get_source, bma2x2_set_source, bma2x2_get_intr_output_type, bma2x2_set_intr_output_type, bma2x2_get_intr_level, bma2x2_set_intr_level, bma2x2_rst_intr, bma2x2_get_latch_intr, bma2x2_set_latch_intr, bma2x2_get_durn, bma2x2_set_durn, bma2x2_get_thres, bma2x2_set_thres, bma2x2_get_low_high_g_hyst, bma2x2_set_low_high_g_hyst, bma2x2_get_low_g_mode, bma2x2_set_low_g_mode, bma2x2_get_tap_durn, bma2x2_set_tap_durn, bma2x2_get_tap_shock, bma2x2_set_tap_shock, bma2x2_get_tap_quiet, bma2x2_set_tap_quiet, bma2x2_get_tap_thres, bma2x2_set_tap_thres, bma2x2_get_tap_sample, bma2x2_set_tap_sample, bma2x2_get_orient_mode, bma2x2_set_orient_mode, bma2x2_get_orient_block, bma2x2_set_orient_block, bma2x2_get_orient_hyst, bma2x2_set_orient_hyst, bma2x2_get_theta, bma2x2_set_theta, bma2x2_get_orient_enable, bma2x2_set_orient_enable, bma2x2_get_flat_hyst, bma2x2_set_flat_hyst, bma2x2_get_flat_hold_time, bma2x2_set_flat_hold_time, bma2x2_get_fifo_wml_trig, bma2x2_set_fifo_wml_trig, bma2x2_get_selftest_axis, bma2x2_set_selftest_axis, bma2x2_get_selftest_sign, bma2x2_set_selftest_sign, bma2x2_get_nvmprog_mode, bma2x2_set_nvmprog_mode, bma2x2_set_nvprog_trig, bma2x2_get_nvmprog_ready, bma2x2_get_nvmprog_remain, bma2x2_get_spi3, bma2x2_set_spi3, bma2x2_get_i2c_wdt, bma2x2_set_i2c_wdt, bma2x2_get_slow_comp, bma2x2_set_slow_comp, bma2x2_get_cal_rdy, bma2x2_set_cal_trigger, bma2x2_set_offset_rst, bma2x2_get_offset_target, bma2x2_set_offset_target, bma2x2_get_offset, bma2x2_set_offset, bma2x2_get_fifo_mode, bma2x2_set_fifo_mode, bma2x2_get_fifo_data_select, bma2x2_set_fifo_data_select, bma2x2_get_fifo_data_output_reg, bma2x2_read_temp, bma2x2_read_accel_xyzt, bma2x2_read_accel_eight_resolution_xyzt.
ERROR
Referenced by bma2x2_burst_read, bma2x2_init, bma2x2_write_reg, bma2x2_read_reg, bma2x2_read_accel_x, bma2x2_read_accel_eight_resolution_x, bma2x2_read_accel_y, bma2x2_read_accel_eight_resolution_y, bma2x2_read_accel_z, bma2x2_read_accel_eight_resolution_z, bma2x2_read_accel_xyz, bma2x2_read_accel_eight_resolution_xyz, bma2x2_get_intr_tap_stat, bma2x2_get_intr_orient_stat, bma2x2_get_fifo_stat, bma2x2_get_fifo_frame_count, bma2x2_get_fifo_overrun, bma2x2_get_intr_stat, bma2x2_get_range, bma2x2_set_range, bma2x2_get_bw, bma2x2_set_bw, bma2x2_get_power_mode, bma2x2_set_power_mode, bma2x2_get_sleep_durn, bma2x2_set_sleep_durn, bma2x2_get_sleep_timer_mode, bma2x2_set_sleep_timer_mode, bma2x2_get_high_bw, bma2x2_set_high_bw, bma2x2_get_shadow_dis, bma2x2_set_shadow_dis, bma2x2_soft_rst, bma2x2_update_image, bma2x2_get_intr_enable, bma2x2_set_intr_enable, bma2x2_get_intr_fifo_full, bma2x2_set_intr_fifo_full, bma2x2_get_intr_fifo_wm, bma2x2_set_intr_fifo_wm, bma2x2_get_slow_no_motion, bma2x2_set_slow_no_motion, bma2x2_get_intr_low_g, bma2x2_set_intr_low_g, bma2x2_get_intr_high_g, bma2x2_set_intr_high_g, bma2x2_get_intr_slope, bma2x2_set_intr_slope, bma2x2_get_intr_slow_no_motion, bma2x2_set_intr_slow_no_motion, bma2x2_get_intr_double_tap, bma2x2_set_intr_double_tap, bma2x2_get_intr_single_tap, bma2x2_set_intr_single_tap, bma2x2_get_intr_orient, bma2x2_set_intr_orient, bma2x2_get_intr_flat, bma2x2_set_intr_flat, bma2x2_get_new_data, bma2x2_set_new_data, bma2x2_get_intr1_fifo_wm, bma2x2_set_intr1_fifo_wm, bma2x2_get_intr2_fifo_wm, bma2x2_set_intr2_fifo_wm, bma2x2_get_intr1_fifo_full, bma2x2_set_intr1_fifo_full, bma2x2_get_intr2_fifo_full, bma2x2_set_intr2_fifo_full, bma2x2_get_source, bma2x2_set_source, bma2x2_get_intr_output_type, bma2x2_set_intr_output_type, bma2x2_get_intr_level, bma2x2_set_intr_level, bma2x2_rst_intr, bma2x2_get_latch_intr, bma2x2_set_latch_intr, bma2x2_get_durn, bma2x2_set_durn, bma2x2_get_thres, bma2x2_set_thres, bma2x2_get_low_high_g_hyst, bma2x2_set_low_high_g_hyst, bma2x2_get_low_g_mode, bma2x2_set_low_g_mode, bma2x2_get_tap_durn, bma2x2_set_tap_durn, bma2x2_get_tap_shock, bma2x2_set_tap_shock, bma2x2_get_tap_quiet, bma2x2_set_tap_quiet, bma2x2_get_tap_thres, bma2x2_set_tap_thres, bma2x2_get_tap_sample, bma2x2_set_tap_sample, bma2x2_get_orient_mode, bma2x2_set_orient_mode, bma2x2_get_orient_block, bma2x2_set_orient_block, bma2x2_get_orient_hyst, bma2x2_set_orient_hyst, bma2x2_get_theta, bma2x2_set_theta, bma2x2_get_orient_enable, bma2x2_set_orient_enable, bma2x2_get_flat_hyst, bma2x2_set_flat_hyst, bma2x2_get_flat_hold_time, bma2x2_set_flat_hold_time, bma2x2_get_fifo_wml_trig, bma2x2_set_fifo_wml_trig, bma2x2_get_selftest_axis, bma2x2_set_selftest_axis, bma2x2_get_selftest_sign, bma2x2_set_selftest_sign, bma2x2_get_nvmprog_mode, bma2x2_set_nvmprog_mode, bma2x2_set_nvprog_trig, bma2x2_get_nvmprog_ready, bma2x2_get_nvmprog_remain, bma2x2_get_spi3, bma2x2_set_spi3, bma2x2_get_i2c_wdt, bma2x2_set_i2c_wdt, bma2x2_get_slow_comp, bma2x2_set_slow_comp, bma2x2_get_cal_rdy, bma2x2_set_cal_trigger, bma2x2_set_offset_rst, bma2x2_get_offset_target, bma2x2_set_offset_target, bma2x2_get_offset, bma2x2_set_offset, bma2x2_get_fifo_mode, bma2x2_set_fifo_mode, bma2x2_get_fifo_data_select, bma2x2_set_fifo_data_select, bma2x2_get_fifo_data_output_reg, bma2x2_read_temp, bma2x2_read_accel_xyzt, bma2x2_read_accel_eight_resolution_xyzt, bme280_init, bme280_read_uncomp_temperature, bme280_read_uncomp_pressure, bme280_read_uncomp_humidity, bme280_read_uncomp_pressure_temperature_humidity, bme280_read_pressure_temperature_humidity, bme280_get_calib_param, bme280_get_oversamp_temperature, bme280_set_oversamp_temperature, bme280_get_oversamp_pressure, bme280_set_oversamp_pressure, bme280_get_oversamp_humidity, bme280_set_oversamp_humidity, bme280_get_power_mode, bme280_set_power_mode, bme280_set_soft_rst, bme280_get_spi3, bme280_set_spi3, bme280_get_filter, bme280_set_filter, bme280_get_standby_durn, bme280_set_standby_durn, bme280_get_forced_uncomp_pressure_temperature_humidity, bme280_write_register, bme280_read_register, bmg160_init, bmg160_get_data_Y, bmg160_get_data_Z, bmg160_get_data_XYZ, bmg160_get_data_XYZI, bmg160_get_temp, bmg160_read_register, bmg160_burst_read, bmg160_write_register, bmg160_get_intr_stat_reg_zero, bmg160_get_intr_stat_reg_one, bmg160_get_intr_stat_reg_two, bmg160_get_intr_stat_reg_three, bmg160_get_range_reg, bmg160_set_range_reg, bmg160_get_bw, bmg160_set_bw, bmg160_get_pmu_ext_tri_select, bmg160_set_pmu_ext_tri_select, bmg160_get_high_bw, bmg160_set_high_bw, bmg160_get_shadow_dis, bmg160_set_shadow_dis, bmg160_set_soft_rst, bmg160_get_data_enable, bmg160_set_data_enable, bmg160_get_fifo_enable, bmg160_set_fifo_enable, bmg160_get_auto_offset_enable, bmg160_set_auto_offset_enable, bmg160_get_intr_output_type, bmg160_set_intr_output_type, bmg160_get_intr_level, bmg160_set_intr_level, bmg160_get_intr1_highrate, bmg160_set_intr1_highrate, bmg160_get_intr1_any_motion, bmg160_set_intr1_any_motion, bmg160_get_intr_data, bmg160_set_intr_data, bmg160_get_intr2_offset, bmg160_set_intr2_offset, bmg160_get_intr_offset, bmg160_set_intr1_offset, bmg160_get_intr2_fifo, bmg160_get_intr1_fifo, bmg160_set_intr_fifo, bmg160_get_intr2_highrate, bmg160_set_intr2_highrate, bmg160_get_intr2_any_motion, bmg160_set_intr2_any_motion, bmg160_get_offset_unfilt, bmg160_set_offset_unfilt, bmg160_get_unfilt_data, bmg160_set_unfilt_data, bmg160_get_any_motion_thres, bmg160_set_any_motion_thres, bmg160_get_awake_durn, bmg160_set_awake_durn, bmg160_get_any_motion_durn_sample, bmg160_set_any_motion_durn_sample, bmg160_get_any_motion_enable_axis, bmg160_set_any_motion_enable_axis, bmg160_get_fifo_wm_enable, bmg160_set_fifo_wm_enable, bmg160_set_rst_intr, bmg160_set_offset_rst, bmg160_get_latch_stat, bmg160_set_latch_stat, bmg160_get_latch_intr, bmg160_set_latch_intr, bmg160_get_highrate_hyst, bmg160_set_highrate_hyst, bmg160_get_highrate_thres, bmg160_set_highrate_thres, bmg160_get_highrate_enable_axis, bmg160_set_highrate_enable_axis, bmg160_get_highrate_durn_axis, bmg160_set_highrate_durn_axis, bmg160_get_slow_offset_thres, bmg160_set_slow_offset_thres, bmg160_get_slow_offset_durn, bmg160_set_slow_offset_durn, bmg160_get_slow_offset_enable_axis, bmg160_set_slow_offset_enable_axis, bmg160_get_offset_word_length, bmg160_set_offset_word_length, bmg160_enable_fast_offset, bmg160_get_fast_offset_enable_axis, bmg160_set_fast_offset_enable_axis, bmg160_get_nvm_remain, bmg160_set_nvm_load, bmg160_get_nvm_rdy, bmg160_set_nvm_prog_trig, bmg160_get_nvm_prog_mode, bmg160_set_nvm_prog_mode, bmg160_get_i2c_wdt, bmg160_set_i2c_wdt, bmg160_get_spi3, bmg160_set_spi3, bmg160_get_fifo_tag, bmg160_set_fifo_tag, bmg160_get_fifo_wm_level, bmg160_set_fifo_wm_level, bmg160_get_offset, bmg160_set_offset, bmg160_get_gp, bmg160_set_gp, bmg160_get_FIFO_data_reg, bmg160_get_fifo_stat_reg, bmg160_get_fifo_frame_count, bmg160_get_fifo_overrun, bmg160_get_fifo_mode, bmg160_set_fifo_mode, bmg160_get_fifo_data_select, bmg160_set_fifo_data_select, bmg160_get_power_mode, bmg160_set_power_mode, bmg160_selftest, bmg160_get_auto_sleep_durn, bmg160_set_auto_sleep_durn, bmg160_get_sleep_durn, bmg160_set_sleep_durn, bmi160_set_accel_foc_trigger, bmi160_accel_foc_trigger_xyz, bmi160_set_foc_gyro_enable, bmi160_set_accel_offset_compensation_xaxis, bmi160_set_accel_offset_compensation_yaxis, bmi160_set_accel_offset_compensation_zaxis, bmi160_set_gyro_offset_compensation_xaxis, bmi160_set_gyro_offset_compensation_yaxis, bmi160_set_gyro_offset_compensation_zaxis, bmi160_bst_yamaha_yas537_calib_values, bmi160_bst_yamaha_yas537_measure_xyz_data, bmi160_bst_yamaha_yas537_fifo_xyz_data, bmm050_init, bmm050_get_presetmode, bmm050_set_presetmode, bmm050_set_functional_state, bmm050_get_functional_state, bmm050_read_mag_data_XYZ, bmm050_read_bmx055_remapped_mag_data_XYZ, bmm050_read_mag_data_XYZ_s32, bmm050_read_bmx055_remapped_mag_data_XYZ_s32, bmm050_read_register, bmm050_write_register, bmm050_set_selftest, bmm050_get_selftest_XYZ, bmm050_set_spi3, bmm050_set_data_rate, bmm050_get_data_rate, bmm050_perform_advanced_selftest, bmm050_init_trim_registers, bmm050_set_advanced_selftest, bmm050_get_advanced_selftest, bmm050_get_power_mode, bmm050_set_power_mode, bmm050_get_rep_XY, bmm050_set_rep_XY, bmm050_get_rep_Z, bmm050_set_rep_Z, bmm050_set_control_measurement_x, bmm050_set_control_measurement_y, bmm050_soft_rst, bmm050_get_raw_xyz, bmm050_get_bmx055_remapped_raw_xyz, bmp280_init, bmp280_read_uncomp_temperature, bmp280_read_uncomp_pressure, bmp280_read_uncomp_pressure_temperature, bmp280_read_pressure_temperature, bmp280_get_calib_param, bmp280_get_oversamp_temperature, bmp280_set_oversamp_temperature, bmp280_get_oversamp_pressure, bmp280_set_oversamp_pressure, bmp280_get_power_mode, bmp280_set_power_mode, bmp280_set_soft_rst, bmp280_get_spi3, bmp280_set_spi3, bmp280_get_filter, bmp280_get_standby_durn, bmp280_set_standby_durn, bmp280_set_work_mode, bmp280_get_forced_uncomp_pressure_temperature, bmp280_write_register, bmp280_read_register.
SUCCESS
Referenced by bma2x2_set_mode_value, bma2x2_set_fifo_mode, bma2x2_set_fifo_data_select, bme280_compute_wait_time, bmi160_set_mag_interface_normal, bmi160_set_accel_output_data_rate, bmi160_set_accel_bw, bmi160_set_accel_under_sampling_parameter, bmi160_set_accel_range, bmi160_set_gyro_output_data_rate, bmi160_set_gyro_bw, bmi160_set_gyro_range, bmi160_set_mag_output_data_rate, bmi160_set_fifo_down_gyro, bmi160_set_gyro_fifo_filter_data, bmi160_set_fifo_down_accel, bmi160_set_accel_fifo_filter_data, bmi160_set_fifo_time_enable, bmi160_set_fifo_tag_intr2_enable, bmi160_set_fifo_tag_intr1_enable, bmi160_set_fifo_header_enable, bmi160_set_fifo_mag_enable, bmi160_set_fifo_accel_enable, bmi160_set_fifo_gyro_enable, bmi160_set_i2c_device_addr, bmi160_set_mag_burst, bmi160_set_mag_offset, bmi160_set_mag_manual_enable, bmi160_set_intr_enable_0, bmi160_set_intr_enable_1, bmi160_set_intr_enable_2, bmi160_set_step_detector_enable, bmi160_set_intr_edge_ctrl, bmi160_set_intr_level, bmi160_set_intr_output_type, bmi160_set_output_enable, bmi160_set_latch_intr, bmi160_set_input_enable, bmi160_set_intr_low_g, bmi160_set_intr_high_g, bmi160_set_intr_any_motion, bmi160_set_intr_nomotion, bmi160_set_intr_double_tap, bmi160_set_intr_single_tap, bmi160_set_intr_orient, bmi160_set_intr_flat, bmi160_set_intr_pmu_trig, bmi160_set_intr_fifo_full, bmi160_set_intr_fifo_wm, bmi160_set_intr_data_rdy, bmi160_set_intr_tap_source, bmi160_set_intr_low_high_source, bmi160_set_intr_motion_source, bmi160_set_intr_low_g_hyst, bmi160_set_intr_low_g_mode, bmi160_set_intr_high_g_hyst, bmi160_set_intr_any_motion_durn, bmi160_set_intr_slow_no_motion_durn, bmi160_set_intr_slow_no_motion_select, bmi160_set_intr_significant_motion_select, bmi160_set_intr_significant_motion_skip, bmi160_set_intr_significant_motion_proof, bmi160_set_intr_tap_durn, bmi160_set_intr_tap_shock, bmi160_set_intr_tap_quiet, bmi160_set_intr_tap_thres, bmi160_set_intr_orient_mode, bmi160_set_intr_orient_blocking, bmi160_set_intr_orient_hyst, bmi160_set_intr_orient_theta, bmi160_set_intr_orient_ud_enable, bmi160_set_intr_orient_axes_enable, bmi160_set_intr_flat_theta, bmi160_set_intr_flat_hold, bmi160_set_intr_flat_hyst, bmi160_set_foc_accel_z, bmi160_set_foc_accel_y, bmi160_set_foc_accel_x, bmi160_set_accel_foc_trigger, bmi160_accel_foc_trigger_xyz, bmi160_set_foc_gyro_enable, bmi160_set_nvm_prog_enable, bmi160_set_spi3, bmi160_set_i2c_wdt_select, bmi160_set_i2c_wdt_enable, bmi160_set_if_mode, bmi160_set_gyro_sleep_trigger, bmi160_set_gyro_wakeup_trigger, bmi160_set_gyro_sleep_state, bmi160_set_gyro_wakeup_intr, bmi160_set_accel_selftest_axis, bmi160_set_accel_selftest_sign, bmi160_set_accel_selftest_amp, bmi160_set_gyro_selftest_start, bmi160_set_spi_enable, bmi160_set_spare0_trim, bmi160_set_nvm_counter, bmi160_set_accel_offset_compensation_xaxis, bmi160_set_accel_offset_compensation_yaxis, bmi160_set_accel_offset_compensation_zaxis, bmi160_set_gyro_offset_compensation_xaxis, bmi160_set_gyro_offset_compensation_yaxis, bmi160_set_gyro_offset_compensation_zaxis, bmi160_set_accel_offset_enable, bmi160_set_gyro_offset_enable, bmi160_set_step_config, bmi160_set_step_counter_enable, bmi160_set_target_page, bmi160_set_paging_enable, bmi160_set_pullup_configuration, bmi160_bmm150_mag_set_power_mode, bmi160_bst_yamaha_yas537_calib_values, bmp280_set_oversamp_temperature, bmp280_set_oversamp_pressure, bmp280_set_spi3, bmp280_set_filter, bmp280_set_standby_durn, bmp280_set_work_mode, bmp280_compute_wait_time, bmi160LibErrorMapping, Accelerometer_setBandwidth, Accelerometer_setRange, bme280LibErrorMapping, BMI160_libErrorMapping, Gyroscope_setBandwidth, Gyroscope_setRange, libErrorMapping, configureNewDataInterrupt, configureSlopeInterrupt, Bma280Utils_initialize, Bme280Utils_initialize.
BMA2x2_RETURN_FUNCTION_TYPE
This refers BMA2x2 return type as char
Referenced by bma2x2_burst_read, bma2x2_init, bma2x2_write_reg, bma2x2_read_reg, bma2x2_read_accel_x, bma2x2_read_accel_eight_resolution_x, bma2x2_read_accel_y, bma2x2_read_accel_eight_resolution_y, bma2x2_read_accel_z, bma2x2_read_accel_eight_resolution_z, bma2x2_read_accel_xyz, bma2x2_read_accel_eight_resolution_xyz, bma2x2_get_intr_tap_stat, bma2x2_get_intr_orient_stat, bma2x2_get_fifo_stat, bma2x2_get_fifo_frame_count, bma2x2_get_fifo_overrun, bma2x2_get_intr_stat, bma2x2_get_range, bma2x2_set_range, bma2x2_get_bw, bma2x2_set_bw, bma2x2_get_power_mode, bma2x2_set_power_mode, bma2x2_set_mode_value, bma2x2_get_sleep_durn, bma2x2_set_sleep_durn, bma2x2_get_sleep_timer_mode, bma2x2_set_sleep_timer_mode, bma2x2_get_high_bw, bma2x2_set_high_bw, bma2x2_get_shadow_dis, bma2x2_set_shadow_dis, bma2x2_soft_rst, bma2x2_update_image, bma2x2_get_intr_enable, bma2x2_set_intr_enable, bma2x2_get_intr_fifo_full, bma2x2_set_intr_fifo_full, bma2x2_get_intr_fifo_wm, bma2x2_set_intr_fifo_wm, bma2x2_get_slow_no_motion, bma2x2_set_slow_no_motion, bma2x2_get_intr_low_g, bma2x2_set_intr_low_g, bma2x2_get_intr_high_g, bma2x2_set_intr_high_g, bma2x2_get_intr_slope, bma2x2_set_intr_slope, bma2x2_get_intr_slow_no_motion, bma2x2_set_intr_slow_no_motion, bma2x2_get_intr_double_tap, bma2x2_set_intr_double_tap, bma2x2_get_intr_single_tap, bma2x2_set_intr_single_tap, bma2x2_get_intr_orient, bma2x2_set_intr_orient, bma2x2_get_intr_flat, bma2x2_set_intr_flat, bma2x2_get_new_data, bma2x2_set_new_data, bma2x2_get_intr1_fifo_wm, bma2x2_set_intr1_fifo_wm, bma2x2_get_intr2_fifo_wm, bma2x2_set_intr2_fifo_wm, bma2x2_get_intr1_fifo_full, bma2x2_set_intr1_fifo_full, bma2x2_get_intr2_fifo_full, bma2x2_set_intr2_fifo_full, bma2x2_get_source, bma2x2_set_source, bma2x2_get_intr_output_type, bma2x2_set_intr_output_type, bma2x2_get_intr_level, bma2x2_set_intr_level, bma2x2_rst_intr, bma2x2_get_latch_intr, bma2x2_set_latch_intr, bma2x2_get_durn, bma2x2_set_durn, bma2x2_get_thres, bma2x2_set_thres, bma2x2_get_low_high_g_hyst, bma2x2_set_low_high_g_hyst, bma2x2_get_low_g_mode, bma2x2_set_low_g_mode, bma2x2_get_tap_durn, bma2x2_set_tap_durn, bma2x2_get_tap_shock, bma2x2_set_tap_shock, bma2x2_get_tap_quiet, bma2x2_set_tap_quiet, bma2x2_get_tap_thres, bma2x2_set_tap_thres, bma2x2_get_tap_sample, bma2x2_set_tap_sample, bma2x2_get_orient_mode, bma2x2_set_orient_mode, bma2x2_get_orient_block, bma2x2_set_orient_block, bma2x2_get_orient_hyst, bma2x2_set_orient_hyst, bma2x2_get_theta, bma2x2_set_theta, bma2x2_get_orient_enable, bma2x2_set_orient_enable, bma2x2_get_flat_hyst, bma2x2_set_flat_hyst, bma2x2_get_flat_hold_time, bma2x2_set_flat_hold_time, bma2x2_get_fifo_wml_trig, bma2x2_set_fifo_wml_trig, bma2x2_get_selftest_axis, bma2x2_set_selftest_axis, bma2x2_get_selftest_sign, bma2x2_set_selftest_sign, bma2x2_get_nvmprog_mode, bma2x2_set_nvmprog_mode, bma2x2_set_nvprog_trig, bma2x2_get_nvmprog_ready, bma2x2_get_nvmprog_remain, bma2x2_get_spi3, bma2x2_set_spi3, bma2x2_get_i2c_wdt, bma2x2_set_i2c_wdt, bma2x2_get_slow_comp, bma2x2_set_slow_comp, bma2x2_get_cal_rdy, bma2x2_set_cal_trigger, bma2x2_set_offset_rst, bma2x2_get_offset_target, bma2x2_set_offset_target, bma2x2_get_offset, bma2x2_set_offset, bma2x2_get_fifo_mode, bma2x2_set_fifo_mode, bma2x2_get_fifo_data_select, bma2x2_set_fifo_data_select, bma2x2_get_fifo_data_output_reg, bma2x2_read_temp, bma2x2_read_accel_xyzt, bma2x2_read_accel_eight_resolution_xyzt, bma2x2LibErrorMapping, Accelerometer_setBandwidth, Accelerometer_getBandwidth, Accelerometer_setRange, Accelerometer_getRange, Accelerometer_setSleepDuration, Accelerometer_getSleepDuration, Accelerometer_setMode, Accelerometer_getMode, Accelerometer_readXyzLsbValue, Accelerometer_readXyzGValue, configureNewDataInterrupt, configureSlopeInterrupt, Bma280Utils_initialize, Bma280Utils_disableInterrupt.
BMA2x2_EEP_OFFSET
BMA2x2_IMAGE_BASE
BMA2x2_IMAGE_LEN
BMA2x2_CHIP_ID_ADDR
BMA2x2_X_AXIS_LSB_ADDR
DATA ADDRESS DEFINITIONS
BMA2x2_X_AXIS_MSB_ADDR
Referenced by bma2x2_read_accel_eight_resolution_x, bma2x2_read_accel_eight_resolution_xyz, bma2x2_read_accel_eight_resolution_xyzt.
BMA2x2_Y_AXIS_LSB_ADDR
BMA2x2_Y_AXIS_MSB_ADDR
Referenced by bma2x2_read_accel_eight_resolution_y, bma2x2_read_accel_eight_resolution_xyz, bma2x2_read_accel_eight_resolution_xyzt.
BMA2x2_Z_AXIS_LSB_ADDR
BMA2x2_Z_AXIS_MSB_ADDR
Referenced by bma2x2_read_accel_eight_resolution_z, bma2x2_read_accel_eight_resolution_xyz, bma2x2_read_accel_eight_resolution_xyzt.
BMA2x2_TEMP_ADDR
Referenced by bma2x2_read_temp, bma2x2_read_accel_eight_resolution_xyzt.
BMA2x2_STAT1_ADDR
STATUS ADDRESS DEFINITIONS
Referenced by bma2x2_get_intr_stat.
BMA2x2_STAT2_ADDR
BMA2x2_STAT_TAP_SLOPE_ADDR
Referenced by bma2x2_get_intr_tap_stat.
BMA2x2_STAT_ORIENT_HIGH_ADDR
Referenced by bma2x2_get_intr_orient_stat.
BMA2x2_STAT_FIFO_ADDR
Referenced by bma2x2_get_fifo_stat.
BMA2x2_RANGE_SELECT_ADDR
STATUS ADDRESS DEFINITIONS
BMA2x2_BW_SELECT_ADDR
BMA2x2_MODE_CTRL_ADDR
BMA2x2_LOW_NOISE_CTRL_ADDR
Referenced by bma2x2_get_power_mode.
BMA2x2_DATA_CTRL_ADDR
BMA2x2_RST_ADDR
Referenced by bma2x2_soft_rst.
BMA2x2_INTR_ENABLE1_ADDR
INTERUPT ADDRESS DEFINITIONS
Referenced by bma2x2_set_intr_enable.
BMA2x2_INTR_ENABLE2_ADDR
Referenced by bma2x2_set_intr_enable.
BMA2x2_INTR_SLOW_NO_MOTION_ADDR
BMA2x2_INTR1_PAD_SELECT_ADDR
BMA2x2_INTR_DATA_SELECT_ADDR
BMA2x2_INTR2_PAD_SELECT_ADDR
BMA2x2_INTR_SOURCE_ADDR
BMA2x2_INTR_SET_ADDR
BMA2x2_INTR_CTRL_ADDR
BMA2x2_LOW_DURN_ADDR
FEATURE ADDRESS DEFINITIONS
Referenced by bma2x2_get_durn, bma2x2_set_durn.
BMA2x2_LOW_THRES_ADDR
Referenced by bma2x2_get_thres, bma2x2_set_thres.
BMA2x2_LOW_HIGH_HYST_ADDR
BMA2x2_HIGH_DURN_ADDR
Referenced by bma2x2_get_durn, bma2x2_set_durn.
BMA2x2_HIGH_THRES_ADDR
Referenced by bma2x2_get_thres, bma2x2_set_thres.
BMA2x2_SLOPE_DURN_ADDR
BMA2x2_SLOPE_THRES_ADDR
Referenced by bma2x2_get_thres, bma2x2_set_thres.
BMA2x2_SLOW_NO_MOTION_THRES_ADDR
Referenced by bma2x2_get_thres, bma2x2_set_thres.
BMA2x2_TAP_PARAM_ADDR
BMA2x2_TAP_THRES_ADDR
BMA2x2_ORIENT_PARAM_ADDR
BMA2x2_THETA_BLOCK_ADDR
BMA2x2_THETA_FLAT_ADDR
BMA2x2_FLAT_HOLD_TIME_ADDR
BMA2x2_SELFTEST_ADDR
BMA2x2_EEPROM_CTRL_ADDR
BMA2x2_SERIAL_CTRL_ADDR
BMA2x2_OFFSET_CTRL_ADDR
OFFSET ADDRESS DEFINITIONS
BMA2x2_OFFSET_PARAMS_ADDR
BMA2x2_OFFSET_X_AXIS_ADDR
Referenced by bma2x2_get_offset, bma2x2_set_offset.
BMA2x2_OFFSET_Y_AXIS_ADDR
Referenced by bma2x2_get_offset, bma2x2_set_offset.
BMA2x2_OFFSET_Z_AXIS_ADDR
Referenced by bma2x2_get_offset, bma2x2_set_offset.
BMA2x2_GP0_ADDR
GP ADDRESS DEFINITIONS
BMA2x2_GP1_ADDR
BMA2x2_FIFO_MODE_ADDR
FIFO ADDRESS DEFINITIONS
BMA2x2_FIFO_DATA_OUTPUT_ADDR
Referenced by bma2x2_get_fifo_data_output_reg.
BMA2x2_FIFO_WML_TRIG
BMA2x2_12_RESOLUTION
Referenced by bma2x2_read_accel_x, bma2x2_read_accel_y, bma2x2_read_accel_z, bma2x2_read_accel_xyz, bma2x2_read_accel_xyzt.
BMA2x2_10_RESOLUTION
Referenced by bma2x2_read_accel_x, bma2x2_read_accel_y, bma2x2_read_accel_z, bma2x2_read_accel_xyz, bma2x2_read_accel_xyzt.
BMA2x2_14_RESOLUTION
Referenced by bma2x2_read_accel_x, bma2x2_read_accel_y, bma2x2_read_accel_z, bma2x2_read_accel_xyz, bma2x2_read_accel_xyzt.
BMA2x2_MDELAY_DATA_TYPE
BMA2x2_EE_W_DELAY
BMA2x2_CHIP_ID_POS
BMA2x2_CHIP_ID_MSK
BMA2x2_CHIP_ID_LEN
BMA2x2_CHIP_ID_REG
Referenced by bma2x2_init.
BMA2x2_NEW_DATA_X_POS
BMA2x2_NEW_DATA_X_LEN
BMA2x2_NEW_DATA_X_MSK
BMA2x2_NEW_DATA_X_REG
BMA2x2_ACCEL_X14_LSB_POS
BMA2x2_ACCEL_X14_LSB_LEN
BMA2x2_ACCEL_X14_LSB_MSK
BMA2x2_ACCEL_X14_LSB_REG
Referenced by bma2x2_read_accel_x, bma2x2_read_accel_xyz, bma2x2_read_accel_xyzt.
BMA2x2_ACCEL_X12_LSB_POS
BMA2x2_ACCEL_X12_LSB_LEN
BMA2x2_ACCEL_X12_LSB_MSK
BMA2x2_ACCEL_X12_LSB_REG
Referenced by bma2x2_read_accel_x, bma2x2_read_accel_xyz, bma2x2_read_accel_xyzt.
BMA2x2_ACCEL_X10_LSB_POS
BMA2x2_ACCEL_X10_LSB_LEN
BMA2x2_ACCEL_X10_LSB_MSK
BMA2x2_ACCEL_X10_LSB_REG
Referenced by bma2x2_read_accel_x, bma2x2_read_accel_xyz, bma2x2_read_accel_xyzt.
BMA2x2_ACCEL_X8_LSB_POS
BMA2x2_ACCEL_X8_LSB_LEN
BMA2x2_ACCEL_X8_LSB_MSK
BMA2x2_ACCEL_X8_LSB_REG
BMA2x2_ACCEL_X_MSB_POS
BMA2x2_ACCEL_X_MSB_LEN
BMA2x2_ACCEL_X_MSB_MSK
BMA2x2_ACCEL_X_MSB_REG
BMA2x2_NEW_DATA_Y_POS
BMA2x2_NEW_DATA_Y_LEN
BMA2x2_NEW_DATA_Y_MSK
BMA2x2_NEW_DATA_Y_REG
BMA2x2_ACCEL_Y14_LSB_POS
BMA2x2_ACCEL_Y14_LSB_LEN
BMA2x2_ACCEL_Y14_LSB_MSK
BMA2x2_ACCEL_Y14_LSB_REG
Referenced by bma2x2_read_accel_y.
BMA2x2_ACCEL_Y12_LSB_POS
BMA2x2_ACCEL_Y12_LSB_LEN
BMA2x2_ACCEL_Y12_LSB_MSK
BMA2x2_ACCEL_Y12_LSB_REG
Referenced by bma2x2_read_accel_y.
BMA2x2_ACCEL_Y10_LSB_POS
BMA2x2_ACCEL_Y10_LSB_LEN
BMA2x2_ACCEL_Y10_LSB_MSK
BMA2x2_ACCEL_Y10_LSB_REG
Referenced by bma2x2_read_accel_y.
BMA2x2_ACCEL_Y8_LSB_POS
BMA2x2_ACCEL_Y8_LSB_LEN
BMA2x2_ACCEL_Y8_LSB_MSK
BMA2x2_ACCEL_Y8_LSB_REG
BMA2x2_ACCEL_Y_MSB_POS
BMA2x2_ACCEL_Y_MSB_LEN
BMA2x2_ACCEL_Y_MSB_MSK
BMA2x2_ACCEL_Y_MSB_REG
BMA2x2_NEW_DATA_Z_POS
BMA2x2_NEW_DATA_Z_LEN
BMA2x2_NEW_DATA_Z_MSK
BMA2x2_NEW_DATA_Z_REG
BMA2x2_ACCEL_Z14_LSB_POS
BMA2x2_ACCEL_Z14_LSB_LEN
BMA2x2_ACCEL_Z14_LSB_MSK
BMA2x2_ACCEL_Z14_LSB_REG
Referenced by bma2x2_read_accel_z.
BMA2x2_ACCEL_Z12_LSB_POS
BMA2x2_ACCEL_Z12_LSB_LEN
BMA2x2_ACCEL_Z12_LSB_MSK
BMA2x2_ACCEL_Z12_LSB_REG
Referenced by bma2x2_read_accel_z.
BMA2x2_ACCEL_Z10_LSB_POS
BMA2x2_ACCEL_Z10_LSB_LEN
BMA2x2_ACCEL_Z10_LSB_MSK
BMA2x2_ACCEL_Z10_LSB_REG
Referenced by bma2x2_read_accel_z.
BMA2x2_ACCEL_Z8_LSB_POS
BMA2x2_ACCEL_Z8_LSB_LEN
BMA2x2_ACCEL_Z8_LSB_MSK
BMA2x2_ACCEL_Z8_LSB_REG
BMA2x2_ACCEL_Z_MSB_POS
BMA2x2_ACCEL_Z_MSB_LEN
BMA2x2_ACCEL_Z_MSB_MSK
BMA2x2_ACCEL_Z_MSB_REG
BMA2x2_ACCEL_TEMP_MSB_POS
BMA2x2_ACCEL_TEMP_MSB_LEN
BMA2x2_ACCEL_TEMP_MSB_MSK
BMA2x2_ACCEL_TEMP_MSB_REG
BMA2x2_LOW_G_INTR_STAT_POS
BMA2x2_LOW_G_INTR_STAT_LEN
BMA2x2_LOW_G_INTR_STAT_MSK
BMA2x2_LOW_G_INTR_STAT_REG
BMA2x2_HIGH_G_INTR_STAT_POS
BMA2x2_HIGH_G_INTR_STAT_LEN
BMA2x2_HIGH_G_INTR_STAT_MSK
BMA2x2_HIGH_G_INTR_STAT_REG
BMA2x2_SLOPE_INTR_STAT_POS
BMA2x2_SLOPE_INTR_STAT_LEN
BMA2x2_SLOPE_INTR_STAT_MSK
BMA2x2_SLOPE_INTR_STAT_REG
BMA2x2_SLOW_NO_MOTION_INTR_STAT_POS
BMA2x2_SLOW_NO_MOTION_INTR_STAT_LEN
BMA2x2_SLOW_NO_MOTION_INTR_STAT_MSK
BMA2x2_SLOW_NO_MOTION_INTR_STAT_REG
BMA2x2_DOUBLE_TAP_INTR_STAT_POS
BMA2x2_DOUBLE_TAP_INTR_STAT_LEN
BMA2x2_DOUBLE_TAP_INTR_STAT_MSK
BMA2x2_DOUBLE_TAP_INTR_STAT_REG
BMA2x2_SINGLE_TAP_INTR_STAT_POS
BMA2x2_SINGLE_TAP_INTR_STAT_LEN
BMA2x2_SINGLE_TAP_INTR_STAT_MSK
BMA2x2_SINGLE_TAP_INTR_STAT_REG
BMA2x2_ORIENT_INTR_STAT_POS
BMA2x2_ORIENT_INTR_STAT_LEN
BMA2x2_ORIENT_INTR_STAT_MSK
BMA2x2_ORIENT_INTR_STAT_REG
BMA2x2_FLAT_INTR_STAT_POS
BMA2x2_FLAT_INTR_STAT_LEN
BMA2x2_FLAT_INTR_STAT_MSK
BMA2x2_FLAT_INTR_STAT_REG
BMA2x2_FIFO_FULL_INTR_STAT_POS
BMA2x2_FIFO_FULL_INTR_STAT_LEN
BMA2x2_FIFO_FULL_INTR_STAT_MSK
BMA2x2_FIFO_FULL_INTR_STAT_REG
BMA2x2_FIFO_WM_INTR_STAT_POS
BMA2x2_FIFO_WM_INTR_STAT_LEN
BMA2x2_FIFO_WM_INTR_STAT_MSK
BMA2x2_FIFO_WM_INTR_STAT_REG
BMA2x2_DATA_INTR_STAT_POS
BMA2x2_DATA_INTR_STAT_LEN
BMA2x2_DATA_INTR_STAT_MSK
BMA2x2_DATA_INTR_STAT_REG
BMA2x2_SLOPE_FIRST_X_POS
BMA2x2_SLOPE_FIRST_X_LEN
BMA2x2_SLOPE_FIRST_X_MSK
BMA2x2_SLOPE_FIRST_X_REG
BMA2x2_SLOPE_FIRST_Y_POS
BMA2x2_SLOPE_FIRST_Y_LEN
BMA2x2_SLOPE_FIRST_Y_MSK
BMA2x2_SLOPE_FIRST_Y_REG
BMA2x2_SLOPE_FIRST_Z_POS
BMA2x2_SLOPE_FIRST_Z_LEN
BMA2x2_SLOPE_FIRST_Z_MSK
BMA2x2_SLOPE_FIRST_Z_REG
BMA2x2_SLOPE_SIGN_STAT_POS
BMA2x2_SLOPE_SIGN_STAT_LEN
BMA2x2_SLOPE_SIGN_STAT_MSK
BMA2x2_SLOPE_SIGN_STAT_REG
BMA2x2_TAP_FIRST_X_POS
BMA2x2_TAP_FIRST_X_LEN
BMA2x2_TAP_FIRST_X_MSK
BMA2x2_TAP_FIRST_X_REG
BMA2x2_TAP_FIRST_Y_POS
BMA2x2_TAP_FIRST_Y_LEN
BMA2x2_TAP_FIRST_Y_MSK
BMA2x2_TAP_FIRST_Y_REG
BMA2x2_TAP_FIRST_Z_POS
BMA2x2_TAP_FIRST_Z_LEN
BMA2x2_TAP_FIRST_Z_MSK
BMA2x2_TAP_FIRST_Z_REG
BMA2x2_TAP_SIGN_STAT_POS
BMA2x2_TAP_SIGN_STAT_LEN
BMA2x2_TAP_SIGN_STAT_MSK
BMA2x2_TAP_SIGN_STAT_REG
BMA2x2_HIGH_G_FIRST_X_POS
BMA2x2_HIGH_G_FIRST_X_LEN
BMA2x2_HIGH_G_FIRST_X_MSK
BMA2x2_HIGH_G_FIRST_X_REG
BMA2x2_HIGH_G_FIRST_Y_POS
BMA2x2_HIGH_G_FIRST_Y_LEN
BMA2x2_HIGH_G_FIRST_Y_MSK
BMA2x2_HIGH_G_FIRST_Y_REG
BMA2x2_HIGH_G_FIRST_Z_POS
BMA2x2_HIGH_G_FIRST_Z_LEN
BMA2x2_HIGH_G_FIRST_Z_MSK
BMA2x2_HIGH_G_FIRST_Z_REG
BMA2x2_HIGH_G_SIGN_STAT_POS
BMA2x2_HIGH_G_SIGN_STAT_LEN
BMA2x2_HIGH_G_SIGN_STAT_MSK
BMA2x2_HIGH_G_SIGN_STAT_REG
BMA2x2_ORIENT_STAT_POS
BMA2x2_ORIENT_STAT_LEN
BMA2x2_ORIENT_STAT_MSK
BMA2x2_ORIENT_STAT_REG
BMA2x2_FLAT_STAT_POS
BMA2x2_FLAT_STAT_LEN
BMA2x2_FLAT_STAT_MSK
BMA2x2_FLAT_STAT_REG
BMA2x2_FIFO_FRAME_COUNT_STAT_POS
BMA2x2_FIFO_FRAME_COUNT_STAT_LEN
BMA2x2_FIFO_FRAME_COUNT_STAT_MSK
BMA2x2_FIFO_FRAME_COUNT_STAT_REG
Referenced by bma2x2_get_fifo_frame_count.
BMA2x2_FIFO_OVERRUN_STAT_POS
BMA2x2_FIFO_OVERRUN_STAT_LEN
BMA2x2_FIFO_OVERRUN_STAT_MSK
BMA2x2_FIFO_OVERRUN_STAT_REG
Referenced by bma2x2_get_fifo_overrun.
BMA2x2_RANGE_SELECT_POS
BMA2x2_RANGE_SELECT_LEN
BMA2x2_RANGE_SELECT_MSK
BMA2x2_RANGE_SELECT_REG
Referenced by bma2x2_get_range, bma2x2_set_range.
BMA2x2_BW_POS
BMA2x2_BW_LEN
BMA2x2_BW_MSK
BMA2x2_BW_REG
Referenced by bma2x2_get_bw, bma2x2_set_bw.
BMA2x2_SLEEP_DURN_POS
BMA2x2_SLEEP_DURN_LEN
BMA2x2_SLEEP_DURN_MSK
BMA2x2_SLEEP_DURN_REG
Referenced by bma2x2_get_sleep_durn, bma2x2_set_sleep_durn.
BMA2x2_MODE_CTRL_POS
BMA2x2_MODE_CTRL_LEN
BMA2x2_MODE_CTRL_MSK
BMA2x2_MODE_CTRL_REG
Referenced by bma2x2_get_power_mode, bma2x2_set_power_mode.
BMA2x2_SLEEP_TIMER_POS
BMA2x2_SLEEP_TIMER_LEN
BMA2x2_SLEEP_TIMER_MSK
BMA2x2_SLEEP_TIMER_REG
Referenced by bma2x2_get_sleep_timer_mode, bma2x2_set_sleep_timer_mode.
BMA2x2_LOW_POWER_MODE_POS
BMA2x2_LOW_POWER_MODE_LEN
BMA2x2_LOW_POWER_MODE_MSK
BMA2x2_LOW_POWER_MODE_REG
Referenced by bma2x2_set_power_mode.
BMA2x2_DIS_SHADOW_PROC_POS
BMA2x2_DIS_SHADOW_PROC_LEN
BMA2x2_DIS_SHADOW_PROC_MSK
BMA2x2_DIS_SHADOW_PROC_REG
Referenced by bma2x2_get_shadow_dis, bma2x2_set_shadow_dis.
BMA2x2_ENABLE_DATA_HIGH_BW_POS
BMA2x2_ENABLE_DATA_HIGH_BW_LEN
BMA2x2_ENABLE_DATA_HIGH_BW_MSK
BMA2x2_ENABLE_DATA_HIGH_BW_REG
Referenced by bma2x2_get_high_bw, bma2x2_set_high_bw.
BMA2x2_ENABLE_SOFT_RESET_VALUE
Referenced by bma2x2_soft_rst.
BMA2x2_ENABLE_SLOPE_X_INTR_POS
BMA2x2_ENABLE_SLOPE_X_INTR_LEN
BMA2x2_ENABLE_SLOPE_X_INTR_MSK
BMA2x2_ENABLE_SLOPE_X_INTR_REG
Referenced by bma2x2_get_intr_enable.
BMA2x2_ENABLE_SLOPE_Y_INTR_POS
BMA2x2_ENABLE_SLOPE_Y_INTR_LEN
BMA2x2_ENABLE_SLOPE_Y_INTR_MSK
BMA2x2_ENABLE_SLOPE_Y_INTR_REG
Referenced by bma2x2_get_intr_enable.
BMA2x2_ENABLE_SLOPE_Z_INTR_POS
BMA2x2_ENABLE_SLOPE_Z_INTR_LEN
BMA2x2_ENABLE_SLOPE_Z_INTR_MSK
BMA2x2_ENABLE_SLOPE_Z_INTR_REG
Referenced by bma2x2_get_intr_enable.
BMA2x2_ENABLE_DOUBLE_TAP_INTR_POS
BMA2x2_ENABLE_DOUBLE_TAP_INTR_LEN
BMA2x2_ENABLE_DOUBLE_TAP_INTR_MSK
BMA2x2_ENABLE_DOUBLE_TAP_INTR_REG
Referenced by bma2x2_get_intr_enable.
BMA2x2_ENABLE_SINGLE_TAP_INTR_POS
BMA2x2_ENABLE_SINGLE_TAP_INTR_LEN
BMA2x2_ENABLE_SINGLE_TAP_INTR_MSK
BMA2x2_ENABLE_SINGLE_TAP_INTR_REG
Referenced by bma2x2_get_intr_enable.
BMA2x2_ENABLE_ORIENT_INTR_POS
BMA2x2_ENABLE_ORIENT_INTR_LEN
BMA2x2_ENABLE_ORIENT_INTR_MSK
BMA2x2_ENABLE_ORIENT_INTR_REG
Referenced by bma2x2_get_intr_enable.
BMA2x2_ENABLE_FLAT_INTR_POS
BMA2x2_ENABLE_FLAT_INTR_LEN
BMA2x2_ENABLE_FLAT_INTR_MSK
BMA2x2_ENABLE_FLAT_INTR_REG
Referenced by bma2x2_get_intr_enable.
BMA2x2_ENABLE_HIGH_G_X_INTR_POS
BMA2x2_ENABLE_HIGH_G_X_INTR_LEN
BMA2x2_ENABLE_HIGH_G_X_INTR_MSK
BMA2x2_ENABLE_HIGH_G_X_INTR_REG
Referenced by bma2x2_get_intr_enable.
BMA2x2_ENABLE_HIGH_G_Y_INTR_POS
BMA2x2_ENABLE_HIGH_G_Y_INTR_LEN
BMA2x2_ENABLE_HIGH_G_Y_INTR_MSK
BMA2x2_ENABLE_HIGH_G_Y_INTR_REG
Referenced by bma2x2_get_intr_enable.
BMA2x2_ENABLE_HIGH_G_Z_INTR_POS
BMA2x2_ENABLE_HIGH_G_Z_INTR_LEN
BMA2x2_ENABLE_HIGH_G_Z_INTR_MSK
BMA2x2_ENABLE_HIGH_G_Z_INTR_REG
Referenced by bma2x2_get_intr_enable.
BMA2x2_ENABLE_LOW_G_INTR_POS
BMA2x2_ENABLE_LOW_G_INTR_LEN
BMA2x2_ENABLE_LOW_G_INTR_MSK
BMA2x2_ENABLE_LOW_G_INTR_REG
Referenced by bma2x2_get_intr_enable.
BMA2x2_ENABLE_NEW_DATA_INTR_POS
BMA2x2_ENABLE_NEW_DATA_INTR_LEN
BMA2x2_ENABLE_NEW_DATA_INTR_MSK
BMA2x2_ENABLE_NEW_DATA_INTR_REG
Referenced by bma2x2_get_intr_enable.
BMA2x2_INTR_FIFO_FULL_ENABLE_INTR_POS
BMA2x2_INTR_FIFO_FULL_ENABLE_INTR_LEN
BMA2x2_INTR_FIFO_FULL_ENABLE_INTR_MSK
BMA2x2_INTR_FIFO_FULL_ENABLE_INTR_REG
Referenced by bma2x2_get_intr_fifo_full, bma2x2_set_intr_fifo_full.
BMA2x2_INTR_FIFO_WM_ENABLE_INTR_POS
BMA2x2_INTR_FIFO_WM_ENABLE_INTR_LEN
BMA2x2_INTR_FIFO_WM_ENABLE_INTR_MSK
BMA2x2_INTR_FIFO_WM_ENABLE_INTR_REG
Referenced by bma2x2_get_intr_fifo_wm, bma2x2_set_intr_fifo_wm.
BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_X_INTR_POS
BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_X_INTR_LEN
BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_X_INTR_MSK
BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_X_INTR_REG
Referenced by bma2x2_get_slow_no_motion, bma2x2_set_slow_no_motion.
BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_Y_INTR_POS
BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_Y_INTR_LEN
BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_Y_INTR_MSK
BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_Y_INTR_REG
Referenced by bma2x2_get_slow_no_motion, bma2x2_set_slow_no_motion.
BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_Z_INTR_POS
BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_Z_INTR_LEN
BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_Z_INTR_MSK
BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_Z_INTR_REG
Referenced by bma2x2_get_slow_no_motion, bma2x2_set_slow_no_motion.
BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_SELECT_INTR_POS
BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_SELECT_INTR_LEN
BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_SELECT_INTR_MSK
BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_SELECT_INTR_REG
Referenced by bma2x2_get_slow_no_motion, bma2x2_set_slow_no_motion.
BMA2x2_ENABLE_INTR1_PAD_LOW_G_POS
BMA2x2_ENABLE_INTR1_PAD_LOW_G_LEN
BMA2x2_ENABLE_INTR1_PAD_LOW_G_MSK
BMA2x2_ENABLE_INTR1_PAD_LOW_G_REG
Referenced by bma2x2_get_intr_low_g, bma2x2_set_intr_low_g.
BMA2x2_ENABLE_INTR1_PAD_HIGH_G_POS
BMA2x2_ENABLE_INTR1_PAD_HIGH_G_LEN
BMA2x2_ENABLE_INTR1_PAD_HIGH_G_MSK
BMA2x2_ENABLE_INTR1_PAD_HIGH_G_REG
Referenced by bma2x2_get_intr_high_g, bma2x2_set_intr_high_g.
BMA2x2_ENABLE_INTR1_PAD_SLOPE_POS
BMA2x2_ENABLE_INTR1_PAD_SLOPE_LEN
BMA2x2_ENABLE_INTR1_PAD_SLOPE_MSK
BMA2x2_ENABLE_INTR1_PAD_SLOPE_REG
Referenced by bma2x2_get_intr_slope, bma2x2_set_intr_slope.
BMA2x2_ENABLE_INTR1_PAD_SLOW_NO_MOTION_POS
BMA2x2_ENABLE_INTR1_PAD_SLOW_NO_MOTION_LEN
BMA2x2_ENABLE_INTR1_PAD_SLOW_NO_MOTION_MSK
BMA2x2_ENABLE_INTR1_PAD_SLOW_NO_MOTION_REG
Referenced by bma2x2_get_intr_slow_no_motion, bma2x2_set_intr_slow_no_motion.
BMA2x2_ENABLE_INTR1_PAD_DOUBLE_TAP_POS
BMA2x2_ENABLE_INTR1_PAD_DOUBLE_TAP_LEN
BMA2x2_ENABLE_INTR1_PAD_DOUBLE_TAP_MSK
BMA2x2_ENABLE_INTR1_PAD_DOUBLE_TAP_REG
Referenced by bma2x2_get_intr_double_tap, bma2x2_set_intr_double_tap.
BMA2x2_ENABLE_INTR1_PAD_SINGLE_TAP_POS
BMA2x2_ENABLE_INTR1_PAD_SINGLE_TAP_LEN
BMA2x2_ENABLE_INTR1_PAD_SINGLE_TAP_MSK
BMA2x2_ENABLE_INTR1_PAD_SINGLE_TAP_REG
Referenced by bma2x2_get_intr_single_tap, bma2x2_set_intr_single_tap.
BMA2x2_ENABLE_INTR1_PAD_ORIENT_POS
BMA2x2_ENABLE_INTR1_PAD_ORIENT_LEN
BMA2x2_ENABLE_INTR1_PAD_ORIENT_MSK
BMA2x2_ENABLE_INTR1_PAD_ORIENT_REG
Referenced by bma2x2_get_intr_orient, bma2x2_set_intr_orient.
BMA2x2_ENABLE_INTR1_PAD_FLAT_POS
BMA2x2_ENABLE_INTR1_PAD_FLAT_LEN
BMA2x2_ENABLE_INTR1_PAD_FLAT_MSK
BMA2x2_ENABLE_INTR1_PAD_FLAT_REG
Referenced by bma2x2_get_intr_flat, bma2x2_set_intr_flat.
BMA2x2_ENABLE_INTR2_PAD_LOW_G_POS
BMA2x2_ENABLE_INTR2_PAD_LOW_G_LEN
BMA2x2_ENABLE_INTR2_PAD_LOW_G_MSK
BMA2x2_ENABLE_INTR2_PAD_LOW_G_REG
Referenced by bma2x2_get_intr_low_g, bma2x2_set_intr_low_g.
BMA2x2_ENABLE_INTR2_PAD_HIGH_G_POS
BMA2x2_ENABLE_INTR2_PAD_HIGH_G_LEN
BMA2x2_ENABLE_INTR2_PAD_HIGH_G_MSK
BMA2x2_ENABLE_INTR2_PAD_HIGH_G_REG
Referenced by bma2x2_get_intr_high_g, bma2x2_set_intr_high_g.
BMA2x2_ENABLE_INTR2_PAD_SLOPE_POS
BMA2x2_ENABLE_INTR2_PAD_SLOPE_LEN
BMA2x2_ENABLE_INTR2_PAD_SLOPE_MSK
BMA2x2_ENABLE_INTR2_PAD_SLOPE_REG
Referenced by bma2x2_get_intr_slope, bma2x2_set_intr_slope.
BMA2x2_ENABLE_INTR2_PAD_SLOW_NO_MOTION_POS
BMA2x2_ENABLE_INTR2_PAD_SLOW_NO_MOTION_LEN
BMA2x2_ENABLE_INTR2_PAD_SLOW_NO_MOTION_MSK
BMA2x2_ENABLE_INTR2_PAD_SLOW_NO_MOTION_REG
Referenced by bma2x2_get_intr_slow_no_motion, bma2x2_set_intr_slow_no_motion.
BMA2x2_ENABLE_INTR2_PAD_DOUBLE_TAP_POS
BMA2x2_ENABLE_INTR2_PAD_DOUBLE_TAP_LEN
BMA2x2_ENABLE_INTR2_PAD_DOUBLE_TAP_MSK
BMA2x2_ENABLE_INTR2_PAD_DOUBLE_TAP_REG
Referenced by bma2x2_get_intr_double_tap, bma2x2_set_intr_double_tap.
BMA2x2_ENABLE_INTR2_PAD_SINGLE_TAP_POS
BMA2x2_ENABLE_INTR2_PAD_SINGLE_TAP_LEN
BMA2x2_ENABLE_INTR2_PAD_SINGLE_TAP_MSK
BMA2x2_ENABLE_INTR2_PAD_SINGLE_TAP_REG
Referenced by bma2x2_get_intr_single_tap, bma2x2_set_intr_single_tap.
BMA2x2_ENABLE_INTR2_PAD_ORIENT_POS
BMA2x2_ENABLE_INTR2_PAD_ORIENT_LEN
BMA2x2_ENABLE_INTR2_PAD_ORIENT_MSK
BMA2x2_ENABLE_INTR2_PAD_ORIENT_REG
Referenced by bma2x2_get_intr_orient, bma2x2_set_intr_orient.
BMA2x2_ENABLE_INTR2_PAD_FLAT_POS
BMA2x2_ENABLE_INTR2_PAD_FLAT_LEN
BMA2x2_ENABLE_INTR2_PAD_FLAT_MSK
BMA2x2_ENABLE_INTR2_PAD_FLAT_REG
Referenced by bma2x2_get_intr_flat, bma2x2_set_intr_flat.
BMA2x2_ENABLE_INTR1_PAD_NEWDATA_POS
BMA2x2_ENABLE_INTR1_PAD_NEWDATA_LEN
BMA2x2_ENABLE_INTR1_PAD_NEWDATA_MSK
BMA2x2_ENABLE_INTR1_PAD_NEWDATA_REG
Referenced by bma2x2_get_new_data, bma2x2_set_new_data.
BMA2x2_ENABLE_INTR2_PAD_NEWDATA_POS
BMA2x2_ENABLE_INTR2_PAD_NEWDATA_LEN
BMA2x2_ENABLE_INTR2_PAD_NEWDATA_MSK
BMA2x2_ENABLE_INTR2_PAD_NEWDATA_REG
Referenced by bma2x2_get_new_data, bma2x2_set_new_data.
BMA2x2_ENABLE_INTR1_PAD_FIFO_WM_POS
BMA2x2_ENABLE_INTR1_PAD_FIFO_WM_LEN
BMA2x2_ENABLE_INTR1_PAD_FIFO_WM_MSK
BMA2x2_ENABLE_INTR1_PAD_FIFO_WM_REG
Referenced by bma2x2_get_intr1_fifo_wm, bma2x2_set_intr1_fifo_wm.
BMA2x2_ENABLE_INTR1_PAD_FIFO_FULL_POS
BMA2x2_ENABLE_INTR1_PAD_FIFO_FULL_LEN
BMA2x2_ENABLE_INTR1_PAD_FIFO_FULL_MSK
BMA2x2_ENABLE_INTR1_PAD_FIFO_FULL_REG
Referenced by bma2x2_get_intr1_fifo_full, bma2x2_set_intr1_fifo_full.
BMA2x2_ENABLE_INTR2_PAD_FIFO_FULL_POS
BMA2x2_ENABLE_INTR2_PAD_FIFO_FULL_LEN
BMA2x2_ENABLE_INTR2_PAD_FIFO_FULL_MSK
BMA2x2_ENABLE_INTR2_PAD_FIFO_FULL_REG
Referenced by bma2x2_get_intr2_fifo_full, bma2x2_set_intr2_fifo_full.
BMA2x2_ENABLE_INTR2_PAD_FIFO_WM_POS
BMA2x2_ENABLE_INTR2_PAD_FIFO_WM_LEN
BMA2x2_ENABLE_INTR2_PAD_FIFO_WM_MSK
BMA2x2_ENABLE_INTR2_PAD_FIFO_WM_REG
Referenced by bma2x2_get_intr2_fifo_wm, bma2x2_set_intr2_fifo_wm.
BMA2x2_UNFILT_INTR_SOURCE_LOW_G_POS
BMA2x2_UNFILT_INTR_SOURCE_LOW_G_LEN
BMA2x2_UNFILT_INTR_SOURCE_LOW_G_MSK
BMA2x2_UNFILT_INTR_SOURCE_LOW_G_REG
Referenced by bma2x2_get_source, bma2x2_set_source.
BMA2x2_UNFILT_INTR_SOURCE_HIGH_G_POS
BMA2x2_UNFILT_INTR_SOURCE_HIGH_G_LEN
BMA2x2_UNFILT_INTR_SOURCE_HIGH_G_MSK
BMA2x2_UNFILT_INTR_SOURCE_HIGH_G_REG
Referenced by bma2x2_get_source, bma2x2_set_source.
BMA2x2_UNFILT_INTR_SOURCE_SLOPE_POS
BMA2x2_UNFILT_INTR_SOURCE_SLOPE_LEN
BMA2x2_UNFILT_INTR_SOURCE_SLOPE_MSK
BMA2x2_UNFILT_INTR_SOURCE_SLOPE_REG
Referenced by bma2x2_get_source, bma2x2_set_source.
BMA2x2_UNFILT_INTR_SOURCE_SLOW_NO_MOTION_POS
BMA2x2_UNFILT_INTR_SOURCE_SLOW_NO_MOTION_LEN
BMA2x2_UNFILT_INTR_SOURCE_SLOW_NO_MOTION_MSK
BMA2x2_UNFILT_INTR_SOURCE_SLOW_NO_MOTION_REG
Referenced by bma2x2_get_source, bma2x2_set_source.
BMA2x2_UNFILT_INTR_SOURCE_TAP_POS
BMA2x2_UNFILT_INTR_SOURCE_TAP_LEN
BMA2x2_UNFILT_INTR_SOURCE_TAP_MSK
BMA2x2_UNFILT_INTR_SOURCE_TAP_REG
Referenced by bma2x2_get_source, bma2x2_set_source.
BMA2x2_UNFILT_INTR_SOURCE_DATA_POS
BMA2x2_UNFILT_INTR_SOURCE_DATA_LEN
BMA2x2_UNFILT_INTR_SOURCE_DATA_MSK
BMA2x2_UNFILT_INTR_SOURCE_DATA_REG
Referenced by bma2x2_get_source, bma2x2_set_source.
BMA2x2_INTR1_PAD_ACTIVE_LEVEL_POS
BMA2x2_INTR1_PAD_ACTIVE_LEVEL_LEN
BMA2x2_INTR1_PAD_ACTIVE_LEVEL_MSK
BMA2x2_INTR1_PAD_ACTIVE_LEVEL_REG
Referenced by bma2x2_get_intr_level, bma2x2_set_intr_level.
BMA2x2_INTR2_PAD_ACTIVE_LEVEL_POS
BMA2x2_INTR2_PAD_ACTIVE_LEVEL_LEN
BMA2x2_INTR2_PAD_ACTIVE_LEVEL_MSK
BMA2x2_INTR2_PAD_ACTIVE_LEVEL_REG
Referenced by bma2x2_get_intr_level, bma2x2_set_intr_level.
BMA2x2_INTR1_PAD_OUTPUT_TYPE_POS
BMA2x2_INTR1_PAD_OUTPUT_TYPE_LEN
BMA2x2_INTR1_PAD_OUTPUT_TYPE_MSK
BMA2x2_INTR1_PAD_OUTPUT_TYPE_REG
Referenced by bma2x2_get_intr_output_type, bma2x2_set_intr_output_type.
BMA2x2_INTR2_PAD_OUTPUT_TYPE_POS
BMA2x2_INTR2_PAD_OUTPUT_TYPE_LEN
BMA2x2_INTR2_PAD_OUTPUT_TYPE_MSK
BMA2x2_INTR2_PAD_OUTPUT_TYPE_REG
Referenced by bma2x2_get_intr_output_type, bma2x2_set_intr_output_type.
BMA2x2_LATCH_INTR_POS
BMA2x2_LATCH_INTR_LEN
BMA2x2_LATCH_INTR_MSK
BMA2x2_LATCH_INTR_REG
Referenced by bma2x2_get_latch_intr, bma2x2_set_latch_intr.
BMA2x2_RESET_INTR_POS
BMA2x2_RESET_INTR_LEN
BMA2x2_RESET_INTR_MSK
BMA2x2_RESET_INTR_REG
Referenced by bma2x2_rst_intr.
BMA2x2_LOW_G_HYST_POS
BMA2x2_LOW_G_HYST_LEN
BMA2x2_LOW_G_HYST_MSK
BMA2x2_LOW_G_HYST_REG
Referenced by bma2x2_get_low_high_g_hyst, bma2x2_set_low_high_g_hyst.
BMA2x2_LOW_G_INTR_MODE_POS
BMA2x2_LOW_G_INTR_MODE_LEN
BMA2x2_LOW_G_INTR_MODE_MSK
BMA2x2_LOW_G_INTR_MODE_REG
Referenced by bma2x2_get_low_g_mode, bma2x2_set_low_g_mode.
BMA2x2_HIGH_G_HYST_POS
BMA2x2_HIGH_G_HYST_LEN
BMA2x2_HIGH_G_HYST_MSK
BMA2x2_HIGH_G_HYST_REG
Referenced by bma2x2_get_low_high_g_hyst, bma2x2_set_low_high_g_hyst.
BMA2x2_SLOPE_DURN_POS
BMA2x2_SLOPE_DURN_LEN
BMA2x2_SLOPE_DURN_MSK
BMA2x2_SLOPE_DURN_REG
Referenced by bma2x2_get_durn, bma2x2_set_durn.
BMA2x2_SLOW_NO_MOTION_DURN_POS
BMA2x2_SLOW_NO_MOTION_DURN_LEN
BMA2x2_SLOW_NO_MOTION_DURN_MSK
BMA2x2_SLOW_NO_MOTION_DURN_REG
Referenced by bma2x2_get_durn, bma2x2_set_durn.
BMA2x2_TAP_DURN_POS
BMA2x2_TAP_DURN_LEN
BMA2x2_TAP_DURN_MSK
BMA2x2_TAP_DURN_REG
Referenced by bma2x2_get_tap_durn, bma2x2_set_tap_durn.
BMA2x2_TAP_SHOCK_DURN_POS
BMA2x2_TAP_SHOCK_DURN_LEN
BMA2x2_TAP_SHOCK_DURN_MSK
BMA2x2_TAP_SHOCK_DURN_REG
Referenced by bma2x2_get_tap_shock, bma2x2_set_tap_shock.
BMA2x2_ADV_TAP_INTR_POS
BMA2x2_ADV_TAP_INTR_LEN
BMA2x2_ADV_TAP_INTR_MSK
BMA2x2_ADV_TAP_INTR_REG
BMA2x2_TAP_QUIET_DURN_POS
BMA2x2_TAP_QUIET_DURN_LEN
BMA2x2_TAP_QUIET_DURN_MSK
BMA2x2_TAP_QUIET_DURN_REG
Referenced by bma2x2_get_tap_quiet, bma2x2_set_tap_quiet.
BMA2x2_TAP_THRES_POS
BMA2x2_TAP_THRES_LEN
BMA2x2_TAP_THRES_MSK
BMA2x2_TAP_THRES_REG
Referenced by bma2x2_get_tap_thres, bma2x2_set_tap_thres.
BMA2x2_TAP_SAMPLES_POS
BMA2x2_TAP_SAMPLES_LEN
BMA2x2_TAP_SAMPLES_MSK
BMA2x2_TAP_SAMPLES_REG
Referenced by bma2x2_get_tap_sample, bma2x2_set_tap_sample.
BMA2x2_ORIENT_MODE_POS
BMA2x2_ORIENT_MODE_LEN
BMA2x2_ORIENT_MODE_MSK
BMA2x2_ORIENT_MODE_REG
Referenced by bma2x2_get_orient_mode, bma2x2_set_orient_mode.
BMA2x2_ORIENT_BLOCK_POS
BMA2x2_ORIENT_BLOCK_LEN
BMA2x2_ORIENT_BLOCK_MSK
BMA2x2_ORIENT_BLOCK_REG
Referenced by bma2x2_get_orient_block, bma2x2_set_orient_block.
BMA2x2_ORIENT_HYST_POS
BMA2x2_ORIENT_HYST_LEN
BMA2x2_ORIENT_HYST_MSK
BMA2x2_ORIENT_HYST_REG
Referenced by bma2x2_get_orient_hyst, bma2x2_set_orient_hyst.
BMA2x2_ORIENT_UD_ENABLE_POS
BMA2x2_ORIENT_UD_ENABLE_LEN
BMA2x2_ORIENT_UD_ENABLE_MSK
BMA2x2_ORIENT_UD_ENABLE_REG
Referenced by bma2x2_get_orient_enable, bma2x2_set_orient_enable.
BMA2x2_THETA_BLOCK_POS
BMA2x2_THETA_BLOCK_LEN
BMA2x2_THETA_BLOCK_MSK
BMA2x2_THETA_BLOCK_REG
Referenced by bma2x2_get_theta, bma2x2_set_theta.
BMA2x2_THETA_FLAT_POS
BMA2x2_THETA_FLAT_LEN
BMA2x2_THETA_FLAT_MSK
BMA2x2_THETA_FLAT_REG
Referenced by bma2x2_get_theta, bma2x2_set_theta.
BMA2x2_FLAT_HOLD_TIME_POS
BMA2x2_FLAT_HOLD_TIME_LEN
BMA2x2_FLAT_HOLD_TIME_MSK
BMA2x2_FLAT_HOLD_TIME_REG
Referenced by bma2x2_get_flat_hold_time, bma2x2_set_flat_hold_time.
BMA2x2_FLAT_HYST_POS
BMA2x2_FLAT_HYST_LEN
BMA2x2_FLAT_HYST_MSK
BMA2x2_FLAT_HYST_REG
Referenced by bma2x2_get_flat_hyst, bma2x2_set_flat_hyst.
BMA2x2_FIFO_WML_TRIG_RETAIN_POS
BMA2x2_FIFO_WML_TRIG_RETAIN_LEN
BMA2x2_FIFO_WML_TRIG_RETAIN_MSK
BMA2x2_FIFO_WML_TRIG_RETAIN_REG
Referenced by bma2x2_get_fifo_wml_trig, bma2x2_set_fifo_wml_trig.
BMA2x2_ENABLE_SELFTEST_POS
BMA2x2_ENABLE_SELFTEST_LEN
BMA2x2_ENABLE_SELFTEST_MSK
BMA2x2_ENABLE_SELFTEST_REG
Referenced by bma2x2_get_selftest_axis, bma2x2_set_selftest_axis.
BMA2x2_NEG_SELFTEST_POS
BMA2x2_NEG_SELFTEST_LEN
BMA2x2_NEG_SELFTEST_MSK
BMA2x2_NEG_SELFTEST_REG
Referenced by bma2x2_get_selftest_sign, bma2x2_set_selftest_sign.
BMA2x2_UNLOCK_EE_PROG_MODE_POS
BMA2x2_UNLOCK_EE_PROG_MODE_LEN
BMA2x2_UNLOCK_EE_PROG_MODE_MSK
BMA2x2_UNLOCK_EE_PROG_MODE_REG
Referenced by bma2x2_get_nvmprog_mode, bma2x2_set_nvmprog_mode.
BMA2x2_START_EE_PROG_TRIG_POS
BMA2x2_START_EE_PROG_TRIG_LEN
BMA2x2_START_EE_PROG_TRIG_MSK
BMA2x2_START_EE_PROG_TRIG_REG
Referenced by bma2x2_set_nvprog_trig.
BMA2x2_EE_PROG_READY_POS
BMA2x2_EE_PROG_READY_LEN
BMA2x2_EE_PROG_READY_MSK
BMA2x2_EE_PROG_READY_REG
Referenced by bma2x2_get_nvmprog_ready.
BMA2x2_UPDATE_IMAGE_POS
BMA2x2_UPDATE_IMAGE_LEN
BMA2x2_UPDATE_IMAGE_MSK
BMA2x2_UPDATE_IMAGE_REG
Referenced by bma2x2_update_image.
BMA2x2_EE_REMAIN_POS
BMA2x2_EE_REMAIN_LEN
BMA2x2_EE_REMAIN_MSK
BMA2x2_EE_REMAIN_REG
Referenced by bma2x2_get_nvmprog_remain.
BMA2x2_ENABLE_SPI_MODE_3_POS
BMA2x2_ENABLE_SPI_MODE_3_LEN
BMA2x2_ENABLE_SPI_MODE_3_MSK
BMA2x2_ENABLE_SPI_MODE_3_REG
Referenced by bma2x2_get_spi3, bma2x2_set_spi3.
BMA2x2_I2C_WDT_PERIOD_POS
BMA2x2_I2C_WDT_PERIOD_LEN
BMA2x2_I2C_WDT_PERIOD_MSK
BMA2x2_I2C_WDT_PERIOD_REG
Referenced by bma2x2_get_i2c_wdt, bma2x2_set_i2c_wdt.
BMA2x2_ENABLE_I2C_WDT_POS
BMA2x2_ENABLE_I2C_WDT_LEN
BMA2x2_ENABLE_I2C_WDT_MSK
BMA2x2_ENABLE_I2C_WDT_REG
Referenced by bma2x2_get_i2c_wdt, bma2x2_set_i2c_wdt.
BMA2x2_UNLOCK_EE_WRITE_TRIM_POS
BMA2x2_UNLOCK_EE_WRITE_TRIM_LEN
BMA2x2_UNLOCK_EE_WRITE_TRIM_MSK
BMA2x2_UNLOCK_EE_WRITE_TRIM_REG
BMA2x2_ENABLE_SLOW_COMP_X_POS
BMA2x2_ENABLE_SLOW_COMP_X_LEN
BMA2x2_ENABLE_SLOW_COMP_X_MSK
BMA2x2_ENABLE_SLOW_COMP_X_REG
Referenced by bma2x2_get_slow_comp, bma2x2_set_slow_comp.
BMA2x2_ENABLE_SLOW_COMP_Y_POS
BMA2x2_ENABLE_SLOW_COMP_Y_LEN
BMA2x2_ENABLE_SLOW_COMP_Y_MSK
BMA2x2_ENABLE_SLOW_COMP_Y_REG
Referenced by bma2x2_get_slow_comp, bma2x2_set_slow_comp.
BMA2x2_ENABLE_SLOW_COMP_Z_POS
BMA2x2_ENABLE_SLOW_COMP_Z_LEN
BMA2x2_ENABLE_SLOW_COMP_Z_MSK
BMA2x2_ENABLE_SLOW_COMP_Z_REG
Referenced by bma2x2_get_slow_comp, bma2x2_set_slow_comp.
BMA2x2_FAST_CAL_RDY_STAT_POS
BMA2x2_FAST_CAL_RDY_STAT_LEN
BMA2x2_FAST_CAL_RDY_STAT_MSK
BMA2x2_FAST_CAL_RDY_STAT_REG
Referenced by bma2x2_get_cal_rdy.
BMA2x2_CAL_TRIGGER_POS
BMA2x2_CAL_TRIGGER_LEN
BMA2x2_CAL_TRIGGER_MSK
BMA2x2_CAL_TRIGGER_REG
Referenced by bma2x2_set_cal_trigger.
BMA2x2_RST_OFFSET_POS
BMA2x2_RST_OFFSET_LEN
BMA2x2_RST_OFFSET_MSK
BMA2x2_RST_OFFSET_REG
Referenced by bma2x2_set_offset_rst.
BMA2x2_COMP_CUTOFF_POS
BMA2x2_COMP_CUTOFF_LEN
BMA2x2_COMP_CUTOFF_MSK
BMA2x2_COMP_CUTOFF_REG
Referenced by bma2x2_get_offset_target, bma2x2_set_offset_target.
BMA2x2_COMP_TARGET_OFFSET_X_POS
BMA2x2_COMP_TARGET_OFFSET_X_LEN
BMA2x2_COMP_TARGET_OFFSET_X_MSK
BMA2x2_COMP_TARGET_OFFSET_X_REG
Referenced by bma2x2_get_offset_target, bma2x2_set_offset_target.
BMA2x2_COMP_TARGET_OFFSET_Y_POS
BMA2x2_COMP_TARGET_OFFSET_Y_LEN
BMA2x2_COMP_TARGET_OFFSET_Y_MSK
BMA2x2_COMP_TARGET_OFFSET_Y_REG
Referenced by bma2x2_get_offset_target, bma2x2_set_offset_target.
BMA2x2_COMP_TARGET_OFFSET_Z_POS
BMA2x2_COMP_TARGET_OFFSET_Z_LEN
BMA2x2_COMP_TARGET_OFFSET_Z_MSK
BMA2x2_COMP_TARGET_OFFSET_Z_REG
Referenced by bma2x2_get_offset_target, bma2x2_set_offset_target.
BMA2x2_FIFO_DATA_SELECT_POS
BMA2x2_FIFO_DATA_SELECT_LEN
BMA2x2_FIFO_DATA_SELECT_MSK
BMA2x2_FIFO_DATA_SELECT_REG
Referenced by bma2x2_get_fifo_data_select, bma2x2_set_fifo_data_select.
BMA2x2_FIFO_MODE_POS
BMA2x2_FIFO_MODE_LEN
BMA2x2_FIFO_MODE_MSK
BMA2x2_FIFO_MODE_REG
Referenced by bma2x2_init, bma2x2_set_power_mode, bma2x2_get_fifo_mode, bma2x2_set_fifo_mode, bma2x2_set_fifo_data_select.
BMA2x2_GET_BITSLICE
Referenced by bma2x2_read_accel_eight_resolution_x, bma2x2_read_accel_eight_resolution_y, bma2x2_read_accel_eight_resolution_z, bma2x2_read_accel_eight_resolution_xyz, bma2x2_get_fifo_frame_count, bma2x2_get_fifo_overrun, bma2x2_get_range, bma2x2_get_bw, bma2x2_get_sleep_durn, bma2x2_get_sleep_timer_mode, bma2x2_get_high_bw, bma2x2_get_shadow_dis, bma2x2_get_intr_enable, bma2x2_get_intr_fifo_full, bma2x2_get_intr_fifo_wm, bma2x2_get_slow_no_motion, bma2x2_get_intr_low_g, bma2x2_get_intr_high_g, bma2x2_get_intr_slope, bma2x2_get_intr_slow_no_motion, bma2x2_get_intr_double_tap, bma2x2_get_intr_single_tap, bma2x2_get_intr_orient, bma2x2_get_intr_flat, bma2x2_get_new_data, bma2x2_get_intr1_fifo_wm, bma2x2_get_intr2_fifo_wm, bma2x2_get_intr1_fifo_full, bma2x2_get_intr2_fifo_full, bma2x2_get_source, bma2x2_get_intr_output_type, bma2x2_get_intr_level, bma2x2_get_latch_intr, bma2x2_get_durn, bma2x2_get_low_high_g_hyst, bma2x2_get_low_g_mode, bma2x2_get_tap_durn, bma2x2_get_tap_shock, bma2x2_get_tap_quiet, bma2x2_get_tap_thres, bma2x2_get_tap_sample, bma2x2_get_orient_mode, bma2x2_get_orient_block, bma2x2_get_orient_hyst, bma2x2_get_theta, bma2x2_get_orient_enable, bma2x2_get_flat_hyst, bma2x2_get_flat_hold_time, bma2x2_get_fifo_wml_trig, bma2x2_get_selftest_axis, bma2x2_get_selftest_sign, bma2x2_get_nvmprog_mode, bma2x2_get_nvmprog_ready, bma2x2_get_nvmprog_remain, bma2x2_get_spi3, bma2x2_get_i2c_wdt, bma2x2_get_slow_comp, bma2x2_get_cal_rdy, bma2x2_get_offset_target, bma2x2_get_fifo_mode, bma2x2_get_fifo_data_select, bma2x2_read_accel_eight_resolution_xyzt.
BMA2x2_SET_BITSLICE
Referenced by bma2x2_set_range, bma2x2_set_bw, bma2x2_set_power_mode, bma2x2_set_sleep_durn, bma2x2_set_sleep_timer_mode, bma2x2_set_high_bw, bma2x2_set_shadow_dis, bma2x2_update_image, bma2x2_set_intr_enable, bma2x2_set_intr_fifo_full, bma2x2_set_intr_fifo_wm, bma2x2_set_slow_no_motion, bma2x2_set_intr_low_g, bma2x2_set_intr_high_g, bma2x2_set_intr_slope, bma2x2_set_intr_slow_no_motion, bma2x2_set_intr_double_tap, bma2x2_set_intr_single_tap, bma2x2_set_intr_orient, bma2x2_set_intr_flat, bma2x2_set_new_data, bma2x2_set_intr1_fifo_wm, bma2x2_set_intr2_fifo_wm, bma2x2_set_intr1_fifo_full, bma2x2_set_intr2_fifo_full, bma2x2_set_source, bma2x2_set_intr_output_type, bma2x2_set_intr_level, bma2x2_rst_intr, bma2x2_set_latch_intr, bma2x2_set_durn, bma2x2_set_low_high_g_hyst, bma2x2_set_low_g_mode, bma2x2_set_tap_durn, bma2x2_set_tap_shock, bma2x2_set_tap_quiet, bma2x2_set_tap_thres, bma2x2_set_tap_sample, bma2x2_set_orient_mode, bma2x2_set_orient_block, bma2x2_set_orient_hyst, bma2x2_set_theta, bma2x2_set_orient_enable, bma2x2_set_flat_hyst, bma2x2_set_flat_hold_time, bma2x2_set_fifo_wml_trig, bma2x2_set_selftest_axis, bma2x2_set_selftest_sign, bma2x2_set_nvmprog_mode, bma2x2_set_nvprog_trig, bma2x2_set_spi3, bma2x2_set_i2c_wdt, bma2x2_set_slow_comp, bma2x2_set_cal_trigger, bma2x2_set_offset_rst, bma2x2_set_offset_target, bma2x2_set_fifo_mode, bma2x2_set_fifo_data_select.
BMA2x2_14_BIT_SHIFT
It refers 14bit accel resolution
Referenced by bma2x2_read_accel_y, bma2x2_read_accel_z, bma2x2_read_accel_xyz, bma2x2_read_accel_xyzt.
BMA2x2_10_BIT_SHIFT
It refers 10bit accel resolution
Referenced by bma2x2_read_accel_y, bma2x2_read_accel_z, bma2x2_read_accel_xyz, bma2x2_read_accel_xyzt.
BMA2x2_12_BIT_SHIFT
It refers 12bit accel resolution
Referenced by bma2x2_read_accel_y, bma2x2_read_accel_z, bma2x2_read_accel_xyz, bma2x2_read_accel_xyzt.
BANDWIDTH_DEFINE
Chip id set for accel bandwidth define
Referenced by bma2x2_set_bw.
INTR_ENABLE
Enable selection for bit
Referenced by configureNewDataInterrupt.
INTR_DISABLE
Disable selection for bit
OPEN_DRAIN
It refers open drain selection
PUSS_PULL
It refers push pull selection
ACTIVE_LOW
It refers active low selection
ACTIVE_HIGH
It refers active high selection
BMA2x2_STAT1
It refers Status interrupt1
BMA2x2_STAT2
It refers Status interrupt2
BMA2x2_STAT3
It refers Status interrupt3
BMA2x2_STAT4
It refers Status interrupt4
BMA2x2_STAT5
It refers Status interrupt5
BMA2x2_RANGE_2G
sets range to +/- 2G mode
Referenced by bma2x2_set_range.
BMA2x2_RANGE_4G
sets range to +/- 4G mode
Referenced by bma2x2_set_range.
BMA2x2_RANGE_8G
sets range to +/- 8G mode
Referenced by bma2x2_set_range.
BMA2x2_RANGE_16G
sets range to +/- 16G mode
Referenced by bma2x2_set_range.
BMA2x2_BW_7_81HZ
sets bandwidth to LowPass 7.81HZ
Referenced by bma2x2_set_bw.
BMA2x2_BW_15_63HZ
sets bandwidth to LowPass 15.63HZ
Referenced by bma2x2_set_bw.
BMA2x2_BW_31_25HZ
sets bandwidth to LowPass 31.25HZ
Referenced by bma2x2_set_bw.
BMA2x2_BW_62_50HZ
sets bandwidth to LowPass 62.50HZ
Referenced by bma2x2_set_bw.
BMA2x2_BW_125HZ
sets bandwidth to LowPass 125HZ
Referenced by bma2x2_set_bw.
BMA2x2_BW_250HZ
sets bandwidth to LowPass 250HZ
Referenced by bma2x2_set_bw.
BMA2x2_BW_500HZ
sets bandwidth to LowPass 500HZ
Referenced by bma2x2_set_bw, Bma280Utils_initialize.
BMA2x2_BW_1000HZ
sets bandwidth to LowPass 1000HZ
Referenced by bma2x2_set_bw.
BMA2x2_SLEEP_DURN_0_5MS
Referenced by bma2x2_set_sleep_durn.
BMA2x2_SLEEP_DURN_1MS
Referenced by bma2x2_set_sleep_durn.
BMA2x2_SLEEP_DURN_2MS
Referenced by bma2x2_set_sleep_durn.
BMA2x2_SLEEP_DURN_4MS
Referenced by bma2x2_set_sleep_durn.
BMA2x2_SLEEP_DURN_6MS
Referenced by bma2x2_set_sleep_durn.
BMA2x2_SLEEP_DURN_10MS
Referenced by bma2x2_set_sleep_durn.
BMA2x2_SLEEP_DURN_25MS
Referenced by bma2x2_set_sleep_durn.
BMA2x2_SLEEP_DURN_50MS
Referenced by bma2x2_set_sleep_durn.
BMA2x2_SLEEP_DURN_100MS
Referenced by bma2x2_set_sleep_durn.
BMA2x2_SLEEP_DURN_500MS
Referenced by bma2x2_set_sleep_durn.
BMA2x2_SLEEP_DURN_1S
Referenced by bma2x2_set_sleep_durn.
BMA2x2_LATCH_DURN_NON_LATCH
Referenced by bma2x2_set_latch_intr.
BMA2x2_LATCH_DURN_250MS
Referenced by bma2x2_set_latch_intr.
BMA2x2_LATCH_DURN_500MS
Referenced by bma2x2_set_latch_intr.
BMA2x2_LATCH_DURN_1S
Referenced by bma2x2_set_latch_intr.
BMA2x2_LATCH_DURN_2S
Referenced by bma2x2_set_latch_intr.
BMA2x2_LATCH_DURN_4S
Referenced by bma2x2_set_latch_intr.
BMA2x2_LATCH_DURN_8S
Referenced by bma2x2_set_latch_intr.
BMA2x2_LATCH_DURN_LATCH
Referenced by bma2x2_set_latch_intr.
BMA2x2_LATCH_DURN_NON_LATCH1
Referenced by bma2x2_set_latch_intr.
BMA2x2_LATCH_DURN_250US
Referenced by bma2x2_set_latch_intr.
BMA2x2_LATCH_DURN_500US
Referenced by bma2x2_set_latch_intr.
BMA2x2_LATCH_DURN_1MS
Referenced by bma2x2_set_latch_intr.
BMA2x2_LATCH_DURN_12_5MS
Referenced by bma2x2_set_latch_intr.
BMA2x2_LATCH_DURN_25MS
Referenced by bma2x2_set_latch_intr.
BMA2x2_LATCH_DURN_50MS
Referenced by bma2x2_set_latch_intr.
BMA2x2_LATCH_DURN_LATCH1
Referenced by bma2x2_set_latch_intr.
BMA2x2_MODE_NORMAL
Referenced by bma2x2_get_power_mode, bma2x2_set_mode_value.
BMA2x2_MODE_LOWPOWER1
Referenced by bma2x2_get_power_mode, bma2x2_set_mode_value.
BMA2x2_MODE_SUSPEND
Referenced by bma2x2_get_power_mode, bma2x2_set_mode_value.
BMA2x2_MODE_DEEP_SUSPEND
Referenced by bma2x2_get_power_mode, bma2x2_set_mode_value.
BMA2x2_MODE_LOWPOWER2
Referenced by bma2x2_get_power_mode, bma2x2_set_mode_value.
BMA2x2_MODE_STANDBY
Referenced by bma2x2_get_power_mode, bma2x2_set_mode_value.
BMA2x2_X_AXIS
It refers BMA2x2 X-axis
Referenced by bma2x2_get_offset, bma2x2_set_offset.
BMA2x2_Y_AXIS
It refers BMA2x2 Y-axis
Referenced by bma2x2_get_offset, bma2x2_set_offset.
BMA2x2_Z_AXIS
It refers BMA2x2 Z-axis
Referenced by bma2x2_get_offset, bma2x2_set_offset.
BMA2x2_LOW_G_INTR
enable/disable low-g interrupt
Referenced by bma2x2_get_intr_enable, bma2x2_set_intr_enable.
BMA2x2_HIGH_G_X_INTR
enable/disable high_g X interrupt
Referenced by bma2x2_get_intr_enable, bma2x2_set_intr_enable.
BMA2x2_HIGH_G_Y_INTR
enable/disable high_g Y interrupt
Referenced by bma2x2_get_intr_enable, bma2x2_set_intr_enable.
BMA2x2_HIGH_G_Z_INTR
enable/disable high_g Z interrupt
Referenced by bma2x2_get_intr_enable, bma2x2_set_intr_enable.
BMA2x2_DATA_ENABLE
enable/disable data interrupt
Referenced by bma2x2_get_intr_enable, bma2x2_set_intr_enable, configureNewDataInterrupt.
BMA2x2_SLOPE_X_INTR
enable/disable slope X interrupt
Referenced by bma2x2_get_intr_enable, bma2x2_set_intr_enable, configureSlopeInterrupt.
BMA2x2_SLOPE_Y_INTR
enable/disable slope X interrupt
Referenced by bma2x2_get_intr_enable, bma2x2_set_intr_enable, configureSlopeInterrupt.
BMA2x2_SLOPE_Z_INTR
enable/disable slope X interrupt
Referenced by bma2x2_get_intr_enable, bma2x2_set_intr_enable, configureSlopeInterrupt.
BMA2x2_SINGLE_TAP_INTR
enable/disable single tap interrupt
Referenced by bma2x2_get_intr_enable, bma2x2_set_intr_enable.
BMA2x2_DOUBLE_TAP_INTR
enable/disable double tap interrupt
Referenced by bma2x2_get_intr_enable, bma2x2_set_intr_enable.
BMA2x2_ORIENT_INTR
enable/disable orient interrupt
Referenced by bma2x2_get_intr_enable, bma2x2_set_intr_enable.
BMA2x2_FLAT_INTR
enable/disable flat interrupt
Referenced by bma2x2_get_intr_enable, bma2x2_set_intr_enable.
BMA2x2_FIFO_FULL_INTR
enable/disable fifo full interrupt
BMA2x2_FIFO_WM_INTR
enable/disable fifo water mark interrupt
BMA2x2_INTR1_LOW_G
disable low-g interrupt
Referenced by bma2x2_get_intr_low_g, bma2x2_set_intr_low_g.
BMA2x2_INTR2_LOW_G
enable low-g interrupt
Referenced by bma2x2_get_intr_low_g, bma2x2_set_intr_low_g.
BMA2x2_INTR1_HIGH_G
disable high-g interrupt
Referenced by bma2x2_get_intr_high_g, bma2x2_set_intr_high_g.
BMA2x2_INTR2_HIGH_G
enable high-g interrupt
Referenced by bma2x2_get_intr_high_g, bma2x2_set_intr_high_g.
BMA2x2_INTR1_SLOPE
disable slope interrupt
Referenced by bma2x2_get_intr_slope, bma2x2_set_intr_slope.
BMA2x2_INTR2_SLOPE
enable slope interrupt
Referenced by bma2x2_get_intr_slope, bma2x2_set_intr_slope.
BMA2x2_INTR1_SLOW_NO_MOTION
disable slow no motion interrupt
Referenced by bma2x2_get_intr_slow_no_motion, bma2x2_set_intr_slow_no_motion.
BMA2x2_INTR2_SLOW_NO_MOTION
enable slow no motion interrupt
Referenced by bma2x2_get_intr_slow_no_motion, bma2x2_set_intr_slow_no_motion.
BMA2x2_INTR1_DOUBLE_TAP
disable double tap interrupt
Referenced by bma2x2_get_intr_double_tap, bma2x2_set_intr_double_tap.
BMA2x2_INTR2_DOUBLE_TAP
enable double tap interrupt
Referenced by bma2x2_get_intr_double_tap, bma2x2_set_intr_double_tap.
BMA2x2_INTR1_SINGLE_TAP
disable single tap interrupt
Referenced by bma2x2_get_intr_single_tap, bma2x2_set_intr_single_tap.
BMA2x2_INTR2_SINGLE_TAP
enable single tap interrupt
Referenced by bma2x2_get_intr_single_tap, bma2x2_set_intr_single_tap.
BMA2x2_INTR1_ORIENT
disable orient interrupt
Referenced by bma2x2_get_intr_orient, bma2x2_set_intr_orient.
BMA2x2_INTR2_ORIENT
enable orient interrupt
Referenced by bma2x2_get_intr_orient, bma2x2_set_intr_orient.
BMA2x2_INTR1_FLAT
disable flat interrupt
Referenced by bma2x2_get_intr_flat, bma2x2_set_intr_flat.
BMA2x2_INTR2_FLAT
enable flat interrupt
Referenced by bma2x2_get_intr_flat, bma2x2_set_intr_flat.
BMA2x2_INTR1_NEWDATA
disable data interrupt
Referenced by bma2x2_get_new_data, bma2x2_set_new_data.
BMA2x2_INTR2_NEWDATA
enable data interrupt
Referenced by bma2x2_get_new_data, bma2x2_set_new_data.
BMA2x2_INTR1_FIFO_WM
disable fifo watermark interrupt
BMA2x2_INTR2_FIFO_WM
enable fifo watermark interrupt
BMA2x2_INTR1_FIFO_FULL
disable fifo full interrupt
BMA2x2_INTR2_FIFO_FULL
enable fifo full interrupt
BMA2x2_SOURCE_LOW_G
Referenced by bma2x2_get_source, bma2x2_set_source.
BMA2x2_SOURCE_HIGH_G
Referenced by bma2x2_get_source, bma2x2_set_source.
BMA2x2_SOURCE_SLOPE
Referenced by bma2x2_get_source, bma2x2_set_source.
BMA2x2_SOURCE_SLOW_NO_MOTION
Referenced by bma2x2_get_source, bma2x2_set_source.
BMA2x2_SOURCE_TAP
Referenced by bma2x2_get_source, bma2x2_set_source.
BMA2x2_SOURCE_DATA
Referenced by bma2x2_get_source, bma2x2_set_source.
BMA2x2_INTR1_OUTPUT
Referenced by bma2x2_get_intr_output_type, bma2x2_set_intr_output_type.
BMA2x2_INTR2_OUTPUT
Referenced by bma2x2_get_intr_output_type, bma2x2_set_intr_output_type.
BMA2x2_INTR1_LEVEL
Referenced by bma2x2_get_intr_level, bma2x2_set_intr_level.
BMA2x2_INTR2_LEVEL
Referenced by bma2x2_get_intr_level, bma2x2_set_intr_level.
BMA2x2_LOW_DURN
Referenced by bma2x2_get_durn, bma2x2_set_durn.
BMA2x2_HIGH_DURN
Referenced by bma2x2_get_durn, bma2x2_set_durn.
BMA2x2_SLOPE_DURN
Referenced by bma2x2_get_durn, bma2x2_set_durn, configureSlopeInterrupt.
BMA2x2_SLOW_NO_MOTION_DURN
Referenced by bma2x2_get_durn, bma2x2_set_durn.
BMA2x2_LOW_THRES
Referenced by bma2x2_get_thres, bma2x2_set_thres.
BMA2x2_HIGH_THRES
Referenced by bma2x2_get_thres, bma2x2_set_thres.
BMA2x2_SLOPE_THRES
Referenced by bma2x2_get_thres, bma2x2_set_thres, configureSlopeInterrupt.
BMA2x2_SLOW_NO_MOTION_THRES
Referenced by bma2x2_get_thres, bma2x2_set_thres.
BMA2x2_LOW_G_HYST
Referenced by bma2x2_get_low_high_g_hyst, bma2x2_set_low_high_g_hyst.
BMA2x2_HIGH_G_HYST
Referenced by bma2x2_get_low_high_g_hyst, bma2x2_set_low_high_g_hyst.
BMA2x2_ORIENT_THETA
Referenced by bma2x2_get_theta, bma2x2_set_theta.
BMA2x2_FLAT_THETA
Referenced by bma2x2_get_theta, bma2x2_set_theta.
BMA2x2_I2C_SELECT
Referenced by bma2x2_get_i2c_wdt, bma2x2_set_i2c_wdt.
BMA2x2_I2C_ENABLE
Referenced by bma2x2_get_i2c_wdt, bma2x2_set_i2c_wdt.
BMA2x2_SLOW_COMP_X
Referenced by bma2x2_get_slow_comp, bma2x2_set_slow_comp.
BMA2x2_SLOW_COMP_Y
Referenced by bma2x2_get_slow_comp, bma2x2_set_slow_comp.
BMA2x2_SLOW_COMP_Z
Referenced by bma2x2_get_slow_comp, bma2x2_set_slow_comp.
BMA2x2_CUT_OFF
Referenced by bma2x2_get_offset_target, bma2x2_set_offset_target.
BMA2x2_OFFSET_TRIGGER_X
Referenced by bma2x2_get_offset_target, bma2x2_set_offset_target.
BMA2x2_OFFSET_TRIGGER_Y
Referenced by bma2x2_get_offset_target, bma2x2_set_offset_target.
BMA2x2_OFFSET_TRIGGER_Z
Referenced by bma2x2_get_offset_target, bma2x2_set_offset_target.
BMA2x2_GP0
BMA2x2_GP1
BMA2x2_SLOW_NO_MOTION_ENABLE_X
Referenced by bma2x2_get_slow_no_motion, bma2x2_set_slow_no_motion.
BMA2x2_SLOW_NO_MOTION_ENABLE_Y
Referenced by bma2x2_get_slow_no_motion, bma2x2_set_slow_no_motion.
BMA2x2_SLOW_NO_MOTION_ENABLE_Z
Referenced by bma2x2_get_slow_no_motion, bma2x2_set_slow_no_motion.
BMA2x2_SLOW_NO_MOTION_ENABLE_SELECT
Referenced by bma2x2_get_slow_no_motion, bma2x2_set_slow_no_motion.
BMA2x2_WAKE_UP_DURN_20MS
BMA2x2_WAKE_UP_DURN_80MS
BMA2x2_WAKE_UP_DURN_320MS
BMA2x2_WAKE_UP_DURN_2560MS
BMA2x2_SELFTEST0_ON
BMA2x2_SELFTEST1_ON
BMA2x2_EE_W_OFF
BMA2x2_EE_W_ON
BMA2x2_RESOLUTION_12_BIT
BMA2x2_RESOLUTION_10_BIT
BMA2x2_RESOLUTION_14_BIT
BMA2x2
BMA280
BMA222E
BMA250E
LOW_G_SINGLE_AXIS_MODE
LOW_G_SUMMING_MODE
TAP_DURN_50_MS
TAP_DURN_100_MS
TAP_DURN_150_MS
TAP_DURN_200_MS
TAP_DURN_250_MS
TAP_DURN_375_MS
TAP_DURN_500_MS
TAP_DURN_700_MS
TAP_SHOCK_50_MS
TAP_SHOCK_75_MS
TAP_QUIET_30_MS
TAP_QUIET_20_MS
BMA2x2_ACCEL_DATA_SIZE
Referenced by bma2x2_read_accel_x, bma2x2_read_accel_y, bma2x2_read_accel_z.
BMA2x2_ACCEL_XYZ_DATA_SIZE
Referenced by bma2x2_read_accel_xyz.
BMA2x2_ACCEL_XYZ_TEMP_DATA_SIZE
Referenced by bma2x2_read_accel_xyzt.
BMA2x2_SENSOR_DATA_ACCEL_LSB
Referenced by bma2x2_read_accel_x, bma2x2_read_accel_y, bma2x2_read_accel_z.
BMA2x2_SENSOR_DATA_ACCEL_MSB
Referenced by bma2x2_read_accel_x, bma2x2_read_accel_y, bma2x2_read_accel_z.
BMA2x2_SENSOR_DATA_XYZ_X_LSB
Referenced by bma2x2_read_accel_xyz, bma2x2_read_accel_xyzt.
BMA2x2_SENSOR_DATA_XYZ_X_MSB
Referenced by bma2x2_read_accel_xyz, bma2x2_read_accel_xyzt.
BMA2x2_SENSOR_DATA_XYZ_Y_LSB
Referenced by bma2x2_read_accel_xyz, bma2x2_read_accel_xyzt.
BMA2x2_SENSOR_DATA_XYZ_Y_MSB
Referenced by bma2x2_read_accel_xyz, bma2x2_read_accel_xyzt.
BMA2x2_SENSOR_DATA_XYZ_Z_LSB
Referenced by bma2x2_read_accel_xyz, bma2x2_read_accel_xyzt.
BMA2x2_SENSOR_DATA_XYZ_Z_MSB
Referenced by bma2x2_read_accel_xyz, bma2x2_read_accel_xyzt.
BMA2x2_SENSOR_DATA_TEMP
Referenced by bma2x2_read_accel_xyzt.
BMA2x2_RESOLUTION_12_MASK
Referenced by bma2x2_read_accel_x.
BMA2x2_RESOLUTION_10_MASK
Referenced by bma2x2_read_accel_x.
BMA2x2_RESOLUTION_14_MASK
Referenced by bma2x2_read_accel_x.
BMA2x2_POWER_MODE_HEX_E_ZERO_MASK
Referenced by bma2x2_get_power_mode.
BMA2x2_POWER_MODE_HEX_4_ZERO_MASK
Referenced by bma2x2_get_power_mode.
BMA2x2_POWER_MODE_HEX_ZERO_ZERO_MASK
Referenced by bma2x2_get_power_mode, bma2x2_set_mode_value.
BMA2x2_POWER_MODE_HEX_ZERO_ONE_MASK
Referenced by bma2x2_get_power_mode, bma2x2_set_mode_value.
BMA2x2_POWER_MODE_HEX_ZERO_TWO_MASK
Referenced by bma2x2_get_power_mode, bma2x2_set_mode_value.
BMA2x2_POWER_MODE_HEX_ZERO_FOUR_MASK
Referenced by bma2x2_get_power_mode, bma2x2_set_mode_value.
BMA2x2_POWER_MODE_HEX_ZERO_SIX_MASK
Referenced by bma2x2_get_power_mode.
BMA2x2_LOW_THRES_IN_G
convert g-values to 8-bit value
Macro to convert floating point low-g-thresholds in G to 8-bit register values. Example: BMA2x2_LOW_TH_IN_G( 0.3, 2.0) generates the register value for 0.3G threshold in 2G mode.
BMA2x2_HIGH_THRES_IN_G
convert g-values to 8-bit value
Macro to convert floating point high-g-thresholds in G to 8-bit register values. Example: BMA2x2_HIGH_TH_IN_G( 1.4, 2.0) generates the register value for 1.4G threshold in 2G mode.
BMA2x2_LOW_HYST_IN_G
convert g-values to 8-bit value
Macro to convert floating point low-g-hysteresis in G to 8-bit register values. Example: BMA2x2_LOW_HY_IN_G( 0.2, 2.0) generates the register value for 0.2G threshold in 2G mode.
BMA2x2_HIGH_HYST_IN_G
convert g-values to 8-bit value
Macro to convert floating point high-g-hysteresis in G to 8-bit register values. Example: BMA2x2_HIGH_HY_IN_G( 0.2, 2.0) generates the register value for 0.2G threshold in 2G mode.
BMA2x2_SLOPE_THRES_IN_G
convert g-values to 8-bit value
Macro to convert floating point G-thresholds to 8-bit register values Example: BMA2x2_SLOPE_TH_IN_G( 1.2, 2.0) generates the register value for 1.2G threshold in 2G mode.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_burst_read(u8 addr_u8, u8 *data_u8, u32 len_u32)
This API reads the data from the given register continuously.
addr_u8 -> Address of the register data_u8 -> The data from the register len_u32 -> no of bytes to read results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_init(struct bma2x2_t *bma2x2)
This function is used for initialize bus read and bus write functions assign the chip id and device address chip id is read in the register 0x00 bit from 0 to 7.
bma2x2 : structure pointer results of bus communication function 0 -> Success -1 -> Error While changing the parameter of the bma2x2_t consider the following point: Changing the reference value of the parameter will changes the local copy or local reference make sure your changes will not affect the reference value of the parameter (Better case don't change the reference value of the parameter)
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, bma2x2_t::dev_addr, BMA2x2_CHIP_ID_REG, BMA2x2_GEN_READ_WRITE_LENGTH, bma2x2_t::chip_id, bma2x2_read_reg, BMA2x2_FIFO_MODE_REG, bma2x2_t::fifo_config.
Referenced by Bma280Utils_initialize.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_write_reg(u8 adr_u8, u8 *data_u8, u8 len_u8)
This API gives data to the given register and the data is written in the corresponding register address.
adr_u8 -> Address of the register data_u8 -> The data to the register len_u8 -> no of bytes to read results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr.
Referenced by bma2x2_set_power_mode.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_read_reg(u8 adr_u8, u8 *data_u8, u8 len_u8)
This API reads the data from the given register address.
adr_u8 -> Address of the register data_u8 -> The data from the register len_u8 -> no of bytes to read results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr.
Referenced by bma2x2_init, bma2x2_set_fifo_mode, bma2x2_set_fifo_data_select.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_read_accel_x(s16 *accel_x_s16)
This API reads acceleration data X values from location 02h and 03h.
accel_x_s16 : pointer holding the data of accel X value resolution 0 BMA2x2_12_RESOLUTION 1 BMA2x2_10_RESOLUTION 2 BMA2x2_14_RESOLUTION results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_ACCEL_DATA_SIZE, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, V_BMA2x2RESOLUTION_U8, BMA2x2_12_RESOLUTION, bma2x2_t::dev_addr, BMA2x2_ACCEL_X12_LSB_REG, BMA2x2_LSB_MSB_READ_LENGTH, BMA2x2_SENSOR_DATA_ACCEL_MSB, BMA2x2_SHIFT_EIGHT_BITS, BMA2x2_SENSOR_DATA_ACCEL_LSB, BMA2x2_RESOLUTION_12_MASK, BMA2x2_SHIFT_FOUR_BITS, BMA2x2_10_RESOLUTION, BMA2x2_ACCEL_X10_LSB_REG, BMA2x2_RESOLUTION_10_MASK, BMA2x2_SHIFT_SIX_BITS, BMA2x2_14_RESOLUTION, BMA2x2_ACCEL_X14_LSB_REG, BMA2x2_RESOLUTION_14_MASK, BMA2x2_SHIFT_TWO_BITS.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_read_accel_eight_resolution_x(s8 *accel_x_s8)
This API reads acceleration data X values from location 02h and 03h bit resolution support 8bit.
accel_x_s8 : pointer holding the data of accel X results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_X_AXIS_MSB_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_read_accel_y(s16 *accel_y_s16)
This API reads acceleration data Y values from location 04h and 05h.
accel_y_s16 : pointer holding the data of accel Y value resolution 0 BMA2x2_12_RESOLUTION 1 BMA2x2_10_RESOLUTION 2 BMA2x2_14_RESOLUTION results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_ACCEL_DATA_SIZE, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, V_BMA2x2RESOLUTION_U8, BMA2x2_12_RESOLUTION, bma2x2_t::dev_addr, BMA2x2_ACCEL_Y12_LSB_REG, BMA2x2_LSB_MSB_READ_LENGTH, BMA2x2_SENSOR_DATA_ACCEL_MSB, BMA2x2_SHIFT_EIGHT_BITS, BMA2x2_SENSOR_DATA_ACCEL_LSB, BMA2x2_12_BIT_SHIFT, BMA2x2_SHIFT_FOUR_BITS, BMA2x2_10_RESOLUTION, BMA2x2_ACCEL_Y10_LSB_REG, BMA2x2_10_BIT_SHIFT, BMA2x2_SHIFT_SIX_BITS, BMA2x2_14_RESOLUTION, BMA2x2_ACCEL_Y14_LSB_REG, BMA2x2_14_BIT_SHIFT, BMA2x2_SHIFT_TWO_BITS.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_read_accel_eight_resolution_y(s8 *accel_y_s8)
This API reads acceleration data Y values of 8bit resolution from location 05h.
accel_y_s8 The data of y results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_Y_AXIS_MSB_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_read_accel_z(s16 *accel_z_s16)
This API reads acceleration data Z values from location 06h and 07h.
accel_z_s16 : pointer holding the data of accel Z value resolution 0 BMA2x2_12_RESOLUTION 1 BMA2x2_10_RESOLUTION 2 BMA2x2_14_RESOLUTION results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_ACCEL_DATA_SIZE, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, V_BMA2x2RESOLUTION_U8, BMA2x2_12_RESOLUTION, bma2x2_t::dev_addr, BMA2x2_ACCEL_Z12_LSB_REG, BMA2x2_LSB_MSB_READ_LENGTH, BMA2x2_SENSOR_DATA_ACCEL_MSB, BMA2x2_SHIFT_EIGHT_BITS, BMA2x2_SENSOR_DATA_ACCEL_LSB, BMA2x2_12_BIT_SHIFT, BMA2x2_SHIFT_FOUR_BITS, BMA2x2_10_RESOLUTION, BMA2x2_ACCEL_Z10_LSB_REG, BMA2x2_10_BIT_SHIFT, BMA2x2_SHIFT_SIX_BITS, BMA2x2_14_RESOLUTION, BMA2x2_ACCEL_Z14_LSB_REG, BMA2x2_14_BIT_SHIFT, BMA2x2_SHIFT_TWO_BITS.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_read_accel_eight_resolution_z(s8 *accel_z_s8)
This API reads acceleration data Z values of 8bit resolution from location 07h.
@aram accel_z_s8 : the data of zresults of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_Z_AXIS_MSB_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_read_accel_xyz(struct bma2x2_accel_data *accel)
This API reads acceleration data X,Y,Z values from location 02h to 07h.
accel : pointer holding the data of accel value resolution 0 BMA2x2_12_RESOLUTION 1 BMA2x2_10_RESOLUTION 2 BMA2x2_14_RESOLUTION results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_ACCEL_XYZ_DATA_SIZE, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, V_BMA2x2RESOLUTION_U8, BMA2x2_12_RESOLUTION, bma2x2_t::dev_addr, BMA2x2_ACCEL_X12_LSB_REG, BMA2x2_SHIFT_SIX_BITS, bma2x2_accel_data::x, BMA2x2_SENSOR_DATA_XYZ_X_MSB, BMA2x2_SHIFT_EIGHT_BITS, BMA2x2_SENSOR_DATA_XYZ_X_LSB, BMA2x2_12_BIT_SHIFT, BMA2x2_SHIFT_FOUR_BITS, bma2x2_accel_data::y, BMA2x2_SENSOR_DATA_XYZ_Y_MSB, BMA2x2_SENSOR_DATA_XYZ_Y_LSB, bma2x2_accel_data::z, BMA2x2_SENSOR_DATA_XYZ_Z_MSB, BMA2x2_SENSOR_DATA_XYZ_Z_LSB, BMA2x2_10_RESOLUTION, BMA2x2_ACCEL_X10_LSB_REG, BMA2x2_10_BIT_SHIFT, BMA2x2_14_RESOLUTION, BMA2x2_ACCEL_X14_LSB_REG, BMA2x2_14_BIT_SHIFT, BMA2x2_SHIFT_TWO_BITS.
Referenced by Accelerometer_readXyzLsbValue, Accelerometer_readXyzGValue.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_read_accel_eight_resolution_xyz(struct bma2x2_accel_eight_resolution *accel)
This API reads acceleration of 8 bit resolution data of X,Y,Z values from location 03h , 05h and 07h.
accel : pointer holding the data of accel results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_X_AXIS_MSB_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH, bma2x2_accel_eight_resolution::x, BMA2x2_GET_BITSLICE, BMA2x2_Y_AXIS_MSB_ADDR, bma2x2_accel_eight_resolution::y, BMA2x2_Z_AXIS_MSB_ADDR, bma2x2_accel_eight_resolution::z.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_tap_stat(u8 *stat_tap_u8)
This API read tap-sign, tap-first-xyz slope-sign, slope-first-xyz status register byte from location 0Bh.
stat_tap_u8 : The status of tap and slope results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_STAT_TAP_SLOPE_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_orient_stat(u8 *stat_orient_u8)
This API read orient, high-sign and high-first-xyz status register byte from location 0Ch.
stat_orient_u8 : The status of orient and high results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_STAT_ORIENT_HIGH_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_fifo_stat(u8 *stat_fifo_u8)
This API reads fifo overrun and fifo frame counter status register byte from location 0Eh.
stat_fifo_u8 : The status of fifo overrun and frame counter results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_STAT_FIFO_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_fifo_frame_count(u8 *frame_count_u8)
This API read fifo frame count from location 0Eh bit position 0 to 6.
frame_count_u8 : The status of fifo frame count results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_FIFO_FRAME_COUNT_STAT_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_fifo_overrun(u8 *fifo_overrun_u8)
This API read fifo overrun from location 0Eh bit position 7.
fifo_overrun_u8 : The status of fifo overrun results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_FIFO_OVERRUN_STAT_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_stat(u8 *intr_stat_u8)
This API read interrupt status of flat, orient, single tap, double tap, slow no motion, slope, highg and lowg from location 09h.
intr_stat_u8 : The value of interrupt status results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_STAT1_ADDR, BMA2x2_SHIFT_FOUR_BITS.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_range(u8 *range_u8)
This API is used to get the ranges(g values) of the sensor in the register 0x0F bit from 0 to 3.
range_u8 : The value of range range_u8 result 0x03 BMA2x2_RANGE_2G 0x05 BMA2x2_RANGE_4G 0x08 BMA2x2_RANGE_8G 0x0C BMA2x2_RANGE_16G results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_RANGE_SELECT_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
Referenced by Accelerometer_getRange.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_range(u8 range_u8)
This API is used to set the ranges(g values) of the sensor in the register 0x0F bit from 0 to 3.
range_u8 : The value of range range_u8 result 0x03 BMA2x2_RANGE_2G 0x05 BMA2x2_RANGE_4G 0x08 BMA2x2_RANGE_8G 0x0C BMA2x2_RANGE_16G results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_RANGE_2G, BMA2x2_RANGE_4G, BMA2x2_RANGE_8G, BMA2x2_RANGE_16G, bma2x2_t::dev_addr, BMA2x2_RANGE_SELECT_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
Referenced by Accelerometer_setRange.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_bw(u8 *bw_u8)
This API is used to get the bandwidth of the sensor in the register 0x10 bit from 0 to 4.
bw_u8 : The value of bandwidth bw_u8 result 0x08 BMA2x2_BW_7_81HZ 0x09 BMA2x2_BW_15_63HZ 0x0A BMA2x2_BW_31_25HZ 0x0B BMA2x2_BW_62_50HZ 0x0C BMA2x2_BW_125HZ 0x0D BMA2x2_BW_250HZ 0x0E BMA2x2_BW_500HZ 0x0F BMA2x2_BW_1000HZ results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_BW_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
Referenced by Accelerometer_getBandwidth.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_bw(u8 bw_u8)
This API is used to set the bandwidth of the sensor in the register 0x10 bit from 0 to 4.
bw_u8 : The value of bandwidth bw_u8 result 0x08 BMA2x2_BW_7_81HZ 0x09 BMA2x2_BW_15_63HZ 0x0A BMA2x2_BW_31_25HZ 0x0B BMA2x2_BW_62_50HZ 0x0C BMA2x2_BW_125HZ 0x0D BMA2x2_BW_250HZ 0x0E BMA2x2_BW_500HZ 0x0F BMA2x2_BW_1000HZ results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::chip_id, BANDWIDTH_DEFINE, BMA2x2_ACCEL_BW_MIN_RANGE, BMA2x2_ACCEL_BW_1000HZ_RANGE, BMA2x2_BW_7_81HZ, BMA2x2_BW_15_63HZ, BMA2x2_BW_31_25HZ, BMA2x2_BW_62_50HZ, BMA2x2_BW_125HZ, BMA2x2_BW_250HZ, BMA2x2_BW_500HZ, bma2x2_t::dev_addr, BMA2x2_BW_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE, BMA2x2_ACCEL_BW_MAX_RANGE, BMA2x2_BW_1000HZ.
Referenced by Accelerometer_setBandwidth, Bma280Utils_initialize.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_power_mode(u8 *power_mode_u8)
This API is used to get the operating modes of the sensor in the register 0x11 and 0x12.
Register 0x11 - bit from 5 to 7 Register 0x12 - bit from 5 and 6 power_mode_u8 : The value of power mode power_mode_u8 value 0x11 0x12 BMA2x2_MODE_NORMAL 0 0x00 0x00 BMA2x2_MODE_LOWPOWER1 1 0x02 0x00 BMA2x2_MODE_SUSPEND 2 0x06 0x00 BMA2x2_MODE_DEEP_SUSPEND 3 0x01 0x00 BMA2x2_MODE_LOWPOWER2 4 0x02 0x01 BMA2x2_MODE_STANDBY 5 0x04 0x00 results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_MODE_CTRL_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_LOW_NOISE_CTRL_ADDR, BMA2x2_POWER_MODE_HEX_E_ZERO_MASK, BMA2x2_SHIFT_FIVE_BITS, BMA2x2_POWER_MODE_HEX_4_ZERO_MASK, BMA2x2_SHIFT_SIX_BITS, BMA2x2_POWER_MODE_HEX_ZERO_ZERO_MASK, BMA2x2_MODE_NORMAL, BMA2x2_POWER_MODE_HEX_ZERO_TWO_MASK, BMA2x2_MODE_LOWPOWER1, BMA2x2_POWER_MODE_HEX_ZERO_FOUR_MASK, BMA2x2_POWER_MODE_HEX_ZERO_SIX_MASK, BMA2x2_MODE_SUSPEND, BMA2x2_POWER_MODE_HEX_ZERO_ONE_MASK, BMA2x2_MODE_DEEP_SUSPEND, BMA2x2_MODE_LOWPOWER2, BMA2x2_MODE_STANDBY, bma2x2_t::power_mode_u8.
Referenced by Accelerometer_getMode.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_power_mode(u8 power_mode_u8)
This API is used to set the operating modes of the sensor in the register 0x11 and 0x12.
Register 0x11 - bit from 5 to 7 Register 0x12 - bit from 5 and 6 power_mode_u8 : The value of power mode power_mode_u8 value 0x11 0x12 BMA2x2_MODE_NORMAL 0 0x00 0x00 BMA2x2_MODE_LOWPOWER1 1 0x02 0x00 BMA2x2_MODE_SUSPEND 2 0x06 0x00 BMA2x2_MODE_DEEP_SUSPEND 3 0x01 0x00 BMA2x2_MODE_LOWPOWER2 4 0x02 0x01 BMA2x2_MODE_STANDBY 5 0x04 0x00 results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_MODE_CTRL_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_LOW_POWER_MODE_REG, bma2x2_set_mode_value, bma2x2_t::ctrl_mode_reg, bma2x2_t::low_mode_reg, BMA2x2_SET_BITSLICE, bma2x2_t::delay_msec, BMA2x2_SHIFT_FOUR_BITS, bma2x2_t::fifo_config, bma2x2_write_reg, BMA2x2_FIFO_MODE_REG.
Referenced by Accelerometer_setMode.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_mode_value(u8 power_mode_u8)
This API is used to assign the power mode values modes of the sensor in the register 0x11 and 0x12.
Register 0x11 - bit from 5 to 7 Register 0x12 - bit from 5 and 6 power_mode_u8 : The value of power mode power_mode_u8 value 0x11 0x12 BMA2x2_MODE_NORMAL 0 0x00 0x00 BMA2x2_MODE_LOWPOWER1 1 0x02 0x00 BMA2x2_MODE_SUSPEND 2 0x06 0x00 BMA2x2_MODE_DEEP_SUSPEND 3 0x01 0x00 BMA2x2_MODE_LOWPOWER2 4 0x02 0x01 BMA2x2_MODE_STANDBY 5 0x04 0x00 results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, SUCCESS, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_POWER_MODE_RANGE, BMA2x2_MODE_NORMAL, bma2x2_t::ctrl_mode_reg, BMA2x2_POWER_MODE_HEX_ZERO_ZERO_MASK, bma2x2_t::low_mode_reg, BMA2x2_MODE_LOWPOWER1, BMA2x2_POWER_MODE_HEX_ZERO_TWO_MASK, BMA2x2_MODE_LOWPOWER2, BMA2x2_POWER_MODE_HEX_ZERO_ONE_MASK, BMA2x2_MODE_SUSPEND, BMA2x2_POWER_MODE_HEX_ZERO_FOUR_MASK, BMA2x2_MODE_STANDBY, BMA2x2_MODE_DEEP_SUSPEND, E_OUT_OF_RANGE.
Referenced by bma2x2_set_power_mode.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_sleep_durn(u8 *sleep_durn_u8)
This API is used to get the sleep duration of the sensor in the register 0x11 Register 0x11 - bit from 0 to 3.
sleep_durn_u8 : The value of sleep duration time sleep_durn_u8 result 0x05 BMA2x2_SLEEP_DURN_0_5MS 0x06 BMA2x2_SLEEP_DURN_1MS 0x07 BMA2x2_SLEEP_DURN_2MS 0x08 BMA2x2_SLEEP_DURN_4MS 0x09 BMA2x2_SLEEP_DURN_6MS 0x0A BMA2x2_SLEEP_DURN_10MS 0x0B BMA2x2_SLEEP_DURN_25MS 0x0C BMA2x2_SLEEP_DURN_50MS 0x0D BMA2x2_SLEEP_DURN_100MS 0x0E BMA2x2_SLEEP_DURN_500MS 0x0F BMA2x2_SLEEP_DURN_1S results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_SLEEP_DURN_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
Referenced by Accelerometer_getSleepDuration.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_sleep_durn(u8 sleep_durn_u8)
This API is used to set the sleep duration of the sensor in the register 0x11 Register 0x11 - bit from 0 to 3.
sleep_durn_u8 : The value of sleep duration time sleep_durn_u8 result 0x05 BMA2x2_SLEEP_DURN_0_5MS 0x06 BMA2x2_SLEEP_DURN_1MS 0x07 BMA2x2_SLEEP_DURN_2MS 0x08 BMA2x2_SLEEP_DURN_4MS 0x09 BMA2x2_SLEEP_DURN_6MS 0x0A BMA2x2_SLEEP_DURN_10MS 0x0B BMA2x2_SLEEP_DURN_25MS 0x0C BMA2x2_SLEEP_DURN_50MS 0x0D BMA2x2_SLEEP_DURN_100MS 0x0E BMA2x2_SLEEP_DURN_500MS 0x0F BMA2x2_SLEEP_DURN_1S results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_SLEEP_DURN_MIN_RANGE, BMA2x2_SLEEP_DURN_MAX_RANGE, BMA2x2_SLEEP_DURN_0_5MS, BMA2x2_SLEEP_DURN_1MS, BMA2x2_SLEEP_DURN_2MS, BMA2x2_SLEEP_DURN_4MS, BMA2x2_SLEEP_DURN_6MS, BMA2x2_SLEEP_DURN_10MS, BMA2x2_SLEEP_DURN_25MS, BMA2x2_SLEEP_DURN_50MS, BMA2x2_SLEEP_DURN_100MS, BMA2x2_SLEEP_DURN_500MS, BMA2x2_SLEEP_DURN_1S, bma2x2_t::dev_addr, BMA2x2_SLEEP_DURN_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
Referenced by Accelerometer_setSleepDuration.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_sleep_timer_mode(u8 *sleep_timer_u8)
This API is used to get the sleep timer mode in the register 0x12 bit 5.
sleep_timer_u8 : The value of sleep timer mode sleep_timer_u8 result 0 enable EventDrivenSampling(EDT) 1 enable Equidistant sampling mode(EST) results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_SLEEP_TIMER_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_sleep_timer_mode(u8 sleep_timer_u8)
This API is used to set the sleep timer mode in the register 0x12 bit 5.
sleep_timer_u8 : The value of sleep timer mode sleep_timer_u8 result 0 enable EventDrivenSampling(EDT) 1 enable Equidistant sampling mode(EST) results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_SLEEP_TIMER_MODE_RANGE, bma2x2_t::dev_addr, BMA2x2_SLEEP_TIMER_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_high_bw(u8 *high_bw_u8)
This API is used to get high bandwidth in the register 0x13 bit 7.
high_bw_u8 : The value of high bandwidth high_bw_u8 result 0 Unfiltered High Bandwidth 1 Filtered Low Bandwidth results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ENABLE_DATA_HIGH_BW_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_high_bw(u8 high_bw_u8)
This API is used to write high bandwidth in the register 0x13 bit 7.
high_bw_u8 : The value of high bandwidth high_bw_u8 result 0 Unfiltered High Bandwidth 1 Filtered Low Bandwidth results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ENABLE_DATA_HIGH_BW_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
Referenced by Accelerometer_setBandwidth.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_shadow_dis(u8 *shadow_dis_u8)
This API is used to get shadow dis in the register 0x13 bit 6.
shadow_dis_u8 : The value of shadow dis shadow_dis_u8 result 0 MSB is Locked 1 No MSB Locking results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_DIS_SHADOW_PROC_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_shadow_dis(u8 shadow_dis_u8)
This API is used to set shadow dis in the register 0x13 bit 6.
shadow_dis_u8 : The value of shadow dis shadow_dis_u8 result 0 MSB is Locked 1 No MSB Locking results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_DIS_SHADOW_PROC_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_soft_rst(void)
This function is used for the soft reset The soft reset register will be written with 0xB6 in the register 0x14.
results of bus communication function 0 -> Success -1 -> Error None results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_ENABLE_SOFT_RESET_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_RST_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_update_image(void)
This API is used to update the register values.
None results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_UPDATE_IMAGE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_enable(u8 intr_type_u8, u8 *value_u8)
This API is used to get interrupt enable bits of the sensor in the registers 0x16 and 0x17.
It reads the flat enable, orient enable, single tap enable, double tap enable slope-x enable, slope-y enable, slope-z enable, fifo watermark enable, fifo full enable, data enable, low-g enable, high-z enable, high-y enable high-z enable intr_type_u8 The value of interrupts intr_type_u8 result 0 BMA2x2_LOW_G_INTR 1 BMA2x2_HIGH_G_X_INTR 2 BMA2x2_HIGH_G_Y_INTR 3 BMA2x2_HIGH_G_Z_INTR 4 BMA2x2_DATA_ENABLE 5 SLOPE_X_INTR 6 SLOPE_Y_INTR 7 SLOPE_Z_INTR 8 SINGLE_TAP_INTR 9 SINGLE_TAP_INTR 10 ORIENT_INT 11 FLAT_INT value_u8 : The value of interrupts enable value_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_LOW_G_INTR, bma2x2_t::dev_addr, BMA2x2_ENABLE_LOW_G_INTR_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_HIGH_G_X_INTR, BMA2x2_ENABLE_HIGH_G_X_INTR_REG, BMA2x2_HIGH_G_Y_INTR, BMA2x2_ENABLE_HIGH_G_Y_INTR_REG, BMA2x2_HIGH_G_Z_INTR, BMA2x2_ENABLE_HIGH_G_Z_INTR_REG, BMA2x2_DATA_ENABLE, BMA2x2_ENABLE_NEW_DATA_INTR_REG, BMA2x2_SLOPE_X_INTR, BMA2x2_ENABLE_SLOPE_X_INTR_REG, BMA2x2_SLOPE_Y_INTR, BMA2x2_ENABLE_SLOPE_Y_INTR_REG, BMA2x2_SLOPE_Z_INTR, BMA2x2_ENABLE_SLOPE_Z_INTR_REG, BMA2x2_SINGLE_TAP_INTR, BMA2x2_ENABLE_SINGLE_TAP_INTR_REG, BMA2x2_DOUBLE_TAP_INTR, BMA2x2_ENABLE_DOUBLE_TAP_INTR_REG, BMA2x2_ORIENT_INTR, BMA2x2_ENABLE_ORIENT_INTR_REG, BMA2x2_FLAT_INTR, BMA2x2_ENABLE_FLAT_INTR_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_enable(u8 intr_type_u8, u8 value_u8)
This API is used to set interrupt enable bits of the sensor in the registers 0x16 and 0x17.
It reads the flat enable, orient enable, single tap enable, double tap enable slope-x enable, slope-y enable, slope-z enable, fifo watermark enable, fifo full enable, data enable, low-g enable, high-z enable, high-y enable high-z enable intr_type_u8 The value of interrupts intr_type_u8 result 0 BMA2x2_LOW_G_INTR 1 BMA2x2_HIGH_G_X_INTR 2 BMA2x2_HIGH_G_Y_INTR 3 BMA2x2_HIGH_G_Z_INTR 4 BMA2x2_DATA_ENABLE 5 SLOPE_X_INTR 6 SLOPE_Y_INTR 7 SLOPE_Z_INTR 8 SINGLE_TAP_INTR 9 SINGLE_TAP_INTR 10 ORIENT_INT 11 FLAT_INT value_u8 : The value of interrupts enable value_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_INTR_ENABLE1_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_INTR_ENABLE2_ADDR, BMA2x2_LOW_G_INTR, BMA2x2_SET_BITSLICE, BMA2x2_HIGH_G_X_INTR, BMA2x2_HIGH_G_Y_INTR, BMA2x2_HIGH_G_Z_INTR, BMA2x2_DATA_ENABLE, BMA2x2_SLOPE_X_INTR, BMA2x2_SLOPE_Y_INTR, BMA2x2_SLOPE_Z_INTR, BMA2x2_SINGLE_TAP_INTR, BMA2x2_DOUBLE_TAP_INTR, BMA2x2_ORIENT_INTR, BMA2x2_FLAT_INTR, E_OUT_OF_RANGE.
Referenced by configureNewDataInterrupt, configureSlopeInterrupt.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_fifo_full(u8 *fifo_full_u8)
This API is used to get the interrupt fifo full enable interrupt status in the register 0x17 bit 5.
fifo_full_u8 The value of fifo full interrupt enable fifo_full_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_INTR_FIFO_FULL_ENABLE_INTR_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_fifo_full(u8 fifo_full_u8)
This API is used to set the interrupt fifo full enable interrupt status in the register 0x17 bit 5.
fifo_full_u8 The value of fifo full interrupt enable fifo_full_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_FIFO_MODE_STATUS_RANGE, bma2x2_t::dev_addr, BMA2x2_INTR_FIFO_FULL_ENABLE_INTR_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_fifo_wm(u8 *fifo_wm_u8)
This API is used to get the interrupt fifo watermark enable interrupt status in the register 0x17 bit 6.
fifo_wm_u8 : the value FIFO Water Mark fifo_wm_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_INTR_FIFO_WM_ENABLE_INTR_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_fifo_wm(u8 fifo_wm_u8)
This API is used to set the interrupt fifo watermark enable interrupt status in the register 0x17 bit 6.
fifo_wm_u8 : the value FIFO Water Mark fifo_wm_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_FIFO_MODE_STATUS_RANGE, bma2x2_t::dev_addr, BMA2x2_INTR_FIFO_WM_ENABLE_INTR_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_slow_no_motion(u8 channel_u8, u8 *slow_no_motion_u8)
This API is used to get the interrupt status of slow/no motion select and slow no motion enable xyz interrupt in the register 0x18 bit from 0 to 3.
channel_u8 : The value of slow/no motion select channel_u8 result 0 BMA2x2_ACCEL_SLOW_NO_MOTION_ENABLE_X 1 BMA2x2_ACCEL_SLOW_NO_MOTION_ENABLE_Y 2 BMA2x2_ACCEL_SLOW_NO_MOTION_ENABLE_Z 3 BMA2x2_ACCEL_SLOW_NO_MOTION_ENABLE_SEL slow_no_motion_u8 : The value of slow no motion interrupt enable slow_no_motion_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_SLOW_NO_MOTION_ENABLE_X, bma2x2_t::dev_addr, BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_X_INTR_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_SLOW_NO_MOTION_ENABLE_Y, BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_Y_INTR_REG, BMA2x2_SLOW_NO_MOTION_ENABLE_Z, BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_Z_INTR_REG, BMA2x2_SLOW_NO_MOTION_ENABLE_SELECT, BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_SELECT_INTR_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_slow_no_motion(u8 channel_u8, u8 slow_no_motion_u8)
This API is used to set the interrupt status of slow/no motion select and slow no motion enable xyz interrupt in the register 0x18 bit from 0 to 3.
channel_u8 : The value of slow/no motion select channel_u8 result 0 BMA2x2_ACCEL_SLOW_NO_MOTION_ENABLE_X 1 BMA2x2_ACCEL_SLOW_NO_MOTION_ENABLE_Y 2 BMA2x2_ACCEL_SLOW_NO_MOTION_ENABLE_Z 3 BMA2x2_ACCEL_SLOW_NO_MOTION_ENABLE_SEL slow_no_motion_u8 : The value of slow no motion interrupt enable slow_no_motion_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_SLOW_NO_MOTION_ENABLE_X, bma2x2_t::dev_addr, BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_X_INTR_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_SLOW_NO_MOTION_ENABLE_Y, BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_Y_INTR_REG, BMA2x2_SLOW_NO_MOTION_ENABLE_Z, BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_Z_INTR_REG, BMA2x2_SLOW_NO_MOTION_ENABLE_SELECT, BMA2x2_INTR_SLOW_NO_MOTION_ENABLE_SELECT_INTR_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_low_g(u8 channel_u8, u8 *intr_low_g_u8)
This API is used to get the interrupt enable of low_g interrupt in the register 0x19 and 0x1B.
INTR1_Low_g -> register 0x19 bit 0 INTR2_Low_g -> register 0x1B bit 0 channel_u8 : The value of low interrupt selection channel channel_u8 result 0 BMA2x2_ACCEL_INTR1_LOW_G 1 BMA2x2_ACCEL_INTR2_LOW_G intr_low_g_u8 : the value of low_g interrupt intr_low_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_LOW_G, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_LOW_G_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_INTR2_LOW_G, BMA2x2_ENABLE_INTR2_PAD_LOW_G_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_low_g(u8 channel_u8, u8 intr_low_u8)
This API is used to set the interrupt enable of low_g interrupt in the register 0x19 and 0x1B.
INTR1_Low_g -> register 0x19 bit 0 INTR2_Low_g -> register 0x1B bit 0 channel_u8 : The value of low interrupt selection channel channel_u8 result 0 BMA2x2_ACCEL_INTR1_LOW_G 1 BMA2x2_ACCEL_INTR2_LOW_G intr_low_u8 : the value of low_g interrupt intr_low_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_LOW_G, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_LOW_G_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_INTR2_LOW_G, BMA2x2_ENABLE_INTR2_PAD_LOW_G_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_high_g(u8 channel_u8, u8 *intr_high_g_u8)
This API is used to get the interrupt enable of high_g interrupt in the register 0x19 and 0x1B.
INTR1_high_g -> register 0x19 bit 1 INTR2_high_g -> register 0x1B bit 1 channel_u8 The value of high_g interrupt selection channel_u8 result 0 BMA2x2_ACCEL_INTR1_HIGH_G 1 BMA2x2_ACCEL_INTR2_HIGH_G intr_high_g_u8 : the value of high_g interrupt intr_high_g_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_HIGH_G, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_HIGH_G_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_INTR2_HIGH_G, BMA2x2_ENABLE_INTR2_PAD_HIGH_G_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_high_g(u8 channel_u8, u8 intr_high_g_u8)
This API is used to set the interrupt enable of high_g interrupt in the register 0x19 and 0x1B.
INTR1_high_g -> register 0x19 bit 1 INTR2_high_g -> register 0x1B bit 1 channel_u8 The value of high_g interrupt selection channel_u8 result 0 BMA2x2_ACCEL_INTR1_HIGH_G 1 BMA2x2_ACCEL_INTR2_HIGH_G intr_high_g_u8 : the value of high_g interrupt intr_high_g_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_HIGH_G, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_HIGH_G_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_INTR2_HIGH_G, BMA2x2_ENABLE_INTR2_PAD_HIGH_G_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_slope(u8 channel_u8, u8 *intr_slope_u8)
This API is used to get the interrupt enable of slope interrupt in the register 0x19 and 0x1B.
INTR1_slope -> register 0x19 bit 2 INTR2_slope -> register 0x1B bit 2 channel_u8 the value of slope channel select channel_u8 result 0 BMA2x2_ACCEL_INTR1_SLOPE 1 BMA2x2_ACCEL_INTR2_SLOPE intr_slope_u8 : The slope value enable value intr_slope_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_SLOPE, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_SLOPE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_INTR2_SLOPE, BMA2x2_ENABLE_INTR2_PAD_SLOPE_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_slope(u8 channel_u8, u8 intr_slope_u8)
This API is used to set the interrupt enable of slope interrupt in the register 0x19 and 0x1B.
INTR1_slope -> register 0x19 bit 2 INTR2_slope -> register 0x1B bit 2 channel_u8 the value of slope channel select channel_u8 result 0 BMA2x2_ACCEL_INTR1_SLOPE 1 BMA2x2_ACCEL_INTR2_SLOPE intr_slope_u8 : The slope value enable value intr_slope_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_SLOPE, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_SLOPE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_INTR2_SLOPE, BMA2x2_ENABLE_INTR2_PAD_SLOPE_REG, E_OUT_OF_RANGE.
Referenced by configureSlopeInterrupt, Bma280Utils_disableInterrupt.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_slow_no_motion(u8 channel_u8, u8 *intr_slow_no_motion_u8)
This API is used to get the interrupt enable of slow/no motion interrupt in the register 0x19 and 0x1B.
INTR1_slow_no_motion -> register 0x19 bit 3 INTR2_slow_no_motion -> register 0x1B bit 3 channel_u8 : The value of slow/no motion selection channel_u8 result 0 BMA2x2_INTR1_SLOW_NO_MOTION 1 BMA2x2_INTR2_SLOW_NO_MOTION intr_slow_no_motion_u8 the slow_no_motion enable value intr_slow_no_motion_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_SLOW_NO_MOTION, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_SLOW_NO_MOTION_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_INTR2_SLOW_NO_MOTION, BMA2x2_ENABLE_INTR2_PAD_SLOW_NO_MOTION_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_slow_no_motion(u8 channel_u8, u8 intr_slow_no_motion_u8)
This API is used to set the interrupt enable of slow/no motion interrupt in the register 0x19 and 0x1B.
INTR1_slow_no_motion -> register 0x19 bit 3 INTR2_slow_no_motion -> register 0x1B bit 3 channel_u8 : The value of slow/no motion selection channel_u8 result 0 BMA2x2_INTR1_SLOW_NO_MOTION 1 BMA2x2_INTR2_SLOW_NO_MOTION intr_slow_no_motion_u8 the slow_no_motion enable value intr_slow_no_motion_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_SLOW_NO_MOTION, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_SLOW_NO_MOTION_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_INTR2_SLOW_NO_MOTION, BMA2x2_ENABLE_INTR2_PAD_SLOW_NO_MOTION_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_double_tap(u8 channel_u8, u8 *intr_double_tap_u8)
This API is used to get the interrupt enable of double tap interrupt in the register 0x19 and 0x1B.
INTR1_double -> register 0x19 bit 4 INTR2_double -> register 0x1B bit 4 channel_u8 The value of double tap selection channel_u8 result 0 BMA2x2_ACCEL_INTR1_DOUBLE_TAP 1 BMA2x2_ACCEL_INTR2_DOUBLE_TAP intr_double_tap_u8 The double tap interrupt enable value intr_double_tap_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_DOUBLE_TAP, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_DOUBLE_TAP_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_INTR2_DOUBLE_TAP, BMA2x2_ENABLE_INTR2_PAD_DOUBLE_TAP_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_double_tap(u8 channel_u8, u8 intr_double_tap_u8)
This API is used to set the interrupt enable of double tap interrupt in the register 0x19 and 0x1B.
INTR1_double -> register 0x19 bit 4 INTR2_double -> register 0x1B bit 4 channel_u8 The value of double tap selection channel_u8 result 0 BMA2x2_ACCEL_INTR1_DOUBLE_TAP 1 BMA2x2_ACCEL_INTR2_DOUBLE_TAP intr_double_tap_u8 The double tap interrupt enable value intr_double_tap_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_DOUBLE_TAP, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_DOUBLE_TAP_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_INTR2_DOUBLE_TAP, BMA2x2_ENABLE_INTR2_PAD_DOUBLE_TAP_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_single_tap(u8 channel_u8, u8 *intr_single_tap_u8)
This API is used to get the interrupt enable of single tap interrupt in the register 0x19 and 0x1B.
INTR1_single_tap -> register 0x19 bit 5 INTR2_single_tap -> register 0x1B bit 5 channel_u8 The value of single tap interrupt select channel_u8 result 0 BMA2x2_ACCEL_INTR1_SINGLE_TAP 1 BMA2x2_ACCEL_INTR2_SINGLE_TAP intr_single_tap_u8 The single tap interrupt enable value intr_single_tap_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_SINGLE_TAP, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_SINGLE_TAP_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_INTR2_SINGLE_TAP, BMA2x2_ENABLE_INTR2_PAD_SINGLE_TAP_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_single_tap(u8 channel_u8, u8 intr_single_tap_u8)
This API is used to set the interrupt enable of single tap interrupt in the register 0x19 and 0x1B.
INTR1_single_tap -> register 0x19 bit 5 INTR2_single_tap -> register 0x1B bit 5 channel_u8 The value of single tap interrupt select channel_u8 result 0 BMA2x2_ACCEL_INTR1_SINGLE_TAP 1 BMA2x2_ACCEL_INTR2_SINGLE_TAP intr_single_tap_u8 The single tap interrupt enable value intr_single_tap_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_SINGLE_TAP, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_SINGLE_TAP_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_INTR2_SINGLE_TAP, BMA2x2_ENABLE_INTR2_PAD_SINGLE_TAP_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_orient(u8 channel_u8, u8 *intr_orient_u8)
This API is used to get the interrupt status of orient interrupt in the register 0x19 and 0x1B.
INTR1_orient -> register 0x19 bit 6 INTR2_orient -> register 0x1B bit 6 channel_u8 The value of orient interrupt select channel_u8 result 0 BMA2x2_ACCEL_INTR1_ORIENT 1 BMA2x2_ACCEL_INTR2_ORIENT intr_orient_u8 The value of orient interrupt enable intr_orient_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_ORIENT, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_ORIENT_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_INTR2_ORIENT, BMA2x2_ENABLE_INTR2_PAD_ORIENT_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_orient(u8 channel_u8, u8 intr_orient_u8)
This API is used to set the interrupt status of orient interrupt in the register 0x19 and 0x1B.
INTR1_orient -> register 0x19 bit 6 INTR2_orient -> register 0x1B bit 6 channel_u8 The value of orient interrupt select channel_u8 result 0 BMA2x2_ACCEL_INTR1_ORIENT 1 BMA2x2_ACCEL_INTR2_ORIENT intr_orient_u8 The value of orient interrupt enable intr_orient_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_ORIENT, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_ORIENT_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_INTR2_ORIENT, BMA2x2_ENABLE_INTR2_PAD_ORIENT_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_flat(u8 channel_u8, u8 *intr_flat_u8)
This API is used to get the interrupt enable of flat interrupt in the register 0x19 and 0x1B.
INTR1_flat -> register 0x19 bit 7 INTR2_flat -> register 0x1B bit 7 channel_u8 The value of flat interrupt select channel_u8 result 0 BMA2x2_ACCEL_INTR1_FLAT 1 BMA2x2_ACCEL_INTR2_FLAT intr_flat_u8 The flat interrupt enable value intr_flat_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_FLAT, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_FLAT_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_INTR2_FLAT, BMA2x2_ENABLE_INTR2_PAD_FLAT_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_flat(u8 channel_u8, u8 intr_flat_u8)
This API is used to set the interrupt enable of flat interrupt in the register 0x19 and 0x1B.
INTR1_flat -> register 0x19 bit 7 INTR2_flat -> register 0x1B bit 7 channel_u8 The value of flat interrupt select channel_u8 result 0 BMA2x2_ACCEL_INTR1_FLAT 1 BMA2x2_ACCEL_INTR2_FLAT intr_flat_u8 The flat interrupt enable value intr_flat_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_FLAT, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_FLAT_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_INTR2_FLAT, BMA2x2_ENABLE_INTR2_PAD_FLAT_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_new_data(u8 channel_u8, u8 *intr_newdata_u8)
This API is used to get the interrupt status of new data in the register 0x19.
INTR1_data -> register 0x19 bit 0 INTR2_data -> register 0x19 bit 7 channel_u8 The value of new data interrupt select channel_u8 result 0 BMA2x2_ACCEL_INTR1_NEWDATA 1 BMA2x2_ACCEL_INTR2_NEWDATA intr_newdata_u8 The new data interrupt enable value intr_newdata_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_NEWDATA, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_NEWDATA_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_INTR2_NEWDATA, BMA2x2_ENABLE_INTR2_PAD_NEWDATA_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_new_data(u8 channel_u8, u8 intr_newdata_u8)
This API is used to set the interrupt status of new data in the register 0x19.
INTR1_data -> register 0x19 bit 0 INTR2_data -> register 0x19 bit 7 channel_u8 The value of new data interrupt select channel_u8 result 0 BMA2x2_ACCEL_INTR1_NEWDATA 1 BMA2x2_ACCEL_INTR2_NEWDATA intr_newdata_u8 The new data interrupt enable value intr_newdata_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_NEWDATA, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_NEWDATA_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_INTR2_NEWDATA, BMA2x2_ENABLE_INTR2_PAD_NEWDATA_REG, E_OUT_OF_RANGE.
Referenced by configureNewDataInterrupt.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr1_fifo_wm(u8 *intr1_fifo_wm_u8)
This API is used to get the fifo watermark interrupt1 data in the register 0x1A bit 1.
intr1_fifo_wm_u8 : The value of interrupt1 FIFO watermark enable intr1_fifo_wm_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_FIFO_WM_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr1_fifo_wm(u8 intr1_fifo_wm_u8)
This API is used to set the fifo watermark interrupt1 data in the register 0x1A bit 1.
intr1_fifo_wm_u8 : The value of interrupt1 FIFO watermark enable intr1_fifo_wm_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_FIFO_MODE_STATUS_RANGE, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_FIFO_WM_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr2_fifo_wm(u8 *intr2_fifo_wm_u8)
This API is used to get the fifo watermark interrupt2 data in the register 0x1A bit 6.
intr2_fifo_wm_u8 : The value of interrupt1 FIFO watermark enable intr2_fifo_wm_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR2_PAD_FIFO_WM_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr2_fifo_wm(u8 intr2_fifo_wm_u8)
This API is used to set the fifo watermark interrupt2 data in the register 0x1A bit 6.
intr2_fifo_wm_u8 : The value of interrupt1 FIFO watermark enable intr2_fifo_wm_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_FIFO_MODE_STATUS_RANGE, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR2_PAD_FIFO_WM_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr1_fifo_full(u8 *intr1_fifo_full_u8)
This API is used to get the fifo full interrupt1 in the register 0x1A bit 2.
intr1_fifo_full_u8 : The value of fifo full interrupt enable intr1_fifo_full_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_FIFO_FULL_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr1_fifo_full(u8 intr1_fifo_full_u8)
This API is used to set the fifo full interrupt1 in the register 0x1A bit 2.
intr1_fifo_full_u8 : The value of fifo full interrupt enable intr1_fifo_full_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_FIFO_MODE_STATUS_RANGE, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR1_PAD_FIFO_FULL_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr2_fifo_full(u8 *intr2_fifo_full_u8)
This API is used to get the fifo full interrupt2 in the register 0x1A bit 5.
intr2_fifo_full_u8 : Thee vale of fifo full enable intr2_fifo_full_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR2_PAD_FIFO_FULL_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr2_fifo_full(u8 intr2_fifo_full_u8)
This API is used to set the fifo full interrupt2 in the register 0x1A bit 5.
intr2_fifo_full_u8 : Thee vale of fifo full enable intr2_fifo_full_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_FIFO_MODE_STATUS_RANGE, bma2x2_t::dev_addr, BMA2x2_ENABLE_INTR2_PAD_FIFO_FULL_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_source(u8 channel_u8, u8 *intr_source_u8)
This API is used to get the source data status of source data, source slow no motion, source slope, source high and source low in the register 0x1E bit from 0 to 5.
channel_u8 : The value of source select channel_u8 result 0 BMA2x2_ACCEL_SOURCE_LOW_G 1 BMA2x2_ACCEL_SOURCE_HIGH_G 2 BMA2x2_ACCEL_SOURCE_SLOPE 3 BMA2x2_ACCEL_SOURCE_SLOW_NO_MOTION 4 BMA2x2_ACCEL_SOURCE_TAP 5 BMA2x2_ACCEL_SOURCE_DATA intr_source_u8 The source status enable value intr_source_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_SOURCE_LOW_G, bma2x2_t::dev_addr, BMA2x2_UNFILT_INTR_SOURCE_LOW_G_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_SOURCE_HIGH_G, BMA2x2_UNFILT_INTR_SOURCE_HIGH_G_REG, BMA2x2_SOURCE_SLOPE, BMA2x2_UNFILT_INTR_SOURCE_SLOPE_REG, BMA2x2_SOURCE_SLOW_NO_MOTION, BMA2x2_UNFILT_INTR_SOURCE_SLOW_NO_MOTION_REG, BMA2x2_SOURCE_TAP, BMA2x2_UNFILT_INTR_SOURCE_TAP_REG, BMA2x2_SOURCE_DATA, BMA2x2_UNFILT_INTR_SOURCE_DATA_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_source(u8 channel_u8, u8 intr_source_u8)
This API is used to set the source data status of source data, source slow no motion, source slope, source high and source low in the register 0x1E bit from 0 to 5.
channel_u8 : The value of source select channel_u8 result 0 BMA2x2_ACCEL_SOURCE_LOW_G 1 BMA2x2_ACCEL_SOURCE_HIGH_G 2 BMA2x2_ACCEL_SOURCE_SLOPE 3 BMA2x2_ACCEL_SOURCE_SLOW_NO_MOTION 4 BMA2x2_ACCEL_SOURCE_TAP 5 BMA2x2_ACCEL_SOURCE_DATA intr_source_u8 The source status enable value intr_source_u8 result 0x00 INTR_DISABLE 0x01 INTR_ENABLE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_SOURCE_LOW_G, bma2x2_t::dev_addr, BMA2x2_UNFILT_INTR_SOURCE_LOW_G_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_SOURCE_HIGH_G, BMA2x2_UNFILT_INTR_SOURCE_HIGH_G_REG, BMA2x2_SOURCE_SLOPE, BMA2x2_UNFILT_INTR_SOURCE_SLOPE_REG, BMA2x2_SOURCE_SLOW_NO_MOTION, BMA2x2_UNFILT_INTR_SOURCE_SLOW_NO_MOTION_REG, BMA2x2_SOURCE_TAP, BMA2x2_UNFILT_INTR_SOURCE_TAP_REG, BMA2x2_SOURCE_DATA, BMA2x2_UNFILT_INTR_SOURCE_DATA_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_output_type(u8 channel_u8, u8 *intr_output_type_u8)
This API is used to get the interrupt output type in the register 0x20.
INTR1 -> bit 1 INTR2 -> bit 3 channel_u8 The value of output type select channel_u8 result 0 BMA2x2_ACCEL_INTR1_OUTPUT 1 BMA2x2_ACCEL_INTR2_OUTPUT intr_output_type_u8 The value of output type select intr_source_u8 result 0x01 OPEN_DRAIN 0x00 PUSS_PULL results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_OUTPUT, bma2x2_t::dev_addr, BMA2x2_INTR1_PAD_OUTPUT_TYPE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_INTR2_OUTPUT, BMA2x2_INTR2_PAD_OUTPUT_TYPE_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_output_type(u8 channel_u8, u8 intr_output_type_u8)
This API is used to set the interrupt output type in the register 0x20.
INTR1 -> bit 1 INTR2 -> bit 3 channel_u8 The value of output type select channel_u8 result 0 BMA2x2_ACCEL_INTR1_OUTPUT 1 BMA2x2_ACCEL_INTR2_OUTPUT intr_output_type_u8 The value of output type select intr_source_u8 result 0x01 OPEN_DRAIN 0x00 PUSS_PULL results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_OUTPUT, bma2x2_t::dev_addr, BMA2x2_INTR1_PAD_OUTPUT_TYPE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_INTR2_OUTPUT, BMA2x2_INTR2_PAD_OUTPUT_TYPE_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_intr_level(u8 channel_u8, u8 *intr_level_u8)
This API is used to get Active Level status in the register 0x20.
INTR1 -> bit 0 INTR2 -> bit 2 channel_u8 The value of Active Level select channel_u8 result 0 BMA2x2_ACCEL_INTR1_LEVEL 1 BMA2x2_ACCEL_INTR2_LEVEL intr_level_u8 The Active Level status enable value intr_level_u8 result 0x01 ACTIVE_HIGH 0x00 ACTIVE_LOW results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_LEVEL, bma2x2_t::dev_addr, BMA2x2_INTR1_PAD_ACTIVE_LEVEL_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_INTR2_LEVEL, BMA2x2_INTR2_PAD_ACTIVE_LEVEL_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_intr_level(u8 channel_u8, u8 intr_level_u8)
This API is used to set Active Level status in the register 0x20.
INTR1 -> bit 0 INTR2 -> bit 2 channel_u8 The value of Active Level select channel_u8 result 0 BMA2x2_ACCEL_INTR1_LEVEL 1 BMA2x2_ACCEL_INTR2_LEVEL intr_level_u8 The Active Level status enable value intr_level_u8 result 0x01 ACTIVE_HIGH 0x00 ACTIVE_LOW results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_INTR1_LEVEL, bma2x2_t::dev_addr, BMA2x2_INTR1_PAD_ACTIVE_LEVEL_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_INTR2_LEVEL, BMA2x2_INTR2_PAD_ACTIVE_LEVEL_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_rst_intr(u8 rst_intr_u8)
This API is used to set the reset interrupt in the register 0x21 bit 7.
rst_intr_u8 The value of reset interrupt rst_intr_u8 result 0x01 clear any latch interrupt 0x00 keep latch interrupt active results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_RESET_INTR_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_latch_intr(u8 *latch_intr_u8)
This API is used to get the latch duration in the register 0x21 bit from 0 to 3.
latch_intr_u8 The value of latch duration latch_intr_u8 result 0x00 BMA2x2_LATCH_DURN_NON_LATCH 0x01 BMA2x2_LATCH_DURN_250MS 0x02 BMA2x2_LATCH_DURN_500MS 0x03 BMA2x2_LATCH_DURN_1S 0x04 BMA2x2_LATCH_DURN_2S 0x05 BMA2x2_LATCH_DURN_4S 0x06 BMA2x2_LATCH_DURN_8S 0x07 BMA2x2_LATCH_DURN_LATCH 0x08 BMA2x2_LATCH_DURN_NON_LATCH1 0x09 BMA2x2_LATCH_DURN_250US 0x0A BMA2x2_LATCH_DURN_500US 0x0B BMA2x2_LATCH_DURN_1MS 0x0C BMA2x2_LATCH_DURN_12_5MS 0x0D BMA2x2_LATCH_DURN_25MS 0x0E BMA2x2_LATCH_DURN_50MS 0x0F BMA2x2_LATCH_DURN_LATCH1 results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_LATCH_INTR_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_latch_intr(u8 latch_intr_u8)
This API is used to set the latch duration in the register 0x21 bit from 0 to 3.
latch_intr_u8 The value of latch duration latch_intr_u8 result 0x00 BMA2x2_LATCH_DURN_NON_LATCH 0x01 BMA2x2_LATCH_DURN_250MS 0x02 BMA2x2_LATCH_DURN_500MS 0x03 BMA2x2_LATCH_DURN_1S 0x04 BMA2x2_LATCH_DURN_2S 0x05 BMA2x2_LATCH_DURN_4S 0x06 BMA2x2_LATCH_DURN_8S 0x07 BMA2x2_LATCH_DURN_LATCH 0x08 BMA2x2_LATCH_DURN_NON_LATCH1 0x09 BMA2x2_LATCH_DURN_250US 0x0A BMA2x2_LATCH_DURN_500US 0x0B BMA2x2_LATCH_DURN_1MS 0x0C BMA2x2_LATCH_DURN_12_5MS 0x0D BMA2x2_LATCH_DURN_25MS 0x0E BMA2x2_LATCH_DURN_50MS 0x0F BMA2x2_LATCH_DURN_LATCH1 results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_ACCEL_BW_MAX_RANGE, BMA2x2_LATCH_DURN_NON_LATCH, BMA2x2_LATCH_DURN_250MS, BMA2x2_LATCH_DURN_500MS, BMA2x2_LATCH_DURN_1S, BMA2x2_LATCH_DURN_2S, BMA2x2_LATCH_DURN_4S, BMA2x2_LATCH_DURN_8S, BMA2x2_LATCH_DURN_LATCH, BMA2x2_LATCH_DURN_NON_LATCH1, BMA2x2_LATCH_DURN_250US, BMA2x2_LATCH_DURN_500US, BMA2x2_LATCH_DURN_1MS, BMA2x2_LATCH_DURN_12_5MS, BMA2x2_LATCH_DURN_25MS, BMA2x2_LATCH_DURN_50MS, BMA2x2_LATCH_DURN_LATCH1, bma2x2_t::dev_addr, BMA2x2_LATCH_INTR_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_durn(u8 channel_u8, u8 *durn_u8)
This API is used to get the duration of Low, High, Slope and slow no motion interrupts in the registers.
LOW_DURN -> register 0x22 bit form 0 to 7 HIGH_DURN -> register 0x25 bit form 0 to 7 SLOPE_DURN -> register 0x27 bit form 0 to 1 SLO_NO_MOT_DURN -> register 0x27 bit form 2 to 7 channel_u8 The value of duration select channel_u8 result 0 BMA2x2_ACCEL_LOW_DURN 1 BMA2x2_ACCEL_HIGH_DURN 2 BMA2x2_ACCEL_SLOPE_DURN 3 BMA2x2_ACCEL_SLOW_NO_MOTION_DURN durn_u8 The value of duration : Duration result BMA2x2_ACCEL_LOW_DURN Low-g interrupt trigger - delay according to([durn_u8 +1]*2)ms - range from 2ms to 512ms. default is 20ms BMA2x2_ACCEL_HIGH_DURN high-g interrupt trigger - delay according to([durn_u8 +1]*2)ms - range from 2ms to 512ms. default is 32ms BMA2x2_ACCEL_SLOPE_DURNslope interrupt trigger - if[durn_u8<1:0>+1] consecutive data points - are above the slope interrupt threshold SLO_NO_MOT_DURN Refer data sheet for clear information results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_LOW_DURN, bma2x2_t::dev_addr, BMA2x2_LOW_DURN_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_HIGH_DURN, BMA2x2_HIGH_DURN_ADDR, BMA2x2_SLOPE_DURN, BMA2x2_SLOPE_DURN_REG, BMA2x2_GET_BITSLICE, BMA2x2_SLOW_NO_MOTION_DURN, BMA2x2_SLOW_NO_MOTION_DURN_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_durn(u8 channel_u8, u8 durn_u8)
This API is used to set the duration of Low, High, Slope and slow no motion interrupts in the registers.
LOW_DURN -> register 0x22 bit form 0 to 7 HIGH_DURN -> register 0x25 bit form 0 to 7 SLOPE_DURN -> register 0x27 bit form 0 to 1 SLO_NO_MOT_DURN -> register 0x27 bit form 2 to 7 channel_u8 The value of duration select channel_u8 result 0 BMA2x2_ACCEL_LOW_DURN 1 BMA2x2_ACCEL_HIGH_DURN 2 BMA2x2_ACCEL_SLOPE_DURN 3 BMA2x2_ACCEL_SLOW_NO_MOTION_DURN durn_u8 The value of duration : Duration result BMA2x2_ACCEL_LOW_DURN Low-g interrupt trigger - delay according to([durn_u8 +1]*2)ms - range from 2ms to 512ms. default is 20ms BMA2x2_ACCEL_HIGH_DURN high-g interrupt trigger - delay according to([durn_u8 +1]*2)ms - range from 2ms to 512ms. default is 32ms BMA2x2_ACCEL_SLOPE_DURNslope interrupt trigger - if[durn_u8<1:0>+1] consecutive data points - are above the slope interrupt threshold SLO_NO_MOT_DURN Refer data sheet for clear information results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_LOW_DURN, bma2x2_t::dev_addr, BMA2x2_LOW_DURN_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_HIGH_DURN, BMA2x2_HIGH_DURN_ADDR, BMA2x2_SLOPE_DURN, BMA2x2_SLOPE_DURN_REG, BMA2x2_SET_BITSLICE, BMA2x2_SLOW_NO_MOTION_DURN, BMA2x2_SLOW_NO_MOTION_DURN_REG, E_OUT_OF_RANGE.
Referenced by configureSlopeInterrupt.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_thres(u8 channel_u8, u8 *thres_u8)
This API is used to get the threshold of Low, High, Slope and slow no motion interrupts in the registers.
LOW_THRES -> register 0x23 bit form 0 to 7 HIGH_THRES -> register 0x26 bit form 0 to 7 SLOPE_THRES -> register 0x28 bit form 0 to 7 SLO_NO_MOT_THRES -> register 0x29 bit form 0 to 7 channel_u8 The value of threshold selection channel_u8 result 0 BMA2x2_ACCEL_LOW_THRES 1 BMA2x2_ACCEL_HIGH_THRES 2 BMA2x2_ACCEL_SLOPE_THRES 3 BMA2x2_ACCEL_SLOW_NO_MOTION_THRES thres_u8 The threshold value of selected interrupts : LOW-G THRESHOLD Threshold result BMA2x2_ACCEL_LOW_THRES Low-threshold interrupt trigger | according to(thres_u8 * 7.81) mg | range from 0g to 1.992g | default is 375mg : HIGH-G THRESHOLD Threshold of high-g interrupt according to accel g range g-range High-g threshold 2g (thres_u8 * 7.81) mg 4g (thres_u8 * 15.63) mg 8g (thres_u8 * 31.25) mg 16g (thres_u8 * 62.5) mg : SLOPE THRESHOLD Threshold of slope interrupt according to accel g range g-range Slope threshold 2g (thres_u8 * 3.19) mg 4g (thres_u8 * 7.81) mg 8g (thres_u8 * 15.63) mg 16g (thres_u8 * 31.25) mg : SLOW NO MOTION THRESHOLD Threshold of slow no motion interrupt according to accel g range g-range slow no motion threshold 2g (thres_u8 * 3.19) mg 4g (thres_u8 * 7.81) mg 8g (thres_u8 * 15.63) mg 16g (thres_u8 * 31.25) mg results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_LOW_THRES, bma2x2_t::dev_addr, BMA2x2_LOW_THRES_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_HIGH_THRES, BMA2x2_HIGH_THRES_ADDR, BMA2x2_SLOPE_THRES, BMA2x2_SLOPE_THRES_ADDR, BMA2x2_SLOW_NO_MOTION_THRES, BMA2x2_SLOW_NO_MOTION_THRES_ADDR, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_thres(u8 channel_u8, u8 thres_u8)
This API is used to set the threshold of Low, High, Slope and slow no motion interrupts in the registers.
LOW_THRES -> register 0x23 bit form 0 to 7 HIGH_THRES -> register 0x26 bit form 0 to 7 SLOPE_THRES -> register 0x28 bit form 0 to 7 SLO_NO_MOT_THRES -> register 0x29 bit form 0 to 7 channel_u8 The value of threshold selection channel_u8 result 0 BMA2x2_ACCEL_LOW_THRES 1 BMA2x2_ACCEL_HIGH_THRES 2 BMA2x2_ACCEL_SLOPE_THRES 3 BMA2x2_ACCEL_SLOW_NO_MOTION_THRES thres_u8 The threshold value of selected interrupts : LOW-G THRESHOLD Threshold result BMA2x2_ACCEL_LOW_THRES Low-threshold interrupt trigger | according to(thres_u8 * 7.81) mg | range from 0g to 1.992g | default is 375mg : HIGH-G THRESHOLD Threshold of high-g interrupt according to accel g range g-range High-g threshold 2g (thres_u8 * 7.81) mg 4g (thres_u8 * 15.63) mg 8g (thres_u8 * 31.25) mg 16g (thres_u8 * 62.5) mg : SLOPE THRESHOLD Threshold of slope interrupt according to accel g range g-range Slope threshold 2g (thres_u8 * 3.19) mg 4g (thres_u8 * 7.81) mg 8g (thres_u8 * 15.63) mg 16g (thres_u8 * 31.25) mg : SLOW NO MOTION THRESHOLD Threshold of slow no motion interrupt according to accel g range g-range slow no motion threshold 2g (thres_u8 * 3.19) mg 4g (thres_u8 * 7.81) mg 8g (thres_u8 * 15.63) mg 16g (thres_u8 * 31.25) mg results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_LOW_THRES, bma2x2_t::dev_addr, BMA2x2_LOW_THRES_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_HIGH_THRES, BMA2x2_HIGH_THRES_ADDR, BMA2x2_SLOPE_THRES, BMA2x2_SLOPE_THRES_ADDR, BMA2x2_SLOW_NO_MOTION_THRES, BMA2x2_SLOW_NO_MOTION_THRES_ADDR, E_OUT_OF_RANGE.
Referenced by configureSlopeInterrupt.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_low_high_g_hyst(u8 channel_u8, u8 *hyst_u8)
This API is used to get the low high hysteresis in the registers 0x24.
LOW_G_HYST -> bit form 0 to 1 HIGH_G_HYST -> bit from 6 to 7 channel_u8 The value of hysteresis selection channel_u8 result 0 BMA2x2_ACCEL_LOW_G_HYST 1 BMA2x2_ACCEL_HIGH_G_HYST hyst_u8 The hysteresis data LOW HYSTERESIS Hysteresis of low-g interrupt according to (hyst_u8 * 125)mg HIGH HYSTERESIS High hysteresis depends on the accel range selection g-range High Hysteresis 2g (thres_u8 * 125) mg 4g (thres_u8 * 250) mg 8g (thres_u8 * 500) mg 16g (thres_u8 * 1000) mg results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_LOW_G_HYST, bma2x2_t::dev_addr, BMA2x2_LOW_G_HYST_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_HIGH_G_HYST, BMA2x2_HIGH_G_HYST_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_low_high_g_hyst(u8 channel_u8, u8 hyst_u8)
This API is used to set the low high hysteresis in the registers 0x24.
LOW_G_HYST -> bit form 0 to 1 HIGH_G_HYST -> bit from 6 to 7 channel_u8 The value of hysteresis selection channel_u8 result 0 BMA2x2_ACCEL_LOW_G_HYST 1 BMA2x2_ACCEL_HIGH_G_HYST hyst_u8 The hysteresis data LOW HYSTERESIS Hysteresis of low-g interrupt according to (hyst_u8 * 125)mg HIGH HYSTERESIS High hysteresis depends on the accel range selection g-range High Hysteresis 2g (thres_u8 * 125) mg 4g (thres_u8 * 250) mg 8g (thres_u8 * 500) mg 16g (thres_u8 * 1000) mg results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_LOW_G_HYST, bma2x2_t::dev_addr, BMA2x2_LOW_G_HYST_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_HIGH_G_HYST, BMA2x2_HIGH_G_HYST_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_low_g_mode(u8 *low_g_mode_u8)
This API is used to get low_g mode in the registers 0x24 bit 2.
low_g_mode_u8 The value of Low_G mode low_g_mode_u8 g-result 0x00 LOW_G_SINGLE_AXIS_MODE 0x01 LOW_G_SUMMING_MODE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_LOW_G_INTR_MODE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_low_g_mode(u8 low_g_mode_u8)
This API is used to set low_g mode in the registers 0x24 bit 2.
low_g_mode_u8 The value of Low_G mode low_g_mode_u8 result 0x00 LOW_G_SINGLE_AXIS_MODE 0x01 LOW_G_SUMMING_MODE results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_LOW_G_INTR_MODE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_tap_durn(u8 *tap_durn_u8)
This API is used to get the tap duration in the register 0x2A bit form 0 to 2.
tap_durn_u8 The value of tap duration tap_durn_u8 result 0x00 TAP_DURN_50_MS 0x01 TAP_DURN_100_MS 0x02 TAP_DURN_150_MS 0x03 TAP_DURN_200_MS 0x04 TAP_DURN_250_MS 0x05 TAP_DURN_375_MS 0x06 TAP_DURN_500_MS 0x07 TAP_DURN_700_MS results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_TAP_DURN_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_tap_durn(u8 tap_durn_u8)
This API is used to set the tap duration in the register 0x2A bit form 0 to 2.
tap_durn_u8 The value of tap duration tap_durn_u8 result 0x00 TAP_DURN_50_MS 0x01 TAP_DURN_100_MS 0x02 TAP_DURN_150_MS 0x03 TAP_DURN_200_MS 0x04 TAP_DURN_250_MS 0x05 TAP_DURN_375_MS 0x06 TAP_DURN_500_MS 0x07 TAP_DURN_700_MS results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_TAP_DURN_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_tap_shock(u8 *tap_shock_u8)
This API is used to get the tap shock form the register 0x2A bit 6.
tap_shock_u8 The value of tap shock tap_shock_u8 result 0x00 TAP_SHOCK_50_MS 0x01 TAP_SHOCK_75_MS results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_TAP_SHOCK_DURN_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_tap_shock(u8 tap_shock_u8)
This API is used to set the tap shock form the register 0x2A bit 6.
tap_shock_u8 The value of tap shock tap_shock_u8 result 0x00 TAP_SHOCK_50_MS 0x01 TAP_SHOCK_75_MS results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_TAP_SHOCK_DURN_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_tap_quiet(u8 *tap_quiet_u8)
This API is used to get the tap quiet in the register 0x2A bit 7.
tap_quiet_u8 : The value of tap quiet tap_quiet_u8 result 0x00 TAP_QUIET_30_MS 0x01 TAP_QUIET_20_MS results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_TAP_QUIET_DURN_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_tap_quiet(u8 tap_quiet_u8)
This API is used to set the tap quiet in the register 0x2A bit 7.
tap_quiet_u8 : The value of tap quiet tap_quiet_u8 result 0x00 TAP_QUIET_30_MS 0x01 TAP_QUIET_20_MS results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_TAP_QUIET_DURN_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_tap_thres(u8 *tap_thres_u8)
This API is used to get the tap threshold in the register 0x2B bit from 0 to 4.
tap_thres_u8 : The value of tap threshold Tap threshold of single and double tap corresponding to accel range range Tap threshold 2g (tap_thres_u8 * 62.5)mg 4g (tap_thres_u8 * 125)mg 8g (tap_thres_u8 * 250)mg 16g (tap_thres_u8 * 500)mg results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_TAP_THRES_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_tap_thres(u8 tap_thres_u8)
This API is used to set the tap threshold in the register 0x2B bit from 0 to 4.
tap_thres_u8 : The value of tap threshold Tap threshold of single and double tap corresponding to accel range range Tap threshold 2g (tap_thres_u8 * 62.5)mg 4g (tap_thres_u8 * 125)mg 8g (tap_thres_u8 * 250)mg 16g (tap_thres_u8 * 500)mg results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_TAP_THRES_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_tap_sample(u8 *tap_sample_u8)
This API is used to get the tap sample in the register 0x2B bit 6 and 7.
*tap_sample_u8 : The value of tap sample tap_sample_u8 result 0x00 2 samples 0x01 4 samples 0x02 8 samples 0x03 16 samples results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_TAP_SAMPLES_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_tap_sample(u8 tap_sample_u8)
This API is used to set the tap sample in the register 0x2B bit 6 and 7.
*tap_sample_u8 : The value of tap sample tap_sample_u8 result 0x00 2 samples 0x01 4 samples 0x02 8 samples 0x03 16 samples results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_TAP_SAMPLES_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_orient_mode(u8 *orient_mode_u8)
This API is used to get the orient mode in the register 0x2C bit 0 and 1.
orient_mode_u8 : The value of orient mode orient_mode_u8 result 0x00 symmetrical 0x01 high asymmetrical 0x02 low asymmetrical 0x03 symmetrical results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ORIENT_MODE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_orient_mode(u8 orient_mode_u8)
This API is used to set the orient mode in the register 0x2C bit 0 and 1.
orient_mode_u8 : The value of orient mode orient_mode_u8 result 0x00 symmetrical 0x01 high asymmetrical 0x02 low asymmetrical 0x03 symmetrical results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ORIENT_MODE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_orient_block(u8 *orient_block_u8)
This API is used to get the orient block in the register 0x2C bit 2 and 3.
orient_block_u8 : The value of orient block orient_mode_u8 result 0x00 no blocking 0x01 theta blocking or | acceleration slope in any axis > 1.5g 0x02 | theta blocking or | acceleration slope in any axis > 0.2g | acceleration in any axis > 1.5g 0x03 | theta blocking or | acceleration slope in any axis > 0.4g | acceleration in any axis > 1.5g | value of orient is not stable for at lease 100ms results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ORIENT_BLOCK_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_orient_block(u8 orient_block_u8)
This API is used to set the orient block in the register 0x2C bit 2 and 3.
orient_block_u8 : The value of orient block orient_mode_u8 result 0x00 no blocking 0x01 theta blocking or | acceleration slope in any axis > 1.5g 0x02 | theta blocking or | acceleration slope in any axis > 0.2g | acceleration in any axis > 1.5g 0x03 | theta blocking or | acceleration slope in any axis > 0.4g | acceleration in any axis > 1.5g | value of orient is not stable for at lease 100ms results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ORIENT_BLOCK_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_orient_hyst(u8 *orient_hyst_u8)
This API is used to get the orient hysteresis in the register 0x2C bit 4 to 6.
orient_hyst_u8 : The value of orient hysteresis results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ORIENT_HYST_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_orient_hyst(u8 orient_hyst_u8)
This API is used to set the orient hysteresis in the register 0x2C bit 4 to 6.
orient_hyst_u8 : The value of orient hysteresis results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ORIENT_HYST_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_theta(u8 channel_u8, u8 *theta_u8)
This API is used to get the theta value of orient and flat interrupts.
ORIENT_THETA -> register 0x2D bit 0 to 5 FLAT_THETA -> register 0x2E bit 0 to 5 channel_u8 The value of theta selection channel_u8 result 0x00 BMA2x2_ACCEL_ORIENT_THETA 0x01 BMA2x2_ACCEL_FLAT_THETA FLAT_THETA : Defines a blocking angle between 0 deg to 44.8 deg ORIENT_THETA : Defines threshold for detection of flat position in range from 0 deg to 44.8 deg theta_u8 The value of theta results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_ORIENT_THETA, bma2x2_t::dev_addr, BMA2x2_THETA_BLOCK_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_FLAT_THETA, BMA2x2_THETA_FLAT_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_theta(u8 channel_u8, u8 theta_u8)
This API is used to set the theta value of orient and flat interrupts.
ORIENT_THETA -> register 0x2D bit 0 to 5 FLAT_THETA -> register 0x2E bit 0 to 5 channel_u8 The value of theta selection channel_u8 result 0x00 BMA2x2_ACCEL_ORIENT_THETA 0x01 BMA2x2_ACCEL_FLAT_THETA FLAT_THETA : Defines a blocking angle between 0 deg to 44.8 deg ORIENT_THETA : Defines threshold for detection of flat position in range from 0 deg to 44.8 deg theta_u8 The value of theta results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_ORIENT_THETA, bma2x2_t::dev_addr, BMA2x2_THETA_BLOCK_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_FLAT_THETA, BMA2x2_THETA_FLAT_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_orient_enable(u8 *orient_enable_u8)
This API is used to get the interrupt enable of orient ud_enable in the register 0x2D bit 6.
orient_enable_u8 : The value of orient ud_enable orient_enable_u8 result 0x00 Generates Interrupt 0x01 Do not generate interrupt results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ORIENT_UD_ENABLE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_orient_enable(u8 orient_enable_u8)
This API is used to set the interrupt enable of orient ud_enable in the register 0x2D bit 6.
orient_enable_u8 : The value of orient ud_enable orient_enable_u8 result 0x00 Generates Interrupt 0x01 Do not generate interrupt results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ORIENT_UD_ENABLE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_flat_hyst(u8 *flat_hyst_u8)
This API is used to get the interrupt enable of flat hysteresis("flat_hy) in the register 0x2F bit 0 to 2.
flat_hyst_u8 : The value of flat hysteresis results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_FLAT_HYST_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_flat_hyst(u8 flat_hyst_u8)
This API is used to set the interrupt enable of flat hysteresis("flat_hy) in the register 0x2F bit 0 to 2.
flat_hyst_u8 : The value of flat hysteresis results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_FLAT_HYST_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_flat_hold_time(u8 *flat_hold_time_u8)
This API is used to get the interrupt enable of flat hold time(flat_hold_time) in the register 0x2F bit 4 and 5.
flat_hold_time_u8 : The value of flat hold time flat_hold_time_u8 result 0x00 0ms 0x01 512ms 0x02 1024ms 0x03 2048ms results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_FLAT_HOLD_TIME_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_flat_hold_time(u8 flat_hold_time_u8)
This API is used to set the interrupt enable of flat hold time(flat_hold_time) in the register 0x2F bit 4 and 5.
flat_hold_time_u8 : The value of flat hold time flat_hold_time_u8 result 0x00 0ms 0x01 512ms 0x02 1024ms 0x03 2048ms results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_FLAT_HOLD_TIME_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_fifo_wml_trig(u8 *fifo_wml_trig)
This API is used to get the fifo water mark level trigger in the register 0x30 bit from 0 to 5.
fifo_wml_trig The value of fifo watermark trigger level results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_FIFO_WML_TRIG_RETAIN_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_fifo_wml_trig(u8 fifo_wml_trig)
This API is used to set the fifo water mark level trigger in the register 0x30 bit from 0 to 5.
fifo_wml_trig The value of fifo watermark trigger level results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_FIFO_WML_RANGE, bma2x2_t::dev_addr, BMA2x2_FIFO_WML_TRIG_RETAIN_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_selftest_axis(u8 *selftest_axis_u8)
This API is for to get the self test axis(self_test_axis) in the register ox32 bit 0 to 2.
selftest_axis_u8 : The value of selftest axis selftest_axis_u8 result 0x00 self test disable 0x01 x-axis 0x02 y-axis 0x03 z-axis results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ENABLE_SELFTEST_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_selftest_axis(u8 selftest_axis_u8)
This API is for to set the self test axis(self_test_axis) in the register ox32 bit 0 to 2.
selftest_axis_u8 : The value of selftest axis selftest_axis_u8 result 0x00 self test disable 0x01 x-axis 0x02 y-axis 0x03 z-axis results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_SELF_TEST_AXIS_RANGE, bma2x2_t::dev_addr, BMA2x2_ENABLE_SELFTEST_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_selftest_sign(u8 *selftest_sign_u8)
This API is for to get the Self Test sign(selftest_sign) in the register 0x32 bit 2.
selftest_sign_u8 : The value of self test sign selftest_sign_u8 result 0x00 negative sign 0x01 positive sign results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_NEG_SELFTEST_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_selftest_sign(u8 selftest_sign_u8)
This API is for to set the Self Test sign(selftest_sign) in the register 0x32 bit 2.
selftest_sign_u8 : The value of self test sign selftest_sign_u8 result 0x00 negative sign 0x01 positive sign results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_SELF_TEST_SIGN_RANGE, bma2x2_t::dev_addr, BMA2x2_NEG_SELFTEST_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_nvmprog_mode(u8 *nvmprog_mode_u8)
This API is used to get the nvm program mode(nvm_prog_mode)in the register 0x33 bit 0.
nvmprog_mode_u8 : The value of nvm program mode nvmprog_mode_u8 result 0x00 Disable program mode 0x01 Enable program mode results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_UNLOCK_EE_PROG_MODE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_nvmprog_mode(u8 nvmprog_mode_u8)
This API is used to set the nvm program mode(nvm_prog_mode)in the register 0x33 bit 0.
nvmprog_mode_u8 : The value of nvm program mode nvmprog_mode_u8 result 0x00 Disable program mode 0x01 Enable program mode results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_UNLOCK_EE_PROG_MODE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_nvprog_trig(u8 nvprog_trig_u8)
This API is used to set the value of nvm program trig in the register 0x33 bit 1.
nvprog_trig_u8 The value of nvm program trig nvprog_trig_u8 result 0x00 Do not trigger nvm program 0x01 Trigger nvm program results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_START_EE_PROG_TRIG_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_nvmprog_ready(u8 *nvprog_ready_u8)
This API is used to get the nvm program ready in the register bit 2.
nvprog_ready_u8 The value of nvm program ready nvprog_ready_u8 result 0x00 nvm write/update operation is in progress 0x01 nvm is ready to accept a new write results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_EE_PROG_READY_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_nvmprog_remain(u8 *nvprog_remain_u8)
This API is used to set the nvm program ready in the register bit 2.
nvprog_remain_u8 The value of nvm program ready nvprog_remain_u8 result 0x00 nvm write/update operation is in progress 0x01 nvm is ready to accept a new write results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_EE_REMAIN_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_spi3(u8 *spi3_u8)
This API is used to get the enable status of spi3 in the register 0x34 bit 0.
spi3_u8 : The value of SPI 3 or 4 wire enable spi3_u8 result 0x00 spi4 0x01 spi3 results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ENABLE_SPI_MODE_3_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_spi3(u8 spi3_u8)
This API is used to set the enable status of spi3 in the register 0x34 bit 0.
spi3_u8 : The value of SPI 3 or 4 wire enable spi3_u8 result 0x00 spi4 0x01 spi3 results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_ENABLE_SPI_MODE_3_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_i2c_wdt(u8 channel_u8, u8 *i2c_wdt_u8)
This API is used to get the i2c watch dog timer period and I2C interface mode is selected in the register 0x34 bit 1 and 2.
channel_u8 The i2c option selection channel_u8 result 0 BMA2x2_ACCEL_I2C_SELECT 1 BMA2x2_ACCEL_I2C_ENABLE i2c_wdt_u8 watch dog timer period and I2C interface mode is selected BMA2x2_ACCEL_I2C_SELECTresult 0x00 Disable the watchdog at SDI pin 0x01 Enable watchdog BMA2x2_I2C_ENABLE result 0x00 1ms 0x01 50ms results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_I2C_SELECT, bma2x2_t::dev_addr, BMA2x2_I2C_WDT_PERIOD_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_I2C_ENABLE, BMA2x2_ENABLE_I2C_WDT_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_i2c_wdt(u8 channel_u8, u8 i2c_wdt_u8)
This API is used to set the i2c watch dog timer period and I2C interface mode is selected in the register 0x34 bit 1 and 2.
channel_u8 The i2c option selection channel_u8 result 0 BMA2x2_ACCEL_I2C_SELECT 1 BMA2x2_ACCEL_I2C_ENABLE i2c_wdt_u8 watch dog timer period and I2C interface mode is selected BMA2x2_ACCEL_I2C_SELECTresult 0x00 Disable the watchdog at SDI pin 0x01 Enable watchdog BMA2x2_I2C_ENABLE result 0x00 1ms 0x01 50ms results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_I2C_SELECT, bma2x2_t::dev_addr, BMA2x2_I2C_WDT_PERIOD_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_I2C_ENABLE, BMA2x2_ENABLE_I2C_WDT_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_slow_comp(u8 channel_u8, u8 *slow_comp_u8)
This API is used to get slow compensation(hp_x_enable, hp_y_enable and hp_z_enable) enable in the register 0x36 bit 0 to 2.
SLOW_COMP_X -> bit 0 SLOW_COMP_Y -> bit 1 SLOW_COMP_Z -> bit 2 channel_u8 The value of slow compensation selection channel_u8 result 0 BMA2x2_ACCEL_SLOW_COMP_X 1 BMA2x2_ACCEL_SLOW_COMP_Y 2 BMA2x2_ACCEL_SLOW_COMP_Z slow_comp_u8 The value of slow compensation enable slow_comp_u8 result 0x00 Disable 0x01 Enable results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_SLOW_COMP_X, bma2x2_t::dev_addr, BMA2x2_ENABLE_SLOW_COMP_X_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_SLOW_COMP_Y, BMA2x2_ENABLE_SLOW_COMP_Y_REG, BMA2x2_SLOW_COMP_Z, BMA2x2_ENABLE_SLOW_COMP_Z_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_slow_comp(u8 channel_u8, u8 slow_comp_u8)
This API is used to set slow compensation(hp_x_enable, hp_y_enable and hp_z_enable) enable in the register 0x36 bit 0 to 2.
SLOW_COMP_X -> bit 0 SLOW_COMP_Y -> bit 1 SLOW_COMP_Z -> bit 2 channel_u8 The value of slow compensation selection channel_u8 result 0 BMA2x2_ACCEL_SLOW_COMP_X 1 BMA2x2_ACCEL_SLOW_COMP_Y 2 BMA2x2_ACCEL_SLOW_COMP_Z slow_comp_u8 The value of slow compensation enable slow_comp_u8 result 0x00 Disable 0x01 Enable results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_SLOW_COMP_X, bma2x2_t::dev_addr, BMA2x2_ENABLE_SLOW_COMP_X_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_SLOW_COMP_Y, BMA2x2_ENABLE_SLOW_COMP_Y_REG, BMA2x2_SLOW_COMP_Z, BMA2x2_ENABLE_SLOW_COMP_Z_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_cal_rdy(u8 *cal_rdy_u8)
This API is used to get the status of fast offset compensation(cal_rdy) in the register 0x36 bit 4(Read Only Possible)
cal_rdy_u8 The value of cal_ready results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_FAST_CAL_RDY_STAT_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_cal_trigger(u8 cal_trigger_u8)
This API is used to set the status of fast offset compensation(cal_rdy) in the register 0x36 bit 4(Read Only Possible)
cal_trigger_u8 The value of cal_ready results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_CAL_TRIGGER_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_offset_rst(u8 offset_rst_u8)
This API is used to set the offset reset(offset_reset) in the register 0x36 bit 7(Write only possible)
offset_rst_u8 The offset reset value results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_RST_OFFSET_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_offset_target(u8 channel_u8, u8 *offset_u8)
This API is used to get the status of offset target axis(offset_target_x, offset_target_y and offset_target_z) and cut_off in the register 0x37.
CUT_OFF -> bit 0 OFFSET_TRIGGER_X -> bit 1 and 2 OFFSET_TRIGGER_Y -> bit 3 and 4 OFFSET_TRIGGER_Z -> bit 5 and 6 channel_u8 The value of offset axis selection channel_u8 result 0 BMA2x2_ACCEL_CUT_OFF 1 BMA2x2_ACCEL_OFFSET_TRIGGER_X 2 BMA2x2_ACCEL_OFFSET_TRIGGER_Y 2 BMA2x2_ACCEL_OFFSET_TRIGGER_Z offset_u8 The offset target value CUT_OFF result 0 1Hz 1 10Hz OFFSET_TRIGGER result 0x00 0g 0x01 +1g 0x02 -1g 0x03 0g results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_CUT_OFF, bma2x2_t::dev_addr, BMA2x2_COMP_CUTOFF_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE, BMA2x2_OFFSET_TRIGGER_X, BMA2x2_COMP_TARGET_OFFSET_X_REG, BMA2x2_OFFSET_TRIGGER_Y, BMA2x2_COMP_TARGET_OFFSET_Y_REG, BMA2x2_OFFSET_TRIGGER_Z, BMA2x2_COMP_TARGET_OFFSET_Z_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_offset_target(u8 channel_u8, u8 offset_u8)
This API is used to set the status of offset target axis(offset_target_x, offset_target_y and offset_target_z) and cut_off in the register 0x37.
CUT_OFF -> bit 0 OFFSET_TRIGGER_X -> bit 1 and 2 OFFSET_TRIGGER_Y -> bit 3 and 4 OFFSET_TRIGGER_Z -> bit 5 and 6 channel_u8 The value of offset axis selection channel_u8 result 0 BMA2x2_ACCEL_CUT_OFF 1 BMA2x2_ACCEL_OFFSET_TRIGGER_X 2 BMA2x2_ACCEL_OFFSET_TRIGGER_Y 2 BMA2x2_ACCEL_OFFSET_TRIGGER_Z offset_u8 The offset target value CUT_OFF result 0 1Hz 1 10Hz OFFSET_TRIGGER result 0x00 0g 0x01 +1g 0x02 -1g 0x03 0g results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_CUT_OFF, bma2x2_t::dev_addr, BMA2x2_COMP_CUTOFF_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, BMA2x2_OFFSET_TRIGGER_X, BMA2x2_COMP_TARGET_OFFSET_X_REG, BMA2x2_OFFSET_TRIGGER_Y, BMA2x2_COMP_TARGET_OFFSET_Y_REG, BMA2x2_OFFSET_TRIGGER_Z, BMA2x2_COMP_TARGET_OFFSET_Z_REG, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_offset(u8 channel_u8, s8 *offset_u8)
This API is used to get the status of offset (offset_x, offset_y and offset_z) in the registers 0x38,0x39 and 0x3A.
offset_x -> register 0x38 bit 0 to 7 offset_y -> register 0x39 bit 0 to 7 offset_z -> register 0x3A bit 0 to 7 channel_u8 The value of offset selection channel_u8 result 0 BMA2x2_ACCEL_X_AXIS 1 BMA2x2_ACCEL_Y_AXIS 2 BMA2x2_ACCEL_Z_AXIS offset_u8 The value of offset results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_X_AXIS, bma2x2_t::dev_addr, BMA2x2_OFFSET_X_AXIS_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_Y_AXIS, BMA2x2_OFFSET_Y_AXIS_ADDR, BMA2x2_Z_AXIS, BMA2x2_OFFSET_Z_AXIS_ADDR, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_offset(u8 channel_u8, s8 offset_u8)
This API is used to set the status of offset (offset_x, offset_y and offset_z) in the registers 0x38,0x39 and 0x3A.
offset_x -> register 0x38 bit 0 to 7 offset_y -> register 0x39 bit 0 to 7 offset_z -> register 0x3A bit 0 to 7 channel_u8 The value of offset selection channel_u8 result 0 BMA2x2_ACCEL_X_AXIS 1 BMA2x2_ACCEL_Y_AXIS 2 BMA2x2_ACCEL_Z_AXIS offset_u8 The value of offset results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_X_AXIS, bma2x2_t::dev_addr, BMA2x2_OFFSET_X_AXIS_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_Y_AXIS, BMA2x2_OFFSET_Y_AXIS_ADDR, BMA2x2_Z_AXIS, BMA2x2_OFFSET_Z_AXIS_ADDR, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_fifo_mode(u8 *fifo_mode_u8)
This API is used to get the status of fifo (fifo_mode) in the register 0x3E bit 6 and 7.
fifo_mode_u8 : The value of fifo mode fifo_mode_u8 result 0x00 BYPASS 0x01 FIFO 0x02 STREAM 0x03 RESERVED results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_FIFO_MODE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_fifo_mode(u8 fifo_mode_u8)
This API is used to set the status of fifo (fifo_mode) in the register 0x3E bit 6 and 7.
fifo_mode_u8 : The value of fifo mode fifo_mode_u8 result 0x00 BYPASS 0x01 FIFO 0x02 STREAM 0x03 RESERVED results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_FIFO_MODE_RANGE, bma2x2_t::dev_addr, BMA2x2_FIFO_MODE_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, SUCCESS, bma2x2_read_reg, bma2x2_t::fifo_config, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_fifo_data_select(u8 *fifo_data_select_u8)
This API is used to get the axis enable of fifo data select in the register 0x3E bit 0 and 1.
fifo_data_select_u8 : The value of FIFO axis data select fifo_data_select_u8 result 0x00 XYZ 0x01 Y 0x02 X 0x03 Z results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_FIFO_DATA_SELECT_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_GET_BITSLICE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_set_fifo_data_select(u8 fifo_data_select_u8)
This API is used to set the axis enable of fifo data select in the register 0x3E bit 0 and 1.
fifo_data_select_u8 : The value of FIFO axis data select fifo_data_select_u8 result 0x00 XYZ 0x01 Y 0x02 X 0x03 Z results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, BMA2x2_FIFO_DATA_SELECT_RANGE, bma2x2_t::dev_addr, BMA2x2_FIFO_DATA_SELECT_REG, BMA2x2_GEN_READ_WRITE_LENGTH, BMA2x2_SET_BITSLICE, SUCCESS, bma2x2_read_reg, BMA2x2_FIFO_MODE_REG, bma2x2_t::fifo_config, E_OUT_OF_RANGE.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_get_fifo_data_output_reg(u8 *output_reg_u8)
This API is used to get the fifo data in the register 0x3F bit 0 to 7.
output_reg_u8 : The value of fifo data results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_FIFO_DATA_OUTPUT_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_read_temp(s8 *temp_s8)
This API is used to read the temp from register 0x08.
temp_s8 The value of temperature results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_INIT_VALUE, BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_TEMP_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_read_accel_xyzt(struct bma2x2_accel_data_temp *accel)
This API reads accelerometer data X,Y,Z values and temperature data from location 02h to 08h.
accel : The value of accel xyz and temperature data results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_ACCEL_XYZ_TEMP_DATA_SIZE, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, V_BMA2x2RESOLUTION_U8, BMA2x2_12_RESOLUTION, bma2x2_t::dev_addr, BMA2x2_ACCEL_X12_LSB_REG, BMA2x2_ACCEL_BW_MIN_RANGE, bma2x2_accel_data_temp::x, BMA2x2_SENSOR_DATA_XYZ_X_MSB, BMA2x2_SHIFT_EIGHT_BITS, BMA2x2_SENSOR_DATA_XYZ_X_LSB, BMA2x2_12_BIT_SHIFT, BMA2x2_SHIFT_FOUR_BITS, bma2x2_accel_data_temp::y, BMA2x2_SENSOR_DATA_XYZ_Y_MSB, BMA2x2_SENSOR_DATA_XYZ_Y_LSB, bma2x2_accel_data_temp::z, BMA2x2_SENSOR_DATA_XYZ_Z_MSB, BMA2x2_SENSOR_DATA_XYZ_Z_LSB, bma2x2_accel_data_temp::temp, BMA2x2_SENSOR_DATA_TEMP, BMA2x2_10_RESOLUTION, BMA2x2_ACCEL_X10_LSB_REG, BMA2x2_10_BIT_SHIFT, BMA2x2_SHIFT_SIX_BITS, BMA2x2_14_RESOLUTION, BMA2x2_ACCEL_X14_LSB_REG, BMA2x2_14_BIT_SHIFT, BMA2x2_SHIFT_TWO_BITS.
BMA2x2_RETURN_FUNCTION_TYPE bma2x2_read_accel_eight_resolution_xyzt(struct bma2x2_accel_eight_resolution_temp *accel)
This API reads accelerometer data X,Y,Z values and temperature data from location 0x02 to 0x08.
accel : The value of accel xyz and temperature data results of bus communication function 0 -> Success -1 -> Error
References BMA2x2_RETURN_FUNCTION_TYPE, ERROR, BMA2x2_INIT_VALUE, BMA2x2_NULL, E_BMA2x2_NULL_PTR, bma2x2_t::dev_addr, BMA2x2_X_AXIS_MSB_ADDR, BMA2x2_GEN_READ_WRITE_LENGTH, bma2x2_accel_eight_resolution_temp::x, BMA2x2_GET_BITSLICE, BMA2x2_Y_AXIS_MSB_ADDR, bma2x2_accel_eight_resolution_temp::y, BMA2x2_Z_AXIS_MSB_ADDR, bma2x2_accel_eight_resolution_temp::z, BMA2x2_TEMP_ADDR, bma2x2_accel_eight_resolution_temp::temp.