bme280.h
BME280_ENABLE_FLOAT
If the user wants to support floating point calculations, please set the following define. If floating point calculation is not wanted or allowed (e.g. in Linux kernel), please do not set the define.
BME280_ENABLE_INT64
If the user wants to support 64 bit integer calculation (needed for optimal pressure accuracy) please set the following define. If int64 calculation is not wanted (e.g. because it would include large libraries), please do not set the define.
BME280_BUS_WR_RETURN_TYPE
Define the calling convention of YOUR bus communication routine.
This includes types of parameters. This example shows the configuration for an SPI bus link. If your communication function looks like this:write_my_bus_xy(u8 device_addr, u8 register_addr, u8 * data, u8 length);The BME280_WR_FUNC_PTR would equal:BME280_WR_FUNC_PTR s8 (* bus_write)(u8, u8, u8 *, u8)Parameters can be mixed as needed refer to the refer BME280_BUS_WRITE_FUNC macro.defines the return parameter type of the BME280_WR_FUNCTION
BME280_BUS_WR_PARAM_TYPES
BME280_BUS_WR_PARAM_ORDER
BME280_BUS_WRITE_FUNC
BME280_BUS_RD_RETURN_TYPE
link macro between API function calls and bus read function
The bus write function can change since this is a system dependant issue. If the bus_read parameter calling order is like: reg_addr, reg_data, wr_len it would be as it is here.If the parameters are differently ordered or your communication function like I2C need to know the device address, you can change this macro accordingly.BME280_BUS_READ_FUNC(dev_addr, reg_addr, reg_data, wr_len)\ bus_read(dev_addr, reg_addr, reg_data, wr_len)This macro lets all API functions call YOUR communication routine in a way that equals your definition in the refer BME280_WR_FUNC_PTR definition.: this macro also includes the "MSB='1' for reading BME280 addresses.
BME280_BUS_RD_PARAM_TYPES
defines the calling parameter types of the BME280_RD_FUNCTION
BME280_BUS_RD_PARAM_ORDER
BME280_BUS_READ_FUNC
BME280_WR_FUNC_PTR
BME280_RD_FUNC_PTR
BME280_MDELAY_DATA_TYPE
BME280_3MS_DELAY
Referenced by bme280_set_oversamp_temperature, bme280_set_oversamp_pressure, bme280_set_oversamp_humidity, bme280_set_power_mode, bme280_set_spi3, bme280_set_filter, bme280_set_standby_durn, bme280_get_forced_uncomp_pressure_temperature_humidity.
BME280_REGISTER_READ_DELAY
Referenced by bme280_init.
BME280_DELAY_RETURN_TYPE
BME280_DELAY_PARAM_TYPES
BME280_DELAY_FUNC
BME280_GET_BITSLICE
Referenced by bme280_get_oversamp_temperature, bme280_get_oversamp_pressure, bme280_get_oversamp_humidity, bme280_get_power_mode, bme280_get_spi3, bme280_get_filter, bme280_get_standby_durn.
BME280_SET_BITSLICE
Referenced by bme280_set_oversamp_temperature, bme280_set_oversamp_pressure, bme280_set_oversamp_humidity, bme280_set_power_mode, bme280_set_spi3, bme280_set_filter, bme280_set_standby_durn, bme280_get_forced_uncomp_pressure_temperature_humidity.
BME280_NULL
Referenced by bme280_read_uncomp_temperature, bme280_read_uncomp_pressure, bme280_read_uncomp_humidity, bme280_read_uncomp_pressure_temperature_humidity, bme280_read_pressure_temperature_humidity, bme280_get_calib_param, bme280_get_oversamp_temperature, bme280_set_oversamp_temperature, bme280_get_oversamp_pressure, bme280_set_oversamp_pressure, bme280_get_oversamp_humidity, bme280_set_oversamp_humidity, bme280_get_power_mode, bme280_set_power_mode, bme280_set_soft_rst, bme280_get_spi3, bme280_set_spi3, bme280_get_filter, bme280_set_filter, bme280_get_standby_durn, bme280_set_standby_durn, bme280_get_forced_uncomp_pressure_temperature_humidity, bme280_write_register, bme280_read_register.
BME280_RETURN_FUNCTION_TYPE
Referenced by bme280_init, bme280_read_uncomp_temperature, bme280_read_uncomp_pressure, bme280_read_uncomp_humidity, bme280_read_uncomp_pressure_temperature_humidity, bme280_read_pressure_temperature_humidity, bme280_get_calib_param, bme280_get_oversamp_temperature, bme280_set_oversamp_temperature, bme280_get_oversamp_pressure, bme280_set_oversamp_pressure, bme280_get_oversamp_humidity, bme280_set_oversamp_humidity, bme280_get_power_mode, bme280_set_power_mode, bme280_set_soft_rst, bme280_get_spi3, bme280_set_spi3, bme280_get_filter, bme280_set_filter, bme280_get_standby_durn, bme280_set_standby_durn, bme280_get_forced_uncomp_pressure_temperature_humidity, bme280_write_register, bme280_read_register, bme280_compute_wait_time, setOverSampling, Environmental_setPowerMode, Environmental_getPowerMode, Environmental_readData, Environmental_readDataLSB, Environmental_readTemperatureLSB, Environmental_readPressureLSB, Environmental_readHumidityLSB, Environmental_setStandbyDuration, Environmental_getStandbyDuration, Environmental_setFilterCoefficient, Bme280Utils_initialize.
BME280_SHIFT_BIT_POSITION_BY_01_BIT
Referenced by bme280_compensate_temperature_int32, bme280_compensate_pressure_int32, bme280_compensate_humidity_int32_sixteen_bit_output, bme280_compensate_pressure_int64_twentyfour_bit_output, bme280_compute_wait_time.
BME280_SHIFT_BIT_POSITION_BY_02_BITS
Referenced by bme280_compensate_pressure_int32.
BME280_SHIFT_BIT_POSITION_BY_03_BITS
Referenced by bme280_compensate_temperature_int32, bme280_compensate_pressure_int32.
BME280_SHIFT_BIT_POSITION_BY_04_BITS
Referenced by bme280_read_uncomp_temperature, bme280_compensate_temperature_int32, bme280_read_uncomp_pressure, bme280_compensate_pressure_int32, bme280_compensate_humidity_int32, bme280_read_uncomp_pressure_temperature_humidity, bme280_get_calib_param, bme280_compensate_pressure_int64.
BME280_SHIFT_BIT_POSITION_BY_07_BITS
Referenced by bme280_compensate_humidity_int32.
BME280_SHIFT_BIT_POSITION_BY_08_BITS
Referenced by bme280_compensate_temperature_int32, bme280_compensate_temperature_int32_sixteen_bit_output, bme280_read_uncomp_humidity, bme280_read_uncomp_pressure_temperature_humidity, bme280_get_calib_param, bme280_compensate_pressure_int64.
BME280_SHIFT_BIT_POSITION_BY_10_BITS
Referenced by bme280_compensate_humidity_int32.
BME280_SHIFT_BIT_POSITION_BY_11_BITS
Referenced by bme280_compensate_temperature_int32, bme280_compensate_pressure_int32, bme280_compensate_humidity_int32.
BME280_SHIFT_BIT_POSITION_BY_12_BITS
Referenced by bme280_read_uncomp_temperature, bme280_compensate_temperature_int32, bme280_read_uncomp_pressure, bme280_compensate_pressure_int32, bme280_compensate_humidity_int32, bme280_read_uncomp_pressure_temperature_humidity, bme280_compensate_pressure_int64.
BME280_SHIFT_BIT_POSITION_BY_13_BITS
Referenced by bme280_compensate_pressure_int32, bme280_compensate_pressure_int64.
BME280_SHIFT_BIT_POSITION_BY_14_BITS
Referenced by bme280_compensate_temperature_int32, bme280_compensate_humidity_int32.
BME280_SHIFT_BIT_POSITION_BY_15_BITS
Referenced by bme280_compensate_pressure_int32, bme280_compensate_humidity_int32.
BME280_SHIFT_BIT_POSITION_BY_16_BITS
Referenced by bme280_compensate_pressure_int32.
BME280_SHIFT_BIT_POSITION_BY_17_BITS
Referenced by bme280_compensate_pressure_int64.
BME280_SHIFT_BIT_POSITION_BY_18_BITS
Referenced by bme280_compensate_pressure_int32.
BME280_SHIFT_BIT_POSITION_BY_19_BITS
Referenced by bme280_compensate_pressure_int64.
BME280_SHIFT_BIT_POSITION_BY_20_BITS
Referenced by bme280_compensate_humidity_int32.
BME280_SHIFT_BIT_POSITION_BY_25_BITS
Referenced by bme280_compensate_pressure_int64.
BME280_SHIFT_BIT_POSITION_BY_31_BITS
Referenced by bme280_compensate_pressure_int64.
BME280_SHIFT_BIT_POSITION_BY_33_BITS
Referenced by bme280_compensate_pressure_int64.
BME280_SHIFT_BIT_POSITION_BY_35_BITS
Referenced by bme280_compensate_pressure_int64.
BME280_SHIFT_BIT_POSITION_BY_47_BITS
Referenced by bme280_compensate_pressure_int64.
BME280_PRESSURE_TEMPERATURE_CALIB_DATA_LENGTH
Referenced by bme280_get_calib_param.
BME280_HUMIDITY_CALIB_DATA_LENGTH
Referenced by bme280_get_calib_param.
BME280_GEN_READ_WRITE_DATA_LENGTH
Referenced by bme280_init, bme280_get_oversamp_temperature, bme280_set_oversamp_temperature, bme280_get_oversamp_pressure, bme280_set_oversamp_pressure, bme280_get_oversamp_humidity, bme280_set_oversamp_humidity, bme280_get_power_mode, bme280_set_power_mode, bme280_set_soft_rst, bme280_get_spi3, bme280_set_spi3, bme280_get_filter, bme280_set_filter, bme280_get_standby_durn, bme280_set_standby_durn, bme280_get_forced_uncomp_pressure_temperature_humidity.
BME280_HUMIDITY_DATA_LENGTH
Referenced by bme280_read_uncomp_humidity.
BME280_TEMPERATURE_DATA_LENGTH
Referenced by bme280_read_uncomp_temperature.
BME280_PRESSURE_DATA_LENGTH
Referenced by bme280_read_uncomp_pressure.
BME280_ALL_DATA_FRAME_LENGTH
Referenced by bme280_read_uncomp_pressure_temperature_humidity.
BME280_INIT_VALUE
Referenced by bme280_init, bme280_read_uncomp_temperature, bme280_compensate_temperature_int32, bme280_compensate_temperature_int32_sixteen_bit_output, bme280_read_uncomp_pressure, bme280_compensate_pressure_int32, bme280_read_uncomp_humidity, bme280_compensate_humidity_int32, bme280_compensate_humidity_int32_sixteen_bit_output, bme280_read_uncomp_pressure_temperature_humidity, bme280_read_pressure_temperature_humidity, bme280_get_calib_param, bme280_get_oversamp_temperature, bme280_set_oversamp_temperature, bme280_get_oversamp_pressure, bme280_set_oversamp_pressure, bme280_get_oversamp_humidity, bme280_set_oversamp_humidity, bme280_get_power_mode, bme280_set_power_mode, bme280_get_spi3, bme280_set_spi3, bme280_get_filter, bme280_set_filter, bme280_get_standby_durn, bme280_set_standby_durn, bme280_get_forced_uncomp_pressure_temperature_humidity, bme280_compensate_temperature_double, bme280_compensate_pressure_double, bme280_compensate_humidity_double, bme280_compensate_pressure_int64, bme280_compensate_pressure_int64_twentyfour_bit_output.
BME280_CHIP_ID_READ_COUNT
Referenced by bme280_init.
BME280_INVALID_DATA
Referenced by bme280_compensate_pressure_int32, bme280_compensate_pressure_double, bme280_compensate_humidity_double, bme280_compensate_pressure_int64.
SUCCESS
E_BME280_NULL_PTR
Referenced by bme280_read_uncomp_temperature, bme280_read_uncomp_pressure, bme280_read_uncomp_humidity, bme280_read_uncomp_pressure_temperature_humidity, bme280_read_pressure_temperature_humidity, bme280_get_calib_param, bme280_get_oversamp_temperature, bme280_set_oversamp_temperature, bme280_get_oversamp_pressure, bme280_set_oversamp_pressure, bme280_get_oversamp_humidity, bme280_set_oversamp_humidity, bme280_get_power_mode, bme280_set_power_mode, bme280_set_soft_rst, bme280_get_spi3, bme280_set_spi3, bme280_get_filter, bme280_set_filter, bme280_get_standby_durn, bme280_set_standby_durn, bme280_get_forced_uncomp_pressure_temperature_humidity, bme280_write_register, bme280_read_register, bme280LibErrorMapping, libErrorMapping.
E_BME280_COMM_RES
E_BME280_OUT_OF_RANGE
Referenced by bme280_set_power_mode, Bme280Utils_initialize.
ERROR
BME280_CHIP_ID_READ_FAIL
Referenced by bme280_init.
BME280_CHIP_ID_READ_SUCCESS
Referenced by bme280_init.
BME280_CHIP_ID
Referenced by bme280_init.
BME280_I2C_ADDRESS1
BME280_I2C_ADDRESS2
BME280_SLEEP_MODE
Referenced by bme280_set_oversamp_temperature, bme280_set_oversamp_pressure, bme280_set_oversamp_humidity, bme280_set_power_mode, bme280_set_spi3, bme280_set_filter, bme280_set_standby_durn, bme280_get_forced_uncomp_pressure_temperature_humidity.
BME280_FORCED_MODE
Referenced by bme280_get_forced_uncomp_pressure_temperature_humidity.
BME280_NORMAL_MODE
Referenced by bme280_set_power_mode, Bme280Utils_initialize.
BME280_SOFT_RESET_CODE
Referenced by bme280_set_soft_rst.
BME280_STANDBY_TIME_1_MS
BME280_STANDBY_TIME_63_MS
BME280_STANDBY_TIME_125_MS
Referenced by Bme280Utils_initialize.
BME280_STANDBY_TIME_250_MS
BME280_STANDBY_TIME_500_MS
BME280_STANDBY_TIME_1000_MS
BME280_STANDBY_TIME_10_MS
BME280_STANDBY_TIME_20_MS
BME280_OVERSAMP_SKIPPED
BME280_OVERSAMP_1X
Referenced by Bme280Utils_initialize.
BME280_OVERSAMP_2X
Referenced by Bme280Utils_initialize.
BME280_OVERSAMP_4X
Referenced by Bme280Utils_initialize.
BME280_OVERSAMP_8X
BME280_OVERSAMP_16X
BME280_STANDARD_OVERSAMP_HUMIDITY
BME280_FILTER_COEFF_OFF
BME280_FILTER_COEFF_2
BME280_FILTER_COEFF_4
BME280_FILTER_COEFF_8
BME280_FILTER_COEFF_16
T_INIT_MAX
Referenced by bme280_compute_wait_time, bmp280_compute_wait_time.
T_MEASURE_PER_OSRS_MAX
Referenced by bme280_compute_wait_time, bmp280_compute_wait_time.
T_SETUP_PRESSURE_MAX
Referenced by bme280_compute_wait_time, bmp280_compute_wait_time.
T_SETUP_HUMIDITY_MAX
Referenced by bme280_compute_wait_time.
BME280_HUMIDITY_DATA_SIZE
Referenced by bme280_read_uncomp_humidity.
BME280_TEMPERATURE_DATA_SIZE
Referenced by bme280_read_uncomp_temperature.
BME280_PRESSURE_DATA_SIZE
Referenced by bme280_read_uncomp_pressure.
BME280_DATA_FRAME_SIZE
data frames includes temperature, pressure and humidity
Referenced by bme280_read_uncomp_pressure_temperature_humidity.
BME280_CALIB_DATA_SIZE
Referenced by bme280_get_calib_param.
BME280_TEMPERATURE_MSB_DATA
Referenced by bme280_read_uncomp_temperature.
BME280_TEMPERATURE_LSB_DATA
Referenced by bme280_read_uncomp_temperature.
BME280_TEMPERATURE_XLSB_DATA
Referenced by bme280_read_uncomp_temperature.
BME280_PRESSURE_MSB_DATA
Referenced by bme280_read_uncomp_pressure.
BME280_PRESSURE_LSB_DATA
Referenced by bme280_read_uncomp_pressure.
BME280_PRESSURE_XLSB_DATA
Referenced by bme280_read_uncomp_pressure.
BME280_HUMIDITY_MSB_DATA
Referenced by bme280_read_uncomp_humidity.
BME280_HUMIDITY_LSB_DATA
Referenced by bme280_read_uncomp_humidity.
BME280_DATA_FRAME_PRESSURE_MSB_BYTE
Referenced by bme280_read_uncomp_pressure_temperature_humidity.
BME280_DATA_FRAME_PRESSURE_LSB_BYTE
Referenced by bme280_read_uncomp_pressure_temperature_humidity.
BME280_DATA_FRAME_PRESSURE_XLSB_BYTE
Referenced by bme280_read_uncomp_pressure_temperature_humidity.
BME280_DATA_FRAME_TEMPERATURE_MSB_BYTE
Referenced by bme280_read_uncomp_pressure_temperature_humidity.
BME280_DATA_FRAME_TEMPERATURE_LSB_BYTE
Referenced by bme280_read_uncomp_pressure_temperature_humidity.
BME280_DATA_FRAME_TEMPERATURE_XLSB_BYTE
Referenced by bme280_read_uncomp_pressure_temperature_humidity.
BME280_DATA_FRAME_HUMIDITY_MSB_BYTE
Referenced by bme280_read_uncomp_pressure_temperature_humidity.
BME280_DATA_FRAME_HUMIDITY_LSB_BYTE
Referenced by bme280_read_uncomp_pressure_temperature_humidity.
BME280_TEMPERATURE_CALIB_DIG_T1_LSB
Referenced by bme280_get_calib_param.
BME280_TEMPERATURE_CALIB_DIG_T1_MSB
Referenced by bme280_get_calib_param.
BME280_TEMPERATURE_CALIB_DIG_T2_LSB
Referenced by bme280_get_calib_param.
BME280_TEMPERATURE_CALIB_DIG_T2_MSB
Referenced by bme280_get_calib_param.
BME280_TEMPERATURE_CALIB_DIG_T3_LSB
Referenced by bme280_get_calib_param.
BME280_TEMPERATURE_CALIB_DIG_T3_MSB
Referenced by bme280_get_calib_param.
BME280_PRESSURE_CALIB_DIG_P1_LSB
Referenced by bme280_get_calib_param.
BME280_PRESSURE_CALIB_DIG_P1_MSB
Referenced by bme280_get_calib_param.
BME280_PRESSURE_CALIB_DIG_P2_LSB
Referenced by bme280_get_calib_param.
BME280_PRESSURE_CALIB_DIG_P2_MSB
Referenced by bme280_get_calib_param.
BME280_PRESSURE_CALIB_DIG_P3_LSB
Referenced by bme280_get_calib_param.
BME280_PRESSURE_CALIB_DIG_P3_MSB
Referenced by bme280_get_calib_param.
BME280_PRESSURE_CALIB_DIG_P4_LSB
Referenced by bme280_get_calib_param.
BME280_PRESSURE_CALIB_DIG_P4_MSB
Referenced by bme280_get_calib_param.
BME280_PRESSURE_CALIB_DIG_P5_LSB
Referenced by bme280_get_calib_param.
BME280_PRESSURE_CALIB_DIG_P5_MSB
Referenced by bme280_get_calib_param.
BME280_PRESSURE_CALIB_DIG_P6_LSB
Referenced by bme280_get_calib_param.
BME280_PRESSURE_CALIB_DIG_P6_MSB
Referenced by bme280_get_calib_param.
BME280_PRESSURE_CALIB_DIG_P7_LSB
Referenced by bme280_get_calib_param.
BME280_PRESSURE_CALIB_DIG_P7_MSB
Referenced by bme280_get_calib_param.
BME280_PRESSURE_CALIB_DIG_P8_LSB
Referenced by bme280_get_calib_param.
BME280_PRESSURE_CALIB_DIG_P8_MSB
Referenced by bme280_get_calib_param.
BME280_PRESSURE_CALIB_DIG_P9_LSB
Referenced by bme280_get_calib_param.
BME280_PRESSURE_CALIB_DIG_P9_MSB
Referenced by bme280_get_calib_param.
BME280_HUMIDITY_CALIB_DIG_H1
Referenced by bme280_get_calib_param.
BME280_HUMIDITY_CALIB_DIG_H2_LSB
Referenced by bme280_get_calib_param.
BME280_HUMIDITY_CALIB_DIG_H2_MSB
Referenced by bme280_get_calib_param.
BME280_HUMIDITY_CALIB_DIG_H3
Referenced by bme280_get_calib_param.
BME280_HUMIDITY_CALIB_DIG_H4_MSB
Referenced by bme280_get_calib_param.
BME280_HUMIDITY_CALIB_DIG_H4_LSB
Referenced by bme280_get_calib_param.
BME280_HUMIDITY_CALIB_DIG_H5_MSB
Referenced by bme280_get_calib_param.
BME280_HUMIDITY_CALIB_DIG_H6
Referenced by bme280_get_calib_param.
BME280_MASK_DIG_H4
Referenced by bme280_get_calib_param.
BME280_TEMPERATURE_CALIB_DIG_T1_LSB_REG
Referenced by bme280_get_calib_param.
BME280_TEMPERATURE_CALIB_DIG_T1_MSB_REG
BME280_TEMPERATURE_CALIB_DIG_T2_LSB_REG
BME280_TEMPERATURE_CALIB_DIG_T2_MSB_REG
BME280_TEMPERATURE_CALIB_DIG_T3_LSB_REG
BME280_TEMPERATURE_CALIB_DIG_T3_MSB_REG
BME280_PRESSURE_CALIB_DIG_P1_LSB_REG
BME280_PRESSURE_CALIB_DIG_P1_MSB_REG
BME280_PRESSURE_CALIB_DIG_P2_LSB_REG
BME280_PRESSURE_CALIB_DIG_P2_MSB_REG
BME280_PRESSURE_CALIB_DIG_P3_LSB_REG
BME280_PRESSURE_CALIB_DIG_P3_MSB_REG
BME280_PRESSURE_CALIB_DIG_P4_LSB_REG
BME280_PRESSURE_CALIB_DIG_P4_MSB_REG
BME280_PRESSURE_CALIB_DIG_P5_LSB_REG
BME280_PRESSURE_CALIB_DIG_P5_MSB_REG
BME280_PRESSURE_CALIB_DIG_P6_LSB_REG
BME280_PRESSURE_CALIB_DIG_P6_MSB_REG
BME280_PRESSURE_CALIB_DIG_P7_LSB_REG
BME280_PRESSURE_CALIB_DIG_P7_MSB_REG
BME280_PRESSURE_CALIB_DIG_P8_LSB_REG
BME280_PRESSURE_CALIB_DIG_P8_MSB_REG
BME280_PRESSURE_CALIB_DIG_P9_LSB_REG
BME280_PRESSURE_CALIB_DIG_P9_MSB_REG
BME280_HUMIDITY_CALIB_DIG_H1_REG
BME280_HUMIDITY_CALIB_DIG_H2_LSB_REG
Referenced by bme280_get_calib_param.
BME280_HUMIDITY_CALIB_DIG_H2_MSB_REG
BME280_HUMIDITY_CALIB_DIG_H3_REG
BME280_HUMIDITY_CALIB_DIG_H4_MSB_REG
BME280_HUMIDITY_CALIB_DIG_H4_LSB_REG
BME280_HUMIDITY_CALIB_DIG_H5_MSB_REG
BME280_HUMIDITY_CALIB_DIG_H6_REG
BME280_CHIP_ID_REG
Referenced by bme280_init.
BME280_RST_REG
Referenced by bme280_set_soft_rst.
BME280_STAT_REG
BME280_CTRL_MEAS_REG
Referenced by bme280_set_oversamp_temperature, bme280_set_oversamp_pressure, bme280_set_oversamp_humidity, bme280_set_power_mode, bme280_set_spi3, bme280_set_filter, bme280_set_standby_durn, bme280_get_forced_uncomp_pressure_temperature_humidity.
BME280_CTRL_HUMIDITY_REG
Referenced by bme280_set_oversamp_temperature, bme280_set_oversamp_pressure, bme280_set_oversamp_humidity, bme280_set_power_mode, bme280_set_spi3, bme280_set_filter, bme280_set_standby_durn, bme280_get_forced_uncomp_pressure_temperature_humidity.
BME280_CONFIG_REG
Referenced by bme280_set_oversamp_temperature, bme280_set_oversamp_pressure, bme280_set_oversamp_humidity, bme280_set_power_mode, bme280_set_spi3, bme280_set_filter, bme280_set_standby_durn, bme280_get_forced_uncomp_pressure_temperature_humidity.
BME280_PRESSURE_MSB_REG
Referenced by bme280_read_uncomp_pressure, bme280_read_uncomp_pressure_temperature_humidity.
BME280_PRESSURE_LSB_REG
BME280_PRESSURE_XLSB_REG
BME280_TEMPERATURE_MSB_REG
Referenced by bme280_read_uncomp_temperature.
BME280_TEMPERATURE_LSB_REG
BME280_TEMPERATURE_XLSB_REG
BME280_HUMIDITY_MSB_REG
Referenced by bme280_read_uncomp_humidity.
BME280_HUMIDITY_LSB_REG
BME280_STAT_REG_MEASURING__POS
BME280_STAT_REG_MEASURING__MSK
BME280_STAT_REG_MEASURING__LEN
BME280_STAT_REG_MEASURING__REG
BME280_STAT_REG_IM_UPDATE__POS
BME280_STAT_REG_IM_UPDATE__MSK
BME280_STAT_REG_IM_UPDATE__LEN
BME280_STAT_REG_IM_UPDATE__REG
BME280_CTRL_MEAS_REG_OVERSAMP_TEMPERATURE__POS
BME280_CTRL_MEAS_REG_OVERSAMP_TEMPERATURE__MSK
BME280_CTRL_MEAS_REG_OVERSAMP_TEMPERATURE__LEN
BME280_CTRL_MEAS_REG_OVERSAMP_TEMPERATURE__REG
Referenced by bme280_get_oversamp_temperature, bme280_set_oversamp_temperature.
BME280_CTRL_MEAS_REG_OVERSAMP_PRESSURE__POS
BME280_CTRL_MEAS_REG_OVERSAMP_PRESSURE__MSK
BME280_CTRL_MEAS_REG_OVERSAMP_PRESSURE__LEN
BME280_CTRL_MEAS_REG_OVERSAMP_PRESSURE__REG
Referenced by bme280_get_oversamp_pressure, bme280_set_oversamp_pressure.
BME280_CTRL_MEAS_REG_POWER_MODE__POS
BME280_CTRL_MEAS_REG_POWER_MODE__MSK
BME280_CTRL_MEAS_REG_POWER_MODE__LEN
BME280_CTRL_MEAS_REG_POWER_MODE__REG
Referenced by bme280_get_power_mode, bme280_set_power_mode.
BME280_CTRL_HUMIDITY_REG_OVERSAMP_HUMIDITY__POS
BME280_CTRL_HUMIDITY_REG_OVERSAMP_HUMIDITY__MSK
BME280_CTRL_HUMIDITY_REG_OVERSAMP_HUMIDITY__LEN
BME280_CTRL_HUMIDITY_REG_OVERSAMP_HUMIDITY__REG
Referenced by bme280_get_oversamp_humidity, bme280_set_oversamp_humidity.
BME280_CONFIG_REG_TSB__POS
BME280_CONFIG_REG_TSB__MSK
BME280_CONFIG_REG_TSB__LEN
BME280_CONFIG_REG_TSB__REG
Referenced by bme280_get_standby_durn, bme280_set_standby_durn.
BME280_CONFIG_REG_FILTER__POS
BME280_CONFIG_REG_FILTER__MSK
BME280_CONFIG_REG_FILTER__LEN
BME280_CONFIG_REG_FILTER__REG
Referenced by bme280_get_filter, bme280_set_filter.
BME280_CONFIG_REG_SPI3_ENABLE__POS
BME280_CONFIG_REG_SPI3_ENABLE__MSK
BME280_CONFIG_REG_SPI3_ENABLE__LEN
BME280_CONFIG_REG_SPI3_ENABLE__REG
Referenced by bme280_get_spi3, bme280_set_spi3.
BME280_PRESSURE_XLSB_REG_DATA__POS
BME280_PRESSURE_XLSB_REG_DATA__MSK
BME280_PRESSURE_XLSB_REG_DATA__LEN
BME280_PRESSURE_XLSB_REG_DATA__REG
BME280_TEMPERATURE_XLSB_REG_DATA__POS
BME280_TEMPERATURE_XLSB_REG_DATA__MSK
BME280_TEMPERATURE_XLSB_REG_DATA__LEN
BME280_TEMPERATURE_XLSB_REG_DATA__REG
BME280_RETURN_FUNCTION_TYPE bme280_init(struct bme280_t *bme280)
This function is used for initialize the bus read and bus write functions and assign the chip id and I2C address of the BME280 sensor chip id is read in the register 0xD0 bit from 0 to 7.
bme280 structure pointer. While changing the parameter of the bme280_t consider the following point: Changing the reference value of the parameter will changes the local copy or local reference make sure your changes will not affect the reference value of the parameter (Better case don't change the reference value of the parameter) results of bus communication function 0 -> Success -1 -> Error
References BME280_RETURN_FUNCTION_TYPE, ERROR, BME280_INIT_VALUE, BME280_CHIP_ID_READ_COUNT, bme280_t::dev_addr, BME280_CHIP_ID_REG, BME280_GEN_READ_WRITE_DATA_LENGTH, BME280_CHIP_ID, bme280_t::delay_msec, BME280_REGISTER_READ_DELAY, bme280_t::chip_id, BME280_CHIP_ID_READ_FAIL, BME280_CHIP_ID_READ_SUCCESS, bme280_get_calib_param.
Referenced by Bme280Utils_initialize.
BME280_RETURN_FUNCTION_TYPE bme280_read_uncomp_temperature(s32 *v_uncomp_temperature_s32)
This API is used to read uncompensated temperature in the registers 0xFA, 0xFB and 0xFC.
0xFA -> MSB -> bit from 0 to 7 0xFB -> LSB -> bit from 0 to 7 0xFC -> LSB -> bit from 4 to 7 v_uncomp_temperature_s32 : The value of uncompensated temperature results of bus communication function 0 -> Success -1 -> Error
References BME280_RETURN_FUNCTION_TYPE, ERROR, BME280_TEMPERATURE_DATA_SIZE, BME280_INIT_VALUE, BME280_NULL, E_BME280_NULL_PTR, bme280_t::dev_addr, BME280_TEMPERATURE_MSB_REG, BME280_TEMPERATURE_DATA_LENGTH, BME280_TEMPERATURE_MSB_DATA, BME280_SHIFT_BIT_POSITION_BY_12_BITS, BME280_TEMPERATURE_LSB_DATA, BME280_SHIFT_BIT_POSITION_BY_04_BITS, BME280_TEMPERATURE_XLSB_DATA.
Referenced by Environmental_readTemperatureLSB.
s32 bme280_compensate_temperature_int32(s32 v_uncomp_temperature_s32)
Reads actual temperature from uncompensated temperature.
Returns the value in 0.01 degree Centigrade Output value of "5123" equals 51.23 DegC. v_uncomp_temperature_s32 : value of uncompensated temperature Returns the actual temperature
References BME280_INIT_VALUE, BME280_SHIFT_BIT_POSITION_BY_03_BITS, bme280_t::cal_param, bme280_calibration_param_t::dig_T1, BME280_SHIFT_BIT_POSITION_BY_01_BIT, bme280_calibration_param_t::dig_T2, BME280_SHIFT_BIT_POSITION_BY_11_BITS, BME280_SHIFT_BIT_POSITION_BY_04_BITS, BME280_SHIFT_BIT_POSITION_BY_12_BITS, bme280_calibration_param_t::dig_T3, BME280_SHIFT_BIT_POSITION_BY_14_BITS, bme280_calibration_param_t::t_fine, BME280_SHIFT_BIT_POSITION_BY_08_BITS.
Referenced by bme280_compensate_temperature_int32_sixteen_bit_output, bme280_read_pressure_temperature_humidity, Environmental_readTemperature.
s16 bme280_compensate_temperature_int32_sixteen_bit_output(s32 v_uncomp_temperature_s32)
Reads actual temperature from uncompensated temperature.
Returns the value with 500LSB/DegC centred around 24 DegC output value of "5123" equals(5123/500)+24 = 34.246DegC v_uncomp_temperature_s32 value of uncompensated temperature Return the actual temperature as s16 output
References BME280_INIT_VALUE, bme280_compensate_temperature_int32, bme280_t::cal_param, bme280_calibration_param_t::t_fine, BME280_SHIFT_BIT_POSITION_BY_08_BITS.
BME280_RETURN_FUNCTION_TYPE bme280_read_uncomp_pressure(s32 *v_uncomp_pressure_s32)
This API is used to read uncompensated pressure. in the registers 0xF7, 0xF8 and 0xF9.
0xF7 -> MSB -> bit from 0 to 7 0xF8 -> LSB -> bit from 0 to 7 0xF9 -> LSB -> bit from 4 to 7 v_uncomp_pressure_s32 : The value of uncompensated pressure results of bus communication function 0 -> Success -1 -> Error
References BME280_RETURN_FUNCTION_TYPE, ERROR, BME280_PRESSURE_DATA_SIZE, BME280_INIT_VALUE, BME280_NULL, E_BME280_NULL_PTR, bme280_t::dev_addr, BME280_PRESSURE_MSB_REG, BME280_PRESSURE_DATA_LENGTH, BME280_PRESSURE_MSB_DATA, BME280_SHIFT_BIT_POSITION_BY_12_BITS, BME280_PRESSURE_LSB_DATA, BME280_SHIFT_BIT_POSITION_BY_04_BITS, BME280_PRESSURE_XLSB_DATA.
Referenced by Environmental_readPressureLSB.
u32 bme280_compensate_pressure_int32(s32 v_uncomp_pressure_s32)
Reads actual pressure from uncompensated pressure.
Returns the value in Pascal(Pa) Output value of "96386" equals 96386 Pa = 963.86 hPa = 963.86 millibar v_uncomp_pressure_s32 : value of uncompensated pressure Return the actual pressure output as u32
References BME280_INIT_VALUE, bme280_t::cal_param, bme280_calibration_param_t::t_fine, BME280_SHIFT_BIT_POSITION_BY_01_BIT, BME280_SHIFT_BIT_POSITION_BY_02_BITS, BME280_SHIFT_BIT_POSITION_BY_11_BITS, bme280_calibration_param_t::dig_P6, bme280_calibration_param_t::dig_P5, bme280_calibration_param_t::dig_P4, BME280_SHIFT_BIT_POSITION_BY_16_BITS, bme280_calibration_param_t::dig_P3, BME280_SHIFT_BIT_POSITION_BY_13_BITS, BME280_SHIFT_BIT_POSITION_BY_03_BITS, bme280_calibration_param_t::dig_P2, BME280_SHIFT_BIT_POSITION_BY_18_BITS, bme280_calibration_param_t::dig_P1, BME280_SHIFT_BIT_POSITION_BY_15_BITS, BME280_SHIFT_BIT_POSITION_BY_12_BITS, BME280_INVALID_DATA, bme280_calibration_param_t::dig_P9, bme280_calibration_param_t::dig_P8, bme280_calibration_param_t::dig_P7, BME280_SHIFT_BIT_POSITION_BY_04_BITS.
Referenced by bme280_read_pressure_temperature_humidity, Environmental_readPressure.
BME280_RETURN_FUNCTION_TYPE bme280_read_uncomp_humidity(s32 *v_uncomp_humidity_s32)
This API is used to read uncompensated humidity. in the registers 0xF7, 0xF8 and 0xF9.
0xFD -> MSB -> bit from 0 to 7 0xFE -> LSB -> bit from 0 to 7 v_uncomp_humidity_s32 : The value of uncompensated humidity results of bus communication function 0 -> Success -1 -> Error
References BME280_RETURN_FUNCTION_TYPE, ERROR, BME280_HUMIDITY_DATA_SIZE, BME280_INIT_VALUE, BME280_NULL, E_BME280_NULL_PTR, bme280_t::dev_addr, BME280_HUMIDITY_MSB_REG, BME280_HUMIDITY_DATA_LENGTH, BME280_HUMIDITY_MSB_DATA, BME280_SHIFT_BIT_POSITION_BY_08_BITS, BME280_HUMIDITY_LSB_DATA.
Referenced by Environmental_readHumidityLSB.
u32 bme280_compensate_humidity_int32(s32 v_uncomp_humidity_s32)
Reads actual humidity from uncompensated humidity.
Returns the value in rH as unsigned 32bit integer in Q22.10 format(22 integer 10 fractional bits). An output value of 42313 represents 42313 / 1024 = 41.321 rH v_uncomp_humidity_s32 value of uncompensated humidity Return the actual relative humidity output as u32
References BME280_INIT_VALUE, bme280_t::cal_param, bme280_calibration_param_t::t_fine, BME280_SHIFT_BIT_POSITION_BY_14_BITS, bme280_calibration_param_t::dig_H4, BME280_SHIFT_BIT_POSITION_BY_20_BITS, bme280_calibration_param_t::dig_H5, BME280_SHIFT_BIT_POSITION_BY_15_BITS, bme280_calibration_param_t::dig_H6, BME280_SHIFT_BIT_POSITION_BY_10_BITS, bme280_calibration_param_t::dig_H3, BME280_SHIFT_BIT_POSITION_BY_11_BITS, bme280_calibration_param_t::dig_H2, BME280_SHIFT_BIT_POSITION_BY_07_BITS, bme280_calibration_param_t::dig_H1, BME280_SHIFT_BIT_POSITION_BY_04_BITS, BME280_SHIFT_BIT_POSITION_BY_12_BITS.
Referenced by bme280_compensate_humidity_int32_sixteen_bit_output, bme280_read_pressure_temperature_humidity, Environmental_readHumidity.
u16 bme280_compensate_humidity_int32_sixteen_bit_output(s32 v_uncomp_humidity_s32)
Reads actual humidity from uncompensated humidity.
Returns the value in rH as unsigned 16bit integer An output value of 42313 represents 42313/512 = 82.643 rH v_uncomp_humidity_s32 value of uncompensated humidity Return the actual relative humidity output as u16
References BME280_INIT_VALUE, bme280_compensate_humidity_int32, BME280_SHIFT_BIT_POSITION_BY_01_BIT.
BME280_RETURN_FUNCTION_TYPE bme280_read_uncomp_pressure_temperature_humidity(s32 *v_uncomp_pressure_s32, s32 *v_uncomp_temperature_s32, s32 *v_uncomp_humidity_s32)
This API used to read uncompensated pressure,temperature and humidity.
v_uncomp_pressure_s32 The value of uncompensated pressure. v_uncomp_temperature_s32 The value of uncompensated temperature v_uncomp_humidity_s32 The value of uncompensated humidity. results of bus communication function 0 -> Success -1 -> Error
References BME280_RETURN_FUNCTION_TYPE, ERROR, BME280_DATA_FRAME_SIZE, BME280_INIT_VALUE, BME280_NULL, E_BME280_NULL_PTR, bme280_t::dev_addr, BME280_PRESSURE_MSB_REG, BME280_ALL_DATA_FRAME_LENGTH, BME280_DATA_FRAME_PRESSURE_MSB_BYTE, BME280_SHIFT_BIT_POSITION_BY_12_BITS, BME280_DATA_FRAME_PRESSURE_LSB_BYTE, BME280_SHIFT_BIT_POSITION_BY_04_BITS, BME280_DATA_FRAME_PRESSURE_XLSB_BYTE, BME280_DATA_FRAME_TEMPERATURE_MSB_BYTE, BME280_DATA_FRAME_TEMPERATURE_LSB_BYTE, BME280_DATA_FRAME_TEMPERATURE_XLSB_BYTE, BME280_DATA_FRAME_HUMIDITY_MSB_BYTE, BME280_SHIFT_BIT_POSITION_BY_08_BITS, BME280_DATA_FRAME_HUMIDITY_LSB_BYTE.
Referenced by bme280_read_pressure_temperature_humidity, bme280_get_forced_uncomp_pressure_temperature_humidity, Environmental_readDataLSB.
BME280_RETURN_FUNCTION_TYPE bme280_read_pressure_temperature_humidity(u32 *v_pressure_u32, s32 *v_temperature_s32, u32 *v_humidity_u32)
This API used to read true pressure, temperature and humidity.
v_pressure_u32 : The value of compensated pressure. v_temperature_s32 : The value of compensated temperature. v_humidity_u32 : The value of compensated humidity. results of bus communication function 0 -> Success -1 -> Error
References BME280_RETURN_FUNCTION_TYPE, ERROR, BME280_INIT_VALUE, BME280_NULL, E_BME280_NULL_PTR, bme280_read_uncomp_pressure_temperature_humidity, bme280_compensate_temperature_int32, bme280_compensate_pressure_int32, bme280_compensate_humidity_int32.
Referenced by Environmental_readData.
BME280_RETURN_FUNCTION_TYPE bme280_get_calib_param(void)
This API is used to calibration parameters used for calculation in the registers.
parameter Register address bit dig_T1 0x88 and 0x89 from 0 : 7 to 8: 15 dig_T2 0x8A and 0x8B from 0 : 7 to 8: 15 dig_T3 0x8C and 0x8D from 0 : 7 to 8: 15 dig_P1 0x8E and 0x8F from 0 : 7 to 8: 15 dig_P2 0x90 and 0x91 from 0 : 7 to 8: 15 dig_P3 0x92 and 0x93 from 0 : 7 to 8: 15 dig_P4 0x94 and 0x95 from 0 : 7 to 8: 15 dig_P5 0x96 and 0x97 from 0 : 7 to 8: 15 dig_P6 0x98 and 0x99 from 0 : 7 to 8: 15 dig_P7 0x9A and 0x9B from 0 : 7 to 8: 15 dig_P8 0x9C and 0x9D from 0 : 7 to 8: 15 dig_P9 0x9E and 0x9F from 0 : 7 to 8: 15 dig_H1 0xA1 from 0 to 7 dig_H2 0xE1 and 0xE2 from 0 : 7 to 8: 15 dig_H3 0xE3 from 0 to 7 results of bus communication function 0 -> Success -1 -> Error parameter Register address bit dig_T1 0x88 and 0x89 from 0 : 7 to 8: 15 dig_T2 0x8A and 0x8B from 0 : 7 to 8: 15 dig_T3 0x8C and 0x8D from 0 : 7 to 8: 15 dig_P1 0x8E and 0x8F from 0 : 7 to 8: 15 dig_P2 0x90 and 0x91 from 0 : 7 to 8: 15 dig_P3 0x92 and 0x93 from 0 : 7 to 8: 15 dig_P4 0x94 and 0x95 from 0 : 7 to 8: 15 dig_P5 0x96 and 0x97 from 0 : 7 to 8: 15 dig_P6 0x98 and 0x99 from 0 : 7 to 8: 15 dig_P7 0x9A and 0x9B from 0 : 7 to 8: 15 dig_P8 0x9C and 0x9D from 0 : 7 to 8: 15 dig_P9 0x9E and 0x9F from 0 : 7 to 8: 15 dig_H1 0xA1 from 0 to 7 dig_H2 0xE1 and 0xE2 from 0 : 7 to 8: 15 dig_H3 0xE3 from 0 to 7 dig_H4 0xE4 and 0xE5 from 4 : 11 to 0: 3 dig_H5 0xE5 and 0xE6 from 0 : 3 to 4: 11 dig_H6 0xE7 from 0 to 7 results of bus communication function 0 -> Success -1 -> Error
References BME280_RETURN_FUNCTION_TYPE, ERROR, BME280_CALIB_DATA_SIZE, BME280_INIT_VALUE, BME280_NULL, E_BME280_NULL_PTR, bme280_t::dev_addr, BME280_TEMPERATURE_CALIB_DIG_T1_LSB_REG, BME280_PRESSURE_TEMPERATURE_CALIB_DATA_LENGTH, bme280_t::cal_param, bme280_calibration_param_t::dig_T1, BME280_TEMPERATURE_CALIB_DIG_T1_MSB, BME280_SHIFT_BIT_POSITION_BY_08_BITS, BME280_TEMPERATURE_CALIB_DIG_T1_LSB, bme280_calibration_param_t::dig_T2, BME280_TEMPERATURE_CALIB_DIG_T2_MSB, BME280_TEMPERATURE_CALIB_DIG_T2_LSB, bme280_calibration_param_t::dig_T3, BME280_TEMPERATURE_CALIB_DIG_T3_MSB, BME280_TEMPERATURE_CALIB_DIG_T3_LSB, bme280_calibration_param_t::dig_P1, BME280_PRESSURE_CALIB_DIG_P1_MSB, BME280_PRESSURE_CALIB_DIG_P1_LSB, bme280_calibration_param_t::dig_P2, BME280_PRESSURE_CALIB_DIG_P2_MSB, BME280_PRESSURE_CALIB_DIG_P2_LSB, bme280_calibration_param_t::dig_P3, BME280_PRESSURE_CALIB_DIG_P3_MSB, BME280_PRESSURE_CALIB_DIG_P3_LSB, bme280_calibration_param_t::dig_P4, BME280_PRESSURE_CALIB_DIG_P4_MSB, BME280_PRESSURE_CALIB_DIG_P4_LSB, bme280_calibration_param_t::dig_P5, BME280_PRESSURE_CALIB_DIG_P5_MSB, BME280_PRESSURE_CALIB_DIG_P5_LSB, bme280_calibration_param_t::dig_P6, BME280_PRESSURE_CALIB_DIG_P6_MSB, BME280_PRESSURE_CALIB_DIG_P6_LSB, bme280_calibration_param_t::dig_P7, BME280_PRESSURE_CALIB_DIG_P7_MSB, BME280_PRESSURE_CALIB_DIG_P7_LSB, bme280_calibration_param_t::dig_P8, BME280_PRESSURE_CALIB_DIG_P8_MSB, BME280_PRESSURE_CALIB_DIG_P8_LSB, bme280_calibration_param_t::dig_P9, BME280_PRESSURE_CALIB_DIG_P9_MSB, BME280_PRESSURE_CALIB_DIG_P9_LSB, bme280_calibration_param_t::dig_H1, BME280_HUMIDITY_CALIB_DIG_H1, BME280_HUMIDITY_CALIB_DIG_H2_LSB_REG, BME280_HUMIDITY_CALIB_DATA_LENGTH, bme280_calibration_param_t::dig_H2, BME280_HUMIDITY_CALIB_DIG_H2_MSB, BME280_HUMIDITY_CALIB_DIG_H2_LSB, bme280_calibration_param_t::dig_H3, BME280_HUMIDITY_CALIB_DIG_H3, bme280_calibration_param_t::dig_H4, BME280_HUMIDITY_CALIB_DIG_H4_MSB, BME280_SHIFT_BIT_POSITION_BY_04_BITS, BME280_MASK_DIG_H4, BME280_HUMIDITY_CALIB_DIG_H4_LSB, bme280_calibration_param_t::dig_H5, BME280_HUMIDITY_CALIB_DIG_H5_MSB, bme280_calibration_param_t::dig_H6, BME280_HUMIDITY_CALIB_DIG_H6.
Referenced by bme280_init.
BME280_RETURN_FUNCTION_TYPE bme280_get_oversamp_temperature(u8 *v_value_u8)
This API is used to get the temperature oversampling setting in the register 0xF4 bits from 5 to 7.
value Temperature oversampling 0x00 Skipped 0x01 BME280_OVERSAMP_1X 0x02 BME280_OVERSAMP_2X 0x03 BME280_OVERSAMP_4X 0x04 BME280_OVERSAMP_8X 0x05,0x06 and 0x07 BME280_OVERSAMP_16X v_value_u8 : The value of temperature over sampling results of bus communication function 0 -> Success -1 -> Error
References BME280_RETURN_FUNCTION_TYPE, ERROR, BME280_INIT_VALUE, BME280_NULL, E_BME280_NULL_PTR, bme280_t::dev_addr, BME280_CTRL_MEAS_REG_OVERSAMP_TEMPERATURE__REG, BME280_GEN_READ_WRITE_DATA_LENGTH, BME280_GET_BITSLICE, bme280_t::oversamp_temperature.
BME280_RETURN_FUNCTION_TYPE bme280_set_oversamp_temperature(u8 v_value_u8)
This API is used to set the temperature oversampling setting in the register 0xF4 bits from 5 to 7.
value Temperature oversampling 0x00 Skipped 0x01 BME280_OVERSAMP_1X 0x02 BME280_OVERSAMP_2X 0x03 BME280_OVERSAMP_4X 0x04 BME280_OVERSAMP_8X 0x05,0x06 and 0x07 BME280_OVERSAMP_16X v_value_u8 : The value of temperature over sampling results of bus communication function 0 -> Success -1 -> Error
References BME280_RETURN_FUNCTION_TYPE, ERROR, BME280_INIT_VALUE, BME280_NULL, E_BME280_NULL_PTR, bme280_t::ctrl_meas_reg, BME280_SET_BITSLICE, bme280_get_power_mode, BME280_SLEEP_MODE, bme280_set_soft_rst, bme280_t::delay_msec, BME280_3MS_DELAY, bme280_t::config_reg, bme280_write_register, BME280_CONFIG_REG, BME280_GEN_READ_WRITE_DATA_LENGTH, bme280_t::ctrl_hum_reg, BME280_CTRL_HUMIDITY_REG, BME280_CTRL_MEAS_REG, bme280_t::dev_addr, BME280_CTRL_MEAS_REG_OVERSAMP_TEMPERATURE__REG, bme280_t::oversamp_temperature, bme280_read_register.
Referenced by setOverSampling, Bme280Utils_initialize.
BME280_RETURN_FUNCTION_TYPE bme280_get_oversamp_pressure(u8 *v_value_u8)
This API is used to get the pressure oversampling setting in the register 0xF4 bits from 2 to 4.
value Pressure oversampling 0x00 Skipped 0x01 BME280_OVERSAMP_1X 0x02 BME280_OVERSAMP_2X 0x03 BME280_OVERSAMP_4X 0x04 BME280_OVERSAMP_8X 0x05,0x06 and 0x07 BME280_OVERSAMP_16X v_value_u8 : The value of pressure oversampling results of bus communication function 0 -> Success -1 -> Error
References BME280_RETURN_FUNCTION_TYPE, ERROR, BME280_INIT_VALUE, BME280_NULL, E_BME280_NULL_PTR, bme280_t::dev_addr, BME280_CTRL_MEAS_REG_OVERSAMP_PRESSURE__REG, BME280_GEN_READ_WRITE_DATA_LENGTH, BME280_GET_BITSLICE, bme280_t::oversamp_pressure.
BME280_RETURN_FUNCTION_TYPE bme280_set_oversamp_pressure(u8 v_value_u8)
This API is used to set the pressure oversampling setting in the register 0xF4 bits from 2 to 4.
value Pressure oversampling 0x00 Skipped 0x01 BME280_OVERSAMP_1X 0x02 BME280_OVERSAMP_2X 0x03 BME280_OVERSAMP_4X 0x04 BME280_OVERSAMP_8X 0x05,0x06 and 0x07 BME280_OVERSAMP_16X v_value_u8 : The value of pressure oversampling results of bus communication function 0 -> Success -1 -> Error
References BME280_RETURN_FUNCTION_TYPE, ERROR, BME280_INIT_VALUE, BME280_NULL, E_BME280_NULL_PTR, bme280_t::ctrl_meas_reg, BME280_SET_BITSLICE, bme280_get_power_mode, BME280_SLEEP_MODE, bme280_set_soft_rst, bme280_t::delay_msec, BME280_3MS_DELAY, bme280_t::config_reg, bme280_write_register, BME280_CONFIG_REG, BME280_GEN_READ_WRITE_DATA_LENGTH, bme280_t::ctrl_hum_reg, BME280_CTRL_HUMIDITY_REG, BME280_CTRL_MEAS_REG, bme280_t::dev_addr, BME280_CTRL_MEAS_REG_OVERSAMP_PRESSURE__REG, bme280_t::oversamp_pressure, bme280_read_register.
Referenced by setOverSampling, Bme280Utils_initialize.
BME280_RETURN_FUNCTION_TYPE bme280_get_oversamp_humidity(u8 *v_value_u8)
This API is used to get the humidity oversampling setting in the register 0xF2 bits from 0 to 2.
value Humidity oversampling 0x00 Skipped 0x01 BME280_OVERSAMP_1X 0x02 BME280_OVERSAMP_2X 0x03 BME280_OVERSAMP_4X 0x04 BME280_OVERSAMP_8X 0x05,0x06 and 0x07 BME280_OVERSAMP_16X v_value_u8 : The value of humidity over sampling results of bus communication function 0 -> Success -1 -> Error
References BME280_RETURN_FUNCTION_TYPE, ERROR, BME280_INIT_VALUE, BME280_NULL, E_BME280_NULL_PTR, bme280_t::dev_addr, BME280_CTRL_HUMIDITY_REG_OVERSAMP_HUMIDITY__REG, BME280_GEN_READ_WRITE_DATA_LENGTH, BME280_GET_BITSLICE, bme280_t::oversamp_humidity.
BME280_RETURN_FUNCTION_TYPE bme280_set_oversamp_humidity(u8 v_value_u8)
This API is used to set the humidity oversampling setting in the register 0xF2 bits from 0 to 2.
value Humidity oversampling 0x00 Skipped 0x01 BME280_OVERSAMP_1X 0x02 BME280_OVERSAMP_2X 0x03 BME280_OVERSAMP_4X 0x04 BME280_OVERSAMP_8X 0x05,0x06 and 0x07 BME280_OVERSAMP_16X v_value_u8 : The value of humidity over sampling The "BME280_CTRL_HUMIDITY_REG_OVERSAMP_HUMIDITY" register sets the humidity data acquisition options of the device. changes to this registers only become effective after a write operation to "BME280_CTRL_MEAS_REG" register. In the code automated reading and writing of "BME280_CTRL_HUMIDITY_REG_OVERSAMP_HUMIDITY" register first set the "BME280_CTRL_HUMIDITY_REG_OVERSAMP_HUMIDITY" and then read and write the "BME280_CTRL_MEAS_REG" register in the function. results of bus communication function 0 -> Success -1 -> Error
References BME280_RETURN_FUNCTION_TYPE, ERROR, BME280_INIT_VALUE, BME280_NULL, E_BME280_NULL_PTR, bme280_t::ctrl_hum_reg, BME280_SET_BITSLICE, bme280_get_power_mode, BME280_SLEEP_MODE, bme280_set_soft_rst, bme280_t::delay_msec, BME280_3MS_DELAY, bme280_t::config_reg, bme280_write_register, BME280_CONFIG_REG, BME280_GEN_READ_WRITE_DATA_LENGTH, BME280_CTRL_HUMIDITY_REG, bme280_t::ctrl_meas_reg, BME280_CTRL_MEAS_REG, bme280_t::dev_addr, BME280_CTRL_HUMIDITY_REG_OVERSAMP_HUMIDITY__REG, bme280_t::oversamp_humidity, bme280_read_register.
Referenced by setOverSampling, Bme280Utils_initialize.
BME280_RETURN_FUNCTION_TYPE bme280_get_power_mode(u8 *v_power_mode_u8)
This API used to get the Operational Mode from the sensor in the register 0xF4 bit 0 and 1.
v_power_mode_u8 : The value of power mode value mode 0x00 BME280_SLEEP_MODE 0x01 and 0x02 BME280_FORCED_MODE 0x03 BME280_NORMAL_MODE results of bus communication function 0 -> Success -1 -> Error
References BME280_RETURN_FUNCTION_TYPE, ERROR, BME280_INIT_VALUE, BME280_NULL, E_BME280_NULL_PTR, bme280_t::dev_addr, BME280_CTRL_MEAS_REG_POWER_MODE__REG, BME280_GEN_READ_WRITE_DATA_LENGTH, BME280_GET_BITSLICE.
Referenced by bme280_set_oversamp_temperature, bme280_set_oversamp_pressure, bme280_set_oversamp_humidity, bme280_set_power_mode, bme280_set_spi3, bme280_set_filter, bme280_set_standby_durn, bme280_get_forced_uncomp_pressure_temperature_humidity, Environmental_getPowerMode.
BME280_RETURN_FUNCTION_TYPE bme280_set_power_mode(u8 v_power_mode_u8)
This API used to set the Operational Mode from the sensor in the register 0xF4 bit 0 and 1.
v_power_mode_u8 : The value of power mode value mode 0x00 BME280_SLEEP_MODE 0x01 and 0x02 BME280_FORCED_MODE 0x03 BME280_NORMAL_MODE results of bus communication function 0 -> Success -1 -> Error
References BME280_RETURN_FUNCTION_TYPE, ERROR, BME280_INIT_VALUE, BME280_NULL, E_BME280_NULL_PTR, BME280_NORMAL_MODE, bme280_t::ctrl_meas_reg, BME280_SET_BITSLICE, bme280_get_power_mode, BME280_SLEEP_MODE, bme280_set_soft_rst, bme280_t::delay_msec, BME280_3MS_DELAY, bme280_t::config_reg, bme280_write_register, BME280_CONFIG_REG, BME280_GEN_READ_WRITE_DATA_LENGTH, bme280_t::ctrl_hum_reg, BME280_CTRL_HUMIDITY_REG, BME280_CTRL_MEAS_REG, bme280_t::dev_addr, BME280_CTRL_MEAS_REG_POWER_MODE__REG, bme280_read_register, E_BME280_OUT_OF_RANGE.
Referenced by Environmental_setPowerMode, Bme280Utils_initialize.
BME280_RETURN_FUNCTION_TYPE bme280_set_soft_rst(void)
Used to reset the sensor The value 0xB6 is written to the 0xE0 register the device is reset using the complete power-on-reset procedure.
Soft reset can be easily set using bme280_set_softreset(). Usage Hint : bme280_set_softreset() results of bus communication function 0 -> Success -1 -> Error
References BME280_RETURN_FUNCTION_TYPE, ERROR, BME280_SOFT_RESET_CODE, BME280_NULL, E_BME280_NULL_PTR, bme280_t::dev_addr, BME280_RST_REG, BME280_GEN_READ_WRITE_DATA_LENGTH.
Referenced by bme280_set_oversamp_temperature, bme280_set_oversamp_pressure, bme280_set_oversamp_humidity, bme280_set_power_mode, bme280_set_spi3, bme280_set_filter, bme280_set_standby_durn, bme280_get_forced_uncomp_pressure_temperature_humidity.
BME280_RETURN_FUNCTION_TYPE bme280_get_spi3(u8 *v_enable_disable_u8)
This API used to get the sensor SPI mode(communication type) in the register 0xF5 bit 0.
v_enable_disable_u8 : The value of SPI enable value Description 0 Disable 1 Enable results of bus communication function 0 -> Success -1 -> Error
References BME280_RETURN_FUNCTION_TYPE, ERROR, BME280_INIT_VALUE, BME280_NULL, E_BME280_NULL_PTR, bme280_t::dev_addr, BME280_CONFIG_REG_SPI3_ENABLE__REG, BME280_GEN_READ_WRITE_DATA_LENGTH, BME280_GET_BITSLICE.
BME280_RETURN_FUNCTION_TYPE bme280_set_spi3(u8 v_enable_disable_u8)
This API used to set the sensor SPI mode(communication type) in the register 0xF5 bit 0.
v_enable_disable_u8 : The value of SPI enable value Description 0 Disable 1 Enable results of bus communication function 0 -> Success -1 -> Error
References BME280_RETURN_FUNCTION_TYPE, ERROR, BME280_INIT_VALUE, BME280_NULL, E_BME280_NULL_PTR, bme280_t::config_reg, BME280_SET_BITSLICE, bme280_get_power_mode, BME280_SLEEP_MODE, bme280_set_soft_rst, bme280_t::delay_msec, BME280_3MS_DELAY, bme280_write_register, BME280_CONFIG_REG, BME280_GEN_READ_WRITE_DATA_LENGTH, bme280_t::ctrl_hum_reg, BME280_CTRL_HUMIDITY_REG, bme280_t::ctrl_meas_reg, BME280_CTRL_MEAS_REG, bme280_t::dev_addr, BME280_CONFIG_REG_SPI3_ENABLE__REG, bme280_read_register.
BME280_RETURN_FUNCTION_TYPE bme280_get_filter(u8 *v_value_u8)
This API is used to reads filter setting in the register 0xF5 bit 3 and 4.
v_value_u8 : The value of IIR filter coefficient value Filter coefficient 0x00 BME280_FILTER_COEFF_OFF 0x01 BME280_FILTER_COEFF_2 0x02 BME280_FILTER_COEFF_4 0x03 BME280_FILTER_COEFF_8 0x04 BME280_FILTER_COEFF_16 results of bus communication function 0 -> Success -1 -> Error
References BME280_RETURN_FUNCTION_TYPE, ERROR, BME280_INIT_VALUE, BME280_NULL, E_BME280_NULL_PTR, bme280_t::dev_addr, BME280_CONFIG_REG_FILTER__REG, BME280_GEN_READ_WRITE_DATA_LENGTH, BME280_GET_BITSLICE.
BME280_RETURN_FUNCTION_TYPE bme280_set_filter(u8 v_value_u8)
This API is used to write filter setting in the register 0xF5 bit 3 and 4.
v_value_u8 : The value of IIR filter coefficient value Filter coefficient 0x00 BME280_FILTER_COEFF_OFF 0x01 BME280_FILTER_COEFF_2 0x02 BME280_FILTER_COEFF_4 0x03 BME280_FILTER_COEFF_8 0x04 BME280_FILTER_COEFF_16 results of bus communication function 0 -> Success -1 -> Error
References BME280_RETURN_FUNCTION_TYPE, ERROR, BME280_INIT_VALUE, BME280_NULL, E_BME280_NULL_PTR, bme280_t::config_reg, BME280_SET_BITSLICE, bme280_get_power_mode, BME280_SLEEP_MODE, bme280_set_soft_rst, bme280_t::delay_msec, BME280_3MS_DELAY, bme280_write_register, BME280_CONFIG_REG, BME280_GEN_READ_WRITE_DATA_LENGTH, bme280_t::ctrl_hum_reg, BME280_CTRL_HUMIDITY_REG, bme280_t::ctrl_meas_reg, BME280_CTRL_MEAS_REG, bme280_t::dev_addr, BME280_CONFIG_REG_FILTER__REG, bme280_read_register.
Referenced by Environmental_setFilterCoefficient.
BME280_RETURN_FUNCTION_TYPE bme280_get_standby_durn(u8 *v_standby_durn_u8)
This API used to Read the standby duration time from the sensor in the register 0xF5 bit 5 to 7.
v_standby_durn_u8 : The value of standby duration time value. value standby duration 0x00 BME280_STANDBY_TIME_1_MS 0x01 BME280_STANDBY_TIME_63_MS 0x02 BME280_STANDBY_TIME_125_MS 0x03 BME280_STANDBY_TIME_250_MS 0x04 BME280_STANDBY_TIME_500_MS 0x05 BME280_STANDBY_TIME_1000_MS 0x06 BME280_STANDBY_TIME_2000_MS 0x07 BME280_STANDBY_TIME_4000_MS results of bus communication function 0 -> Success -1 -> Error
References BME280_RETURN_FUNCTION_TYPE, ERROR, BME280_INIT_VALUE, BME280_NULL, E_BME280_NULL_PTR, bme280_t::dev_addr, BME280_CONFIG_REG_TSB__REG, BME280_GEN_READ_WRITE_DATA_LENGTH, BME280_GET_BITSLICE.
Referenced by Environmental_getStandbyDuration.
BME280_RETURN_FUNCTION_TYPE bme280_set_standby_durn(u8 v_standby_durn_u8)
This API used to write the standby duration time from the sensor in the register 0xF5 bit 5 to 7.
v_standby_durn_u8 : The value of standby duration time value. value standby duration 0x00 BME280_STANDBY_TIME_1_MS 0x01 BME280_STANDBY_TIME_63_MS 0x02 BME280_STANDBY_TIME_125_MS 0x03 BME280_STANDBY_TIME_250_MS 0x04 BME280_STANDBY_TIME_500_MS 0x05 BME280_STANDBY_TIME_1000_MS 0x06 BME280_STANDBY_TIME_2000_MS 0x07 BME280_STANDBY_TIME_4000_MS Normal mode comprises an automated perpetual cycling between an (active) Measurement period and an (inactive) standby period. The standby time is determined by the contents of the register t_sb. Standby time can be set using BME280_STANDBY_TIME_125_MS. Usage Hint : bme280_set_standby_durn(BME280_STANDBY_TIME_125_MS) results of bus communication function 0 -> Success -1 -> Error
References BME280_RETURN_FUNCTION_TYPE, ERROR, BME280_INIT_VALUE, BME280_NULL, E_BME280_NULL_PTR, bme280_t::config_reg, BME280_SET_BITSLICE, bme280_get_power_mode, BME280_SLEEP_MODE, bme280_set_soft_rst, bme280_t::delay_msec, BME280_3MS_DELAY, bme280_write_register, BME280_CONFIG_REG, BME280_GEN_READ_WRITE_DATA_LENGTH, bme280_t::ctrl_hum_reg, BME280_CTRL_HUMIDITY_REG, bme280_t::ctrl_meas_reg, BME280_CTRL_MEAS_REG, bme280_t::dev_addr, BME280_CONFIG_REG_TSB__REG, bme280_read_register.
Referenced by Environmental_setStandbyDuration, Bme280Utils_initialize.
BME280_RETURN_FUNCTION_TYPE bme280_get_forced_uncomp_pressure_temperature_humidity(s32 *v_uncom_pressure_s32, s32 *v_uncom_temperature_s32, s32 *v_uncom_humidity_s32)
This API used to read uncompensated temperature,pressure and humidity in forced mode.
v_uncom_pressure_s32 The value of uncompensated pressure v_uncom_temperature_s32 The value of uncompensated temperature v_uncom_humidity_s32 The value of uncompensated humidity results of bus communication function 0 -> Success -1 -> Error
References BME280_RETURN_FUNCTION_TYPE, ERROR, BME280_INIT_VALUE, BME280_NULL, E_BME280_NULL_PTR, bme280_t::ctrl_meas_reg, BME280_SET_BITSLICE, BME280_FORCED_MODE, bme280_get_power_mode, BME280_SLEEP_MODE, bme280_set_soft_rst, bme280_t::delay_msec, BME280_3MS_DELAY, bme280_t::config_reg, bme280_write_register, BME280_CONFIG_REG, BME280_GEN_READ_WRITE_DATA_LENGTH, bme280_t::ctrl_hum_reg, BME280_CTRL_HUMIDITY_REG, BME280_CTRL_MEAS_REG, bme280_compute_wait_time, bme280_read_uncomp_pressure_temperature_humidity, bme280_read_register.
BME280_RETURN_FUNCTION_TYPE bme280_write_register(u8 v_addr_u8, u8 *v_data_u8, u8 v_len_u8)
This API write the data to the given register.
v_addr_u8 -> Address of the register v_data_u8 -> The data from the register v_len_u8 -> no of bytes to read results of bus communication function 0 -> Success -1 -> Error
References BME280_RETURN_FUNCTION_TYPE, ERROR, BME280_NULL, E_BME280_NULL_PTR, bme280_t::dev_addr.
Referenced by bme280_set_oversamp_temperature, bme280_set_oversamp_pressure, bme280_set_oversamp_humidity, bme280_set_power_mode, bme280_set_spi3, bme280_set_filter, bme280_set_standby_durn, bme280_get_forced_uncomp_pressure_temperature_humidity.
BME280_RETURN_FUNCTION_TYPE bme280_read_register(u8 v_addr_u8, u8 *v_data_u8, u8 v_len_u8)
This API reads the data from the given register.
v_addr_u8 -> Address of the register v_data_u8 -> The data from the register v_len_u8 -> no of bytes to read results of bus communication function 0 -> Success -1 -> Error
References BME280_RETURN_FUNCTION_TYPE, ERROR, BME280_NULL, E_BME280_NULL_PTR, bme280_t::dev_addr.
Referenced by bme280_set_oversamp_temperature, bme280_set_oversamp_pressure, bme280_set_oversamp_humidity, bme280_set_power_mode, bme280_set_spi3, bme280_set_filter, bme280_set_standby_durn, bme280_get_forced_uncomp_pressure_temperature_humidity.
double bme280_compensate_temperature_double(s32 v_uncom_temperature_s32)
Reads actual temperature from uncompensated temperature.
returns the value in Degree centigrade Output value of "51.23" equals 51.23 DegC. v_uncom_temperature_s32 : value of uncompensated temperature Return the actual temperature in floating point
References BME280_INIT_VALUE, bme280_t::cal_param, bme280_calibration_param_t::dig_T1, bme280_calibration_param_t::dig_T2, bme280_calibration_param_t::dig_T3, bme280_calibration_param_t::t_fine.
double bme280_compensate_pressure_double(s32 v_uncom_pressure_s32)
Reads actual pressure from uncompensated pressure.
Returns pressure in Pa as double. Output value of "96386.2" equals 96386.2 Pa = 963.862 hPa. v_uncom_pressure_s32 : value of uncompensated pressure Return the actual pressure in floating point
References BME280_INIT_VALUE, bme280_t::cal_param, bme280_calibration_param_t::t_fine, bme280_calibration_param_t::dig_P6, bme280_calibration_param_t::dig_P5, bme280_calibration_param_t::dig_P4, bme280_calibration_param_t::dig_P3, bme280_calibration_param_t::dig_P2, bme280_calibration_param_t::dig_P1, BME280_INVALID_DATA, bme280_calibration_param_t::dig_P9, bme280_calibration_param_t::dig_P8, bme280_calibration_param_t::dig_P7.
double bme280_compensate_humidity_double(s32 v_uncom_humidity_s32)
Reads actual humidity from uncompensated humidity.
returns the value in relative humidity (rH) Output value of "42.12" equals 42.12 rH v_uncom_humidity_s32 : value of uncompensated humidity Return the actual humidity in floating point
References BME280_INIT_VALUE, bme280_t::cal_param, bme280_calibration_param_t::t_fine, bme280_calibration_param_t::dig_H4, bme280_calibration_param_t::dig_H5, bme280_calibration_param_t::dig_H2, bme280_calibration_param_t::dig_H6, bme280_calibration_param_t::dig_H3, BME280_INVALID_DATA, bme280_calibration_param_t::dig_H1.
u32 bme280_compensate_pressure_int64(s32 v_uncom_pressure_s32)
Reads actual pressure from uncompensated pressure.
Returns the value in Pa as unsigned 32 bit integer in Q24.8 format (24 integer bits and 8 fractional bits). Output value of "24674867" represents 24674867 / 256 = 96386.2 Pa = 963.862 hPa v_uncom_pressure_s32 : value of uncompensated temperature Return the actual pressure in u32
References BME280_INIT_VALUE, bme280_t::cal_param, bme280_calibration_param_t::t_fine, bme280_calibration_param_t::dig_P6, bme280_calibration_param_t::dig_P5, BME280_SHIFT_BIT_POSITION_BY_17_BITS, bme280_calibration_param_t::dig_P4, BME280_SHIFT_BIT_POSITION_BY_35_BITS, bme280_calibration_param_t::dig_P3, BME280_SHIFT_BIT_POSITION_BY_08_BITS, bme280_calibration_param_t::dig_P2, BME280_SHIFT_BIT_POSITION_BY_12_BITS, BME280_SHIFT_BIT_POSITION_BY_47_BITS, bme280_calibration_param_t::dig_P1, BME280_SHIFT_BIT_POSITION_BY_33_BITS, BME280_SHIFT_BIT_POSITION_BY_31_BITS, BME280_INVALID_DATA, bme280_calibration_param_t::dig_P9, BME280_SHIFT_BIT_POSITION_BY_13_BITS, BME280_SHIFT_BIT_POSITION_BY_25_BITS, bme280_calibration_param_t::dig_P8, BME280_SHIFT_BIT_POSITION_BY_19_BITS, bme280_calibration_param_t::dig_P7, BME280_SHIFT_BIT_POSITION_BY_04_BITS.
Referenced by bme280_compensate_pressure_int64_twentyfour_bit_output.
u32 bme280_compensate_pressure_int64_twentyfour_bit_output(s32 v_uncom_pressure_s32)
Reads actual pressure from uncompensated pressure.
Returns the value in Pa. Output value of "12337434" represents 12337434 / 128 = 96386.2 Pa = 963.862 hPa v_uncom_pressure_s32 : value of uncompensated pressure the actual pressure in u32
References BME280_INIT_VALUE, bme280_compensate_pressure_int64, BME280_SHIFT_BIT_POSITION_BY_01_BIT.
BME280_RETURN_FUNCTION_TYPE bme280_compute_wait_time(u8 *v_delaytime_u8)
Computing waiting time for sensor data read.
v_delaytime_u8 : The value of delay time for force mode 0 -> Success
References BME280_RETURN_FUNCTION_TYPE, SUCCESS, T_INIT_MAX, T_MEASURE_PER_OSRS_MAX, bme280_t::oversamp_temperature, BME280_SHIFT_BIT_POSITION_BY_01_BIT, bme280_t::oversamp_pressure, bme280_t::oversamp_humidity, T_SETUP_PRESSURE_MAX, T_SETUP_HUMIDITY_MAX.
Referenced by bme280_get_forced_uncomp_pressure_temperature_humidity.
BME280_64BITSUPPORT_PRESENT
MACHINE_32_BIT
The following definition uses for define the data types.
While porting the API please consider the following Please check the version of C standard Are you using Linux platform For the Linux platform support Please use the types.h for your data types definitionsBy default it is defined as 32 bit machine configuration define your data types based on your machine/compiler/controller configuration
typedef signed short int s16
used for signed 16bit
typedef signed int s32
used for signed 32bit
typedef signed long long int s64
used for signed 64bit
typedef signed char s8
used for signed 8bit
typedef unsigned short int u16
used for unsigned 16bit
typedef unsigned int u32
used for unsigned 32bit
typedef unsigned long long int u64
used for unsigned 64bit
typedef unsigned char u8
used for unsigned 8bit