bmg160.c
struct bmg160_t* p_bmg160
file bmg160.c brief Driver for BMG160
BMG160_RETURN_FUNCTION_TYPE bmg160_burst_read(u8 v_addr_u8, u8 *v_data_u8, u32 v_len_u32)
This API reads the data from the given register.
v_addr_u8 -> Address of the register v_data_u8 -> The data from the register v_len_u32 -> no of bytes to read results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr.
BMG160_RETURN_FUNCTION_TYPE bmg160_enable_fast_offset(void)
This API is used to enable fast offset in the register 0x32 bit 3 it is a write only register.
results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_FAST_OFFSET_ENABLE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_any_motion_durn_sample(u8 *v_durn_sample_u8)
This API is used to get the any motion Duration samples in the register 0x1C bit 4 and 5.
v_durn_sample_u8 : The value of any motion duration samples value Samples 0x00 4 samples 0x01 8 samples 0x02 12 samples 0x03 16 samples results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_TWO_ADDR_ANY_MOTION_DURN_SAMPLE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_any_motion_enable_axis(u8 v_channel_u8, u8 *v_any_motion_axis_u8)
This API is used to get the status of Any motion interrupt axis(X,Y,Z) enable channel.
BMG160_X_AXIS -> bit 0 BMG160_Y_AXIS -> bit 1 BMG160_Z_AXIS -> bit 2 v_channel_u8 : The value of Any Enable channel number v_channel_u8 axis 0 BMG160_X_AXIS 1 BMG160_Y_AXIS 2 BMG160_Z_AXIS v_data_u8 The value of Any motion axis enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_INTR_TWO_ADDR_ANY_MOTION_ENABLE_X__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_Y_AXIS, BMG160_INTR_TWO_ADDR_ANY_MOTION_ENABLE_Y__REG, BMG160_Z_AXIS, BMG160_INTR_TWO_ADDR_ANY_MOTION_ENABLE_Z__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_any_motion_thres(u8 *v_any_motion_thres_u8)
This API is used to get Any motion Threshold in the register 0x1B bit from 0 to 6.
v_any_motion_thres_u8 : The value of any_motion Threshold Any motion threshold can be calculate using ((1+ v_any_motion_thres_u8)*16LSB) results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_ONE_ADDR_ANY_MOTION_THRES__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_auto_offset_enable(u8 *v_offset_enable_u8)
This API is used to get the auto offset(auto_offset_enable) interrupt enable bits of the sensor in the registers 0x15 bit 3.
v_offset_enable_u8 : The value of offset enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_ENABLE0_AUTO_OFFSET__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_auto_sleep_durn(u8 *v_durn_u8)
This API is used to get the auto sleep duration in the register 0x12 bit 0 to 2.
v_durn_u8 : The value of gyro auto sleep duration sleep duration value not allowed 0 4ms 1 5ms 2 8ms 3 10ms 4 15ms 5 20ms 6 40ms 7 results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_MODE_LPM2_ADDR_AUTO_SLEEP_DURN__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
Referenced by bmg160_set_bw, bmg160_set_power_mode.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_awake_durn(u8 *v_awake_durn_u8)
This API is used to get the awake Duration in the register 0x1C bit 6 and 7.
v_awake_durn_u8 : The value of awake Duration value Duration 0x00 8 samples 0x01 16 samples 0x02 32 samples 0x03 64 samples results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_TWO_ADDR_AWAKE_DURN__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_bw(u8 *v_bw_u8)
This API is used to get the gyro bandwidth in the register 0x10 bits from 0 to 3.
v_bw_u8 The value of gyro bandwidth value bandwidth 0x00 BMG160_BW_500_HZ 0x01 BMG160_BW_230_HZ 0x02 BMG160_BW_116_HZ 0x03 BMG160_BW_47_HZ 0x04 BMG160_BW_23_HZ 0x05 BMG160_BW_12_HZ 0x06 BMG160_BW_64_HZ 0x07 BMG160_BW_32_HZ results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_BW_ADDR__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_BW_ADDR.
Referenced by bmg160_set_power_mode, Gyroscope_getBandwidth.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_data_enable(u8 *v_data_enable_u8)
This API is used to get the data(data_enable) interrupt enable bits of the sensor in the registers 0x15 bit 7.
v_data_enable_u8 : The value of data enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_ENABLE0_DATA__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_data_X(s16 *v_data_x_s16)
Reads Rate data X in the registers 0x02 to 0x03.
v_data_x_s16 The value of gyro x axis data results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, BMG160_INIT_VALUE, BMG160_X_DATA_SIZE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_RATE_X_LSB_BIT__REG, BMG160_X_DATA_LENGTH, BMG160_X_LSB_DATA, BMG160_GET_BITSLICE, BMG160_X_MSB_DATA, BMG160_SHIFT_BIT_POSITION_BY_08_BITS.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_data_XYZ(struct bmg160_data_t *data)
Reads data X,Y and Z from register location 0x02 to 0x07.
data The value of gyro xyz axis data results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_XYZ_DATA_SIZE, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_RATE_X_LSB_BIT__REG, BMG160_ALL_DATA_FRAME_LENGTH, BMG160_DATA_FRAME_X_LSB_BYTE, BMG160_GET_BITSLICE, bmg160_data_t::datax, BMG160_DATA_FRAME_X_MSB_BYTE, BMG160_SHIFT_BIT_POSITION_BY_08_BITS, BMG160_DATA_FRAME_Y_LSB_BYTE, bmg160_data_t::datay, BMG160_DATA_FRAME_Y_MSB_BYTE, BMG160_DATA_FRAME_Z_LSB_BYTE, bmg160_data_t::dataz, BMG160_DATA_FRAME_Z_MSB_BYTE.
Referenced by Gyroscope_readXyzValue, Gyroscope_readXyzDegreeValue.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_data_XYZI(struct bmg160_data_t *data)
Reads data X,Y,Z and Interrupts from register location 0x02 to 0x07.
data The value of gyro xyz axis data and interrupt status results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_XYZ_INTR_DATA_SIZE, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_RATE_X_LSB_BIT__REG, BMG160_XYZ_AND_INTR_DATA_LENGTH, BMG160_DATA_FRAME_X_LSB_BYTE, BMG160_GET_BITSLICE, bmg160_data_t::datax, BMG160_DATA_FRAME_X_MSB_BYTE, BMG160_SHIFT_BIT_POSITION_BY_08_BITS, BMG160_DATA_FRAME_Y_LSB_BYTE, bmg160_data_t::datay, BMG160_DATA_FRAME_Y_MSB_BYTE, BMG160_DATA_FRAME_Z_LSB_BYTE, bmg160_data_t::dataz, BMG160_DATA_FRAME_Z_MSB_BYTE, bmg160_data_t::intstatus, BMG160_INTR0_STAT, BMG160_DATA_FRAME_INTR0_BYTE, BMG160_INTR1_STAT, BMG160_DATA_FRAME_INTR1_BYTE, BMG160_INTR2_STAT, BMG160_DATA_FRAME_INTR2_BYTE, BMG160_INTR3_STAT, BMG160_DATA_FRAME_INTR3_BYTE, BMG160_INTR4_STAT, BMG160_DATA_FRAME_INTR4_BYTE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_data_Y(s16 *v_data_y_s16)
Reads Rate data Y in the registers 0x04 to 0x05.
v_data_y_s16 The value of gyro y axis data results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_Y_DATA_SIZE, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_RATE_Y_LSB_BIT__REG, BMG160_Y_DATA_LENGTH, BMG160_Y_LSB_DATA, BMG160_GET_BITSLICE, BMG160_Y_MSB_DATA, BMG160_SHIFT_BIT_POSITION_BY_08_BITS.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_data_Z(s16 *v_data_z_s16)
Reads Rate data Z in the registers 0x06 to 0x07.
v_data_z_s16 The value of gyro z axis data results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_Z_DATA_SIZE, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_RATE_Z_LSB_BIT__REG, BMG160_Z_DATA_LENGTH, BMG160_Z_LSB_DATA, BMG160_GET_BITSLICE, BMG160_Z_MSB_DATA, BMG160_SHIFT_BIT_POSITION_BY_08_BITS.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_fast_offset_enable_axis(u8 *v_fast_offset_u8)
This API read the Fast offset enable v_axis_u8(X,Y and Z) in the register 0x32.
X_AXIS -> bit 0 Y_AXIS -> bit 1 Z_AXIS -> bit 2 v_fast_offset_u8 The value of fast offset enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_FAST_OFFSET_ENABLE_XYZ__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_FIFO_data_reg(u8 *v_fifo_data_u8)
Reads FIFO data from location 0x3F.
v_fifo_data_u8 : The data of fifo results of bus communication function 0 -> Success -1 -> Error result of communication routines
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_FIFO_DATA_ADDR, BMG160_GEN_READ_WRITE_DATA_LENGTH.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_fifo_data_select(u8 *v_fifo_data_select_u8)
This API is used to get the status of fifo data select in the register 0x3E bit 0 and 1.
v_fifo_data_select_u8 : The value of fifo data selection data selection value X,Y and Z (DEFAULT) 0 X only 1 Y only 2 Z only 3 results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_FIFO_CGF0_ADDR_DATA_SELECT__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_fifo_enable(u8 *v_fifo_enable_u8)
This API is used to get the fifo(fifo_enable) interrupt enable bits of the sensor in the registers 0x15 bit 6.
v_fifo_enable_u8 : The value of fifo enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_ENABLE0_FIFO__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_fifo_frame_count(u8 *v_fifo_frame_count_u8)
this API is used to get the fifo frame counter in the register 0x0E bit 0 to 6
v_fifo_frame_count_u8 The value of fifo frame counter results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_FIFO_STAT_FRAME_COUNTER__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_fifo_mode(u8 *v_fifo_mode_u8)
This API is used to get the status of fifo mode in the register 0x3E bit 6 and 7.
v_fifo_mode_u8 : The value of fifo mode mode value BYPASS 0 FIFO 1 STREAM 2 RESERVED 3 results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_FIFO_CGF0_ADDR_MODE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_fifo_overrun(u8 *v_fifo_overrun_u8)
this API is used to get the fifo over run in the register 0x0E bit 7
v_fifo_overrun_u8 The value of fifo over run results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_FIFO_STAT_OVERRUN__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_fifo_stat_reg(u8 *v_fifo_stat_u8)
this api is used to read the fifo status of frame_counter and overrun in the register 0x0E
frame_counter > bit from 0 to 6 overrun -> bit 7 v_fifo_stat_u8 : The value of fifo overrun and fifo counter results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_FIFO_STAT_ADDR, BMG160_GEN_READ_WRITE_DATA_LENGTH.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_fifo_tag(u8 *v_fifo_tag_u8)
This API is used to get the status of FIFO tag in the register 0x3D bit 7.
v_fifo_tag_u8 : The value of fifo tag enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_FIFO_CGF1_ADDR_TAG__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_fifo_wm_enable(u8 *v_fifo_wm_enable_u8)
This API is used to get the status of fifo water mark in the register 0x1E bit 7.
v_fifo_wm_enable_u8 : The value of fifo water mark enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_4_FIFO_WM_ENABLE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_fifo_wm_level(u8 *v_fifo_wm_level_u8)
This API is used to get Water Mark Level in the register 0x3D bit from 0 to 6.
v_fifo_wm_level_u8 : The value of fifo water mark level results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_FIFO_CGF1_ADDR_WML__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_gp(u8 v_param_u8, u8 *v_gp_u8)
This API is used to get the status of general purpose register in the register 0x3A and 0x3B.
v_param_u8 The value of general purpose register select v_param_u8 value BMG160_GP0 0 BMG160_GP1 1 v_gp_u8 The value of general purpose register results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_GP0, bmg160_t::dev_addr, BMG160_TRIM_GP0_ADDR_GP0__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_GP1, BMG160_TRIM_GP1_ADDR, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_high_bw(u8 *v_high_bw_u8)
This API is used to get data high bandwidth in the register 0x13 bit 7.
v_high_bw_u8 : The value of high bandwidth value Description 1 unfiltered 0 filtered results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_HIGH_BW__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_highrate_durn_axis(u8 v_channel_u8, u8 *v_highrate_durn_axis_u8)
This API is used to get the status of High duration of X,Y,Z axis in the registers 0x23, 0x25 and 0x27.
X_AXIS - 0x23 bit form 0 to 7 Y_AXIS - 0x25 bit form 0 to 7 Z_AXIS - 0x27 bit form 0 to 7 v_channel_u8 The value of High Duration channel number v_channel_u8 value BMG160_X_AXIS 0 BMG160_Y_AXIS 1 BMG160_Z_AXIS 2 v_highrate_durn_axis_u8 The value of high duration High rate duration can be calculated by using the formula High_durn = ((1+v_highrate_durn_axis_u8)*2.5ms) results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_HIGHRATE_DURN_X_ADDR, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_Y_AXIS, BMG160_HIGHRATE_THRES_Y_ADDR, BMG160_Z_AXIS, BMG160_HIGHRATE_THRES_Z_ADDR, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_highrate_enable_axis(u8 v_channel_u8, u8 *v_enable_u8)
This API is used to get the status of High Enable Channel X,Y,Z in the registers 0x22, 0x24 and 0x26.
X_AXIS - 0x22 bit 0 Y_AXIS - 0x24 bit 0 Z_AXIS - 0x26 bit 0 v_channel_u8 : The value of high enable channel number v_channel_u8 value BMG160_X_AXIS 0 BMG160_Y_AXIS 1 BMG160_Z_AXIS 2 v_enable_u8 The value of high axis enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_HIGHRATE_ENABLE_X__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_Y_AXIS, BMG160_HIGHRATE_ENABLE_Y__REG, BMG160_Z_AXIS, BMG160_HIGHRATE_ENABLE_Z__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_highrate_hyst(u8 v_channel_u8, u8 *v_highrate_hyst_u8)
This API is used to get the status of High Hysteresis of X,Y,Z axis in the registers 0x22,0x24 and 0x26.
X_AXIS - 0x22 bit 6 and 7 Y_AXIS - 0x24 bit 6 and 7 Z_AXIS - 0x26 bit 6 and 7 v_channel_u8 The value of high Hysteresis channel number v_channel_u8 value BMG160_X_AXIS 0 BMG160_Y_AXIS 1 BMG160_Z_AXIS 2 v_highrate_hyst_u8 The value of high Hysteresis High hysteresis can be calculated by High_hyst = ((255+256 *v_highrate_hyst_u8) * 4LSB) results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_HIGHRATE_HYST_X__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_Y_AXIS, BMG160_HIGHRATE_HYST_Y__REG, BMG160_Z_AXIS, BMG160_HIGHRATE_HYST_Z__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_highrate_thres(u8 v_channel_u8, u8 *v_highrate_thres_u8)
This API is used to get the value of High rate Threshold of X,Y,Z axis in the registers 0x22, 0x24 and 0x26.
X_AXIS - 0x22 bit from 1 to 5 Y_AXIS - 0x24 bit from 1 to 5 Z_AXIS - 0x26 bit from 1 to 5 v_channel_u8 : The value of high threshold channel number v_channel_u8 value BMG160_X_AXIS 0 BMG160_Y_AXIS 1 BMG160_Z_AXIS 2 v_highrate_thres_u8 the high threshold value High Threshold can be calculated by High_thres = ((255+256 *v_highrate_thres_u8) * 4LSB) results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_HIGHRATE_THRES_X__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_Y_AXIS, BMG160_HIGHRATE_THRES_Y__REG, BMG160_Z_AXIS, BMG160_HIGHRATE_THRES_Z__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_i2c_wdt(u8 v_channel_u8, u8 *v_i2c_wdt_u8)
This API is used to get the status of i2c wdt select and enable in the register 0x34.
i2c_wdt_select -> bit 1 i2c_wdt_enable -> bit 2 v_channel_u8 The value of i2c wdt channel number v_channel_u8 value BMG160_I2C_WDT_ENABLE 1 BMG160_I2C_WDT_SELECT 0 v_i2c_wdt_u8 The value of I2C enable and WDT select value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_I2C_WDT_ENABLE, bmg160_t::dev_addr, BMG160_BGW_SPI3_WDT_ADDR_I2C_WDT_ENABLE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_I2C_WDT_SELECT, BMG160_BGW_SPI3_WDT_ADDR_I2C_WDT_SELECT__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr1_any_motion(u8 *v_int1r_any_motion_u8)
This API is used to get the any motion(int1_any) interrupt1 enable bits of the sensor in the registers 0x17 bit 1.
v_int1r_any_motion_u8 : The value of any motion interrupt1 value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_MAP_ZERO_INTR1_ANY_MOTION__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr1_fifo(u8 *v_intr_fifo_u8)
This API is used to get the fifo(int1_fifo) interrupt1 enable bits of the sensor in the registers 0x18 bit 5.
v_intr_fifo_u8 : The interrupt1 fifo value value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_MAP_ONE_INTR1_FIFO__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr1_highrate(u8 *v_intr1_u8)
This API is used to get the high rate(int1_high) interrupt1 enable bits of the sensor in the registers 0x17 bit 3.
v_intr1_u8 : The value of interrupt1 high_rate enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_MAP_ZERO_INTR1_HIGHRATE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr2_any_motion(u8 *v_intr2_any_motion_u8)
This API is used to get the any motion(int2_any_motion) interrupt2 enable bits of the sensor in the registers 0x19 bit 1.
v_intr2_any_motion_u8 : The value of interrupt2 any_motion value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_MAP_TWO_INTR2_ANY_MOTION__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr2_fifo(u8 *v_intr_fifo_u8)
This API is used to get the fifo(int2_fifo) interrupt2 enable bits of the sensor in the registers 0x18 bit 5.
v_intr_fifo_u8 : The interrupt2 fifo value value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_MAP_ONE_INTR2_FIFO__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr2_highrate(u8 *v_intr2_highrate_u8)
This API is used to get the high rate(int2_high_rate) interrupt2 enable bits of the sensor in the registers 0x19 bit 3.
v_intr2_highrate_u8 : The interrupt2 high_rate value value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_MAP_TWO_INTR2_HIGHRATE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr2_offset(u8 v_axis_u8, u8 *v_intr2_offset_u8)
This API is used to get the fast offset(intr2_fast_offset) and auto offset(intr2_auto_offset) of interrupt2 in the register 0x18.
int2_fast_offset -> bit 6 int2_auto_offset -> bit 4 v_axis_u8 The value of fast/auto offset interrupts selection v_axis_u8 Data interrupt 1 BMG160_FAST_OFFSET 2 BMG160_AUTO_OFFSET v_intr2_offset_u8 The value of fast/auto offset enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_FAST_OFFSET, bmg160_t::dev_addr, BMG160_MAP_ONE_INTR2_FAST_OFFSET__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_AUTO_OFFSET, BMG160_MAP_ONE_INTR2_AUTO_OFFSET__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr_data(u8 v_axis_u8, u8 *v_intr_data_u8)
This API is used to get the data interrupt1 and interrupt2(int1_data and int2_data) in the register 0x18.
INT1 -> bit 0 INT2 -> bit 7 v_axis_u8 data interrupt selection v_axis_u8 Data interrupt 0 BMG160_INTR1_DATA 1 BMG160_INTR2_DATA v_intr_data_u8 The value of data interrupt1 or interrupt2 value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_INTR1_DATA, bmg160_t::dev_addr, BMG160_MAP_ONE_INTR1_DATA__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_INTR2_DATA, BMG160_MAP_ONE_INTR2_DATA__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr_level(u8 v_param_u8, u8 *v_intr_level_u8)
This API is used to get Active Level status in the register 0x16.
INT1 -> bit 0 INT2 -> bit 2 v_param_u8 The value of Active Level selection number v_param_u8Active Level 0 BMG160_INTR1 1 BMG160_INTR2 v_intr_level_u8 The value of Active Level status value value Active Level 1 Active HIGH 0 Active LOW results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_INTR1, bmg160_t::dev_addr, BMG160_INTR_ENABLE1_IT1_LEVEL__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_INTR2, BMG160_INTR_ENABLE1_IT2_LEVEL__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr_offset(u8 v_axis_u8, u8 *v_intr1_offset_u8)
This API is used to get the fast offset(int1_fast_offset) and auto offset(int1_auto_offset) of interrupt1 in the register 0x18.
int1_fast_offset -> bit 1 int1_auto_offset -> bit 3 v_axis_u8 The value of fast/auto offset interrupts selection v_axis_u8 Data interrupt 1 BMG160_FAST_OFFSET 2 BMG160_AUTO_OFFSET v_intr1_offset_u8 The value of fast/auto offset value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_FAST_OFFSET, bmg160_t::dev_addr, BMG160_MAP_ONE_INTR1_FAST_OFFSET__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_AUTO_OFFSET, BMG160_MAP_ONE_INTR1_AUTO_OFFSET__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr_output_type(u8 v_param_u8, u8 *v_intr_output_type_u8)
This API is used to get the output type status in the register 0x16.
INT1 -> bit 1 INT2 -> bit 3 v_param_u8 The value of output type selection number v_param_u8output type 0 BMG160_INTR1 1 BMG160_INTR2 v_intr_output_type_u8 The value of output type value output 1 open drain 0 push pull results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_INTR1, bmg160_t::dev_addr, BMG160_INTR_ENABLE1_IT1_OUTPUT_TYPE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_INTR2, BMG160_INTR_ENABLE1_IT2_OUTPUT_TYPE__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr_stat_reg_one(u8 *v_stat1_data_u8)
This api used to reads the interrupt status of data, auto_offset, fast_offset and fifo_int in the register 0x0A.
data bit -> 7 auto_offset bit -> 6 fast_offset bit -> 5 fifo_int bit -> 4 v_stat1_data_u8 : The interrupt status of data, auto_offset, fast_offset and fifo_int results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_STAT_ONE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr_stat_reg_three(u8 *v_stat3_data_u8)
This api used to reads the interrupt status of high_rate sign, high_rate first_z, high_rate first_x and high_rate first_y in the register 0x0C.
high_rate sign bit -> 3 high_rate first_z bit -> 2 high_rate first_x bit -> 1 high_rate first_y bit -> 0 high_rate first_y bit -> 0 v_stat3_data_u8 : The interrupt status of high_rate sign, high_rate first_z, high_rate first_x and high_rate first_y results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_STAT_THREE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr_stat_reg_two(u8 *v_stat2_data_u8)
This api used to reads the interrupt status of.
any motion sign, any motion first_z, any motion first_x and any motion first_y in the register 0x0B any motion sign bit -> 3 any motion first_z bit -> 2 any motion first_x bit -> 1 any motion first_y bit -> 0 v_stat2_data_u8 : Pointer holding the the interrupt status of any motion sign, any motion first_z, any motion first_x and any motion first_y results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_STAT_TWO__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr_stat_reg_zero(u8 *v_stat0_data_u8)
This api used to reads interrupt status of any motion and high rate in the register 0x09.
any motion bit -> 2 high rate bit -> 1 v_stat0_data_u8 : The interrupt status of any motion and high rate results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_STAT_ZERO__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_latch_intr(u8 *v_latch_intr_u8)
This API is used to get the Latch interrupt in the register 0x21 bit from 0 to 3.
v_latch_intr_u8 : The value of latch interrupt Latch Interrupt Value BMG160_NON_LATCH 0x00 BMG160_LATCH_250_MS 0x01 BMG160_LATCH_500_MS 0x02 BMG160_LATCH_1_SEC 0x03 BMG160_LATCH_2_SEC 0x04 BMG160_LATCH_4_SEC 0x05 BMG160_LATCH_8_SEC 0x06 BMG160_LATCH_LATCHED 0x07 BMG160_LATCH_NON_LATCHED 0x08 BMG160_LATCH_250_MICRO_SEC 0x09 BMG160_LATCH_500_MICRO_SEC 0x0A BMG160_LATCH_1_MILLI_SEC 0x0B BMG160_LATCH_12.5_MILLI_SEC 0x0C BMG160_LATCH_25_MILLI_SEC 0x0D BMG160_LATCH_50_MILLI_SEC 0x0E BMG160_LATCH_LATCHED 0x0F results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_RST_LATCH_ADDR_LATCH_INTR__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_latch_stat(u8 *v_latch_stat_u8)
This API is used to get the Latch Status in the register 0x21 bit 4.
v_latch_stat_u8 : The value of latch status value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_RST_LATCH_ADDR_LATCH_STAT__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_nvm_prog_mode(u8 *nvm_prog_mode)
This API is used to get the status of nvm program mode in the register 0x33 bit 0.
nvm_prog_mode The value of nvm program mode value Description 1 Unlock 0 Lock nvm write results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_TRIM_NVM_CTRL_ADDR_NVM_PROG_MODE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_nvm_rdy(u8 *v_nvm_rdy_u8)
This API is used to get the status of nvm program in the register 0x33 bit 2.
v_nvm_rdy_u8 The value of nvm program value Description 1 NVM write is in progress 0 NVM is ready to accept a new write results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_TRIM_NVM_CTRL_ADDR_NVM_RDY__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_nvm_remain(u8 *v_nvm_remain_u8)
This API is used to get the status of nvm program remain in the register 0x33 bit from 4 to 7.
v_nvm_remain_u8 The value of nvm program value Description 1 Do not trigger 0 Trigger results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_TRIM_NVM_CTRL_ADDR_NVM_REMAIN__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_offset(u8 v_axis_u8, s16 *v_offset_s16)
This API is used to get the value of offset X, Y and Z in the registers 0x36, 0x37, 0x38, 0x39 and 0x3A the offset is a 12bit value.
X_AXIS -> bit 0 and 1 is available in the register 0x3A bit 2 and 3 bit 2 and 3 is available in the register 0x36 bit 6 and 7 bit 4 to 11 is available in the register 0x37 bit 0 to 7 Y_AXIS -> bit 0 is available in the register 0x3A bit 1 bit 1,2 and 3 is available in the register 0x36 bit 3,4 and 5 bit 4 to 11 is available in the register 0x38 bit 0 to 7 Z_AXIS -> bit 0 is available in the register 0x3A bit 0 bit 1,2 and 3 is available in the register 0x36 bit 0,1 and 3 bit 4 to 11 is available in the register 0x39 bit 0 to 7 v_axis_u8 : The value of offset axis selection v_axis_u8 value BMG160_X_AXIS 1 BMG160_Y_AXIS 0 BMG160_Z_AXIS 0 v_offset_s16 The value of offset results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_TRIM_GP0_ADDR_OFFSET_X__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_OFC1_ADDR_OFFSET_X__REG, BMG160_SHIFT_BIT_POSITION_BY_02_BITS, BMG160_OFC2_ADDR, BMG160_SHIFT_BIT_POSITION_BY_04_BITS, BMG160_Y_AXIS, BMG160_TRIM_GP0_ADDR_OFFSET_Y__REG, BMG160_OFC1_ADDR_OFFSET_Y__REG, BMG160_SHIFT_BIT_POSITION_BY_01_BIT, BMG160_OFC3_ADDR, BMG160_Z_AXIS, BMG160_TRIM_GP0_ADDR_OFFSET_Z__REG, BMG160_OFC1_ADDR_OFFSET_Z__REG, BMG160_OFC4_ADDR, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_offset_unfilt(u8 v_param_u8, u8 *v_offset_unfilt_u8)
This API is used to get the slow offset and fast offset unfilt data in the register 0x1A and 1B.
slow_offset_unfilt -> 0x1A bit 5 fast_offset_unfilt -> 0x1B bit 7 v_param_u8 The value of fast/slow offset unfilt data selection v_param_u8 offset selection 0 BMG160_SLOW_OFFSET 1 BMG160_FAST_OFFSET v_offset_unfilt_u8 The value of fast/slow offset unfilt data value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_SLOW_OFFSET, bmg160_t::dev_addr, BMG160_INTR_ZERO_ADDR_SLOW_OFFSET_UNFILT__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_FAST_OFFSET, BMG160_INTR_ONE_ADDR_FAST_OFFSET_UNFILT__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_offset_word_length(u8 v_channel_u8, u8 *v_offset_word_length_u8)
This API is used to get Fast Offset WordLength and Auto Offset WordLength in the register 0x32.
fast_offset_wordlength -> bit 4 and 5 auto_offset_wordlength -> bit 6 and 7 v_channel_u8 The value of WordLengthchannel number v_channel_u8 value BMG160_AUTO_OFFSET_WL 0 BMG160_FAST_OFFSET_WL 1 v_offset_word_length_u8 The value of offset word length value word length 0x00 32 samples 0x01 64 samples 0x02 128 samples 0x03 256 samples results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_AUTO_OFFSET_WORD_LENGHTH, bmg160_t::dev_addr, BMG160_AUTO_OFFSET_WORD_LENGHTH__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_FAST_OFFSET_WORD_LENGHTH, BMG160_FAST_OFFSET_WORD_LENGHTH__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_pmu_ext_tri_select(u8 *v_pwu_ext_tri_select_u8)
This API used to get the status of External Trigger selection in the register 0x12h bits from 4 to 5.
v_pwu_ext_tri_select_u8 : The value of External Trigger selection v_pwu_ext_tri_select_u8 Trigger source 0x00 No 0x01 INT1 pin 0x02 INT2 pin 0x03 SDO pin(SPI3 mode) results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_MODE_LPM2_ADDR_EXT_TRI_SELECT__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_power_mode(u8 *v_power_mode_u8)
This API is used to get the operating modes of the sensor in the registers 0x11 and 0x12.
v_power_mode_u8 :The value of power mode value power mode 0 BMG160_MODE_NORMAL 1 BMG160_MODE_SUSPEND 2 BMG160_MODE_DEEPSUSPEND 3 BMG160_MODE_FASTPOWERUP 4 BMG160_MODE_ADVANCEDPOWERSAVING results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_MODE_LPM1_ADDR, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_MODE_LPM2_ADDR, BMG160_MODE_ADVANCEDPOWERSAVING, BMG160_MODE_NORMAL, BMG160_MODE_DEEPSUSPEND, BMG160_MODE_SUSPEND, BMG160_MODE_FASTPOWERUP.
Referenced by bmg160_set_bw, Gyroscope_getMode.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_range_reg(u8 *v_range_u8)
This API is used to get the range in the register 0x0F bits from 0 to 2.
v_range_u8 : The value of gyro range value range 0x00 BMG160_RANGE_2000 0x01 BMG160_RANGE_1000 0x02 BMG160_RANGE_500 0x03 BMG160_RANGE_250 0x04 BMG160_RANGE_125 results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_RANGE_ADDR_RANGE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
Referenced by Gyroscope_getRange.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_shadow_dis(u8 *v_shadow_dis_u8)
This API is used to get the shadow dis in the register 0x13 bit 6.
v_shadow_dis_u8 : The value of shadow dis value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_SHADOW_DIS__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_sleep_durn(u8 *v_durn_u8)
This API is used to get the sleep duration in the register 0x11 bit 1 to 3.
v_durn_u8 : The value of sleep duration sleep duration value 2ms 0 4ms 1 5ms 2 8ms 3 10ms 4 15ms 5 18ms 6 20ms 7 results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_MODELPM1_ADDR_SLEEP_DURN__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_slow_offset_durn(u8 *v_offset_durn_u8)
This API is used to get Slow Offset duration status in the register 0x31 bit 4,5 and 6.
v_offset_durn_u8 : The value of Slow Offset duration value Duration 0x00 40ms 0x01 80ms 0x02 160ms 0x03 320ms 0x04 640ms 0x05 1280ms 0x06 unused 0x07 unused results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_SLOW_OFFSET_DURN__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_slow_offset_enable_axis(u8 v_channel_u8, u8 *v_slow_offset_u8)
This API is used to get Slow Offset Enable channel X,Y,Z in the register 0x31.
X_AXIS -> bit 0 Y_AXIS -> bit 1 Z_AXIS -> bit 2 v_channel_u8 The value of slow offset channel number v_channel_u8 value BMG160_X_AXIS 0 BMG160_Y_AXIS 1 BMG160_Z_AXIS 2 v_slow_offset_u8 The slow offset value value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_SLOW_OFFSET_ENABLE_X__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_Y_AXIS, BMG160_SLOW_OFFSET_ENABLE_Y__REG, BMG160_Z_AXIS, BMG160_SLOW_OFFSET_ENABLE_Z__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_slow_offset_thres(u8 *v_offset_thres_u8)
This API is used to get Slow Offset Threshold status in the register 0x31 bit 6 and 7.
v_offset_thres_u8 : The value of slow offset Threshold value threshold 0x00 0.1 degree/sec 0x01 0.2 degree/sec 0x02 0.5 degree/sec 0x03 1 degree/sec results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_SLOW_OFFSET_THRES__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_spi3(u8 *v_spi3_u8)
This API is used to get the status of spi3 in the register 0x34 bit 0.
v_spi3_u8 : The value of spi3 enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_BGW_SPI3_WDT_ADDR_SPI3__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_temp(s8 *v_temp_s8)
Reads Temperature from register location 0x08.
v_temp_s8 The value of temperature results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_TEMP_ADDR, BMG160_GEN_READ_WRITE_DATA_LENGTH.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_unfilt_data(u8 v_param_u8, u8 *v_unfilt_data_u8)
This API is used to get the any motion and high rate unfilt data in the register 0x1A.
any_unfilt_data -> bit 1 high_unfilt_data -> bit 3 v_param_u8 The value of any/high offset unfilt data selection v_param_u8 offset selection 1 BMG160_HIGHRATE_UNFILT_DATA 3 BMG160_ANY_MOTION_UNFILT_DATA v_unfilt_data_u8 The value of any/high unfilt data value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_HIGHRATE_UNFILT_DATA, bmg160_t::dev_addr, BMG160_INTR_ZERO_ADDR_HIGHRATE_UNFILT_DATA__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_ANY_MOTION_UNFILT_DATA, BMG160_INTR_ZERO_ADDR_ANY_MOTION_UNFILT_DATA__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_init(struct bmg160_t *bmg160)
This function is used for initialize the bus read and bus write functions and assign the chip id and I2C address of the gyro chip id is read in the register 0x00 bit from 0 to 7.
bmg160 structure pointer. While changing the parameter of the bmg160_t consider the following point: Changing the reference value of the parameter will changes the local copy or local reference make sure your changes will not affect the reference value of the parameter (Better case don't change the reference value of the parameter) results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, bmg160_t::dev_addr, BMG160_CHIP_ID_ADDR, BMG160_GEN_READ_WRITE_DATA_LENGTH, bmg160_t::chip_id.
Referenced by Bmg160Utils_initialize.
BMG160_RETURN_FUNCTION_TYPE bmg160_read_register(u8 v_addr_u8, u8 *v_data_u8, u8 v_len_u8)
This API reads the data from the given register.
v_addr_u8 -> Address of the register v_data_u8 -> The data from the register v_len_u8 -> no of bytes to read results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr.
BMG160_RETURN_FUNCTION_TYPE bmg160_selftest(u8 *v_result_u8)
This API is used to to do selftest to sensor sensor in the register 0x3C.
v_result_u8 The value of self test results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, bmg160_t::dev_addr, BMG160_SELFTEST_ADDR, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_SET_BITSLICE, BMG160_SELFTEST_ADDR_TRIGBIST__REG, bmg160_t::delay_msec, BMG160_SELFTEST_DELAY, BMG160_SELFTEST_ADDR_BISTFAIL__REG, BMG160_SELFTEST_BISTFAIL, BMG160_SELFTEST_RATEOK, C_BMG160_SUCCESS, C_BMG160_FAILURE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_any_motion_durn_sample(u8 v_durn_sample_u8)
This API is used to set the any motion Duration samples in the register 0x1C bit 4 and 5.
v_durn_sample_u8 : The value of any motion duration samples value Samples 0x00 4 samples 0x01 8 samples 0x02 12 samples 0x03 16 samples results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_TWO_ADDR_ANY_MOTION_DURN_SAMPLE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_any_motion_enable_axis(u8 v_channel_u8, u8 v_any_motion_axis_u8)
This API is used to set the status of Any motion interrupt axis(X,Y,Z) enable channel.
BMG160_X_AXIS -> bit 0 BMG160_Y_AXIS -> bit 1 BMG160_Z_AXIS -> bit 2 v_channel_u8 : The value of Any Enable channel number v_channel_u8 axis 0 BMG160_X_AXIS 1 BMG160_Y_AXIS 2 BMG160_Z_AXIS v_any_motion_axis_u8 The value of Any motion axis enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_INTR_TWO_ADDR_ANY_MOTION_ENABLE_X__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_Y_AXIS, BMG160_INTR_TWO_ADDR_ANY_MOTION_ENABLE_Y__REG, BMG160_Z_AXIS, BMG160_INTR_TWO_ADDR_ANY_MOTION_ENABLE_Z__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_any_motion_thres(u8 v_any_motion_thres_u8)
This API is used to set Any motion Threshold in the register 0x1B bit from 0 to 6.
v_any_motion_thres_u8 : The value of any_motion Threshold Any motion threshold can be calculate using ((1+ v_any_motion_thres_u8)*16LSB) results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_ONE_ADDR_ANY_MOTION_THRES__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_auto_offset_enable(u8 v_offset_enable_u8)
This API is used to set the auto offset(auto_offset_enable) interrupt enable bits of the sensor in the registers 0x15 bit 3.
v_offset_enable_u8 : The value of offset enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_ENABLE0_AUTO_OFFSET__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_auto_sleep_durn(u8 v_durn_u8, u8 v_bw_u8)
This API is used to set the auto sleep duration in the register 0x12 bit 0 to 2.
v_durn_u8 : The value of gyro auto sleep duration sleep duration value not allowed 0 4ms 1 5ms 2 8ms 3 10ms 4 15ms 5 20ms 6 40ms 7 v_bw_u8 : The value of selected bandwidth v_bw_u8 value C_BMG160_NO_FILTER_U8X 0 C_BMG160_BW_230HZ_U8X 1 C_BMG160_BW_116HZ_u8X 2 C_BMG160_BW_47HZ_u8X 3 C_BMG160_BW_23HZ_u8X 4 C_BMG160_BW_12HZ_u8X 5 C_BMG160_BW_64HZ_u8X 6 C_BMG160_BW_32HZ_u8X 7 : sleep duration depends on selected power mode and bandwidth results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_MODE_LPM2_ADDR_AUTO_SLEEP_DURN__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_BIT_LENGTH_DURN, C_BMG160_NO_FILTER_U8X, C_BMG160_4MS_AUTO_SLEEP_DURN_U8X, C_BMG160_BW_230HZ_U8X, C_BMG160_BW_116HZ_U8X, C_BMG160_BW_47HZ_U8X, C_BMG160_5MS_AUTO_SLEEP_DURN_U8X, C_BMG160_BW_23HZ_U8X, C_BMG160_10MS_AUTO_SLEEP_DURN_U8X, C_BMG160_BW_12HZ_U8X, C_BMG160_20MS_AUTO_SLEEP_DURN_U8X, C_BMG160_BW_64HZ_U8X, C_BMG160_BW_32HZ_U8X, BMG160_SET_BITSLICE, E_BMG160_OUT_OF_RANGE.
Referenced by bmg160_set_bw, bmg160_set_power_mode, Gyroscope_setAutoSleepDuration.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_awake_durn(u8 v_awake_durn_u8)
This API is used to set the awake Duration in the register 0x1C bit 6 and 7.
v_awake_durn_u8 : The value of awake Duration value Duration 0x00 8 samples 0x01 16 samples 0x02 32 samples 0x03 64 samples results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_TWO_ADDR_AWAKE_DURN__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_bw(u8 v_bw_u8)
This API is used to set the gyro bandwidth in the register 0x10 bits from 0 to 3.
v_bw_u8 The value of gyro bandwidth value bandwidth 0x00 BMG160_BW_500_HZ 0x01 BMG160_BW_230_HZ 0x02 BMG160_BW_116_HZ 0x03 BMG160_BW_47_HZ 0x04 BMG160_BW_23_HZ 0x05 BMG160_BW_12_HZ 0x06 BMG160_BW_64_HZ 0x07 BMG160_BW_32_HZ results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_BIT_LENGTH_BW, bmg160_get_power_mode, BMG160_MODE_ADVANCEDPOWERSAVING, bmg160_get_auto_sleep_durn, bmg160_set_auto_sleep_durn, bmg160_t::dev_addr, BMG160_BW_ADDR__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_BW_ADDR, E_BMG160_OUT_OF_RANGE.
Referenced by Gyroscope_setBandwidth.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_data_enable(u8 v_data_enable_u8)
This API is used to set the data(data_enable) interrupt enable bits of the sensor in the registers 0x15 bit 7.
v_data_enable_u8 : The value of data enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_ENABLE0_DATA__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_fast_offset_enable_axis(u8 v_channel_u8, u8 v_fast_offset_u8)
This API set the Fast offset enable v_axis_u8(X,Y and Z) in the register 0x32.
X_AXIS -> bit 0 Y_AXIS -> bit 1 Z_AXIS -> bit 2 v_channel_u8 The value of fast offset channel select v_channel_u8 value BMG160_X_AXIS 0 BMG160_Y_AXIS 1 BMG160_Z_AXIS 2 v_fast_offset_u8 The value of fast offset enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_FAST_OFFSET_ENABLE_X__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_Y_AXIS, BMG160_FAST_OFFSET_ENABLE_Y__REG, BMG160_Z_AXIS, BMG160_FAST_OFFSET_ENABLE_Z__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_fifo_data_select(u8 v_fifo_data_select_u8)
This API is used to set the status of fifo data select in the register 0x3E bit 0 and 1.
v_fifo_data_select_u8 : The value of fifo data selection data selection value X,Y and Z (DEFAULT) 0 X only 1 Y only 2 Z only 3 results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_BIT_LENGTH_FIFO_DATA_SELECT, bmg160_t::dev_addr, BMG160_FIFO_CGF0_ADDR_DATA_SELECT__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_fifo_enable(u8 v_fifo_enable_u8)
This API is used to set the fifo(fifo_enable) interrupt enable bits of the sensor in the registers 0x15 bit 6.
v_fifo_enable_u8 : The value of fifo enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_BIT_LENGTH_FIFO, bmg160_t::dev_addr, BMG160_INTR_ENABLE0_FIFO__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_fifo_mode(u8 v_fifo_mode_u8)
This API is used to set the status of fifo mode in the register 0x3E bit 6 and 7.
v_fifo_mode_u8 : The value of fifo mode mode value BYPASS 0 FIFO 1 STREAM 2 RESERVED 3 results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_BIT_LENGTH_FIFO_MODE, bmg160_t::dev_addr, BMG160_FIFO_CGF0_ADDR_MODE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_fifo_tag(u8 v_fifo_tag_u8)
This API is used to set the status of FIFO tag in the register 0x3D bit 7.
v_fifo_tag_u8 : The value of fifo tag enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_BIT_LENGTH_FIFO_TAG, bmg160_t::dev_addr, BMG160_FIFO_CGF1_ADDR_TAG__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_fifo_wm_enable(u8 v_fifo_wm_enable_u8)
This API is used to set the status of fifo water mark in the register 0x1E bit 7.
v_fifo_wm_enable_u8 : The value of fifo water mark enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_BIT_LENGTH_FIFO_WM, bmg160_t::dev_addr, BMG160_INTR_4_FIFO_WM_ENABLE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_fifo_wm_level(u8 v_fifo_wm_level_u8)
This API is used to set Water Mark Level in the register 0x3D bit from 0 to 6.
v_fifo_wm_level_u8 : The value of fifo water mark level results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_FIFO_WM_LENGTH, bmg160_t::dev_addr, BMG160_FIFO_CGF1_ADDR_WML__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_gp(u8 v_param_u8, u8 v_gp_u8)
This API is used to set the status of general purpose register in the register 0x3A and 0x3B.
v_param_u8 The value of general purpose register select v_param_u8 value BMG160_GP0 0 BMG160_GP1 1 v_gp_u8 The value of general purpose register results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_GP0, bmg160_t::dev_addr, BMG160_TRIM_GP0_ADDR_GP0__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_GP1, BMG160_TRIM_GP1_ADDR, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_high_bw(u8 v_high_bw_u8)
This API is used to set data high bandwidth in the register 0x13 bit 7.
v_high_bw_u8 : The value of high bandwidth value Description 1 unfiltered 0 filtered results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_BIT_LENGTH_HIGH_BW, bmg160_t::dev_addr, BMG160_HIGH_BW__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, E_BMG160_OUT_OF_RANGE.
Referenced by Gyroscope_setBandwidth.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_highrate_durn_axis(u8 v_channel_u8, u8 v_highrate_durn_axis_u8)
This API is used to set the value of High duration of X,Y,Z axis in the registers 0x23, 0x25 and 0x27.
X_AXIS - 0x23 bit form 0 to 7 Y_AXIS - 0x25 bit form 0 to 7 Z_AXIS - 0x27 bit form 0 to 7 v_channel_u8 The value of High Duration channel number v_channel_u8 value BMG160_X_AXIS 0 BMG160_Y_AXIS 1 BMG160_Z_AXIS 2 v_highrate_durn_axis_u8 The value of high duration High rate duration can be calculated by using the formula High_durn = ((1+v_highrate_durn_axis_u8)*2.5ms) results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_HIGHRATE_THRES_X_ADDR, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_Y_AXIS, BMG160_HIGHRATE_THRES_Y_ADDR, BMG160_Z_AXIS, BMG160_HIGHRATE_THRES_Z_ADDR, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_highrate_enable_axis(u8 v_channel_u8, u8 v_enable_u8)
This API is used to set the status of High Enable Channel X,Y,Z in the registers 0x22, 0x24 and 0x26.
X_AXIS - 0x22 bit 0 Y_AXIS - 0x24 bit 0 Z_AXIS - 0x26 bit 0 v_channel_u8 : The value of high enable channel number v_channel_u8 value BMG160_X_AXIS 0 BMG160_Y_AXIS 1 BMG160_Z_AXIS 2 v_enable_u8 The value of high axis enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_HIGHRATE_ENABLE_X__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_Y_AXIS, BMG160_HIGHRATE_ENABLE_Y__REG, BMG160_Z_AXIS, BMG160_HIGHRATE_ENABLE_Z__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_highrate_hyst(u8 v_channel_u8, u8 v_highrate_hyst_u8)
This API is used to set the status of High Hysteresis of X,Y,Z axis in the registers 0x22,0x24 and 0x26.
X_AXIS - 0x22 bit 6 and 7 Y_AXIS - 0x24 bit 6 and 7 Z_AXIS - 0x26 bit 6 and 7 v_channel_u8 The value of high Hysteresis channel number v_channel_u8 value BMG160_X_AXIS 0 BMG160_Y_AXIS 1 BMG160_Z_AXIS 2 v_highrate_hyst_u8 The value of high Hysteresis High hysteresis can be calculated by High_hyst = ((255+256 *v_highrate_hyst_u8) * 4LSB) results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_HIGHRATE_HYST_X__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_Y_AXIS, BMG160_HIGHRATE_HYST_Y__REG, BMG160_Z_AXIS, BMG160_HIGHRATE_HYST_Z__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_highrate_thres(u8 v_channel_u8, u8 v_highrate_thres_u8)
This API is used to set the value of High rate Threshold of X,Y,Z axis in the registers 0x22, 0x24 and 0x26.
X_AXIS - 0x22 bit from 1 to 5 Y_AXIS - 0x24 bit from 1 to 5 Z_AXIS - 0x26 bit from 1 to 5 v_channel_u8 : The value of high threshold channel number v_channel_u8 value BMG160_X_AXIS 0 BMG160_Y_AXIS 1 BMG160_Z_AXIS 2 v_highrate_thres_u8 the high threshold value High Threshold can be calculated by High_thres = ((255+256 *v_highrate_thres_u8) * 4LSB) results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_HIGHRATE_THRES_X__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_Y_AXIS, BMG160_HIGHRATE_THRES_Y__REG, BMG160_Z_AXIS, BMG160_HIGHRATE_THRES_Z__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_i2c_wdt(u8 v_channel_u8, u8 v_i2c_wdt_u8)
This API is used to set the status of i2c wdt select and enable in the register 0x34.
i2c_wdt_select -> bit 1 i2c_wdt_enable -> bit 2 v_channel_u8 The value of i2c wdt channel number v_channel_u8 value BMG160_I2C_WDT_ENABLE 1 BMG160_I2C_WDT_SELECT 0 v_i2c_wdt_u8 The value of I2C enable and WDT select value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_I2C_WDT_ENABLE, bmg160_t::dev_addr, BMG160_BGW_SPI3_WDT_ADDR_I2C_WDT_ENABLE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_I2C_WDT_SELECT, BMG160_BGW_SPI3_WDT_ADDR_I2C_WDT_SELECT__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_intr1_any_motion(u8 v_int1r_any_motion_u8)
This API is used to set the any motion(int1_any) interrupt1 enable bits of the sensor in the registers 0x17 bit 1.
v_int1r_any_motion_u8 : The value of any motion interrupt1 value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_MAP_ZERO_INTR1_ANY_MOTION__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_intr1_highrate(u8 v_intr1_u8)
This API is used to set the high rate(int1_high) interrupt1 enable bits of the sensor in the registers 0x17 bit 3.
v_intr1_u8 : The value of interrupt1 high_rate enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_MAP_ZERO_INTR1_HIGHRATE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_intr1_offset(u8 v_axis_u8, u8 v_intr1_offset_u8)
This API is used to set the fast offset(int1_fast_offset) and auto offset(int1_auto_offset) of interrupt1 in the register 0x18.
int1_fast_offset -> bit 1 int1_auto_offset -> bit 3 v_axis_u8 The value of fast/auto offset interrupts selection v_axis_u8 Data interrupt 1 BMG160_FAST_OFFSET 2 BMG160_AUTO_OFFSET v_intr1_offset_u8 The value of fast/auto offset value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_FAST_OFFSET, bmg160_t::dev_addr, BMG160_MAP_ONE_INTR1_FAST_OFFSET__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_AUTO_OFFSET, BMG160_MAP_ONE_INTR1_AUTO_OFFSET__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_intr2_any_motion(u8 v_intr2_any_motion_u8)
This API is used to set the any motion(int2_any_motion) interrupt2 enable bits of the sensor in the registers 0x19 bit 1.
v_intr2_any_motion_u8 : The value of interrupt2 any_motion value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_MAP_TWO_INTR2_ANY_MOTION__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_intr2_highrate(u8 v_intr2_highrate_u8)
This API is used to set the high rate(int2_high_rate) interrupt2 enable bits of the sensor in the registers 0x19 bit 3.
v_intr2_highrate_u8 : The interrupt2 high_rate value value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_MAP_TWO_INTR2_HIGHRATE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_intr2_offset(u8 v_axis_u8, u8 v_intr2_offset_u8)
This API is used to set the fast offset(intr2_fast_offset) and auto offset(intr2_auto_offset) of interrupt2 in the register 0x18.
int2_fast_offset -> bit 6 int2_auto_offset -> bit 4 v_axis_u8 The value of fast/auto offset interrupts selection v_axis_u8 Data interrupt 1 BMG160_FAST_OFFSET 2 BMG160_AUTO_OFFSET v_intr2_offset_u8 The value of fast/auto offset enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_FAST_OFFSET, bmg160_t::dev_addr, BMG160_MAP_ONE_INTR2_FAST_OFFSET__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_AUTO_OFFSET, BMG160_MAP_ONE_INTR2_AUTO_OFFSET__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_intr_data(u8 v_axis_u8, u8 v_intr_data_u8)
This API is used to set the data interrupt1 and interrupt2(int1_data and int2_data) in the register 0x18.
INT1 -> bit 0 INT2 -> bit 7 v_axis_u8 data interrupt selection v_axis_u8 Data interrupt 0 BMG160_INTR1_DATA 1 BMG160_INTR2_DATA v_intr_data_u8 The value of data interrupt1 or interrupt2 value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_INTR1_DATA, bmg160_t::dev_addr, BMG160_MAP_ONE_INTR1_DATA__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_INTR2_DATA, BMG160_MAP_ONE_INTR2_DATA__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_intr_fifo(u8 v_axis_u8, u8 v_intr_fifo_u8)
This API is used to set the value of the fifo interrupt1 and interrupt2(int1_fifo and int2_fifo) in the register 0x18.
int1_fifo -> bit 2 int2_fifo -> bit 5 v_axis_u8 The value of fifo interrupts selection v_axis_u8 fifo interrupt 0 BMG160_INTR1 1 BMG160_INTR2 v_intr_fifo_u8 the value of int1_fifo/int2_fifo enable/disable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_INTR1, bmg160_t::dev_addr, BMG160_MAP_ONE_INTR1_FIFO__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_INTR2, BMG160_MAP_ONE_INTR2_FIFO__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_intr_level(u8 v_param_u8, u8 v_intr_level_u8)
This API is used to set Active Level status in the register 0x16.
INT1 -> bit 0 INT2 -> bit 2 v_param_u8 The value of Active Level selection number v_param_u8Active Level 0 BMG160_INTR1 1 BMG160_INTR2 v_intr_level_u8 The value of Active Level status value value Active Level 1 Active HIGH 0 Active LOW results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_INTR1, bmg160_t::dev_addr, BMG160_INTR_ENABLE1_IT1_LEVEL__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_INTR2, BMG160_INTR_ENABLE1_IT2_LEVEL__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_intr_output_type(u8 v_param_u8, u8 v_intr_output_type_u8)
This API is used to set the output type status in the register 0x16.
INT1 -> bit 1 INT2 -> bit 3 v_param_u8 The value of output type selection number v_param_u8output type 0 BMG160_INTR1 1 BMG160_INTR2 v_intr_output_type_u8 The value of output type value output 1 open drain 0 push pull results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_INTR1, bmg160_t::dev_addr, BMG160_INTR_ENABLE1_IT1_OUTPUT_TYPE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_INTR2, BMG160_INTR_ENABLE1_IT2_OUTPUT_TYPE__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_latch_intr(u8 v_latch_intr_u8)
This API is used to set the Latch interrupt in the register 0x21 bit from 0 to 3.
v_latch_intr_u8 : The value of latch interrupt Latch Interrupt Value BMG160_NON_LATCH 0x00 BMG160_LATCH_250_MS 0x01 BMG160_LATCH_500_MS 0x02 BMG160_LATCH_1_SEC 0x03 BMG160_LATCH_2_SEC 0x04 BMG160_LATCH_4_SEC 0x05 BMG160_LATCH_8_SEC 0x06 BMG160_LATCH_LATCHED 0x07 BMG160_LATCH_NON_LATCHED 0x08 BMG160_LATCH_250_MICRO_SEC 0x09 BMG160_LATCH_500_MICRO_SEC 0x0A BMG160_LATCH_1_MILLI_SEC 0x0B BMG160_LATCH_12.5_MILLI_SEC 0x0C BMG160_LATCH_25_MILLI_SEC 0x0D BMG160_LATCH_50_MILLI_SEC 0x0E BMG160_LATCH_LATCHED 0x0F results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_RST_LATCH_ADDR_LATCH_INTR__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_latch_stat(u8 v_latch_stat_u8)
This API is used to set the Latch Status in the register 0x21 bit 4.
v_latch_stat_u8 : The value of latch status value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_RST_LATCH_ADDR_LATCH_STAT__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_nvm_load(u8 v_nvm_load_u8)
This API is used to set the status of nvm program remain in the register 0x33 bit from 4 to 7.
v_nvm_load_u8 The value of nvm program value Description 1 Do not trigger 0 Trigger results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_TRIM_NVM_CTRL_ADDR_NVM_LOAD__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_nvm_prog_mode(u8 nvm_prog_mode)
This API is used to set the status of nvm program mode in the register 0x33 bit 0.
nvm_prog_mode The value of nvm program mode value Description 1 Unlock 0 Lock nvm write results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_TRIM_NVM_CTRL_ADDR_NVM_PROG_MODE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_nvm_prog_trig(u8 nvm_prog_trig)
This API is used to set the status of nvm ready in the register 0x33 bit 1.
nvm_prog_trig The value of nvm program value Description 1 program seq in progress 0 program seq finished results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_TRIM_NVM_CTRL_ADDR_NVM_PROG_TRIG__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_offset(u8 v_axis_u8, s16 v_offset_s16)
This API is used to set the value of offset X, Y and Z in the registers 0x36, 0x37, 0x38, 0x39 and 0x3A the offset is a 12bit value.
X_AXIS -> bit 0 and 1 is available in the register 0x3A bit 2 and 3 bit 2 and 3 is available in the register 0x36 bit 6 and 7 bit 4 to 11 is available in the register 0x37 bit 0 to 7 Y_AXIS -> bit 0 is available in the register 0x3A bit 1 bit 1,2 and 3 is available in the register 0x36 bit 3,4 and 5 bit 4 to 11 is available in the register 0x38 bit 0 to 7 Z_AXIS -> bit 0 is available in the register 0x3A bit 0 bit 1,2 and 3 is available in the register 0x36 bit 0,1 and 3 bit 4 to 11 is available in the register 0x39 bit 0 to 7 v_axis_u8 : The value of offset axis selection v_axis_u8 value BMG160_X_AXIS 1 BMG160_Y_AXIS 0 BMG160_Z_AXIS 0 v_offset_s16 The value of offset results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, BMG160_OFFSET_MASK_BYTE_OF_DATA, BMG160_SHIFT_BIT_POSITION_BY_04_BITS, bmg160_t::dev_addr, BMG160_OFC2_ADDR, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_OFFSET_X_BIT_MASK1, BMG160_SET_BITSLICE, BMG160_OFC1_ADDR_OFFSET_X__REG, BMG160_OFFSET_X_BIT_MASK2, BMG160_TRIM_GP0_ADDR_OFFSET_X__REG, BMG160_Y_AXIS, BMG160_OFC3_ADDR, BMG160_OFFSET_Y_Z_BIT_MASK2, BMG160_OFC1_ADDR_OFFSET_Y__REG, BMG160_OFFSET_Y_Z_BIT_MASK1, BMG160_TRIM_GP0_ADDR_OFFSET_Y__REG, BMG160_Z_AXIS, BMG160_OFC4_ADDR, BMG160_OFC1_ADDR_OFFSET_Z__REG, BMG160_TRIM_GP0_ADDR_OFFSET_Z__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_offset_rst(u8 v_offset_rst_u8)
This API is used to set the offset Reset in the register 0x21 bit 6.
v_offset_rst_u8 the value of reset offset results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_RST_LATCH_ADDR_OFFSET_RST__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_offset_unfilt(u8 v_param_u8, u8 v_offset_unfilt_u8)
This API is used to set the slow offset and fast offset unfilt data in the register 0x1A and 1B.
slow_offset_unfilt -> 0x1A bit 5 fast_offset_unfilt -> 0x1B bit 7 v_param_u8 The value of fast/slow offset unfilt data selection v_param_u8 offset selection 0 BMG160_SLOW_OFFSET 1 BMG160_FAST_OFFSET v_offset_unfilt_u8 The value of fast/slow offset unfilt data value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_SLOW_OFFSET, bmg160_t::dev_addr, BMG160_INTR_ZERO_ADDR_SLOW_OFFSET_UNFILT__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_FAST_OFFSET, BMG160_INTR_ONE_ADDR_FAST_OFFSET_UNFILT__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_offset_word_length(u8 v_channel_u8, u8 v_offset_word_length_u8)
This API is used to set Fast Offset WordLength and Auto Offset WordLength in the register 0x32.
fast_offset_wordlength -> bit 4 and 5 auto_offset_wordlength -> bit 6 and 7 v_channel_u8 The value of WordLengthchannel number v_channel_u8 value BMG160_AUTO_OFFSET_WL 0 BMG160_FAST_OFFSET_WL 1 v_offset_word_length_u8 The value of offset word length value word length 0x00 32 samples 0x01 64 samples 0x02 128 samples 0x03 256 samples results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_AUTO_OFFSET_WORD_LENGHTH, bmg160_t::dev_addr, BMG160_AUTO_OFFSET_WORD_LENGHTH__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_FAST_OFFSET_WORD_LENGHTH, BMG160_FAST_OFFSET_WORD_LENGHTH__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_pmu_ext_tri_select(u8 v_pwu_ext_tri_select_u8)
This API used to set the status of External Trigger selection in the register 0x12h bits from 4 to 5.
v_pwu_ext_tri_select_u8 : The value of External Trigger selection v_pwu_ext_tri_select_u8 Trigger source 0x00 No 0x01 INT1 pin 0x02 INT2 pin 0x03 SDO pin(SPI3 mode) results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_MODE_LPM2_ADDR_EXT_TRI_SELECT__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_power_mode(u8 v_power_mode_u8)
This API is used to set the operating modes of the sensor in the registers 0x11 and 0x12.
v_power_mode_u8 :The value of power mode value power mode 0 BMG160_MODE_NORMAL 1 BMG160_MODE_SUSPEND 2 BMG160_MODE_DEEPSUSPEND 3 BMG160_MODE_FASTPOWERUP 4 BMG160_MODE_ADVANCEDPOWERSAVING results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, E_BMG160_NULL_PTR, BMG160_BIT_LENGTH_POWER_MODE, bmg160_t::dev_addr, BMG160_MODE_LPM1_ADDR, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_MODE_LPM2_ADDR, BMG160_MODE_NORMAL, BMG160_SET_BITSLICE, bmg160_t::delay_msec, BMG160_POWER_MODE_DELAY, BMG160_MODE_DEEPSUSPEND, BMG160_MODE_SUSPEND, BMG160_BIT_MASK_MODE_LPM1, BMG160_MODE_FASTPOWERUP, BMG160_MODE_ADVANCEDPOWERSAVING, bmg160_get_bw, bmg160_get_auto_sleep_durn, bmg160_set_auto_sleep_durn, E_BMG160_OUT_OF_RANGE.
Referenced by Gyroscope_setMode.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_range_reg(u8 v_range_u8)
This API is used to set the range in the register 0x0F bits from 0 to 2.
v_range_u8 : The value of gyro range value range 0x00 BMG160_RANGE_2000 0x01 BMG160_RANGE_1000 0x02 BMG160_RANGE_500 0x03 BMG160_RANGE_250 0x04 BMG160_RANGE_125 results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_BIT_LENGTH_RANGE, bmg160_t::dev_addr, BMG160_RANGE_ADDR_RANGE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, E_BMG160_OUT_OF_RANGE.
Referenced by Gyroscope_setRange.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_rst_intr(u8 v_rst_int_u8)
This API is used to set the Interrupt Reset in the register 0x21 bit 7.
v_rst_int_u8 the value of reset interrupt results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_RST_LATCH_ADDR_RST_INTR__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_shadow_dis(u8 v_shadow_dis_u8)
This API is used to set the shadow dis in the register 0x13 bit 6.
v_shadow_dis_u8 : The value of shadow dis value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_BIT_LENGTH_SHADOW_DIS, bmg160_t::dev_addr, BMG160_SHADOW_DIS__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_sleep_durn(u8 v_durn_u8)
This API is used to set the sleep duration in the register 0x11 bit 1 to 3.
v_durn_u8 : The value of sleep duration sleep duration value 2ms 0 4ms 1 5ms 2 8ms 3 10ms 4 15ms 5 18ms 6 20ms 7 results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_BIT_LENGTH_DURN, bmg160_t::dev_addr, BMG160_MODELPM1_ADDR_SLEEP_DURN__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, E_BMG160_OUT_OF_RANGE.
Referenced by Gyroscope_setSleepDuration.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_slow_offset_durn(u8 v_offset_durn_u8)
This API is used to set Slow Offset duration status in the register 0x31 bit 4,5 and 6.
v_offset_durn_u8 : The value of Slow Offset duration value Duration 0x00 40ms 0x01 80ms 0x02 160ms 0x03 320ms 0x04 640ms 0x05 1280ms 0x06 unused 0x07 unused results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_SLOW_OFFSET_DURN__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_slow_offset_enable_axis(u8 v_channel_u8, u8 v_slow_offset_u8)
This API is used to set Slow Offset Enable channel X,Y,Z in the register 0x31.
X_AXIS -> bit 0 Y_AXIS -> bit 1 Z_AXIS -> bit 2 v_channel_u8 The value of slow offset channel number v_channel_u8 value BMG160_X_AXIS 0 BMG160_Y_AXIS 1 BMG160_Z_AXIS 2 v_slow_offset_u8 The slow offset value value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_SLOW_OFFSET_ENABLE_X__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_Y_AXIS, BMG160_SLOW_OFFSET_ENABLE_Y__REG, BMG160_Z_AXIS, BMG160_SLOW_OFFSET_ENABLE_Z__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_slow_offset_thres(u8 v_offset_thres_u8)
This API is used to set Slow Offset Threshold status in the register 0x31 bit 6 and 7.
v_offset_thres_u8 : The value of slow offset Threshold value threshold 0x00 0.1 degree/sec 0x01 0.2 degree/sec 0x02 0.5 degree/sec 0x03 1 degree/sec results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_SLOW_OFFSET_THRES__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_soft_rst(void)
This function is used for the soft reset The soft reset register will be written with 0xB6 in the register 0x14.results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_SOFT_RESET, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_BGW_SOFT_RST_ADDR, BMG160_GEN_READ_WRITE_DATA_LENGTH.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_spi3(u8 v_spi3_u8)
This API is used to set the status of spi3 in the register 0x34 bit 0.
v_spi3_u8 : The value of spi3 enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_BGW_SPI3_WDT_ADDR_SPI3__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_unfilt_data(u8 v_param_u8, u8 v_unfilt_data_u8)
This API is used to set the any motion and high rate unfilt data in the register 0x1A.
any_unfilt_data -> bit 1 high_unfilt_data -> bit 3 v_param_u8 The value of any/high offset unfilt data selection v_param_u8 offset selection 1 BMG160_HIGHRATE_UNFILT_DATA 3 BMG160_ANY_MOTION_UNFILT_DATA v_unfilt_data_u8 The value of any/high unfilt data value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_HIGHRATE_UNFILT_DATA, bmg160_t::dev_addr, BMG160_INTR_ZERO_ADDR_HIGHRATE_UNFILT_DATA__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_ANY_MOTION_UNFILT_DATA, BMG160_INTR_ZERO_ADDR_ANY_MOTION_UNFILT_DATA__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_write_register(u8 v_addr_u8, u8 *v_data_u8, u8 v_len_u8)
This API write the data to the given register.
v_addr_u8 -> Address of the register v_data_u8 -> The data from the register v_len_u8 -> no of bytes to read results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr.