bmg160.h
BMG160_BUS_WR_RETURN_TYPE
Define the calling convention of YOUR bus communication routine.
This includes types of parameters. This example shows the configuration for an SPI bus link. If your communication function looks like this:write_my_bus_xy(u8 device_addr, u8 register_addr, u8 * data, u8 length);The BMG160_WR_FUNC_PTR would equal:BMG160_WR_FUNC_PTR s8 (* bus_write)(u8, u8, u8 *, u8)Parameters can be mixed as needed refer to the refer BMG160_BUS_WRITE_FUNC macro.
BMG160_BUS_WR_PARAM_TYPES
BMG160_BUS_WR_PARAM_ORDER
BMG160_BUS_WRITE_FUNC
link macro between API function calls and bus read function The bus write function can change since this is a system dependant issue. If the bus_read parameter calling order is like: reg_addr, reg_data, wr_len it would be as it is here.If the parameters are differently ordered or your communication function like I2C need to know the device address, you can change this macro accordingly.BMG160_BUS_READ_FUNC(dev_addr, reg_addr, reg_data, wr_len)\ bus_read(dev_addr, reg_addr, reg_data, wr_len)This macro lets all API functions call YOUR communication routine in a way that equals your definition in the refer BMG160_WR_FUNC_PTR definition.: this macro also includes the "MSB='1' for reading BMG160 addresses.
BMG160_BUS_RD_RETURN_TYPE
BMG160_BUS_RD_PARAM_TYPES
BMG160_BUS_RD_PARAM_ORDER
BMG160_BUS_READ_FUNC
BMG160_BURST_RD_RETURN_TYPE
BMG160_BURST_RD_PARAM_TYPES
BMG160_BURST_RD_PARAM_ORDER
BMG160_BURST_READ_FUNC
BMG160_DELAY_RETURN_TYPE
defines the return parameter type of the BMG160_DELAY_FUNCTION
BMG160_DELAY_FUNC
BMG160_RETURN_FUNCTION_TYPE
Referenced by bmg160_init, bmg160_get_data_X, bmg160_get_data_Y, bmg160_get_data_Z, bmg160_get_data_XYZ, bmg160_get_data_XYZI, bmg160_get_temp, bmg160_read_register, bmg160_burst_read, bmg160_write_register, bmg160_get_intr_stat_reg_zero, bmg160_get_intr_stat_reg_one, bmg160_get_intr_stat_reg_two, bmg160_get_intr_stat_reg_three, bmg160_get_range_reg, bmg160_set_range_reg, bmg160_get_bw, bmg160_set_bw, bmg160_get_pmu_ext_tri_select, bmg160_set_pmu_ext_tri_select, bmg160_get_high_bw, bmg160_set_high_bw, bmg160_get_shadow_dis, bmg160_set_shadow_dis, bmg160_set_soft_rst, bmg160_get_data_enable, bmg160_set_data_enable, bmg160_get_fifo_enable, bmg160_set_fifo_enable, bmg160_get_auto_offset_enable, bmg160_set_auto_offset_enable, bmg160_get_intr_output_type, bmg160_set_intr_output_type, bmg160_get_intr_level, bmg160_set_intr_level, bmg160_get_intr1_highrate, bmg160_set_intr1_highrate, bmg160_get_intr1_any_motion, bmg160_set_intr1_any_motion, bmg160_get_intr_data, bmg160_set_intr_data, bmg160_get_intr2_offset, bmg160_set_intr2_offset, bmg160_get_intr_offset, bmg160_set_intr1_offset, bmg160_get_intr2_fifo, bmg160_get_intr1_fifo, bmg160_set_intr_fifo, bmg160_get_intr2_highrate, bmg160_set_intr2_highrate, bmg160_get_intr2_any_motion, bmg160_set_intr2_any_motion, bmg160_get_offset_unfilt, bmg160_set_offset_unfilt, bmg160_get_unfilt_data, bmg160_set_unfilt_data, bmg160_get_any_motion_thres, bmg160_set_any_motion_thres, bmg160_get_awake_durn, bmg160_set_awake_durn, bmg160_get_any_motion_durn_sample, bmg160_set_any_motion_durn_sample, bmg160_get_any_motion_enable_axis, bmg160_set_any_motion_enable_axis, bmg160_get_fifo_wm_enable, bmg160_set_fifo_wm_enable, bmg160_set_rst_intr, bmg160_set_offset_rst, bmg160_get_latch_stat, bmg160_set_latch_stat, bmg160_get_latch_intr, bmg160_set_latch_intr, bmg160_get_highrate_hyst, bmg160_set_highrate_hyst, bmg160_get_highrate_thres, bmg160_set_highrate_thres, bmg160_get_highrate_enable_axis, bmg160_set_highrate_enable_axis, bmg160_get_highrate_durn_axis, bmg160_set_highrate_durn_axis, bmg160_get_slow_offset_thres, bmg160_set_slow_offset_thres, bmg160_get_slow_offset_durn, bmg160_set_slow_offset_durn, bmg160_get_slow_offset_enable_axis, bmg160_set_slow_offset_enable_axis, bmg160_get_offset_word_length, bmg160_set_offset_word_length, bmg160_enable_fast_offset, bmg160_get_fast_offset_enable_axis, bmg160_set_fast_offset_enable_axis, bmg160_get_nvm_remain, bmg160_set_nvm_load, bmg160_get_nvm_rdy, bmg160_set_nvm_prog_trig, bmg160_get_nvm_prog_mode, bmg160_set_nvm_prog_mode, bmg160_get_i2c_wdt, bmg160_set_i2c_wdt, bmg160_get_spi3, bmg160_set_spi3, bmg160_get_fifo_tag, bmg160_set_fifo_tag, bmg160_get_fifo_wm_level, bmg160_set_fifo_wm_level, bmg160_get_offset, bmg160_set_offset, bmg160_get_gp, bmg160_set_gp, bmg160_get_FIFO_data_reg, bmg160_get_fifo_stat_reg, bmg160_get_fifo_frame_count, bmg160_get_fifo_overrun, bmg160_get_fifo_mode, bmg160_set_fifo_mode, bmg160_get_fifo_data_select, bmg160_set_fifo_data_select, bmg160_get_power_mode, bmg160_set_power_mode, bmg160_selftest, bmg160_get_auto_sleep_durn, bmg160_set_auto_sleep_durn, bmg160_get_sleep_durn, bmg160_set_sleep_durn, bmg160LibErrorMapping, Gyroscope_setBandwidth, Gyroscope_setRange, Gyroscope_getRange, Gyroscope_getBandwidth, Gyroscope_setMode, Gyroscope_getMode, Gyroscope_readXyzValue, Gyroscope_readXyzDegreeValue, Gyroscope_setSleepDuration, Gyroscope_setAutoSleepDuration, Bmg160Utils_initialize.
BMG160_I2C_ADDR1
BMG160_I2C_ADDR2
BMG160_CHIP_ID_ADDR
Address of Chip ID Register
Referenced by bmg160_init.
BMG160_RATE_X_LSB_ADDR
Address of X axis Rate LSB Register
BMG160_RATE_X_MSB_ADDR
Address of X axis Rate MSB Register
BMG160_RATE_Y_LSB_ADDR
Address of Y axis Rate LSB Register
BMG160_RATE_Y_MSB_ADDR
Address of Y axis Rate MSB Register
BMG160_RATE_Z_LSB_ADDR
Address of Z axis Rate LSB Register
BMG160_RATE_Z_MSB_ADDR
Address of Z axis Rate MSB Register
BMG160_TEMP_ADDR
Address of Temperature Data LSB Register
Referenced by bmg160_get_temp.
BMG160_INTR_STAT0_ADDR
Address of Interrupt status Register
BMG160_INTR_STAT1_ADDR
Address of Interrupt status Register
BMG160_INTR_STAT2_ADDR
Address of Interrupt status Register
BMG160_INTR_STAT3_ADDR
Address of Interrupt status Register
BMG160_FIFO_STAT_ADDR
Address of FIFO status Register
Referenced by bmg160_get_fifo_stat_reg.
BMG160_RANGE_ADDR
Address of Range address Register
BMG160_BW_ADDR
Address of Bandwidth Register
Referenced by bmg160_get_bw, bmg160_set_bw.
BMG160_MODE_LPM1_ADDR
Address of Mode LPM1 Register
Referenced by bmg160_get_power_mode, bmg160_set_power_mode.
BMG160_MODE_LPM2_ADDR
Address of Mode LPM2 Register
Referenced by bmg160_get_power_mode, bmg160_set_power_mode.
BMG160_HIGH_BW_ADDR
Address of Rate HIGH_BW Register
BMG160_BGW_SOFT_RST_ADDR
Address of BGW Softreset Register
Referenced by bmg160_set_soft_rst.
BMG160_INTR_ENABLE0_ADDR
Address of Interrupt Enable
BMG160_INTR_ENABLE1_ADDR
Address of Interrupt Enable
BMG160_INTR_MAP_ZERO_ADDR
Address of Interrupt MAP
BMG160_INTR_MAP_ONE_ADDR
Address of Interrupt MAP
BMG160_INTR_MAP_TWO_ADDR
Address of Interrupt MAP
BMG160_INTR_ZERO_ADDR
Address of Interrupt register
BMG160_INTR_ONE_ADDR
Address of Interrupt register
BMG160_INTR_TWO_ADDR
Address of Interrupt register
BMG160_INTR_4_ADDR
Address of Interrupt register
BMG160_RST_LATCH_ADDR
Address of Reset Latch Register
BMG160_HIGHRATE_THRES_X_ADDR
Address of High Th x Address register
Referenced by bmg160_set_highrate_durn_axis.
BMG160_HIGHRATE_DURN_X_ADDR
Address of High Dur x Address register
Referenced by bmg160_get_highrate_durn_axis.
BMG160_HIGHRATE_THRES_Y_ADDR
Address of High Th y Address register
Referenced by bmg160_get_highrate_durn_axis, bmg160_set_highrate_durn_axis.
BMG160_HIGHRATE_DURN_Y_ADDR
Address of High Dur y Address register
BMG160_HIGHRATE_THRES_Z_ADDR
Address of High Th z Address register
Referenced by bmg160_get_highrate_durn_axis, bmg160_set_highrate_durn_axis.
BMG160_HIGHRATE_DURN_Z_ADDR
Address of High Dur z Address register
BMG160_SOC_ADDR
Address of SOC register
BMG160_A_FOC_ADDR
Address of A_FOC Register
BMG160_TRIM_NVM_CTRL_ADDR
Address of Trim NVM control register
BMG160_BGW_SPI3_WDT_ADDR
Address of BGW SPI3,WDT Register
BMG160_OFFSET_OFC1_ADDR
Address of OFC1 Register
BMG160_OFC2_ADDR
Address of OFC2 Register
Referenced by bmg160_get_offset, bmg160_set_offset.
BMG160_OFC3_ADDR
Address of OFC3 Register
Referenced by bmg160_get_offset, bmg160_set_offset.
BMG160_OFC4_ADDR
Address of OFC4 Register
Referenced by bmg160_get_offset, bmg160_set_offset.
BMG160_TRIM_GP0_ADDR
Address of Trim GP0 Register
BMG160_TRIM_GP1_ADDR
Address of Trim GP1 Register
Referenced by bmg160_get_gp, bmg160_set_gp.
BMG160_SELFTEST_ADDR
Address of BGW Self test Register
Referenced by bmg160_selftest.
BMG160_FIFO_CGF1_ADDR
Address of FIFO CGF0 Register
BMG160_FIFO_CGF0_ADDR
Address of FIFO CGF1 Register
BMG160_FIFO_DATA_ADDR
Address of FIFO Data Register
Referenced by bmg160_get_FIFO_data_reg.
BMG160_RATE_X_LSB_BIT__POS
Last (8) bits of RateX LSB Registers
BMG160_RATE_X_LSB_BIT__LEN
BMG160_RATE_X_LSB_BIT__MSK
BMG160_RATE_X_LSB_BIT__REG
Referenced by bmg160_get_data_X, bmg160_get_data_XYZ, bmg160_get_data_XYZI.
BMG160_RATE_Y_LSB_BIT__POS
< Last (8) bits of RateY LSB Registers
BMG160_RATE_Y_LSB_BIT__LEN
BMG160_RATE_Y_LSB_BIT__MSK
BMG160_RATE_Y_LSB_BIT__REG
Referenced by bmg160_get_data_Y.
BMG160_RATE_Z_LSB_BIT__POS
< Last (8) bits of RateZ LSB Registers
BMG160_RATE_Z_LSB_BIT__LEN
BMG160_RATE_Z_LSB_BIT__MSK
BMG160_RATE_Z_LSB_BIT__REG
Referenced by bmg160_get_data_Z.
BMG160_INTR_STAT0_ANY_MOTION_INTR__POS
< 2th bit of Interrupt status register
BMG160_INTR_STAT0_ANY_MOTION_INTR__LEN
BMG160_INTR_STAT0_ANY_MOTION_INTR__MSK
BMG160_INTR_STAT0_ANY_MOTION_INTR__REG
1st bit of Interrupt status register
BMG160_INTR_STAT0_HIGHRATE_INTR__POS
BMG160_INTR_STAT0_HIGHRATE_INTR__LEN
BMG160_INTR_STAT0_HIGHRATE_INTR__MSK
BMG160_INTR_STAT0_HIGHRATE_INTR__REG
1st and 2nd bit of Interrupt status register
BMG160_INTR_STAT_ZERO__POS
BMG160_INTR_STAT_ZERO__LEN
BMG160_INTR_STAT_ZERO__MSK
BMG160_INTR_STAT_ZERO__REG
Referenced by bmg160_get_intr_stat_reg_zero.
BMG160_INTR_STAT1_DATA_INTR__POS
< 7th bit of Interrupt status register
BMG160_INTR_STAT1_DATA_INTR__LEN
BMG160_INTR_STAT1_DATA_INTR__MSK
BMG160_INTR_STAT1_DATA_INTR__REG
BMG160_INTR_STAT1_AUTO_OFFSET_INTR__POS
< 6th bit of Interrupt status register
BMG160_INTR_STAT1_AUTO_OFFSET_INTR__LEN
BMG160_INTR_STAT1_AUTO_OFFSET_INTR__MSK
BMG160_INTR_STAT1_AUTO_OFFSET_INTR__REG
5th bit of Interrupt status register
BMG160_INTR_STAT1_FAST_OFFSET_INTR__POS
BMG160_INTR_STAT1_FAST_OFFSET_INTR__LEN
BMG160_INTR_STAT1_FAST_OFFSET_INTR__MSK
BMG160_INTR_STAT1_FAST_OFFSET_INTR__REG
BMG160_INTR_STAT1_FIFO_INTR__POS
< 4th bit of Interrupt status register
BMG160_INTR_STAT1_FIFO_INTR__LEN
BMG160_INTR_STAT1_FIFO_INTR__MSK
BMG160_INTR_STAT1_FIFO_INTR__REG
MSB (4) bits of Interrupt status1 register
BMG160_INTR_STAT_ONE__POS
BMG160_INTR_STAT_ONE__LEN
BMG160_INTR_STAT_ONE__MSK
BMG160_INTR_STAT_ONE__REG
Referenced by bmg160_get_intr_stat_reg_one.
BMG160_INTR_STAT2_ANY_MOTION_SIGN_INTR__POS
< 3th bit of Interrupt status register
BMG160_INTR_STAT2_ANY_MOTION_SIGN_INTR__LEN
BMG160_INTR_STAT2_ANY_MOTION_SIGN_INTR__MSK
BMG160_INTR_STAT2_ANY_MOTION_SIGN_INTR__REG
2th bit of Interrupt status register
BMG160_INTR_STAT2_ANY_MOTION_FIRSTZ_INTR__POS
BMG160_INTR_STAT2_ANY_MOTION_FIRSTZ_INTR__LEN
BMG160_INTR_STAT2_ANY_MOTION_FIRSTZ_INTR__MSK
BMG160_INTR_STAT2_ANY_MOTION_FIRSTZ_INTR__REG
1st bit of Interrupt status register
BMG160_INTR_STAT2_ANY_MOTION_FIRSTY_INTR__POS
BMG160_INTR_STAT2_ANY_MOTION_FIRSTY_INTR__LEN
BMG160_INTR_STAT2_ANY_MOTION_FIRSTY_INTR__MSK
BMG160_INTR_STAT2_ANY_MOTION_FIRSTY_INTR__REG
0th bit of Interrupt status register
BMG160_INTR_STAT2_ANY_MOTION_FIRSTX_INTR__POS
BMG160_INTR_STAT2_ANY_MOTION_FIRSTX_INTR__LEN
BMG160_INTR_STAT2_ANY_MOTION_FIRSTX_INTR__MSK
BMG160_INTR_STAT2_ANY_MOTION_FIRSTX_INTR__REG
(4) bits of Interrupt status register
BMG160_INTR_STAT_TWO__POS
BMG160_INTR_STAT_TWO__LEN
BMG160_INTR_STAT_TWO__MSK
BMG160_INTR_STAT_TWO__REG
Referenced by bmg160_get_intr_stat_reg_two.
BMG160_INTR_STAT3_HIGHRATE_SIGN_INTR__POS
< 3th bit of Interrupt status register
BMG160_INTR_STAT3_HIGHRATE_SIGN_INTR__LEN
BMG160_INTR_STAT3_HIGHRATE_SIGN_INTR__MSK
BMG160_INTR_STAT3_HIGHRATE_SIGN_INTR__REG
2th bit of Interrupt status register
BMG160_INTR_STAT3_HIGHRATE_FIRSTZ_INTR__POS
BMG160_INTR_STAT3_HIGHRATE_FIRSTZ_INTR__LEN
BMG160_INTR_STAT3_HIGHRATE_FIRSTZ_INTR__MSK
BMG160_INTR_STAT3_HIGHRATE_FIRSTZ_INTR__REG
1st bit of Interrupt status register
BMG160_INTR_STAT3_HIGHRATE_FIRSTY_INTR__POS
BMG160_INTR_STAT3_HIGHRATE_FIRSTY_INTR__LEN
BMG160_INTR_STAT3_HIGHRATE_FIRSTY_INTR__MSK
BMG160_INTR_STAT3_HIGHRATE_FIRSTY_INTR__REG
0th bit of Interrupt status register
BMG160_INTR_STAT3_HIGHRATE_FIRSTX_INTR__POS
BMG160_INTR_STAT3_HIGHRATE_FIRSTX_INTR__LEN
BMG160_INTR_STAT3_HIGHRATE_FIRSTX_INTR__MSK
BMG160_INTR_STAT3_HIGHRATE_FIRSTX_INTR__REG
LSB (4) bits of Interrupt status register
BMG160_INTR_STAT_THREE__POS
BMG160_INTR_STAT_THREE__LEN
BMG160_INTR_STAT_THREE__MSK
BMG160_INTR_STAT_THREE__REG
Referenced by bmg160_get_intr_stat_reg_three.
BMG160_FIFO_STAT_OVERRUN__POS
< 7th bit of FIFO status Register
BMG160_FIFO_STAT_OVERRUN__LEN
BMG160_FIFO_STAT_OVERRUN__MSK
BMG160_FIFO_STAT_OVERRUN__REG
Referenced by bmg160_get_fifo_overrun.
BMG160_FIFO_STAT_FRAME_COUNTER__POS
< First (7) bits of FIFO status Register
BMG160_FIFO_STAT_FRAME_COUNTER__LEN
BMG160_FIFO_STAT_FRAME_COUNTER__MSK
BMG160_FIFO_STAT_FRAME_COUNTER__REG
Referenced by bmg160_get_fifo_frame_count.
BMG160_RANGE_ADDR_RANGE__POS
< First (3) bits of range Registers
BMG160_RANGE_ADDR_RANGE__LEN
BMG160_RANGE_ADDR_RANGE__MSK
BMG160_RANGE_ADDR_RANGE__REG
Referenced by bmg160_get_range_reg, bmg160_set_range_reg.
BMG160_BW_ADDR__POS
< First (3) bits of Bandwidth Registers
BMG160_BW_ADDR__LEN
BMG160_BW_ADDR__MSK
BMG160_BW_ADDR__REG
5th and 7th bit of LPM1 Register
Referenced by bmg160_get_bw, bmg160_set_bw.
BMG160_MODE_LPM1__POS
BMG160_MODE_LPM1__LEN
BMG160_MODE_LPM1__MSK
BMG160_MODE_LPM1__REG
BMG160_MODELPM1_ADDR_SLEEP_DURN__POS
< 1st to 3rd bit of LPM1 Register
BMG160_MODELPM1_ADDR_SLEEP_DURN__LEN
BMG160_MODELPM1_ADDR_SLEEP_DURN__MSK
BMG160_MODELPM1_ADDR_SLEEP_DURN__REG
7th bit of Mode LPM2 Register
Referenced by bmg160_get_sleep_durn, bmg160_set_sleep_durn.
BMG160_MODE_LPM2_ADDR_FAST_POWERUP__POS
BMG160_MODE_LPM2_ADDR_FAST_POWERUP__LEN
BMG160_MODE_LPM2_ADDR_FAST_POWERUP__MSK
BMG160_MODE_LPM2_ADDR_FAST_POWERUP__REG
6th bit of Mode LPM2 Register
BMG160_MODE_LPM2_ADDR_ADV_POWERSAVING__POS
BMG160_MODE_LPM2_ADDR_ADV_POWERSAVING__LEN
BMG160_MODE_LPM2_ADDR_ADV_POWERSAVING__MSK
BMG160_MODE_LPM2_ADDR_ADV_POWERSAVING__REG
4th & 5th bit of Mode LPM2 Register
BMG160_MODE_LPM2_ADDR_EXT_TRI_SELECT__POS
BMG160_MODE_LPM2_ADDR_EXT_TRI_SELECT__LEN
BMG160_MODE_LPM2_ADDR_EXT_TRI_SELECT__MSK
BMG160_MODE_LPM2_ADDR_EXT_TRI_SELECT__REG
Referenced by bmg160_get_pmu_ext_tri_select, bmg160_set_pmu_ext_tri_select.
BMG160_MODE_LPM2_ADDR_AUTO_SLEEP_DURN__POS
< 0th to 2nd bit of LPM2 Register
BMG160_MODE_LPM2_ADDR_AUTO_SLEEP_DURN__LEN
BMG160_MODE_LPM2_ADDR_AUTO_SLEEP_DURN__MSK
BMG160_MODE_LPM2_ADDR_AUTO_SLEEP_DURN__REG
Referenced by bmg160_get_auto_sleep_durn, bmg160_set_auto_sleep_durn.
BMG160_HIGH_BW__POS
< 7th bit of HIGH_BW Register
BMG160_HIGH_BW__LEN
BMG160_HIGH_BW__MSK
BMG160_HIGH_BW__REG
6th bit of HIGH_BW Register
Referenced by bmg160_get_high_bw, bmg160_set_high_bw.
BMG160_SHADOW_DIS__POS
BMG160_SHADOW_DIS__LEN
BMG160_SHADOW_DIS__MSK
BMG160_SHADOW_DIS__REG
Referenced by bmg160_get_shadow_dis, bmg160_set_shadow_dis.
BMG160_INTR_ENABLE0_DATA__POS
< 7th bit of Interrupt Enable Registers
BMG160_INTR_ENABLE0_DATA__LEN
BMG160_INTR_ENABLE0_DATA__MSK
BMG160_INTR_ENABLE0_DATA__REG
Referenced by bmg160_get_data_enable, bmg160_set_data_enable.
BMG160_INTR_ENABLE0_FIFO__POS
< 6th bit of Interrupt Enable Registers
BMG160_INTR_ENABLE0_FIFO__LEN
BMG160_INTR_ENABLE0_FIFO__MSK
BMG160_INTR_ENABLE0_FIFO__REG
Referenced by bmg160_get_fifo_enable, bmg160_set_fifo_enable.
BMG160_INTR_ENABLE0_AUTO_OFFSET__POS
< 2nd bit of Interrupt Enable Registers
BMG160_INTR_ENABLE0_AUTO_OFFSET__LEN
BMG160_INTR_ENABLE0_AUTO_OFFSET__MSK
BMG160_INTR_ENABLE0_AUTO_OFFSET__REG
Referenced by bmg160_get_auto_offset_enable, bmg160_set_auto_offset_enable.
BMG160_INTR_ENABLE1_IT2_OUTPUT_TYPE__POS
< 3rd bit of Interrupt Enable Registers
BMG160_INTR_ENABLE1_IT2_OUTPUT_TYPE__LEN
BMG160_INTR_ENABLE1_IT2_OUTPUT_TYPE__MSK
BMG160_INTR_ENABLE1_IT2_OUTPUT_TYPE__REG
Referenced by bmg160_get_intr_output_type, bmg160_set_intr_output_type.
BMG160_INTR_ENABLE1_IT1_OUTPUT_TYPE__POS
< 1st bit of Interrupt Enable Registers
BMG160_INTR_ENABLE1_IT1_OUTPUT_TYPE__LEN
BMG160_INTR_ENABLE1_IT1_OUTPUT_TYPE__MSK
BMG160_INTR_ENABLE1_IT1_OUTPUT_TYPE__REG
Referenced by bmg160_get_intr_output_type, bmg160_set_intr_output_type.
BMG160_INTR_ENABLE1_IT2_LEVEL__POS
< 2nd bit of Interrupt Enable Registers
BMG160_INTR_ENABLE1_IT2_LEVEL__LEN
BMG160_INTR_ENABLE1_IT2_LEVEL__MSK
BMG160_INTR_ENABLE1_IT2_LEVEL__REG
Referenced by bmg160_get_intr_level, bmg160_set_intr_level.
BMG160_INTR_ENABLE1_IT1_LEVEL__POS
< 0th bit of Interrupt Enable Registers
BMG160_INTR_ENABLE1_IT1_LEVEL__LEN
BMG160_INTR_ENABLE1_IT1_LEVEL__MSK
BMG160_INTR_ENABLE1_IT1_LEVEL__REG
Referenced by bmg160_get_intr_level, bmg160_set_intr_level.
BMG160_INTR_MAP_ZERO_INTR1_HIGHRATE__POS
< 3rd bit of Interrupt MAP (0) Registers
BMG160_INTR_MAP_ZERO_INTR1_HIGHRATE__LEN
BMG160_INTR_MAP_ZERO_INTR1_HIGHRATE__MSK
BMG160_INTR_MAP_ZERO_INTR1_HIGHRATE__REG
Referenced by bmg160_get_intr1_highrate, bmg160_set_intr1_highrate.
BMG160_INTR_MAP_TWO_INTR2_HIGHRATE__POS
< 3rd bit of Interrupt Map Registers
BMG160_INTR_MAP_TWO_INTR2_HIGHRATE__LEN
BMG160_INTR_MAP_TWO_INTR2_HIGHRATE__MSK
BMG160_INTR_MAP_TWO_INTR2_HIGHRATE__REG
Referenced by bmg160_get_intr2_highrate, bmg160_set_intr2_highrate.
BMG160_INTR_MAP_ZERO_INTR1_ANY_MOTION__POS
< 1st bit of Interrupt MAP Registers
BMG160_INTR_MAP_ZERO_INTR1_ANY_MOTION__LEN
BMG160_INTR_MAP_ZERO_INTR1_ANY_MOTION__MSK
BMG160_INTR_MAP_ZERO_INTR1_ANY_MOTION__REG
7th bit of MAP_1Registers
Referenced by bmg160_get_intr1_any_motion, bmg160_set_intr1_any_motion.
BMG160_MAP_ONE_INTR2_DATA__POS
BMG160_MAP_ONE_INTR2_DATA__LEN
BMG160_MAP_ONE_INTR2_DATA__MSK
BMG160_MAP_ONE_INTR2_DATA__REG
Referenced by bmg160_get_intr_data, bmg160_set_intr_data.
BMG160_MAP_ONE_INTR2_FAST_OFFSET__POS
< 6th bit of MAP_1Registers
BMG160_MAP_ONE_INTR2_FAST_OFFSET__LEN
BMG160_MAP_ONE_INTR2_FAST_OFFSET__MSK
BMG160_MAP_ONE_INTR2_FAST_OFFSET__REG
Referenced by bmg160_get_intr2_offset, bmg160_set_intr2_offset.
BMG160_MAP_ONE_INTR1_FAST_OFFSET__POS
< 1st bit of MAP_1Registers
BMG160_MAP_ONE_INTR1_FAST_OFFSET__LEN
BMG160_MAP_ONE_INTR1_FAST_OFFSET__MSK
BMG160_MAP_ONE_INTR1_FAST_OFFSET__REG
Referenced by bmg160_get_intr_offset, bmg160_set_intr1_offset.
BMG160_MAP_ONE_INTR2_FIFO__POS
< 5th bit of MAP_1Registers
BMG160_MAP_ONE_INTR2_FIFO__LEN
BMG160_MAP_ONE_INTR2_FIFO__MSK
BMG160_MAP_ONE_INTR2_FIFO__REG
Referenced by bmg160_get_intr2_fifo, bmg160_set_intr_fifo.
BMG160_MAP_ONE_INTR1_FIFO__POS
< 2nd bit of MAP_1Registers
BMG160_MAP_ONE_INTR1_FIFO__LEN
BMG160_MAP_ONE_INTR1_FIFO__MSK
BMG160_MAP_ONE_INTR1_FIFO__REG
Referenced by bmg160_get_intr1_fifo, bmg160_set_intr_fifo.
BMG160_MAP_ONE_INTR2_AUTO_OFFSET__POS
< 4th bit of MAP_1Registers
BMG160_MAP_ONE_INTR2_AUTO_OFFSET__LEN
BMG160_MAP_ONE_INTR2_AUTO_OFFSET__MSK
BMG160_MAP_ONE_INTR2_AUTO_OFFSET__REG
3rd bit of MAP_1Registers
Referenced by bmg160_get_intr2_offset, bmg160_set_intr2_offset.
BMG160_MAP_ONE_INTR1_AUTO_OFFSET__POS
BMG160_MAP_ONE_INTR1_AUTO_OFFSET__LEN
BMG160_MAP_ONE_INTR1_AUTO_OFFSET__MSK
BMG160_MAP_ONE_INTR1_AUTO_OFFSET__REG
Referenced by bmg160_get_intr_offset, bmg160_set_intr1_offset.
BMG160_MAP_ONE_INTR1_DATA__POS
< 0th bit of MAP_1Registers
BMG160_MAP_ONE_INTR1_DATA__LEN
BMG160_MAP_ONE_INTR1_DATA__MSK
BMG160_MAP_ONE_INTR1_DATA__REG
Referenced by bmg160_get_intr_data, bmg160_set_intr_data.
BMG160_INTR_MAP_TWO_INTR2_ANY_MOTION__POS
< 1st bit of Interrupt Map Registers
BMG160_INTR_MAP_TWO_INTR2_ANY_MOTION__LEN
BMG160_INTR_MAP_TWO_INTR2_ANY_MOTION__MSK
BMG160_INTR_MAP_TWO_INTR2_ANY_MOTION__REG
Referenced by bmg160_get_intr2_any_motion, bmg160_set_intr2_any_motion.
BMG160_INTR_ZERO_ADDR_SLOW_OFFSET_UNFILT__POS
< 5th bit of Interrupt Registers
BMG160_INTR_ZERO_ADDR_SLOW_OFFSET_UNFILT__LEN
BMG160_INTR_ZERO_ADDR_SLOW_OFFSET_UNFILT__MSK
BMG160_INTR_ZERO_ADDR_SLOW_OFFSET_UNFILT__REG
Referenced by bmg160_get_offset_unfilt, bmg160_set_offset_unfilt.
BMG160_INTR_ZERO_ADDR_HIGHRATE_UNFILT_DATA__POS
< 3rd bit of Interrupt Registers
BMG160_INTR_ZERO_ADDR_HIGHRATE_UNFILT_DATA__LEN
BMG160_INTR_ZERO_ADDR_HIGHRATE_UNFILT_DATA__MSK
BMG160_INTR_ZERO_ADDR_HIGHRATE_UNFILT_DATA__REG
Referenced by bmg160_get_unfilt_data, bmg160_set_unfilt_data.
BMG160_INTR_ZERO_ADDR_ANY_MOTION_UNFILT_DATA__POS
< 1st bit of Interrupt (0) Registers
BMG160_INTR_ZERO_ADDR_ANY_MOTION_UNFILT_DATA__LEN
BMG160_INTR_ZERO_ADDR_ANY_MOTION_UNFILT_DATA__MSK
BMG160_INTR_ZERO_ADDR_ANY_MOTION_UNFILT_DATA__REG
Referenced by bmg160_get_unfilt_data, bmg160_set_unfilt_data.
BMG160_INTR_ONE_ADDR_FAST_OFFSET_UNFILT__POS
< 7th bit of INT_1 Registers
BMG160_INTR_ONE_ADDR_FAST_OFFSET_UNFILT__LEN
BMG160_INTR_ONE_ADDR_FAST_OFFSET_UNFILT__MSK
BMG160_INTR_ONE_ADDR_FAST_OFFSET_UNFILT__REG
Referenced by bmg160_get_offset_unfilt, bmg160_set_offset_unfilt.
BMG160_INTR_ONE_ADDR_ANY_MOTION_THRES__POS
< First (7) bits of INT_1 Registers
BMG160_INTR_ONE_ADDR_ANY_MOTION_THRES__LEN
BMG160_INTR_ONE_ADDR_ANY_MOTION_THRES__MSK
BMG160_INTR_ONE_ADDR_ANY_MOTION_THRES__REG
Referenced by bmg160_get_any_motion_thres, bmg160_set_any_motion_thres.
BMG160_INTR_TWO_ADDR_AWAKE_DURN__POS
< Last (2) bits of INT 2Registers
BMG160_INTR_TWO_ADDR_AWAKE_DURN__LEN
BMG160_INTR_TWO_ADDR_AWAKE_DURN__MSK
BMG160_INTR_TWO_ADDR_AWAKE_DURN__REG
Referenced by bmg160_get_awake_durn, bmg160_set_awake_durn.
BMG160_INTR_TWO_ADDR_ANY_MOTION_DURN_SAMPLE__POS
< 4th & 5th bit of INT 2Registers
BMG160_INTR_TWO_ADDR_ANY_MOTION_DURN_SAMPLE__LEN
BMG160_INTR_TWO_ADDR_ANY_MOTION_DURN_SAMPLE__MSK
BMG160_INTR_TWO_ADDR_ANY_MOTION_DURN_SAMPLE__REG
Referenced by bmg160_get_any_motion_durn_sample, bmg160_set_any_motion_durn_sample.
BMG160_INTR_TWO_ADDR_ANY_MOTION_ENABLE_Z__POS
< 2nd bit of INT 2Registers
BMG160_INTR_TWO_ADDR_ANY_MOTION_ENABLE_Z__LEN
BMG160_INTR_TWO_ADDR_ANY_MOTION_ENABLE_Z__MSK
BMG160_INTR_TWO_ADDR_ANY_MOTION_ENABLE_Z__REG
1st bit of INT 2Registers
Referenced by bmg160_get_any_motion_enable_axis, bmg160_set_any_motion_enable_axis.
BMG160_INTR_TWO_ADDR_ANY_MOTION_ENABLE_Y__POS
BMG160_INTR_TWO_ADDR_ANY_MOTION_ENABLE_Y__LEN
BMG160_INTR_TWO_ADDR_ANY_MOTION_ENABLE_Y__MSK
BMG160_INTR_TWO_ADDR_ANY_MOTION_ENABLE_Y__REG
0th bit of INT 2Registers
Referenced by bmg160_get_any_motion_enable_axis, bmg160_set_any_motion_enable_axis.
BMG160_INTR_TWO_ADDR_ANY_MOTION_ENABLE_X__POS
BMG160_INTR_TWO_ADDR_ANY_MOTION_ENABLE_X__LEN
BMG160_INTR_TWO_ADDR_ANY_MOTION_ENABLE_X__MSK
BMG160_INTR_TWO_ADDR_ANY_MOTION_ENABLE_X__REG
Referenced by bmg160_get_any_motion_enable_axis, bmg160_set_any_motion_enable_axis.
BMG160_INTR_4_FIFO_WM_ENABLE__POS
< Last bit of INT Registers
BMG160_INTR_4_FIFO_WM_ENABLE__LEN
BMG160_INTR_4_FIFO_WM_ENABLE__MSK
BMG160_INTR_4_FIFO_WM_ENABLE__REG
Referenced by bmg160_get_fifo_wm_enable, bmg160_set_fifo_wm_enable.
BMG160_RST_LATCH_ADDR_RST_INTR__POS
< Last bit of Reset Latch Registers
BMG160_RST_LATCH_ADDR_RST_INTR__LEN
BMG160_RST_LATCH_ADDR_RST_INTR__MSK
BMG160_RST_LATCH_ADDR_RST_INTR__REG
6th bit of Reset Latch Registers
Referenced by bmg160_set_rst_intr.
BMG160_RST_LATCH_ADDR_OFFSET_RST__POS
BMG160_RST_LATCH_ADDR_OFFSET_RST__LEN
BMG160_RST_LATCH_ADDR_OFFSET_RST__MSK
BMG160_RST_LATCH_ADDR_OFFSET_RST__REG
4th bit of Reset Latch Registers
Referenced by bmg160_set_offset_rst.
BMG160_RST_LATCH_ADDR_LATCH_STAT__POS
BMG160_RST_LATCH_ADDR_LATCH_STAT__LEN
BMG160_RST_LATCH_ADDR_LATCH_STAT__MSK
BMG160_RST_LATCH_ADDR_LATCH_STAT__REG
First (4) bits of Reset Latch Registers
Referenced by bmg160_get_latch_stat, bmg160_set_latch_stat.
BMG160_RST_LATCH_ADDR_LATCH_INTR__POS
BMG160_RST_LATCH_ADDR_LATCH_INTR__LEN
BMG160_RST_LATCH_ADDR_LATCH_INTR__MSK
BMG160_RST_LATCH_ADDR_LATCH_INTR__REG
Referenced by bmg160_get_latch_intr, bmg160_set_latch_intr.
BMG160_HIGHRATE_HYST_X__POS
< Last (2) bits of HIGHRATE_THRES_X Registers
BMG160_HIGHRATE_HYST_X__LEN
BMG160_HIGHRATE_HYST_X__MSK
BMG160_HIGHRATE_HYST_X__REG
(5) bits of HIGHRATE_THRES_X Registers
Referenced by bmg160_get_highrate_hyst, bmg160_set_highrate_hyst.
BMG160_HIGHRATE_THRES_X__POS
BMG160_HIGHRATE_THRES_X__LEN
BMG160_HIGHRATE_THRES_X__MSK
BMG160_HIGHRATE_THRES_X__REG
0th bit of HIGHRATE_THRES_X Registers
Referenced by bmg160_get_highrate_thres, bmg160_set_highrate_thres.
BMG160_HIGHRATE_ENABLE_X__POS
BMG160_HIGHRATE_ENABLE_X__LEN
BMG160_HIGHRATE_ENABLE_X__MSK
BMG160_HIGHRATE_ENABLE_X__REG
Last (2) bits of HIGHRATE_THRES_Y Registers
Referenced by bmg160_get_highrate_enable_axis, bmg160_set_highrate_enable_axis.
BMG160_HIGHRATE_HYST_Y__POS
BMG160_HIGHRATE_HYST_Y__LEN
BMG160_HIGHRATE_HYST_Y__MSK
BMG160_HIGHRATE_HYST_Y__REG
(5) bits of HIGHRATE_THRES_Y Registers
Referenced by bmg160_get_highrate_hyst, bmg160_set_highrate_hyst.
BMG160_HIGHRATE_THRES_Y__POS
BMG160_HIGHRATE_THRES_Y__LEN
BMG160_HIGHRATE_THRES_Y__MSK
BMG160_HIGHRATE_THRES_Y__REG
0th bit of HIGHRATE_THRES_Y Registers
Referenced by bmg160_get_highrate_thres, bmg160_set_highrate_thres.
BMG160_HIGHRATE_ENABLE_Y__POS
BMG160_HIGHRATE_ENABLE_Y__LEN
BMG160_HIGHRATE_ENABLE_Y__MSK
BMG160_HIGHRATE_ENABLE_Y__REG
Last (2) bits of HIGHRATE_THRES_Z Registers
Referenced by bmg160_get_highrate_enable_axis, bmg160_set_highrate_enable_axis.
BMG160_HIGHRATE_HYST_Z__POS
BMG160_HIGHRATE_HYST_Z__LEN
BMG160_HIGHRATE_HYST_Z__MSK
BMG160_HIGHRATE_HYST_Z__REG
(5) bits of HIGHRATE_THRES_Z Registers
Referenced by bmg160_get_highrate_hyst, bmg160_set_highrate_hyst.
BMG160_HIGHRATE_THRES_Z__POS
BMG160_HIGHRATE_THRES_Z__LEN
BMG160_HIGHRATE_THRES_Z__MSK
BMG160_HIGHRATE_THRES_Z__REG
0th bit of HIGHRATE_THRES_Z Registers
Referenced by bmg160_get_highrate_thres, bmg160_set_highrate_thres.
BMG160_HIGHRATE_ENABLE_Z__POS
BMG160_HIGHRATE_ENABLE_Z__LEN
BMG160_HIGHRATE_ENABLE_Z__MSK
BMG160_HIGHRATE_ENABLE_Z__REG
Referenced by bmg160_get_highrate_enable_axis, bmg160_set_highrate_enable_axis.
BMG160_SLOW_OFFSET_THRES__POS
< Last 3 bits of INT OFF0 Registers
BMG160_SLOW_OFFSET_THRES__LEN
BMG160_SLOW_OFFSET_THRES__MSK
BMG160_SLOW_OFFSET_THRES__REG
2 bits of INT OFF0 Registers
Referenced by bmg160_get_slow_offset_thres, bmg160_set_slow_offset_thres.
BMG160_SLOW_OFFSET_DURN__POS
BMG160_SLOW_OFFSET_DURN__LEN
BMG160_SLOW_OFFSET_DURN__MSK
BMG160_SLOW_OFFSET_DURN__REG
2nd bit of INT OFF0 Registers
Referenced by bmg160_get_slow_offset_durn, bmg160_set_slow_offset_durn.
BMG160_SLOW_OFFSET_ENABLE_Z__POS
BMG160_SLOW_OFFSET_ENABLE_Z__LEN
BMG160_SLOW_OFFSET_ENABLE_Z__MSK
BMG160_SLOW_OFFSET_ENABLE_Z__REG
1st bit of INT OFF0 Registers
Referenced by bmg160_get_slow_offset_enable_axis, bmg160_set_slow_offset_enable_axis.
BMG160_SLOW_OFFSET_ENABLE_Y__POS
BMG160_SLOW_OFFSET_ENABLE_Y__LEN
BMG160_SLOW_OFFSET_ENABLE_Y__MSK
BMG160_SLOW_OFFSET_ENABLE_Y__REG
0th bit of INT OFF0 Registers
Referenced by bmg160_get_slow_offset_enable_axis, bmg160_set_slow_offset_enable_axis.
BMG160_SLOW_OFFSET_ENABLE_X__POS
BMG160_SLOW_OFFSET_ENABLE_X__LEN
BMG160_SLOW_OFFSET_ENABLE_X__MSK
BMG160_SLOW_OFFSET_ENABLE_X__REG
Referenced by bmg160_get_slow_offset_enable_axis, bmg160_set_slow_offset_enable_axis.
BMG160_AUTO_OFFSET_WORD_LENGHTH__POS
< Last 2 bits of INT OFF1 Registers
BMG160_AUTO_OFFSET_WORD_LENGHTH__LEN
BMG160_AUTO_OFFSET_WORD_LENGHTH__MSK
BMG160_AUTO_OFFSET_WORD_LENGHTH__REG
Referenced by bmg160_get_offset_word_length, bmg160_set_offset_word_length.
BMG160_FAST_OFFSET_WORD_LENGHTH__POS
< 2 bits of INT OFF1 Registers
BMG160_FAST_OFFSET_WORD_LENGHTH__LEN
BMG160_FAST_OFFSET_WORD_LENGHTH__MSK
BMG160_FAST_OFFSET_WORD_LENGHTH__REG
3nd bit of INT OFF1 Registers
Referenced by bmg160_get_offset_word_length, bmg160_set_offset_word_length.
BMG160_FAST_OFFSET_ENABLE__POS
BMG160_FAST_OFFSET_ENABLE__LEN
BMG160_FAST_OFFSET_ENABLE__MSK
BMG160_FAST_OFFSET_ENABLE__REG
2nd bit of INT OFF1 Registers
Referenced by bmg160_enable_fast_offset.
BMG160_FAST_OFFSET_ENABLE_Z__POS
BMG160_FAST_OFFSET_ENABLE_Z__LEN
BMG160_FAST_OFFSET_ENABLE_Z__MSK
BMG160_FAST_OFFSET_ENABLE_Z__REG
1st bit of INT OFF1 Registers
Referenced by bmg160_set_fast_offset_enable_axis.
BMG160_FAST_OFFSET_ENABLE_Y__POS
BMG160_FAST_OFFSET_ENABLE_Y__LEN
BMG160_FAST_OFFSET_ENABLE_Y__MSK
BMG160_FAST_OFFSET_ENABLE_Y__REG
0th bit of INT OFF1 Registers
Referenced by bmg160_set_fast_offset_enable_axis.
BMG160_FAST_OFFSET_ENABLE_X__POS
BMG160_FAST_OFFSET_ENABLE_X__LEN
BMG160_FAST_OFFSET_ENABLE_X__MSK
BMG160_FAST_OFFSET_ENABLE_X__REG
0 to (2) bits of INT OFF1 Registers
Referenced by bmg160_set_fast_offset_enable_axis.
BMG160_FAST_OFFSET_ENABLE_XYZ__POS
BMG160_FAST_OFFSET_ENABLE_XYZ__LEN
BMG160_FAST_OFFSET_ENABLE_XYZ__MSK
BMG160_FAST_OFFSET_ENABLE_XYZ__REG
Referenced by bmg160_get_fast_offset_enable_axis.
BMG160_TRIM_NVM_CTRL_ADDR_NVM_REMAIN__POS
< Last 4 bits of Trim NVM control Registers
BMG160_TRIM_NVM_CTRL_ADDR_NVM_REMAIN__LEN
BMG160_TRIM_NVM_CTRL_ADDR_NVM_REMAIN__MSK
BMG160_TRIM_NVM_CTRL_ADDR_NVM_REMAIN__REG
3rd bit of Trim NVM control Registers
Referenced by bmg160_get_nvm_remain.
BMG160_TRIM_NVM_CTRL_ADDR_NVM_LOAD__POS
BMG160_TRIM_NVM_CTRL_ADDR_NVM_LOAD__LEN
BMG160_TRIM_NVM_CTRL_ADDR_NVM_LOAD__MSK
BMG160_TRIM_NVM_CTRL_ADDR_NVM_LOAD__REG
2nd bit of Trim NVM control Registers
Referenced by bmg160_set_nvm_load.
BMG160_TRIM_NVM_CTRL_ADDR_NVM_RDY__POS
BMG160_TRIM_NVM_CTRL_ADDR_NVM_RDY__LEN
BMG160_TRIM_NVM_CTRL_ADDR_NVM_RDY__MSK
BMG160_TRIM_NVM_CTRL_ADDR_NVM_RDY__REG
1st bit of Trim NVM control Registers
Referenced by bmg160_get_nvm_rdy.
BMG160_TRIM_NVM_CTRL_ADDR_NVM_PROG_TRIG__POS
BMG160_TRIM_NVM_CTRL_ADDR_NVM_PROG_TRIG__LEN
BMG160_TRIM_NVM_CTRL_ADDR_NVM_PROG_TRIG__MSK
BMG160_TRIM_NVM_CTRL_ADDR_NVM_PROG_TRIG__REG
0th bit of Trim NVM control Registers
Referenced by bmg160_set_nvm_prog_trig.
BMG160_TRIM_NVM_CTRL_ADDR_NVM_PROG_MODE__POS
BMG160_TRIM_NVM_CTRL_ADDR_NVM_PROG_MODE__LEN
BMG160_TRIM_NVM_CTRL_ADDR_NVM_PROG_MODE__MSK
BMG160_TRIM_NVM_CTRL_ADDR_NVM_PROG_MODE__REG
Referenced by bmg160_get_nvm_prog_mode, bmg160_set_nvm_prog_mode.
BMG160_BGW_SPI3_WDT_ADDR_I2C_WDT_ENABLE__POS
< 2nd bit of SPI3 WDT Registers
BMG160_BGW_SPI3_WDT_ADDR_I2C_WDT_ENABLE__LEN
BMG160_BGW_SPI3_WDT_ADDR_I2C_WDT_ENABLE__MSK
BMG160_BGW_SPI3_WDT_ADDR_I2C_WDT_ENABLE__REG
1st bit of SPI3 WDT Registers
Referenced by bmg160_get_i2c_wdt, bmg160_set_i2c_wdt.
BMG160_BGW_SPI3_WDT_ADDR_I2C_WDT_SELECT__POS
BMG160_BGW_SPI3_WDT_ADDR_I2C_WDT_SELECT__LEN
BMG160_BGW_SPI3_WDT_ADDR_I2C_WDT_SELECT__MSK
BMG160_BGW_SPI3_WDT_ADDR_I2C_WDT_SELECT__REG
0th bit of SPI3 WDT Registers
Referenced by bmg160_get_i2c_wdt, bmg160_set_i2c_wdt.
BMG160_BGW_SPI3_WDT_ADDR_SPI3__POS
BMG160_BGW_SPI3_WDT_ADDR_SPI3__LEN
BMG160_BGW_SPI3_WDT_ADDR_SPI3__MSK
BMG160_BGW_SPI3_WDT_ADDR_SPI3__REG
Referenced by bmg160_get_spi3, bmg160_set_spi3.
BMG160_SELFTEST_ADDR_RATEOK__POS
< 4th bit of Self test Registers
BMG160_SELFTEST_ADDR_RATEOK__LEN
BMG160_SELFTEST_ADDR_RATEOK__MSK
BMG160_SELFTEST_ADDR_RATEOK__REG
2nd bit of Self test Registers
BMG160_SELFTEST_ADDR_BISTFAIL__POS
BMG160_SELFTEST_ADDR_BISTFAIL__LEN
BMG160_SELFTEST_ADDR_BISTFAIL__MSK
BMG160_SELFTEST_ADDR_BISTFAIL__REG
1st bit of Self test Registers
Referenced by bmg160_selftest.
BMG160_SELFTEST_ADDR_BISTRDY__POS
BMG160_SELFTEST_ADDR_BISTRDY__LEN
BMG160_SELFTEST_ADDR_BISTRDY__MSK
BMG160_SELFTEST_ADDR_BISTRDY__REG
0th bit of Self test Registers
BMG160_SELFTEST_ADDR_TRIGBIST__POS
BMG160_SELFTEST_ADDR_TRIGBIST__LEN
BMG160_SELFTEST_ADDR_TRIGBIST__MSK
BMG160_SELFTEST_ADDR_TRIGBIST__REG
Referenced by bmg160_selftest.
BMG160_FIFO_CGF1_ADDR_TAG__POS
< 7th bit of FIFO CGF1 Registers
BMG160_FIFO_CGF1_ADDR_TAG__LEN
BMG160_FIFO_CGF1_ADDR_TAG__MSK
BMG160_FIFO_CGF1_ADDR_TAG__REG
First 7 bits of FIFO CGF1 Registers
Referenced by bmg160_get_fifo_tag, bmg160_set_fifo_tag.
BMG160_FIFO_CGF1_ADDR_WML__POS
BMG160_FIFO_CGF1_ADDR_WML__LEN
BMG160_FIFO_CGF1_ADDR_WML__MSK
BMG160_FIFO_CGF1_ADDR_WML__REG
Last 2 bits of FIFO CGF0 Addr Registers
Referenced by bmg160_get_fifo_wm_level, bmg160_set_fifo_wm_level.
BMG160_FIFO_CGF0_ADDR_MODE__POS
BMG160_FIFO_CGF0_ADDR_MODE__LEN
BMG160_FIFO_CGF0_ADDR_MODE__MSK
BMG160_FIFO_CGF0_ADDR_MODE__REG
First 2 bits of FIFO CGF0 Addr Registers
Referenced by bmg160_get_fifo_mode, bmg160_set_fifo_mode.
BMG160_FIFO_CGF0_ADDR_DATA_SELECT__POS
BMG160_FIFO_CGF0_ADDR_DATA_SELECT__LEN
BMG160_FIFO_CGF0_ADDR_DATA_SELECT__MSK
BMG160_FIFO_CGF0_ADDR_DATA_SELECT__REG
Referenced by bmg160_get_fifo_data_select, bmg160_set_fifo_data_select.
BMG160_OFC1_ADDR_OFFSET_X__POS
< Last 2 bits of INL Offset MSB Registers
BMG160_OFC1_ADDR_OFFSET_X__LEN
BMG160_OFC1_ADDR_OFFSET_X__MSK
BMG160_OFC1_ADDR_OFFSET_X__REG
3 bits of INL Offset MSB Registers
Referenced by bmg160_get_offset, bmg160_set_offset.
BMG160_OFC1_ADDR_OFFSET_Y__POS
BMG160_OFC1_ADDR_OFFSET_Y__LEN
BMG160_OFC1_ADDR_OFFSET_Y__MSK
BMG160_OFC1_ADDR_OFFSET_Y__REG
First 3 bits of INL Offset MSB Registers
Referenced by bmg160_get_offset, bmg160_set_offset.
BMG160_OFC1_ADDR_OFFSET_Z__POS
BMG160_OFC1_ADDR_OFFSET_Z__LEN
BMG160_OFC1_ADDR_OFFSET_Z__MSK
BMG160_OFC1_ADDR_OFFSET_Z__REG
4 bits of Trim GP0 Registers
Referenced by bmg160_get_offset, bmg160_set_offset.
BMG160_TRIM_GP0_ADDR_GP0__POS
BMG160_TRIM_GP0_ADDR_GP0__LEN
BMG160_TRIM_GP0_ADDR_GP0__MSK
BMG160_TRIM_GP0_ADDR_GP0__REG
2 bits of Trim GP0 Registers
Referenced by bmg160_get_gp, bmg160_set_gp.
BMG160_TRIM_GP0_ADDR_OFFSET_X__POS
BMG160_TRIM_GP0_ADDR_OFFSET_X__LEN
BMG160_TRIM_GP0_ADDR_OFFSET_X__MSK
BMG160_TRIM_GP0_ADDR_OFFSET_X__REG
1st bit of Trim GP0 Registers
Referenced by bmg160_get_offset, bmg160_set_offset.
BMG160_TRIM_GP0_ADDR_OFFSET_Y__POS
BMG160_TRIM_GP0_ADDR_OFFSET_Y__LEN
BMG160_TRIM_GP0_ADDR_OFFSET_Y__MSK
BMG160_TRIM_GP0_ADDR_OFFSET_Y__REG
First bit of Trim GP0 Registers
Referenced by bmg160_get_offset, bmg160_set_offset.
BMG160_TRIM_GP0_ADDR_OFFSET_Z__POS
BMG160_TRIM_GP0_ADDR_OFFSET_Z__LEN
BMG160_TRIM_GP0_ADDR_OFFSET_Z__MSK
BMG160_TRIM_GP0_ADDR_OFFSET_Z__REG
Referenced by bmg160_get_offset, bmg160_set_offset.
BMG160_X_AXIS
< It refers BMG160 X-axis It refers BMG160 Y-axis
Referenced by bmg160_get_any_motion_enable_axis, bmg160_set_any_motion_enable_axis, bmg160_get_highrate_hyst, bmg160_set_highrate_hyst, bmg160_get_highrate_thres, bmg160_set_highrate_thres, bmg160_get_highrate_enable_axis, bmg160_set_highrate_enable_axis, bmg160_get_highrate_durn_axis, bmg160_set_highrate_durn_axis, bmg160_get_slow_offset_enable_axis, bmg160_set_slow_offset_enable_axis, bmg160_set_fast_offset_enable_axis, bmg160_get_offset, bmg160_set_offset.
BMG160_Y_AXIS
It refers BMG160 Z-axis
Referenced by bmg160_get_any_motion_enable_axis, bmg160_set_any_motion_enable_axis, bmg160_get_highrate_hyst, bmg160_set_highrate_hyst, bmg160_get_highrate_thres, bmg160_set_highrate_thres, bmg160_get_highrate_enable_axis, bmg160_set_highrate_enable_axis, bmg160_get_highrate_durn_axis, bmg160_set_highrate_durn_axis, bmg160_get_slow_offset_enable_axis, bmg160_set_slow_offset_enable_axis, bmg160_set_fast_offset_enable_axis, bmg160_get_offset, bmg160_set_offset.
BMG160_Z_AXIS
Referenced by bmg160_get_any_motion_enable_axis, bmg160_set_any_motion_enable_axis, bmg160_get_highrate_hyst, bmg160_set_highrate_hyst, bmg160_get_highrate_thres, bmg160_set_highrate_thres, bmg160_get_highrate_enable_axis, bmg160_set_highrate_enable_axis, bmg160_get_highrate_durn_axis, bmg160_set_highrate_durn_axis, bmg160_get_slow_offset_enable_axis, bmg160_set_slow_offset_enable_axis, bmg160_set_fast_offset_enable_axis, bmg160_get_offset, bmg160_set_offset.
BMG160_MODE_NORMAL
Referenced by bmg160_get_power_mode, bmg160_set_power_mode.
BMG160_MODE_DEEPSUSPEND
Referenced by bmg160_get_power_mode, bmg160_set_power_mode.
BMG160_MODE_SUSPEND
Referenced by bmg160_get_power_mode, bmg160_set_power_mode.
BMG160_MODE_FASTPOWERUP
Referenced by bmg160_get_power_mode, bmg160_set_power_mode.
BMG160_MODE_ADVANCEDPOWERSAVING
Referenced by bmg160_set_bw, bmg160_get_power_mode, bmg160_set_power_mode.
BMG160_GET_BITSLICE
Referenced by bmg160_get_data_X, bmg160_get_data_Y, bmg160_get_data_Z, bmg160_get_data_XYZ, bmg160_get_data_XYZI, bmg160_get_intr_stat_reg_zero, bmg160_get_intr_stat_reg_one, bmg160_get_intr_stat_reg_two, bmg160_get_intr_stat_reg_three, bmg160_get_range_reg, bmg160_get_bw, bmg160_get_pmu_ext_tri_select, bmg160_get_high_bw, bmg160_get_shadow_dis, bmg160_get_data_enable, bmg160_get_fifo_enable, bmg160_get_auto_offset_enable, bmg160_get_intr_output_type, bmg160_get_intr_level, bmg160_get_intr1_highrate, bmg160_get_intr1_any_motion, bmg160_get_intr_data, bmg160_get_intr2_offset, bmg160_get_intr_offset, bmg160_get_intr2_fifo, bmg160_get_intr1_fifo, bmg160_get_intr2_highrate, bmg160_get_intr2_any_motion, bmg160_get_offset_unfilt, bmg160_get_unfilt_data, bmg160_get_any_motion_thres, bmg160_get_awake_durn, bmg160_get_any_motion_durn_sample, bmg160_get_any_motion_enable_axis, bmg160_get_fifo_wm_enable, bmg160_get_latch_stat, bmg160_get_latch_intr, bmg160_get_highrate_hyst, bmg160_get_highrate_thres, bmg160_get_highrate_enable_axis, bmg160_get_slow_offset_thres, bmg160_get_slow_offset_durn, bmg160_get_slow_offset_enable_axis, bmg160_get_offset_word_length, bmg160_get_fast_offset_enable_axis, bmg160_get_nvm_remain, bmg160_get_nvm_rdy, bmg160_get_nvm_prog_mode, bmg160_get_i2c_wdt, bmg160_get_spi3, bmg160_get_fifo_tag, bmg160_get_fifo_wm_level, bmg160_get_offset, bmg160_get_gp, bmg160_get_fifo_frame_count, bmg160_get_fifo_overrun, bmg160_get_fifo_mode, bmg160_get_fifo_data_select, bmg160_selftest, bmg160_get_auto_sleep_durn, bmg160_get_sleep_durn.
BMG160_SET_BITSLICE
Referenced by bmg160_set_range_reg, bmg160_set_bw, bmg160_set_pmu_ext_tri_select, bmg160_set_high_bw, bmg160_set_shadow_dis, bmg160_set_data_enable, bmg160_set_fifo_enable, bmg160_set_auto_offset_enable, bmg160_set_intr_output_type, bmg160_set_intr_level, bmg160_set_intr1_highrate, bmg160_set_intr1_any_motion, bmg160_set_intr_data, bmg160_set_intr2_offset, bmg160_set_intr1_offset, bmg160_set_intr_fifo, bmg160_set_intr2_highrate, bmg160_set_intr2_any_motion, bmg160_set_offset_unfilt, bmg160_set_unfilt_data, bmg160_set_any_motion_thres, bmg160_set_awake_durn, bmg160_set_any_motion_durn_sample, bmg160_set_any_motion_enable_axis, bmg160_set_fifo_wm_enable, bmg160_set_rst_intr, bmg160_set_offset_rst, bmg160_set_latch_stat, bmg160_set_latch_intr, bmg160_set_highrate_hyst, bmg160_set_highrate_thres, bmg160_set_highrate_enable_axis, bmg160_set_slow_offset_thres, bmg160_set_slow_offset_durn, bmg160_set_slow_offset_enable_axis, bmg160_set_offset_word_length, bmg160_enable_fast_offset, bmg160_set_fast_offset_enable_axis, bmg160_set_nvm_load, bmg160_set_nvm_prog_trig, bmg160_set_nvm_prog_mode, bmg160_set_i2c_wdt, bmg160_set_spi3, bmg160_set_fifo_tag, bmg160_set_fifo_wm_level, bmg160_set_offset, bmg160_set_gp, bmg160_set_fifo_mode, bmg160_set_fifo_data_select, bmg160_set_power_mode, bmg160_selftest, bmg160_set_auto_sleep_durn, bmg160_set_sleep_durn.
BMG160_X_DATA_SIZE
Referenced by bmg160_get_data_X.
BMG160_Y_DATA_SIZE
Referenced by bmg160_get_data_Y.
BMG160_Z_DATA_SIZE
Referenced by bmg160_get_data_Z.
BMG160_XYZ_DATA_SIZE
Referenced by bmg160_get_data_XYZ.
BMG160_XYZ_INTR_DATA_SIZE
Referenced by bmg160_get_data_XYZI.
BMG160_X_LSB_DATA
Referenced by bmg160_get_data_X.
BMG160_X_MSB_DATA
Referenced by bmg160_get_data_X.
BMG160_Y_LSB_DATA
Referenced by bmg160_get_data_Y.
BMG160_Y_MSB_DATA
Referenced by bmg160_get_data_Y.
BMG160_Z_LSB_DATA
Referenced by bmg160_get_data_Z.
BMG160_Z_MSB_DATA
Referenced by bmg160_get_data_Z.
BMG160_INTR0_STAT
Referenced by bmg160_get_data_XYZI.
BMG160_INTR1_STAT
Referenced by bmg160_get_data_XYZI.
BMG160_INTR2_STAT
Referenced by bmg160_get_data_XYZI.
BMG160_INTR3_STAT
Referenced by bmg160_get_data_XYZI.
BMG160_INTR4_STAT
Referenced by bmg160_get_data_XYZI.
BMG160_DATA_FRAME_X_LSB_BYTE
Referenced by bmg160_get_data_XYZ, bmg160_get_data_XYZI.
BMG160_DATA_FRAME_X_MSB_BYTE
Referenced by bmg160_get_data_XYZ, bmg160_get_data_XYZI.
BMG160_DATA_FRAME_Y_LSB_BYTE
Referenced by bmg160_get_data_XYZ, bmg160_get_data_XYZI.
BMG160_DATA_FRAME_Y_MSB_BYTE
Referenced by bmg160_get_data_XYZ, bmg160_get_data_XYZI.
BMG160_DATA_FRAME_Z_LSB_BYTE
Referenced by bmg160_get_data_XYZ, bmg160_get_data_XYZI.
BMG160_DATA_FRAME_Z_MSB_BYTE
Referenced by bmg160_get_data_XYZ, bmg160_get_data_XYZI.
BMG160_DATA_FRAME_INTR0_BYTE
Referenced by bmg160_get_data_XYZI.
BMG160_DATA_FRAME_INTR1_BYTE
Referenced by bmg160_get_data_XYZI.
BMG160_DATA_FRAME_INTR2_BYTE
Referenced by bmg160_get_data_XYZI.
BMG160_DATA_FRAME_INTR3_BYTE
Referenced by bmg160_get_data_XYZI.
BMG160_DATA_FRAME_INTR4_BYTE
Referenced by bmg160_get_data_XYZI.
BMG160_NULL
constant declaration of NULL
Referenced by bmg160_get_data_X, bmg160_get_data_Y, bmg160_get_data_Z, bmg160_get_data_XYZ, bmg160_get_data_XYZI, bmg160_get_temp, bmg160_read_register, bmg160_burst_read, bmg160_write_register, bmg160_get_intr_stat_reg_zero, bmg160_get_intr_stat_reg_one, bmg160_get_intr_stat_reg_two, bmg160_get_intr_stat_reg_three, bmg160_get_range_reg, bmg160_set_range_reg, bmg160_get_bw, bmg160_set_bw, bmg160_get_pmu_ext_tri_select, bmg160_set_pmu_ext_tri_select, bmg160_get_high_bw, bmg160_set_high_bw, bmg160_get_shadow_dis, bmg160_set_shadow_dis, bmg160_set_soft_rst, bmg160_get_data_enable, bmg160_set_data_enable, bmg160_get_fifo_enable, bmg160_set_fifo_enable, bmg160_get_auto_offset_enable, bmg160_set_auto_offset_enable, bmg160_get_intr_output_type, bmg160_set_intr_output_type, bmg160_get_intr_level, bmg160_set_intr_level, bmg160_get_intr1_highrate, bmg160_set_intr1_highrate, bmg160_get_intr1_any_motion, bmg160_set_intr1_any_motion, bmg160_get_intr_data, bmg160_set_intr_data, bmg160_get_intr2_offset, bmg160_set_intr2_offset, bmg160_get_intr_offset, bmg160_set_intr1_offset, bmg160_get_intr2_fifo, bmg160_get_intr1_fifo, bmg160_set_intr_fifo, bmg160_get_intr2_highrate, bmg160_set_intr2_highrate, bmg160_get_intr2_any_motion, bmg160_set_intr2_any_motion, bmg160_get_offset_unfilt, bmg160_set_offset_unfilt, bmg160_get_unfilt_data, bmg160_set_unfilt_data, bmg160_get_any_motion_thres, bmg160_set_any_motion_thres, bmg160_get_awake_durn, bmg160_set_awake_durn, bmg160_get_any_motion_durn_sample, bmg160_set_any_motion_durn_sample, bmg160_get_any_motion_enable_axis, bmg160_set_any_motion_enable_axis, bmg160_get_fifo_wm_enable, bmg160_set_fifo_wm_enable, bmg160_set_rst_intr, bmg160_set_offset_rst, bmg160_get_latch_stat, bmg160_set_latch_stat, bmg160_get_latch_intr, bmg160_set_latch_intr, bmg160_get_highrate_hyst, bmg160_set_highrate_hyst, bmg160_get_highrate_thres, bmg160_set_highrate_thres, bmg160_get_highrate_enable_axis, bmg160_set_highrate_enable_axis, bmg160_get_highrate_durn_axis, bmg160_set_highrate_durn_axis, bmg160_get_slow_offset_thres, bmg160_set_slow_offset_thres, bmg160_get_slow_offset_durn, bmg160_set_slow_offset_durn, bmg160_get_slow_offset_enable_axis, bmg160_set_slow_offset_enable_axis, bmg160_get_offset_word_length, bmg160_set_offset_word_length, bmg160_enable_fast_offset, bmg160_get_fast_offset_enable_axis, bmg160_set_fast_offset_enable_axis, bmg160_get_nvm_remain, bmg160_set_nvm_load, bmg160_get_nvm_rdy, bmg160_set_nvm_prog_trig, bmg160_get_nvm_prog_mode, bmg160_set_nvm_prog_mode, bmg160_get_i2c_wdt, bmg160_set_i2c_wdt, bmg160_get_spi3, bmg160_set_spi3, bmg160_get_fifo_tag, bmg160_set_fifo_tag, bmg160_get_fifo_wm_level, bmg160_set_fifo_wm_level, bmg160_get_offset, bmg160_set_offset, bmg160_get_gp, bmg160_set_gp, bmg160_get_FIFO_data_reg, bmg160_get_fifo_stat_reg, bmg160_get_fifo_frame_count, bmg160_get_fifo_overrun, bmg160_get_fifo_mode, bmg160_set_fifo_mode, bmg160_get_fifo_data_select, bmg160_set_fifo_data_select, bmg160_get_auto_sleep_durn, bmg160_set_auto_sleep_durn, bmg160_get_sleep_durn, bmg160_set_sleep_durn.
BMG160_DISABLE
It refers BMG160 disable
BMG160_ENABLE
It refers BMG160 enable
BMG160_OFF
It refers BMG160 OFF state
BMG160_ON
It refers BMG160 ON state
BMG160_INTR1
It refers BMG160 INT1
Referenced by bmg160_get_intr_output_type, bmg160_set_intr_output_type, bmg160_get_intr_level, bmg160_set_intr_level, bmg160_set_intr_fifo.
BMG160_INTR2
It refers BMG160 INT2
Referenced by bmg160_get_intr_output_type, bmg160_set_intr_output_type, bmg160_get_intr_level, bmg160_set_intr_level, bmg160_set_intr_fifo.
BMG160_SLOW_OFFSET
It refers BMG160 Slow Offset
Referenced by bmg160_get_offset_unfilt, bmg160_set_offset_unfilt.
BMG160_AUTO_OFFSET
It refers BMG160 Auto Offset
Referenced by bmg160_get_intr2_offset, bmg160_set_intr2_offset, bmg160_get_intr_offset, bmg160_set_intr1_offset.
BMG160_FAST_OFFSET
It refers BMG160 Fast Offset
Referenced by bmg160_get_intr2_offset, bmg160_set_intr2_offset, bmg160_get_intr_offset, bmg160_set_intr1_offset, bmg160_get_offset_unfilt, bmg160_set_offset_unfilt.
BMG160_OFFSET_MASK_BYTE_OF_DATA
Referenced by bmg160_set_offset.
BMG160_OFFSET_X_BIT_MASK1
Referenced by bmg160_set_offset.
BMG160_OFFSET_X_BIT_MASK2
Referenced by bmg160_set_offset.
BMG160_OFFSET_Y_Z_BIT_MASK1
Referenced by bmg160_set_offset.
BMG160_OFFSET_Y_Z_BIT_MASK2
Referenced by bmg160_set_offset.
BMG160_S_TAP
It refers BMG160 Single Tap
BMG160_D_TAP
It refers BMG160 Double Tap
BMG160_INTR1_DATA
It refers BMG160 Int1 Data
Referenced by bmg160_get_intr_data, bmg160_set_intr_data.
BMG160_INTR2_DATA
It refers BMG160 Int2 Data
Referenced by bmg160_get_intr_data, bmg160_set_intr_data.
BMG160_TAP_UNFILT_DATA
It refers BMG160 Tap unfilt data
BMG160_HIGHRATE_UNFILT_DATA
It refers BMG160 High unfilt data
Referenced by bmg160_get_unfilt_data, bmg160_set_unfilt_data.
BMG160_CONST_UNFILT_DATA
It refers BMG160 Const unfilt data
BMG160_ANY_MOTION_UNFILT_DATA
It refers BMG160 Any unfilt data
Referenced by bmg160_get_unfilt_data, bmg160_set_unfilt_data.
BMG160_SHAKE_UNFILT_DATA
It refers BMG160 Shake unfilt data
BMG160_SHAKE_TH
It refers BMG160 Shake Threshold
BMG160_SHAKE_TH2
It refers BMG160 Shake Threshold2
BMG160_AUTO_OFFSET_WORD_LENGHTH
It refers BMG160 Auto Offset word length
Referenced by bmg160_get_offset_word_length, bmg160_set_offset_word_length.
BMG160_FAST_OFFSET_WORD_LENGHTH
It refers BMG160 Fast Offset word length
Referenced by bmg160_get_offset_word_length, bmg160_set_offset_word_length.
BMG160_I2C_WDT_ENABLE
It refers BMG160 I2C WDT En
Referenced by bmg160_get_i2c_wdt, bmg160_set_i2c_wdt.
BMG160_I2C_WDT_SELECT
It refers BMG160 I2C WDT Sel
Referenced by bmg160_get_i2c_wdt, bmg160_set_i2c_wdt.
BMG160_EXT_MODE
It refers BMG160 Ext Mode
BMG160_EXT_PAGE
It refers BMG160 Ext page
BMG160_START_ADDR
It refers BMG160 Start Address
BMG160_STOP_ADDR
It refers BMG160 Stop Address
BMG160_SLOW_CMD
It refers BMG160 Slow Command
BMG160_FAST_CMD
It refers BMG160 Fast Command
BMG160_TRIM_VRA
It refers BMG160 Trim VRA
BMG160_TRIM_VRD
It refers BMG160 Trim VRD
BMG160_LOGBIT_EM
It refers BMG160 LogBit Em
BMG160_LOGBIT_VM
It refers BMG160 LogBit VM
BMG160_GP0
It refers BMG160 GP0
Referenced by bmg160_get_gp, bmg160_set_gp.
BMG160_GP1
It refers BMG160 GP1
Referenced by bmg160_get_gp, bmg160_set_gp.
BMG160_LOW_SPEED
It refers BMG160 Low Speed Oscillator
BMG160_HIGHRATE_SPEED
It refers BMG160 High Speed Oscillator
BMG160_DRIVE_OFFSET_P
It refers BMG160 Drive Offset P
BMG160_DRIVE_OFFSET_N
It refers BMG160 Drive Offset N
BMG160_TEST_MODE_ENABLE
It refers BMG160 Test Mode Enable
BMG160_TEST_MODE_REG
It refers BMG160 Test Mode reg
BMG160_IBIAS_DRIVE_TRIM
It refers BMG160 IBIAS Drive Trim
BMG160_IBIAS_RATE_TRIM
It refers BMG160 IBIAS Rate Trim
BMG160_BAA_MODE
It refers BMG160 BAA Mode Trim
BMG160_BMA_MODE
It refers BMG160 BMA Mode Trim
BMG160_PI_KP
It refers BMG160 PI KP
BMG160_PI_KI
It refers BMG160 PI KI
C_BMG160_SUCCESS
It refers BMG160 operation is success
Referenced by bmg160_selftest, Gyroscope_setBandwidth, Gyroscope_setRange, libErrorMapping.
C_BMG160_FAILURE
It refers BMG160 operation is Failure
Referenced by bmg160_selftest, Gyroscope_setBandwidth, Gyroscope_setRange, Gyroscope_getRange, Gyroscope_getBandwidth, Gyroscope_setMode, Gyroscope_getMode, Gyroscope_readXyzValue, Gyroscope_readXyzDegreeValue, Gyroscope_setSleepDuration, Gyroscope_setAutoSleepDuration.
E_BMG160_NULL_PTR
Referenced by bmg160_get_data_X, bmg160_get_data_Y, bmg160_get_data_Z, bmg160_get_data_XYZ, bmg160_get_data_XYZI, bmg160_get_temp, bmg160_read_register, bmg160_burst_read, bmg160_write_register, bmg160_get_intr_stat_reg_zero, bmg160_get_intr_stat_reg_one, bmg160_get_intr_stat_reg_two, bmg160_get_intr_stat_reg_three, bmg160_get_range_reg, bmg160_set_range_reg, bmg160_get_bw, bmg160_set_bw, bmg160_get_pmu_ext_tri_select, bmg160_set_pmu_ext_tri_select, bmg160_get_high_bw, bmg160_set_high_bw, bmg160_get_shadow_dis, bmg160_set_shadow_dis, bmg160_set_soft_rst, bmg160_get_data_enable, bmg160_set_data_enable, bmg160_get_fifo_enable, bmg160_set_fifo_enable, bmg160_get_auto_offset_enable, bmg160_set_auto_offset_enable, bmg160_get_intr_output_type, bmg160_set_intr_output_type, bmg160_get_intr_level, bmg160_set_intr_level, bmg160_get_intr1_highrate, bmg160_set_intr1_highrate, bmg160_get_intr1_any_motion, bmg160_set_intr1_any_motion, bmg160_get_intr_data, bmg160_set_intr_data, bmg160_get_intr2_offset, bmg160_set_intr2_offset, bmg160_get_intr_offset, bmg160_set_intr1_offset, bmg160_get_intr2_fifo, bmg160_get_intr1_fifo, bmg160_set_intr_fifo, bmg160_get_intr2_highrate, bmg160_set_intr2_highrate, bmg160_get_intr2_any_motion, bmg160_set_intr2_any_motion, bmg160_get_offset_unfilt, bmg160_set_offset_unfilt, bmg160_get_unfilt_data, bmg160_set_unfilt_data, bmg160_get_any_motion_thres, bmg160_set_any_motion_thres, bmg160_get_awake_durn, bmg160_set_awake_durn, bmg160_get_any_motion_durn_sample, bmg160_set_any_motion_durn_sample, bmg160_get_any_motion_enable_axis, bmg160_set_any_motion_enable_axis, bmg160_get_fifo_wm_enable, bmg160_set_fifo_wm_enable, bmg160_set_rst_intr, bmg160_set_offset_rst, bmg160_get_latch_stat, bmg160_set_latch_stat, bmg160_get_latch_intr, bmg160_set_latch_intr, bmg160_get_highrate_hyst, bmg160_set_highrate_hyst, bmg160_get_highrate_thres, bmg160_set_highrate_thres, bmg160_get_highrate_enable_axis, bmg160_set_highrate_enable_axis, bmg160_get_highrate_durn_axis, bmg160_set_highrate_durn_axis, bmg160_get_slow_offset_thres, bmg160_set_slow_offset_thres, bmg160_get_slow_offset_durn, bmg160_set_slow_offset_durn, bmg160_get_slow_offset_enable_axis, bmg160_set_slow_offset_enable_axis, bmg160_get_offset_word_length, bmg160_set_offset_word_length, bmg160_enable_fast_offset, bmg160_get_fast_offset_enable_axis, bmg160_set_fast_offset_enable_axis, bmg160_get_nvm_remain, bmg160_set_nvm_load, bmg160_get_nvm_rdy, bmg160_set_nvm_prog_trig, bmg160_get_nvm_prog_mode, bmg160_set_nvm_prog_mode, bmg160_get_i2c_wdt, bmg160_set_i2c_wdt, bmg160_get_spi3, bmg160_set_spi3, bmg160_get_fifo_tag, bmg160_set_fifo_tag, bmg160_get_fifo_wm_level, bmg160_set_fifo_wm_level, bmg160_get_offset, bmg160_set_offset, bmg160_get_gp, bmg160_set_gp, bmg160_get_FIFO_data_reg, bmg160_get_fifo_stat_reg, bmg160_get_fifo_frame_count, bmg160_get_fifo_overrun, bmg160_get_fifo_mode, bmg160_set_fifo_mode, bmg160_get_fifo_data_select, bmg160_set_fifo_data_select, bmg160_get_power_mode, bmg160_set_power_mode, bmg160_get_auto_sleep_durn, bmg160_set_auto_sleep_durn, bmg160_get_sleep_durn, bmg160_set_sleep_durn, bmg160LibErrorMapping, libErrorMapping, Bmg160Utils_initialize.
E_BMG160_OUT_OF_RANGE
Referenced by bmg160_set_range_reg, bmg160_set_bw, bmg160_set_high_bw, bmg160_set_shadow_dis, bmg160_set_fifo_enable, bmg160_get_intr_output_type, bmg160_set_intr_output_type, bmg160_get_intr_level, bmg160_set_intr_level, bmg160_get_intr_data, bmg160_set_intr_data, bmg160_get_intr2_offset, bmg160_set_intr2_offset, bmg160_get_intr_offset, bmg160_set_intr1_offset, bmg160_set_intr_fifo, bmg160_get_offset_unfilt, bmg160_set_offset_unfilt, bmg160_get_unfilt_data, bmg160_set_unfilt_data, bmg160_get_any_motion_enable_axis, bmg160_set_any_motion_enable_axis, bmg160_set_fifo_wm_enable, bmg160_get_highrate_hyst, bmg160_set_highrate_hyst, bmg160_get_highrate_thres, bmg160_set_highrate_thres, bmg160_get_highrate_enable_axis, bmg160_set_highrate_enable_axis, bmg160_get_highrate_durn_axis, bmg160_set_highrate_durn_axis, bmg160_get_slow_offset_enable_axis, bmg160_set_slow_offset_enable_axis, bmg160_get_offset_word_length, bmg160_set_offset_word_length, bmg160_set_fast_offset_enable_axis, bmg160_get_i2c_wdt, bmg160_set_i2c_wdt, bmg160_set_fifo_tag, bmg160_set_fifo_wm_level, bmg160_get_offset, bmg160_set_offset, bmg160_get_gp, bmg160_set_gp, bmg160_set_fifo_mode, bmg160_set_fifo_data_select, bmg160_set_power_mode, bmg160_set_auto_sleep_durn, bmg160_set_sleep_durn.
ERROR
BMG160_SPI_RD_MASK
Read mask
BMG160_READ_SET
Setting for reading data
BMG160_SHIFT_BIT_POSITION_BY_01_BIT
Shift bit by 1 Position
Referenced by bmg160_get_offset.
BMG160_SHIFT_BIT_POSITION_BY_02_BITS
Shift bit by 2 Position
Referenced by bmg160_get_offset.
BMG160_SHIFT_BIT_POSITION_BY_04_BITS
Shift bit by (4) Position
Referenced by bmg160_get_offset, bmg160_set_offset.
BMG160_SHIFT_BIT_POSITION_BY_08_BITS
Shift bit by (8) Position
Referenced by bmg160_get_data_X, bmg160_get_data_Y, bmg160_get_data_Z, bmg160_get_data_XYZ, bmg160_get_data_XYZI.
BMG160_INIT_VALUE
Referenced by bmg160_init, bmg160_get_data_X, bmg160_get_data_Y, bmg160_get_data_Z, bmg160_get_data_XYZ, bmg160_get_data_XYZI, bmg160_get_temp, bmg160_get_intr_stat_reg_zero, bmg160_get_intr_stat_reg_one, bmg160_get_intr_stat_reg_two, bmg160_get_intr_stat_reg_three, bmg160_get_range_reg, bmg160_set_range_reg, bmg160_get_bw, bmg160_set_bw, bmg160_get_pmu_ext_tri_select, bmg160_set_pmu_ext_tri_select, bmg160_get_high_bw, bmg160_set_high_bw, bmg160_get_shadow_dis, bmg160_set_shadow_dis, bmg160_set_soft_rst, bmg160_get_data_enable, bmg160_set_data_enable, bmg160_get_fifo_enable, bmg160_set_fifo_enable, bmg160_get_auto_offset_enable, bmg160_set_auto_offset_enable, bmg160_get_intr_output_type, bmg160_set_intr_output_type, bmg160_get_intr_level, bmg160_set_intr_level, bmg160_get_intr1_highrate, bmg160_set_intr1_highrate, bmg160_get_intr1_any_motion, bmg160_set_intr1_any_motion, bmg160_get_intr_data, bmg160_set_intr_data, bmg160_get_intr2_offset, bmg160_set_intr2_offset, bmg160_get_intr_offset, bmg160_set_intr1_offset, bmg160_get_intr2_fifo, bmg160_get_intr1_fifo, bmg160_set_intr_fifo, bmg160_get_intr2_highrate, bmg160_set_intr2_highrate, bmg160_get_intr2_any_motion, bmg160_set_intr2_any_motion, bmg160_get_offset_unfilt, bmg160_set_offset_unfilt, bmg160_get_unfilt_data, bmg160_set_unfilt_data, bmg160_get_any_motion_thres, bmg160_set_any_motion_thres, bmg160_get_awake_durn, bmg160_set_awake_durn, bmg160_get_any_motion_durn_sample, bmg160_set_any_motion_durn_sample, bmg160_get_any_motion_enable_axis, bmg160_set_any_motion_enable_axis, bmg160_get_fifo_wm_enable, bmg160_set_fifo_wm_enable, bmg160_set_rst_intr, bmg160_set_offset_rst, bmg160_get_latch_stat, bmg160_set_latch_stat, bmg160_get_latch_intr, bmg160_set_latch_intr, bmg160_get_highrate_hyst, bmg160_set_highrate_hyst, bmg160_get_highrate_thres, bmg160_set_highrate_thres, bmg160_get_highrate_enable_axis, bmg160_set_highrate_enable_axis, bmg160_get_highrate_durn_axis, bmg160_set_highrate_durn_axis, bmg160_get_slow_offset_thres, bmg160_set_slow_offset_thres, bmg160_get_slow_offset_durn, bmg160_set_slow_offset_durn, bmg160_get_slow_offset_enable_axis, bmg160_set_slow_offset_enable_axis, bmg160_get_offset_word_length, bmg160_set_offset_word_length, bmg160_enable_fast_offset, bmg160_get_fast_offset_enable_axis, bmg160_set_fast_offset_enable_axis, bmg160_get_nvm_remain, bmg160_set_nvm_load, bmg160_get_nvm_rdy, bmg160_set_nvm_prog_trig, bmg160_get_nvm_prog_mode, bmg160_set_nvm_prog_mode, bmg160_get_i2c_wdt, bmg160_set_i2c_wdt, bmg160_get_spi3, bmg160_set_spi3, bmg160_get_fifo_tag, bmg160_set_fifo_tag, bmg160_get_fifo_wm_level, bmg160_set_fifo_wm_level, bmg160_get_offset, bmg160_set_offset, bmg160_get_gp, bmg160_set_gp, bmg160_get_FIFO_data_reg, bmg160_get_fifo_stat_reg, bmg160_get_fifo_frame_count, bmg160_get_fifo_overrun, bmg160_get_fifo_mode, bmg160_set_fifo_mode, bmg160_get_fifo_data_select, bmg160_set_fifo_data_select, bmg160_get_power_mode, bmg160_set_power_mode, bmg160_selftest, bmg160_get_auto_sleep_durn, bmg160_set_auto_sleep_durn, bmg160_get_sleep_durn, bmg160_set_sleep_durn.
BMG160_GEN_READ_WRITE_DATA_LENGTH
Referenced by bmg160_init, bmg160_get_temp, bmg160_get_intr_stat_reg_zero, bmg160_get_intr_stat_reg_one, bmg160_get_intr_stat_reg_two, bmg160_get_intr_stat_reg_three, bmg160_get_range_reg, bmg160_set_range_reg, bmg160_get_bw, bmg160_set_bw, bmg160_get_pmu_ext_tri_select, bmg160_set_pmu_ext_tri_select, bmg160_get_high_bw, bmg160_set_high_bw, bmg160_get_shadow_dis, bmg160_set_shadow_dis, bmg160_set_soft_rst, bmg160_get_data_enable, bmg160_set_data_enable, bmg160_get_fifo_enable, bmg160_set_fifo_enable, bmg160_get_auto_offset_enable, bmg160_set_auto_offset_enable, bmg160_get_intr_output_type, bmg160_set_intr_output_type, bmg160_get_intr_level, bmg160_set_intr_level, bmg160_get_intr1_highrate, bmg160_set_intr1_highrate, bmg160_get_intr1_any_motion, bmg160_set_intr1_any_motion, bmg160_get_intr_data, bmg160_set_intr_data, bmg160_get_intr2_offset, bmg160_set_intr2_offset, bmg160_get_intr_offset, bmg160_set_intr1_offset, bmg160_get_intr2_fifo, bmg160_get_intr1_fifo, bmg160_set_intr_fifo, bmg160_get_intr2_highrate, bmg160_set_intr2_highrate, bmg160_get_intr2_any_motion, bmg160_set_intr2_any_motion, bmg160_get_offset_unfilt, bmg160_set_offset_unfilt, bmg160_get_unfilt_data, bmg160_set_unfilt_data, bmg160_get_any_motion_thres, bmg160_set_any_motion_thres, bmg160_get_awake_durn, bmg160_set_awake_durn, bmg160_get_any_motion_durn_sample, bmg160_set_any_motion_durn_sample, bmg160_get_any_motion_enable_axis, bmg160_set_any_motion_enable_axis, bmg160_get_fifo_wm_enable, bmg160_set_fifo_wm_enable, bmg160_set_rst_intr, bmg160_set_offset_rst, bmg160_get_latch_stat, bmg160_set_latch_stat, bmg160_get_latch_intr, bmg160_set_latch_intr, bmg160_get_highrate_hyst, bmg160_set_highrate_hyst, bmg160_get_highrate_thres, bmg160_set_highrate_thres, bmg160_get_highrate_enable_axis, bmg160_set_highrate_enable_axis, bmg160_get_highrate_durn_axis, bmg160_set_highrate_durn_axis, bmg160_get_slow_offset_thres, bmg160_set_slow_offset_thres, bmg160_get_slow_offset_durn, bmg160_set_slow_offset_durn, bmg160_get_slow_offset_enable_axis, bmg160_set_slow_offset_enable_axis, bmg160_get_offset_word_length, bmg160_set_offset_word_length, bmg160_enable_fast_offset, bmg160_get_fast_offset_enable_axis, bmg160_set_fast_offset_enable_axis, bmg160_get_nvm_remain, bmg160_set_nvm_load, bmg160_get_nvm_rdy, bmg160_set_nvm_prog_trig, bmg160_get_nvm_prog_mode, bmg160_set_nvm_prog_mode, bmg160_get_i2c_wdt, bmg160_set_i2c_wdt, bmg160_get_spi3, bmg160_set_spi3, bmg160_get_fifo_tag, bmg160_set_fifo_tag, bmg160_get_fifo_wm_level, bmg160_set_fifo_wm_level, bmg160_get_offset, bmg160_set_offset, bmg160_get_gp, bmg160_set_gp, bmg160_get_FIFO_data_reg, bmg160_get_fifo_stat_reg, bmg160_get_fifo_frame_count, bmg160_get_fifo_overrun, bmg160_get_fifo_mode, bmg160_set_fifo_mode, bmg160_get_fifo_data_select, bmg160_set_fifo_data_select, bmg160_get_power_mode, bmg160_set_power_mode, bmg160_selftest, bmg160_get_auto_sleep_durn, bmg160_set_auto_sleep_durn, bmg160_get_sleep_durn, bmg160_set_sleep_durn.
BMG160_X_DATA_LENGTH
Referenced by bmg160_get_data_X.
BMG160_Y_DATA_LENGTH
Referenced by bmg160_get_data_Y.
BMG160_Z_DATA_LENGTH
Referenced by bmg160_get_data_Z.
BMG160_ALL_DATA_FRAME_LENGTH
Referenced by bmg160_get_data_XYZ.
BMG160_BIT_LENGTH_HIGH_BW
Referenced by bmg160_set_high_bw.
BMG160_BIT_LENGTH_SHADOW_DIS
Referenced by bmg160_set_shadow_dis.
BMG160_BIT_LENGTH_FIFO
Referenced by bmg160_set_fifo_enable.
BMG160_BIT_LENGTH_FIFO_WM
Referenced by bmg160_set_fifo_wm_enable.
BMG160_BIT_LENGTH_FIFO_TAG
Referenced by bmg160_set_fifo_tag.
BMG160_BIT_LENGTH_FIFO_MODE
Referenced by bmg160_set_fifo_mode.
BMG160_BIT_LENGTH_FIFO_DATA_SELECT
Referenced by bmg160_set_fifo_data_select.
BMG160_BIT_MASK_MODE_LPM1
Referenced by bmg160_set_power_mode.
BMG160_BIT_LENGTH_RANGE
Referenced by bmg160_set_range_reg.
BMG160_BIT_LENGTH_BW
Referenced by bmg160_set_bw.
BMG160_BIT_LENGTH_DURN
Referenced by bmg160_set_auto_sleep_durn, bmg160_set_sleep_durn.
BMG160_BIT_LENGTH_POWER_MODE
Referenced by bmg160_set_power_mode.
BMG160_XYZ_AND_INTR_DATA_LENGTH
Referenced by bmg160_get_data_XYZI.
BMG160_FIFO_WM_LENGTH
Referenced by bmg160_set_fifo_wm_level.
BMG160_POWER_MODE_DELAY
Referenced by bmg160_set_power_mode.
BMG160_SELFTEST_DELAY
Referenced by bmg160_selftest.
BMG160_SELFTEST_BISTFAIL
Referenced by bmg160_selftest.
BMG160_SELFTEST_RATEOK
Referenced by bmg160_selftest.
C_BMG160_NO_FILTER_U8X
Referenced by bmg160_set_auto_sleep_durn.
C_BMG160_BW_230HZ_U8X
Referenced by bmg160_set_auto_sleep_durn.
C_BMG160_BW_116HZ_U8X
Referenced by bmg160_set_auto_sleep_durn.
C_BMG160_BW_47HZ_U8X
Referenced by bmg160_set_auto_sleep_durn.
C_BMG160_BW_23HZ_U8X
Referenced by bmg160_set_auto_sleep_durn.
C_BMG160_BW_12HZ_U8X
Referenced by bmg160_set_auto_sleep_durn.
C_BMG160_BW_64HZ_U8X
Referenced by bmg160_set_auto_sleep_durn.
C_BMG160_BW_32HZ_U8X
Referenced by bmg160_set_auto_sleep_durn.
BMG160_BW_500_HZ
BMG160_BW_230_HZ
BMG160_BW_116_HZ
BMG160_BW_47_HZ
BMG160_BW_23_HZ
BMG160_BW_12_HZ
BMG160_BW_64_HZ
BMG160_BW_32_HZ
C_BMG160_NO_AUTO_SLEEP_DURN_U8X
C_BMG160_4MS_AUTO_SLEEP_DURN_U8X
Referenced by bmg160_set_auto_sleep_durn.
C_BMG160_5MS_AUTO_SLEEP_DURN_U8X
Referenced by bmg160_set_auto_sleep_durn.
C_BMG160_8MS_AUTO_SLEEP_DURN_U8X
C_BMG160_10MS_AUTO_SLEEP_DURN_U8X
Referenced by bmg160_set_auto_sleep_durn.
C_BMG160_15MS_AUTO_SLEEP_DURN_U8X
C_BMG160_20MS_AUTO_SLEEP_DURN_U8X
Referenced by bmg160_set_auto_sleep_durn.
C_BMG160_40MS_AUTO_SLEEP_DURN_U8X
BMG160_RANGE_2000
BMG160_RANGE_1000
BMG160_RANGE_500
BMG160_RANGE_250
BMG160_RANGE_125
BMG160_SOFT_RESET
Referenced by bmg160_set_soft_rst.
BMG160_NON_LATCH
BMG160_LATCH_250_MS
BMG160_LATCH_500_MS
BMG160_LATCH_1_SEC
BMG160_LATCH_2_SEC
BMG160_LATCH_4_SEC
BMG160_LATCH_8_SEC
BMG160_LATCH_LATCHED
BMG160_LATCH_NON_LATCHED
BMG160_LATCH_250_MICRO_SEC
BMG160_LATCH_500_MICRO_SEC
BMG160_LATCH_1_MILLI_SEC
BMG160_LATCH_12_5_MILLI_SEC
BMG160_LATCH_25_MILLI_SEC
BMG160_LATCH_50_MILLI_SEC
BMG160_WR_FUNC_PTR
BMG160_RD_FUNC_PTR
BMG160_BRD_FUNC_PTR
BMG160_MDELAY_DATA_TYPE
BMG160_RETURN_FUNCTION_TYPE bmg160_init(struct bmg160_t *bmg160)
This function is used for initialize the bus read and bus write functions and assign the chip id and I2C address of the gyro chip id is read in the register 0x00 bit from 0 to 7.
bmg160 structure pointer. While changing the parameter of the bmg160_t consider the following point: Changing the reference value of the parameter will changes the local copy or local reference make sure your changes will not affect the reference value of the parameter (Better case don't change the reference value of the parameter) results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, bmg160_t::dev_addr, BMG160_CHIP_ID_ADDR, BMG160_GEN_READ_WRITE_DATA_LENGTH, bmg160_t::chip_id.
Referenced by Bmg160Utils_initialize.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_data_X(s16 *v_data_x_s16)
Reads Rate data X in the registers 0x02 to 0x03.
v_data_x_s16 The value of gyro x axis data results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, BMG160_INIT_VALUE, BMG160_X_DATA_SIZE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_RATE_X_LSB_BIT__REG, BMG160_X_DATA_LENGTH, BMG160_X_LSB_DATA, BMG160_GET_BITSLICE, BMG160_X_MSB_DATA, BMG160_SHIFT_BIT_POSITION_BY_08_BITS.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_data_Y(s16 *v_data_y_s16)
Reads Rate data Y in the registers 0x04 to 0x05.
v_data_y_s16 The value of gyro y axis data results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_Y_DATA_SIZE, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_RATE_Y_LSB_BIT__REG, BMG160_Y_DATA_LENGTH, BMG160_Y_LSB_DATA, BMG160_GET_BITSLICE, BMG160_Y_MSB_DATA, BMG160_SHIFT_BIT_POSITION_BY_08_BITS.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_data_Z(s16 *v_data_z_s16)
Reads Rate data Z in the registers 0x06 to 0x07.
v_data_z_s16 The value of gyro z axis data results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_Z_DATA_SIZE, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_RATE_Z_LSB_BIT__REG, BMG160_Z_DATA_LENGTH, BMG160_Z_LSB_DATA, BMG160_GET_BITSLICE, BMG160_Z_MSB_DATA, BMG160_SHIFT_BIT_POSITION_BY_08_BITS.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_data_XYZ(struct bmg160_data_t *data)
Reads data X,Y and Z from register location 0x02 to 0x07.
data The value of gyro xyz axis data results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_XYZ_DATA_SIZE, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_RATE_X_LSB_BIT__REG, BMG160_ALL_DATA_FRAME_LENGTH, BMG160_DATA_FRAME_X_LSB_BYTE, BMG160_GET_BITSLICE, bmg160_data_t::datax, BMG160_DATA_FRAME_X_MSB_BYTE, BMG160_SHIFT_BIT_POSITION_BY_08_BITS, BMG160_DATA_FRAME_Y_LSB_BYTE, bmg160_data_t::datay, BMG160_DATA_FRAME_Y_MSB_BYTE, BMG160_DATA_FRAME_Z_LSB_BYTE, bmg160_data_t::dataz, BMG160_DATA_FRAME_Z_MSB_BYTE.
Referenced by Gyroscope_readXyzValue, Gyroscope_readXyzDegreeValue.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_data_XYZI(struct bmg160_data_t *data)
Reads data X,Y,Z and Interrupts from register location 0x02 to 0x07.
data The value of gyro xyz axis data and interrupt status results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_XYZ_INTR_DATA_SIZE, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_RATE_X_LSB_BIT__REG, BMG160_XYZ_AND_INTR_DATA_LENGTH, BMG160_DATA_FRAME_X_LSB_BYTE, BMG160_GET_BITSLICE, bmg160_data_t::datax, BMG160_DATA_FRAME_X_MSB_BYTE, BMG160_SHIFT_BIT_POSITION_BY_08_BITS, BMG160_DATA_FRAME_Y_LSB_BYTE, bmg160_data_t::datay, BMG160_DATA_FRAME_Y_MSB_BYTE, BMG160_DATA_FRAME_Z_LSB_BYTE, bmg160_data_t::dataz, BMG160_DATA_FRAME_Z_MSB_BYTE, bmg160_data_t::intstatus, BMG160_INTR0_STAT, BMG160_DATA_FRAME_INTR0_BYTE, BMG160_INTR1_STAT, BMG160_DATA_FRAME_INTR1_BYTE, BMG160_INTR2_STAT, BMG160_DATA_FRAME_INTR2_BYTE, BMG160_INTR3_STAT, BMG160_DATA_FRAME_INTR3_BYTE, BMG160_INTR4_STAT, BMG160_DATA_FRAME_INTR4_BYTE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_temp(s8 *v_temp_s8)
Reads Temperature from register location 0x08.
v_temp_s8 The value of temperature results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_TEMP_ADDR, BMG160_GEN_READ_WRITE_DATA_LENGTH.
BMG160_RETURN_FUNCTION_TYPE bmg160_read_register(u8 v_addr_u8, u8 *v_data_u8, u8 v_len_u8)
This API reads the data from the given register.
v_addr_u8 -> Address of the register v_data_u8 -> The data from the register v_len_u8 -> no of bytes to read results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr.
BMG160_RETURN_FUNCTION_TYPE bmg160_burst_read(u8 v_addr_u8, u8 *v_data_u8, u32 v_len_u32)
This API reads the data from the given register.
v_addr_u8 -> Address of the register v_data_u8 -> The data from the register v_len_u32 -> no of bytes to read results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr.
BMG160_RETURN_FUNCTION_TYPE bmg160_write_register(u8 v_addr_u8, u8 *v_data_u8, u8 v_len_u8)
This API write the data to the given register.
v_addr_u8 -> Address of the register v_data_u8 -> The data from the register v_len_u8 -> no of bytes to read results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr_stat_reg_zero(u8 *v_stat0_data_u8)
This api used to reads interrupt status of any motion and high rate in the register 0x09.
any motion bit -> 2 high rate bit -> 1 v_stat0_data_u8 : The interrupt status of any motion and high rate results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_STAT_ZERO__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr_stat_reg_one(u8 *v_stat1_data_u8)
This api used to reads the interrupt status of data, auto_offset, fast_offset and fifo_int in the register 0x0A.
data bit -> 7 auto_offset bit -> 6 fast_offset bit -> 5 fifo_int bit -> 4 v_stat1_data_u8 : The interrupt status of data, auto_offset, fast_offset and fifo_int results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_STAT_ONE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr_stat_reg_two(u8 *v_stat2_data_u8)
This api used to reads the interrupt status of.
any motion sign, any motion first_z, any motion first_x and any motion first_y in the register 0x0B any motion sign bit -> 3 any motion first_z bit -> 2 any motion first_x bit -> 1 any motion first_y bit -> 0 v_stat2_data_u8 : Pointer holding the the interrupt status of any motion sign, any motion first_z, any motion first_x and any motion first_y results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_STAT_TWO__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr_stat_reg_three(u8 *v_stat3_data_u8)
This api used to reads the interrupt status of high_rate sign, high_rate first_z, high_rate first_x and high_rate first_y in the register 0x0C.
high_rate sign bit -> 3 high_rate first_z bit -> 2 high_rate first_x bit -> 1 high_rate first_y bit -> 0 high_rate first_y bit -> 0 v_stat3_data_u8 : The interrupt status of high_rate sign, high_rate first_z, high_rate first_x and high_rate first_y results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_STAT_THREE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_range_reg(u8 *v_range_u8)
This API is used to get the range in the register 0x0F bits from 0 to 2.
v_range_u8 : The value of gyro range value range 0x00 BMG160_RANGE_2000 0x01 BMG160_RANGE_1000 0x02 BMG160_RANGE_500 0x03 BMG160_RANGE_250 0x04 BMG160_RANGE_125 results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_RANGE_ADDR_RANGE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
Referenced by Gyroscope_getRange.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_range_reg(u8 v_range_u8)
This API is used to set the range in the register 0x0F bits from 0 to 2.
v_range_u8 : The value of gyro range value range 0x00 BMG160_RANGE_2000 0x01 BMG160_RANGE_1000 0x02 BMG160_RANGE_500 0x03 BMG160_RANGE_250 0x04 BMG160_RANGE_125 results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_BIT_LENGTH_RANGE, bmg160_t::dev_addr, BMG160_RANGE_ADDR_RANGE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, E_BMG160_OUT_OF_RANGE.
Referenced by Gyroscope_setRange.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_bw(u8 *v_bw_u8)
This API is used to get the gyro bandwidth in the register 0x10 bits from 0 to 3.
v_bw_u8 The value of gyro bandwidth value bandwidth 0x00 BMG160_BW_500_HZ 0x01 BMG160_BW_230_HZ 0x02 BMG160_BW_116_HZ 0x03 BMG160_BW_47_HZ 0x04 BMG160_BW_23_HZ 0x05 BMG160_BW_12_HZ 0x06 BMG160_BW_64_HZ 0x07 BMG160_BW_32_HZ results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_BW_ADDR__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_BW_ADDR.
Referenced by bmg160_set_power_mode, Gyroscope_getBandwidth.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_bw(u8 v_bw_u8)
This API is used to set the gyro bandwidth in the register 0x10 bits from 0 to 3.
v_bw_u8 The value of gyro bandwidth value bandwidth 0x00 BMG160_BW_500_HZ 0x01 BMG160_BW_230_HZ 0x02 BMG160_BW_116_HZ 0x03 BMG160_BW_47_HZ 0x04 BMG160_BW_23_HZ 0x05 BMG160_BW_12_HZ 0x06 BMG160_BW_64_HZ 0x07 BMG160_BW_32_HZ results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_BIT_LENGTH_BW, bmg160_get_power_mode, BMG160_MODE_ADVANCEDPOWERSAVING, bmg160_get_auto_sleep_durn, bmg160_set_auto_sleep_durn, bmg160_t::dev_addr, BMG160_BW_ADDR__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_BW_ADDR, E_BMG160_OUT_OF_RANGE.
Referenced by Gyroscope_setBandwidth.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_pmu_ext_tri_select(u8 *v_pwu_ext_tri_select_u8)
This API used to get the status of External Trigger selection in the register 0x12h bits from 4 to 5.
v_pwu_ext_tri_select_u8 : The value of External Trigger selection v_pwu_ext_tri_select_u8 Trigger source 0x00 No 0x01 INT1 pin 0x02 INT2 pin 0x03 SDO pin(SPI3 mode) results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_MODE_LPM2_ADDR_EXT_TRI_SELECT__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_pmu_ext_tri_select(u8 v_pwu_ext_tri_select_u8)
This API used to set the status of External Trigger selection in the register 0x12h bits from 4 to 5.
v_pwu_ext_tri_select_u8 : The value of External Trigger selection v_pwu_ext_tri_select_u8 Trigger source 0x00 No 0x01 INT1 pin 0x02 INT2 pin 0x03 SDO pin(SPI3 mode) results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_MODE_LPM2_ADDR_EXT_TRI_SELECT__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_high_bw(u8 *v_high_bw_u8)
This API is used to get data high bandwidth in the register 0x13 bit 7.
v_high_bw_u8 : The value of high bandwidth value Description 1 unfiltered 0 filtered results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_HIGH_BW__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_high_bw(u8 v_high_bw_u8)
This API is used to set data high bandwidth in the register 0x13 bit 7.
v_high_bw_u8 : The value of high bandwidth value Description 1 unfiltered 0 filtered results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_BIT_LENGTH_HIGH_BW, bmg160_t::dev_addr, BMG160_HIGH_BW__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, E_BMG160_OUT_OF_RANGE.
Referenced by Gyroscope_setBandwidth.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_shadow_dis(u8 *v_shadow_dis_u8)
This API is used to get the shadow dis in the register 0x13 bit 6.
v_shadow_dis_u8 : The value of shadow dis value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_SHADOW_DIS__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_shadow_dis(u8 v_shadow_dis_u8)
This API is used to set the shadow dis in the register 0x13 bit 6.
v_shadow_dis_u8 : The value of shadow dis value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_BIT_LENGTH_SHADOW_DIS, bmg160_t::dev_addr, BMG160_SHADOW_DIS__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_soft_rst(void)
This function is used for the soft reset The soft reset register will be written with 0xB6 in the register 0x14.results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_SOFT_RESET, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_BGW_SOFT_RST_ADDR, BMG160_GEN_READ_WRITE_DATA_LENGTH.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_data_enable(u8 *v_data_enable_u8)
This API is used to get the data(data_enable) interrupt enable bits of the sensor in the registers 0x15 bit 7.
v_data_enable_u8 : The value of data enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_ENABLE0_DATA__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_data_enable(u8 v_data_enable_u8)
This API is used to set the data(data_enable) interrupt enable bits of the sensor in the registers 0x15 bit 7.
v_data_enable_u8 : The value of data enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_ENABLE0_DATA__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr_data(u8 v_axis_u8, u8 *v_intr_data_u8)
This API is used to get the data interrupt1 and interrupt2(int1_data and int2_data) in the register 0x18.
INT1 -> bit 0 INT2 -> bit 7 v_axis_u8 data interrupt selection v_axis_u8 Data interrupt 0 BMG160_INTR1_DATA 1 BMG160_INTR2_DATA v_intr_data_u8 The value of data interrupt1 or interrupt2 value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_INTR1_DATA, bmg160_t::dev_addr, BMG160_MAP_ONE_INTR1_DATA__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_INTR2_DATA, BMG160_MAP_ONE_INTR2_DATA__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_intr_data(u8 v_axis_u8, u8 v_intr_data_u8)
This API is used to set the data interrupt1 and interrupt2(int1_data and int2_data) in the register 0x18.
INT1 -> bit 0 INT2 -> bit 7 v_axis_u8 data interrupt selection v_axis_u8 Data interrupt 0 BMG160_INTR1_DATA 1 BMG160_INTR2_DATA v_intr_data_u8 The value of data interrupt1 or interrupt2 value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_INTR1_DATA, bmg160_t::dev_addr, BMG160_MAP_ONE_INTR1_DATA__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_INTR2_DATA, BMG160_MAP_ONE_INTR2_DATA__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_fifo_enable(u8 *v_fifo_enable_u8)
This API is used to get the fifo(fifo_enable) interrupt enable bits of the sensor in the registers 0x15 bit 6.
v_fifo_enable_u8 : The value of fifo enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_ENABLE0_FIFO__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_fifo_enable(u8 v_fifo_enable_u8)
This API is used to set the fifo(fifo_enable) interrupt enable bits of the sensor in the registers 0x15 bit 6.
v_fifo_enable_u8 : The value of fifo enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_BIT_LENGTH_FIFO, bmg160_t::dev_addr, BMG160_INTR_ENABLE0_FIFO__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_auto_offset_enable(u8 *v_offset_enable_u8)
This API is used to get the auto offset(auto_offset_enable) interrupt enable bits of the sensor in the registers 0x15 bit 3.
v_offset_enable_u8 : The value of offset enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_ENABLE0_AUTO_OFFSET__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_auto_offset_enable(u8 v_offset_enable_u8)
This API is used to set the auto offset(auto_offset_enable) interrupt enable bits of the sensor in the registers 0x15 bit 3.
v_offset_enable_u8 : The value of offset enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_ENABLE0_AUTO_OFFSET__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr_output_type(u8 v_param_u8, u8 *v_intr_output_type_u8)
This API is used to get the output type status in the register 0x16.
INT1 -> bit 1 INT2 -> bit 3 v_param_u8 The value of output type selection number v_param_u8output type 0 BMG160_INTR1 1 BMG160_INTR2 v_intr_output_type_u8 The value of output type value output 1 open drain 0 push pull results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_INTR1, bmg160_t::dev_addr, BMG160_INTR_ENABLE1_IT1_OUTPUT_TYPE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_INTR2, BMG160_INTR_ENABLE1_IT2_OUTPUT_TYPE__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_intr_output_type(u8 v_param_u8, u8 v_intr_output_type_u8)
This API is used to set the output type status in the register 0x16.
INT1 -> bit 1 INT2 -> bit 3 v_param_u8 The value of output type selection number v_param_u8output type 0 BMG160_INTR1 1 BMG160_INTR2 v_intr_output_type_u8 The value of output type value output 1 open drain 0 push pull results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_INTR1, bmg160_t::dev_addr, BMG160_INTR_ENABLE1_IT1_OUTPUT_TYPE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_INTR2, BMG160_INTR_ENABLE1_IT2_OUTPUT_TYPE__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr_level(u8 v_param_u8, u8 *v_intr_level_u8)
This API is used to get Active Level status in the register 0x16.
INT1 -> bit 0 INT2 -> bit 2 v_param_u8 The value of Active Level selection number v_param_u8Active Level 0 BMG160_INTR1 1 BMG160_INTR2 v_intr_level_u8 The value of Active Level status value value Active Level 1 Active HIGH 0 Active LOW results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_INTR1, bmg160_t::dev_addr, BMG160_INTR_ENABLE1_IT1_LEVEL__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_INTR2, BMG160_INTR_ENABLE1_IT2_LEVEL__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_intr_level(u8 v_param_u8, u8 v_intr_level_u8)
This API is used to set Active Level status in the register 0x16.
INT1 -> bit 0 INT2 -> bit 2 v_param_u8 The value of Active Level selection number v_param_u8Active Level 0 BMG160_INTR1 1 BMG160_INTR2 v_intr_level_u8 The value of Active Level status value value Active Level 1 Active HIGH 0 Active LOW results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_INTR1, bmg160_t::dev_addr, BMG160_INTR_ENABLE1_IT1_LEVEL__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_INTR2, BMG160_INTR_ENABLE1_IT2_LEVEL__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr1_highrate(u8 *v_intr1_u8)
This API is used to get the high rate(int1_high) interrupt1 enable bits of the sensor in the registers 0x17 bit 3.
v_intr1_u8 : The value of interrupt1 high_rate enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_MAP_ZERO_INTR1_HIGHRATE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_intr1_highrate(u8 v_intr1_u8)
This API is used to set the high rate(int1_high) interrupt1 enable bits of the sensor in the registers 0x17 bit 3.
v_intr1_u8 : The value of interrupt1 high_rate enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_MAP_ZERO_INTR1_HIGHRATE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr1_any_motion(u8 *v_int1r_any_motion_u8)
This API is used to get the any motion(int1_any) interrupt1 enable bits of the sensor in the registers 0x17 bit 1.
v_int1r_any_motion_u8 : The value of any motion interrupt1 value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_MAP_ZERO_INTR1_ANY_MOTION__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_intr1_any_motion(u8 v_int1r_any_motion_u8)
This API is used to set the any motion(int1_any) interrupt1 enable bits of the sensor in the registers 0x17 bit 1.
v_int1r_any_motion_u8 : The value of any motion interrupt1 value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_MAP_ZERO_INTR1_ANY_MOTION__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr2_offset(u8 v_axis_u8, u8 *v_intr2_offset_u8)
This API is used to get the fast offset(intr2_fast_offset) and auto offset(intr2_auto_offset) of interrupt2 in the register 0x18.
int2_fast_offset -> bit 6 int2_auto_offset -> bit 4 v_axis_u8 The value of fast/auto offset interrupts selection v_axis_u8 Data interrupt 1 BMG160_FAST_OFFSET 2 BMG160_AUTO_OFFSET v_intr2_offset_u8 The value of fast/auto offset enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_FAST_OFFSET, bmg160_t::dev_addr, BMG160_MAP_ONE_INTR2_FAST_OFFSET__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_AUTO_OFFSET, BMG160_MAP_ONE_INTR2_AUTO_OFFSET__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_intr2_offset(u8 v_axis_u8, u8 v_intr2_offset_u8)
This API is used to set the fast offset(intr2_fast_offset) and auto offset(intr2_auto_offset) of interrupt2 in the register 0x18.
int2_fast_offset -> bit 6 int2_auto_offset -> bit 4 v_axis_u8 The value of fast/auto offset interrupts selection v_axis_u8 Data interrupt 1 BMG160_FAST_OFFSET 2 BMG160_AUTO_OFFSET v_intr2_offset_u8 The value of fast/auto offset enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_FAST_OFFSET, bmg160_t::dev_addr, BMG160_MAP_ONE_INTR2_FAST_OFFSET__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_AUTO_OFFSET, BMG160_MAP_ONE_INTR2_AUTO_OFFSET__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr_offset(u8 v_axis_u8, u8 *v_intr1_offset_u8)
This API is used to get the fast offset(int1_fast_offset) and auto offset(int1_auto_offset) of interrupt1 in the register 0x18.
int1_fast_offset -> bit 1 int1_auto_offset -> bit 3 v_axis_u8 The value of fast/auto offset interrupts selection v_axis_u8 Data interrupt 1 BMG160_FAST_OFFSET 2 BMG160_AUTO_OFFSET v_intr1_offset_u8 The value of fast/auto offset value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_FAST_OFFSET, bmg160_t::dev_addr, BMG160_MAP_ONE_INTR1_FAST_OFFSET__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_AUTO_OFFSET, BMG160_MAP_ONE_INTR1_AUTO_OFFSET__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_intr1_offset(u8 v_axis_u8, u8 v_intr1_offset_u8)
This API is used to set the fast offset(int1_fast_offset) and auto offset(int1_auto_offset) of interrupt1 in the register 0x18.
int1_fast_offset -> bit 1 int1_auto_offset -> bit 3 v_axis_u8 The value of fast/auto offset interrupts selection v_axis_u8 Data interrupt 1 BMG160_FAST_OFFSET 2 BMG160_AUTO_OFFSET v_intr1_offset_u8 The value of fast/auto offset value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_FAST_OFFSET, bmg160_t::dev_addr, BMG160_MAP_ONE_INTR1_FAST_OFFSET__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_AUTO_OFFSET, BMG160_MAP_ONE_INTR1_AUTO_OFFSET__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr2_fifo(u8 *v_intr_fifo_u8)
This API is used to get the fifo(int2_fifo) interrupt2 enable bits of the sensor in the registers 0x18 bit 5.
v_intr_fifo_u8 : The interrupt2 fifo value value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_MAP_ONE_INTR2_FIFO__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr1_fifo(u8 *v_intr_fifo_u8)
This API is used to get the fifo(int1_fifo) interrupt1 enable bits of the sensor in the registers 0x18 bit 5.
v_intr_fifo_u8 : The interrupt1 fifo value value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_MAP_ONE_INTR1_FIFO__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_intr_fifo(u8 v_axis_u8, u8 v_intr_fifo_u8)
This API is used to set the value of the fifo interrupt1 and interrupt2(int1_fifo and int2_fifo) in the register 0x18.
int1_fifo -> bit 2 int2_fifo -> bit 5 v_axis_u8 The value of fifo interrupts selection v_axis_u8 fifo interrupt 0 BMG160_INTR1 1 BMG160_INTR2 v_intr_fifo_u8 the value of int1_fifo/int2_fifo enable/disable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_INTR1, bmg160_t::dev_addr, BMG160_MAP_ONE_INTR1_FIFO__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_INTR2, BMG160_MAP_ONE_INTR2_FIFO__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr2_highrate(u8 *v_intr2_highrate_u8)
This API is used to get the high rate(int2_high_rate) interrupt2 enable bits of the sensor in the registers 0x19 bit 3.
v_intr2_highrate_u8 : The interrupt2 high_rate value value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_MAP_TWO_INTR2_HIGHRATE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_intr2_highrate(u8 v_intr2_highrate_u8)
This API is used to set the high rate(int2_high_rate) interrupt2 enable bits of the sensor in the registers 0x19 bit 3.
v_intr2_highrate_u8 : The interrupt2 high_rate value value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_MAP_TWO_INTR2_HIGHRATE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_intr2_any_motion(u8 *v_intr2_any_motion_u8)
This API is used to get the any motion(int2_any_motion) interrupt2 enable bits of the sensor in the registers 0x19 bit 1.
v_intr2_any_motion_u8 : The value of interrupt2 any_motion value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_MAP_TWO_INTR2_ANY_MOTION__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_intr2_any_motion(u8 v_intr2_any_motion_u8)
This API is used to set the any motion(int2_any_motion) interrupt2 enable bits of the sensor in the registers 0x19 bit 1.
v_intr2_any_motion_u8 : The value of interrupt2 any_motion value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_MAP_TWO_INTR2_ANY_MOTION__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_offset_unfilt(u8 v_param_u8, u8 *v_offset_unfilt_u8)
This API is used to get the slow offset and fast offset unfilt data in the register 0x1A and 1B.
slow_offset_unfilt -> 0x1A bit 5 fast_offset_unfilt -> 0x1B bit 7 v_param_u8 The value of fast/slow offset unfilt data selection v_param_u8 offset selection 0 BMG160_SLOW_OFFSET 1 BMG160_FAST_OFFSET v_offset_unfilt_u8 The value of fast/slow offset unfilt data value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_SLOW_OFFSET, bmg160_t::dev_addr, BMG160_INTR_ZERO_ADDR_SLOW_OFFSET_UNFILT__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_FAST_OFFSET, BMG160_INTR_ONE_ADDR_FAST_OFFSET_UNFILT__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_offset_unfilt(u8 v_param_u8, u8 v_offset_unfilt_u8)
This API is used to set the slow offset and fast offset unfilt data in the register 0x1A and 1B.
slow_offset_unfilt -> 0x1A bit 5 fast_offset_unfilt -> 0x1B bit 7 v_param_u8 The value of fast/slow offset unfilt data selection v_param_u8 offset selection 0 BMG160_SLOW_OFFSET 1 BMG160_FAST_OFFSET v_offset_unfilt_u8 The value of fast/slow offset unfilt data value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_SLOW_OFFSET, bmg160_t::dev_addr, BMG160_INTR_ZERO_ADDR_SLOW_OFFSET_UNFILT__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_FAST_OFFSET, BMG160_INTR_ONE_ADDR_FAST_OFFSET_UNFILT__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_unfilt_data(u8 v_param_u8, u8 *v_unfilt_data_u8)
This API is used to get the any motion and high rate unfilt data in the register 0x1A.
any_unfilt_data -> bit 1 high_unfilt_data -> bit 3 v_param_u8 The value of any/high offset unfilt data selection v_param_u8 offset selection 1 BMG160_HIGHRATE_UNFILT_DATA 3 BMG160_ANY_MOTION_UNFILT_DATA v_unfilt_data_u8 The value of any/high unfilt data value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_HIGHRATE_UNFILT_DATA, bmg160_t::dev_addr, BMG160_INTR_ZERO_ADDR_HIGHRATE_UNFILT_DATA__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_ANY_MOTION_UNFILT_DATA, BMG160_INTR_ZERO_ADDR_ANY_MOTION_UNFILT_DATA__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_unfilt_data(u8 v_param_u8, u8 v_unfilt_data_u8)
This API is used to set the any motion and high rate unfilt data in the register 0x1A.
any_unfilt_data -> bit 1 high_unfilt_data -> bit 3 v_param_u8 The value of any/high offset unfilt data selection v_param_u8 offset selection 1 BMG160_HIGHRATE_UNFILT_DATA 3 BMG160_ANY_MOTION_UNFILT_DATA v_unfilt_data_u8 The value of any/high unfilt data value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_HIGHRATE_UNFILT_DATA, bmg160_t::dev_addr, BMG160_INTR_ZERO_ADDR_HIGHRATE_UNFILT_DATA__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_ANY_MOTION_UNFILT_DATA, BMG160_INTR_ZERO_ADDR_ANY_MOTION_UNFILT_DATA__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_any_motion_thres(u8 *v_any_motion_thres_u8)
This API is used to get Any motion Threshold in the register 0x1B bit from 0 to 6.
v_any_motion_thres_u8 : The value of any_motion Threshold Any motion threshold can be calculate using ((1+ v_any_motion_thres_u8)*16LSB) results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_ONE_ADDR_ANY_MOTION_THRES__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_any_motion_thres(u8 v_any_motion_thres_u8)
This API is used to set Any motion Threshold in the register 0x1B bit from 0 to 6.
v_any_motion_thres_u8 : The value of any_motion Threshold Any motion threshold can be calculate using ((1+ v_any_motion_thres_u8)*16LSB) results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_ONE_ADDR_ANY_MOTION_THRES__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_awake_durn(u8 *v_awake_durn_u8)
This API is used to get the awake Duration in the register 0x1C bit 6 and 7.
v_awake_durn_u8 : The value of awake Duration value Duration 0x00 8 samples 0x01 16 samples 0x02 32 samples 0x03 64 samples results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_TWO_ADDR_AWAKE_DURN__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_awake_durn(u8 v_awake_durn_u8)
This API is used to set the awake Duration in the register 0x1C bit 6 and 7.
v_awake_durn_u8 : The value of awake Duration value Duration 0x00 8 samples 0x01 16 samples 0x02 32 samples 0x03 64 samples results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_TWO_ADDR_AWAKE_DURN__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_any_motion_durn_sample(u8 *v_durn_sample_u8)
This API is used to get the any motion Duration samples in the register 0x1C bit 4 and 5.
v_durn_sample_u8 : The value of any motion duration samples value Samples 0x00 4 samples 0x01 8 samples 0x02 12 samples 0x03 16 samples results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_TWO_ADDR_ANY_MOTION_DURN_SAMPLE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_any_motion_durn_sample(u8 v_durn_sample_u8)
This API is used to set the any motion Duration samples in the register 0x1C bit 4 and 5.
v_durn_sample_u8 : The value of any motion duration samples value Samples 0x00 4 samples 0x01 8 samples 0x02 12 samples 0x03 16 samples results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_TWO_ADDR_ANY_MOTION_DURN_SAMPLE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_any_motion_enable_axis(u8 v_channel_u8, u8 *v_any_motion_axis_u8)
This API is used to get the status of Any motion interrupt axis(X,Y,Z) enable channel.
BMG160_X_AXIS -> bit 0 BMG160_Y_AXIS -> bit 1 BMG160_Z_AXIS -> bit 2 v_channel_u8 : The value of Any Enable channel number v_channel_u8 axis 0 BMG160_X_AXIS 1 BMG160_Y_AXIS 2 BMG160_Z_AXIS v_any_motion_axis_u8 The value of Any motion axis enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error BMG160_X_AXIS -> bit 0 BMG160_Y_AXIS -> bit 1 BMG160_Z_AXIS -> bit 2 v_channel_u8 : The value of Any Enable channel number v_channel_u8 axis 0 BMG160_X_AXIS 1 BMG160_Y_AXIS 2 BMG160_Z_AXIS v_data_u8 The value of Any motion axis enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_INTR_TWO_ADDR_ANY_MOTION_ENABLE_X__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_Y_AXIS, BMG160_INTR_TWO_ADDR_ANY_MOTION_ENABLE_Y__REG, BMG160_Z_AXIS, BMG160_INTR_TWO_ADDR_ANY_MOTION_ENABLE_Z__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_any_motion_enable_axis(u8 v_channel_u8, u8 v_any_motion_axis_u8)
This API is used to set the status of Any motion interrupt axis(X,Y,Z) enable channel.
BMG160_X_AXIS -> bit 0 BMG160_Y_AXIS -> bit 1 BMG160_Z_AXIS -> bit 2 v_channel_u8 : The value of Any Enable channel number v_channel_u8 axis 0 BMG160_X_AXIS 1 BMG160_Y_AXIS 2 BMG160_Z_AXIS v_any_motion_axis_u8 The value of Any motion axis enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_INTR_TWO_ADDR_ANY_MOTION_ENABLE_X__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_Y_AXIS, BMG160_INTR_TWO_ADDR_ANY_MOTION_ENABLE_Y__REG, BMG160_Z_AXIS, BMG160_INTR_TWO_ADDR_ANY_MOTION_ENABLE_Z__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_fifo_wm_enable(u8 *v_fifo_wm_enable_u8)
This API is used to get the status of fifo water mark in the register 0x1E bit 7.
v_fifo_wm_enable_u8 : The value of fifo water mark enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_INTR_4_FIFO_WM_ENABLE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_fifo_wm_enable(u8 v_fifo_wm_enable_u8)
This API is used to set the status of fifo water mark in the register 0x1E bit 7.
v_fifo_wm_enable_u8 : The value of fifo water mark enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_BIT_LENGTH_FIFO_WM, bmg160_t::dev_addr, BMG160_INTR_4_FIFO_WM_ENABLE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_fifo_tag(u8 *v_fifo_tag_u8)
This API is used to get the status of FIFO tag in the register 0x3D bit 7.
v_fifo_tag_u8 : The value of fifo tag enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_FIFO_CGF1_ADDR_TAG__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_fifo_tag(u8 v_fifo_tag_u8)
This API is used to set the status of FIFO tag in the register 0x3D bit 7.
v_fifo_tag_u8 : The value of fifo tag enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_BIT_LENGTH_FIFO_TAG, bmg160_t::dev_addr, BMG160_FIFO_CGF1_ADDR_TAG__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_fifo_wm_level(u8 *v_fifo_wm_level_u8)
This API is used to get Water Mark Level in the register 0x3D bit from 0 to 6.
v_fifo_wm_level_u8 : The value of fifo water mark level results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_FIFO_CGF1_ADDR_WML__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_fifo_wm_level(u8 v_fifo_wm_level_u8)
This API is used to set Water Mark Level in the register 0x3D bit from 0 to 6.
v_fifo_wm_level_u8 : The value of fifo water mark level results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_FIFO_WM_LENGTH, bmg160_t::dev_addr, BMG160_FIFO_CGF1_ADDR_WML__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_rst_intr(u8 v_rst_int_u8)
This API is used to set the Interrupt Reset in the register 0x21 bit 7.
v_rst_int_u8 the value of reset interrupt results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_RST_LATCH_ADDR_RST_INTR__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_offset_rst(u8 v_offset_rst_u8)
This API is used to set the offset Reset in the register 0x21 bit 6.
v_offset_rst_u8 the value of reset offset results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_RST_LATCH_ADDR_OFFSET_RST__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_latch_stat(u8 *v_latch_stat_u8)
This API is used to get the Latch Status in the register 0x21 bit 4.
v_latch_stat_u8 : The value of latch status value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_RST_LATCH_ADDR_LATCH_STAT__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_latch_stat(u8 v_latch_stat_u8)
This API is used to set the Latch Status in the register 0x21 bit 4.
v_latch_stat_u8 : The value of latch status value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_RST_LATCH_ADDR_LATCH_STAT__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_latch_intr(u8 *v_latch_intr_u8)
This API is used to get the Latch interrupt in the register 0x21 bit from 0 to 3.
v_latch_intr_u8 : The value of latch interrupt Latch Interrupt Value BMG160_NON_LATCH 0x00 BMG160_LATCH_250_MS 0x01 BMG160_LATCH_500_MS 0x02 BMG160_LATCH_1_SEC 0x03 BMG160_LATCH_2_SEC 0x04 BMG160_LATCH_4_SEC 0x05 BMG160_LATCH_8_SEC 0x06 BMG160_LATCH_LATCHED 0x07 BMG160_LATCH_NON_LATCHED 0x08 BMG160_LATCH_250_MICRO_SEC 0x09 BMG160_LATCH_500_MICRO_SEC 0x0A BMG160_LATCH_1_MILLI_SEC 0x0B BMG160_LATCH_12.5_MILLI_SEC 0x0C BMG160_LATCH_25_MILLI_SEC 0x0D BMG160_LATCH_50_MILLI_SEC 0x0E BMG160_LATCH_LATCHED 0x0F results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_RST_LATCH_ADDR_LATCH_INTR__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_latch_intr(u8 v_latch_intr_u8)
This API is used to set the Latch interrupt in the register 0x21 bit from 0 to 3.
v_latch_intr_u8 : The value of latch interrupt Latch Interrupt Value BMG160_NON_LATCH 0x00 BMG160_LATCH_250_MS 0x01 BMG160_LATCH_500_MS 0x02 BMG160_LATCH_1_SEC 0x03 BMG160_LATCH_2_SEC 0x04 BMG160_LATCH_4_SEC 0x05 BMG160_LATCH_8_SEC 0x06 BMG160_LATCH_LATCHED 0x07 BMG160_LATCH_NON_LATCHED 0x08 BMG160_LATCH_250_MICRO_SEC 0x09 BMG160_LATCH_500_MICRO_SEC 0x0A BMG160_LATCH_1_MILLI_SEC 0x0B BMG160_LATCH_12.5_MILLI_SEC 0x0C BMG160_LATCH_25_MILLI_SEC 0x0D BMG160_LATCH_50_MILLI_SEC 0x0E BMG160_LATCH_LATCHED 0x0F results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_RST_LATCH_ADDR_LATCH_INTR__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_highrate_hyst(u8 v_channel_u8, u8 *v_highrate_hyst_u8)
This API is used to get the status of High Hysteresis of X,Y,Z axis in the registers 0x22,0x24 and 0x26.
X_AXIS - 0x22 bit 6 and 7 Y_AXIS - 0x24 bit 6 and 7 Z_AXIS - 0x26 bit 6 and 7 v_channel_u8 The value of high Hysteresis channel number v_channel_u8 value BMG160_X_AXIS 0 BMG160_Y_AXIS 1 BMG160_Z_AXIS 2 v_highrate_hyst_u8 The value of high Hysteresis High hysteresis can be calculated by High_hyst = ((255+256 *v_highrate_hyst_u8) * 4LSB) results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_HIGHRATE_HYST_X__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_Y_AXIS, BMG160_HIGHRATE_HYST_Y__REG, BMG160_Z_AXIS, BMG160_HIGHRATE_HYST_Z__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_highrate_hyst(u8 v_channel_u8, u8 v_highrate_hyst_u8)
This API is used to set the status of High Hysteresis of X,Y,Z axis in the registers 0x22,0x24 and 0x26.
X_AXIS - 0x22 bit 6 and 7 Y_AXIS - 0x24 bit 6 and 7 Z_AXIS - 0x26 bit 6 and 7 v_channel_u8 The value of high Hysteresis channel number v_channel_u8 value BMG160_X_AXIS 0 BMG160_Y_AXIS 1 BMG160_Z_AXIS 2 v_highrate_hyst_u8 The value of high Hysteresis High hysteresis can be calculated by High_hyst = ((255+256 *v_highrate_hyst_u8) * 4LSB) results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_HIGHRATE_HYST_X__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_Y_AXIS, BMG160_HIGHRATE_HYST_Y__REG, BMG160_Z_AXIS, BMG160_HIGHRATE_HYST_Z__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_highrate_thres(u8 v_channel_u8, u8 *v_highrate_thres_u8)
This API is used to get the value of High rate Threshold of X,Y,Z axis in the registers 0x22, 0x24 and 0x26.
X_AXIS - 0x22 bit from 1 to 5 Y_AXIS - 0x24 bit from 1 to 5 Z_AXIS - 0x26 bit from 1 to 5 v_channel_u8 : The value of high threshold channel number v_channel_u8 value BMG160_X_AXIS 0 BMG160_Y_AXIS 1 BMG160_Z_AXIS 2 v_highrate_thres_u8 the high threshold value High Threshold can be calculated by High_thres = ((255+256 *v_highrate_thres_u8) * 4LSB) results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_HIGHRATE_THRES_X__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_Y_AXIS, BMG160_HIGHRATE_THRES_Y__REG, BMG160_Z_AXIS, BMG160_HIGHRATE_THRES_Z__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_highrate_thres(u8 v_channel_u8, u8 v_highrate_thres_u8)
This API is used to set the value of High rate Threshold of X,Y,Z axis in the registers 0x22, 0x24 and 0x26.
X_AXIS - 0x22 bit from 1 to 5 Y_AXIS - 0x24 bit from 1 to 5 Z_AXIS - 0x26 bit from 1 to 5 v_channel_u8 : The value of high threshold channel number v_channel_u8 value BMG160_X_AXIS 0 BMG160_Y_AXIS 1 BMG160_Z_AXIS 2 v_highrate_thres_u8 the high threshold value High Threshold can be calculated by High_thres = ((255+256 *v_highrate_thres_u8) * 4LSB) results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_HIGHRATE_THRES_X__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_Y_AXIS, BMG160_HIGHRATE_THRES_Y__REG, BMG160_Z_AXIS, BMG160_HIGHRATE_THRES_Z__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_highrate_enable_axis(u8 v_channel_u8, u8 *v_enable_u8)
This API is used to get the status of High Enable Channel X,Y,Z in the registers 0x22, 0x24 and 0x26.
X_AXIS - 0x22 bit 0 Y_AXIS - 0x24 bit 0 Z_AXIS - 0x26 bit 0 v_channel_u8 : The value of high enable channel number v_channel_u8 value BMG160_X_AXIS 0 BMG160_Y_AXIS 1 BMG160_Z_AXIS 2 v_enable_u8 The value of high axis enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_HIGHRATE_ENABLE_X__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_Y_AXIS, BMG160_HIGHRATE_ENABLE_Y__REG, BMG160_Z_AXIS, BMG160_HIGHRATE_ENABLE_Z__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_highrate_enable_axis(u8 v_channel_u8, u8 v_enable_u8)
This API is used to set the status of High Enable Channel X,Y,Z in the registers 0x22, 0x24 and 0x26.
X_AXIS - 0x22 bit 0 Y_AXIS - 0x24 bit 0 Z_AXIS - 0x26 bit 0 v_channel_u8 : The value of high enable channel number v_channel_u8 value BMG160_X_AXIS 0 BMG160_Y_AXIS 1 BMG160_Z_AXIS 2 v_enable_u8 The value of high axis enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_HIGHRATE_ENABLE_X__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_Y_AXIS, BMG160_HIGHRATE_ENABLE_Y__REG, BMG160_Z_AXIS, BMG160_HIGHRATE_ENABLE_Z__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_highrate_durn_axis(u8 v_channel_u8, u8 *v_highrate_durn_axis_u8)
This API is used to get the status of High duration of X,Y,Z axis in the registers 0x23, 0x25 and 0x27.
X_AXIS - 0x23 bit form 0 to 7 Y_AXIS - 0x25 bit form 0 to 7 Z_AXIS - 0x27 bit form 0 to 7 v_channel_u8 The value of High Duration channel number v_channel_u8 value BMG160_X_AXIS 0 BMG160_Y_AXIS 1 BMG160_Z_AXIS 2 v_highrate_durn_axis_u8 The value of high duration High rate duration can be calculated by using the formula High_durn = ((1+v_highrate_durn_axis_u8)*2.5ms) results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_HIGHRATE_DURN_X_ADDR, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_Y_AXIS, BMG160_HIGHRATE_THRES_Y_ADDR, BMG160_Z_AXIS, BMG160_HIGHRATE_THRES_Z_ADDR, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_highrate_durn_axis(u8 v_channel_u8, u8 v_highrate_durn_axis_u8)
This API is used to set the value of High duration of X,Y,Z axis in the registers 0x23, 0x25 and 0x27.
X_AXIS - 0x23 bit form 0 to 7 Y_AXIS - 0x25 bit form 0 to 7 Z_AXIS - 0x27 bit form 0 to 7 v_channel_u8 The value of High Duration channel number v_channel_u8 value BMG160_X_AXIS 0 BMG160_Y_AXIS 1 BMG160_Z_AXIS 2 v_highrate_durn_axis_u8 The value of high duration High rate duration can be calculated by using the formula High_durn = ((1+v_highrate_durn_axis_u8)*2.5ms) results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_HIGHRATE_THRES_X_ADDR, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_Y_AXIS, BMG160_HIGHRATE_THRES_Y_ADDR, BMG160_Z_AXIS, BMG160_HIGHRATE_THRES_Z_ADDR, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_slow_offset_thres(u8 *v_offset_thres_u8)
This API is used to get Slow Offset Threshold status in the register 0x31 bit 6 and 7.
v_offset_thres_u8 : The value of slow offset Threshold value threshold 0x00 0.1 degree/sec 0x01 0.2 degree/sec 0x02 0.5 degree/sec 0x03 1 degree/sec results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_SLOW_OFFSET_THRES__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_slow_offset_thres(u8 v_offset_thres_u8)
This API is used to set Slow Offset Threshold status in the register 0x31 bit 6 and 7.
v_offset_thres_u8 : The value of slow offset Threshold value threshold 0x00 0.1 degree/sec 0x01 0.2 degree/sec 0x02 0.5 degree/sec 0x03 1 degree/sec results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_SLOW_OFFSET_THRES__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_slow_offset_durn(u8 *v_offset_durn_u8)
This API is used to get Slow Offset duration status in the register 0x31 bit 4,5 and 6.
v_offset_durn_u8 : The value of Slow Offset duration value Duration 0x00 40ms 0x01 80ms 0x02 160ms 0x03 320ms 0x04 640ms 0x05 1280ms 0x06 unused 0x07 unused results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_SLOW_OFFSET_DURN__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_slow_offset_durn(u8 v_offset_durn_u8)
This API is used to set Slow Offset duration status in the register 0x31 bit 4,5 and 6.
v_offset_durn_u8 : The value of Slow Offset duration value Duration 0x00 40ms 0x01 80ms 0x02 160ms 0x03 320ms 0x04 640ms 0x05 1280ms 0x06 unused 0x07 unused results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_SLOW_OFFSET_DURN__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_slow_offset_enable_axis(u8 v_channel_u8, u8 *v_slow_offset_u8)
This API is used to get Slow Offset Enable channel X,Y,Z in the register 0x31.
X_AXIS -> bit 0 Y_AXIS -> bit 1 Z_AXIS -> bit 2 v_channel_u8 The value of slow offset channel number v_channel_u8 value BMG160_X_AXIS 0 BMG160_Y_AXIS 1 BMG160_Z_AXIS 2 v_slow_offset_u8 The slow offset value value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_SLOW_OFFSET_ENABLE_X__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_Y_AXIS, BMG160_SLOW_OFFSET_ENABLE_Y__REG, BMG160_Z_AXIS, BMG160_SLOW_OFFSET_ENABLE_Z__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_slow_offset_enable_axis(u8 v_channel_u8, u8 v_slow_offset_u8)
This API is used to set Slow Offset Enable channel X,Y,Z in the register 0x31.
X_AXIS -> bit 0 Y_AXIS -> bit 1 Z_AXIS -> bit 2 v_channel_u8 The value of slow offset channel number v_channel_u8 value BMG160_X_AXIS 0 BMG160_Y_AXIS 1 BMG160_Z_AXIS 2 v_slow_offset_u8 The slow offset value value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_SLOW_OFFSET_ENABLE_X__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_Y_AXIS, BMG160_SLOW_OFFSET_ENABLE_Y__REG, BMG160_Z_AXIS, BMG160_SLOW_OFFSET_ENABLE_Z__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_offset_word_length(u8 v_channel_u8, u8 *v_offset_word_length_u8)
This API is used to get Fast Offset WordLength and Auto Offset WordLength in the register 0x32.
fast_offset_wordlength -> bit 4 and 5 auto_offset_wordlength -> bit 6 and 7 v_channel_u8 The value of WordLengthchannel number v_channel_u8 value BMG160_AUTO_OFFSET_WL 0 BMG160_FAST_OFFSET_WL 1 v_offset_word_length_u8 The value of offset word length value word length 0x00 32 samples 0x01 64 samples 0x02 128 samples 0x03 256 samples results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_AUTO_OFFSET_WORD_LENGHTH, bmg160_t::dev_addr, BMG160_AUTO_OFFSET_WORD_LENGHTH__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_FAST_OFFSET_WORD_LENGHTH, BMG160_FAST_OFFSET_WORD_LENGHTH__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_offset_word_length(u8 v_channel_u8, u8 v_offset_word_length_u8)
This API is used to set Fast Offset WordLength and Auto Offset WordLength in the register 0x32.
fast_offset_wordlength -> bit 4 and 5 auto_offset_wordlength -> bit 6 and 7 v_channel_u8 The value of WordLengthchannel number v_channel_u8 value BMG160_AUTO_OFFSET_WL 0 BMG160_FAST_OFFSET_WL 1 v_offset_word_length_u8 The value of offset word length value word length 0x00 32 samples 0x01 64 samples 0x02 128 samples 0x03 256 samples results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_AUTO_OFFSET_WORD_LENGHTH, bmg160_t::dev_addr, BMG160_AUTO_OFFSET_WORD_LENGHTH__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_FAST_OFFSET_WORD_LENGHTH, BMG160_FAST_OFFSET_WORD_LENGHTH__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_enable_fast_offset(void)
This API is used to enable fast offset in the register 0x32 bit 3 it is a write only register.
results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_FAST_OFFSET_ENABLE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_fast_offset_enable_axis(u8 *v_fast_offset_u8)
This API read the Fast offset enable v_axis_u8(X,Y and Z) in the register 0x32.
X_AXIS -> bit 0 Y_AXIS -> bit 1 Z_AXIS -> bit 2 v_fast_offset_u8 The value of fast offset enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_FAST_OFFSET_ENABLE_XYZ__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_fast_offset_enable_axis(u8 v_channel_u8, u8 v_fast_offset_u8)
This API set the Fast offset enable v_axis_u8(X,Y and Z) in the register 0x32.
X_AXIS -> bit 0 Y_AXIS -> bit 1 Z_AXIS -> bit 2 v_channel_u8 The value of fast offset channel select v_channel_u8 value BMG160_X_AXIS 0 BMG160_Y_AXIS 1 BMG160_Z_AXIS 2 v_fast_offset_u8 The value of fast offset enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_FAST_OFFSET_ENABLE_X__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_Y_AXIS, BMG160_FAST_OFFSET_ENABLE_Y__REG, BMG160_Z_AXIS, BMG160_FAST_OFFSET_ENABLE_Z__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_nvm_remain(u8 *v_nvm_remain_u8)
This API is used to get the status of nvm program remain in the register 0x33 bit from 4 to 7.
v_nvm_remain_u8 The value of nvm program value Description 1 Do not trigger 0 Trigger results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_TRIM_NVM_CTRL_ADDR_NVM_REMAIN__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_nvm_load(u8 v_nvm_load_u8)
This API is used to set the status of nvm program remain in the register 0x33 bit from 4 to 7.
v_nvm_load_u8 The value of nvm program value Description 1 Do not trigger 0 Trigger results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_TRIM_NVM_CTRL_ADDR_NVM_LOAD__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_nvm_rdy(u8 *v_nvm_rdy_u8)
This API is used to get the status of nvm program in the register 0x33 bit 2.
v_nvm_rdy_u8 The value of nvm program value Description 1 NVM write is in progress 0 NVM is ready to accept a new write results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_TRIM_NVM_CTRL_ADDR_NVM_RDY__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_nvm_prog_trig(u8 nvm_prog_trig)
This API is used to set the status of nvm ready in the register 0x33 bit 1.
nvm_prog_trig The value of nvm program value Description 1 program seq in progress 0 program seq finished results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_TRIM_NVM_CTRL_ADDR_NVM_PROG_TRIG__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_nvm_prog_mode(u8 *nvm_prog_mode)
This API is used to get the status of nvm program mode in the register 0x33 bit 0.
nvm_prog_mode The value of nvm program mode value Description 1 Unlock 0 Lock nvm write results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_TRIM_NVM_CTRL_ADDR_NVM_PROG_MODE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_nvm_prog_mode(u8 nvm_prog_mode)
This API is used to set the status of nvm program mode in the register 0x33 bit 0.
nvm_prog_mode The value of nvm program mode value Description 1 Unlock 0 Lock nvm write results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_TRIM_NVM_CTRL_ADDR_NVM_PROG_MODE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_i2c_wdt(u8 v_channel_u8, u8 *v_i2c_wdt_u8)
This API is used to get the status of i2c wdt select and enable in the register 0x34.
i2c_wdt_select -> bit 1 i2c_wdt_enable -> bit 2 v_channel_u8 The value of i2c wdt channel number v_channel_u8 value BMG160_I2C_WDT_ENABLE 1 BMG160_I2C_WDT_SELECT 0 v_i2c_wdt_u8 The value of I2C enable and WDT select value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_I2C_WDT_ENABLE, bmg160_t::dev_addr, BMG160_BGW_SPI3_WDT_ADDR_I2C_WDT_ENABLE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_I2C_WDT_SELECT, BMG160_BGW_SPI3_WDT_ADDR_I2C_WDT_SELECT__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_i2c_wdt(u8 v_channel_u8, u8 v_i2c_wdt_u8)
This API is used to set the status of i2c wdt select and enable in the register 0x34.
i2c_wdt_select -> bit 1 i2c_wdt_enable -> bit 2 v_channel_u8 The value of i2c wdt channel number v_channel_u8 value BMG160_I2C_WDT_ENABLE 1 BMG160_I2C_WDT_SELECT 0 v_i2c_wdt_u8 The value of I2C enable and WDT select value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_I2C_WDT_ENABLE, bmg160_t::dev_addr, BMG160_BGW_SPI3_WDT_ADDR_I2C_WDT_ENABLE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_I2C_WDT_SELECT, BMG160_BGW_SPI3_WDT_ADDR_I2C_WDT_SELECT__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_spi3(u8 *v_spi3_u8)
This API is used to get the status of spi3 in the register 0x34 bit 0.
v_spi3_u8 : The value of spi3 enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_BGW_SPI3_WDT_ADDR_SPI3__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_spi3(u8 v_spi3_u8)
This API is used to set the status of spi3 in the register 0x34 bit 0.
v_spi3_u8 : The value of spi3 enable value Description 1 BMG160_ENABLE 0 BMG160_DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_BGW_SPI3_WDT_ADDR_SPI3__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_offset(u8 v_axis_u8, s16 *v_offset_s16)
This API is used to get the value of offset X, Y and Z in the registers 0x36, 0x37, 0x38, 0x39 and 0x3A the offset is a 12bit value.
X_AXIS -> bit 0 and 1 is available in the register 0x3A bit 2 and 3 bit 2 and 3 is available in the register 0x36 bit 6 and 7 bit 4 to 11 is available in the register 0x37 bit 0 to 7 Y_AXIS -> bit 0 is available in the register 0x3A bit 1 bit 1,2 and 3 is available in the register 0x36 bit 3,4 and 5 bit 4 to 11 is available in the register 0x38 bit 0 to 7 Z_AXIS -> bit 0 is available in the register 0x3A bit 0 bit 1,2 and 3 is available in the register 0x36 bit 0,1 and 3 bit 4 to 11 is available in the register 0x39 bit 0 to 7 v_axis_u8 : The value of offset axis selection v_axis_u8 value BMG160_X_AXIS 1 BMG160_Y_AXIS 0 BMG160_Z_AXIS 0 v_offset_s16 The value of offset results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, bmg160_t::dev_addr, BMG160_TRIM_GP0_ADDR_OFFSET_X__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_OFC1_ADDR_OFFSET_X__REG, BMG160_SHIFT_BIT_POSITION_BY_02_BITS, BMG160_OFC2_ADDR, BMG160_SHIFT_BIT_POSITION_BY_04_BITS, BMG160_Y_AXIS, BMG160_TRIM_GP0_ADDR_OFFSET_Y__REG, BMG160_OFC1_ADDR_OFFSET_Y__REG, BMG160_SHIFT_BIT_POSITION_BY_01_BIT, BMG160_OFC3_ADDR, BMG160_Z_AXIS, BMG160_TRIM_GP0_ADDR_OFFSET_Z__REG, BMG160_OFC1_ADDR_OFFSET_Z__REG, BMG160_OFC4_ADDR, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_offset(u8 v_axis_u8, s16 v_offset_s16)
This API is used to set the value of offset X, Y and Z in the registers 0x36, 0x37, 0x38, 0x39 and 0x3A the offset is a 12bit value.
X_AXIS -> bit 0 and 1 is available in the register 0x3A bit 2 and 3 bit 2 and 3 is available in the register 0x36 bit 6 and 7 bit 4 to 11 is available in the register 0x37 bit 0 to 7 Y_AXIS -> bit 0 is available in the register 0x3A bit 1 bit 1,2 and 3 is available in the register 0x36 bit 3,4 and 5 bit 4 to 11 is available in the register 0x38 bit 0 to 7 Z_AXIS -> bit 0 is available in the register 0x3A bit 0 bit 1,2 and 3 is available in the register 0x36 bit 0,1 and 3 bit 4 to 11 is available in the register 0x39 bit 0 to 7 v_axis_u8 : The value of offset axis selection v_axis_u8 value BMG160_X_AXIS 1 BMG160_Y_AXIS 0 BMG160_Z_AXIS 0 v_offset_s16 The value of offset results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_X_AXIS, BMG160_OFFSET_MASK_BYTE_OF_DATA, BMG160_SHIFT_BIT_POSITION_BY_04_BITS, bmg160_t::dev_addr, BMG160_OFC2_ADDR, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_OFFSET_X_BIT_MASK1, BMG160_SET_BITSLICE, BMG160_OFC1_ADDR_OFFSET_X__REG, BMG160_OFFSET_X_BIT_MASK2, BMG160_TRIM_GP0_ADDR_OFFSET_X__REG, BMG160_Y_AXIS, BMG160_OFC3_ADDR, BMG160_OFFSET_Y_Z_BIT_MASK2, BMG160_OFC1_ADDR_OFFSET_Y__REG, BMG160_OFFSET_Y_Z_BIT_MASK1, BMG160_TRIM_GP0_ADDR_OFFSET_Y__REG, BMG160_Z_AXIS, BMG160_OFC4_ADDR, BMG160_OFC1_ADDR_OFFSET_Z__REG, BMG160_TRIM_GP0_ADDR_OFFSET_Z__REG, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_gp(u8 v_param_u8, u8 *v_gp_u8)
This API is used to get the status of general purpose register in the register 0x3A and 0x3B.
v_param_u8 The value of general purpose register select v_param_u8 value BMG160_GP0 0 BMG160_GP1 1 v_gp_u8 The value of general purpose register results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_GP0, bmg160_t::dev_addr, BMG160_TRIM_GP0_ADDR_GP0__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_GP1, BMG160_TRIM_GP1_ADDR, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_gp(u8 v_param_u8, u8 v_gp_u8)
This API is used to set the status of general purpose register in the register 0x3A and 0x3B.
v_param_u8 The value of general purpose register select v_param_u8 value BMG160_GP0 0 BMG160_GP1 1 v_gp_u8 The value of general purpose register results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_GP0, bmg160_t::dev_addr, BMG160_TRIM_GP0_ADDR_GP0__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, BMG160_GP1, BMG160_TRIM_GP1_ADDR, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_FIFO_data_reg(u8 *v_fifo_data_u8)
Reads FIFO data from location 0x3F.
v_fifo_data_u8 : The data of fifo results of bus communication function 0 -> Success -1 -> Error result of communication routines
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_FIFO_DATA_ADDR, BMG160_GEN_READ_WRITE_DATA_LENGTH.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_fifo_stat_reg(u8 *v_fifo_stat_u8)
this api is used to read the fifo status of frame_counter and overrun in the register 0x0E
frame_counter > bit from 0 to 6 overrun -> bit 7 v_fifo_stat_u8 : The value of fifo overrun and fifo counter results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_FIFO_STAT_ADDR, BMG160_GEN_READ_WRITE_DATA_LENGTH.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_fifo_frame_count(u8 *v_fifo_frame_count_u8)
this API is used to get the fifo frame counter in the register 0x0E bit 0 to 6
v_fifo_frame_count_u8 The value of fifo frame counter results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_FIFO_STAT_FRAME_COUNTER__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_fifo_overrun(u8 *v_fifo_overrun_u8)
this API is used to get the fifo over run in the register 0x0E bit 7
v_fifo_overrun_u8 The value of fifo over run results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_FIFO_STAT_OVERRUN__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_fifo_mode(u8 *v_fifo_mode_u8)
This API is used to get the status of fifo mode in the register 0x3E bit 6 and 7.
v_fifo_mode_u8 : The value of fifo mode mode value BYPASS 0 FIFO 1 STREAM 2 RESERVED 3 results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_FIFO_CGF0_ADDR_MODE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_fifo_mode(u8 v_fifo_mode_u8)
This API is used to set the status of fifo mode in the register 0x3E bit 6 and 7.
v_fifo_mode_u8 : The value of fifo mode mode value BYPASS 0 FIFO 1 STREAM 2 RESERVED 3 results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_BIT_LENGTH_FIFO_MODE, bmg160_t::dev_addr, BMG160_FIFO_CGF0_ADDR_MODE__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_fifo_data_select(u8 *v_fifo_data_select_u8)
This API is used to get the status of fifo data select in the register 0x3E bit 0 and 1.
v_fifo_data_select_u8 : The value of fifo data selection data selection value X,Y and Z (DEFAULT) 0 X only 1 Y only 2 Z only 3 results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_FIFO_CGF0_ADDR_DATA_SELECT__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_fifo_data_select(u8 v_fifo_data_select_u8)
This API is used to set the status of fifo data select in the register 0x3E bit 0 and 1.
v_fifo_data_select_u8 : The value of fifo data selection data selection value X,Y and Z (DEFAULT) 0 X only 1 Y only 2 Z only 3 results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_BIT_LENGTH_FIFO_DATA_SELECT, bmg160_t::dev_addr, BMG160_FIFO_CGF0_ADDR_DATA_SELECT__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, E_BMG160_OUT_OF_RANGE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_power_mode(u8 *v_power_mode_u8)
This API is used to get the operating modes of the sensor in the registers 0x11 and 0x12.
v_power_mode_u8 :The value of power mode value power mode 0 BMG160_MODE_NORMAL 1 BMG160_MODE_SUSPEND 2 BMG160_MODE_DEEPSUSPEND 3 BMG160_MODE_FASTPOWERUP 4 BMG160_MODE_ADVANCEDPOWERSAVING results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_MODE_LPM1_ADDR, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_MODE_LPM2_ADDR, BMG160_MODE_ADVANCEDPOWERSAVING, BMG160_MODE_NORMAL, BMG160_MODE_DEEPSUSPEND, BMG160_MODE_SUSPEND, BMG160_MODE_FASTPOWERUP.
Referenced by bmg160_set_bw, Gyroscope_getMode.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_power_mode(u8 v_power_mode_u8)
This API is used to set the operating modes of the sensor in the registers 0x11 and 0x12.
v_power_mode_u8 :The value of power mode value power mode 0 BMG160_MODE_NORMAL 1 BMG160_MODE_SUSPEND 2 BMG160_MODE_DEEPSUSPEND 3 BMG160_MODE_FASTPOWERUP 4 BMG160_MODE_ADVANCEDPOWERSAVING results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, E_BMG160_NULL_PTR, BMG160_BIT_LENGTH_POWER_MODE, bmg160_t::dev_addr, BMG160_MODE_LPM1_ADDR, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_MODE_LPM2_ADDR, BMG160_MODE_NORMAL, BMG160_SET_BITSLICE, bmg160_t::delay_msec, BMG160_POWER_MODE_DELAY, BMG160_MODE_DEEPSUSPEND, BMG160_MODE_SUSPEND, BMG160_BIT_MASK_MODE_LPM1, BMG160_MODE_FASTPOWERUP, BMG160_MODE_ADVANCEDPOWERSAVING, bmg160_get_bw, bmg160_get_auto_sleep_durn, bmg160_set_auto_sleep_durn, E_BMG160_OUT_OF_RANGE.
Referenced by Gyroscope_setMode.
BMG160_RETURN_FUNCTION_TYPE bmg160_selftest(u8 *v_result_u8)
This API is used to to do selftest to sensor sensor in the register 0x3C.
v_result_u8 The value of self test results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, bmg160_t::dev_addr, BMG160_SELFTEST_ADDR, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE, BMG160_SET_BITSLICE, BMG160_SELFTEST_ADDR_TRIGBIST__REG, bmg160_t::delay_msec, BMG160_SELFTEST_DELAY, BMG160_SELFTEST_ADDR_BISTFAIL__REG, BMG160_SELFTEST_BISTFAIL, BMG160_SELFTEST_RATEOK, C_BMG160_SUCCESS, C_BMG160_FAILURE.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_auto_sleep_durn(u8 *v_durn_u8)
This API is used to get the auto sleep duration in the register 0x12 bit 0 to 2.
v_durn_u8 : The value of gyro auto sleep duration sleep duration value not allowed 0 4ms 1 5ms 2 8ms 3 10ms 4 15ms 5 20ms 6 40ms 7 results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_MODE_LPM2_ADDR_AUTO_SLEEP_DURN__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
Referenced by bmg160_set_bw, bmg160_set_power_mode.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_auto_sleep_durn(u8 v_durn_u8, u8 v_bw_u8)
This API is used to set the auto sleep duration in the register 0x12 bit 0 to 2.
v_durn_u8 : The value of gyro auto sleep duration sleep duration value not allowed 0 4ms 1 5ms 2 8ms 3 10ms 4 15ms 5 20ms 6 40ms 7 v_bw_u8 : The value of selected bandwidth v_bw_u8 value C_BMG160_NO_FILTER_U8X 0 C_BMG160_BW_230HZ_U8X 1 C_BMG160_BW_116HZ_u8X 2 C_BMG160_BW_47HZ_u8X 3 C_BMG160_BW_23HZ_u8X 4 C_BMG160_BW_12HZ_u8X 5 C_BMG160_BW_64HZ_u8X 6 C_BMG160_BW_32HZ_u8X 7 : sleep duration depends on selected power mode and bandwidth results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_MODE_LPM2_ADDR_AUTO_SLEEP_DURN__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_BIT_LENGTH_DURN, C_BMG160_NO_FILTER_U8X, C_BMG160_4MS_AUTO_SLEEP_DURN_U8X, C_BMG160_BW_230HZ_U8X, C_BMG160_BW_116HZ_U8X, C_BMG160_BW_47HZ_U8X, C_BMG160_5MS_AUTO_SLEEP_DURN_U8X, C_BMG160_BW_23HZ_U8X, C_BMG160_10MS_AUTO_SLEEP_DURN_U8X, C_BMG160_BW_12HZ_U8X, C_BMG160_20MS_AUTO_SLEEP_DURN_U8X, C_BMG160_BW_64HZ_U8X, C_BMG160_BW_32HZ_U8X, BMG160_SET_BITSLICE, E_BMG160_OUT_OF_RANGE.
Referenced by bmg160_set_bw, bmg160_set_power_mode, Gyroscope_setAutoSleepDuration.
BMG160_RETURN_FUNCTION_TYPE bmg160_get_sleep_durn(u8 *v_durn_u8)
This API is used to get the sleep duration in the register 0x11 bit 1 to 3.
v_durn_u8 : The value of sleep duration sleep duration value 2ms 0 4ms 1 5ms 2 8ms 3 10ms 4 15ms 5 18ms 6 20ms 7 results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, bmg160_t::dev_addr, BMG160_MODELPM1_ADDR_SLEEP_DURN__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_GET_BITSLICE.
BMG160_RETURN_FUNCTION_TYPE bmg160_set_sleep_durn(u8 v_durn_u8)
This API is used to set the sleep duration in the register 0x11 bit 1 to 3.
v_durn_u8 : The value of sleep duration sleep duration value 2ms 0 4ms 1 5ms 2 8ms 3 10ms 4 15ms 5 18ms 6 20ms 7 results of bus communication function 0 -> Success -1 -> Error
References BMG160_RETURN_FUNCTION_TYPE, ERROR, BMG160_INIT_VALUE, BMG160_NULL, E_BMG160_NULL_PTR, BMG160_BIT_LENGTH_DURN, bmg160_t::dev_addr, BMG160_MODELPM1_ADDR_SLEEP_DURN__REG, BMG160_GEN_READ_WRITE_DATA_LENGTH, BMG160_SET_BITSLICE, E_BMG160_OUT_OF_RANGE.
Referenced by Gyroscope_setSleepDuration.
MACHINE_32_BIT
The following definition uses for define the data types.
While porting the API please consider the following Please check the version of C standard Are you using Linux platform For the Linux platform support Please use the types.h for your data types definitionsBy default it is defined as 32 bit machine configuration define your data types based on your machine/compiler/controller configuration
typedef signed short int s16
used for signed 16bit
typedef signed int s32
used for signed 32bit
typedef signed long long int s64
used for signed 64bit
typedef signed char s8
If your machine support 16 bit define the MACHINE_16_BIT.
used for signed 8bit
typedef unsigned short int u16
used for unsigned 16bit
typedef unsigned int u32
used for unsigned 32bit
typedef unsigned long long int u64
used for unsigned 64bit
typedef unsigned char u8
used for unsigned 8bit