bmm050.c
struct bmm050_t* p_bmm050
s16 bmm050_compensate_X(s16 mag_data_x, u16 data_r)
This API used to get the compensated X data the out put of X as s16.
mag_data_x : The value of raw X data data_r : The value of R data results of compensated X data value output as s16
References BMM050_INIT_VALUE, BMM050_FLIP_OVERFLOW_ADCVAL, bmm050_t::dig_xyz1, BMM050_SHIFT_BIT_POSITION_BY_14_BITS, BMM050_OVERFLOW_OUTPUT, bmm050_t::dig_xy2, BMM050_SHIFT_BIT_POSITION_BY_07_BITS, bmm050_t::dig_xy1, BMM050_SHIFT_BIT_POSITION_BY_09_BITS, bmm050_t::dig_x2, BMM050_SHIFT_BIT_POSITION_BY_12_BITS, BMM050_SHIFT_BIT_POSITION_BY_13_BITS, bmm050_t::dig_x1, BMM050_SHIFT_BIT_POSITION_BY_03_BITS.
Referenced by bmm050_read_mag_data_XYZ, bmm050_read_bmx055_remapped_mag_data_XYZ, bmm050_compensate_X_s32.
s32 bmm050_compensate_X_s32(s16 mag_data_x, u16 data_r)
This API used to get the compensated X data the out put of X as s32.
mag_data_x : The value of raw X data data_r : The value of R data results of compensated X data value output as s32
References BMM050_INIT_VALUE, bmm050_compensate_X, BMM050_OVERFLOW_OUTPUT, BMM050_OVERFLOW_OUTPUT_S32.
Referenced by bmm050_read_mag_data_XYZ_s32, bmm050_read_bmx055_remapped_mag_data_XYZ_s32.
s16 bmm050_compensate_Y(s16 mag_data_y, u16 data_r)
This API used to get the compensated Y data the out put of Y as s16.
mag_data_y : The value of raw Y data data_r : The value of R data results of compensated Y data value output as s16
References BMM050_INIT_VALUE, BMM050_FLIP_OVERFLOW_ADCVAL, bmm050_t::dig_xyz1, BMM050_SHIFT_BIT_POSITION_BY_14_BITS, BMM050_OVERFLOW_OUTPUT, bmm050_t::dig_xy2, BMM050_SHIFT_BIT_POSITION_BY_07_BITS, bmm050_t::dig_xy1, BMM050_SHIFT_BIT_POSITION_BY_09_BITS, bmm050_t::dig_y2, BMM050_SHIFT_BIT_POSITION_BY_12_BITS, BMM050_SHIFT_BIT_POSITION_BY_13_BITS, bmm050_t::dig_y1, BMM050_SHIFT_BIT_POSITION_BY_03_BITS.
Referenced by bmm050_read_mag_data_XYZ, bmm050_read_bmx055_remapped_mag_data_XYZ, bmm050_compensate_Y_s32.
s32 bmm050_compensate_Y_s32(s16 mag_data_y, u16 data_r)
This API used to get the compensated Y data the out put of Y as s32.
mag_data_y : The value of raw Y data data_r : The value of R data results of compensated Y data value output as s32
References BMM050_INIT_VALUE, bmm050_compensate_Y, BMM050_OVERFLOW_OUTPUT, BMM050_OVERFLOW_OUTPUT_S32.
Referenced by bmm050_read_mag_data_XYZ_s32, bmm050_read_bmx055_remapped_mag_data_XYZ_s32.
s16 bmm050_compensate_Z(s16 mag_data_z, u16 data_r)
This API used to get the compensated Z data the out put of Z as s16.
mag_data_z : The value of raw Z data data_r : The value of R data results of compensated Z data value output as s16
References BMM050_INIT_VALUE, BMM050_HALL_OVERFLOW_ADCVAL, bmm050_t::dig_z2, bmm050_t::dig_z1, bmm050_t::dig_xyz1, bmm050_t::dig_z4, BMM050_SHIFT_BIT_POSITION_BY_15_BITS, bmm050_t::dig_z3, BMM050_SHIFT_BIT_POSITION_BY_02_BITS, BMM050_SHIFT_BIT_POSITION_BY_01_BIT, BMM050_SHIFT_BIT_POSITION_BY_16_BITS, BMM050_OVERFLOW_OUTPUT, BMM050_POSITIVE_SATURATION_Z, BMM050_NEGATIVE_SATURATION_Z.
Referenced by bmm050_read_mag_data_XYZ, bmm050_read_bmx055_remapped_mag_data_XYZ.
s32 bmm050_compensate_Z_s32(s16 mag_data_z, u16 data_r)
This API used to get the compensated Z data the out put of Z as s32.
mag_data_z : The value of raw Z data data_r : The value of R data results of compensated Z data value output as s32
References BMM050_INIT_VALUE, BMM050_HALL_OVERFLOW_ADCVAL, bmm050_t::dig_z2, bmm050_t::dig_z1, bmm050_t::dig_xyz1, bmm050_t::dig_z4, BMM050_SHIFT_BIT_POSITION_BY_15_BITS, bmm050_t::dig_z3, BMM050_SHIFT_BIT_POSITION_BY_02_BITS, BMM050_SHIFT_BIT_POSITION_BY_01_BIT, BMM050_SHIFT_BIT_POSITION_BY_16_BITS, BMM050_OVERFLOW_OUTPUT_S32.
Referenced by bmm050_read_mag_data_XYZ_s32, bmm050_read_bmx055_remapped_mag_data_XYZ_s32.
BMM050_RETURN_FUNCTION_TYPE bmm050_get_advanced_selftest(u8 *v_advanced_selftest_u8)
This API used to get the advanced self test in the register 0x4C bit 6 and 7.
v_advanced_selftest_u8 : The output value of advanced self test value Status 0 BMM050_ADVANCED_SELFTEST_OFF 2 BMM050_ADVANCED_SELFTEST_NEGATIVE 3 BMM050_ADVANCED_SELFTEST_POSITIVE results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_CONTROL_ADVANCED_SELFTEST__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_GET_BITSLICE.
BMM050_RETURN_FUNCTION_TYPE bmm050_get_bmx055_remapped_raw_xyz(struct bmm050_remapped_mag_s16_data_t *mag_data)
This API reads remapped Magnetometer raw data of X,Y,Z values and RHALL values from location 0x42 to 0x49.
In this function X and Y axis is remapped X is read from the address 0x44 & 0x45 Y is read from the address 0x42 & 0x43 this API is only applicable for BMX055 sensor mag_data : The data of remapped raw XYZ data results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_DATA_FRAME_SIZE, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_REMAPPED_BMX055_DATA_Y_LSB, BMM050_ALL_DATA_FRAME_LENGTH, BMM050_XLSB_DATA, BMM050_GET_BITSLICE, bmm050_remapped_mag_s16_data_t::datay, BMM050_SHIFT_BIT_POSITION_BY_05_BITS, BMM050_YLSB_DATA, bmm050_remapped_mag_s16_data_t::datax, BMM050_ZLSB_DATA, bmm050_remapped_mag_s16_data_t::dataz, BMM050_SHIFT_BIT_POSITION_BY_07_BITS, bmm050_remapped_mag_s16_data_t::data_ready, BMM050_RLSB_DATA, bmm050_remapped_mag_s16_data_t::resistance, BMM050_RMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_06_BITS.
BMM050_RETURN_FUNCTION_TYPE bmm050_get_data_rate(u8 *v_data_rate_u8)
This API used to get the data rate of the sensor in the register 0x4C bit 3 to 5.
v_data_rate_u8 : The value of data rate value Description 0x00 BMM050_DATA_RATE_10HZ 0x01 BMM050_DATA_RATE_02HZ 0x02 BMM050_DATA_RATE_06HZ 0x03 BMM050_DATA_RATE_08HZ 0x04 BMM050_DATA_RATE_15HZ 0x05 BMM050_DATA_RATE_20HZ 0x06 BMM050_DATA_RATE_25HZ 0x07 BMM050_DATA_RATE_30HZ results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_CONTROL_DATA_RATE__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_GET_BITSLICE.
Referenced by bmm050_get_presetmode, Magnetometer_getDataRate.
BMM050_RETURN_FUNCTION_TYPE bmm050_get_functional_state(u8 *v_functional_state_u8)
This API used to get the functional state in the register 0x4C bit 1 and 2.
v_functional_state_u8 The value of functional mode value functional state 0x00 Normal 0x03 Sleep If user set the functional state as Force mode(0x01) and read the register it returns the value as 0x03 that is sleep mode. results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_CONTROL_OPERATION_MODE__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_GET_BITSLICE.
Referenced by Magnetometer_getPowerMode.
BMM050_RETURN_FUNCTION_TYPE bmm050_get_power_mode(u8 *v_power_mode_u8)
This API used to get the power control bit in the register 0x4B bit 0.
v_power_mode_u8 : The value of power control bit enable value status 0 Disable the power control bit 1 Enable the power control bit results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_POWER_CONTROL_POWER_CONTROL_BIT__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_GET_BITSLICE.
Referenced by bmm050_set_functional_state.
BMM050_RETURN_FUNCTION_TYPE bmm050_get_presetmode(u8 *v_presetmode_u8)
This API used to get the preset modes.
The preset mode setting is depend on Data Rate, XY and Z repetitions v_presetmode_u8 The value of selected preset mode value preset_mode 1 BMM050_PRESETMODE_LOWPOWER 2 BMM050_PRESETMODE_REGULAR 3 BMM050_PRESETMODE_HIGHACCURACY 4 BMM050_PRESETMODE_ENHANCED results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, bmm050_get_data_rate, bmm050_get_rep_XY, bmm050_get_rep_Z, BMM050_LOWPOWER_DR, BMM050_LOWPOWER_REPXY, BMM050_LOWPOWER_REPZ, BMM050_PRESETMODE_LOWPOWER, BMM050_REGULAR_DR, BMM050_REGULAR_REPXY, BMM050_REGULAR_REPZ, BMM050_PRESETMODE_REGULAR, BMM050_HIGHACCURACY_DR, BMM050_HIGHACCURACY_REPXY, BMM050_HIGHACCURACY_REPZ, BMM050_PRESETMODE_HIGHACCURACY, BMM050_ENHANCED_DR, BMM050_ENHANCED_REPXY, BMM050_ENHANCED_REPZ, BMM050_PRESETMODE_ENHANCED, E_BMM050_UNDEFINED_MODE.
Referenced by Magnetometer_getPresetMode.
BMM050_RETURN_FUNCTION_TYPE bmm050_get_raw_xyz(struct bmm050_mag_data_s16_t *mag_data)
This API reads Magnetometer raw data of X,Y,Z values and RHALL values from location 0x42 to 0x49.
mag_data : The data of raw XYZ data results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_DATA_FRAME_SIZE, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_DATA_X_LSB, BMM050_ALL_DATA_FRAME_LENGTH, BMM050_XLSB_DATA, BMM050_GET_BITSLICE, bmm050_mag_data_s16_t::datax, BMM050_SHIFT_BIT_POSITION_BY_05_BITS, BMM050_YLSB_DATA, bmm050_mag_data_s16_t::datay, BMM050_ZLSB_DATA, bmm050_mag_data_s16_t::dataz, BMM050_SHIFT_BIT_POSITION_BY_07_BITS, bmm050_mag_data_s16_t::data_ready, BMM050_RLSB_DATA, bmm050_mag_data_s16_t::resistance, BMM050_RMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_06_BITS.
BMM050_RETURN_FUNCTION_TYPE bmm050_get_rep_XY(u8 *v_rep_xy_u8)
This API used to get the x and y repetition in the register 0x51 bit 0 to 7.
v_rep_xy_u8 : The value of x and y repetitions results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_REP_XY, BMM050_GEN_READ_WRITE_DATA_LENGTH.
Referenced by bmm050_get_presetmode.
BMM050_RETURN_FUNCTION_TYPE bmm050_get_rep_Z(u8 *v_rep_z_u8)
This API used to get the z repetition in the register 0x52 bit 0 to 7.
v_rep_z_u8 : The value of z repetitions results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_REP_Z, BMM050_GEN_READ_WRITE_DATA_LENGTH.
Referenced by bmm050_get_presetmode.
BMM050_RETURN_FUNCTION_TYPE bmm050_get_selftest_XYZ(u8 *v_selftest_xyz)
This API used to read the selftest of the sensor.
v_selftest_xyz The self test value of XYZ results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_SELFTEST_DATA_SIZE, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_DATA_X_LSB_TESTX__REG, BMM050_SELFTEST_DATA_LENGTH, BMM050_GET_BITSLICE, BMM050_ZLSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_01_BIT, BMM050_YLSB_DATA, BMM050_XLSB_DATA.
BMM050_RETURN_FUNCTION_TYPE bmm050_init(struct bmm050_t *bmm050)
This function is used for initialize bus read and bus write functions assign the chip id and device address chip id is read in the register 0x40 bit from 0 to 7.
While changing the parameter of the bmm050 consider the following point: Changing the reference value of the parameter will changes the local copy or local reference make sure your changes will not affect the reference value of the parameter (Better case don't change the reference value of the parameter) results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_DATA_SIZE, BMM050_INIT_VALUE, bmm050_set_power_mode, BMM050_ON, bmm050_t::delay_msec, BMM050_DELAY_SETTLING_TIME, bmm050_t::dev_addr, BMM050_CHIP_ID, BMM050_GEN_READ_WRITE_DATA_LENGTH, bmm050_t::company_id, BMM050_CHIP_ID_DATA, bmm050_init_trim_registers, bmm050_set_presetmode, BMM050_PRESETMODE_REGULAR.
Referenced by Bmm150Utils_initialize.
BMM050_RETURN_FUNCTION_TYPE bmm050_init_trim_registers(void)
This API used to get the trim values.
results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_TRIM_DATA_SIZE, BMM050_INIT_VALUE, bmm050_t::dev_addr, BMM050_DIG_X1, bmm050_t::dig_x1, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_DIG_Y1, bmm050_t::dig_y1, BMM050_DIG_X2, bmm050_t::dig_x2, BMM050_DIG_Y2, bmm050_t::dig_y2, BMM050_DIG_XY1, bmm050_t::dig_xy1, BMM050_DIG_XY2, bmm050_t::dig_xy2, BMM050_DIG_Z1_LSB, BMM050_TRIM_DATA_LENGTH, bmm050_t::dig_z1, BMM050_TRIM_DIG_Z1_MSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_08_BITS, BMM050_TRIM_DIG_Z1_LSB_DATA, BMM050_DIG_Z2_LSB, bmm050_t::dig_z2, BMM050_TRIM_DIG_Z2_MSB_DATA, BMM050_TRIM_DIG_Z2_LSB_DATA, BMM050_DIG_Z3_LSB, bmm050_t::dig_z3, BMM050_TRIM_DIG_Z3_MSB_DATA, BMM050_TRIM_DIG_Z3_LSB_DATA, BMM050_DIG_Z4_LSB, bmm050_t::dig_z4, BMM050_TRIM_DIG_Z4_MSB_DATA, BMM050_TRIM_DIG_Z4_LSB_DATA, BMM050_DIG_XYZ1_LSB, BMM050_TRIM_DIG_XYZ1_MSB_DATA, BMM050_GET_BITSLICE, BMM050_DIG_XYZ1_MSB, bmm050_t::dig_xyz1, BMM050_TRIM_DIG_XYZ1_LSB_DATA.
Referenced by bmm050_init.
BMM050_RETURN_FUNCTION_TYPE bmm050_perform_advanced_selftest(s16 *v_diff_z_s16)
This API used to perform the advanced self test.
v_diff_z_s16 : The output of advance self test results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_set_functional_state, BMM050_SLEEP_MODE, bmm050_set_rep_Z, BMM050_LOWPOWER_REPZ, bmm050_set_control_measurement_x, BMM050_CHANNEL_DISABLE, bmm050_set_control_measurement_y, bmm050_set_advanced_selftest, BMM050_ADVANCED_SELFTEST_POSITIVE, BMM050_FORCED_MODE, bmm050_t::delay_msec, BMM050_SELFTEST_DELAY, bmm050_read_mag_data_XYZ, bmm050_mag_data_s16_t::dataz, BMM050_ADVANCED_SELFTEST_NEGATIVE, BMM050_ADVANCED_SELFTEST_OFF, BMM050_CHANNEL_ENABLE.
BMM050_RETURN_FUNCTION_TYPE bmm050_read_bmx055_remapped_mag_data_XYZ(struct bmm050_remapped_mag_s16_data_t *mag_data)
This API reads remapped compensated Magnetometer data of X,Y,Z values.
In this function X and Y axis is remapped X is read from the address 0x44 & 0x45 Y is read from the address 0x42 & 0x43 this API is only applicable for BMX055 sensor mag_data : The data of remapped compensated mag xyz data results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_DATA_FRAME_SIZE, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_REMAPPED_BMX055_DATA_Y_LSB, BMM050_ALL_DATA_FRAME_LENGTH, BMM050_REMAPPED_YLSB_DATA, BMM050_GET_BITSLICE, BMM050_REMAPPED_YMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_05_BITS, BMM050_REMAPPED_XLSB_DATA, BMM050_ZLSB_DATA, BMM050_ZMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_07_BITS, bmm050_remapped_mag_s16_data_t::data_ready, BMM050_RLSB_DATA, BMM050_RMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_06_BITS, bmm050_remapped_mag_s16_data_t::datax, bmm050_compensate_X, bmm050_remapped_mag_s16_data_t::datay, bmm050_compensate_Y, bmm050_remapped_mag_s16_data_t::dataz, bmm050_compensate_Z, bmm050_remapped_mag_s16_data_t::resistance.
BMM050_RETURN_FUNCTION_TYPE bmm050_read_bmx055_remapped_mag_data_XYZ_s32(struct bmm050_remapped_mag_s32_data_t *mag_data)
This API reads remapped compensated magnetometer data of X,Y,Z values.
The output value of compensated X, Y, Z as s32 In this function X and Y axis is remapped X is read from the address 0x44 & 0x45 Y is read from the address 0x42 & 0x43 this API is only applicable for BMX055 sensor mag_data : The data of remapped compensated XYZ data results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_DATA_FRAME_SIZE, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_REMAPPED_BMX055_DATA_Y_LSB, BMM050_ALL_DATA_FRAME_LENGTH, BMM050_REMAPPED_YLSB_DATA, BMM050_GET_BITSLICE, BMM050_REMAPPED_YMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_05_BITS, BMM050_REMAPPED_XLSB_DATA, BMM050_REMAPPED_XMSB_DATA, BMM050_ZLSB_DATA, BMM050_ZMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_07_BITS, bmm050_remapped_mag_s32_data_t::data_ready, BMM050_RLSB_DATA, BMM050_RMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_06_BITS, bmm050_remapped_mag_s32_data_t::datax, bmm050_compensate_X_s32, bmm050_remapped_mag_s32_data_t::datay, bmm050_compensate_Y_s32, bmm050_remapped_mag_s32_data_t::dataz, bmm050_compensate_Z_s32, bmm050_remapped_mag_s32_data_t::resistance.
BMM050_RETURN_FUNCTION_TYPE bmm050_read_mag_data_XYZ(struct bmm050_mag_data_s16_t *mag_data)
This API reads compensated Magnetometer data of X,Y,Z values from location 0x42 to 0x49.
mag_data : The data of mag compensated XYZ data results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_DATA_FRAME_SIZE, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_DATA_X_LSB, BMM050_ALL_DATA_FRAME_LENGTH, BMM050_XLSB_DATA, BMM050_GET_BITSLICE, BMM050_XMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_05_BITS, BMM050_YLSB_DATA, BMM050_YMSB_DATA, BMM050_ZLSB_DATA, BMM050_ZMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_07_BITS, bmm050_mag_data_s16_t::data_ready, BMM050_RLSB_DATA, BMM050_RMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_06_BITS, bmm050_mag_data_s16_t::datax, bmm050_compensate_X, bmm050_mag_data_s16_t::datay, bmm050_compensate_Y, bmm050_mag_data_s16_t::dataz, bmm050_compensate_Z, bmm050_mag_data_s16_t::resistance.
Referenced by bmm050_perform_advanced_selftest.
BMM050_RETURN_FUNCTION_TYPE bmm050_read_mag_data_XYZ_s32(struct bmm050_mag_s32_data_t *mag_data)
This API reads compensated magnetometer data of X,Y,Z values.
The output value of compensated X, Y, Z as s32 mag_data : The data of compensated XYZ data results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_DATA_FRAME_SIZE, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_DATA_X_LSB, BMM050_ALL_DATA_FRAME_LENGTH, BMM050_XLSB_DATA, BMM050_GET_BITSLICE, BMM050_XMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_05_BITS, BMM050_YLSB_DATA, BMM050_YMSB_DATA, BMM050_ZLSB_DATA, BMM050_ZMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_07_BITS, bmm050_mag_s32_data_t::data_ready, BMM050_RLSB_DATA, BMM050_RMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_06_BITS, bmm050_mag_s32_data_t::datax, bmm050_compensate_X_s32, bmm050_mag_s32_data_t::datay, bmm050_compensate_Y_s32, bmm050_mag_s32_data_t::dataz, bmm050_compensate_Z_s32, bmm050_mag_s32_data_t::resistance.
Referenced by readMagData.
BMM050_RETURN_FUNCTION_TYPE bmm050_read_register(u8 v_addr_u8, u8 *v_data_u8, u8 v_len_u8)
This API reads the data from the given register.
v_addr_u8 -> Address of the register v_data_u8 -> The data from the register v_len_u8 -> no of bytes to read results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr.
BMM050_RETURN_FUNCTION_TYPE bmm050_set_advanced_selftest(u8 v_advanced_selftest_u8)
This API used to set the advanced self test in the register 0x4C bit 6 and 7.
v_advanced_selftest_u8 : The output value of advanced self test value Status 0 BMM050_ADVANCED_SELFTEST_OFF 2 BMM050_ADVANCED_SELFTEST_NEGATIVE 3 BMM050_ADVANCED_SELFTEST_POSITIVE results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, BMM050_ADVANCED_SELFTEST_OFF, bmm050_t::dev_addr, BMM050_CONTROL_ADVANCED_SELFTEST__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_SET_BITSLICE, BMM050_ADVANCED_SELFTEST_POSITIVE, BMM050_ADVANCED_SELFTEST_NEGATIVE.
Referenced by bmm050_perform_advanced_selftest.
BMM050_RETURN_FUNCTION_TYPE bmm050_set_control_measurement_x(u8 v_enable_disable_u8)
This API used to set the control measurement X data in the register 0x4E bit 3.
v_enable_disable_u8 The value of control measurement-x value Status 1 ENABLE 0 DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_SENS_CONTROL_CHANNELX__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_SET_BITSLICE.
Referenced by bmm050_perform_advanced_selftest.
BMM050_RETURN_FUNCTION_TYPE bmm050_set_control_measurement_y(u8 v_enable_disable_u8)
This API used to set the control measurement Y data in the register 0x4E bit 4.
v_enable_disable_u8 The value of control measurement-y value Status 1 ENABLE 0 DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_SENS_CONTROL_CHANNELY__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_SET_BITSLICE.
Referenced by bmm050_perform_advanced_selftest.
BMM050_RETURN_FUNCTION_TYPE bmm050_set_data_rate(u8 v_data_rate_u8)
This API used to set the data rate of the sensor in the register 0x4C bit 3 to 5.
v_data_rate_u8 : The value of data rate value Description 0x00 BMM050_DATA_RATE_10HZ 0x01 BMM050_DATA_RATE_02HZ 0x02 BMM050_DATA_RATE_06HZ 0x03 BMM050_DATA_RATE_08HZ 0x04 BMM050_DATA_RATE_15HZ 0x05 BMM050_DATA_RATE_20HZ 0x06 BMM050_DATA_RATE_25HZ 0x07 BMM050_DATA_RATE_30HZ results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_CONTROL_DATA_RATE__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_SET_BITSLICE.
Referenced by bmm050_set_presetmode, Magnetometer_setDataRate.
BMM050_RETURN_FUNCTION_TYPE bmm050_set_functional_state(u8 v_functional_state_u8)
This API used to set the functional state in the register 0x4C and 0x4B.
0x4C bit 1 and 2 0x4B bit 0 v_functional_state_u8 The value of functional mode value functional state 0x00 BMM050_NORMAL_MODE 0x01 BMM050_SUSPEND_MODE 0x02 BMM050_FORCED_MODE 0x03 BMM050_SLEEP_MODE results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, BMM050_NORMAL_MODE, bmm050_get_power_mode, BMM050_OFF, bmm050_set_power_mode, BMM050_ON, bmm050_t::delay_msec, BMM050_DELAY_SUSPEND_SLEEP, bmm050_t::dev_addr, BMM050_CONTROL_OPERATION_MODE__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_SET_BITSLICE, BMM050_SUSPEND_MODE, BMM050_FORCED_MODE, BMM050_SLEEP_MODE, E_BMM050_OUT_OF_RANGE.
Referenced by bmm050_perform_advanced_selftest, Magnetometer_setPowerMode, Bmm150Utils_initialize.
BMM050_RETURN_FUNCTION_TYPE bmm050_set_power_mode(u8 v_power_mode_u8)
This API used to set the power control bit in the register 0x4B bit 0.
v_power_mode_u8 : The value of power control bit enable value status 0 Disable the power control bit 1 Enable the power control bit results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_POWER_CONTROL_POWER_CONTROL_BIT__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_SET_BITSLICE.
Referenced by bmm050_init, bmm050_set_functional_state.
BMM050_RETURN_FUNCTION_TYPE bmm050_set_presetmode(u8 v_presetmode_u8)
This API used to set the preset modes.
The preset mode setting is depend on Data Rate, XY and Z repetitions v_presetmode_u8 The value of selected preset mode value preset_mode 1 BMM050_PRESETMODE_LOWPOWER 2 BMM050_PRESETMODE_REGULAR 3 BMM050_PRESETMODE_HIGHACCURACY 4 BMM050_PRESETMODE_ENHANCED results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_PRESETMODE_LOWPOWER, bmm050_set_data_rate, BMM050_LOWPOWER_DR, bmm050_set_rep_XY, BMM050_LOWPOWER_REPXY, bmm050_set_rep_Z, BMM050_LOWPOWER_REPZ, BMM050_PRESETMODE_REGULAR, BMM050_REGULAR_DR, BMM050_REGULAR_REPXY, BMM050_REGULAR_REPZ, BMM050_PRESETMODE_HIGHACCURACY, BMM050_HIGHACCURACY_DR, BMM050_HIGHACCURACY_REPXY, BMM050_HIGHACCURACY_REPZ, BMM050_PRESETMODE_ENHANCED, BMM050_ENHANCED_DR, BMM050_ENHANCED_REPXY, BMM050_ENHANCED_REPZ, E_BMM050_OUT_OF_RANGE.
Referenced by bmm050_init, Magnetometer_setPresetMode.
BMM050_RETURN_FUNCTION_TYPE bmm050_set_rep_XY(u8 v_rep_xy_u8)
This API used to set the x and y repetition in the register 0x51 bit 0 to 7.
v_rep_xy_u8 : The value of x and y repetitions results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_REP_XY, BMM050_GEN_READ_WRITE_DATA_LENGTH.
Referenced by bmm050_set_presetmode.
BMM050_RETURN_FUNCTION_TYPE bmm050_set_rep_Z(u8 v_rep_z_u8)
This API used to set the z repetition in the register 0x52 bit 0 to 7.
v_rep_z_u8 : The value of z repetitions results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_REP_Z, BMM050_GEN_READ_WRITE_DATA_LENGTH.
Referenced by bmm050_set_presetmode, bmm050_perform_advanced_selftest.
BMM050_RETURN_FUNCTION_TYPE bmm050_set_selftest(u8 v_selftest_u8)
This API used to set the self test of the sensor in the register 0x4C bit 0.
v_selftest_u8 : The value of selftest write 0x01 to start self test results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_CONTROL_SELFTEST__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_SET_BITSLICE.
BMM050_RETURN_FUNCTION_TYPE bmm050_set_spi3(u8 v_value_u8)
This API used to set the spi3 in the register 0x4B bit 2.
v_value_u8 : the value of spi3 value Description 0 Disable 1 Enable results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_POWER_CONTROL_SPI3_ENABLE__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_SET_BITSLICE.
BMM050_RETURN_FUNCTION_TYPE bmm050_soft_rst(void)
This API used reset the register values to default in the register 0x4B.
results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, BMM050_ON, bmm050_t::dev_addr, BMM050_POWER_CONTROL_SOFT_RST_7__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_SET_BITSLICE, BMM050_SOFT_RESET7_ON, BMM050_POWER_CONTROL_SOFT_RST_1__REG, BMM050_SOFT_RESET1_ON, bmm050_t::delay_msec, BMM050_DELAY_SOFTRESET.
BMM050_RETURN_FUNCTION_TYPE bmm050_write_register(u8 v_addr_u8, u8 *v_data_u8, u8 v_len_u8)
This API write the data to the given register.
v_addr_u8 -> Address of the register v_data_u8 -> The data from the register v_len_u8 -> no of bytes to read results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr.