bmm050.h
BMM050_BUS_WR_RETURN_TYPE
Define the calling convention of YOUR bus communication routine.
This includes types of parameters. This example shows the configuration for an SPI bus link. If your communication function looks like this:write_my_bus_xy(u8 device_addr, u8 register_addr, u8 * data, u8 length);The BMM050_WR_FUNC_PTR would equal:BMM050_WR_FUNC_PTR s8 (* bus_write)(u8, u8, u8 *, u8)Parameters can be mixed as needed refer to the refer BMM050_BUS_WRITE_FUNC macro.
BMM050_BUS_WR_PARAM_TYPES
BMM050_BUS_WR_PARAM_ORDER
BMM050_BUS_WRITE_FUNC
BMM050_BUS_RD_RETURN_TYPE
link macro between API function calls and bus read function
The bus write function can change since this is a system dependant issue. If the bus_read parameter calling order is like: reg_addr, reg_data, wr_len it would be as it is here. If the parameters are differently ordered or your communication function like I2C need to know the device address, you can change this macro accordingly. BMM050_BUS_READ_FUNC(dev_addr, reg_addr, reg_data, wr_len)\ bus_read(dev_addr, reg_addr, reg_data, wr_len) This macro lets all API functions call YOUR communication routine in a way that equals your definition in the refer BMM050_RD_FUNC_PTR definition. : this macro also includes the "MSB='1' for reading BMM050 addresses.
BMM050_BUS_RD_PARAM_TYPES
BMM050_BUS_RD_PARAM_ORDER
BMM050_BUS_READ_FUNC
BMM050_DELAY_RETURN_TYPE
BMM050_DELAY_FUNC
BMM050_RETURN_FUNCTION_TYPE
Referenced by bmm050_init, bmm050_get_presetmode, bmm050_set_presetmode, bmm050_set_functional_state, bmm050_get_functional_state, bmm050_read_mag_data_XYZ, bmm050_read_bmx055_remapped_mag_data_XYZ, bmm050_read_mag_data_XYZ_s32, bmm050_read_bmx055_remapped_mag_data_XYZ_s32, bmm050_read_register, bmm050_write_register, bmm050_set_selftest, bmm050_get_selftest_XYZ, bmm050_set_spi3, bmm050_set_data_rate, bmm050_get_data_rate, bmm050_perform_advanced_selftest, bmm050_init_trim_registers, bmm050_set_advanced_selftest, bmm050_get_advanced_selftest, bmm050_get_power_mode, bmm050_set_power_mode, bmm050_get_rep_XY, bmm050_set_rep_XY, bmm050_get_rep_Z, bmm050_set_rep_Z, bmm050_set_control_measurement_x, bmm050_set_control_measurement_y, bmm050_soft_rst, bmm050_get_raw_xyz, bmm050_get_bmx055_remapped_raw_xyz, readMagData, Magnetometer_setPowerMode, Magnetometer_setPresetMode, Magnetometer_setDataRate, Magnetometer_getPowerMode, Magnetometer_getPresetMode, Magnetometer_getDataRate, Bmm150Utils_initialize.
BMM050_I2C_ADDRESS
BMM050_CHIP_ID
Referenced by bmm050_init.
BMM050_DATA_X_LSB
Referenced by bmm050_read_mag_data_XYZ, bmm050_read_mag_data_XYZ_s32, bmm050_get_raw_xyz.
BMM050_DATA_X_MSB
BMM050_DATA_Y_LSB
BMM050_DATA_Y_MSB
BMM050_DATA_Z_LSB
BMM050_DATA_Z_MSB
BMM050_DATA_R_LSB
BMM050_DATA_R_MSB
BMM050_REMAPPED_BMX055_DATA_Y_LSB
Referenced by bmm050_read_bmx055_remapped_mag_data_XYZ, bmm050_read_bmx055_remapped_mag_data_XYZ_s32, bmm050_get_bmx055_remapped_raw_xyz.
BMM050_REMAPPED_BMX055_DATA_Y_MSB
BMM050_REMAPPED_BMX055_DATA_X_LSB
BMM050_REMAPPED_BMX055_DATA_X_MSB
BMM050_INT_STAT_REG
BMM050_POWER_CONTROL
BMM050_CONTROL
BMM050_INT_CONTROL
BMM050_SENS_CONTROL
BMM050_LOW_THRES
BMM050_HIGH_THRES
BMM050_NORMAL_MODE
Referenced by bmm050_set_functional_state, Bmm150Utils_initialize.
BMM050_FORCED_MODE
Referenced by bmm050_set_functional_state, bmm050_perform_advanced_selftest.
BMM050_SUSPEND_MODE
Referenced by bmm050_set_functional_state.
BMM050_SLEEP_MODE
Referenced by bmm050_set_functional_state, bmm050_perform_advanced_selftest.
BMM050_REP_XY
Referenced by bmm050_get_rep_XY, bmm050_set_rep_XY.
BMM050_REP_Z
Referenced by bmm050_get_rep_Z, bmm050_set_rep_Z.
BMM050_DIG_X1
Referenced by bmm050_init_trim_registers.
BMM050_DIG_Y1
Referenced by bmm050_init_trim_registers.
BMM050_DIG_Z4_LSB
Referenced by bmm050_init_trim_registers.
BMM050_DIG_Z4_MSB
BMM050_DIG_X2
Referenced by bmm050_init_trim_registers.
BMM050_DIG_Y2
Referenced by bmm050_init_trim_registers.
BMM050_DIG_Z2_LSB
Referenced by bmm050_init_trim_registers.
BMM050_DIG_Z2_MSB
BMM050_DIG_Z1_LSB
Referenced by bmm050_init_trim_registers.
BMM050_DIG_Z1_MSB
BMM050_DIG_XYZ1_LSB
Referenced by bmm050_init_trim_registers.
BMM050_DIG_XYZ1_MSB
Referenced by bmm050_init_trim_registers.
BMM050_DIG_Z3_LSB
Referenced by bmm050_init_trim_registers.
BMM050_DIG_Z3_MSB
BMM050_DIG_XY2
Referenced by bmm050_init_trim_registers.
BMM050_DIG_XY1
Referenced by bmm050_init_trim_registers.
BMM050_DATA_X_LSB_BIT__POS
BMM050_DATA_X_LSB_BIT__LEN
BMM050_DATA_X_LSB_BIT__MSK
BMM050_DATA_X_LSB_BIT__REG
BMM050_DATA_X_LSB_TESTX__POS
BMM050_DATA_X_LSB_TESTX__LEN
BMM050_DATA_X_LSB_TESTX__MSK
BMM050_DATA_X_LSB_TESTX__REG
Referenced by bmm050_get_selftest_XYZ.
BMM050_DATA_Y_LSB_BIT__POS
BMM050_DATA_Y_LSB_BIT__LEN
BMM050_DATA_Y_LSB_BIT__MSK
BMM050_DATA_Y_LSB_BIT__REG
BMM050_DATA_Y_LSB_TESTY__POS
BMM050_DATA_Y_LSB_TESTY__LEN
BMM050_DATA_Y_LSB_TESTY__MSK
BMM050_DATA_Y_LSB_TESTY__REG
BMM050_DATA_Z_LSB_BIT__POS
BMM050_DATA_Z_LSB_BIT__LEN
BMM050_DATA_Z_LSB_BIT__MSK
BMM050_DATA_Z_LSB_BIT__REG
BMM050_DATA_Z_LSB_TESTZ__POS
BMM050_DATA_Z_LSB_TESTZ__LEN
BMM050_DATA_Z_LSB_TESTZ__MSK
BMM050_DATA_Z_LSB_TESTZ__REG
BMM050_DATA_R_LSB_BIT__POS
BMM050_DATA_R_LSB_BIT__LEN
BMM050_DATA_R_LSB_BIT__MSK
BMM050_DATA_R_LSB_BIT__REG
BMM050_DATA_RDYSTAT__POS
BMM050_DATA_RDYSTAT__LEN
BMM050_DATA_RDYSTAT__MSK
BMM050_DATA_RDYSTAT__REG
BMM050_REMAPPED_BMX055_DATA_X_LSB_BIT__POS
BMM050_REMAPPED_BMX055_DATA_X_LSB_BIT__LEN
BMM050_REMAPPED_BMX055_DATA_X_LSB_BIT__MSK
BMM050_REMAPPED_BMX055_DATA_X_LSB_BIT__REG
BMM050_REMAPPED_BMX055_DATA_Y_LSB_BIT__POS
BMM050_REMAPPED_BMX055_DATA_Y_LSB_BIT__LEN
BMM050_REMAPPED_BMX055_DATA_Y_LSB_BIT__MSK
BMM050_REMAPPED_BMX055_DATA_Y_LSB_BIT__REG
BMM050_INT_STAT_DOR__POS
BMM050_INT_STAT_DOR__LEN
BMM050_INT_STAT_DOR__MSK
BMM050_INT_STAT_DOR__REG
BMM050_INT_STAT_OVRFLOW__POS
BMM050_INT_STAT_OVRFLOW__LEN
BMM050_INT_STAT_OVRFLOW__MSK
BMM050_INT_STAT_OVRFLOW__REG
BMM050_INT_STAT_HIGH_THZ__POS
BMM050_INT_STAT_HIGH_THZ__LEN
BMM050_INT_STAT_HIGH_THZ__MSK
BMM050_INT_STAT_HIGH_THZ__REG
BMM050_INT_STAT_HIGH_THY__POS
BMM050_INT_STAT_HIGH_THY__LEN
BMM050_INT_STAT_HIGH_THY__MSK
BMM050_INT_STAT_HIGH_THY__REG
BMM050_INT_STAT_HIGH_THX__POS
BMM050_INT_STAT_HIGH_THX__LEN
BMM050_INT_STAT_HIGH_THX__MSK
BMM050_INT_STAT_HIGH_THX__REG
BMM050_INT_STAT_LOW_THZ__POS
BMM050_INT_STAT_LOW_THZ__LEN
BMM050_INT_STAT_LOW_THZ__MSK
BMM050_INT_STAT_LOW_THZ__REG
BMM050_INT_STAT_LOW_THY__POS
BMM050_INT_STAT_LOW_THY__LEN
BMM050_INT_STAT_LOW_THY__MSK
BMM050_INT_STAT_LOW_THY__REG
BMM050_INT_STAT_LOW_THX__POS
BMM050_INT_STAT_LOW_THX__LEN
BMM050_INT_STAT_LOW_THX__MSK
BMM050_INT_STAT_LOW_THX__REG
BMM050_POWER_CONTROL_SOFT_RST_7__POS
BMM050_POWER_CONTROL_SOFT_RST_7__LEN
BMM050_POWER_CONTROL_SOFT_RST_7__MSK
BMM050_POWER_CONTROL_SOFT_RST_7__REG
Referenced by bmm050_soft_rst.
BMM050_POWER_CONTROL_SPI3_ENABLE__POS
BMM050_POWER_CONTROL_SPI3_ENABLE__LEN
BMM050_POWER_CONTROL_SPI3_ENABLE__MSK
BMM050_POWER_CONTROL_SPI3_ENABLE__REG
Referenced by bmm050_set_spi3.
BMM050_POWER_CONTROL_SOFT_RST_1__POS
BMM050_POWER_CONTROL_SOFT_RST_1__LEN
BMM050_POWER_CONTROL_SOFT_RST_1__MSK
BMM050_POWER_CONTROL_SOFT_RST_1__REG
Referenced by bmm050_soft_rst.
BMM050_POWER_CONTROL_POWER_CONTROL_BIT__POS
BMM050_POWER_CONTROL_POWER_CONTROL_BIT__LEN
BMM050_POWER_CONTROL_POWER_CONTROL_BIT__MSK
BMM050_POWER_CONTROL_POWER_CONTROL_BIT__REG
Referenced by bmm050_get_power_mode, bmm050_set_power_mode.
BMM050_CONTROL_ADVANCED_SELFTEST__POS
BMM050_CONTROL_ADVANCED_SELFTEST__LEN
BMM050_CONTROL_ADVANCED_SELFTEST__MSK
BMM050_CONTROL_ADVANCED_SELFTEST__REG
Referenced by bmm050_set_advanced_selftest, bmm050_get_advanced_selftest.
BMM050_CONTROL_SELFTEST__POS
BMM050_CONTROL_SELFTEST__LEN
BMM050_CONTROL_SELFTEST__MSK
BMM050_CONTROL_SELFTEST__REG
Referenced by bmm050_set_selftest.
BMM050_CONTROL_DATA_RATE__POS
BMM050_CONTROL_DATA_RATE__LEN
BMM050_CONTROL_DATA_RATE__MSK
BMM050_CONTROL_DATA_RATE__REG
Referenced by bmm050_set_data_rate, bmm050_get_data_rate.
BMM050_CONTROL_OPERATION_MODE__POS
BMM050_CONTROL_OPERATION_MODE__LEN
BMM050_CONTROL_OPERATION_MODE__MSK
BMM050_CONTROL_OPERATION_MODE__REG
Referenced by bmm050_set_functional_state, bmm050_get_functional_state.
BMM050_INT_CONTROL_DOR_EN__POS
BMM050_INT_CONTROL_DOR_EN__LEN
BMM050_INT_CONTROL_DOR_EN__MSK
BMM050_INT_CONTROL_DOR_EN__REG
BMM050_INT_CONTROL_OVRFLOW_EN__POS
BMM050_INT_CONTROL_OVRFLOW_EN__LEN
BMM050_INT_CONTROL_OVRFLOW_EN__MSK
BMM050_INT_CONTROL_OVRFLOW_EN__REG
BMM050_INT_CONTROL_HIGH_THZ_EN__POS
BMM050_INT_CONTROL_HIGH_THZ_EN__LEN
BMM050_INT_CONTROL_HIGH_THZ_EN__MSK
BMM050_INT_CONTROL_HIGH_THZ_EN__REG
BMM050_INT_CONTROL_HIGH_THY_EN__POS
BMM050_INT_CONTROL_HIGH_THY_EN__LEN
BMM050_INT_CONTROL_HIGH_THY_EN__MSK
BMM050_INT_CONTROL_HIGH_THY_EN__REG
BMM050_INT_CONTROL_HIGH_THX_EN__POS
BMM050_INT_CONTROL_HIGH_THX_EN__LEN
BMM050_INT_CONTROL_HIGH_THX_EN__MSK
BMM050_INT_CONTROL_HIGH_THX_EN__REG
BMM050_INT_CONTROL_LOW_THZ_EN__POS
BMM050_INT_CONTROL_LOW_THZ_EN__LEN
BMM050_INT_CONTROL_LOW_THZ_EN__MSK
BMM050_INT_CONTROL_LOW_THZ_EN__REG
BMM050_INT_CONTROL_LOW_THY_EN__POS
BMM050_INT_CONTROL_LOW_THY_EN__LEN
BMM050_INT_CONTROL_LOW_THY_EN__MSK
BMM050_INT_CONTROL_LOW_THY_EN__REG
BMM050_INT_CONTROL_LOW_THX_EN__POS
BMM050_INT_CONTROL_LOW_THX_EN__LEN
BMM050_INT_CONTROL_LOW_THX_EN__MSK
BMM050_INT_CONTROL_LOW_THX_EN__REG
BMM050_SENS_CONTROL_DRDY_EN__POS
BMM050_SENS_CONTROL_DRDY_EN__LEN
BMM050_SENS_CONTROL_DRDY_EN__MSK
BMM050_SENS_CONTROL_DRDY_EN__REG
BMM050_SENS_CONTROL_IE__POS
BMM050_SENS_CONTROL_IE__LEN
BMM050_SENS_CONTROL_IE__MSK
BMM050_SENS_CONTROL_IE__REG
BMM050_SENS_CONTROL_CHANNELZ__POS
BMM050_SENS_CONTROL_CHANNELZ__LEN
BMM050_SENS_CONTROL_CHANNELZ__MSK
BMM050_SENS_CONTROL_CHANNELZ__REG
BMM050_SENS_CONTROL_CHANNELY__POS
BMM050_SENS_CONTROL_CHANNELY__LEN
BMM050_SENS_CONTROL_CHANNELY__MSK
BMM050_SENS_CONTROL_CHANNELY__REG
Referenced by bmm050_set_control_measurement_y.
BMM050_SENS_CONTROL_CHANNELX__POS
BMM050_SENS_CONTROL_CHANNELX__LEN
BMM050_SENS_CONTROL_CHANNELX__MSK
BMM050_SENS_CONTROL_CHANNELX__REG
Referenced by bmm050_set_control_measurement_x.
BMM050_SENS_CONTROL_DR_POLARITY__POS
BMM050_SENS_CONTROL_DR_POLARITY__LEN
BMM050_SENS_CONTROL_DR_POLARITY__MSK
BMM050_SENS_CONTROL_DR_POLARITY__REG
BMM050_SENS_CONTROL_INTERRUPT_LATCH__POS
BMM050_SENS_CONTROL_INTERRUPT_LATCH__LEN
BMM050_SENS_CONTROL_INTERRUPT_LATCH__MSK
BMM050_SENS_CONTROL_INTERRUPT_LATCH__REG
BMM050_SENS_CONTROL_INTERRUPT_POLARITY__POS
BMM050_SENS_CONTROL_INTERRUPT_POLARITY__LEN
BMM050_SENS_CONTROL_INTERRUPT_POLARITY__MSK
BMM050_SENS_CONTROL_INTERRUPT_POLARITY__REG
BMM050_DIG_XYZ1_MSB__POS
BMM050_DIG_XYZ1_MSB__LEN
BMM050_DIG_XYZ1_MSB__MSK
BMM050_DIG_XYZ1_MSB__REG
E_BMM050_NULL_PTR
Error code definitions
Referenced by bmm050_set_functional_state, bmm050_get_functional_state, bmm050_read_mag_data_XYZ, bmm050_read_bmx055_remapped_mag_data_XYZ, bmm050_read_mag_data_XYZ_s32, bmm050_read_bmx055_remapped_mag_data_XYZ_s32, bmm050_read_register, bmm050_write_register, bmm050_set_selftest, bmm050_get_selftest_XYZ, bmm050_set_spi3, bmm050_set_data_rate, bmm050_get_data_rate, bmm050_perform_advanced_selftest, bmm050_set_advanced_selftest, bmm050_get_advanced_selftest, bmm050_get_power_mode, bmm050_set_power_mode, bmm050_get_rep_XY, bmm050_set_rep_XY, bmm050_get_rep_Z, bmm050_set_rep_Z, bmm050_set_control_measurement_x, bmm050_set_control_measurement_y, bmm050_soft_rst, bmm050_get_raw_xyz, bmm050_get_bmx055_remapped_raw_xyz, bmm150LibErrorMapping, readMagData, Magnetometer_setPowerMode, Magnetometer_setPresetMode, Magnetometer_setDataRate, Magnetometer_getPowerMode, Magnetometer_getPresetMode, Magnetometer_getDataRate, libErrorMapping.
ERROR
E_BMM050_OUT_OF_RANGE
Referenced by bmm050_set_presetmode, bmm050_set_functional_state.
BMM050_NULL
Referenced by bmm050_set_functional_state, bmm050_get_functional_state, bmm050_read_mag_data_XYZ, bmm050_read_bmx055_remapped_mag_data_XYZ, bmm050_read_mag_data_XYZ_s32, bmm050_read_bmx055_remapped_mag_data_XYZ_s32, bmm050_read_register, bmm050_write_register, bmm050_set_selftest, bmm050_get_selftest_XYZ, bmm050_set_spi3, bmm050_set_data_rate, bmm050_get_data_rate, bmm050_perform_advanced_selftest, bmm050_set_advanced_selftest, bmm050_get_advanced_selftest, bmm050_get_power_mode, bmm050_set_power_mode, bmm050_get_rep_XY, bmm050_set_rep_XY, bmm050_get_rep_Z, bmm050_set_rep_Z, bmm050_set_control_measurement_x, bmm050_set_control_measurement_y, bmm050_soft_rst, bmm050_get_raw_xyz, bmm050_get_bmx055_remapped_raw_xyz.
E_BMM050_UNDEFINED_MODE
Referenced by bmm050_get_presetmode.
BMM050_SOFT_RESET7_ON
Referenced by bmm050_soft_rst.
BMM050_SOFT_RESET1_ON
Referenced by bmm050_soft_rst.
BMM050_SOFT_RESET7_OFF
BMM050_SOFT_RESET1_OFF
BMM050_DELAY_SOFTRESET
Referenced by bmm050_soft_rst.
BMM050_DELAY_POWEROFF_SUSPEND
BMM050_DELAY_SUSPEND_SLEEP
Referenced by bmm050_set_functional_state.
BMM050_DELAY_SLEEP_ACTIVE
BMM050_DELAY_ACTIVE_SLEEP
BMM050_DELAY_SLEEP_SUSPEND
BMM050_DELAY_ACTIVE_SUSPEND
BMM050_DELAY_SLEEP_POWEROFF
BMM050_DELAY_ACTIVE_POWEROFF
BMM050_DELAY_SETTLING_TIME
Referenced by bmm050_init.
BMM050_MDELAY_DATA_TYPE
BMM050_X_AXIS
BMM050_Y_AXIS
BMM050_Z_AXIS
BMM050_RESISTANCE
BMM050_X
BMM050_Y
BMM050_Z
BMM050_XYZ
BMM050_CHANNEL_DISABLE
Referenced by bmm050_perform_advanced_selftest.
BMM050_CHANNEL_ENABLE
Referenced by bmm050_perform_advanced_selftest.
BMM050_OFF
Referenced by bmm050_set_functional_state.
BMM050_ON
Referenced by bmm050_init, bmm050_set_functional_state, bmm050_soft_rst.
BMM050_ADVANCED_SELFTEST_OFF
Referenced by bmm050_perform_advanced_selftest, bmm050_set_advanced_selftest.
BMM050_ADVANCED_SELFTEST_NEGATIVE
Referenced by bmm050_perform_advanced_selftest, bmm050_set_advanced_selftest.
BMM050_ADVANCED_SELFTEST_POSITIVE
Referenced by bmm050_perform_advanced_selftest, bmm050_set_advanced_selftest.
BMM050_NEGATIVE_SATURATION_Z
Referenced by bmm050_compensate_Z.
BMM050_POSITIVE_SATURATION_Z
Referenced by bmm050_compensate_Z.
BMM050_SPI_RD_MASK
BMM050_READ_SET
BMM050_WR_FUNC_PTR
BMM050_RD_FUNC_PTR
BMM050_GEN_READ_WRITE_DATA_LENGTH
Referenced by bmm050_init, bmm050_set_functional_state, bmm050_get_functional_state, bmm050_set_selftest, bmm050_set_spi3, bmm050_set_data_rate, bmm050_get_data_rate, bmm050_init_trim_registers, bmm050_set_advanced_selftest, bmm050_get_advanced_selftest, bmm050_get_power_mode, bmm050_set_power_mode, bmm050_get_rep_XY, bmm050_set_rep_XY, bmm050_get_rep_Z, bmm050_set_rep_Z, bmm050_set_control_measurement_x, bmm050_set_control_measurement_y, bmm050_soft_rst.
BMM050_TRIM_DATA_LENGTH
Referenced by bmm050_init_trim_registers.
BMM050_SELFTEST_DELAY
Referenced by bmm050_perform_advanced_selftest.
BMM050_SELFTEST_DATA_LENGTH
Referenced by bmm050_get_selftest_XYZ.
BMM050_ALL_DATA_FRAME_LENGTH
Frame length refers the x,y,z and r values
Referenced by bmm050_read_mag_data_XYZ, bmm050_read_bmx055_remapped_mag_data_XYZ, bmm050_read_mag_data_XYZ_s32, bmm050_read_bmx055_remapped_mag_data_XYZ_s32, bmm050_get_raw_xyz, bmm050_get_bmx055_remapped_raw_xyz.
BMM050_INIT_VALUE
Referenced by bmm050_init, bmm050_get_presetmode, bmm050_set_functional_state, bmm050_get_functional_state, bmm050_read_mag_data_XYZ, bmm050_read_bmx055_remapped_mag_data_XYZ, bmm050_read_mag_data_XYZ_s32, bmm050_read_bmx055_remapped_mag_data_XYZ_s32, bmm050_set_selftest, bmm050_get_selftest_XYZ, bmm050_set_spi3, bmm050_set_data_rate, bmm050_get_data_rate, bmm050_perform_advanced_selftest, bmm050_init_trim_registers, bmm050_set_advanced_selftest, bmm050_get_advanced_selftest, bmm050_get_power_mode, bmm050_set_power_mode, bmm050_get_rep_XY, bmm050_set_rep_XY, bmm050_get_rep_Z, bmm050_set_rep_Z, bmm050_compensate_X, bmm050_compensate_X_s32, bmm050_compensate_Y, bmm050_compensate_Y_s32, bmm050_compensate_Z, bmm050_compensate_Z_s32, bmm050_set_control_measurement_x, bmm050_set_control_measurement_y, bmm050_soft_rst, bmm050_get_raw_xyz, bmm050_get_bmx055_remapped_raw_xyz.
BMM050_GET_BITSLICE
Referenced by bmm050_get_functional_state, bmm050_read_mag_data_XYZ, bmm050_read_bmx055_remapped_mag_data_XYZ, bmm050_read_mag_data_XYZ_s32, bmm050_read_bmx055_remapped_mag_data_XYZ_s32, bmm050_get_selftest_XYZ, bmm050_get_data_rate, bmm050_init_trim_registers, bmm050_get_advanced_selftest, bmm050_get_power_mode, bmm050_get_raw_xyz, bmm050_get_bmx055_remapped_raw_xyz.
BMM050_SET_BITSLICE
Referenced by bmm050_set_functional_state, bmm050_set_selftest, bmm050_set_spi3, bmm050_set_data_rate, bmm050_set_advanced_selftest, bmm050_set_power_mode, bmm050_set_control_measurement_x, bmm050_set_control_measurement_y, bmm050_soft_rst.
BMM050_OVERFLOW_OUTPUT
Referenced by bmm050_compensate_X, bmm050_compensate_X_s32, bmm050_compensate_Y, bmm050_compensate_Y_s32, bmm050_compensate_Z.
BMM050_OVERFLOW_OUTPUT_S32
Referenced by bmm050_compensate_X_s32, bmm050_compensate_Y_s32, bmm050_compensate_Z_s32, readMagData.
BMM050_OVERFLOW_OUTPUT_FLOAT
BMM050_FLIP_OVERFLOW_ADCVAL
Referenced by bmm050_compensate_X, bmm050_compensate_Y.
BMM050_HALL_OVERFLOW_ADCVAL
Referenced by bmm050_compensate_Z, bmm050_compensate_Z_s32.
BMM050_PRESETMODE_LOWPOWER
Referenced by bmm050_get_presetmode, bmm050_set_presetmode.
BMM050_PRESETMODE_REGULAR
Referenced by bmm050_init, bmm050_get_presetmode, bmm050_set_presetmode.
BMM050_PRESETMODE_HIGHACCURACY
Referenced by bmm050_get_presetmode, bmm050_set_presetmode.
BMM050_PRESETMODE_ENHANCED
Referenced by bmm050_get_presetmode, bmm050_set_presetmode.
BMM050_LOWPOWER_DR
Referenced by bmm050_get_presetmode, bmm050_set_presetmode.
BMM050_REGULAR_DR
Referenced by bmm050_get_presetmode, bmm050_set_presetmode.
BMM050_HIGHACCURACY_DR
Referenced by bmm050_get_presetmode, bmm050_set_presetmode.
BMM050_ENHANCED_DR
Referenced by bmm050_get_presetmode, bmm050_set_presetmode.
BMM050_LOWPOWER_REPXY
Referenced by bmm050_get_presetmode, bmm050_set_presetmode.
BMM050_REGULAR_REPXY
Referenced by bmm050_get_presetmode, bmm050_set_presetmode.
BMM050_HIGHACCURACY_REPXY
Referenced by bmm050_get_presetmode, bmm050_set_presetmode.
BMM050_ENHANCED_REPXY
Referenced by bmm050_get_presetmode, bmm050_set_presetmode.
BMM050_LOWPOWER_REPZ
Referenced by bmm050_get_presetmode, bmm050_set_presetmode, bmm050_perform_advanced_selftest.
BMM050_REGULAR_REPZ
Referenced by bmm050_get_presetmode, bmm050_set_presetmode.
BMM050_HIGHACCURACY_REPZ
Referenced by bmm050_get_presetmode, bmm050_set_presetmode.
BMM050_ENHANCED_REPZ
Referenced by bmm050_get_presetmode, bmm050_set_presetmode.
BMM050_DR_10HZ
BMM050_DR_02HZ
BMM050_DR_06HZ
BMM050_DR_08HZ
BMM050_DR_15HZ
BMM050_DR_20HZ
BMM050_DR_25HZ
BMM050_DR_30HZ
BMM050_DATA_RATE_10HZ
BMM050_DATA_RATE_02HZ
BMM050_DATA_RATE_06HZ
BMM050_DATA_RATE_08HZ
BMM050_DATA_RATE_15HZ
BMM050_DATA_RATE_20HZ
BMM050_DATA_RATE_25HZ
BMM050_DATA_RATE_30HZ
BMM050_SHIFT_BIT_POSITION_BY_01_BIT
Referenced by bmm050_get_selftest_XYZ, bmm050_compensate_Z, bmm050_compensate_Z_s32.
BMM050_SHIFT_BIT_POSITION_BY_02_BITS
Referenced by bmm050_compensate_Z, bmm050_compensate_Z_s32.
BMM050_SHIFT_BIT_POSITION_BY_03_BITS
Referenced by bmm050_compensate_X, bmm050_compensate_Y.
BMM050_SHIFT_BIT_POSITION_BY_05_BITS
Referenced by bmm050_read_mag_data_XYZ, bmm050_read_bmx055_remapped_mag_data_XYZ, bmm050_read_mag_data_XYZ_s32, bmm050_read_bmx055_remapped_mag_data_XYZ_s32, bmm050_get_raw_xyz, bmm050_get_bmx055_remapped_raw_xyz.
BMM050_SHIFT_BIT_POSITION_BY_06_BITS
Referenced by bmm050_read_mag_data_XYZ, bmm050_read_bmx055_remapped_mag_data_XYZ, bmm050_read_mag_data_XYZ_s32, bmm050_read_bmx055_remapped_mag_data_XYZ_s32, bmm050_get_raw_xyz, bmm050_get_bmx055_remapped_raw_xyz.
BMM050_SHIFT_BIT_POSITION_BY_07_BITS
Referenced by bmm050_read_mag_data_XYZ, bmm050_read_bmx055_remapped_mag_data_XYZ, bmm050_read_mag_data_XYZ_s32, bmm050_read_bmx055_remapped_mag_data_XYZ_s32, bmm050_compensate_X, bmm050_compensate_Y, bmm050_get_raw_xyz, bmm050_get_bmx055_remapped_raw_xyz.
BMM050_SHIFT_BIT_POSITION_BY_08_BITS
Referenced by bmm050_init_trim_registers.
BMM050_SHIFT_BIT_POSITION_BY_09_BITS
Referenced by bmm050_compensate_X, bmm050_compensate_Y.
BMM050_SHIFT_BIT_POSITION_BY_12_BITS
Referenced by bmm050_compensate_X, bmm050_compensate_Y.
BMM050_SHIFT_BIT_POSITION_BY_13_BITS
Referenced by bmm050_compensate_X, bmm050_compensate_Y.
BMM050_SHIFT_BIT_POSITION_BY_16_BITS
Referenced by bmm050_compensate_Z, bmm050_compensate_Z_s32.
BMM050_SHIFT_BIT_POSITION_BY_14_BITS
Referenced by bmm050_compensate_X, bmm050_compensate_Y.
BMM050_SHIFT_BIT_POSITION_BY_15_BITS
Referenced by bmm050_compensate_Z, bmm050_compensate_Z_s32.
BMM050_DATA_FRAME_SIZE
Referenced by bmm050_read_mag_data_XYZ, bmm050_read_bmx055_remapped_mag_data_XYZ, bmm050_read_mag_data_XYZ_s32, bmm050_read_bmx055_remapped_mag_data_XYZ_s32, bmm050_get_raw_xyz, bmm050_get_bmx055_remapped_raw_xyz.
BMM050_INIT_DATA_SIZE
Referenced by bmm050_init.
BMM050_CHIP_ID_DATA
Referenced by bmm050_init.
BMM050_SELFTEST_DATA_SIZE
Referenced by bmm050_get_selftest_XYZ.
BMM050_TRIM_DATA_SIZE
Referenced by bmm050_init_trim_registers.
BMM050_XLSB_DATA
Referenced by bmm050_read_mag_data_XYZ, bmm050_read_mag_data_XYZ_s32, bmm050_get_selftest_XYZ, bmm050_get_raw_xyz, bmm050_get_bmx055_remapped_raw_xyz.
BMM050_XMSB_DATA
Referenced by bmm050_read_mag_data_XYZ, bmm050_read_mag_data_XYZ_s32.
BMM050_YLSB_DATA
Referenced by bmm050_read_mag_data_XYZ, bmm050_read_mag_data_XYZ_s32, bmm050_get_selftest_XYZ, bmm050_get_raw_xyz, bmm050_get_bmx055_remapped_raw_xyz.
BMM050_YMSB_DATA
Referenced by bmm050_read_mag_data_XYZ, bmm050_read_mag_data_XYZ_s32.
BMM050_ZLSB_DATA
Referenced by bmm050_read_mag_data_XYZ, bmm050_read_bmx055_remapped_mag_data_XYZ, bmm050_read_mag_data_XYZ_s32, bmm050_read_bmx055_remapped_mag_data_XYZ_s32, bmm050_get_selftest_XYZ, bmm050_get_raw_xyz, bmm050_get_bmx055_remapped_raw_xyz.
BMM050_ZMSB_DATA
Referenced by bmm050_read_mag_data_XYZ, bmm050_read_bmx055_remapped_mag_data_XYZ, bmm050_read_mag_data_XYZ_s32, bmm050_read_bmx055_remapped_mag_data_XYZ_s32.
BMM050_RLSB_DATA
Referenced by bmm050_read_mag_data_XYZ, bmm050_read_bmx055_remapped_mag_data_XYZ, bmm050_read_mag_data_XYZ_s32, bmm050_read_bmx055_remapped_mag_data_XYZ_s32, bmm050_get_raw_xyz, bmm050_get_bmx055_remapped_raw_xyz.
BMM050_RMSB_DATA
Referenced by bmm050_read_mag_data_XYZ, bmm050_read_bmx055_remapped_mag_data_XYZ, bmm050_read_mag_data_XYZ_s32, bmm050_read_bmx055_remapped_mag_data_XYZ_s32, bmm050_get_raw_xyz, bmm050_get_bmx055_remapped_raw_xyz.
BMM050_TRIM_DIG_Z1_LSB_DATA
Referenced by bmm050_init_trim_registers.
BMM050_TRIM_DIG_Z1_MSB_DATA
Referenced by bmm050_init_trim_registers.
BMM050_TRIM_DIG_Z2_LSB_DATA
Referenced by bmm050_init_trim_registers.
BMM050_TRIM_DIG_Z2_MSB_DATA
Referenced by bmm050_init_trim_registers.
BMM050_TRIM_DIG_Z3_LSB_DATA
Referenced by bmm050_init_trim_registers.
BMM050_TRIM_DIG_Z3_MSB_DATA
Referenced by bmm050_init_trim_registers.
BMM050_TRIM_DIG_Z4_LSB_DATA
Referenced by bmm050_init_trim_registers.
BMM050_TRIM_DIG_Z4_MSB_DATA
Referenced by bmm050_init_trim_registers.
BMM050_TRIM_DIG_XYZ1_LSB_DATA
Referenced by bmm050_init_trim_registers.
BMM050_TRIM_DIG_XYZ1_MSB_DATA
Referenced by bmm050_init_trim_registers.
BMM050_REMAPPED_YLSB_DATA
Referenced by bmm050_read_bmx055_remapped_mag_data_XYZ, bmm050_read_bmx055_remapped_mag_data_XYZ_s32.
BMM050_REMAPPED_YMSB_DATA
Referenced by bmm050_read_bmx055_remapped_mag_data_XYZ, bmm050_read_bmx055_remapped_mag_data_XYZ_s32.
BMM050_REMAPPED_XLSB_DATA
Referenced by bmm050_read_bmx055_remapped_mag_data_XYZ, bmm050_read_bmx055_remapped_mag_data_XYZ_s32.
BMM050_REMAPPED_XMSB_DATA
Referenced by bmm050_read_bmx055_remapped_mag_data_XYZ_s32.
BMM050_RETURN_FUNCTION_TYPE bmm050_init(struct bmm050_t *bmm050)
This function is used for initialize bus read and bus write functions assign the chip id and device address chip id is read in the register 0x40 bit from 0 to 7.
While changing the parameter of the bmm050 consider the following point: Changing the reference value of the parameter will changes the local copy or local reference make sure your changes will not affect the reference value of the parameter (Better case don't change the reference value of the parameter) results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_DATA_SIZE, BMM050_INIT_VALUE, bmm050_set_power_mode, BMM050_ON, bmm050_t::delay_msec, BMM050_DELAY_SETTLING_TIME, bmm050_t::dev_addr, BMM050_CHIP_ID, BMM050_GEN_READ_WRITE_DATA_LENGTH, bmm050_t::company_id, BMM050_CHIP_ID_DATA, bmm050_init_trim_registers, bmm050_set_presetmode, BMM050_PRESETMODE_REGULAR.
Referenced by Bmm150Utils_initialize.
BMM050_RETURN_FUNCTION_TYPE bmm050_read_mag_data_XYZ(struct bmm050_mag_data_s16_t *mag_data)
This API reads compensated Magnetometer data of X,Y,Z values from location 0x42 to 0x49.
mag_data : The data of mag compensated XYZ data results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_DATA_FRAME_SIZE, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_DATA_X_LSB, BMM050_ALL_DATA_FRAME_LENGTH, BMM050_XLSB_DATA, BMM050_GET_BITSLICE, BMM050_XMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_05_BITS, BMM050_YLSB_DATA, BMM050_YMSB_DATA, BMM050_ZLSB_DATA, BMM050_ZMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_07_BITS, bmm050_mag_data_s16_t::data_ready, BMM050_RLSB_DATA, BMM050_RMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_06_BITS, bmm050_mag_data_s16_t::datax, bmm050_compensate_X, bmm050_mag_data_s16_t::datay, bmm050_compensate_Y, bmm050_mag_data_s16_t::dataz, bmm050_compensate_Z, bmm050_mag_data_s16_t::resistance.
Referenced by bmm050_perform_advanced_selftest.
BMM050_RETURN_FUNCTION_TYPE bmm050_read_bmx055_remapped_mag_data_XYZ(struct bmm050_remapped_mag_s16_data_t *mag_data)
This API reads remapped compensated Magnetometer data of X,Y,Z values.
In this function X and Y axis is remapped X is read from the address 0x44 & 0x45 Y is read from the address 0x42 & 0x43 this API is only applicable for BMX055 sensor mag_data : The data of remapped compensated mag xyz data results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_DATA_FRAME_SIZE, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_REMAPPED_BMX055_DATA_Y_LSB, BMM050_ALL_DATA_FRAME_LENGTH, BMM050_REMAPPED_YLSB_DATA, BMM050_GET_BITSLICE, BMM050_REMAPPED_YMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_05_BITS, BMM050_REMAPPED_XLSB_DATA, BMM050_ZLSB_DATA, BMM050_ZMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_07_BITS, bmm050_remapped_mag_s16_data_t::data_ready, BMM050_RLSB_DATA, BMM050_RMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_06_BITS, bmm050_remapped_mag_s16_data_t::datax, bmm050_compensate_X, bmm050_remapped_mag_s16_data_t::datay, bmm050_compensate_Y, bmm050_remapped_mag_s16_data_t::dataz, bmm050_compensate_Z, bmm050_remapped_mag_s16_data_t::resistance.
BMM050_RETURN_FUNCTION_TYPE bmm050_read_mag_data_XYZ_s32(struct bmm050_mag_s32_data_t *mag_data)
This API reads compensated magnetometer data of X,Y,Z values.
The output value of compensated X, Y, Z as s32 mag_data : The data of compensated XYZ data results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_DATA_FRAME_SIZE, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_DATA_X_LSB, BMM050_ALL_DATA_FRAME_LENGTH, BMM050_XLSB_DATA, BMM050_GET_BITSLICE, BMM050_XMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_05_BITS, BMM050_YLSB_DATA, BMM050_YMSB_DATA, BMM050_ZLSB_DATA, BMM050_ZMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_07_BITS, bmm050_mag_s32_data_t::data_ready, BMM050_RLSB_DATA, BMM050_RMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_06_BITS, bmm050_mag_s32_data_t::datax, bmm050_compensate_X_s32, bmm050_mag_s32_data_t::datay, bmm050_compensate_Y_s32, bmm050_mag_s32_data_t::dataz, bmm050_compensate_Z_s32, bmm050_mag_s32_data_t::resistance.
Referenced by readMagData.
BMM050_RETURN_FUNCTION_TYPE bmm050_read_bmx055_remapped_mag_data_XYZ_s32(struct bmm050_remapped_mag_s32_data_t *mag_data)
This API reads remapped compensated magnetometer data of X,Y,Z values.
The output value of compensated X, Y, Z as s32 In this function X and Y axis is remapped X is read from the address 0x44 & 0x45 Y is read from the address 0x42 & 0x43 this API is only applicable for BMX055 sensor mag_data : The data of remapped compensated XYZ data results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_DATA_FRAME_SIZE, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_REMAPPED_BMX055_DATA_Y_LSB, BMM050_ALL_DATA_FRAME_LENGTH, BMM050_REMAPPED_YLSB_DATA, BMM050_GET_BITSLICE, BMM050_REMAPPED_YMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_05_BITS, BMM050_REMAPPED_XLSB_DATA, BMM050_REMAPPED_XMSB_DATA, BMM050_ZLSB_DATA, BMM050_ZMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_07_BITS, bmm050_remapped_mag_s32_data_t::data_ready, BMM050_RLSB_DATA, BMM050_RMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_06_BITS, bmm050_remapped_mag_s32_data_t::datax, bmm050_compensate_X_s32, bmm050_remapped_mag_s32_data_t::datay, bmm050_compensate_Y_s32, bmm050_remapped_mag_s32_data_t::dataz, bmm050_compensate_Z_s32, bmm050_remapped_mag_s32_data_t::resistance.
BMM050_RETURN_FUNCTION_TYPE bmm050_read_register(u8 v_addr_u8, u8 *v_data_u8, u8 v_len_u8)
This API reads the data from the given register.
v_addr_u8 -> Address of the register v_data_u8 -> The data from the register v_len_u8 -> no of bytes to read results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr.
BMM050_RETURN_FUNCTION_TYPE bmm050_write_register(u8 v_addr_u8, u8 *v_data_u8, u8 v_len_u8)
This API write the data to the given register.
v_addr_u8 -> Address of the register v_data_u8 -> The data from the register v_len_u8 -> no of bytes to read results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr.
BMM050_RETURN_FUNCTION_TYPE bmm050_set_selftest(u8 v_selftest_u8)
This API used to set the self test of the sensor in the register 0x4C bit 0.
v_selftest_u8 : The value of selftest write 0x01 to start self test results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_CONTROL_SELFTEST__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_SET_BITSLICE.
BMM050_RETURN_FUNCTION_TYPE bmm050_get_selftest_XYZ(u8 *v_selftest_xyz)
This API used to read the selftest of the sensor.
v_selftest_xyz The self test value of XYZ results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_SELFTEST_DATA_SIZE, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_DATA_X_LSB_TESTX__REG, BMM050_SELFTEST_DATA_LENGTH, BMM050_GET_BITSLICE, BMM050_ZLSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_01_BIT, BMM050_YLSB_DATA, BMM050_XLSB_DATA.
BMM050_RETURN_FUNCTION_TYPE bmm050_set_spi3(u8 v_value_u8)
This API used to set the spi3 in the register 0x4B bit 2.
v_value_u8 : the value of spi3 value Description 0 Disable 1 Enable results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_POWER_CONTROL_SPI3_ENABLE__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_SET_BITSLICE.
BMM050_RETURN_FUNCTION_TYPE bmm050_set_data_rate(u8 v_data_rate_u8)
This API used to set the data rate of the sensor in the register 0x4C bit 3 to 5.
v_data_rate_u8 : The value of data rate value Description 0x00 BMM050_DATA_RATE_10HZ 0x01 BMM050_DATA_RATE_02HZ 0x02 BMM050_DATA_RATE_06HZ 0x03 BMM050_DATA_RATE_08HZ 0x04 BMM050_DATA_RATE_15HZ 0x05 BMM050_DATA_RATE_20HZ 0x06 BMM050_DATA_RATE_25HZ 0x07 BMM050_DATA_RATE_30HZ results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_CONTROL_DATA_RATE__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_SET_BITSLICE.
Referenced by bmm050_set_presetmode, Magnetometer_setDataRate.
BMM050_RETURN_FUNCTION_TYPE bmm050_get_data_rate(u8 *v_data_rate_u8)
This API used to get the data rate of the sensor in the register 0x4C bit 3 to 5.
v_data_rate_u8 : The value of data rate value Description 0x00 BMM050_DATA_RATE_10HZ 0x01 BMM050_DATA_RATE_02HZ 0x02 BMM050_DATA_RATE_06HZ 0x03 BMM050_DATA_RATE_08HZ 0x04 BMM050_DATA_RATE_15HZ 0x05 BMM050_DATA_RATE_20HZ 0x06 BMM050_DATA_RATE_25HZ 0x07 BMM050_DATA_RATE_30HZ results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_CONTROL_DATA_RATE__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_GET_BITSLICE.
Referenced by bmm050_get_presetmode, Magnetometer_getDataRate.
BMM050_RETURN_FUNCTION_TYPE bmm050_set_functional_state(u8 v_functional_state_u8)
This API used to set the functional state in the register 0x4C and 0x4B.
0x4C bit 1 and 2 0x4B bit 0 v_functional_state_u8 The value of functional mode value functional state 0x00 BMM050_NORMAL_MODE 0x01 BMM050_SUSPEND_MODE 0x02 BMM050_FORCED_MODE 0x03 BMM050_SLEEP_MODE results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, BMM050_NORMAL_MODE, bmm050_get_power_mode, BMM050_OFF, bmm050_set_power_mode, BMM050_ON, bmm050_t::delay_msec, BMM050_DELAY_SUSPEND_SLEEP, bmm050_t::dev_addr, BMM050_CONTROL_OPERATION_MODE__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_SET_BITSLICE, BMM050_SUSPEND_MODE, BMM050_FORCED_MODE, BMM050_SLEEP_MODE, E_BMM050_OUT_OF_RANGE.
Referenced by bmm050_perform_advanced_selftest, Magnetometer_setPowerMode, Bmm150Utils_initialize.
BMM050_RETURN_FUNCTION_TYPE bmm050_get_functional_state(u8 *v_functional_state_u8)
This API used to get the functional state in the register 0x4C bit 1 and 2.
v_functional_state_u8 The value of functional mode value functional state 0x00 Normal 0x03 Sleep If user set the functional state as Force mode(0x01) and read the register it returns the value as 0x03 that is sleep mode. results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_CONTROL_OPERATION_MODE__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_GET_BITSLICE.
Referenced by Magnetometer_getPowerMode.
BMM050_RETURN_FUNCTION_TYPE bmm050_perform_advanced_selftest(s16 *v_diff_z_s16)
This API used to perform the advanced self test.
v_diff_z_s16 : The output of advance self test results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_set_functional_state, BMM050_SLEEP_MODE, bmm050_set_rep_Z, BMM050_LOWPOWER_REPZ, bmm050_set_control_measurement_x, BMM050_CHANNEL_DISABLE, bmm050_set_control_measurement_y, bmm050_set_advanced_selftest, BMM050_ADVANCED_SELFTEST_POSITIVE, BMM050_FORCED_MODE, bmm050_t::delay_msec, BMM050_SELFTEST_DELAY, bmm050_read_mag_data_XYZ, bmm050_mag_data_s16_t::dataz, BMM050_ADVANCED_SELFTEST_NEGATIVE, BMM050_ADVANCED_SELFTEST_OFF, BMM050_CHANNEL_ENABLE.
BMM050_RETURN_FUNCTION_TYPE bmm050_init_trim_registers(void)
This API used to get the trim values.
results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_TRIM_DATA_SIZE, BMM050_INIT_VALUE, bmm050_t::dev_addr, BMM050_DIG_X1, bmm050_t::dig_x1, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_DIG_Y1, bmm050_t::dig_y1, BMM050_DIG_X2, bmm050_t::dig_x2, BMM050_DIG_Y2, bmm050_t::dig_y2, BMM050_DIG_XY1, bmm050_t::dig_xy1, BMM050_DIG_XY2, bmm050_t::dig_xy2, BMM050_DIG_Z1_LSB, BMM050_TRIM_DATA_LENGTH, bmm050_t::dig_z1, BMM050_TRIM_DIG_Z1_MSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_08_BITS, BMM050_TRIM_DIG_Z1_LSB_DATA, BMM050_DIG_Z2_LSB, bmm050_t::dig_z2, BMM050_TRIM_DIG_Z2_MSB_DATA, BMM050_TRIM_DIG_Z2_LSB_DATA, BMM050_DIG_Z3_LSB, bmm050_t::dig_z3, BMM050_TRIM_DIG_Z3_MSB_DATA, BMM050_TRIM_DIG_Z3_LSB_DATA, BMM050_DIG_Z4_LSB, bmm050_t::dig_z4, BMM050_TRIM_DIG_Z4_MSB_DATA, BMM050_TRIM_DIG_Z4_LSB_DATA, BMM050_DIG_XYZ1_LSB, BMM050_TRIM_DIG_XYZ1_MSB_DATA, BMM050_GET_BITSLICE, BMM050_DIG_XYZ1_MSB, bmm050_t::dig_xyz1, BMM050_TRIM_DIG_XYZ1_LSB_DATA.
Referenced by bmm050_init.
BMM050_RETURN_FUNCTION_TYPE bmm050_set_advanced_selftest(u8 v_advanced_selftest_u8)
This API used to set the advanced self test in the register 0x4C bit 6 and 7.
v_advanced_selftest_u8 : The output value of advanced self test value Status 0 BMM050_ADVANCED_SELFTEST_OFF 2 BMM050_ADVANCED_SELFTEST_NEGATIVE 3 BMM050_ADVANCED_SELFTEST_POSITIVE results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, BMM050_ADVANCED_SELFTEST_OFF, bmm050_t::dev_addr, BMM050_CONTROL_ADVANCED_SELFTEST__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_SET_BITSLICE, BMM050_ADVANCED_SELFTEST_POSITIVE, BMM050_ADVANCED_SELFTEST_NEGATIVE.
Referenced by bmm050_perform_advanced_selftest.
BMM050_RETURN_FUNCTION_TYPE bmm050_get_advanced_selftest(u8 *v_advanced_selftest_u8)
This API used to get the advanced self test in the register 0x4C bit 6 and 7.
v_advanced_selftest_u8 : The output value of advanced self test value Status 0 BMM050_ADVANCED_SELFTEST_OFF 2 BMM050_ADVANCED_SELFTEST_NEGATIVE 3 BMM050_ADVANCED_SELFTEST_POSITIVE results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_CONTROL_ADVANCED_SELFTEST__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_GET_BITSLICE.
BMM050_RETURN_FUNCTION_TYPE bmm050_get_power_mode(u8 *v_power_mode_u8)
This API used to get the power control bit in the register 0x4B bit 0.
v_power_mode_u8 : The value of power control bit enable value status 0 Disable the power control bit 1 Enable the power control bit results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_POWER_CONTROL_POWER_CONTROL_BIT__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_GET_BITSLICE.
Referenced by bmm050_set_functional_state.
BMM050_RETURN_FUNCTION_TYPE bmm050_set_power_mode(u8 v_power_mode_u8)
This API used to set the power control bit in the register 0x4B bit 0.
v_power_mode_u8 : The value of power control bit enable value status 0 Disable the power control bit 1 Enable the power control bit results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_POWER_CONTROL_POWER_CONTROL_BIT__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_SET_BITSLICE.
Referenced by bmm050_init, bmm050_set_functional_state.
BMM050_RETURN_FUNCTION_TYPE bmm050_get_rep_XY(u8 *v_rep_xy_u8)
This API used to get the x and y repetition in the register 0x51 bit 0 to 7.
v_rep_xy_u8 : The value of x and y repetitions results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_REP_XY, BMM050_GEN_READ_WRITE_DATA_LENGTH.
Referenced by bmm050_get_presetmode.
BMM050_RETURN_FUNCTION_TYPE bmm050_set_rep_XY(u8 v_rep_xy_u8)
This API used to set the x and y repetition in the register 0x51 bit 0 to 7.
v_rep_xy_u8 : The value of x and y repetitions results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_REP_XY, BMM050_GEN_READ_WRITE_DATA_LENGTH.
Referenced by bmm050_set_presetmode.
BMM050_RETURN_FUNCTION_TYPE bmm050_get_rep_Z(u8 *v_rep_z_u8)
This API used to get the z repetition in the register 0x52 bit 0 to 7.
v_rep_z_u8 : The value of z repetitions results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_REP_Z, BMM050_GEN_READ_WRITE_DATA_LENGTH.
Referenced by bmm050_get_presetmode.
BMM050_RETURN_FUNCTION_TYPE bmm050_set_rep_Z(u8 v_rep_z_u8)
This API used to set the z repetition in the register 0x52 bit 0 to 7.
v_rep_z_u8 : The value of z repetitions results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_REP_Z, BMM050_GEN_READ_WRITE_DATA_LENGTH.
Referenced by bmm050_set_presetmode, bmm050_perform_advanced_selftest.
BMM050_RETURN_FUNCTION_TYPE bmm050_get_presetmode(u8 *v_presetmode_u8)
This API used to get the preset modes.
The preset mode setting is depend on Data Rate, XY and Z repetitions v_presetmode_u8 The value of selected preset mode value preset_mode 1 BMM050_PRESETMODE_LOWPOWER 2 BMM050_PRESETMODE_REGULAR 3 BMM050_PRESETMODE_HIGHACCURACY 4 BMM050_PRESETMODE_ENHANCED results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, bmm050_get_data_rate, bmm050_get_rep_XY, bmm050_get_rep_Z, BMM050_LOWPOWER_DR, BMM050_LOWPOWER_REPXY, BMM050_LOWPOWER_REPZ, BMM050_PRESETMODE_LOWPOWER, BMM050_REGULAR_DR, BMM050_REGULAR_REPXY, BMM050_REGULAR_REPZ, BMM050_PRESETMODE_REGULAR, BMM050_HIGHACCURACY_DR, BMM050_HIGHACCURACY_REPXY, BMM050_HIGHACCURACY_REPZ, BMM050_PRESETMODE_HIGHACCURACY, BMM050_ENHANCED_DR, BMM050_ENHANCED_REPXY, BMM050_ENHANCED_REPZ, BMM050_PRESETMODE_ENHANCED, E_BMM050_UNDEFINED_MODE.
Referenced by Magnetometer_getPresetMode.
BMM050_RETURN_FUNCTION_TYPE bmm050_set_presetmode(u8 v_presetmode_u8)
This API used to set the preset modes.
The preset mode setting is depend on Data Rate, XY and Z repetitions v_presetmode_u8 The value of selected preset mode value preset_mode 1 BMM050_PRESETMODE_LOWPOWER 2 BMM050_PRESETMODE_REGULAR 3 BMM050_PRESETMODE_HIGHACCURACY 4 BMM050_PRESETMODE_ENHANCED results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_PRESETMODE_LOWPOWER, bmm050_set_data_rate, BMM050_LOWPOWER_DR, bmm050_set_rep_XY, BMM050_LOWPOWER_REPXY, bmm050_set_rep_Z, BMM050_LOWPOWER_REPZ, BMM050_PRESETMODE_REGULAR, BMM050_REGULAR_DR, BMM050_REGULAR_REPXY, BMM050_REGULAR_REPZ, BMM050_PRESETMODE_HIGHACCURACY, BMM050_HIGHACCURACY_DR, BMM050_HIGHACCURACY_REPXY, BMM050_HIGHACCURACY_REPZ, BMM050_PRESETMODE_ENHANCED, BMM050_ENHANCED_DR, BMM050_ENHANCED_REPXY, BMM050_ENHANCED_REPZ, E_BMM050_OUT_OF_RANGE.
Referenced by bmm050_init, Magnetometer_setPresetMode.
s16 bmm050_compensate_X(s16 mag_data_x, u16 data_r)
This API used to get the compensated X data the out put of X as s16.
mag_data_x : The value of raw X data data_r : The value of R data results of compensated X data value output as s16
References BMM050_INIT_VALUE, BMM050_FLIP_OVERFLOW_ADCVAL, bmm050_t::dig_xyz1, BMM050_SHIFT_BIT_POSITION_BY_14_BITS, BMM050_OVERFLOW_OUTPUT, bmm050_t::dig_xy2, BMM050_SHIFT_BIT_POSITION_BY_07_BITS, bmm050_t::dig_xy1, BMM050_SHIFT_BIT_POSITION_BY_09_BITS, bmm050_t::dig_x2, BMM050_SHIFT_BIT_POSITION_BY_12_BITS, BMM050_SHIFT_BIT_POSITION_BY_13_BITS, bmm050_t::dig_x1, BMM050_SHIFT_BIT_POSITION_BY_03_BITS.
Referenced by bmm050_read_mag_data_XYZ, bmm050_read_bmx055_remapped_mag_data_XYZ, bmm050_compensate_X_s32.
s32 bmm050_compensate_X_s32(s16 mag_data_x, u16 data_r)
This API used to get the compensated X data the out put of X as s32.
mag_data_x : The value of raw X data data_r : The value of R data results of compensated X data value output as s32
References BMM050_INIT_VALUE, bmm050_compensate_X, BMM050_OVERFLOW_OUTPUT, BMM050_OVERFLOW_OUTPUT_S32.
Referenced by bmm050_read_mag_data_XYZ_s32, bmm050_read_bmx055_remapped_mag_data_XYZ_s32.
s16 bmm050_compensate_Y(s16 mag_data_y, u16 data_r)
This API used to get the compensated Y data the out put of Y as s16.
mag_data_y : The value of raw Y data data_r : The value of R data results of compensated Y data value output as s16
References BMM050_INIT_VALUE, BMM050_FLIP_OVERFLOW_ADCVAL, bmm050_t::dig_xyz1, BMM050_SHIFT_BIT_POSITION_BY_14_BITS, BMM050_OVERFLOW_OUTPUT, bmm050_t::dig_xy2, BMM050_SHIFT_BIT_POSITION_BY_07_BITS, bmm050_t::dig_xy1, BMM050_SHIFT_BIT_POSITION_BY_09_BITS, bmm050_t::dig_y2, BMM050_SHIFT_BIT_POSITION_BY_12_BITS, BMM050_SHIFT_BIT_POSITION_BY_13_BITS, bmm050_t::dig_y1, BMM050_SHIFT_BIT_POSITION_BY_03_BITS.
Referenced by bmm050_read_mag_data_XYZ, bmm050_read_bmx055_remapped_mag_data_XYZ, bmm050_compensate_Y_s32.
s32 bmm050_compensate_Y_s32(s16 mag_data_y, u16 data_r)
This API used to get the compensated Y data the out put of Y as s32.
mag_data_y : The value of raw Y data data_r : The value of R data results of compensated Y data value output as s32
References BMM050_INIT_VALUE, bmm050_compensate_Y, BMM050_OVERFLOW_OUTPUT, BMM050_OVERFLOW_OUTPUT_S32.
Referenced by bmm050_read_mag_data_XYZ_s32, bmm050_read_bmx055_remapped_mag_data_XYZ_s32.
s16 bmm050_compensate_Z(s16 mag_data_z, u16 data_r)
This API used to get the compensated Z data the out put of Z as s16.
mag_data_z : The value of raw Z data data_r : The value of R data results of compensated Z data value output as s16
References BMM050_INIT_VALUE, BMM050_HALL_OVERFLOW_ADCVAL, bmm050_t::dig_z2, bmm050_t::dig_z1, bmm050_t::dig_xyz1, bmm050_t::dig_z4, BMM050_SHIFT_BIT_POSITION_BY_15_BITS, bmm050_t::dig_z3, BMM050_SHIFT_BIT_POSITION_BY_02_BITS, BMM050_SHIFT_BIT_POSITION_BY_01_BIT, BMM050_SHIFT_BIT_POSITION_BY_16_BITS, BMM050_OVERFLOW_OUTPUT, BMM050_POSITIVE_SATURATION_Z, BMM050_NEGATIVE_SATURATION_Z.
Referenced by bmm050_read_mag_data_XYZ, bmm050_read_bmx055_remapped_mag_data_XYZ.
s32 bmm050_compensate_Z_s32(s16 mag_data_z, u16 data_r)
This API used to get the compensated Z data the out put of Z as s32.
mag_data_z : The value of raw Z data data_r : The value of R data results of compensated Z data value output as s32
References BMM050_INIT_VALUE, BMM050_HALL_OVERFLOW_ADCVAL, bmm050_t::dig_z2, bmm050_t::dig_z1, bmm050_t::dig_xyz1, bmm050_t::dig_z4, BMM050_SHIFT_BIT_POSITION_BY_15_BITS, bmm050_t::dig_z3, BMM050_SHIFT_BIT_POSITION_BY_02_BITS, BMM050_SHIFT_BIT_POSITION_BY_01_BIT, BMM050_SHIFT_BIT_POSITION_BY_16_BITS, BMM050_OVERFLOW_OUTPUT_S32.
Referenced by bmm050_read_mag_data_XYZ_s32, bmm050_read_bmx055_remapped_mag_data_XYZ_s32.
BMM050_RETURN_FUNCTION_TYPE bmm050_set_control_measurement_x(u8 v_enable_disable_u8)
This API used to set the control measurement X data in the register 0x4E bit 3.
v_enable_disable_u8 The value of control measurement-x value Status 1 ENABLE 0 DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_SENS_CONTROL_CHANNELX__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_SET_BITSLICE.
Referenced by bmm050_perform_advanced_selftest.
BMM050_RETURN_FUNCTION_TYPE bmm050_set_control_measurement_y(u8 v_enable_disable_u8)
This API used to set the control measurement Y data in the register 0x4E bit 4.
v_enable_disable_u8 The value of control measurement-y value Status 1 ENABLE 0 DISABLE results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_SENS_CONTROL_CHANNELY__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_SET_BITSLICE.
Referenced by bmm050_perform_advanced_selftest.
BMM050_RETURN_FUNCTION_TYPE bmm050_soft_rst(void)
This API used reset the register values to default in the register 0x4B.
results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, BMM050_ON, bmm050_t::dev_addr, BMM050_POWER_CONTROL_SOFT_RST_7__REG, BMM050_GEN_READ_WRITE_DATA_LENGTH, BMM050_SET_BITSLICE, BMM050_SOFT_RESET7_ON, BMM050_POWER_CONTROL_SOFT_RST_1__REG, BMM050_SOFT_RESET1_ON, bmm050_t::delay_msec, BMM050_DELAY_SOFTRESET.
BMM050_RETURN_FUNCTION_TYPE bmm050_get_raw_xyz(struct bmm050_mag_data_s16_t *mag_data)
This API reads Magnetometer raw data of X,Y,Z values and RHALL values from location 0x42 to 0x49.
mag_data : The data of raw XYZ data results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_DATA_FRAME_SIZE, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_DATA_X_LSB, BMM050_ALL_DATA_FRAME_LENGTH, BMM050_XLSB_DATA, BMM050_GET_BITSLICE, bmm050_mag_data_s16_t::datax, BMM050_SHIFT_BIT_POSITION_BY_05_BITS, BMM050_YLSB_DATA, bmm050_mag_data_s16_t::datay, BMM050_ZLSB_DATA, bmm050_mag_data_s16_t::dataz, BMM050_SHIFT_BIT_POSITION_BY_07_BITS, bmm050_mag_data_s16_t::data_ready, BMM050_RLSB_DATA, bmm050_mag_data_s16_t::resistance, BMM050_RMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_06_BITS.
BMM050_RETURN_FUNCTION_TYPE bmm050_get_bmx055_remapped_raw_xyz(struct bmm050_remapped_mag_s16_data_t *mag_data)
This API reads remapped Magnetometer raw data of X,Y,Z values and RHALL values from location 0x42 to 0x49.
In this function X and Y axis is remapped X is read from the address 0x44 & 0x45 Y is read from the address 0x42 & 0x43 this API is only applicable for BMX055 sensor mag_data : The data of remapped raw XYZ data results of bus communication function 0 -> Success -1 -> Error
References BMM050_RETURN_FUNCTION_TYPE, ERROR, BMM050_DATA_FRAME_SIZE, BMM050_INIT_VALUE, BMM050_NULL, E_BMM050_NULL_PTR, bmm050_t::dev_addr, BMM050_REMAPPED_BMX055_DATA_Y_LSB, BMM050_ALL_DATA_FRAME_LENGTH, BMM050_XLSB_DATA, BMM050_GET_BITSLICE, bmm050_remapped_mag_s16_data_t::datay, BMM050_SHIFT_BIT_POSITION_BY_05_BITS, BMM050_YLSB_DATA, bmm050_remapped_mag_s16_data_t::datax, BMM050_ZLSB_DATA, bmm050_remapped_mag_s16_data_t::dataz, BMM050_SHIFT_BIT_POSITION_BY_07_BITS, bmm050_remapped_mag_s16_data_t::data_ready, BMM050_RLSB_DATA, bmm050_remapped_mag_s16_data_t::resistance, BMM050_RMSB_DATA, BMM050_SHIFT_BIT_POSITION_BY_06_BITS.
MACHINE_32_BIT
For Enabling and Disabling the floating point API's If your platform supports the FLOAT support, please enable this macro.
The following definition uses for define the data typesWhile porting the API please consider the following Please check the version of C standard Are you using Linux platform For the Linux platform support Please use the types.h for your data types definitionsBy default it is defined as 32 bit machine configuration define your data types based on your machine/compiler/controller configuration
typedef signed short int s16
used for signed 16bit
typedef signed int s32
used for signed 32bit
typedef signed long long int s64
used for signed 64bit
typedef signed char s8
If your machine support 16 bit define the MACHINE_16_BIT.
used for signed 8bit
typedef unsigned short int u16
used for unsigned 16bit
typedef unsigned int u32
used for unsigned 32bit
typedef unsigned long long int u64
used for unsigned 64bit
typedef unsigned char u8
used for unsigned 8bit