ccsbcs.c
WCHAR ff_convert(WCHAR chr, UINT dir)
Referenced by get_fileinfo, create_name, f_gets, putc_bfd.
WCHAR ff_wtoupper(WCHAR chr)
Referenced by cmp_lfn, create_name.