device.c
const _SlCmdCtrl_t _SlStopCmdCtrl
const SlWlanMode_e StartResponseLUT[8][8]
Referenced by _sl_GetStartResponseConvert.
static SlWlanMode_e _sl_GetStartResponseConvert(_i32 Status)
References StartResponseLUT.
Referenced by _sl_HandleAsync_InitComplete.
_SlReturnVal_t _sl_HandleAsync_InitComplete(void *pVoidBuf)
References _SL_RESP_ARGS_START, SL_DRV_PROTECTION_OBJ_LOCK_FOREVER, g_pCB, _SlDriverCb_t::pInitCallback, _sl_GetStartResponseConvert, InitComplete_t::Status, sl_Memcpy, _SlDriverCb_t::ObjPool, _SlDriverCb_t::FunctionParams, _SlFunctionParams_t::AsyncExt, AsyncExt_t::ActionIndex, _SlPoolObj_t::pRespArgs, SL_DRV_SYNC_OBJ_SIGNAL, _SlPoolObj_t::SyncObj, SL_DRV_PROTECTION_OBJ_UNLOCK, SL_SET_DEVICE_STARTED, _SlDrvReleasePoolObj, SL_RET_CODE_OK.
Referenced by _SlDrvDeviceEventHandler.
void _sl_HandleAsync_Stop(void *pVoidBuf)
References _SL_RESP_ARGS_START, VERIFY_SOCKET_CB, NULL, g_pCB, SL_DRV_PROTECTION_OBJ_LOCK_FOREVER, sl_Memcpy, _SlDriverCb_t::ObjPool, _SlDriverCb_t::FunctionParams, _SlFunctionParams_t::AsyncExt, AsyncExt_t::ActionIndex, _SlPoolObj_t::pRespArgs, SL_DRV_SYNC_OBJ_SIGNAL, _SlPoolObj_t::SyncObj, SL_DRV_PROTECTION_OBJ_UNLOCK.
Referenced by _SlDrvDeviceEventHandler.
_SlReturnVal_t _SlDrvDeviceEventHandler(void *pEventInfo)
References DeviceEventInfo_t::pAsyncMsgBuff, _SL_RESP_ARGS_START, _SlResponseHeader_t::GenHeader, _SlGenericHeader_t::Opcode, SL_OPCODE_DEVICE_INITCOMPLETE, _sl_HandleAsync_InitComplete, SL_OPCODE_DEVICE_STOP_ASYNC_RESPONSE, _sl_HandleAsync_Stop, SL_OPCODE_DEVICE_ABORT, DeviceEventInfo_t::bInCmdContext, SL_DRV_LOCK_GLOBAL_UNLOCK, _SlDriverHandleError, SL_DEVICE_ABORT_ERROR_EVENT, _u32, SL_OPCODE_DEVICE_ASYNC_GENERAL_ERROR, SlDeviceEvent_t::Event, SL_DEVICE_GENERAL_ERROR_EVENT, SlDeviceEvent_t::EventData, SlDeviceEventData_u::deviceEvent, sl_DeviceReport::status, sl_DeviceReport::sender, SL_ERROR_TRACE2, SL_OS_RET_CODE_OK.