driver.c
_SL_PENDING_RX_MSG
Referenced by _SlDrvMsgReadCmdCtx, _SlDrvMsgReadSpawnCtx.
ACT_DATA_SIZE
Referenced by _SlDrvMsgRead.
BUF_SYNC_SPIM
MATCH_WITH_SEQ_NUM
MATCH_WOUT_SEQ_NUM
N2H_SYNC_PATTERN_MASK
N2H_SYNC_PATTERN_MATCH
Referenced by _SlDrvRxHdrRead.
N2H_SYNC_PATTERN_SEQ_NUM_BITS
N2H_SYNC_PATTERN_SEQ_NUM_EXISTS
N2H_SYNC_SPI_BUGS_MASK
N2H_SYNC_SPIM
N2H_SYNC_SPIM_WITH_SEQ
OPCODE
Referenced by _SlDrvMsgRead.
RSP_PAYLOAD_LEN
Referenced by _SlDrvMsgRead.
SD
Referenced by _SlDrvMsgRead.
const _SlActionLookup_t _SlActionLookupTable[][]
_volatile _u8 g_bDeviceRestartIsRequired
const _SlSyncPattern_t g_H2NCnysPattern
const _SlSyncPattern_t g_H2NSyncPattern
_SlDriverCb_t* g_pCB
Referenced by _sl_HandleAsync_InitComplete, _sl_HandleAsync_Stop, _SlDrvProtectAsyncRespSetting, _sl_HandleAsync_DnsGetHostByService, _sl_HandleAsync_DnsGetHostByName, _sl_HandleAsync_PingResponse, _SlNonOsSemGet, _sl_HandleAsync_Connect, _sl_HandleAsync_Accept, _sl_HandleAsync_Select.
_u16 g_SlDeviceStatus
_SlStatMem_t g_StatMem
_u8 gFirstCmdMode
const OpcodeKeyVal_t OpcodeTranslateTable[][]
P_SL_DEV_PING_CALLBACK pPingCallBackFunc
Referenced by _sl_HandleAsync_PingResponse.
_volatile _u8 RxIrqCnt
const _SlSpawnEntryFunc_t RxMsgClassLUT[][]
static void _SlAsyncEventGenericHandler(_u8 bInCmdContext)
References _u32, _u8, FALSE, NULL, _SlDriverCb_t::FunctionParams, _SlFunctionParams_t::AsyncExt, AsyncExt_t::pAsyncBuf, AsyncExt_t::AsyncEvtHandler, _SlResponseHeader_t::GenHeader, _SlGenericHeader_t::Opcode, OpcodeKeyVal_t::event, TRUE, SL_OPCODE_SILO_MASK, SL_OPCODE_SILO_DEVICE, DeviceEventInfo_t::pAsyncMsgBuff, DeviceEventInfo_t::bInCmdContext.
Referenced by _SlDrvMsgReadCmdCtx, _SlDrvMsgReadSpawnCtx.
void _SlDriverHandleError(SlDeviceDriverError_e eError, _u32 info1, _u32 info2)
References _u8, TRUE, sl_LockObjDelete, _SlDriverCb_t::GlobalLockObj, SL_DRV_SYNC_OBJ_SIGNAL, _SlDriverCb_t::ObjPool, _SlPoolObj_t::SyncObj, SlDeviceEvent_t::Event, SL_DEVICE_ABORT_ERROR_EVENT, SlDeviceEvent_t::EventData, SlDeviceEventData_u::deviceReport, sl_DeviceReportAbort::AbortType, _u32, sl_DeviceReportAbort::AbortData, SL_DEVICE_DRIVER_TIMEOUT_ASYNC_EVENT, SL_DEVICE_DRIVER_TIMEOUT_CMD_COMPLETE, SlDeviceEventData_u::deviceDriverReport, sl_DeviceDriverErrorReport::info.
Referenced by _SlDrvDeviceEventHandler, _SlDrvMsgRead, _SlDrvMsgReadCmdCtx, _SlDrvSyncObjWaitTimeout.
_i16 _SlDrvBasicCmd(_SlOpcode_t Opcode)
References _SlDrvMemZero, _u16, _SlCmdCtrl_t::Opcode, _SlCmdCtrl_t::TxDescLen, _SlCmdCtrl_t::RxDescLen, VERIFY_RET_OK, _SlDrvCmdOp, _i16, _SlBasicCmdMsg_u::Rsp, _BasicResponse_t::status.
static _SlReturnVal_t _SlDrvClassifyRxMsg(_SlOpcode_t Opcode)
References NULL, CMD_RESP_CLASS, _u8, SL_OPCODE_SYNC, SL_OPCODE_DEVICE_DEVICEASYNCDUMMY, DUMMY_MSG_CLASS, SL_OPCODE_SOCKET_RECVASYNCRESPONSE, SL_OPCODE_SOCKET_RECVFROMASYNCRESPONSE, SL_OPCODE_SOCKET_RECVFROMASYNCRESPONSE_V6, RECV_RESP_CLASS, ASYNC_EVT_CLASS, SL_OPCODE_SILO_OFFSET, VERIFY_PROTOCOL, SL_OPCODE_NETAPP_HTTPGETTOKENVALUE, SL_OPCODE_NETAPP_HTTPPOSTTOKENVALUE, _SlDrvNetAppEventHandler, _sl_HandleAsync_PingResponse, _SlDriverCb_t::FunctionParams, _SlFunctionParams_t::AsyncExt, AsyncExt_t::RxMsgClass, AsyncExt_t::AsyncEvtHandler, SL_RET_CODE_OK.
Referenced by _SlDrvMsgRead.
_SlReturnVal_t _SlDrvCmdOp(_SlCmdCtrl_t *pCmdCtrl, void *pTxRxDescBuff, _SlCmdExt_t *pCmdExt)
References SL_DRV_LOCK_GLOBAL_LOCK_FOREVER, TRUE, SL_DRV_LOCK_GLOBAL_UNLOCK, SL_API_ABORTED, _SlDriverCb_t::IsCmdRespWaited, SL_TRACE0, _SlDrvMsgWrite, SL_OS_RET_CODE_OK, _u32, CPU_FREQ_IN_MHZ, USEC_DELAY, _SlDrvMsgReadCmdCtx, _SlCmdCtrl_t::Opcode.
Referenced by _SlDrvBasicCmd.
_SlReturnVal_t _SlDrvCmdSend(_SlCmdCtrl_t *pCmdCtrl, void *pTxRxDescBuff, _SlCmdExt_t *pCmdExt)
References _u8, _SlDriverCb_t::IsCmdRespWaited, sl_Memcpy, _SlDriverCb_t::FunctionParams, FALSE, SL_TRACE0, _SlDrvMsgWrite.
_SlReturnVal_t _SlDrvDataReadOp(_SlSd_t Sd, _SlCmdCtrl_t *pCmdCtrl, void *pTxRxDescBuff, _SlCmdExt_t *pCmdExt)
References _u8, VERIFY_PROTOCOL, NULL, _SlCmdExt_t::pRxPayload, _SlCmdExt_t::RxPayloadLen, BSD_SOCKET_ID_MASK, SL_MAX_SOCKETS, SL_EBADF, _SlDrvWaitForPoolObj, RECV_ID, SL_POOL_IS_EMPTY, SL_DRV_PROTECTION_OBJ_LOCK_FOREVER, _SlArgsData_t::pData, _SlArgsData_t::pArgs, _SlDriverCb_t::ObjPool, _SlPoolObj_t::pRespArgs, SL_DRV_PROTECTION_OBJ_UNLOCK, SL_DRV_OBJ_LOCK_FOREVER, _SlDriverCb_t::FlowContCB, _SlFlowContCB_t::TxLockObj, SL_DRV_SYNC_OBJ_CLEAR, _SlFlowContCB_t::TxSyncObj, _SlFlowContCB_t::TxPoolCnt, FLOW_CONT_MIN, SL_DRV_SYNC_OBJ_WAIT_FOREVER, SL_DRV_LOCK_GLOBAL_LOCK_FOREVER, TRUE, SL_DRV_LOCK_GLOBAL_UNLOCK, SL_API_ABORTED, SL_DRV_OBJ_UNLOCK, _SlDrvMsgWrite, SL_OS_RET_CODE_OK, _SlDriverCb_t::SocketNonBlocking, _SlCmdCtrl_t::Opcode, SL_OPCODE_SOCKET_RECV, SL_DRIVER_API_SOCKET_RECV, SL_DRIVER_API_SOCKET_RECVFROM, SL_DRV_SYNC_OBJ_WAIT_TIMEOUT, _SlPoolObj_t::SyncObj, SL_DRIVER_TIMEOUT_SHORT, _SlDrvReleasePoolObj.
_SlReturnVal_t _SlDrvDataWriteOp(_SlSd_t Sd, _SlCmdCtrl_t *pCmdCtrl, void *pTxRxDescBuff, _SlCmdExt_t *pCmdExt)
References SL_EAGAIN, SL_DRV_OBJ_LOCK_FOREVER, _SlDriverCb_t::FlowContCB, _SlFlowContCB_t::TxLockObj, SL_DRV_SYNC_OBJ_CLEAR, _SlFlowContCB_t::TxSyncObj, _SlDriverCb_t::SocketTXFailure, BSD_SOCKET_ID_MASK, SL_DRV_OBJ_UNLOCK, SL_SOC_ERROR, _SlFlowContCB_t::TxPoolCnt, FLOW_CONT_MIN, _SlDriverCb_t::SocketNonBlocking, SL_DRV_SYNC_OBJ_WAIT_FOREVER, SL_DRV_LOCK_GLOBAL_LOCK_FOREVER, TRUE, SL_DRV_LOCK_GLOBAL_UNLOCK, SL_API_ABORTED, VERIFY_PROTOCOL, _SlDrvMsgWrite.
_SlReturnVal_t _SlDrvDriverCBDeinit(void)
References _u8, SL_UNSET_DEVICE_STARTED, _SlDriverCb_t::FlowContCB, _SlFlowContCB_t::TxPoolCnt, OSI_RET_OK_CHECK, sl_LockObjDelete, _SlFlowContCB_t::TxLockObj, sl_SyncObjDelete, _SlFlowContCB_t::TxSyncObj, _SlDriverCb_t::CmdSyncObj, _SlDriverCb_t::GlobalLockObj, _SlDriverCb_t::ProtectionLockObj, _SlDriverCb_t::ObjPool, _SlPoolObj_t::SyncObj, _SlDriverCb_t::FreePoolIdx, _SlDriverCb_t::PendingPoolIdx, _SlDriverCb_t::ActivePoolIdx, NULL, SL_OS_RET_CODE_OK.
_SlReturnVal_t _SlDrvDriverCBInit(void)
References _u8, _SlStatMem_t::DriverCB, MALLOC_OK_CHECK, g__SlNonOsCB, sl_Memset, _SlDrvMemZero, _u16, OSI_RET_OK_CHECK, sl_SyncObjCreate, _SlDriverCb_t::CmdSyncObj, SL_DRV_SYNC_OBJ_CLEAR, sl_LockObjCreate, _SlDriverCb_t::GlobalLockObj, _SlDriverCb_t::ProtectionLockObj, _SlDriverCb_t::ObjPool, _SlDriverCb_t::FreePoolIdx, _SlPoolObj_t::NextIndex, _SlPoolObj_t::AdditionalData, SL_MAX_SOCKETS, _SlPoolObj_t::SyncObj, _SlDriverCb_t::ActivePoolIdx, _SlDriverCb_t::PendingPoolIdx, _SlDriverCb_t::FlowContCB, _SlFlowContCB_t::TxPoolCnt, FLOW_CONT_MIN, _SlFlowContCB_t::TxLockObj, _SlFlowContCB_t::TxSyncObj, SL_OS_RET_CODE_OK.
_SlReturnVal_t _SlDrvGlobalObjUnLock(void)
References OSI_RET_OK_CHECK, sl_LockObjUnlock, _SlDriverCb_t::GlobalLockObj, SL_OS_RET_CODE_OK.
void _SlDrvMemZero(void *Addr, _u16 size)
References sl_Memset.
Referenced by _SlDrvDriverCBInit, _SlDrvMsgRead, _SlDrvBasicCmd, _SlDrvResetCmdExt.
static _SlReturnVal_t _SlDrvMsgRead(void)
References _u8, _SL_RESP_HDR_SIZE, _u32, _u16, NULL, SL_MAX_SOCKETS, _SlDriverCb_t::FunctionParams, _SlFunctionParams_t::AsyncExt, AsyncExt_t::pAsyncBuf, AsyncExt_t::AsyncEvtHandler, VERIFY_RET_OK, _SlDrvRxHdrRead, SL_API_ABORTED, SL_DRV_LOCK_GLOBAL_UNLOCK, _SlDriverHandleError, SL_DEVICE_DRIVER_TIMEOUT_SYNC_PATTERN, OPCODE, RSP_PAYLOAD_LEN, SL_OPCODE_DEVICE_INITCOMPLETE, _SlDriverCb_t::FlowContCB, _SlFlowContCB_t::TxPoolCnt, _SlDriverCb_t::SocketNonBlocking, _SlDriverCb_t::SocketTXFailure, FLOW_CONT_MIN, SL_DRV_SYNC_OBJ_SIGNAL, _SlFlowContCB_t::TxSyncObj, _SlDrvClassifyRxMsg, AsyncExt_t::RxMsgClass, ASYNC_EVT_CLASS, VERIFY_PROTOCOL, SL_ASYNC_MAX_MSG_LEN, _SlStatMem_t::AsyncRespBuf, _SlDrvMemZero, MALLOC_OK_CHECK, sl_Memcpy, _SL_PROTOCOL_ALIGN_SIZE, SL_ASYNC_MAX_PAYLOAD_LEN, NWP_IF_READ_CHECK, _SlDriverCb_t::FD, SL_DRV_PROTECTION_OBJ_LOCK_FOREVER, SL_OPCODE_SOCKET_ACCEPTASYNCRESPONSE_V6, BSD_SOCKET_ID_MASK, _SlFindAndSetActiveObj, SL_DRV_PROTECTION_OBJ_UNLOCK, RECV_RESP_CLASS, SL_OPCODE_SOCKET_RECVFROMASYNCRESPONSE, RECVFROM_IPV4_ARGS_SIZE, SL_OPCODE_SOCKET_RECVFROMASYNCRESPONSE_V6, RECVFROM_IPV6_ARGS_SIZE, RECV_ARGS_SIZE, SD, VERIFY_SOCKET_CB, _SlDriverCb_t::ObjPool, AsyncExt_t::ActionIndex, _SlPoolObj_t::pRespArgs, ACT_DATA_SIZE, _SlPoolObj_t::SyncObj, CMD_RESP_CLASS, _SlFunctionParams_t::pTxRxDescBuff, _SlFunctionParams_t::pCmdCtrl, _SlCmdCtrl_t::RxDescLen, _SlFunctionParams_t::pCmdExt, _SlCmdExt_t::RxPayloadLen, _i16, _SlCmdExt_t::ActualRxPayloadLen, _SlCmdExt_t::pRxPayload, _SL_DBG_CNT_INC, SL_OS_RET_CODE_OK.
Referenced by _SlDrvMsgReadCmdCtx, _SlDrvMsgReadSpawnCtx.
static _SlReturnVal_t _SlDrvMsgReadCmdCtx(_u16 cmdOpcode)
References _u32, SL_OPCODE_SILO_NVMEM, SL_DRIVER_TIMEOUT_LONG, SL_DRIVER_TIMEOUT_SHORT, TRUE, _SlDriverCb_t::IsCmdRespWaited, _SL_PENDING_RX_MSG, VERIFY_RET_OK, _SlDrvMsgRead, SL_OS_RET_CODE_OK, SL_API_ABORTED, SL_DRV_LOCK_GLOBAL_UNLOCK, _SlDriverCb_t::RxDoneCnt, CMD_RESP_CLASS, _SlDriverCb_t::FunctionParams, _SlFunctionParams_t::AsyncExt, AsyncExt_t::RxMsgClass, FALSE, SL_DRV_SYNC_OBJ_CLEAR, _SlDriverCb_t::CmdSyncObj, ASYNC_EVT_CLASS, _SlAsyncEventGenericHandler, AsyncExt_t::pAsyncBuf, NULL, _SlDrvSyncObjWaitForever, sl_SyncObjWait, _SlDriverHandleError, SL_DEVICE_DRIVER_TIMEOUT_CMD_COMPLETE, sl_Spawn, _SlDrvMsgReadSpawnCtx.
Referenced by _SlDrvCmdOp.
_SlReturnVal_t _SlDrvMsgReadSpawnCtx(void *pValue)
References _i16, OSI_OK, sl_LockObjLock, _SlDriverCb_t::GlobalLockObj, TRUE, _SlDriverCb_t::IsCmdRespWaited, SL_DRV_SYNC_OBJ_SIGNAL, _SlDriverCb_t::CmdSyncObj, SL_RET_CODE_OK, SL_DRV_LOCK_GLOBAL_LOCK_FOREVER, FALSE, _SL_PENDING_RX_MSG, SL_DRV_LOCK_GLOBAL_UNLOCK, VERIFY_RET_OK, _SlDrvMsgRead, SL_OS_RET_CODE_OK, SL_API_ABORTED, _SlDriverCb_t::RxDoneCnt, _SlDriverCb_t::FunctionParams, _SlFunctionParams_t::AsyncExt, AsyncExt_t::RxMsgClass, ASYNC_EVT_CLASS, VERIFY_PROTOCOL, NULL, AsyncExt_t::pAsyncBuf, _SlAsyncEventGenericHandler, DUMMY_MSG_CLASS, RECV_RESP_CLASS, CMD_RESP_CLASS.
Referenced by _SlDrvRxIrqHandler, _SlDrvMsgReadCmdCtx.
static _SlReturnVal_t _SlDrvMsgWrite(_SlCmdCtrl_t *pCmdCtrl, _SlCmdExt_t *pCmdExt, _u8 *pTxRxDescBuff)
References _u8, FALSE, VERIFY_PROTOCOL, NULL, _SlDriverCb_t::FunctionParams, _SlFunctionParams_t::pCmdCtrl, _SlFunctionParams_t::pTxRxDescBuff, _SlFunctionParams_t::pCmdExt, _SlDriverCb_t::TempProtocolHeader, _SlGenericHeader_t::Opcode, _SlCmdCtrl_t::Opcode, _SlGenericHeader_t::Len, _u16, _SL_PROTOCOL_CALC_LEN, _SlCmdExt_t::RxPayloadLen, TRUE, _SlDriverCb_t::FD, NWP_IF_WRITE_CHECK, _SlSyncPattern_t::Long, SYNC_PATTERN_LEN, _SlSyncPattern_t::Short, _SL_CMD_HDR_SIZE, _SlCmdCtrl_t::TxDescLen, _SL_PROTOCOL_ALIGN_SIZE, _SlCmdExt_t::pRxPayload, _SlCmdExt_t::TxPayloadLen, _SL_IS_PROTOCOL_ALIGNED_SIZE, _SlCmdExt_t::pTxPayload, _SL_DBG_CNT_INC, SL_OS_RET_CODE_OK.
Referenced by _SlDrvCmdOp, _SlDrvDataReadOp, _SlDrvDataWriteOp, _SlDrvCmdSend.
static _SlReturnVal_t _SlDrvObjGlobalLockWaitForever(void)
References TRUE, SL_API_ABORTED, sl_LockObjLock, _SlDriverCb_t::GlobalLockObj, SL_OS_WAIT_FOREVER.
_SlReturnVal_t _SlDrvObjLockWaitForever(_SlLockObj_t *pLockObj)
References OSI_RET_OK_CHECK, sl_LockObjLock, SL_OS_WAIT_FOREVER, SL_OS_RET_CODE_OK.
_SlReturnVal_t _SlDrvObjUnLock(_SlLockObj_t *pLockObj)
References OSI_RET_OK_CHECK, sl_LockObjUnlock, SL_OS_RET_CODE_OK.
_u8 _SlDrvProtectAsyncRespSetting(_u8 *pAsyncRsp, _SlActionID_e ActionID, _u8 SocketID)
References _u8, _SlDrvWaitForPoolObj, SL_DRV_PROTECTION_OBJ_LOCK_FOREVER, g_pCB, _SlDriverCb_t::ObjPool, _SlPoolObj_t::pRespArgs, SL_DRV_PROTECTION_OBJ_UNLOCK.
_SlReturnVal_t _SlDrvProtectionObjLockWaitForever(void)
References OSI_RET_OK_CHECK, sl_LockObjLock, _SlDriverCb_t::ProtectionLockObj, SL_OS_WAIT_FOREVER, SL_OS_RET_CODE_OK.
_SlReturnVal_t _SlDrvProtectionObjUnLock(void)
References OSI_RET_OK_CHECK, sl_LockObjUnlock, _SlDriverCb_t::ProtectionLockObj, SL_OS_RET_CODE_OK.
void _SlDrvReleasePoolObj(_u8 ObjIdx)
References _u8, SL_DRV_PROTECTION_OBJ_LOCK_FOREVER, _SlDriverCb_t::PendingPoolIdx, _SlDriverCb_t::ObjPool, _SlPoolObj_t::ActionID, SL_MAX_SOCKETS, _SlPoolObj_t::AdditionalData, BSD_SOCKET_ID_MASK, _SlRemoveFromList, SL_DRV_SYNC_OBJ_SIGNAL, _SlPoolObj_t::SyncObj, _SlPoolObj_t::NextIndex, _SlDriverCb_t::ActiveActionsBitmap, _SlPoolObj_t::pRespArgs, NULL, _SlDriverCb_t::ActivePoolIdx, _SlDriverCb_t::FreePoolIdx, SL_DRV_PROTECTION_OBJ_UNLOCK.
Referenced by _sl_HandleAsync_InitComplete, _SlDrvDataReadOp.
void _SlDrvResetCmdExt(_SlCmdExt_t *pCmdExt)
References _SlDrvMemZero, _u16.
static _SlReturnVal_t _SlDrvRxHdrRead(_u8 *pBuf, _u8 *pAlignSize)
References _u32, _u8, TIMEOUT_STATE_INIT_VAL, TRUE, NWP_IF_WRITE_CHECK, _SlDriverCb_t::FD, _SlSyncPattern_t::Short, SYNC_PATTERN_LEN, SYNC_PATTERN_TIMEOUT_IN_MSEC, NWP_IF_READ_CHECK, _SL_DBG_SYNC_LOG, SL_API_ABORTED, sl_Memcpy, N2H_SYNC_PATTERN_MATCH, _SlDriverCb_t::TxSeqNum, FALSE, TIMEOUT_ONE_MORE_SHOT, TIMEOUT_STATE_EXPIRY, _SL_DBG_CNT_INC, _SL_RESP_SPEC_HDR_SIZE, SL_RET_CODE_OK.
Referenced by _SlDrvMsgRead.
_SlReturnVal_t _SlDrvRxIrqHandler(void *pValue)
References TRUE, _SlDriverCb_t::IsCmdRespWaited, OSI_RET_OK_CHECK, sl_SyncObjSignalFromIRQ, _SlDriverCb_t::CmdSyncObj, sl_Spawn, _SlDrvMsgReadSpawnCtx, NULL, SL_SPAWN_FLAG_FROM_SL_IRQ_HANDLER, SL_OS_RET_CODE_OK.
_SlReturnVal_t _SlDrvSyncObjSignal(_SlSyncObj_t *pSyncObj)
References OSI_RET_OK_CHECK, sl_SyncObjSignal, SL_OS_RET_CODE_OK.
_SlReturnVal_t _SlDrvSyncObjWaitForever(_SlSyncObj_t *pSyncObj)
References sl_SyncObjWait, SL_OS_WAIT_FOREVER, TRUE, SL_API_ABORTED, SL_RET_CODE_OK.
Referenced by _SlDrvMsgReadCmdCtx, _SlDrvWaitForPoolObj.
_SlReturnVal_t _SlDrvSyncObjWaitTimeout(_SlSyncObj_t *pSyncObj, _u32 timeoutVal, SlDriverAPIWithTimeout_e apiIdx)
References sl_SyncObjWait, _SlDriverHandleError, SL_DEVICE_DRIVER_TIMEOUT_ASYNC_EVENT, TRUE, SL_API_ABORTED, SL_RET_CODE_OK.
_u8 _SlDrvWaitForPoolObj(_u8 ActionID, _u8 SocketID)
References _u8, SL_DRV_PROTECTION_OBJ_LOCK_FOREVER, _SlDriverCb_t::FreePoolIdx, _SlDriverCb_t::ObjPool, _SlPoolObj_t::NextIndex, SL_DRV_PROTECTION_OBJ_UNLOCK, _SlPoolObj_t::ActionID, SL_MAX_SOCKETS, _SlPoolObj_t::AdditionalData, _SlDriverCb_t::ActiveActionsBitmap, _SlDriverCb_t::PendingPoolIdx, _SlDrvSyncObjWaitForever, _SlPoolObj_t::SyncObj, _SlDriverCb_t::ActivePoolIdx.
Referenced by _SlDrvProtectAsyncRespSetting, _SlDrvDataReadOp.
static _SlReturnVal_t _SlFindAndSetActiveObj(_SlOpcode_t Opcode, _u8 Sd)
References _u8, _SlDriverCb_t::ActivePoolIdx, _SlDriverCb_t::ObjPool, _SlPoolObj_t::AdditionalData, SL_NETAPP_FAMILY_MASK, SL_OPCODE_IPV6, _SlPoolObj_t::ActionID, RECV_ID, SL_OPCODE_SOCKET_RECVASYNCRESPONSE, SL_OPCODE_SOCKET_RECVFROMASYNCRESPONSE, SL_OPCODE_SOCKET_RECVFROMASYNCRESPONSE_V6, _SlDriverCb_t::FunctionParams, _SlFunctionParams_t::AsyncExt, AsyncExt_t::ActionIndex, SL_RET_CODE_OK, MAX_SOCKET_ENUM_IDX, BSD_SOCKET_ID_MASK, SL_MAX_SOCKETS, AsyncExt_t::AsyncEvtHandler, _SlPoolObj_t::NextIndex, SL_RET_CODE_SELF_ERROR.
Referenced by _SlDrvMsgRead.
static void _SlRemoveFromList(_u8 *ListIndex, _u8 ItemIndex)
References _u8, _SlDriverCb_t::ObjPool, _SlPoolObj_t::NextIndex.
Referenced by _SlDrvReleasePoolObj.