driver.h
_SL_IS_PROTOCOL_ALIGNED_SIZE
Referenced by _SlDrvMsgWrite.
_SL_PROTOCOL_ALIGN_SIZE
Referenced by _SlDrvMsgWrite, _SlDrvMsgRead.
_SL_PROTOCOL_CALC_LEN
Referenced by _SlDrvMsgWrite.
CPU_FREQ_IN_MHZ
Referenced by _SlDrvCmdOp.
INIT_COMPLETE_TIMEOUT
SL_DRIVER_TIMEOUT_LONG
Referenced by _SlDrvMsgReadCmdCtx.
SL_DRIVER_TIMEOUT_SHORT
Referenced by _SlDrvDataReadOp, _SlDrvMsgReadCmdCtx.
SL_DRV_LOCK_GLOBAL_LOCK_FOREVER
Referenced by _SlDrvCmdOp, _SlDrvDataReadOp, _SlDrvDataWriteOp, _SlDrvMsgReadSpawnCtx.
SL_DRV_LOCK_GLOBAL_UNLOCK
Referenced by _SlDrvDeviceEventHandler, _SlDrvCmdOp, _SlDrvDataReadOp, _SlDrvDataWriteOp, _SlDrvMsgRead, _SlDrvMsgReadCmdCtx, _SlDrvMsgReadSpawnCtx.
SL_DRV_OBJ_LOCK_FOREVER
Referenced by _SlDrvDataReadOp, _SlDrvDataWriteOp.
SL_DRV_OBJ_UNLOCK
Referenced by _SlDrvDataReadOp, _SlDrvDataWriteOp.
SL_DRV_PROTECTION_OBJ_LOCK_FOREVER
Referenced by _sl_HandleAsync_InitComplete, _sl_HandleAsync_Stop, _SlDrvProtectAsyncRespSetting, _SlDrvDataReadOp, _SlDrvMsgRead, _SlDrvWaitForPoolObj, _SlDrvReleasePoolObj, _sl_HandleAsync_DnsGetHostByName, _sl_HandleAsync_PingResponse, _sl_HandleAsync_Connect, _sl_HandleAsync_Accept, _sl_HandleAsync_Select.
SL_DRV_PROTECTION_OBJ_UNLOCK
Referenced by _sl_HandleAsync_InitComplete, _sl_HandleAsync_Stop, _SlDrvProtectAsyncRespSetting, _SlDrvDataReadOp, _SlDrvMsgRead, _SlDrvWaitForPoolObj, _SlDrvReleasePoolObj, _sl_HandleAsync_DnsGetHostByName, _sl_HandleAsync_PingResponse, _sl_HandleAsync_Connect, _sl_HandleAsync_Accept, _sl_HandleAsync_Select.
SL_DRV_SYNC_OBJ_CLEAR
Referenced by _SlDrvDriverCBInit, _SlDrvDataReadOp, _SlDrvDataWriteOp, _SlDrvMsgReadCmdCtx.
SL_DRV_SYNC_OBJ_SIGNAL
Referenced by _sl_HandleAsync_InitComplete, _sl_HandleAsync_Stop, _SlDrvMsgRead, _SlDrvMsgReadSpawnCtx, _SlDrvReleasePoolObj, _SlDriverHandleError, _sl_HandleAsync_DnsGetHostByService, _sl_HandleAsync_DnsGetHostByName, _sl_HandleAsync_PingResponse, _sl_HandleAsync_Connect, _sl_HandleAsync_Accept, _sl_HandleAsync_Select.
SL_DRV_SYNC_OBJ_WAIT_FOREVER
Referenced by _SlDrvDataReadOp, _SlDrvDataWriteOp.
SL_DRV_SYNC_OBJ_WAIT_TIMEOUT
Referenced by _SlDrvDataReadOp.
SL_IS_COMMAND_ALLOWED
SL_SET_DEVICE_STARTED
Referenced by _sl_HandleAsync_InitComplete.
SL_UNSET_DEVICE_STARTED
Referenced by _SlDrvDriverCBDeinit.
STOP_DEVICE_TIMEOUT
SYNC_PATTERN_TIMEOUT_IN_MSEC
Referenced by _SlDrvRxHdrRead.
TIMEOUT_ONE_MORE_SHOT
Referenced by _SlDrvRxHdrRead.
TIMEOUT_STATE_EXPIRY
Referenced by _SlDrvRxHdrRead.
TIMEOUT_STATE_INIT_VAL
Referenced by _SlDrvRxHdrRead.
USEC_DELAY
Referenced by _SlDrvCmdOp.
_SlActionID_e
_SlRxMsgClass_e
typedef struct _SlActionLookup_t _SlActionLookup_t
typedef struct _SlArgsData_t _SlArgsData_t
typedef struct _SlPoolObj_t _SlPoolObj_t
typedef _u8 _SlSd_t
_volatile _u8 g_bDeviceRestartIsRequired
_SlDriverCb_t* g_pCB
Referenced by _sl_HandleAsync_InitComplete, _sl_HandleAsync_Stop, _SlDrvProtectAsyncRespSetting, _sl_HandleAsync_DnsGetHostByService, _sl_HandleAsync_DnsGetHostByName, _sl_HandleAsync_PingResponse, _SlNonOsSemGet, _sl_HandleAsync_Connect, _sl_HandleAsync_Accept, _sl_HandleAsync_Select.
_u16 g_SlDeviceStatus
P_SL_DEV_PING_CALLBACK pPingCallBackFunc
Referenced by _sl_HandleAsync_PingResponse.
_volatile _u8 RxIrqCnt
_SlReturnVal_t _sl_HandleAsync_Accept(void *pVoidBuf)
References _SL_RESP_ARGS_START, SL_DRV_PROTECTION_OBJ_LOCK_FOREVER, VERIFY_PROTOCOL, _SocketAddrResponse_u::IpV4, _SocketAddrAsyncIPv4Response_t::sd, SL_MAX_SOCKETS, VERIFY_SOCKET_CB, NULL, g_pCB, _SlDriverCb_t::ObjPool, _SlDriverCb_t::FunctionParams, _SlFunctionParams_t::AsyncExt, AsyncExt_t::ActionIndex, _SlPoolObj_t::pRespArgs, sl_Memcpy, SL_DRV_SYNC_OBJ_SIGNAL, _SlPoolObj_t::SyncObj, SL_DRV_PROTECTION_OBJ_UNLOCK, SL_RET_CODE_OK.
_SlReturnVal_t _sl_HandleAsync_Connect(void *pVoidBuf)
References _SL_RESP_ARGS_START, SL_DRV_PROTECTION_OBJ_LOCK_FOREVER, VERIFY_PROTOCOL, _SocketResponse_t::sd, BSD_SOCKET_ID_MASK, SL_MAX_SOCKETS, VERIFY_SOCKET_CB, NULL, g_pCB, _SlDriverCb_t::ObjPool, _SlDriverCb_t::FunctionParams, _SlFunctionParams_t::AsyncExt, AsyncExt_t::ActionIndex, _SlPoolObj_t::pRespArgs, _SocketResponse_t::statusOrLen, SL_DRV_SYNC_OBJ_SIGNAL, _SlPoolObj_t::SyncObj, SL_DRV_PROTECTION_OBJ_UNLOCK, SL_RET_CODE_OK.
_SlReturnVal_t _sl_HandleAsync_DnsGetHostByAddr(void *pVoidBuf)
References SL_TRACE0, SL_RET_CODE_OK.
_SlReturnVal_t _sl_HandleAsync_DnsGetHostByName(void *pVoidBuf)
References _SL_RESP_ARGS_START, SL_DRV_PROTECTION_OBJ_LOCK_FOREVER, VERIFY_SOCKET_CB, NULL, g_pCB, _SlDriverCb_t::ObjPool, _SlDriverCb_t::FunctionParams, _SlFunctionParams_t::AsyncExt, AsyncExt_t::ActionIndex, _SlPoolObj_t::pRespArgs, _SlPoolObj_t::AdditionalData, SL_NETAPP_FAMILY_MASK, sl_Memcpy, SL_DRV_SYNC_OBJ_SIGNAL, _SlPoolObj_t::SyncObj, SL_DRV_PROTECTION_OBJ_UNLOCK, SL_RET_CODE_OK.
Referenced by _SlDrvNetAppEventHandler.
_SlReturnVal_t _sl_HandleAsync_DnsGetHostByService(void *pVoidBuf)
References _u16, _SL_RESP_ARGS_START, VERIFY_SOCKET_CB, NULL, g_pCB, _SlDriverCb_t::ObjPool, _SlDriverCb_t::FunctionParams, _SlFunctionParams_t::AsyncExt, AsyncExt_t::ActionIndex, _SlPoolObj_t::pRespArgs, _SlPoolObj_t::AdditionalData, SL_NETAPP_FAMILY_MASK, SL_RET_CODE_OK, _GetHostByServiceIPv4AsyncResponse_t::TextLen, _GetHostByServiceAsyncResponse_t::out_pAddr, _GetHostByServiceIPv4AsyncResponse_t::Address, _GetHostByServiceAsyncResponse_t::out_pPort, _GetHostByServiceIPv4AsyncResponse_t::Port, _GetHostByServiceAsyncResponse_t::Status, _i16, _GetHostByServiceIPv4AsyncResponse_t::Status, _GetHostByServiceAsyncResponse_t::inout_TextLen, sl_Memcpy, _GetHostByServiceAsyncResponse_t::out_pText, _i8, SL_DRV_SYNC_OBJ_SIGNAL, _SlPoolObj_t::SyncObj.
Referenced by _SlDrvNetAppEventHandler.
_SlReturnVal_t _sl_HandleAsync_InitComplete(void *pVoidBuf)
References _SL_RESP_ARGS_START, SL_DRV_PROTECTION_OBJ_LOCK_FOREVER, g_pCB, _SlDriverCb_t::pInitCallback, _sl_GetStartResponseConvert, InitComplete_t::Status, sl_Memcpy, _SlDriverCb_t::ObjPool, _SlDriverCb_t::FunctionParams, _SlFunctionParams_t::AsyncExt, AsyncExt_t::ActionIndex, _SlPoolObj_t::pRespArgs, SL_DRV_SYNC_OBJ_SIGNAL, _SlPoolObj_t::SyncObj, SL_DRV_PROTECTION_OBJ_UNLOCK, SL_SET_DEVICE_STARTED, _SlDrvReleasePoolObj, SL_RET_CODE_OK.
Referenced by _SlDrvDeviceEventHandler.
_SlReturnVal_t _sl_HandleAsync_PingResponse(void *pVoidBuf)
References _SL_RESP_ARGS_START, pPingCallBackFunc, CopyPingResultsToReport, SL_DRV_PROTECTION_OBJ_LOCK_FOREVER, VERIFY_SOCKET_CB, NULL, g_pCB, _SlDriverCb_t::ObjPool, _SlDriverCb_t::FunctionParams, _SlFunctionParams_t::AsyncExt, AsyncExt_t::ActionIndex, _SlPoolObj_t::pRespArgs, sl_Memcpy, SL_DRV_SYNC_OBJ_SIGNAL, _SlPoolObj_t::SyncObj, SL_DRV_PROTECTION_OBJ_UNLOCK, SL_RET_CODE_OK.
Referenced by _SlDrvClassifyRxMsg, _SlDrvNetAppEventHandler.
_SlReturnVal_t _sl_HandleAsync_Select(void *pVoidBuf)
References _SL_RESP_ARGS_START, SL_DRV_PROTECTION_OBJ_LOCK_FOREVER, VERIFY_SOCKET_CB, NULL, g_pCB, _SlDriverCb_t::ObjPool, _SlDriverCb_t::FunctionParams, _SlFunctionParams_t::AsyncExt, AsyncExt_t::ActionIndex, _SlPoolObj_t::pRespArgs, sl_Memcpy, SL_DRV_SYNC_OBJ_SIGNAL, _SlPoolObj_t::SyncObj, SL_DRV_PROTECTION_OBJ_UNLOCK, SL_RET_CODE_OK.
void _sl_HandleAsync_Stop(void *pVoidBuf)
References _SL_RESP_ARGS_START, VERIFY_SOCKET_CB, NULL, g_pCB, SL_DRV_PROTECTION_OBJ_LOCK_FOREVER, sl_Memcpy, _SlDriverCb_t::ObjPool, _SlDriverCb_t::FunctionParams, _SlFunctionParams_t::AsyncExt, AsyncExt_t::ActionIndex, _SlPoolObj_t::pRespArgs, SL_DRV_SYNC_OBJ_SIGNAL, _SlPoolObj_t::SyncObj, SL_DRV_PROTECTION_OBJ_UNLOCK.
Referenced by _SlDrvDeviceEventHandler.
void _SlDriverHandleError(SlDeviceDriverError_e eError, _u32 info1, _u32 info2)
References _u8, TRUE, sl_LockObjDelete, _SlDriverCb_t::GlobalLockObj, SL_DRV_SYNC_OBJ_SIGNAL, _SlDriverCb_t::ObjPool, _SlPoolObj_t::SyncObj, SlDeviceEvent_t::Event, SL_DEVICE_ABORT_ERROR_EVENT, SlDeviceEvent_t::EventData, SlDeviceEventData_u::deviceReport, sl_DeviceReportAbort::AbortType, _u32, sl_DeviceReportAbort::AbortData, SL_DEVICE_DRIVER_TIMEOUT_ASYNC_EVENT, SL_DEVICE_DRIVER_TIMEOUT_CMD_COMPLETE, SlDeviceEventData_u::deviceDriverReport, sl_DeviceDriverErrorReport::info.
Referenced by _SlDrvDeviceEventHandler, _SlDrvMsgRead, _SlDrvMsgReadCmdCtx, _SlDrvSyncObjWaitTimeout.
_u16 _SlDrvAlignSize(_u16 msgLen)
_i16 _SlDrvBasicCmd(_SlOpcode_t Opcode)
References _SlDrvMemZero, _u16, _SlCmdCtrl_t::Opcode, _SlCmdCtrl_t::TxDescLen, _SlCmdCtrl_t::RxDescLen, VERIFY_RET_OK, _SlDrvCmdOp, _i16, _SlBasicCmdMsg_u::Rsp, _BasicResponse_t::status.
_SlReturnVal_t _SlDrvCmdOp(_SlCmdCtrl_t *pCmdCtrl, void *pTxRxDescBuff, _SlCmdExt_t *pCmdExt)
References SL_DRV_LOCK_GLOBAL_LOCK_FOREVER, TRUE, SL_DRV_LOCK_GLOBAL_UNLOCK, SL_API_ABORTED, _SlDriverCb_t::IsCmdRespWaited, SL_TRACE0, _SlDrvMsgWrite, SL_OS_RET_CODE_OK, _u32, CPU_FREQ_IN_MHZ, USEC_DELAY, _SlDrvMsgReadCmdCtx, _SlCmdCtrl_t::Opcode.
Referenced by _SlDrvBasicCmd.
_SlReturnVal_t _SlDrvCmdSend(_SlCmdCtrl_t *pCmdCtrl, void *pTxRxDescBuff, _SlCmdExt_t *pCmdExt)
References _u8, _SlDriverCb_t::IsCmdRespWaited, sl_Memcpy, _SlDriverCb_t::FunctionParams, FALSE, SL_TRACE0, _SlDrvMsgWrite.
_SlReturnVal_t _SlDrvDataReadOp(_SlSd_t Sd, _SlCmdCtrl_t *pCmdCtrl, void *pTxRxDescBuff, _SlCmdExt_t *pCmdExt)
References _u8, VERIFY_PROTOCOL, NULL, _SlCmdExt_t::pRxPayload, _SlCmdExt_t::RxPayloadLen, BSD_SOCKET_ID_MASK, SL_MAX_SOCKETS, SL_EBADF, _SlDrvWaitForPoolObj, RECV_ID, SL_POOL_IS_EMPTY, SL_DRV_PROTECTION_OBJ_LOCK_FOREVER, _SlArgsData_t::pData, _SlArgsData_t::pArgs, _SlDriverCb_t::ObjPool, _SlPoolObj_t::pRespArgs, SL_DRV_PROTECTION_OBJ_UNLOCK, SL_DRV_OBJ_LOCK_FOREVER, _SlDriverCb_t::FlowContCB, _SlFlowContCB_t::TxLockObj, SL_DRV_SYNC_OBJ_CLEAR, _SlFlowContCB_t::TxSyncObj, _SlFlowContCB_t::TxPoolCnt, FLOW_CONT_MIN, SL_DRV_SYNC_OBJ_WAIT_FOREVER, SL_DRV_LOCK_GLOBAL_LOCK_FOREVER, TRUE, SL_DRV_LOCK_GLOBAL_UNLOCK, SL_API_ABORTED, SL_DRV_OBJ_UNLOCK, _SlDrvMsgWrite, SL_OS_RET_CODE_OK, _SlDriverCb_t::SocketNonBlocking, _SlCmdCtrl_t::Opcode, SL_OPCODE_SOCKET_RECV, SL_DRIVER_API_SOCKET_RECV, SL_DRIVER_API_SOCKET_RECVFROM, SL_DRV_SYNC_OBJ_WAIT_TIMEOUT, _SlPoolObj_t::SyncObj, SL_DRIVER_TIMEOUT_SHORT, _SlDrvReleasePoolObj.
_SlReturnVal_t _SlDrvDataWriteOp(_SlSd_t Sd, _SlCmdCtrl_t *pCmdCtrl, void *pTxRxDescBuff, _SlCmdExt_t *pCmdExt)
References SL_EAGAIN, SL_DRV_OBJ_LOCK_FOREVER, _SlDriverCb_t::FlowContCB, _SlFlowContCB_t::TxLockObj, SL_DRV_SYNC_OBJ_CLEAR, _SlFlowContCB_t::TxSyncObj, _SlDriverCb_t::SocketTXFailure, BSD_SOCKET_ID_MASK, SL_DRV_OBJ_UNLOCK, SL_SOC_ERROR, _SlFlowContCB_t::TxPoolCnt, FLOW_CONT_MIN, _SlDriverCb_t::SocketNonBlocking, SL_DRV_SYNC_OBJ_WAIT_FOREVER, SL_DRV_LOCK_GLOBAL_LOCK_FOREVER, TRUE, SL_DRV_LOCK_GLOBAL_UNLOCK, SL_API_ABORTED, VERIFY_PROTOCOL, _SlDrvMsgWrite.
_SlReturnVal_t _SlDrvDeviceEventHandler(void *pEventInfo)
References DeviceEventInfo_t::pAsyncMsgBuff, _SL_RESP_ARGS_START, _SlResponseHeader_t::GenHeader, _SlGenericHeader_t::Opcode, SL_OPCODE_DEVICE_INITCOMPLETE, _sl_HandleAsync_InitComplete, SL_OPCODE_DEVICE_STOP_ASYNC_RESPONSE, _sl_HandleAsync_Stop, SL_OPCODE_DEVICE_ABORT, DeviceEventInfo_t::bInCmdContext, SL_DRV_LOCK_GLOBAL_UNLOCK, _SlDriverHandleError, SL_DEVICE_ABORT_ERROR_EVENT, _u32, SL_OPCODE_DEVICE_ASYNC_GENERAL_ERROR, SlDeviceEvent_t::Event, SL_DEVICE_GENERAL_ERROR_EVENT, SlDeviceEvent_t::EventData, SlDeviceEventData_u::deviceEvent, sl_DeviceReport::status, sl_DeviceReport::sender, SL_ERROR_TRACE2, SL_OS_RET_CODE_OK.
_SlReturnVal_t _SlDrvDriverCBDeinit(void)
References _u8, SL_UNSET_DEVICE_STARTED, _SlDriverCb_t::FlowContCB, _SlFlowContCB_t::TxPoolCnt, OSI_RET_OK_CHECK, sl_LockObjDelete, _SlFlowContCB_t::TxLockObj, sl_SyncObjDelete, _SlFlowContCB_t::TxSyncObj, _SlDriverCb_t::CmdSyncObj, _SlDriverCb_t::GlobalLockObj, _SlDriverCb_t::ProtectionLockObj, _SlDriverCb_t::ObjPool, _SlPoolObj_t::SyncObj, _SlDriverCb_t::FreePoolIdx, _SlDriverCb_t::PendingPoolIdx, _SlDriverCb_t::ActivePoolIdx, NULL, SL_OS_RET_CODE_OK.
_SlReturnVal_t _SlDrvDriverCBInit(void)
References _u8, _SlStatMem_t::DriverCB, MALLOC_OK_CHECK, g__SlNonOsCB, sl_Memset, _SlDrvMemZero, _u16, OSI_RET_OK_CHECK, sl_SyncObjCreate, _SlDriverCb_t::CmdSyncObj, SL_DRV_SYNC_OBJ_CLEAR, sl_LockObjCreate, _SlDriverCb_t::GlobalLockObj, _SlDriverCb_t::ProtectionLockObj, _SlDriverCb_t::ObjPool, _SlDriverCb_t::FreePoolIdx, _SlPoolObj_t::NextIndex, _SlPoolObj_t::AdditionalData, SL_MAX_SOCKETS, _SlPoolObj_t::SyncObj, _SlDriverCb_t::ActivePoolIdx, _SlDriverCb_t::PendingPoolIdx, _SlDriverCb_t::FlowContCB, _SlFlowContCB_t::TxPoolCnt, FLOW_CONT_MIN, _SlFlowContCB_t::TxLockObj, _SlFlowContCB_t::TxSyncObj, SL_OS_RET_CODE_OK.
_SlReturnVal_t _SlDrvGlobalObjUnLock(void)
References OSI_RET_OK_CHECK, sl_LockObjUnlock, _SlDriverCb_t::GlobalLockObj, SL_OS_RET_CODE_OK.
void _SlDrvMemZero(void *Addr, _u16 size)
References sl_Memset.
Referenced by _SlDrvDriverCBInit, _SlDrvMsgRead, _SlDrvBasicCmd, _SlDrvResetCmdExt.
_SlReturnVal_t _SlDrvMsgReadSpawnCtx(void *pValue)
References _i16, OSI_OK, sl_LockObjLock, _SlDriverCb_t::GlobalLockObj, TRUE, _SlDriverCb_t::IsCmdRespWaited, SL_DRV_SYNC_OBJ_SIGNAL, _SlDriverCb_t::CmdSyncObj, SL_RET_CODE_OK, SL_DRV_LOCK_GLOBAL_LOCK_FOREVER, FALSE, _SL_PENDING_RX_MSG, SL_DRV_LOCK_GLOBAL_UNLOCK, VERIFY_RET_OK, _SlDrvMsgRead, SL_OS_RET_CODE_OK, SL_API_ABORTED, _SlDriverCb_t::RxDoneCnt, _SlDriverCb_t::FunctionParams, _SlFunctionParams_t::AsyncExt, AsyncExt_t::RxMsgClass, ASYNC_EVT_CLASS, VERIFY_PROTOCOL, NULL, AsyncExt_t::pAsyncBuf, _SlAsyncEventGenericHandler, DUMMY_MSG_CLASS, RECV_RESP_CLASS, CMD_RESP_CLASS.
Referenced by _SlDrvRxIrqHandler, _SlDrvMsgReadCmdCtx.
_SlReturnVal_t _SlDrvNetAppEventHandler(void *pArgs)
References _SlResponseHeader_t::GenHeader, _SlGenericHeader_t::Opcode, SL_OPCODE_NETAPP_DNSGETHOSTBYNAMEASYNCRESPONSE, SL_OPCODE_NETAPP_DNSGETHOSTBYNAMEASYNCRESPONSE_V6, _sl_HandleAsync_DnsGetHostByName, SL_OPCODE_NETAPP_MDNSGETHOSTBYSERVICEASYNCRESPONSE, SL_OPCODE_NETAPP_MDNSGETHOSTBYSERVICEASYNCRESPONSE_V6, _sl_HandleAsync_DnsGetHostByService, SL_OPCODE_NETAPP_PINGREPORTREQUESTRESPONSE, _sl_HandleAsync_PingResponse, SL_OPCODE_NETAPP_HTTPGETTOKENVALUE, _u8, _SL_RESP_ARGS_START, SlHttpServerResponse_t::Response, SL_NETAPP_HTTPSETTOKENVALUE, SlHttpServerResponse_t::ResponseData, SlHttpServerResponsedata_u::token_value, _slHttpServerString_t::len, MAX_TOKEN_VALUE_LEN, _slHttpServerString_t::data, MAX_TOKEN_NAME_LEN, SlHttpServerEvent_t::Event, SL_NETAPP_HTTPGETTOKENVALUE_EVENT, SlHttpServerEvent_t::EventData, SlHttpServerEventData_u::httpTokenName, _sl_NetAppHttpServerGetToken_t::token_name_len, _slHttpServerData_t::token_name, _slHttpServerData_t::value_len, _slHttpServerData_t::name_len, _slHttpServerData_t::token_value, SL_OPCODE_NETAPP_HTTPPOSTTOKENVALUE, SL_NETAPP_HTTPPOSTTOKENVALUE_EVENT, SlHttpServerEventData_u::httpPostData, _slHttpServerPostData_t::action, _sl_NetAppHttpServerPostToken_t::post_action_len, _slHttpServerPostData_t::token_name, _sl_NetAppHttpServerPostToken_t::token_name_len, _slHttpServerPostData_t::token_value, _sl_NetAppHttpServerPostToken_t::token_value_len, SL_NETAPP_RESPONSE_NONE, SL_ERROR_TRACE2, VERIFY_PROTOCOL, SL_RET_CODE_OK.
Referenced by _SlDrvClassifyRxMsg.
_SlReturnVal_t _SlDrvObjLock(_SlLockObj_t *pLockObj, _SlTime_t Timeout)
_SlReturnVal_t _SlDrvObjLockWaitForever(_SlLockObj_t *pLockObj)
References OSI_RET_OK_CHECK, sl_LockObjLock, SL_OS_WAIT_FOREVER, SL_OS_RET_CODE_OK.
_SlReturnVal_t _SlDrvObjUnLock(_SlLockObj_t *pLockObj)
References OSI_RET_OK_CHECK, sl_LockObjUnlock, SL_OS_RET_CODE_OK.
_u8 _SlDrvProtectAsyncRespSetting(_u8 *pAsyncRsp, _SlActionID_e ActionID, _u8 SocketID)
References _u8, _SlDrvWaitForPoolObj, SL_DRV_PROTECTION_OBJ_LOCK_FOREVER, g_pCB, _SlDriverCb_t::ObjPool, _SlPoolObj_t::pRespArgs, SL_DRV_PROTECTION_OBJ_UNLOCK.
_SlReturnVal_t _SlDrvProtectionObjLockWaitForever(void)
References OSI_RET_OK_CHECK, sl_LockObjLock, _SlDriverCb_t::ProtectionLockObj, SL_OS_WAIT_FOREVER, SL_OS_RET_CODE_OK.
_SlReturnVal_t _SlDrvProtectionObjUnLock(void)
References OSI_RET_OK_CHECK, sl_LockObjUnlock, _SlDriverCb_t::ProtectionLockObj, SL_OS_RET_CODE_OK.
void _SlDrvReleasePoolObj(_u8 pObj)
References _u8, SL_DRV_PROTECTION_OBJ_LOCK_FOREVER, _SlDriverCb_t::PendingPoolIdx, _SlDriverCb_t::ObjPool, _SlPoolObj_t::ActionID, SL_MAX_SOCKETS, _SlPoolObj_t::AdditionalData, BSD_SOCKET_ID_MASK, _SlRemoveFromList, SL_DRV_SYNC_OBJ_SIGNAL, _SlPoolObj_t::SyncObj, _SlPoolObj_t::NextIndex, _SlDriverCb_t::ActiveActionsBitmap, _SlPoolObj_t::pRespArgs, NULL, _SlDriverCb_t::ActivePoolIdx, _SlDriverCb_t::FreePoolIdx, SL_DRV_PROTECTION_OBJ_UNLOCK.
Referenced by _sl_HandleAsync_InitComplete, _SlDrvDataReadOp.
void _SlDrvResetCmdExt(_SlCmdExt_t *pCmdExt)
References _SlDrvMemZero, _u16.
_SlReturnVal_t _SlDrvRxIrqHandler(void *pValue)
References TRUE, _SlDriverCb_t::IsCmdRespWaited, OSI_RET_OK_CHECK, sl_SyncObjSignalFromIRQ, _SlDriverCb_t::CmdSyncObj, sl_Spawn, _SlDrvMsgReadSpawnCtx, NULL, SL_SPAWN_FLAG_FROM_SL_IRQ_HANDLER, SL_OS_RET_CODE_OK.
_SlReturnVal_t _SlDrvSyncObjSignal(_SlSyncObj_t *pSyncObj)
References OSI_RET_OK_CHECK, sl_SyncObjSignal, SL_OS_RET_CODE_OK.
_SlReturnVal_t _SlDrvSyncObjWaitForever(_SlSyncObj_t *pSyncObj)
References sl_SyncObjWait, SL_OS_WAIT_FOREVER, TRUE, SL_API_ABORTED, SL_RET_CODE_OK.
Referenced by _SlDrvMsgReadCmdCtx, _SlDrvWaitForPoolObj.
_SlReturnVal_t _SlDrvSyncObjWaitTimeout(_SlSyncObj_t *pSyncObj, _u32 timeoutVal, SlDriverAPIWithTimeout_e apiIdx)
References sl_SyncObjWait, _SlDriverHandleError, SL_DEVICE_DRIVER_TIMEOUT_ASYNC_EVENT, TRUE, SL_API_ABORTED, SL_RET_CODE_OK.
_u8 _SlDrvWaitForPoolObj(_u8 ActionID, _u8 SocketID)
References _u8, SL_DRV_PROTECTION_OBJ_LOCK_FOREVER, _SlDriverCb_t::FreePoolIdx, _SlDriverCb_t::ObjPool, _SlPoolObj_t::NextIndex, SL_DRV_PROTECTION_OBJ_UNLOCK, _SlPoolObj_t::ActionID, SL_MAX_SOCKETS, _SlPoolObj_t::AdditionalData, _SlDriverCb_t::ActiveActionsBitmap, _SlDriverCb_t::PendingPoolIdx, _SlDrvSyncObjWaitForever, _SlPoolObj_t::SyncObj, _SlDriverCb_t::ActivePoolIdx.
Referenced by _SlDrvProtectAsyncRespSetting, _SlDrvDataReadOp.