ff.c
_DF1E
_DF1S
Referenced by get_fileinfo, create_name.
_DF2E
_DF2S
_DS1E
_DS1S
_DS2E
_DS2S
ABORT
Referenced by f_read, f_write, f_lseek.
BPB_BkBootSec
Referenced by f_mkfs.
BPB_BytsPerSec
Referenced by find_volume, f_mkfs.
BPB_ExtFlags
BPB_FATSz16
Referenced by find_volume, f_mkfs.
BPB_FATSz32
Referenced by find_volume, f_mkfs.
BPB_FSInfo
Referenced by find_volume, f_mkfs.
BPB_FSVer
BPB_HiddSec
Referenced by f_mkfs.
BPB_Media
Referenced by f_mkfs.
BPB_NumFATs
Referenced by find_volume, f_mkfs.
BPB_NumHeads
Referenced by f_mkfs.
BPB_RootClus
Referenced by find_volume, f_mkfs.
BPB_RootEntCnt
Referenced by find_volume, f_mkfs.
BPB_RsvdSecCnt
Referenced by find_volume, f_mkfs.
BPB_SecPerClus
Referenced by find_volume, f_mkfs.
BPB_SecPerTrk
Referenced by f_mkfs.
BPB_TotSec16
Referenced by find_volume, f_mkfs.
BPB_TotSec32
Referenced by find_volume, f_mkfs.
BS_55AA
Referenced by sync_fs, check_fs, find_volume, f_mkfs.
BS_BootSig
Referenced by f_mkfs.
BS_BootSig32
Referenced by f_mkfs.
BS_DrvNum
Referenced by f_mkfs.
BS_DrvNum32
Referenced by f_mkfs.
BS_FilSysType
Referenced by check_fs.
BS_FilSysType32
Referenced by check_fs.
BS_jmpBoot
BS_NTres
BS_NTres32
BS_OEMName
BS_VolID
Referenced by f_mkfs.
BS_VolID32
Referenced by f_mkfs.
BS_VolLab
Referenced by f_mkfs.
BS_VolLab32
Referenced by f_mkfs.
DDEM
Referenced by dir_alloc, dir_find, dir_read, dir_remove, get_fileinfo, create_name.
DEFINE_NAMEBUF
Referenced by f_open, f_opendir, f_readdir, f_stat, f_unlink, f_mkdir, f_chmod, f_rename, f_utime.
DIR_Attr
Referenced by dir_find, dir_read, get_fileinfo, follow_path, f_open, f_sync, f_opendir, f_unlink, f_mkdir, f_chmod, f_rename.
DIR_CrtDate
DIR_CrtTime
Referenced by f_open.
DIR_CrtTimeTenth
DIR_FileSize
Referenced by get_fileinfo, f_open, f_sync.
DIR_FstClusHI
Referenced by ld_clust, st_clust.
DIR_FstClusLO
Referenced by ld_clust, st_clust.
DIR_LstAccDate
Referenced by f_sync.
DIR_Name
Referenced by dir_find, dir_read, f_mkdir.
DIR_NTres
Referenced by dir_register, get_fileinfo.
DIR_WrtDate
Referenced by get_fileinfo, f_utime.
DIR_WrtTime
Referenced by get_fileinfo, f_open, f_sync, f_mkdir, f_utime.
ENTER_FF
Referenced by find_volume, validate.
FREE_BUF
Referenced by f_open, f_opendir, f_readdir, f_stat, f_unlink, f_mkdir, f_chmod, f_rename, f_utime.
FSI_Free_Count
Referenced by sync_fs, find_volume, f_mkfs.
FSI_LeadSig
Referenced by sync_fs, find_volume, f_mkfs.
FSI_Nxt_Free
Referenced by sync_fs, find_volume, f_mkfs.
FSI_StrucSig
Referenced by sync_fs, find_volume, f_mkfs.
GET_FATTIME
Referenced by f_open, f_sync, f_mkdir, f_mkfs.
INIT_BUF
Referenced by f_open, f_opendir, f_readdir, f_stat, f_unlink, f_mkdir, f_chmod, f_rename, f_utime.
IsDBCS1
Referenced by gen_numname, get_fileinfo, create_name, f_gets.
IsDBCS2
Referenced by get_fileinfo, create_name.
IsDigit
Referenced by f_printf.
IsLower
Referenced by create_name, get_ldnumber, f_printf.
IsUpper
Referenced by get_fileinfo, create_name.
LDIR_Attr
Referenced by fit_lfn.
LDIR_Chksum
Referenced by fit_lfn, dir_find, dir_read.
LDIR_FstClusLO
Referenced by cmp_lfn, pick_lfn, fit_lfn.
LDIR_Ord
Referenced by cmp_lfn, pick_lfn, fit_lfn.
LDIR_Type
Referenced by fit_lfn.
LEAVE_FF
Referenced by f_mount, f_open, f_read, f_write, f_sync, f_lseek, f_opendir, f_readdir, f_stat, f_getfree, f_truncate, f_unlink, f_mkdir, f_chmod, f_rename, f_utime.
LLEF
Referenced by cmp_lfn, pick_lfn, fit_lfn, dir_find, dir_read.
MBR_Table
Referenced by find_volume, f_mkfs.
MIN_FAT16
Referenced by find_volume, f_mkfs.
MIN_FAT32
Referenced by find_volume, f_mkfs.
N_FATS
Referenced by f_mkfs.
N_ROOTDIR
Referenced by f_mkfs.
NS_BODY
Referenced by dir_register, get_fileinfo, create_name.
NS_DOT
Referenced by dir_register, create_name, follow_path, f_unlink, f_mkdir, f_chmod, f_rename, f_utime.
NS_EXT
Referenced by dir_register, get_fileinfo, create_name.
NS_LAST
Referenced by create_name, follow_path.
NS_LFN
Referenced by dir_register, create_name.
NS_LOSS
Referenced by dir_find, dir_register, create_name.
NSFLAG
Referenced by dir_find, dir_register, create_name, follow_path, f_unlink, f_mkdir, f_chmod, f_rename, f_utime.
RDDEM
Referenced by get_fileinfo, create_name.
SS
Referenced by sync_fs, get_fat, put_fat, dir_sdi, dir_next, find_volume, f_read, f_write, f_lseek, f_getfree, f_mkdir, f_mkfs.
SZ_DIRE
Referenced by dir_sdi, dir_next, dir_register, dir_remove, find_volume, f_mkdir, f_rename, f_mkfs.
SZ_PTE
Referenced by find_volume, f_mkfs.
FATFS* FatFs[_VOLUMES][_VOLUMES]
WORD Fsid
Referenced by find_volume.
const BYTE LfnOfs[][]
static BYTE check_fs(FATFS *fs, DWORD sect)
References FATFS::wflag, FATFS::winsect, move_window, FR_OK, LD_WORD, FATFS::win, BS_55AA, LD_DWORD, BS_FilSysType, BS_FilSysType32.
Referenced by find_volume.
static int chk_chr(const char *str, int chr)
Referenced by create_name.
DWORD clust2sect(FATFS *fs, DWORD clst)
References FATFS::n_fatent, FATFS::csize, FATFS::database.
Referenced by remove_chain, dir_sdi, dir_next, f_read, f_write, f_lseek, f_mkdir, f_rename.
static int cmp_lfn(WCHAR *lfnbuf, BYTE *dir)
References LD_WORD, LDIR_FstClusLO, LDIR_Ord, _MAX_LFN, ff_wtoupper, LLEF.
Referenced by dir_find.
static DWORD create_chain(FATFS *fs, DWORD clst)
References FATFS::last_clust, FATFS::n_fatent, get_fat, put_fat, FR_OK, FATFS::free_clust, FATFS::fsi_flag, FR_DISK_ERR.
Referenced by dir_next, f_write, f_lseek, f_mkdir.
static FRESULT create_name(DIR *dp, const TCHAR **path)
References DIR::lfn, _MAX_LFN, FR_INVALID_NAME, IsDBCS1, IsDBCS2, ff_convert, chk_chr, NS_LAST, DIR::fn, NS_DOT, FR_OK, mem_set, NS_LOSS, NS_LFN, ff_wtoupper, _DF1S, IsUpper, IsLower, DDEM, RDDEM, NS_EXT, NS_BODY, NSFLAG.
Referenced by follow_path.
static FRESULT dir_alloc(DIR *dp, UINT nent)
References dir_sdi, FR_OK, move_window, DIR::fs, DIR::sect, DIR::dir, DDEM, dir_next, FR_NO_FILE, FR_DENIED.
Referenced by dir_register.
static FRESULT dir_find(DIR *dp)
References dir_sdi, FR_OK, DIR::lfn_idx, move_window, DIR::fs, DIR::sect, DIR::dir, DIR_Name, FR_NO_FILE, DIR_Attr, AM_MASK, DDEM, AM_VOL, AM_LFN, DIR::lfn, LLEF, LDIR_Chksum, DIR::index, cmp_lfn, sum_sfn, DIR::fn, NSFLAG, NS_LOSS, mem_cmp, dir_next.
Referenced by dir_register, follow_path.
static FRESULT dir_next(DIR *dp, int stretch)
References DIR::index, DIR::sect, FR_NO_FILE, SS, DIR::fs, SZ_DIRE, DIR::clust, FATFS::n_rootdir, FATFS::csize, get_fat, FR_INT_ERR, FR_DISK_ERR, FATFS::n_fatent, create_chain, FR_DENIED, sync_window, mem_set, FATFS::win, FATFS::winsect, clust2sect, FATFS::wflag, DIR::dir, FR_OK.
Referenced by dir_alloc, dir_find, dir_read, dir_register, dir_remove, f_readdir.
static FRESULT dir_read(DIR *dp, int vol)
References FR_NO_FILE, DIR::sect, move_window, DIR::fs, FR_OK, DIR::dir, DIR_Name, DIR_Attr, AM_MASK, DDEM, _FS_RPATH, AM_ARC, AM_VOL, AM_LFN, LLEF, LDIR_Chksum, DIR::lfn_idx, DIR::index, pick_lfn, DIR::lfn, sum_sfn, dir_next.
Referenced by f_readdir, f_unlink.
static FRESULT dir_register(DIR *dp)
References DIR::fn, DIR::lfn, mem_cpy, _FS_RPATH, NSFLAG, NS_DOT, FR_INVALID_NAME, NS_LOSS, gen_numname, dir_find, FR_OK, FR_DENIED, FR_NO_FILE, NS_LFN, dir_alloc, dir_sdi, DIR::index, sum_sfn, move_window, DIR::fs, DIR::sect, fit_lfn, DIR::dir, FATFS::wflag, dir_next, mem_set, SZ_DIRE, DIR_NTres, NS_BODY, NS_EXT.
Referenced by f_open, f_mkdir, f_rename.
static FRESULT dir_remove(DIR *dp)
References DIR::index, dir_sdi, DIR::lfn_idx, FR_OK, move_window, DIR::fs, DIR::sect, mem_set, DIR::dir, SZ_DIRE, DDEM, FATFS::wflag, dir_next, FR_NO_FILE, FR_INT_ERR.
Referenced by f_unlink, f_rename.
static FRESULT dir_sdi(DIR *dp, UINT idx)
References DIR::index, DIR::sclust, DIR::fs, FATFS::n_fatent, FR_INT_ERR, FATFS::fs_type, FS_FAT32, FATFS::dirbase, FATFS::n_rootdir, SS, SZ_DIRE, FATFS::csize, get_fat, FR_DISK_ERR, clust2sect, DIR::clust, DIR::sect, DIR::dir, FATFS::win, FR_OK.
Referenced by dir_alloc, dir_find, dir_register, dir_remove, follow_path, f_opendir, f_readdir, f_unlink.
FRESULT f_chmod(const TCHAR *path, BYTE attr, BYTE mask)
The f_chmod function changes the attribute of a file or sub-directory.
The f_chmod() function changes the attribute of a file or sub-directory. Example: /*Setread-onlyflag,cleararchiveflagandothersareleftunchanged.*/ f_chmod("file.txt",AR_RDO,AR_RDO|AR_ARC); path Pointer to the null-terminated string that specifies an object to be changed attr Attribute flags to be set in one or more combination of the following flags. The specified flags are set and others are cleard. Attribute Description AM_RDO Read only AM_ARC Archive AM_SYS System AM_HID Hidden mask Attribute mask that specifies which attribute is changed. The specified attributes are set or cleard and others are left unchanged. FR_OK FR_DISK_ERR FR_INT_ERR FR_NOT_READY FR_NO_FILE FR_NO_PATH FR_INVALID_NAME FR_WRITE_PROTECTED FR_INVALID_DRIVE FR_NOT_ENABLED FR_NO_FILESYSTEM FR_TIMEOUT FR_NOT_ENOUGH_CORE Available when _FS_READONLY == 0 and _FS_MINIMIZE == 0.
References DEFINE_NAMEBUF, find_volume, DIR::fs, FR_OK, INIT_BUF, follow_path, FREE_BUF, _FS_RPATH, DIR::fn, NSFLAG, NS_DOT, FR_INVALID_NAME, DIR::dir, AM_RDO, AM_HID, AM_SYS, AM_ARC, DIR_Attr, FATFS::wflag, sync_fs, LEAVE_FF.
FRESULT f_close(FIL *fp)
The f_close function closes an open file.
The f_close() function closes an open file object. If any data has been written to the file, the cached information of the file is written back to the volume. After the function succeeded, the file object is no longer valid and it can be discarded. Note that if the file object is in read-only mode and _FS_LOCK option is not enabled, the file object can also be discarded without this process. However this is not recommended for future compatibility. fp Pointer to the open file object structure to be closed. FR_OK FR_DISK_ERR FR_INT_ERR FR_NOT_READY FR_INVALID_OBJECT FR_TIMEOUT Always available.
References f_sync, FR_OK, validate, FIL::fs, unlock_fs.
FRESULT f_closedir(DIR *dp)
The f_closedir function closes an open directory.
The f_closedir() function closes an open directory object. After the function succeeded, the directory object is no longer valid and it can be discarded. Note that the directory object can also be discarded without this process if _FS_LOCK option is not enabled. However this is not recommended for future compatibility. dp Pointer to the open directory object structure to be closed. FR_OK FR_INT_ERR FR_INVALID_OBJECT FR_TIMEOUT Available when _FS_MINIMIZE <= 1.
References validate, FR_OK, DIR::fs, unlock_fs.
FRESULT f_getfree(const TCHAR *path, DWORD *nclst, FATFS **fatfs)
The f_getfree function gets number of the free clusters on the volume.
The f_getfree() function gets number of free clusters on the volume. The member csize in the file system object indicates number of sectors per cluster, so that the free space in unit of sector can be calcurated with this information. When FSINFO structure on the FAT32 volume is not in sync, this function can return an incorrect free cluster count. To avoid this problem, FatFs can be forced full FAT scan by _FS_NOFSINFO option. Example: FATFS*fs; DWORDfre_clust,fre_sect,tot_sect; /*Getvolumeinformationandfreeclustersofdrive1*/ res=f_getfree("1:",&fre_clust,&fs); if(res)die(res); /*Gettotalsectorsandfreesectors*/ tot_sect=(fs->n_fatent-2)*fs->csize; fre_sect=fre_clust*fs->csize; /*Printthefreespace(assuming512bytes/sector)*/ printf("%10luKiBtotaldrivespace.\n%10luKiBavailable.\n", tot_sect/2,fre_sect/2); path Pointer to the null-terminated string that specifies the logical drive. A null-string means the default drive. nclst Pointer to the DWORD variable to store number of free clusters. fatfs Pointer to pointer that to store a pointer to the corresponding file system object. FR_OK FR_DISK_ERR FR_INT_ERR FR_NOT_READY FR_INVALID_DRIVE FR_NOT_ENABLED FR_NO_FILESYSTEM FR_TIMEOUT Available when _FS_READONLY == 0 and _FS_MINIMIZE == 0.
References find_volume, FR_OK, FATFS::free_clust, FATFS::n_fatent, FATFS::fs_type, FS_FAT12, get_fat, FR_DISK_ERR, FR_INT_ERR, FATFS::fatbase, move_window, FATFS::win, SS, FS_FAT16, LD_WORD, LD_DWORD, FATFS::fsi_flag, LEAVE_FF.
TCHAR* f_gets(TCHAR *buff, int len, FIL *fp)
The f_gets reads a string from the file.
The f_gets() function is a wrapper function of f_read() function. The read operation continues until a ' ' is stored, reached end of the file or the buffer is filled with len - 1 characters. The read string is terminated with a '\0'. When no character to read or any error occured during read operation, it returns a null pointer. The status of EOF and error can be examined with f_eof() and f_error() macros. When FatFs is configured to Unicode API (_LFN_UNICODE == 1), data types on the srting fuctions, f_putc(), f_puts(), f_printf() and f_gets(), is also switched to Unicode. The character encoding on the file to be read/written via those functions is selected by _STRF_ENCODE option. buff Pointer to read buffer to store the read string. len Size of the read buffer in unit of character. fp Pointer to the open file object structure. When the function succeeded, buff will be returuned. Available when _USE_STRFUNC is 1 or 2. When it is set to 2, ''s contained in the file are stripped out.
References f_read, IsDBCS1, ff_convert, _USE_STRFUNC.
FRESULT f_lseek(FIL *fp, DWORD ofs)
The f_lseek function moves the file read/write pointer of an open file object. It can also be used to expand the file size (cluster pre-allocation).
The f_lseek() function moves the file read/write pointer of an open file. The offset can be specified in only origin from top of the file. When an offset beyond the file size is specified at write mode, the file size is expanded to the specified offset. The file data in the expanded area is undefined because no data is written to the file. This is suitable to pre-allocate a cluster chain quickly, for fast write operation. After the f_lseek() function succeeded, the current read/write pointer should be checked in order to make sure the read/write pointer has been moved correctry. In case of the current read/write pointer is not the expected value, either of followings has been occured. End of file. The specified ofs was clipped at end of the file because the file has been opened in read-only mode. Disk full. There is insufficient free space on the volume to expand the file. Fast seek feature is enabled when _USE_FASTSEEK is set to 1 and the member cltbl in the file object is not NULL. This feature enables fast backward/long seek operations without FAT access by using CLMT (cluster link map table). The fast seek feature is also applied to f_read()/f_write() function, however, the file size cannot be expanded by f_write()/f_lseek() function. The CLMT must be created in the user defined DWORD array prior to use the fast seek feature. To create the CLMT, set address of the DWORD array to the member cltbl in the file object, set the array size in unit of items into the first item and call the f_lseek() function with ofs = CREATE_LINKMAP. After the function succeeded and CLMT is created, no FAT access is occured at subsequent f_read()/f_write()/f_lseek() function to the file. If the function failed with FR_NOT_ENOUGH_CORE, the given array size is insufficient for the file and number of items required is returned into the first item of the array. The required array size is (number of fragments + 1) * 2 items. For example, when the file is fragmented in 5, 12 items will be required for the CLMT. Examples: /*Openfile*/ fp=malloc(sizeof(FIL)); res=f_open(fp,"file.dat",FA_READ|FA_WRITE); if(res)... /*Movetooffsetof5000fromtopofthefile*/ res=f_lseek(fp,5000); /*Movetoendofthefiletoappenddata*/ res=f_lseek(fp,f_size(fp)); /*Forward3000bytes*/ res=f_lseek(fp,f_tell(fp)+3000); /*Rewind2000bytes(takecareonwraparound)*/ res=f_lseek(fp,f_tell(fp)-2000); /*Clusterpre-allocation(topreventbufferoverrunonstreamingwrite)*/ res=f_open(fp,recfile,FA_CREATE_NEW|FA_WRITE);/*Createafile*/ res=f_lseek(fp,PRE_SIZE);/*Expandfilesize(clusterpre-allocation)*/ if(res||f_tell(fp)!=PRE_SIZE).../*Checkifthefilehasbeenexpanded*/ res=f_lseek(fp,DATA_START);/*RecorddatastreamWITHOUTclusterallocationdelay*/ .../*DATA_STARTandwriteblocksizeshouldbealignedtosectorboundary*/ res=f_truncate(fp);/*Truncateunusedarea*/ res=f_lseek(fp,0);/*Putfileheader*/ ... res=f_close(fp); /*Usingfastseekfeature*/ DWORDclmt[SZ_TBL];/*Clusterlinkmaptablebuffer*/ res=f_lseek(fp,ofs1);/*Thisisnormalseek(cltblisnulledonfileopen)*/ fp->cltbl=clmt;/*Enablefastseekfeature(cltbl!=NULL)*/ clmt[0]=SZ_TBL;/*Settablesize*/ res=f_lseek(fp,CREATE_LINKMAP);/*CreateCLMT*/ ... res=f_lseek(fp,ofs2);/*Thisisfastseek*/ fp Pointer to the open file object. ofs Byte offset from top of the file. FR_OK FR_DISK_ERR FR_INT_ERR FR_NOT_READY FR_INVALID_OBJECT FR_TIMEOUT Available when _FS_MINIMIZE <= 2.
References validate, FR_OK, LEAVE_FF, FIL::fs, FIL::err, CREATE_LINKMAP, FIL::sclust, get_fat, ABORT, FR_INT_ERR, FR_DISK_ERR, FATFS::n_fatent, FR_NOT_ENOUGH_CORE, FIL::fsize, FIL::fptr, FIL::clust, clust2sect, SS, FATFS::csize, FIL::dsect, FIL::flag, FA__DIRTY, disk_write, FATFS::drv, FIL::buf, RES_OK, disk_read, _FS_READONLY, FA_WRITE, create_chain, FA__WRITTEN.
FRESULT f_mkdir(const TCHAR *path)
The f_mkdir function creates a new directory.
This function creates a new directory. Example: res=f_mkdir("sub1"); if(res)die(res); res=f_mkdir("sub1/sub2"); if(res)die(res); res=f_mkdir("sub1/sub2/sub3"); if(res)die(res); path Pointer to the null-terminated string that specifies the directory name to create. FR_OK FR_DISK_ERR FR_INT_ERR FR_NOT_READY FR_NO_PATH FR_INVALID_NAME FR_DENIED FR_EXIST FR_WRITE_PROTECTED FR_INVALID_DRIVE FR_NOT_ENABLED FR_NO_FILESYSTEM FR_TIMEOUT FR_NOT_ENOUGH_CORE Available when _FS_READONLY == 0 and _FS_MINIMIZE == 0.
References GET_FATTIME, DEFINE_NAMEBUF, find_volume, DIR::fs, FR_OK, INIT_BUF, follow_path, FR_EXIST, _FS_RPATH, FR_NO_FILE, DIR::fn, NSFLAG, NS_DOT, FR_INVALID_NAME, create_chain, FR_DENIED, FR_INT_ERR, FR_DISK_ERR, sync_window, clust2sect, FATFS::win, mem_set, SS, DIR_Name, DIR_Attr, AM_DIR, ST_DWORD, DIR_WrtTime, st_clust, mem_cpy, SZ_DIRE, DIR::sclust, FATFS::fs_type, FS_FAT32, FATFS::dirbase, FATFS::csize, FATFS::winsect, FATFS::wflag, dir_register, remove_chain, DIR::dir, sync_fs, FREE_BUF, LEAVE_FF.
FRESULT f_mkfs(const TCHAR *path, BYTE sfd, UINT au)
The f_mkfs fucntion creates an FAT file system on the logical drive.
The f_mkfs() function creates an FAT volume on the specified logical drive. When FDISK format is specified, a primary partition occupies entire space of the physical drive is created and then an FAT volume is created on the partition. When SFD format is specified, the FAT volume starts from the first sector of the physical drive. If the logical drive is bound to the specific partition (1-4) by multiple partition feature (_MULTI_PARTITION), the FAT volume is created into the partition. In this case, the second argument sfd is ignored. The physical drive must have been partitioned with f_fdisk() function or any other partitioning tools prior to create the FAT volume with this function. Note that there are two partitioning rules, FDISK and SFD. The FDISK partitioning is usually used for harddisk, MMC, SDC, CFC and U Disk. It can divide a physical drive into one or more partitions with a partition table on the MBR. However Windows does not support multiple partition on the removable disk. The SFD is non-partitioned method. The FAT volume starts from the first sector on the physical drive without partition table. It is usually used for floppy disk, Microdrive, optical disk and any type of super-floppy media. The FAT sub-type, FAT12/FAT16/FAT32, is determined by number of clusters on the volume and nothing else, according to the FAT specification issued by Microsoft. Thus which FAT sub-type is selected, is depends on the volume size and the specified cluster size. The cluster size affects read/write throughput and space usage efficiency. Larger cluster size increases the read/write throughput and decreases the space usage efficiency of the volume. In case of the number of clusters gets near the FAT sub-type boundaries, the function can fail with FR_MKFS_ABORTED. Example: /*Formatthedefaultdrive*/ intmain(void) { FATFSfs;/*Filesystemobject(volumeworkarea)*/ FILfil;/*Fileobject*/ FRESULTres;/*APIresultcode*/ UINTbw;/*Byteswritten*/ /*Registerworkarea*/ f_mount(&fs,"",0); /*CreateFATvolumewithdefaultclustersize*/ res=f_mkfs("",0,0); if(res)... /*Createafileasnew*/ res=f_open(&fil,"hello.txt",FA_CREATE_NEW|FA_WRITE); if(res)... /*Writeamessage*/ f_write(&fil,"Hello,World!\r\n",15,&bw); if(bw!=15)... /*Closethefile*/ f_close(&fil); /*Unregisterworkarea*/ f_mount(0,"",0); path Pointer to the null-terminated string that specifies the logical drive to be formatted. If there is no drive number, it means the default drive. sfd Specifies partitioning rule (FDISK(0) or SFD(1)). This argument will be ignored on some case. au Specifies size of the allocation unit (cluter) in number of bytes or sectors. When the value is from 1 to 128, it specifies number of sectors. When the value is >= _MIN_SS, it specifies number of bytes. If any invalid value, zero or not power of 2, is given, the cluster size is automatically determined depends on the volume size. FR_OK FR_DISK_ERR FR_NOT_READY FR_WRITE_PROTECTED FR_INVALID_DRIVE FR_NOT_ENABLED FR_MKFS_ABORTED FR_INVALID_PARAMETER Available when _FS_READOLNY == 0 and _USE_MKFS == 1.
References FR_INVALID_PARAMETER, get_ldnumber, FR_INVALID_DRIVE, FR_NOT_ENABLED, FATFS::fs_type, LD2PD, LD2PT, disk_initialize, STA_NOINIT, FR_NOT_READY, STA_PROTECT, FR_WRITE_PROTECTED, disk_ioctl, GET_SECTOR_SIZE, SS, RES_OK, _MAX_SS, _MIN_SS, FR_DISK_ERR, _MULTI_PARTITION, disk_read, FATFS::win, LD_WORD, BS_55AA, FR_MKFS_ABORTED, MBR_Table, SZ_PTE, LD_DWORD, GET_SECTOR_COUNT, FS_FAT12, MIN_FAT16, FS_FAT16, MIN_FAT32, FS_FAT32, N_ROOTDIR, SZ_DIRE, N_FATS, GET_BLOCK_SIZE, disk_write, mem_set, ST_DWORD, ST_WORD, mem_cpy, BPB_BytsPerSec, BPB_SecPerClus, BPB_RsvdSecCnt, BPB_NumFATs, BPB_RootEntCnt, BPB_TotSec16, BPB_TotSec32, BPB_Media, BPB_SecPerTrk, BPB_NumHeads, BPB_HiddSec, GET_FATTIME, BS_VolID32, BPB_FATSz32, BPB_RootClus, BPB_FSInfo, BPB_BkBootSec, BS_DrvNum32, BS_BootSig32, BS_VolLab32, BS_VolID, BPB_FATSz16, BS_DrvNum, BS_BootSig, BS_VolLab, CTRL_TRIM, FSI_LeadSig, FSI_StrucSig, FSI_Free_Count, FSI_Nxt_Free, CTRL_SYNC, FR_OK.
FRESULT f_mount(FATFS *fs, const TCHAR *path, BYTE opt)
The f_mount fucntion registers/unregisters file system object to the FatFs module.
The f_mount() function registers/unregisters a file system object used for the logical drive to the FatFs module as follows: 1.Determines the logical drive which specified by path. 2.Clears and unregisters the regsitered work area of the drive. 3.Clears and registers the new work area to the drive if fs is not NULL. 4.Performs volume mount process to the drive if forced mount is specified. The file system object is the work area needed for each logical drive. It must be given to the logical drive with this function prior to use any other file functions except for f_fdisk() function. To unregister a work area, specify a NULL to the fs, and then the work area can be discarded. If forced mount is not specified, this function always succeeds regardless of the physical drive status due to delayed mount feature. It only clears (de-initializes) the given work area and registers its address to the internal table. No activity of the physical drive in this function. It can also be used to force de-initialized the registered work area of a logical drive. The volume mount processes, initialize the corresponding physical drive, find the FAT volume in it and initialize the work area, is performed in the subsequent file access functions when either or both of following condition is true. File system object is not initialized. It is cleared by f_mount().Physical drive is not initialized. It is de-initialized by system reset or media removal. If the function with forced mount failed, it means that the file system object has been registered successfully but the volume is currently not ready to use. Mount process will also be attempted in subsequent file access functions. If implementation of the disk I/O layer lacks media change detection, application program needs to perform a f_mount() after each media change to force cleared the file system object. fs Pointer to the new file system object to be registered. Null pointer unregisters the registered file system object. path Pointer to the null-terminated string that specifies the logical drive. The string with no drive number means the default drive. opt Initialization option. 0: Do not mount now (to be mounted later),1: Force mounted the volume to check if the FAT volume is available. FR_OK FR_INVALID_DRIVE FR_DISK_ERR FR_NOT_READY FR_NO_FILESYSTEM Always available.
References get_ldnumber, FR_INVALID_DRIVE, ff_del_syncobj, FATFS::sobj, FR_INT_ERR, FATFS::fs_type, ff_cre_syncobj, FR_OK, find_volume, LEAVE_FF.
FRESULT f_open(FIL *fp, const TCHAR *path, BYTE mode)
The f_open function creates a file object to be used to access the file.
After f_open() function succeeded, the file object is valid. The file object is used for subsequent read/write functions to identify the file. To close an open file, use f_close() function. If the file is modified and not closed properly, the file data will be collapsed. If duplicated file open is needed, read here carefully. However duplicated open of a file with write mode flag is always prohibited. Before using any file function, a work area (file system object) must be registered to the logical drive with f_mount() function. All API functions except for f_fdisk() function can work after this procedure. Examples: /*Readatextfileanddisplayit*/ FATFSFatFs;/*Workarea(filesystemobject)forlogicaldrive*/ intmain(void) { FILfil;/*Fileobject*/ charline[82];/*Linebuffer*/ FRESULTfr;/*FatFsreturncode*/ /*Registerworkareatothedefaultdrive*/ f_mount(&FatFs,"",0); /*Openatextfile*/ fr=f_open(&fil,"message.txt",FA_READ); if(fr)return(int)fr; /*Readalllinesanddisplayit*/ while(f_gets(line,sizeofline,&fil)) printf(line); /*Closethefile*/ f_close(&fil); return0; } /*Copyafile"file.bin"onthedrive1todrive0*/ intmain(void) { FATFSfs[2];/*Workarea(filesystemobject)forlogicaldrives*/ FILfsrc,fdst;/*Fileobjects*/ BYTEbuffer[4096];/*Filecopybuffer*/ FRESULTfr;/*FatFsfunctioncommonresultcode*/ UINTbr,bw;/*Fileread/writecount*/ /*Registerworkareaforeachlogicaldrive*/ f_mount(&fs[0],"0:",0); f_mount(&fs[1],"1:",0); /*Opensourcefileonthedrive1*/ fr=f_open(&fsrc,"1:file.bin",FA_OPEN_EXISTING|FA_READ); if(fr)return(int)fr; /*Createdestinationfileonthedrive0*/ fr=f_open(&fdst,"0:file.bin",FA_CREATE_ALWAYS|FA_WRITE); if(fr)return(int)fr; /*Copysourcetodestination*/ for(;;){ fr=f_read(&fsrc,buffer,sizeofbuffer,&br);/*Readachunkofsourcefile*/ if(fr||br==0)break;/*errororeof*/ fr=f_write(&fdst,buffer,br,&bw);/*Writeittothedestinationfile*/ if(fr||bw<br)break;/*errorordiskfull*/ } /*Closeopenfiles*/ f_close(&fsrc); f_close(&fdst); /*Unregisterworkareapriortodiscardit*/ f_mount(NULL,"0:",0); f_mount(NULL,"1:",0); return(int)fr; } fp Pointer to the blank file object structure to be created. path Pointer to a null-terminated string that specifies the file name to open or create. mode Mode flags that specifies the type of access and open method for the file. It is specified by a combination of following flags. Value Description FA_READ Specifies read access to the object. Data can be read from the file. Combine with FA_WRITE for read-write access. FA_WRITE Specifies write access to the object. Data can be written to the file. Combine with FA_READ for read-write access. FA_OPEN_EXISTING Opens the file. The function fails if the file is not existing. (Default) . FA_OPEN_ALWAYS Opens the file if it is existing. If not, a new file is created. To append data to the file, use f_lseek() function after file open in this method. FA_CREATE_NEW Creates a new file. The function fails with FR_EXIST if the file is existing. FA_CREATE_NEW Creates a new file. If the file is existing, it will be truncated and overwritten. FR_OK FR_DISK_ERR FR_INT_ERR FR_NOT_READY FR_NO_FILE FR_NO_PATH FR_INVALID_NAME FR_DENIED FR_EXIST FR_INVALID_OBJECT FR_WRITE_PROTECTED FR_INVALID_DRIVE FR_NOT_ENABLED FR_NO_FILESYSTEM FR_TIMEOUT FR_LOCKED FR_NOT_ENOUGH_CORE FR_TOO_MANY_OPEN_FILES Always available. The mode flags, FA_WRITE, FA_CREATE_ALWAYS, FA_CREATE_NEW and FA_OPEN_ALWAYS, are not available when _FS_READONLY == 1.
References DEFINE_NAMEBUF, FR_INVALID_OBJECT, FIL::fs, FA_READ, FA_WRITE, FA_CREATE_ALWAYS, FA_OPEN_ALWAYS, FA_CREATE_NEW, find_volume, DIR::fs, FR_OK, INIT_BUF, follow_path, DIR::dir, FR_INVALID_NAME, FR_NO_FILE, dir_register, FR_TOO_MANY_OPEN_FILES, DIR_Attr, AM_RDO, AM_DIR, FR_DENIED, FR_EXIST, GET_FATTIME, ST_DWORD, DIR_CrtTime, DIR_WrtTime, DIR_FileSize, ld_clust, st_clust, FATFS::wflag, FATFS::winsect, remove_chain, FATFS::last_clust, move_window, FA__WRITTEN, FIL::dir_sect, FIL::dir_ptr, FR_INT_ERR, FREE_BUF, FIL::flag, FIL::err, FIL::sclust, FIL::fsize, LD_DWORD, FIL::fptr, FIL::dsect, FIL::id, FATFS::id, LEAVE_FF.
FRESULT f_opendir(DIR *dp, const TCHAR *path)
The f_opendir function opens a directory.
The f_opendir() function opens an exsisting directory and creates a directory object for subsequent f_readdir() function. dp Pointer to the blank directory object to create a new one. path Pointer to the null-terminated string that specifies the directory name to be opened. FR_OK FR_DISK_ERR FR_INT_ERR FR_NOT_READY FR_NO_PATH FR_INVALID_NAME FR_INVALID_OBJECT FR_INVALID_DRIVE FR_NOT_ENABLED FR_NO_FILESYSTEM FR_TIMEOUT FR_NOT_ENOUGH_CORE FR_TOO_MANY_OPEN_FILES Available when _FS_MINIMIZE <= 1.
References DEFINE_NAMEBUF, FR_INVALID_OBJECT, find_volume, FR_OK, DIR::fs, INIT_BUF, follow_path, FREE_BUF, DIR::dir, DIR_Attr, AM_DIR, DIR::sclust, ld_clust, FR_NO_PATH, DIR::id, FATFS::id, dir_sdi, FR_TOO_MANY_OPEN_FILES, FR_NO_FILE, LEAVE_FF.
int f_printf(FIL *fp, const TCHAR *fmt,...)
The f_printf function writes formatted string to the file.
The f_printf() is a wrapper function of f_write(). The format control directive is a sub-set of standard library shown as follows: Type: c C s S d D u U x X b BSize: l LFlag: 0 - Example: f_printf(&fil,"%d",1234);/*"1234"*/ f_printf(&fil,"%6d,%3d%%",-200,5);/*"-200,5%"*/ f_printf(&fil,"%ld",12345L);/*"12345"*/ f_printf(&fil,"%06d",25);/*"000025"*/ f_printf(&fil,"%06d",-25);/*"000-25"*/ f_printf(&fil,"%-6d",25);/*"25"*/ f_printf(&fil,"%u",-1);/*"65535"or"4294967295"*/ f_printf(&fil,"%04x",0xAB3);/*"0ab3"*/ f_printf(&fil,"%08LX",0x123ABCL);/*"00123ABC"*/ f_printf(&fil,"%016b",0x550F);/*"0101010100001111"*/ f_printf(&fil,"%s","String");/*"String"*/ f_printf(&fil,"%8s","abc");/*"abc"*/ f_printf(&fil,"%-8s","abc");/*"abc"*/ f_printf(&fil,"%c",'a');/*"a"*/ f_printf(&fil,"%f",10.0);/*f_printflacksfloatingpointsupport*/ fp Pointer to the open file object structure. fmt Pointer to the null terminated format string. The terminator charactor will not be written. ... Optional arguments... When the function succeeded, it returns number of characters written. When the function failed due to disk full or any error, an EOF (-1) will be returned. Available when _FS_READONLY == 0 and _USE_STRFUNC is 1 or 2. When it is set to 2, ' 's contained in the output are converted to ''+' '. When FatFs is configured to Unicode API (_LFN_UNICODE == 1), data types on the srting fuctions, f_putc(), f_puts(), f_printf() and f_gets(), is also switched to Unicode. The character encoding on the file to be read/written via those functions is selected by _STRF_ENCODE option.
References putbuff::fp, putbuff::nchr, putbuff::idx, putc_bfd, IsDigit, IsLower, f_write, putbuff::buf, FR_OK, EOF.
int f_putc(TCHAR c, FIL *fp)
The f_putc funciton puts a character to the file.
The f_putc() function is a wrapper function of f_write() function. chr A character to be put. fp Pointer to the open file object structuer. When the character was written successfuly, it returns number of characters written. When the function failed due to disk full or any error, an EOF (-1) will be returned. When FatFs is configured to Unicode API (_LFN_UNICODE == 1), character encoding on the string fuctions, f_putc(), f_puts(), f_printf() and f_gets(), is also switched to Unicode. The character encoding on the file to be read/written via those functions is selected by _STRF_ENCODE option. Available when _FS_READONLY == 0 and _USE_STRFUNC is 1 or 2. When it is set to 2, a ' ' is converted to ''+' '.
References putbuff::fp, putbuff::nchr, putbuff::idx, putc_bfd, f_write, putbuff::buf, FR_OK, EOF.
int f_puts(const TCHAR *str, FIL *fp)
The f_puts function writes a string to the file.
The f_puts() function is a wrapper function of f_write() function. str Pointer to the null terminated string to be written. The terminator character will not be written. fp Pointer to the open file object structure. When the function succeeded, it returns number of characters written. When the write operation is aborted due to disk full or any error, an EOF (-1) will be returned. When FatFs is configured to Unicode API (_LFN_UNICODE == 1), character encoding on the srting fuctions, f_putc(), f_puts(), f_printf() and f_gets(), is also switched to Unicode. The character encoding on the file to be read/written via those functions is selected by _STRF_ENCODE option. Available when _FS_READONLY == 0 and _USE_STRFUNC is 1 or 2. When it is set to 2, ' 's contained in the string are converted to ''+' '.
References putbuff::fp, putbuff::nchr, putbuff::idx, putc_bfd, f_write, putbuff::buf, FR_OK, EOF.
FRESULT f_read(FIL *fp, void *buff, UINT btr, UINT *br)
The f_read function reads data from a file.
The file read/write pointer of the file object advances number of bytes read. After the function succeeded, *br should be checked to detect end of the file. In case of *br is less than btr, it means the read/write pointer reached end of the file during read operation. fp Pointer to the open file object. buff Pointer to the buffer to store read data. btr Number of bytes to read in range of UINT type. br Pointer to the UINT variable to return number of bytes read. The value is always valid after the function call regardless of the result. FR_OK FR_DISK_ERR FR_INT_ERR FR_NOT_READY FR_INVALID_OBJECT FR_TIMEOUT Always available.
References validate, FR_OK, LEAVE_FF, FIL::fs, FIL::err, FIL::flag, FA_READ, FR_DENIED, FIL::fsize, FIL::fptr, SS, FATFS::csize, FIL::sclust, get_fat, FIL::clust, ABORT, FR_INT_ERR, FR_DISK_ERR, clust2sect, disk_read, FATFS::drv, RES_OK, FATFS::wflag, FATFS::winsect, mem_cpy, FATFS::win, FA__DIRTY, FIL::dsect, FIL::buf, disk_write, move_window.
Referenced by f_gets.
FRESULT f_readdir(DIR *dp, FILINFO *fno)
The f_readdir function reads directory entries.
The f_readdir() function reads directory items, file and directory, in sequence. All items in the directory can be read by calling f_readdir() function repeatedly. When relative path feature is enabled (_FS_RPATH >= 1), dot entries ("." and "..") are not filtered out and they will appear in the read items. When all directory items have been read and no item to read, a null string is returned into the fname[] without any error. When a null pointer is given to the fno, the read index of the directory object is rewinded. When LFN feature is enabled, lfname and lfsize in the file information structure must be initialized with valid value prior to use it. The lfname is a pointer to the LFN read buffer. The lfsize is size of the LFN read buffer in unit of TCHAR. If the LFN is not needed, set a null pointer to the lfname and the LFN is not returned. A null string will be returned into the LFN read buffer in case of following conditions. The directory item has no LFN information.Either the size of read buffer or LFN working buffer is insufficient for the LFN.The LFN contains any Unicode character that cannot be converted to OEM code. (not the case at Unicode API cfg.) When the directory item has no LFN information, lower case characters can be contained in the fname[]. Sample Code: FRESULTscan_files( char*path/*Startnodetobescanned(alsousedasworkarea)*/ ) { FRESULTres; FILINFOfno; DIRdir; inti; char*fn;/*Thisfunctionassumesnon-Unicodeconfiguration*/ #if_USE_LFN staticcharlfn[_MAX_LFN+1];/*BuffertostoretheLFN*/ fno.lfname=lfn; fno.lfsize=sizeoflfn; #endif res=f_opendir(&dir,path);/*Openthedirectory*/ if(res==FR_OK){ i=strlen(path); for(;;){ res=f_readdir(&dir,&fno);/*Readadirectoryitem*/ if(res!=FR_OK||fno.fname[0]==0)break;/*Breakonerrororendofdir*/ if(fno.fname[0]=='.')continue;/*Ignoredotentry*/ #if_USE_LFN fn=*fno.lfname?fno.lfname:fno.fname; #else fn=fno.fname; #endif if(fno.fattrib&AM_DIR){/*Itisadirectory*/ sprintf(&path[i],"/%s",fn); res=scan_files(path); path[i]=0; if(res!=FR_OK)break; }else{/*Itisafile.*/ printf("%s/%s\n",path,fn); } } f_closedir(&dir) } returnres; } dp Pointer to the open directory object. fno Pointer to the file information structure to store the read item. FR_OK FR_DISK_ERR FR_INT_ERR FR_NOT_READY FR_INVALID_OBJECT FR_TIMEOUT FR_NOT_ENOUGH_CORE Available when _FS_MINIMIZE <= 1.
References DEFINE_NAMEBUF, validate, FR_OK, dir_sdi, INIT_BUF, dir_read, FR_NO_FILE, DIR::sect, get_fileinfo, dir_next, FREE_BUF, LEAVE_FF, DIR::fs.
FRESULT f_rename(const TCHAR *path_old, const TCHAR *path_new)
Renames a file or sub-directory.
Renames a file or sub-directory and can also move it to other directory within the same logical drive. Do not rename open objects or directry table can be broken. Example: /*Renameanobject*/ f_rename("oldname.txt","newname.txt"); /*Renameandmoveanobjecttootherdirectory*/ f_rename("oldname.txt","dir1/newname.txt"); old_name Pointer to a null-terminated string that specifies an existing file or sub-directory to be renamed. new_name Pointer to a null-terminated string that specifies the new object name. The drive number specified in this string is ignored and one determined by old_name is used instead. FR_OK FR_DISK_ERR FR_INT_ERR FR_NOT_READY FR_NO_FILE FR_NO_PATH FR_INVALID_NAME FR_DENIED FR_EXIST FR_EXIST FR_WRITE_PROTECTED FR_INVALID_DRIVE FR_NOT_ENABLED FR_NO_FILESYSTEM FR_TIMEOUT FR_LOCKED FR_NOT_ENOUGH_CORE Available when _FS_READONLY == 0 and _FS_MINIMIZE == 0.
References DEFINE_NAMEBUF, find_volume, DIR::fs, FR_OK, INIT_BUF, follow_path, _FS_RPATH, DIR::fn, NSFLAG, NS_DOT, FR_INVALID_NAME, DIR::dir, FR_NO_FILE, mem_cpy, DIR_Attr, get_ldnumber, FR_INVALID_DRIVE, FR_EXIST, dir_register, AM_ARC, FATFS::wflag, AM_DIR, DIR::sclust, clust2sect, ld_clust, FR_INT_ERR, move_window, FATFS::win, SZ_DIRE, st_clust, dir_remove, sync_fs, FREE_BUF, LEAVE_FF.
Referenced by FOTA_ValidateSdcardFw.
FRESULT f_stat(const TCHAR *path, FILINFO *fno)
The f_stat function checks the existence of a file or sub-directory.
The f_stat() function checks the existence of a file or sub-directory. If not exist, the function returns with FR_NO_FILE. If exist, the function returns with FR_OK and the informations of the object, file size, timestamp, attribute and SFN, are stored to the file information structure. For details of the file information, refer to the FILINFO structure and f_readdir() function. When LFN feature is enabled, lfname in the file information structure must be NULLed prior to use it. Examples: FRESULTfr; FILINFOfno; printf("Testfor'file.txt'...\n"); #if_USE_LFN fno.lfname=0; #endif fr=f_stat("file.txt",&fno); switch(fr){ caseFR_OK: printf("Size:%u\n",fno.fsize); printf("Timestamp:%u/%02u/%02u,%02u:%02u\n", (fno.fdate>>9)+1980,fno.fdate>>5&15,fno.fdate&31, fno.ftime>>11,fno.ftime>>5&63); printf("Attributes:%c%c%c%c%c\n", (fno.fattrib&AM_DIR)?'D':'-', (fno.fattrib&AM_RDO)?'R':'-', (fno.fattrib&AM_HID)?'H':'-', (fno.fattrib&AM_SYS)?'S':'-', (fno.fattrib&AM_ARC)?'A':'-'); break; caseFR_NO_FILE: printf("Itisnotexist.\n"); break; default: printf("Anerroroccured.(%d)\n",fr); } path Pointer to the null-terminated string that specifies the object to get its information. fno Pointer to the blank FILINFO structure to store the information of the object. Set null pointer if it is not needed. FR_OK FR_DISK_ERR FR_INT_ERR FR_NOT_READY FR_NO_FILE FR_NO_PATH FR_INVALID_NAME FR_INVALID_DRIVE FR_NOT_ENABLED FR_NO_FILESYSTEM FR_TIMEOUT FR_NOT_ENOUGH_CORE Available when _FS_MINIMIZE == 0.
References DEFINE_NAMEBUF, find_volume, DIR::fs, FR_OK, INIT_BUF, follow_path, DIR::dir, get_fileinfo, FR_INVALID_NAME, FREE_BUF, LEAVE_FF.
Referenced by FOTA_UpdateSdcardFw.
FRESULT f_sync(FIL *fp)
The f_sync function flushes the cached information of a writing file.
The f_sync() function performs the same process as f_close() function but the file is left opened and can continue read/write/seek operations to the file. This is suitable for the applications that open files for a long time in write mode, such as data logger. Performing f_sync() function of periodic or immediataly after f_write() function can minimize the risk of data loss due to a sudden blackout or an unintentional media removal. However there is no sense in f_sync() function immediataly before f_close() function because it performs f_sync() function in it. In other words, the differnce between those functions is that the file object is invalidated or not. fp Pointer to the open file object to be flushed. FR_OK FR_DISK_ERR FR_INT_ERR FR_NOT_READY FR_INVALID_OBJECT FR_TIMEOUT Available when _FS_READONLY == 0.
References validate, FR_OK, FIL::flag, FA__WRITTEN, FA__DIRTY, disk_write, FIL::fs, FATFS::drv, FIL::buf, FIL::dsect, RES_OK, LEAVE_FF, FR_DISK_ERR, move_window, FIL::dir_sect, FIL::dir_ptr, DIR_Attr, AM_ARC, ST_DWORD, DIR_FileSize, FIL::fsize, st_clust, FIL::sclust, GET_FATTIME, DIR_WrtTime, ST_WORD, DIR_LstAccDate, FATFS::wflag, sync_fs.
Referenced by f_close.
FRESULT f_truncate(FIL *fp)
The f_truncate function truncates the file size.
The f_truncate() function truncates the file size to the current file read/write pointer. This function has no effect if the file read/write pointer is already pointing end of the file. fp Pointer to the open file object to be truncated. FR_OK FR_DISK_ERR FR_INT_ERR FR_NOT_READY FR_INVALID_OBJECT FR_TIMEOUT Available when _FS_READONLY == 0 and _FS_MINIMIZE == 0.
References validate, FR_OK, FIL::err, FIL::flag, FA_WRITE, FR_DENIED, FIL::fsize, FIL::fptr, FA__WRITTEN, remove_chain, FIL::fs, FIL::sclust, get_fat, FIL::clust, FR_DISK_ERR, FR_INT_ERR, FATFS::n_fatent, put_fat, FA__DIRTY, disk_write, FATFS::drv, FIL::buf, FIL::dsect, RES_OK, LEAVE_FF.
FRESULT f_unlink(const TCHAR *path)
The f_unlink function removes a file or sub-directory.
If condition of the object to be removed is applicable to the following terms, the function will be rejected. The file/sub-directory must not have read-only attribute (AM_RDO), or the function will be rejected with FR_DENIED.The sub-directory must be empty and must not be current directory, or the function will be rejected with FR_DENIED.The file/sub-directory must not be opened, or the FAT volume can be collapsed. It can be rejected with FR_LOCKED when file lock feature is enabled. path Pointer to the null-terminated string that specifies an object to be removed. FR_OK FR_DISK_ERR FR_INT_ERR FR_NOT_READY FR_NO_FILE FR_NO_PATH FR_INVALID_NAME FR_DENIED FR_EXIST FR_WRITE_PROTECTED FR_INVALID_DRIVE FR_NOT_ENABLED FR_NO_FILESYSTEM FR_TIMEOUT FR_LOCKED FR_NOT_ENOUGH_CORE Available when _FS_READONLY == 0 and _FS_MINIMIZE == 0.
References DEFINE_NAMEBUF, find_volume, DIR::fs, FR_OK, INIT_BUF, follow_path, _FS_RPATH, DIR::fn, NSFLAG, NS_DOT, FR_INVALID_NAME, DIR::dir, DIR_Attr, AM_RDO, FR_DENIED, ld_clust, AM_DIR, mem_cpy, DIR::sclust, dir_sdi, dir_read, FR_NO_FILE, dir_remove, remove_chain, sync_fs, FREE_BUF, LEAVE_FF.
Referenced by FOTA_ValidateSdcardFw.
FRESULT f_utime(const TCHAR *path, const FILINFO *fno)
The f_utime function changes the timestamp of a file or sub-directory.
The f_utime() function changes the timestamp of a file or sub-directory Example: FRESULTset_timestamp( char*obj,/*Pointertothefilename*/ intyear, intmonth, intmday, inthour, intmin, intsec ) { FILINFOfno; fno.fdate=(WORD)(((year-1980)*512U)|month*32U|mday); fno.ftime=(WORD)(hour*2048U|min*32U|sec/2U); returnf_utime(obj,&fno); } path Pointer to the null-terminated string that specifies an object to be changed. fno Pointer to the file information structure that has a timestamp to be set in member fdate and ftime. Do not care any other members. FR_OK FR_DISK_ERR FR_INT_ERR FR_NOT_READY FR_NO_FILE FR_NO_PATH FR_INVALID_NAME FR_WRITE_PROTECTED FR_INVALID_DRIVE FR_NOT_ENABLED FR_NO_FILESYSTEM FR_TIMEOUT FR_NOT_ENOUGH_CORE Available when _FS_READONLY == 0 and _FS_MINIMIZE == 0.
References DEFINE_NAMEBUF, find_volume, DIR::fs, FR_OK, INIT_BUF, follow_path, FREE_BUF, _FS_RPATH, DIR::fn, NSFLAG, NS_DOT, FR_INVALID_NAME, DIR::dir, ST_WORD, DIR_WrtTime, FILINFO::ftime, DIR_WrtDate, FILINFO::fdate, FATFS::wflag, sync_fs, LEAVE_FF.
FRESULT f_write(FIL *fp, const void *buff, UINT btw, UINT *bw)
The f_write writes data to a file.
The read/write pointer of the file object advances number of bytes written. After the function succeeded, *bw should be checked to detect the disk full. In case of *bw is less than btw, it means the volume got full during the write operation. The function can take a time when the volume is full or close to full. fp Pointer to the open file object. buff Pointer to the data to be written. btw Specifies number of bytes to write in range of UINT type. bw Pointer to the UINT variable to return the number of bytes written. The value is always valid after the function call regardless of the result. FR_OK FR_DISK_ERR FR_INT_ERR FR_NOT_READY FR_INVALID_OBJECT FR_TIMEOUT Available when _FS_READONLY == 0.
References validate, FR_OK, LEAVE_FF, FIL::fs, FIL::err, FIL::flag, FA_WRITE, FR_DENIED, FIL::fptr, SS, FATFS::csize, FIL::sclust, create_chain, FIL::clust, ABORT, FR_INT_ERR, FR_DISK_ERR, FATFS::winsect, FIL::dsect, sync_window, FA__DIRTY, disk_write, FATFS::drv, FIL::buf, RES_OK, clust2sect, mem_cpy, FATFS::win, FATFS::wflag, FIL::fsize, disk_read, move_window, FA__WRITTEN.
Referenced by putc_bfd, f_putc, f_puts, f_printf.
static FRESULT find_volume(FATFS **rfs, const TCHAR **path, BYTE wmode)
References get_ldnumber, FR_INVALID_DRIVE, FR_NOT_ENABLED, ENTER_FF, FATFS::fs_type, disk_status, FATFS::drv, STA_NOINIT, _FS_READONLY, STA_PROTECT, FR_WRITE_PROTECTED, FR_OK, LD2PD, disk_initialize, FR_NOT_READY, disk_ioctl, GET_SECTOR_SIZE, SS, RES_OK, _MIN_SS, _MAX_SS, FR_DISK_ERR, check_fs, LD2PT, FATFS::win, MBR_Table, SZ_PTE, LD_DWORD, FR_NO_FILESYSTEM, LD_WORD, BPB_BytsPerSec, BPB_FATSz16, BPB_FATSz32, FATFS::fsize, FATFS::n_fats, BPB_NumFATs, FATFS::csize, BPB_SecPerClus, FATFS::n_rootdir, BPB_RootEntCnt, SZ_DIRE, BPB_TotSec16, BPB_TotSec32, BPB_RsvdSecCnt, FS_FAT12, MIN_FAT16, FS_FAT16, MIN_FAT32, FS_FAT32, FATFS::n_fatent, FATFS::volbase, FATFS::fatbase, FATFS::database, FATFS::dirbase, BPB_RootClus, FATFS::last_clust, FATFS::free_clust, FATFS::fsi_flag, BPB_FSInfo, move_window, BS_55AA, FSI_LeadSig, FSI_StrucSig, FSI_Free_Count, FSI_Nxt_Free, FATFS::id, Fsid.
Referenced by f_mount, f_open, f_opendir, f_stat, f_getfree, f_unlink, f_mkdir, f_chmod, f_rename, f_utime.
static void fit_lfn(const WCHAR *lfnbuf, BYTE *dir, BYTE ord, BYTE sum)
References LDIR_Chksum, LDIR_Attr, AM_LFN, LDIR_Type, ST_WORD, LDIR_FstClusLO, LLEF, LDIR_Ord.
Referenced by dir_register.
static FRESULT follow_path(DIR *dp, const TCHAR *path)
References DIR::sclust, DIR::fs, dir_sdi, DIR::dir, create_name, FR_OK, dir_find, DIR::fn, NSFLAG, FR_NO_FILE, _FS_RPATH, NS_DOT, NS_LAST, FR_NO_PATH, DIR_Attr, AM_DIR, ld_clust.
Referenced by f_open, f_opendir, f_stat, f_unlink, f_mkdir, f_chmod, f_rename, f_utime.
static void gen_numname(BYTE *dst, const BYTE *src, const WCHAR *lfn, UINT seq)
References mem_cpy, IsDBCS1.
Referenced by dir_register.
DWORD get_fat(FATFS *fs, DWORD clst)
References FATFS::n_fatent, FATFS::fs_type, FS_FAT12, move_window, FATFS::fatbase, SS, FR_OK, FATFS::win, FS_FAT16, LD_WORD, FS_FAT32, LD_DWORD.
Referenced by remove_chain, create_chain, dir_sdi, dir_next, f_read, f_lseek, f_getfree, f_truncate.
static void get_fileinfo(DIR *dp, FILINFO *fno)
References FILINFO::fname, DIR::sect, DIR::dir, RDDEM, DDEM, IsUpper, DIR_NTres, NS_EXT, NS_BODY, IsDBCS1, IsDBCS2, ff_convert, FILINFO::fattrib, DIR_Attr, FILINFO::fsize, LD_DWORD, DIR_FileSize, FILINFO::fdate, LD_WORD, DIR_WrtDate, FILINFO::ftime, DIR_WrtTime, FILINFO::lfname, FILINFO::lfsize, DIR::lfn_idx, DIR::lfn, _DF1S.
Referenced by f_readdir, f_stat.
static int get_ldnumber(const TCHAR **path)
References _VOLUME_STRS, _USE_LFN, _VOLUMES, IsLower.
Referenced by find_volume, f_mount, f_rename, f_mkfs.
static DWORD ld_clust(FATFS *fs, const BYTE *dir)
References LD_WORD, DIR_FstClusLO, FATFS::fs_type, FS_FAT32, DIR_FstClusHI.
Referenced by follow_path, f_open, f_opendir, f_unlink, f_rename.
static int lock_fs(FATFS *fs)
References ff_req_grant, FATFS::sobj.
static int mem_cmp(const void *dst, const void *src, UINT cnt)
Referenced by dir_find.
static void mem_cpy(void *dst, const void *src, UINT cnt)
Referenced by gen_numname, dir_register, f_read, f_write, f_unlink, f_mkdir, f_rename, f_mkfs.
static void mem_set(void *dst, int val, UINT cnt)
Referenced by sync_fs, dir_next, dir_register, dir_remove, create_name, f_mkdir, f_mkfs.
static FRESULT move_window(FATFS *fs, DWORD sector)
References FR_OK, FATFS::winsect, sync_window, disk_read, FATFS::drv, FATFS::win, RES_OK, FR_DISK_ERR.
Referenced by get_fat, put_fat, dir_alloc, dir_find, dir_read, dir_register, dir_remove, check_fs, find_volume, f_open, f_read, f_write, f_sync, f_getfree, f_rename.
static int pick_lfn(WCHAR *lfnbuf, BYTE *dir)
References LD_WORD, LDIR_FstClusLO, LDIR_Ord, _MAX_LFN, LLEF.
Referenced by dir_read.
FRESULT put_fat(FATFS *fs, DWORD clst, DWORD val)
References FATFS::n_fatent, FR_INT_ERR, FATFS::fs_type, FS_FAT12, move_window, FATFS::fatbase, SS, FR_OK, FATFS::win, FATFS::wflag, FS_FAT16, ST_WORD, FS_FAT32, LD_DWORD, ST_DWORD.
Referenced by remove_chain, create_chain, f_truncate.
static void putc_bfd(putbuff *pb, TCHAR c)
References _USE_STRFUNC, putbuff::idx, putbuff::buf, ff_convert, f_write, putbuff::fp, putbuff::nchr.
Referenced by f_putc, f_puts, f_printf.
static FRESULT remove_chain(FATFS *fs, DWORD clst)
References FATFS::n_fatent, FR_INT_ERR, FR_OK, get_fat, FR_DISK_ERR, put_fat, FATFS::free_clust, FATFS::fsi_flag, clust2sect, FATFS::csize, disk_ioctl, FATFS::drv, CTRL_TRIM.
Referenced by f_open, f_truncate, f_unlink, f_mkdir.
static void st_clust(BYTE *dir, DWORD cl)
References ST_WORD, DIR_FstClusLO, DIR_FstClusHI.
Referenced by f_open, f_sync, f_mkdir, f_rename.
static BYTE sum_sfn(const BYTE *dir)
Referenced by dir_find, dir_read, dir_register.
static FRESULT sync_fs(FATFS *fs)
References sync_window, FR_OK, FATFS::fs_type, FS_FAT32, FATFS::fsi_flag, mem_set, FATFS::win, SS, ST_WORD, BS_55AA, ST_DWORD, FSI_LeadSig, FSI_StrucSig, FSI_Free_Count, FATFS::free_clust, FSI_Nxt_Free, FATFS::last_clust, FATFS::winsect, FATFS::volbase, disk_write, FATFS::drv, disk_ioctl, CTRL_SYNC, RES_OK, FR_DISK_ERR.
Referenced by f_sync, f_unlink, f_mkdir, f_chmod, f_rename, f_utime.
static FRESULT sync_window(FATFS *fs)
References FR_OK, FATFS::wflag, FATFS::winsect, disk_write, FATFS::drv, FATFS::win, RES_OK, FR_DISK_ERR, FATFS::fatbase, FATFS::fsize, FATFS::n_fats.
Referenced by move_window, sync_fs, dir_next, f_write, f_mkdir.
static void unlock_fs(FATFS *fs, FRESULT res)
References FR_NOT_ENABLED, FR_INVALID_DRIVE, FR_INVALID_OBJECT, FR_TIMEOUT, ff_rel_grant, FATFS::sobj.
Referenced by f_close, f_closedir.
static FRESULT validate(void *obj)
References FIL::fs, FATFS::fs_type, FATFS::id, FIL::id, disk_status, FATFS::drv, STA_NOINIT, FR_INVALID_OBJECT, ENTER_FF, FR_OK.
Referenced by f_read, f_write, f_sync, f_close, f_lseek, f_closedir, f_readdir, f_truncate.