EXTBUS_TEMP_IO_BOARD
CmdProcessor_T* AppCmdProcessor
Handle to store the main Command processor handle to be used by run-time event driven threads
Referenced by AppControllerSetup.
xTaskHandle AppControllerHandle
OS thread handle for Application controller to be used by run-time blocking threads
Referenced by AppControllerEnable.
ExternalSensor_Setup_T ExternalSensorSetup
External Sensor setup parameters
Sensor_Setup_T SensorSetup
Sensor setup parameters
void AppController_Init(void *cmdProcessorHandle, uint32_t param2)
Gives control to the Application controller.
This is a template function where the user can write his custom application.Refer interface header for description
References BCDS_UNUSED, RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, CmdProcessor_Enqueue, AppControllerSetup, Retcode_RaiseError, assert.
static void AppControllerEnable(void *param1, uint32_t param2)
To enable the necessary modules for the application.
Sensor param1 Unused param2 Unused
References BCDS_UNUSED, Sensor_Enable, RETCODE_OK, ExternalSensor_Enable, AppControllerFire, TASK_STACK_SIZE_APP_CONTROLLER, NULL, TASK_PRIO_APP_CONTROLLER, AppControllerHandle, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_OUT_OF_RESOURCES, Retcode_RaiseError, assert, Utils_PrintResetCause.
Referenced by AppControllerSetup.
static void AppControllerFire(void *pvParameters)
This function controls the application flow.
Triggers Sensor data samplingRead the sampled Sensor data pvParameters Unused Internal Temperature sensor, external temperature sensor and external resistance is enabled. The external temperature sensor is connected to the XDK which gives the temperature value based on the resistance provided. The internal temperature sensor uses BME280 sensor and gives the temperature value
References BCDS_UNUSED, RETCODE_OK, Sensor_GetData, ExternalSensor_GetData, Sensor_Setup_S::Enable, Sensor_Enable_S::Temp, Sensor_Value_S::Temp, ExternalSensor_Setup_S::Enable, ExternalSensor_Enable_S::MaxTemp, ExternalSensor_Enable_S::MaxResistance, ExternalSensor_Value_S::XMaxT, ExternalSensor_Value_S::XMaxR, Retcode_RaiseError, vTaskDelay, APP_CONTROLLER_SAMPLING_DELAY.
Referenced by AppControllerEnable.
static void AppControllerSetup(void *param1, uint32_t param2)
To setup the necessary modules for the application.
Sensor param1 Unused param2 Unused
References BCDS_UNUSED, Sensor_Setup_S::CmdProcessorHandle, AppCmdProcessor, Sensor_Setup, RETCODE_OK, ExternalSensor_Setup_S::CmdProcessorHandle, ExternalSensor_Setup, CmdProcessor_Enqueue, AppControllerEnable, NULL, Retcode_RaiseError, assert.
Referenced by AppController_Init.
BCDS_MODULE_ID