SYSTEMSTARTUP
SystemStartup_ErrorCode_E
void assertIndicationMapping(const unsigned long line, const unsigned char *const file)
This API is called when function enters an assert.
line : line number where asserted file : file name which is asserted
References RETCODE_OK, BSP_LED_COMMAND_ON, vTaskSuspendAll.
Referenced by systemStartup.
void DefaultErrorHandlingFunc(Retcode_T error, bool isfromIsr)
System Error Handling routine.
Error Error Information from Basic isfromIsr :currently unused, can be used for future implementation.
References Retcode_GetPackage, Retcode_GetCode, Retcode_GetModuleId, Retcode_GetSeverity, RETCODE_SEVERITY_FATAL, RETCODE_SEVERITY_ERROR, RETCODE_SEVERITY_WARNING, RETCODE_SEVERITY_INFO.
Referenced by main.
Retcode_T systemStartup(void)
The main function initializes the hardware and starts the RTOS scheduler.
returns RETCODE_OK for successful intialisation.
References RETCODE_OK, NULL, BSP_Board_OSTickInitialize, SystickPreCallback, Assert_Initialize, assertIndicationMapping, BSP_Board_Initialize, UsbResetUtility_Init, NVM_Initialize, NVM_ReadUInt8, NVM_ITEM_CONTENT_INDEX, BLE_MAC_USERPAGE_FLAG_BIT, WIFI_MAC_USERPAGE_FLAG_BIT, NVM_WriteUInt8, NVM_Flush, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NVM_WIFI_AND_BLE_BIT_SET_FAILED.
Referenced by main.
TIMER_AUTORELOAD_OFF
Auto reload of timer is disabled
TIMERBLOCKTIME
block time of timer is defined by this macro