EXTENSIONPORTSPI
ExtensionPortSpi_BitOrder_E
ExtensionPortSpi_ClockMode_E
typedef enum ExtensionPortSpi_BitOrder_E ExtensionPortSpi_BitOrder_T
Typedef to represent the bit order for the data sent via the extension port SPI.
typedef enum ExtensionPortSpi_ClockMode_E ExtensionPortSpi_ClockMode_T
Typedef to represent the clock mode of the extension port SPI.
typedef struct ExtensionPortSpi_Config_S ExtensionPortSpi_Config_T
Structure to represent the configuration of the extension port SPI.
Retcode_T ExtensionPortSpi_DeInitialize(void)
This API Deinitialize the SPI interface driver.
RETCODE_OK in case of Spi De-Initialization Success. RETCODE_UNINITIALIZED in case of spi not initialized. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Refer interface header for description
References RETCODE_OK, NULL, SpiHandle, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, SpiCompleteSync, vSemaphoreDelete.
Referenced by Sigfox_SendToSleep, ExtensionSpiExample_DeInitialize.
Retcode_T ExtensionPortSpi_Initialize(ExtensionPortSpi_Config_T *config)
This API initialize the SPI Interface Driver.
RETCODE_OK in case of Spi Initialization Success. RETCODE_OUT_OF_RESOURCES in case of Failed to create Semaphore to handle the interrupt or Failed to Set the Spi Configurations or While enabling the SPI. RETCODE_NULL_POINTER in case of SPI Handle NULL. In case of other failures refer #BSP_ExtensionPort_Connect API's. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Refer interface header for description
References RETCODE_OK, ExtensionPortSpi_Config_S::BaudRate, NULL, ExtensionPortSpi_Config_S::ClockMode, ExtensionPortSpi_Config_S::BitOrder, SpiCompleteSync, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_OUT_OF_RESOURCES, SpiHandle, AppCallback, RETCODE_NULL_POINTER.
Referenced by Sigfox_Setup, ExtensionSpiExample_Initialize.
Retcode_T ExtensionPortSpi_Read(uint8_t *readVal, uint32_t readLength, uint32_t timeout)
This API will Read the value from the SPI interface driver.
readVal Buffer to hold the data received over SPI readLength No of bytes to be read over the SPI bus RETCODE_OK in case of Spi Read Register Success. RETCODE_TIMEOUT in case of interrupt not triggered. RETCODE_NULL_POINTER in case of SPI Handle NULL. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Refer interface header for description
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_WARNING, RETCODE_INVALID_PARAM, SpiCompleteSync, RETCODE_UNINITIALIZED, SpiHandle, xSemaphoreTake, RETCODE_TIMEOUT.
Referenced by HandleSPIDataTransfer, ExtensionSpiExample_ReadRegister.
Retcode_T ExtensionPortSpi_Write(uint8_t *writeVal, uint32_t writeLength, uint32_t timeout)
This API will Write the Value to the SPI interface driver.
writeVal Buffer to hold the data to be transmitted over SPI writeLength No of bytes to be transmitted over the SPI bus RETCODE_OK in case of Spi Write value on passing Register Success. RETCODE_TIMEOUT in case of interrupt not triggered. RETCODE_NULL_POINTER in case of SPI Handle NULL. The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code). Refer interface header for description
References RETCODE_OK, RETCODE, RETCODE_SEVERITY_WARNING, RETCODE_INVALID_PARAM, SpiCompleteSync, NULL, RETCODE_UNINITIALIZED, SpiHandle, xSemaphoreTake, RETCODE_TIMEOUT.
Referenced by HandleSPIDataTransfer, ExtensionSpiExample_ReadRegister, ExtensionSpiExample_WriteRegister.