XDK_Extension_Port_Spi
Retcode_T ExtensionSpiExample_DeInitialize(void)
This API Deinitialize the SPI interface driver Once this called, from there-on user needs to call ExtensionSpiExample_Initialize for using the SPI communication again.
Refer interface header for description
References RETCODE_OK, ExtensionPortSpi_DeInitialize, SpiCSPinDeInit.
Retcode_T ExtensionSpiExample_Initialize(CmdProcessor_T *handle)
This API initialize the SPI Interface Driver.
Refer interface header for description
References BCDS_UNUSED, RETCODE_OK, ExtensionPortSpi_Config_S::BaudRate, SPI_DATA_TRANSFER_BAUDRATE, EXTENSION_PORT_SPI_BIT_ORDER_MSB_FIRST, EXTENSION_PORT_SPI_CLOCK_MODE_0, SpiCSPinInit, ExtensionPortSpi_Initialize.
Referenced by AppControllerSetup.
Retcode_T ExtensionSpiExample_ReadRegister(uint8_t regAddr, uint8_t *readVal, uint8_t readLength)
This API Read the value from the SPI interface driver.
Refer interface header for description
References RETCODE_OK, SpiSetCSLow, ExtensionPortSpi_Write, SPI_DATA_TRANSFER_TIMEOUT_MILLISEC, ExtensionPortSpi_Read, SpiSetCSHigh.
Referenced by ExtensionSpiExample_ValidateChip.
Retcode_T ExtensionSpiExample_ValidateChip(void)
This API is used to demonstrate read and write on the extension port SPI interface.
Refer interface header for description
References RETCODE_OK, ExtensionSpiExample_ReadRegister, EXT_PORT_SPI_REG2_ADDR, EXT_PORT_SPI_READ_BIT, EXT_PORT_SPI_REG2_ADDR_VAL, EXT_PORT_SPI_REG1_ADDR_VAL, ExtensionSpiExample_WriteRegister, EXT_PORT_SPI_REG1_ADDR, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_FAILURE.
Referenced by AppControllerFire.
Retcode_T ExtensionSpiExample_WriteRegister(uint8_t regAddr, uint8_t *writeVal, uint8_t writeLength)
This API Write the Value to the SPI interface driver.
Refer interface header for description
References RETCODE_OK, SpiSetCSLow, ExtensionPortSpi_Write, SPI_DATA_TRANSFER_TIMEOUT_MILLISEC, SpiSetCSHigh.
Referenced by ExtensionSpiExample_ValidateChip.
static Retcode_T SpiCSPinDeInit(void)
function to De-Initialize the Extension Port SPI CS pin.
References RETCODE_OK, EXT_PORT_SPI_CS_PIN_ID.
Referenced by ExtensionSpiExample_DeInitialize.
static Retcode_T SpiCSPinInit(void)
function to Initialize the Extension Port SPI CS pin with the configurations.
References RETCODE_OK, EXT_PORT_SPI_CS_PIN_ID, NULL.
Referenced by ExtensionSpiExample_Initialize.
static Retcode_T SpiSetCSHigh(void)
function to Put the Extension board SPI CS pin High
References EXT_PORT_SPI_CS_PIN_ID.
Referenced by ExtensionSpiExample_ReadRegister, ExtensionSpiExample_WriteRegister.
static Retcode_T SpiSetCSLow(void)
function to Put the Extension board SPI CS pin Low
References EXT_PORT_SPI_CS_PIN_ID.
Referenced by ExtensionSpiExample_ReadRegister, ExtensionSpiExample_WriteRegister.
BCDS_MODULE_ID
EXT_PORT_SPI_CS_PIN_ID
Referenced by SpiSetCSLow, SpiSetCSHigh, SpiCSPinInit, SpiCSPinDeInit.
EXT_PORT_SPI_READ_BIT
Referenced by ExtensionSpiExample_ValidateChip.
EXT_PORT_SPI_REG1_ADDR
Referenced by ExtensionSpiExample_ValidateChip.
EXT_PORT_SPI_REG1_ADDR_VAL
Referenced by ExtensionSpiExample_ValidateChip.
EXT_PORT_SPI_REG2_ADDR
Referenced by ExtensionSpiExample_ValidateChip.
EXT_PORT_SPI_REG2_ADDR_VAL
Referenced by ExtensionSpiExample_ValidateChip.
EXT_PORT_SPI_SLAVE_ADDR
SPI_DATA_TRANSFER_BAUDRATE
Macro used to define the SPI Baudrate
Referenced by ExtensionSpiExample_Initialize.
SPI_DATA_TRANSFER_TIMEOUT_MILLISEC
Macro used to define the data transfer timeout
Referenced by ExtensionSpiExample_ReadRegister, ExtensionSpiExample_WriteRegister.