WLAN_NETWORK_MANAGEMENT
CmdProcessor_T* AppCmdProcessor
Handle to store the main Command processor handle to be reused by ServalPAL thread
xTaskHandle AppControllerHandle
OS thread handle for Application controller
Referenced by AppControllerEnable.
uint8_t dhcpFlag_mdu8
callback flag for DHCP; let user know that the DHCP IP was acquired
Referenced by myDhcpIpCallbackFunc, SetAndGetIp.
SemaphoreHandle_t NetworkConfigSemaphore
Referenced by myDhcpIpCallbackFunc, SetAndGetIp, AppControllerEnable.
SemaphoreHandle_t WlanEventSemaphore
Referenced by WlanConnectStatusCallback, SetAndGetIp, AppControllerEnable.
WLAN_Setup_T WLANSetupInfo
WLAN setup parameters
void AppController_Init(void *cmdProcessorHandle, uint32_t param2)
Gives control to the Application controller.
This is a template function where the user can write his custom application.Refer interface header for description
References BCDS_UNUSED, RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, CmdProcessor_Enqueue, AppControllerSetup, Retcode_RaiseError, assert.
static void AppControllerEnable(void *param1, uint32_t param2)
To enable the necessary modules for the application.
LEDWLAN param1 Unused param2 Unused
References BCDS_UNUSED, RETCODE_OK, LED_Enable, WlanNetworkConnect_Init, WlanConnectStatusCallback, NetworkConfigSemaphore, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_SEMAPHORE_ERROR, WlanEventSemaphore, vSemaphoreDelete, AppControllerFire, TASK_STACK_SIZE_APP_CONTROLLER, TASK_PRIO_APP_CONTROLLER, AppControllerHandle, RETCODE_OUT_OF_RESOURCES, Retcode_RaiseError, assert, Utils_PrintResetCause.
Referenced by AppControllerSetup.
static void AppControllerFire(void *pvParameters)
Responsible for controlling the Wlan network management control flow.
Scan for available networksSet IP, Connect, Get IP and Disconnect from network pvParameters Unused
References BCDS_UNUSED, ScanNetwork, SetAndGetIp.
Referenced by AppControllerEnable.
static void AppControllerSetup(void *param1, uint32_t param2)
To setup the necessary modules for the application.
LEDWLAN param1 Unused param2 Unused
References BCDS_UNUSED, RETCODE_OK, LED_Setup, WLAN_Setup, CmdProcessor_Enqueue, AppControllerEnable, NULL, Retcode_RaiseError, assert.
Referenced by AppController_Init.
void myDhcpIpCallbackFunc(WlanNetworkConfig_IpStatus_T returnStatus)
NCI DHCP Callback function. This function is called by the device when an IP was acquired using DHCP.
returnStatus Enumeration element containing the IP return status. none.
References WLANNWCNF_IPSTATUS_IPV4_AQRD, dhcpFlag_mdu8, WLANNWCNF_DHCP_FLG_ACQ, NULL, NetworkConfigSemaphore, xSemaphoreGive.
Referenced by SetAndGetIp.
static void ScanNetwork(void)
Local function for scanning networks. This function also calls the SetAndGetIp function in order to set/get IP settings and connect/disconnect from a network.
none. none.
References RETCODE_OK, SCAN_INTERVAL, LED_On, LED_INBUILT_RED, LED_INBUILT_ORANGE, LED_INBUILT_YELLOW, WlanNetworkConnect_ScanNetworks, ZERO, WLANNWCT_MAX_SCAN_INFO_BUF, WlanNetworkConnect_ScanList_S::ScanData, WlanNetworkConnect_ScanInfo_S::SsidLength, WlanNetworkConnect_ScanInfo_S::Ssid, static_assert, portTICK_RATE_MS, vTaskDelay, portTickType, DELAY_500_MSEC, RETCODE_NO_NW_AVAILABLE, Retcode_GetCode, LED_Off.
Referenced by AppControllerFire.
static void SetAndGetIp(void)
This function does the following :
disconnects from a network if connectedsets an IP (either static or DHCP),connects to a known networkget the IP settingdisconnects from WLAN network none. none.
References RETCODE_OK, myDhcpIpCallbackFunc, WLANNWCT_STATUS_CONNECTED, WlanNetworkConnect_GetStatus, WLANNWCNF_IPSTATUS_IPV4_AQRD, WlanNetworkConfig_GetIpStatus, WLANNWCT_IPSTATUS_DISCT_NAQRD, WlanNetworkConnect_GetIpStatus, WLANNWCT_IPSTATUS_DISCT_AQRD, xSemaphoreTake, WlanEventSemaphore, WlanNetworkConnect_Disconnect, WLANNETWORK_EVENT_TIMEOUT, WLANNWCT_STATUS_DISCONNECTED, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_WLAN_DISCONNECT_FAILED, RETCODE_SEMAPHORE_ERROR, dhcpFlag_mdu8, WLANNWCNF_DHCP_FLG_NOT_ACQ, NetworkConfigSemaphore, WlanNetworkConfig_SetIpDhcp, WlanNetworkConnect_PersonalWPA, WLAN_Setup_S::SSID, WLAN_Setup_S::Password, RETCODE_WLAN_CONNECT_FAILED, ZERO, WlanNetworkConfig_IpSettings_S::isDHCP, WLANNWCNF_DHCP_DISABLED, WlanNetworkConfig_IpSettings_S::ipV4, sl_Htonl, WLAN_Setup_S::IpAddr, WlanNetworkConfig_IpSettings_S::ipV4DnsServer, WLAN_Setup_S::DnsAddr, WlanNetworkConfig_IpSettings_S::ipV4Gateway, WLAN_Setup_S::GwAddr, WlanNetworkConfig_IpSettings_S::ipV4Mask, WLAN_Setup_S::Mask, WlanNetworkConfig_SetIpStatic, WlanNetworkConfig_Ipv4Byte, SL_POLICY_CONNECTION, SL_CONNECTION_POLICY, NULL, SL_RET_CODE_OK, static_assert, portTICK_RATE_MS, vTaskDelay, portTickType, DELAY_15_SEC, WlanNetworkConfig_GetIpSettings, WLANNWCNF_DHCP_FLG_ACQ.
Referenced by AppControllerFire.
static void WlanConnectStatusCallback(WlanNetworkConnect_Status_T status)
References BCDS_UNUSED, NULL, WlanEventSemaphore, xSemaphoreGive.
Referenced by AppControllerEnable.
BCDS_MODULE_ID
DELAY_15_SEC
Macro used for delay function for 15 seconds
Referenced by SetAndGetIp.
DELAY_500_MSEC
Macro used for delay function for 0,5 seconds
Referenced by ScanNetwork.
MINUS_ONE
Macro for defining -1
ONE
Macro for defining 1
THREE
Macro for defining 3
TWO
Macro for defining 2
WLANNETWORK_EVENT_TIMEOUT
Macro for wlan event timeout for simplelink
Referenced by SetAndGetIp.
ZERO
Macro for defining 0
Referenced by SetAndGetIp, ScanNetwork.