MAX31865
TemperatureSensorType_E
PT100 based temperature sensor
typedef enum TemperatureSensorType_E TemperatureSensorType_T
Retcode_T MAX31865_Connect(void)
The function to connect to the MAX31865 chip.
RETCODE_OK Connection to MAX31865 chip successful. In case of any error refer BSP_Max31865_Connect or BSP_Max31865_Enable error codes.
Referenced by HandleExternalHwHotPlug, AppControllerEnable.
Retcode_T MAX31865_Disconnect(void)
The function to disconnect from the MAX31865 chip.
RETCODE_OK Disconnection to MAX31865 chip successful.\ In case of any error refer BSP_Max31865_Disable or BSP_Max31865_Disconnect error codes.
Referenced by HandleExternalHwHotPlug.
Retcode_T MAX31865_ReadResistance(float *resistance)
The function to read the Resistance Value.
resistance pointer to variable to hold the resistance in Ohms RETCODE_OK Reading the Resistance value successfully. RETCODE_NULL_POINTER NULL Pointer. RETCODE_FAILURE Reading the Resistance data failed. In case of any error refer #SPISensorTransceiver_Transfer error codes.
Retcode_T MAX31865_ReadTemperature(float *temperature)
The function to read the external temperature sensor data.
temperature pointer to variable to hold the temperature data in millidegree Celcius RETCODE_OK Reading the external temperature sensor data successful. RETCODE_NULL_POINTER Invalid sensor data. RETCODE_FAILURE Reading the external temperature sensor data failed. In case of any error refer MAX31865_ReadResistance error codes. MAX31865_ReadTemperature uses Callendar Van Dusen model for temperature calculation. For PT1000/PT100 the errors for different range of resistance is mentioned below Ambient Temperature Range (in °C) Temperature Error in (°C) -40 to 60 +/- 0.03 70 to 170 +/-0.08 180 to 300 +/-0.2 310 to 530 +/-0.4 540 to 700 +/-0.8 to +/-0.9 710 to 800 +/- 2
Retcode_T MAX31865_SetSensorType(TemperatureSensorType_T SensorType)
The function to Set the Sensor type of MAX31865 is either PT100 or PT1000.
SensorType variable as a type TemperatureSensorType_T to pass which needs to be set either PT100 or PT1000 Sensor RETCODE_OK Successfully received the Sensor type is either PT100 or PT1000. RETCODE_FAILURE Failed to get the the external temperature sensor type failed.