LoRa
LoRa_Event_E
LoRa_JoinType_E
typedef enum LoRa_Event_E LoRa_Event_T
LORA events for the supported drivers.
typedef void(* LoRa_EventNotificationCB_T)(LoRa_Event_T event))(LoRa_Event_T event)
Typedef of the LORA event notification callback.
event run-time event of the LORA stack
typedef enum LoRa_JoinType_E LoRa_JoinType_T
Enumeration representing supported join procedures as in LoRaWAN specification V1.0.1
typedef struct LoRa_Setup_S LoRa_Setup_T
Typedef to represent the WLAN setup feature.
uint64_t AppEUI
AppEUI is unique to the Application Server and each Application Server will have its own AppEUI
uint8_t* AppKey
AppKey is the data encryption key used to "encode" the messages between the end nodes and the Application Server
char* CodingRate
Coding rate used for LORA communication
uint64_t* DevEUI
Unique ID of the end device. if it is NULL then Hardware EUI will be used
LoRa_EventNotificationCB_T EventCallback
LORA event callback
uint32_t Freq
Frequency band used for the LORA
LoRa_JoinType_T JoinType
LORA Join Type
uint32_t RxFreq
Frequency used for the Receive window
Retcode_T LoRa_Close(void)
This will close the LoRa medium.
RETCODE_OK on success, or an error code otherwise.
Retcode_T LoRa_Disable(void)
This will disable the LoRa medium.
RETCODE_OK on success, or an error code otherwise.
Retcode_T LoRa_Enable(void)
This will enable the LORA(by calling this the Rxwindow2 frequency,DevEUI,appEUI,appKey, Coding rate will be set and saved)
RETCODE_OK on success, or an error code otherwise.
Referenced by AppControllerEnable.
Retcode_T LoRa_GetADR(bool *adr)
Returns the status of the Adaptive data Rate.
adr RETCODE_OK in case of success error code otherwise.
Retcode_T LoRa_GetHwEUI(uint64_t *hwDevEUI)
This will read the hardware dev EUI of the LoRa medium.
hwDevEUI place holder for Unique Identifier of the LoRa module RETCODE_OK on success, or an error code otherwise.
Referenced by AppControllerFire, AppControllerEnable.
Retcode_T LoRa_Join(void)
performs a join request if the device has not joined a network yet
RETCODE_OK in case of success error code otherwise.
Referenced by AppControllerFire.
Retcode_T LoRa_SendConfirmed(uint8_t LoRaPort, uint8_t *dataBuffer, uint32_t dataBufferSize)
Sends confirmed data over LoRa.
LoRaPort The LoraWan Port that will be used for sending dataBuffer Pointer to the data frame that will be sent dataBufferSize Length of the frame to send RETCODE_OK in case of success error code otherwise
Retcode_T LoRa_SendUnconfirmed(uint8_t LoRaPort, uint8_t *dataBuffer, uint32_t dataBufferSize)
Sends unconfirmed data frame over LoRa.
LoRaPort The LoraWan Port that will be used for sending dataBuffer Pointer to the data frame that will be sent dataBufferSize Length of the frame to send RETCODE_OK in case of success error code otherwise. This function returns if an ACK has been received from the Network Server or if an error or a timeout occurred
Referenced by AppControllerFire.
Retcode_T LoRa_SetADR(bool enable)
Sets the Adaptive Data Rate option to ON/OFF.
adr set to true if ADR is to be enabled, set to false otherwise. RETCODE_OK in case of success error code otherwise.
Retcode_T LoRa_SetDataRate(uint8_t dataRate)
Sets the Data Rate used for the transmission.
dataRate to be used according to LoRaWAN spec RETCODE_OK in case of success error code otherwise.
Referenced by AppControllerFire.
Retcode_T LoRa_Setup(LoRa_Setup_T *setup)
This will setup the LORA.
setup Pointer to the LORA setup feature RETCODE_OK on success, or an error code otherwise. This must be the first API to be called if LORA feature is to be used.Do not call this API more than once.
Referenced by AppControllerSetup.