TIMESTAMP
Retcode_T TimeStamp_SecsToTm(int64_t timeInSeconds, struct tm *tm)
This converts time from seconds to struct tm format.
timeInSeconds time in seconds tm time in tm format RETCODE_OK on success, or an error code otherwise. Refer interface header for description
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, TIME_OVERFLOW_INT_MAX_MULTIPLIER, RETCODE_INVALID_PARAM, TIME_OFFSET, SECS_TO_DAYS_FACTOR, NO_OF_DAYS_PER_400_Y, NO_OF_DAYS_PER_100_Y, NO_OF_DAYS_PER_4_Y.
Referenced by AppControllerFireTask, AppControllerFire.
Retcode_T TimeStamp_TmToIso8601(struct tm *tmPtr, char *iso8601Format, uint8_t bufferSize)
This converts time from struct tm format to ISO 8601 format.
tmPtr time in tm format in/out] iso8601Format time in ISO 8601 format. User must provide memory for this. bufferSize size of the iso8601Format buffer RETCODE_OK on success, or an error code otherwise. Refer interface header for description
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, tm_to_realtime, RETCODE_INVALID_PARAM.
Referenced by AppControllerFire.