BLE
BLE_Service_E
SensorService_Type_E
accelerometer sensor service
SensorServices_EnvironmentalType_E
pressure sensor
SensorServices_HighDataRateType_E
high priority array
SensorServices_MagnetometerType_E
X axis
SensorServices_SensorAxisType_E
X axis
SensorServices_SensorControlNode_E
start sampling
typedef void(* BLE_DataRxCB_T)(uint8_t *rxBuffer, uint8_t rxDataLength, void *param))(uint8_t *rxBuffer, uint8_t rxDataLength, void *param)
Typedef to notify the application about any incoming data.
rxBuffer pointer to the received data buffer rxDataLength Length of the received data param unused if setup->Service is not BLE_XDK_SENSOR_SERVICES. Otherwise, of type SensorServices_Info_T pointer. Do not perform any heavy processing within this function and return ASAP.
typedef struct BLE_DeviceCharacteristicsValue_S BLE_DeviceCharacteristicsValue_T
Typedef to represent the BLE device characteristics value.
typedef enum BLE_Service_E BLE_Service_T
Typedef to represent the BLE service supported.
typedef struct BLE_Setup_S BLE_Setup_T
Typedef to represent the BLE setup feature.
typedef enum SensorService_Type_E SensorService_Type_T
Typedef to represent the sensor service type.
typedef enum SensorServices_EnvironmentalType_E SensorServices_EnvironmentalType_T
Typedef to represent the environmental service characteristic.
typedef enum SensorServices_HighDataRateType_E SensorServices_HighDataRateType_T
Typedef to represent the high data rate service characteristic.
typedef struct SensorServices_Info_S SensorServices_Info_T
Typedef to represent the node sensor service information.
typedef enum SensorServices_MagnetometerType_E SensorServices_MagnetometerType_T
typedef to represent the magnetometer service characteristic
typedef enum SensorServices_SensorAxisType_E SensorServices_SensorAxisType_T
Typedef to represent the sensor axis type for accelerometer and gyro services.
typedef enum SensorServices_SensorControlNode_E SensorServices_SensorControlNode_T
Typedef to control the node.
Typedef to control the node.
Retcode_T BLE_Enable(void)
This will enable the BLE.
RETCODE_OK on success, or an error code otherwise. BLE_Setup must have been successful prior.Do not call this API more than once.
Referenced by AppControllerEnable.
bool BLE_IsConnected(void)
This will tell if any peer is connected via BLE.
Boolean representing if a peer is connected or not.
Referenced by AppControllerFire.
Retcode_T BLE_SendData(uint8_t *dataToSend, uint8_t dataToSendLen, void *param, uint32_t timeout)
This will send the data via BLE.
dataToSend The payload to be sent dataToSendLen The length of the payload to be sent param unused if setup->Service is not BLE_XDK_SENSOR_SERVICES. Otherwise, type casted to SensorServices_Info_T pointer. timeout Timeout for the payload to be sent RETCODE_OK on success, or an error code otherwise. RETCODE_BLE_NOT_CONNECTED if there is no peer connected. BLE_Setup must have been successful prior.Do not call this API more than once.This is a blocking call guarded with a mutex of wait time of 1 second.This supports only BLE_BCDS_BIDIRECTIONAL_SERVICE and BLE_XDK_SENSOR_SERVICES.
Referenced by AppControllerBleStartOrEndMsgSend, AppControllerFire, SampleAndNotifyHighPriorityData.
Retcode_T BLE_Setup(BLE_Setup_T *setup)
This will setup the BLE.
setup Pointer to the BLE setup feature RETCODE_OK on success, or an error code otherwise. This must be the first API to be called if BLE feature is to be used.Do not call this API more than once.
Referenced by AppControllerSetup.