BUTTON
ButtonEvent_E
typedef struct Button_Setup_S Button_Setup_T
Typedef to represent the Button setup feature.
typedef enum ButtonEvent_E ButtonEvent_T
typedef void(* ButtonEventCallback_T)(ButtonEvent_T buttonEvent))(ButtonEvent_T buttonEvent)
Retcode_T Button_Enable(void)
This will enable the Button.
RETCODE_OK on success, or an error code otherwise.
Referenced by AppControllerFireTask, AppControllerEnable.
Retcode_T Button_Setup(Button_Setup_T *setup)
This will setup the Button.
setup Pointer to the Button setup feature RETCODE_OK on success, or an error code otherwise.
Referenced by AppControllerSetup.