XDK_Extension_Port_I2c
I2cTranceiverHandle_T I2CTranceiverInstance
Referenced by I2cMcuCallback, ExtensionI2cExample_Initialize, ExtensionI2cExample_Read, ExtensionI2cExample_Write, ExtensionI2cExample_DeInitialize.
Retcode_T ExtensionI2cExample_DeInitialize(void)
This API is used to deinitialize the I2C interface. Once this called, from there-on user needs to call ExtensionI2cExample_Initialize for using the I2C communication again.
Refer interface header for description
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, I2CTranceiverInstance.
Retcode_T ExtensionI2cExample_Initialize(CmdProcessor_T *handle)
This API is used to prepare the I2C with the user configuration data.
Refer interface header for description
References BCDS_UNUSED, RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, I2cMcuCallback, I2CTranceiverInstance.
Referenced by AppControllerSetup.
Retcode_T ExtensionI2cExample_Read(uint8_t slaveAddr, uint8_t regAddr, uint8_t *readVal, uint8_t readLength)
This API is used to read the data received over the I2C extension port interface.
Refer interface header for description
References I2CTranceiverInstance.
Referenced by ExtensionI2cExample_ValidateChip.
Retcode_T ExtensionI2cExample_ValidateChip(void)
This API is used to demonstrate read and write on the extension port I2C interface.
Refer interface header for description
References RETCODE_OK, EXT_PORT_I2C_REG1_VAL, ExtensionI2cExample_Read, EXT_PORT_I2C_SLAVE_ADDR, EXT_PORT_I2C_REG2_ADDR, EXT_PORT_I2C_REG2_VAL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_UNEXPECTED_BEHAVIOR, ExtensionI2cExample_Write, EXT_PORT_I2C_REG1_ADDR.
Referenced by AppControllerFire.
Retcode_T ExtensionI2cExample_Write(uint8_t slaveAddr, uint8_t regAddr, uint8_t *writeVal, uint8_t writeLength)
This API is used to write the data received over the I2C extension port interface.
Refer interface header for description
References I2CTranceiverInstance.
Referenced by ExtensionI2cExample_ValidateChip.
static void I2cMcuCallback(I2C_T i2c, struct MCU_I2C_Event_S event)
References I2CTranceiverInstance, Retcode_RaiseErrorFromIsr, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM.
Referenced by ExtensionI2cExample_Initialize.
BCDS_MODULE_ID
EXT_PORT_I2C_REG1_ADDR
Referenced by ExtensionI2cExample_ValidateChip.
EXT_PORT_I2C_REG1_VAL
Referenced by ExtensionI2cExample_ValidateChip.
EXT_PORT_I2C_REG2_ADDR
Referenced by ExtensionI2cExample_ValidateChip.
EXT_PORT_I2C_REG2_VAL
Referenced by ExtensionI2cExample_ValidateChip.
EXT_PORT_I2C_SLAVE_ADDR
Referenced by ExtensionI2cExample_ValidateChip.