SEND_DATA_OVER_MQTT
CmdProcessor_T* AppCmdProcessor
Handle to store the main Command processor handle to be used by run-time event driven threads
Referenced by AppControllerSetup.
xTaskHandle AppControllerHandle
OS thread handle for Application controller to be used by run-time blocking threads
Referenced by AppControllerEnable.
uint32_t AppIncomingMsgCount
Incoming message count
Referenced by AppMQTTSubscribeCB.
char AppIncomingMsgPayloadBuffer[APP_MQTT_DATA_BUFFER_SIZE][APP_MQTT_DATA_BUFFER_SIZE]
Incoming message payload buffer
Referenced by AppMQTTSubscribeCB.
char AppIncomingMsgTopicBuffer[APP_MQTT_DATA_BUFFER_SIZE][APP_MQTT_DATA_BUFFER_SIZE]
Incoming message topic buffer
Referenced by AppMQTTSubscribeCB.
MQTT_Connect_T MqttConnectInfo
MQTT connect parameters
MQTT_Publish_T MqttPublishInfo
MQTT publish parameters
MQTT_Setup_T MqttSetupInfo
MQTT setup parameters
MQTT_Subscribe_T MqttSubscribeInfo
MQTT subscribe parameters
Sensor_Setup_T SensorSetup
Sensor setup parameters
WLAN_Setup_T WLANSetupInfo
WLAN setup parameters
void AppController_Init(void *cmdProcessorHandle, uint32_t param2)
Gives control to the Application controller.
This is a template function where the user can write his custom application.Refer interface header for description
References BCDS_UNUSED, RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, CmdProcessor_Enqueue, AppControllerSetup, Retcode_RaiseError, assert.
static void AppControllerEnable(void *param1, uint32_t param2)
To enable the necessary modules for the application.
WLANServalPALSNTP (if secure communication)MQTTSensor param1 Unused param2 Unused
References BCDS_UNUSED, WLAN_Enable, RETCODE_OK, ServalPAL_Enable, SNTP_Enable, MQTT_Enable, Sensor_Enable, AppControllerFire, TASK_STACK_SIZE_APP_CONTROLLER, NULL, TASK_PRIO_APP_CONTROLLER, AppControllerHandle, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_OUT_OF_RESOURCES, Retcode_RaiseError, assert, Utils_PrintResetCause.
Referenced by AppControllerSetup.
static void AppControllerFire(void *pvParameters)
Responsible for controlling the send data over MQTT application control flow.
Synchronize SNTP time stamp for the system if MQTT communication is secureConnect to MQTT brokerSubscribe to MQTT topicRead environmental sensor dataPublish data periodically for a MQTT topic pvParameters Unused
References BCDS_UNUSED, RETCODE_OK, APP_MQTT_DATA_BUFFER_SIZE, SNTP_GetTimeFromServer, APP_RESPONSE_FROM_SNTP_SERVER_TIMEOUT, MQTT_ConnectToBroker, MQTT_CONNECT_TIMEOUT_IN_MS, MQTT_SubsribeToTopic, MQTT_SUBSCRIBE_TIMEOUT_IN_MS, Retcode_RaiseError, vTaskSuspend, NULL, AppControllerValidateWLANConnectivity, Sensor_GetData, Sensor_Value_S::RH, Sensor_Value_S::Pressure, Sensor_Value_S::Temp, MQTT_Publish_S::Payload, MQTT_Publish_S::PayloadLength, MQTT_PublishToTopic, MQTT_PUBLISH_TIMEOUT_IN_MS, vTaskDelay, APP_MQTT_DATA_PUBLISH_PERIODICITY.
Referenced by AppControllerEnable.
static void AppControllerSetup(void *param1, uint32_t param2)
To setup the necessary modules for the application.
WLANServalPALSNTP (if secure communication)MQTTSensor param1 Unused param2 Unused
References BCDS_UNUSED, WLAN_Setup, RETCODE_OK, ServalPAL_Setup, SNTP_Setup, MQTT_Setup, Sensor_Setup_S::CmdProcessorHandle, AppCmdProcessor, Sensor_Setup, CmdProcessor_Enqueue, AppControllerEnable, NULL, Retcode_RaiseError, assert.
Referenced by AppController_Init.
static Retcode_T AppControllerValidateWLANConnectivity(void)
This will validate the WLAN network connectivity.
If there is no connectivity then it will scan for the given network and try to reconnectRETCODE_OK on success, or an error code otherwise.
References RETCODE_OK, WlanNetworkConnect_GetIpStatus, WLANNWCT_IPSTATUS_CT_AQRD, SNTP_Disable, WLAN_Reconnect, SNTP_Enable, MQTT_ConnectToBroker, MQTT_CONNECT_TIMEOUT_IN_MS, MQTT_SubsribeToTopic, MQTT_SUBSCRIBE_TIMEOUT_IN_MS.
Referenced by AppControllerFire.
static void AppMQTTSubscribeCB(MQTT_SubscribeCBParam_T param)
References AppIncomingMsgCount, AppIncomingMsgTopicBuffer, AppIncomingMsgPayloadBuffer, MQTT_SubscribeCBParam_S::PayloadLength, MQTT_SubscribeCBParam_S::Payload, MQTT_SubscribeCBParam_S::TopicLength, MQTT_SubscribeCBParam_S::Topic.
APP_MQTT_DATA_BUFFER_SIZE
macro for data size of incoming subscribed and published messages
Referenced by AppControllerFire.
APP_TEMPERATURE_OFFSET_CORRECTION
Macro for static temperature offset correction. Self heating, temperature correction factor
BCDS_MODULE_ID
MQTT_CONNECT_TIMEOUT_IN_MS
Macro for MQTT connection timeout in milli-second
Referenced by AppControllerValidateWLANConnectivity, AppControllerFire.
MQTT_PUBLISH_TIMEOUT_IN_MS
Macro for MQTT publication timeout in milli-second
Referenced by AppControllerFire.
MQTT_SUBSCRIBE_TIMEOUT_IN_MS
Macro for MQTT subscription timeout in milli-second
Referenced by AppControllerValidateWLANConnectivity, AppControllerFire.