LED
LED_E
LED_Pattern_E
This is roll through all the in-built LED's periodically forward and reverse
typedef enum LED_Pattern_E LED_Pattern_T
Typedef to represent the pattern of LED's supported.
typedef enum LED_E LED_T
Typedef to represent the inbuilt and external LED.
Retcode_T LED_Blink(bool enable, LED_T ledToBlink, uint32_t onTimeInMs, uint32_t offTimeInMs)
This will blink the LED based on the user requested configuration.
enable Boolean to enable/disable LED blink ledToBlink LED to blink (More the one LED can be provided for blinking with a bit-wise OR) Unused if 'enable' is 'false' onTimeInMs LED ON time while blinking in ms Unused if 'enable' is 'false' offTimeInMs LED OFF time while blinking in ms Unused if 'enable' is 'false' RETCODE_OK on success, or an error code otherwise. - LED_Blink when enabled, it is expected for the interface user to disable prior to other LED related API calls to avoid misbehavior. It uses software timer internally which is shared with LED_Pattern API. So user is expected to avoid using them in parallel.
Retcode_T LED_Enable(void)
This will enable the LED's available on-board.
By default these are Powered OFF RETCODE_OK on success, or an error code otherwise.
Referenced by AppControllerEnable.
Retcode_T LED_Off(LED_T led)
This will power OFF a particular LED.
led The LED to be powered OFF (More the one LED can be provided with a bit-wise OR) RETCODE_OK on success, or an error code otherwise.
Referenced by AppLWM2MStatusNotificationCB, Button1Callback, Button2Callback, LoRaEventNotificationCB, AppControllerFire, ProcessFingerPrint, AppSpecificLedIndication, ScanNetwork.
Retcode_T LED_On(LED_T led)
This will power ON a particular LED.
led The LED to be powered ON (More the one LED can be provided with a bit-wise OR) RETCODE_OK on success, or an error code otherwise.
Referenced by AppLWM2MStatusNotificationCB, Button1Callback, Button2Callback, LoRaEventNotificationCB, AppControllerFire, ProcessFingerPrint, AppSpecificLedIndication, ScanNetwork.
Retcode_T LED_Pattern(bool enable, LED_Pattern_T pattern, uint32_t statusTimeInMs)
This will provide a LED pattern based on the user requested configuration.
enable Boolean to enable/disable LED pattern pattern LED pattern to be enabled Unused if 'enable' is 'false' statusTimeInMs LED status time until which an ongoing LED pattern change must be held in ms Unused if 'enable' is 'false' RETCODE_OK on success, or an error code otherwise. - LED_Pattern when enabled, it is expected for the interface user to disable prior to other LED related API calls to avoid misbehavior. It uses software timer internally which is shared with LED_Blink API. So user is expected to avoid using them in parallel.
Referenced by AppSpecificLedIndication.
Retcode_T LED_Setup(void)
This will setup the LED's available on-board.
RETCODE_OK on success, or an error code otherwise.
Referenced by AppControllerSetup.
Retcode_T LED_Status(LED_T led, uint8_t *status)
This will provide the status of a particular LED.
led The LED to be read for status in/out] status Status on the IO port. User needs to provide memory for the same. This will read the value on the IO port and provide the same to the user RETCODE_OK on success, or an error code otherwise.
Referenced by SampleAndNotifyHighPriorityData.
Retcode_T LED_Toggle(LED_T led)
This will toggle a particular LED.
led The LED to be toggled (More the one LED can be provided with a bit-wise OR) RETCODE_OK on success, or an error code otherwise.
Referenced by ProcessFingerPrint.