SNTP
typedef struct SNTP_Setup_S SNTP_Setup_T
typedef to represent the SNTP setup feature.
Retcode_T SNTP_Disable(void)
This will disable the SNTP.
RETCODE_OK on success, or an error code otherwise for XDK_UTILITY_SERVALPAL enabled. RETCODE_NOT_SUPPORTED for XDK_UTILITY_SERVALPAL disabled. SNTP_Enable must have been successful prior.
Referenced by AppControllerValidateWLANConnectivity.
Retcode_T SNTP_Enable(void)
This will enable the SNTP.
RETCODE_OK on success, or an error code otherwise. WLAN_Enable must have been successful prior.ServalPAL_Enable must have been successful prior.SNTP_Setup must have been successful prior.Do not call this API more than once.
Referenced by AppControllerEnable, AppControllerValidateWLANConnectivity.
Retcode_T SNTP_GetTimeFromServer(uint64_t *sntpTimeStamp, uint32_t timeout)
This will request SNTP time-stamp from the SNTP server and return the same.
in/out] sntpTimeStamp SNTP time-stamp in UNIX format. 0 if server response was 0. Interface user must provide data memory. timeout Timeout for response from the server. RETCODE_OK on success, or an error code otherwise. SNTP_Setup and SNTP_Enable must have been successful prior.Must be called prior to SNTP_GetTimeFromSystem usage.
Referenced by AppControllerFireTask, AppControllerSyncSNTP, AppControllerFire.
Retcode_T SNTP_GetTimeFromSystem(uint64_t *sntpTimeStamp, uint32_t *timeLapseInMs)
This will provide SNTP time-stamp based on last synced SNTP server value and system time.
in/out] sntpTimeStamp Pointer to SNTP time-stamp in UNIX format. In seconds. 0 if server response failed. Interface user must provide data memory. in/out] timeLapseInMs Pointer to time lapsed in millisecond. Interface user must provide data memory. RETCODE_OK on success, or an error code otherwise. SNTP_Setup and SNTP_Enable must have been successful prior.SNTP_GetTimeFromSystem must have be called prior to this.Accuracy is limited due to XDK's internal clock inaccuracies w.r.t real time.Perform SNTP_GetTimeFromServer once in ~40 days atleast to avoid invalid time stamp since we use uint32_t system tick which will overflow otherwise.
Referenced by Button1Callback, AppControllerFire, getCurrentTime.
Retcode_T SNTP_SetTime(uint64_t sntpTimeStamp)
This will set SNTP time-stamp for the device.
sntpTimeStamp SNTP time-stamp in UNIX format. In seconds. RETCODE_OK on success, or an error code otherwise. SNTP_Setup and SNTP_Enable must have been successful prior.Make sure that the right time is provided.
Referenced by getCurrentTime.
Retcode_T SNTP_Setup(SNTP_Setup_T *setup)
This will setup the SNTP.
setup Pointer to the SNTP setup feature RETCODE_OK on success, or an error code otherwise. If setup->UseServerUrl is enabled, then setup->ServerIpAddr is unusedIf setup->UseServerUrl is disabled, then setup->ServerUrl is unusedThis must be the first API to be called if SNTP feature is to be used.WLAN_Setup must have been successful prior.ServalPAL_Setup must have been successful prior.Do not call this API more than once.
Referenced by AppControllerSetup.