XDK_Extension_Port_Gpio
CmdProcessor_T* GpioCmdProcessHandle
BSP_ExtensionPort_PinId_T GpioPinIdForEdgeInterrupt
Referenced by GpioInterruptCallback, ExtensionGpioExample_InitGpioIntBothEdge.
Retcode_T ExtensionGpioExample_DeleteGpio(BSP_ExtensionPort_PinId_T pinId)
This API is used to de-initialize a particular GPIO pin and put it into default state.
Refer interface header for description
References RETCODE_OK.
Retcode_T ExtensionGpioExample_InitGpioIntBothEdge(BSP_ExtensionPort_PinId_T pinId)
This API is used to configure GPIO as Input and capable of triggering interrupt for both Raising and Falling. After calling this API successfully the signal on the GPIO will trigger an Interrupt.
Refer interface header for description
References RETCODE_OK, NULL, GpioInterruptCallback, GpioPinIdForEdgeInterrupt.
Referenced by AppControllerEnable.
Retcode_T ExtensionGpioExample_InitGpioOutputMode(BSP_ExtensionPort_PinId_T pinId)
This API is used to configure GPIO pin as output pin.
Refer interface header for description
References RETCODE_OK, NULL.
Referenced by AppControllerFire.
Retcode_T ExtensionGpioExample_Initialize(CmdProcessor_T *handle)
This API is used to initialize the GPIO example resources.
Refer interface header for description
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER.
Referenced by AppControllerSetup.
static void GpioInterruptCallback(void)
Callback function to be triggered upon interrupt in GPIO input pin BSP_ExtensionPort_ReadGpio() is used to read the pin value on interrupt.
Note: De-bouncing logic is not implemented here. The user shall implement his own in case if it is required for their use case.
References RETCODE_OK, GpioPinIdForEdgeInterrupt, NULL, CmdProcessor_EnqueueFromIsr, GpioInterruptConsumer, Retcode_RaiseErrorFromIsr.
Referenced by ExtensionGpioExample_InitGpioIntBothEdge.
static void GpioInterruptConsumer(void *param1, uint32_t pinValue)
Deferred function called upon interrupt to process, this way of implementation can be used in case user want to execute long procedure upon this event on GPIO.
param1 Unused pinValue Value on the GPIO pin
References BCDS_UNUSED.
Referenced by GpioInterruptCallback.
BCDS_MODULE_ID