LWM2M_EXAMPLE_CLIENT
CmdProcessor_T* AppCmdProcessor
Handle to store the main Command processor handle to be reused by ServalPAL thread
Referenced by AppControllerSetup.
xTaskHandle AppControllerHandle
OS thread handle for Application controller to be used by run-time blocking threads
Referenced by AppControllerEnable.
LWM2M_Setup_T Lwm2mSetup
Lwm2m setup parameters
SNTP_Setup_T SNTPSetupInfo
SNTP setup parameters
WLAN_Setup_T WLANSetupInfo
WLAN setup parameters
void AppController_Init(void *cmdProcessorHandle, uint32_t param2)
Gives control to the Application controller.
This is a template function where the user can write his custom application.Refer interface header for description
References BCDS_UNUSED, RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, CmdProcessor_Enqueue, AppControllerSetup, Retcode_RaiseError, assert.
static void AppControllerEnable(void *param1, uint32_t param2)
To enable the necessary modules for the application.
LEDWLANServalPALSNTPLwm2m param1 Unused param2 Unused
References BCDS_UNUSED, LED_Enable, RETCODE_OK, WLAN_Enable, ServalPAL_Enable, SNTP_Enable, LWM2M_Enable, AppControllerFire, TASK_STACK_SIZE_APP_CONTROLLER, NULL, TASK_PRIO_APP_CONTROLLER, AppControllerHandle, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_OUT_OF_RESOURCES, Retcode_RaiseError, assert, Utils_PrintResetCause.
Referenced by AppControllerSetup.
static void AppControllerFire(void *pvParameters)
Responsible for controlling the LWM2M Example client control flow.
pvParameters FreeRTOS task handle. Could be used if more than one thread is using this function block.
References BCDS_UNUSED, RETCODE_OK, AppControllerSyncSNTP, LWM2M_Register, Retcode_RaiseError, vTaskDelay, APP_SYNC_TIME_INTERVAL_MAX_MS.
Referenced by AppControllerEnable.
static void AppControllerSetup(void *param1, uint32_t param2)
To setup the necessary modules for the application.
LEDWLANServalPALSNTPLwm2m param1 Unused param2 Unused
References BCDS_UNUSED, LED_Setup, RETCODE_OK, WLAN_Setup, ServalPAL_Setup, SNTP_Setup, LWM2M_Setup_S::CmdProcessorHandle, AppCmdProcessor, LWM2M_Setup, CmdProcessor_Enqueue, AppControllerEnable, NULL, Retcode_RaiseError, assert.
Referenced by AppController_Init.
void AppControllerSyncSNTP(void)
This will synchronizing the SNTP server time with the node.
References RETCODE_OK, SNTP_GetTimeFromServer, APP_RESPONSE_FROM_SNTP_SERVER_TIMEOUT, BCDS_UNUSED.
static void AppLWM2MStatusNotificationCB(LWM2M_StatusNotification_T status)
Refer function prototype for description
References RETCODE_OK, LWM2M_REGISTRATION_SUCCESS, LED_Off, LED_INBUILT_RED, LED_On, LED_INBUILT_ORANGE, LED_INBUILT_YELLOW, LWM2M_REGISTRATION_FAILURE, LWM2M_REGISTRATION_UPDATE_SUCCESS, LWM2M_REGISTRATION_UPDATE_FAILURE, LWM2M_DEREGISTRATION_SUCCESS, LWM2M_DEREGISTRATION_FAILURE, LWM2M_NOTIFICATION_SUCCESS, LWM2M_NOTIFICATION_FAILURE, Retcode_RaiseError.
APP_RESPONSE_FROM_SNTP_SERVER_TIMEOUT
Timeout for SNTP server time sync
Referenced by AppControllerSyncSNTP.
APP_SYNC_TIME_INTERVAL_MAX_MS
APP_SYNC_TIME_INTERVAL_MAX_MS is the synchronization time with SNTP server.
Referenced by AppControllerFire.
BCDS_MODULE_ID