VIRTUAL_XDK_DEMO
CmdProcessor_T* AppCmdProcessor
Handle to store the main Command processor handle to be used by run-time event driven threads
Referenced by AppControllerSetup.
xTaskHandle AppControllerHandle
OS thread handle for Application controller to be used by run-time blocking threads
Referenced by AppControllerEnable.
BLE_Setup_T BLESetupInfo
BLE setup parameters
uint8_t Button1Status
Referenced by Button1EventCallback, SampleAndNotifyHighPriorityData.
uint8_t Button2Status
Referenced by Button2EventCallback, SampleAndNotifyHighPriorityData.
Button_Setup_T ButtonSetup
Button setup parameters
uint32_t DataSampleRateInMs
variable to store the sensor sample time
Referenced by AppControllerBleDataRxCB, AppControllerFire.
ExternalSensor_Setup_T ExternalSensorSetup
External Sensor setup parameters
ExternalSensor_Target_T ExtHwConnected
Referenced by HandleExternalHwHotPlug, AppControllerSetup.
bool extTempHwConnectStatus
Referenced by AppControllerEnable, AppControllerSetup.
uint8_t IsUseBuiltInSensorFusion
Referenced by AppControllerBleDataRxCB, SampleAndNotifyHighPriorityData.
bool lemHwConnectStatus
Referenced by AppControllerEnable, AppControllerSetup.
uint8_t ManufacturerCharacteristicValue[][]
uint8_t ModelNumberCharacteristicValue[][]
volatile float NoiseRmsVoltage
Referenced by SampleAndNotifyHighPriorityData, NoiseSensorTask.
xTaskHandle NoiseSensorHandle
OS thread handle for noise sensor to be used by run-time blocking threads
Referenced by AppControllerEnable.
uint16_t SampleCounter
counter used for toggling low priority data messages.
Referenced by SampleAndNotifyHighPriorityData, AppControllerFire.
bool SensorDataStartSampling
Referenced by AppControllerBleDataRxCB, AppControllerFire.
Sensor_Setup_T SensorSetup
Sensor setup parameters
uint8_t SoftwareRevisionCharacteristicValue[10U][10U]
Referenced by GetFwVersionInfo.
Storage_Setup_T StorageSetup
Storage setup parameters
const VirtualSensor_Enable_T VirtualSensors
void AppController_Init(void *cmdProcessorHandle, uint32_t param2)
Gives control to the Application controller.
This is a template function where the user can write his custom application.Refer interface header for description
References BCDS_UNUSED, RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, CmdProcessor_Enqueue, AppControllerSetup, APP_CONTROLLER_STEP1, Retcode_RaiseError, assert.
static void AppControllerBleDataRxCB(uint8_t *rxBuffer, uint8_t rxDataLength, void *param)
References BCDS_UNUSED, BLE_CONTROL_NODE, SensorServices_Info_S::sensorServicesType, CONTROL_NODE_START_SAMPLING, SensorServices_Info_S::sensorServicesContent, SensorDataStartSampling, CONTROL_NODE_CHANGE_SAMPLING_RATE, DataSampleRateInMs, CONTROL_NODE_REBOOT, BSP_Board_SoftReset, CONTROL_NODE_USE_SENSOR_FUSION, IsUseBuiltInSensorFusion.
static void AppControllerEnable(void *param1, uint32_t param2)
To enable the necessary modules for the application.
BLESensor InternalExternalVirtual StorageLEDButton
References BCDS_UNUSED, RETCODE_OK, APP_CONTROLLER_STEP1, Sensor_Enable, LED_Enable, AppSpecificLedIndication, CmdProcessor_Enqueue, AppControllerSetup, NULL, APP_CONTROLLER_STEP2, Retcode_RaiseError, assert, BLE_Enable, NoiseSensor_Enable, Storage_Enable, RETCODE_STORAGE_SDCARD_NOT_AVAILABLE, Retcode_GetCode, Button_Enable, ExternalSensor_Setup_S::Enable, ExternalSensor_Enable_S::LemVoltage, ExternalSensor_Enable_S::LemCurrent, lemHwConnectStatus, Lem_Enable, ExternalSensor_Enable_S::MaxTemp, ExternalSensor_Enable_S::MaxResistance, extTempHwConnectStatus, MAX31865_Connect, VirtualSensor_Enable, AppControllerFire, TASK_STACK_SIZE_APP_CONTROLLER, TASK_PRIO_APP_CONTROLLER, AppControllerHandle, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_OUT_OF_RESOURCES, NoiseSensorTask, TASK_STACK_SIZE_NOISE_SENSOR, TASK_PRIO_NOISE_SENSOR, NoiseSensorHandle, Utils_PrintResetCause.
Referenced by AppControllerSetup.
static void AppControllerFire(void *pvParameters)
Responsible for controlling the Virtual XDK demo application control flow.
Wait for BLE to be connectedBased on user need, sample the sensor and notify all the necessary sensor / high priority data pvParameters Unused
References BCDS_UNUSED, RETCODE_OK, BLE_IsConnected, AppSpecificLedIndication, SensorDataStartSampling, SampleAndNotifyHighPriorityData, Retcode_RaiseError, SampleCounter, vTaskDelay, DataSampleRateInMs.
Referenced by AppControllerEnable.
static void AppControllerSetup(void *param1, uint32_t param2)
To setup the necessary modules for the application.
BLESensor InternalExternalVirtual StorageLEDButton param1 Unused param2 Step to be fired
References BCDS_UNUSED, RETCODE_OK, APP_CONTROLLER_STEP1, Sensor_Setup_S::CmdProcessorHandle, AppCmdProcessor, Sensor_Setup, LED_Setup, CmdProcessor_Enqueue, AppControllerEnable, NULL, Retcode_RaiseError, assert, VirtualSensor_Setup_S::Enable, VirtualSensors, GetFwVersionInfo, BLE_Setup, NoiseSensor_Setup, NOISE_SAMPLING_FREQUENCY, ExternalSensor_HwStatusPinInit, ExternalSensor_Setup_S::Enable, ExternalSensor_Enable_S::LemVoltage, ExternalSensor_Enable_S::LemCurrent, ExternalSensor_IsAvailable, XDK_EXTERNAL_LEM, lemHwConnectStatus, ExtHwConnected, XDK_EXTERNAL_MAX31865, extTempHwConnectStatus, XDK_EXTERNAL_INVALID, ExternalSensor_HwStatusPinDeInit, ExternalSensor_Enable_S::MaxTemp, ExternalSensor_Setup_S::CmdProcessorHandle, ExternalSensor_Setup, VirtualSensor_Setup, Storage_Setup, Button_Setup_S::CmdProcessorHandle, Button_Setup, APP_CONTROLLER_STEP2.
Referenced by AppControllerEnable, AppController_Init.
static void AppSpecificLedIndication(bool bleConnectionStatus)
This function is to control the Application specific LED indication for BLE connection status.
If connected then Orange LED is turned ONIf disconnected then Rolling LED pattern is provided bleConnectionStatus Boolean representing the control BLE connection status
References RETCODE_OK, LED_Pattern, LED_PATTERN_ROLLING, LED_On, LED_INBUILT_ORANGE, LED_Off, Retcode_RaiseError.
Referenced by AppControllerFire, AppControllerEnable.
static void Button1EventCallback(ButtonEvent_T buttonEvent)
References BUTTON_EVENT_PRESSED, Button1Status.
static void Button2EventCallback(ButtonEvent_T buttonEvent)
References BUTTON_EVENT_PRESSED, Button2Status.
static uint8_t* ConvertDecimalToSTring(uint8_t data, uint8_t *str)
Convert Decimal/Hex value to String Format to display Version Information.
data - Number which needs to be convert into string to display in Decimal instead of HEX values. in/out] *str - pointer to Store/write the Version number in String Format.
Referenced by ConvertInteger32ToVersionString.
static void ConvertInteger32ToVersionString(uint32_t xdkVersion, uint8_t *str)
This function is to convert the integer data into a string data.
xdkVersion - 32 bit value containing the XDK SW version information in/out] str - pointer to the parsed version string
References ConvertDecimalToSTring.
Referenced by GetFwVersionInfo.
static Retcode_T CurrentExternalHWConnected(ExternalSensor_Target_T *currentHw)
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, XDK_EXTERNAL_INVALID, ExternalSensor_IsAvailable, XDK_EXTERNAL_LEM, XDK_EXTERNAL_MAX31865.
Referenced by HandleExternalHwHotPlug.
static void GetFwVersionInfo(void)
This function to Get the Firmware Version by combining the XDK SW Release (i.e., Workbench Release) version (i.e., 3.2.0)
References XdkVersion_GetVersion, ConvertInteger32ToVersionString, SoftwareRevisionCharacteristicValue.
Referenced by AppControllerSetup.
static void HandleExternalHwHotPlug(ExternalSensor_Target_T *connectedHw)
References XDK_EXTERNAL_INVALID, RETCODE_OK, NULL, CurrentExternalHWConnected, ExtHwConnected, XDK_EXTERNAL_LEM, Lem_Disable, ExternalSensor_HwStatusPinInit, XDK_EXTERNAL_MAX31865, MAX31865_Disconnect, ExternalSensor_HwStatusPinDeInit, MAX31865_Connect, Lem_Enable.
Referenced by SampleAndNotifyHighPriorityData.
static void NoiseSensorTask(void *pvParameters)
Responsible for reading the RMS voltage of noise sensor.
pvParameters Unused
References BCDS_UNUSED, RETCODE_OK, NoiseSensor_ReadRmsValue, Retcode_RaiseError, NOISE_RMS_ADC_SAMPLES, NOISE_RMS_AVG_RANGE_IN_MV, ADC_CENTRAL_NO_OF_SAMPLES, NoiseRmsVoltage.
Referenced by AppControllerEnable.
static Retcode_T SampleAndNotifyHighPriorityData(void)
References RETCODE_OK, HandleExternalHwHotPlug, Sensor_GetData, ExternalSensor_Setup_S::Enable, ExternalSensor_Enable_S::LemVoltage, XDK_EXTERNAL_LEM, ExternalSensor_GetLemData, NULL, ExternalSensor_Enable_S::MaxTemp, XDK_EXTERNAL_MAX31865, ExternalSensor_GetMax31865Data, Sensor_Value_S::Temp, LED_Status, LED_INBUILT_YELLOW, LED_INBUILT_RED, LED_INBUILT_ORANGE, IsUseBuiltInSensorFusion, Sensor_Value_S::Accel, Sensor_AxisValue_S::X, Sensor_AxisValue_S::Y, Sensor_AxisValue_S::Z, Sensor_Value_S::Gyro, VirtualSensor_GetRotationData, ROTATION_QUATERNION, VirtualSensor_DataType_U::RotationQuaternion, VirtualSensor_RotationQuaternion_S::W, VirtualSensor_RotationQuaternion_S::X, VirtualSensor_RotationQuaternion_S::Y, VirtualSensor_RotationQuaternion_S::Z, SensorServices_Info_S::sensorServicesContent, HIGH_DATA_RATE_HIGH_PRIO, SensorServices_Info_S::sensorServicesType, BLE_HIGH_DATA_RATE, BLE_SendData, BLE_SEND_TIMEOUT_IN_MS, SampleCounter, Sensor_Value_S::Light, Sensor_Value_S::Pressure, Sensor_Value_S::RH, SDCARD_INSERTED, SDCardDriver_GetDetectStatus, Button1Status, Button2Status, Sensor_Value_S::Mag, Sensor_MagValue_S::X, Sensor_MagValue_S::Y, Sensor_MagValue_S::Z, Sensor_MagValue_S::R, LEM_SENSOR_DATA_VOLTS_TO_MICROVOLTS, NoiseRmsVoltage, NOISE_SENSOR_DATA_VOLTS_TO_MILLIVOLTS, HIGH_DATA_RATE_LOW_PRIO.
Referenced by AppControllerFire.
APP_CONTROLLER_STEP1
Referenced by AppControllerEnable, AppControllerSetup, AppController_Init.
APP_CONTROLLER_STEP2
Referenced by AppControllerEnable, AppControllerSetup.
BCDS_MODULE_ID
BLE_SEND_TIMEOUT_IN_MS
Referenced by SampleAndNotifyHighPriorityData.
LEM_SENSOR_DATA_VOLTS_TO_MICROVOLTS
Referenced by SampleAndNotifyHighPriorityData.
NOISE_RMS_ADC_SAMPLES
Referenced by NoiseSensorTask.
NOISE_RMS_AVG_RANGE_IN_MV
Referenced by NoiseSensorTask.
NOISE_SAMPLING_FREQUENCY
ADC sampling frequency in hertz (Hz)
Referenced by AppControllerSetup.
NOISE_SENSOR_DATA_VOLTS_TO_MILLIVOLTS
Referenced by SampleAndNotifyHighPriorityData.