HTTP_EXAMPLE_CLIENT
CmdProcessor_T* AppCmdProcessor
Handle to store the main Command processor handle to be reused by ServalPAL thread
xTaskHandle AppControllerHandle
OS thread handle for Application controller
Referenced by AppControllerEnable.
HTTPRestClient_Config_T HTTPRestClientConfigInfo
HTTP rest client configuration parameters
HTTPRestClient_Get_T HTTPRestClientGetInfo
HTTP rest client GET parameters
HTTPRestClient_Post_T HTTPRestClientPostInfo
HTTP rest client POST parameters
HTTPRestClient_Setup_T HTTPRestClientSetupInfo
HTTP rest client setup parameters
WLAN_Setup_T WLANSetupInfo
WLAN setup parameters
void AppController_Init(void *cmdProcessorHandle, uint32_t param2)
Gives control to the Application controller.
This is a template function where the user can write his custom application.Refer interface header for description
References BCDS_UNUSED, RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, CmdProcessor_Enqueue, AppControllerSetup, Retcode_RaiseError, assert.
static void AppControllerEnable(void *param1, uint32_t param2)
To enable the necessary modules for the application.
WLANServalPALSNTP (if HTTPS)HTTP rest client param1 Unused param2 Unused
References BCDS_UNUSED, WLAN_Enable, RETCODE_OK, ServalPAL_Enable, SNTP_Enable, HTTPRestClient_Enable, AppControllerFire, TASK_STACK_SIZE_APP_CONTROLLER, NULL, TASK_PRIO_APP_CONTROLLER, AppControllerHandle, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_OUT_OF_RESOURCES, Retcode_RaiseError, assert, Utils_PrintResetCause.
Referenced by AppControllerSetup.
static void AppControllerFire(void *pvParameters)
Responsible for controlling the HTTP Example application control flow.
Synchronize the node with the SNTP server for time-stamp (if HTTPS)Check whether the WLAN network connection is availableDo a HTTP rest client POSTWait for INTER_REQUEST_INTERVAL if POST was successfulDo a HTTP rest client GET if POST was successfulWait for INTER_REQUEST_INTERVAL if GET was successfulRedo the last 5 steps pvParameters Unused
References BCDS_UNUSED, RETCODE_OK, SNTP_GetTimeFromServer, APP_RESPONSE_FROM_SNTP_SERVER_TIMEOUT, AppControllerValidateWLANConnectivity, HTTPRestClient_Post, APP_RESPONSE_FROM_HTTP_SERVER_POST_TIMEOUT, vTaskDelay, INTER_REQUEST_INTERVAL, HTTPRestClient_Get, APP_RESPONSE_FROM_HTTP_SERVER_GET_TIMEOUT, Retcode_RaiseError.
Referenced by AppControllerEnable.
static void AppControllerSetup(void *param1, uint32_t param2)
To setup the necessary modules for the application.
WLANServalPALSNTP (if HTTPS)HTTP rest client param1 Unused param2 Unused
References BCDS_UNUSED, WLAN_Setup, RETCODE_OK, ServalPAL_Setup, SNTP_Setup, HTTPRestClient_Setup, CmdProcessor_Enqueue, AppControllerEnable, NULL, Retcode_RaiseError, assert.
Referenced by AppController_Init.
static Retcode_T AppControllerValidateWLANConnectivity(void)
This will validate the WLAN network connectivity.
If there is no connectivity then it will scan for the given network and try to reconnectRETCODE_OK on success, or an error code otherwise.
References RETCODE_OK, WlanNetworkConnect_GetIpStatus, WLANNWCT_IPSTATUS_CT_AQRD, SNTP_Disable, WLAN_Reconnect, SNTP_Enable.
Referenced by AppControllerFire.
static void HTTPRestClientGetCB(const char *responseContent, uint32_t responseContentLen, bool isLastMessage)
The HTTP GET request response callback.
responseContent Pointer to the GET request response responseContentLen Length of the GET request response isLastMessage Boolean to represent if it is the last part of the ongoing message Refer function definition for description
References BCDS_UNUSED, NULL.
APP_RESPONSE_FROM_HTTP_SERVER_GET_TIMEOUT
Timeout for completion of HTTP rest client GET
Referenced by AppControllerFire.
APP_RESPONSE_FROM_HTTP_SERVER_POST_TIMEOUT
Timeout for completion of HTTP rest client POST
Referenced by AppControllerFire.
BCDS_MODULE_ID