INBUILDSENSOR
Sensor_AccelType_E
In-built BMA280 sensor
Sensor_GyroType_E
In-built BMG160 sensor
typedef struct Sensor_AccelConfiguration_S Sensor_AccelConfiguration_T
Typedef representing the accelerometer configurations.
typedef enum Sensor_AccelType_E Sensor_AccelType_T
Typedef representing the supported Accelerometer sensor.
typedef struct Sensor_AxisValue_S Sensor_AccelValue_T
Typedef to represent the Accelerometer Data.
typedef struct Sensor_Configuration_S Sensor_Configuration_T
typedef struct Sensor_Enable_S Sensor_Enable_T
Typedef to represent the Sensor to be enabled.
typedef struct Sensor_GyroConfiguration_S Sensor_GyroConfiguration_T
Typedef representing the Gyro configurations.
typedef enum Sensor_GyroType_E Sensor_GyroType_T
Typedef representing the supported Gyroscope sensor.
typedef struct Sensor_AxisValue_S Sensor_GyroValue_T
Typedef to represent the Gyroscope Data.
typedef struct Sensor_LightConfiguration_S Sensor_LightConfiguration_T
Typedef representing the supported light sensor.
typedef struct Sensor_MagConfiguration_S Sensor_MagConfiguration_T
Typedef representing the Magnetometer configurations.
typedef struct Sensor_MagValue_S Sensor_MagValue_T
Typedef to represent the Magnetometer Data.
typedef struct Sensor_Setup_S Sensor_Setup_T
Typedef to represent the Sensor setup features.
typedef struct Sensor_TempConfiguration_S Sensor_TempConfiguration_T
Typedef representing to configure Temperature sensor.
typedef struct Sensor_Value_S Sensor_Value_T
Typedef to represent the Data Collector sampled node information.
Retcode_T Sensor_Enable(void)
This will enable the Sensor module.
RETCODE_OK on success, or an error code otherwise. Based on setup->Enable value, it will enable the necessary sensors.Sensor_Setup must have been successful prior.Do not call this API more than once.
Referenced by AppControllerEnable.
Retcode_T Sensor_GetData(Sensor_Value_T *value)
This will sample the necessary sensor nodes.
in/out] value The sampled sensor node values. User must provide a valid buffer. RETCODE_OK on success, or an error code otherwise. Sensor_Setup and Sensor_Enable must have been successful prior.This is a blocking callSensor_GetData are not thread safe, yet.
Referenced by AppControllerFireTask, AppControllerFire, SampleAndNotifyHighPriorityData.
Retcode_T Sensor_Setup(Sensor_Setup_T *setup)
This will setup the Sensor module.
setup Pointer to the Sensor setup feature RETCODE_OK on success, or an error code otherwise. This must be the first API to be called if this Sensor feature is to be used.Do not call this API more than once.
Referenced by AppControllerSetup.