BCDS_WLAN_NETWORK_CONFIG
WlanNetworkConfig_IpStatus_E
IPv4 Address Acquired
typedef void(* WlanNetworkConfig_IpCallback_T)(WlanNetworkConfig_IpStatus_T ipStatus))(WlanNetworkConfig_IpStatus_T ipStatus)
Type defining the prototype which Set IP function call back must conform to. This call back is called to notify the user when the IP is acquired following the call of WlanNetworkConfig_SetIpDhcp(). Returns the NCI IP status as a parameter
typedef struct WlanNetworkConfig_IpSettings_S WlanNetworkConfig_IpSettings_T
typedef enum WlanNetworkConfig_IpStatus_E WlanNetworkConfig_IpStatus_T
Retcode_T WlanNetworkConfig_GetIpAddress(uint8_t *url, uint32_t *destAddr)
This API returns back the Ip address by the host name.
url The string pointer holding the host name destAddr The variable in which IP address to be stored RETCODE_OK IP address returned succesffuly RETCODE_FAILURE Error occurred in fetching the ip address RETCODE_NULL_POINTER if the input parameter passes NULL Example usage:uint8_turl[]="www.google.com" uint32_tipAddress=0x00; Retcode_Tret; ret=WlanNetworkConfig_GetIpaddress(url,&ipAddress); if(RETCODE_OK!=ret) { //handleerror }
Referenced by NetworkConfig_GetIpAddress, PAL_getIpaddress, LWM2MDnsUtil_ExtendedResolveHostname.
Retcode_T WlanNetworkConfig_GetIpSettings(WlanNetworkConfig_IpSettings_T *myIpSettings)
Function to handle WLAN IP settings. This function gets the IP settings after a Successful connection.
myIpSettings Network configuration settings. Pointer contains IP address, Gateway, DNS Server and DHCP information RETCODE_NULL_POINTER - if the input parameter passes NULL. RETCODE_OK - Settings retrieved correctly. RETCODE_UNINITIALIZED - if WlanConnect_GetInitStatus failed by returning WLANCONNECT_NOT_INITIALZED. RETCODE_FAILURE - if sl_NetCfgGet failed by returning NETWORKCONFIG_FAILURE . The return value consist of (First 1 MSByte represents Package ID, Next Byte represents Severity and Last 2 LSBytes represents error code) Below shows the error code(last 2 Bytes) meaning Example usage: Getting the IP settings //LocalvariablethatstorestheIPsettings WlanNetworkConfig_IpSettings_TmyIpGet; //Localvariableforstoringthereturnstatus Retcode_TretStatus; //retrievetheIPsettings retStatus=WlanNetworkConfig_GetIpSettings(&myIpGet); //printamessageifthefunctionreturnedsuccessfully if(RETCODE_OK==retStatus) { printf("TheIPwasretrievedsuccessfully"); }
Referenced by AppControllerValidateWLANConnectivity, SetAndGetIp, NetworkConfig_GetIpSettings.
WlanNetworkConfig_IpStatus_T WlanNetworkConfig_GetIpStatus(void)
Function to get the IP status. This function return the IP status.
none WLANNWCNF_IPSTATUS_IPV4_AQRD - IPv4 was acquired WLANNWCNF_IPSTATUS_IPV6_AQRD - IPv6 was acquired (currently not supported) WLANNWCNF_IPSTATUS_IP_NOTAQRD - IP was not acquired Example usage: Block until IP status is acquired and Wlan is connected while((WLANNWCT_STATUS_DISCONNECTED==WlanNetworkConnect_GetStatus()) ||(WLANNWCNF_IPSTATUS_IP_NOTAQRD==WlanNetworkConfig_GetIpStatus())) { //Stayhereuntilconnectedandipacquired. //Timeoutlogiccanbeaddedhere. } This API must be called only after initialization
Referenced by AppControllerValidateWLANConnectivity, AppControllerWLANMonitor, SetAndGetIp, NetworkConfig_GetIpStatus.
uint8_t WlanNetworkConfig_Ipv4Byte(uint32_t ipValue, uint8_t index)
Function to convert an hexadecimal to IP.
ipValue Hexadecimal value of the IP V4 index Determines which byte of the IPV4 will be returned.It should be from 0 to 3 On success returns the integer value of IP from given hexadecimal value any error value refer SL_IPV4_BYTE error codes Example usage: Extract IPV4 byte from the hexadecimal IP value and print it //GettheIPsettings WlanNetworkConfig_GetIpSettings(&myIpGet); //PrinttheretrievedIPaddress.TheGateway,DNSandMask //canalsobeextractedinthesamemanner printf("-ThestaticIPwasretrieved:%u.%u.%u.%u\n\r", (unsignedint)(WlanNetworkConfig_Ipv4Byte(myIpGet.ipV4,3)), (unsignedint)(WlanNetworkConfig_Ipv4Byte(myIpGet.ipV4,2)), (unsignedint)(WlanNetworkConfig_Ipv4Byte(myIpGet.ipV4,1)), (unsignedint)(WlanNetworkConfig_Ipv4Byte(myIpGet.ipV4,0)));
Referenced by SetAndGetIp.
uint32_t WlanNetworkConfig_Ipv4Value(uint8_t add3, uint8_t add2, uint8_t add1, uint8_t add0)
Function to convert an IP to hexadecimal.
add3 Decimal value of the first byte (MSB) of an IPV4 add2 Decimal value of the second byte of an IPV4 add1 Decimal value of the third byte of an IPV4 add0 Decimal value of the last byte (LSB) of an IPV4 On success returns the integer value of IP from given hexadecimal value any error value refer SL_IPV4_VAL error codes Example usage: Transform IPV4 to hexadecimal value //Localvariables WlanNetworkConfig_IpSettings_TmyIpSet; //AftercallingthefunctiontheIPV4valuesshallbe: //0xc0a80278,theequivalentfor192.168.2.120 //0xc0a80201,theequivalentfor192.168.2.1 //0xffffff00,theequivalentfor255.255.255.0 myIpSet.ipv4=WlanNetworkConfig_Ipv4Value(192,168,2,120); myIpSet.ipV4DnsServer=WlanNetworkConfig_Ipv4Value(192,168,2,1); myIpSet.ipV4Gateway=WlanNetworkConfig_Ipv4Value(192,168,2,1); myIpSet.ipV4Mask=WlanNetworkConfig_Ipv4Value(255,255,255,0);
Retcode_T WlanNetworkConfig_SetIpDhcp(WlanNetworkConfig_IpCallback_T myIpCallback)
Function to handle WLAN IP settings. This function sets the IP by using DHCP.
myIpCallback Callback function for notifying user of IP acquisition using DHCP RETCODE_UNINITIALIZED - if WlanConnect_GetInitStatus failed by returning WLANCONNECT_NOT_INITIALZED. RETCODE_FAILURE - if sl_Start failed by returning other than ROLE_STA. RETCODE_OK - sets the IP by using DHCP successfully. Retcode_T The return value consist of (First 1 MSByte represents Package ID, Next Byte represents Severity and Last 2 LSBytes represents error code) Below shows the error code(last 2 Bytes) meaning Example usage: Setting DHCP IP with Callback //Callbackfunction voidmyDhcpIpCallbackFunc(WlanNetworkConfig_IpStatus_TreturnStatus) { //usercandosomethinginsidethiscallback } //localvariables NCI_ipCallback_tmyIpCallback; Retcode_TretStatus; //SettheIPcallback myIpCallback=myDhcpIpCallbackFunc; //ConfigureDHCPIPwithcallback retStatus=WlanNetworkConfig_SetIpDhcp(myIpCallback); Example2 usage: Setting DHCP IP without Callback //ConfigureDHCPIPwithoutcallback. //Notethatthisisthedefaultfunctionincasenoother //functionisusedinordertosettheIP retStatus=WlanNetworkConfig_SetIpDhcp(NULL);
Referenced by SetAndGetIp, NetworkConfig_SetIpDhcp.
Retcode_T WlanNetworkConfig_SetIpStatic(WlanNetworkConfig_IpSettings_T myIpSettings)
Function to handle WLAN IP settings. This function sets the static IP.
myIpSettings Network configuration settings structure. Contains IP address, Gateway, DNS Server and DHCP information RETCODE_OK - Settings retrieved correctly. RETCODE_UNINITIALIZED - if WlanConnect_GetInitStatus failed by returning WLANCONNECT_NOT_INITIALZED. RETCODE_FAILURE - if sl_NetCfgGet failed by returning NETWORKCONFIG_FAILURE. RETCODE_FAILURE - if sl_Start failed by returning other than ROLE_STA. Retcode_T The return value consist of (First 1 MSByte represents Package ID, Next Byte represents Severity and Last 2 LSBytes represents error code) Below shows the error code(last 2 Bytes) meaning Example usage: Setting static IP //Localvariables WlanNetworkConfig_IpSettings_TmyIpSet; Retcode_TretStatus; //IPsettingsthatwillbeused. myIpSet.isDHCP=(uint8_t)DHCP_DISABLED; myIpSet.ipV4=NCI_ipv4Value(192,168,2,120); myIpSet.ipV4DnsServer=NCI_ipv4Value(192,168,2,1); myIpSet.ipV4Gateway=NCI_ipv4Value(192,168,2,1); myIpSet.ipV4Mask=NCI_ipv4Value(255,255,255,0); //SetthestaticIP retStatus=WlanNetworkConfig_SetIpStatic(myIpSet); //printamessageifthefunctionreturnedsuccessfully if(RETCODE_OK==retStatus) { printf("ThestaticIPwassetsuccessfully"); }
Referenced by SetAndGetIp, NetworkConfig_SetIpStatic.
WLANNWCNF_DHCP_DISABLED
Macro for Dynamically Host Configuration Protocol disabled
Referenced by SetAndGetIp.
WLANNWCNF_DHCP_ENABLED
Macro for Dynamically Host Configuration Protocol enabled
WLANNWCNF_DHCP_FLG_ACQ
Macro for Dynamically Host Configuration Protocol acquired
Referenced by myDhcpIpCallbackFunc, SetAndGetIp.
WLANNWCNF_DHCP_FLG_NOT_ACQ
Macro for Dynamically Host Configuration Protocol not acquired
Referenced by SetAndGetIp.