UDP
UDP_Setup_E
typedef enum UDP_Setup_E UDP_Setup_T
Typedef to represent the UDP setup feature.
Retcode_T UDP_Close(int16_t handle)
This function will delete the local end-point for communication.
handle Handle to the UDP socket RETCODE_OK on success, or an error code otherwise.
Referenced by AppControllerFire.
Retcode_T UDP_Enable(void)
This will enable the UDP communication.
RETCODE_OK on success, or an error code otherwise. UDP_Setup must have been successful prior.Do not call this API more than once.
Referenced by AppControllerEnable.
Retcode_T UDP_Open(int16_t *handle)
This will create a local end-point for communication It creates a new socket of UDP socket type and provides the handle to the user for further communication.
in/out] handle Handle to the UDP socket. User must provide the memory. RETCODE_OK on success, or an error code otherwise.
Referenced by AppControllerFire.
Retcode_T UDP_Send(int16_t handle, uint32_t serverIp, uint16_t serverPort, uint8_t *dataPtr, uint32_t dataLen)
This will send a message to the server.
handle Handle to the UDP socket serverIp Server IP Address serverPort Server Port Number dataPtr Pointer to the buffer containing the message to be sent dataLen Length of the message to be sent RETCODE_OK on success, or an error code otherwise. Irrespective of send success or not, socket needs to be closed from application
Referenced by AppControllerFire.
Retcode_T UDP_Setup(UDP_Setup_T setup)
This will setup the UDP communication.
setup Pointer to the UDP setup feature RETCODE_OK on success, or an error code otherwise. This must be the first API to be called if UDP feature is to be used.Do not call this API more than once.
Referenced by AppControllerSetup.