BCDS_HAL_BSP_Board
typedef void(* BSP_Systick_Callback_T)(void))(void)
Type definition for the SysTick callback If an operating system is in use it may needs to perform some operations each system clock tick, this callback has to be provided by the application through BSP_Board_OSTickInitialize() function.
typedef void(* OStoBSPDelayFunc_T)(uint32_t))(uint32_t)
Type definition for the delay function which is passed from the OS to the BSP in order to replace the blocking delay function. uint32_t expected delay parameter type.
Retcode_T BSP_Board_ControlPowerRail(uint32_t control)
Controls the on-board power rails.
: provided that there are controllable power rails on the board, the BSP will provide the necessary commands that are possible to have in order to control them safely. control the desired power rail command implemented by the BSP. RETCODE_OK in the case of success or an error code otherwise.
References RETCODE_OK, BSP_XDK_RAIL_3V3_DISABLE, PWR_3V3_EN_PORT, PWR_3V3_EN_PIN, PowerSupply3V3Register_U::Register, BSP_XDK_RAIL_2V5_SNOOZE, PWR_2V5_SNOOZE_PORT, PWR_2V5_SNOOZE_PIN, PowerSupply2V5Register_U::Register, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM.
void BSP_Board_Delay(uint32_t delay)
Provide accurate delay based on variable incremented.
delay specifies the delay time Refer to your implementation for time granularity details.
References Board_GetTick.
Referenced by ExtensionPortSpiCtrl_AckAwaitHigh, ExtensionPortSpiCtrl_AckAwaitLow, Sigfox_Enable, Sigfox_SendWakeUp, BSP_BT_EM9301_Reset, BSP_Max31865_Connect, BSP_UMTS_LisaU2_Enable, BSP_UMTS_LisaU2_Disable, BSP_UMTS_LisaU2_Reset, configureSlopeInterrupt, Bma280Utils_DelayMS, Bme280Utils_DelayMS, Bme280Utils_initialize, Bmg160_DelayMS, Bmm150_DelayMS, Max44009Utils_initialize.
void BSP_Board_DelayUs(uint32_t delayInUs)
Provide accurate delay based on variable incremented in mikro seconds.
delayInUs specifies the delay time in us Refer to your implementation for time granularity details.
uint32_t BSP_Board_DetectPowerSupply(void)
Returns the power-supply mode.
This function detects whether the MCU is being supplied using a battery or using an external power supply.the current power supply type.
References POWER_SUPPLY_UNKNOWN.
void BSP_Board_DisableSysTick(void)
Disable the Core SysTick.
Retcode_T BSP_Board_EnableSysTick(void)
Enable the Core SysTick.
RETCODE_OK if success RETCODE_FAILURE if failure
References RETCODE_OK, HSE_VALUE, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_FAILURE.
Referenced by BSP_Board_Initialize.
uint32_t BSP_Board_GetBoardRevision(void)
Returns the BSP Revision.
BSP Revision.
uint64_t BSP_Board_GetTick(void)
Provide a timestamp based on variable incremented in milli seconds.
Refer to your implementation for time granularity details.
uint32_t BSP_Board_GetWakeupSource(void)
Returns the last wake-up source.
This function will return the last event that resulted in the wake-up of the MCU from a sleep/deep-sleep state.The latest wake-up event source.
References BSP_XDK_WAKE_EVENT_NONE.
Retcode_T BSP_Board_Initialize(uint32_t param1, void *param2)
Initializes the entire board.
This function is responsible of setting the initial configuration at the MCU and board level in order to establish a running state and perform basic operations.The MCU resources are at this time configured according to their use cases and shut-down in order to maintain a low power consumption. As an example for a UART interface the BSP_Board_Initialize(param1, param2) will set the baudrate, the parity, the number of data bits, the number of stop bits, etc. and then disables the UART and turns off its clock. param1 : Initialization parameter depending on the implementation, can be used to indicate type of param2. param2 : Initialization parameter depending on the implementation. RETCODE_OK in the case of success or an error code otherwise.
References BCDS_UNUSED, RETCODE_OK, IrqHandler_SysTickDummyHandler, BSP_Board_EnableSysTick, Board_WakeupPowerSupply2V5, MCU, Board_BURTC_Init, Board_RTC_Init, Board_GPIO_Init, Board_GPIOInterruptInit, Board_UART0_UART_Init, Board_UART1_UART_Init, Board_USART0_SPI_Init, Board_USART1_SPI_Init, Board_I2C0_Init, Board_I2C1_Init, Board_ADC_Init, Board_USB_Init, BSP_Board_SetOStoBSPDelayFunc, Board_Delay.
Referenced by systemStartup.
void BSP_Board_OSTickInitialize(BSP_Systick_Callback_T preCallback, BSP_Systick_Callback_T postCallback)
Initializes pre/post tick increment processing in OS based applications.
If an operating system needs to perform some operations before and/or after the system tick count is incremented the application needs to call this function and provide the callbacks which are called before and after the tick increment. preCallback A pointer to the function which the system needs to execute before incrementing the tick count of the system tick. If no pre-processing is needed provide NULL. postCallback A pointer that points to the function which the system needs to execute after incrementing the tick count of the system tick. If no post-processing is needed provide NULL.
References SysTickOsPreProcessing, SysTickOsPostProcessing.
Referenced by systemStartup.
void BSP_Board_SetOStoBSPDelayFunc(OStoBSPDelayFunc_T delayFunc)
Passes delay function from OS to BSP.
If the application needs to replace the blocking delays greater than 50ms with non blocking delays it has to assign the delay function to this function pointer.In general the delays implemented have 1 ms granularity. delayFunc delay function.
References OStoBSPdelayFunc.
Referenced by BSP_Board_Initialize.
void BSP_Board_SoftReset(void)
Invoke Board Soft Reset. This puts the MCU registers to appropriate state applicable for soft reset. Please note this is not equivalent to hard reset.
Referenced by AppControllerValidateWLANConnectivity, AppControllerFire, AppControllerBleDataRxCB, extractFaultInfo, FOTA_UpdateSdcardFw.
Retcode_T BSP_Board_SwitchPowerMode(uint32_t powerMode)
Switches between different power modes.
This function is responsible of preparing switching between the available MCU power modes if the transition from the current mode to the next mode is allowed. Depending on the selected mode this function implements the recovery routines in order to bring the system to the state before it switched to that power mode. powerMode 32 bit value designating the desired power mode according to what is specified in the implementation under BSP_BoardType.h RETCODE_OK in the case of success or an error code otherwise.
References BCDS_UNUSED, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NOT_SUPPORTED.