SEND_DATA_OVER_UDP
CmdProcessor_T* AppCmdProcessor
Handle to store the main Command processor handle to be used by run-time event driven threads
xTaskHandle AppControllerHandle
OS thread handle for Application controller to be used by run-time blocking threads
Referenced by AppControllerEnable.
uint8_t AppControllerTxBuffer[APP_CONTROLLER_TX_BUFFER_SIZE][APP_CONTROLLER_TX_BUFFER_SIZE]
This buffer holds the data to be sent to server via UDP
Referenced by AppControllerFire.
WLAN_Setup_T WLANSetupInfo
WLAN setup parameters
void AppController_Init(void *cmdProcessorHandle, uint32_t param2)
Gives control to the Application controller.
This is a template function where the user can write his custom application.Refer interface header for description
References BCDS_UNUSED, RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, CmdProcessor_Enqueue, AppControllerSetup, Retcode_RaiseError, assert.
static void AppControllerEnable(void *param1, uint32_t param2)
To enable the necessary modules for the application.
WLANUDP param1 Unused param2 Unused
References BCDS_UNUSED, WLAN_Enable, RETCODE_OK, UDP_Enable, AppControllerFire, TASK_STACK_SIZE_APP_CONTROLLER, NULL, TASK_PRIO_APP_CONTROLLER, AppControllerHandle, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_OUT_OF_RESOURCES, Retcode_RaiseError, assert, Utils_PrintResetCause.
Referenced by AppControllerSetup.
static void AppControllerFire(void *pvParameters)
Responsible for controlling the UDP Example application control flow.
-Creates a socket for communication -Sends the data to the remote server. -Closes the socket after successful communication. pvParameters Unused
References BCDS_UNUSED, RETCODE_OK, AppControllerTxBuffer, UDP_Open, UDP_Send, DEST_SERVER_IP, DEST_SERVER_PORT, Retcode_RaiseError, UDP_Close, vTaskDelay, APP_UDP_TX_DELAY.
Referenced by AppControllerEnable.
static void AppControllerSetup(void *param1, uint32_t param2)
To setup the necessary modules for the application.
WLANUDP param1 Unused param2 Unused
References BCDS_UNUSED, WLAN_Setup, RETCODE_OK, UDP_Setup, UDP_SETUP_USE_CC31XX_LAYER, CmdProcessor_Enqueue, AppControllerEnable, NULL, Retcode_RaiseError, assert.
Referenced by AppController_Init.
APP_CONTROLLER_TX_BUFFER_SIZE
BCDS_MODULE_ID