LORA_THINGS_NETWORK_DEMO
CmdProcessor_T* AppCmdProcessor
Handle to store the main Command processor handle to be used by run-time event driven threads
Referenced by AppControllerSetup.
xTaskHandle AppControllerHandle
OS thread handle for Application controller to be used by run-time blocking threads
const uint8_t AppKey[16][16]
< AppKey is the data encryption key used to "encode" the messages between the end nodes and the Application Server
LoRa_Setup_T LoRaSetupInfo
< LoRa setup parameters Sensor setup parameters
Sensor_Setup_T SensorSetup
void AppController_Init(void *cmdProcessorHandle, uint32_t param2)
Gives control to the Application controller.
This is a template function where the user can write his custom application.Refer interface header for description
References BCDS_UNUSED, RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, CmdProcessor_Enqueue, AppControllerSetup, Retcode_RaiseError, assert.
static void AppControllerEnable(void *param1, uint32_t param2)
To enable the necessary modules for the application.
LoRaSensor param1 Unused param2 Unused
References BCDS_UNUSED, RETCODE_OK, LoRa_Enable, LoRa_GetHwEUI, Sensor_Enable, LED_Enable, AppControllerFire, TASK_STACK_SIZE_APP_CONTROLLER, NULL, TASK_PRIO_APP_CONTROLLER, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_OUT_OF_RESOURCES, Retcode_RaiseError, assert.
Referenced by AppControllerSetup.
static void AppControllerFire(void *pvParameters)
Responsible for controlling the LORA Example application control flow.
LoRa join is doneRead the Sensor dataSend sensor data via. LoRa.Wait for APP_CONTROLLER_LORA_TX_DELAY before proceeding to redoing the above steps except first step pvParameters Unused
References BCDS_UNUSED, RETCODE_OK, APP_LORA_BUFFER_MAX_SIZE, CayenneLPPSerializer_Output_S::BufferLength, LoRa_Join, LED_On, LED_INBUILT_YELLOW, LoRa_SetDataRate, LoRa_SendUnconfirmed, Sensor_GetData, CayenneLPPSerializer_Output_S::BufferPointer, CayenneLPPSerializer_Input_S::DataType, CAYENNE_LLP_SERIALIZER_TEMPERATURE_SENSOR, CayenneLPPSerializer_Input_S::DataChannel, TEMPERATURE_DATA_CH, CayenneLPPSerializer_Input_S::Data, CayenneLPPSerializer_Data_U::TemperatureSensorValue, Sensor_Value_S::Temp, CayenneLPPSerializer_SingleInstance, CayenneLPPSerializer_Output_S::BufferFilledLength, CAYENNE_LLP_SERIALIZER_HUMIDITY_SENSOR, HUMIDITY_DATA_CH, CayenneLPPSerializer_Data_U::HumiditySensorValue, Sensor_Value_S::RH, CAYENNE_LLP_SERIALIZER_BAROMETER, PRESSURE_DATA_CH, CayenneLPPSerializer_Data_U::BarometerValue, Sensor_Value_S::Pressure, CAYENNE_LLP_SERIALIZER_ILLUMINANCE_SENSOR, ILLUMINANCE_DATA_CH, CayenneLPPSerializer_Data_U::IlluminanceSensorValue, Sensor_Value_S::Light, APP_LORA_PORT, Retcode_RaiseError, vTaskDelay, APP_CONTROLLER_LORA_TX_DELAY, LoRa_GetHwEUI, LED_INBUILT_RED, vTaskSuspend.
Referenced by AppControllerEnable.
static void AppControllerSetup(void *param1, uint32_t param2)
To setup the necessary modules for the application.
LoRaSensor param1 Unused param2 Unused
References BCDS_UNUSED, RETCODE_OK, LoRa_Setup, Sensor_Setup_S::CmdProcessorHandle, AppCmdProcessor, Sensor_Setup, LED_Setup, CmdProcessor_Enqueue, AppControllerEnable, NULL, Retcode_RaiseError, assert.
Referenced by AppController_Init.
static void LoRaEventNotificationCB(LoRa_Event_T event)
This is the LoRa event Notification callback function.
event event type that is received.
References RETCODE_OK, LORA_EVENT_RECEIVED_PACKET, LED_On, LED_INBUILT_RED, LED_INBUILT_ORANGE, LED_INBUILT_YELLOW, LORA_EVENT_SEND_FAILED, LED_Off.
APP_TEMPERATURE_OFFSET_CORRECTION
Macro for static temperature offset correction. Self heating, temperature correction factor
BCDS_MODULE_ID
HUMIDITY_DATA_CH
Referenced by AppControllerFire.
ILLUMINANCE_DATA_CH
Referenced by AppControllerFire.
PRESSURE_DATA_CH
Referenced by AppControllerFire.
TEMPERATURE_DATA_CH
Referenced by AppControllerFire.