SEND_ACCELEROMETER_DATA_OVER_UDP_AND_BLE
CmdProcessor_T* AppCmdProcessor
Handle to store the main Command processor handle to be used by run-time event driven threads
Referenced by AppControllerSetup.
bool AppControllerBleTransmitPayload
Boolean representing if BLE needs to be streamed. Validate the repeated start flag
Referenced by AppControllerBleDataRxCB, AppControllerFire.
xTaskHandle AppControllerHandle
OS thread handle for Application controller to be used by run-time blocking threads
Referenced by AppControllerEnable.
BLE_Setup_T BLESetupInfo
BLE setup parameters
Sensor_Setup_T SensorSetup
Sensor setup parameters
WLAN_Setup_T WLANSetupInfo
WLAN setup parameters
void AppController_Init(void *cmdProcessorHandle, uint32_t param2)
Gives control to the Application controller.
This is a template function where the user can write his custom application.Refer interface header for description
References BCDS_UNUSED, RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, CmdProcessor_Enqueue, AppControllerSetup, Retcode_RaiseError, assert.
static void AppControllerBleDataRxCB(uint8_t *rxBuffer, uint8_t rxDataLength, void *param)
This is the BLE data receive callback function.
Callback function called on data reception over BLE. rxBuffer pointer to the received data buffer rxDataLength Length of the received data param unused Do not perform any heavy processing within this function and return ASAP. rxBuffer : Buffer in which received data to be stored. rxDataLength : Length of received data. param Unused
References BCDS_UNUSED, RETCODE_OK, APP_CONTROLLER_BLE_RX_BUFFER_SIZE, APP_CONTROLLER_BLE_START_ID, AppControllerBleTransmitPayload, CmdProcessor_Enqueue, AppControllerBleStartOrEndMsgSend, NULL, APP_CONTROLLER_BLE_START_TRIGGER, APP_CONTROLLER_BLE_END_ID, APP_CONTROLLER_BLE_END_TRIGGER, Retcode_RaiseError.
static void AppControllerBleStartOrEndMsgSend(void *param1, uint32_t param2)
This will send start or stop message based on input parameter.
param1 Unused, Reserved for future use param2 Differentiates start and stop command. APP_CONTROLLER_BLE_START_PAYLOAD for start. APP_CONTROLLER_BLE_END_PAYLOAD for stop.
References BCDS_UNUSED, RETCODE_OK, APP_CONTROLLER_BLE_START_TRIGGER, BLE_SendData, APP_CONTROLLER_BLE_START_PAYLOAD, NULL, APP_CONTROLLER_BLE_SEND_TIMEOUT_IN_MS, APP_CONTROLLER_BLE_END_TRIGGER, APP_CONTROLLER_BLE_END_PAYLOAD, Retcode_RaiseError.
Referenced by AppControllerBleDataRxCB.
static void AppControllerEnable(void *param1, uint32_t param2)
To enable the necessary modules for the application.
WLANUDPBLESensor param1 Unused param2 Unused
References BCDS_UNUSED, WLAN_Enable, RETCODE_OK, UDP_Enable, BLE_Enable, Sensor_Enable, AppControllerFire, TASK_STACK_SIZE_APP_CONTROLLER, NULL, TASK_PRIO_APP_CONTROLLER, AppControllerHandle, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_OUT_OF_RESOURCES, Retcode_RaiseError, assert, Utils_PrintResetCause.
Referenced by AppControllerSetup.
static void AppControllerFire(void *pvParameters)
Responsible for controlling the UDP Example application control flow.
Check whether the network connection is availableTriggers a Sensor data samplingRead the sampled Sensor dataCreates a socket for communicationSends the data to the remote server.Closes the socket after successful communication.Send sensor data via. BLE.Wait for APP_CONTROLLER_UDP_TX_DELAY before proceeding to redoing the above steps except the first pvParameters Unused
References BCDS_UNUSED, RETCODE_OK, APP_CONTROLLER_BLE_TX_LEN, APP_CONTROLLER_TX_AXIS_COUNT, AppControllerValidateWLANConnectivity, Sensor_GetData, Sensor_Value_S::Accel, Sensor_AxisValue_S::X, Sensor_AxisValue_S::Y, Sensor_AxisValue_S::Z, UDP_Open, UDP_Send, DEST_SERVER_IP, DEST_SERVER_PORT, UDP_Close, Retcode_RaiseError, AppControllerBleTransmitPayload, BLE_IsConnected, BLE_SendData, NULL, APP_CONTROLLER_BLE_SEND_TIMEOUT_IN_MS, vTaskDelay, APP_CONTROLLER_TX_DELAY.
Referenced by AppControllerEnable.
static void AppControllerSetup(void *param1, uint32_t param2)
To setup the necessary modules for the application.
WLANUDPBLESensor param1 Unused param2 Unused
References BCDS_UNUSED, WLAN_Setup, RETCODE_OK, UDP_Setup, UDP_SETUP_USE_CC31XX_LAYER, BLE_Setup, Sensor_Setup_S::CmdProcessorHandle, AppCmdProcessor, Sensor_Setup, CmdProcessor_Enqueue, AppControllerEnable, NULL, Retcode_RaiseError, assert.
Referenced by AppController_Init.
static void AppControllerValidateWLANConnectivity(void)
This will validate the WLAN network connectivity.
Currently, upon abrupt disconnection the event from the WiFi chip is not propagated / notified to the application. Until then, we manually validate prior to ever HTTP Rest Client POST/GET cycle to make sure that the possibility of software break is reduced. We check if the IP is valid to validate the same.If there is no connectivity we will restart the node after 10 seconds.
References RETCODE_OK, WLANNWCNF_IPSTATUS_IP_NOTAQRD, WlanNetworkConfig_GetIpStatus, WLANNWCNF_IPSTATUS_IPV4_AQRD, WlanNetworkConfig_GetIpSettings, WlanNetworkConfig_IpSettings_S::ipV4, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NODE_IPV4_IS_CORRUPTED, RETCODE_NODE_WLAN_CONNECTION_IS_LOST, Retcode_RaiseError, vTaskDelay, BSP_Board_SoftReset, assert.
Referenced by AppControllerFire.
APP_CONTROLLER_BLE_END_TRIGGER
BLE end command send application logic
Referenced by AppControllerBleStartOrEndMsgSend, AppControllerBleDataRxCB.
APP_CONTROLLER_BLE_RX_BUFFER_SIZE
Size of BLE receive buffer
Referenced by AppControllerBleDataRxCB.
APP_CONTROLLER_BLE_SEND_TIMEOUT_IN_MS
Timeout for BLE send
Referenced by AppControllerBleStartOrEndMsgSend, AppControllerFire.
APP_CONTROLLER_BLE_START_TRIGGER
BLE start command send application logic
Referenced by AppControllerBleStartOrEndMsgSend, AppControllerBleDataRxCB.
APP_CONTROLLER_BLE_TX_LEN
Size of accelerometer complete payload in bytes with spaces in-between the axis values and NULL terminator
Referenced by AppControllerFire.
APP_CONTROLLER_TX_AXIS_COUNT
Number of accelerometer axis (x, y & z)
Referenced by AppControllerFire.
APP_TEMPERATURE_OFFSET_CORRECTION
Macro for static temperature offset correction. Self heating, temperature correction factor
BCDS_MODULE_ID