PPMPSERIALIZER
typedef struct PPMPSerializer_Setup_S PPMPSerializer_Setup_T
Typedef to represent the PPMP serializer setup feature.
Retcode_T PPMPSerializer_Enable(void)
This will enable the PPMP serializer.
RETCODE_OK on success, or an error code otherwise. PPMPSerializer_Setup must have been successful prior.Do not call this API more than once. Refer interface header for description
References RETCODE_OK.
Referenced by AppControllerEnable.
char* PPMPSerializer_PayloadExternalSensorSelective(bool create, char *timezoneISO8601format, uint32_t timeStampDelta, ExternalSensor_Value_T *sensorValue, ExternalSensor_Enable_T *serializeSensor)
This will construct and destruct the PPMP payload for XDK interfaced external sensors.
create If "true" the payload will be Constructed by allocating memory from the MCU heap. If "false" then any previously allocated memory will be destructed. timezoneISO8601format time zone in ISO-8601 format (string) timeStampDelta time stamp in milli seconds offset to timezoneISO8601format value sensorValue data collector last valid snap-shot to be serialized serializeSensor denotes which sensors needs to be serialized per request pointer to the constructed payload. Will be NULL in-case of failure. Every PPMPSerializer_PayloadExternalSensorSelective(true, ...) must follow with with PPMPSerializer_PayloadExternalSensorSelective(false, ...) Only LEM is supported, yet. Refer interface header for description
References NULL, Retcode_RaiseError, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, ExternalSensor_Enable_S::LemCurrent, ExternalSensor_Enable_S::LemVoltage, cJSON_CreateObject, cJSON_AddItemToObject, cJSON_CreateString, cJSON_AddStringToObject, PPMPSerializer_Setup_S::DeviceName, cJSON_CreateArray, cJSON_AddNumberToObject, ExternalSensor_Value_S::XLemI, ExternalSensor_Value_S::XLemV, JsonSensorSelective, cJSON_Print, cJSON_Minify, cJSON_Delete.
char* PPMPSerializer_PayloadSensorSelective(bool create, char *timezoneISO8601format, uint32_t timeStampDelta, Sensor_Value_T *sensorValue, Sensor_Enable_T *serializeSensor)
This will construct and destruct the PPMP payload for XDK in-built sensors.
create If "true" the payload will be Constructed by allocating memory from the MCU heap. If "false" then any previously allocated memory will be destructed. timezoneISO8601format time zone in ISO-8601 format (string) timeStampDelta time stamp in milli seconds offset to timezoneISO8601format value sensorValue data collector last valid snap-shot to be serialized serializeSensor denotes which sensors needs to be serialized per request pointer to the constructed payload. Will be NULL in-case of failure. Every PPMPSerializer_PayloadSensorSelective(true, ...) must follow with with PPMPSerializer_PayloadSensorSelective(false, ...) Refer interface header for description
References NULL, Retcode_RaiseError, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, Sensor_Enable_S::Accel, Sensor_Enable_S::Mag, Sensor_Enable_S::Gyro, Sensor_Enable_S::Humidity, Sensor_Enable_S::Temp, Sensor_Enable_S::Pressure, Sensor_Enable_S::Light, Sensor_Enable_S::Noise, cJSON_CreateObject, cJSON_AddItemToObject, cJSON_CreateString, cJSON_AddStringToObject, PPMPSerializer_Setup_S::DeviceName, cJSON_CreateArray, cJSON_AddNumberToObject, Sensor_Value_S::Accel, Sensor_AxisValue_S::X, Sensor_AxisValue_S::Y, Sensor_AxisValue_S::Z, Sensor_Value_S::Mag, Sensor_MagValue_S::X, Sensor_MagValue_S::Y, Sensor_MagValue_S::Z, Sensor_MagValue_S::R, Sensor_Value_S::Gyro, Sensor_Value_S::RH, Sensor_Value_S::Temp, Sensor_Value_S::Pressure, Sensor_Value_S::Light, Sensor_Value_S::Noise, JsonSensorSelective, cJSON_Print, cJSON_Minify, cJSON_Delete.
Referenced by AppControllerFire.
Retcode_T PPMPSerializer_Setup(PPMPSerializer_Setup_T *setup)
This will setup the PPMP serializer.
setup Pointer to the PPMP serializer setup feature RETCODE_OK on success, or an error code otherwise. This must be the first API to be called if PPMP serializer feature is to be used.Do not call this API more than once. Refer interface header for description
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER.
Referenced by AppControllerSetup.