WLAN
typedef struct WLAN_Setup_S WLAN_Setup_T
Typedef to represent the WLAN setup feature.
Retcode_T WLAN_ConvertIPAddressToString(uint32_t ipAddress, char *string)
This will converts a given uint32_t IP address to a null-terminated string, and stores the result in the given buffer. ipAddress The IP address to be converted. in/out] string A valid pointer to the buffer which the IP string should be written to. The given buffer must be larger than the maximal length of the IP string presentation by at least 1 (for the null-character). The written string will be NULL terminated. This must have a buffer size greater than 15U bytes. RETCODE_OK on success, or an error code otherwise.
Referenced by AppControllerWLANMonitor.
Retcode_T WLAN_Disable(void)
This will disable the WLAN.
RETCODE_OK on success, or an error code otherwise. This will disconnect from the WLAN network.
Retcode_T WLAN_Enable(void)
This will enable the WLAN.
RETCODE_OK on success, or an error code otherwise. If setup->IsHostPgmEnabled was enabled at the time of WLAN_Setup, then WLAN chip programming for dummy certificate will be enabled (programmed) as well.WLAN_Setup must have been successful prior.This is a blocking call and will connect to the WLAN network.Do not call this API more than once.
Referenced by AppControllerEnable.
WlanNetworkConnect_Callback_T WLAN_GetConnectionCallbackHandle(void)
Retcode_T WLAN_IsIpChanged(bool *ipChangeStatus, uint32_t *newIp)
This will validate if the WLAN IP configuration changed since WLAN_Enable.
in/out] ipChangeStatus Boolean if the IP changed in/out] newIp new IP if *ipChangeStatus is true RETCODE_OK on success, or an error code otherwise. WLAN_Enable must have been successful prior.
Referenced by AppControllerWLANMonitor.
Retcode_T WLAN_Reconnect(void)
This will reconnect to the specified network if it is available.
RETCODE_OK on success, or an error code otherwise.
Referenced by AppControllerValidateWLANConnectivity.
Retcode_T WLAN_Setup(WLAN_Setup_T *setup)
This will setup the WLAN.
setup Pointer to the WLAN setup feature RETCODE_OK on success, or an error code otherwise. If setup->IsHostPgmEnabled is enabled, then WLAN chip programming for dummy certificate will be setup as well.This must be the first API to be called if WLAN feature is to be used.Do not call this API more than once.
Referenced by AppControllerSetup.