SEND_VIRTUALSENSOR_DATA_OVER_USB
FingPrintMonitoringState_E
FingPrintSetValue_E
menuLevel_E
typedef enum FingPrintMonitoringState_E FingPrintMonitoringState_T
enum to represent magnetic fingerprint operational status
typedef enum FingPrintSetValue_E FingPrintSetValue_T
typedef enum menuLevel_E MenuLevel_T
enum to represent user interface menu level
CmdProcessor_T* AppCmdProcessor
Handle to store the main Command processor handle to be used by run-time event driven threads
Referenced by AppControllerSetup.
xTaskHandle AppControllerHandle
OS thread handle for Application controller to be used by run-time blocking threads
Referenced by AppControllerEnable.
uint8_t ButtonLeftPressedCnt
counter to monitor menu level: 0-> mag fing print monitoring; 1->set/reset/check MF1; 2->set/reset/check MF2; 3->set/reset/check MF3
Referenced by Button2Callback, Button1Callback, ProcessFingerPrint.
Button_Setup_T ButtonSetup
Button setup parameters
FingPrintSetValue_T FingPrintRequest[FINGERPRINT_REFVAL_MAX][FINGERPRINT_REFVAL_MAX]
variable to store whether a fingerprint has been requested
Referenced by Button2Callback, ProcessFingerPrint.
FingPrintMonitoringState_T FingPrintStatus
variable to store magnetic fingerprint oparation status
Referenced by Button2Callback, ProcessFingerPrint.
const VirtualSensor_Enable_T VirtualSensors
More than one sensor is not supported
Referenced by AppControllerSetup.
void AppController_Init(void *cmdProcessorHandle, uint32_t param2)
Gives control to the Application controller.
This is a template function where the user can write his custom application.Refer interface header for description
References BCDS_UNUSED, RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, CmdProcessor_Enqueue, AppControllerSetup, Retcode_RaiseError, assert.
static void AppControllerEnable(void *param1, uint32_t param2)
To enable the necessary modules for the application.
LEDButton param1 Unused param2 Unused
References BCDS_UNUSED, RETCODE_OK, VirtualSensor_Enable, LED_Enable, VirtualSensor_Enable_S::FingerPrint, Button_Enable, AppControllerFire, TASK_STACK_SIZE_APP_CONTROLLER, NULL, TASK_PRIO_APP_CONTROLLER, AppControllerHandle, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_OUT_OF_RESOURCES, Retcode_RaiseError, assert, Utils_PrintResetCause.
Referenced by AppControllerSetup.
static void AppControllerFire(void *pvParameters)
Print the enabled VirtualSensor for every PRINT_DATA_INTERVAL mS.
LEDButton pvParameters Unused
References BCDS_UNUSED, VirtualSensor_Enable_S::Rotation, PrintRotation, VirtualSensor_Enable_S::Compass, PrintCompass, VirtualSensor_Enable_S::AbsoluteHumidity, PrintHumidity, VirtualSensor_Enable_S::CalibratedAccel, PrintCalibratedAccel, VirtualSensor_Enable_S::CalibratedGyro, PrintCalibratedGyro, VirtualSensor_Enable_S::CalibratedMag, PrintCalibratedMag, VirtualSensor_Enable_S::Gravity, PrintGravity, VirtualSensor_Enable_S::StepCounter, PrintStepCounter, VirtualSensor_Enable_S::FingerPrint, ProcessFingerPrint, VirtualSensor_Enable_S::LinearAccel, PrintLinearAccel, VirtualSensor_Enable_S::Gesture, PrintGesture, vTaskDelay, FINGERPRINT_PROCESS_INTERVAL, PRINT_DATA_INTERVAL.
Referenced by AppControllerEnable.
static void AppControllerSetup(void *param1, uint32_t param2)
To setup the necessary modules for the application.
LEDButton param1 Unused param2 Unused
References BCDS_UNUSED, RETCODE_OK, VirtualSensor_Setup_S::Enable, VirtualSensors, VirtualSensor_Setup, LED_Setup, VirtualSensor_Enable_S::FingerPrint, Button_Setup_S::CmdProcessorHandle, AppCmdProcessor, Button_Setup, CmdProcessor_Enqueue, AppControllerEnable, NULL, Retcode_RaiseError, assert.
Referenced by AppController_Init.
static void Button1Callback(ButtonEvent_T buttonEvent)
Process the Button1 Data in side the Application context.
buttonEvent
References RETCODE_OK, BUTTON_EVENT_PRESSED, ButtonLeftPressedCnt, UI_MENU_LEVEL_3, UI_MENU_LEVEL_0, BUTTON_EVENT_RELEASED, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM, Retcode_RaiseError.
static void Button2Callback(ButtonEvent_T buttonEvent)
Process the Button2 Data in side the Application context.
buttonEvent
References RETCODE_OK, BUTTON_EVENT_PRESSED, UI_MENU_LEVEL_0, ButtonLeftPressedCnt, PROCESS_ON, FingPrintStatus, PROCESS_OFF, UI_MENU_LEVEL_1, VALUE_SET_REQUEST, FingPrintRequest, FINGERPRINT_REFVAL_1, VALUE_RESET_REQUEST, UI_MENU_LEVEL_2, FINGERPRINT_REFVAL_2, UI_MENU_LEVEL_3, FINGERPRINT_REFVAL_3, BUTTON_EVENT_RELEASED, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM, Retcode_RaiseError.
static void PrintCalibratedAccel(void)
References VirtualSensor_GetCalibratedAccel, ACCEL_LSB_MODE, RETCODE_OK, VirtualSensor_DataType_U::AxisInteger, VirtualSensor_AxisIntData_S::X, VirtualSensor_AxisIntData_S::Y, VirtualSensor_AxisIntData_S::Z, ACCEL_MPS2_MODE, VirtualSensor_DataType_U::AxisFloat, VirtualSensor_AxisFloatData_S::X, VirtualSensor_AxisFloatData_S::Y, VirtualSensor_AxisFloatData_S::Z, ACCEL_G_MODE.
Referenced by AppControllerFire.
static void PrintCalibratedGyro(void)
References VirtualSensor_GetCalibratedGyro, GYRO_LSB_MODE, RETCODE_OK, VirtualSensor_DataType_U::AxisInteger, VirtualSensor_AxisIntData_S::X, VirtualSensor_AxisIntData_S::Y, VirtualSensor_AxisIntData_S::Z, GYRO_RPS_MODE, VirtualSensor_DataType_U::AxisFloat, VirtualSensor_AxisFloatData_S::X, VirtualSensor_AxisFloatData_S::Y, VirtualSensor_AxisFloatData_S::Z, GYRO_DPS_MODE.
Referenced by AppControllerFire.
static void PrintCalibratedMag(void)
References VirtualSensor_GetCalibratedMag, MAG_LSB_MODE, RETCODE_OK, VirtualSensor_DataType_U::AxisInteger, VirtualSensor_AxisIntData_S::X, VirtualSensor_AxisIntData_S::Y, VirtualSensor_AxisIntData_S::Z, MAG_GAUSS_MODE, VirtualSensor_DataType_U::AxisFloat, VirtualSensor_AxisFloatData_S::X, VirtualSensor_AxisFloatData_S::Y, VirtualSensor_AxisFloatData_S::Z, MAG_MICROTESLA_MODE.
Referenced by AppControllerFire.
static void PrintCompass(void)
References VirtualSensor_GetCompassData, RETCODE_OK.
Referenced by AppControllerFire.
static void PrintGesture(void)
References RETCODE_OK, VirtualSensor_GetGestureCount.
Referenced by AppControllerFire.
static void PrintGravity(void)
References VirtualSensor_GetGravity, GRAVITY_LSB_MODE, RETCODE_OK, VirtualSensor_DataType_U::AxisInteger, VirtualSensor_AxisIntData_S::X, VirtualSensor_AxisIntData_S::Y, VirtualSensor_AxisIntData_S::Z, GRAVITY_MPS2_MODE, VirtualSensor_DataType_U::AxisFloat, VirtualSensor_AxisFloatData_S::X, VirtualSensor_AxisFloatData_S::Y, VirtualSensor_AxisFloatData_S::Z, GRAVITY_G_MODE.
Referenced by AppControllerFire.
static void PrintHumidity(void)
References VirtualSensor_GetAbsoluteHumidityData, RETCODE_OK.
Referenced by AppControllerFire.
static void PrintLinearAccel(void)
References VirtualSensor_GetLinearAccel, ACCEL_LSB_MODE, RETCODE_OK, VirtualSensor_DataType_U::AxisInteger, VirtualSensor_AxisIntData_S::X, VirtualSensor_AxisIntData_S::Y, VirtualSensor_AxisIntData_S::Z, ACCEL_MPS2_MODE, VirtualSensor_DataType_U::AxisFloat, VirtualSensor_AxisFloatData_S::X, VirtualSensor_AxisFloatData_S::Y, VirtualSensor_AxisFloatData_S::Z, ACCEL_G_MODE.
Referenced by AppControllerFire.
static void PrintRotation(void)
References VirtualSensor_GetRotationData, ROTATION_QUATERNION, RETCODE_OK, VirtualSensor_DataType_U::RotationQuaternion, VirtualSensor_RotationQuaternion_S::W, VirtualSensor_RotationQuaternion_S::X, VirtualSensor_RotationQuaternion_S::Y, VirtualSensor_RotationQuaternion_S::Z.
Referenced by AppControllerFire.
static void PrintStepCounter(void)
References VirtualSensor_GetStepCounter, RETCODE_OK.
Referenced by AppControllerFire.
static void ProcessFingerPrint(void)
References RETCODE_OK, FINGERPRINT_STORAGE_EMPTY, FINGERPRINT_REFVAL_MAX, ButtonLeftPressedCnt, UI_MENU_LEVEL_0, LED_Off, LED_INBUILT_RED, LED_INBUILT_ORANGE, LED_INBUILT_YELLOW, PROCESS_ON, FingPrintStatus, VirtualSensor_MonitorFingerPrint, FINGERPRINT_REFVAL_1, MATCHING_FACTOR, LED_On, FINGERPRINT_REFVAL_2, FINGERPRINT_REFVAL_3, UI_MENU_LEVEL_1, VirtualSensor_CheckFingerPrintStoredValue, FINGERPRINT_STORAGE_RECORDED, LED_Toggle, VALUE_SET_REQUEST, FingPrintRequest, VirtualSensor_SetFingerPrintValue, VALUE_RESET_REQUEST, VirtualSensor_ResetFingerPrintValue, NO_REQUEST, UI_MENU_LEVEL_2, UI_MENU_LEVEL_3, Retcode_RaiseError.
Referenced by AppControllerFire.
BCDS_MODULE_ID
MATCHING_FACTOR
Macro represents fingerprint matching factor
Referenced by ProcessFingerPrint.