XDK_Extension_Port_Uart
uint8_t TxBuffer[MAX_UART_RX_BUFFERSIZE][MAX_UART_RX_BUFFERSIZE]
Referenced by ProcessUartRxData.
CmdProcessor_T* uartCmdProcessorPtr
uint8_t UartRxBuffInstance[MAX_UART_RX_BUFFERSIZE][MAX_UART_RX_BUFFERSIZE]
Referenced by ProcessUartRxData, ExtensionUartExample_Initialize.
UARTTransceiver_T UartTranscieverInstance
Retcode_T ExtensionUartExample_DeInitialize(void)
This API is used to deinit the UART interface. Once this called, from there-on user needs to call ExtensionUartExample_Initialize for using the UART communication again.
Refer interface header for description
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, UARTTransceiver_Deinitialize.
Retcode_T ExtensionUartExample_Initialize(CmdProcessor_T *handle)
This API is used to prepare the UART with the user configuration data. Once after this call the user can write over UART interface at any time. Read callback will happen for each byte and user can able to read received data using UartRead()
Refer interface header for description
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, UART_BAURDRATE, UartCallBack, UART_TRANSCEIVER_UART_TYPE_UART, MAX_UART_RX_BUFFERSIZE, UARTTransceiver_Initialize, UartRxBuffInstance, UARTTransceiver_StartInAsyncMode, FrameEndCheckFunc, UartAppCallback.
Referenced by AppControllerSetup.
Retcode_T ExtensionUartExample_Read(uint8_t *readBuffer, uint8_t readlength, uint32_t *actualLength)
This API is used to read the data received over the UART interface.
Refer interface header for description
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, UARTTransceiver_ReadData, UART_SPI_DATA_TRANSFER_TIMEOUT_MILLISEC.
Referenced by ProcessUartRxData.
Retcode_T ExtensionUartExample_Write(uint8_t *writeBuffer, uint8_t writeLength)
This API is used to write data over the UART interface. Once the UartInit() was success, user can transmit data over UART interface.
Refer interface header for description
References RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, UARTTransceiver_WriteData, UART_SPI_DATA_TRANSFER_TIMEOUT_MILLISEC.
Referenced by SendUartResponseData.
static bool FrameEndCheckFunc(uint8_t lastByte)
References BCDS_UNUSED.
Referenced by ExtensionUartExample_Initialize.
static void ProcessUartRxData(void *param1, uint32_t param2)
References BCDS_UNUSED, RETCODE_OK, UART_RX_ERROR, ExtensionUartExample_Read, UartRxBuffInstance, TxBuffer, ProcessUartTxData.
Referenced by UartAppCallback.
static void ProcessUartTxData(uint8_t *txBuff, uint32_t txLength)
References RETCODE_OK, CmdProcessor_Enqueue, SendUartResponseData, Retcode_RaiseError.
Referenced by ProcessUartRxData.
static void SendUartResponseData(void *param1, uint32_t param2)
References RETCODE_OK, ExtensionUartExample_Write, Retcode_RaiseError.
Referenced by ProcessUartTxData.
static void UartAppCallback(struct MCU_UART_Event_S event)
References RETCODE_OK, NULL, CmdProcessor_EnqueueFromIsr, ProcessUartRxData, UART_RX_SUCCESS, UART_RX_ERROR, Retcode_RaiseErrorFromIsr.
Referenced by ExtensionUartExample_Initialize.
void UartCallBack(UART_T uart, struct MCU_UART_Event_S event)
References RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM, _UARTTransceiver_S::handle, UARTTransceiver_LoopCallback, Retcode_RaiseError.
Referenced by ExtensionUartExample_Initialize.
BCDS_MODULE_ID
END_OF_FRAME
MAX_UART_RX_BUFFERSIZE
Referenced by ExtensionUartExample_Initialize.
UART_BAURDRATE
Referenced by ExtensionUartExample_Initialize.
UART_RX_ERROR
Referenced by ProcessUartRxData, UartAppCallback.
UART_RX_SUCCESS
Referenced by UartAppCallback.
UART_SPI_DATA_TRANSFER_TIMEOUT_MILLISEC
Referenced by ExtensionUartExample_Read, ExtensionUartExample_Write.