BOSCH_XDK_CLOUD_CONNECTIVITY
uint32_t ActualFileReadSize
Length of store the configuration file retrieved from the SD card / WiFi storage
Referenced by AppControllerFire, AppControllerSetup.
CmdProcessor_T* AppCmdProcessor
Handle to store the main Command processor handle to be used by run-time event driven threads
Referenced by AppControllerSetup.
xTaskHandle AppControllerHandle
OS thread handle for Application controller to be used by run-time blocking threads
Referenced by AppControllerFire.
volatile bool Button1State
Boolean to represent the Button 1 state ("true" if pressed, "false" otherwise)
Referenced by Button1Callback, Button2Callback.
volatile bool Button2State
Boolean to represent the Button 2 state ("true" if pressed, "false" otherwise)
Referenced by Button1Callback, Button2Callback.
Button_Setup_T ButtonSetup
Button setup parameters
uint8_t FileReadBuffer[WIFI_CFG_FILE_READ_BUFFER][WIFI_CFG_FILE_READ_BUFFER]
Buffer to store the configuration file from the SD card / WiFi storage
Referenced by AppControllerFire, AppControllerSetup.
LWM2M_Setup_T Lwm2mSetup
LWM2M setup parameters. Many parameters are updated in run time
SNTP_Setup_T SNTPSetupInfo
SNTP setup parameters
Storage_Setup_T StorageSetup
Storage setup parameters
bool UseButtonsForLWM2MAlert
Boolean to represent if LWM2M alerts can be done for button triggers
Referenced by Button1Callback, Button2Callback, AppControllerFireTask.
WlanNetworkConnect_Status_T WlanConnectStatus
WLAN connection status
Referenced by AppControllerWLANMonitor.
WLAN_Setup_T WLANSetupInfo
WLAN setup parameters
void AppController_Init(void *cmdProcessorHandle, uint32_t param2)
Gives control to the Application controller.
This is a template function where the user can write his custom application.Refer interface header for description
References BCDS_UNUSED, RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, CmdProcessor_Enqueue, AppControllerSetup, APP_CONTROLLER_STEP1, Retcode_RaiseError, assert.
static void AppControllerEnable(void *param1, uint32_t param2)
To enable the necessary modules for the application. It is done in 2 steps. In Step 1, the modules enabled are:
Storage In Step 2, the modules enabled are:WLANServalPALSNTPLWM2M param1 Unused param2 Step to be enabled
References BCDS_UNUSED, RETCODE_OK, APP_CONTROLLER_STEP1, Storage_Enable, Retcode_RaiseError, Utils_GetXdkVersionString, CmdProcessor_Enqueue, AppControllerFire, NULL, APP_CONTROLLER_STEP2, WLAN_Enable, ServalPAL_Enable, SNTP_Enable, LWM2M_Enable, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM, assert, Utils_PrintResetCause.
Referenced by AppControllerSetup.
static void AppControllerFire(void *param1, uint32_t param2)
To fire the necessary modules for the application. It is done in 2 steps. In Step 1, the modules run functionality are:
Validate if SD Card storage if availableIf SD Card storage is available, validate if WIFI_CONFIG_FILE_NAME is availableIf WIFI_CONFIG_FILE_NAME is available, copy it to the WiFi file systemRename WIFI_CONFIG_FILE_NAME to SD_CARD_RENAME_FILE_NAMERead WIFI_CONFIG_FILE_NAME from the WiFi file system and store the contents to a global memoryEnqueue AppControllerSetup APP_CONTROLLER_STEP2 and exit In Step 2, the modules run functionality are:Create a task to perform the following enable the button supportSync SNTP server timetrigger a LWM2M registration param1 Unused param2 Step to be fired
References BCDS_UNUSED, RETCODE_OK, Storage_Read_S::FileName, WIFI_CONFIG_FILE_NAME, FileReadBuffer, Storage_Write_S::FileName, Storage_Rename_S::OriginalFileName, SD_CARD_RENAME_FILE_NAME, APP_CONTROLLER_STEP1, Storage_IsAvailable, STORAGE_MEDIUM_SD_CARD, Storage_Read, STORAGE_MEDIUM_WIFI_FILE_SYSTEM, Storage_Write_S::BytesToWrite, Storage_Read_S::ActualBytesRead, Storage_Write, Storage_Rename, RETCODE_STORAGE_SDCARD_NOT_AVAILABLE, Retcode_GetCode, Retcode_RaiseError, AppTxtParser_PrintConfigurations, ActualFileReadSize, CmdProcessor_Enqueue, AppControllerSetup, NULL, APP_CONTROLLER_STEP2, AppControllerFireTask, TASK_STACK_SIZE_APP_CONTROLLER, TASK_PRIO_APP_CONTROLLER, AppControllerHandle, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_OUT_OF_RESOURCES, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM, assert.
Referenced by AppControllerEnable.
static void AppControllerFireTask(void *pvParameters)
This task triggers the below.
Button supportSynchronizing the SNTP server timeLWM2M registration After that it periodically (APP_SYNC_TIME_INTERVAL_MAX_MS) synchronizes the SNTP time stamp pvParameters Unused
References BCDS_UNUSED, RETCODE_OK, AppControllerSyncSNTP, UseButtonsForLWM2MAlert, LWM2M_TEST_MODE_NO, AppTxtParser_LWM2MTestModeValue, Button_Enable, LWM2M_Register, Retcode_RaiseError, APP_SYNC_TIME_INTERVAL_MAX_MS, APP_WLAN_MONITOR_MAX_MS, AppControllerWLANMonitor, vTaskDelay.
Referenced by AppControllerFire.
static const char* AppControllerGetWlanConnectDescription(WlanNetworkConnect_Status_T wlanStatus)
References NULL, WLANNWCT_STATUS_CONNECTED, WLANNWCT_STATUS_DISCONNECTED, WLANNWCT_STATUS_CONNECTERR, WLANNWCT_STATUS_PWD_ERROR, WLANNWCT_STATUS_DISCONNECTERR.
Referenced by AppControllerWLANMonitor.
static void AppControllerSetup(void *param1, uint32_t param2)
To setup the necessary modules for the application. It is done in 2 steps. In Step 1, the modules setup are:
Refer function definition for description Wait for serial port to be enumeratedStorageButton In Step 2, the modules setup are:Fetch the MAC address of the WLAN chipAppTxtParserWLANServalPALSNTPLWM2M param1 Unused param2 Step to be setup
References BCDS_UNUSED, RETCODE_OK, SL_MAC_ADDR_LEN, AppTxtParser_Init_S::DataPointer, FileReadBuffer, ActualFileReadSize, APP_CONTROLLER_STEP1, vTaskDelay, SERIAL_CONNECT_TIME_INTERVAL_IN_MS, Storage_Setup, Button_Setup_S::CmdProcessorHandle, AppCmdProcessor, Button_Setup, CmdProcessor_Enqueue, AppControllerEnable, NULL, APP_CONTROLLER_STEP2, _u8, SL_MAC_ADDRESS_GET, SL_RET_CODE_OK, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_APP_FETCH_WLAN_MAC_FAILED, AppTxtParser_Init_S::DeviceMAC, AppTxtParser_Initialize, WLAN_Setup_S::SSID, AppTxtParser_WLANSsidValue, WLAN_Setup_S::Password, AppTxtParser_WLANPasswordValue, WLAN_Setup_S::IsStatic, AppTxtParser_WLANStaticIpValue, WLAN_Setup_S::IpAddr, AppTxtParser_WLANIpAddrValue, WLAN_Setup_S::GwAddr, AppTxtParser_WLANGwAddrValue, WLAN_Setup_S::DnsAddr, AppTxtParser_WLANDnsAddrValue, WLAN_Setup_S::Mask, AppTxtParser_WLANMaskValue, WLAN_Setup, ServalPAL_Setup, SNTP_Setup, LWM2M_Setup_S::CmdProcessorHandle, LWM2M_Setup_S::IsSecure, AppTxtParser_LWM2MIsSecureValue, LWM2M_Setup_S::SecurityMode, LWM2M_SECURITY_MODE_PRE_SHARED_KEY, LWM2M_Setup_S::SecurityPreSharedKey, LWM2M_SecurityPreSharedKeyInfo_S::Identity, AppTxtParser_DTLSPSKIdentityValue, LWM2M_SecurityPreSharedKeyInfo_S::Key, AppTxtParser_DTLSPSKSecretKeyValue, LWM2M_SecurityPreSharedKeyInfo_S::KeyLength, AppTxtParser_DTLSPSKSecretKeyLengthValue, LWM2M_Setup_S::EndPointName, AppTxtParser_LWM2MEndPointValue, LWM2M_Setup_S::ServerURL, AppTxtParser_LWM2MServerURLValue, LWM2M_Setup_S::ServerPort, AppTxtParser_LWM2MServerPortValue, LWM2M_Setup_S::Binding, AppTxtParser_LWM2MBindingValue, LWM2M_Setup_S::ConfirmableNotification, AppTxtParser_LWM2MConNotifiesValue, LWM2M_Setup_S::TestMode, AppTxtParser_LWM2MTestModeValue, LWM2M_Setup_S::Lifetime, AppTxtParser_LWM2MLifetimeValue, LWM2M_Setup, RETCODE_INVALID_PARAM, Retcode_RaiseError, assert.
Referenced by AppControllerFire, AppController_Init.
void AppControllerSyncSNTP(void)
This will synchronizing the SNTP server time with the node.
References RETCODE_OK, SNTP_GetTimeFromServer, APP_RESPONSE_FROM_SNTP_SERVER_TIMEOUT, BCDS_UNUSED.
Referenced by AppControllerFireTask, AppControllerFire.
void AppControllerWLANMonitor(void)
This will monitor the WLAN health.
References RETCODE_OK, WlanNetworkConnect_GetStatus, WLAN_IsIpChanged, WlanConnectStatus, AppControllerGetWlanConnectDescription, NULL, WLANNWCT_STATUS_CONNECTED, LWM2M_ConnectivityMonitoring, LWM2M_SET_IP_ADDRESS, WlanNetworkConfig_GetIpStatus, WLANNWCNF_IPSTATUS_IPV4_AQRD, WLAN_ConvertIPAddressToString, SL_RET_CODE_OK, LWM2M_SET_RADIO_SIGNAL_STRENGTH, SlGetRxStatResponse_t::AvarageDataCtrlRssi, Retcode_RaiseError.
Referenced by AppControllerFireTask.
static void AppLWM2MStatusNotificationCB(LWM2M_StatusNotification_T status)
LWM2M status notification callback.
status run-time status of the LWM2M stack Refer function prototype for description
References RETCODE_OK, LWM2M_REGISTRATION_SUCCESS, LED_Off, LED_INBUILT_RED, LED_On, LED_INBUILT_ORANGE, LED_INBUILT_YELLOW, LWM2M_REGISTRATION_FAILURE, LWM2M_REGISTRATION_UPDATE_SUCCESS, LWM2M_REGISTRATION_UPDATE_FAILURE, LWM2M_DEREGISTRATION_SUCCESS, LWM2M_DEREGISTRATION_FAILURE, LWM2M_NOTIFICATION_SUCCESS, LWM2M_NOTIFICATION_FAILURE, Retcode_RaiseError.
static void Button1Callback(ButtonEvent_T buttonEvent)
Callback for Button 1.
buttonEvent Button 1 event Refer function prototype for description
References RETCODE_OK, BUTTON_EVENT_PRESSED, Button1State, UseButtonsForLWM2MAlert, Button2State, LWM2M_TriggerForceRegister, LWM2M_LedMixModeControl, LWM2M_LED_MIX_MODE_RED_ON, SNTP_GetTimeFromSystem, LWM2M_AlertNotification, BUTTON_EVENT_RELEASED, LWM2M_LED_MIX_MODE_RED_OFF, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INCONSITENT_STATE, Retcode_RaiseError.
static void Button2Callback(ButtonEvent_T buttonEvent)
Callback for Button 2.
buttonEvent Button 2 event Refer function prototype for description
References RETCODE_OK, BUTTON_EVENT_PRESSED, Button2State, UseButtonsForLWM2MAlert, Button1State, LWM2M_TriggerForceRegister, LWM2M_LedMixModeControl, LWM2M_LED_MIX_MODE_ORANGE_OFF, BUTTON_EVENT_RELEASED, LWM2M_LED_MIX_MODE_ORANGE_ON, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INCONSITENT_STATE, Retcode_RaiseError.
APP_CONTROLLER_STEP1
Referenced by AppControllerFire, AppControllerEnable, AppControllerSetup, AppController_Init.
APP_CONTROLLER_STEP2
Referenced by AppControllerFire, AppControllerEnable, AppControllerSetup.
APP_RESPONSE_FROM_SNTP_SERVER_TIMEOUT
Timeout for SNTP server time sync
Referenced by AppControllerSyncSNTP.
APP_SYNC_TIME_INTERVAL_MAX_MS
APP_SYNC_TIME_INTERVAL_MAX_MS is the synchronization time with SNTP server.
Referenced by AppControllerFireTask, AppControllerFire.
APP_WLAN_MONITOR_MAX_MS
APP_WLAN_MONITOR_MAX_MS is the interval for monitoring the WLAN health.
Referenced by AppControllerFireTask.
BCDS_MODULE_ID
LWM2M_CLIENT_PORT
Macro to represent LWM2M client port
SD_CARD_RENAME_FILE_NAME
Referenced by AppControllerFire.
SERIAL_CONNECT_TIME_INTERVAL_IN_MS
Macro to represent connect time interval
Referenced by AppControllerSetup.
WIFI_CFG_FILE_READ_BUFFER
WIFI_CONFIG_FILE_NAME
Referenced by AppControllerFire.