AWS_SEND_DATA_OVER_MQTT
CmdProcessor_T* AppCmdProcessor
Handle to store the main Command processor handle to be used by run-time event driven threads
Referenced by AppControllerSetup.
xTaskHandle AppControllerHandle
OS thread handle for Application controller to be used by run-time blocking threads
Referenced by AppControllerFire.
uint32_t AppIncomingMsgCount
Incoming message count
Referenced by AppMQTTSubscribeCB.
char AppIncomingMsgPayloadBuffer[APP_MQTT_DATA_BUFFER_SIZE][APP_MQTT_DATA_BUFFER_SIZE]
Incoming message payload buffer
Referenced by AppMQTTSubscribeCB.
char AppIncomingMsgTopicBuffer[APP_MQTT_DATA_BUFFER_SIZE][APP_MQTT_DATA_BUFFER_SIZE]
Incoming message topic buffer
Referenced by AppMQTTSubscribeCB.
uint8_t FileReadBuffer[WIFI_CFG_FILE_READ_BUFFER][WIFI_CFG_FILE_READ_BUFFER]
Buffer to store the configuration file from the SD card / WiFi storage
Referenced by AppParseConfigFile, AppControllerFire.
cJSON* JsonParserHandle
MQTT_Connect_T MqttConnectInfo
MQTT connect parameters
MQTT_Publish_T MqttPublishInfo
MQTT publish parameters
MQTT_Setup_T MqttSetupInfo
MQTT setup parameters
MQTT_Subscribe_T MqttSubscribeInfo
MQTT subscribe parameters
Sensor_Setup_T SensorSetup
Sensor setup parameters
SNTP_Setup_T SNTPSetupInfo
SNTP setup parameters
Storage_Setup_T StorageSetup
Storage setup parameters
WLAN_Setup_T WLANSetupInfo
WLAN setup parameters
void AppController_Init(void *cmdProcessorHandle, uint32_t param2)
Gives control to the Application controller.
This is a template function where the user can write his custom application.Refer interface header for description
Referenced by main.
static void AppControllerEnable(void *param1, uint32_t param2)
To enable the necessary modules for the application. It is done in 2 steps. In Step 1, the modules enabled are:
Storage In Step 2, the modules enabled are:WLANServalPALSNTPLWM2MMQTTSensor param1 Unused param2 Step to be enabled
References BCDS_UNUSED, RETCODE_OK, APP_CONTROLLER_STEP1, Storage_Enable, Retcode_RaiseError, CmdProcessor_Enqueue, AppControllerFire, NULL, APP_CONTROLLER_STEP2, WLAN_Enable, ServalPAL_Enable, SNTP_Enable, MQTT_Enable, Sensor_Enable, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM, assert, Utils_PrintResetCause.
Referenced by AppControllerSetup.
static void AppControllerFire(void *param1, uint32_t param2)
To fire the necessary modules for the application. It is done in 2 steps. In Step 1, the modules run functionality are:
Validate if SD Card storage if available If available, then copy the below files to WiFi file system and rename the same in SD card APP_ROOT_CA_FILE_NAMEAPP_PRIVATE_KEY_FILE_NAMEAPP_CLIENT_CERT_KEY_FILE_NAMEAPP_CONFIGURATION_FILE_NAME Read APP_CONFIGURATION_FILE_NAME from the WiFi file system and store the contents to a global memoryParse the APP_CONFIGURATION_FILE_NAME content In Step 2, the modules run functionality are:Create a task to perform the following Sync SNTP server timeTrigger a MQTT connect, subscribe and periodic publish param1 Unused param2 Step to be fired
References BCDS_UNUSED, RETCODE_OK, Storage_Read_S::FileName, AWS_CONFIGURATION_FILE_NAME, FileReadBuffer, APP_CONTROLLER_STEP1, Storage_IsAvailable, STORAGE_MEDIUM_SD_CARD, Storage_Transfer_S::SourceFileName, APP_ROOT_CA_FILE_NAME, Storage_Transfer_S::DestinationFileName, AWS_ROOT_CA_FILE_NAME, Storage_Transfer_S::TransferBuffer, Storage_Transfer_S::TransferBlockSizeSize, Storage_Rename_S::OriginalFileName, Storage_Rename_S::NewFileName, APP_ROOT_CA_BACKUP_FILE_NAME, Storage_Transfer, STORAGE_MEDIUM_WIFI_FILE_SYSTEM, Storage_Rename, Retcode_RaiseError, APP_PRIVATE_KEY_FILE_NAME, AWS_PRIVATE_KEY_FILE_NAME, APP_PRIVATE_KEY_BACKUP_FILE_NAME, APP_CLIENT_CERT_KEY_FILE_NAME, AWS_CLIENT_CERT_KEY_FILE_NAME, APP_CLIENT_CERT_KEY_BACKUP_FILE_NAME, APP_CONFIGURATION_FILE_NAME, APP_CONFIGURATION_BACKUP_FILE_NAME, APP_USE_CONFIG_FILE, Storage_Read, Storage_Read_S::ActualBytesRead, AppParseConfigFile, CmdProcessor_Enqueue, AppControllerSetup, NULL, APP_CONTROLLER_STEP2, AppControllerFireTask, TASK_STACK_SIZE_APP_CONTROLLER, TASK_PRIO_APP_CONTROLLER, AppControllerHandle, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_OUT_OF_RESOURCES, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM, assert.
Referenced by AppControllerEnable.
static void AppControllerFireTask(void *pvParameters)
Responsible for controlling the send data over MQTT application control flow.
Synchronize SNTP time stamp for the WLAN chipConnect to MQTT brokerSubscribe to MQTT topicRead sensor dataPublish data periodically for a MQTT topic pvParameters Unused
References BCDS_UNUSED, RETCODE_OK, APP_MQTT_DATA_BUFFER_SIZE, SNTP_GetTimeFromServer, APP_RESPONSE_FROM_SNTP_SERVER_TIMEOUT, TimeStamp_SecsToTm, WlanDriver_SetDeviceTime, MQTT_ConnectToBroker, MQTT_CONNECT_TIMEOUT_IN_MS, MQTT_SubsribeToTopic, MQTT_SUBSCRIBE_TIMEOUT_IN_MS, Retcode_RaiseError, vTaskSuspend, NULL, AppControllerValidateWLANConnectivity, Sensor_GetData, Sensor_Value_S::Accel, Sensor_AxisValue_S::X, Sensor_AxisValue_S::Y, Sensor_AxisValue_S::Z, Sensor_Value_S::Mag, Sensor_MagValue_S::X, Sensor_MagValue_S::Y, Sensor_MagValue_S::Z, Sensor_Value_S::Gyro, Sensor_Value_S::RH, Sensor_Value_S::Pressure, Sensor_Value_S::Temp, MQTT_Publish_S::Payload, MQTT_Publish_S::PayloadLength, MQTT_PublishToTopic, MQTT_PUBLISH_TIMEOUT_IN_MS, vTaskDelay, APP_MQTT_DATA_PUBLISH_PERIODICITY.
Referenced by AppControllerFire.
static void AppControllerSetup(void *param1, uint32_t param2)
To setup the necessary modules for the application. It is done in 2 steps. In Step 1, the modules setup are:
Storage In Step 2, the modules setup are:WLANServalPALSNTPLWM2MMQTTSensor param1 Unused param2 Step to be setup
References BCDS_UNUSED, RETCODE_OK, APP_CONTROLLER_STEP1, Storage_Setup, CmdProcessor_Enqueue, AppControllerEnable, NULL, APP_CONTROLLER_STEP2, WLAN_Setup, ServalPAL_Setup, SNTP_Setup, MQTT_Setup_S::CmdProcessorHandle, AppCmdProcessor, MQTT_Setup, Sensor_Setup_S::CmdProcessorHandle, Sensor_Setup, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_INVALID_PARAM, Retcode_RaiseError, assert.
Referenced by AppControllerFire, AppController_Init.
static void AppControllerValidateWLANConnectivity(void)
This will validate the WLAN network connectivity.
Currently, upon abrupt disconnection the event from the WiFi chip is not propagated / notified to the application. Until then, we manually validate prior to ever HTTP Rest Client POST/GET cycle to make sure that the possibility of software break is reduced. We check if the IP is valid to validate the same.If there is no connectivity we will restart the node after 10 seconds.
References RETCODE_OK, WLANNWCNF_IPSTATUS_IP_NOTAQRD, WlanNetworkConfig_GetIpStatus, WLANNWCNF_IPSTATUS_IPV4_AQRD, WlanNetworkConfig_GetIpSettings, WlanNetworkConfig_IpSettings_S::ipV4, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NODE_IPV4_IS_CORRUPTED, RETCODE_NODE_WLAN_CONNECTION_IS_LOST, Retcode_RaiseError, vTaskDelay, BSP_Board_SoftReset, assert.
Referenced by AppControllerFireTask.
static void AppMQTTSubscribeCB(MQTT_SubscribeCBParam_T param)
References AppIncomingMsgCount, AppIncomingMsgTopicBuffer, AppIncomingMsgPayloadBuffer, MQTT_SubscribeCBParam_S::PayloadLength, MQTT_SubscribeCBParam_S::Payload, MQTT_SubscribeCBParam_S::TopicLength, MQTT_SubscribeCBParam_S::Topic.
static Retcode_T AppParseConfigFile(void)
References RETCODE_OK, cJSON_ParseWithOpts, FileReadBuffer, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, cJSON_GetObjectItem, RETCODE_INVALID_PARAM, WLAN_Setup_S::IsEnterprise, cJSON::valueint, WLAN_Setup_S::IsHostPgmEnabled, WLAN_Setup_S::SSID, cJSON::valuestring, WLAN_Setup_S::Username, WLAN_Setup_S::Password, WLAN_Setup_S::IsStatic, Utils_ConvertIpStringToNumber, WLAN_Setup_S::IpAddr, WLAN_Setup_S::GwAddr, WLAN_Setup_S::DnsAddr, WLAN_Setup_S::Mask, SNTP_Setup_S::ServerUrl, SNTP_Setup_S::ServerPort, MQTT_Connect_S::ClientId, MQTT_Connect_S::BrokerURL, MQTT_Connect_S::BrokerPort.
Referenced by AppControllerFire.
APP_CLIENT_CERT_KEY_BACKUP_FILE_NAME
Referenced by AppControllerFire.
APP_CLIENT_CERT_KEY_FILE_NAME
Referenced by AppControllerFire.
APP_CONFIGURATION_BACKUP_FILE_NAME
Referenced by AppControllerFire.
APP_CONFIGURATION_FILE_NAME
Referenced by AppControllerFire.
APP_CONTROLLER_STEP1
Referenced by AppControllerFire, AppControllerEnable, AppControllerSetup, AppController_Init.
APP_CONTROLLER_STEP2
Referenced by AppControllerFire, AppControllerEnable, AppControllerSetup.
APP_MQTT_DATA_BUFFER_SIZE
Macro for data size of incoming subscribed and published messages
Referenced by AppControllerFireTask.
APP_PRIVATE_KEY_BACKUP_FILE_NAME
Referenced by AppControllerFire.
APP_PRIVATE_KEY_FILE_NAME
Referenced by AppControllerFire.
APP_RESPONSE_FROM_SNTP_SERVER_TIMEOUT
Timeout for SNTP server time sync
Referenced by AppControllerFireTask, AppControllerFire.
APP_ROOT_CA_BACKUP_FILE_NAME
Referenced by AppControllerFire.
APP_ROOT_CA_FILE_NAME
Referenced by AppControllerFire.
APP_TEMPERATURE_OFFSET_CORRECTION
Macro for static temperature offset correction. Self heating, temperature correction factor
AWS_CONFIGURATION_FILE_NAME
Referenced by AppControllerFire.
BCDS_MODULE_ID
MQTT_CONNECT_TIMEOUT_IN_MS
Macro for MQTT connection timeout in milli-second
Referenced by AppControllerFireTask.
MQTT_PUBLISH_TIMEOUT_IN_MS
Macro for MQTT publication timeout in milli-second
Referenced by AppControllerFireTask.
MQTT_SUBSCRIBE_TIMEOUT_IN_MS
Macro for MQTT subscription timeout in milli-second
Referenced by AppControllerFireTask.
WIFI_CFG_FILE_READ_BUFFER
Macro for wifi config file read buffer