STREAM_SENSOR_DATA_OVER_USB
CmdProcessor_T* AppCmdProcessor
Handle to store the main Command processor handle to be reused by ServalPAL thread
Referenced by AppControllerSetup.
xTaskHandle AppControllerHandle
OS thread handle for Application controller to be used by run-time blocking threads
Referenced by AppControllerEnable.
Sensor_Setup_T SensorSetup
Sensor setup parameters
static void AccelAppCallback(void *param1, uint32_t param2)
Callback function called when interrupt occurs.
param1 Unused param2 Unused
References BCDS_UNUSED.
void AppController_Init(void *cmdProcessorHandle, uint32_t param2)
Gives control to the Application controller.
This is a template function where the user can write his custom application.Refer interface header for description
References BCDS_UNUSED, RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, CmdProcessor_Enqueue, AppControllerSetup, Retcode_RaiseError, assert.
static void AppControllerEnable(void *param1, uint32_t param2)
To enable the necessary modules for the application.
Sensor param1 Unused param2 Unused
References BCDS_UNUSED, Sensor_Enable, RETCODE_OK, AppControllerFire, TASK_STACK_SIZE_APP_CONTROLLER, NULL, TASK_PRIO_APP_CONTROLLER, AppControllerHandle, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_OUT_OF_RESOURCES, Retcode_RaiseError, assert, Utils_PrintResetCause.
Referenced by AppControllerSetup.
static void AppControllerFire(void *pvParameters)
This function controls the application flow.
Triggers Sensor data samplingRead the sampled Sensor data pvParameters Unused
References BCDS_UNUSED, RETCODE_OK, Sensor_GetData, Sensor_Setup_S::Enable, Sensor_Enable_S::Accel, Sensor_Setup_S::Config, Sensor_Configuration_S::Accel, Sensor_AccelConfiguration_S::IsRawData, Sensor_Value_S::Accel, Sensor_AxisValue_S::X, Sensor_AxisValue_S::Y, Sensor_AxisValue_S::Z, Sensor_Enable_S::Humidity, Sensor_Value_S::RH, Sensor_Enable_S::Pressure, Sensor_Value_S::Pressure, Sensor_Enable_S::Temp, Sensor_Value_S::Temp, Sensor_Enable_S::Mag, Sensor_Configuration_S::Mag, Sensor_MagConfiguration_S::IsRawData, Sensor_Value_S::Mag, Sensor_MagValue_S::X, Sensor_MagValue_S::Y, Sensor_MagValue_S::Z, Sensor_MagValue_S::R, Sensor_Enable_S::Gyro, Sensor_Configuration_S::Gyro, Sensor_GyroConfiguration_S::IsRawData, Sensor_Value_S::Gyro, Sensor_Enable_S::Light, Sensor_Value_S::Light, Sensor_Enable_S::Noise, Sensor_Value_S::Noise, Retcode_RaiseError, vTaskDelay, APP_CONTROLLER_TX_DELAY.
Referenced by AppControllerEnable.
static void AppControllerSetup(void *param1, uint32_t param2)
To setup the necessary modules for the application.
Sensor param1 Unused param2 Unused
References BCDS_UNUSED, Sensor_Setup_S::CmdProcessorHandle, AppCmdProcessor, Sensor_Setup, RETCODE_OK, CmdProcessor_Enqueue, AppControllerEnable, NULL, Retcode_RaiseError, assert.
Referenced by AppController_Init.
static void LightAppCallback(void *param1, uint32_t param2)
Callback function called when interrupt occurs.
param1 Unused param2 Unused
References BCDS_UNUSED.
BCDS_MODULE_ID