BMA280_SENSORUTILS
Bma280Utils_IntrChannel_E
Bma280Utils_IntrType_E
typedef struct Bma280Utils_ConfigInterrupt_S Bma280Utils_ConfigInterrupt_T
typedef struct Bma280Utils_ConfigInterrupt_S * Bma280Utils_ConfigInterruptPtr_T
typedef struct Bma280Utils_Info_S Bma280Utils_Info_T
typedef struct Bma280Utils_Info_S * Bma280Utils_InfoPtr_T
typedef enum Bma280Utils_IntrChannel_E Bma280Utils_IntrChannel_T
typedef void* Bma280Utils_IntrConfigPtr_T
Pointer to represent interrupt configuration structure.
typedef enum Bma280Utils_IntrType_E Bma280Utils_IntrType_T
typedef struct Bma280Utils_SlopeIntrConfig_S Bma280Utils_SlopeIntrConfig_T
typedef struct Bma280Utils_SlopeIntrConfig_S * Bma280Utils_SlopeIntrConfigPtr_T
Retcode_T Bma280Utils_configInterrupt(Bma280Utils_InfoPtr_T bma280Info, Bma280Utils_ConfigInterruptPtr_T interruptConfig)
Function to Configure interrupts of Bma280. Before calling this API Update the below information in the appropriate structure 1) Update callback function in Bma280Utils_InfoPtr_T. 2) Update the type of callback(deferred or real time) in Bma280Utils_InfoPtr_T. 3) Update interrupt type and channel to Which interrupt needs be associated in Bma280Utils_ConfigInterrupt_T. 4) Update Bma280Utils_IntrConfigPtr_T with appropriate interrupt configuration After calling this API the given interrupt will be enabled on the given channel and the callback will be associated with the interrupt.
bma280Info :Structure holding the bma280 specific configurations.Callback for the interrupt and its type should be given in this handle interruptConfig :Structure holding the information about interrupt type,channel and its related configuration should be given here RETCODE_OK Configuration of interrupt for BMA280 is success. RETCODE_NULL_POINTER when any of the input parameter(interruptConfig & interruptConfig->configInterrupt) is NULL. RETCODE_LIB_NULL_POINTER when any of the input parameter for BST library API is NULL. RETCODE_BST_BMA280_ERROR when error is returned from BST library API. RETCODE_INVALID_PARAM when the interrupt configuration parameter is invalid. RETCODE_UNINITIALIZED when this api is called before initializing Bma280 sensor The return value consist of (First 1 MSByte represents Package ID, Next byte represents Severity and Last 2 LSBytes represents error code).
References BCDS_UNUSED, RETCODE_FAILURE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, Bma280Utils_ConfigInterrupt_S::interruptChannel, BMA280UTILS_INTERRUPT_CHANNEL2, RETCODE_INVALID_PARAM, Bma280Utils_ConfigInterrupt_S::interruptType, BMA280UTILS_SLOPE_INTERRUPT, configureSlopeInterrupt, Bma280Utils_ConfigInterrupt_S::configInterrupt, BMA280UTILS_NEW_DATA_INTERRUPT, configureNewDataInterrupt.
Referenced by Accelerometer_configInterrupt.
Retcode_T Bma280Utils_disableInterrupt(Bma280Utils_InfoPtr_T bma280Info, Bma280Utils_IntrType_T interruptType, Bma280Utils_IntrChannel_T interruptChannel)
Function to Disable the Interrupt.
bma280Info :structure holding the Bma280 specific configurations interruptType :type of interrupt that needs to be disabled interruptChannel :interrupt channel in which interrupt needs to be disabled RETCODE_OK BMA280 disable interrupt success RETCODE_LIB_NULL_POINTER when any of the input parameter for BST library API is NULL. RETCODE_BST_BMA280_ERROR when error is returned from BST library API. RETCODE_INVALID_PARAM when the interrupt configuration parameter is invalid. RETCODE_UNINITIALIZED when this api is called before initializing Bma280 sensor. The return value consist of (First MSB Byte represents Package ID,Next Byte represents Severity and Last 2LSB Bytes represents error code).
References BCDS_UNUSED, BMA2x2_RETURN_FUNCTION_TYPE, E_OUT_OF_RANGE, RETCODE_FAILURE, BMA280UTILS_INTERRUPT_CHANNEL_INVALID, BMA280UTILS_INVALID_INTERRUPT, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_INVALID_PARAM, initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, BMA280UTILS_SLOPE_INTERRUPT, bma2x2_set_intr_slope, DISABLE_INTERRUPT, libErrorMapping.
Referenced by Accelerometer_disableInterrupt.
Retcode_T Bma280Utils_initialize(Bma280Utils_InfoPtr_T bma280Info)
Function to initialize Bma280. This needs to be called before calling any other API.
bma280Info :structure holding the bma280 specific configurations RETCODE_OK BMA280 is initialized successfully. RETCODE_NULL_POINTER when any of the input parameter(bma280Info->ISRCallback or bma280Info) is NULL. RETCODE_LIB_NULL_POINTER when any of the input parameter for BST library API is NULL. RETCODE_BST_BMA280_ERROR when error is returned from BST library API. RETCODE_DOPPLE_INITIALIZATION When initialization is already done. In case of other failures refer BSP_SensorNode_Enable or #I2CSensorTransceiver_Init API's. 1) The return value consist of (First MSB Byte represents Package ID,Next Byte represents Severity and Last 2LSB Bytes represents error code). 2) The support of multiple instances is not possible due to the limitation in the BST library. 3) Calling Bma280 initialization API present in sensorUtils (Bma280Utils_initialize) and BST library (bma2x2_init) concurrently will lead to unexpected behaviour.
References BMA2x2_RETURN_FUNCTION_TYPE, E_OUT_OF_RANGE, RETCODE_FAILURE, NULL, Bma280Utils_Info_S::ISRCallback, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, initializationStatus, RETCODE_SEVERITY_WARNING, RETCODE_DOPPLE_INITIALIZATION, SensorNodeMapping_Init, RETCODE_OK, BSP_SensorNode_Enable, Bma280Utils_Info_S::BspSensorId, RETCODE_SEVERITY_INFO, Retcode_GetSeverity, bma280Initialization, SensorNodeMapping_Read, SensorNodeMapping_Write, bma2x2_t::delay_msec, Bma280Utils_DelayMS, bma2x2_t::dev_addr, Bma280Utils_Info_S::dev_addr, bma2x2_init, SUCCESS, bma2x2_set_bw, BMA2x2_BW_500HZ, libErrorMapping.
Referenced by Accelerometer_init.
Retcode_T Bma280Utils_remapAxis(Bma280Utils_InfoPtr_T bma280Info, AxisRemap_Data_T *accelData)
Function to read remapped Bma280 data.
bma280Info :structure holding the Bma280 specific configurations. The information about remap configuration should be given in this struct accelData : while calling this API structure will hold the Bma280 data that needs to be the remapped. After calling this API the structure will hold remapped data RETCODE_OK BMA280 axis remap success RETCODE_NULL_POINTER when any of the input parameter is NULL. RETCODE_UNINITIALIZED when this api is called before initializing Bma280 sensor. In case of other failures refer AxisRemap_remapSensorData API. The return value consist of (First MSB Byte represents Package ID,Next Byte represents Severity and Last 2LSB Bytes represents error code).
References RETCODE_FAILURE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, AxisRemap_Data_S::x, AxisRemap_Data_S::y, AxisRemap_Data_S::z, AxisRemap_remapSensorData, Bma280Utils_Info_S::remap.
Referenced by Accelerometer_readXyzLsbValue, Accelerometer_readXyzGValue.
Retcode_T Bma280Utils_uninitialize(Bma280Utils_InfoPtr_T bma280Info)
Function to uninitialize Accel.After calling this API sensor is no more usable without initializing it again by calling Bma280Utils_initialize() API.
bma280Info :structure holding the bma280 specific configurations RETCODE_OK BMA280 un-initialization success RETCODE_NULL_POINTER when bma280Info is NULL. RETCODE_UNINITIALIZED when this api is called before initializing Bma280 sensor. In case of other failures refer BSP_SensorNode_Disable or BSP_SensorNode_IsAllNodesDisabled or #I2CSensorTransceiver_Deinit API. The return value consist of (First MSB Byte represents Package ID,Next Byte represents Severity and Last 2LSB Bytes represents error code).
References RETCODE_FAILURE, NULL, RETCODE, RETCODE_SEVERITY_FATAL, RETCODE_NULL_POINTER, initializationStatus, RETCODE_SEVERITY_ERROR, RETCODE_UNINITIALIZED, BSP_SensorNode_Disable, Bma280Utils_Info_S::BspSensorId, RETCODE_OK, SensorNodeMapping_DeInit.
Referenced by Accelerometer_deInit.