BCDS_HAL_BSP_Mic_AKU340
BCDS_DEPRECATED(int32_t BSP_Mic_AKU340_Sense(void))
Senses the AKU340 Microphone signal.
DeprecatedThis API is deprecated.This function is called to trigger an ADC Conversion at the microphone pin and return the measured value.returns INT32_MIN.
Retcode_T BSP_Mic_AKU340_Connect(void)
Maps the GPIO pins To their desired function.
The function once called will map the GPIO pins dedicated for the peripheral to their desired function. RETCODE_OK in the case of success or an error code otherwise.
References VDD_AKU_PORT, VDD_AKU_PIN, AKU_OUT_PORT, AKU_OUT_PIN, RETCODE_OK.
Referenced by NoiseSensor_Enable.
Retcode_T BSP_Mic_AKU340_Disable(void)
Disables the control over the AKU340.
RETCODE_OK in the case of success or an error code otherwise.
References micEnabled, VDD_AKU_PORT, VDD_AKU_PIN, AKU_OUT_PORT, AKU_OUT_PIN, Board_SnoozePowerSupply2V5, MIC_AKU340, RETCODE_OK.
Referenced by NoiseSensor_Disable.
Retcode_T BSP_Mic_AKU340_Disconnect(void)
Disconnects the peripheral from the MCU.
This function once called will disconnect the peripheral from the MCU and puts the pins into low power consumption status. RETCODE_OK in the case of success or an error code otherwise.
References VDD_AKU_PORT, VDD_AKU_PIN, AKU_OUT_PORT, AKU_OUT_PIN, RETCODE_OK.
Referenced by NoiseSensor_Disable.
Retcode_T BSP_Mic_AKU340_Enable(void)
Enables the control over the on board AKU340.
This function once called will enable the AKU340 microphone and start the ADC conversion for its channel. RETCODE_OK in the case of success or an error code otherwise.
References micEnabled, Board_WakeupPowerSupply2V5, MIC_AKU340, VDD_AKU_PORT, VDD_AKU_PIN, AKU_OUT_PORT, AKU_OUT_PIN, RETCODE_OK.
Referenced by NoiseSensor_Enable.