XDK_APPLICATION_TEMPLATE
CmdProcessor_T* AppCmdProcessor
Handle to store the main Command processor handle to be used by run-time event driven threads
xTaskHandle AppControllerHandle
OS thread handle for Application controller to be used by run-time blocking threads
Referenced by AppControllerEnable.
void AppController_Init(void *cmdProcessorHandle, uint32_t param2)
Gives control to the Application controller.
This is a template function where the user can write his custom application.Refer interface header for description
References BCDS_UNUSED, RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, CmdProcessor_Enqueue, AppControllerSetup, Retcode_RaiseError, assert.
static void AppControllerEnable(void *param1, uint32_t param2)
To enable the necessary modules for the application.
param1 A generic pointer to any context data structure which will be passed to the function when it is invoked by the command processor. param2 A generic 32 bit value which will be passed to the function when it is invoked by the command processor..
References BCDS_UNUSED, RETCODE_OK, AppControllerFire, TASK_STACK_SIZE_APP_CONTROLLER, NULL, TASK_PRIO_APP_CONTROLLER, AppControllerHandle, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_OUT_OF_RESOURCES, Retcode_RaiseError, assert, Utils_PrintResetCause.
Referenced by AppControllerSetup.
static void AppControllerFire(void *pvParameters)
Responsible for controlling application control flow. Any application logic which is blocking in nature or fixed time dependent can be placed here.
pvParameters FreeRTOS task handle. Could be used if more than one thread is using this function block.
References BCDS_UNUSED, vTaskDelay, XDK_APP_DELAY.
Referenced by AppControllerEnable.
static void AppControllerSetup(void *param1, uint32_t param2)
To setup the necessary modules for the application.
param1 A generic pointer to any context data structure which will be passed to the function when it is invoked by the command processor. param2 A generic 32 bit value which will be passed to the function when it is invoked by the command processor..
References BCDS_UNUSED, RETCODE_OK, CmdProcessor_Enqueue, AppControllerEnable, NULL, Retcode_RaiseError, assert.
Referenced by AppController_Init.
BCDS_MODULE_ID
XDK_APP_DELAY
Referenced by AppControllerFire.