XDK_EXTENSION_PORT
CmdProcessor_T* AppCmdProcessor
Handle to store the main Command processor handle to be reused by ServalPAL thread
xTaskHandle AppControllerHandle
OS thread handle for Application controller
Referenced by AppControllerEnable.
void AppController_Init(void *cmdProcessorHandle, uint32_t param2)
Gives control to the Application controller.
This is a template function where the user can write his custom application.Refer interface header for description
References BCDS_UNUSED, RETCODE_OK, NULL, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER, CmdProcessor_Enqueue, AppControllerSetup, APP_CONTROLLER_STEP1, Retcode_RaiseError, assert.
static void AppControllerEnable(void *param1, uint32_t param2)
To enable the necessary modules for the application.
GPIO pin PA0 as both edge triggered if EXTENSION_PORT_GPIO_FEATURE is enabled param1 Unused param2 Unused
References BCDS_UNUSED, RETCODE_OK, ExtensionGpioExample_InitGpioIntBothEdge, AppControllerFire, TASK_STACK_SIZE_APP_CONTROLLER, NULL, TASK_PRIO_APP_CONTROLLER, AppControllerHandle, RETCODE, RETCODE_SEVERITY_ERROR, RETCODE_OUT_OF_RESOURCES, Retcode_RaiseError, assert, Utils_PrintResetCause.
Referenced by AppControllerSetup.
static void AppControllerFire(void *pvParameters)
Responsible for controlling the XDK Extension Port application control flow.
Validate the I2C communication if EXTENSION_PORT_I2C_FEATURE is enabledValidate the SPI communication if EXTENSION_PORT_SPI_FEATURE is enabledValidate the GPIO feature by configuring pin PA1 as output and toggling it twice if EXTENSION_PORT_GPIO_FEATURE is enabled pvParameters Unused
References BCDS_UNUSED, RETCODE_OK, ExtensionI2cExample_ValidateChip, ExtensionSpiExample_ValidateChip, ExtensionGpioExample_InitGpioOutputMode, vTaskDelay, Retcode_RaiseError, vTaskSuspend, NULL.
Referenced by AppControllerEnable.
static void AppControllerSetup(void *param1, uint32_t param2)
To setup the necessary modules for the application.
BSP for Extension PortExtension Port UART if EXTENSION_PORT_UART_FEATUREExtension Port I2C if EXTENSION_PORT_I2C_FEATUREExtension Port SPI if EXTENSION_PORT_SPI_FEATUREExtension Port GPIO if EXTENSION_PORT_GPIO_FEATURE param1 Unused param2 Unused
References BCDS_UNUSED, RETCODE_OK, ExtensionUartExample_Initialize, ExtensionI2cExample_Initialize, ExtensionSpiExample_Initialize, ExtensionGpioExample_Initialize, CmdProcessor_Enqueue, AppControllerEnable, NULL, Retcode_RaiseError, assert.
Referenced by AppController_Init.
BCDS_MODULE_ID