httpcli.c
CHUNKED_FLAG
Referenced by checkContentField, getChunkedData, HTTPCli_readResponseBody.
CONTENT_BUFLEN
Referenced by contentHandler.
HTTP_PREFIX
Referenced by HTTPCli_initSockAddr.
HTTP_VER
Referenced by getStatus, HTTPCli_sendRequest.
HTTPS_PREFIX
Referenced by HTTPCli_initSockAddr.
INPROGRESS_FLAG
Referenced by sprsend, HTTPCli_connect.
MAX_FIELD_NAME_LEN
Referenced by HTTPCli_getResponseField.
READ_FLAG
Referenced by readLine, HTTPCli_getResponseField.
REDIRECT_FLAG
Referenced by redirect, HTTPCli_sendField.
SEND_BUFLEN
Referenced by sprsend.
STATUS_BUFLEN
Referenced by getStatus.
URI_BUFLEN
Referenced by redirect, HTTPCli_initSockAddr.
typedef void(* ThreadFxnPtr)(HTTPCli_Handle cli))(HTTPCli_Handle cli)
struct sockaddr proxyAddr
Referenced by HTTPCli_connect, HTTPCli_setProxy.
HTTPCli_SecureParams tlsParams
Referenced by startSecureMode, HTTPCli_setSecureParams.
static void asyncThread(HTTPCli_Handle cli)
References getStatus, NULL, contentHandler, threadExit.
Referenced by HTTPCli_sendField.
ssize_t bufferedRecv(HTTPCli_Handle cli, Ssock_Handle ssock, void *buf, size_t len, int flags)
References Ssock_recv.
Referenced by getStatus, readLine, skipLine, HTTPCli_getResponseField, HTTPCli_readRawResponseBody.
static int checkContentField(HTTPCli_Handle cli, char *fname, char *fvalue, bool moreFlag)
References setCliState, CHUNKED_FLAG, NULL.
Referenced by HTTPCli_getResponseField.
static void contentHandler(HTTPCli_Handle cli, int status)
References CONTENT_BUFLEN, NULL, HTTPCli_setResponseFields, HTTPCli_getResponseField, HTTPCli_readResponseBody.
Referenced by asyncThread.
static int getChunkedData(HTTPCli_Handle cli, char *body, int len, bool *moreFlag)
References getCliState, CHUNKED_FLAG, readLine, NULL, HTTPCli_readRawResponseBody.
Referenced by HTTPCli_readResponseBody.
static bool getCliState(HTTPCli_Handle cli, int flag)
Referenced by getChunkedData, sprsend, HTTPCli_connect, HTTPCli_sendField, HTTPCli_getResponseField, HTTPCli_readResponseBody.
static int getStatus(HTTPCli_Handle cli)
References STATUS_BUFLEN, HTTP_VER, bufferedRecv, readLine, skipLine, NULL, redirect.
Referenced by asyncThread, HTTPCli_getResponseStatus.
int HTTPCli_connect(HTTPCli_Struct *cli, const struct sockaddr *addr, int flags, const HTTPCli_Params *params)
References NULL, proxyAddr, getCliState, INPROGRESS_FLAG, SL_SEC_SOCKET, isValidSocket, Ssock_construct, HTTPCli_disconnect, startSecureMode, setCliState.
void HTTPCli_construct(HTTPCli_Handle cli)
References NULL.
Referenced by HTTPCli_create.
HTTPCli_Handle HTTPCli_create()
References NULL, HTTPCli_construct.
void HTTPCli_delete(HTTPCli_Handle cli)
References NULL, HTTPCli_destruct.
void HTTPCli_destruct(HTTPCli_Struct *cli)
References NULL.
Referenced by HTTPCli_delete, HTTPCli_disconnect.
void HTTPCli_disconnect(HTTPCli_Struct *cli)
References NULL, Ssock_getSocket, Ssock_destruct, HTTPCli_destruct.
Referenced by HTTPCli_connect.
int HTTPCli_getResponseField(HTTPCli_Handle cli, char *body, int len, bool *moreFlag)
References MAX_FIELD_NAME_LEN, NULL, getCliState, READ_FLAG, bufferedRecv, skipLine, lookUpResponseFields, readLine, checkContentField.
Referenced by contentHandler, redirect.
int HTTPCli_getResponseStatus(HTTPCli_Handle cli)
References NULL, getStatus.
int HTTPCli_initSockAddr(struct sockaddr *addr, const char *uri, int flags)
References URI_BUFLEN, NULL, stringCompareByLen, HTTP_PREFIX, HTTPS_PREFIX.
int HTTPCli_readRawResponseBody(HTTPCli_Handle cli, char *body, int len)
References NULL, bufferedRecv.
Referenced by getChunkedData, HTTPCli_readResponseBody.
int HTTPCli_readResponseBody(HTTPCli_Handle cli, char *body, int len, bool *moreFlag)
References NULL, getCliState, CHUNKED_FLAG, getChunkedData, HTTPCli_readRawResponseBody.
Referenced by contentHandler, redirect.
int HTTPCli_sendField(HTTPCli_Handle cli, const char *name, const char *value, bool lastFlag)
References NULL, sprsend, getCliState, REDIRECT_FLAG, threadCreate, asyncThread.
Referenced by HTTPCli_sendRequest.
int HTTPCli_sendRequest(HTTPCli_Handle cli, const char *method, const char *requestURI, bool moreFlag)
References NULL, sprsend, HTTP_VER, HTTPCli_sendField, value.
int HTTPCli_sendRequestBody(HTTPCli_Handle cli, const char *body, int len)
References NULL, Ssock_send.
void HTTPCli_setProxy(const struct sockaddr *addr)
References proxyAddr.
HTTPCli_Field* HTTPCli_setRequestFields(HTTPCli_Handle cli, const HTTPCli_Field *fields)
References NULL.
char** HTTPCli_setResponseFields(HTTPCli_Handle cli, const char *fields[])
References NULL.
Referenced by contentHandler, redirect.
void HTTPCli_setSecureParams(HTTPCli_SecureParams *sparams)
References NULL, tlsParams.
static bool isValidSocket(int skt)
Referenced by HTTPCli_connect.
static int lookUpResponseFields(HTTPCli_Handle cli, char *field)
References NULL, stringCompare.
Referenced by HTTPCli_getResponseField.
static int readLine(HTTPCli_Handle cli, char *line, int len, bool *moreFlag)
References setCliState, READ_FLAG, bufferedRecv.
Referenced by getChunkedData, getStatus, HTTPCli_getResponseField.
static int redirect(HTTPCli_Handle cli, int status)
References URI_BUFLEN, NULL, HTTPCli_setResponseFields, HTTPCli_getResponseField, HTTPCli_readResponseBody, setCliState, REDIRECT_FLAG.
Referenced by getStatus.
static void setCliState(HTTPCli_Handle cli, int flag, bool value)
Referenced by checkContentField, readLine, redirect, HTTPCli_connect.
static int skipLine(HTTPCli_Handle cli)
References bufferedRecv.
Referenced by getStatus, HTTPCli_getResponseField.
static int sprsend(HTTPCli_Handle cli, const char *fmt,...)
References SEND_BUFLEN, getCliState, INPROGRESS_FLAG, Ssock_send.
Referenced by HTTPCli_sendRequest, HTTPCli_sendField.
static int startSecureMode(HTTPCli_Handle cli)
References tlsParams, NULL, Ssock_getSocket, Ssock_startSecure, SL_SOL_SOCKET, SL_SO_SECMETHOD, SL_SO_SECURE_MASK, SL_SO_SECURE_FILES_CA_FILE_NAME, SL_SO_SECURE_FILES_PRIVATE_KEY_FILE_NAME, SL_SO_SECURE_FILES_CERTIFICATE_FILE_NAME, SL_SO_SECURE_FILES_DH_KEY_FILE_NAME.
Referenced by HTTPCli_connect.
static int stringCompare(const char *str1, const char *str2)
References toLowerCase.
Referenced by lookUpResponseFields.
static int stringCompareByLen(const char *str1, const char *str2, int len)
References toLowerCase.
Referenced by HTTPCli_initSockAddr.
static int threadCreate(ThreadFxnPtr fxn, void *cli)
References NULL, osi_TaskCreate.
Referenced by HTTPCli_sendField.
static void threadExit()
References NULL, osi_TaskDelete.
Referenced by asyncThread.
static unsigned char toLowerCase(unsigned char c)
Referenced by stringCompare, stringCompareByLen.