netapp.c
NETAPP_MDNS_MAX_SERVICE_NAME_AND_TEXT_LENGTH
NETAPP_MDNS_OPTIONS_ADD_SERVICE_BIT
_SlPingStatus_e
_SlReturnVal_t _sl_HandleAsync_DnsGetHostByAddr(void *pVoidBuf)
References SL_TRACE0, SL_RET_CODE_OK.
_SlReturnVal_t _sl_HandleAsync_DnsGetHostByName(void *pVoidBuf)
References _SL_RESP_ARGS_START, SL_DRV_PROTECTION_OBJ_LOCK_FOREVER, VERIFY_SOCKET_CB, NULL, g_pCB, _SlDriverCb_t::ObjPool, _SlDriverCb_t::FunctionParams, _SlFunctionParams_t::AsyncExt, AsyncExt_t::ActionIndex, _SlPoolObj_t::pRespArgs, _SlPoolObj_t::AdditionalData, SL_NETAPP_FAMILY_MASK, sl_Memcpy, SL_DRV_SYNC_OBJ_SIGNAL, _SlPoolObj_t::SyncObj, SL_DRV_PROTECTION_OBJ_UNLOCK, SL_RET_CODE_OK.
Referenced by _SlDrvNetAppEventHandler.
_SlReturnVal_t _sl_HandleAsync_DnsGetHostByService(void *pVoidBuf)
References _u16, _SL_RESP_ARGS_START, VERIFY_SOCKET_CB, NULL, g_pCB, _SlDriverCb_t::ObjPool, _SlDriverCb_t::FunctionParams, _SlFunctionParams_t::AsyncExt, AsyncExt_t::ActionIndex, _SlPoolObj_t::pRespArgs, _SlPoolObj_t::AdditionalData, SL_NETAPP_FAMILY_MASK, SL_RET_CODE_OK, _GetHostByServiceIPv4AsyncResponse_t::TextLen, _GetHostByServiceAsyncResponse_t::out_pAddr, _GetHostByServiceIPv4AsyncResponse_t::Address, _GetHostByServiceAsyncResponse_t::out_pPort, _GetHostByServiceIPv4AsyncResponse_t::Port, _GetHostByServiceAsyncResponse_t::Status, _i16, _GetHostByServiceIPv4AsyncResponse_t::Status, _GetHostByServiceAsyncResponse_t::inout_TextLen, sl_Memcpy, _GetHostByServiceAsyncResponse_t::out_pText, _i8, SL_DRV_SYNC_OBJ_SIGNAL, _SlPoolObj_t::SyncObj.
Referenced by _SlDrvNetAppEventHandler.
_SlReturnVal_t _sl_HandleAsync_PingResponse(void *pVoidBuf)
References _SL_RESP_ARGS_START, pPingCallBackFunc, CopyPingResultsToReport, SL_DRV_PROTECTION_OBJ_LOCK_FOREVER, VERIFY_SOCKET_CB, NULL, g_pCB, _SlDriverCb_t::ObjPool, _SlDriverCb_t::FunctionParams, _SlFunctionParams_t::AsyncExt, AsyncExt_t::ActionIndex, _SlPoolObj_t::pRespArgs, sl_Memcpy, SL_DRV_SYNC_OBJ_SIGNAL, _SlPoolObj_t::SyncObj, SL_DRV_PROTECTION_OBJ_UNLOCK, SL_RET_CODE_OK.
Referenced by _SlDrvClassifyRxMsg, _SlDrvNetAppEventHandler.
_SlReturnVal_t _SlDrvNetAppEventHandler(void *pArgs)
References _SlResponseHeader_t::GenHeader, _SlGenericHeader_t::Opcode, SL_OPCODE_NETAPP_DNSGETHOSTBYNAMEASYNCRESPONSE, SL_OPCODE_NETAPP_DNSGETHOSTBYNAMEASYNCRESPONSE_V6, _sl_HandleAsync_DnsGetHostByName, SL_OPCODE_NETAPP_MDNSGETHOSTBYSERVICEASYNCRESPONSE, SL_OPCODE_NETAPP_MDNSGETHOSTBYSERVICEASYNCRESPONSE_V6, _sl_HandleAsync_DnsGetHostByService, SL_OPCODE_NETAPP_PINGREPORTREQUESTRESPONSE, _sl_HandleAsync_PingResponse, SL_OPCODE_NETAPP_HTTPGETTOKENVALUE, _u8, _SL_RESP_ARGS_START, SlHttpServerResponse_t::Response, SL_NETAPP_HTTPSETTOKENVALUE, SlHttpServerResponse_t::ResponseData, SlHttpServerResponsedata_u::token_value, _slHttpServerString_t::len, MAX_TOKEN_VALUE_LEN, _slHttpServerString_t::data, MAX_TOKEN_NAME_LEN, SlHttpServerEvent_t::Event, SL_NETAPP_HTTPGETTOKENVALUE_EVENT, SlHttpServerEvent_t::EventData, SlHttpServerEventData_u::httpTokenName, _sl_NetAppHttpServerGetToken_t::token_name_len, _slHttpServerData_t::token_name, _slHttpServerData_t::value_len, _slHttpServerData_t::name_len, _slHttpServerData_t::token_value, SL_OPCODE_NETAPP_HTTPPOSTTOKENVALUE, SL_NETAPP_HTTPPOSTTOKENVALUE_EVENT, SlHttpServerEventData_u::httpPostData, _slHttpServerPostData_t::action, _sl_NetAppHttpServerPostToken_t::post_action_len, _slHttpServerPostData_t::token_name, _sl_NetAppHttpServerPostToken_t::token_name_len, _slHttpServerPostData_t::token_value, _sl_NetAppHttpServerPostToken_t::token_value_len, SL_NETAPP_RESPONSE_NONE, SL_ERROR_TRACE2, VERIFY_PROTOCOL, SL_RET_CODE_OK.
Referenced by _SlDrvClassifyRxMsg.
static void CopyPingResultsToReport(_PingReportResponse_t *pResults, SlPingReport_t *pReport)
References SlPingReport_t::PacketsSent, _PingReportResponse_t::numSendsPings, SlPingReport_t::PacketsReceived, _PingReportResponse_t::numSuccsessPings, SlPingReport_t::MinRoundTime, _PingReportResponse_t::rttMin, SlPingReport_t::MaxRoundTime, _PingReportResponse_t::rttMax, SlPingReport_t::AvgRoundTime, _PingReportResponse_t::rttAvg, SlPingReport_t::TestTime, _PingReportResponse_t::testTime.
Referenced by _sl_HandleAsync_PingResponse.
_i16 sl_NetAppMDNSRegisterUnregisterService(const _i8 *pServiceName, const _u8 ServiceNameLen, const _i8 *pText, const _u8 TextLen, const _u16 Port, const _u32 TTL, const _u32 Options)