osi.h
OSI_ABORTED
OSI_EVENT_OPEARTION_FAILURE
OSI_EVENTS_IN_USE
OSI_FAILURE
OSI_INVALID_PARAMS
Referenced by osi_SyncObjCreate, osi_SyncObjDelete, osi_SyncObjSignal, osi_SyncObjSignalFromISR, osi_SyncObjWait, osi_SyncObjClear, osi_LockObjCreate, osi_LockObjLock, osi_LockObjUnlock, osi_MsgQCreate, osi_MsgQDelete, osi_MsgQWrite, osi_MsgQRead.
OSI_MEMORY_ALLOCATION_FAILURE
OSI_NO_WAIT
OSI_OK
OSI_OPERATION_FAILED
Referenced by osi_SyncObjCreate, osi_SyncObjWait, osi_SyncObjClear, osi_LockObjCreate, osi_TaskCreate, osi_LockObjLock, osi_LockObjUnlock, osi_Spawn, VStartSimpleLinkSpawnTask, osi_MsgQCreate, osi_MsgQWrite, osi_MsgQRead.
OSI_TIMEOUT
OSI_WAIT_FOREVER
Referenced by osi_MsgQRead.
typedef void* OsiLockObj_t
type definition for a locking object container
Locking object are used to protect a resource from mutual accesses of two or more threads. The locking object should support re-entrant locks by a signal thread. This object is generally implemented by mutex semaphoreOn each porting or platform the type could be whatever is needed - integer, structure etc.
typedef void* OsiMsgQ_t
typedef long OsiReturnVal_e
typedef void* OsiSyncObj_t
type definition for a sync object container
Sync object is object used to synchronize between two threads or thread and interrupt handler. One thread is waiting on the object and the other thread send a signal, which then release the waiting thread. The signal must be able to be sent from interrupt context. This object is generally implemented by binary semaphore or events.On each porting or platform the type could be whatever is needed - integer, structure etc.
typedef void* OsiTaskHandle
typedef unsigned long OsiTime_t
type definition for a time value
On each porting or platform the type could be whatever is needed - integer, pointer to structure etc.
typedef void(* P_OSI_EVENT_HANDLER)(void *pValue))(void *pValue)
typedef void(* P_OSI_INTR_ENTRY)(void))(void)
typedef void(* P_OSI_SPAWN_ENTRY)(void *pValue))(void *pValue)
type definition for a spawn entry callback
the spawn mechanism enable to run a function on different context. This mechanism allow to transfer the execution context from interrupt context to thread context or changing the context from an unknown user thread to general context. The implementation of the spawn mechanism depends on the user's system requirements and could varies from implementation of serialized execution using single thread to creating thread per callThe stack size of the execution thread must be at least of TBD bytes!
typedef void(* P_OSI_TASK_ENTRY)(void *pValue))(void *pValue)
void* xSimpleLinkSpawnQueue
Referenced by osi_Spawn, vSimpleLinkSpawnTask, VStartSimpleLinkSpawnTask, VDeleteSimpleLinkSpawnTask.
void mem_copy(void *pDst, void *pSrc, size_t Size)
Copy Memory.
pDst - Pointer to the Destination Buffer pSrc - Pointer to the Source Buffer Size - Size of the memory to be copied void Copy Memory. pDst - pointer to the destination pSrc - pointer to the source Size - Size of the memory which needs to be copy - void
void mem_Free(void *pMem)
Deallocates Memory.
pMem - Pointer to the Buffer to be freed void Deallocates Memory. pMem - pointer to the memory which needs to be freed - void
References vPortFree.
void* mem_Malloc(unsigned long Size)
Allocates Memory on Heap.
Size - Size of the Buffer to be allocated Allocates Memory on Heap. Size - size of memory to alloc in bytes - void *
References pvPortMalloc.
void mem_set(void *pBuf, int Val, size_t Size)
Set Memory.
pBuf - Pointer to the Buffer Val - Value to be set Size - Size of the memory to be set Set Memory. pBuf - pointer to the memory to be fill Val - Value to be fill Size - Size of the memory which needs to be fill - void
void osi_ContextRestore()
This function used to retrieve the context after sleep.
void void This function used to retrieve the context after sleep. void - void
void osi_ContextSave()
This function used to save the os context before sleep.
void void This function used to save the os context before sleep. void - void
unsigned long osi_EnterCritical(void)
Enter Critical Section.
Enter Critical Section. void - void
References portENTER_CRITICAL.
void osi_ExitCritical(unsigned long ulKey)
Exit Critical Section.
Exit Critical Section. void - void
References portENTER_CRITICAL.
void osi_InterruptDeRegister(int iIntrNum)
This function De-registers an interrupt in NVIC table.
iIntrNum - Interrupt number to register pEntry - Pointer to the interrupt handler upon successful creation the function should return Positive number Otherwise, a negative value indicating the error code shall be returned
OsiReturnVal_e osi_InterruptRegister(int iIntrNum, P_OSI_INTR_ENTRY pEntry, unsigned char ucPriority)
This function registers an interrupt in NVIC table.
The sync object is used for synchronization between different thread or ISR and a thread. iIntrNum - Interrupt number to register pEntry - Pointer to the interrupt handler upon successful creation the function should return 0 Otherwise, a negative value indicating the error code shall be returned
OsiReturnVal_e osi_LockObjCreate(OsiLockObj_t *pLockObj)
This function creates a locking object.
The locking object is used for protecting a shared resources between different threads. pLockObj - pointer to the locking object control block upon successful creation the function should return 0 Otherwise, a negative value indicating the error code shall be returned
References NULL, OSI_INVALID_PARAMS, OSI_OK, OSI_OPERATION_FAILED.
OsiReturnVal_e osi_LockObjDelete(OsiLockObj_t *pLockObj)
This function deletes a locking object.
pLockObj - pointer to the locking object control block upon successful deletion the function should return 0 Otherwise, a negative value indicating the error code shall be returned
References vSemaphoreDelete, OSI_OK.
OsiReturnVal_e osi_LockObjLock(OsiLockObj_t *pLockObj, OsiTime_t Timeout)
This function locks a locking object.
All other threads that call this function before this thread calls the osi_LockObjUnlock would be suspended pLockObj - pointer to the locking object control block Timeout - numeric value specifies the maximum number of mSec to stay suspended while waiting for the locking object Currently, the simple link driver uses only two values: OSI_WAIT_FOREVEROSI_NO_WAIT upon successful reception of the locking object the function should return 0 Otherwise, a negative value indicating the error code shall be returned
References NULL, OSI_INVALID_PARAMS, xSemaphoreTake, portTICK_PERIOD_MS, OSI_OK, OSI_OPERATION_FAILED.
OsiReturnVal_e osi_LockObjUnlock(OsiLockObj_t *pLockObj)
This function unlock a locking object.
pLockObj - pointer to the locking object control block upon successful unlocking the function should return 0 Otherwise, a negative value indicating the error code shall be returned
References NULL, OSI_INVALID_PARAMS, xSemaphoreGive, OSI_OK, OSI_OPERATION_FAILED.
OsiReturnVal_e osi_MsgQCreate(OsiMsgQ_t *pMsgQ, char *pMsgQName, unsigned long MsgSize, unsigned long MaxMsgs)
This function is used to create the MsgQ.
pMsgQ - pointer to the message queue pMsgQName - msg queue name MsgSize - size of message on the queue MaxMsgs - max. number of msgs that the queue can hold - OsiReturnVal_e
References NULL, OSI_INVALID_PARAMS, OSI_OPERATION_FAILED, OSI_OK.
OsiReturnVal_e osi_MsgQDelete(OsiMsgQ_t *pMsgQ)
This function is used to delete the MsgQ.
pMsgQ - pointer to the message queue - OsiReturnVal_e
References NULL, OSI_INVALID_PARAMS, vQueueDelete, OSI_OK.
OsiReturnVal_e osi_MsgQRead(OsiMsgQ_t *pMsgQ, void *pMsg, OsiTime_t Timeout)
This function is used to read data from the MsgQ.
pMsgQ - pointer to the message queue pMsg - pointer to the Msg strut to read into Timeout - timeout to wait for the Msg to be available - OsiReturnVal_e
References NULL, OSI_INVALID_PARAMS, OSI_WAIT_FOREVER, portMAX_DELAY, xQueueReceive, OSI_OK, OSI_OPERATION_FAILED.
OsiReturnVal_e osi_MsgQWrite(OsiMsgQ_t *pMsgQ, void *pMsg, OsiTime_t Timeout)
This function is used to write data to the MsgQ.
pMsgQ - pointer to the message queue pMsg - pointer to the Msg strut to read into Timeout - timeout to wait for the Msg to be available - OsiReturnVal_e
References NULL, OSI_INVALID_PARAMS, xQueueSendFromISR, xHigherPriorityTaskWoken, taskYIELD, OSI_OK, OSI_OPERATION_FAILED.
void osi_Sleep(unsigned int MilliSecs)
This function used to suspend the task for the specified number of milli secs.
MilliSecs - Time in millisecs to suspend the task void MilliSecs - Time in millisecs to suspend the task - void
References portTICK_PERIOD_MS, vTaskDelay.
OsiReturnVal_e osi_Spawn(P_OSI_SPAWN_ENTRY pEntry, void *pValue, unsigned long flags)
This function call the pEntry callback from a different context.
pEntry - pointer to the entry callback function pValue - pointer to any type of memory structure that would be passed to pEntry callback from the execution thread. flags - execution flags - reserved for future usage upon successful registration of the spawn the function should return 0 (the function is not blocked till the end of the execution of the function and could be returned before the execution is actually completed) Otherwise, a negative value indicating the error code shall be returned
References tSimpleLinkSpawnMsg::pEntry, tSimpleLinkSpawnMsg::pValue, xHigherPriorityTaskWoken, xQueueSendFromISR, xSimpleLinkSpawnQueue, taskYIELD, OSI_OK, OSI_OPERATION_FAILED.
void osi_start()
This function starts the OS Scheduler.
- void - void This function starts the OS Scheduler. void - void
References vTaskStartScheduler.
OsiReturnVal_e osi_SyncObjClear(OsiSyncObj_t *pSyncObj)
This function clears a sync object.
pSyncObj - pointer to the sync object control block upon successful clearing the function should return 0 Otherwise, a negative value indicating the error code shall be returned
References NULL, OSI_INVALID_PARAMS, OSI_OK, osi_SyncObjWait, OSI_OPERATION_FAILED.
OsiReturnVal_e osi_SyncObjCreate(OsiSyncObj_t *pSyncObj)
This function creates a sync object.
The sync object is used for synchronization between different thread or ISR and a thread. pSyncObj - pointer to the sync object control block upon successful creation the function should return 0 Otherwise, a negative value indicating the error code shall be returned
References NULL, OSI_INVALID_PARAMS, OSI_OK, OSI_OPERATION_FAILED.
OsiReturnVal_e osi_SyncObjDelete(OsiSyncObj_t *pSyncObj)
This function deletes a sync object.
pSyncObj - pointer to the sync object control block upon successful deletion the function should return 0 Otherwise, a negative value indicating the error code shall be returned
References NULL, OSI_INVALID_PARAMS, vSemaphoreDelete, OSI_OK.
OsiReturnVal_e osi_SyncObjSignal(OsiSyncObj_t *pSyncObj)
This function generates a sync signal for the object.
All suspended threads waiting on this sync object are resumed pSyncObj - pointer to the sync object control block upon successful signalling the function should return 0 Otherwise, a negative value indicating the error code shall be returned the function could be called from ISR context All suspended threads waiting on this sync object are resumed pSyncObj - pointer to the sync object control block upon successful signaling the function should return 0 Otherwise, a negative value indicating the error code shall be returned the function could be called from ISR context
References NULL, OSI_INVALID_PARAMS, xSemaphoreGive, OSI_OK.
OsiReturnVal_e osi_SyncObjSignalFromISR(OsiSyncObj_t *pSyncObj)
This function generates a sync signal for the object. from ISR context.
All suspended threads waiting on this sync object are resumed pSyncObj - pointer to the sync object control block upon successful signalling the function should return 0 Otherwise, a negative value indicating the error code shall be returned the function is called from ISR context This function generates a sync signal for the object. from ISR context.All suspended threads waiting on this sync object are resumed pSyncObj - pointer to the sync object control block upon successful signalling the function should return 0 Otherwise, a negative value indicating the error code shall be returned the function is called from ISR context
References NULL, OSI_INVALID_PARAMS, xHigherPriorityTaskWoken, xSemaphoreGiveFromISR, taskYIELD, OSI_OK.
OsiReturnVal_e osi_SyncObjWait(OsiSyncObj_t *pSyncObj, OsiTime_t Timeout)
This function waits for a sync signal of the specific sync object.
pSyncObj - pointer to the sync object control block Timeout - numeric value specifies the maximum number of mSec to stay suspended while waiting for the sync signal Currently, the simple link driver uses only two values: OSI_WAIT_FOREVEROSI_NO_WAIT upon successful reception of the signal within the timeout window return 0 Otherwise, a negative value indicating the error code shall be returned
References NULL, OSI_INVALID_PARAMS, xSemaphoreTake, portTICK_PERIOD_MS, OSI_OK, OSI_OPERATION_FAILED.
Referenced by osi_SyncObjClear.
OsiReturnVal_e osi_TaskCreate(P_OSI_TASK_ENTRY pEntry, const signed char *const pcName, unsigned short usStackDepth, void *pvParameters, unsigned long uxPriority, OsiTaskHandle *pTaskHandle)
This function call the pEntry callback from a different context.
pEntry - pointer to the entry callback function pValue - pointer to any type of memory structure that would be passed to pEntry callback from the execution thread. flags - execution flags - reserved for future usage upon successful registration of the spawn the function should return 0 (the function is not blocked till the end of the execution of the function and could be returned before the execution is actually completed) Otherwise, a negative value indicating the error code shall be returned This function creates a Task.Creates a new Task and add it to the last of tasks that are ready to run pEntry - pointer to the Task Function pcName - Task Name String usStackDepth - Stack Size Stack Size in 32-bit long words pvParameters - pointer to structure to be passed to the Task Function uxPriority - Task Priority upon successful unlocking the function should return 0 Otherwise, a negative value indicating the error code shall be returned This function call the pEntry callback from a different context.Creates a new Task and add it to the last of tasks that are ready to run pEntry - pointer to the Task Function pcName - Task Name String usStackDepth - Stack Size in bytes pvParameters - pointer to structure to be passed to the Task Function uxPriority - Task Priority upon successful creation the function should return 0 Otherwise, a negative value indicating the error code shall be returned
References portSTACK_TYPE, portBASE_TYPE, OSI_OK, OSI_OPERATION_FAILED.
Referenced by threadCreate.
void osi_TaskDelete(OsiTaskHandle *pTaskHandle)
This function Deletes a Task.
Deletes a Task and remove it from list of running task pTaskHandle - Task Handle
References vTaskDelete.
Referenced by threadExit.
unsigned long osi_TaskDisable(void)
This function used to disable the tasks.
- void - Key with the suspended tasks
References vTaskSuspendAll, OSI_OK.
void osi_TaskEnable(unsigned long)
This function used to enable all tasks.
unsigned long - void This function used to enable all tasks. key - returned from suspend tasks - void
References xTaskResumeAll.
void VDeleteSimpleLinkSpawnTask(void)
This is the API to delete SL spawn task and delete the SL queue.
none void
References xSimpleLinkSpawnTaskHndl, vTaskDelete, xSimpleLinkSpawnQueue, vQueueDelete.
OsiReturnVal_e VStartSimpleLinkSpawnTask(unsigned portBASE_TYPE uxPriority)
This is the API to create SL spawn task and create the SL queue.
uxPriority - task priority void
References xSimpleLinkSpawnQueue, slQUEUE_SIZE, OSI_OPERATION_FAILED, vSimpleLinkSpawnTask, portCHAR, portSTACK_TYPE, NULL, xSimpleLinkSpawnTaskHndl, OSI_OK.