osi_freertos.c
slQUEUE_SIZE
Referenced by VStartSimpleLinkSpawnTask.
portBASE_TYPE xHigherPriorityTaskWoken
Referenced by AppCallback, osi_SyncObjSignalFromISR, osi_Spawn, osi_MsgQWrite, bmaIsrCallback, maxIsrCallback.
QueueHandle_t xSimpleLinkSpawnQueue
Referenced by osi_Spawn, vSimpleLinkSpawnTask, VStartSimpleLinkSpawnTask, VDeleteSimpleLinkSpawnTask.
TaskHandle_t xSimpleLinkSpawnTaskHndl
Referenced by VStartSimpleLinkSpawnTask, VDeleteSimpleLinkSpawnTask.
void mem_copy(void *pDst, void *pSrc, size_t Size)
This function call the memcopy function.
Copy Memory. pDst - pointer to the destination pSrc - pointer to the source Size - Size of the memory which needs to be copy - void
void mem_Free(void *pMem)
This function to call the memory de-allocation function of the FREERTOS.
Deallocates Memory. pMem - pointer to the memory which needs to be freed - void
References vPortFree.
void* mem_Malloc(unsigned long Size)
This function to call the memory de-allocation function of the FREERTOS.
Allocates Memory on Heap. Size - size of memory to alloc in bytes - void *
References pvPortMalloc.
void mem_set(void *pBuf, int Val, size_t Size)
This function call the memset function.
Set Memory. pBuf - pointer to the memory to be fill Val - Value to be fill Size - Size of the memory which needs to be fill - void
void osi_ContextRestore()
This function used to restore the OS context after sleep.
This function used to retrieve the context after sleep. void - void
void osi_ContextSave()
This function used to save the OS context before sleep.
This function used to save the os context before sleep. void - void
unsigned long osi_EnterCritical(void)
This function use to entering into critical section.
Enter Critical Section. void - void
References portENTER_CRITICAL.
void osi_ExitCritical(unsigned long ulKey)
This function use to exit critical section.
Exit Critical Section. void - void
References portENTER_CRITICAL.
OsiReturnVal_e osi_LockObjCreate(OsiLockObj_t *pLockObj)
This function creates a locking object.
The locking object is used for protecting a shared resources between different threads. pLockObj - pointer to the locking object control block upon successful creation the function should return 0 Otherwise, a negative value indicating the error code shall be returned
References NULL, OSI_INVALID_PARAMS, OSI_OK, OSI_OPERATION_FAILED.
OsiReturnVal_e osi_LockObjDelete(OsiLockObj_t *pLockObj)
This function deletes a locking object.
pLockObj - pointer to the locking object control block upon successful deletion the function should return 0 Otherwise, a negative value indicating the error code shall be returned
References vSemaphoreDelete, OSI_OK.
OsiReturnVal_e osi_LockObjLock(OsiLockObj_t *pLockObj, OsiTime_t Timeout)
This function locks a locking object.
All other threads that call this function before this thread calls the osi_LockObjUnlock would be suspended pLockObj - pointer to the locking object control block Timeout - numeric value specifies the maximum number of mSec to stay suspended while waiting for the locking object Currently, the simple link driver uses only two values: OSI_WAIT_FOREVEROSI_NO_WAIT upon successful reception of the locking object the function should return 0 Otherwise, a negative value indicating the error code shall be returned
References NULL, OSI_INVALID_PARAMS, xSemaphoreTake, portTICK_PERIOD_MS, OSI_OK, OSI_OPERATION_FAILED.
OsiReturnVal_e osi_LockObjUnlock(OsiLockObj_t *pLockObj)
This function unlock a locking object.
pLockObj - pointer to the locking object control block upon successful unlocking the function should return 0 Otherwise, a negative value indicating the error code shall be returned
References NULL, OSI_INVALID_PARAMS, xSemaphoreGive, OSI_OK, OSI_OPERATION_FAILED.
OsiReturnVal_e osi_MsgQCreate(OsiMsgQ_t *pMsgQ, char *pMsgQName, unsigned long MsgSize, unsigned long MaxMsgs)
This function is used to create the MsgQ.
pMsgQ - pointer to the message queue pMsgQName - msg queue name MsgSize - size of message on the queue MaxMsgs - max. number of msgs that the queue can hold - OsiReturnVal_e
References NULL, OSI_INVALID_PARAMS, OSI_OPERATION_FAILED, OSI_OK.
OsiReturnVal_e osi_MsgQDelete(OsiMsgQ_t *pMsgQ)
This function is used to delete the MsgQ.
pMsgQ - pointer to the message queue - OsiReturnVal_e
References NULL, OSI_INVALID_PARAMS, vQueueDelete, OSI_OK.
OsiReturnVal_e osi_MsgQRead(OsiMsgQ_t *pMsgQ, void *pMsg, OsiTime_t Timeout)
This function is used to read data from the MsgQ.
pMsgQ - pointer to the message queue pMsg - pointer to the Msg strut to read into Timeout - timeout to wait for the Msg to be available - OsiReturnVal_e
References NULL, OSI_INVALID_PARAMS, OSI_WAIT_FOREVER, portMAX_DELAY, xQueueReceive, OSI_OK, OSI_OPERATION_FAILED.
OsiReturnVal_e osi_MsgQWrite(OsiMsgQ_t *pMsgQ, void *pMsg, OsiTime_t Timeout)
This function is used to write data to the MsgQ.
pMsgQ - pointer to the message queue pMsg - pointer to the Msg strut to read into Timeout - timeout to wait for the Msg to be available - OsiReturnVal_e
References NULL, OSI_INVALID_PARAMS, xQueueSendFromISR, xHigherPriorityTaskWoken, taskYIELD, OSI_OK, OSI_OPERATION_FAILED.
void osi_Sleep(unsigned int MilliSecs)
This function used to suspend the task for the specified number of milli secs.
MilliSecs - Time in millisecs to suspend the task - void
References portTICK_PERIOD_MS, vTaskDelay.
OsiReturnVal_e osi_Spawn(P_OSI_SPAWN_ENTRY pEntry, void *pValue, unsigned long flags)
This function call the pEntry callback from a different context.
pEntry - pointer to the entry callback function pValue - pointer to any type of memory structure that would be passed to pEntry callback from the execution thread. flags - execution flags - reserved for future usage upon successful registration of the spawn the function should return 0 (the function is not blocked till the end of the execution of the function and could be returned before the execution is actually completed) Otherwise, a negative value indicating the error code shall be returned
References tSimpleLinkSpawnMsg::pEntry, tSimpleLinkSpawnMsg::pValue, xHigherPriorityTaskWoken, xQueueSendFromISR, xSimpleLinkSpawnQueue, taskYIELD, OSI_OK, OSI_OPERATION_FAILED.
void osi_start()
This function used to start the scheduler.
This function starts the OS Scheduler. void - void
References vTaskStartScheduler.
OsiReturnVal_e osi_SyncObjClear(OsiSyncObj_t *pSyncObj)
This function clears a sync object.
pSyncObj - pointer to the sync object control block upon successful clearing the function should return 0 Otherwise, a negative value indicating the error code shall be returned
References NULL, OSI_INVALID_PARAMS, OSI_OK, osi_SyncObjWait, OSI_OPERATION_FAILED.
OsiReturnVal_e osi_SyncObjCreate(OsiSyncObj_t *pSyncObj)
This function creates a sync object.
The sync object is used for synchronization between different thread or ISR and a thread. pSyncObj - pointer to the sync object control block upon successful creation the function should return 0 Otherwise, a negative value indicating the error code shall be returned
References NULL, OSI_INVALID_PARAMS, OSI_OK, OSI_OPERATION_FAILED.
OsiReturnVal_e osi_SyncObjDelete(OsiSyncObj_t *pSyncObj)
This function deletes a sync object.
pSyncObj - pointer to the sync object control block upon successful deletion the function should return 0 Otherwise, a negative value indicating the error code shall be returned
References NULL, OSI_INVALID_PARAMS, vSemaphoreDelete, OSI_OK.
OsiReturnVal_e osi_SyncObjSignal(OsiSyncObj_t *pSyncObj)
This function generates a sync signal for the object.
All suspended threads waiting on this sync object are resumed pSyncObj - pointer to the sync object control block upon successful signaling the function should return 0 Otherwise, a negative value indicating the error code shall be returned the function could be called from ISR context
References NULL, OSI_INVALID_PARAMS, xSemaphoreGive, OSI_OK.
OsiReturnVal_e osi_SyncObjSignalFromISR(OsiSyncObj_t *pSyncObj)
This function generates a sync signal for the object from ISR context.
This function generates a sync signal for the object. from ISR context.All suspended threads waiting on this sync object are resumed pSyncObj - pointer to the sync object control block upon successful signalling the function should return 0 Otherwise, a negative value indicating the error code shall be returned the function is called from ISR context
References NULL, OSI_INVALID_PARAMS, xHigherPriorityTaskWoken, xSemaphoreGiveFromISR, taskYIELD, OSI_OK.
OsiReturnVal_e osi_SyncObjWait(OsiSyncObj_t *pSyncObj, OsiTime_t Timeout)
This function waits for a sync signal of the specific sync object.
pSyncObj - pointer to the sync object control block Timeout - numeric value specifies the maximum number of mSec to stay suspended while waiting for the sync signal Currently, the simple link driver uses only two values: OSI_WAIT_FOREVEROSI_NO_WAIT upon successful reception of the signal within the timeout window return 0 Otherwise, a negative value indicating the error code shall be returned
References NULL, OSI_INVALID_PARAMS, xSemaphoreTake, portTICK_PERIOD_MS, OSI_OK, OSI_OPERATION_FAILED.
Referenced by osi_SyncObjClear.
OsiReturnVal_e osi_TaskCreate(P_OSI_TASK_ENTRY pEntry, const signed char *const pcName, unsigned short usStackDepth, void *pvParameters, unsigned long uxPriority, OsiTaskHandle *pTaskHandle)
This function creates a Task.
This function call the pEntry callback from a different context.Creates a new Task and add it to the last of tasks that are ready to run pEntry - pointer to the Task Function pcName - Task Name String usStackDepth - Stack Size in bytes pvParameters - pointer to structure to be passed to the Task Function uxPriority - Task Priority upon successful creation the function should return 0 Otherwise, a negative value indicating the error code shall be returned
References portSTACK_TYPE, portBASE_TYPE, OSI_OK, OSI_OPERATION_FAILED.
Referenced by threadCreate.
void osi_TaskDelete(OsiTaskHandle *pTaskHandle)
This function Deletes a Task.
Deletes a Task and remove it from list of running task pTaskHandle - Task Handle
References vTaskDelete.
Referenced by threadExit.
unsigned long osi_TaskDisable(void)
This function used to disable the tasks.
- void - Key with the suspended tasks
References vTaskSuspendAll, OSI_OK.
void osi_TaskEnable(unsigned long key)
This function used to resume all the tasks.
This function used to enable all tasks. key - returned from suspend tasks - void
References xTaskResumeAll.
void VDeleteSimpleLinkSpawnTask(void)
This is the API to delete SL spawn task and delete the SL queue.
none void
References xSimpleLinkSpawnTaskHndl, vTaskDelete, xSimpleLinkSpawnQueue, vQueueDelete.
void vSimpleLinkSpawnTask(void *pvParameters)
This is the simplelink spawn task to call SL callback from a different context.
pvParameters - pointer to the task parameter void
References portBASE_TYPE, xQueueReceive, xSimpleLinkSpawnQueue, portMAX_DELAY, tSimpleLinkSpawnMsg::pEntry, tSimpleLinkSpawnMsg::pValue.
Referenced by VStartSimpleLinkSpawnTask.
OsiReturnVal_e VStartSimpleLinkSpawnTask(unsigned portBASE_TYPE uxPriority)
This is the API to create SL spawn task and create the SL queue.
uxPriority - task priority void
References xSimpleLinkSpawnQueue, slQUEUE_SIZE, OSI_OPERATION_FAILED, vSimpleLinkSpawnTask, portCHAR, portSTACK_TYPE, NULL, xSimpleLinkSpawnTaskHndl, OSI_OK.