ssock.c
MAXSENDLEN
Referenced by Ssock_send.
void Ssock_construct(Ssock_Struct *ssockP, int s)
References NULL.
Referenced by HTTPCli_connect, Ssock_create.
Ssock_Handle Ssock_create(int s)
References Ssock_construct.
void Ssock_delete(Ssock_Handle *ssock)
References Ssock_destruct, NULL.
void Ssock_destruct(Ssock_Struct *ssockP)
References NULL.
Referenced by HTTPCli_disconnect, Ssock_delete.
int Ssock_getSocket(Ssock_Handle ssock)
Referenced by startSecureMode, HTTPCli_disconnect.
ssize_t Ssock_recv(Ssock_Handle ssock, void *buf, size_t len, int flags)
Referenced by bufferedRecv, Ssock_recvall.
ssize_t Ssock_recvall(Ssock_Handle ssock, void *buf, size_t len, int flags)
References Ssock_recv.
ssize_t Ssock_send(Ssock_Handle ssock, const void *buf, size_t len, int flags)
References NULL, MAXSENDLEN.
Referenced by sprsend, HTTPCli_sendRequestBody.
int Ssock_startSecure(Ssock_Handle ssock, Ssock_SecureFxns *sec, void *ctx)
Referenced by startSecureMode.