syscall.c
int ff_cre_syncobj(BYTE vol, _SYNC_t *sobj)
References NULL, FALSE.
Referenced by f_mount.
int ff_del_syncobj(_SYNC_t sobj)
Referenced by f_mount.
void ff_rel_grant(_SYNC_t sobj)
Referenced by unlock_fs.
int ff_req_grant(_SYNC_t sobj)
References _FS_TIMEOUT.
Referenced by lock_fs.